### ISSUE TITLE
Is an operator a package? And how to manage dependencies?

### ISSUE THREAD

**Issue by pierreozoux** [operator-framework/operator-sdk#1008]
A package in the sense of RPM package. I think it is and if it is, then as part of the operator community we have to fulfill the following - [package manager](https://github.com/helm/community/blob/master/helm-v3/009-package_manager.md).

In this issue, I'm especially interested in solving the `dependency resolution` part.

Say that I want to deploy a Nextcloud instance. This depends on an SQL instance. My Nextcloud operator as to resolve this dependency.

What is the plan around dependency management? Maybe there is already one?

Thanks for your help!

**Comment by hasbro17** [comment]
@pierreozoux When considering operators as packages that need to be managed(installed, upgraded etc) you might be interested in looking at the [Operator Lifecycle Manger (OLM)](https://github.com/operator-framework/operator-lifecycle-manager), if you haven't already come across it.

The [design philosophy](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/philosophy.md) and [architecture](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/architecture.md) docs should provide a good overview of how OLM manages operators.

Specifically for [dependency resolution](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/dependency-resolution.md#dependency-resolution-and-upgrades) OLM allows an operator to specify the APIs that are provided by it as well as what APIs are required by(or depended on) by that operator.

With the operator specifying an API that it depends on via the [CSV](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/building-your-csv.md#what-is-a-cluster-service-version-csv), OLM will ensure that prerequisite is fulfilled by installing the operator that provides that API.

**Comment by pierreozoux** [comment]
Thanks for your feedback I'll close here, read and open there if necessary.
