### ISSUE TITLE
operator-sdk master build issue on my local mac high sierra

### ISSUE THREAD

**Issue by mandaltu123** [operator-framework/operator-sdk#1018]
I was trying to build operator-sdk as per guide, but ran into issue when I tried make install.

I got the following error:

github.com/operator-framework/operator-sdk/vendor/google.golang.org/grpc/resolver
compile: version "go1.11.4" does not match go tool version "go1.11.5"
make: *** [install] Error 2

Here are the details:

go version go1.11.5 darwin/amd64
GitVersion:"v1.13.1"
> kubectl version

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:10Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by shawn-hurley** [comment]
I think this is an issue with your golang installation. How did you install?

**Comment by mandaltu123** [comment]
Hi @shawn-hurley  thanks for your quick reply. 

I installed golang on my mac with go1.11.5.darwin-amd64.pkg last week.
Are you suggesting un install and install again ?
And does the following mean:
"compile: version "go1.11.4" does not match go tool version "go1.11.5"" --> instead of installing latest 11.5 downgrading to 11.4 ?

**Comment by shawn-hurley** [comment]
I think that you might have a mismatch between a version that is installed in your $PATH and you may have $GOROOT set to a different version.

**Comment by mandaltu123** [comment]
thanks @shawn-hurley for your reply.
I am new to golang.
here is what I did on my machine:
on ~/.bash_profile
export GOPATH=/Users/xxxx/gocode
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$GOPATH/bin
=============================

> echo $PATH-> part of it is as follows:
/usr/local/go/bin:/usr/local/go/bin:/Users/xxxx/gocode/bin
===========

**Comment by shawn-hurley** [comment]
you may need to delete the tools in `/Users/xxxx/gocode/bin` and reinstall them based on the new version of golang.

**Comment by mandaltu123** [comment]
Hi @shawn-hurley there was issue with my .zshrc entry. After commenting out GOROOT "make install" worked and I am able to see that 
/Users/xxx/gocode/bin/operator-sdk is installed. 
--> some issues with $PATH variable though, I am running it like this for now: 
/Users/xxx/gocode/bin/operator-sdk new app-operator.

Let me fix the path problem, or log out from my laptop once and retry that just operator-sdk new app-operator works or not.

Thanks for your help. have a great day.

**Comment by LiliC** [comment]
Closing this as it solved the problem, @mandaltu123 if you run into any other problems feel free to open a new issue.
