### ISSUE TITLE
Helm Operator RBAC finalizer issue

### ISSUE THREAD

**Issue by robszumski** [operator-framework/operator-sdk#1021]
## Bug Report

**What did you do?**
Created a Helm chart based Operator using PR#949. The Operator was built from https://github.com/helm/charts/tree/master/stable/airflow/ and deployed successfully.

**What did you expect to see?**
CR is processed and pods are started

**What did you see instead? Under which circumstances?**
Two issues:
First is that the Operator panics on this PDB error. See logs below.
Second, is that I applied a namespace'd Role Binding for `admin` to the Operator's Service Account, and the errors do not change. What object is this error about if a SA that has root in the NS can't mutate it?

```
2019-01-29T19:35:48.341Z    ERROR    kubebuilder.controller    Reconciler error    {"controller": "cockroachdb-controller", "request": "openshift-operators/example", "error": "release example-72qnnsakjngcmdcudpiltowu failed: poddisruptionbudgets.policy \"example-72qnnsakjngcmdcudpiltowu-cockroachdb-budget\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>"}
github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error
    /home/joe/go/src/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128
github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /home/joe/go/src/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
    /home/joe/go/src/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
    /home/joe/go/src/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil
    /home/joe/go/src/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.Until
    /home/joe/go/src/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
```

**Environment**
* operator-sdk version: custom build based on PR#949

* Kubernetes version information: `kubernetes v1.11.0+8868a98a7b`

* Kubernetes cluster kind: OpenShift

* Are you writing your operator in ansible, helm, or go? Helm

**Possible Solution**
Granting the `cluster-admin` (aka root on the cluster) to the Service Account does fix this issue. However, the OpenShift `admin` role, (aka root in the NS) does not fix the issue.

**Additional context**
This fails on two different Helm Operators in the same way, so I think something is trying to create or mutate an OwnerRef at the cluster-level.

**Comment by robszumski** [comment]
Yes, I with this guidance I was able to update my RBAC role accordingly. It was very unclear how PDB was related to not being able to mutate the chart object. Instead of this:

```
- apiGroups:
      - charts.helm.k8s.io
    resources:
      - '*'
    verbs:
      - 'airflows'
```

I needed to match all resources:

```
- apiGroups:
      - charts.helm.k8s.io
    resources:
      - '*'
    verbs:
      - '*'
```

**Comment by joelanford** [comment]
For kicks, I tried specifying the individual `airflows` resource and got a failure. Turns out I also needed to add `airflows/status`:

```yaml
- apiGroups:
  - charts.helm.k8s.io
  resources:
  - airflows
  - airflows/status
  verbs:
  - '*'
