### ISSUE TITLE
Feature Request: Support config file for all sdk commands

### ISSUE THREAD

**Issue by AlexNPavel** [operator-framework/operator-sdk#1024]
## Feature Request

PR #950 implemented config file support for the sdk's scorecard subcommand. It would be useful to have support for this in multiple subcommands for the sdk. Due to the way cobra and viper can integrate, it shouldn't be too difficult to implement in other subcommands, but it may be a bit time consuming as it would require quite a bit of refactoring.

**Comment by camilamacedo86** [comment]
HI @joelanford, @jmccormick2001 and @estroz

Is it something that can be closed? It shows still valid to be considered with the changes that will be made on it. WDYT?

**Comment by joelanford** [comment]
Yeah, I think this can be closed (for now at least). We can revisit after the KB integration and create a new issue if necessary.
