### ISSUE TITLE
Add eventhandler example in user-guide

### ISSUE THREAD

**Issue by robinbraemer** [operator-framework/operator-sdk#1028]
Can someone give me a quick example of what is meant here?
https://github.com/operator-framework/operator-sdk/blob/c5cc09b184ac4782c68b071a9da20d9ea2a9052d/doc/user-guide.md#L150
https://github.com/operator-framework/operator-sdk/blob/c5cc09b184ac4782c68b071a9da20d9ea2a9052d/doc/user-guide.md#L152

I think event handling is a very important topic that should be understood and directly shown to every new operator developer when reading the user guide.

Thanks! :D

**Comment by LiliC** [comment]
cc @hasbro17 think you added that TODO comment.

**Comment by hasbro17** [comment]
Yes, the event handler docs are on my ToDo list. Essentially we need a doc that explains the [EventHandler](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg#hdr-EventHandler) a bit more, and how to use the [EnqueueRequestsFromMapFunc](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/handler#EnqueueRequestsFromMapFunc) to enqueue requests for arbitrary objects.
I don't intend to repeat the controller-runtime godocs but I think an overview pointing to the godocs, and an example would benefit first time operator developers.

I think we already have a [doc on predicates](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/event-filtering.md) so we just need to point to that.

And the [Channel Source type](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/source#Channel) is useful for processing events from outside the cluster(not by watching k8s objects). Haven't thought of a good example use case to demonstrate that yet though.

**Comment by LiliC** [comment]
/remove-lifecycle stale

unless @hasbro17 this is not relevant anymore?

**Comment by hasbro17** [comment]
@LiliC It's still relevant. It just hasn't been highly requested and I kind of forgot to get around to this.
So yes we should keep this open until we add in some docs and an example for the [EnqueueRequestsFromMapFunc](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/handler#EnqueueRequestsFromMapFunc).

Hard to think of a useful example for it though. I haven't seen any actual usage of this so far.

**Comment by gaurav-dalvi** [comment]
I will take this item. I have implemented `EnqueueRequestsFromMapFunc` for my use case recently. Assigning this item to me.

**Comment by joelanford** [comment]
@gaurav-dalvi Thanks so much! It doesn't look like I can assign it to you, so I'll assign it to myself as a proxy so I can help keep track of it. Let me know if you need any help or want me to review anything for you!

**Comment by gaurav-dalvi** [comment]
PR : https://github.com/operator-framework/operator-sdk/pull/1744
