### ISSUE TITLE
Unable to install package deepcopy-gen

### ISSUE THREAD

**Issue by bvkin** [operator-framework/operator-sdk#1029]
## Type of question

General Context and Help

## Question

Hello,
I seem to be unable to install the deepcopy-gen package in order to use the operator-sdk. Iv'e been following along with this guide: https://learn.openshift.com/operatorframework/go-operator-podset/

Also, I have tried to follow the instructions in issues #334 but when I run the install command I get the following error.

```
$ go install github.com/example-inc/memcached-operator/vendor/k8s.io/code-generator/cmd/deepcopy-gen
can't load package: package github.com/example-inc/memcached-operator/vendor/k8s.io/code-generator/cmd/deepcopy-gen: cannot find package "github.com/example-inc/memcached-operator/vendor/k8s.io/code-generator/cmd/deepcopy-gen" in any of:
	/usr/lib/golang/src/github.com/example-inc/memcached-operator/vendor/k8s.io/code-generator/cmd/deepcopy-gen (from $GOROOT)
	/home/bkincaid/go/src/github.com/example-inc/memcached-operator/vendor/k8s.io/code-generator/cmd/deepcopy-gen (from $GOPATH)

``` 

I've tried running this within the terminal session provided by the learn.openshift course as well as locally and gotten the same results. Has this package been moved to somewhere else?

Thanks!

**Environment**
* operator-sdk version:
operator-sdk version v0.2.0+git

**Comment by AlexNPavel** [comment]
I ran through the terminal session in the learn.openshift.com example you linked and that course works correctly. You shouldn't need to install the code generator manually, as the generate k8s command should do that for you.

Can you run `operator-sdk generate k8s` in your project and post the output here?

**Comment by bvkin** [comment]
It seems to be working now. I think that whoever is maintaining that package may have been having some issues.
Thanks!
