### ISSUE TITLE
Helm Operator update loop

### ISSUE THREAD

**Issue by zipper97412** [operator-framework/operator-sdk#1069]
## Bug Report

**What did you do?**
`operator-sdk up local --namespace myproject`
- I am in the folder of my helm based operator
- I have uploaded the coresponding CRD on my okd(openshift) cluster
- I have an instance of my CRD

**What did you expect to see?**
The operator successfully apply my helm package then wait for changes in my CRD instances

**What did you see instead? Under which circumstances?**
The operator successfully apply my helm package then change the `resourceVersion` of my CRD instance then wake up again to re-apply my helm package again and again in a loop many times per seconds. My application pod is restarted every seconds

**Environment**
* operator-sdk version: 
operator-sdk version v0.4.0

* Kubernetes version information:
`> oc version`
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://192.168.99.100:8443
kubernetes v1.11.0+d4cacc0

* Kubernetes cluster kind: 
okd minishift

* Are you writing your operator in ansible, helm, or go?
helm
**Possible Solution**
?

**Additional context**
nginx example on the doc seems to work 
I am using some openshift only ressources : 
- DeploymentConfig
- ImageStream
- BuildConfig

but helm shouldn't see the difference

**Comment by joelanford** [comment]
@zipper97412 By chance, does your helm chart release include any randomly generated fields?

**Comment by joelanford** [comment]
@zipper97412 Were you able to resolve your issue? If not, please feel free to re-open.
