### ISSUE TITLE
document need for cluster-admin to run tests

### ISSUE THREAD

**Issue by mhrivnak** [operator-framework/operator-sdk#1082]
## Feature Request

Users of OpenShift, and presumably other clusters as well, do not generally run as cluster-admin the way some developers do when using minikube or similar. When developing an operator on openshift, it would be helpful to have some documentation that provides guidance on the best or most appropriate way to ensure that the tests run with sufficient permission to create and remove the CRD.

**Comment by dhellmann** [comment]
I ended up with 1 extra step to add the cluster-admin ClusterRole to my user. It's possible a role with fewer privileges would work, too.

See https://github.com/metalkube/baremetal-operator#running-end-to-end-tests and https://github.com/metalkube/baremetal-operator/blob/master/test/e2e/role_binding.yaml
