### ISSUE TITLE
test local --up-local leaves a running process

### ISSUE THREAD

**Issue by bofm** [operator-framework/operator-sdk#1088]
`operator-sdk test local --up-local` command leaves a running process after completion.

**What did you do?**

```
operator-sdk test local --up-local --namespace operator-test ./test/e2e
```

**What did you expect to see?**
`operator-sdk test local --up-local` should kill the background processes it has created.

**What did you see instead? Under which circumstances?**
```
ps ax|grep 'go-build.*exe/main'
41208 s002  S      0:00.80 /var/folders/9k/97gyz52j17g_zjpy5kd9j09c0000gn/T/go-build774160954/b001/exe/main
```

**Environment**

* operator-sdk version: operator-sdk version v0.4.0+git 203301be4d10eae16b02b6ae787352dd22143ca1

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: minikube

* Are you writing your operator in ansible, helm, or go?
Go

**Comment by AlexNPavel** [comment]
This was an issue caused by us using `go run` to run the operators locally. We fixed this in `operator-sdk up local`, but didn't update the test subcommand as well: https://github.com/operator-framework/operator-sdk/pull/1010/files. I'll update the the `test local --up-local` command with those changes as well.
