### ISSUE TITLE
Ansible operator using  oc auth can-i failed

### ISSUE THREAD

**Issue by matihost** [operator-framework/operator-sdk#1092]
When Operator docker was injected `oc` command (OpenShift kubectl fork) (in order to mitigate k8s  object tracking caching - aka  https://github.com/operator-framework/operator-sdk/issues/1051)

When I ran it, I encountered a problem with 
`TASK [catproject : Check whether logged user can create projectrequest resources] ***
task path: /opt/ansible/roles/catproject/tasks/main.yml:10
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "oc auth can-i create projectrequest -q", "delta": "0:00:00.505599", "end": "2019-02-12 13:31:05.706886", "msg": "non-zero return code", "rc": 1, "start": "2019-02-12 13:31:05.201287", "stderr": "The  \"\" is invalid: metadata: Invalid value: v1.ObjectMeta{Name:\"\", GenerateName:\"\", Namespace:\"\", SelfLink:\"\", UID:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference{v1.OwnerReference{APIVersion:\"some.cat.com/v1alpha1\", Kind:\"CatProject\", Name:\"alamakota\", UID:\"848ca4c8-2eb8-11e9-9a3b-06989c5df67c\", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}}, Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:\"\"}: must be empty", "stderr_lines": ["The  \"\" is invalid: metadata: Invalid value: v1.ObjectMeta{Name:\"\", GenerateName:\"\", Namespace:\"\", SelfLink:\"\", UID:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference{v1.OwnerReference{APIVersion:\"some.cat.com/v1alpha1\", Kind:\"CatProject\", Name:\"alamakota\", UID:\"848ca4c8-2eb8-11e9-9a3b-06989c5df67c\", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}}, Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:\"\"}: must be empty"], "stdout": "", "stdout_lines": []}
`

The oc apply etc. commands works..

Running `oc auth can-i create projectrequest` from the operator pod (oc rsh operatorpodid) just works...
I dunno what is the problem and why it complains about CR content (CatProject with resource id: alamakota) ... Looks like butterfly effect issue...

**Comment by shawn-hurley** [comment]
This is closed by #1463
