### ISSUE TITLE
Implementing custom status and delete hook for managing external resources in v0.4.1

### ISSUE THREAD

**Issue by the-scott-hand** [operator-framework/operator-sdk#1093]
## Type of question
Feature Implementation/Existence/Best Practice

## Background
I am currently working on creating an operator that manages a non-kubernetes resource. Create/Update/Delete calls require the operator to submit a call to a non-kubernetes API. I also want to have a "status" field that periodically hits this external API for status. 

**operator-sdk version:**
 v0.4.1+git
Using Reconcile loop and controller.go rather than handler.go

## Question 1: Pre-Delete Hook
My first question is about pre-delete hooks. Essentially, I want to make sure a certain block of code gets run before the cr gets deleted. Previously(as others have mentioned in other issues) you could do an "if event.Deleted" in the handler.go (I was doing this in v0.0.6 or so?). I am not sure the best way to go about this in v0.4 with the reconciler loop. Currently have two thoughts(below) for implementing this, are either of these viable or is there a third better option?

1. Hijack the [predicate filtering logic](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/event-filtering.md)
Not sure if this is meant to be used like this. My understanding is that a delete event would need to get blessed by whatever code gets run in the predicate. Is it bad practice(or even viable) to use the predicate to run an external API call, and if that fails then "filter out" the delete event? 

2. [Finalizers](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#advanced-topics)
I've seen this referenced a few times when looking at related issues, but not sure how to actually implement them from an operator-sdk perspective. Are there any examples/documentation I can checkout for implementing a "pre-delete" hook?

## Question 2: Status
My second question is about a "status" field. I ultimately want to implement something similar to the STATUS field you see when you do a "kubectl get pods". In my understanding the "subresource: status: {}"  field is more for if your cr spins off more k8s resources, rather than getting a general "status" from some external API, but I could be totally wrong about that. I have one main idea(below) for implementing this, is this viable or is there a better option?

1. Make a spec key value pair called "status"
The idea is that I would use some spec.Status as a field that I update on some interval using the results of an API call. With the reconcile loop, it seems like you can "requeue" your cr(every 30 seconds for example) using something like this:
``` return reconcile.Result{RequeueAfter: time.Second*30}, nil ```
In theory I could use this to keep "updating" spec.Status of my cr every 30 seconds, and configure a additional printer column in the crd to display this. Is this my best option, or is there an easier/more conventional way to do this?

**Comment by shawn-hurley** [comment]
To answer your first question: 

> 2\. [Finalizers](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#advanced-topics)
    I've seen this referenced a few times when looking at related issues, but not sure how to actually implement them from an operator-sdk perspective. Are there any examples/documentation I can checkout for implementing a "pre-delete" hook?

This is the correct option. You have to remember that your operator could miss events and if you want to make sure to clean something up, then a finalizer stops the GC from cleaning up the object. Here is a good doc on this: https://book.kubebuilder.io/beyond_basics/using_finalizers.html


To answer your second question:

This is not documented anywhere in our stuff. Basically what you need to do is use the status object and create [conditions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties) here. Then you can implement in your CRD a custom printer columns if you're on a new enough version of kubernetes. Here is a link to this: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns

Let me know if this makes sense and answers your questions.

**Comment by the-scott-hand** [comment]
**Re: Question 1:** I believe this question is answered. The [finalizer link you mentioned](https://book.kubebuilder.io/beyond_basics/using_finalizers.html) was particularly useful for my question about a pre-delete hook. Correct me if im wrong, but it seems that the key to detecting the delete is using `instance.ObjectMeta.DeletionTimestamp.IsZero()`(when true, instance is not being deleted, when false, is being deleted) in combination with a finalizer(which I guess makes sure you dont miss the delete?). This snippet was particularly useful, although i did need to modify `r.Update` to `r.client.Update` to work in my reconcile function. Once again the whole example (including implementation of helper functions containsString(),removeString(), and stub of deleteExternalDependency() )  is at [this link shawn mentioned](https://book.kubebuilder.io/beyond_basics/using_finalizers.html):
```
// name of your custom finalizer
    myFinalizerName := "storage.finalizers.example.com"

    if instance.ObjectMeta.DeletionTimestamp.IsZero() {
        // The object is not being deleted, so if it does not have our finalizer,
        // then lets add the finalizer and update the object.
        if !containsString(instance.ObjectMeta.Finalizers, myFinalizerName) {
            instance.ObjectMeta.Finalizers = append(instance.ObjectMeta.Finalizers, myFinalizerName)
            if err := r.Update(context.Background(), instance); err != nil {
                return reconcile.Result{}, err
            }
        }
    } else {
        // The object is being deleted
        if containsString(instance.ObjectMeta.Finalizers, myFinalizerName) {
            // our finalizer is present, so lets handle our external dependency
            if err := r.deleteExternalDependency(instance); err != nil {
                // if fail to delete the external dependency here, return with error
                // so that it can be retried
                return reconcile.Result{}, err
            }

            // remove our finalizer from the list and update it.
            instance.ObjectMeta.Finalizers = removeString(instance.ObjectMeta.Finalizers, myFinalizerName)
            if err := r.Update(context.Background(), instance); err != nil {
                return reconcile.Result{}, err
            }
        } 
```
**Re: Question 2:** These links were also useful, I had used the printer columns before but I hadn't seen 
"conditions" yet. Needed to google around for more examples to get a better feel for those. I am still trying to figure out the best way to use the reconcile loop to update my cr with some status/condition that tells me about an external(non-kubernetes) resource? As of now my general strategy is below. **Is my strategy of requeue-ing every `s` seconds to update status my best bet for updating my cr, or am I doing something hacky and/or following bad practice?**
```
// 
func Reconcile (){
// 1. Do some api call to get status of my external dependency
// 2. Modify some instance.Status.Condition with the status
// 3. Run r.client.Update(context.Background(), instance)
// 4. Requeue every s seconds(e.g. 30 in line below) to get status again
return reconcile.Result{RequeueAfter: time.Second*30}, nil
}
```
Thanks again for your help!

**Comment by shawn-hurley** [comment]
Assuming that you can't have some very odd webhook behavior to get updates from the external resource then this does make sense to me. 

I could see some other thing that will run every 30 seconds and attempt to get the status and then update the object but not doing the entire reconciliation run. You could then set up predicates to filter out status updates for success but if the 30-second http.GET failed for some reason then when you update that the resource is in a failed status, you could then reconcile the entire thing. This feel like a ton more work though. Let me know if this makes sense :)

**Comment by the-scott-hand** [comment]
Oh interesting, so I could query the status in a predicate and filter out the event if the status hasnt changed? Thats pretty cool. Thanks again shawn for your help, I think this can be closed.
