### ISSUE TITLE
Ansible Operator on an Infinite Loop

### ISSUE THREAD

**Issue by gbaufake** [operator-framework/operator-sdk#1101]
## Bug Report
**What did you do?**

I have created an ansible-operator (https://github.com/kiali/kiali-test-mesh/pull/41) which basically execute some playbooks.

**What did you expect to see?**
After the playbook is finished, I would expect to see the operator doing nothing else.

**What did you see instead? Under which circumstances?**
The operator goes to the first step (full logs -> https://paste.fedoraproject.org/paste/kfGudIArzgiWJEqws~aJmQ)

I see on the log the event finished 

```{"level":"info","ts":1550079880.6553488,"logger":"runner","msg":"Ansible-runner exited successfully","job":"835940449026680189","name":"kili-test-mesh-installation","namespace":"kiali-test-mesh-operator"}```

I hoped it stayed there, but  it spins back to the begin of the plabook: 

``` {"level":"info","ts":1550079943.069268,"logger":"logging_event_handler","msg":"[playbook task]","name":"kili-test-mesh-installation","namespace":"kiali-test-mesh-operator","gvk":"kiali-test-mesh.kiali.io/v1, Kind=Installation","event_type":"playbook_on_task_start","job":"524837426166675703","EventData.Name":"Gathering Facts"} ```

**Environment**
 operator-sdk version v0.4.0+git

  Insert operator-sdk release or Git SHA here. If you have paste the Gopkg.lock operator-sdk information here. 

* Kubernetes version information:

``` $ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://url:8443
openshift v3.11.43
kubernetes v1.11.0+d4cacc0
````
`

* Are you writing your operator in ansible, helm, or go? 
Ansible

**Possible Solution**

**Additional context**

**Comment by shawn-hurley** [comment]
Just a quick glance at your watches file and I notice that you have not set
your reconcile period to zero

**Comment by gbaufake** [comment]
Yes you are right. I didn't notice that closing this bug.
Sorry for the misunderstood.

**Comment by gbaufake** [comment]
@shawn-hurley  Added ` reconcilePeriod: 0` and I still got this issue of restarting the operator workflow.

Logs attached

[kiali-test-mesh-operator-5ddf9d5c5d-7mzrz-kiali-test-mesh-operator.log](https://github.com/operator-framework/operator-sdk/files/2906859/kiali-test-mesh-operator-5ddf9d5c5d-7mzrz-kiali-test-mesh-operator.log)

**Comment by shawn-hurley** [comment]
Yes, assuming that we are re-running reconciliation because as we starting watching the dependent resources, the queue got another event. I would expect that eventually, this would stop, but two runs are something to be expected from all operators because as you create the dependent resources, you will get reconciliation requests for the primary resource.

**Comment by shawn-hurley** [comment]
We can chat on the issue here if the above explanation was not enough, but I am not considering this an issue to be fixed based on the above.
