### ISSUE TITLE
operator-sdk generate openapi omits field that contains numbers

### ISSUE THREAD

**Issue by miguelsorianod** [operator-framework/operator-sdk#1120]
**What did you do?**
Execute the command `operator-sdk generate openapi` using operator-sdk master branch.

The CRD Go specification contains the following struct:

```
type SystemFileStorageSpec struct {
	// Union type. Only one of the fields can be set.
	PVC *SystemPVCSpec `json:"persistentVolumeClaim,omitempty"`
	S3  *SystemS3Spec  `json:"s3,omitempty"`
}
```

This struct is not the Spec of the CRD itself nor its own CRD (it is not registered in the schema) but a field in the CRD spec.

**What did you expect to see?**

The YAML file of the CRD should contain s3 as one of the validation fields. Instead it does not appear.

I've observed that if I change the json field name from   `json:"s3,omitempty"` to   `json:"sthree,omitempty"` it is included in the .yaml validation section.

operator-sdk version: master branch

**Comment by estroz** [comment]
@miguelsorianod if this is indeed a bug it is in upstream [kube-openapi](https://github.com/kubernetes/kube-openapi/tree/master/cmd/openapi-gen), as we directly call that binary in `generate openapi`.

**Comment by estroz** [comment]
Check out this issue for more info: https://github.com/kubernetes-sigs/controller-tools/issues/139
