### ISSUE TITLE
pulling dependencies from master

### ISSUE THREAD

**Issue by theishshah** [operator-framework/operator-sdk#1134]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

TravisCI runs are fetching master versions of Ansible Molecule (and possibly other dependencies) and as a result a breaking change on a dependency can break the sdk. Note that this specific instance of the issue has been fixed in #1131 

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

Travis passing when no breaking changes are made in the sdk.

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

Travis failed on master with no changes in our repo.

**Environment**
* operator-sdk version: 0.5.0

**Possible Solution**

I suggest freezing our dependencies on the latest releases and then updating those versions whenever we lock the new version of the sdk.

**Comment by estroz** [comment]
@shawn-hurley @fabianvf thoughts?

**Comment by shawn-hurley** [comment]
yep, I totally agree we should, and will, but we actually need a change in molecule that is unreleased (which is going to be released soon). This means that for now, we need to do it this way, we are tracking this and will be making the necessary changes once molecule is released.
