### ISSUE TITLE
Handling delete Events for Ansible operator 

### ISSUE THREAD

**Issue by Dimss** [operator-framework/operator-sdk#1179]
## Feature Request

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to implement custom deletion logic on CR delete. 
And I don't see any way to do it with Ansible operator. 
For example, the `watches.yaml` may hold an extra field which is indicates on which event type the playbook or role should be executed.
```
- version: v1alpha1
  group: mygroup.com
  kind: MyTestApi
  playbook: /opt/ansible/playbook1_create.yml
  event: create

- version: v1alpha1
  group: mygroup.com
  kind: MyTestApi
  playbook: /opt/ansible/playbook1_delete.yml
  event: delete
``` 
Such functionality exists in Golang based operator [447](https://github.com/operator-framework/operator-sdk/issues/447) but I didn't found any references to this functionality for Ansible based operators

**Comment by shawn-hurley** [comment]
I think this should cover it. Please re-open if this is not sufficient and you would like to add additional features 😄.

https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/finalizers.md

**Comment by Dimss** [comment]
Awesome, thanks!
