### ISSUE TITLE
Do not expose commands/operator-sdk/cmd

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-sdk#1184]
**Problem**
Users are not going to need `commands/operator-sdk/cmd` as a library, so it should not be exported.

**Proposed fix**
Move `commands/operator-sdk/cmd` -> `commands/operator-sdk/internal/cmd`

**Comment by jmrodri** [comment]
Do we have a huge problem of people using code in this project? I've never really seen things in `internal` until this project.
