### ISSUE TITLE
Maturity model accuracy

### ISSUE THREAD

**Issue by rafik8** [operator-framework/operator-sdk#1200]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
General context question

## Question

**What did you do?**
Explore the operator maturity model: https://github.com/operator-framework/operator-sdk/blob/master/doc/images/operator-maturity-model.png
**What did you expect to see?**
I expected to see helm go into `Phase II` maturity as it support patch and minor version upgrade.
![image](https://user-images.githubusercontent.com/13514337/54216962-9a16e480-44e2-11e9-808c-f16cba8e87c7.png)

**What did you see instead? Under which circumstances?**
I see from the maturity model that helm is limited to `Phase I `only: 
![image](https://user-images.githubusercontent.com/13514337/54217050-cd597380-44e2-11e9-95b3-e5c3d0762b31.png)

**Environment**
* operator-sdk version:
N/A
  insert release or Git SHA here
N/A
* Kubernetes version information:

  insert output of `kubectl version` here
N/A
* Kubernetes cluster kind: 
N/A
**Additional context**
Add any other context about the question here.
`helm version: v2.11.0`

**Comment by joelanford** [comment]
/cc @dmesser @robszumski 

Thoughts?

**Comment by joelanford** [comment]
For what it's worth, I think I agree, but it depends on what we mean by "Seamless Upgrades."

If it means "A user can update the version of an image reference in their CR, and the operator will roll that new version out," then I agree that the Helm operator supports that (if the Helm chart supports it).

@rafik8 do you have a specific example in mind that supports bumping the Helm operator maturity level?

**Comment by dmesser** [comment]
I think it comes down to what level of complexity can handled with an upgrade. If it is really just a changing an image tag then this could be handled with a `Deployment` as well.
What makes an Operator leverage built-in, application-specific logic are upgrades where orchestration needs to occur. This could be either in the form of pre- and post-upgrade activities on a single application instance or throughout an application cluster where individual members have an identity and awareness of each other.

**Comment by rafik8** [comment]
@joelanford, I totally agree that it depends on the definition of “Seamless Upgrades”. The current definition of it (as of the maturity model) is : “Patch and minor version upgrades supported” and Helm support that.  As a practical example, I was been able to incrementally upgrade from Istio 1.0.1 to 1.0.6 using Helm.
If we add major version upgrade to the definition, Helm will not fit into that as additional work may be needed.
So, I think we could keep the current definition with helm is bumped to Phase 2.
Another option is to add an extra step Phase 3, so we will have:
`Phase 2`:  seamless **minor** upgrades (Patch and minor version upgrades supported) 
`Phase 3`:  seamless **major** upgrades (Major version upgrades supported) 
to get something like this: 
![image](https://user-images.githubusercontent.com/13514337/54240162-93599300-451d-11e9-8fac-c401b42a67f8.png)

**Comment by dmesser** [comment]
@rafik8  Thanks for testing that with helm. I thin we need to be clearer in our verbage for Phase II and call out the application-specific orchestration happening there. Because this differentiates an Operator from simple rip-and-replace updates and may occur regardloess of major and minor upgrades.
The EtcdOperator for instance will still do a rolling update, even in case of minor version jumps.

**Comment by joelanford** [comment]
@dmesser Just as another data point, Helm does support [chart hooks](https://github.com/helm/helm/blob/master/docs/charts_hooks.md), which can do some rudimentary application-specific orchestration based on release lifecycle events. They're not widely used though (only 21 of the 266 charts in the `stable` repo use non-test hooks).

**Comment by joelanford** [comment]
@dmesser Just wanted to follow up to see if you're planning on submitting a PR to clarify the Phase II definition and whether you think Helm's support for chart hooks means the Helm operator should be included as a Phase II operator?

**Comment by dmesser** [comment]
I think we would not convolute our model with this nuance. Even minor version changes might need some additional handholding - are we able to to leverage chart hooks with helm-based Operators? If so, I'd vote to extend the helm capability to Phase II.

**Comment by joelanford** [comment]
> are we able to to leverage chart hooks with helm-based Operators?

Yes. See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/operator-framework/hVZeiuTwq2Q

**Comment by joelanford** [comment]
I believe this was fixed by #1320
