### ISSUE TITLE
generate api fails with no explation

### ISSUE THREAD

**Issue by raffaelespazzoli** [operator-framework/operator-sdk#1203]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).
I run the following command:
```
operator-sdk generate openapi 
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [raffa:[v1alpha1], ] 
Error: failed to perform openapi code-generation: exit status 1
Usage:
  operator-sdk generate openapi [flags]

Flags:
      --header-file string   Path to file containing headers for generated files.
  -h, --help                 help for openapi
```

**What did you expect to see?**
not sure it never worked correctly. Although I would expect the zz_generated_openapi.go file to be updated and also the CRD definition to be updated.

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).
see the error.

**Environment**
* operator-sdk version:
```
operator-sdk --version
operator-sdk version v0.5.0+git
```

note that this version is not actually accurate I have compiled operator-sdk from the master branch.
this is the first entry of my git log:
```
commit 35ad467e945897a56afe99a558869ac0fccc1ff5 (HEAD -> master, origin/master, origin/HEAD)
Author: Timo Lotterbach <timo.lotterbach@googlemail.com>
Date:   Sat Mar 9 20:37:13 2019 +0100

    Fix a minor typo (#1187)
    
    fixed a typo.
```

**Comment by hasbro17** [comment]
@raffaelespazzoli You can get the verbose output via `GOFLAGS="-v" operator-sdk generate openapi` to show the errors for now.

I've mentioned this in #1181 that we need to update the default verbosity to show all errors on failure. I'm going to close this issue and follow up in #1181
