### ISSUE TITLE
subresource Object is deleted but still available 

### ISSUE THREAD

**Issue by petro404** [operator-framework/operator-sdk#1204]
## Type of question

How to implement a specific feature
## Question

**What did you do?**

I created a watch for sub resource(configmap) that is not created as part of the reconcile flow.
Once this resource is deleted  reconcile flow is being called so i am trying to check if the configmap
is deleted but somehow the client get method return that the DeletionTimestamp is zero.
my concern that it took the object from the cache , so the configmap was deleted by the client still working against the cache
is there anyway to refresh cache or to trigger the client to retrieve the latest update object 

```
err = c.Watch(&source.Kind{Type: &corev1.ConfigMap{}}, &handler.EnqueueRequestsFromMapFunc{
		ToRequests: handler.ToRequestsFunc(func(configMapObject handler.MapObject) []reconcile.Request {
		//do some logic
		}),
	},
```
	

//Controller Logic : Expect to enter the block of finalize but i got empty map object with deletion time //zero which means object return empty and there is no way to delete that its deleted

```
  foundConfigMap := &corev1.ConfigMap{}
	if err := client.Get(context.TODO(), types.NamespacedName{Name: instance.Spec.ConfigMapRef, Namespace: instance.Namespace}, foundConfigMap); errors.IsNotFound(err) {
		
		if !foundConfigMap.ObjectMeta.DeletionTimestamp.IsZero() {
			//do finalize
		}else
		{
		  //skip finalize
		}
		
	}

```

**What did you expect to see?**
 DeletionTimestamp is not zero.
 Block finalize is called

**What did you see instead? Under which circumstances?**
  skip finalize block was called

**Environment**
* operator-sdk version: version v0.4.0

  insert release or Git SHA here

* Kubernetes version information:

  insert output of `kubectl version` here
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by LiliC** [comment]
@petro404 Sorry no one got back to you on this, are you still experiencing the same problem?
