### ISSUE TITLE
Auto generated CRD to golang struct

### ISSUE THREAD

**Issue by petro404** [operator-framework/operator-sdk#1208]
## Feature Request

Auto generated CRD to golang will be very useful while integration between 2 operators ,so in case we have one operator written in java and another written in go. 
we can take the java crd input and auto generated golang struct so the operator SDK will generate the appropriate golang struct.
This feature is very useful so in case the java operator crd is changing its auto generated in the operator sdk     

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

**Comment by LiliC** [comment]
> Auto generated CRD to golang

If I understand correctly you want a custom resource struct to be generated for you based on java equivalent input? Not sure we currently have plans to add support for java operators, but can you elaborate a bit on that, what would the end result look like and what would the input be.

**Comment by petro404** [comment]
basically i would like to perform integration between operators ,main operator is written in go and it expect to create CRD and run it for another operator that is written in java.
so instead of creation the CRD struct manually as part of my project i would like to have the option to generate this struct in golang automatically during build/generation so in case any change in the crd the struct will be updated during build time
