### ISSUE TITLE
Could GPLv3 code be removed / relicensed under ASL 2.0? 

### ISSUE THREAD

**Issue by nickboldt** [operator-framework/operator-sdk#1213]
## Bug Report

You've got a file in the repo which has a GPLv3 license on it, but everything else in here is Apache 2.0.

**What did you do?**

I tried to submit this code to the Eclipse Foundation via their CQ/ipzilla process, and this one file was rejected because GPL is scary.

**What did you expect to see?**

Since the LICENSE file in this repo is Apache 2.0, I expected that everything in the repo would bear the same license terms.

https://github.com/operator-framework/operator-sdk/blob/master/LICENSE

**What did you see instead? Under which circumstances?**

This snippet shows the GPLv3 reference:

https://github.com/operator-framework/operator-sdk/blob/v0.5.0/test/ansible-inventory/plugins/filter/test.py#L5-L8

**Environment**
* operator-sdk version: 0.5.0

**Possible Solution**

Could the license in the above file be removed? Dual-licensed as Apache 2.0? 

**Additional context**

See also https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19238

The reason we need to go through this is so that Che can use this code in its next release from the Eclipse Foundation.

**Comment by hasbro17** [comment]
I don't know too much about GPL but if it's not okay for us to remove the license header then it's probably not okay for us to add it in the first place to an Apache 2.0 licensed project.

From the [note on Apache 2.0 and GPL v3 compatibility](https://apache.org/licenses/GPL-compatibility.html):
> Apache 2 software can therefore be included in GPLv3 projects, because the GPLv3 license accepts our software into GPLv3 works. However, GPLv3 software cannot be included in Apache projects

@fabianvf Is it possible to do without copying that test file as is?

/cc @robszumski @dmesser Can you please chime in on if we should be steering clear of GPLv3 in the project.

**Comment by dmesser** [comment]
@hasbro17 don't think we avoid or steer clear of GPLv3. As a project we should keep it to one license though.

**Comment by fabianvf** [comment]
This file is mislicensed, slipped through code review. I'm the author and will update the license properly. My apologies for the oversight.

**Comment by nickboldt** [comment]
Great, thanks!
