### ISSUE TITLE
add support for finalizers

### ISSUE THREAD

**Issue by raffaelespazzoli** [operator-framework/operator-sdk#1216]
Sorry the template for a feature request got lost when I changed the type from bug...
I'd like to request support for finalizers.
Some CRD type need to do complex cleanup via a finalizers.
The operator sdk could provide support for it with the following:
1. optional flag in the `operator-sdk add controller` to specify that code to support finalizer for that type should be generated.
2. add logic to the reconciliation cycle to detect if a CR is being deleted. If it's the case hand control to a dedicated function
3. generate stub for the dedicated finalizer function
4. if the function returns successfully, handle the removing of the finalizer entry from the array of finalizer of the to-be-deleted CR.

**Comment by joelanford** [comment]
@raffaelespazzoli There is related discussion in #460 and there is a proposal PR open in #489. In the interest of keeping the discussion in one place, would you mind contributing your ideas there?

You may notice there hasn't been much discussion lately, but we are definitely interested in adding better support for finalizers (and we'd happily accept contributions to the proposal and eventual implementation :slightly_smiling_face:)
