### ISSUE TITLE
Support for defaulting of CR fields via mutating admission webhooks

### ISSUE THREAD

**Issue by raffaelespazzoli** [operator-framework/operator-sdk#1218]
## Feature Request
Some CRs need a way to set some fields to default values.
Please add a facility to the operator-sdk to manage this situation. From a developer perspective a stub field defaulting method should be generated and the developer needs to fill it up. Requesting the generation the generation of this method should be optional for the `operator-sdk generate controller` command 

**Is your feature request related to a problem? Please describe.**
As I said some CRs require defaulting of fields, as of now every developer of an operator has to come up with its own solution. 

**Describe the solution you'd like**
I believe there are multiple ways to implement this, but perhaps the most kubernetes-pure would be via a MutatingAdmissionController. The generated operator could provide a http endpoint to listen for these MutatingAdmissionController webhook calls. Regardless the user experience should be the one defined above.

**Comment by hasbro17** [comment]
As discussed in https://github.com/operator-framework/operator-sdk/issues/1217#issuecomment-476407298 we'll be using the upstream controller-runtime APIs for mutating admission webhooks.
Example:
https://github.com/kubernetes-sigs/controller-runtime/blob/5e3a6da770e2f16f8ce9b0905eaa74974fe7a4c0/examples/builtins/mutatingwebhook.go

We just need to add the scaffolding,docs and examples.
