### ISSUE TITLE
Wait for the Kubernetes API to become available fails on an IPv6 enabled host

### ISSUE THREAD

**Issue by themr0c** [operator-framework/operator-sdk#1221]
## Bug Report

On an IPv6 enabled host, kind will start listening on  `:::10443` instead of `localhost:10443`

````
docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                          NAMES
8ffe853af49c        bsycorp/kind:latest-1.12   "dockerd-entrypoint.…"   7 minutes ago       Up 6 minutes        2375/tcp, 10080/tcp, 0.0.0.0:10443->8443/tcp   kind-test-local
````

````
netstat  -pan | grep 10443
tcp6       0      0 :::10443                :::*                    LISTEN      -        
````

As a consequence this task will fail:

````
    - name: Wait for the Kubernetes API to become available (this could take a minute)
      uri:
        url: "https://localhost:8443/apis"
[...]
````

Possible solution: During the creation of the kind container, we should force it to listen on IPv4 interface.

**What did you do?**

1. Foilow https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md

````
operator-sdk new memcached-operator --api-version=cache.example.com/v1alpha1 --kind=Memcached --type=ansible
cd memcached-operator/
molecule test
````

**What did you expect to see?**

molecule test success

**What did you see instead? Under which circumstances?**

````
fatal: [kind-default]: FAILED! => {"attempts": 60, "changed": false, "content": "", "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 99] Address not available>", "redirected": false, "status": -1, "url": "https://localhost:8443/apis"}
````

**Environment**

* operator-sdk version:

master branch

* Kubernetes version information:

 kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

 bsycorp/kind:latest-1.12

**Possible Solution**

Force kind to listen on IPv4 interface.

**Comment by joelanford** [comment]
@themr0c Sorry this seems to have fallen through the cracks. Do you know if this is still an issue?

/cc @shawn-hurley

**Comment by shawn-hurley** [comment]
I don't that we have had the bandwidth to look into this.

**Comment by themr0c** [comment]
I haven't looked at this since then, and my focus has changed. If nobody else complains, the issue is probably not important and can go in the attic.

**Comment by geerlingguy** [comment]
Using a different mechanism entirely—`kubectl cluster-info` instead of a direct URI request to the API endpoint—may solve this problem and #1748.
