### ISSUE TITLE
User docs for gen-csv cmd

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/operator-sdk#1227]
The CSV generation command `operator-sdk gen-csv` has certain assumptions and a specific workflow in how it updates only certain fields of the CSV manifest and uses certain manifests as the source of truth for updates.

Most of this behavior is what was discussed in the original [design doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/design/milestone-0.2.0/csv-generation.md) for CSV generation but we could do with a more trimmed down version of that for users to better understand the workflow of creating/updating CSV manifests.
Also that doc is outdated on recent changes to how the command handles multiple CSV versions.

**Comment by robszumski** [comment]
Fixed in #1242
