### ISSUE TITLE
leader.Become() using bad error checks

### ISSUE THREAD

**Issue by bah2830** [operator-framework/operator-sdk#1229]
## Bug Report

**What did you do?**
When using leader.Become with `operator-sdk up local` the namespace not found error is not checked correctly resulting in an error

**What did you expect to see?**
Log line `log.Info("Skipping leader election; not running in a cluster.")` get hit

**What did you see instead? Under which circumstances?**
Before Jan 11 2019: No error as it's ignored
After Jan 11 2019: (https://github.com/operator-framework/operator-sdk/pull/894) error `namespace not found for current environment`

**Environment**
* operator-sdk version: all
* Kubernetes version information: 1.13+
* Kubernetes cluster kind: no cluster (local)
* Are you writing your operator in ansible, helm, or go? go

**Possible Solution**
https://github.com/operator-framework/operator-sdk/blob/master/pkg/leader/leader.go#L50 is checking that the errors equal but they are pointers and will never equal unless it's the same object. This should be checking that the error strings match or even better check a custom error that implements the error interface.

**Comment by joelanford** [comment]
@bah2830 What version of operator-sdk are you using? With `v0.5.0` and `v0.6.0`, I'm seeing the "Skipping leader election" line in my log output when I run `operator-sdk up local` against a new go operator project.

**Comment by joelanford** [comment]
@bah2830 Just following up to see if you are still experiencing this issue? If so, please feel free to re-open.
