### ISSUE TITLE
Cannot disable leader election

### ISSUE THREAD

**Issue by snarlysodboxer** [operator-framework/operator-sdk#1231]
## Bug Report

**What did you do?**
I generated a new operator, then disabled leader election in `cmd/manager/main.go` with
```golang
    mgr, err := manager.New(cfg, manager.Options{
        Namespace:          namespace,
        MetricsBindAddress: fmt.Sprintf("%s:%d", metricsHost, metricsPort),
        LeaderElection:     false,
    })
```
then built the binary and started two copies of the operator in a k8s cluster, and it still performs leader election.

**What did you expect to see?**
No leader election in the logs.

**What did you see instead? Under which circumstances?**
One copy of the operator becomes the leader, and the other waits as the non-leader.

**Environment**
operator-sdk version v0.6.0+git

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.6", GitCommit:"144b681e3870074abfdaaf176e48b1b13360d7e5", GitTreeState:"clean", BuildDate:"2019-02-09T00:08:19Z", GoVersion:"go1.10.7b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
GKE

* Are you writing your operator in ansible, helm, or go?
go

**Additional context**
My operator use-case does not modify any objects in the cluster, only reads information to update it in memory for other use, so I do not want leader election.

**Comment by joelanford** [comment]
@snarlysodboxer Does your `main.go` file also have the following lines (around line 78)?

```go
// Become the leader before proceeding
err = leader.Become(ctx, "my-operator-lock")
if err != nil {
	log.Error(err, "")
	os.Exit(1)
}
```

If so, that is what you should remove. You can also remove the `LeaderElection: false` line in the` manager.Options` struct if you'd like, because it is disabled by default in the controller-runtime manager.

**Comment by snarlysodboxer** [comment]
@joelanford Thank you! That was it. It's working as expected now. Thanks again!
