### ISSUE TITLE
Ansible pod watch

### ISSUE THREAD

**Issue by kfox1111** [operator-framework/operator-sdk#1237]
## Question

**What did you do?**
I want to create a low level controller like a statefulset. It would watch a cr and spawn pods itself using ansible. If the pod changed/died/etc then ansible would trigger again and put it back.

**What did you expect to see?**
Some documentation explaining how to do this. So far as I can tell it can only watch it's cr.

Is this possible? If not, then this is a feature request.  :)

**Comment by hasbro17** [comment]
@kfox1111 I think this is already supported. The ansible-operator will inject ownerreferences into any objects that you create and then watch for that type so that it will re-trigger the reconcile loop when the created object is updated.

@shawn-hurley @fabianvf Not sure if we have this documented anywhere in the ansible-operator user-guide but this is the only place where we mention this behavior right?
https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/information-flow-ansible-operator.md#the-proxy

**Comment by kfox1111** [comment]
Ah, interesting. I'll give it a shot then. Thank you.

Would you like me to close the issue, or keep it open until any documentation related questions are covered?

**Comment by shawn-hurley** [comment]
@kfox1111 

If you want to watch pods and take actions on pods as well, you could do that by adding a section in the watches file to watch pods. This might not be what you're looking for but just to let you know. 

We need to spend more time than just adding a line to the documentation. I think the user guide is a quick start and we need to make it much easier to find the other documentation that goes into more detail about the other features that don't make sense in a quick start. Let's close this, and we will track this in a sprint task.

**Comment by vadimeisenbergibm** [comment]
@shawn-hurley Is it possible to watch specific pods, by some label? Otherwise, will the operator's role run for any change in any pod in the namespace?

**Comment by vadimeisenbergibm** [comment]
@shawn-hurley Another issue with watching pods, is that the operator will update their status:
`"logger":"reconciler","msg":"Unable to update the status to mark cr as running"`. However, if I am only interested in watching some resources and not interested in updating their status, what should I do?

**Comment by fabianvf** [comment]
@vadimeisenbergibm you can set the `manageStatus` option to false in the watches.yaml to skip status management. I also don't think there's a way to filter by label currently

**Comment by camilamacedo86** [comment]
HI @vadimeisenbergibm, 

In order to better help the users and we are able to help you more assertively, could I kindly ask for you to raise one subject/matter per issue? Could you please open a new one with further questions/issues bring up and/or if the above comment did not help you with?.

**Comment by vadimeisenbergibm** [comment]
Hi @camilamacedo86, the answer of @fabianvf helped me, thanks. I will open an issue regarding filtering watched resources.

**Comment by vadimeisenbergibm** [comment]
@camilamacedo86 @fabianvf I have added a feature request https://github.com/operator-framework/operator-sdk/issues/2378.
