### ISSUE TITLE
CRD Upgrade Lifecycle Documentation

### ISSUE THREAD

**Issue by andrewwebber** [operator-framework/operator-sdk#1240]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I would like to have documentation assurances about going through revisions of an initially deployed CRD

**Describe the solution you'd like**
The memcached/nginx examples would be even better if it walked through the following:
- deploy v1 of an operator and CRD
...
- deploy v2 of an operator and CRD

**Comment by hasbro17** [comment]
We don't have a defined workflow for upgrading CRD versions right now so we'll need to define that first.
Beyond having documentation and CLI support in the SDK to upgrade the generated CRDs and API definitions for a new version, we will most likely be leveraging the upstream controller-runtime conversion webhook APIs to support upgrading CRDs whenever that lands.
https://github.com/kubernetes-sigs/controller-runtime/issues/275

**Comment by andrewwebber** [comment]
Other examples include new available values in a helm chart when using the helm operator. 

Presumably in such a case a new CRD is required

**Comment by hasbro17** [comment]
Closing this in favor of #1541 which is essentially the same feature request but has more details on the issue.
I've also created a separate issue for showing an example of CRD version upgrade in the operator-sdk-samples repo https://github.com/operator-framework/operator-sdk-samples/issues/69
