### ISSUE TITLE
 We should need an event return

### ISSUE THREAD

**Issue by MengZn** [operator-framework/operator-sdk#1254]
## Type of question

This  question is around the operator-sdk.

## Question

**What did you do?**

We can get the return of the event etc Create,Delete ...

**What did you expect to see?**

If we design an action here, we can know the state of the current resource.
```
type Request struct {
	// NamespacedName is the name and namespace of the object to reconcile.
	types.NamespacedName
}
```

**What did you see instead? Under which circumstances?**
By passing the action through the handler, the user can know the current resource situation.
```
// Create is called in response to an create event - e.g. Pod Creation.
func (h *NetHandler) Create(evt event.CreateEvent, q workqueue.RateLimitingInterface) {
	if evt.Meta == nil {
		fmt.Printf("evt.Meta == nil")
		return
	}

	q.Add(reconcile.Request{NamespacedName: types.NamespacedName{
		Name:      evt.Meta.GetName(),
		Namespace: evt.Meta.GetNamespace(),
		Action:    Create,
	}})
}
```

**Environment**
* operator-sdk version:
```
2761657e4cccb42836c8ffca7b6bcacc378e3e1d
 ```

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by shawn-hurley** [comment]
This will need to be filed against https://github.com/kubernetes-sigs/controller-runtime. 

IMO this is not information that a reconciler should need.

**Comment by MengZn** [comment]
@shawn-hurley thanks i will patch this feature in kubernetes-sigs/controller-runtime.
