### ISSUE TITLE
How to create Operator Docker image without Docker (and using Kaniko)?

### ISSUE THREAD

**Issue by marcomancuso** [operator-framework/operator-sdk#1256]
## Type of question

**help around the operator-sdk**

## Question

I need to build the Operator Docker image in Jenkins in Kubernetes using Kaniko, but the current SDK needs the Docker Deamon to create the image.
I was hoping I could run `operator-sdk build ` to just compile the operator without creating the image, but without Docker daemon, it would build the operator and then fail with 
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error: failed to output build image test: (failed to exec []string{"docker", "build", ".", "-f", "build/Dockerfile", "-t", "test"}: exit status 1)
```

A workaround would be to let the command fail and then use Kaniko to push the image.

Is there a better way to do it?
Also, is there an official Docker image with Go and Operator SDK already installed?

**Environment**
* operator-sdk version:

operator-sdk version v0.5.0+git

**Comment by AlexNPavel** [comment]
Hello. The build context for the operator is stored in `build`. The sdk will still fail to build the image itself, but the actual binary and dockerfile should be correct in that directory. For your use case, you can ignore the error and then run the image build part yourself.

**Comment by marcomancuso** [comment]
Is there an official Docker image with Go and Operator SDK already installed?

**Comment by LiliC** [comment]
>Is there an official Docker image with Go and Operator SDK already installed?

There is discussion happening in the https://github.com/operator-framework/operator-sdk/issues/1115

@marcomancuso If Alex answered your question feel free to close this issue and continue the Docker discussion in the above issue so it's in one place, thanks!
