### ISSUE TITLE
How to debug operator remotely

### ISSUE THREAD

**Issue by petro404** [operator-framework/operator-sdk#1260]
## Type of question
best practices

## Question

How can i debug the operator remotely.
I installed my operator on k8s cluster remotely and i would like debug it.

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:

  insert release or Git SHA here

* Kubernetes version information:

  insert output of `kubectl version` here

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by shawn-hurley** [comment]
I think if you want to a debugger like experience, this is your best bet: 

https://github.com/go-delve/delve

Golang's debugger is GDB and even that has some issue AFAIK.

**Comment by petro404** [comment]
so do i need to compile and run delve as part of the operator image?

**Comment by LiliC** [comment]
You can also just run the operator locally with `operator-sdk up local` that should make it easier to debug. Have a look at https://github.com/go-delve/delve/blob/master/Documentation/cli/getting_started.md#debugging-main-packages

**Comment by petro404** [comment]
cool I tried it and its working fine just want to confirm the steps,
in case i want debug remote operator in production i need to setup my .kube/config with the context of the production env ,then i can use visual code(already configured with delve)  to start local operator which watch all the resource in production.
in Addition i need to stop that the production operator in order to prevent race condition between the remote and local operator.

**Comment by LiliC** [comment]
> .kube/config with the context of the production env

Do you have a dev cluster you can test this, might be better? :) But yes you can stop the operator in the cluster and start one locally, the `operator-sdk up local` is usually useful for devel or testing.

**Comment by petro404** [comment]
agree  using the production context  , BTW `operator-sdk up local` will run the operator as separate process and not as containerized  application right?

**Comment by LiliC** [comment]
Yes, it will run on your machine locally, not in the container.

**Comment by petro404** [comment]
Great thanks a lot for your support.
appreciated :)

**Comment by LiliC** [comment]
No problem!
