### ISSUE TITLE
operator-sdk error for --api-version parameter when trying to add `api` and `controller`

### ISSUE THREAD

**Issue by subodh-dharma** [operator-framework/operator-sdk#1262]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

- Installed the operator-sdk from homebrew version 0.6.0
- Created a new project succesfully
- Tried to add the api and controller to the project with commands
```
$ operator-sdk add api --api-version=com.example.com/v1alpha1 --kind=MyKind
$ operator-sdk add controller --api-version=com.example.com/v1alpha1 --kind=MyKind
```

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).
- Expected to see the expected output as per the README.md

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).
- Each of the command lines returns an error as follows

```
$ operator-sdk add api --api-version=com.example.com --kind=MyKind
INFO[0000] Generating api version com.example.com/v1aplha1 for kind MyKind. 
Error: version is not in the correct Kubernetes version format, ex. v1alpha1
Usage:
  operator-sdk add api [flags]

Flags:
      --api-version string   Kubernetes APIVersion that has a format of $GROUP_NAME/$VERSION (e.g app.example.com/v1alpha1)
  -h, --help                 help for api
      --kind string          Kubernetes resource Kind name. (e.g AppService)



$ operator-sdk add controller --api-version=com.example.com --kind=MyKind
INFO[0000] Generating controller version com.example.com/v1aplha1 for kind MyKind. 
Error: version is not in the correct Kubernetes version format, ex. v1alpha1
Usage:
  operator-sdk add controller [flags]

Flags:
      --api-version string   Kubernetes APIVersion that has a format of $GROUP_NAME/$VERSION (e.g app.example.com/v1alpha1)
  -h, --help                 help for controller
      --kind string          Kubernetes resource Kind name. (e.g AppService)
```

**Environment**
* operator-sdk version:

  homebrew install version 0.6.0

* Kubernetes version information:

  

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

Operator in go

**Possible Solution**

I observed inconsistency in the Regex matching here. [source code](https://github.com/operator-framework/operator-sdk/blob/8fbc3446efbed1cc0099f601dff30b07316260a2/pkg/scaffold/resource.go#L31)

**Additional context**
Also if the `--api-version=v1alpha1` is used it returns with the following error
```
Error: full group cannot be empty
```

**Comment by AlexNPavel** [comment]
You need to specify a full group version. For example, "com.example.com/v1alpha1"

**Comment by subodh-dharma** [comment]
My bad also had some typos in the command. Sorry to bother.

**Comment by bclermont** [comment]
in case someone need to use something like `v1/Event` or other api group in k8s you need to use something like this:

```
 operator-sdk add controller --api-version=core/v1 --kind=Event
```

I got `core` from [there](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#event-v1-core)

**Comment by camilamacedo86** [comment]
Hi @bclermont, 

See that this issue shows has a diff context of your need and is closed. Please, feel free to open a new issue for your scenario and do not forget to provide all requested info as versions used and etc for we are able to help you with.

**Comment by bclermont** [comment]
@camilamacedo86 it's not necessarily an issue, I ended on this issue because I was googling the same error message. I put that comment in case someone else in same situation like me ends here.
