### ISSUE TITLE
Improve error messages in olm-catalog file generation

### ISSUE THREAD

**Issue by LiliC** [operator-framework/operator-sdk#1281]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When trying to generate the olm-catalog and there is a problem with something in the yaml manifests, the error message should include which file the problem happened in.

**Describe the solution you'd like**
For example when running the following command I would like to see the information about the file path and filename included in the error message, currently I just can see the problem is on line 7 of a file:
```sh
operator-sdk olm-catalog gen-csv --csv-version 0.1.0
INFO[0000] Generating CSV manifest version 0.1.0
Error: catalog scaffold failed: (error converting YAML to JSON: yaml: line 7: did not find expected key)
Usage:
  operator-sdk olm-catalog gen-csv [flags]
```

**Comment by LiliC** [comment]
cc @estroz

**Comment by hasbro17** [comment]
We should probably strive to be more generous with wrapping errors with some context everywhere we return them.
With something like [errors.Wrap()](https://github.com/pkg/errors#adding-context-to-an-error).
Of course the flip side to that is error messages that can become too verbose but with some judgement there's probably a healthy balance we can strive for.
