### ISSUE TITLE
Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection

### ISSUE THREAD

**Issue by gbaufake** [operator-framework/operator-sdk#1282]
## Bug Report

**What did you do?**
- Installed an Operator (Kiali Test Mesh Operator) which installs on namespace

**What did you expect to see?**
- An operator running the watches

**What did you see instead? Under which circumstances?**
I saw a problem on operator which delete the namespace and all resources created by ansible operator after the following message:

> E0403 14:59:04.093475       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=557, ErrCode=NO_ERROR, debug=""`

Complete Log:

[kiali-test-mesh-operator-fbb758b69-zcknm-operator.log](https://github.com/operator-framework/operator-sdk/files/3039386/kiali-test-mesh-operator-fbb758b69-zcknm-operator.log)

**Environment**
* operator-sdk version: `operator-sdk version v0.6.0`

* Kubernetes version information:

`oc v4.0.0-0.139.0
kubernetes v1.11.0+c69f926354
features: Basic-Auth
kubernetes v1.12.4+8156b0c`

* Kubernetes cluster kind: Openshift

* Are you writing your operator in ansible, helm, or go?
Ansible

**Possible Solution**

Possible problem: https://github.com/openshift/installer/issues/1383
Related #1177 

Possible Related: https://github.com/kubernetes/kubernetes/pull/73277

**Additional context**

**Comment by hasbro17** [comment]
@gbaufake From the upstream issue that you've linked it seems like `Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection` is a harmless log for an event that is expected.
What's surprising is that it is still showing up in SDK `v0.6.0`. With the 1.13.x k8s client libraries I thought this log would have been suppressed.
https://github.com/kubernetes/client-go/blob/master/rest/request.go#L582-L589
https://github.com/kubernetes/apimachinery/blob/3115ef20f323/pkg/util/net/http.go#L77

In any case I don't know if this log line is just a consequence of some other bug in the SDK or completely unrelated.
@gbaufake Are you able to reproduce this consistently? If so, can you please share the steps so we can try it on our end.

@shawn-hurley @fabianvf Do you see anything obvious in the attached logs that jumps out?

**Comment by gbaufake** [comment]
@hasbro17 Yes.
I am able to reproduce with some frequency.

Everything created by the operator vanishes after this message.
[kiali-operator-b5769c4c8-hbfp6-operator.log](https://github.com/operator-framework/operator-sdk/files/3073153/kiali-operator-b5769c4c8-hbfp6-operator.log)

I am using the latest ocp4 builds and updated the openshift-installer

oc v4.0.0-0.139.0
kubernetes v1.11.0+c69f926354
features: Basic-Auth

Server
kubernetes v1.12.4+0ba401e

**Comment by gbaufake** [comment]
@hasbro17 
Retested on Kubernetes  - v1.13.4+81fc896 and it was completely gone.
 I guess it might need to some documentation it would affect old versions of Kubernetes and Openshift.
