### ISSUE TITLE
How to handle expensive reconciling of remote resources?

### ISSUE THREAD

**Issue by paterczm** [operator-framework/operator-sdk#1293]
Hello

I'm trying to manage remote resources via rest api using an ansible operator. It works well for creation and deletion, but I'm not sure how to handle updates. If I set resyncPeriod short, my controller will put significant load on the remote service. If I set resyncPeriod long, users will have to wait significant time before their custom resource updates become effective.

A lastUpdateTimestamp maintained by Kubernetes on the watched resources would solve my problem, but I see no such thing. I could also try comparing against kubectl.kubernetes.io/last-applied-configuration, but from what I'm reading it does not account for all changes. What is the recommended approach for this case?

Thanks
Marek

**Comment by joelanford** [comment]
@paterczm I may be missing something, but the ansible operator should be watching your CRs and dependent resources, and triggering a reconciliation when any of them change.

You should be able to set your `resyncPeriod` long (or disable the periodic resync by setting it to 0) so that your CRs are only reconciled as often as necessary.

Are you seeing different behavior?

**Comment by paterczm** [comment]
Hello @joelanford. My ansible operator is calling the ansible role every resyncPeriod, regardless if the custom resource changed or not. I thought it up to me to detect if it really changed.

**Comment by joelanford** [comment]
@paterczm You set the reconcile period globally with the [`--reconcile-period` flag](https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#ansible), or you can set the `reconcilePeriod` option for a particular GVK in your [`watches.yaml` file](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md#watches-file).

Setting the value to `0` should disable the periodic resync.

**Comment by paterczm** [comment]
> Setting the value to 0 should disable the periodic resync.

That's correct. Looks like there are 2 modes of operation depending on `reconcilePeriod`:
* > 0 means the operator will reconcile every `reconcilePeriod`, regardless if the custom resource changed or not
* == 0 means the operator will reconcile only if the related custom resource changes.

Thanks for help!
