### ISSUE TITLE
Operator-sdk makes syscall, specific to linux making it non-portable to windows.

### ISSUE THREAD

**Issue by ankitsinhaiitg** [operator-framework/operator-sdk#1298]
## Bug Report

**What did you do?**
I tried to compile operator-sdk for windows, got following error - 
 github.com/operator-framework/operator-sdk/pkg/ansible/proxy
pkg\ansible\proxy\kubectl.go:243:13: undefined: syscall.Umask
pkg\ansible\proxy\kubectl.go:245:2: undefined: syscall.Umask
make: *** [install] Error 2

syscall specific to linux and won't work for windows

**Environment**
* operator-sdk version: 0.6.0 

-Can make it generic so it can be compiled on windows as well.

**Comment by joelanford** [comment]
@shawn-hurley Do we use [`ListenUnix()`](https://github.com/operator-framework/operator-sdk/blob/987b9c945a0871fcc074384cc93b7fc5412341e3/pkg/ansible/proxy/kubectl.go#L233-L247)? If not can we remove it so that we don't break windows portability?

If we do need to keep it, maybe we could move it to `kubectl_unix.go` and use [conditional compilation](https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool) so that it only builds on unix systems?

**Comment by shawn-hurley** [comment]
Consider this: 

```
// This code was retrieved from
// https://github.com/kubernetes/kubernetes/blob/204d994/pkg/kubectl/proxy/proxy_server.go
// and modified for use in this project.
```

I have to assume that k/k has some way to build the binary for windows because it does not appear to need conditional compilation as far as I can tell.

**Comment by joelanford** [comment]
It looks like we use `syscall` directly, but that implementation of `proxy_server.go` uses conditional compilation in [`k8s.io/kubernetes/pkg/kubectl/util`](https://github.com/kubernetes/kubernetes/blob/204d994/pkg/kubectl/util) with:
* https://github.com/kubernetes/kubernetes/blob/204d994aca210e1ef20ea947ae0555df7b70a994/pkg/kubectl/util/umask.go
* https://github.com/kubernetes/kubernetes/blob/204d994aca210e1ef20ea947ae0555df7b70a994/pkg/kubectl/util/umask_windows.go

We could probably just swap out `syscall` for `k8s.io/kubernetes/pkg/kubectl/util`.

**Comment by joelanford** [comment]
We already [vendor `k8s.io/kuberentes`](https://github.com/operator-framework/operator-sdk/blob/2ca5cb197fad6e5a4f4f61d53e1426835cb267c9/Gopkg.toml#L62) and [prune unused packages](https://github.com/operator-framework/operator-sdk/blob/2ca5cb197fad6e5a4f4f61d53e1426835cb267c9/Gopkg.toml#L78), so I don't think it would be a big deal to use `k8s.io/kubernetes/pkg/kubectl/util` directly.

I'll submit a PR and we'll see how it looks.
