### ISSUE TITLE
Is the operator-sdk scorecard up to date?

### ISSUE THREAD

**Issue by galderz** [operator-framework/operator-sdk#1299]
I've compiled master and tried running it as, but get an error saying the operator manifest cannot be found:

```
operator-sdk scorecard \
      --cr-manifest ../cr_minimal.yaml \
      --csv-path .../operator.clusterserviceversion.yaml \
WARN[0000] Could not load config file; using flags
WARN[0000] Could not find the serviceaccount manifest: (open deploy/service_account.yaml: no such file or directory)
WARN[0000] Could not find role manifest: (open deploy/role.yaml: no such file or directory)
WARN[0000] Could not find role_binding manifest: (open deploy/role_binding.yaml: no such file or directory)
Error: could not find operator manifest: (open deploy/operator.yaml: no such file or directory)
```

What exactly is it complaining about? The README of scorecard says this should work.

**Comment by LiliC** [comment]
@galderz Yes, I tried it out and confirmed the above does not work for me either. The problem is it assumes you have a `deploy` directory in that path, as per the operator-sdk directory/file structure. So when it tries to search for the other manifests it searches for them in the known paths and yours are not there.

cc @AlexNPavel WDYT of adding a flag to provide your own path to the "deploy" directory where users would keep all the manifests?

**Comment by AlexNPavel** [comment]
What is your directory structure? If it follows the standard deploy directory structure of the SDK (for versions v0.1.0+), it should work correctly. If not, you can either modify your project to match the expected directory/manifest structure, or use the `--global-manifest` and `--namespaced-manifest` flags to specify the necessary manifests for running your operator (documentation: https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/scorecard.md#running-the-tests).

NOTE: in SDK versions before v0.1.0, the `--namespaced-manifest` flag had a typo and was `--namespace-manifest` instead.

**Comment by galderz** [comment]
Ah ok, now I understand this has to be executed from the root of the operator directory.

We originally did not have these role/role_binding/service_account files separated, we just had a `deploy/rbac.yaml` file containing all of them, so that's why I was confused about this.

I'll close this and reopen, I'm still having some other issues.
