### ISSUE TITLE
How to deploy scorecard proxy?

### ISSUE THREAD

**Issue by galderz** [operator-framework/operator-sdk#1301]
What are we supposed to do with the scorecard proxy? There's no info about it on scorecard README.

See below:

```
@g ~/1 $    operator-sdk scorecard \
@>      --cr-manifest go/src/github.com/infinispan/infinispan-operator/deploy/cr/cr_minimal.yaml \
@>      --csv-path openshift/community-operators/upstream-community-operators/infinispan/infinispan-operator.v0.2.1.clusterserviceversion.yaml \
@>      --crds-dir openshift/community-operators/upstream-community-operators/infinispan \
@>      --olm-deployed \
@>      --namespace local-operators \
@>      --verbose
WARN[0000] Could not load config file; using flags
WARN[0010] getUsedResource failed: failed to get logs: container scorecard-proxy is not valid for pod infinispan-operator-645477f7b-7ljvk
Basic Tests:
	Spec Block Exists: 1/1
	Status Block Exists: 0/1
	Writing into CRs has an effect: 0/1
OLM Tests:
	Provided APIs have validation: 0/0
	Owned CRDs have resources listed: 1/1
	CRs have at least 1 example: 1/1
	Spec fields with descriptors: 1/2
	Status fields with descriptors: 0/0

Total Score: 44%
SUGGESTION: Add a 'status' field to your Custom Resource
SUGGESTION: Add a spec descriptor for image
ERROR: error getting proxy logs: failed to get logs: container scorecard-proxy is not valid for pod infinispan-operator-645477f7b-7ljvk
```

**Comment by LiliC** [comment]
There is a flag:
```
proxy-image string - Image name for scorecard proxy (default "quay.io/operator-framework/scorecard-proxy")
```

https://github.com/operator-framework/operator-sdk/blob/76d13fccc3672c0ad4eb969abb9b9885678771e4/doc/sdk-cli-reference.md#flags-13

**Comment by estroz** [comment]
@galderz we'll be adding to the scorecard docs in the coming weeks. From the scorecard [docs](https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/scorecard.md#how-it-works):

>The scorecard works by creating all resources required by CRs and the operator. For the operator deployment, it also adds another container to the operator's pod that is used to record calls to the API server, which are analyzed by the scorecard for various tests. The scorecard will also analyze the CR object itself, modifying spec fields and monitoring how the operator responds.

This section refers to the scorecard proxy container.

Can you link your `deploy/operator.yaml`?

**Comment by galderz** [comment]
Closing this for now. I'm unable to get the scorecard running at all, see #1517.

**Comment by flickerfly** [comment]
Anyone who runs into this issue because of `ERROR: error getting proxy logs: failed to get logs: container scorecard-proxy is not valid for pod` might want to see: #1918 

And the resulting pull #1921 .

**Comment by camilamacedo86** [comment]
Hi @flickerfly,

It shows to be another issue. Could you please raise a new one?

**Comment by flickerfly** [comment]
@camilamacedo86 Will do!
