### ISSUE TITLE
operator-sdk test x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by allamand** [operator-framework/operator-sdk#1304]
## Question

What is the best way to get ride of the x509 error message in tests ?

Can we interract with the config: kubeconfig.TLSClientConfig.Insecure = true

**What did you do?**
```
operator-sdk test local ./test/e2e  --kubeconfig /user/.kube/config --go-test-flags "-v -timeout 40m"
```

**What did you expect to see?**
Tests to execute properly on the cluster.

Note, that I've got no problem with kubectl

**What did you see instead? Under which circumstances?**

I've got the error message : 
```
time="2019-04-09T16:16:36+02:00" level=fatal msg="failed to set up framework: failed to build the dynamic client: Get https://mycluster.org/api?timeout=32s: x509: certificate signed by unknown authority"
```

**Environment**
* operator-sdk version:
operator-sdk version v0.2.0+git

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by AlexNPavel** [comment]
Hello. Is `insecure-skip-tls-verify: true` set in your kubeconfig for your cluster or are you specifying it as a flag to kubectl? The test framework in `v0.2.0` uses the `clientcmd` config getter, which should be correctly picking up the `insecure-skip-tls-verify` config in the kubeconfig.

**Comment by allamand** [comment]
Hi Alex, thanks for the input.

I didn't uses the `insecure-skip-tks-verify` flag as my laptop is normally configure to accept the certificate.

Meanwhile I added this to the config and you're right this makes it works with operator-sdk test :)

But I didn't understand why operator-sdk need the insecure flag, while kubectl don't?

I try to set this environment variable before starting operator-sdk-test (without insecure-skip in the config) and it works

```
CGO_ENABLED=0 operator-sdk test local ./test/e2e  --kubeconfig /user/.kube/config --go-test-flags "-v -timeout 40m"
```

This may help others
