### ISSUE TITLE
ansible and helm packages should be useful libraries

### ISSUE THREAD

**Issue by mhrivnak** [operator-framework/operator-sdk#1307]
## Feature Request

Relevant use cases as an operator author:
* I want to augment reconciliation logic with go code that runs before or after my ansible or helm based reconciliation logic.
* I want to trigger reconciliation from a goroutine, such as from a Channel source.

These use cases target someone who has created a go-based operator and wants to add reconciliation behavior by using ansible or helm.

**Describe the solution you'd like**
Proposals need to be made to turn the ansible and helm packages into first-class libraries, with documentation, that can be used to add behavior to a go-based controller.

**Open Questions**
The existing Helm (and possibly Ansible) libraries export most of their types and functions. As we approach the SDK 1.0.0 release:
* Which of those types and functions should we unexport to give us more flexibility to make changes in the future?
* Which do we need to continue to export to support these use cases?
  * Answer: We should expose pretty much everything except the reconciler.

**Comment by varshaprasad96** [comment]
We have released SDK 1.0 a while back, and also have respective code-bases split into useful libraries. Closing this issue since this has been open for a while.
