### ISSUE TITLE
helm-operator Release not found, removing finalizer

### ISSUE THREAD

**Issue by dragon9783** [operator-framework/operator-sdk#1316]
## Bug Report

**What did you do?**
1. `operator-sdk up local`
2. `kubectl create -f /path/to/crd.yaml`
3. `kubectl create -f /path/to/cr.yaml`
4. `kubectl delete -f /path/to/cr/yaml`

I found that the custom resource Nginx not been deleted, and got errors
`{"level":"info","ts":1555057401.86288,"logger":"helm.controller","msg":"Release not found, removing finalizer","namespace":"default","name":"example-test","apiVersion":"plat.test.ai/v1alpha1","kind":"Nginx","release":"example-test-959sw3k5axhsnsozgp5dlpdn8"}
{"level":"error","ts":1555057402.4121048,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"nginx-controller","request":"default/example-nginx","error":"the server could not find the requested resource","stacktrace":"github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsrc/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tsrc/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}`

**What did you expect to see?**
delete custome resource sucessfully

**What did you see instead? Under which circumstances?**

**Environment**
* operator-sdk version: v0.6.0

* go version: go1.12.3 darwin/amd64

* Kubernetes version information: v1.10.2

* Kubernetes cluster kind: helm

* Are you writing your operator in ansible, helm, or go?
`operator-sdk new project`

**Possible Solution**

**Additional context**

**Comment by LiliC** [comment]
Hello @dragon9783 not sure if it's related but we support Kubernetes v1.11.3+ cluster, as noted in the https://github.com/operator-framework/operator-sdk#prerequisites. 

So the logs are after you executed the `kubectl delete -f /path/to/cr/yaml` command? 

cc @joelanford

**Comment by joelanford** [comment]
@dragon9783 I'm pretty sure this is related to the Kubernetes version. The Helm-based operators use the status subresource, which requires Kubernetes 1.11. I think `"error":"the server could not find the requested resource"` is saying it can't find the status subresource. 

And if you're curious, the reason for v1.11.3 specifically is that it includes a fix related to CRD pluralization that affects some resource names, one being `Nginx`.

**Comment by dragon9783** [comment]
@LiliC @joelanford thanks for reply soon, i will upgrade kubernetes to version v1.11.3, and try it, thanks again!
