### ISSUE TITLE
Update json tag, keep compatibility

### ISSUE THREAD

**Issue by eivantsov** [operator-framework/operator-sdk#1317]
## Type of question

What would be the best way to update json tag in CR struct spec, and keep compatibility at the same time?

Now I have an existing CR in a running server:

```
spec:
  oldKey: true
```
If I change json tag to a `newKey` in the struct, and update custom resource, it is replaced with a new one, however, it has the default value, since oldKey wasn't found when CR was retrieved:

```
spec:
  newKey: false
```

How can I keep backward compatibility, ie update oldKey with newKey, keeping the same value? It is not possible to have several json tags in a struct. Are there any best practices here?

**Comment by hasbro17** [comment]
@eivantsov If I understand correctly you are trying to update the API/spec fields of your CRD, but you still want to handle older instances of the CRD with the older API and convert them to the new API.

If that's the case then you're probably asking about the CRD versioning and conversion.
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/
We're still figuring out the workflow for the CRD upgrade lifecycle and are waiting on some upstream changes to support this #1240 
If that's what you meant then we can move the discussion to #1240 

If it's something else then we can clarify it here.

**Comment by eivantsov** [comment]
@hasbro17 yes, it looks like I asked if versioning is the best solution. I tried to add a new API version + migration function, and it worked for me. Thanks for helpful links. CLosing.
