### ISSUE TITLE
Update brew formula : version 0.7.0

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#1318]
## Feature Request

Is it possible to update the Brew's formula in order to been able to install `operator-sdk` version `0.7.0` ?

**Comment by AlexNPavel** [comment]
Hello. We don't manage the brew formula for the operator-sdk. The bump from `v0.5.0` to `v0.6.0` was done by the brew community about 3 days after release, so I would expect them to update soon. I will have access to a Mac for testing on Monday, so if it is not done by then, I will make a PR over at homebrew-core for the version bump.

**Comment by LiliC** [comment]
@cmoulliard there should be a new formula for the latest version.
