### ISSUE TITLE
Operator container -- Running as is non root user

### ISSUE THREAD

**Issue by petro404** [operator-framework/operator-sdk#1325]
## Type of question

support

## Question
is there an option to run the operator container as non root user?

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:0.50

  insert release or Git SHA here

* Kubernetes version information:

  insert output of `kubectl version` here

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by AlexNPavel** [comment]
Can you clarify your question? The process inside the built containers already runs as a non-root user (which is a requirement for openshift clusters). Specifically, we run as UID 1001: https://github.com/operator-framework/operator-sdk/blob/master/internal/pkg/scaffold/build_dockerfile.go#L39:L51

**Comment by petro404** [comment]
thanks
