### ISSUE TITLE
Pass operator env from CLI

### ISSUE THREAD

**Issue by BuddhiWathsala** [operator-framework/operator-sdk#1332]
## Type of question

How to pass environment variables in operator.yaml from operator-sdk CLI?

## Question

**What did I do?**
I had some of the operator related configurations which I need to access in the `Reconcile` loop. So, I added those configuration parameters as environment variables in operator.yaml deployment.

**What did I expect to see?**
Once I build and run the operator deployment inside the cluster, it works fine. But when I run locally outside the cluster(using `operator-sdk up local --namespace=default`), reconcile loop unable to access operator environment variables. My reconcile loop need to access those environmental variables when I run `operator-sdk up local --namespace=default`.

**What did I see instead? Under which circumstances?**
`Reconcile` loop unable to access those environmental variables.

**Environment**
* operator-sdk version: v0.5.0+git

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: minikube version: v0.33.1

**Comment by linzhaoming** [comment]
I think you could refer the following codes, to access the env in the Reconciler codes.

https://github.com/operator-framework/operator-sdk/blob/3f9650c8088944b893516fb3175bf8b95843fe42/pkg/k8sutil/k8sutil.go#L34

**Comment by shawn-hurley** [comment]
Have you exported the environment variables into your environment when running `operator-sdk up local`?

**Comment by LiliC** [comment]
@BuddhiWathsala has the above answered your question and we can close this issue, or do you have any other questions?
