### ISSUE TITLE
unable to generate olm-csv if no CRD are defined

### ISSUE THREAD

**Issue by raffaelespazzoli** [operator-framework/operator-sdk#1334]
## Bug Report

**What did you do?**
I wanted to generate the OCL CSV. I have an operator that does not define any new CRD. I got the following output:
```
operator-sdk olm-catalog gen-csv --csv-version 0.1.0
INFO[0000] Generating CSV manifest version 0.1.0        
Error: catalog scaffold failed: (lstat deploy/crds: no such file or directory)
Usage:
  operator-sdk olm-catalog gen-csv [flags]

Flags:
      --csv-config string     Path to CSV config file. Defaults to deploy/olm-catalog/csv-config.yaml
      --csv-version string    Semantic version of the CSV
      --from-version string   Semantic version of an existing CSV to use as a base
  -h, --help                  help for gen-csv
      --update-crds           Update CRD manifests in deploy/{operator-name}/{csv-version} the using latest API's
``` 

**What did you expect to see?**
Not sure, this was the first time I was running this command, not an error though.

**What did you see instead? Under which circumstances?**
see the output above.

The general question is: can OLM be used with an operator that does not define any new CRD? If yes the `operato-sdk olm-catalog gen-cvs` command should work.

**Environment**
* operator-sdk version:
```
operator-sdk --version
operator-sdk version v0.6.0+git
```
* go version:

```
go version
go version go1.11.6 linux/amd64
```

**Comment by hasbro17** [comment]
@raffaelespazzoli Probably someone from the OLM team can confirm if a CSV with no [owned CRDs](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/building-your-csv.md#owned-crds) is valid before we decide to update the `csv-gen` command.
/cc @estroz 

@ecordell @alecmerdler Is the `spec.customresourcedefinitions.owned` field optional for a CSV?

**Comment by estroz** [comment]
Based on the language used to describe the CRD's field, it sounds like they're optional:

>There are two types of CRDs that your Operator may use, ones that are “owned” by it and ones that it depends on, which are “required”.

I'm ok removing the requirement for `owned` CRD's. @raffaelespazzoli I assume you're using external `required` CRD's instead?

**Comment by raffaelespazzoli** [comment]
yes I am using required.
