### ISSUE TITLE
Watch regular resources like pod,ingress,service

### ISSUE THREAD

**Issue by fkarakas** [operator-framework/operator-sdk#1335]
Hello,
Is is possible to watch "regular" kubernetes resources like pods, ingress, service using operator-framework.

No custom resources

thanks

**Comment by hasbro17** [comment]
@fkarakas Yes, the controller's [Watch](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/controller#ex-Controller) API let's you watch any resource that is registered on your apiserver (custom and standard k8s resources).

E.g we add a secondary watch for `appsv1.Deployment{}` in the memcached-operator example.
https://github.com/operator-framework/operator-sdk-samples/blob/master/memcached-operator/pkg/controller/memcached/memcached_controller.go#L55-L58

If you were reconciling events for Deployments as the primary resource for your controller you would simply specify that as the type in your Watch:
```Go
err = c.Watch(&source.Kind{Type: &appsv1.Deployment{}}, &handler.EnqueueRequestForObject{})
```
And your reconciler would handle Deployments as the primary resource:
```Go
func (r *ReconcileDeployment) Reconcile(request reconcile.Request) (reconcile.Result, error) {
	// Fetch the Deployment instance
	dep := &appsv1.Deployment{}
	err := r.client.Get(context.TODO(), request.NamespacedName, dep)
	...
}
``` 

Feel free to close the issue if the above helps answer your question.

**Comment by camilamacedo86** [comment]
Hi @fkarakas I'd like to recommend checking the discussion https://github.com/operator-framework/operator-sdk/issues/1350 which shows help you regards the subject raised here as well.

**Comment by hasbro17** [comment]
Closing this for now.

**Comment by Jamlee** [comment]
operator-sdk 1.0 使用这种方式：
```
 operator-sdk create api  --group="core"  --version v1 --kind Service  --resource=false --controller=true
```

**Comment by drewwells** [comment]
> operator-sdk 1.0 使用这种方式：
> 
> ```
>  operator-sdk create api  --group="core"  --version v1 --kind Service  --resource=false --controller=true
> ```

This would be a great addition to the docs. Alternatively, the word "core" could ensure resource does not get created.
