### ISSUE TITLE
Helm chart dependency fetch when creating new project

### ISSUE THREAD

**Issue by morstad** [operator-framework/operator-sdk#1336]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**  help around operator-sdk - change observed with latest code

## Question

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

```
operator-sdk new ibm-websphere-liberty-oper --type=helm --helm-chart=https://raw.githubusercontent.com/IBM/charts/master/repo/stable/ibm-websphere-liberty-1.8.0.tgz
```

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

Creation of ibm-websphere-liberty-oper project

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

Project creation failed - helm fetch performed for dependencies in requirements.yaml even though version of subchart is already present in charts subdirectory.  The requirements.yaml references internal helm repo location for subchart that was packaged with parent chart and is NOT defined / available to fetch updates.  Prior to pulling latest operator-sdk this was successful, but appears change was made to update dependencies.  Is there a way to disable fetch of dependencies if present?  

**requirements.yaml :** 
```
dependencies:
  - name: ibm-shared-liberty
    repository: "@slt" ## where 'slt' is [NAME] from the cmd: helm repo add [flags] [NAME] [URL]
    version: 1.9.0
    alias: slt
```

**Failure message :** 
```
INFO[0000] Creating new Helm operator 'ibm-websphere-liberty-oper'. 

Error: failed to create helm chart: failed to fetch chart dependencies: no repository definition for @slt. Please add them via 'helm repo add'
Usage:
  operator-sdk new <project-name> [flags]

Flags:
      --api-version string          Kubernetes apiVersion and has a format of $GROUP_NAME/$VERSION (e.g app.example.com/v1alpha1) - used with "ansible" or "helm" types
      --cluster-scoped              Generate cluster-scoped resources instead of namespace-scoped
      --generate-playbook           Generate a playbook skeleton. (Only used for --type ansible)
      --helm-chart string           Initialize helm operator with existing helm chart (<URL>, <repo>/<name>, or local path)
      --helm-chart-repo string      Chart repository URL for the requested helm chart
      --helm-chart-version string   Specific version of the helm chart (default is latest version)
  -h, --help                        help for new
      --kind string                 Kubernetes CustomResourceDefintion kind. (e.g AppService) - used with "ansible" or "helm" types
      --skip-git-init               Do not init the directory as a git repository
      --type string                 Type of operator to initialize (choices: "go", "ansible" or "helm") (default "go")

```

**Environment**
* operator-sdk version:
```
$operator-sdk version
operator-sdk version: v0.7.0+git
```
* Kubernetes version information:
```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4+icp-ee", GitCommit:"d03f6421b5463042d87aa0211f116ba4848a0d0f", GitTreeState:"clean", BuildDate:"2019-01-17T13:14:09Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
```
ICP
```
**Additional context**
Using operator-sdk to convert helm chart which contains subcharts that are developed separately and included as subchart for publication - subcharts are NOT published separately to external helm repo.

**Comment by joelanford** [comment]
@morstad The automatic dependency fetching was added recently because many of the charts in [`helm/charts`](https://github.com/helm/charts) are not self-contained and require their dependencies to be fetched prior to generating their RBAC rules and being packaged into an operator.

The helm dependency updater currently [checks that all dependency repos exist](https://github.com/helm/helm/blob/74209401d32ad4751708e4a737a81a601abc8bea/pkg/downloader/manager.go#L89-L92), regardless of the presence of the required sub-charts.

Since the `ibm-shared-liberty` dependency is distributed with the parent chart and is not accessible separately externally, it should probably not be present in the externally distributed `requirements.yaml` file. Is it possible to remove it?

If not, a simple workaround would be to fetch the chart into a local directory, remove the inaccessible repos/dependencies from `requirements.yaml`, and then create the operator with `operator-sdk new --type=helm --helm-chart=/path/to/local/modified/chart my-oper`.

On the operator-sdk side, we could look into adding a flag to skip the dependency update entirely, but it seems like a hack that only makes sense in the scenario you've described (i.e. the dependency is distributed with parent chart and `requirements.yaml` refers to that dependency but in an inaccessible location)

**Comment by morstad** [comment]
The subchart in this case may be able to be removed from requirements.yaml, but do not believe that is always the case - especially when doing conditional enablement of subcharts with the  requirements.yaml at install time.  I am able to work around this change, but wanted to be sure impact of recent change was understand.

**Comment by joelanford** [comment]
@morstad Good point about the conditional subcharts. I didn't think about that aspect of it.

To handle that case, I think there are two options:
1. Distribute `ibm-shared-liberty` from a publically accessible Helm repo, such that it "just works" with `requirements.yaml`.
2. In `requirements.yaml`, use `repo: file://...`. I've been experimenting with this option, and it looks like you would need to move the subcharts to a different subdirectory of the chart and leave them untar-ed to make Helm happy.

For example:
```
$ tree ibm-websphere-liberty
ibm-websphere-liberty
├── Chart.yaml
├── local-repo
│   └── ibm-shared-liberty
│       ├── Chart.yaml
│       ├── README.md
│       └── templates
│           ├── ...
├── requirements.yaml
├── ...

$ cat ibm-websphere-liberty/requirements.yaml
dependencies:
  - name: ibm-shared-liberty
    repository: file://./local-repo/ibm-shared-liberty
    version: 1.9.0
```

FWIW, its a little strange to me that Helm doesn't seem to support resolving subcharts from the parent's `charts` directory with the repo `file:///` mode. That might be worth an upstream issue if you think option 2 makes sense.

**Comment by morstad** [comment]
I found issue previously which reported behavior you saw (see  https://github.com/helm/helm/issues/3742) - looks like may have been some movement to fix in last month, but unfortunately has been open for some time.

**Comment by joelanford** [comment]
Oh wow, yeah that's exactly what I was seeing. It looks like the PR (https://github.com/helm/helm/pull/3987) has been updated somewhat recently and is waiting on another review.

Do you think that PR will resolve this issue?

**Comment by morstad** [comment]
Understand options and investigating how to best address issue encountering - at different stages of build process there is need for helm dependency update.  Ultimately an option to disable dependency checking on conversion would be preferred, but understand is limited use case.

**Comment by joelanford** [comment]
@morstad Understood. I think the best way forward is to leave this issue open and wait for the upstream fix to be merged. If that resolves this issue, we can close this one. If it doesn't (or that PR is closed without being merged), we can look into other options on the SDK side.
