### ISSUE TITLE
unauthorized: access to the requested resource is not authorized to push docker image

### ISSUE THREAD

**Issue by houshengbo** [operator-framework/operator-sdk#1337]
```
$ operator-sdk build quay.io/example/memcached-operator:v0.0.1
$ sed -i 's|REPLACE_IMAGE|quay.io/example/memcached-operator:v0.0.1|g' deploy/operator.yaml
$ docker push quay.io/example/memcached-operator:v0.0.1
```
I was running thru these commands, but it popped up "unauthorized: access to the requested resource is not authorized", when I hit "docker push quay.io/example/memcached-operator:v0.0.1".

**Comment by joelanford** [comment]
@houshengbo the `quay.io/example/memcached-operator` image name is just an example. You'll need to create a quay account and use it in your image name in place of `example` (e.g. `quay.io/houshengbo/memcached-operator:v0.0.1`). 

Or if you already have an account on another image repository like Docker Hub, you can push there as well.

If the above doesn't solve your problem, definitely re-open this issue and we can help figure it out.

**Comment by houshengbo** [comment]
@joelanford I just figured it out, but strongly suggest updating the documentation, by saying that the image should be named after quay.io/<username>/<repository name>.

First, make sure you have a valid account with quay.io or other public online repo like docker.io.
Then, <username> should be the username registered with the public repo.
Third, <repository name> can be anything, when push the docker image.
At last but not least, make <repository name> public, after pushing the image, so that it can be pulled.

**Comment by degenaro** [comment]
As a noob to operators and docker registry, I concur with houshengbo.  Here https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md just a few words on the necessary prereqs for docker push to work would be helpful:
```
Build the memcached-operator image and push it to a registry:

$ operator-sdk build quay.io/example/memcached-operator:v0.0.1
$ sed -i 's|REPLACE_IMAGE|quay.io/example/memcached-operator:v0.0.1|g' deploy/operator.yaml
$ docker push quay.io/example/memcached-operator:v0.0.1
```
