### ISSUE TITLE
kubectl get deployment and kubectl get pods did not generate as the instruction described

### ISSUE THREAD

**Issue by houshengbo** [operator-framework/operator-sdk#1338]
When I went through 2. Run locally outside the cluster, I have got nothing about the deployment, after the command "kubectl apply -f deploy/crds /cache_v1alpha1_memcached_cr.yaml".
"kubectl get deployment" yielded nothing.
"kubectl get pods"yields 
```
NAME                              READY   STATUS      RESTARTS   AGE
example-memcached-pod             1/1     Running     0          73s
```

It is not as described in the instruction.

**Comment by hasbro17** [comment]
@houshengbo Did you update the default reconcile code in your memcached_controller.go file?

https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#add-a-new-controller

> For this example replace the generated Controller file `pkg/controller/memcached/memcached_controller.go` with the example [memcached_controller.go](https://github.com/operator-framework/operator-sdk/blob/master/example/memcached-operator/memcached_controller.go.tmpl) implementation.

From the name of the pod `<cr-name>-pod` it seems you're using the default reconciler code scaffolded for your controller's handler.
