### ISSUE TITLE
watchClusterScopedResources does not seem to work for Ansible Operator

### ISSUE THREAD

**Issue by wkulhanek** [operator-framework/operator-sdk#1342]
## Bug Report

**What did you do?**
Wrote an operator that creates ClusterResourceQuota objects based on User objects and a custom UserQuota object. Added "watchClusterScopedResources: true" to the watches.yaml file.

**What did you expect to see?**
Expected the CRQs to be cleaned up when the UserQuota object gets deleted. This does not happen.

**What did you see instead? Under which circumstances?**
CRQs don't get deleted. I had to label the created CRQs during the creation and then write a finalizer that deletes all CRQs upon deletion of the UserQuota object.

UserQuota is a clusterwide resource.

**Environment**
* operator-sdk version: 0.0.7

* Kubernetes version information:
OCP 4.0.0-0.9

* Kubernetes cluster kind: 
OpenShift

* Are you writing your operator in ansible, helm, or go?
Ansible

**Additional context**
The full source code for the operator is here:
https://github.com/redhat-gpte-devopsautomation/userquota-operator

ATTN: @shawn-hurley

**Comment by shawn-hurley** [comment]
@wkulhanek Sorry for the late reply is your operator watching all namespaces or just a single namespace?

**Comment by wkulhanek** [comment]
@shawn-hurley Watching a cluster wide resource. The "ClusterQuota" custom resource is cluster scoped.
