### ISSUE TITLE
Error when running `operator-sdk build` using brew install 

### ISSUE THREAD

**Issue by hsaputra** [operator-framework/operator-sdk#1345]
## Bug Report

**What did you do?**
Following steps from User guide to try to build Memcached Operator

**What did you expect to see?**
When running `operator-sdk build quay.io/example/memcached-operator:v0.0.1` I expect to generate Docker image for the Operator.

**What did you see instead? Under which circumstances?**

```
 operator-sdk build quay.io/example/memcached-operator:v0.0.1
# github.com/example-inc/memcached-operator/vendor/contrib.go.opencensus.io/exporter/ocagent
vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go:299:38: undefined: "github.com/example-inc/memcached-operator/vendor/github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1".ConstantSampler_ALWAYS_ON
vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go:52:3: unknown field 'MetricDescriptor' in struct literal of type "github.com/example-inc/memcached-operator/vendor/github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1".Metric
Error: failed to build operator binary: (failed to exec []string{"go", "build", "-gcflags", "all=-trimpath=${GOPATH}", "-asmflags", "all=-trimpath=${GOPATH}", "-o", "/Users/hsaputra/go/src/github.com/example-inc/memcached-operator/build/_output/bin/memcached-operator", "github.com/example-inc/memcached-operator/cmd/manager"}: exit status 2)
```

**Environment**
* operator-sdk version:

```
operator-sdk version
operator-sdk version: v0.6.0+git
```

* go version:
```
go version
go version go1.12.4 darwin/amd64
```

* Kubernetes version information:
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

I was building the operator using Go lang.

**Comment by joelanford** [comment]
@hsaputra Can you retry with operator-sdk `v0.7.0`? I'm pretty sure this was fixed by https://github.com/operator-framework/operator-sdk/pull/1248.

**Comment by joelanford** [comment]
I should have also mentioned that you'll likely need to recreate the project or remove [these lines](https://github.com/estroz/operator-sdk/blob/f0d8d965d5fd22d17a3efcb7fe3b8d94af5c402f/pkg/scaffold/gopkgtoml.go#L98-L101) from your `Gopkg.toml` and then run `dep ensure -update`.

**Comment by hsaputra** [comment]
Thanks, @joelanford - will give it a try

**Comment by hsaputra** [comment]
Cool, it works. Thanks! 👍
