### ISSUE TITLE
How can we search about metav1.List resources

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#1350]
## Query a list of resources

How can we query a list of resources (pod, service, ...) using the `client.List(` function ?

Example
```
	listResources := &unstructured.UnstructuredList{}
	listResources.SetGroupVersionKind(schema.GroupVersionKind{Kind: "List", Group: "", Version: "v1"})
	// Let's check if we have owned references for the CR
	listOps := client.ListOptions{
		Namespace:     instance.ObjectMeta.Namespace,
		LabelSelector: getLabelsSelector(labels),
	}
	err = r.client.List(context.TODO(), &listOps, listResources)
	if err != nil {
```
generates an error 

![Screenshot 2019-04-25 15 36 01](https://user-images.githubusercontent.com/463790/56739800-dd19d800-676f-11e9-815d-76083b1aeb1e.png)

**Comment by cmoulliard** [comment]
Apparently, the `set/GroupKindVersion` should be defined using a k8s resource list such as by example`PodList, ServiceList,...`. Otherwise [this function](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/unstructured_client.go#L144) will remove from the string the 4 chars represented by `Kind` and this why we get the error. That will not happen if we define the group ads `PodList`

Question: Can we make a search for all the k8s resources then ?

**Comment by cmoulliard** [comment]
Any feedback ? @LiliC

**Comment by LiliC** [comment]
@cmoulliard You can go through all the resources (Pod, Service, Deployment, etc.) in a loop and replace the group you set to list them all. Why do you need to do this, if I can ask? :)

**Comment by cmoulliard** [comment]
Here is what I have coded to fetch all the resources created by the operator and where the label condition matches

```
 // Query k8s to get all the resources having labels of the Custom Resources
	res, err := r.Query(convertMapToString(labels),instance.ObjectMeta.Namespace,"all")
	if err != nil {
		return reconcile.Result{}, err
	} else {
		reqLogger.Info("Status of the resources")
		for _, r := range res {
			resource := r.Object
			unstruct, _ := runtime.DefaultUnstructuredConverter.ToUnstructured(resource)
			status := unstruct["status"].(map[string]interface{})
			reqLogger.Info("Status of the resource","Type",resource.GetObjectKind().GroupVersionKind().Kind,"AND Status",status["phase"])
		}
	}

    ...
	// CR has already been processed. No further action needed
	return reconcile.Result{}, nil
}

type QueryOptions struct {
	builder *resource.Builder
	configFlags *genericclioptions.ConfigFlags
}

func NewQueryOptions() *QueryOptions {
	return &QueryOptions{
		configFlags: genericclioptions.NewConfigFlags(),
	}
}

func (r *Reconciledatabase) Config() *QueryOptions {
	q := NewQueryOptions()
	q.configFlags.ToRESTConfig()
	q.builder = resource.NewBuilder(q.configFlags)
	return q
}

func (r *Reconciledatabase) Query(selector, ns, resources string) ([] *resource.Info, error) {
	resp := r.Config().builder.
		Unstructured().
		NamespaceParam(ns).
		ResourceTypeOrNameArgs(true, resources).
		LabelSelector(selector).
		Latest().
		Flatten().
		Do()

	infos, err := resp.Infos()
	if err != nil {
		return nil, err
	}

	return infos, nil
}
```

Remarks: 

- I would like to get all the watched resources in order to verify if the pod status = `running`, .... and if all the statuses of the resources are OK, then I will update the status of the CR to by example the value `Running` or `Installed` in order to inform the user that they can continue to work
- Ideally, I would like to fetch all resources owned by a k8s resource

**Comment by camilamacedo86** [comment]
Hi @cmoulliard, you can do it. 

In the controller, you will define the type of object that you would like to watch as the filters. The following code means that it will watch all resources which are from this type/owner. 

```go
	err = c.Watch(&source.Kind{Type: &mobilesecurityservicev1alpha1.MobileSecurityService{}}, &handler.EnqueueRequestForObject{})
	if err != nil {
		return err
	}
```

To watch all Pods you will do as follows. 

```go
func watchService(c controller.Controller) error {
	err := c.Watch(&source.Kind{Type: &corev1.Pod{}}, &handler.EnqueueRequestForOwner{
		IsController: true, 
		OwnerType:    &mobilesecurityservicev1alpha1.MobileSecurityService{}, // HERE is the owner
	})
	return err
} 
```

Then, note that the order followed is the order that you add the impl in the Reconcile. In the reconcile you will be able to check if exist or not and create as update the status in the CR. Following an example. 

```
reqLogger.Info("Checking if the pod already exists")
	pod := &corev1.POD{}
	err := r.client.Get(context.TODO(), types.NamespacedName{Name: instance.Name, Namespace: instance.Namespace}, service)
```

*NOTE:* The filter to check is defined in `types.NamespacedName{Name: instance.Name, Namespace: instance.Namespace},`.

Now, if you would like to get ALL pods, I mean a list of pods then you need to use the func List instead of Get. 

```go
reqLogger.Info("Checking if the pod already exists")
	pods := []&corev1.POD{}
	err := r.client.List(context.TODO(), <ListOptions>, pods)
```

See it impl.

```go
// List retrieves list of objects for a given namespace and list options. On a
	// successful call, Items field in the list will be populated with the
	// result returned from the server.
	List(ctx context.Context, opts *ListOptions, list runtime.Object) error

```

In the reconcile after creating the resources you can do fetches and update the status.  Please, feel free to check the project in development as an example https://github.com/aerogear/mobile-security-service-operator.

I hope that it helps you.

**Comment by cmoulliard** [comment]
So, the strategy that you propose to use is then to `r.client.list` all the watched resources in order to find those having the label corresponding to the condition that you want to match

That means that if the controller, base on the CR definition, will create a Pod, Service, Deployment, ... or any kind of k8s combinations, then you will create a function to list each resource and check if it contains a matching for the condition.

The alternative is to query the resources or all the resources as k8s.io  `cli-runtime` project proposes
```
func (r *Reconciledatabase) Query(selector, ns, resources string) ([] *resource.Info, error) {
	resp := r.Config().builder.
		Unstructured().
		NamespaceParam(ns).
		ResourceTypeOrNameArgs(true, resources).
		LabelSelector(selector).
		Latest().
		Flatten().
		Do()

	infos, err := resp.Infos()
	if err != nil {
		return nil, err
	}

	return infos, nil
}
```
 but without fetching the resources from the internal cache of the controller-runtime - correct ?

**Comment by camilamacedo86** [comment]
Hi @cmoulliard,

I do not think that the client will featch in the internal cache. I understand that it is the client-go command which will do the same that you do when you run ` kubectl get pods`. The idea here with operators is you be able to automate the "operations", so instead of you run the commands in the command line you will use the same ks8 API that is used by the command in your project by the code implementation. 

I hope that it answered your question.

**Comment by cmoulliard** [comment]
Many thanks for your suggestion @camilamacedo86. I like the idea and approach even if it is needed to register each resource to watch (and maybe to filter them using a label selector) [1]
vs having a Query function able to fetch all the resources as we can do with k8s cli runtimes [2] used by kubectl, oc 

Question: Is there an advantage to use `c.Watch(` instead of fetching all the resources as I did with another client (e.g cli-runtime) ?

[1] https://github.com/aerogear/mobile-security-service-operator/blob/master/pkg/controller/mobilesecurityservice/controller.go#L52-L72
[2] https://github.com/kubernetes/cli-runtime

**Comment by camilamacedo86** [comment]
HI @cmoulliard,

I am really happy that it was helpful. Following the following approach in my understanding has significant advantages.  

Approach example:

```
        // Watch resources with thee KIND = ConfigMAP AND Controlled by the Operator AND OwnerType = KIND 
	err := c.Watch(&source.Kind{Type: &corev1.ConfigMap{}}, &handler.EnqueueRequestForOwner{
		IsController: true, 
		OwnerType:    &mobilesecurityservicev1alpha1.MobileSecurityServiceApp{},
	})

```
NOTE: I understand that "IsController" == true will make it looks into the cache which has just the objects/resources managed by the operator which will make it more performative.
 
```
        //Search for the ConfigMap in the nampesce X with the name Y which the KIND is from the Operator and controlled by it. 
	configMap := &corev1.ConfigMap{}
	err := r.client.Get(context.TODO(), types.NamespacedName{Name: getSDKConfigMapName(instance), Namespace: instance.Namespace}, configMap)
```

Advantages:

- It is following as it's examples/docs[3] and ks8 code docs, for example[4]. 
- Specify one watch and fetch for each resource can bring performance since it will be like  SELECT "SpecificResource" FROM NAMESPACE = {{NAMESPACE}} WHERE KIND = {{KIND}} 
- It makes easily understand the code and keep it maintained.

**Comment by camilamacedo86** [comment]
HI @cmoulliard, 

I think your question raised here was answered. So, could you please close this issue and/or let us know what still missing here for we are able to do it. 

Cheers

**Comment by cmoulliard** [comment]
We can close it as this feature is not longer required

**Comment by aravinder111** [comment]
Hi @camilamacedo86, do you see Ansible operator managing a specific k8s resource ? I can do it in GO, but ansible operator `watches.yaml` doesn't provide a way to watch for example a specific configmap ?

**Comment by Hats-Wang** [comment]
> HI @cmoulliard,
> 
> I am really happy that it was helpful.
> 
> Following the following approach in my understanding has significant advantages.
> 
> ### Approach example:
> ```go
>         // Watch resources with thee KIND = ConfigMAP AND Controlled by the Operator AND OwnerType = KIND 
> 	err := c.Watch(&source.Kind{Type: &corev1.ConfigMap{}}, &handler.EnqueueRequestForOwner{
> 		IsController: true, 
> 		OwnerType:    &mobilesecurityservicev1alpha1.MobileSecurityServiceApp{},
> 	})
> ```
> 
> ```go
>         //Search for the ConfigMap in the nampesce X with the name Y which the KIND is from the Operator and controlled by it. 
> 	configMap := &corev1.ConfigMap{}
> 	err := r.client.Get(context.TODO(), types.NamespacedName{Name: getSDKConfigMapName(instance), Namespace: instance.Namespace}, configMap)
> ```
> 
> **NOTE:** I understand that "IsController" == true will make it looks into the cache which has just the objects/resources managed by the operator which will make it more performative. The cache of the manager is defined in the main.go in the following code line, for example, and by default, it will be evicted every 10 hours. See [here](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/manager.go#L102)
> 
> ```go
> // Create a new Cmd to provide shared dependencies and start components
> 	mgr, err := manager.New(cfg, manager.Options{
> 		Namespace:          "",
> 	})
> ```
> 
> Ref.: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/manager.go#L122
> 
> ### Advantages:
> * It is following it's [examples/docs](https://github.com/operator-framework/getting-started#resources-watched-by-the-controller)
> * Specify one watch and fetch for each resource can bring performance since it will be like  SELECT "SpecificResource" FROM NAMESPACE = {{NAMESPACE}} WHERE KIND = {{KIND}}
> * It makes easily understand the code and keep it maintained.

I don't understand the approach how to create cache you wrote here. 
I watch a second resource, but when I delete the second resource, the recouncil func would not be called automatically. 

> HI @cmoulliard,
> 
> I am really happy that it was helpful.
> 
> Following the following approach in my understanding has significant advantages.
> 
> ### Approach example:
> ```go
>         // Watch resources with thee KIND = ConfigMAP AND Controlled by the Operator AND OwnerType = KIND 
> 	err := c.Watch(&source.Kind{Type: &corev1.ConfigMap{}}, &handler.EnqueueRequestForOwner{
> 		IsController: true, 
> 		OwnerType:    &mobilesecurityservicev1alpha1.MobileSecurityServiceApp{},
> 	})
> ```
> 
> ```go
>         //Search for the ConfigMap in the nampesce X with the name Y which the KIND is from the Operator and controlled by it. 
> 	configMap := &corev1.ConfigMap{}
> 	err := r.client.Get(context.TODO(), types.NamespacedName{Name: getSDKConfigMapName(instance), Namespace: instance.Namespace}, configMap)
> ```
> 
> **NOTE:** I understand that "IsController" == true will make it looks into the cache which has just the objects/resources managed by the operator which will make it more performative. The cache of the manager is defined in the main.go in the following code line, for example, and by default, it will be evicted every 10 hours. See [here](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/manager.go#L102)
> 
> ```go
> // Create a new Cmd to provide shared dependencies and start components
> 	mgr, err := manager.New(cfg, manager.Options{
> 		Namespace:          "",
> 	})
> ```
> 
> Ref.: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/manager.go#L122
> 
> ### Advantages:
> * It is following it's [examples/docs](https://github.com/operator-framework/getting-started#resources-watched-by-the-controller)
> * Specify one watch and fetch for each resource can bring performance since it will be like  SELECT "SpecificResource" FROM NAMESPACE = {{NAMESPACE}} WHERE KIND = {{KIND}}
> * It makes easily understand the code and keep it maintained.

I use the same approach to watch second resources in operator-sdk v0.19, but when I delete a second resource instace using ”kubectl delete“, the recouncil func woundn't be called.  Generally speaking, where is the most likely problem? If you have available time, here is the code https://github.com/Hats-Wang/ChubaoMonitorOperator/blob/59343b3f8793b18e23841516a020abf94690f476/controllers/chubaomonitor_controller.go#L507.
