### ISSUE TITLE
Generating tests from `operator-sdk generate`

### ISSUE THREAD

**Issue by briantopping** [operator-framework/operator-sdk#1355]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When using `operator-sdk generate`, I would ideally like to have had the build also create minimal tests. Ideally, it could run e2e as well. 

**Describe the solution you'd like**
[This document](https://kubernetes.io/blog/2019/03/22/kubernetes-end-to-end-testing-for-everyone/) seems to be quite current and I'm going to implement the tests for my controller this way, mostly because TDD is much faster when the cost to bring up a test environment is high. It would also help lower the bar for fully tested operators, so hopefully more of them would emerge into the community that way.

**Comment by LiliC** [comment]
Just so we are clear @briantopping so you want a generate command to generate e2e tests for your operator? 

We have the e2e framework already in operator SDK https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/writing-e2e-tests.md

We also have the `operator-sdk test` command to run the e2e tests.

**Comment by briantopping** [comment]
The thought was that it’s easy to template skeleton tests when the skeletons don’t do much. It’s a good start for good habits and makes it easier to document a TDD lifecycle. There’s reasons to do it and also not to do it... :)

**Comment by LiliC** [comment]
cc @AlexNPavel
