### ISSUE TITLE
Update migration guide

### ISSUE THREAD

**Issue by LiliC** [operator-framework/operator-sdk#1359]
The [guide](https://github.com/operator-framework/operator-sdk/blob/51d28df214440d97031368d7d700a2805161015d/doc/migration/v0.1.0-migration-guide.md) for migrating from v0.0.x to v0.1.0, needs to be updated to reflect any additional changes that may have happened since the `0.1.0` release. Afterward, we should update the title to something like `Migration Guide from v0.0.x to v0.x.0`. The motivation for this is that users who decide to migrate their existing projects from 0.0.x will choose the latest release.

Maybe we should add a note to the release steps to double check anything major changed and reflect that in the migration guide.

**Comment by hasbro17** [comment]
With #1833 and #1891 we now have a [version upgrade guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md) now for post `v0.1.0` upgrades that don't require an actual migration.
