### ISSUE TITLE
Can gen-csv update the WATCH_NAMESPACE downward api destination?

### ISSUE THREAD

**Issue by jcrossley3** [operator-framework/operator-sdk#1360]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
operator-sdk

## Question

**What did you do?**
The `gen-csv` task seems to copy the `deploy/operator.yaml` whole into the generated CSV, but the `metadata.namespace` value for `WATCH_NAMESPACE` may not be correct for the CSV.

**What did you expect to see?**
I expected the value to be changed to `metadata.annotations['olm.targetNamespaces']` per the OLM docs.

**What did you see instead? Under which circumstances?**
It retained its `metadata.namespace` value, which is only correct when `operator.yaml` is deployed outside of OLM

**Environment**
* operator-sdk version:

  0.7.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: minikube

**Comment by LiliC** [comment]
cc @estroz

**Comment by estroz** [comment]
@jcrossley3 @LiliC PR open: #1396
