### ISSUE TITLE
How to get the hostname by a project/operator which is running in the cluster? 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1362]
## Type of question

Usage

## Question

**What did you do?**
In a golang operator project, I'd like to get the hostname which is returned by the command  `kubectl cluster-info` for example.

```
$ kubectl cluster-info
Kubernetes master is running at https://192.168.64.19:8443
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

The following works when the project is executed out of the cluster by the tool operator-sdk by the command `operator-sdk up local --namespace={{namespace}}` but not when the operator is running in the cluster.

* If it is running in a cluster the os.Getenv("KUBERNETES_SERVICE_HOST") has a value which is returned here and is not the value expected. ("https://172.30.0.1:443")

* When run locally, "outside of the cluster" the  KUBERNETES_SERVICE_HOST is empty and the value expected is returned. ("https://192.168.64.19:8443")

Following the code.
```go
func getClusterProtocol() string {
	cfg, _:= config.GetConfig()
	cfgHost := cfg.Host
	cfgHost = strings.Replace(cfgHost, "//", "", 2)
	host := strings.Split(cfgHost, ":")

	return host[0]
}


func getHostIP() string {
	cfg, _:= config.GetConfig()
	cfgHost := cfg.Host
	cfgHost = strings.Replace(cfgHost, "//", "", 2)
	host := strings.Split(cfgHost, ":")

	return host[1]
}
```
 
The same behaviour happened if we try to use the func `rest.InClusterConfig()` as follows.

```go
func getClusterProtocol() string {
	cfg, _:= rest.InClusterConfig()
	cfgHost := cfg.Host
	cfgHost = strings.Replace(cfgHost, "//", "", 2)
	host := strings.Split(cfgHost, ":")
	log.Info("Utils - ConfigHost", cfg.Host)
	return host[0]
}


func getHostIP() string {
	cfg, _:= rest.InClusterConfig()
	cfgHost := cfg.Host
	cfgHost = strings.Replace(cfgHost, "//", "", 2)
	host := strings.Split(cfgHost, ":")
	log.Info("Utils - ConfigHost", cfg.Host)

	return host[1]
}
```

**What did you expect to see?**

The cluster hostname/master url. 

**What did you see instead? Under which circumstances?**

* If it is running in a cluster the os.Getenv("KUBERNETES_SERVICE_HOST") has a value which is returned here and is not the value expected. ("https://172.30.0.1:443")

**Environment**
* operator-sdk version:

` operator-sdk version v0.5.0+git`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-04-16T17:19:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

I thought that it is more related to the ks8 so I opened the question there. However, you can help me with this answer folks. Following the link.

https://github.com/kubernetes/client-go/issues/600

NOTE: My goal is to get the hostname where the operator is running by the code implementation/runtime.

**Comment by shawn-hurley** [comment]
I think you may be able to use the kubeconfig.

You can get the [kubeconfig](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client/config) and then use [it](https://godoc.org/k8s.io/client-go/rest#Config) to get the k8s hostname?

I have not tried this, and I don't know how perfect it will work in the cluster but this might be a place to look?

**Comment by camilamacedo86** [comment]
@shawn-hurley  thanks but I understand that it is what I am doing above. If the project is running outside of the cluster works because of the os.Getenv("KUBERNETES_SERVICE_HOST") is null. However, when it is in the mind shift/cluster has a value and it is not working well as I expected.

**Comment by joelanford** [comment]
@camilamacedo86 I'm not sure this is possible. 

When running outside the cluster, `kubectl cluster-info` and other clients use the `cluster.server` value in your `$KUBECONFIG`. This typically uses a host name or IP that is routable to the cluster API server from outside the cluster.

When running inside the cluster, clients use the `$KUBERNETES_SERVICE_HOST` environment variable, which comes from the `kubernetes.default.svc` service. This host/IP is typically only routable inside the cluster.

Is your operator having an issue connecting to the API server when running in-cluster?

**Comment by camilamacedo86** [comment]
Hi @joelanford,

Thank you for your detailed explanation. It is not facing any issue. I was just looking for a way to create an ingress resource in runtime which requires the HOST without the need to spec it. 

Anyway, we will not able to use ingress since our project requires oauth proxy authentication. So this need also is no longer required. However, it is great to confirm the understanding and get this detailed info. 

Again really tks for your help. I am closing it.
