### ISSUE TITLE
Is possible to get objects/resources created by the kind A in the controller of kind B? 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1363]
## Type of question

Usage

## Question

**What did you do?**
Is possible to get objects/resources created by the kind A in the controller of kind B? 

**What did you expect to see?**

When I have an operator project with more than one kind and controllers for each kind as this project I'd like to be able to fetch/get the resources created and managed for one kind in a controller of another kind. 

Following an example:

* We have the KIND A and its controller which creates a pod
* From the controller/reconcile of the KIND B  I'd like to get the Pod created by the KIND A and its reconcile. 

IMPORTANT: the KIND A and B are not in the same namespace. 

**What did you see instead? Under which circumstances?**

When I tried to do it I cannot find/fetch/GET the object/resource created from the other KIND/Controller. It is not returned in the fetch. 

**Environment**
* operator-sdk version:

` operator-sdk version v0.5.0+git`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-04-16T17:19:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

In order to clarify maybe can be easier if you see our project https://github.com/aerogear/mobile-security-service-operator. I'd like from the [APP - controller.go](https://github.com/aerogear/mobile-security-service-operator/blob/master/pkg/controller/mobilesecurityserviceapp/controller.go) get an object created in the [MSS - controller.go](https://github.com/aerogear/mobile-security-service-operator/blob/master/pkg/controller/mobilesecurityservice/controller.go#L158)

**Comment by shawn-hurley** [comment]
Hi @camilamacedo86,

Can you past the code that you used?

This should work:

```
mss := &mobilesecurityservicev1alpha1.MobileSecurityService{}
key := types.NamespacedName{Namespace: "<namespace of the MSS you want>", Name: "<name of the mss you want>"}
err := r.client.Get(context.TODO(), key, mss)
```

Let me know if I can help further.

**Comment by camilamacedo86** [comment]
Are you sure that it should work? I tried exactly the same and the mss in your example is nil. :-(
