### ISSUE TITLE
How to add the route ocp scheme? Error "no kind is registered for the type v1.Route in scheme" is faced when the user guide is followed

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1365]
## Type of question

Operator-sdk usage

## Question

**What did you do?**
Add the route scheme to the project. 

* Add the dep `dep ensure -add github.com/openshift/api`
* Add in the main.go as described in the user guide https://github.com/operator-framework/operator-sdk/blob/c3a77eee021a1cc6a31861a0efd253dc23fbe591/doc/user-guide.md#register-with-the-managers-scheme.
  
```go
        //Import
	routev1 "github.com/openshift/api/route/v1"

	//Add route scheme
	if err := routev1.AddToScheme(mgr.GetScheme()); err != nil {
		log.Error(err, "")
		os.Exit(1)
	}
```
PS.: The AddToScheme is deprecated. Should we really do it in this way?

**What did you expect to see?**
Following the [user guide](https://github.com/operator-framework/operator-sdk/blob/c3a77eee021a1cc6a31861a0efd253dc23fbe591/doc/user-guide.md#register-with-the-managers-scheme ) and check that it works.

**What did you see instead? Under which circumstances?**
The following error is faced when I try to run the operator.

```shell
INFO[0000] Running the operator locally.                
INFO[0000] Using namespace mobile-security-service-operator. 
{"level":"info","ts":1556697594.0715148,"logger":"cmd","msg":"Go Version: go1.11.5"}
{"level":"info","ts":1556697594.0715861,"logger":"cmd","msg":"Go OS/Arch: darwin/amd64"}
{"level":"info","ts":1556697594.071598,"logger":"cmd","msg":"Version of operator-sdk: v0.7.0"}
{"level":"info","ts":1556697594.077124,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1556697594.0771892,"logger":"leader","msg":"Skipping leader election; not running in a cluster."}
{"level":"info","ts":1556697594.130168,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1556697594.1305962,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"mobilesecurityservice-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1556697594.13086,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"mobilesecurityservice-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1556697594.130964,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"mobilesecurityservice-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1556697594.1310878,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"mobilesecurityservice-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1556697594.131196,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"mobilesecurityservice-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1556697594.1312199,"logger":"cmd","msg":"","error":"no kind is registered for the type v1.Route in scheme \"k8s.io/client-go/kubernetes/scheme/register.go:61\"","stacktrace":"github.com/aerogear/mobile-security-service-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/camilamacedo/go/src/github.com/aerogear/mobile-security-service-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/Users/camilamacedo/go/src/github.com/aerogear/mobile-security-service-operator/cmd/manager/main.go:96\nruntime.main\n\t/usr/local/Cellar/go/1.11.5/libexec/src/runtime/proc.go:201"}
Error: failed to run operator locally: (failed to exec []string{"build/_output/bin/mobile-security-service-operator-local"}: exit status 1)

```

**Environment**
* operator-sdk version:
Version of operator-sdk: v0.7.0
  
* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-04-22T23:30:51Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: minishift

**Additional context**

Also, I tried to follow https://github.com/operator-framework/operator-sdk/issues/477 by using the following impl.

```go
	//Add route type since it is from Openshift and not kubernetes
	k8sutil.AddToSDKScheme(routev1.Install)
```
However, the AddToSDKScheme is no longer part of https://github.com/operator-framework/operator-sdk/blob/master/pkg/k8sutil/k8sutil.go

**Comment by camilamacedo86** [comment]
@lisa @jfchevrette @jcrossley3 @jmrodri

**Comment by shawn-hurley** [comment]
> PS.: The AddToScheme is deprecated. Should we really do it in this way?

AddToScheme is not deprecated as a mechanism, it appears openshift/api would prefer you use `Install` which is the same thing under the hood. This mechanism is the correct thing to do. 

Where are you registering the scheme?

**Comment by camilamacedo86** [comment]
Hi @shawn-hurley,

Note that I am doing exactly like the guide and I am facing the issue(you can check the details above). Another way that I found to do it is in #477, however, the func `k8sutil.AddToSDKScheme` no longer exist. Please, could you help me?

**Comment by shawn-hurley** [comment]
Ok, don't follow 477 that is old. 

Can you link me to the code?

**Comment by camilamacedo86** [comment]
Hi @shawn-hurley really tks for the help!!! ++++++++@shawn-hurley

The issue was because I was adding the Route scheme after the setup the controller. The following solution is working perfectly well. 

```go
	// Setup Scheme for all resources
	if err := apis.AddToScheme(mgr.GetScheme()); err != nil {
		log.Error(err, "")
		os.Exit(1)
	}

	//Add route scheme
	if err := routev1.AddToScheme(mgr.GetScheme()); err != nil {
		log.Error(err, "")
		os.Exit(1)
	}

	// Setup all Controllers
	if err := controller.AddToManager(mgr); err != nil {
		log.Error(err, "")
		os.Exit(1)
	}
```

**Comment by camilamacedo86** [comment]
@shawn-hurley done the pr for the docs as requested. See:https://github.com/operator-framework/operator-sdk/pull/1387
