### ISSUE TITLE
Operator sdk, Prometheus and Kafka

### ISSUE THREAD

**Issue by spanichellazhaw** [operator-framework/operator-sdk#1372]
## Type of question

** both implement a specific feature and  general context of operator-sdk **

## Question

**What did you do?**

My goal is to detecting patterns, anomalies and incidents in Kubernetes applications.
Thus, I played with operator SDK examples https://github.com/operator-framework/operator-sdk
I'm currently trying to use Kafka and Prometheus with minishift (using the following guideline https://strimzi.io/docs/0.4.0/#_getting_started).

**What did you expect to see?**

All fine while using operators. Still need to have a better look at how to use Kafka and Prometheus with minishift.

**What did you see instead? Under which circumstances?**

All fine while using operators. Still need to have a better look at how to use Kafka and Prometheus with minishift.
**Environment**
* operator-sdk version:

operator-sdk version: v0.7.0+git

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-05-01T23:53:16Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

**Additional context**

As described above, My goal is to detecting patterns, anomalies and incidents in Kubernetes applications.
In discrete event processing systems, operators react on events to perform an action, often based on additional context-dependent rules. I would like to implement a services that provides the rules and context information whereas the attached monitoring provides the events.  The requirement for the operator instantiation I envision is clear supported annotations which customers can insert into their deployment descriptors. 

My question is, does it make sense to combine operator sdk and Prometheus for 
detecting patterns, anomalies and incidents in Kubernetes applications?
Ideally, prometheus + Kafka can provide a lot of information on what happen to the system, while the operator could observe such metrics and information in particular files (or annotations) and make specific actions in particular conditions.

Not sure if my question is clear or not. I can try to be more specific, but I'm looking to feedback on how to proceed.

**Comment by LiliC** [comment]
hi @spanichellazhaw, so if I understand correctly, you want to build an operator that "detects patterns, anomalies and incidents in Kubernetes applications"?

**Comment by panichella** [comment]
Yes. However, I would start with a very simple example in the first place. 

One idea I had in mind is trying to monitor some metrics with Prometheus and use operators to make some simple decision making. E.g., annotate some files or resources with operators, gather information with Prometheus, then in case a certain Prometheus metrics go lower than a certain threshold make some decision with operators.

I was wondering if this process makes sense with an operator in general.

**Comment by LiliC** [comment]
@panichella an operator is a custom controller that holds the knowledge of an application and it reconciles to the desired state. I guess it really depends on what those decisions are, are they there to influence k8s resources and reconcile, then yes I would say you are building an operator. But if they are there to just inform the user, I would say just leverage the k8s api and you don't need the reconcile loop or controller, but simple application that you deploy in the k8s cluster (or outside even). Are you familiar with https://freshtracks.io/
