### ISSUE TITLE
Multiple CRD & CRs for 1 controller

### ISSUE THREAD

**Issue by mossuchida** [operator-framework/operator-sdk#1383]
I want to create a microservice operator using single controller (I would like to group each apps in different files as files get huge & confusing. also, hard to create nested specs in type.go file).  I don't want to create different controllers for each services as they need to be coordinated by single controller.

I have created multiple CRDs & CRs using commands:
operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=App1
operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=App2

Then I wanted to mange then using single controller, but I have issue with the following:
instance := &appv1alpha1.App1{}
instance := &appv1alpha1.App2{}
App1 works well, but App2 search fails here that it cannot find it (it seems like it is searching with App1 CR name)
r.client.Get(context.TODO(), types.NamespacedName{Name: app2.Name, Namespace: app2.Namespace}, app2resourcedef)

I tried with 2 clients, but it still doesn't work.
r.client1.Get(context.TODO(), types.NamespacedName{Name: app1.Name, Namespace: app1.Namespace}, app1resourcedef)
r.client2.Get(context.TODO(), types.NamespacedName{Name: app2.Name, Namespace: app2.Namespace}, app2resourcedef)

Is it possible to have multiple CRDs & CRs & types to be managed by a single controller?

**Comment by shawn-hurley** [comment]
I think this is explicitly against the design goals for the controller-runtime. 

Could you explain further what your trying to do and I could help come up with an alternative implementation?

**Comment by mossuchida** [comment]
ok, I wanted to know if it was possible or designed this way. I will figure out other way then. thanks!

**Comment by camilamacedo86** [comment]
@mossuchida,

I'd like to share that you can use/call the type/instance A in controller B if required. See [here](https://github.com/aerogear/mobile-security-service-operator/blob/master/pkg/controller/mobilesecurityserviceapp/controller.go#L133) for example we doing it. I hope that it can be helpful for you.

**Comment by nmarcetic** [comment]
@camilamacedo86 I am also looking for an example of how to create an operator for microservice oriented architecture. Do you have any refs? For example, there is a system that contains like 10 microservices (most of them are loosely coupled, but there is some tightly coupled or dependencies like service A depend on the database, service B on cache, etc...), what would be the way to go? I must create CRD and controllers for each service or?  Do you have any example or documentation that I can check? Everything I found so far si basic examples... like Memcache operator. Thanks!

**Comment by camilamacedo86** [comment]
Hi @nmarcetic, 

I believe that the comment https://github.com/operator-framework/operator-sdk/issues/2151#issuecomment-549574954 provides the info that you are looking for with example. Also, see that to manage dependency between operators you can use the [Dependency Resolution from OLM](https://github.com/operator-framework/operator-lifecycle-manager#dependency-resolution). However, if you still requiring a help could you please raise a new issue?

**Comment by nmarcetic** [comment]
Thank you @camilamacedo86 

Yes, referenced comment provides the answer I was looking for. I still think we miss more complex, let's say real-life examples :) and that doc is more focused on theoretical concepts, then practical. So I will open a new issue and try to explain what I am looking for. Thanks!
