### ISSUE TITLE
operator-sdk generate k8s failed with no meaningful error

### ISSUE THREAD

**Issue by siddontang** [operator-framework/operator-sdk#1391]
## Bug Report

**What did you do?**

Follow https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md to run the generate subcommand

```
operator-sdk generate k8s --header-file hack/boilerplate.go.txt
```

**What did you expect to see?**

Run ok

**What did you see instead? Under which circumstances?**

Failed, but no meaningful error, I don't why.

```
Error: exit status 2
Usage:
  operator-sdk generate k8s [flags]

Flags:
      --header-file string   Path to file containing headers for generated files.
  -h, --help                 help for k8s
```

**Environment**
* operator-sdk version:

version v0.7.0

* go version:

go version go1.12.4 darwin/amd64

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2+coreos.0", GitCommit:"211703c179e2f3b8c6aa10e232a3f3363786ff5b", GitTreeState:"clean", BuildDate:"2018-04-30T18:07:20Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

Go

**Comment by hasbro17** [comment]
@siddontang Again couldn't reproduce this but I think this might be related to your issue in #1389 
Did you manage to find a fix for that? If not then we should probably fix that first before moving on to this.
Either way we can probably consolidate both these issues together.

And similar to https://github.com/operator-framework/operator-sdk/issues/1389#issuecomment-489767987 if you could confirm that you have this issue against then master branch then we can hopefully narrow it down.
