### ISSUE TITLE
Generate Kustomization file in /deploy

### ISSUE THREAD

**Issue by fentas** [operator-framework/operator-sdk#1393]
## Feature Request
First of all, thanks for your awesome work. :+1:
This is the first time I get in touch with `operator-sdk`, so if there is a better way let me know.

Instead of generating deploy yaml files with lots of placeholder like `REPLACE_*` I would love to see one env file (defining all required fields) which will be used by `kustomize` to generate a ConfigMap which is used as a variable reference. These variables (e.g. `$(SDK_NAMESPACE)`) are used instead of placeholders.

And as `kustomize` is already included within `kubectl` this would be really convenient.

**Comment by joelanford** [comment]
My two cents, this is something [kubebuilder is already using](https://book.kubebuilder.io/beyond_basics/deploying_controller.html#customizing-the-controller-manager-manifests-using-kustomize), and I think it could be pretty useful to incorporate into the SDK.

One minor concern is that we would need to add a new dependency on `kustomize`, bump our `kubectl` dependency to 1.14.x, or vendor `kustomize` into the SDK or SDK projects.

If other maintainers agree that this is a good idea, the next step would be to draft a proposal to describe the details of the design and implementation. We would also need to come up with a plan for how to migrate existing projects to use the the `kustomize` functionality.

@hasbro17 @shawn-hurley @estroz @LiliC @AlexNPavel @theishshah, thoughts?

**Comment by LiliC** [comment]
@joelanford agreed it would be something nice to have, especially since kustomize is already part of kubectl! My only fear is when do we stop, which ways do we expect and which we reject. We have OLM for obvious reasons, and yaml as that is the default option. But if someone wants jssonet do we want to support that? 

@fentas would this be something you would be interested in working, no worries if not. If yes, we have a guide on how to submit a new proposal -> https://github.com/operator-framework/operator-sdk/tree/master/doc/proposals

**Comment by fentas** [comment]
Would love to but atm I am quite busy creating an operator. :+1:

**Comment by hasbro17** [comment]
This issue should be resolved once the SDK integrates Kubebuilder and we switch over to using Kustomize per the Kubebuilder workflow for updating manifest configurations.
See: https://github.com/operator-framework/operator-sdk/blob/master/doc/proposals/kubebuilder-integration.md

**Comment by camilamacedo86** [comment]
After 0.19 SDK release, the new projects created with the tool will be configured via kustomize be the default. In this way, I am closing this one as sorted out.
