### ISSUE TITLE
Release process: use latest release and links

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-sdk#1398]
It would be nice to use the [latest release link](https://help.github.com/en/articles/linking-to-releases#linking-to-the-latest-release) so that we don't have to update the install doc every time we make a release.

To use that, I think we would need to stop using the "This is a pre-release" checkbox when we create a new release, and we would need to stop including the version number in the release binaries that we post to the releases page.

**Comment by LiliC** [comment]
This was done in #1395

**Comment by joelanford** [comment]
While #1395 was a great step forward, my intent with this issue was to look at whether our install doc could have a static link that always points to our latest release in GitHub. Something like:

https://github.com/operator-framework/operator-sdk/releases/download/latest/operator-sdk-x86_64-linux-gnu

Having a static link would mean one less thing to update a version number in, and it would make it easier for users/scripts to get the most recent version.

**Comment by camilamacedo86** [comment]
Have we not a JIRA for it as well?
