### ISSUE TITLE
Multiple image builder options

### ISSUE THREAD

**Issue by radu-matei** [operator-framework/operator-sdk#1399]
Hi, everyone!
First of all, thanks for the awesome work put into this project!

Is it in the scope of this project to support multiple image builder options?
I'm thinking specifically at using various cloud-provided container builders, for cases when running in containerized environments (so running `buildah` is not straightforward, and neither is any form of Docker in Docker), or simply don't want to run Docker / `buildah` locally.

In these cases, you could use the CLI for both [Azure](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-quick-task#build-in-azure-with-acr-tasks) and [GCP](https://cloud.google.com/cloud-build/docs/quickstart-docker#build_using_dockerfile).

That being said, I have a branch that uses `az acr build` to build the image using the Azure CLI - it's [another case in the switch statement for the image builder](https://github.com/operator-framework/operator-sdk/blob/master/cmd/operator-sdk/build/cmd.go#L148), and I assume the same can be done for other builders as well.

Let me know if this is of interest, and I can create a PR for it.
Thanks!

**Comment by LiliC** [comment]
@radu-matei Thanks for the feature request, if you are interested you can write up a quick proposal to provide more details on this? https://github.com/operator-framework/operator-sdk/tree/master/doc/proposals
