### ISSUE TITLE
Allow configuration of the number of informer workers

### ISSUE THREAD

**Issue by mikewied** [operator-framework/operator-sdk#140]
Currently the number of workers in the informer is hardcoded to 1. Being able to set this number higher will allow operator to process multiple CRD updates at once. This will help the operator be more responsive when it is managing a large number of CRD's.

Note: I think 1 is definitely the right default.

**Comment by ib-steffen** [comment]
is there any reason why it has to be 1 at the moment? It seem that our operator is currently limited by this, because we manage want to mange many CRs at the same time. In our case we also create/delete them all the time, so there's really quite some work to do be done by the operator.

**Comment by theishshah** [comment]
Number of Workers is now configurable!
