### ISSUE TITLE
ansible operator does not support multiple inventories

### ISSUE THREAD

**Issue by willthames** [operator-framework/operator-sdk#1405]
## Bug Report

**What did you do?**
Set ANSIBLE_INVENTORY to `/opt/ansible/inventory,/applications/docker-debug/docker-debug/inventory,/applications/kuard/kuard/inventory`

**What did you expect to see?**
Ansible operator passing the inventory value on to ansible-runner without complaint

**What did you see instead? Under which circumstances?**

```
{
  "level": "error",
  "ts": 1557141565.9710336,
  "logger": "kubebuilder.controller",
  "msg": "Reconciler error",
  "controller": "consolidation-controller",
  "request": "test/test-application-operator",
  "error": "stat /opt/ansible/inventory,/applications/docker-debug/docker-debug/inventory,/applications/kuard/kuard/inventory: no such file or directory",
  "stacktrace": "github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsrc/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tsrc/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"
}
```

**Environment**
* operator-sdk version:

0.7.0

* go version:

No idea, I used the quay.io image

* Kubernetes version information:
`Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: docker-for-desktop

* Are you writing your operator in ansible, helm, or go?
Ansible

**Possible Solution**
Just let ansible-runner worry about the inventory handling

**Additional context**

To be honest, I'm not convinced ansible-runner will handle this any better, but it's a valid use case and it probably needs to be solved at both ends

**Comment by willthames** [comment]
https://github.com/ansible/ansible-runner/issues/296 is the corresponding ansible-runner issue. 

As it stands, I think you'd need to do the split and pass each item with `--inventory` but it'd be nice if ansible-runner handled ANSIBLE_INVENTORY and/or inventory in ansible.cfg, and the operator only checking inventory if it was explicitly set.

**Comment by fabianvf** [comment]
@willthames did the fix in ansible-runner fix this or are you still waiting on changes in the operator-sdk?
