### ISSUE TITLE
Build error following doc/user-guide.md or README.md, with go modules

### ISSUE THREAD

**Issue by syedriko** [operator-framework/operator-sdk#1409]
## Bug Report

**What did you do?**
Followed doc/user-guide.md, with go modules, to the point of
```
$operator-sdk build quay.io/example/memcached-operator:v0.0.1
```

**What did you expect to see?**
quay.io/example/memcached-operator:v0.0.1 docker image is built

**What did you see instead? Under which circumstances?**
```
[foo@localhost memcached-operator]$ operator-sdk build quay.io/example/memcached-operator:v0.0.1
build github.com/example-inc/memcached-operator/cmd/manager: cannot load sigs.k8s.io/controller-runtime/pkg/controller: open /home/syedriko/go/src/github.com/example-inc/memcached-operator/vendor/sigs.k8s.io/controller-runtime/pkg/controller: no such file or directory
Error: failed to build operator binary: (failed to exec []string{"go", "build", "-o", "/home/syedriko/go/src/github.com/example-inc/memcached-operator/build/_output/bin/memcached-operator", "-gcflags", "all=-trimpath=${GOPATH}", "-asmflags", "all=-trimpath=${GOPATH}", "-mod=vendor", "github.com/example-inc/memcached-operator/cmd/manager"}: exit status 1)
```

**Environment**

OOTB Fedora 30

* operator-sdk version:

operator-sdk version: v0.7.0+git
the current HEAD of https://github.com/operator-framework/operator-sdk as of 2019/05/10

* go version:

go version go1.12.1 linux/amd64

* Kubernetes version information:

n/a

* Kubernetes cluster kind: 

n/a

* Are you writing your operator in ansible, helm, or go?

go

**Possible Solution**
A workaround is to run "go mod vendor -v" just before "operator-sdk build quay.io/example/memcached-operator:v0.0.1".
I've root-caused it to the fact that 
"go mod vendor -v" that "operator-sdk new memcached-operator" runs, only includes vendor packages actually imported from the project's source code at the time "go mod vendor" runs. At that stage, there's no pkg/controller/memcached/memcached_controller.go file in the project, which is the only one that imports 
```
	"sigs.k8s.io/controller-runtime/pkg/controller"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
```
so they are not present in the vendored controller-runtime.

**Comment by LiliC** [comment]
@syedriko yes I believe we mention the need to rerun `go mod vendor` in the docs.

cc @estroz

**Comment by syedriko** [comment]
There's indeed a mention of it in the Advanced Topics of the user-guide.md. But look at this from the first timer perspective. I, for one, did not know go modules existed until I started working through the user guide.

I followed the "Get started with the SDK" link on https://www.openshift.com/learn/topics/operators and worked through the guide step-by-step and ran into the issue I'm reporting.

In the "Create and deploy an app-operator using the SDK CLI:" section of README.md, there's no mention of "go mod vendor" and just running the commands from there by copy-paste fails at the "operator-sdk build quay.io/example/app-operator" step.

Since the operator-sdk tool wraps "go mod vendor" in the "operator-sdk new" command, may be "operator-sdk build" should invoke it too, before running "go build"?

**Comment by joelanford** [comment]
@syedriko thanks for pointing this out. We just merged the go modules support yesterday, so with such a big change, there are likely still some rough edges (like this one). 

Since go modules make the `vendor` directory less necessary, we plan to make a follow-up change that only invokes the `go` command with `vendor`-related options when a vendor directory is already present.

When we make that change, you'll no longer need a vendor directory, and the `go build` command should automatically handle fetching new dependencies.

**Comment by syedriko** [comment]
>We just merged the go modules support yesterday
Lucky me :)
Can we then add the `go mod vendor` to the user guide and the readme for now and remove them when they're no longer needed? I added a commit to here: https://github.com/operator-framework/operator-sdk/pull/1408/commits/84ffd568d717b15f0dd7675053b1e53814bfc0e8

**Comment by syedriko** [comment]
Should we close this now that PR #1408 is merged?

**Comment by joelanford** [comment]
:+1: Thanks!
