### ISSUE TITLE
Permission denied writing files in the container of deployed operator.

### ISSUE THREAD

**Issue by iwasaki-kenta** [operator-framework/operator-sdk#1418]
## Type of question

Help around `operator-sdk`.

## Question

**What did you do?**

Try to write a Go-based operator that writes and saves files into its container.

**What did you expect to see?**

Permission should be granted; works if the operator is deployed locally rather than as a Docker container.

**What did you see instead? Under which circumstances?**

Permission denied. Does anything need to be setup with the RHEL minimal image wrapping my operator built with `operator-sdk` to enable write/read file permissions in the base directory the operator runs within?

**Environment**
* operator-sdk version:

`github.com/operator-framework/operator-sdk v0.0.0-20190423132450-ec538b5b4e4c`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: AWS

**Comment by AlexNPavel** [comment]
For security purposes, the processes in the container are configured to not run as root, so you cannot modify files at the base directory. The operator process has permissions to it's home directory (in `$HOME`), and if you wish to save files, they should be saved in the home directory.

**Comment by LiliC** [comment]
@iwasaki-kenta Hopefully the above answered your question otherwise feel free to reopen this or open another issue.
