### ISSUE TITLE
Better local deployment workflow

### ISSUE THREAD

**Issue by fanminshi** [operator-framework/operator-sdk#142]
Currently, the the deployment workflow of an operator is:
* Build the image: `operator-sdk build $Image`
* Push the image to a public registry: `docker push $Image`
* Create the operator deployment:  `kubectl create -f deploy/operator.yaml`
* Then test out the operator image via `kubectl`

Development cycle can be faster if we can avoid building/pushing the image. A workflow like the following maybe better (idea learned from [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder)):
* Build the operator binary `bin/operator` that knows kubeconfig so that the client can access the kubernetes cluster that's associated with kubeconfig.
*  Execute `./bin/operator`
* Then test out the operator via `kubectl`

The proposed approach saves developer time from building and pushing Image to a registry and operator deployment.

Action Items:
- [x] Implement `operator-sdk up` command ref: #219
- [x] Document how to use the `operator-sdk up` ref: https://github.com/operator-framework/operator-sdk/pull/279

**Comment by fanminshi** [comment]
I am proposing to have a `operator-sdk up` or something better named to help user to achieve the better local workflow.

Instead of the user follows the  `operator-sdk build $Image` and `docker push $Image` model every time they need to test out their code locally, the user can just calls `operator-sdk up --kubeconfig=<your-kubeconfig-path>` to run the operator locally.

The `operator-sdk up` compiles and runs the operator binary and gives it's internal Kubernete client the access to a kubernetes cluster by setting the client config to that of the passed in ` --kubeconfig`.
In this way, you can think that your local machine is a "pod" of a Kubernete cluster, and it can watch, query, and mutate anything in that Kubernete cluster.

**Comment by spahl** [comment]
Yeah you are right the subcommands are good and more explicit than flags.

**Comment by Verolop** [comment]
I agree with having separate commands, since the definitions and use cases don't necessarily overlap

**Comment by fanminshi** [comment]
`operator-sdk up local` command is implemented via https://github.com/operator-framework/operator-sdk/pull/219

I'll add doc to describe how to use it on the next few days.

**Comment by kgibm** [comment]
Hi, what's the latest recommended approach to this? I see `operator-sdk up` was [removed](https://github.com/operator-framework/operator-sdk/issues/4158) and I can't find the alternative. I tried `make build docker-build install deploy` but the pod shows as ErrImagePull and `make run` shows `if kind is a CRD, it should be installed before calling Start`.

Note that the non-local flow of pushing and pulling from Docker works with `make docker-build docker-push IMG="..."` and `make deploy IMG="..."`

**Comment by winem** [comment]
Is there any update? I'm currently running into the same issue when I try to test my operator in a local kind setup.
