### ISSUE TITLE
What does `var _ reconcile.Reconciler` do?

### ISSUE THREAD

**Issue by oreissig** [operator-framework/operator-sdk#1424]
## Type of question

Question about generated code.

## Question

**What did you do?**
Took a look at the example code.

**What did you expect to see?**
Clear, well-commented code.

**What did you see instead? Under which circumstances?**
The generated code is indeed pretty well-documented, but this referenced line I do not get. I assume it is not there by accident, but fail to see its semantic.
EDIT: "Reference in new issue" didn't work, here's what I mean:
https://github.com/operator-framework/operator-sdk/blob/ead640af152a0ea4656972f0f7a469a388eba946/example/memcached-operator/memcached_controller.go.tmpl#L71
Could someone please explain this to me?
I have the feeling that this may be a good candidate to add a one-line comment into the generated code for future generations who wonder :-)

**Comment by shawn-hurley** [comment]
This allows the compiler to make sure that your type conforms to the interface that it should conform too.

**Comment by oreissig** [comment]
Oh that makes sense, thank you!
So maybe it was just a n00b question from me being new to Go, but would you agree that there should be a one-line comment about that in the generated code?

**Comment by shawn-hurley** [comment]
> So maybe it was just a n00b question from me being new to Go, but would you agree that there should be a one-line comment about that in the generated code?

No, not an n00b question! Thanks for bringing it up.  I totally think that makes sense to document this. Would you like to add it?

**Comment by oreissig** [comment]
Yeah sure, will do tomorrow 👍
