### ISSUE TITLE
Broken Integration Test in Travis

### ISSUE THREAD

**Issue by mathianasj** [operator-framework/operator-sdk#1425]
## Bug Report

**What did you do?**
I was in the process of submitting a pull request, and noticed the travis tests were failing.  I checked out the master branch and ran the tests locally and was presented with the same failure.

**What did you expect to see?**
I expected the tests to pass

**What did you see instead? Under which circumstances?**
```
INFO[0039] Local operator test successfully completed.  
+ kubectl delete namespace test-memcached
namespace "test-memcached" deleted
+ kubectl create namespace test-memcached
Error from server (AlreadyExists): object is being deleted: namespaces "test-memcached" already exists
+ kubectl delete namespace test-memcached
Error from server (Conflict): Operation cannot be fulfilled on namespaces "test-memcached": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
+ true
+ echo exiting @ Tue May 14 14:01:18 EDT 2019
exiting @ Tue May 14 14:01:18 EDT 2019
make: *** [test/subcommand/test-local] Error 1
```

**Environment**
* operator-sdk version: ead640af152a0ea4656972f0f7a469a388eba946

* go version: 1.12.5 darwin/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-05-02T11:52:09Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
OpenShift
* Are you writing your operator in ansible, helm, or go?

**Possible Solution**
The tests do not seem to wait for the test namespace to delete and fails out.

**Comment by AlexNPavel** [comment]
Where did you see this happening on travis? We test every PR and branch on travis and I haven't seen this issue occur on travis or in local runs on my workstation.

Results of travis tests on our repo's branches: https://travis-ci.org/operator-framework/operator-sdk/branches

**Comment by LiliC** [comment]
@mathianasj Hello, like @AlexNPavel mentioned before we run the tests constantly and we haven't noticed this. If you run into this again feel free to open this issue or open another one possibly with link to the failing test, thanks!

**Comment by mathianasj** [comment]
It was on a pull request and ran successfully the second time
