### ISSUE TITLE
Extend metrics API to support custom metrics

### ISSUE THREAD

**Issue by fahlmant** [operator-framework/operator-sdk#1426]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Our operator needs to expose metrics based on stats other than direct CR counts. For example,
the [certman-operator](https://github.com/openshift/certman-operator/) exposes metrics based on a count from the https://crt.sh/ api. More generally, we may want to count CRs a different way, or add a metric that uses two CR counts in its calculation. 

**Describe the solution you'd like**
Extending the current metrics package to support adding custom metrics. Just as controllers are generated using the operator-sdk and the end user fills out the reconcile loop logic, the operator-sdk should generate a generic metrics endpoint. There should then be an API that has some sort of RegisterMetric() function that takes a prometheus client_golang type, kube-state-metric type, or other type of metric package (makes it easily extendable). The operator would, on start up, register the custom metrics and expose them over the service that the operator already creates.

**Comment by joelanford** [comment]
Ping @LiliC

**Comment by LiliC** [comment]
@fahlmant  I believe what you are looking for is helpers to serve metrics?

**Comment by fahlmant** [comment]
Yes. The desire is to serve our own metrics using the already provided metrics package.

**Comment by LiliC** [comment]
@fahlmant 
These metrics you mention are specific to your operator we can't create helpers for that, so that logic will live in your operator. What we can do is create a helper function for new registry, metrics serving and k8s service creation. (Or you can use the global registry that is already in controller-runtime, which I would advise against.)

Also noticed you already have metrics pkg, so maybe you can be more specific in what you want?

@joelanford I believe we said we want to avoid adding helpers that just serve as wrappers that we don't use directly?

**Comment by fahlmant** [comment]
@LiliC The goal is to leverage the metrics server/service/servicemonitor that the operator already deploys instead of having to create a unique package. We just to register a metric with the actual `/metrics` endpoint that already exists from operator-sdk, all the logic of defining and updating will live elsewhere.

**Comment by LiliC** [comment]
@fahlmant that would mean using the global registry of controller-runtime and we want to avoid doing that.

If anything else we would be creating helpers for a new registry and serving the /metrics endpoint on a different port. We need to discuss this first if we want to support those helpers.

We do plan on making changes to the Service helper function, so you will be able to pass in port and just one metrics Service would be created, that should be already helpful for you IMO. Issue https://github.com/operator-framework/operator-sdk/issues/1107 

As for ServiceMonitor, you can already use that by passing in the Service.

**Comment by fahlmant** [comment]
@LiliC Why avoid the global registry? Metrics already live there, it makes sense to put more metrics in the same place

**Comment by LiliC** [comment]
In general, avoiding globals is good :), but to read specific reasons for avoiding using global metrics registry here is an extract from k8s SIG instrumentation KEP:

> Kubernetes also makes extensive use of a global metrics registry to register metrics to be exposed. Aside from general shortcomings of global variables, Kubernetes is seeing actual effects of this, causing a number of components to use sync.Once or other mechanisms to ensure to not panic, when registering metrics. Instead a metrics registry should be passed to each component in order to explicitly register metrics instead of through init methods or other global, non-obvious executions. Within the scope of this KEP, we want to explore other ways, however, it is not blocking for its success, as the primary goal is to make the metrics exposed themselves more consistent and stable.

To read more on this https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20181106-kubernetes-metrics-overhaul.md

You are welcome to use this in your operator, but we won't be adding helper functions to encourage use of global metrics registry to stay in line with the above SIG guidelines. :) Hopefully makes more sense now? :)

**Comment by fahlmant** [comment]
@LiliC Okay, then I think I'm missing something. What is the metrics package used for if not for serving metrics about the operator?

**Comment by LiliC** [comment]
@fahlmant the metrics package in operator SDK creates a Service object and exposes the port on which the metrics are exposed. The metrics themselves are indeed operator specific, but they come via controller-runtime, it does use the global registry but there is an issue in controller-runtime for that too and in the future we will move away from that.

To read more docs on this https://github.com/operator-framework/operator-sdk/tree/master/doc/user/metrics 

Those metrics are the basic metrics about the operator, but not specific to your business logic like the ones you are interested above, if that makes sense? So the go specific metrics plus some [others.]( https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/internal/controller/metrics)

**Comment by joelanford** [comment]
Had an offline chat with @fahlmant, where the suggested way forward is to create a new non-global metrics registry in the operator and serve that directly.

@LiliC suggested https://github.com/brancz/prometheus-example-app/blob/master/main.go for a good example.
