### ISSUE TITLE
Error `no kind "Route" is registered for version "v1" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:61` is shown when try to use the Get and/or List for the fakeClient 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1427]
## Bug Report
**What did you do?**

Impl a unit test to get a v1.Route object as described in the [unit-testing](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/unit-testing.md) docs.  

```go
import (
        .... 
        routev1 github.com/openshift/api/route/v1
        ....
)


func TestReconcile<>_ReconcileController(t *testing.T) {
         ....
         route = &routev1.Route{}
	err = r.client.Get(context.TODO(), types.NamespacedName{Name: name, Namespace: namespace}, route)
	if err != nil {
		t.Fatalf("get route: (%v)", err)
	}
        ....
}
```

**What did you expect to see?**

Able to use `fakeClient.Get` and `fakeClient.List` when the object is of the type [v1.Route](https://docs.openshift.com/container-platform/3.4/rest_api/openshift_v1.html#v1-route)

**IMPORTANT:** The scheme is added with success and the actions`fakeClient.Create` and `fakeClient.Update` are working well

**What did you see instead? Under which circumstances?**
Following the error.

```shell
get route: (no kind "Route" is registered for version "v1" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:61")
```

**IMPORTANT:** It is not the same msg which is faced when the Scheme is not added. Following the error faced when the scheme is NOT added. 

```shell
create a route: (no kind is registered for the type v1.Route in scheme "k8s.io/client-go/kubernetes/scheme/register.go:61")`
```

**Environment**
* operator-sdk version: `Checked with the master branch and version 0.7.0`
* go version: `go version go1.11.5 darwin/amd64`
* Kubernetes version information:

**Analyse of the Problem**
* The error output came from [return nil, NewNotRegisteredErrForKind(s.schemeName, kind)](https://github.com/kubernetes/apimachinery/blob/master/pkg/runtime/error.go#L34)
* In this scenario it will try to perform the new [here](https://github.com/kubernetes/apimachinery/blob/master/pkg/runtime/codec.go#L93), however, the 
`schema.GroupVersionKind` required is nil which causes the error. 
<img width="1651" alt="Screenshot 2019-05-15 at 01 01 52" src="https://user-images.githubusercontent.com/7708031/57739922-4e80e280-76ad-11e9-9961-73fa19c66243.png">

**Additional context**
* Following the code used to test it. 
* See the comments which can be helpful to check it. 
* Also, note that the Memcached unit-test [example](https://github.com/operator-framework/operator-sdk-samples/blob/master/memcached-operator/pkg/controller/memcached/memcached_controller_test.go#L25) can be used to reproduce this issue. 

```go
package mobilesecurityservice

import (
	"context"
	"github.com/aerogear/mobile-security-service-operator/pkg/apis/mobilesecurityservice/v1alpha1"
	mobilesecurityservicev1alpha1 "github.com/aerogear/mobile-security-service-operator/pkg/apis/mobilesecurityservice/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	logf "sigs.k8s.io/controller-runtime/pkg/runtime/log"
	routev1 "github.com/openshift/api/route/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/kubernetes/scheme"
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
	"testing"
)

var (
	name            = "mobile-security-service"
	namespace       = "mobile-security-service-operator"

	instance = &mobilesecurityservicev1alpha1.MobileSecurityService{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: namespace,
		},
		Spec: v1alpha1.MobileSecurityServiceSpec{
			Size:                    1,
			SkipNamespaceValidation: true,
		},
	}
)

func TestReconcileMobileSecurityService_ReconcileController(t *testing.T) {

	//dev logs
	logf.SetLogger(logf.ZapLogger(true))

	// Register operator types with the runtime scheme.
	s := scheme.Scheme

	//Add route Openshift scheme
	if err := routev1.AddToScheme(s); err != nil {
		t.Fatalf("Unable to add route scheme: (%v)", err)
	}

	//Create mock Route Object
	route := &routev1.Route{
		TypeMeta: v1.TypeMeta{
			APIVersion: "v1",
			Kind:       "Route",
		},
		ObjectMeta: v1.ObjectMeta{
			Name:      name,
			Namespace: namespace,
			Labels:    getAppLabels(name),
		},
	}

	s.AddKnownTypes(mobilesecurityservicev1alpha1.SchemeGroupVersion, instance)
	objs := []runtime.Object{instance, route}

	// Create a fake client to mock API calls.
	cl := fake.NewFakeClientWithScheme(s, objs...)
	// Create a ReconcileMemcached object with the scheme and fake client.
	r := &ReconcileMobileSecurityService{client: cl, scheme: s}

	// Mock request to simulate Reconcile() being called on an event for a
	// watched resource .
	req := reconcile.Request{
		NamespacedName: types.NamespacedName{
			Name:      name,
			Namespace: namespace,
		},
	}
	res, err := r.Reconcile(req)
	if err != nil {
		t.Fatalf("reconcile: (%v)", err)
	}
	// Check the result of reconciliation to make sure it has the desired state.
	if !res.Requeue {
		t.Error("reconcile did not requeue request as expected")
	}

	//The following code works
	err = r.client.Update(context.TODO(), route)
	if err != nil {
		t.Fatalf("create route: (%v)", err)
	}

	//FIXME: It will return the error
	//FIXME: get route: (no kind "Route" is registered for version "v1" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:61")
	route = &routev1.Route{}
	err = r.client.Get(context.TODO(), types.NamespacedName{Name: name, Namespace: namespace}, route)
	if err != nil {
		t.Fatalf("get route: (%v)", err)
	}
}
```

**Comment by shawn-hurley** [comment]
Can you try:

```
//Create mock Route Object
	route := &routev1.Route{
		TypeMeta: v1.TypeMeta{
			APIVersion: "route.openshift.io/v1",
			Kind:       "Route",
		},
		ObjectMeta: v1.ObjectMeta{
			Name:      name,
			Namespace: namespace,
			Labels:    getAppLabels(name),
		},
	}
```

**Comment by camilamacedo86** [comment]
Hi @shawn-hurley,

I was very silly here. Yes, it makes sense and worked !! 

I will create a PR for the docs with all info over this subject for we are able to close this issue and https://github.com/operator-framework/operator-sdk/issues/1421#issuecomment-492442344.  I will ping you and let you know.  

Following the test.

<img width="1257" alt="Screenshot 2019-05-15 at 14 46 33" src="https://user-images.githubusercontent.com/7708031/57780575-6a719c00-7720-11e9-80f8-608bc6b367d0.png">

**Comment by camilamacedo86** [comment]
We checked that  TypeMeta: v1.TypeMeta{ is injected automatically, so shows not a good practice subscribe to these values. In this way, the best solution here would be not adding "TypeMeta: v1.TypeMeta" at all :-)

**Comment by shawn-hurley** [comment]
@camilamacedo86 do you think that we can close this bug then? Or do you and @craicoverflow think that we should add some documentation for this somewhere?

**Comment by camilamacedo86** [comment]
Yes, we can. I just keep open in order to remind me to create the PR for docs.

**Comment by camilamacedo86** [comment]
PR done in order to address it in the docs https://github.com/operator-framework/operator-sdk/pull/1440
