### ISSUE TITLE
Flag to provide Go build arguments

### ISSUE THREAD

**Issue by baijum** [operator-framework/operator-sdk#1435]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I want to include Git commit hash in the operator binary. It can be injected as a build-time value as described in this blog: https://blog.alexellis.io/inject-build-time-vars-golang/
This requires a way to specify Go build arguments in the `operator-sdk build` command.

**Describe the solution you'd like**

The flag could be similar to what is used in `up local` sub-command:  `operator-sdk up local --go-ldflags`. 

---

Earlier I have added this feature request as a comment here: https://github.com/operator-framework/operator-sdk/issues/1404#issuecomment-491261300

**Comment by ZoltanOnody** [comment]
@hasbro17 any update or ETA for the feature?
