### ISSUE TITLE
Homebrew v0.8.0 upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [operator-framework/operator-sdk#1451]
relates to https://github.com/Homebrew/homebrew-core/pull/40000

build log:
```
==> /usr/local/Cellar/operator-sdk/0.8.0/bin/operator-sdk new test
time="2019-05-17T22:45:15+01:00" level=info msg="Creating new Go operator 'test'."
time="2019-05-17T22:45:15+01:00" level=fatal msg="Dependency manager \"modules\" has been selected but go modules are not active. Activate modules then run \"operator-sdk new test\"."
Error: operator-sdk: failed
```

Upgrade to 0.7.1 seems fine.

**Comment by AlexNPavel** [comment]
The default dependency management system starting with operator-sdk `v0.8.0` is go modules. Go 1.12+ is required, and currently the `GO111MODULE=on` environment variable needs to be set to enable modules. To use `dep` instead, you can use `--dep-manager=dep`

See the README and sdk cli guide for more info: https://github.com/operator-framework/operator-sdk#create-and-deploy-an-app-operator https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#new

**Comment by LiliC** [comment]
Upgrading worked for using homebrew to v0.8.0 so closing this issue, thanks @chenrui333

**Comment by chenrui333** [comment]
👍

**Comment by danehrlich1** [comment]
`export GO111MODULE=on` fixed it for me immediately.
