### ISSUE TITLE
operator-sdk new app-operator failed 

### ISSUE THREAD

**Issue by BaddamJhansi** [operator-framework/operator-sdk#1459]
**What did you do**

**operator-sdk** new app-operator failed. It has created app-operator, go.mod, tools.go then it shows new Go scaffold failed, illegal character U+0073 's' in escape sequence (and 11 more errors)).

This is the error shown when I am trying to create new go operator.

**What did you see instead? Under which circumstances?**
```
C:\Users\goworkspace\src\github.com\example-inc>operator-sdk new app-operator

time="2019-05-21T10:04:26+05:30" level=info msg="Creating new Go operator 'app-operator'."
time="2019-05-21T10:04:26+05:30" level=info msg="Created go.mod"
time="2019-05-21T10:04:26+05:30" level=info msg="Created tools.go"
Error: new Go scaffold failed: (C:\Users\jz754x\goworkspace\src\github.com\example-inc\app-operator\cmd\manager\main.go:13:7: illegal character U+0073 's' in escape sequence (and 11 more errors))
Usage:
  operator-sdk new <project-name> [flags]

Flags:
      --api-version string          Kubernetes apiVersion and has a format of $GROUP_NAME/$VERSION (e.g app.example.com/v1alpha1) - used with "ansible" or "helm" types
      --cluster-scoped              Generate cluster-scoped resources instead of namespace-scoped
      --dep-manager string          Dependency manager the new project will use (choices: "dep", "modules") (default "modules")
      --generate-playbook           Generate a playbook skeleton. (Only used for --type ansible)
      --header-file string          Path to file containing headers for generated Go files. Copied to hack/boilerplate.go.txt
      --helm-chart string           Initialize helm operator with existing helm chart (<URL>, <repo>/<name>, or local path)
      --helm-chart-repo string      Chart repository URL for the requested helm chart
      --helm-chart-version string   Specific version of the helm chart (default is latest version)
  -h, --help                        help for new
      --kind string                 Kubernetes CustomResourceDefintion kind. (e.g AppService) - used with "ansible" or "helm" types
      --skip-git-init               Do not init the directory as a git repository
      --type string                 Type of operator to initialize (choices: "go", "ansible" or "helm") (default "go")

Global Flags:
      --verbose   Enable verbose logging
 ```
***operator-sdk version:

operator-sdk version: v0.7.0+git

*** Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
  
***go version:

go version go1.11.8 windows/amd64

***git version:
git version 2.21.0.windows.1

***dep version:
dep:
 version     : v0.4.1
 build date  : 2018-01-24
 git hash    : 37d9ea0a
 go version  : go1.9.1
 go compiler : gc
 platform    : windows/amd64

***operating system:
windows10

Please, someone help me with this to solve my problem.

**Comment by camilamacedo86** [comment]
Are you able to face the same issue if you use the master branch of operator-sdk?

**Comment by joelanford** [comment]
@BaddamJhansi we don't test `operator-sdk` on Windows, so we don't claim to support it. However, we don't _think_ there should be anything that prevents it from working on Windows.

Unfortunately, that error message is not very helpful. Taking a shot in the dark here, could you post the first line of the `go.mod` file that was generated?

**Comment by joelanford** [comment]
As an aside, that message shows that we don't log much context for these errors. I'll open a PR tomorrow to improve the error messages so that we can try to figure out where this is coming from.

**Comment by BaddamJhansi** [comment]
@joelanford Thank you so much for looking into my issue.  I am not unable to open go.mod file. Even main.go file which is in app-operator/cmd/manager/main.go is also empty.

**Comment by BaddamJhansi** [comment]
@camilamacedo86 i am facing same issue even using master branch.

**Comment by BaddamJhansi** [comment]
@joelanford  Thank you so much for looking into my issue. I am unable to open go.mod file. Even main.go file which is in app-operator/cmd/manager/main.go is also empty.

**Comment by joelanford** [comment]
@BaddamJhansi just to clarify:
- You have a `go.mod` file, but you can't open it to see it's contents? What issue are you having with opening it? 
- You also have `cmd/manager/main.go`, but it is empty?
- Other than `go.mod`, `tools.go`, and `cmd/manager/main.go`, do any other files exist?

**Comment by BaddamJhansi** [comment]
- @joelanford  go.mod type is Movie Clip when I am trying to play it is showing

Windows Media Player cannot play the file. The Player might not support the file type or might not support the codec that was used to compress the file.

- yes cmd/manger/main.go file is empty.

- No, only go.mod, tools.go, and cmd/manager/main.go are created.

- I am able to open tools.go file it has below content
// +build tools

package tools

import (
	// Code generators built at runtime.
	_ "k8s.io/code-generator/cmd/client-gen"
	_ "k8s.io/code-generator/cmd/conversion-gen"
	_ "k8s.io/code-generator/cmd/deepcopy-gen"
	_ "k8s.io/code-generator/cmd/informer-gen"
	_ "k8s.io/code-generator/cmd/lister-gen"
	_ "k8s.io/gengo/args"
	_ "k8s.io/kube-openapi/cmd/openapi-gen"
	_ "sigs.k8s.io/controller-tools/pkg/crd/generator"
)

**Comment by joelanford** [comment]
@BaddamJhansi `go.mod` is a text file. You should be able to open it with a text editor like VS Code, notepad, etc.

**Comment by BaddamJhansi** [comment]
@joelanford I think this might be problem with windows machine. It was working fine with ubuntu on virtual box.

**Comment by joelanford** [comment]
@BaddamJhansi I agree that this is likely Windows-specific. My hunch is that we don't handle Windows path segments and file separators correctly. It's hard to know for sure without more information, but I think #1487 may fix your issue.

**Comment by estroz** [comment]
@BaddamJhansi if you can build the SDK from master and try again, let us know if your issue is fixed.

**Comment by joelanford** [comment]
@BaddamJhansi we think this is fixed for Windows on the latest `master`. If you get a chance to try it and find that it is not fixed. Please leave a comment and we can re-open.
