### ISSUE TITLE
can we implement the ansible operator in cloud environment?

### ISSUE THREAD

**Issue by arunkanthkarre** [operator-framework/operator-sdk#1460]
to implement ansible operator minikube is required but it does not support in cloud environment.
how can i rectify this one if any one  implement this environment in cloud can u please help me to implement it

**Comment by shawn-hurley** [comment]
Are you asking if the ansible operator can be used with any version of kubernetes? are you asking about a specific operator-sdk command?

**Comment by hasbro17** [comment]
@arunkanthkarre Can you please clarify your question?
If I understand correctly by "cloud environment" I'm guessing you meant if your ansible-operator built by the SDK can run on a k8s cluster setup like GKE or Openshift. 
If so then yes, your operator should be able to run on any cluster that meets the pre-requisite k8s version specified in the README.

Closing this for now. Please re-open the issue if you have a more specific details on the errors with your environment.
