### ISSUE TITLE
Build error on 10.14 Yosemite with latest operator-sdk from Homebrew

### ISSUE THREAD

**Issue by kdwodc** [operator-framework/operator-sdk#1468]
## Bug Report

(dependencies seem all in place, and `brew doctor` reports no issues.)

My first time trying to build a new operator with the latest operator-sdk version. Perhaps I did something wrong?

**What did you do?**

```
export GO111MODULE=on
cd ~/go/src
mkdir example.com
cd example.com
operator-sdk new tester
cd tester
operator-sdk add api --api-version=example.com/v1 --kind=Tester
operator-sdk generate k8s
operator-sdk add controller --api-version=example.com/v1 --kind=Tester
go mod vendor
operator-sdk build quay.io/example/tester
```

**What did you expect to see?**

A successful build of the generated code, since I didn't change anything.

**What did you see instead? Under which circumstances?**

Output from `operator-sdk build quay.io/example/tester` command above:

```
# os/user
/usr/local/Cellar/go/1.12.5/libexec/src/os/user/getgrouplist_unix.go:16:35: warning: passing 'gid_t *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:653:43: note: passing argument to parameter here
# example.com/tester/cmd/manager
runtime/cgo(__TEXT/__text): relocation target x_cgo_inittls not defined
runtime/cgo(__TEXT/__text): relocation target x_cgo_threadentry not defined
Error: failed to build operator binary: (failed to exec []string{"go", "build", "-o", "/Users/myusername/go/src/example.com/tester/build/_output/bin/tester", "-gcflags", "all=-trimpath=${GOPATH}", "-asmflags", "all=-trimpath=${GOPATH}", "-mod=vendor", "example.com/tester/cmd/manager"}: exit status 2)
```

**Environment**
* operator-sdk version:

`operator-sdk version: v0.8.0, commit: 78c472461e75e6c64589cfadf577a2004b8a26b3`

(latest from Homebrew)

* go version:

`go version go1.12.5 darwin/amd64`

(latest from Homebrew)

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

created by Kubespray

* Are you writing your operator in ansible, helm, or go?

Go

**Possible Solution**

Seems to be either a code bug in Go or the CommandLineTools, or the generated operator code. Not sure.

**Additional context**

Wondering if this is an issue with the latest CommandLineTools for OS X. My OS is 10.14.5, not sure how to tell what version the CommandLineTools are. Also possibly a Go bug, either from Homebrew setup or in Go itself? Previously we used `dep` for dependencies, so maybe I did something wrong with the new mod stuff?

**Comment by joelanford** [comment]
@kdwodc do you by any change have `CGO_ENABLED=1` in your environment? If so, try `unset`-ing that and re-running the build.

**Comment by kdwodc** [comment]
Ah, that was it. Thanks!
