### ISSUE TITLE
Custom flags for test local (no go test ones)

### ISSUE THREAD

**Issue by smiklosovic** [operator-framework/operator-sdk#1476]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I see there in memcached example in main that you are doing flag.String("image") but this flag is set in stone in operator-sdk in test command.

If I want to add my flag (as I have other properties to set, specific to my test), I can not propagate any to "test local" because operator-sdk and go test itself does not recognise them.

**Describe the solution you'd like**

I want to be able to specify my own additional flags.

**Comment by AlexNPavel** [comment]
You should be able to pass the flags to your test using `--go-test-flags`. That flag simply appends the string you give it (split by spaces) to `go test`, which then passes it to the test that is being run if it does not match one of `go test`'s own flags. The only requirement would be putting the code to add the flags before the call to `test.MainEntry(m)`, the same way that the sdk's own e2e tests do.

**Comment by smiklosovic** [comment]
@AlexNPavel  I was doing that, the `go test` way with my flags, but I remember that it said that `go test` does no recognise these flags I am trying to pass and it failed. I am doing it via env properties instead. Are you 100% I can do that?

**Comment by smiklosovic** [comment]
`image` flag is in operator-sdk test subcommand itself so it is recognised hence parsed from `flag` but I have not see any other case when something completely custom is passed to that.

**Comment by nikhil-thomas** [comment]
> You should be able to pass the flags to your test using `--go-test-flags`. That flag simply appends the string you give it (split by spaces) to `go test`, which then passes it to the test that is being run if it does not match one of `go test`'s own flags. The only requirement would be putting the code to add the flags before the call to `test.MainEntry(m)`, the same way that the sdk's own e2e tests do.
@AlexNPavel this works only if the flag is being used inside the test code. I believe what @smiklosovic  is asking for is a way to pass a flag to operator code under test.

ie, an equivalent for `--operator-flags` flag in 
`operator-sdk up local --operator-flags` command.

At present, if we use `--go-test-flags` it will not be passed to the part of the code where the operator code is run locally (not on cluster)
here: https://github.com/operator-framework/operator-sdk/blob/e9e59c05d39a36bd3f52ac46f4893ff80749d922/pkg/test/main_entry.go#L77

**Comment by nikhil-thomas** [comment]
i have made a PR addressing this issue.
Could you take a look. https://github.com/operator-framework/operator-sdk/pull/1509

**Comment by smiklosovic** [comment]
@nikhil-thomas I want to do something like this

https://github.com/operator-framework/operator-sdk/blob/master/test/e2e/main_test.go#L27

On whatever flag, not just image.

**Comment by nikhil-thomas** [comment]
yes, the idea is to pass any flag which is defined in the operator code.
we have `operator-sdk up local --operator-flags "flag1=val1 flag2=val2"`

my PR adds that functionality to `--up-local` testing
`operator-sdk test lcoal --namespace test-operator-namespace --up-local --local-operator-flags "flag1=val1 flag2=val2"
