### ISSUE TITLE
Auto reload the local operator for code changes

### ISSUE THREAD

**Issue by baijum** [operator-framework/operator-sdk#1484]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When running the operator using `operator-sdk up local` command, I expect the operator to restart whenever there is a change in Go source code in the file-system.

**Describe the solution you'd like**
Operator SDK should watch for any Go source file changes in the file-system and restart the operator. It could be the default behavior, and it should be possible to turn off it using a flag, say `--disable-auto-reload`. Probably, this package can be used: https://github.com/fsnotify/fsnotify
Here is an example of usage: https://github.com/openshift/odo/blob/0381d45aa9b837e162d823e7e719b28c0b85a6e9/pkg/component/watch.go

**Comment by LiliC** [comment]
Thanks for the feature request. Seems like something that would be useful to users, we will try to prioritize it, or if you are willing to work on it you are welcome to do a PR for it! Thanks again!
