### ISSUE TITLE
Service created with operator

### ISSUE THREAD

**Issue by younglee1** [operator-framework/operator-sdk#1495]
## Type of question

Question about general context

## Question

**What did you do?**
Created an operator and successfully run in cluster.

**Question in detail**
Hi, I'm new to operator. I created my operator following the user guide, and the operator successfully run in k8s cluster. And I noticed that a service with same name as deployment was created. So my question is: what is the service used for? How is it created? I tried to find out the answers to these questions but failed.

**Comment by LiliC** [comment]
@younglee1  It's used for metrics and it's created in your main.go file, we have docs explaining this https://github.com/operator-framework/operator-sdk/tree/master/doc/user/metrics#monitoring-with-prometheus

Let me know if any of those don't make sense, we can explain and update the doc as well! :)

**Comment by younglee1** [comment]
Thanks @LiliC 
It really helps!

**Comment by LiliC** [comment]
Closing this but if you have another questions or if you want to improve the docs you are welcome to!
