### ISSUE TITLE
Obviate the scorecard with more complete code generation

### ISSUE THREAD

**Issue by jcrossley3** [operator-framework/operator-sdk#1499]
In theory, the scorecard should return 100% for any application built with the operator-sdk. Any code it generates should include everything the scorecard will test for. Reasonable defaults for everything can probably be derived from the CRD. And if not, even "**CHANGEME**" fields would be better than putting nothing in there.

In other words, give the user something to work with! A score is meaningless and unhelpful, even a little adversarial, especially considering most of the code it's scoring was generated by the operator-sdk itself!

Thanks!

**Comment by joelanford** [comment]
I agree this could be better. I tested out the current master with the default scaffolds:

```console
$ operator-sdk new scorecard-operator
$ cd scorecard-operator/
$ operator-sdk add api --api-version=example.com/v1alpha1 --kind App
$ operator-sdk add controller --api-version=example.com/v1alpha1 --kind App
$ operator-sdk olm-catalog gen-csv --csv-version=0.1.0
$ operator-sdk scorecard --cr-manifest=deploy/crds/example_v1alpha1_app_cr.yaml --csv-path=deploy/olm-catalog/scorecard-operator/0.1.0/scorecard-operator.v0.1.0.clusterserviceversion.yaml
WARN[0000] Could not load config file; using flags      
Running for cr: deploy/crds/example_v1alpha1_app_cr.yaml
WARN[0063] Plugin directory not found; skipping plugin tests: stat scorecard: no such file or directory 
OLM Tests:
	Spec fields with descriptors: 0/1
	Status fields with descriptors: 0/0
	Provided APIs have validation: 0/1
	Owned CRDs have resources listed: 0/1
	CRs have at least 1 example: 1/1
Basic Tests:
	Status Block Exists: 0/1
	Writing into CRs has an effect: 0/1
	Spec Block Exists: 1/1

Total Score: 30%
SUGGESTION: Add a spec descriptor for size
SUGGESTION: Add CRD validation for spec field `size` in App/v1alpha1
SUGGESTION: Add a 'status' field to your Custom Resource
SUGGESTION: The operator should write into objects to update state. No PUT or POST requests from the operator were recorded by the scorecard.
```

@AlexNPavel @estroz Are there improvements we could make to our `types.go` and `controller_kind.go` scaffolds that would improve the out-of-the-box scores?

**Comment by estroz** [comment]
#1162 makes it easier to improve the score (adds annotations for `types.go` files) but there are no fields to add annotations to in new API's, so this won't improve the score out of the box.

We should add more **CHANGEME**-type notes to scaffolded files. The scorecard depends a lot on how the user has defined their operator, so I doubt the score can be improved much out of the box.

**Comment by joelanford** [comment]
Also, I think #1143 should make the basic tests pass, since it adds the status with a simple "Ready" condition.

**Comment by flickerfly** [comment]
As someone working through all this fresh right now, having some CHANGEME notes in the created files would be really helpful. 

Example experience: 
Notes about changing spec.something leave some potential ambiguity about which spec. Root spec or spec.install.spec or spec.deployments.spec or a spec I don't yet have created. Guess and check works, but I'd be fine skipping that. :-)
