### ISSUE TITLE
Utility Methods to Ease Operator Development with Operator-SDK (redhat-cop/operator-utils)

### ISSUE THREAD

**Issue by madorn** [operator-framework/operator-sdk#1504]
Raffaele Spazzoli (Red Hat) put together a library of utility methods for operator-sdk available here: https://github.com/redhat-cop/operator-utils

May be nice to have something like this integrated into core operator-sdk project.

**Comment by LiliC** [comment]
@raffaelespazzoli ^ Are you maintaining this project, what was the initial purpose? :)

**Comment by raffaelespazzoli** [comment]
@LiliC the initial and current purpose of this project is to make it easier to develop operators and increase consistency in behavior and code layout across operators. This is achieved by making available a set of reusable functions and suggesting a set of best practices.

**Comment by LiliC** [comment]
@raffaelespazzoli any reason why we can't have those contributed back to operator SDK?

**Comment by raffaelespazzoli** [comment]
There is nothing stopping us.

**Comment by LiliC** [comment]
@raffaelespazzoli we look forward to your [proposals](https://github.com/operator-framework/operator-sdk/tree/master/doc/proposals#proposals) and contributions! Thanks!
