### ISSUE TITLE
Operator failed to deploy helm chart with weird error

### ISSUE THREAD

**Issue by adityabyreddy74** [operator-framework/operator-sdk#1505]
## Type of question

Seeking help to debug

## Question

**What did you do?**
I'm trying to deploy a helm chart with helm type Operator. When a CustomResource is created, operator failed to deploy the helm chart with unclear exception about the failure.

**What did you expect to see?**
Some valid information about the exception.

**What did you see instead? Under which circumstances?**
`
{
    "level":"error",
    "ts":1559309818.3805418,
    "logger":"helm.controller",
    "msg":"Failed to install release",
    "namespace":"default",
    "name":"swip",
    "apiVersion":"charts.helm.k8s.io/v1alpha1",
    "kind":"Swip",
    "release":"swip-c616bz1xv9rr32l157xj5xj4f",
    "error":"failed to roll back failed installation: no release provided: rendering template failed: reflect: Zero(nil)",
    "stacktrace":"github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr.(*zapLogger).Errorsrc/github.com/operator-framework/operator-sdk/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/helm/controller.HelmOperatorReconciler.Reconcile\n\tsrc/github.com/operator-framework/operator-sdk/pkg/helm/controller/reconcile.go:165\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsrc/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tsrc/github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\tsrc/github.com/operator-framework/operator-sdk/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"
}
`

**Environment**

* Operator base image:

quay.io/operator-framework/helm-operator:v0.6.0

* operator-sdk version:

 v0.6.0

* Kubernetes version information:

`
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
`

* Kubernetes cluster kind: 
kube-adm based setup (internal)

**Additional context**

I tried digging into the issue. Exception is exactly happening at https://github.com/operator-framework/operator-sdk/blob/master/pkg/helm/release/manager.go#L234. It would be helpful if someone can provide a debug build with much more verbose logging.

**Comment by joelanford** [comment]
@adityabyreddy74 Breaking down the error message, we have two errors:
- `failed to roll back failed installation: no release provided`
- `rendering template failed: reflect: Zero(nil)`

The first error is a little bit misleading. The helm-operator will attempt to rollback the installation if it fails. In this case, the installation is failing, and then the rollback is also failing with the error "no release provided". Without a release name, that probably means there's nothing to rollback, so it looks like we could improve that logic.

The second error is what caused the installation failure. `rendering template failed: reflect: Zero(nil)` is saying that there was an issue rendering the release manifest with the combination of the chart and values provided by the CR. Are you able to run `helm template` with the same chart and value?

**Comment by joelanford** [comment]
@adityabyreddy74 We improved the log messages for release failures in #1515, which should make the actual errors a bit clearer

**Comment by adityabyreddy74** [comment]
@joelanford Thanks Joe. 

The other issue was with our helm charts. Gotta dig deep into whats going wrong in there.
