### ISSUE TITLE
How can we use the CR.status fields to create alerts/monitor checks for the CRD applied in OCP and managed by an operator project?

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1511]
## Type of question

Usage / How to

## Question

How can we use the CR.status fields to create alerts/monitor checks for the CRD applied in OCP and managed by an operator project?

**What did you do?**
Add status in the CR as follows.

```go
type MobileSecurityServiceStatus struct {
         ....
	AppStatus          string                   `json:"appStatus"`
         .....
}
```

**What did you expect to see?**
Get the "status" to create a monitor alert with Prometheus for example. 
E.g if AppStatus <> "OK" shows alert. 

**What did you see instead? Under which circumstances?**
deployment, pods and etc info in the Prometheus but not the status fields

**Comment by joelanford** [comment]
@LiliC Do you know if there is a mechanism to propagate CR status to a prometheus metric using the controller-runtime or kube-state-metrics features? If not, is there a way to add a custom metric to an existing metrics servers?

@camilamacedo86 If there isn't built in support for this already, you would likely need to implement and register your own custom metric in your operator.

**Comment by camilamacedo86** [comment]
Hi @joelanford and @LiliC really tks for the help.

**Comment by LiliC** [comment]
Hi @camilamacedo86 you shouldn't use those fields to create alerts or metrics. You should collect the metrics themselves about your application directly in the application. And alert later depending on the metrics themselves. Basically, you are forcing some alerting rules on people, but you should just collect metrics instead. :) 

You shouldn't see the status field in Prometheus, but you can create alerts based on different already existing pod info metrics. But those are based on your needs. So for example: if you want to create an alert for pods, you would do something like this `absent(up{job="kubernetes-pods"})`.

**Comment by LiliC** [comment]
Hopefully, that answers your question, closing this, but feel free to ask any follows up! :)

**Comment by camilamacedo86** [comment]
Hi @LiliC and @joelanford,

Thank you for your time and help. I am not sure if I understand it very well, I am quite sure that you have a lot more knowledge in it than I have and maybe my questions are silly, however, could you please help me understand it better?

1. If the custom resource follows the same principle/interface of the "default" resources as a pod for example, why not I should not want to create an alert as `absent(up{job="<operator>", instance="<KIND/CRD>"}: )` for example? 

2. If I can create an alert based on the corev1.Route specs and status like [here](https://prometheus.io/docs/alerting/configuration/#route) why not I cannot do the same for my custom object/resources applied in the cluster?

3.  Why we should impl the status of custom resource if we cannot monitor it? What is the need that it has the purposed to attend?

**Comment by LiliC** [comment]
@camilamacedo86  No worries, happy to answer any questions.

1. That is fine to create an alert like that, you just need to expose those metrics in the operator and create the alert later in alertmanager.

2. Because those are not the same, one is the number of replicas, the other is OK. You want to create the number of instances for your app and then do the same alert like the first one.
You want to use the [RED method](https://grafana.com/blog/2018/08/02/the-red-method-how-to-instrument-your-services/), RateErrorDuration and just collect those, then you can come up with any alerts later on. 

3. This status is for human operators/users to consume, not for alerts. Alerts are based on the metrics and are not tied to anything k8s specific, like the status field.

**Comment by camilamacedo86** [comment]
Really tks I will check this video to understand better.
