### ISSUE TITLE
[Ansible-Operator] - Unable to deleted namespace when CR of an Ansible operator has a Finalizer

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1513]
## Bug Report

- Unable to deleted namespace when CR of an Ansible operator has a Finalizer
- **It doesn't occur with Golang operators**
- It occurs always when has a finalizer and we try to delete the namespace. 
- The Ansible operator is able to remove the metadata of the finalizer when deleting is directly made for the CR and not the namespace. (`oc delete  -f deploy/crds/cache_v1alpha1_memcached_cr.yaml`) 
- **The issue occurs because when we run `oc delete project <namespace>` the operator has been deleted before the CR.** (the issue is with the cascade/link of the resources generated )

**What did you do?**
- Checked it with the Memcached example: https://github.com/operator-framework/operator-sdk-samples/tree/master/ansible/memcached-operator
- Added just the finalizer:

```yaml
---
- version: v1alpha1
  group: cache.example.com
  kind: Memcached
  role: /opt/ansible/roles/memcached
  finalizer:
    name: finalizer.cache.example.com
```
- Create an namespace and apply the example.

```shell
$ oc new-project memcached

$ kubectl create -f deploy/crds/cache_v1alpha1_memcached_crd.yaml
$ kubectl create -f deploy/service_account.yaml
$ kubectl create -f deploy/role.yaml
$ kubectl create -f deploy/role_binding.yaml
$ kubectl create -f deploy/operator.yaml
$ kubectl create -f deploy/crds/cache_v1alpha1_memcached_cr.yaml
```
- Try to delete the namespace

```shell
$ oc project delete memcached
```

**What did you expect to see?**
The CR + Operator + Namespace be deleted with success. 

**What did you see instead? Under which circumstances?**
The namespace is marked to be deleted, the operator is deleted, but the CR is not which not allows the namespace to be deleted as well and is hanging it. 

- **Reason:** The operator has been deleted before the CR then it cannot remove the finalizer metadata from it which causes the bug. 

- **Workarround:** manual deletion of the finalizer metadata from the CR which would be made by the operator if it was not deleted first. E.g `oc patch memcached example-memcached -p '{"metadata":{"finalizers": []}}' --type=merge` 

OR 

- Delete the CR before deleting the namespace for the operator be able to remove the finalizer metadata.`oc delete -f  deploy/crds/cache_v1alpha1_memcached_cr.yaml`

**Environment**
* operator-sdk version: `0.8.1`
* go version: `go version go1.12.5 darwin/amd64`
* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-05-02T11:52:09Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: Minishift
* Are you writing your operator in ansible, helm, or go? Ansible

**Additional context**
Following the images to illustrate the bug. 

* Namespaced marked to be deleted and hanged by the CR with finalizer. 

<img width="1111" alt="Screenshot 2019-05-31 at 10 22 53" src="https://user-images.githubusercontent.com/7708031/58695931-6edbbd00-838e-11e9-9a18-bdd3a4ad3c18.png">

* See that the operator was deleted before the CR. 
<img width="1360" alt="Screenshot 2019-05-31 at 10 23 27" src="https://user-images.githubusercontent.com/7708031/58695981-90d53f80-838e-11e9-8ae8-62823340bba2.png">

* See that the CR still there with the finalizer metadata which should be removed by the operator. 
<img width="1639" alt="Screenshot 2019-05-31 at 10 23 20" src="https://user-images.githubusercontent.com/7708031/58696088-bb26fd00-838e-11e9-8fc3-1f4892f0e485.png">

**NOTE:** Issue opened in order to make clear the scenario/bug raised in #1493

**Comment by camilamacedo86** [comment]
Hi @estroz,

I closed https://github.com/operator-framework/operator-sdk/issues/1503 because I think that has too many comments that will be not helpful for we are able to address this scenario. 

Unfortunately, shows that my comments/descriptions there were not clear enough for @rcernich and @jmazzitelli and/or they are facing another issue which should be reported separately. 

Please, could you add here in this on the respective label? Really thank you for your time and support.

**Comment by rcernich** [comment]
@camilamacedo86, sorry for the confusion.  This issue is not the problem I was describing, but sounds like it is the issue that @jmazzitelli was having.  If you want me to create an issue for the problem I was describing, I can do that.  As I mentioned in the other issue, the problem I was describing was very difficult to track down the root cause.  Once again, sorry for the confusion.

**Comment by camilamacedo86** [comment]
Hi, @rcernich no problem at all

IMHO: It is better we have one issue for it issue :-) How much more clear we be able to provide the info better/easier and faster can be the fix 👍 So, please feel free to raise your scenario.

**Comment by robbie-demuth** [comment]
I believe this is also a problem for Helm-based operators. Custom resources created from Helm CRDs have a `uninstall-helm-release` finalizer. If the custom resource is namespace-scoped, deleting the namespace deletes the controller at which point the finalizer on the custom resources in the namespace cannot be handled - causing the namespace to get stuck in a terminating state

**Comment by shawn-hurley** [comment]
I believe it is a problem with all operators. Once the delete on the namespace is called, there is nothing that the operator could do.

**Comment by camilamacedo86** [comment]
HI @shawn-hurley it worked 100% in the Go operator ones. Note that the diff between both is that when it works in Go the operator pod is not removed before the CR/CRD be deleted. The problem here in POV is it. The operator.yaml has been deleted before.
