### ISSUE TITLE
Allow for customization in Helm based operator

### ISSUE THREAD

**Issue by rcernich** [operator-framework/operator-sdk#1514]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I have a set of charts, for which some resources need to be customized prior to installation (e.g. specifying a URL value in a ConfigMap that points to a Route installed ).

I have a set of charts that need to be applied in a certain order (e.g. as above, I need the chart providing the Route to be installed before its dependent).

I need to modify resources as part of the installation (e.g. applying labels to namespaces).

**Describe the solution you'd like**

It would be nice if the charts were rendered in a more controlled fashion, in a system where listeners could be registered to alter or enhance the behavior (as in the examples above).

We've started doing something similar to this in [Maistra](https://github.com/Maistra/istio-operator) and I've recently refactored the generic rendering bits into a simple framework for the [istio/operator](https://github.com/istio/operator/tree/master/pkg/helmreconciler).  Would something like this framework be beneficial for the operator-sdk?  If so, I'm happy to extract the generic portions I contributed to Istio for the SDK.

**Comment by rcernich** [comment]
You can see how the framework is used [here](https://github.com/istio/operator/tree/master/pkg/controller/istiocontrolplane).  The basic framework utilizes json merge patch and k8s strategic merge patch to process updates to resources and uses labels to prune created resources.  The extension simply tells the framework:

* what set of charts to use
* what order to apply the charts
* what labels to apply to the created resources
* what resource types are being managed (so the labelled resources can be pruned, as necessary)

**Comment by joelanford** [comment]
@rcernich This sounds interesting. A few questions:

> I have a set of charts, for which some resources need to be customized prior to installation (e.g. specifying a URL value in a ConfigMap that points to a Route installed ).

Do you envision the collection of charts having their lifecycle managed under one CR or multiple? Is there a parent chart that has one or more dependent subcharts?

>  I have a set of charts that need to be applied in a certain order (e.g. as above, I need the chart providing the Route to be installed before its dependent).

If I understand this correctly, this part would be a big change from the existing design, which is that a single CR reconciliation results in a single Helm lifecycle action (e.g. install, update, uninstall), and a single Helm release object. Does this imply multiple helm release objects per CR?

> I need to modify resources as part of the installation (e.g. applying labels to namespaces).

Basically a way to patch or inject things into the release manifest that's not in the chart template and controlled by values? This is definitely something we've thought about. The helm operator itself currently does this to inject owner references into the release manifest.

> It would be nice if the charts were rendered in a more controlled fashion, in a system where listeners could be registered to alter or enhance the behavior (as in the examples above).

Our idea for this is to refactor the helm-operator into a library that has extension points for adding custom logic. For example, interfaces that can be wrapped or overridden for choosing a release name, rendering the manifest, adding custom finalizers, executing the actual release action (maybe similar to HTTP middlewares where you get a `next` handler and have the chance to execute code before and/or after calling `next.ExecuteRelease` or something).

In your scenario, are you envisioning that operator developers would write Go code to augment and change how the Helm release is managed, or are you thinking that this functionality could be added to the native helm-operator and configured entirely via `watches.yaml` and maybe other templates, patch files, etc.?

**Comment by rcernich** [comment]
Answers:
1. The reconcile would be driven off a single CR.  Currently, the framework would only support a single chart, which could have multiple subcharts.  That said, invocations could be chained together to support multiple charts.
2. No helm release objects are used.
3. Correct.  One thing we do on Maistra is to modify a ConfigMap, which contains fields for various URLs, by looking them up from Route objects that were created by other subcharts.  This allows things to be wired correctly across the install.
4. Users would write custom go code to handle callbacks.

Here's basically how the operator works:
1. Render charts (effectively `helm template`)
2. Group manifests by chart name (map chart-name => manifest-list)
3. Create/update objects in manifestList for each chart (order of chart processing can be specified)
4. For each object, allow user to modify the object before it is applied.
5. If the object already exists, create a patch and apply it (this protects against things like overwriting immutable fields that have been set by k8s, e.g. Service.Spec.ClusterIP)
6. After manifest processing is complete, objects not aligned with the current CR are pruned.

To facilitate patching, objects are annotated in the same way they would if a user created them using `kubectl apply`.  This annotation is used as the source for the patch in a three way merge strategy (along with the installed structure and the new structure).

To facilitate pruning, all objects are labelled with an `owner` and a `generation` annotation is added.  For update processing, any labelled resources whose generation doesn't match are deleted.  For deletion all owned resources with a generation label are deleted.  (Deleting derived resources is avoided by asserting the existences of the generation annotation on the object.)

Theoretically, you could use this as a generic helm rendering engine, as all it does by default is add the labels and annotations to the objects (as opposed to using the helm release mechanism).

Currently, this mechanism has not been used in an _upgrade_ scenario, so I don't know if there are appropriate hooks that would support migration.  I can say that it does correctly overlay rendered objects, so the resources created reflect the latest state of the CR.

HTH

**Comment by joelanford** [comment]
I like the idea of removing the requirement for storing release state in a separate object. It sounds like a combination of labels and annotations on the release resources are sufficient for recreating the install, upgrade, uninstall lifecycle. And I really like the idea of the apply-like annotation for the 3-way merge. This is something I'd be interested in investigating more as a standalone design change.

> 3. Create/update objects in manifestList for each chart (order of chart processing can be specified)

Helm (and tiller) currently render the manifest for the entire release and then [sort it based on kind](https://github.com/helm/helm/blob/v2.14.0/pkg/tiller/kind_sorter.go) before installing (and the order is reversed for uninstall). It intermingles objects from various charts. Would it be sufficient to use Helm's sorting algorithm by default, but allow it to be overridden? Or is it important to handle each chart individually? More generally, could the helm operator allow the entire rendering process to be overridden with a custom Render function provided by the operator developer?

> Theoretically, you could use this as a generic helm rendering engine, as all it does by default is add the labels and annotations to the objects (as opposed to using the helm release mechanism).

Would there be a mechanism to rollback a failed install or upgrade?  An example of this is when a release attempts to change a service type from `NodePort` to `ClusterIP`. Helm fails the upgrade, leaves the previous release state in place (unless the user passes `--force`, in which case the service is deleted and recreated), and creates a new failed release object. The helm operator automatically rolls back in this scenario. 

Also, one of the features of the helm release mechanism is [chart hooks](https://github.com/helm/helm/blob/master/docs/charts_hooks.md), which are currently supported in the helm operator. Would this alternate mechanism be able to handle chart hooks?

Along those same lines, I think it would be nice to allow arbitrary go code execution before and after the release. This would give operator developers the chance to change the manifest, run custom migration code, handle errors, etc. to handle complex logic that is too complex or not possible to handle with native Helm and chart hooks. 

Lastly, have you seen the set of changes coming in Helm 3? Is there anything there that would need consideration?

**Comment by rcernich** [comment]
Hey, sorry I've been on PTO...

> Helm (and tiller) currently render the manifest for the entire release and then sort it based on kind before installing (and the order is reversed for uninstall). It intermingles objects from various charts. Would it be sufficient to use Helm's sorting algorithm by default, but allow it to be overridden? Or is it important to handle each chart individually? More generally, could the helm operator allow the entire rendering process to be overridden with a custom Render function provided by the operator developer?

We rely on the helm ordering of resources, but also insert OpenShift specific resources in the appropriate locations (e.g. routes after services).

The ordering I was speaking of was specific to the chart ordering.  We organize the manifest list by charts, as opposed to having a single list of all resources from all charts, then apply resources for each chart, based on some custom ordering (i.e. apply chart a, chart b, chart d, chart c, etc.).  The use case for this is for when there is a dependency from one chart to another chart, or when a resources needs to be updated dynamically using information from a resource in another chart (e.g. the host name from a route that's referenced in a config map).

> Would there be a mechanism to rollback a failed install or upgrade? An example of this is when a release attempts to change a service type from NodePort to ClusterIP. Helm fails the upgrade, leaves the previous release state in place (unless the user passes --force, in which case the service is deleted and recreated), and creates a new failed release object. The helm operator automatically rolls back in this scenario.

I haven't looked into anything like this.  Theoretically, this would involve a rollback of the custom resource and/or adding something like --force.  To be honest, there's work to do with respect to updates.  Using the patching mechanism was a simple way of avoiding having to write custom merge logic for every resource.

> Also, one of the features of the helm release mechanism is chart hooks, which are currently supported in the helm operator. Would this alternate mechanism be able to handle chart hooks?

I think there's some overlap with this and hooks.  Part of the reason for developing this was to avoid using jobs to patch the install (i.e. install it correctly from the start).  That said, this mechanism doesn't currently look for or run hooks (it basically just calls `helm template` and manually creates/updates the rendered resources).

> Lastly, have you seen the set of changes coming in Helm 3? Is there anything there that would need consideration?

I have not and don't know.
