### ISSUE TITLE
operator-sdk up local doesn't read ansible.cfg in the cwd

### ISSUE THREAD

**Issue by jdoss** [operator-framework/operator-sdk#1516]
## Bug Report

**What did you do?**
I am running Fedora 30 with Ansible 2.8 running through Python 3 for all of my other Ansible work. System Python is still set to python 2.7, but the system package for installing the openshift is only available for python 3.

```
$ rpm -qa |grep openshift
python3-openshift-0.8.8-1.fc30.noarch
```
I created an ansible.cfg file that is following the same configuration for my other ansible work. This includes setting `interpreter_python=/usr/bin/python3`.

I could install the openshift python module from pip for Python 2.7 or set `interpreter_python=/usr/bin/python3` in `/etc/ansible/ansible.cfg` (I did this for now) to work around the problem.

**What did you expect to see?**

I expected `operator-sdk up local` to use the ansible.cfg that I have sitting in my current working directory. When you create the container we copy this file into the it so someone like would assume it would be used when running `operator-sdk up local` too. 

**What did you see instead? Under which circumstances?**

The error made it clear it is reading ` /etc/ansible/ansible.cfg`

```
{"level":"error","ts":1559624708.329098,"logger":"runner","msg":"\u001b[0;34mansible-playbook 2.8.0\u001b[0m\r
\u001b[0;34m  config file = /etc/ansible/ansible.cfg\u001b[0m\r
\u001b[0;34m  configured module search path = ['/home/jdoss/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']\u001b[0m\r
\u001b[0;34m  ansible python module location = /usr/lib/python3.7/site-packages/ansible\u001b[0m\r
\u001b[0;34m  executable location = /usr/bin/ansible-playbook\u001b[0m\r
\u001b[0;34m  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]\u001b[0m\r
\u001b[0;34mUsing /etc/ansible/ansible.cfg as config file\u001b[0m\r
```

**Environment**
* operator-sdk version:

```
operator-sdk version: v0.8.0, commit: 78c472461e75e6c64589cfadf577a2004b8a26b3
```

* go version:

```
go version go1.12.5 linux/amd64
```

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-12-06T15:15:06Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-05-02T11:52:09Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

$ oc version
oc v3.11.0+8de5c34
kubernetes v1.10.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://mycool.cluster.local:8443
kubernetes v1.11.0+d4cacc0
```

* Kubernetes cluster kind: 

Openshift / Minishift 3.11

* Are you writing your operator in ansible, helm, or go?

Ansible

**Possible Solution**

Allow for `operator-sdk up local` to search the same locations as ansible does out of the box per https://docs.ansible.com/ansible/latest/reference_appendices/config.html#the-configuration-file

- `ANSIBLE_CONFIG` (environment variable if set)
- `ansible.cfg` (in the current directory)
- `~/.ansible.cfg` (in the home directory)
- `/etc/ansible/ansible.cfg`

**Comment by joelanford** [comment]
@jdoss I'm not sure about the `ansible.cfg` file, but for the roles and playbooks, the decision was made to honor the paths listed in `watches.yaml` rather than to try to do something fancy to handle both the `up local` case and the running as a container in the cluster case.

@shawn-hurley @fabianvf is there a reason we don't look for `ansible.cfg` in the root of the ansible operator directory during `up local` or was that just an oversight?

**Comment by fabianvf** [comment]
We don't really do anything related to parsing Ansible configuration, we let Ansible handle that when we kick off playbook runs. I'm not sure off the top of my head what context the Ansible commands are being run in, but it's probably not the same directory as the operator is launched from. Does it work when you set the `ANSIBLE_CONFIG` envvar?

**Comment by jdoss** [comment]
@fabianvf setting ANSIBLE_CONFIG with the absolute path to the ansible.cfg works. 

```
export ANSIBLE_CONFIG=/home/jdoss/operators/ansible.cfg
operator-sdk up local
```

**Comment by shawn-hurley** [comment]
so as Fabian mentioned ansible-runner is actually running the ansible and this is done in the ansible-runner directories. To enable this we would have to look for an ansible.cfg file and then copy it into those directories and I am not sure that ansible-runner would respect that anyhow from my reading here: https://ansible-runner.readthedocs.io/en/latest/index.html

1. An option would be to set the env var ourselves if an ansible.cfg file exists.

2. Another option is to just to document to achieve this is set the env var as you have done. 

@fabianvf @jdoss  I am leaning to option 2 WDYT?

**Comment by jdoss** [comment]
From my user perspective option 1 seems pretty appealing because it is very similar to to how Ansible works outside of an operator. If there is an `ansible.cfg` in the CWD of where you are invoking `operator-sdk up local` set `ANSIBLE_CONFIG`  to use that cfg until `operator-sdk up local` finishes.

I am using Ansible in a bunch of different contexts unrelated to the `operator-sdk` and having to keep track of what `ANSIBLE_CONFIG` I have loading feels clunky. Not to mention you have to give it the full path which is going to change all the time for a user and if `ANSIBLE_CONFIG` is set it will always use that even if you `cd` into a different project and it has a totally different `ansible.cfg` file.
