### ISSUE TITLE
Unable to run scorecard

### ISSUE THREAD

**Issue by galderz** [operator-framework/operator-sdk#1517]
Hi, I'm trying to run the scorecard on our operator (see branch).

I start minikube 1.1.0 with 4gb and 4cpu and nothing deployed on it.

After having built operator-sdk master (commit 49ec1963a0ce7490dd52384449d544751bf15934), I execute the scorecard and get:

```bash
$ operator-sdk scorecard --verbose
DEBU[0000] Debug logging is set
INFO[0000] Using config file: /Users/g/1/go/src/github.com/infinispan/infinispan-operator/.osdk-scorecard.yaml
WARN[0000] Duplicate gvks in CR list detected (infinispan.org/v1, Kind=Infinispan); results may be inaccurate
Running for cr: deploy/crds/cr_minimal.yaml
Error: failed to create cr resource: no matches for kind "Infinispan" in version "infinispan.org/v1"
```

The scorecard configuration can be found [here](https://github.com/galderz/infinispan-operator/blob/t_scorecard/.osdk-scorecard.yaml). The CSV comes from [here](https://github.com/operator-framework/community-operators/blob/master/community-operators/infinispan/infinispan-operator.v0.2.1.clusterserviceversion.yaml).

Any ideas? 

Also, why the WARN message about duplicate gvks?

`kubectl get events` shows this but not sure the warning message is meaningful here:

```
9m4s        Normal    Scheduled                 pod/infinispan-operator-58789c4db-h6gq9    Successfully assigned default/infinispan-operator-58789c4db-h6gq9 to minikube
9m3s        Normal    Pulling                   pod/infinispan-operator-58789c4db-h6gq9    Pulling image "jboss/infinispan-operator:latest"
8m39s       Normal    Pulled                    pod/infinispan-operator-58789c4db-h6gq9    Successfully pulled image "jboss/infinispan-operator:latest"
8m39s       Warning   Failed                    pod/infinispan-operator-58789c4db-h6gq9    Error: cannot find volume "scorecard-kubeconfig" to mount into container "infinispan-operator"
8m39s       Normal    Pulling                   pod/infinispan-operator-58789c4db-h6gq9    Pulling image "quay.io/operator-framework/scorecard-proxy:v0.8.0"
8m9s        Normal    Pulled                    pod/infinispan-operator-58789c4db-h6gq9    Successfully pulled image "quay.io/operator-framework/scorecard-proxy:v0.8.0"
8m9s        Warning   Failed                    pod/infinispan-operator-58789c4db-h6gq9    Error: cannot find volume "infinispan-operator-token-sdxzr" to mount into container "scorecard-proxy"
9m4s        Normal    SuccessfulCreate          replicaset/infinispan-operator-58789c4db   Created pod: infinispan-operator-58789c4db-h6gq9
9m4s        Normal    ScalingReplicaSet         deployment/infinispan-operator             Scaled up replica set infinispan-operator-58789c4db to 1
```

If I execute the scorecard again I see:

```
5m50s       Normal    Scheduled                 pod/infinispan-operator-58789c4db-m79hw    Successfully assigned default/infinispan-operator-58789c4db-m79hw to minikube
5m45s       Normal    Pulling                   pod/infinispan-operator-58789c4db-m79hw    Pulling image "jboss/infinispan-operator:latest"
5m43s       Normal    Pulled                    pod/infinispan-operator-58789c4db-m79hw    Successfully pulled image "jboss/infinispan-operator:latest"
5m43s       Normal    Created                   pod/infinispan-operator-58789c4db-m79hw    Created container infinispan-operator
5m43s       Normal    Started                   pod/infinispan-operator-58789c4db-m79hw    Started container infinispan-operator
5m47s       Normal    Pulling                   pod/infinispan-operator-58789c4db-m79hw    Pulling image "quay.io/operator-framework/scorecard-proxy:v0.8.0"
5m46s       Normal    Pulled                    pod/infinispan-operator-58789c4db-m79hw    Successfully pulled image "quay.io/operator-framework/scorecard-proxy:v0.8.0"
5m46s       Normal    Created                   pod/infinispan-operator-58789c4db-m79hw    Created container scorecard-proxy
5m46s       Normal    Started                   pod/infinispan-operator-58789c4db-m79hw    Started container scorecard-proxy
5m42s       Warning   BackOff                   pod/infinispan-operator-58789c4db-m79hw    Back-off restarting failed container
5m39s       Normal    Killing                   pod/infinispan-operator-58789c4db-m79hw    Stopping container scorecard-proxy
5m50s       Normal    SuccessfulCreate          replicaset/infinispan-operator-58789c4db   Created pod: infinispan-operator-58789c4db-m79hw
5m50s       Normal    ScalingReplicaSet         deployment/infinispan-operator             Scaled up replica set infinispan-operator-58789c4db to 1
```

**Comment by estroz** [comment]
@galderz you need to have your CSV/CRD's deployed onto the cluster using the [OLM](https://github.com/operator-framework/operator-lifecycle-manager/), then run the scorecard command as you have it with `--olm-deployed`. The scorecard assumes that the CSV and necessary CRD's have been deployed when passing a CSV.

There is no good documentation explaining this feature unfortunately, but I am working on it.

**Comment by galderz** [comment]
@estroz I've just been passed [this link](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md#testing-with-scorecard) which seems to explain exactly what you just said. 

IMO, the scorecard documentation should explain how to test it (obvious isn't it?), and the community operators docu should link to that.

**Comment by estroz** [comment]
@galderz it definitely will. Feel free to close this issue if you get OLM deployed and the scorecard runs successfully.

**Comment by galderz** [comment]
Hmmmm, tried with `--olm-deployed` and seeing:

```
INFO[0000] Using config file: /Users/g/1/go/src/github.com/infinispan/infinispan-operator/.osdk-scorecard.yaml
Error: failed to get newly created deployment: deployments.apps "infinispan-operator" not found
```

**Comment by estroz** [comment]
@galderz have you set up OLM in minikube and deployed your operator? Check out [this doc](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md) if you haven't.

**Comment by galderz** [comment]
I've set up OLM but have not deployed the operator. Shouldn't the scorecard do that? With the descriptor references that you pass in it has all the information to deploy and instantiate the operator.

**Comment by estroz** [comment]
@galderz the SDK will do that in the future, but cannot as of now.

**Comment by camilamacedo86** [comment]
Hi @galderz, 

I checked it these days with the latest version and it worked for me. Note that I applied all first n the cluster and ensure that all was running successfully. See here the project where it is working: https://github.com/dev4devs-com/postgresql-operator. To test it clone the project, run make install then run operator-sdk scorecard.
