### ISSUE TITLE
Scorecard test misinterprets status as a resource on a global CRD

### ISSUE THREAD

**Issue by alexander-aldev** [operator-framework/operator-sdk#1526]
## Bug Report

**What did you do?**
Ran the scorecard test on a cluster CRD (mariadbsize):
 
`operator-sdk scorecard --cr-manifest=deploy/examples/mariadbsize_example.yaml --csv-path=manifest/mariadb-operator-0.1.3-4.clusterserviceversion.yaml`

**What did you expect to see?**
No warnings related to status.

**What did you see instead? Under which circumstances?**
A warning:
`WARN[0014] could not find singular version of status`

and a suggestion:
`SUGGESTION: If it would be helpful to an end-user to understand or troubleshoot your CR, consider adding resources [status/v1alpha1 mariadbsizes/v1alpha1 deployments/v1 statefulsets/v1] to the resources section for owned CRD MariaDBSize`

**Environment**
* operator-sdk version:
c447c45f49f7075fe041ba910b632c10cc00bc8f

* go version:
go version go1.12.5 linux/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-05-02T11:52:09Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
Minishift 3.11

* Are you writing your operator in ansible, helm, or go?
Python 

**Possible Solution**
When parsing this URL `/apis/mariadb.com/v1alpha1/mariadbsizes/sandbox/status` in a PUT request, the function `getUsedResources` is taking `splitURI[5]` as `Kind` which is correct for a namespaced CRD, but not correct for a cluster CRD. I believe this line https://github.com/operator-framework/operator-sdk/blob/342284e4d66f22df9eefdc1e7160dea7994d8cc2/internal/pkg/scorecard/olm_tests.go#L351 needs to be fixed to distinguish between namespaced and cluster resources.

**Additional context**
Related line in scorecard-proxy container log:
 
`{"level":"info","ts":1559799415.4229803,"logger":"proxy","msg":"Request Info","method":"PUT","uri":"/apis/mariadb.com/v1alpha1/mariadbsizes/sandbox/status", "body":"{\"apiVersion\": \"mariadb.com/v1alpha1\", \"kind\": \"MariaDBSize\", \"metadata\": {\"creationTimestamp\": \"2019-06-06T05:36:42Z\", \"generation\": 1, \"name\": \"sandbox\", \"resourceVersion\": \"7280594\", \"selfLink\": \"/apis/mariadb.com/v1alpha1/mariadbsizes/sandbox\", \"uid\": \"10d161d1-881d-11e9-b1fd-b20c21536bab\"}, \"status\": {\"registered\": true}}"}`

**Comment by AlexNPavel** [comment]
Hello. Is your code open source? I would like to see what situations this occurs in, as we haven't seen this before (it looks like the scorecard is probably getting confused by subresources, which is odd because our CRs use status subresources as well)

**Comment by AlexNPavel** [comment]
Looking at this, it might not be too difficult to fix. We can identify that a resource is namespaced if one of the parts of the URI is `namespaces`. We made some assumptions on how simple the checks could be based on the different formats that a k8s api URI can have, but didn't take into account subresources: https://github.com/operator-framework/operator-sdk/blob/master/internal/pkg/scorecard/olm_tests.go#L284:L300. To handle a cluster scoped resource we probably just need to check if the `namespaces` field in the URI exists for some of the if statements and change some of the previous assumptions.

**Comment by alexander-aldev** [comment]
Thanks for the quick response. Currently MariaDB operator is being distributed under a commercial license (BSL), but I'll try to create a minimal example to use for reproducing the reported problem (ETA next week). Our final score is 100%, so this is not a showstopper.
