### ISSUE TITLE
Error to generate/move files when the command ` operator-sdk olm-catalog gen-csv --csv-version <tag> --update-crds` is executed

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1536]
## Bug Report

The following error is faced when in the deploy/ directory has files which has other names and/or the operator is cluster scoped and instead of role.yaml will have cluster_roles.yaml by following the docs.

```shell
$ operator-sdk olm-catalog gen-csv --csv-version 0.1.0 --update-crds
INFO[0000] Generating CSV manifest version 0.1.0        
Error: catalog scaffold failed: (open deploy/role.yaml: no such file or directory)
```

**What did you do?**
Run `$ operator-sdk olm-catalog gen-csv --csv-version 0.1.0 --update-crds`
**What did you expect to see?**
All yaml files under the path deploy/ be copied to the new tag dir as the csv be generated.

**What did you see instead? Under which circumstances?**
`Error: catalog scaffold failed: (open deploy/role.yaml: no such file or directory)`
The files were not moved and the csv was created empty. 

**Environment**
* operator-sdk version: `0.8.1`

* go version:`go version go1.12.5 darwin/amd64`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-06-03T16:51:23Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: Minishift

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**
* Move *.yaml when the  --update-crds be used 
* Looking for "kind: ClusterRole" and `kind: Role` as well to get the roles

**Additional context**
Cluster scoped operators may not have a `role,yaml`

**Comment by LiliC** [comment]
@camilamacedo86 I think this a valid request but we make these assumptions because we expect the operator to be generated with operator-sdk and we always generate the role.yaml. So it's not a bug really from our side. But if you want to maybe change this to a feature request?

cc @estroz

**Comment by estroz** [comment]
@camilamacedo86 you can specify which {cluster}role file is used by modifying the `role-path` field in a [CSV config](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/olm-catalog/generating-a-csv.md#configuration):
```yaml
operator-path: deploy/operator.yaml
role-path: deploy/cluster_role.yaml # Any name you want
crd-cr-paths:
    - deploy/crds/crd.yaml
```
then run:
```console
$ operator-sdk olm-catalog gen-csv --csv-config=path/to/config.yaml --csv-version 0.1.0 --update-crds
```
