### ISSUE TITLE
Add an option to dump operator log to file

### ISSUE THREAD

**Issue by caitong93** [operator-framework/operator-sdk#1537]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Sometimes e2e test run and failed, we want to check operator log and it is overhead to do it by hand again and again.

**Describe the solution you'd like**

Add an option to support dump operator log to file

```
operator-sdk test local --dump-operator-log=stderr ./test/e2e 
```

**Comment by LiliC** [comment]
@caitong93 thanks for your feature request! Do you know can also always tail the logs? e.g.:
`kubectl logs deploment/<operator-name> -f`
