### ISSUE TITLE
record.EventRecorder in operator-sdk don't trigger new event incase the event is already seen earlier. 

### ISSUE THREAD

**Issue by traghave** [operator-framework/operator-sdk#1538]
## Bug Report
I'm using recorder in reconcile method like below

```
func newReconciler(mgr manager.Manager) reconcile.Reconciler {
        return &Reconcilememcached{client: mgr.GetClient(),recorder: mgr.GetRecorder(controllerName), scheme: mgr.GetScheme()}
}

...
...

r.recorder.Event(client, corev1.EventTypeNormal, "SuccessEvent" , "New object create successful")
```

Event appears for once, but if same event is triggered from code it not actually seen when i describe the CRD
kubectl describe memcached

It lists event but with older timestamp.

My usecase is I create the crd instance and a success event shoud get triggered.
Then Edit the same crd instance with additional data and the same event should get triggered. However in this case event is not triggered or the existing event is not updated with `Last seen`.

**What did you do?**
I'm trying to leverage `mgr.GetClient(),recorder` for event handling.

**What did you expect to see?**
I think the event should gets triggered everytime the update is succeful or everytime the error is same, meaning the last seen should get changed.
 
**What did you see instead? Under which circumstances?**
Old event still present but not updated with timestamp.

**Environment**
* operator-sdk version: 

operator-sdk version: v0.8.0, commit: 78c472461e75e6c64589cfadf577a2004b8a26b3

* go version:

go version go1.12.2 linux/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5+icp-ee", GitCommit:"eb4df6c6fb47f5b4fd1ed8bfbfe2d0ed5ea636e1", GitTreeState:"clean", BuildDate:"2019-05-08T02:18:32Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5+icp-ee", GitCommit:"eb4df6c6fb47f5b4fd1ed8bfbfe2d0ed5ea636e1", GitTreeState:"clean", BuildDate:"2019-05-08T02:18:32Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
Single Node master

* Are you writing your operator in ansible, helm, or go?

go

**Additional context**
NA

**Comment by smiklosovic** [comment]
@traghave any luck?
