### ISSUE TITLE
extreme-citadel-208123

### ISSUE THREAD

**Issue by roufique2** [operator-framework/operator-sdk#1542]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:

* go version:

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**

**Additional context**

**Comment by joelanford** [comment]
@roufique2 There's no information in your bug report. Did you mistakenly create this issue? If not, please re-open a new issue with details of your problem/question
