### ISSUE TITLE
Broken link in template code

### ISSUE THREAD

**Issue by gautamkmr** [operator-framework/operator-sdk#1543]
## Bug Report

Following link is broken in multiple files.
Link: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html

Pages:
https://github.com/operator-framework/operator-sdk/blob/master/internal/pkg/scaffold/types.go#L59
https://github.com/operator-framework/operator-sdk/blob/master/internal/pkg/scaffold/types.go#L67

https://github.com/operator-framework/operator-sdk/blob/master/internal/pkg/scaffold/types_test.go#L54
https://github.com/operator-framework/operator-sdk/blob/master/internal/pkg/scaffold/types_test.go#L62

**What did you do?**
N/A

**What did you expect to see?**
Working link

**What did you see instead? Under which circumstances?**
Broken link

**Environment**
* operator-sdk version:

* go version:

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**

**Additional context**

**Comment by joelanford** [comment]
@gautamkmr This link works for me.

```console
$ curl -sSL -D - https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html -o /dev/null
HTTP/2 200
cache-control: public, max-age=0, must-revalidate
content-type: text/html; charset=UTF-8
date: Tue, 11 Jun 2019 18:50:38 GMT
etag: "469b3a608cbfda57c8c900dce7c7ebfe-ssl"
strict-transport-security: max-age=31536000
age: 15
content-length: 31942
server: Netlify
x-nf-request-id: 02f6031d-2fff-4b7e-b65e-f890f4fa9589-77229706
```

**Comment by joelanford** [comment]
@gautamkmr It is possible that you're behind a proxy that is blocking access for some reason?

**Comment by gautamkmr** [comment]
I see thanks @joelanford

**Comment by gautamkmr** [comment]
its work now.
