### ISSUE TITLE
ansible operator causes role to continually be called if k8s task creates CRs of a custom CRD kind

### ISSUE THREAD

**Issue by jmazzitelli** [operator-framework/operator-sdk#1550]
## Bug Report

**What did you do?**

I will attach a zip file with everything you need to replicate this (see the bottom of this message).

But in short, if my Ansible task does the following (creates CRs of a Kind from a custom CRD), then the ansible operator-sdk framework continually calls my role over and over infinitely:

```
- name: Create the Dashboards
  k8s:
    state: "present"
    namespace: "myproject"
    definition: "{{ lookup('template', item) }}"
  with_fileglob:
  - "templates/dashboards/*.yaml"
  ignore_errors: yes
```

If I take that out of my Ansible script, my operator functions properly (that means, my role is called one time, and one time only, when the operator detects my CR is created).

**What did you expect to see?**

When my CR is created and the operator detects it, the ansible role should be run one time only.

**What did you see instead? Under which circumstances?**

My role was called over and over constantly, with no pause in between. See the log file I will attach - you see my Ansible script spitting out the debug messages "START !!!" and "FINISH!!!" over and over repeatedly. It never stops (my role's main.yml spits out a debug msg "START !!!" as the first thing it does and "FINISH !!!" as the last thing it does before exiting - you can see this in the attached tarball in `roles/kiali-deploy/tasks/main.yml`)

**Environment**
* operator-sdk version: **0.8.0** (I also tried with **0.8.1**; that didn't help)

* go version: **N/A** (i'm using ansible operator)

* Kubernetes version information: **OpenShift 3.11**

* Are you writing your operator in ansible, helm, or go?: **ANSIBLE**

**Possible Solution**

Don't use "AllNamespace" mode - but that is not a viable solution - because my operator needs the WATCH_NAMESPACE to be "" (i.e. it needs AllNamespace mode).

**REPLICATION PROCEDURES**

To run this test, you need `make`, `oc`, and `operator-sdk` in your $PATH. You need a `myproject` namespace (which you probably already have if you are on OpenShift). You need to be logged in as a user with cluster-admin rights.

1. Take the attached zip file and unzip it and change your working directory to the "operator" directory (the top directory that came from the zip file).
2. Create a `myproject` namespace in your cluster if you do not have it already
3. Run the script `prepare-test.sh` - this builds the operator image in your local docker, creates a test namespace, and creates the operator.
4. Run the script `trigger-bug.sh`. This creates the CR that the operator is looking for

Now look at the operator's log (the operator will be in the namespace "kiali-operator"). Notice how it continually calls the deploy role over and over again. I will attach a log file to show you what I see - the log file is called `ansible-operator-bug.log`.

To clean up after the test, just run `cleanup.sh` to delete all the resources (the operator, the CR, etc).

Zip with the code: [ansible-operator-bug.zip](https://github.com/operator-framework/operator-sdk/files/3279563/ansible-operator-bug.zip)

Log file showing the problem: [ansible-operator-bug.log](https://github.com/operator-framework/operator-sdk/files/3279564/ansible-operator-bug.log)

One note of interest - I only see this when OPERATOR_WATCH_NAMESPACE is set to "" (i.e. I'm in "AllNamespaces" mode.) If I change the operator to only watch a single namespace, I don't see this bug happen.

You can see my test operator work if you edit the `kiali-operator.yaml` file and change the WATCH_NAMESPACE to look like this:

```
  - name: WATCH_NAMESPACE
    value: mazz2
```

Now run the test again:

```
./cleanup.sh
./prepare-test.sh
./trigger-bug.sh
```

At this point, look at the kiali operator logs and you'll see it only runs the role one time (as it should - so you don't see the bug here).

**Comment by gbaufake** [comment]
Facing this issue on OCP 4.1.0

```
oc version                                                                                                                                                                                                                                                    
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0-201905191700+82e7b55-dirty", GitCommit:"82e7b55", GitTreeState:"dirty", BuildDate:"2019-05-20T00:17:47Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+838b4fa", GitCommit:"838b4fa", GitTreeState:"clean", BuildDate:"2019-05-19T23:51:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

ansible logs - 
[ansible-logs](https://github.com/operator-framework/operator-sdk/files/3282498/running_4_1_0.txt)

**Comment by estroz** [comment]
@shawn-hurley @fabianvf @dymurray

**Comment by jmazzitelli** [comment]
If I add this to `watches.yaml`

```
watchDependentResources: False
```

This looping doesn't happen anymore, however, the operator logs get flooded with this error message - every 1 second I see this message spit out:

```
E0613 19:26:40.021725       1 reflector.go:251] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: Failed to watch *unstructured.Unstructured: unknown
```

Interestingly, this doesn't happen with my little test example I attached to this issue - this is only happening on my actual operator that I'm coding up. If I figure out how to replicate it, I'll post it here.

**Comment by shawn-hurley** [comment]
I believe that we determined the issue is with the no-op patches updating the resource version of a custom resource.

@fabianvf I believe you mentioned in slack that you were unable to reproduce this behavior?

**Comment by jmazzitelli** [comment]
> were unable to reproduce this behavior?

FYI: my previous comment https://github.com/operator-framework/operator-sdk/issues/1550#issuecomment-501315208 has replication procedures that reproduces it... it also has a .zip that reproduces the problem if you just want to run the code and not have to go through the steps to generate/modify the code to get there.

**Comment by fabianvf** [comment]
@shawn-hurley I reproduced it in openshift 3.11 and then tested a few kubernetes installs, here are the results:

| project | version | reproduced |
| ---------- | ---------- | ------------- |
| openshift | 3.11 | yes |
| kubernetes | 1.11 | no |
| kubernetes | 1.12 | no |
| kubernetes | 1.13 | no |

So this looks like an error specific to openshift, and we should either file a bug against openshift or bump one if it's already been filed.

**Comment by jmazzitelli** [comment]
@gbaufake were you able to replicate this on OpenShift 4.1 ?

**Comment by fabianvf** [comment]
@jmazzitelli I was unable to replicate the error in openshift 4.1

**Comment by gbaufake** [comment]
@fabianvf  I faced on 4.1 before adding `watchDependentResources: False` on watches file. as I commented on https://github.com/operator-framework/operator-sdk/issues/1550#issuecomment-501375911

**Comment by fabianvf** [comment]
@gbaufake can you paste your logs (`oc logs <operator pod> -c operator`, `oc logs <operator pod> -c ansible`)? I was not able to replicate the issue on 4.1 and did not have `watchDependentResources: False`
