### ISSUE TITLE
Zombie processes are created by ansible and never cleaned up

### ISSUE THREAD

**Issue by chancez** [operator-framework/operator-sdk#1551]
## Bug Report

**What did you do?**

Wrote a role which uses async tasks which results in processes accumulating like this:

```
root      2467  0.0  0.0      0     0 pts/0    Z+   21:04   0:00 [python] <defunct>
root      2468  0.0  0.0      0     0 ?        Zs   21:04   0:00 [python] <defunct>
root      2469  0.0  0.0      0     0 ?        Z    21:04   0:00 [python] <defunct>
root      2622  0.0  0.0      0     0 pts/0    Z+   21:05   0:00 [python] <defunct>
root      2623  0.0  0.0      0     0 ?        Zs   21:05   0:00 [python] <defunct>
root      2624  0.0  0.0      0     0 ?        Z    21:05   0:00 [python] <defunct>```
```

The async task module in ansible double forks the task processes it runs and they never get cleaned up. This was originally reported in https://github.com/operator-framework/operator-metering/issues/744 

This upstream ansible issue mentions this is basically expected, and you should be running an init system to handle this: https://github.com/ansible/ansible/issues/49270

**What did you expect to see?**

No defunct zombie processes

**What did you see instead? Under which circumstances?**

```
root      2467  0.0  0.0      0     0 pts/0    Z+   21:04   0:00 [python] <defunct>
root      2468  0.0  0.0      0     0 ?        Zs   21:04   0:00 [python] <defunct>
root      2469  0.0  0.0      0     0 ?        Z    21:04   0:00 [python] <defunct>
root      2622  0.0  0.0      0     0 pts/0    Z+   21:05   0:00 [python] <defunct>
root      2623  0.0  0.0      0     0 ?        Zs   21:05   0:00 [python] <defunct>
root      2624  0.0  0.0      0     0 ?        Z    21:05   0:00 [python] <defunct>```
```

**Environment**
* operator-sdk version: v0.6.0

**Possible Solution**

Using something like `tini` https://github.com/krallin/tini or dumb-init https://github.com/Yelp/dumb-init would ensure these zombie processes get cleaned up.

**Additional context**

The root cause here is ansible not ansible-operator, but the currently behavior is what is expected by ansible.

**Comment by estroz** [comment]
@shawn-hurley @fabianvf @dymurray
