### ISSUE TITLE
Ansible Operator on a Diet

### ISSUE THREAD

**Issue by eformat** [operator-framework/operator-sdk#1553]
## Feature Request

If i look to use ansible operator per app, per namespace - the underlying image size is considerable (i note that in quay.io its showing the squashed image size as ~ 200MB?) on disk it seems to be:

podman images
REPOSITORY                                    TAG      IMAGE ID       CREATED       SIZE
quay.io/operator-framework/ansible-operator   latest   7c667eba29ce   3 weeks ago   637 MB

any change of slimming the ansible-operator image down ?

**Describe the solution you'd like**

Even using UBI, python seems to be the challenge in terms of size:

registry.access.redhat.com/ubi8/python-36     latest   5bac20a7ed49   6
weeks ago         766 MB
registry.access.redhat.com/ubi8/ubi-minimal   latest   3bfa511b67f8   6
weeks ago         91.7 MB

not sure what the solution is for this, perhaps micropython ?

**Comment by camilamacedo86** [comment]
Hi @eformat,

We upgrade in the ansible images and we have tracked more few improvements. Could you check the current images and let us know what do you think?
