### ISSUE TITLE
How to run a command from reconcile inside of a pod/container?

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1561]
## Type of question

**Usage**

## Question

**What did you do?**
Getting a pod and trying to `kubectl exec` by using the client libs available. 

**What did you expect to see?**
Do something as :

```go
	cmd := []string{
		"/bin/sh",
		"-c",
		"pg_dump mobile_security_service | gzip > mobile_security_service.gz",
	}

       command(cmd).Run()
```
API example:

`/api/v1/namespaces/project-1/pods/pod-1-lmlzj/exec?command=/bin/bash&command=-c&command=/bin/bash&stdin=true&stderr=true&stdout=true&tty=true`

**Comment by LiliC** [comment]
@camilamacedo86 Can you explain a bit more, not sure I understand the reconcile part.

**Comment by cmoulliard** [comment]
Why don't you use the k8s client to execute this command - see https://github.com/snowdrop/kreate/blob/78f0b5ee8e27117b78fe9d6d5192bc5b04c0e5db/pkg/k8s/client.go#L243 ? @camilamacedo86

**Comment by camilamacedo86** [comment]
hi @LiliC I want in the reconcile execute a command inside of the container like `kubectl exec`

**Comment by camilamacedo86** [comment]
I tried the following impl and it did not work as well. The restClient is nil. 

```go
// Get the config
	cfg, err := config.GetConfig()
	if err != nil {
		return reconcile.Result{}, err
	}

	// Get The Rest client for this config
	restClient, _ := rest.RESTClientFor(cfg);

	// Do the request
	req := restClient.Post().
		Namespace(pod.Namespace).
		Resource("pods").
		Name(pod.Name).
		SubResource("exec").
		VersionedParams(&corev1.PodExecOptions{
			Command: cmd,
		}, scheme.ParameterCodec)

	// Connect to url (constructed from req) using SPDY (HTTP/2) protocol which allows bidirectional streams.
	exec, err := remotecommand.NewSPDYExecutor(cfg, "POST", req.URL())
	if err != nil {
		reqLogger.Error(err, "cmd", cmd, "pod", pod.Name)
		return reconcile.Result{}, err
	}

	// initialize the transport of the standard shell streams
	err = exec.Stream(remotecommand.StreamOptions{})
	if err != nil {
		reqLogger.Error(err, "cmd", cmd, "pod", pod.Name)
		return reconcile.Result{}, err

	}

```

Could you help me here? How can I execute a command inside of the containers of the pods managed by the operator? PS.: I cannot add the command via args when the deployment is made for example. In my case, I would like to do a bkp of the database and move the file for another place.

**Comment by camilamacedo86** [comment]
@shawn-hurley @LiliC @cmoulliard any ideas?

**Comment by shawn-hurley** [comment]
I think you need to change some of the options of your impl to get it to work.

https://github.com/snowdrop/kreate/blob/78f0b5ee8e27117b78fe9d6d5192bc5b04c0e5db/pkg/k8s/client.go#L251

https://github.com/snowdrop/kreate/blob/78f0b5ee8e27117b78fe9d6d5192bc5b04c0e5db/pkg/k8s/client.go#L270

**Comment by camilamacedo86** [comment]
Hi @shawn-hurley,

Really tks. However, I am still with an issue before that. The following code will return null. 


```go
	// Get The Rest client for this config
	restClient, _ := rest.RESTClientFor(cfg);
``` 

PS.: The cfg is that one injects in the manager. Have you any idea to solve it?

**Comment by cmoulliard** [comment]
> some of the options of your impl to get it to work.

Such examples will work as the restclient is created outside of the k8s cluster, We need for the Camila use case, something like this but able to working within the cluster

https://gist.github.com/cmoulliard/ec4dac1275042643bab7f4ba2867604f#file-gistfile1-txt-L279

**Comment by LiliC** [comment]
@camilamacedo86 if you want to do the request directly we do it like this:
https://github.com/operator-framework/operator-sdk/blob/c8ead552930d086056f779e8fdefa7f681c1e432/test/e2e/memcached_test.go#L792-L801

and to get the client we do:
https://github.com/operator-framework/operator-sdk/blob/c8ead552930d086056f779e8fdefa7f681c1e432/pkg/test/framework.go#L72-L79

You should be able to do direct requests then, haven't tried it myself.

**Comment by camilamacedo86** [comment]
Hi @LiliC I am not sure if it will attend the need as well. 
Note that is required the `kubeconfigPath`. From inside of the cluster it is one path (when the operator been executed) and from outside of the cluster (when we run `operator-sdk up local`) is another path

**Comment by camilamacedo86** [comment]
@Marco shared: https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/exec.go#L44

**Comment by anikin-aa** [comment]
Guys, any ideas here ? Or we should just use kubeClient ?
