### ISSUE TITLE
Is there a way to know the deployment status

### ISSUE THREAD

**Issue by adityabyreddy74** [operator-framework/operator-sdk#1569]
## Is there a way to know deployment status from helm based operator? something like helm status.

**Environment**
* operator-sdk version:

operator-sdk version v0.6.0

* Kubernetes cluster kind: Kubeadm

**Additional context**
I'm trying to evaluate deployment status from a operator based helm chart deployment.

**Comment by camilamacedo86** [comment]
I understand that you can use the command line tools to check it and/or the interface. Are you not able to see a pod created for the operator?

**Comment by joelanford** [comment]
@camilamacedo86 I think @adityabyreddy74 is asking about how to get the status of a helm release that was deployed by the helm operator. Is that right?

Details about the release status can be found in the CR status conditions. For example, the following will print the list of conditions for a particular CR's release:

```console
$ kubectl get nginxes.example.com example-nginx -o json | jq .status.conditions
[
  {
    "lastTransitionTime": "2019-06-19T03:13:11Z",
    "status": "True",
    "type": "Initialized"
  },
  {
    "lastTransitionTime": "2019-06-19T03:13:11Z",
    "message": "1. Get the application URL by running these commands:\n  export POD_NAME=$(kubectl get pods --namespace default -l \"app.kubernetes.io/name=nginx,app.kubernetes.io/instance=example-nginx-2hey5mzgu01x4wjcobsbpa8xx\" -o jsonpath=\"{.items[0].metadata.name}\")\n  echo \"Visit http://127.0.0.1:8080 to use your application\"\n  kubectl port-forward $POD_NAME 8080:80\n",
    "reason": "InstallSuccessful",
    "status": "True",
    "type": "Deployed"
  }
]
```

**Comment by joelanford** [comment]
@adityabyreddy74 I think the above comment should answer your question so I'm going to close the issue. If it doesn't let us know and we can re-open.

**Comment by adityabyreddy74** [comment]
@joelanford Is this the same behaviour with helm based operator too?

I'm using a helm based operator built using operator-sdk and strangely i don't see status field for my CustomResource object.
