### ISSUE TITLE
Unable to get the rest.Config ,"k8s.io/client-go/rest", with client provided by the framework

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1570]
## Bug Report

**What did you do?**

```go
import (
...
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/rest"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/manager"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
	logf "sigs.k8s.io/controller-runtime/pkg/runtime/log"
	"sigs.k8s.io/controller-runtime/pkg/source"
...
)

// newReconciler returns a new reconcile.Reconciler
func newReconciler(mgr manager.Manager) reconcile.Reconciler {
	//, restClient:mgr.GetConfig()
	return &ReconcileMobileSecurityServiceDBBackup{client: mgr.GetClient(), scheme: mgr.GetScheme(),  config: mgr.GetConfig()}
}

type ReconcileMobileSecurityServiceDBBackup struct {
	// This client, initialized using mgr.Client() above, is a split client
	// that reads objects from the cache and writes to the apiserver
	client client.Client
	config *rest.Config
	scheme *runtime.Scheme
}

func (r *ReconcileMobileSecurityServiceDBBackup) Reconcile(request reconcile.Request) (reconcile.Result, error) {
...
rc, _ := rest.RESTClientFor(r.config); // Here is the issue. It is returning nil when should return the *rest.Config
...
}
```
**What did you expect to see?**
```go
rc, _ := rest.RESTClientFor(r.config); // return the rest.Config
```
**What did you see instead? Under which circumstances?**
```go
rc, _ := rest.RESTClientFor(r.config); // it is returning nil
```

**Environment**
* operator-sdk version:

operator-sdk version: v0.8.0, commit: 78c472461e75e6c64589cfadf577a2004b8a26b3

* go version:

go version go1.12.5 darwin/amd64

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-06-14T18:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:  Minikube/Minishift

* Are you writing your operator in ansible, helm, or go? Go

**Possible Solution**
- Maybe impl it for the client provided by the framework. See that RESTClientFor is checking from the Config if there is are a GroupVersion, NegotiatedSerializer,... otherwise, it returns nil
- Maybe add new func in the client provided in the framework to run commands in the pods/containers which would solve the same need. 

**Additional context**

It is required to execute the ks8 remotecommad and perform executions inside of the pods. See 
https://github.com/snowdrop/kreate/blob/78f0b5ee8e27117b78fe9d6d5192bc5b04c0e5db/pkg/k8s/client.go#L245

IMPORTANT: Note that the func `rc, _ := rest.UnversionedRESTClientFor(r.config) ` will not work as well.

**Comment by shawn-hurley** [comment]
what is the error that is returned?

**Comment by LiliC** [comment]
@camilamacedo86 I think what Shawn meant was that you are ignoring the error that is being returned. So can you check if the error is not nil. e.g.:
```go
rc, err := rest.RESTClientFor(r.config); 
if err != nil {
  return nil, err
}
```

**Comment by LiliC** [comment]
@camilamacedo86 did you have a chance to get any more info or errors, otherwise we can close this and if you run into more problems we can reopen. Thanks.

**Comment by camilamacedo86** [comment]
@LiliC and @shawn-hurley the error faced is: "GroupVersion is required when initializing a RESTClient"

<img width="779" alt="Screenshot 2019-07-02 at 16 42 50" src="https://user-images.githubusercontent.com/7708031/60541687-8b01af80-9ce8-11e9-8415-b7240be31d7f.png">

**Comment by camilamacedo86** [comment]
The error came from : https://github.com/kubernetes/client-go/blob/master/rest/config.go#L274

**Comment by ClareChu** [comment]
I dealt with it this way and solved the problem


```go

import (
        "k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/runtime/serializer"
)

// GroupName is the group name use in this package
const GroupName = ""

// SchemeGroupVersion is group version used to register these objects
var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: "v1"}

func GetRestClient() (config *rest.Config, err error) {
	if os.Getenv("KUBERNETES_SERVICE_HOST") == "" {
		kubeConfig := GetKubeConfig()
		config, err = clientcmd.BuildConfigFromFlags("", kubeConfig)
		if err != nil {
			return
		}
	} else {
		config, err = rest.InClusterConfig()
		if err != nil {
			return
		}
	}
	config.APIPath = "/api"
	config.GroupVersion = &SchemeGroupVersion
	config.NegotiatedSerializer = serializer.WithoutConversionCodecFactory{CodecFactory: scheme.Codecs}
	return
}
```

**Comment by jamesnieper-alation** [comment]
> I dealt with it this way and solved the problem
> 
> ```go
> import (
>         "k8s.io/apimachinery/pkg/runtime/schema"
> 	"k8s.io/apimachinery/pkg/runtime/serializer"
> )
> 
> // GroupName is the group name use in this package
> const GroupName = ""
> 
> // SchemeGroupVersion is group version used to register these objects
> var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: "v1"}
> 
> func GetRestClient() (config *rest.Config, err error) {
> 	if os.Getenv("KUBERNETES_SERVICE_HOST") == "" {
> 		kubeConfig := GetKubeConfig()
> 		config, err = clientcmd.BuildConfigFromFlags("", kubeConfig)
> 		if err != nil {
> 			return
> 		}
> 	} else {
> 		config, err = rest.InClusterConfig()
> 		if err != nil {
> 			return
> 		}
> 	}
> 	config.APIPath = "/api"
> 	config.GroupVersion = &SchemeGroupVersion
> 	config.NegotiatedSerializer = serializer.WithoutConversionCodecFactory{CodecFactory: scheme.Codecs}
> 	return
> }
> ```

Thanks, fixed my issue, only change I had to make was add `"k8s.io/client-go/kubernetes/scheme"` to the imports to have it compile
