### ISSUE TITLE
Add or Replace Docker with Buildah/ Podman?

### ISSUE THREAD

**Issue by djohnston89** [operator-framework/operator-sdk#1573]
## Feature Request
Container community drive towards podman/ buildah. 

Please add these as an option for container builds/ pushes for those not running Docker.

**Comment by joelanford** [comment]
@djohnston89 Podman and buildah are already supported with the `operator-sdk build` command. See https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#flags
