### ISSUE TITLE
metrics: Include CreateServiceMonitor in every main.go file

### ISSUE THREAD

**Issue by LiliC** [operator-framework/operator-sdk#1576]
Despite ServiceMonitor helper function being well [documented](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/metrics/service-monitor.md) I noticed is not used that often. I fear this is because of the lack of discoverability. Because [prometheus-operator](https://github.com/coreos/prometheus-operator) is so widely used and regarded as almost the default option for running Prometheus in kubernetes clusters, we should generate this function by default in the main.go files.

I propose the following in the main.go file right after the creation of Service:

```go
package main

....
// TODO(user):
// Comment out the following lines if you have prometheus-operator
// running your kubernetes cluster. It creates ServiceMonitor object
// based on the Service ports, in turn it creates the set of targets
// to be monitored by Prometheus automaticly.
// _, err := metrics.CreateServiceMonitors(cfg, namespace, services)
// if err != nil {
//
// }
```

We can also just leave it uncommented as we do check before creating ServiceMonitors if they are registered to prevent errors and return early.

**Comment by joelanford** [comment]
If we already check to see if the CRD is present before trying to create the ServiceMonitor instance, I don't see any reason not to add it uncommented with a comment that describes what it does.
