### ISSUE TITLE
Adding third party types.go to current scheme is not working

### ISSUE THREAD

**Issue by gaurav-dalvi** [operator-framework/operator-sdk#1578]
## Bug Report

**What did you do?**
1: I have external types.go and hence CR : 
https://github.com/noironetworks/aci-containers/blob/snat-jayaram/pkg/nodeinfo/apis/aci.nodeinfo/v1/types.go

2: my operator code : https://github.com/gaurav-dalvi/snat-operator/tree/sdk-bug
I am trying to use Nodeinfo object in my operator code. I added AddToScheme call in main.go but my client is not able to get those objects for me.

**What did you expect to see?**
https://github.com/gaurav-dalvi/snat-operator/blob/sdk-bug/cmd/manager/utils/k8sutils.go#L79
This line should get printed

**What did you see instead? Under which circumstances?**
Line did not get print in the logs. Object came as `nil` . There was not even error.

**Environment**
* operator-sdk version:

`operator-sdk version: v0.8.1, commit: 33b3bfe10176f8647f5354516fff29dea42b6342`

* go version:

`go version go1.12.5 darwin/amd64`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
```
 minikube version
minikube version: v1.1.0
```

* Are you writing your operator in ansible, helm, or go?
`Go`

**Possible Solution**
NA

**Additional context**
Based on this help : https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#register-with-the-managers-scheme
When external type exposes AddToScheme, you should be registering that in main.go of your operator code. I did the same. But my client is not able to get the object from apiserver.

**Comment by LiliC** [comment]
@gaurav-dalvi can you please fill in the fields in the bug report above so we can help solve the problem faster, thanks!

**Comment by gaurav-dalvi** [comment]
@LiliC Done. I thought I updated it already.

**Comment by LiliC** [comment]
@gaurav-dalvi you need to add the third party APIs to the scheme, the guide is here https://github.com/operator-framework/operator-sdk/blob/757f7a0b9d12cacf407cb12c30b89374206f1ff2/doc/user-guide.md#adding-3rd-party-resources-to-your-operator

**Comment by gaurav-dalvi** [comment]
@LiliC : Yes I did it correctly. You can see it here : https://github.com/gaurav-dalvi/snat-operator/blob/sdk-bug/cmd/manager/main.go#L100

**Comment by hasbro17** [comment]
@gaurav-dalvi Are you still having the same issue?

> Line did not get print in the logs. Object came as nil . There was not even error.

Looking at your code it would be more evident if you could print the error returned from a `c.Get` or `c.List()` rather than look for that specific log statement.
https://github.com/gaurav-dalvi/snat-operator/blob/sdk-bug/cmd/manager/utils/k8sutils.go#L70-L74

If the error is nil and the object is "nil"(I'm assuming you mean empty since you passed in a `&nodeinfo.NodeinfoList{}`) then it's quite possible that there are no objects of type `NodeinfoList` in your cluster.

If it were missing type in the scheme then I would expect to see an error like `Error: no kind is registered for the type v1.NodeinfoList in scheme` from the first client call.

**Comment by gaurav-dalvi** [comment]
@hasbro17 : thanks for commenting. I am sure that i have NodeInfoList objects present in the k8s cluster before running this operator. If i put types.go in my snat-operator code then it works perfectly fine. But i am not able to add third party types.go as mentioned by this doc.

**Comment by estroz** [comment]
@gaurav-dalvi type `NodeinfoList{}` [not registered](https://github.com/noironetworks/aci-containers/blob/snat-jayaram/pkg/nodeinfo/apis/aci.nodeinfo/v1/register.go#L35-L37) with the scheme builder, which might be the source of your issue. But as @hasbro17 mentioned I would expect an error if that type is not registered.

**Comment by gaurav-dalvi** [comment]
@estroz : As I said earlier, I registered that type to manager scheme in operator-sdk here : 
https://github.com/gaurav-dalvi/snat-operator/blob/sdk-bug/cmd/manager/main.go#L100

I am sure that an object present. That's why I am not getting an error related to registering the new object. because it's already registered.

**Comment by gaurav-dalvi** [comment]
I dont want to put types.go of nodeInfoList in this project as it defeats the purpose of third party types.go addition to operator-sdk project.

**Comment by hasbro17** [comment]
> That's why I am not getting an error related to registering the new object. because it's already registered.

@gaurav-dalvi I think we're all on the same page here. The issue you're having is not that your third party type nodeInfoList is not getting registered correctly. If that were the case then you would have seen the registration error. 

Unfortunately as it is now there's not much more we can guess from just looking at your helper function.

Can you please provide more context by showing us the entire operator logs?

**Comment by meragodbole** [comment]
@LiliC In my reconcile code, I am creating another new CR that is operated on by another operator. How do I account or this? My code flags all the fields in this Object Spec as "unknown field"

**Comment by gaurav-dalvi** [comment]
@meragodbole : you will probably need to do this : https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#register-with-the-managers-scheme

import your types.go from other operator code here (you need to vendor in) and then try to add to current operator's manager scheme. I was never able to do this successfully thats why i opened this issue.

**Comment by meragodbole** [comment]
I am new to this so pardon my ignorance on this.

So, I have a CRD1 in the cluster for the CR1 object that I am trying to create in the reconcile function of another CR2. And in my operator for CRD2, I am creating a new CR1 object and get "unknown field" for anything in this CR1 object. I have CR1 in pkg/apis....
what else should I be doing to register this CR1?

**Comment by hasbro17** [comment]
@gaurav-dalvi Are you still having this issue? As it is, it's hard to see what your issue might be without looking at the operator logs.

@meragodbole Can you please open up a new issue if you're still having a problem.
If your operator needs to create an instance of a CRD not defined in it's project then you just need to register that type with your operator's scheme first before using the dynamic client to create that resource.

```Go
import (
  ....

  routev1 "github.com/openshift/api/route/v1"
)

func main() {
	....

	// Adding the routev1
	if err := routev1.AddToScheme(mgr.GetScheme()); err != nil {
		log.Error(err, "")
		os.Exit(1)
	}
}

...


func (r *ReconcileMemcached) Reconcile(request reconcile.Request) (reconcile.Result, error) {
	...
	// Create a CR instance of an external type Route
	route := routev1.Route{...}
	err := r.client.Create(context.TODO(), route)
	...
}
```

**Comment by camilamacedo86** [comment]
Hi @gaurav-dalvi, 

Show that your question was already sorted. However, if would check an example of this working and a project which is using the same version see [here](https://github.com/aerogear/mobile-security-service-operator/blob/master/cmd/manager/main.go#L155).

In this way, I am closing this one. However, feel free to re-open if you see that is required.
