### ISSUE TITLE
Operator SDK CLI should report its version

### ISSUE THREAD

**Issue by fanminshi** [operator-framework/operator-sdk#158]
Currently, user can't determine the version of Operator SDK CLI easily.
We can add additional command or flags to `operator-sdk` to print out the version:

```sh
$ operator-sdk version
v0.0.2
...
```

or 
```sh
 $ operator-sdk --version
v0.0.2
...
 $ operator-sdk -v
v0.0.2
...
```

**Comment by hasbro17** [comment]
Fixed by #234
