### ISSUE TITLE
Leader election mechanism prevents running multiple instances of the same operator

### ISSUE THREAD

**Issue by riccardomc** [operator-framework/operator-sdk#1584]
## Bug Report

While developing this [External Secret Operator](https://github.com/ContainerSolutions/externalsecret-operator) I ran into an issue with the leader election mechanism as summarized here: https://github.com/ContainerSolutions/externalsecret-operator/issues/22.

My intention is to run multiple instances of the same operator in the same namespace for isolation reasons, however the leader election mechanism gets in the way of this approach because it uses an hardcoded string for the lock id:

```golang
err = leader.Become(ctx, "externalsecret-operator-lock")
```

**What did you do?**
Deploy two instances of the same operator in the same namespace

**What did you expect to see?**
Both instances of the operator working correctly

**What did you see instead? Under which circumstances?**
Only the first instance starts correctly because both instances compete for the same lock in the leader election mechanism:
```
% kubectl logs dummy1-externalsecret-operator-654ccd8c5-rbzgz -n operators
{"level":"info","ts":1561133148.715241,"logger":"cmd","msg":"Go Version: go1.12.5"}
{"level":"info","ts":1561133148.7154908,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1561133148.7155504,"logger":"cmd","msg":"Version of operator-sdk: v0.6.0+git"}
{"level":"info","ts":1561133148.7156768,"logger":"cmd","msg":"External Secret Operator Version: 0.0.3"}
{"level":"info","ts":1561133148.7157323,"logger":"backend","msg":"initFromEnv","availableBackends":"asm,dummy,onepassword"}
{"level":"info","ts":1561133148.7158184,"logger":"backend","msg":"instantiate","name":"dummy1","type":"dummy"}
{"level":"info","ts":1561133148.7158797,"logger":"backend","msg":"initialize","name":"dummy1"}
{"level":"info","ts":1561133148.7162175,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1561133148.7607462,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1561133148.7654803,"logger":"leader","msg":"Became the leader."}
```

```
% kl dummy2-externalsecret-operator-77589468ff-tdftn -n operators
{"level":"info","ts":1561133153.1770334,"logger":"cmd","msg":"Go Version: go1.12.5"}
{"level":"info","ts":1561133153.1770985,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1561133153.1771052,"logger":"cmd","msg":"Version of operator-sdk: v0.6.0+git"}
{"level":"info","ts":1561133153.1771102,"logger":"cmd","msg":"External Secret Operator Version: 0.0.3"}
{"level":"info","ts":1561133153.1771166,"logger":"backend","msg":"initFromEnv","availableBackends":"asm,dummy,onepassword"}
{"level":"info","ts":1561133153.177162,"logger":"backend","msg":"instantiate","name":"dummy2","type":"dummy"}
{"level":"info","ts":1561133153.1771667,"logger":"backend","msg":"initialize","name":"dummy2"}
{"level":"info","ts":1561133153.177314,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1561133153.2079115,"logger":"leader","msg":"Found existing lock","LockOwner":"dummy1-externalsecret-operator-654ccd8c5-rbzgz"}
{"level":"info","ts":1561133153.2110562,"logger":"leader","msg":"Not the leader. Waiting."}
```

**Environment**
* operator-sdk version:
v0.6.0+git

* go version:
go1.12.5

* Kubernetes version information:
1.14.0

* Kubernetes cluster kind: 
minikube

* Are you writing your operator in ansible, helm, or go?
go

**Possible Solution**

The generated deployment manifests already use the `OPERATOR_NAME` environment variable. This could be used to choose the lock id programmatically, for example:
```golang
	// Become the leader before proceeding
	operatorName := os.Getenv("OPERATOR_NAME")
	if len(operatorName) == 0 {
		operatorName = "{{ .ProjectName }}"
	}
	err = leader.Become(ctx, operatorName+"-lock")
```

**Additional context**

The operator in question reads secrets from an external source (like AWS Secrets Manager, 1Password, etc.) and injects them as Kubernetes `Secrets`. To increase the level of isolation I depend on RBAC and namespace scope, for this reason I would like to keep multiple operators in the same namespace while allowing them to watch only one namespace, not necessarily the one they are deployed in.

I can consistently reproduce the issue following these steps:
```
git clone https://github.com/ContainerSolutions/externalsecret-operator
cd externalsecret-operator
kubectl create namespace operators
kubectl create namespace dev1
kubectl create namespace dev2

helm upgrade --install dummy1 --wait \
    --namespace operators \
    --set watchNamespace="dev1" \
    --set secret.data.Name="dummy1" \
    --set secret.data.Type="dummy" \
    --set secret.data.Parameters.suffix="-dummy1" \
    ./deploy/helm/.

helm upgrade --install dummy2 --wait \
    --namespace operators \
    --set watchNamespace="dev2" \
    --set crds.create=false \
    --set secret.data.Name="dummy2" \
    --set secret.data.Type="dummy" \
    --set secret.data.Parameters.suffix="-dummy2" \
    ./deploy/helm/.
```

**Comment by riccardomc** [comment]
Please let me know if this is a valid bug and the proposed solution is adequate. I would like to try contributing a PR if necessary.

**Comment by joelanford** [comment]
@riccardomc I don't think this is a bug since the leader election mechanism is actually working as intended. The `main.go` that the SDK scaffolds is meant to cover the general use case (i.e. don't let two operator instances compete to watch and reconcile the same set of resources).

In your use case, you're watching separate sets of resources, so you can edit your `main.go` to generate an appropriate lock name.

As you mentioned, you could update your `main.go` to look like:

```go
	operatorName := os.Getenv("OPERATOR_NAME")
	if len(operatorName) == 0 {
		operatorName = "externalsecret-operator"
	}
	err = leader.Become(ctx, operatorName+"-lock")
```

**Comment by riccardomc** [comment]
Ok, thank you. I thought it would be useful for the scaffolding to support this use case but I also see the value in keeping it simple and target the general use case.

I will implement the solution you suggested in our case. Closing.
