### ISSUE TITLE
Unknown field 'Repo' in struct literal of type "vendor/sigs.k8s.io/controller-tools/pkg/crd/generator".Generator

### ISSUE THREAD

**Issue by pawelzny** [operator-framework/operator-sdk#1591]
## Bug Report

`scaffold.CustomRender()` method tries to set unknown `Repo` field in `Generator` struct.
https://github.com/operator-framework/operator-sdk/blob/master/internal/pkg/scaffold/crd.go#L114

`Generator` does not have `Repo` field https://github.com/kubernetes-sigs/controller-tools/blob/v0.1.11/pkg/crd/generator/generator.go#L38

It results with error:

```
operator-sdk test local ./tests/e2e/...
INFO[0000] Testing operator locally.                    
# vendor/github.com/operator-framework/operator-sdk/internal/pkg/scaffold
vendor/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/crd.go:114:5: unknown field 'Repo' in struct literal of type "vendor/sigs.k8s.io/controller-tools/pkg/crd/generator".Generator
```

**What did you do?**

1. Update operator-sdk from v0.7.0 to v0.8.1
1. Run e2e tests `operator-sdk test local ./tests/e2e/...`

**Environment**

* operator-sdk version: **v0.8.1**
* go version: **go1.12.3 linux/amd64**
* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: **Standard Minikube cluster**
* Are you writing your operator in ansible, helm, or go? **GO**

**Possible Solution**

Removing line 114 solves the problem https://github.com/operator-framework/operator-sdk/blob/master/internal/pkg/scaffold/crd.go#L114

**Comment by hasbro17** [comment]
@pawelzny Can you please check what version or commit sha you have in your Gopkg.toml for controller-tools?

Did you manually update your controller-tools dependency to v0.1.11?
That was released last week and the SDK isn't using that in v0.7.0 or in v0.8.1.

In the SDK v0.8.1 we've have controller-tools pinned to a commit that has the Repo field in the generator.
- [SDK v0.8.1 Gopkg.toml scaffold](https://github.com/operator-framework/operator-sdk/blob/33b3bfe10176f8647f5354516fff29dea42b6342/internal/pkg/scaffold/gopkgtoml.go#L63-L65) using controller-tools [9d55346c2bde73fb3326ac22eac2e5210a730207](https://github.com/kubernetes-sigs/controller-tools/tree/9d55346c2bde73fb3326ac22eac2e5210a730207)
- generator.go with Repo field:  https://github.com/kubernetes-sigs/controller-tools/blob/9d55346c2bde73fb3326ac22eac2e5210a730207/pkg/crd/generator/generator.go#L41

**Comment by pawelzny** [comment]
@hasbro17 Thank you for your support. After controller-tools update to the hash you gave me everything started to work as expected.

In my Gopkg.toml file it looks like this:

```
[[override]]
  name = "sigs.k8s.io/controller-tools"
  revision = "9d55346c2bde73fb3326ac22eac2e5210a730207"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "=v0.8.1" #osdk_version_annotation
```

Since this solved my problem I am closing the issue.
