### ISSUE TITLE
Option to disable OCI image build

### ISSUE THREAD

**Issue by baijum** [operator-framework/operator-sdk#1599]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I want to build operator binary without producing OCI image.

**Describe the solution you'd like**
Introduce a `--without-image` for `operator-sdk build` command to disable building OCI image.

**Comment by camilamacedo86** [comment]
Closing this on based on the discussion made in the https://github.com/operator-framework/operator-sdk/pull/1600. Please, feel free to re-open if you wish or think that it is required.
