### ISSUE TITLE
Not able to deploy operator-helm CR

### ISSUE THREAD

**Issue by aman1989v** [operator-framework/operator-sdk#1602]
Firstly, I am not able to push the image using the below query 
<code># docker push quay.io/example/nginx-operator:v0.0.1 <br>
The push refers to repository [quay.io/example/nginx-operator] <br>
b00085e81020: Preparing <br>
dc5b6598c38d: Preparing <br>
f5f564a6c664: Preparing <br>
a9a9f6c83b12: Preparing <br>
d0bf58423527: Preparing <br>
97327e241a2a: Waiting <br>
5cb7ea77f481: Waiting <br>
unauthorized: access to the requested resource is not authorized </code>
Then, I used my quay.io credentials to the make the push <br>
Command: <code>docker push quay.io/veram04/nginx-operator:v0.0.1 </code> <br>
the above command worked 
Then I created the CR  using the below command <br>
# kubectl create -f deploy/crds/example_v1alpha1_nginx_cr.yaml<br>
nginx.example.com/example-nginx created<br>

but when I queried it didnt show any deployment and nginx-operator pod shows that it has not able to pull the image 
Can you please guide. <br>
<code>kubectl get deployment <br>
NAME             READY   UP-TO-DATE   AVAILABLE   AGE<br>
nginx-operator   0/1     1            0           2m32s<br>
 kubectl get pods<br>
NAME                              READY   STATUS             RESTARTS   AGE<br>
nginx-operator-6974c6d9db-qps9h   0/1     ImagePullBackOff   0          2m54s<br>

Error from server (BadRequest): container "nginx-operator" in pod "nginx-operator-6974c6d9db-qps9h"  <br> 
is waiting to start: trying and failing to pull image</code><br>

**Comment by joelanford** [comment]
@aman1989v The example namespace in quay is meant to just be an example, so you were correct to push the operator image with your own credentials.

The error you're getting (`trying and failing to pull image`) seems to indicate that the image name you're using in `deploy/operator.yaml` does not exist or is not accessible. Try setting it to `quay.io/veram04/nginx-operator:v0.0.1` and running `kubectl apply -f deploy/operator.yaml` again.
