### ISSUE TITLE
Is it necessary to manage our own observedGeneration field to trigger the reconcile loop?

### ISSUE THREAD

**Issue by gpanagiotidis** [operator-framework/operator-sdk#1603]
When reading the object's metadata, I can not find the observedGeneration field in the status of the object. how is the reconcile loop triggered? Can we exclude triggering on status change?

Another example would be not to trigger a reconcile when it is just the metadata that changes.

**Comment by AlexNPavel** [comment]
I don't believe it is possible to exclude triggering for only certain types of changes. The Kubernetes server sends all changes that occur to the operator that is watching the resource type, which is what triggers the reconcile loop.

**Comment by LiliC** [comment]
@gpanagiotidis 

> Another example would be not to trigger a reconcile when it is just the metadata that changes.

You can filter out events by using Predicates https://github.com/operator-framework/operator-sdk/blob/1b1ebc09edf6d967c96da6ea6318c8e555209846/doc/user/event-filtering.md

**Comment by gpanagiotidis** [comment]
Just commenting to say that I am using [operator-utils](https://github.com/redhat-cop/operator-utils) which manages the triggering of the reconcile loop.
