### ISSUE TITLE
'generate openapi' should mark optional fields as 'nullable'

### ISSUE THREAD

**Issue by jpkrohling** [operator-framework/operator-sdk#1609]
## Feature Request

When tagging fields as `optional`, arrays and pointers fail to be persisted back due to validation failures, complaining that those arrays/pointers aren't arrays or objects, but rather, null:

```
ERRO[0005] failed to store back the current CustomResource  error="Jaeger.jaegertracing.io \"simplest\" is invalid ... validation failure list:\nspec.storage.cassandraCreateSchema.enabled in body must be of type boolean: \"null\"
```

In the example above, `spec.storage.cassandraCreateSchema.enabled` is a `*bool`:

https://github.com/jpkrohling/jaeger-operator/blob/466-ValidateCR/pkg/apis/jaegertracing/v1/jaeger_types.go#L314-L331

I realize that this change probably belongs to `kubernetes/kube-openapi` or somewhere else, but as I'm not familiar with the internals, I'm reporting this to the component I'm interfacing with (operator-sdk).

**Comment by AlexNPavel** [comment]
Yes, this would likely have to involve a fix in `kube-openapi`, but maybe there's something we need to change on our side (maybe even a dependency version bump if this has been fixed upstream). I'm not to familiar with the openapi generation though.

/cc @estroz

**Comment by estroz** [comment]
@jpkrohling I assume you're still experiencing this issue because we have not changed `kube-openapi`'s version in the SDK. Can you describe:

1. `operator-sdk version`
1. What command you're running
1. What all logs looks like after running the command
1. What you expect to see

While this likely belongs in the `kube-openapi` repo, we might be able to help.

**Comment by jpkrohling** [comment]
We skipped this task for now, and we'll revisit this in the next few weeks. I'll let you know by then.

**Comment by camilamacedo86** [comment]
Hi @jpkrohling, 

Could you please let us know if it is something that still required? If yes, could you please provide the info requested above and if possible let us know if you are able to reproduce the same behaviour with the master branch?

**Comment by jpkrohling** [comment]
I just rebased that branch on top of the current Jaeger Operator's master, ran `operator-sdk generate openapi`, fixed whatever it complained about, and re-run the test from this issue, and it works now. Looks like something that was done between 0.8.1 and 0.10.0 has fixed the issue. This is the operator-sdk version I'm using right now: `operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170`.

I'm therefore closing this issue.
