### ISSUE TITLE
cmd/manager/main.go:119:11: undefined: metrics.ExposeMetricsPort

### ISSUE THREAD

**Issue by bingosummer** [operator-framework/operator-sdk#1619]
## Bug Report

**What did you do?**
Create and deploy an app-operator

**What did you expect to see?**
`operator-sdk new app-operator` should succeed.

**What did you see instead? Under which circumstances?**

```
$ operator-sdk new app-operator
INFO[0000] Creating new Go operator 'app-operator'.
INFO[0000] Created go.mod
INFO[0000] Created tools.go
INFO[0000] Created cmd/manager/main.go
INFO[0000] Created build/Dockerfile
INFO[0000] Created build/bin/entrypoint
INFO[0000] Created build/bin/user_setup
INFO[0000] Created deploy/service_account.yaml
INFO[0000] Created deploy/role.yaml
INFO[0000] Created deploy/role_binding.yaml
INFO[0000] Created deploy/operator.yaml
INFO[0000] Created pkg/apis/apis.go
INFO[0000] Created pkg/controller/controller.go
INFO[0000] Created version/version.go
INFO[0000] Created .gitignore
INFO[0000] Validating project
go: finding github.com/operator-framework/operator-sdk master
# github.com/bingosummer/app-operator/cmd/manager
cmd/manager/main.go:119:11: undefined: metrics.ExposeMetricsPort
Error: failed to exec []string{"go", "build", "./..."}: exit status 2
```
https://github.com/operator-framework/operator-sdk/pull/1560 breaks the released version. Please release a new version.

**Environment**
* operator-sdk version:
$ operator-sdk version
operator-sdk version: v0.8.0-46-gc8ead552, commit: c8ead552930d086056f779e8fdefa7f681c1e432

* go version:

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**

**Additional context**

**Comment by LiliC** [comment]
@bingosummer hello, yes this is expected, as stated in the [CHANGELOG](https://github.com/operator-framework/operator-sdk/blob/0fc57468390834f2424ffae982c1d869c21f14b7/CHANGELOG.md#removed) we have removed this and instead use `metrics. OperatorPortName`

Can you explain how you ran into this problem? As if I use master branch to create a new operator that works fine for me. Same if I use a release.

**Comment by bingosummer** [comment]
Thanks @LiliC for your quick response.
My bad. I thought I was using a release version. But actually I was using a version `v0.8.0-46-gc8ead552, commit: c8ead55` which is a version in master branch. I think, that's why I ran into the problem.
I've tried the latest master and v0.8.1, and both work.

BTW, the version is `v0.8.0-74-g4d7b8537` if building from source, but it's lower than the latest release v0.8.1. Is it expected? From my understanding, the dev version should be higher than the release version.

**Comment by LiliC** [comment]
@bingosummer building from source of master or a different branch?

**Comment by bingosummer** [comment]
master

**Comment by bingosummer** [comment]
https://github.com/operator-framework/operator-sdk/blob/master/version/version.go

**Comment by LiliC** [comment]
@bingosummer weird, I built from master as well and it worked fine for me. Can you provide details on how you built from master to get the above error, thanks!

**Comment by bingosummer** [comment]
The initial issue is gone. As I mentioned, `I've tried the latest master and v0.8.1, and both work.` So it worked fine for me. So I closed the issue.

A new question is about the version `https://github.com/operator-framework/operator-sdk/blob/master/version/version.go`. The version is lower than the version of the latest release v0.8.1. Just to confirm whether it's expected or not. :)

**Comment by LiliC** [comment]
>  The version is lower than the version of the latest release v0.8.1. Just to confirm whether it's expected or not. :)

Yes pretty sure that should have been updated, already pinged @joelanford who was doing the release in case there is a specific reason why it wasn't. Thanks for spotting that!
