### ISSUE TITLE
Missing wildcard arbitrary JSON object

### ISSUE THREAD

**Issue by nmiculinic** [operator-framework/operator-sdk#1624]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I want to support arbitrary JSON fields in the status of my CRD. When I try something like:

```go
type ServiceStatus struct {
	Example                  map[string]interface{} `json:"aa"`
}
```

and 
`operator-sdk generate openapi`

it screams with error `Unknown supported Kind Interface`

**Describe the solution you'd like**

Some wildcard, you're on your own go type which I can use for Arbitrary JSON object.

**Comment by BuddhiWathsala** [comment]
Seems like I'm also facing the same problem right now. I got the below error when I tried the above approach.

```
DeepCopy of "interface{}" is unsupported. Instead, use named interfaces with DeepCopy<named-interface> as one of the methods.
```

So I use something like this.
```
type Conf interface{
}

type ServiceStatus struct {
	Example map[string]Conf `json:"aa"`
}
```

This does not give an error when I changed the DeepCopyInto function in the generated `zz_generated.deepcopy.go` file. But this did not marshal the JSON properly and my `Example` entry was empty.

Any idea on how to achieve this thing in operator sdk?

**Comment by estroz** [comment]
@nmiculinic any `interface{}` type is not supported in `controller-tools <v0.2.0` [CRD generator](https://github.com/kubernetes-sigs/controller-tools/blob/464fbed97efaced33902e262f09c5eae7315c3e3//pkg/internal/codegen/parse/crd.go#L224). However we are in the process of upgrading to `v0.2.0` which does support `interface{}`.

@BuddhiWathsala your issue has a different source because it deals with Golang's `interface{}` semantics. Because an `interface{}` has some underlying type that is statically opaque to the go compiler, there needs to be a `DeepCopyConf` method for `type Conf interface`:

```Go
type ServiceStatus struct {
	Example map[string]Conf `json:"example"`
}

type Conf interface {
	DeepCopyConf() Conf
}

type conf struct {
	c interface{}
}

func (c *conf) DeepCopyConf() Conf {
	o := &conf{}
	*o = *c
    // interface-specific copying here
	return o
}
```

which allows `ServiceStatus.DeepCopyInto()` to compile.

**Comment by estroz** [comment]
@BuddhiWathsala if you have an *external* interface you want `deepcopy-gen` to implement, add the following to your `<kind>_types.go`:

```go
// +k8s:deepcopy-gen:interfaces=path.to/external/package.Conf

type YourKind struct {
    ...
}
```

It seems you do not need this annotation though. Check out [this blog post](https://blog.openshift.com/kubernetes-deep-dive-code-generation-customresources/) for more info if you do.

**Comment by hasbro17** [comment]
@nmiculinic If you were still waiting on this feature then it should be supported on the master branch via the bump to controller-tools `v0.2.0`
https://github.com/operator-framework/operator-sdk/pull/1876

We will cut a release for those changes hopefully soon but in the meanwhile you can test this out on a build from the master branch.

One thing to note is that one of the breaking changes is the change in CRD manifest name from `<group>_<version>_<kind>_crd.yaml` to `<full group>_<resource>_crd.yaml`.
https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md#breaking-changes
