### ISSUE TITLE
Ansible operator not deleting ImageStream on resource deletion

### ISSUE THREAD

**Issue by elmiko** [operator-framework/operator-sdk#1628]
## Bug Report

i am developing an operator based on the ansible instructions. as i am early in this work i have started by having my first task be creating an ImageStream that will be utilized during a deployment of the resource.

when i create my custom resource i see the operator creating the ImageStream, but when i delete the custom resource the ImageStream is not deleted.

**What did you do?**

1. deployed [this operator](https://gitlab.com/elmiko/stasis-reactor-operator) using the local method.
1. created a custom resource by applying the following manifest
    ```
    apiVersion: elmiko.dev/v1alpha1
    kind: StasisReactor
    metadata:
      name: example-stasisreactor
    spec:
      # Add fields here
      size: 3
    ```
1. deleted the resource created by the previous manifest.

**What did you expect to see?**

i expected the ImageStream that was created to be removed from the system.

**What did you see instead? Under which circumstances?**

the ImageStream is not removed from the system and persists.

here are the logs from the operator
```
$ operator-sdk up local
INFO[0000] Running the operator locally.                
INFO[0000] Using namespace sr.                          
{"level":"info","ts":1562011963.6475394,"logger":"cmd","msg":"Go Version: go1.12.5"}
{"level":"info","ts":1562011963.6475701,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1562011963.6475804,"logger":"cmd","msg":"Version of operator-sdk: v0.8.0+git"}
{"level":"info","ts":1562011963.6475987,"logger":"cmd","msg":"Watching namespace.","Namespace":"sr"}
{"level":"info","ts":1562011963.7717905,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1562011963.7719312,"logger":"leader","msg":"Skipping leader election; not running in a cluster."}
{"level":"info","ts":1562011963.871017,"logger":"metrics","msg":"Skipping metrics Service creation; not running in a cluster."}
{"level":"info","ts":1562011963.8717926,"logger":"proxy","msg":"Starting to serve","Address":"127.0.0.1:8888"}
{"level":"info","ts":1562011963.8725662,"logger":"manager","msg":"Using default value for workers 1"}
{"level":"info","ts":1562011963.8726327,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"elmiko.dev","Opti
ons.Version":"v1alpha1","Options.Kind":"StasisReactor"}
{"level":"info","ts":1562011963.8731115,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"stasisreactor
-controller","source":"kind source: elmiko.dev/v1alpha1, Kind=StasisReactor"}
{"level":"info","ts":1562011963.9743147,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"stasisreactor-
controller"}
{"level":"info","ts":1562011964.0748928,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"stasisreactor-con
troller","worker count":1}
{"level":"info","ts":1562012011.0980759,"logger":"logging_event_handler","msg":"[playbook task]","name":"example-stasisreactor","n
amespace":"sr","gvk":"elmiko.dev/v1alpha1, Kind=StasisReactor","event_type":"playbook_on_task_start","job":"2116603485980631332","
EventData.Name":"Gathering Facts"}
{"level":"info","ts":1562012012.1394017,"logger":"logging_event_handler","msg":"[playbook task]","name":"example-stasisreactor","n
amespace":"sr","gvk":"elmiko.dev/v1alpha1, Kind=StasisReactor","event_type":"playbook_on_task_start","job":"2116603485980631332","
EventData.Name":"stasisreactor : create imagestream"}
{"level":"info","ts":1562012012.927851,"logger":"proxy","msg":"Cache miss, can not find in rest mapper"}
{"level":"info","ts":1562012013.3716984,"logger":"runner","msg":"Ansible-runner exited successfully","job":"2116603485980631332","
name":"example-stasisreactor","namespace":"sr"}
```

**Environment**
* operator-sdk version:

```
$ operator-sdk version
operator-sdk version: v0.8.0-48-gc2b49e8f, commit: c2b49e8f6a0e1bb310f59be4447211332df292fd
```

* go version:

```
$ go version
go version go1.12.5 linux/amd64
```

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-06-20T16:29:27Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

ansible

**Possible Solution**

**Additional context**

based on [this documentation](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/finalizers.md)
> The default behavior of an Ansible Operator is to delete all resources the operator created during reconciliation when a managed resource is marked for deletion.

i was under the impression that the ImageStream would be deleted, do i need to write a finalizer role for this type of operation instead?

**Comment by elmiko** [comment]
just an update, i ended up adding a finalizer and i am able to delete the ImageStream. i am still curious about the underlying question of which resources _should_ the operator be deleting on its own.

**Comment by fabianvf** [comment]
Hmm, I would expect that it's deleted automatically, could you paste the ImageStream before and after deleting the CR?

**Comment by elmiko** [comment]
i think i have an error in my manifest that might be aggravating this issue. i am going to test again and i will post the imagestream before and after deleting the cr.

i have since implemented a finalizer role to cleanup everything, but i can disable it to see what happens.

**Comment by elmiko** [comment]
i have retested everything after finding the bug in my manifest, and it looks like what i was experiencing was an error based on me putting the wrong `apiVersion` for the `ImageStream` into my manifest.

this worked on deployment, but failed on cleanup. with the proper version string it is now working as i would expect. i am going to close this issue, thanks for the response @fabianvf
