### ISSUE TITLE
Support CRUD operations on unstructured objects

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#1630]
## Feature Request

**Is your feature request related to a problem?** 
No

**Describe the solution you'd like**
Would it be possible that the Operator SDK supports CRUD operations for unstructured objects
s we can do with the client-go

Example - see [1]
```
deploymentRes := schema.GroupVersionResource{Group: "apps", Version: "v1", Resource: "deployments"}

deployment := &unstructured.Unstructured{
	Object: map[string]interface{}{
		"apiVersion": "apps/v1",
		"kind":       "Deployment",
		"metadata": map[string]interface{}{
			"name": "demo-deployment",
		},
		"spec": map[string]interface{}{
			"replicas": 2,
			"selector": map[string]interface{}{
				"matchLabels": map[string]interface{}{
					"app": "demo",
				},
			},
			"template": map[string]interface{}{
				"metadata": map[string]interface{}{
					"labels": map[string]interface{}{
						"app": "demo",
					},
				},

				"spec": map[string]interface{}{
					"containers": []map[string]interface{}{
						{
							"name":  "web",
							"image": "nginx:1.12",
							"ports": []map[string]interface{}{
								{
									"name":          "http",
									"protocol":      "TCP",
									"containerPort": 80,
								},
							},
						},
					},
				},
			},
		},
	},
}

// Create Deployment
fmt.Println("Creating deployment...")
result, err := client.Resource(deploymentRes).Namespace(namespace).Create(deployment, metav1.CreateOptions{})
if err != nil {
	panic(err)
}
```

[1] https://github.com/kubernetes/client-go/blob/master/examples/dynamic-create-update-delete-deployment/main.go#L66-L111

**Comment by joelanford** [comment]
@cmoulliard You can use `controller-runtime`'s client with unstructured objects.

For example, from the default scaffolded reconciler, you could change [`newPodForCR`](https://github.com/operator-framework/operator-sdk/blob/d6903be02d4e8541e777b25af0498fe31e2e41e8/internal/pkg/scaffold/controller_kind.go#L260-L281) to return a `*unstructured.Unstructured` deployment (e.g. the `deployment` variable from your example).

Then you should be able to use [`r.client.Get`](https://github.com/operator-framework/operator-sdk/blob/d6903be02d4e8541e777b25af0498fe31e2e41e8/internal/pkg/scaffold/controller_kind.go#L241), [`r.client.Create`](https://github.com/operator-framework/operator-sdk/blob/d6903be02d4e8541e777b25af0498fe31e2e41e8/internal/pkg/scaffold/controller_kind.go#L244), etc. with your unstructured object just like any other type that implements `runtime.Object`.

The one caveat is that if you plan to use an unstructured CRD instance, you have to make sure that the CRD is registered with the scheme before the manager is started.

The helm and ansible operators are example of operators that do this: [here](https://github.com/operator-framework/operator-sdk/blob/d6903be02d4e8541e777b25af0498fe31e2e41e8/pkg/helm/controller/controller.go#L66) and [here](https://github.com/operator-framework/operator-sdk/blob/d6903be02d4e8541e777b25af0498fe31e2e41e8/pkg/ansible/controller/controller.go#L74).

**Comment by cmoulliard** [comment]
> The one caveat is that if you plan to use an unstructured CRD instance, you have to make sure that the CRD is registered with the scheme before the manager is started.

Great remark indeed ;-)

**Comment by estroz** [comment]
@cmoulliard is that a satisfactory solution or would you like to see more SDK functionality for unstructured CRUD?
