### ISSUE TITLE
operator-sdk test local ./test/e2e has fixed the name of the files instead of looking for types

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1631]
## Bug Report

The command `operator-sdk test local ./test/e2e --namespace $NAMESPACE` is looking for an specific name of rules files names instead of looking for types. 

**What did you do?**
When we run `operator-sdk test local ./test/e2e --namespace $NAMESPACE` it will look just for  
`deploy/service_account.yaml, deploy/role.yaml, deploy/role_binding.yaml and deploy/operator.yaml` and if the operator is cluster scope for example we will have `deploy/cluster_role.yaml, deploy/cluster_role_binding.yaml`. Also, we could have other roles as well. 

**What did you expect to see?**
The ./test/e2e run any *role file for example. 

**What did you see instead? Under which circumstances?**
If we have more roles files or use other names, for example, cluster_role.yaml to make clear the scope it will not work. 

```
 $ operator-sdk test local ./test/e2e 
INFO[0000] Testing operator locally.                    
WARN[0000] Could not find role manifest: (open deploy/role.yaml: no such file or directory) 
WARN[0000] Could not find role_binding manifest: (open deploy/role_binding.yaml: no such file or directory) 
```
**Environment**
* operator-sdk version:
operator-sdk version: v0.8.0, commit: 78c472461e75e6c64589cfadf577a2004b8a26b3

**Possible Solution**
- Looking for any file with the end _role.yaml.
- Here is the point: https://github.com/operator-framework/operator-sdk/blob/4564a35d12c7a9b2d9873751084c1a38879a4061/internal/util/yamlutil/manifest.go#L73

**Comment by LiliC** [comment]
Yes because it assumes the operator to be generated with operator-sdk, we use this pattern all over the place in operator-sdk.

cc @AlexNPavel

**Comment by camilamacedo86** [comment]
Hi @LiliC,

Thank you for check it.  However, after use, the operator-SDK to create the project users will grow it and has many needs which may lead them to have more than one rule file and more names because of it. 

Are not we suggesting for them use `operator-sdk test local ./test/e2e --namespace $NAMESPACEoperator-sdk test local ./test/e2e --namespace $NAMESPACE` to do the e2e test for the projects as well or just the scaffold?

**Comment by AlexNPavel** [comment]
The SDK test framework is designed to work based on the structure generated by the SDK, so by default we use the manifests that the SDK generates. This should work for both cluster scoped resources and namespaced resources as the filenames are supposed to stay the same (see this doc for changing a namespaced resource to a cluster scoped one: https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md#operator-scope; older versions of the SDK would generate cluster scoped resources using a flag, but newer version require you to do so manually. I believe the autogenerated cluster scoped resources made by the SDK used a slightly different name, so those files may need to be renamed).

If you have a different manifest structure, you can use the `--global-manifest` and `--namespaced-manifest` flags to specify a single manifest files containing all your resources. Creating one is shown briefly in the doc: https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/writing-e2e-tests.md#running-go-test-directly-not-recommended

**Comment by camilamacedo86** [comment]
Hi @AlexNPavel,

Thank you for your reply. Following few concerns and questions. Please, could you help me with?

1.  Regards

> This should work for both cluster scoped resources and namespaced resources as the filenames are supposed to stay the same (see this doc for changing a namespaced resource to a cluster scoped one: https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md#operator-scope;

The doc does not say that we should not change the name the file. IMHO: it just makes clear that we need to change the type of RBCA. Should not make more sense has a `cluster_rule.yaml` instead of `rule_yaml` in order to make clear the scope used/applied on it?  
 
2. **User is able to have 1 to Many rules files**. So, should not make sense change the e2e to apply any file in the deploy dir?

**Comment by camilamacedo86** [comment]
I am /remove-lifecycle stale since I think it still valid and if we are able to do it will be helpful to allow the project to be compatible with other structures/layouts as well. Hi @hasbro17 and @joelanford WDYT? should we keep this one or close it?
