### ISSUE TITLE
The leader has been waiting when the node where the operator is located is unknown

### ISSUE THREAD

**Issue by AllenZMC** [operator-framework/operator-sdk#1643]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).
```
err = leader.Become(ctx, "mongodb-operator-lock") 
	if err != nil {
		log.Error(err, "")
		os.Exit(1)
	}
```
**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
```
mongodb-operator-645c6f9c57-8jr78      1/1       Unknown   0          
mongodb-operator-787fd69bb-xv4zg       1/1       Running   0       

2019-07-04T05:43:07.358Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:43:23.497Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:43:41.445Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:43:58.325Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:44:17.001Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:44:36.085Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:44:55.094Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:45:11.879Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:45:30.226Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:45:48.758Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:46:06.238Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:46:23.335Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:46:41.036Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:47:00.257Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:47:17.428Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:47:34.236Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:47:50.400Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:48:08.936Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:48:27.366Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:48:45.489Z	INFO	leader	Not the leader. Waiting.
2019-07-04T05:49:02.207Z	INFO	leader	Not the leader. Waiting.
```

**Environment**
* operator-sdk version: 0.8.1

* go version: 1.12.6

* Kubernetes version information: 1.12.3

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**

**Additional context**

I found the problem here, this loop will continue to execute
```
//pkg/leader/leader.go
for {
		err := client.Create(ctx, cm)
		switch {
		case err == nil:
			log.Info("Became the leader.")
			return nil
		case apierrors.IsAlreadyExists(err):
			log.Info("Not the leader. Waiting.")
			select {
			case <-time.After(wait.Jitter(backoff, .2)):
				if backoff < maxBackoffInterval {
					backoff *= 2
				}
				continue
			case <-ctx.Done():
				return ctx.Err()
			}
		default:
			log.Error(err, "Unknown error creating ConfigMap")
			return err
		}
	}
```

**Comment by LiliC** [comment]
@AllenZMC What were you expecting to see, can you explain? It seems like it's correct from first glace. You have one opreator pod running and one is waiting as it's not the leader.

**Comment by AllenZMC** [comment]
pod `mongodb-operator-645c6f9c57-8jr78`  is Unknown
Then I logs the other running pod `mongodb-operator-787fd69bb-xv4zg`, it always output `Not the leader. Waiting` ，I  expect to see it become the leader ， but there is no

**Comment by LiliC** [comment]
@AllenZMC if you kill the other pod that is the leader does the unknown pod become the leader?

**Comment by AllenZMC** [comment]
@LiliC  Since the node unready causes the pod state to be unknown, I try to kill the pod, but it can't be killed

**Comment by AllenZMC** [comment]
@LiliC  My expectation is that when the node has a problem, the pod is regenerated. At this time, the unkown pod should give up the leader, and the newly generated pod gets the leader.

**Comment by LiliC** [comment]
@AllenZMC this is not an operator-sdk problem, but more a problem with kubernetes itself. If you have a look at this issue you can see others have been running into this before https://github.com/kubernetes/kubernetes/issues/55713

**Comment by AllenZMC** [comment]
@LiliC The k8s native election does not do this. It does not always hold a lock, it will be deleted periodically, and the unknown node will give up the lock.

**Comment by LiliC** [comment]
@AllenZMC  so you are saying you want changes to our leader election package to delete the pods periodically?

**Comment by AllenZMC** [comment]
Do you have to consider optimizing this leader election? When there is a problem with the operator pod, the leader will be abandoned, or the operator pod will only hold the leader for a certain period of time？
Thanks！

**Comment by LiliC** [comment]
cc @mhrivnak @shawn-hurley I believe you worked on leader election, WDYT of the above suggestion for the leader election lock to be released periodically. Maybe there could be enabled via an argument to the leader election.

**Comment by AllenZMC** [comment]
@LiliC  Look at the following paragraph, this is the user's guidance, is that what I mean?
`Leader-with-lease: The leader pod periodically renews the leader lease and gives up leadership when it can't renew the lease. This implementation allows for a faster transition to a new leader when the existing leader is isolated, but there is a possibility of split brain in certain situations.`

**Comment by mhrivnak** [comment]
If you need a leader that is running on a node whose status is unknown (hardware failure, network failure, etc) to quickly "stand down" as the leader, you should use lease-based leader election. But for most use cases, that is unnecessary.

If you find that your cluster is not rescheduling work from a failed node as quickly as you'd like, your effort will be better spent working on node lifecycle behavior to recover all kinds of workloads more quickly, rather than worry about individual operator leases. The problem of course is that the cluster doesn't know if the failed node is still running with broken network connectivity, or is actually dead.

By default, k8s will start rescheduling pods five minutes after losing contact with a kubelet, but that time is configurable. There are also ways, such as through a cloud-controller-manager, for your cluster to identify that a missing node is completely dead and automatically delete its pods quickly. It can either 1) passively ask the cloud environment if the node still exists and is powered on, or 2) actively power off the failed node and replace it. Those are by far the best recovery options.

**Comment by AllenZMC** [comment]
@mhrivnak  OK, thanks . I see
