### ISSUE TITLE
Fail To Make deepcopy code-generation

### ISSUE THREAD

**Issue by RnnyZhng** [operator-framework/operator-sdk#1644]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).
(1) Add one line to ~/go/src/github.com/example-inc/app-operator/pkg/apis/app/v1alpha1/appservice_types.go. Other files remaind unchange.

(2) The details are as following:
     type AppServiceSpec struct {
           Input string 'json:"input"'  //This is the new line.
    }

(4) cd ~/go/src/github.com/example-inc/app-operator

(5) operator-sdk generate k8s

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).
Answer: There should not be any error.

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).
![图片](https://user-images.githubusercontent.com/27443676/60656032-570dc200-9e81-11e9-9dc4-b14be3b2b5e3.png)

ERROR: INFO[0002] Running deepcopy code-generation for Custom Resource group versions: [app:[v1alpha1], ]
F0704 09:19:20.643435   11288 main.go:82] Error: Failed making a parser: unable to add directory "github.com/example-inc/app-operator/pkg/apis/app/v1alpha1": while parsing "/root/go/src/github.com/example-inc/app-operator/pkg/apis/app/v1alpha1/appservice_types.go": /root/go/src/github.com/example-inc/app-operator/pkg/apis/app/v1alpha1/appservice_types.go:16:22: illegal rune literal (and 1 more errors)
Error: failed to perform deepcopy code-generation: failed to exec []string{"/root/go/src/github.com/example-inc/app-operator/build/_output/bin/deepcopy-gen", "--input-dirs", "github.com/example-inc/app-operator/pkg/apis/app/v1alpha1", "--output-file-base", "zz_generated.deepcopy", "--bounding-dirs", "github.com/example-inc/app-operator/pkg/apis", "--go-header-file", "/tmp/399086793"}: exit status 255
Usage:
  operator-sdk generate k8s [flags]

Flags:
  -h, --help   help for k8s

Global Flags:
      --verbose   Enable verbose logging

**Environment**
* operator-sdk version:
operator-sdk version: v0.8.1, commit: 33b3bfe10176f8647f5354516fff29dea42b6342

* go version:

go version go1.12.6 linux/amd64

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?
go
**Possible Solution**

**Additional context**

**Comment by BuddhiWathsala** [comment]
Can you check your `$GOPATH` environment variable defined correctly?

**Comment by LiliC** [comment]
@RnnyZhng You need to write it the following way:

```
type AppServiceSpec struct {
        Input string `json:"input"` //This is the new line.
}
```

you were using ' but instead should be using `

**Comment by RnnyZhng** [comment]
> 
> 
> @RnnyZhng You need to write it the following way:
> 
> ```
> type AppServiceSpec struct {
>         Input string `json:"input"` //This is the new line.
> }
> ```
> 
> you were using ' but instead should be using `

It works, thank you so much.
