### ISSUE TITLE
Conform all helpers to be more like library functions

### ISSUE THREAD

**Issue by lilic** [operator-framework/operator-sdk#1645]
As per the discussion in https://github.com/operator-framework/operator-sdk/pull/1601#discussion_r300086228 we should do the same in other functions where we follow the same pattern.

>  This function and leader election (and probably others) have checks that can log and disable the function's intended purpose within the function, making them more helper functions that libraries.
> 
> Typically, libraries don't log and they return errors when the thing you asked them to do can't be done. So we have this question about what to do with these helpers.
> 
> My two cents is that we should make them more like libraries for two primary reasons:
> 
> It makes them more flexible outside the context of a main.go function.
> To make the case for upstreaming these into controller-runtime we need to make sure we conform to other controller-runtime style and design choices, which seems more library-centric than main.go-helper-centric.

**Comment by LiliC** [comment]
cc @joelanford

**Comment by camilamacedo86** [comment]
Hi @joelanford, 

Should we froze this one?

**Comment by estroz** [comment]
A lot of these libraries have changed/will be upstreamed. Closing.
