### ISSUE TITLE
add generate command client/informer/lister

### ISSUE THREAD

**Issue by mingzhuyang** [operator-framework/operator-sdk#1646]
## Feature Request

**Is your feature request related to a problem? Please describe.**

When using the operator-sdk generate command to generate code, it now only supports the generation of deepcopy and openapi. Whether code-generate informer, client and lister can be added to it.

**Describe the solution you'd like**

add operator-sdk generate client /operator-sdk generate informer /operator-sdk generate lister command

**Comment by hasbro17** [comment]
@mingzhuyang Thanks for the feature request.

Can you please outline your use case for needing a typed lister/informer/client?
Specifically what is something that you need the above 3 for that can't be done with the controller-runtime's existing Watch and dynamic client APIs.

**Comment by jhgaylor** [comment]
My use case is to be able to have a UI that shows the status of my custom resources. The way I do that today is to run `vendor/k8s.io/code-generator/generate-groups.sh all github.com/my/repo/pkg/client github.com/my/repo/pkg/apis "core:v1alpha1"`.

It took a lot of digging to put that together and I'm not sure it is the best way to generate the clientset much less the best way to access my CRs. I happened upon this ticket looking for "the answer" on this.

**Comment by hasbro17** [comment]
@jhgaylor That was always a bit of a hack to use the vendored code-generator script.
We're no longer vendoring the code-gen scripts in the operator project anymore though https://github.com/operator-framework/operator-sdk/pull/1470

For your use case however if you just want to look at the status of your CR then that should already be possible with the dynamic client by doing a `client.Get()` to get your CR object, and then looking at the status field. You don't need a typed clientset for that.

**Comment by hasbro17** [comment]
Closing this for now. Feel free to reopen if there is a use case for using generated CRD clients.
