### ISSUE TITLE
CRD scope reset to Namespaced on YAML generation

### ISSUE THREAD

**Issue by NicolasT** [operator-framework/operator-sdk#1650]
There's documentation on how to turn a scaffolded CRD into a cluster-scoped one, which works. However, when re-generating the OpenAPI CRD manifests, the CRD `scope` gets reset to `Namespaced`, which requires special care / manual reverts / ... It'd be nice if somehow the scope of a CRD could be declared somewhere, and this being honoured by the code generator.

For reference: https://kubernetes.slack.com/archives/CAW0GV7A5/p1562255836345700

**Comment by LiliC** [comment]
cc @hasbro17 What do you think of the above feature request, as you worked on the operator scopes.

**Comment by estroz** [comment]
@NicolasT add the type comment `// +genclient:nonNamespaced` to your kind and the scope will be set to `Cluster`, like so:

```Go
// Memcached is the Schema for the memcacheds API
// +k8s:openapi-gen=true
// +kubebuilder:subresource:status
// +genclient:nonNamespaced
type Memcached struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MemcachedSpec   `json:"spec,omitempty"`
	Status MemcachedStatus `json:"status,omitempty"`
}
```

Apologies for the lack of documentation on codegen annotations. We are in the process of refactoring the SDK to use controller-runtime/tools v0.2.0, which will have a complete list of new API annotations available that we will link to.

**Comment by hasbro17** [comment]
I'll update the cluster scope doc with the requirement of `// +genclient:nonNamespaced` tag.
But hopefully we should have a complete list of supported CRD generation tags documented soon.

**Comment by NicolasT** [comment]
That was fast :smile: I'll test this later today, but seems very reasonable, thanks for getting back! Looking forward to see more documentation about the available annotations.

Thanks again!
