### ISSUE TITLE
operator-sdk test local ./test/e2e --no-setup --namespace test failing to run

### ISSUE THREAD

**Issue by dipak-pawar** [operator-framework/operator-sdk#1657]
**What did you do?**
1. Running end to end tests using following command:
`operator-sdk test local ./test/e2e --no-setup --namespace test-namespace-25c86144-7275-475f-9c66-a3a511fba572 --go-test-flags "-v -timeout=15m"`
2. Logs can be found at https://storage.googleapis.com/origin-ci-test/pr-logs/pull/codeready-toolchain_member-operator/26/pull-ci-codeready-toolchain-member-operator-master-e2e/9/build-log.txt
 

**What did you expect to see?**

While running end to end tests, for operator having go modules enabled, looks like operator sdk couldn't able to identity `go.mod` file which is default mode, due to which it's assuming it doesn't exists and appending `-mod=vendor"` for go test. 

**What did you see instead? Under which circumstances?**
If I run `go mod vendor`, before running tests, it's working fine. but Ideally it should be able to resolve go modules.

**Environment**
* operator-sdk version:
`operator-sdk version: v0.8.1, commit: 33b3bfe10176f8647f5354516fff29dea42b6342`

* go version:
`go1.12.5`

* Kubernetes version information:
`v3.11.0+0cbc58b`

* Kubernetes cluster kind: 
minishift

**Possible Solution**
Maybe worth to add flag to pass to detect environment if won't be able to detect automatically dep manager.

code references
1. https://github.com/operator-framework/operator-sdk/blob/master/cmd/operator-sdk/test/local.go#L221
2. https://github.com/operator-framework/operator-sdk/blob/master/internal/util/projutil/project_util.go#L101

**Additional context**
 `operator-sdk build quay.io/codeready-toolchain/member-operator` is also failing

**Comment by AlexNPavel** [comment]
Hello. I've looked at the code and identified the problem. The issue you are having is present in the `v0.8.1` release, but has been fixed in master. We are preparing to release `v0.8.2` release, so I will make sure the fix gets into that release and will notify you when it is ready.

**Comment by dipak-pawar** [comment]
thank you @AlexNPavel

**Comment by estroz** [comment]
@dipak-pawar this issue will be fixed in `v0.9.0` rather than a patch release `v0.8.2`. We only support using [`vendor/`](https://github.com/operator-framework/operator-sdk/blob/v0.8.0/doc/user-guide.md#vendoring) in `v0.8.x`. Ability to use go modules without vendoring was a feature added [after](https://github.com/operator-framework/operator-sdk/commit/93175d31c7327732e3535ba84c39cadaee36c239#diff-f180fadbdf97ebe6db92e0f5f9099b68) `v0.8.0` was released.

`v0.9.0` will be released very soon.
