### ISSUE TITLE
[ansible] provide support for admission webhooks within ansible operators

### ISSUE THREAD

**Issue by jmazzitelli** [operator-framework/operator-sdk#1658]
_<tl;dr>_
Ansible operator needs access to the information about the user that created the CR so the operator can perform some validations based on permissions that user has. This is most likely going to require some kind of admission webhook functionality baked into the ansible operator SDK.
_</tl;dr>_

This kind of request has been mentioned in several issues, but mostly they discuss Go operators - such as:

- https://github.com/operator-framework/operator-sdk/issues/269
- https://github.com/operator-framework/operator-sdk/issues/1217
- https://github.com/operator-framework/operator-sdk/issues/1218
- https://github.com/operator-framework/operator-sdk/pull/1455

The only one that seems to broach this subject is:

- https://github.com/operator-framework/operator-sdk/issues/1308

But I want to create an issue that calls out a specific use-case to further define this feature request.

Specifically, this is dealing with the [Kiali Operator](https://github.com/kiali/kiali/tree/master/operator). For background, [Kiali](https://www.kiali.io/documentation/getting-started) is a front-end visualization/management tool for Istio/Maistra service mesh. The Kiali operator watches for a Kiali CR and based on what is in it, installs and configures Kiali (as any operator would do).

What is special is that the Kiali CR is used to configure Kiali so it has access to any namespace(s) within the cluster. You actually define what namespaces make up your service mesh by setting the Kiali CR's `spec.deployment.accessible_namespaces` (which is just a list of namespace names).  The operator will then create the necessary things that are needed for Kiali to probe and look into those namespaces listed in the Kiali CR (since Kiali is observing the mesh, it obviously needs to observe the mesh's namespaces and the resources in them).

However, we do NOT want user "foo" who creates namespace "foo" but has no permissions to see any other namespace to be able to create a Kiali CR in namespace "foo" and in that CR set `spec.deployment.accessible_namespaces` to "bar", essentially saying, "Hey, Kiali Operator - give Kiali access to the 'bar' namespace". This essentially will allow user "foo" to gain insight and access into namespaces that he has no permission to see (in that example, user "foo" doesn't have access to namespace "bar" so he should not be allowed to give Kiali access to the "bar" namespace).

So we need a validating webhook (or something like it) to say, "User 'foo' just created a Kiali CR that has `spec.deployment.accessible_namespaces` set to 'bar' - but user 'foo' doesn't have access to namespace 'bar' so I'm going to refuse to process this Kiali CR because user 'foo' is trying to give Kiali access to a namespace that user 'foo' has no permissions to see."

We allow users to create Kiali CRs in their own namespaces by supporting [InstallMode](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/building-your-csv.md#operator-metadata) of AllNamespaces (as well as OwnNamespace and SingleNamespace modes). We need to be able to have the operator support WATCH_NAMESPACE of "" (AllNamespaces installmode) because we want to allow any user to set up their own meshes within the cluster.

A temporary solution to the problem is just disallow AllNamespace installmode and just lock down the operator's watchnamespace and only allow admins to create Kiali CRs (with the implication that admins will only provide valid accessible namespaces in the Kiali CR).

To be clear, this is not a case where we want to restrict to only certain users the ability to create Kiali CRs. It is more subtle and fine-grained than that. It is more like "do not allow a user to create a Kiali CR that has names of namespaces in a spec value in the CR if the user doesn't have access to those namespaces". But ANY user should be allowed to create a Kiali CR, so long as they only configure its `spec.deployment.accessible_namespaces` setting to namespaces they (the user) have access to. The user can't put just any names of namespaces in the Kiali CR - if they do not have access to a namespace, they must not be allowed to mention it in the Kiali CR.

So this is where an admission webhook would be useful. It all hinges on the requirement that the ansible operator needs a way to get the information of the user that created the CR that the operator is watching for. If the ansible operator can just get the user information, it will be possible for the ansible playbook to perform the necessary tasks required to determine if that user is allowed to submit the CR or not.

So one feature enhancement to the ansible operator SDK would be to have its own, under-the-covers mutating webhook that simple takes the information of the user that created the CR and have the webhook store that user information in the CR's `status:` data. The operator would then be able to look at the `status:` data and perform SAR checks to make sure the user has permissions that the operator requires. That's just one idea. Perhaps there are ways in which we can do this - say, execute an ansible playbook as part of a mutating or validating webhook that the ansible operator sdk sets up under-the-covers?

For the record, here is Maistra's Go operator code that does the same "namespace" check I explain above  - it is making sure the user that created the CR has access to "update pods" in the named namespaces. This is the exact kind of check I would like ansible operators to be able to perform:

```
	sar := &authorizationv1.SubjectAccessReview{}
	sar.Spec.User = req.AdmissionRequest.UserInfo.Username
	copy(sar.Spec.Groups, req.AdmissionRequest.UserInfo.Groups)
	sar.Spec.ResourceAttributes = &authorizationv1.ResourceAttributes{
		Verb:     "update",
		Group:    "",
		Resource: "pods",
	}
	for _, member := range smmr.Spec.Members {
		if _, ok := namespacesAlreadyConfigured[member]; ok {
			return admission.ErrorResponse(http.StatusBadRequest, fmt.Errorf("one or more members are already defined in another ServiceMeshMemberRoll"))
		} else if smmr.Namespace == member {
			return admission.ErrorResponse(http.StatusBadRequest, fmt.Errorf("mesh project/namespace cannot be listed as a member"))
		}
		// verify user can access all smmr member namespaces
		sar.Spec.ResourceAttributes.Namespace = member
		err = v.client.Create(ctx, sar)
		if err != nil {
			logger.Error(err, "error processing SubjectAccessReview")
			return admission.ErrorResponse(http.StatusInternalServerError, err)
		}
		if !sar.Status.Allowed || sar.Status.Denied {
			return admission.ErrorResponse(http.StatusForbidden, fmt.Errorf("user '%s' does not have permission to access project/namespace '%s'", req.AdmissionRequest.UserInfo.Username, member))
		}
	}

	return admission.ValidationResponse(true, "")

```

**Comment by jmazzitelli** [comment]
Seems somewhat relevant but again does not seem to address Ansible implementations of operators:

https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/contributors/design-proposals/webhooks.md

**Comment by jmazzitelli** [comment]
I would like to bring this to the top again - this is an important feature that, without it, is going to cause a potential security issue with the kiali operator - there is no way for us to plug up this hole that I know of, short of having this feature implemented. The way we avoid any problems today is with our integration with the Maistra operator (which, itself, is implemented in Go and has an admission webhook that effectively performs the work for Kiali that kiali can't do itself).

**Comment by fabianvf** [comment]
I definitely see this as something that we need to figure out sooner than later, providing an easy way to get this functionality for operators in Ansible would close a big gap. 

I wonder if we could do something similar to the way that we map events to playbooks, where we allow you to write a webhook playbook that takes in the resource and use the playbook success/failure to determine whether to allow admission. We could then write a generic webhook handler and let users just worry about their Ansible logic.

**Comment by jmazzitelli** [comment]
We still want this. I believe work is ongoing to implement this so we should /remove-lifecycle stale.

**Comment by jmazzitelli** [comment]
/remove-lifecycle rotten

Where are we with this? I see the proposal PR is still open: https://github.com/operator-framework/operator-sdk/pull/2048

**Comment by fabianvf** [comment]
@jmazzitelli I began to implement the proposal in #2048 and it proved to be quite awkward and unwieldy, the document in #2685 has an alternate approach that I think will likely be much better
