### ISSUE TITLE
Can you drop apple from apple-darwin in release built?

### ISSUE THREAD

**Issue by etsangsplk** [operator-framework/operator-sdk#1669]
## Feature Request

**Is your feature request related to a problem? Please describe.**
It is much easier for script taht calles uname to get the running platform. It returns darwin not apple-darwin. People knows mac os is darwin anyway, adding apple on it is just making it more difficult to automate. There is no need to mention microsoft for windows ...

**Comment by LiliC** [comment]
That makes sense @etsangsplk to me.

cc @AlexNPavel wdyt?

**Comment by AlexNPavel** [comment]
What is the specific use case that would require the default SDK's binary filename to change? It shouldn't really affect anything. We are currently using the standard LLVM style multiarch tuple, which uses `x86_64-apple-darwin` and `x86_64-linux-gnu` for 64-bit macOS and GNU/Linux based systems respectively.
