### ISSUE TITLE
jinja2 (version 2.7.2) in the ansible operator image doesn't include selectattr filter `equalto`

### ISSUE THREAD

**Issue by gearoidibm** [operator-framework/operator-sdk#1676]
## Bug Report

**What did you do?**
Use the selectattr() filter in ansible role that uses the K8s module.
Snippet from the role
```
...
spec:
  replicas: "{{ (drinks | selectattr('kind', 'equalto', 'Tea') | first ).replicas | default(0) }}"
```
Snippet from the custom resource
```
spec:
  drinks:
  - kind: "Tea"
    name: "Earl Grey"
    replicas: 3
```

**What did you expect to see?**
Ansible role run

**What did you see instead? Under which circumstances?**
Ansible role fails with
```
TASK [order : For each drink type we have a Deployment, each pod is an instance of the drink] ***
task path: /opt/ansible/roles/order/tasks/main.yml:7
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TemplateRuntimeError: no test named 'equalto'
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Environment**
* operator-sdk version:

0.9.0

* go version:

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
`minikube version: v1.2.0`
* Are you writing your operator in ansible, helm, or go?
ansible
**Possible Solution**
upgrade the jinja2 in the docker image ?

**Additional context**
Operator was created with sdk 0.8.1.
Upgraded sdk to 0.9.0 and rebuilt the image.
The image is being built from the docker cache (with the exception of a new layer for change in the role file that added the `selectattr` filter).
The same line of filter code works in a regular ansible playbook.

Perhaps this is related ?
Other than upgrading the sdk is there other steps required when upgrading sdk ?
Can `operator-sdk build` be forced not to use the cache ?

Additional information from the ansible container log
```
ansible-playbook 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/openshift']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
```
Jinja version in the image is 2.7.2
```
pip show Jinja2
---
Metadata-Version: 1.1
Name: Jinja2
Version: 2.7.2
```
Seems the `eqaulto` test isn't in Jinja2.7.2 as per this [issue](https://github.com/pallets/jinja/issues/329)

**Comment by gearoidibm** [comment]
The `0.9.0` operator image also has Jinja2 version `2.7.2` and exhibits the same error:
```
---
Metadata-Version: 1.1
Name: Jinja2
Version: 2.7.2
```

**Comment by camilamacedo86** [comment]
Hi @gearoidibm,

I could not reproduce this issue with the latest release of the SDK which is version 0.11.0. In this way, I am closing this one. However, could you please feel free to re-open if you see that it still required.
