### ISSUE TITLE
Don't use global state

### ISSUE THREAD

**Issue by ericchiang** [operator-framework/operator-sdk#169]
https://github.com/coreos/operator-sdk/blob/01a1d22496f3344e750234bde022f7565d5d0fbe/pkg/k8sclient/client.go#L37-L45

https://peter.bourgon.org/blog/2017/06/09/theory-of-modern-go.html

**Comment by ericchiang** [comment]
cc @rithujohn191

**Comment by CSdread** [comment]
@hasbro17 @ericchiang is this PR in the direction you were thinking, i want to verify that it is the right direction and i will complete it and add unit tests.

https://github.com/CSdread/operator-sdk/pull/1

**Comment by hasbro17** [comment]
@CSdread I would hold off on that for now. Your PR is in the right direction but there's more to it than just making it a package level singleton.
The client is also used by the Watch API to create the informers which has it's own global state. So we're currently redesigning the sdk.Watch API into a controller package and the client will have to be part of that so it can be exposed to the handler. I will update this issue with more context on that once we have something more concrete on that front.

**Comment by hasbro17** [comment]
With #382 and the controller-runtime objects we don't have any implicit pkg level state backing global functions(for the client) anymore.
