### ISSUE TITLE
olm-catalog gen-csv generates invalid CSV (displayName/description)

### ISSUE THREAD

**Issue by dprince** [operator-framework/operator-sdk#1699]
## Bug Report

I generate a clusterserviceversion like this:

operator-sdk olm-catalog gen-csv --csv-channel default --operator-name keystone-operator --csv-version 0.0.2

When I try to create the resource it gives the following errors:

validation failure list:
spec.customresourcedefinitions.owned.displayName in body is required
spec.customresourcedefinitions.owned.description in body is required

**Comment by dprince** [comment]
I am able to use --from-version to pre-populate these fields. This may still be a bug as I would have expected the fields to be set to FIXME or something as a default where as right now they don't exist in the Yaml at all.

**Comment by camilamacedo86** [comment]
Hi @dprince I checked it now with the version: `operator-sdk version: v0.8.1, commit: 33b3bfe10176f8647f5354516fff29dea42b6342` and it is solved. In this way, could you please let us know:

1. What is the version of the operator-sdk used by you? (Run ` operator-sdk version`)
2. If it is lower than 8.1 then could you try to do the same with the latest one? 
3. Are you using the OpenAPI to generated the validations of your CRDs? (`operator-sdk generate openapi`). If not, could you try to generate these valuations and then re-run the command for the OLM?
See [here](https://github.com/aerogear/mobile-security-service-operator/blob/master/deploy/crds/mobilesecurityservice_v1alpha1_mobilesecurityserviceapp_crd.yaml) an example of this result and [here](https://github.com/aerogear/mobile-security-service-operator/blob/master/Makefile#L207) the command used.

**Comment by hasbro17** [comment]
Closing this issue for now since has been fixed for a while.
https://github.com/operator-framework/operator-sdk/blob/f509fcd6dfa8307b87aeb756ec64f1d83b3903c2/internal/pkg/scaffold/olm-catalog/csv.go#L203-L204
@dprince Feel free to reopen if it's still a problem in the latest versions.
