### ISSUE TITLE
Stale resource when removing properties from CR

### ISSUE THREAD

**Issue by pb82** [operator-framework/operator-sdk#1700]
## Bug Report

I have a CRD with a nested struct that looks like this:

```yaml
...
kind: Grafana
spec:
  config:
    log:
      mode: "console"
      level: "warn"
    dashboards:
      versions_to_keep: 2
...
```

 Updating nested properties, e.g. `versions_to_keep` and applying the resource works as expected. When removing the property only it also works as expected. But when i remove a whole section (e.g. the dashboards section along with all the keys in it) i receive a stale resource on the next reconciliation that still has the property set to it's value of 2.

The struct mapping this section looks like this:

```go
type GrafanaConfigDashboards struct {
	VersionsToKeep int `json:"versions_to_keep,omitempty" ini:"versions_to_keep,omitempty"`
}
```

**What did you do?**

I removed a property and all it's subproperties from a CR and applied the resource using `kubectl apply`

**What did you expect to see?**

I expected the values in the Golang struct to be reset to their default values (0 in that case since it's an integer type).

**What did you see instead? Under which circumstances?**

I received a stale resource still with the old value set.

**Environment**
* operator-sdk version:

0.9.0

* go version:

go version go1.12.1 linux/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-04-10T17:49:11Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: reproducable on OpenShift 3.11 and k3s

* Are you writing your operator in ansible, helm, or go? Go

**Comment by camilamacedo86** [comment]
Hi @pb82, 

Following a few questions.

1. If the CR was not applied before and you apply the CR without the whole dashboard section is it working as expected? 
2. When you do the operation of applying the CR with a value in the subsection, then you reply the CR without the whole dashboard section which you did not check this new state be applied with success did you saw any issue in the logs provided by the operator? If yes, could you provide them?
