### ISSUE TITLE
Error during building operator :- in.Spec.DeepCopyInto undefined (type spec has no field or method DeepCopyInto)

### ISSUE THREAD

**Issue by Man-Jain** [operator-framework/operator-sdk#1703]
On running the command `operator sdk build` fails with the following error 

`man-jain@manjain-pc:~/go/src/cello/cello-k8s-fabric-operator$ operator-sdk up local --namespace=default
INFO[0000] Running the operator locally.                
INFO[0000] Using namespace default.                     
# cello/k8s-fabric-operator/pkg/apis/app/v1alpha1
pkg/apis/app/v1alpha1/zz_generated.deepcopy.go:76:9: in.Spec.DeepCopyInto undefined (type spec has no field or method DeepCopyInto)
pkg/apis/app/v1alpha1/zz_generated.deepcopy.go:176:9: in.Spec.DeepCopyInto undefined (type orderers_specs has no field or method DeepCopyInto)
pkg/apis/app/v1alpha1/zz_generated.deepcopy.go:276:9: in.Spec.DeepCopyInto undefined (type peers_specs has no field or method DeepCopyInto)
Error: failed to build operator to run locally: (failed to exec []string{"go", "build", "-o", "build/_output/bin/cello-k8s-fabric-operator-local", "cello/k8s-fabric-operator/cmd/manager"}: exit status 2)`

The code for the types.go file is [here](https://github.com/Man-Jain/cello-k8s-fabric-operator/blob/master/pkg/apis/app/v1alpha1/peers_types.go) and others files are similar.

**Comment by Man-Jain** [comment]
The struct should be passed as a pointer in order to remove this error.

**Comment by M4R774** [comment]
I am facing similar issue. What do you mean, that struct should be passed as a pointer? @Man-Jain

**Comment by Man-Jain** [comment]
Checkout these as an example

https://github.com/hyperledger/cello/tree/master/src/agent/fabric-operator/pkg/apis/fabric/v1alpha1

**Comment by vimalk78** [comment]
> Checkout these as an example
> 
> https://github.com/hyperledger/cello/tree/master/src/agent/fabric-operator/pkg/apis/fabric/v1alpha1

@Man-Jain can you point out in comments how to fix the problem? it will be easier than going through the types in link

**Comment by Krex0r** [comment]
Anyone found a solution? Im trying to use a struct generated from swagger.

```go
import (
	"<path>/generatedstructre"
)

// ObjectSpec defines the desired state of Object
type ObjectSpec struct {
	generatedstructre // HERE

	// Name is the name of the Object
	Name string `json:"name"`
}
```

I tried the "the struct should be passed as a pointer (...)" but it isnt working ...

```go
import (
	"<path>/generatedstructre"
)

// ObjectSpec defines the desired state of Object
type ObjectSpec struct {
	*generatedstructre // HERE

	// Name is the name of the Object
	Name string `json:"name"`
}
```

or

```go
import (
	"<path>/generatedstructre"
)

// ObjectSpec defines the desired state of Object
type ObjectSpec struct {
	obh *generatedstructre // HERE

	// Name is the name of the Object
	Name string `json:"name"`
}
```

So now, my only solutions are

1. Manually write the DeepCopy() function **or**
2. Automatically add `// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object` on the generated swagger struct
3. ???

Any ideas/suggestions ?  🙏🏻

**Comment by byashimov** [comment]
I know this is an old thread, but for those who still looking for a solution: just add `// +kubebuilder:object:generate=true` at the top of your file or before struct name. [Docs](https://book.kubebuilder.io/reference/markers/object.html).
