### ISSUE TITLE
Help. How many goroutines are used to process CR in operator code generated by operator-sdk？

### ISSUE THREAD

**Issue by AllenZMC** [operator-framework/operator-sdk#1705]
Who can tell me this question, thanks!
```
Reconcile(Request) (Result, error)
```

**Comment by hasbro17** [comment]
@AllenZMC By default the SDK scaffolds each controller with the default [Controller options](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/controller#Options):
https://github.com/operator-framework/operator-sdk-samples/blob/c05e3bd2f942e879dff8eb6f7e4f19ca4970fafb/memcached-operator/pkg/controller/memcached/memcached_controller.go#L42-L45

Which means it uses the default value of 1 for `MaxConcurrentReconciles`.
You can update this as needed to increase the number of concurrent reconciles:
```Go
	c, err := controller.New("memcached-controller", mgr, controller.Options{Reconciler: r, MaxConcurrentReconciles: 2})
	if err != nil {
		return err
	}
```

Hopefully this answers your question. If not feel free to reopen the issue.
