### ISSUE TITLE
I'd like to see the CSV generated with `alm-examples` attribute in a pretty format 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1708]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have an issue when a CSV is created by the command `operator-sdk  olm-catalog` if I would like to change maintain the `alm-examples` generated because they are not in a pretty format. 

**Describe the solution you'd like**
Show it in a pretty format in order to improve the Maintenace ability and understatement. 

Following an example. 

Currently: 
<img width="1157" alt="Screenshot 2019-07-19 at 12 33 55" src="https://user-images.githubusercontent.com/7708031/61547401-ab887400-aa21-11e9-9e83-df080e67f285.png">

As I'd like to check it: 
<img width="815" alt="Screenshot 2019-07-19 at 12 34 18" src="https://user-images.githubusercontent.com/7708031/61547387-a9261a00-aa21-11e9-8ff1-271ec5e1ce56.png">

**Comment by camilamacedo86** [comment]
Hi, @shawn-hurley @jmrodri @hasbro17 @LiliC  wdyt?

**Comment by joelanford** [comment]
@camilamacedo86 I think this is a good idea. We would need to use the ["literal style" indicator](https://yaml.org/spec/1.2/spec.html#id2795688), which is a pipe (`|`) for this to work properly. Not sure if our YAML marshaller supports that.

```yaml
annotations:
  alm-examples: |
    [
        {
            "apiVersion": "mobile-security-service.aerogear.com/v1alpha1"
            ...
        }
    ]
```

Would you be interested in investigating and submitting a PR?

**Comment by camilamacedo86** [comment]
Hi @joelanford,

I believe that it https://github.com/operator-framework/operator-sdk/pull/1793 could work but I need to test it. I will let you know when I finish it.

**Comment by camilamacedo86** [comment]
Hi @joelanford,

Really tks for your help. It is working now. Please, feel free to review.

**Comment by camilamacedo86** [comment]
Done and merged. 👍
