### ISSUE TITLE
Option --max-workers is not working on v0.9.0

### ISSUE THREAD

**Issue by kvaps** [operator-framework/operator-sdk#1714]
## Bug Report

**What did you do?**
Start operator-sdk with --max-workers option

```
/usr/bin/operator-sdk run ansible --watches-file=/opt/ansible/watches.yaml --max-workers=10 --zap-devel
```

**What did you expect to see?**
```
INFO    kubebuilder.controller  Starting workers        {"controller": "moonshotnode-controller", "worker count": 10}
```

**What did you see instead? Under which circumstances?**
```
INFO    kubebuilder.controller  Starting workers        {"controller": "moonshotnode-controller", "worker count": 1}
```

**Environment**
* operator-sdk version:

```
operator-sdk version: v0.9.0, commit: 560208dc998de497bbf59fea1b63426aec430934
```

* go version:

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**

**Additional context**

**Comment by fabianvf** [comment]
@jmrodri any idea why this might be happening?

**Comment by jmrodri** [comment]
That's definitely odd, I'll take a look.

**Comment by wondersong** [comment]
@jmrodri 
Hi Jesus
I attempted it using latest build quay.io/operator-framework/ansible-operator:master
whatever set maxWorkers: 10 in watches.yaml or add ENTRYPOINT ["/usr/local/bin/entrypoint", "--max-workers=10"] in Dockerfile. the operator still start 1 worker 
```
{"level":"info","ts":1568192803.755292,"logger":"cmd","msg":"Go Version: go1.12.7"}
{"level":"info","ts":1568192803.756442,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1568192803.7564585,"logger":"cmd","msg":"Version of operator-sdk: v0.10.0+git"}
{"level":"info","ts":1568192803.7564964,"logger":"cmd","msg":"Watching namespace.","Namespace":"bais-project"}
...

{"level":"info","ts":1568192838.7122517,"logger":"proxy","msg":"Starting to serve","Address":"127.0.0.1:8888"}
{"level":"info","ts":1568192838.8153512,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"appcluster-controller"}
{"level":"info","ts":1568192838.9310238,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"appcluster-controller","worker count":1}
```
The latest ansible-operator:master image dose not include this fix? If not, which one image will have it. Thank you.

**Comment by asmacdo** [comment]
Using base image:
FROM quay.io/operator-framework/ansible-operator:v0.10.0

Looks like max-workers is not being respected:

```bash
$ ansible-operator run ansible --watches-file /opt/ansible/watches.yaml --max-workers 10`
...
{"level":"info","ts":1570740830.0672555,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"memcached-controller","worker count":1}
```

**Comment by asmacdo** [comment]
This issue is fixed in master, but needs to be backported to v0.10.x

https://github.com/operator-framework/operator-sdk/pull/2050

**Comment by camilamacedo86** [comment]
The solution here is to upgrade to use the latest versions where has the fix. See: 

<img width="936" alt="Screenshot 2020-01-07 at 08 28 38" src="https://user-images.githubusercontent.com/7708031/71880232-c1046e00-3127-11ea-87e8-b3f087385ec9.png">

Closing this one. @asmacdo, please feel free to re-open if you see that it still required.
