### ISSUE TITLE
Resolve dependencies manager detects conflicting when mixing dep and module in one project  

### ISSUE THREAD

**Issue by dmvolod** [operator-framework/operator-sdk#1738]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We had a problem (right now, we used a workaround) in camel-k problem https://github.com/apache/camel-k
When project could use in the same time mixing dep and module dependencies managers, the 'operator-sdk build' command always use dep whether GO111MODULE set or not. 
Right now, dependencies manager detection mechanism starts with looking for gopkgTOMLFile or goModFile and next for just GO111MODULE.

**Describe the solution you'd like**
It would be nice to change priority for detecting dependencies manager.
- first, look for GO111MODULE settings
- if it set to "on" check for goModFile
- if not set or set to auto, look for goModFile or gopkgTOMLFile

I'm ready to provide fix for this solution. Any feedback's are appreciate.

**Comment by dmvolod** [comment]
@shawn-hurley , @jmrodri, @hasbro17 @LiliC could you please to look at this request. If it suitable, i can provide a PR for it. Thank you.

**Comment by dmvolod** [comment]
@joelanford could you please to look at this issue also?

**Comment by joelanford** [comment]
@dmvolod I'm not opposed to accepting a change for this (assuming @estroz agrees with the logic). However, we're planning to completely drop support for `dep` when Go 1.13 is released. If history is any indication, that should be sometime this month, so it might make sense to just wait for that.

**Comment by estroz** [comment]
@joelanford this priority change is ok with me. @dmvolod feel free to submit a PR, or I can whip one up. Thanks!

**Comment by dmvolod** [comment]
Thanks @joelanford and @estroz for response.
I will provide PR as well as submit a new issue related to the "dep drop support" and assign it with Go1.13 release milestone (https://github.com/golang/go/milestone/83) for tracking, and could help with it if possible.

**Comment by estroz** [comment]
@dmvolod the SDK has upgraded to go 1.13 and dropped support for `dep`/Gopkg.toml in new projects. We recommend upgrading to v0.12.0. If you still have trouble with your dual dependency management issue, feel free to submit a patch PR to the `v0.11.x` branch and we can look into getting that merged. I will reopen this issue if that is the case.
