### ISSUE TITLE
Invalid Go build tag generated in zz_generated.openapi.go

### ISSUE THREAD

**Issue by johananl** [operator-framework/operator-sdk#1747]
## Bug Report

**What did you do?**

```
operator-sdk new app-operator --repo github.com/example-inc/app-operator
cd app-operator
operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=AppService
head pkg/apis/app/v1alpha1/zz_generated.openapi.go
```

**What did you expect to see?**

A valid Go build tag. For example, the following build tag was generated by version `v0.8.2` of `operator-sdk`:

```go
// +build !ignore_autogenerated
```

**What did you see instead? Under which circumstances?**

The following build tag:

```go
// +build !
```

AFAIK the above isn't a valid build tag, which may have negative effects on the way the project is built.

**Environment**
* operator-sdk version:

`v0.9.0, commit: 560208dc998de497bbf59fea1b63426aec430934`

* go version:

go version go1.12.7 linux/amd64

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"archive", BuildDate:"2019-06-20T22:55:20Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Lokomotive

* Are you writing your operator in ansible, helm, or go?

Go

**Possible Solution**

**Additional context**

**Comment by joelanford** [comment]
I can confirm that I was able to reproduce this. It's strange because it doesn't look like our `kube-openapi` dependency changed between `0.8.2` and `0.9.0`

@estroz Any idea what might have changed?

**Comment by estroz** [comment]
@johananl @joelanford when the `kube-openapi` generator was directly imported, default arguments, which contains a default build tag, weren't used. #1757 uses default args to generate the build tag.
