### ISSUE TITLE
fileReady is not idempotent

### ISSUE THREAD

**Issue by mhrivnak** [operator-framework/operator-sdk#1760]
## Bug Report

**What did you do?**
call [`Set()`](https://github.com/operator-framework/operator-sdk/blob/v0.9.0/pkg/ready/ready.go#L47) twice in a row, or [`Unset()`](https://github.com/operator-framework/operator-sdk/blob/v0.9.0/pkg/ready/ready.go#L56) twice in a row. If an operator is going to intelligently change the value of its readiness probe during runtime, there is a chance that multiple events will result in the value being set or unset.

For example, consider a case where an operator starts and begins an upgrade workflow. It sets not-ready as requested by OLM. If something goes wrong and the operator exits with an error, the last thing that will happen in main.go (based on a `defer statement`) will be to call `Unset()`. That will result in an error, because the file will be not-found.

**What did you expect to see?**
No error returned.

**What did you see instead? Under which circumstances?**
Error returned

**Environment**
* operator-sdk version:
0.9.0

**Possible Solution**

If `Set()` finds that the file already exists, return `nil`.

If `Unset()` fails to unlink the file because it doesn't exist, return `nil`.

**Comment by jmrodri** [comment]
Assigned to myself to track the PR that @djzager has done.
