### ISSUE TITLE
Can I know the target date of next release?

### ISSUE THREAD

**Issue by YanFen-Guo** [operator-framework/operator-sdk#1766]
Hi There,
First thank you very much for this amazing tool. I'd like to know the schedule of next release because I noticed you changed the ansible-operator base image from ansible-runner to ubi, which is exactly the base image we need.
Thank you.

**Comment by hasbro17** [comment]
@YanFen-Guo We do patch releases as needed, and minor releases roughly every month. However the next `v0.10.0` release might still be a couple of weeks away.

Closing this out for now but feel free to follow up if we don't have a release out in the next 2 weeks.

**Comment by YanFen-Guo** [comment]
@hasbro17 Do you have a specific date or a more accurate time.... than couple of weeks?

**Comment by hasbro17** [comment]
@YanFen-Guo Sorry for the vague timing. Turns out we were able to make one sooner than expected.
https://github.com/operator-framework/operator-sdk/releases/tag/v0.10.0

**Comment by YanFen-Guo** [comment]
@hasbro17 Great, thanks a lot, this is really helpful!
