### ISSUE TITLE
Help. Is the client generated by operator sdk obtained from the cache when getting the k8s resource?

### ISSUE THREAD

**Issue by AllenZMC** [operator-framework/operator-sdk#1767]
Is the client generated by operator sdk obtained from the cache when getting the k8s resource?  Thanks.

See the following example code.   Is the `client.Get` method operating the data in the cache?
```
func newReconciler(mgr manager.Manager) (reconcile.Reconciler, error) {
 ...
	return &ReconcileFailover{
		client: mgr.GetClient(),
		scheme: mgr.GetScheme(),
        }
...
}

client.Get(context.TODO(), types.NamespacedName{})
```

**Comment by joelanford** [comment]
@AllenZMC The manager's default client is a split client. It reads from the cache and writes to the API.

**Comment by AllenZMC** [comment]
Thanks! @joelanford
