### ISSUE TITLE
Setup CI for operator-sdk

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/operator-sdk#177]
We need to setup continuous integration testing for the operator-sdk.

Action items:
- [x] Test scripts to run the generator unit tests locally
- [x] Setup up the CI with travis
- [x] Add a framework for running e2e tests on a k8s cluster
- [x] Add an e2e test for the user-guide example i.e build and test a memcached-operator using the SDK

**Comment by srleyva** [comment]
I'm up for writing some integration tests

**Comment by theishshah** [comment]
PR #322 adds a full build of the user-guide example to travis

**Comment by hasbro17** [comment]
With #346 we have a CI in place with an e2e test that runs through the user-guide example.
