### ISSUE TITLE
operator-sdk build without creating image

### ISSUE THREAD

**Issue by bekircanagaoglu** [operator-framework/operator-sdk#1785]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have an issue when I am trying to build an operator inside docker because `operator-sdk build <image>` command also creates an image. I couldn't find any option just builds the project.

Here is what I am trying to do. Example psudo-Dockerfile:
`#build the operator`
`FROM golang as builder`
`COPY <project>`
`ADD <url>/operator-sdk`
`RUN cd <project> && operator-sdk build`
` #create release container`
`FROM golang`
`COPY --from=builder <project>/build/bin`
`COPY --from=builder <project>/build/_output`
`... other stuff`

**Describe the solution you'd like**
Do not create image option in `operator-sdk build` command.

**Comment by joelanford** [comment]
@bekircanagaoglu we're planning to transition to a Makefile based approach, so we're not adding new flags or features to the existing `build` CLI subcommand. See discussion in #1600 and #1655
