### ISSUE TITLE
Generating CRDs kubebuilder book link broken

### ISSUE THREAD

**Issue by Noah-Huppert** [operator-framework/operator-sdk#1786]
## Bug Report

**What did you do?**
```
operator-sdk add --api-version=example.com/v1 --kind=Example
cat pkg/apis/example/v1/example_types.go
```

The https://book.kubebuilder.io/beyond_basics/generating_crd.html link is broken in the generated `ExampleSpec` comment which explains how to add custom validation kubebuilder tags.

**What did you expect to see?**
When I followed the link in the generated code I expected to see documentation about kubebuilder validation tags.

**What did you see instead? Under which circumstances?**
![2019-08-06- 9-24-05](https://user-images.githubusercontent.com/3323504/62543448-f7158d00-b82b-11e9-997d-6adef985aa37.png)

**Environment**
* operator-sdk version: v0.8.2, commit: 28bd2b0d4fd25aa68e15d928ae09d3c18c3b51da

* go version go1.12.7 linux/amd64

* Kubernetes version information: 

```
% oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0-201905191700+7bd2e
5b-dirty", GitCommit:"7bd2e5b", GitTreeState:"dirty", BuildDate:"2019-05-19T23:52:43Z", G
oVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
% kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485
c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"archive", BuildDate:"2019-07-31T07:2
3:24Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
error: You must be logged in to the server ... SNIP
```

* Kubernetes cluster kind: OpenShift

* Are you writing your operator in ansible, helm, or go? Go

**Possible Solution**
https://book.kubebuilder.io/reference/generating-crd.html#validation

or 

https://book.kubebuilder.io/reference/markers/crd-validation.html

I couldn't find a page under the exact same section.

**Additional context**
N/a

**Comment by joelanford** [comment]
@Noah-Huppert Thanks for the report!

The v1 kubebuilder doc links moved to a new base URL: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html

This was fixed in the latest v0.9.0 release, so if you upgrade to that, new scaffolded APIs will have the correct link.

**Comment by joelanford** [comment]
See #1492

**Comment by Noah-Huppert** [comment]
@joelanford Has the operator-sdk switched off of GitHub releases? The latest release I can find is v0.8.2: 

![2019-08-07-12-11-20](https://user-images.githubusercontent.com/3323504/62638951-7e3a3200-b90c-11e9-9367-aa2491c779a6.png)

**Comment by joelanford** [comment]
Nope, `v0.9.0` is there. We just released a patch release for `0.8.x` more recently. Github orders releases chronologically, not by semver.

https://github.com/operator-framework/operator-sdk/releases/tag/v0.9.0

**Comment by Noah-Huppert** [comment]
Oh wow my bad, thank you for pointing that out.

**Comment by joelanford** [comment]
:smile: No worries!
