### ISSUE TITLE
Customizable Dockerfile

### ISSUE THREAD

**Issue by fanminshi** [operator-framework/operator-sdk#179]
Currently, the `Dockerfile` used for build the operator image under the `tmp/build/` is pre-generated with `alphine-3.6` as the base image. User might want to customize how their operator image is built. We need to provide a way for user to customize the image.

A workaround for this is to change the `tmp/build/Dockerfile` directly and invoke `operator-sdk build $image` to build the image based on the modify the `Dockerfile`. Underneath, `operator-sdk build` command simply calls `tmp/build/docker_build.sh` which in turn builds the docker image based on the `tmp/build/Dockerfile`.

**Comment by spahl** [comment]
Closing in favor of #184
