### ISSUE TITLE
how to declare nested map in CRD yaml

### ISSUE THREAD

**Issue by ffoysal** [operator-framework/operator-sdk#1795]
## Type of question

**how to implement a specific feature, or about general context and help around the operator-sdk**

## Question

**What did you do?**
```
type MyJobSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file
	// Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
	JobName       string `yaml:"jobName,omitempty"`
	Services     map[string]interface{} `yaml:"services,omitempty"`
}
```
expecting in custom resource yaml nested map can be defined
```
services:
  serv1:
    val: val3
    another:
      an_val: val4
.........
```

**What did you expect to see?**
`operator-sdk generate k8s` should be successful

**What did you see instead? Under which circumstances?**
it throws this exception 
```
 4009 deepcopy.go:750] DeepCopy of "interface{}" is unsupported. Instead, use named interfaces with DeepCopy<named-interface> as one of the methods.
```

**Environment**
* operator-sdk version:

  `operator-sdk version: v0.9.0, commit: 560208dc998de497bbf59fea1b63426aec430934`
* Kubernetes version information:

 ```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

docker-desktop, minikube

**Additional context**
Add any other context about the question here.

**Comment by camilamacedo86** [comment]
Hi @ffoysal,

I do not think that  `map[string]interface{}` will works. Instead of that, I think that you could use an object which represents what you would like to have. Something as: 

```go
type MyJobSpec struct {
         ...
	Services []Services `json:"services,omitempty"`
}

type Services struct {
	Name string `json:"name"`
	ID string `json:"id"`
}
```

**Comment by ffoysal** [comment]
Thank you @camilamacedo86 
yes I tried similar thing but did not solve my problem. What I would like to achieve is having a valid yaml documents under `services:`

**Comment by camilamacedo86** [comment]
HI @ffoysal,

I am not sure if I understood what you mean with  `What I would like to achieve is having a valid YAML document under services:`. 

Note that when we are working with k8s and/or OCP by editing any YAML file what we actually do is edit the values of attributes defined for the objects in these API's. So, for example, a Deployment YAML file configuration is an Object from K8s which is defined (see [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#deployment-v1-apps)), the YAML file is just a format for you are able to check it and change the values. 

In this way, in the CR's you are able to set the values of the specs(attributes) of your own object definition(CRD) of your own API which will be created by using the operator-framework. 

Following some examples with similar implementations like the suggested one which are working with success for you have an idea. 

* https://github.com/integr8ly/keycloak-operator/blob/master/pkg/apis/aerogear/v1alpha1/types.go#L80
* https://github.com/aerogear/mobile-security-service-operator/blob/master/pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservice_types.go#L78
* https://github.com/integr8ly/grafana-operator/blob/master/pkg/apis/integreatly/v1alpha1/grafanadashboard_types.go#L16

I hope that it helps you with.

**Comment by ffoysal** [comment]
Thank you very much @camilamacedo86 for nice references.
I am sorry for confusions, actually my intention to have valid yaml document under `services:` meaning to have similar kind of open yaml structure like helm values file for example https://github.com/helm/charts/blob/master/stable/mongodb/values.yaml. In other words under `services:` I will have any values that is supported by helm `values` file. As helm values file has an open structure similarly I dont have specific types what will go under `services:` for my task.

**Comment by joelanford** [comment]
@ffoysal 

```
4009 deepcopy.go:750] DeepCopy of "interface{}" is unsupported. Instead, use named interfaces with DeepCopy<named-interface> as one of the methods.
```

This error message basically means that the deep copy generators don't know how to copy `interface{}`, which makes sense, because `interface{}` can be _anything_.

It's telling you to declare an interface (e.g. `Values`) that includes a `DeepCopyValues()` method in the interface definition. While that would probably work for deep copy generation, I think you'd run into problems with that approach for CRD generation.

Rather, I think you can probably declare a typed `map[string]interface{}` that has a `DeepCopy()` method (that you have to implement yourself).

```go
type Values map[string]interface{}
func (v *Values) DeepCopy() *Values { ... }
// or func(v Values) DeepCopy() Values { ... }
```

**Comment by Finkes** [comment]
When I try the solution proposal I receive the following error:
```map values must be a named type, not *ast.InterfaceType```

Any ideas whether this has changed? At least it sounds like this was a proper solution in 2019 :-)

**Comment by ccremer** [comment]
I'm also very interested to know.
Previously, at least in K8s 1.18 we could do this:
```go
SyncItems []unstructured.Unstructured `json:"syncItems,omitempty"`
```
with a spec like
```yaml
  syncItems:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: test-data
```
But now that we want to upgrade our Operator to K8s 1.20, this doesn't work anymore (not sure if that would be already the case with 1.19). The property is empty:
```yaml
  syncItems:
    - {}
```
This creates errors all over the place when Operator tries to read/deserialize the JSON from the server.

**Comment by ccremer** [comment]
Actually, we "sort of" figured it out.

Using `unstructured.Unstructured` is fine, serialization and deserialization generally works with this type.
But, if the CRD is version `apiextension.k8s.io/v1` (with v1beta1 it works out of the box), then the server removes unknown fields. This can be counteracted by setting `// +kubebuilder:pruning:PreserveUnknownFields` on that field. However, since clients also do validation, resources need to be applied with `kubectl apply --validate=false`...

**Comment by ccremer** [comment]
We made it work even with validatation:
```go
type (
	SyncItems []SyncItem `json:"syncItems,omitempty"`

	// +kubebuilder:pruning:PreserveUnknownFields
	// +kubebuilder:validation:EmbeddedResource
	SyncItem unstructured.Unstructured
)

func (in *SyncItem) DeepCopyInto(out *SyncItem) {
	// controller-gen cannot handle the interface{} type of an aliased Unstructured, thus we write our own DeepCopyInto function.
	if out != nil {
		casted := unstructured.Unstructured(*in)
		deepCopy := casted.DeepCopy()
		out.Object = deepCopy.Object
	}
}

```
