### ISSUE TITLE
documentation suggestion -- when should we use which type of operator?

### ISSUE THREAD

**Issue by gregsheremeta** [operator-framework/operator-sdk#1797]
## Feature Request
documentation suggestion -- when should we use which type of operator?

As we were reviewing the different types of operators we could create, it wasn't clear when we should use Helm based operators vs Go based operators. For example, do we get more power and control with Go based? Helm seems simpler, but are there things we're unable to do later on if we use Helm?

**Describe the solution you'd like**
On the README and perhaps elsewhere, add high level advice about when to use which type.
```
Workflow
The SDK provides workflows to develop operators in Go, Ansible, or Helm.
<insert help here>
```

**Comment by estroz** [comment]
@gregsheremeta take a peek at this [capability level diagram](https://github.com/operator-framework/operator-sdk/blob/master/doc/images/operator-capability-level.png) for a decent overview of which operator has what level of control. This diagram should probably be put somewhere more visible than our `doc/images` dir.

**Comment by gregsheremeta** [comment]
> This diagram should probably be put somewhere more visible than our doc/images dir.

I'd suggest the front page README or front page of the docs.

**Comment by camilamacedo86** [comment]
With the merge of https://github.com/operator-framework/operator-sdk/pull/2070 I understand that we can close this one @estroz. WDYT?
