### ISSUE TITLE
Make '/tmp' better 

### ISSUE THREAD

**Issue by fanminshi** [operator-framework/operator-sdk#180]
The name tmp might cause a user to not to consider to put its content under version control. However, that's not the case, the `tmp/` folder contain necessary scripts for operator-sdk command to work such as `build` and `generate`. We probably need to think about a better naming scheme for the `/tmp` folder.

**Comment by spahl** [comment]
Note: if done right there is no reason for the tmp folder to exist.

**Comment by dmage** [comment]
> that no one should change

In theory yes, but in our operator we've changed it to fill the Version field based on the git data (`-ldflags "-X github.com/my/package/version.Version=$(git describe)"`).

**Comment by shawn-hurley** [comment]
Closed by #615
