### ISSUE TITLE
Add generate client command

### ISSUE THREAD

**Issue by robinbraemer** [operator-framework/operator-sdk#1802]
## Feature Request

It would be convenient to provide a `generate client/clientset` command to generate a versioned clientset.

**Comment by hasbro17** [comment]
@robinbraemer Thanks for opening the issue. Although this is probably a duplicate of #1646 so I'm going to close this and we can follow up over there.

In particular though I'd like to know the use case for using a generated clientset as opposed to the existing dynamic client.
