### ISSUE TITLE
Function AddToManagerFuncs is undefined 

### ISSUE THREAD

**Issue by danyollee** [operator-framework/operator-sdk#1809]
## Bug Report

**What did you do?**
I am running the standard command `operator-sdk build leed3mentor/example-operator:v0.0.1`

**What did you expect to see?**
I expected to see a successful build message.

**What did you see instead? Under which circumstances?**
I receive an error message that reads:

"# github.com/context/deployment-operator/pkg/controller
pkg/controller/add_sustain.go:9:2: undefined: AddToManagerFuncs"

**Environment**
* operator-sdk version:

operator-sdk version: v0.10.0-3-g9d6ffddc, commit: 9d6ffddcd86fba2bf56191b55f61215675aee3f1

* go version:

go version go1.12.6 linux/amd64

* Kubernetes version information:

v1.14.3

* Kubernetes cluster kind: 
Docker-for-Desktop

* Are you writing your operator in ansible, helm, or go?
Golang

**Possible Solution**

**Additional context**

**Comment by jmrodri** [comment]
I assumed this worked in a previous build? When I create a new operator the scaffolding adds `var AddToManagerFuncs []func(manager.Manager) error` to `pkg/controller/controller.go` for me.

**Comment by danyollee** [comment]
> I assumed this worked in a previous build? When I create a new operator the scaffolding adds `var AddToManagerFuncs []func(manager.Manager) error` to `pkg/controller/controller.go` for me.

You hit it on the nail. For some reason, my `pkg/controller/controller.go` file was non-existent. Adding it back solved my issue.
