### ISSUE TITLE
CLI should guide through version upgrades

### ISSUE THREAD

**Issue by baichinger** [operator-framework/operator-sdk#181]
The CLI should be able to guide the operator author in case of an upgrade to a newer version of the SDK:

1. Perform automatic migrations if possible.
2. Point out guidelines the author needs to tackle manually.

**Comment by spahl** [comment]
I agree with this. It will take a couple of revisions of this project for us to understand what a migration looks like. At that point we can start talking about more automatic and guided ways.

**Comment by bonhamcm** [comment]
Is there an update on this issue? There's been a few releases since June of 2018...

**Comment by LiliC** [comment]
@bonhamcm  We have migration docs and always mention any breaking changes in the CHANGELOG, so this can be closed. If you have any specific questions about the recent release feel free to open a new issue. Thanks!
