### ISSUE TITLE
How to migrate to modules for operator project that uses dep?

### ISSUE THREAD

**Issue by jsanda** [operator-framework/operator-sdk#1810]
## Type of question
building with `operator-sdk`

## Question
I have a project that was that currently uses dep and all dependencies are declared in Go.toml. I am trying to migrate to Go modules but not clear on how exactly to do this. Are there documented steps for this?

https://github.com/operator-framework/operator-sdk/pull/1566 mentions that new projects should use modules, but the PR does not mention what to do for existing projects that already use a vendor directory.

**Comment by jmrodri** [comment]
@jsanda Hey John, thanks for the question. I looked and didn't see anything either. I'll see what can be done.

**Comment by jsanda** [comment]
Hi @jmrodri. Nice to hear from you and thanks for helping out :)

The project is currently using v0.7.0 of operator-sdk. I was working on upgrading to v0.9.0. This resulted in some changes to the project's CircleCI configuration which we might be able to circumvent by migrating to modules. I have run into various dependency/build issues when I trying moving to module at v0.7.0 as well as at v0.9.0. I suspect that some of those bumps might be unavoidable so any guidance is greatly appreciated.

**Comment by jsanda** [comment]
Let me share what I m hitting in case it is of any help:

```
$ export GO111MODULE=on 
$ go mod init
go: creating new go.mod: module github.com/Orange-OpenSource/cassandra-k8s-operator
go: copying requirements from Gopkg.lock

$ operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [db:[v1alpha1], ]
F0810 13:07:52.075636   69813 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from github.com/Orange-OpenSource/cassandra-k8s-operator/pkg/apis/db/v1alpha1.CassandraCluster
goroutine 1 [running]:
k8s.io/klog.stacks(0xc002f14100, 0xc00030a480, 0xc5, 0x115)
	pkg/mod/k8s.io/klog@v0.3.1/klog.go:855 +0xb1
k8s.io/klog.(*loggingT).output(0x3ffc080, 0xc000000003, 0xc000329c00, 0x3e3ba28, 0xb, 0x375, 0x0)
	pkg/mod/k8s.io/klog@v0.3.1/klog.go:806 +0x2d9
k8s.io/klog.(*loggingT).printf(0x3ffc080, 0x3, 0x29c3d82, 0x2a, 0xc002484e88, 0x3, 0x3)
	pkg/mod/k8s.io/klog@v0.3.1/klog.go:705 +0x14e
k8s.io/klog.Fatalf(...)
	pkg/mod/k8s.io/klog@v0.3.1/klog.go:1256
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).doStruct(0xc002f00080, 0xc002eb0160, 0xc002eca730)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/examples/deepcopy-gen/generators/deepcopy.go:885 +0x7bf
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).generateFor(0xc002f00080, 0xc002eb0160, 0xc002eca730)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/examples/deepcopy-gen/generators/deepcopy.go:695 +0xc5
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).GenerateType(0xc002f00080, 0xc002dff380, 0xc002eb0160, 0x2c99d40, 0xc002f02360, 0x0, 0x0)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/examples/deepcopy-gen/generators/deepcopy.go:608 +0xe86
k8s.io/gengo/generator.(*Context).executeBody(0xc002dff380, 0x2c968c0, 0xc002ef2650, 0x2d0f5a0, 0xc002f00080, 0x60, 0x10)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/generator/execute.go:304 +0x11d
k8s.io/gengo/generator.(*Context).ExecutePackage(0xc002dff1a0, 0xc0002f2ba0, 0x24, 0x2ce7ae0, 0xc002ebff80, 0x0, 0x0)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/generator/execute.go:265 +0xbf7
k8s.io/gengo/generator.(*Context).ExecutePackages(0xc002dff1a0, 0xc0002f2ba0, 0x24, 0xc002ef07f0, 0x1, 0x1, 0x0, 0xc00043b290)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/generator/execute.go:51 +0xc5
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc0005685a0, 0xc002485810, 0x296a2c4, 0x6, 0x2a5f9d8, 0xc00014a820, 0x16)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/args/args.go:194 +0x2d7
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.deepcopyGen(0xc0000c7900, 0x3a, 0xc00034d3a0, 0x1, 0x1, 0x18, 0xc0006cb9b0)
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:94 +0x4d2
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.K8sCodegen.func1(0xc0000c7900, 0x3a, 0xc0000c7900, 0x3a)
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:53 +0x50
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.generateWithHeaderFile(0xc000281c60, 0x0, 0x0)
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/genutil.go:104 +0x178
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.K8sCodegen(0xc0005b0c80, 0x0)
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:54 +0x4a5
github.com/operator-framework/operator-sdk/cmd/operator-sdk/generate.k8sFunc(0xc0005b0c80, 0x401fc80, 0x0, 0x0, 0x0, 0x0)
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/generate/k8s.go:56 +0x156
github.com/spf13/cobra.(*Command).execute(0xc0005b0c80, 0x401fc80, 0x0, 0x0, 0xc0005b0c80, 0x401fc80)
	pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002fb680, 0x2c9b2e0, 0xc0002f7b00, 0x0)
	pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/main.go:85 +0x50f
```

**Comment by jsanda** [comment]
https://github.com/kubernetes/kubernetes/issues/79149 may be relevant.

**Comment by camilamacedo86** [comment]
HI @jsanda, 

It https://blog.callr.tech/migrating-from-dep-to-go-1.11-modules/ may help you with.

**Comment by joelanford** [comment]
@jsanda I'd typically recommend using the `operator-sdk print-deps` command, but that seems to be broken for go modules at the moment.

Instead you may be able to piece things together using our `go.mod` file template that `operator-sdk new` scaffolds.

https://github.com/operator-framework/operator-sdk/blob/560208dc998de497bbf59fea1b63426aec430934/internal/pkg/scaffold/go_mod.go#L40-L92

**Comment by jsanda** [comment]
Thanks for the reference @camilamacedo86. It was helpful.

Since I am upgrading a project on v0.7.0 I decided to create the example project at https://github.com/operator-framework/operator-sdk/tree/v0.7.0 and upgrade from it to see what happens. I was able to reproduce the error, but I think it was because I needed to run `go mod tidy`.

I then went back through the example app a second time and successfully upgraded. Here is a summary of my steps:

* Create operator project, `operator-sdk new app-operator`
* Generate api, `operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=AppService`
* Add controller, `operator-sdk add controller --api-version=app.example.com/v1alpha1 --kind=AppService`
* Upgrade to v0.9.0 of operator-skd and confirm by running `operator-sdk version`
* Update version operator-sdk in Go.toml
* `go mod init`
* `go mod tidy`
* `rm -rf vendor/`
* `rm -f Gopkg.lock Gopkg.toml`
* `operator-sdk generate k8s`

The first time I went through those steps but left out `go mod init` and the project failed to build after switching to modules and upgrading to v0.9.0.

I still have some errors in my project to resolve, but I think it is just a matter of sorting out some dependencies.

@joelanford thanks for the tip! Should help with resolving my errors.

**Comment by estroz** [comment]
@jsanda #1819 allows you to force dep manager type using `--dep-manager`, so you can migrate your project to the correct dep manager. Note this only works with `master` until we release again, and any project v0.10+ as deps have changed (slightly) over the last few releases. It may still work with a v0.9.0 operator though.
