### ISSUE TITLE
Metadata about Kubernetes/OpenShift

### ISSUE THREAD

**Issue by baichinger** [operator-framework/operator-sdk#182]
SDK should provide information about the Kubernetes distribution in use. The information should contain information like:

- `kubectl version`
- `oc version`
- `kubectl api-versions`
- ...

Use cases:
- Take appropriate measures if run on OpenShift.
- Determine if feature X is available.
- Different versions might require special handling. E.g. version upgrade / migrations.

**Comment by spahl** [comment]
While we could add some utilities for getting versions we believe probing for the capability/api is a safer pattern and would prefer supporting that. Happy to revisit given a concrete use case. Closing for now.

**Comment by delgod** [comment]
looks like operators started to implement own version detection functionality :(
yes, maybe it is better to probing the capability/api but sometimes it is hard to implement.

@spahl @LiliC Could you please reopen this issue?
