### ISSUE TITLE
Can't build using dep

### ISSUE THREAD

**Issue by math3vz** [operator-framework/operator-sdk#1823]
## Bug Report

**What did you do?**
Followed the used guide (https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md) using `--dep-manager=dep` but when I run `operator-sdk build myimage:0.1` It breaks. Using `go get` works fine.

**What did you expect to see?**
To build operator image

**What did you see instead? Under which circumstances?**
```$ operator-sdk build myimage:v0.0.1
# /path/to/vendor/contrib.go.opencensus.io/exporter/ocagent
vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go:297:35: cannot convert true (type untyped bool) to type "/path/to/vendor/github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1".ConstantSampler_ConstantDecision
vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go:297:35: invalid operation: csamp.Decision == true (mismatched types "/path/to/vendor/github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1".ConstantSampler_ConstantDecision and bool)
vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go:53:3: unknown field 'Descriptor_' in struct literal of type "/path/to/vendor/github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1".Metric
vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go:59:45: undefined: "/path/to/vendor/github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1".Metric_MetricDescriptor
vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go:67:11: undefined: "/path/to/vendor/github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1".Metric_MetricDescriptor
Error: failed to build operator binary: (failed to exec []string{"go", "build", "-o", "/$GOPATH/src//path/to/build/_output/bin/example-operator", "-gcflags", "all=-trimpath=/$GOPATH/src/github.com/linux-blog-demo", "-asmflags", "all=-trimpath=/$GOPATH/src/github.com/linux-blog-demo", "/path/to/cmd/manager"}: exit status 2)
```

**Environment**
* operator-sdk version:

``` $ operator-sdk version
operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170
```

* go version:

```$ go version
go version go1.12.7 linux/amd64
```

* Kubernetes version information:
``` $ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:14:38Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
Minikube

* Are you writing your operator in ansible, helm, or go?
Go

**Comment by estroz** [comment]
@math3vz I was not able to reproduce your issue with a new project and `operator-sdk` v0.10.0 (with APIs and controllers). Are you using an < v0.10.0 operator project with the v0.10.0 `operator-sdk` binary?

**Comment by math3vz** [comment]
@estroz I'm following the user guide (https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md)

Created the project with `operator-sdk new memcached-operator --dep-manager=dep`

**Comment by camilamacedo86** [comment]
Hi @math3vz,

Did you try to execute `dep ensure` before to do the `go get`?

**Comment by math3vz** [comment]
> Hi @math3vz,
> 
> Did you try to execute `dep ensure` before to do the `go get`?

Yep, same problem

**Comment by camilamacedo86** [comment]
HI @math3vz,

>  @math3vz I was not able to reproduce your issue with a new project and operator-sdk v0.10.0 (with APIs and controllers). Are you using an < v0.10.0 operator project with the v0.10.0 operator-sdk binary?

Could you provide the url for your repo? Is possible we are able to check it? Is publish public?

**Comment by math3vz** [comment]
> HI @math3vz,
> 
> > @math3vz I was not able to reproduce your issue with a new project and operator-sdk v0.10.0 (with APIs and controllers). Are you using an < v0.10.0 operator project with the v0.10.0 operator-sdk binary?
> 
> Could you provide the url for your repo? Is possible we are able to check it? Is it public?

This is my code right now: https://github.com/math3vz/memcache-operator

**Comment by estroz** [comment]
There are two issues with your operator project, the cause of the first I'm not sure of:

1. Your project's import paths do not contain a [repo](https://github.com/math3vz/memcache-operator/blob/master/cmd/manager/main.go#L14). Import paths should be `github.com/math3vz/memcached-operator/...`.
1. Your project's name is `memcache-operator` but import paths are `memcached-operator/...` (a naming mismatch will cause build errors).

Once I make these changes, I see the compilation errors you're getting. However when I follow the user guide, I do not see them. Note that you must be in your `$GOPATH/src` when using dep. I recommend re-installing `dep` v0.5.0, `rm -rf $GOPATH/pkg/dep`, and following the user guide again.

Also note that we plan to drop support for `dep` when go 1.13 releases. You definitely can still use dep for testing with `operator-sdk` < v0.10. Otherwise I recommend switching to Go modules.

**Comment by math3vz** [comment]
> There are two issues with your operator project, the cause of the first I'm not sure of:
> 
>     1. Your project's import paths do not contain a [repo](https://github.com/math3vz/memcache-operator/blob/master/cmd/manager/main.go#L14). Import paths should be `github.com/math3vz/memcached-operator/...`.
> 
>     2. Your project's name is `memcache-operator` but import paths are `memcached-operator/...` (a naming mismatch will cause build errors).
> 
> 
> Once I make these changes, I see the compilation errors you're getting. However when I follow the user guide, I do not see them. Note that you must be in your `$GOPATH/src` when using dep. I recommend re-installing `dep` v0.5.0, `rm -rf $GOPATH/pkg/dep`, and following the user guide again.
> 
> Also note that we plan to drop support for `dep` when go 1.13 releases. You definitely can still use dep for testing with `operator-sdk` < v0.10. Otherwise I recommend switching to Go modules.

Maybe de problem is with my `dep` version, I installed it with the command:  `$ curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh`

Running `$ dep version` I get the following output:
```
 $ dep version
dep:
 version     : devel
 build date  : 
 git hash    : 
 go version  : go1.8.3
 go compiler : gc
 platform    : linux/amd64
```

Not sure what devel means.

I just started working with Go and I thought `dep` was the best option for managing dependencies, I'll stick with Go modules, feel free to close the issue, thanks.

**Comment by estroz** [comment]
@math3vz `devel` points to the latest commit of `dep` (v0.5.4+) which should be fine. We say to reinstall `dep` because some users may have an old version.

I'm still curious why the vendor directory/Gopkg.lock file generated for your project does not contain the correct dependencies in your project. It may just be an environment issue. Glad modules works for you!
