### ISSUE TITLE
Status.Time always null after update

### ISSUE THREAD

**Issue by itdove** [operator-framework/operator-sdk#1824]
## Type of question

I'm trying to implement the ManagerError best practice explained here https://blog.openshift.com/kubernetes-operators-best-practices/#error
but when the CR is requeued the status.LastUpdate is always null.

## Question

**What did you do?**
Add a Status attribute to my CRD.
```
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// MyStruct is the Schema for the mystruc API
// +k8s:openapi-gen=true
// +kubebuilder:subresource:status
type MyStruct struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MyStructSpec   `json:"spec,omitempty"`
	Status MyStructStatus `json:"status,omitempty"`
}
...

type MyStructStatus struct {
	Message    string                   `json:"message,omitempty"`
	Reason     string                   `json:"reason,omitempty"`
	LastUpdate metav1.Time              `json:"lastUpdate,omitempty"`
}
```

Have this code to manage errors and requeue  as described https://blog.openshift.com/kubernetes-operators-best-practices/#error

```
func (r *ReconcileMyStruct) ManageError(sr *appv1alpha1.MyStruct, issue error) (reconcile.Result, error) {
	srLogger := log.WithValues("MyStruct.Namespace", sr.GetNamespace(), "MyStruct.Name", sr.GetName())
	var retryInterval time.Duration
	//  r.GetRecorder().Event(runtimeObj, "Warning", "ProcessingError", issue.Error())
	srLogger.Info("sr.Status", "sr.Status", sr.Status)
	lastUpdate := sr.Status.LastUpdate.Time
	lastPhase := sr.Status.Phase
	srLogger.Info("lastUpdate", "lastUpdate", lastUpdate.String())
	srLogger.Info("lastUpdate.IsZero()", "lastUpdate.IsZero()", lastUpdate.IsZero())
	srLogger.Info("lastPhase", "lastPhase", lastPhase)
	if lastUpdate.IsZero() || lastPhase != appv1alpha1.MyStructFailed {
		retryInterval = time.Second
	} else {
		retryInterval = sr.Status.LastUpdate.Sub(lastUpdate).Round(time.Second)
	}
	srLogger.Info("retryInterval", "retryInterval", retryInterval)
	requeueAfter := time.Duration(math.Min(float64(retryInterval.Nanoseconds()*2), float64(time.Hour.Nanoseconds()*6)))
	srLogger.Info("requeueAfter", "requeueAfter", requeueAfter)
	sr.Status = appv1alpha1.MyStructStatus{
		Message:    fmt.Sprintf("Error, retrying in %.2f sec", requeueAfter.Seconds()),
		Reason:     issue.Error(),
		Phase:      appv1alpha1.SubscriptionReleaseFailed,
		LastUpdate: metav1.Now(),
	}
	srLogger.Info("sr.Status", "sr.Status", sr.Status)

	err := r.client.Status().Update(context.Background(), sr)
	if err != nil {
		srLogger.Error(err, "unable to update status")
		return reconcile.Result{
			RequeueAfter: time.Second,
			Requeue:      true,
		}, nil
	}
	return reconcile.Result{
		RequeueAfter: requeueAfter,
		Requeue:      true,
	}, nil
}
```
**What did you expect to see?**
The lastUpdate variable having the metav1.Now() as value each time I reenter in the ManagerError method.

**What did you see instead? Under which circumstances?**

The lastUpdate value is null
Other attribute have the lasted updated values.

**Environment**
* operator-sdk version: `github.com/operator-framework/operator-sdk v0.9.1-0.20190724001845-d6e1aba9fa51`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5+icp-ee", GitCommit:"eb4df6c6fb47f5b4fd1ed8bfbfe2d0ed5ea636e1", GitTreeState:"clean", BuildDate:"2019-05-08T02:18:32Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by itdove** [comment]
Changed the code by adding a predicate to avoid reconcile on status update and seems ok now.

**Comment by hasbro17** [comment]
@itdove Glad to hear you were able to resolve the issue. Did you use the metadata.Generation to ignore status updates? If so, this might be of use to you:
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/predicate/predicate.go#L137

Based on your comment above I'm guessing there was probably something else in your reconcile loop that was overwriting the status when the CR got re-queued a second time after the first status update.

**Comment by itdove** [comment]
I used the standard predicate and implemented the update... https://github.com/kubernetes-sigs/controller-runtime/blob/d7467fcf9e1c5817231f2768ffd626a244f2221b/pkg/predicate/predicate.go#L27

but what you mentioned above is exactly what I need! Many Thanks

**Comment by kotyara85** [comment]
@itdove can you share what you changes in your code? Having the same issue with double updates after status changes

**Comment by itdove** [comment]
@kotyara85 I don't have the code handy anymore.
but I think I added a predicate to filter the reconcile and run the reconcile only when the spec change.

For example

```
	p := predicate.Funcs{
		UpdateFunc: func(e event.UpdateEvent) bool {
			subRelOld := e.ObjectOld.(*appv1alpha1.HelmChartSubscription)
			subRelNew := e.ObjectNew.(*appv1alpha1.HelmChartSubscription)
			return !reflect.DeepEqual(subRelOld.Spec, subRelNew.Spec)
		},
		DeleteFunc: func(e event.DeleteEvent) bool {
			return false
		},
	}

	err = c.Watch(&source.Kind{Type: &appv1alpha1.HelmChartSubscription{}}, &handler.EnqueueRequestForObject{}, p)

```

As the predicated is added in the watcher... the reconcile is only triggered when the "spec" change.

**Comment by kotyara85** [comment]
@itdove  thanks, I will look into predicate pkg
