### ISSUE TITLE
Upgrade controller-runtime to v0.2.0-x to support cluster-scoped owner

### ISSUE THREAD

**Issue by vincent-pli** [operator-framework/operator-sdk#1834]
## Bug Report

**What did you do?**
We try to watch a resource (`Deployment`) which is create by an cluster-scope resource (`Config`)
```
	err = c.Watch(
		&source.Kind{Type: &appsv1.Deployment{}},
		&handler.EnqueueRequestForOwner{
			IsController: true,
			OwnerType:    &op.Config{},
		})
```

**What did you expect to see?**
When delete the `Deployment`, the `reconcile` should receive request.

**What did you see instead? Under which circumstances?**
No request received.

**Environment**
* operator-sdk version:
Master

**Possible Solution**
Upgrade `controller-runtime` to v0.2.0-x

**Additional context**
See this pr in `controller-runtime`:https://github.com/kubernetes-sigs/controller-runtime/pull/274

**Comment by joelanford** [comment]
@vincent-pli We plan to upgrade SDK to use controller-runtime v0.2.0 when a stable release is made. We don't want to include `beta` or `rc` dependencies in SDK stable release dependencies. That said, we expect controller-runtime and controller-tools to have stable releases in the near future, and we'll follow with a release with those new versions.

If you’re really wanting to get started early, you can build SDK’s `refactor/controller-runtime-v0.2.0` branch from source and use that for now.
