### ISSUE TITLE
How to manage multiple resources with one controller

### ISSUE THREAD

**Issue by ffoysal** [operator-framework/operator-sdk#1836]
I am trying to create two k8s resources (namely `Job` and `Secret`) from a single CR. meaning the controller watches the primary resource (which is the CR) and create those two k8s resources. So when I delete my operator CRD, expecting all the resources created by operator also be deleted. But only one resource got deleted depending on the order the reference is set

`controllerutil.SetControllerReference(myOperator, newSecret, r.scheme)`
`controllerutil.SetControllerReference(myOperator, newJob, r.scheme)`

In this case only `newJob` got deleted while I delete the CRD.

I am not sure what is the best practice to create/manage multiple k8s resources using a single CRD/CR

In case if I have to create multiple controllers from a single CR then how to make sequential   dependencies between resources creation. Because to create `Job` the `Secret` must exist.

**Comment by hasbro17** [comment]
@ffoysal You have it right the first time.

Your operator should be using 1 controller for 1 primary resource(your CRD) and creating secondary resources(Job and Secret) with OwnerReferences set to their respective CRs.

Having only one two secondary resources type being set with the correct ownerref or not being garbage collected might be a bug elsewhere in the reconcile loop.

Can you share more about your reconcile loop on how you're setting the owner refs and then creating each object. Just the above two lines seem to be the correct way to set ownerrefs.

Can you also get the YAML output for your CR and secondary resources to see if the ownerref for the secondary objects is not being correctly set to your CR instance? e.g `kubectl get secret <secret-name> -o yaml`

**Comment by camilamacedo86** [comment]
Hi @ffoysal, 

Just to complement here, regards the following point:

> In case if I have to create multiple controllers from a single CR then how to make sequential dependencies between resources creation. Because to create Job the Secret must exist.
 
Note that the reconcile is a loop and it will not stop until all conditions are as expected. So, you just need to impl the checks. See [here](https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/controller/backup/controller.go#L161) an example. The Backup service(represented by the Backup CR/CRD) needs the Pod and Service created for the Database(represented by Postgresql CR/CRD). So, if it is not found it will be re-queued(the loop will not stop) until it is satisfied.

**Comment by ffoysal** [comment]
Thank you @hasbro17 and @camilamacedo86 .
I was able to create multiple resources by following [this](https://github.com/operator-framework/operator-sdk-samples/blob/bd30254f3a7e3943fdbae33e9b6992bce1e07755/vault-operator/pkg/vault/deploy_vault.go#L93) instead of using `controllerutil`
