### ISSUE TITLE
Move Dockerfile to the project root

### ISSUE THREAD

**Issue by matyix** [operator-framework/operator-sdk#184]
In case the operator implementation requires changes to be made to the Dockerfile (most likely) we'd commit the changes made to Dockerfile to GitHub. Since the Dockerfile generated by the **operator-sdk** is placed under `tmp/build` developers inadvertently may commit the whole `tmp/` directory which is not desirable. 

Suggest moving the Dockerfile at the root of the project.

**Comment by EronWright** [comment]
One option to consider is to invert the relationship between `docker build` and `operator-sdk build`.  In other words, use a multi-stage Docker build that first invokes `operator-sdk build` and then copies the build outputs into the final image.   This would provide an easy and natural way to customize the `Dockerfile`, and would make it possible to encapsulate the Operator SDK installation into an image.
