### ISSUE TITLE
In the future, what version of operator-sdk can modify the `LeaseDuration` in `leaderelection.LeaderElectionConfig`?

### ISSUE THREAD

**Issue by AllenZMC** [operator-framework/operator-sdk#1841]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: "I have an issue when (...)"
```
func (cm *controllerManager) startLeaderElection() (err error) {
	l, err := leaderelection.NewLeaderElector(leaderelection.LeaderElectionConfig{
		Lock: cm.resourceLock,
		// Values taken from: https://github.com/kubernetes/apiserver/blob/master/pkg/apis/config/v1alpha1/defaults.go
		// TODO(joelspeed): These timings should be configurable
		LeaseDuration: 15 * time.Second,
		RenewDeadline: 10 * time.Second,
		RetryPeriod:   2 * time.Second,
```
In the future, what version of operator-sdk can modify the `LeaseDuration`or `RenewDeadline` in `leaderelection.LeaderElectionConfig`?

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

**Comment by joelanford** [comment]
@AllenZMC I think this is an issue in controller-runtime, right? Looking at the code in [`0.2.0-rc.0`](https://github.com/kubernetes-sigs/controller-runtime/blob/8941d18f48f7f27a939031df9bb891f733cc6726/pkg/manager/manager.go#L121-L130), this is already fixed.

We're tracking the v0.2.0 changes in the [`refactor/controller-runtime-v0.2.0`](https://github.com/operator-framework/operator-sdk/tree/refactor/controller-runtime-v0.2.0) branch, which we'll merge into `master` once controller-runtime cuts a stable `v0.2.0` release, which should be pretty soon.

**Comment by AllenZMC** [comment]
@joelanford  Yes, I am looking forward to the integration of this feature. Thanks!
