### ISSUE TITLE
Pass env variables to ansible-runner

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/operator-sdk#1842]
## Feature Request

**env variables not passed to ansible-runner**
I'm using the ipa modules for Ansible and the credentials can be passed by env variable to the module. When I pass the env variables like IPA_USER and IPA_HOST to the container, I can see them in the container, but ansible-runner does not appear to have them and therefore my task fails due to lack of credentials.

**Provide environment variables to ansible-runner**
I'd like to have the environment variables passed to ansible-runner so that ansible modules can take advantage of them and make configuration of those modules quick and flexible.

I foresee the potential of not wanting to pass all the variables. Perhaps any variable prepended by ANSIBLE_ could be passed without the prefix? 

------
If I'm simply missing something that already exists to accomplish this effectively, I'd be glad to get some pointers and document.

**Comment by flickerfly** [comment]
I also tried mounting a secret to /runner/env/envvars with the contents, but am getting the same error.
```
---
IPA_USER: username
IPA_PASS: password
IPA_HOST: some.dns.name
```

**Comment by joelanford** [comment]
@flickerfly I'm not familiar with IPA at all, but I'm curious if these configurations belong in the operator, to be used globally across all CRs, or if it is possible/reasonable for different CRs to need to use different credentials, in which case, you could put them in the CR spec?

/cc @fabianvf

**Comment by flickerfly** [comment]
In this case, the operator is building up resources around a project. I want developers to be able to create a CR, but not have credentials to directly add users and groups to the authentication database (what the ipa module does). So I can't put these in the CR spec or it will leak outside its intended bounds.

**Comment by flickerfly** [comment]
I'm trying to find another way to accomplish this. It would be handy to know how ansible-runner is run from within the container so I can trigger it manually. I tried to find a Dockerfile for the base image, but that doesn't seem to be around.

**Comment by flickerfly** [comment]
Eventually, I figured out that you have to pass these to the "operator" container, not the "ansible" container. The Ansible container only seems to be displaying the logs of ansible runs. It doesn't actually run ansible.
