### ISSUE TITLE
Go operator doesn't shutdown gracefully on SIGTERM

### ISSUE THREAD

**Issue by aeb-sia** [operator-framework/operator-sdk#1843]
## Bug Report
The operator terminates immediately on SIGTERM
**What did you do?**
Start the built operator and press CTRL+C

**What did you expect to see?**
The operator wait for all reconcile loops to finish and then exit

**What did you see instead? Under which circumstances?**
The operators exits immediately interrupting the ongoing reconciles which leaves my kubernetes cluster in a dangling state.

**Environment**
* operator-sdk version:
0.9.0

**Comment by theishshah** [comment]
That is the expected behaviour for SIGINT (Control + C). SIGTERM and SIGINT are generally not handled by the operator and are expected to exit without clean up.

**Comment by joelanford** [comment]
Actually, I think this is supposed to be handled by controller-runtime's signal handler (which SDK uses), but there's a bug that causes the manager to return before the `Runnable`s have stopped.

See https://github.com/kubernetes-sigs/controller-runtime/issues/350

We'll pick this fix up when it makes it into a controller-runtime release.

**Comment by RobEarl** [comment]
Does https://github.com/kubernetes-sigs/controller-runtime/pull/967/ allow this to progress?
