### ISSUE TITLE
How to set custom validation on CRD using oneOf

### ISSUE THREAD

**Issue by ffoysal** [operator-framework/operator-sdk#1844]
I have a struct
```
type Volume struct {
	VolumeClaim string `json:"existingVolumeClaim,omitempty" yaml:"existingVolumeClaim,omitempty"`
	HostPath            string `json:"hostPath,omitempty" yaml:"hostPath,omitempty"`
}
```
In the CR the app should accept either `VolumeClaim` or `HostPath` not both. How to set this validation in the generated CRD. In terms functionality it will be similar to [oneOf](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) keyword

**Comment by joelanford** [comment]
@ffoysal There's currently ongoing discussion and work upstream to help with this problem. See https://github.com/kubernetes-sigs/controller-tools/pull/298

Since operator-sdk relies on controller-tools for OpenAPI generation, we'll need to pursue this feature upstream.
