### ISSUE TITLE
Generated package file with duplicate entry

### ISSUE THREAD

**Issue by jpkrohling** [operator-framework/operator-sdk#1846]
## Bug Report

**What did you do?**
```console
$ ls -l deploy/olm-catalog/
total 232
-rw-r--r--. 1 jpkroehling wheel    558  7. Mär 17:29 _generated.concat_crd.yaml
-rw-r--r--. 1 jpkroehling wheel 227721 13. Aug 11:39 jaeger.clusterserviceversion.yaml
-rw-r--r--. 1 jpkroehling wheel     83 20. Aug 17:32 jaeger.package.yaml
$ GO111MODULE=on operator-sdk olm-catalog gen-csv --csv-channel=stable --default-channel --csv-version=1.13.1
INFO[0000] Generating CSV manifest version 1.13.1       
INFO[0000] Fill in the following required fields in file deploy/olm-catalog/jaeger-operator/1.13.1/jaeger-operator.v1.13.1.clusterserviceversion.yaml:
	spec.keywords
	spec.maintainers
	spec.provider 
INFO[0000] Created deploy/olm-catalog/jaeger-operator/1.13.1/jaeger-operator.v1.13.1.clusterserviceversion.yaml 
INFO[0000] Created deploy/olm-catalog/jaeger-operator/jaeger-operator.package.yaml 
$ cat deploy/olm-catalog/jaeger-operator/jaeger-operator.package.yaml
channels:
- currentCSV: jaeger-operator.v1.13.1
  name: stable
- currentCSV: jaeger-operator.v1.13.1
  name: stable
defaultChannel: stable
packageName: jaeger-operator
```

Note the duplicate entry for `currentCSV`.

**What did you expect to see?**

```console
$ cat deploy/olm-catalog/jaeger-operator/jaeger-operator.package.yaml
channels:
- currentCSV: jaeger-operator.v1.13.1
  name: stable
defaultChannel: stable
packageName: jaeger-operator
```

**Environment**
* operator-sdk version: `operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170`
* go version: `go version go1.12.5 linux/amd64`
* Kubernetes version information:  not relevant, as those are "offline" operations
* Are you writing your operator in ~ansible, helm~, or *go*?

**Additional context**
Found while working on https://github.com/jaegertracing/jaeger-operator/issues/604

**Comment by jpkrohling** [comment]
Something similar happens when a new CSV is generated using `--from-version`, following the steps from #1847:

```yaml
channels:
- currentCSV: jaeger-operator.v1.13.1
  name: stable
- currentCSV: jaeger-operator.v1.13.2
  name: stable
defaultChannel: stable
packageName: jaeger
```

**Comment by camilamacedo86** [comment]
HI @jpkrohling,

It shows occurs because of the operator project `
 jaegertracing/jaeger-operator#604` is not respecting the layout of the files and dirs as expected by the framework. In order to ensure that the generated commands will work as expected is required keep the directories and files as defined in the standard. 

Could you try to remove from`
 jaegertracing/jaeger-operator#604` the currently olm-catalog dir and use the command to check if the same behaviour will still be faced? 

See that it should be as the following example: 

```
│   ├── deploy
│   │   ├── olm-catalog
│   │   │   └── memcached-operator
│   │   │       ├── 0.5.0
│   │   │       │   └── memcached-operator.v0.5.0.clusterserviceversion.yaml
│   │   │       └── 0.6.0
│   │   │           └── memcached-operator.v0.6.0.clusterserviceversion.yaml
│   │   ├── operator.yaml
│   │   ├── role.yaml
│   │   ├── role_binding.yaml
│   │   └── service_account.yaml
```

When it is : 

```
├── deploy
│   ├── olm-catalog 
│   │   ├── _generated.concat_crd.yaml
│   │   ├── jaeger.clusterserviceversion.yaml
│   │   └── jaeger.package.yaml
│   ├── operator.yaml
│   ├── role.yaml
│   ├── role_binding.yaml
│   └── service_account.yaml
```

**Comment by jpkrohling** [comment]
Are you sure that's the cause? I'm pretty sure I ran the commands from the first issue on a newly created operator.

**Comment by camilamacedo86** [comment]
Hi @jpkrohling,

Following the suggested steps performed with your project. See that the currentCSV will NOT be duplicated.  

1. Remove the current olm-catalogue dir that is not following the standard
2. Run the command to generate the OLM files as follows. 

```
$ operator-sdk olm-catalog gen-csv --csv-channel=stable --default-channel --csv-version=1.13.1
INFO[0000] Generating CSV manifest version 1.13.1       
INFO[0000] Fill in the following required fields in file deploy/olm-catalog/jaeger-operator/1.13.1/jaeger-operator.v1.13.1.clusterserviceversion.yaml:
	spec.keywords
	spec.maintainers
	spec.provider 
INFO[0000] Created deploy/olm-catalog/jaeger-operator/1.13.1/jaeger-operator.v1.13.1.clusterserviceversion.yaml 
INFO[0000] Created deploy/olm-catalog/jaeger-operator/jaeger-operator.package.yaml
``` 
3. Check that it was not duplicated and that the struture of files and dir created is no longer the same. 

<img width="961" alt="Screenshot 2019-09-02 at 11 12 14" src="https://user-images.githubusercontent.com/7708031/64107680-fc0a2580-cd72-11e9-8c7a-548eada2dde4.png">

4. Run the command again with another version to check it. 

```
$ operator-sdk olm-catalog gen-csv --csv-channel=stable --default-channel --csv-version=1.13.2
INFO[0000] Generating CSV manifest version 1.13.2       
INFO[0000] Fill in the following required fields in file deploy/olm-catalog/jaeger-operator/1.13.2/jaeger-operator.v1.13.2.clusterserviceversion.yaml:
	spec.keywords
	spec.maintainers
	spec.provider 
INFO[0000] Created deploy/olm-catalog/jaeger-operator/1.13.2/jaeger-operator.v1.13.2.clusterserviceversion.yaml 
INFO[0000] Created deploy/olm-catalog/jaeger-operator/jaeger-operator.package.yaml 
```
 
<img width="750" alt="Screenshot 2019-09-02 at 11 17 01" src="https://user-images.githubusercontent.com/7708031/64107790-35db2c00-cd73-11e9-8252-ca421e826160.png">

So, we can confirm that the issue here is because this project is not respecting the expected structure of files and directories which is used to generate the files. 

Please, let us know if are you ok with or if has anything else that you would expect be done/checked here.

**Comment by jpkrohling** [comment]
I see the same behavior in [another operator I'm working on](https://github.com/jpkrohling/opentelemetry-operator/), created using the `operator-sdk` v0.10.0:

```console
$ git log -1
commit 4d1e2fc02a317e4ef8ca2d78fe80b51436b42abc (HEAD -> master, origin/master)
Author: Juraci Paixão Kröhling <juraci@kroehling.de>
Date:   Thu Aug 29 17:53:11 2019 +0200

    badges for codecov and codeclimate
    
    Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
$ cat deploy/olm-catalog/opentelemetry-operator/opentelemetry-operator.package.yaml
channels:
- currentCSV: opentelemetry-operator.v0.0.1
  name: alpha
defaultChannel: alpha
packageName: opentelemetry-operator
$ operator-sdk olm-catalog gen-csv --csv-version 0.0.2 --update-crds --from-version 0.0.1 --csv-channel=alpha --default-channel 
INFO[0000] Generating CSV manifest version 0.0.2        
INFO[0000] Created deploy/olm-catalog/opentelemetry-operator/0.0.2/opentelemetry-operator.v0.0.2.clusterserviceversion.yaml 
INFO[0000] Created deploy/olm-catalog/opentelemetry-operator/opentelemetry-operator.package.yaml 
$ cat deploy/olm-catalog/opentelemetry-operator/opentelemetry-operator.package.yaml
channels:
- currentCSV: opentelemetry-operator.v0.0.1
  name: alpha
- currentCSV: opentelemetry-operator.v0.0.2
  name: alpha
defaultChannel: alpha
packageName: opentelemetry-operator
```

**Comment by camilamacedo86** [comment]
Hi @jpkrohling,

I am unable to reproduce the same behaviour with the current master branch. 

```
 $ operator-sdk version
operator-sdk version: "v0.10.0-27-gc0947baa", commit: "c0947baa1fed27e9746964e449fe57ebd9b2383d", go version: "go1.12.7 darwin/amd64"
```

Note that I am using your project to test it. Could you please try to use the master branch and check if you will be able to get it sorted?

```
$  operator-sdk olm-catalog gen-csv --csv-version 0.0.2 --update-crds --from-version 0.0.1 --csv-channel=alpha --default-channel 
INFO[0000] Generating CSV manifest version 0.0.2        
INFO[0000] Created deploy/olm-catalog/opentelemetry-operator/0.0.2/opentelemetry-operator.v0.0.2.clusterserviceversion.yaml 
INFO[0000] Created deploy/olm-catalog/opentelemetry-operator/opentelemetry-operator.package.yaml 
```

<img width="1087" alt="Screenshot 2019-09-02 at 13 07 20" src="https://user-images.githubusercontent.com/7708031/64113637-bfdec100-cd82-11e9-90cb-3e27a1206ce4.png">

**Comment by jpkrohling** [comment]
Indeed, this seems to be fixed in the latest version from master! Thanks for your patience and support, @camilamacedo86!

**Comment by camilamacedo86** [comment]
Hi @jpkrohling,
 
Really tks for check that it fixed in the master as well and to raise it. 
I am very glad that I could help you with.
