### ISSUE TITLE
operator fails with forbidden error when hostname is given nginx_cr.yaml of nginx helm operator

### ISSUE THREAD

**Issue by Tirumalavasa** [operator-framework/operator-sdk#1848]
## Bug Report

**What did you do?**
I followed the guideline for installing the operator as described here to deploy nginx helm based operator:
https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md

**What did you expect to see?**
when i enable ingress in the example_v1alpha1_nginx_cr.yaml which has host name and create a deployment an ingress resource should be created with hostname configured in it

**What did you see instead? Under which circumstances?**
Ingress resource is not getting created , instead we see below error int the describe command of the ngnx resource
```
Status:
  Conditions:
    Last Transition Time:  2019-08-21T12:32:25Z
    Status:                True
    Type:                  Initialized
    Last Transition Time:  2019-08-21T12:32:26Z
    Message:               failed to install release: release example-nginx-b4m7rhvs52kuyloyechvbfs6n failed: ingresses.extensions is forbidden: User "system:serviceaccount:ibmmobile:nginx-operator" cannot create ingresses.extensions in the namespace "testproject": no RBAC policy matched
    Reason:                InstallError
    Status:                True
    Type:                  ReleaseFailed
Events:                    <none>
```

**Environment**
* operator-sdk version:
operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170

* go version:
go version go1.12.9 darwin/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-08-16T16:39:41Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
 OKD 3.11
* Are you writing your operator in ansible, helm, or go?
Helm based operator
**Possible Solution**

**Additional context**

**Comment by joelanford** [comment]
@Tirumalavasa what you're seeing is that the Role that the operator is using lacks permission to manage ingresses. When the SDK generates the role, it uses the chart's default values to render the default chart, enumerate the resources, and create rules for each of them.

Since `Ingress` is disabled in the default values, the rendered chart doesn't contain an `Ingress` resource, so a rule is not created for it. You can fix this by manually updating the role in `deploy/role.yaml` to include permissions to manage ingresses and then re-applying the role.

The CLI prints a warning when generating the role that mentions this limitation.


> WARN[0000] The RBAC rules generated in deploy/role.yaml are based on the chart's default manifest. Some rules may be missing for resources that are only enabled with custom values, and some existing rules may be overly broad. Double check the rules generated in deploy/role.yaml to ensure they meet the operator's permission requirements.
