### ISSUE TITLE
how to get component instance from manager

### ISSUE THREAD

**Issue by afoninsky** [operator-framework/operator-sdk#1849]
## Type of question

**community best practice to implement a specific feature**

## Question

I want to implement web ui which shows some useful information based on custom resources data. There are two CRD resources: `crdA` and `crdB` to display in single interface. Here is what I did:

1) Added two CRD controllers (pkg/controller/crdA, pkg/controller/crdB) to watch for these resources.
2) Created "web ui" instance using [Runnable](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager#Runnable) interface:
```
	if err := mgr.Add(&ws.WebServer{}); err != nil {
		log.Error(err, "")
		os.Exit(1)
	}
```
3) Want from CRD controllers to trigger webui instance methods when create/update/delete events come but can't understand how CRD controller gets webui instance from manager

Questions are:
- is it the recommended way to inject instances to controller or better one exists?
- how can I inject webui instance to controller so controller can use webui methods? looks like I've missed something due to my skills or lack of documentation

Thank you.

**Comment by camilamacedo86** [comment]
H @afoninsky,

I am not sure if I understood properly your question. Shows that you'd like to read the CR of some CRD applied in the cluster and show this data in some web project/UI. Am I right?

Note that the goal of the operators is a simple way to say, just to better explain my idea here, is to manage data/objects in the cluster so it will do CRUDS (create/read/update/delete) the ks8, OCP, and other third-party APIs objects in the reconcile method. If you would like to read an object and show the data in another project ( e.g a web app ) you may solve this need by calling a REST API endpoint of your project/service which will receive this data and store it in you solution DB to show in some UI. 

Note that the `watches` are like observers. They will trigger the reconcile if they check that the KIND/Object watched was created/update/delete in the cluster. 

Also, I'd like to recommend you follow and check the [Getting Started](https://github.com/operator-framework/getting-started) example which is very fast just for you get a better idea of how the things work if you did not it yet and [here](https://github.com/aerogear/mobile-security-service-operator/blob/master/pkg/controller/mobilesecurityserviceapp/controller.go#L194) you can see an example of an operator project using a REST API. 

I hope that it is the info that you are looking for.

**Comment by afoninsky** [comment]
Yes you do understand me correctly.

Thank you for your response. Everything is clear so far.
