### ISSUE TITLE
Operator-sdk add controller native kubernetes objects

### ISSUE THREAD

**Issue by Devin-Holland** [operator-framework/operator-sdk#1851]
I am trying to use the `operator-sdk add controller` to create a controller that is watching for native kubernetes secrets instead of a custom resource of my own. I ran the following command:

`operator-sdk add controller --api-version=core/v1 --kind=Secret` 

Thinking it would watch for `&source.Kind{Type: &corev1.Secret{}}` in the `k8s.io/api/core/v1` package but instead it generated a controller watching for `&corev1api.Secret{}` and included an api reference within the project that doesn't exist. So, is there a way to use the generator to watch native kubernetes objects out of the box or am I better off just not using the generator and adding a controller manually?

**Comment by joelanford** [comment]
@Devin-Holland You can use the `--custom-api-import`  for this.

I think it would be: 
`operator-sdk add controller --custom-api-import=k8s.io/api/core/v1 --api-version=core/v1 --kind=Secret`

If that doesn't work. Let us know and we'll re-open. That flag is relatively new and hasn't had a lot of use AFAIK.
