### ISSUE TITLE
Prevent helm/kubernetes manifests in logfiles for helm-operator

### ISSUE THREAD

**Issue by ipansa** [operator-framework/operator-sdk#1855]
Question: Is there a simple way to configure a vanilla helm chart operator to prevent the rendered kubernetes manifest from being logged? I did set zap-level to error, but still I see a complete rendered kubernetes manifest in the logfiles

**Comment by joelanford** [comment]
@ipansa Thanks for the report! There is not a way to configure that at the moment, but I agree that it should not show up at the error level. I submitted #1857 to resolve this.

**Comment by ipansa** [comment]
Excellent and thanks for the quick turnaround - looking forward to it!
