### ISSUE TITLE
operator and custom resources deleted in e2e test when created with no cleanup

### ISSUE THREAD

**Issue by jsanda** [operator-framework/operator-sdk#1869]
## Bug Report

**What did you do?**
The [writing-e2e-tests guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/writing-e2e-tests.md) shows the following examples for creating examples with no cleanup:

```go
Create(goctx.TODO(), exampleMemcached, &framework.CleanupOptions{})
Create(goctx.TODO(), exampleMemcached, nil)
```
I have an e2e test that is written following the examples. It initializes resources with:

```go
err := ctx.InitializeClusterResources(&framework.CleanupOptions{})
```
My custom resources and the operator get deleted at the end of the test. I tried passing `nil`, but behavior was still the same.

**What did you expect to see?**
I expected my operator and custom resources to still exist when the test finished.

**What did you see instead? Under which circumstances?**
The operator deployment, the custom resources, and the CRD are all deleted.

**Environment**
* operator-sdk version: 0.9.0

* go version: go1.12.6 darwin/amd64

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.19", GitCommit:"bebe882824db5431820e3d59851c8fb52cb41675", GitTreeState:"clean", BuildDate:"2019-07-26T00:09:47Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jmrodri** [comment]
Thanks @jsanda , quick triaget he test client seems to be doing the right thing with the `CleanupOptions` struct.
https://github.com/operator-framework/operator-sdk/blob/master/pkg/test/client.go#L51-L53
```golang
	if cleanupOptions == nil || cleanupOptions.TestContext == nil {
		return nil
	}
```

I wonder if the deletion of the namespace is what's killing your operator and resources.
https://github.com/operator-framework/operator-sdk/blob/master/pkg/test/resource_creator.go#L49-L51
```golang
	ctx.AddCleanupFn(func() error {
		return Global.KubeClient.CoreV1().Namespaces().Delete(ctx.namespace, metav1.NewDeleteOptions(0))
	})
```

**Comment by jsanda** [comment]
Hi @jmrodri 

I forgot to mention that I am using a pre-existing namespace, so I do not think the namespace deletion comes into play in my case. In any event, I am not reproducing the behavior. I suspect it was a mistake in my code that I overlooked.

I am going to close the ticket and chalk this one up to operator error 😁
