### ISSUE TITLE
Allow the namespace to be configurable

### ISSUE THREAD

**Issue by matyix** [operator-framework/operator-sdk#187]
The namespace being watched by the operator (in `main.go`) is hardcoded. The namespace should be configurable at runtime when the operator is created.

**Comment by fanminshi** [comment]
@rongou yeah, that sounds right to me. Have you tested it out yet?

**Comment by eparis** [comment]
I'm not entirely sure #227 completely fixes this. It does at least allow the operator to work outside of the default namespace and shows what needs to change. #227 certainly feels like a better starting place for devs to me.
