### ISSUE TITLE
Why remove --cluster-scoped support in v0.10.0?

### ISSUE THREAD

**Issue by yueyongyue** [operator-framework/operator-sdk#1870]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:

  insert release or Git SHA here

* Kubernetes version information:

  insert output of `kubectl version` here

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by yueyongyue** [comment]
https://github.com/operator-framework/operator-sdk/blob/v0.10.x/doc/operator-scope.md  fail to succeed

**Comment by joelanford** [comment]
@yueyongyue Support for the `--cluster-scoped` flag was removed in v0.8.0. See https://github.com/operator-framework/operator-sdk/pull/1434 for the motivation.

However, cluster-scoped CRDs and operators are still supported. Read the [operator scope documentation](https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md) on the changes needed to run a cluster-scoped operator.

**Comment by yueyongyue** [comment]
@joelanford Use this document, Gets a empty Namespace

**Comment by hedeesaa** [comment]
the doc is not available anymore, 
Is there any other documentation?

**Comment by camilamacedo86** [comment]
See; https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/

**Comment by hedeesaa** [comment]
I followed steps defined in the Doc but I the it didnt work properly. I get this error from operator:
```
