### ISSUE TITLE
API seems to require a warm up time

### ISSUE THREAD

**Issue by adawolfs** [operator-framework/operator-sdk#1871]
## Bug Report

**What did you do?**
Hi
When I first start my operator and try get an object, api says that it doesn't exist (when it is).
I notice that as the CR is requeue the validation actually works after 3 attempts or so... It made me try adding a "time.sleep"  at Reconcile method and it makes the error disappear on first start.

Is this an usual behavior ? would be related to my API version? 
```
secretFound := &corev1.Secret{}
err := r.client.Get(
	context.TODO(),
	types.NamespacedName{
		Name:      "my-secret",
		Namespace: "my-project",
	},
	secretFound)

if err != nil && errors.IsNotFound(err) {
	reqLogger.Info("Creating MySQL Config Secret")
	err = r.client.Create(context.TODO(), newSecret)
        // This log display a "secret exist error"
	reqLogger.Info(fmt.Sprintf("Error value not possible: %v", err))

	return newSecret, err
}
```

**Environment**
* operator-sdk version: v0.10.0
* go version: v1.12.9
* Openshift go-client api: v3.9
* Openshfit server: v3.11

**Comment by joelanford** [comment]
@adawolfs This is likely caused by the fact that the controller-runtime manager uses a caching client.

Without seeing your code I'm speculating, but I assume you are not adding a watch to your controller for `corev1.Secret` resources. Is that correct?

If so, try adding that watch. You'll likely want to reconcile your primary CR if this secret changes or is deleted. By adding the secret watch, I think the manager should automatically fill the caches with secrets before starting reconciliation.

**Comment by adawolfs** [comment]
@joelanford 
I understand what you mention but why to implement a watcher like:
```
err = c.Watch(&source.Kind{Type: &corev1.Pod{}}, &handler.EnqueueRequestForOwner{
	IsController: true,
	OwnerType:    &appv1alpha1.PortalProject{},
})
if err != nil {
	return err
}
```
 is required to query objects? why if I don't want to track those objects? or make decisions based on what is already deployed on my cluster?

> I don't want to sound pushy, I'm just curious about how is it actually intended to be implemented

**Comment by joelanford** [comment]
Controller watches and resource queries are separate, but related. The flow of events into your reconciler (i.e. the events that cause your reconciler to be called) always flow through the cache. So if you're watching for objects owned by a parent resource, the object that triggered the event is guaranteed to be populated in the cache before the `Reconcile` method for the parent resource is called.

As you've discovered, you can still query the cache for resources without establishing a watch, but the cache is not guaranteed to have the latest state.

In general, if the reconciliation of a primary resource involves knowing about, using, or acting upon the state of a secondary resource, you should watch the secondary resource. That way your primary resource cannot get out-of-sync with the secondary resources it cares about.

Taking a step back, can you describe your use case with a little bit more detail. From your description, it sounds like your secondary resource is a `Secret` that contains the configuration for a MySQL database. Does your primary resource represent a MySQL database?

In your example, what do you do with the `Secret` once you've fetched it? What do you do if the `Secret` is not present in the cluster?

**Comment by joelanford** [comment]
@adawolfs We're you able to figure this out? If not let me know and we can re-open and keep the discussion going!
