### ISSUE TITLE
How should I set up resources from another operator in e2e tests?

### ISSUE THREAD

**Issue by jsanda** [operator-framework/operator-sdk#1872]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

This is a question around best practices for writing e2e tests for an operator that has a dependency on another operator, specifically one implemented with operator-sdk.

## Question
I need to provide a little background. I am developing an operator that has a dependency on another operator. This made writing e2e tests a little more complicated in terms of setup. I am storing manifests (RBAC, service account, deployment) in a `test/manifests` directory. My Makefile has the targets `e2e-test` and `e2e-setup`. The former depends on the latter and `e2e-setup` creates everything in the `test/manifests` directory.

What is the best way to do this?  I spent some time looking to see if there is a particular way to handle this scenario with operator-sdk, but I did not find anything definitive. 

**Environment**
* operator-sdk version: 0.9.0

**Comment by joelanford** [comment]
@jsanda It sounds like the dependency on the other operator is a runtime dependency? Is that correct?

If so, it sounds like you're looking for suggestions on how to deploy the operator your operator depends on? Have you looked at the Operator Lifecycle Manager? While not directly related to running e2e tests, it may be able to help you with managing your operator's runtime dependencies.

Barring that, your current approach seems like a reasonable way to structure your e2e test setup and execution.

**Comment by joelanford** [comment]
Let us know if you have any more questions!
