### ISSUE TITLE
replace git.apache.org/thrift.git with github.com/apache/thrift

### ISSUE THREAD

**Issue by UdayVishwakarma** [operator-framework/operator-sdk#1883]
## Bug Report

**What did you do?**
I tried to create a new operator from the latest release from this repo. I get an error while downloading dependencies.

`
➜  example-operator: go mod vendor
go: finding git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git -c protocol.version=0 fetch --unshallow -f https://git.apache.org/thrift.git refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/udayvishwakarma/github/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Operation timed out
go: error loading module requirements
`

**What did you expect to see?**
It created the boilerplate folder structure with files. when I run `go mod vendor` it should download all the dependencies .

**What did you see instead? Under which circumstances?**
I get an error when it tries to download `https://git.apache.org/thrift.git`. error is below 

```
go mod vendor
go: finding git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git -c protocol.version=0 fetch --unshallow -f https://git.apache.org/thrift.git refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/udayvishwakarma/github/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Operation timed out
go: error loading module requirements
```

**Environment**
* operator-sdk version:

operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170

* go version:

go version go1.12.7 darwin/amd64

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: minikube 

* Are you writing your operator in ansible, helm, or go?  go

**Possible Solution**

replace `https://git.apache.org/thrift.git/` in dependencies with `github.com/apache/thrift`

**Additional context**
I didn't find `git.apache.org/thrift` in `go.mod` of the boilerplate generated by operator-sdk. I searched whole project i was not able to find

**Comment by camilamacedo86** [comment]
Hi @UdayVishwakarma,

Thank you for raise it. It is the same scenario discussed in https://github.com/operator-framework/operator-sdk/issues/1873. In this way, I am closing this issue.

**Comment by camilamacedo86** [comment]
Please, feel free to reopen it if you think that some other action would be required to address this subject.
