### ISSUE TITLE
Can't run operator locally - windows 10

### ISSUE THREAD

**Issue by michalkarolik** [operator-framework/operator-sdk#1886]
## Bug Report

**What did you do?**
operator-sdk up local --namespace=""

**What did you expect to see?**
Running operator locally ; )

**What did you see instead? Under which circumstances?**
```
operator-sdk up local --namespace=""
time="2019-09-06T14:42:16+02:00" level=info msg="Running the operator locally."
time="2019-09-06T14:42:16+02:00" level=info msg="Using namespace ."
Error: failed to run operator locally: (failed to exec []string{"build\\_output\\bin\\metrics-operator-local"}: exec: "build\\_output\\bin\\metrics-operator-local": file does not exist)
```

File is on specified path:
```bash
ls  build\_output\bin\metrics-operator-local  
'build\_output\bin\metrics-operator-local'* 
```

**Environment**
* operator-sdk version:
```
operator-sdk version: "v0.10.0-27-gc0947baa-dirty", commit: "c0947baa1fed27e9746964e449fe57ebd9b2383d", go version: "go1.12.9 windows/amd64"
```

* go version:
```
 go version go1.12.9 windows/amd64
```

* Are you writing your operator in ansible, helm, or go?
Go

**Additional context**
It is windows 10. Operator code itself works - I am able to test iton kubernetes created by docker, but in a long term it is pain to work like that. Would love to run it locally and hopefully be able to debug code in my IDE.

**Comment by joelanford** [comment]
@michalkarolik we currently don't _officially_ support Windows, but we do our best not to break it either :)

Just to make sure I understand correctly, you're saying that the `operator-sdk up local` command fails, but that the `build\_output\bin\metrics-operator-local` binary exists after calling `up local`?

If so, can you run that binary directly?

Also, are you using WSL? Can you tell whether the binary is a linux or windows executable?

**Comment by michalkarolik** [comment]
I did not think to run it directly before - it worked! All I had to do is to change suffix to .exe and just run
```
./metrics-operator-local.exe
```
or even using delve so finally I can debug it in IDE:
```
dlv --listen=:2345 --headless=true --api-version=2 exec metrics-operator-local.exe
```

so - thanks! Seems it works,
