### ISSUE TITLE
ReadMe Cluster Service Version link end in 404

### ISSUE THREAD

**Issue by aneeshkp** [operator-framework/operator-sdk#1887]
Source 
`https://github.com/operator-framework/operator-sdk/blob/master/doc/design/milestone-0.2.0/csv-generation.md` 

in CSV generation md link to `Cluster Service Version link` throws 404 
`'Error link`

https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/building-your-csv.md#what-is-a-cluster-service-version-csv

**Comment by camilamacedo86** [comment]
Hi @aneeshkp,

Thank you for raise it. The correct path of the link is: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#what-is-a-cluster-service-version-csv. 

We will fix it as soon as possible.

**Comment by camilamacedo86** [comment]
Pr to fix it is : https://github.com/operator-framework/operator-sdk/pull/1888

**Comment by camilamacedo86** [comment]
Closing this one.
