### ISSUE TITLE
missing dot in first path element

### ISSUE THREAD

**Issue by damozhiying** [operator-framework/operator-sdk#1892]
``
operator-sdk new app-operator --repo github.com/example-inc/app-operator
``
![2019-09-09 14-55-27屏幕截图](https://user-images.githubusercontent.com/10277950/64509301-fd5ac580-d311-11e9-8d73-4b98da6703cb.png)

**Comment by damozhiying** [comment]
``
dmzy@host1:~/projects/example-inc/app-operator$ go version 

go version go1.13 linux/amd64
dmzy@host1:~/projects/example-inc/app-operator$ operator-sdk version 

operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170
``

**Comment by joelanford** [comment]
@damozhiying I'm not able to reproduce this. It seems like it could be an issue with your module cache. Something seems odd with the `golang_org/x/net` imports. I think they should be `golang.org/x/net`.

You could try `go clean -modcache` to clean out your modules cache and then retry.

**Comment by joelanford** [comment]
@damozhiying Let me know if you are still unable to solve the problem and we can reopen and/or discuss more.

Thanks!
