### ISSUE TITLE
Unable to pull containerPort from yaml

### ISSUE THREAD

**Issue by danyollee** [operator-framework/operator-sdk#1897]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
Help with an Operator feature

## Question

**What did you do?**
With the controller, I am creating a StatefulSet and pulling the configuration from the cr.yaml file I have. In the .yaml, I have a section
```
ports:
   - name: mysql
      containerPort: 3306
```

**What did you expect to see?**
I expected to see the port listed when I run `kubectl describe sts mysql`

**What did you see instead? Under which circumstances?**
Port section was empty

**Environment**
* operator-sdk version:
v0.10.0-31-ga827815d

  insert release or Git SHA here

* Kubernetes version information:

1.14.6

* Kubernetes cluster kind: 
Docker-for-Desktop

**Additional context**
Add any other context about the question here.

**Comment by camilamacedo86** [comment]
Hi @danyollee, 

I understand that you would like to see the MySQL container in a deployment using the info added in the CR. 

Note that the CRD is the definition of a new /customized object which will represent your solution in the cluster, for example, the MySQL. The CR is where you are able to set the values for the CRD specs/attributes. 

So, for your MySQL container in the cluster use info from the CR you need define it programmatically in the code of your operator when you are developing the deployment/container on it. See [here](https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/resource/deployments.go#L43) an example where the deployment is using the value defined in the CR as a port of the DB container.

I hope that it is the info which you are looking for. 
Please, let us know if it answers your question or not.

**Comment by danyollee** [comment]
Thanks for your reply!

So I've added all of the values from the types.go into the CRD and specified the types. Unfortunately, it still looks like the controller is unable to pull the ports from the CR. 

What strikes me as odd is that the controller is able to pull other objects/arrays from the CR just fine. I just don't know why the container port is having issues. In my CR, I have something along the lines of 
```
  volumemounts:
  - name: storage
    mountPath: /var/lib/mysql
    subPath: mysql
  - name: mysql-conf
    mountPath: /etc/mysql/conf.d
  volumes:
  - name: mysql-conf
    configMap:
      name: mysql


  # Special for mysql
  containerPorts: 
  - containerPort: 3306
    name: mysql
    protocol: TCP
```
My controller is able to pull the volumes and the volumemounts just fine. In fact, I set an _if statement_ where the controller will pull the volumes, volumemounts, and ports. If they exist, then it'll log that the specifications exists. I get existing logs for the volumes and volumemounts, just not the container ports :(

Any ideas?

**Comment by danyollee** [comment]
Another piece to note is that in the same CR yaml file, I have another spec source which looks like 
```
  # Service specs
  serviceSpec:
    tier: backend
    ports: 
    - name: mysql
      port: 3306
    clusterIP: None
    selector: mysql
```
These values are used to create a Service. The controller **is** able to pull the ports from the serviceSpec and successfully use the ports in the Service creation.

**Comment by camilamacedo86** [comment]
Did you run the command "operator-sdk generate k8s" to update the deep copy files? Is it finishing with success? If yes, how are they defined in the *_type.go?

**Comment by danyollee** [comment]
The command `operator-sdk generate k8s` as well as `operator-sdk build ...` and `docker push ...` are all completing successfully. The *_types.go is defined as 
```
type SustainSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file
	// Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
	Namespace       string                      `json:"namespace,omitempty"`
	Replicas        *int32                      `json:"replicas,omitempty"`
	Name            string                      `json:"name,omitempty"`
	Image           string                      `json:"image,omitempty"`
	Secret          string                      `json:"secret,omitempty"`
	VolumeMounts    []corev1.VolumeMount        `json:"volumemounts,omitempty"`
	Volumes         []corev1.Volume             `json:"volumes,omitempty"`
	EnvFrom         []corev1.EnvFromSource      `json:"envFrom,omitempty"`
	ImagePullPolicy corev1.PullPolicy           `json:"imagePullPolicy,omitempty"`
	**Ports           []corev1.ContainerPort      `json:"ports,omitempty`**
	Resources       corev1.ResourceRequirements `json:"resources,omitempty"`
	LivenessProbe   *corev1.Probe               `json:"livenessProbe,omitempty"`
	ReadinessProbe  *corev1.Probe               `json:"readinessProbe,omitempty"`
	Env             []corev1.EnvVar             `json:"env,omitempty"`

	ServiceSpec ServiceSpec `json:"serviceSpec,omitempty"`
}
```

Bolded is where the ports _should_ be pulling from. The controller to pull the ports looks like 
```
				},
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{
						corev1.Container{
							Name:            cr.Spec.Name,
							Image:           cr.Spec.Image,
							ImagePullPolicy: cr.Spec.ImagePullPolicy,
							EnvFrom:         cr.Spec.EnvFrom,
							Env:             cr.Spec.Env,
							**Ports:           cr.Spec.Ports,**

```

**Comment by danyollee** [comment]
I also have a debugging line in the controller just before the creation of the resource where it checks to see the controller has pulled pieces from the CR file. 
``` 
	val := cr.Spec.EnvFrom
	if val != nil {
		log.Info("EnvFrom exists")
		log.Info(strconv.Itoa(len(val)))
	}
	val2 := cr.Spec.Ports
	if val2 == nil {
		log.Info("Ports do not exist")
	} else {
		log.Info("ports exist")
		log.Info(strconv.Itoa(len(val2)))
	}
```
In the logs for the operator, I see the following logs associated from these lines.
```
{"level":"info","ts":1568150276.05756,"logger":"controller_sustain","msg":"EnvFrom exists"}
{"level":"info","ts":1568150276.0575795,"logger":"controller_sustain","msg":"1"}
{"level":"info","ts":1568150276.0575871,"logger":"controller_sustain","msg":"Ports do not exist"}
```

**Comment by joelanford** [comment]
@danyollee In your `_types.go` your JSON tag is `ports`, but in your YAML, you're calling it `containerPorts`. I think you could fix it by changing your CR from `containerPorts` to `ports`.

**Comment by danyollee** [comment]
@joelanford Ah my apologies. I had copied a previous version. After changing the CR yaml to match the *_types.go, I am still not able to pull the ports :-(

```
  # Special for mysql
  ports: 
  - containerPort: 3306
    name: mysql
    protocol: TCP
```

**Comment by joelanford** [comment]
Are you missing a quotation mark at the end of the JSON tag?

Looks like you have:
`` `json:"ports,omitempty` ``

And you may need:
`` `json:"ports,omitempty"` ``

**Comment by danyollee** [comment]
Looks like the syntax was it 😫 I'm so embarrassed lol

**Comment by camilamacedo86** [comment]
I am glad that it is solved.

**Comment by danyollee** [comment]
Thanks for the help!
