### ISSUE TITLE
Expose the k8s_client

### ISSUE THREAD

**Issue by matyix** [operator-framework/operator-sdk#190]
The **operator-sdk** library allows CRUD operations on K8S resources through the `actions` and `query` packages. There might be cases when it is desired to build custom business logic that requires access to the `k8s_client` (access to the k8s api server). The SDK might expose the `k8s_client` as well.

**Comment by allamand** [comment]
I would like to access the k8s_client from the sdk to be able to exec into some pods to execute commands and get results.

**Comment by saada** [comment]
It would be great to also have an example in the docs to `exec` into a pod using the exposed client.
