### ISSUE TITLE
Consider adding [type] before 'User Guide' on docs user-guides

### ISSUE THREAD

**Issue by geerlingguy** [operator-framework/operator-sdk#1905]
## Feature Request

Currently when you search for terms like 'Ansible Operator SDK' or 'Helm Operator SDK' (or anything of the like), you usually end up hitting proposal docs or other less relevant example documentation... you never see the "User Guide" for these items.

The reason is all these documents have the page / document title "User Guide":

  - https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md - H1 title is "User Guide"
  - https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md - H1 title is "User Guide"
  - https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md - H1 title is "User Guide"

I propose we add more meaningful titles to these documents, either just "Ansible User Guide", "Helm User Guide", etc. — or maybe a full "Ansible User Guide for Operator SDK", "Helm User Guide for Operator SDK"

That way people will be able to google or GitHub search and get to these docs a lot more easily. As it is, I always google my way into the proposal doc, then navigate manually through the docs to get back to the user guide :/

**Comment by joelanford** [comment]
@geerlingguy This sounds reasonable to me. Would you be interested in submitting a quick PR to update the titles?

FWIW, I prefer the full names, e.g. "Ansible User Guide for Operator SDK", "Helm User Guide for Operator SDK"

**Comment by geerlingguy** [comment]
Just opened #1919, hope that looks good!

**Comment by camilamacedo86** [comment]
To close this one shows that we are just missing do the same for the dev guides.

**Comment by camilamacedo86** [comment]
Done the PR https://github.com/operator-framework/operator-sdk/issues/1905 in order to apply the same standard across the repo in all docs.
