### ISSUE TITLE
Reconcile Event Running each 5 min 

### ISSUE THREAD

**Issue by petro404** [operator-framework/operator-sdk#1906]
Hi,

I would like to know if the operator SDK is running  Reconcile Event for each CR even the CR was not changed at all , i have noticed that it happen each 5 min.

Is it the right behaviour ? where can i see this code , is it configurable

**Comment by petro404** [comment]
Hi @camilamacedo86 
Thanks for your response , as part of my project i didnt overrode SyncPeriod but somehow its not 10 hours as its also defined in operator.go

**Comment by petro404** [comment]
Hi @camilamacedo86  
Thanks a lot for your input , based on your input I  managed to find this option as part of manager.go in the controller runtime , so i can override it as part of the main.go of the operator as you mention above.


I would like to ask another question as we are talking about subresources.
my current implementation is new CRD lets call it proxyManager and it has 2 sub resource  k8s deployment and service.

in case this CR changed or the deployment/service was changes  i got a new reconcile event ,my question in the context of the reconcile method.
so if the proxyManager changed the operator SDK provide me the instance name as part of the reconcile method.

But lets assume deployment was changed then i got an event how can i got the deployment name as part of the reconcile method without keeping data structure as part of the operator?

Thanks a lot

**Comment by joelanford** [comment]
@petro404 Your reconcile function should be written to always reconcile the entire state of your CR and its owned resources. Typically the way to solve this problem is to make the names of the dependent resources deterministic from the CR. How does your reconcile method choose a name when the deployment is created?

Here's some typical pseudocode:
```
1. Fetch root CR.
2. Derive name of deployment from CR.
3. Fetch deployment.
4. If deployment does not exist, create it.
5. If deployment does exist, does it have expected state?
6. If not, update or patch it to reconcile back to expected state.
7. Repeat steps 2-6 for service.

This might be relevant: https://github.com/kubernetes-sigs/controller-runtime/blob/master/FAQ.md#q-how-do-i-know-which-type-of-object-a-controller-references

Closing since the it seems like you were able to solve your original issue.
