### ISSUE TITLE
Proposals should be marked as 'closed' or have some other prominent status

### ISSUE THREAD

**Issue by geerlingguy** [operator-framework/operator-sdk#1910]
## Feature Request

Alongside #1905, another thing I have run into (and I know others have as well) is the fact that many searches (e.g. for 'Ansible Operator SDK' or 'Ansible operator status') will turn up _proposal_ docs, for example:

1. https://github.com/operator-framework/operator-sdk/blob/master/doc/proposals/ansible-operator.md
1. https://github.com/operator-framework/operator-sdk/blob/master/doc/proposals/ansible-operator-status.md
1. https://github.com/operator-framework/operator-sdk/blob/master/doc/proposals/ansible-operator-testing.md

If someone new to this project lands on these documents through search, they will think that these things are still in 'proposal' state.

Therefore I propose we do one of two things to make it more clear that the proposed thing is either built or in progress:

1. If the proposed thing is done, either delete the proposal doc, or add a bold note at the top like "Status: **completed** (this is now part of Operator SDK. See [documentation](#))."
2. If the proposed thing is being worked on (e.g. you can start using/testing it), add a status to the top like "Status: **initial implementation complete** (please help us test this thing)."

**Comment by joelanford** [comment]
@geerlingguy Thanks for the issue. I think we should keep the proposals around, but I agree that they should be updated to reflect their current status.

Want to take a stab at updating the ones you mentioned?

**Comment by geerlingguy** [comment]
Implemented in #1920
