### ISSUE TITLE
OpenApi validation generation failing for v1.ObjectMeta type

### ISSUE THREAD

**Issue by nitishm** [operator-framework/operator-sdk#1922]
## Bug Report

**What did you do?**
Trying to utilize `operator-sdk generate openapi` for struct members of type `v1.ObjectMeta` ("k8s.io/apimachinery/pkg/apis/meta/v1")

**What did you expect to see?**
zz_generated.openapi.go to be created successfully

**What did you see instead? Under which circumstances?**
```
 operator-sdk generate openapi                                                                                                                                                                                                     
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [istioconfig:[v1alpha1], ] 
API rule violation: names_match,./pkg/apis/istioconfig/v1alpha1,ExternalHostStatus,VirtualServices
API rule violation: names_match,./pkg/apis/istioconfig/v1alpha1,ExternalHostStatus,DestinationRules
API rule violation: names_match,./pkg/apis/istioconfig/v1alpha1,ExternalHostStatus,ServiceEntries
Error: openapi-gen generator error: Failed executing generator: some packages had errors:
API rule violations exist
```

**Environment**
* operator-sdk version:

```
operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170
ff80b17737a6a0aade663e4827e8af3ab5a21170
```
* go version:

go version go1.13 darwin/amd64

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?
go

**Possible Solution**

**Additional context**

**Comment by camilamacedo86** [comment]
Hi, 

The problem here shows that your code is not passing in the API validations. See the info:

```
API rule violation: names_match,./pkg/apis/istioconfig/v1alpha1,ExternalHostStatus,VirtualServices
API rule violation: names_match,./pkg/apis/istioconfig/v1alpha1,ExternalHostStatus,DestinationRules
API rule violation: names_match,./pkg/apis/istioconfig/v1alpha1,ExternalHostStatu
```
Also, I'd recomend check the [k8s doc](https://github.com/kubernetes/kubernetes/tree/master/api/api-rules).

If the info provided be not enough for you are able to solve it, could you please provide the code(e.g link for its impl _type def in the repo) for we try to help you with?

**Comment by joelanford** [comment]
Just to tack on to what @camilamacedo86 said, this is most often caused by your struct field names not matching up with your JSON tag names.

Based on those errors, check that you have something like:

```go
type ExternalHostStatus struct
    ...
    // VirtualServices -> "virtualServices"
    VirtualServices  []VirtualService `json:"virtualServices,omitempty"`

    // DestinationRules -> "destinationRules"
    DestinationRules []DestinationRule `json:"destinationRules,omitempty"`
    ...
}

**Comment by nitishm** [comment]
@joelanford That seemed to fix the issue. I assumed it would follow the default `go` based json naming convention where `camelCase` is converted to `underscore` case in the json tags. Anyway good to know.

I do however hit another error, which isnt very descriptive (atleast to me).

```
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [istioconfig:[v1alpha1], ] 
2019/09/16 17:18:08 failed to parse resource annotations, error: The given input Cluster is invalid
```

Any ideas what `Cluster is invalid` whould mean ?

**Comment by nitishm** [comment]
Forgot to mention. This only shows up with the following kubebuilder tag
```
// ExternalHost is the Schema for the externalhosts API
// +k8s:openapi-gen=true
// +kubebuilder:subresource:status
type ExternalHost struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ExternalHostSpec   `json:"spec,omitempty"`
	Status ExternalHostStatus `json:"status,omitempty"`
}
```

**Comment by joelanford** [comment]
@nitishm Looks like you're trying to use the latest version of the kubebuilder annotations that are on `master` but not in `v0.10.0`

Check out the `v0.10.0` docs on CRD scope: https://github.com/operator-framework/operator-sdk/blob/v0.10.0/doc/operator-scope.md#crd-scope

Looks like you want:
```
// +genclient:nonNamespaced
```
