### ISSUE TITLE
Unable to do type assert on generated structs for event filtering

### ISSUE THREAD

**Issue by hehesky** [operator-framework/operator-sdk#1923]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
how to implement a specific feature

## Question

**What did you do?**
I'm trying to implement event filtering to control what kind of event can trigger a reconcile call. More specifically, I want the reconcile to trigger on an update event where only the spec is changed in the CR.

So I created a predicate that has `UpdateFunc`. I tried to convert the `e.ObjectOld` and `e.ObjectNew` to the struct that matches the CRD (ie generated by the sdk)
 
**What did you expect to see?**
When building, the compiler throws an error as:
` impossible type assertion: <MyType> does not implement "k8s.io/apimachinery/pkg/runtime".Object (DeepCopyObject method has pointer receiver)`

What I did to convert the types
```
old:=e.ObjectOld.(v1alpha1.MyType)
new:=e.ObjectNew.(v1alpha1.MyType)
```

**What did you see instead? Under which circumstances?**
The build works and throws no error

**Environment**
* operator-sdk version: 0.10

  insert release or Git SHA here

* Kubernetes version information:

  insert output of `kubectl version` here

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by joelanford** [comment]
@hehesky you need to assert it to a pointer type. I.e.:

```go
old:=e.ObjectOld.(*v1alpha1.MyType)
new:=e.ObjectNew.(*v1alpha1.MyType)
```

If that doesn't work, we can re-open and debug more.

**Comment by hehesky** [comment]
I've changed as suggested and the issue is still there @joelanford 

```
does not implement "k8s.io/apimachinery/pkg/runtime".Object (DeepCopyObject method has pointer receiver)
```
