### ISSUE TITLE
Please update k8s.io/kube-state-metrics from v1.6.0 to latest version (v1.7.2)

### ISSUE THREAD

**Issue by 27149chen** [operator-framework/operator-sdk#1925]
## Bug Report

**What did you do?**
go get  github.com/operator-framework/operator-sdk@v0.10.0

**What did you expect to see?**
no error

**What did you see instead? Under which circumstances?**
```
go: finding github.com v0.10.0
go: finding github.com/operator-framework v0.10.0
go get: github.com/operator-framework/operator-sdk@v0.10.0 requires
	k8s.io/kube-state-metrics@v1.6.0 requires
	k8s.io/client-go@v2.0.0-alpha.0.0.20190313235726-6ee68ca5fd83+incompatible: invalid pseudo-version: preceding tag (v2.0.0-alpha.0) not found
```

**Environment**
* operator-sdk version: v0.10.0

* go version: 1.13

* Are you writing your operator in ansible, helm, or go?    go

**Possible Solution**
Please update k8s.io/kube-state-metrics from v1.6.0 to latest version (v1.7.2)

**Comment by camilamacedo86** [comment]
@27149chen,  

The operator-SDK is not updated to support Go 1.13, then may it is the issue. Could you please retry with Go 1.12 and let us know?

**Comment by 27149chen** [comment]
Tried, go 1.12.5 doesn't have this issue, master branch has the same issue.

**Comment by estroz** [comment]
@27149chen I'm closing this since it refers to an issue with a Go version we do not support yet.

**Comment by camilamacedo86** [comment]
Hi, @27149chen also we will try to address your request to update the lib ok.

**Comment by 27149chen** [comment]
@camilamacedo86 , good news, thanks
