### ISSUE TITLE
make tidy failing with ambiguous import

### ISSUE THREAD

**Issue by Purushotham233** [operator-framework/operator-sdk#1926]
## Bug Report

**What did you do?**
Followed the given steps in the doc for installing operator-sdk from master.

**What did you expect to see?**
make tidy step to work fine.

**What did you see instead? Under which circumstances?**
On executing $make tidy
Got the below error:
Error Details:
`github.com/operator-framework/operator-sdk/internal/olm/client imports
	k8s.io/kubernetes/pkg/controller/deployment/util imports
	k8s.io/kubernetes/pkg/controller imports
	k8s.io/kubernetes/pkg/serviceaccount tested by
	k8s.io/kubernetes/pkg/serviceaccount.test imports
	k8s.io/kubernetes/pkg/controller/serviceaccount imports
	k8s.io/kubernetes/pkg/registry/core/secret imports
	k8s.io/apiserver/pkg/registry/generic imports
	k8s.io/apiserver/pkg/storage/storagebackend/factory tested by
	k8s.io/apiserver/pkg/storage/storagebackend/factory.test imports
	github.com/coreos/etcd/integration imports
	github.com/coreos/etcd/client imports
	github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
	github.com/ugorji/go v1.1.1 (/Users/purushotham.m/go/pkg/mod/github.com/ugorji/go@v1.1.1/codec)
	github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8 (/Users/purushotham.m/go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181204163529-d75b2dcb6bc8)
make: *** [tidy] Error 1
`
**Environment**
* operator-sdk version: master branch at commit: 244ae8692d2d088a33c4cd5ddf9f915fc934325a
* go version: go1.13 darwin/amd64

**Comment by joelanford** [comment]
@Purushotham233 we have not updated the repo to support Go 1.13 yet, so that might be the problem. Could you retry with Go 1.12 and see if you still have the same problem?

**Comment by Purushotham233** [comment]
Thanks, Worked with go1.12.
