### ISSUE TITLE
Document the build steps

### ISSUE THREAD

**Issue by jpkrohling** [operator-framework/operator-sdk#1930]
## Feature Request

As recommended via #1867, when more complex build scenarios are required for an operator (like, requiring a couple of `LD_FLAGS` to be set), it's the project's responsibility to setup a build script. However, the build steps aren't described anywhere that I could find, making it hard to come up with a drop-in replacement.

Here's the description from `operator-sdk build --help`:

```
The operator-sdk build command compiles the code, builds the executables,
and generates Kubernetes manifests.
```

This feature request is to add a documentation page somewhere describing what the `operator-sdk build` is expected to do in concrete terms (which executables are built? which Kubernetes manifests are generated?).

**Comment by camilamacedo86** [comment]
Hi @jpkrohling, 

In the following link, we can find the doc of the command.  What do you think about doing a PR  with what you expected to see on it? Also, have you any suggestion for improvements in the output of the help of this command? 

https://github.com/operator-framework/operator-sdk/blob/947a464dbe968b8af147049e76e40f787ccb0847/doc/sdk-cli-reference.md#build

**Comment by jpkrohling** [comment]
I just read the code behind `operator-sdk build`, and I'm a bit confused by the help text: it says that the `build` command generates the Kubernetes manifests, but I don't see where it does that. All I could see is that it simply runs two commands:

```console
$ go build ...
$ docker|buildah  build -f build/Dockerfile ...
```

If you can confirm that no Kubernetes files are touched during the build process, I think the issue then becomes more about removing its mention from the help text.

**Comment by camilamacedo86** [comment]
HI @jpkrohling,

I did a small PR to change it. See https://github.com/operator-framework/operator-sdk/pull/1967. 
Since it is very small I think we can close this issue. However, please feel free to re-open if has anything else that still need be addressed here.
