### ISSUE TITLE
Cluster scoped CRDs annotation is wrong

### ISSUE THREAD

**Issue by prometherion** [operator-framework/operator-sdk#1933]
**What did you do?**
Followed the how-to [provided](https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md) to setup a CRDs handled at cluster scope with Go annotation `+kubebuilder:resource:path=<resource_plural>,scope=Cluster`

**What did you expect to see?**
Once running `operator-sdk generate openapi` I'm expecting to see the CRD `.spec.scope` key set to `Cluster` instead of `Namespaced`

**What did you see instead? Under which circumstances?**
The Operator SDK binary fails with `failed to parse resource annotations, error: The given input Cluster is invalid`. The way to get CRD OpenAPI file correct is using the annotation `+genclient:nonNamespaced`

**Environment**
* operator-sdk version:

`operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170`

* go version:

`go version go1.12.5 linux/amd64`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Minikube

* Are you writing your operator in ansible, helm, or go?

Go

**Possible Solution**

Correcting the documentation using the annotation `+genclient:nonNamespaced`

**Additional context**
Nope.

**Comment by camilamacedo86** [comment]
Hi @prometherion, 

Applying the following code in this [project](https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/apis/postgresql/v1alpha1/database_types.go#L176) then I executed `operator-sdk generate openapi` and all worked well as expected and described in the doc. 

May that the problem in the doc is that it does not make clear where the annotation should be added. Could you please confirm that you did not added it on top of struct and/or recheck it and let us know the result? ( PS. I am using the master branch )

```go
// Database is the Schema for the the Database Database API
// +k8s:openapi-gen=true
// +kubebuilder:subresource:status
// +operator-sdk:gen-csv:customresourcedefinitions.displayName="Database Database"
// +operator-sdk:gen-csv:customresourcedefinitions.resources="Deployment,v1,\"A Kubernetes Deployment\""
// +operator-sdk:gen-csv:customresourcedefinitions.resources="Service,v1,\"A Kubernetes Service\""
// +operator-sdk:gen-csv:customresourcedefinitions.resources="PersistentVolumeClaim,v1,\"A Kubernetes PersistentVolumeClaim\""
// +kubebuilder:resource:path=databases,scope=Cluster
type Database struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DatabaseSpec   `json:"spec,omitempty"`
	Status DatabaseStatus `json:"status,omitempty"`
} 
```

Result: 

```go
  group: postgresql.dev4devs.com
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
  scope: Cluster
  version: v1alpha1
  versions:
```

**Comment by joelanford** [comment]
@prometherion Looks like you were using the `master` documentation, not the [`v0.10.0`](https://github.com/operator-framework/operator-sdk/blob/v0.10.0/doc/operator-scope.md) documentation.

On `master` we've migrated to controller-tools v0.2.0, which has different comment annotations to control CRD scope.
