### ISSUE TITLE
Add a 'status' field to your Custom Resource 

### ISSUE THREAD

**Issue by YathendraPrasad** [operator-framework/operator-sdk#1934]
## Bug Report

**What did you do?**
We have helm based operator and running score-card against the custom-resource and we are just running the basic tests .

```
operator-sdk scorecard --olm-deployed=false --olm-tests=false --cr-manifest /root/yathiokdev/ibm-mobilefoundation-helm-operator/deploy/crds/charts_v1_mfoperator_cr.yaml
```
**What did you expect to see?**
I would expect Total Score: 100%

**What did you see instead? Under which circumstances?**
But i see one Suggesstion where it says  Add 'status' field to your custom resource

```
Basic Tests:
	Spec Block Exists: 1/1
	Status Block Exists: 0/1
	Writing into CRs has an effect: 1/1

Total Score: 71%
SUGGESTION: Add a 'status' field to your Custom Resource
```
**Environment**
* operator-sdk version:

```
[root@biasses1 ibm-mobilefoundation-helm-operator]# operator-sdk version
operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170
```

* go version:
```
[root@biasses1 ibm-mobilefoundation-helm-operator]# go version
go version go1.12.9 linux/amd64
```
* Kubernetes version information:
```
[root@biasses1 ibm-mobilefoundation-helm-operator]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-15T09:45:30Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-08-16T16:39:41Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
OKD cluster
* Are you writing your operator in ansible, helm, or go?
helm
**Possible Solution**
NA

**Additional context**

I tried adding the below status snippet in CRD.yaml but i dont see it taking effect . 

```
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```

But from your code base  i see the check

```
if t.CR.Object["spec"] != nil {
		res.EarnedPoints++
}
in commands/operator-sdk/cmd/scorecard/basic_tests.go

 ```

Just one clarification , is it in the custom resource or custom resource definition the status check is happening . In such case what is the possible value i need to give for the status field to get rid of the Error .

Let me know if you need further info.

**Comment by camilamacedo86** [comment]
Hi @YathendraPrasad, 

Did you impl the status for your own CRD's in the *_type.go?  

See [here](https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/apis/postgresql/v1alpha1/database_types.go#L141) an example. Also, you can check it implemented in the  [Memcached Getting Started example](https://github.com/operator-framework/operator-sdk-samples/blob/master/memcached-operator/pkg/apis/cache/v1alpha1/memcached_types.go#L19)

**Comment by YathendraPrasad** [comment]
Hi @camilamacedo86 : We are using helm based operators and this is our project structure .


<img width="753" alt="Screenshot 2019-09-18 at 5 28 07 PM" src="https://user-images.githubusercontent.com/28103260/65146561-c8e5b880-da39-11e9-9ef8-9735c4289960.png">

<img width="779" alt="Screenshot 2019-09-18 at 5 29 10 PM" src="https://user-images.githubusercontent.com/28103260/65146601-db5ff200-da39-11e9-9e46-d0a250f04971.png">

This is my crd.yaml

```apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mfoperators.mf.ibm.com
  labels:
    app.kubernetes.io/name: mf-operator
    app.kubernetes.io/instance: mf-instance
    app.kubernetes.io/managed-by: helm
    helm.sh/chart: mf-operator-1.0.2
    release: mf-operator-1.0.2
spec:
  group: mf.ibm.com
  names:
    kind: MFOperator
    listKind: MFOperatorList
    plural: mfoperators
    shortNames:
    - mf
    singular: mfoperator
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
```

What values should be given for status in the crd to solve the issue.

**Comment by camilamacedo86** [comment]
Hi @YathendraPrasad, 

I am not familiarized with the helms operator because of this I will flag this issue and ask help here. However, I understand that it is over the validation.status instead of this one. Something that in Go operator will be generated by the tool as [here](https://github.com/dev4devs-com/postgresql-operator/blob/master/deploy/crds/postgresql_v1alpha1_backup_crd.yaml#L102)

**Comment by joelanford** [comment]
@YathendraPrasad The Helm operator should be writing a status block in pretty much all circumstances (search for "SetCondition" and "updateResourceStatus" in the [Reconcile](https://github.com/operator-framework/operator-sdk/blob/5f663690a3bb97bf7b9e9b8a15a2f8d6bc481808/pkg/helm/controller/reconcile.go) method of the Helm operator)

Here is the struct that defines the status of Helm operator CRs: https://github.com/operator-framework/operator-sdk/blob/5f663690a3bb97bf7b9e9b8a15a2f8d6bc481808/pkg/helm/internal/types/types.go#L77-L80.

Are you able to run the operator outside of scorecard and see that the CR has a status? If so, this is probably something specific to scorecard, and not your operator.

**Comment by YathendraPrasad** [comment]
Yeah i am able to run the operator and i see the status for the CR as below

```

[root@colon1 ~]# oc describe crd mfoperators.mf.ibm.com
Name:         mfoperators.mf.ibm.com
Namespace:    
Labels:       app.kubernetes.io/instance=mf-instance
              app.kubernetes.io/managed-by=helm
              app.kubernetes.io/name=mf-operator
              helm.sh/chart=mf-operator-1.0.2
              release=mf-operator-1.0.2
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2019-09-13T08:19:59Z
  Generation:          1
  Resource Version:    2740222
  Self Link:           /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/mfoperators.mf.ibm.com
  UID:                 46b0ef7d-d5ff-11e9-9cb7-00163e01ac66
Spec:
  Additional Printer Columns:
    JSON Path:    .metadata.creationTimestamp
    Description:  CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    Name:  Age
    Type:  date
  Group:   mf.ibm.com
  Names:
    Kind:       MFOperator
    List Kind:  MFOperatorList
    Plural:     mfoperators
    Short Names:
      mf
    Singular:  mfoperator
  Scope:       Namespaced
  Subresources:
    Status:
  Validation:
    Open APIV 3 Schema:
      Properties:
        API Version:
          Type:  string
        Kind:
          Type:  string
        Metadata:
          Type:  object
  Version:       v1
  Versions:
    Name:     v1
    Served:   true
    Storage:  true
Status:
  Accepted Names:
    Kind:       MFOperator
    List Kind:  MFOperatorList
    Plural:     mfoperators
    Short Names:
      mf
    Singular:  mfoperator
  Conditions:
    Last Transition Time:  2019-09-13T08:19:59Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  <nil>
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1
Events:  <none>
```

**Comment by joelanford** [comment]
@YathendraPrasad That's the CRD, not the CR.

What's the output of `oc get mfoperators.mf.ibm.com -o yaml`?

**Comment by camilamacedo86** [comment]
Hi, @YathendraPrasad 

Also, could you please check your MFOperatorStatus Struct as @joelanford point out in the comment https://github.com/operator-framework/operator-sdk/issues/1934#issuecomment-532717708? Shows that you did not impl status for it.

**Comment by joelanford** [comment]
@camilamacedo86 For helm and ansible operators, operator developers do not implement their own go code. They just add a helm chart and `watches.yaml` on top of the helm-operator base image that the SDK team provides.

See https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md for a tutorial/walkthrough.

**Comment by YathendraPrasad** [comment]
Hi @joelanford : This is the o/p of the watches.yaml

<img width="546" alt="Screenshot 2019-09-19 at 11 45 06 AM" src="https://user-images.githubusercontent.com/28103260/65217920-fd598300-dad2-11e9-839c-541dc4bf1c3c.png">

Is there any thing specific i need to add in watches.yaml ??

**Comment by joelanford** [comment]
@YathendraPrasad There shouldn't be anything you need to add to `watches.yaml`. That looks okay to me. I am a little confused though, so a few more questions:

1. The output of `oc describe crd mfoperators.mf.ibm.com` that you pasted includes labels that indicate it was deployed by helm as part of the `mf-operator` chart. Just want to confirm that you're using a helm chart called `mf-operator` to deploy a helm-based operator and that that CRD is the one from `deploy/crds/`?

2. Scorecard is testing is that the CR has a status block (not the CRD), so I think my original question still makes sense. Can you run the operator and then `oc apply -f deploy/crds/charts_v1_mfoperator_cr.yaml`? Once you do, can you paste the output of `oc get mfoperators.mf.ibm.com -o yaml` and the logs of the operator?

**Comment by YathendraPrasad** [comment]
@joelanford : Answered your questions below::

1. Right we are using helm-based operator and crds are in deploy/crds
2. The out put of the ```mfoperators.mf.ibm.com``` operator .yaml is in the
[output.txt](https://github.com/operator-framework/operator-sdk/files/3634439/output.txt)

**Comment by YathendraPrasad** [comment]
Hi @joelanford  , any update on the issue please

**Comment by YathendraPrasad** [comment]
Hi @joelanford @camilamacedo86 , is there any action from my side to resolve the issue . Please do let me know

**Comment by joelanford** [comment]
@YathendraPrasad sorry I was on vacation last week. I took a look at your output.txt file and there is a status block on your CR starting at line 185, so it isn't immediately clear why scorecard is failing that test. Let me spend some time testing helm-operator with scorecard to see if I can reproduce this issue.

**Comment by joelanford** [comment]
@YathendraPrasad I created a simple helm-based operator from the `stable/tomcat` chart to try to recreate.

```
$ operator-sdk new tomcat-operator --type=helm --helm-chart=stable/tomcat
$ cd tomcat-operator
$ operator-sdk scorecard --olm-tests=false --cr-manifest ./deploy/crds/charts_v1alpha1_tomcat_cr.yaml
```

The above run failed both the `Status Block Exists` and `Writing into CRs has an effect` tests, so I re-ran and simultaneously watched `kubectl get pods` and noticed that my operator was failing to start.

At that point I remembered that I needed to create my operator image and push it to a registry so that it matched the deployment image in `deploy/operator.yaml`. Last, I re-ran the same scorecard command and everything passed.

In your output, I see that the `Writing into CRs has an effect` test is passing, so I would guess that you're not running into the issue I did (can you confirm?).

Looking through the code, my hunch is that it may be taking awhile for the operator to update the status. By default, the scorecard waits 60 seconds during initialization before executing the tests. If it takes longer than 60 seconds for the operator to start and the status to be populated it would result in the false positive that you're seeing.

Can you try to re-run the scorecard with `--init-timeout=300` so that it waits longer before executing the tests after initialization? Not positive that will fix it, but that's my first guess.

**Comment by yathendra** [comment]
Hey Thanks @joelanford . I did figured out the issue . I noticed from the operator logs that it s failing to create security constraints which is in seperate scc.yaml in our project .

From the README.md https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/scorecard.md#config-file , this statement ```By default, the scorecard will combine service_account.yaml, role.yaml, role_binding.yaml, and operator.yaml from the deploy directory into a temporary manifest to use as the namespaced manifest``` which means it doesnot pick up the rest of the *.yaml  present in my project . Is there a way that i could specify to include scc.yaml while running scorecard addditionally .

**Comment by joelanford** [comment]
@YathendraPrasad yes. In that case, you would need to build the appropriate manifest(s) yourself and pass `--global-manifest` and/or `--namespaced-manifest` (depending on the scope of the extra resources you need to add) in your scorecard run

**Comment by joelanford** [comment]
Please let me know if you run into anything else, or if that doesn't work. We can re-open and continue debugging!

**Comment by yathendra** [comment]
@joelanford It would be helpful if you  point me out the procedure of creating manifest / direct me to some samples so that i can follow and try

**Comment by subrnath** [comment]
I am facing similar issue with Ansible based Kubernetes Operator.  With the default operator-sdk generated CRD,  status is coming fine.

piVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: <name>
spec:
  group: <name>
  names:
    kind: 
    listKind:
    plural: 
    singular: 
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}

With the above, "kubectl describe" command shows the status filed properly

Status:
  Conditions:
    Last Transition Time:  2020-09-01T07:03:06Z
    Message:               Running reconciliation
    Reason:                Running
    Status:                True
    Type:                  Running
Events:                    <none>

But when i changed the generated type and replace the above with CR spec parameters

  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              global:
                type: object
                properties:
                  param1:
                    type: boolean
                  param2:
                    type: boolean
----
    served: true
    storage: true
    subresources:
      status: {}


"kubectl describe" command doesn't show any "status" field.

**Comment by apoorva11029** [comment]
> I am facing similar issue with Ansible based Kubernetes Operator. With the default operator-sdk generated CRD, status is coming fine.
> 
> piVersion: apiextensions.k8s.io/v1
> kind: CustomResourceDefinition
> metadata:
> name:
> spec:
> group:
> names:
> kind:
> listKind:
> plural:
> singular:
> scope: Namespaced
> versions:
> 
>     * name: v1alpha1
>       schema:
>       openAPIV3Schema:
>       type: object
>       x-kubernetes-preserve-unknown-fields: true
>       served: true
>       storage: true
>       subresources:
>       status: {}
> 
> 
> With the above, "kubectl describe" command shows the status filed properly
> 
> Status:
> Conditions:
> Last Transition Time: 2020-09-01T07:03:06Z
> Message: Running reconciliation
> Reason: Running
> Status: True
> Type: Running
> Events:
> 
> But when i changed the generated type and replace the above with CR spec parameters
> 
> scope: Namespaced
> versions:
> 
>     * name: v1alpha1
>       schema:
>       openAPIV3Schema:
>       type: object
>       properties:
>       spec:
>       type: object
>       properties:
>       global:
>       type: object
>       properties:
>       param1:
>       type: boolean
>       param2:
>       type: boolean
> 
> 
> ```
> served: true
> storage: true
> subresources:
>   status: {}
> ```
> 
> "kubectl describe" command doesn't show any "status" field.

I am seeing the same issue, were you able to find a fix?

**Comment by nelsonpraveen** [comment]
By adding status in CRD as shown in a sample CRD in - https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
, I was able to view the status with custom fields in the CRD.

I added the below status section to the CRD (shown in bold)

  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
         <the custom definitions go here>
          **status:
              type: object
              properties:
                replicas:
                  type: integer
                labelSelector:
                  type: string**

Note: This is in addition to the status under subresources.
