### ISSUE TITLE
Adding flags (--json in particular) to the ansible-runner command

### ISSUE THREAD

**Issue by Annegies** [operator-framework/operator-sdk#1935]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I want the output to be in json. For this a flag has to be passed to the ansible-runner command (--json) which is not possible as of now.

**Describe the solution you'd like**
An option to pass the --json flag to the ansible-runner command

**Comment by iverberk** [comment]
Could someone from the team respond if this is an acceptable addition? And if there are any plans to implement this. In general, we could create a PR that allows customisation of the ansible-runner parameters.

**Comment by fabianvf** [comment]
Hi, sorry I let this slip, which output are you referring to? Do you mean the ansible stdout that runner records? If so it may be possible to set that now by setting the callback plugin in the `/etc/ansible/ansible.cfg`.
