### ISSUE TITLE
can we watch an existing resource instead of Custom Resource

### ISSUE THREAD

**Issue by rajmechi** [operator-framework/operator-sdk#1944]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
yes

## Question

**Environment**
* operator-sdk version:
  operator-sdk version: v0.8.0,
  insert release or Git SHA here
  commit: 78c472461e75e6c64589cfadf577a2004b8a26b3
* Kubernetes version information:
         kubernetes v1.10.0+b81c8f8
  insert output of `kubectl version` here

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

I see in doc ( https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md ) all about Custom Resource but can we watch  new/changes to  existing ( included in kubernetes API ) resource like Rroute,  ServiceAccount, Service, Secret  etc.

for example i would like to watch Route
``` 
---
- version: v1
  group: route.openshift.io
  kind: Route
  role: /opt/ansible/roles/route
```

![image](https://user-images.githubusercontent.com/39564006/65264854-84abf400-dadd-11e9-8f73-3ef2293952d8.png)

**Comment by jmccormick2001** [comment]
https://github.com/operator-framework/operator-sdk-samples/blob/master/memcached-operator/pkg/controller/memcached/memcached_controller.go#L55

that example watches a Deployment and Services too.

**Comment by rajmechi** [comment]
@jmccormick2001  Thanks for your replay :+1: 

but i am wondering on how can i achieve that using ansible based operator-sdk.

**Comment by mew2057** [comment]
It is possible, for example this can watch a secret:
```
- version: v1
  kind: Secret
  role: /opt/ansible/roles/<a-role>
  manageStatus: false
```

`manageStatus` needs to be set to `false` though in the case of some resource type, otherwise the reconciler will error out.

**Comment by fabianvf** [comment]
@mew2057 you aren't seeing the operator trigger after an update to the resource?

**Comment by mew2057** [comment]
@ fabianvf  The secret watch only triggered when the operator came up. Subsequent edits didn't trigger, only the initial create.

**Comment by fabianvf** [comment]
@mew2057 that's definitely not the expected behavior, would you mind filing an issue for that with your watches.yaml?

**Comment by michaelgugino** [comment]
+1 to this RFE.  I wanted to create a go-based operator that watches configmaps.  It doesn't work out of the box, but it didn't take many tweaks either.  Also, the boiler plate to create a pod was not needed, as that's not the intent of what I'm doing.

**Comment by camilamacedo86** [comment]
Hi @michaelgugino, 

> +1 to this RFE. I wanted to create a go-based operator that watches configmaps.

It is already supported. You can use the watch feature. See in the Memcached sample an example [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/pkg/controller/memcached/memcached_controller.go#L54).

**Comment by camilamacedo86** [comment]
HI @fabianvf, 

Shows that the question raised here is sorted out and an issue for the scenario which shows a specific issue was raised as well #2108. In this way, I am closing this one. However, please feel free to re-open if you see that something still is required to be addressed here.

**Comment by michaelgugino** [comment]
@camilamacedo86 I realize I can use existing examples to create what I want to do.  What I want is to be able to specify a type when using the generation tool so I don't have to make so many modifications.  I don't consider this to be solved.

**Comment by camilamacedo86** [comment]
So, @michaelgugino, if you are looking for an RFE please, raise a new issue of this type telling us what, when and why it would be required. 

Regards the topic `
Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?`

If we cover all and provide the examples, so it shows sorted out. Do not you agree?

**Comment by michaelgugino** [comment]
I'll open an RFE.
