### ISSUE TITLE
Cleanup when operator scaffold fails

### ISSUE THREAD

**Issue by alenkacz** [operator-framework/operator-sdk#1954]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

```
operator-helm operator-sdk new nginx-operator --helm-chart stable/nginx --type helm
INFO[0000] Creating new Helm operator 'nginx-operator'.
Error: failed to create helm chart: failed to fetch chart: chart "nginx" matching "" not found in stable index. (try 'helm repo update'). no chart name found
Usage:
...


operator-helm ls -l nginx-operator
total 0
drwxr-xr-x  2 alenavarkockova  staff  64 Sep 22 08:27 helm-charts
```

**What did you expect to see?**
No nginx-operator folder was created

**What did you see instead? Under which circumstances?**
nginx-operator with partially scaffolded operator, so the command cannot be re-run without removing that.

**Environment**
* operator-sdk version:

operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170

* go version:

go version go1.13 darwin/amd64

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**
helm

**Additional context**

**Comment by camilamacedo86** [comment]
Hi @alenkacz,

Version 1.13 of Go is not supported yet. I believe that it may the cause of the issue.  

Also, I will track it as an RFE for we check if we could improve it by if an issue is faced then remove the partial scaffold project created so far. It would be valid for all types (go, ansible and helm).  

Wdyt @joelanford ?

**Comment by camilamacedo86** [comment]
We could address it after the integration with Kubebuilder or there as well.

**Comment by estroz** [comment]
@alenkacz you can effectively get this behavior using VCS like `git`. I'd say this shouldn't be an SDK feature.

**Comment by alenkacz** [comment]
@estroz I don't agree, I think it's a good practice to cleanup after yourself, be it temporary folders or something that is not really functional and is left on the disk. Especially because with this, operator creation cannot be simply re-run :) pushing this to the user and letting him/her initialize a git repository prior to running operator-sdk for the first time is an option, but not very user-friendly one :)
