### ISSUE TITLE
Provide user understandable error message for OpenAPI validation failure

### ISSUE THREAD

**Issue by umangachapagain** [operator-framework/operator-sdk#1962]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, when my Custom Resource fails OpenAPI validation, I receive a big dump of the whole CR with the error message mixed in between.

When using UI to create this resource, user gets this hard to decode dump on the screen.
This message should be user understandable and not break UI/UX.

(Same applies for CLI way of creating CRs.)

I was suggested to use `Response` spec of OpenAPI. But, I do not see any annotation that can generate this spec for me. If I do it manually, this will be removed next time when I do `operator-sdk generate openapi`

**Describe the solution you'd like**
Annotation or some other way needs to be added to provide user understandable error messages when OpenAPI validations fail.

For e.g When we request for Negative size PVC, Kubernetes provides a well formated error message saying "negative values are not allowed for PVC requests" instead of throwing the entire PVC manifest back to the user.

**Comment by umangachapagain** [comment]
If someone could point to an exisiting feature similar to this, I'd be happy to close this.
(Assuming operator-sdk is the right place to take care of this.)

**Comment by camilamacedo86** [comment]
Hi @umangachapagain, 

Could you please add here the following information for we are able to help you better with ?

1. An error msg example of an attribute in a CR that would like to have a customized msg 
2. The code implementation that you have in the *_type.go for this attribute with its annotations

**Comment by umangachapagain** [comment]
Code implementation in `*_types.go` ,
https://github.com/openshift/ocs-operator/blob/bed1df0ab1659a831ff984938087a3de80e1ac0b/pkg/apis/ocs/v1/storagecluster_types.go#L31-L32

```
type StorageDeviceSet struct {
	Name string `json:"name"`
	// +kubebuilder:validation:Minimum=1
	Count           int                          `json:"count"`
	Resources       corev1.ResourceRequirements  `json:"resources"`
	Placement       rookalpha.Placement          `json:"placement"`
	Config          StorageDeviceSetConfig       `json:"config,omitempty"`
	DataPVCTemplate corev1.PersistentVolumeClaim `json:"dataPVCTemplate"`
	Portable        bool                         `json:"portable"`
}
```

CRD part of code where validation is generated,
https://github.com/openshift/ocs-operator/blob/bed1df0ab1659a831ff984938087a3de80e1ac0b/deploy/crds/ocs_v1_storagecluster_crd.yaml#L51-L54

```
            storageDeviceSets:
              items:
                properties:
                  config:
                    type: object
                  count:
                    format: int64
                    minimum: 1
                    type: integer
```

Error message that is received,
```
Error "Invalid value: map[string]interface {}{"apiVersion":"ocs.openshift.io/v1", "kind":"StorageCluster", "metadata":map[string]interface {}{"creationTimestamp":"2019-09-19T10:47:22Z", "generation":2, "name":"ocs-storagecluster", "namespace":"openshift-storage", "resourceVersion":"35229", "uid":"dc12e08e-daca-11e9-8a28-0a6bf9652cfe"}, "spec":map[string]interface {}{"managedNodes":false, "storageDeviceSets":[]interface {}{map[string]interface {}{"count":4.5, "dataPVCTemplate":map[string]interface {}{"spec":map[string]interface {}{"accessModes":[]interface {}{"ReadWriteOnce"}, "resources":map[string]interface {}{"requests":map[string]interface {}{"storage":"1Ti"}}, "storageClassName":"gp2", "volumeMode":"Block"}}, "name":"ocs-deviceset", "placement":map[string]interface {}{}, "portable":true, "resources":map[string]interface {}{}}}}, "status":map[string]interface {}{"conditions":[]interface {}{map[string]interface {}{"lastHeartbeatTime":"2019-09-19T11:07:41Z", "lastTransitionTime":"2019-09-19T10:47:22Z", "message":"Reconcile completed successfully", "reason":"ReconcileCompleted", "status":"True", "type":"ReconcileComplete"}, map[string]interface {}{"lastHeartbeatTime":"2019-09-19T11:07:41Z", "lastTransitionTime":"2019-09-19T10:52:32Z", "message":"Reconcile completed successfully", "reason":"ReconcileCompleted", "status":"True", "type":"Available"}, map[string]interface {}{"lastHeartbeatTime":"2019-09-19T11:07:41Z", "lastTransitionTime":"2019-09-19T10:52:32Z", "message":"Reconcile completed successfully", "reason":"ReconcileCompleted", "status":"False", "type":"Progressing"}, map[string]interface {}{"lastHeartbeatTime":"2019-09-19T11:07:41Z", "lastTransitionTime":"2019-09-19T10:47:22Z", "message":"Reconcile completed successfully", "reason":"ReconcileCompleted", "status":"False", "type":"Degraded"}, map[string]interface {}{"lastHeartbeatTime":"2019-09-19T11:07:41Z", "lastTransitionTime":"2019-09-19T10:52:32Z", "message":"Reconcile completed successfully", "reason":"ReconcileCompleted", "status":"True", "type":"Upgradeable"}}, "phase":"Ready", "relatedObjects":[]interface {}{map[string]interface {}{"apiVersion":"ceph.rook.io/v1", "kind":"CephCluster", "name":"ocs-storagecluster", "namespace":"openshift-storage", "resourceVersion":"35227", "uid":"dc204f45-daca-11e9-95c3-06f006ddaeb0"}}}}: validation failure list: spec.storageDeviceSets.count in body must be of type int64: "float64"" for field "[]"
```

Error message that I expect,
```
Error "Invalid value: spec.storageDeviceSets.count in body must be of type int64"
```
Some metadata (Kind, Name and Version) would be good to have but having entire CR dump inside `map[string]interface` is not very useful.

Also, I have noticed that even though validation says `minimum: 1`, `0` value is accepted and no error is returned. Where do I raise this bug?

**Comment by camilamacedo86** [comment]
Hi @umangachapagain, 

The error added here shows be from the operator logs and has no relation with the validation. For you check the validation error it will be output in your shell when the CR be applied and not get from the operator.  So, could you please try to add an invalid value for this field in your CR and then apply it and check its output?

**Comment by umangachapagain** [comment]
> If you check the log added by you it shows came from the operator logs and not from the output when the CR is applied because of this it has more information and not just the validation error.
>
We do not have a custom client generated to handle CRUD operations and seems to be using default behavior what operator-framework provides. Do you think that could be an issue?
On the operator side we don't do anything to send a response back to user.
I am investigating use of client-gen to fix this. If it works, i will update (probably close) this issue.
> 
> In this way, could you do the following checks?
>
>   Could you check the validation error output in the shell when the CR is applied?
>
Shell also gives the same error.
>   
>   Could you try to add a description in the field and check if it will change the output?
>
It adds description field to crd. Nothing related to validation.
>
> Also, could you clarify what UI/UX it is breaking? Are you using OLM?
>
Yes, we are using OLM. But, for OCS we have custom components.
Displaying such big dump on small card sized components causes overflow issue and real error message is invisible.

**Comment by camilamacedo86** [comment]
Hi @umangachapagain, 

The validation is made by k8s API which is using OpenAPI.  **Note that the error msg is returned by the API which is the CR schema + validation failure list: + [] output of errors.** 

Following an example of the error output. 
**`spec.databaseCRName in body should be at most 3 chars long`**

For further information see [here](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition) the k8s documentation over the CRD API and how the schemas validations work. All valid properties can be found [here](https://godoc.org/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1#JSONSchemaProps). 

I'd like to suggest you open an issue against the Kubernetes repos requesting it as a feature since  I could not find a property in the schema which would allow you customize the error messages as you wish. May this one https://github.com/kubernetes/kube-openapi would be a good place for it. 

## Regards de UI (OLM):

You can use annotations to customise the UI as the following example. 

```go
	// Name of the Database CR applied which this backup will work with
	// Default Value: "database"
	// +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors=true
	// +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors.displayName="Name of Database CR"
	DatabaseCRName string `json:"databaseCRName,omitempty"`
```

However, note that this data needs to be generated in the CSV for it be to reflect. See [here](https://github.com/dev4devs-com/postgresql-operator/blob/master/deploy/olm-catalog/postgresql-operator/0.1.1/postgresql-operator.v0.1.1.clusterserviceversion.yaml#L74).

**NOTE:** 
- You can try to use the [PR](https://github.com/operator-framework/operator-sdk/pull/1162) to help generate the CSV since it is not yet added on the tool. 

Please, let me know if the above information answers your question and if you agree in close this one.
