### ISSUE TITLE
CRs names are not following the format

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1965]
## Bug Report

**What did you do?**
Update for the master branch and generate the code with the sdk. (operator-sdk generate k8s)

**What did you expect to see?**
CR's and CRD's created with new standard/format name

**What did you see instead? Under which circumstances?**
CR's were not recreated. 
<img width="511" alt="Screenshot 2019-09-25 at 18 27 40" src="https://user-images.githubusercontent.com/7708031/65624770-73258900-dfc2-11e9-9651-6f48763fbda5.png">

**Environment**
* operator-sdk version: "v0.10.0-50-g3a85983e",

**Comment by camilamacedo86** [comment]
c/c @estroz

**Comment by estroz** [comment]
I'm not sure this is necessarily a bug, because `generate k8s` does not regenerate CRs by design. We should instead add a note to rename CRs in the migration guide between v0.10.0 and the next release (v0.11.0).

**Comment by camilamacedo86** [comment]
I am closing this one since the steps to fix it was added in the Migration doc.
