### ISSUE TITLE
Add predicates to Ansible operator for filtering Update, Delete, and Create events

### ISSUE THREAD

**Issue by rammohanc** [operator-framework/operator-sdk#1968]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Without predicates for update events, controller is triggering reconcile for objects that have not changed, by user, causing unnecessary reconciles. Adding predicates to the Ansible operator, similar to how Helm operator is handling the update, create and delete events, will help optimize the Ansible operator. We have tried the above changes for update event and it helped reduce the amount of reconciles (or the number of times the playbook is run) significantly as we have many CRs (close to hundred)

**Describe the solution you'd like**
Predicates should be added before the events are passed to the controller.

**Comment by camilamacedo86** [comment]
c/c @fabianvf

**Comment by shawn-hurley** [comment]
I would really like to understand the reasoning for wanting these direct events. 

We have tried to hide this from the user as we don't believe that this information is necessary and causes more edge cases then you would expect. to see a more detailed response look here: https://github.com/kubernetes-sigs/controller-runtime/issues/374#issuecomment-480415643 

I would love to help figure out what/why we need this and how we can enable the functionality you're looking for without exposing the events.

**Comment by joelanford** [comment]
@rammohanc Are you talking about [this predicate](https://github.com/operator-framework/operator-sdk/blob/1a5772eb71859693c9c0fa5042d33599df30b29f/pkg/helm/controller/controller.go#L95-L132) that is used to filter events of dependent resources?

**Comment by rammohanc** [comment]
Hi @shawn-hurley 

Reason behind the feature ask is we are seeing the occasional reconciles on CRs, that have not changed or its dependents have not been updated by the user (watchDependentResources and inject_owner_reference are turned on). When we are getting the update event for any of the dependent objects , that have not been updated by the user, reconcile is getting triggered.  We want to avoid these reconcile or running playbook when we know there is no change to the dependent object similar to how Helm operator is handling these events. We made the changes and we don't see the above mentioned reconciles. 

Thanks

> I would really like to understand the reasoning for wanting these direct events.
> 
> We have tried to hide this from the user as we don't believe that this information is necessary and causes more edge cases then you would expect. to see a more detailed response look here: [kubernetes-sigs/controller-runtime#374 (comment)](https://github.com/kubernetes-sigs/controller-runtime/issues/374#issuecomment-480415643)
> 
> I would love to help figure out what/why we need this and how we can enable the functionality you're looking for without exposing the events.

**Comment by rammohanc** [comment]
Hi @joelanford ,

Yes, we have used some of that logic (for update event) to address the reconciles that are not needed. 


> @rammohanc Are you talking about [this predicate](https://github.com/operator-framework/operator-sdk/blob/1a5772eb71859693c9c0fa5042d33599df30b29f/pkg/helm/controller/controller.go#L95-L132) that is used to filter events of dependent resources?
