### ISSUE TITLE
Watch for not connected resources

### ISSUE THREAD

**Issue by afoninsky** [operator-framework/operator-sdk#1974]
## Type of question

best practice request
## Question

My operator should watch for additional resources created outside (not linked with operator's resources). It is  a separated logic and I don't need to pass events to 'Reconcile' method.
So I've created following code and it looks working:
```
// add adds a new Controller to mgr with r as the reconcile.Reconciler
func add(mgr manager.Manager, r reconcile.Reconciler) error {
	c, err := controller.New("stream-controller", mgr, controller.Options{Reconciler: r})
	if err != nil {
		return err
	}

	mapFn := handler.ToRequestsFunc(
		func(a handler.MapObject) []reconcile.Request {
			objCopy := a.Object.DeepCopyObject()
			key, err := dynclient.ObjectKeyFromObject(objCopy)
			if err != nil {
				panic(err)
			}

			instance := &corev1.Endpoints{}
			err = mgr.GetClient().Get(context.TODO(), key, instance)
			if err != nil {
				panic(err)
			}
			if err != nil {
				if errors.IsNotFound(err) {
					// TODO: resource removed
				}
				panic(err)
			}
			// TODO: resource upserted
			return []reconcile.Request{}
		})

	err = c.Watch(&source.Kind{Type: &corev1.Endpoints{}}, &handler.EnqueueRequestsFromMapFunc{
		ToRequests: mapFn,
	})
```

But I'm wondering - it doesn't look like a preferred way. I tried to search in issues and found something about "watcher" helpers. But didn't find any actual documentation or examples.

Any thoughts about how I can implement it in a better way? Thank you.

**Comment by camilamacedo86** [comment]
Hi @afoninsky, 

For we are able to use objects that are not from k8s API and are not from your operator project API you need to import the schemas. See here an example of the Route from OCP Api been imported how it works in the docs: https://github.com/operator-framework/operator-sdk/blob/05a106abd9ff94bb2f0cc84b5054d0a603c9474f/doc/user-guide.md#adding-3rd-party-resources-to-your-operator. 

Please, let us know if answer your question and if we can close this one.

**Comment by camilamacedo86** [comment]
HI @afoninsky,

IMHO: The preferred would be as it is suggested in the doc provided. Have you any reason to not follow that?
