### ISSUE TITLE
Support to generate clientset

### ISSUE THREAD

**Issue by kameshsampath** [operator-framework/operator-sdk#1975]
Right now there is no clientset generated with operator-sdk, this makes it difficult to use the API with other needed applications. It will be nice if the operator-sdk can  generate the client using the https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/generating-clientset.md

**Comment by camilamacedo86** [comment]
Hi @kameshsampath, 

Thank you to raise your suggestion.

**Comment by avarabyeu** [comment]
Is there any chance support of clientset generation will be added in the future?

**Comment by mkimuram** [comment]
@camilamacedo86 @kameshsampath @avarabyeu 

I have the same use case. So, I tried it manually and managed to generate client code by using [slok/kube-code-generator](https://github.com/slok/kube-code-generator). (See details below for all the steps that I did.)

I'm not enough familiar with clientset generation to ensure that I did it in the right way. If someone can confirm that it is good enough, I might be able to add this feature to operator-sdk. (It will require just two-lines addition in generated codes and one command execution.) 

/remove-lifecycle rotten

<details>

1. Create new operator
```
$ mkdir -p $GOPATH/github.com/example-inc/ 
$ cd $GOPATH/github.com/example-inc/ 
$ operator-sdk new app-operator --repo github.com/example-inc/app-operator
$ cd app-operator
$ operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=AppService
$ operator-sdk add controller --api-version=app.example.com/v1alpha1 --kind=AppService
$ export USERNAME=<username>
$ operator-sdk build quay.io/$USERNAME/app-operator
```

2. modify types.go and add "// +genclient"
```
$ cp pkg/apis/app/v1alpha1/appservice_types.go pkg/apis/app/v1alpha1/appservice_types.go.orig
$ vi pkg/apis/app/v1alpha1/appservice_types.go
$ diff -urN pkg/apis/app/v1alpha1/appservice_types.go.orig pkg/apis/app/v1alpha1/appservice_types.go
--- pkg/apis/app/v1alpha1/appservice_types.go.orig      2020-03-30 20:56:48.452325253 +0000
+++ pkg/apis/app/v1alpha1/appservice_types.go   2020-03-30 20:57:35.692525564 +0000
@@ -22,6 +22,7 @@
 }
 
 // +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
+// +genclient
 
 // AppService is the Schema for the appservices API
 // +kubebuilder:subresource:status
```

3. Modify register.go and add "AddToScheme"
```
$ cp pkg/apis/app/v1alpha1/register.go pkg/apis/app/v1alpha1/register.go.orig
$ vi pkg/apis/app/v1alpha1/register.go
$ diff -urN pkg/apis/app/v1alpha1/register.go.orig pkg/apis/app/v1alpha1/register.go
--- pkg/apis/app/v1alpha1/register.go.orig      2020-03-31 18:58:05.385480861 +0000
+++ pkg/apis/app/v1alpha1/register.go   2020-03-31 19:06:37.896654043 +0000
@@ -16,4 +16,5 @@
 
        // SchemeBuilder is used to add go types to the GroupVersionKind scheme
        SchemeBuilder = &scheme.Builder{GroupVersion: SchemeGroupVersion}
+       AddToScheme   = SchemeBuilder.AddToScheme
 )
```

4. Create Makefile to run slok/kube-code-generator
```
$ vi Makefile
$ cat Makefile
IMAGE := quay.io/slok/kube-code-generator:v1.16.7

DIRECTORY := $(PWD)
PROJECT_PACKAGE := "github.com/example-inc/app-operator"
GROUPS_VERSION := "app:v1alpha1"

.PHONY: generate-client
generate-client:
        docker run -it --rm \
        -v $(DIRECTORY):/go/src/$(PROJECT_PACKAGE) \
        -e PROJECT_PACKAGE=$(PROJECT_PACKAGE) \
        -e CLIENT_GENERATOR_OUT=$(PROJECT_PACKAGE)/pkg/client \
        -e APIS_ROOT=$(PROJECT_PACKAGE)/pkg/apis \
        -e GROUPS_VERSION=$(GROUPS_VERSION) \
        -e GENERATION_TARGETS="deepcopy,client" \
        $(IMAGE)
```

5. Run make and generate client code (By this command, code is generated under pkg/client.)
```
$ make generate-client
```

6. Create code to test generated client
```
$ mkdir client
$ cd client
$ vi example.go
$ cat example.go
package main

import (
        "fmt"
        "os"

        appv1alpha1 "github.com/example-inc/app-operator/pkg/apis/app/v1alpha1"
        clientappv1alpha1 "github.com/example-inc/app-operator/pkg/client/clientset/versioned/typed/app/v1alpha1"
        apierrors "k8s.io/apimachinery/pkg/api/errors"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
        "k8s.io/client-go/tools/clientcmd"
)

func main() {
        kubeConfig := os.Getenv("KUBECONFIG")
        clientConfig, err := clientcmd.BuildConfigFromFlags("", kubeConfig)
        if err != nil {
                panic(err)
        }

        cl, err := clientappv1alpha1.NewForConfig(clientConfig)
        if err != nil {
                panic(err)
        }
        app := &appv1alpha1.AppService{
                ObjectMeta: metav1.ObjectMeta{
                        Name: "test-app",
                },
                Spec: appv1alpha1.AppServiceSpec{},
        }
        r, err := cl.AppServices("default").Create(app)
        if err != nil && !apierrors.IsAlreadyExists(err) {
                panic(err)
        }

        fmt.Printf("Created app resource: %s\n", r.Name)

        l, err := cl.AppServices("default").List(metav1.ListOptions{})
        if err != nil {
                panic(err)
        }

        fmt.Printf("List of app resources:\n")
        for i, item := range l.Items {
                fmt.Printf("\t%d: %s\n", i, item.Name)
        }
}
```

7. Build the code
```
$ export GO111MODULE=on
$ go build -o example .
```

8. Test with the client (It shows that the client can add and list the appservices resources.)
```
$ export KUBECONFIG=~/.kube/config 
$ kubectl create -f ../deploy/crds/app.example.com_appservices_crd.yaml
customresourcedefinition.apiextensions.k8s.io/appservices.app.example.com created
$ kubectl create -f ../deploy/crds/app.example.com_v1alpha1_appservice_cr.yaml 
appservice.app.example.com/example-appservice created

$ kubectl get appservice
NAME                 AGE
example-appservice   5s

$ ./example
Created app resource: test-app
List of app resources:
        0: example-appservice
        1: test-app

$ kubectl get appservice
NAME                 AGE
example-appservice   47s
test-app             28s
```

**Comment by mkimuram** [comment]
>  I might be able to add this feature to operator-sdk. (It will require just two-lines addition in generated codes and one command execution.)

This [patch](https://github.com/mkimuram/operator-sdk/commit/ef6dbb1d1dd7360a288bf82f7939781a8a4ef90e) should (re)generate client on `add api` and `generate k8s`. If this makes sense, I will make a PR. 
(We might need to create separate sub-command, like `generate client`, in order to specify container environment other than docker, and so on.)

**Comment by joelanford** [comment]
Re-opening for discussion since this has some new activity.

I think we’re unlikely to accept patches to build this into the SDK CLI. We recently deprecated and removed support for Go openapi code generation and started directing folks to use `openapi-gen` directly.

If think it follows that we would make a similar suggestion for client generation.

Ping @estroz

**Comment by estroz** [comment]
@joelanford @mkimuram we could add a section about generators with links in the user guide for Go operators.

**Comment by estroz** [comment]
I think we can punt on this for now since generators are generally well-known. See https://github.com/operator-framework/operator-sdk/pull/2803#issuecomment-610645354.

**Comment by SpecialYang** [comment]
Anyone working on this? Does this feature has been implemented?

**Comment by mkimuram** [comment]
According to https://github.com/kubernetes-sigs/kubebuilder/issues/1152 , the kubebuilder community recommends to use controller-runtime client or to generate typed clientset by using upstream client-gen.
@camilamacedo86 @estroz Is my understanding right that operator-sdk recommends the same ways?
