### ISSUE TITLE
gen-csv requires CRD files to have _crd.yaml suffix

### ISSUE THREAD

**Issue by MatousJobanek** [operator-framework/operator-sdk#1980]
## Bug Report

**What did you do?**
we used this command for generating CRD yaml files out of `*_types.go` files
```
go run ./vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go crd \
	--domain dev.openshift.com \
	--output-dir deploy/crds
```
That generated a list of CRDs with filenames:
```
toolchain_v1alpha1_masteruserrecord.yaml
toolchain_v1alpha1_nstemplatetier.yaml
toolchain_v1alpha1_usersignup.yaml
```
Then we executed 
```
operator-sdk olm-catalog gen-csv --csv-version 0.0.1 --update-crds
```
but the CRD files weren't checked & coppied to the `olm-catalog/host-operator/0.0.1` directory
It's the same no matter what I set into `csv-config.yaml` file - I tried:
* specifying a new regex
```
crd-cr-paths:
- deploy/crds/*.yaml
```
* directly listing the files
```
crd-cr-paths:
- deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
- deploy/crds/toolchain_v1alpha1_nstemplatetier.yaml
- deploy/crds/toolchain_v1alpha1_usersignup.yaml
```

but the files weren't still copied

**What did you expect to see?**
When I specify a new regex or when I list the files in `csv-config.yaml` file, then the files should be checked & coppied

**What did you see instead? Under which circumstances?**
nothing was coppied:
```
$ tree deploy/olm-catalog/host-operator/
deploy/olm-catalog/host-operator/
├── 0.0.1
│   └── host-operator.v0.0.1.clusterserviceversion.yaml
└── host-operator.package.yaml
```

**Environment**
* operator-sdk version:

```
operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170
```

* go version:

```
go version go1.12.7 linux/amd64
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+68e229c", GitCommit:"68e229c", GitTreeState:"clean", BuildDate:"2019-08-06T18:30:32Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-09-20T11:09:36Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

openshift

* Are you writing your operator in ansible, helm, or go?

go

**Possible Solution**
Accept a new regex from `csv-config.yaml` file or the directly listed files

**Comment by hasbro17** [comment]
@estroz We can relax this restriction and drop the check for the `crd.yaml` suffix right?

https://github.com/operator-framework/operator-sdk/blob/ff284ea01e7ecc5cea0f9b69a6cc6d9083e84b02/cmd/operator-sdk/olmcatalog/gen-csv.go#L170-L173

For the provided `crd-cr-paths` manifests we can make the CRD CR distinction by checking the `kind: CustomResourceDefinition` for the manifest instead.
I think that's already how we separate the CRD and CRs when populating the CSV alm-examples field.

**Comment by estroz** [comment]
@hasbro17 yes, this should be done using utilities in [k8sutil](https://github.com/operator-framework/operator-sdk/tree/master/internal/util/k8sutil).

**Comment by MatousJobanek** [comment]
Awesome, thanks guys for fixing it :+1:
