### ISSUE TITLE
Question: How can we specify the namespace where the helm charts should be installed

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#2002]
## Question

How can we specify the namespace where the helm charts should be installed using a helm operator-sdk operator ?

When we use the `helm` client, we can specify where a chart should be deployed 
```
helm install appscode/kubedb-catalog --name kubedb-catalog \
      --namespace {{ kubedb_namespace }}
```

Can we do that with the Helm Operator SDK ?

**Comment by camilamacedo86** [comment]
c/c @joelanford

**Comment by joelanford** [comment]
@cmoulliard Yes, the helm-operator supports only namespace-scoped CRDs to define releases. When a CR is created in a namespace, the helm-operator will create the corresponding release in that same namespace.

If you need more info, let us know and we can re-open!
