### ISSUE TITLE
Add tests to ensure the gen-csv commands

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#2016]
## What
- Check what is missing and add tests to ensure the gen-csv commands for example `operator-sdk olm-catalog gen-csv --update-crds`

**Comment by joelanford** [comment]
:+1: It has been on our plate to add unit tests for the components that make up `gen-csv`. It would definitely be good to add these.

**Comment by hasbro17** [comment]
We have some unit tests for the CSV scaffolding that do test the basic scenarios like new CSVs and updates to existing ones https://github.com/operator-framework/operator-sdk/blob/master/internal/pkg/scaffold/olm-catalog/csv_test.go

But we need to see what's missing in order to catch bugs like #2015 and #2017 
/cc @estroz

**Comment by flickerfly** [comment]
Here are some of the things I've documented having to edit in my CSV after running `gen-csv`. I hope that is helpful. If I should open these as a different ticket, please say so. 

- spec.keywords
- spec.maintainers
- spec.provider
- metadata.namespace
- spec.icon (base64 encoded image embedded in the yaml)
- spec.customresourcedefinitions
- spec.customresourcedefinitions.owned.[description, displayName, kind, name, version, resources]

**Comment by camilamacedo86** [comment]
Hi @flickerfly, 

This task is about we add a test for the command which is implemented already, so you have been editing manually the CSV because the tool is not implemented to generated this fields and it would be out of the scope of this issue. Could you please open a new issue since the subject is not the same? 

Really thank you.

**Comment by camilamacedo86** [comment]
It was done already. Closing with sorted out. 
/remove-lifecycle stale
