### ISSUE TITLE
Question: when can we have next release?

### ISSUE THREAD

**Issue by YanFenGuo** [operator-framework/operator-sdk#2020]
I'm expecting ubi8 which have been committed in master branch, wondering when is next formal release so we can upgrade our operator.
Checking https://quay.io/repository/operator-framework/ansible-operator?tab=tags, it has been two months since last release, suppose it should be soon, right?

**Comment by hasbro17** [comment]
We're currently waiting to get some bug fixes into the master but we expect to cut the `v0.11.0` release soon, hopefully by the end of this week.

**Comment by YanFenGuo** [comment]
Great, expecting the new release, thanks a lot!

**Comment by YanFenGuo** [comment]
@hasbro17 I saw ansible-operator:0.10.1 released, but it is still based on ubi 7. 
I'm wondering when is next release with ubi 8?

I see branch release-4.4 have ubi8: https://github.com/operator-framework/operator-sdk/blob/release-4.4/ci/dockerfiles/ansible.Dockerfile
What's the ansible-operator tag to use for this release?

**Comment by hasbro17** [comment]
@YanFenGuo UBI 8 should be in the ansible base image for the `v0.11.0` release tag.
We're in the midst of releasing that currently as we're addressing some last minute bugs.
https://github.com/operator-framework/operator-sdk/pull/2047

**Comment by YanFenGuo** [comment]
Thank you, I can see v0.11.0 is released now!
