### ISSUE TITLE
Immediate Garbage Collection

### ISSUE THREAD

**Issue by hyprnick** [operator-framework/operator-sdk#2029]
## Type of question

Help with bug

## Question

**What did you do?**
I have a cluster wide operator that only runs in the default namespace. Within the operator I have two controllers. One controller that watches for an `Org` resource the other controller watches for a sub resource within the namespaces created by the `Org` controller. 

When an `Org` resource is created, it creates a namespace and several resources inside that namespace. Some of those resources are secrets.  Since secrets are not cluster wide, I copy some secrets into the namespace.  

Here is my `reconcileSecret` function
```go
func (r *ReconcileOrg) reconcileSecret(rlog *logrus.Entry, Org *mycrd.Org, secret string) (*reconcile.Result, error) {
	// Check if the target namespace contains this secret
	namespace := fmt.Sprintf("org-%d", org.Spec.Org)
	nn := types.NamespacedName{
		Namespace: namespace,
		Name:      secret,
	}
	s := &corev1.Secret{}
	err := r.client.Get(context.TODO(), nn, s)
	if err != nil {
		if !errors.IsNotFound(err) {
			return nil, err
		}

		// Get the master secret
		nn := types.NamespacedName{
			Namespace: "default",
			Name:      secret,
		}
		ms := &corev1.Secret{}
		err := r.client.Get(context.TODO(), nn, ms)
		if err != nil {
			if errors.IsNotFound(err) {
				return nil, fmt.Errorf("Could not find master secret \"%s\" in namespace default", secret)
			}
			return nil, err
		}

		rlog.WithField("secret", secret).Info("Creating Secret")
		s = &corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{
				Namespace: namespace,
				Name:      secret,
			},
			Data:       ms.Data,
			StringData: ms.StringData,
			Type:       ms.Type,
		}
		err = controllerutil.SetControllerReference(org, s, r.scheme)
		if err != nil {
			return nil, err
		}
		err = r.client.Create(context.TODO(), s)
		if err != nil {
			return nil, err
		}
		org.Status.Available = false
		return &reconcile.Result{
			Requeue:      true,
			RequeueAfter: 5 * time.Second,
		}, nil
	}

	return nil, nil
}
```

**What did you expect to see?**
I expect the secrets to be created. 

**What did you see instead? Under which circumstances?**
For a period of time, this seems to work great. However, after a certain amount of time (days or a week), things go wrong.  I'll check and all the secrets in the namespace will be gone. I'll check the logs of the operator and its in an endless loop of trying to create the secrets.  

If I `--watch` the secrets in that namespace, I'll see that when they are created, they get deleted immediately.  

I have tried commenting out the `SetControllerReference` and the resources do not get deleted so I'm assuming garbage collection is removing the resources. My `Org` resource is not deleted or being deleted (no deleted timestamp) and the UUID matches in the owner reference section of the Secret.  

This doesn't seem to happen with just Secrets. I started with my CRD creating everything including the namespace. After several days, I'll check my cluster and the namespace will be in the `Terminating` state and all pods trying to be deleted.  

To work around this issue, I started to remove the controller reference to avoid garbage collection.  

Any help would be appreciated. I have contacted DO to get kubelet logs however I'm not sure if those will help.  

**Environment**
* operator-sdk version:

operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170

* Kubernetes version information:

I saw this issue when my cluster was version 1.13 and have since upgraded to 1.15 and still see this problem.  

```Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
DigitalOcean

**Additional context**
The operator has two controllers, one for the `Org` and one for within the namespace to watch for sub resources.  I'm not sure if this is causing the conflict and I should split this into two operators.  This controller doesn't seem to have the same issues.

**Comment by hyprnick** [comment]
I think I found the answer here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L297-L299

Cluster scoped objects cannot have an owner reference in another namespace.  So when the object is created in the other namespace with an owner reference to the one in default, garbage collection can't find it and deletes it.  

I'll test this theory and post an update.

**Comment by joelanford** [comment]
@hyprnick Correct. The only supported owner to child relationships are:
1. Cluster-scoped owner to cluster-scoped child.
2. Cluster-scoped owner to namespace-scoped child.
3. Namespace-scoped child to namespace-scoped child, where both owner and child are in the same namespace.

If I'm understanding correctly, you would need to make your `Org` resource cluster-scoped.

Let us know what you find! And if you still need help designing your operator, we can re-open and help you figure it out!

**Comment by hyprnick** [comment]
@joelanford Thanks for the reply!  The `Org` resource _should_ be cluster scoped.  Do you have any references for doing that? Thank you
