### ISSUE TITLE
Creating unstructured.Unstructured object leads to controller error "the server does not allow this method on the requested resource"

### ISSUE THREAD

**Issue by aerdei** [operator-framework/operator-sdk#2033]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
General context and help around the operator-sdk

## Question

**What did you do?**
When trying to use the client to create an unstructured object, an error occurs: "the server does not allow this method on the requested resource".
```go
[...]
u := &unstructured.Unstructured{}
u.Object = map[string]interface{}{
        "name":      "name",
        "namespace": "namespace",
        "spec": map[string]interface{}{
                "replicas": 2,
                "selector": map[string]interface{}{
                        "matchLabels": map[string]interface{}{
                                "foo": "bar",
                        },
                },
                "template": map[string]interface{}{
                        "labels": map[string]interface{}{
                                "foo": "bar",
                        },
                        "spec": map[string]interface{}{
                                "containers": []map[string]interface{}{
                                        {
                                                "name":  "nginx",
                                                "image": "nginx",
                                        },
                                },
                        },
                },
        },
}
u.SetGroupVersionKind(schema.GroupVersionKind{
        Group:   "apps",
        Kind:    "Deployment",
        Version: "v1",
})
if err := r.client.Create(context.TODO(), u); err != nil {
        return reconcile.Result{}, err
}
[...]
```
(I'm using the example from https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client#example-Client--Create)
**What did you expect to see?**
The object is created on the cluster.

**What did you see instead? Under which circumstances?**
An error occurs:
```go
{"level":"error","ts":1570708735.755607,"logger":"controller-runtime.controller","error":"the server does not allow this method on the requested resource"}
```

**Environment**
* operator-sdk version:
operator-sdk version: "v0.10.0-72-gdc713e4d", commit: "dc713e4d78905ce67128680a7f823a95ba3db234", go version: "go1.12.10 linux/amd64"

* Kubernetes version information:
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

* Kubernetes cluster kind: 
OpenShift v3.11.141

**Comment by aerdei** [comment]
The issue was with the incorrect structure of the Deployment object. Name and namespace belong under metadata.

**Comment by camilamacedo86** [comment]
Really thank you for let us know @aerdei. 
I am glad that you could solve it before we have time to help you with.
