### ISSUE TITLE
Use controllerutil.CreateOrUpdate in scaffolded controllers & examples

### ISSUE THREAD

**Issue by grdryn** [operator-framework/operator-sdk#2057]
## Feature Request

I recently discovered the `controllerutil.CreateOrUpdate` function in the controller-runtime project, and I think it's a really good way to handle secondary resources in the reconciliation method of controllers.

**Is your feature request related to a problem? Please describe.**
Being able to create controllers from the operator-sdk CLI, but if I follow the example pattern (for secondary resources at least) in the scaffolded `Reconcile` method, it can start to get a little hairy when there are lots of fields in a secondary resource that need to be kept in check.

**Describe the solution you'd like**
I've created a PR in the operator-sdk-samples repo to update the memcached-operator as an example to highlight what I mean. I'd love feedback on that, if you have any! If you think this is a good idea, I'm happy to update any other examples, or the scaffold templates in this repo in the same way.

Example PR: https://github.com/operator-framework/operator-sdk-samples/pull/77

**Comment by camilamacedo86** [comment]
IMHO what we could is to add in the docs some annotation and or description suggesting users check the controller-runtime godocs for further option as for example the [CreateOrUpdate](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil#CreateOrUpdate)

**Comment by camilamacedo86** [comment]
It was closed in the bug triaged:

The reason, the client has some options and features that can be used and then examples and its docs can be found in the controller-runtime docs. 

Also, If in the future or if you @grdryn think that something should be addressed in SDK than probably would be such as add a not in its docs to lt users check the controller-runtime/client docs as its examples.

Please, let us know if you think you do not agree with and if you think that it still needs to be addressed for we re-open this one.
