### ISSUE TITLE
Image use in blog post

### ISSUE THREAD

**Issue by WtfJoke** [operator-framework/operator-sdk#2059]
Hi there

Some unusual question here. I currently write a blogpost about kubernetes operator and would like to include this image  [operator-capability-level-transparent-bg.png](https://github.com/operator-framework/operator-sdk/blob/master/doc/images/operator-capability-level-transparent-bg.png).

Is it ok if I use this image? 

I will publish the article on [https://blog.codecentric.de](https://blog.codecentric.de/en/)

**Comment by hasbro17** [comment]
That should be fine with us.

I'll defer to @dmesser and/or @robszumski on whether that diagram needs any more updates though.

**Comment by robszumski** [comment]
@WtfJoke Feel free to use it, no issues there. Update this issue with a link to the post so we can check it out!

**Comment by robszumski** [comment]
@WtfJoke Forgot to add, can you use a caption that links it back to the original? The capabilities get updated every so often and it would be great for folks to have a way to discover the latest.

**Comment by camilamacedo86** [comment]
I think that would be good to make the reference regards the source as well 👍

**Comment by WtfJoke** [comment]
Hi everyone, thanks for your fast reply and allow me to use the image. 😃 

I will update the link to the post here. It is still in process. Expect nothing fancy, the target audience are beginners.  Post will be in german, maybe I will also publish it in english.

@camilamacedo86 I would have put a link under the image, something like "Source: [Operator-SDK Repository](https://github.com/operator-framework/operator-sdk/blob/master/doc/images/operator-capability-level.png)" It wasnt my intention to not link to the source.

**Comment by WtfJoke** [comment]
Hi there,
Wanted to let you know the german blog post just got published:
https://blog.codecentric.de/2019/10/dein-erster-kubernetes-operator/

If you like to have attribution changed, let me know. :) 
If I write an english version, will let you guys know here as well

**Comment by WtfJoke** [comment]
Hi there,

Its me again.  👋 
A german tech magazine https://t3n.de/ asked me to write an article about k8 operators. 
This time its less about writing an operator by itself and more what is an operator and how they work.  The article is supposed to get printed first and later on published on their website.

I would like to use the image in the article. If its fine for that use too? Just wanted to make sure. If have no problem if thats an issue for you, then I wont use it. 

I would give you credits by providing the source as in my blog post in format: 

Source:  [https://github.com/operator-framework/operator-sdk](https://github.com/operator-framework/operator-sdk/blob/master/doc/images/operator-capability-level.png)

Thanks a bunch! 🙏

**Comment by robszumski** [comment]
@WtfJoke No issues! We'd love to see the article when its published :)
