### ISSUE TITLE
Improve log messages on failure

### ISSUE THREAD

**Issue by jpkrohling** [operator-framework/operator-sdk#2061]
When a failure during the `generate openapi` happens, it would be helpful to have a message that reflects the problem. I'm migrating an operator from 0.10.0 to 0.11.0, and I'm faced with this:

```console
$ operator-sdk generate openapi 
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [opentelemetry:[v1alpha1], ] 
Error: error generating CRD for Group opentelemetry Version v1alpha1 Kind OpenTelemetryCollector
Usage:
  operator-sdk generate openapi [flags]

Flags:
  -h, --help   help for openapi

Global Flags:
      --verbose   Enable verbose logging
```

I then decided to turn on the verbose logging, to figure out what's exactly going wrong:

```console
$ operator-sdk generate openapi  --verbose
DEBU[0000] Debug logging is set                         
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [opentelemetry:[v1alpha1], ] 
Error: error generating CRD for Group opentelemetry Version v1alpha1 Kind OpenTelemetryCollector
Usage:
  operator-sdk generate openapi [flags]

Flags:
  -h, --help   help for openapi

Global Flags:
      --verbose   Enable verbose logging
```

Operator SDK version: 

```console
$ operator-sdk version
operator-sdk version: "v0.11.0", commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d", go version: "go1.12.7 linux/amd64"
```

**Comment by camilamacedo86** [comment]
Hi @jpkrohling, 

it shows duplicated of https://github.com/operator-framework/operator-sdk/issues/2042 because of this I am closing this one. However, please feel free to re-open if you fell that is required. My suggestion would be as described in this https://github.com/operator-framework/operator-sdk/issues/2042#issuecomment-541339927.

I hope that it helps you.

**Comment by jpkrohling** [comment]
Thanks @camilamacedo86 for the quick response and for pointing me to the right direction.
