### ISSUE TITLE
ASC files are broken since v0.10.1

### ISSUE THREAD

**Issue by ddompe** [operator-framework/operator-sdk#2062]
## Bug Report

**What did you do?**
Followed installation procedure

**What did you expect to see?**
PGP validation working

**What did you see instead? Under which circumstances?**
Errors as the .asc files published in releases are incorrect.

**Comment by hasbro17** [comment]
Ah whoops, turns out there was a bug in our release script for macos.
Thanks for spotting that @ddompe 

I've just updated the `*.asc` signatures in the [v0.11.0](https://github.com/operator-framework/operator-sdk/releases/tag/v0.11.0) release. Those should be verifiable now if you want to check again.

Going to update `v0.10.1` as well.

**Comment by hasbro17** [comment]
[v0.10.1](https://github.com/operator-framework/operator-sdk/releases/tag/v0.10.1) signatures should be fixed now as well.
Please reopen if they still don't verify correctly on your end.

**Comment by ddompe** [comment]
Thanks @hasbro17 : however now I'm getting:

```
Signature made Mon 14 Oct 2019 08:58:50 PM UTC
gpg:                using RSA key 254C316A384E10DDE421A5C3910921F178086003
$ gpg --recv-key  254C316A384E10DDE421A5C3910921F178086003
gpg: requesting key 78086003 from hkp server keys.gnupg.net
gpgkeys: key 254C316A384E10DDE421A5C3910921F178086003 not found on keyserver
```

Is the key published?

**Comment by hasbro17** [comment]
@ddompe It should be:
http://hkps.pool.sks-keyservers.net/pks/lookup?search=0x254C316A384E10DDE421A5C3910921F178086003&fingerprint=on&op=index

Can you try the keyserver `hkps.pool.sks-keyservers.net`:
```
$ gpg --keyserver hkps://hkps.pool.sks-keyservers.net --recv-keys 254C316A384E10DDE421A5C3910921F178086003
```
or the keyID if the fingerprint doesn't work:

```
$ gpg --keyserver hkps://hkps.pool.sks-keyservers.net --recv-keys 910921F178086003
```
