### ISSUE TITLE
Testing Ansible based operators with molecule should be easier to find

### ISSUE THREAD

**Issue by djzager** [operator-framework/operator-sdk#2072]
Currently, if you go to the [Ansible user guide](https://github.com/operator-framework/operator-sdk/blob/491cdf6d9f600514963f5f29ccff34a5bfe9ba4e/doc/ansible/user-guide.md) there is no mention:

- [Ansible testing guide](https://github.com/operator-framework/operator-sdk/blob/491cdf6d9f600514963f5f29ccff34a5bfe9ba4e/doc/ansible/dev/testing_guide.md)
- [Ansible developer guide](https://github.com/operator-framework/operator-sdk/blob/491cdf6d9f600514963f5f29ccff34a5bfe9ba4e/doc/ansible/dev/developer_guide.md) there is however, at the time of this writing, a link to the testing doc in the developer guide

Since the [Ansible user guide](https://github.com/operator-framework/operator-sdk/blob/491cdf6d9f600514963f5f29ccff34a5bfe9ba4e/doc/ansible/user-guide.md) is the landing page for new/prospect operator developers interested in using Ansible, the path from intro to development, to testing should be clear.

At a **minimum** I would think a collection of links to follow-up documentation users would be interested in (like the developer and testing guide) would be appropriate in the user guide.

**Comment by djzager** [comment]
**This is a doc issue**. Want to point that out since I'm not able to add labels.

**Comment by bradtopol** [comment]
working on this now.
/remove-lifecycle rotten

**Comment by camilamacedo86** [comment]
This problem will be solved with the website docs since it has a menu which makes easier users found the infos. So, I am closing this one. However, please feel free to re-open if you see that it still required.
