### ISSUE TITLE
[Discussion] Community meetings for Operator SDK Contributors

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#2077]
As the project shifts to upstream, we are looking for ways to increase transparency and community involvement. 

Would you be interested in attending a community meeting?
Do you have a preference for meeting format? (IRC, slack, video call, and so on)

**Comment by dmueller2001** [comment]
We have monthly Operator Framework SIG meetings, and if you have topics related to Operator-SDK, please add them to the OF-SIG agenda here: https://github.com/operator-framework/community/projects/2#column-6841650

**Comment by pchriste** [comment]
@dmueller2001 I think what we're talking about here is getting more developers involved in contributing to the upstream development of the SDK as well as roadmap and feature development decisions. @asmacdo I'd be interested in attending. maybe this is something we can address at the SIG as to the format and how to get more folks involved.

**Comment by jberkhahn** [comment]
I'm an open source developer that's looking to contribute to the operator framework, I'd definitely like something like this. I think a video conference call kind of thing would be good.

**Comment by pchriste** [comment]
a community meeting is being scheduled here: https://github.com/operator-framework/community/pull/4

**Comment by asmacdo** [comment]
We now have an Operator-SDK SIG meeting https://github.com/operator-framework/community/projects/3
