### ISSUE TITLE
When creating a CSV move spec.icon to the bottom

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/operator-sdk#2082]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When generating a CSV, put spec.icon at the bottom. This is just a readability thing.

**Describe the solution you'd like**
When I'm editing my generated CSV, one of the first things I do is move spec.icon to the bottom so I spend less time scrolling past the block of base64data that I really don't care to see. It is simple cut&paste for me. I imagine that's harder in code, but it'd make the experience a bit better.

**Comment by jberkhahn** [comment]
I'm not sure this is possible the way things currently are. We use a custom marshalling function [here](https://github.com/operator-framework/operator-sdk/blob/master/internal/scaffold/olm-catalog/csv.go#L144), which [passes the object through a json marshaller, and then into yaml.](https://github.com/ghodss/yaml/blob/master/yaml.go#L26) If it was just json, we could define a custom json marshaller to move things around, but [yaml marshalling doesn't seem to have any mechanism to define structure](https://pkg.go.dev/gopkg.in/yaml.v2?tab=doc#Marshaler), just content. So the only way I can see to move this around would be to perform manually manipulation of the resulting byte array, which seems hacky at best.

**Comment by camilamacedo86** [comment]
IHMO we should not address this one. Currently, the CSV is gen with the specs order by name which shows easily to find anyone specifically

WDYT @estroz @hasbro17 @jmrodri

**Comment by flickerfly** [comment]
If it isn't a quick thing, then it is just a minor inconvenience. The
effort is better placed elsewhere. Thanks for looking into it!

**Comment by camilamacedo86** [comment]
Hi @flickerfly, 

Just to clarifies, my comment was not about the effort to do it. In POV I think would be better keep is order by name as it is now instead of change the rules for any specific spec.  Is it make sense?
Note that now it will be scaffold by default as well. What do you think?

**Comment by flickerfly** [comment]
@camilamacedo86 I understand what you are saying and generally I'd agree with that, but with the way vim handles the base64 encoded icon it can be awkward to deal with because it makes scanning the code harder. If this is just a preference thing that no one else feels the pain of, that's fine. I could probably find a way to tell vim not to wrap those lines or fold it or something like that. Call it a task of the IDE.

**Comment by camilamacedo86** [comment]
In POV shows that we could close this one at least until we have more scenarios and/or users that would justify this change. I let it up to @estroz decide. WDYT?

**Comment by estroz** [comment]
Lets keep this open. As @flickerfly points out, the base64 icon is cumbersome when editing text, which we obviously want to enable.

I'd like to see a general solution, so if people request that other fields be sorted to the bottom (ex. descriptions) we can easily do so.

**Comment by jmrodri** [comment]
After looking into this more, I agree with @jberkhahn analysis, it is not an an easy fix, it would require re-writing a significant portion of the generator to support it. I'm going to close this for now.
