### ISSUE TITLE
Add e2e test to check scaffold project and metrics when it is cluster scope

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#2084]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The https://github.com/operator-framework/operator-sdk/pull/2078 should not pass as described in https://github.com/operator-framework/operator-sdk/pull/2078#pullrequestreview-304200840

**Describe the solution you'd like**
Add e2e test to check scaffold project and metrics when it is cluster scope

**Comment by joelanford** [comment]
@camilamacedo86 We don't support scaffolding projects that use cluster-scoped CRDs or watches, so I don't think we need an e2e test to handle that.

However, we may want to update the cluster-scope doc to discuss the need changes to the metrics setup code. WDYT?

**Comment by camilamacedo86** [comment]
I catcher your point over the tool options. I am not sure if has something in the docs that we could address regards it.  What do you have in mind? Otherwise, I am ok with we just close this one based on your argumentation.

**Comment by camilamacedo86** [comment]
I am closing this one as obsolete since we have the #2811 with all that still missing regards the metrics and many fixes and improvements were already done in the latest released versions. 

PS.: Also, by reading the description added by myself I am not sure if I am able to remember exactly what was in my mind when I tracked this one.
