### ISSUE TITLE
Configure Ansible Verbosity via Annotation

### ISSUE THREAD

**Issue by djzager** [operator-framework/operator-sdk#2091]
## Feature Request

#2087 makes it possible to configure Ansible verbosity via:

1. `ansible-verbosity` command line flag
1. environment variable in the operator container of the form `ANSIBLE_VERBOSITY_<kind>_<group>`

Also, the `maxRunnerArtifacts` (how many old executions of `ansible-runner` to keep around) is configurable via an annotation, for example `ansible.operator-sdk/max-runner-artifacts: "100"`.

**Describe the solution you'd like**

It should be possible to make the verbosity configurable via an annotation, for example `ansible.operator-sdk/verbosity: "6"`.

**Comment by joelanford** [comment]
@fabianvf this sounds pretty reasonable to me. thoughts?

@djzager assuming Fabian is in agreement, would you be interested and have the time to submit a PR for this?

**Comment by fabianvf** [comment]
Yeah this sounds great to me, would make the process of debugging so much easier. It might be necessary for us to include an admin level option to disable processing these annotations, just to prevent some sort of user-side attack if the admin wants to keep the logs/other stuff like runner artifacts locked down (ie, could balloon the number of artifacts by triggering runs, and I'm not sure how verbosity levels impact performance but writing everything to stdout likely isn't free).

**Comment by djzager** [comment]
> @djzager assuming Fabian is in agreement, would you be interested and have the time to submit a PR for this?

Yes.
