### ISSUE TITLE
How to upgrade controller-runtime in project generated by Operator-SDK

### ISSUE THREAD

**Issue by vincent-pli** [operator-framework/operator-sdk#2110]
## Feature Request

I have a project generated by `Operator-sdk v0.10.0`, I noticed the version of `controller-runtime` is `v0.1.12`. it's a very old version, some useful features is missing, such as:
- `webhook`
- `MultiNamespacedCach`

So I wonder to know, if we have a official document to guide user to upgrade these package?

**Comment by camilamacedo86** [comment]
Hi @vincent-pli, 

The latest version released of SDK, which is 0.11.0, is using the version `sigs.k8s.io/controller-runtime v0.2.2`. So, to upgrade controller-runtime you need to upgrade your project to use an upper version of SDK.  

See [version upgrade guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md#v011x) to help you achieve it. Also, may you would like to check [here](https://github.com/operator-framework/operator-sdk-samples/pull/82/files) the PR to upgrade the Memcached sample from 0.10 to 0.11 as well.

**Comment by vincent-pli** [comment]
@camilamacedo86 
Thanks, that's exactly what I need.
