### ISSUE TITLE
gen-csv working with 0.8.0 but failing with 0.11.0

### ISSUE THREAD

**Issue by alanconway** [operator-framework/operator-sdk#2115]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

gen-csv works with operator-sdk 0.8.0 but not 0.11.0. Reproduce by cloning `github.com/openshift-knative/knative-kafka-operator` at commit `c97a6cd` and following these steps:

```bash
[aconway@grommit knative-kafka-operator (master=)]$ ~/Downloads/operator-sdk-v0.8.0-x86_64-linux-gnu  olm-catalog gen-csv --update-crds --csv-version 0.9.0 --from-version 0.8.2
INFO[0000] Generating CSV manifest version 0.9.0        
INFO[0000] Created deploy/olm-catalog/knative-kafka-operator/0.9.0/knative-kafka-operator.v0.9.0.clusterserviceversion.yaml 
[aconway@grommit knative-kafka-operator (master=)]$ ~/Downloads/operator-sdk-v0.11.0-x86_64-linux-gnu  olm-catalog gen-csv --update-crds --csv-version 0.9.0 --from-version 0.8.2
INFO[0000] Generating CSV manifest version 0.9.0        
INFO[0000] Created deploy/olm-catalog/knative-kafka-operator/0.9.0/knative-kafka-operator.v0.9.0.clusterserviceversion.yaml 
Error: catalog scaffold failed: (failed to validate package manifest knative-kafka-operator: default channel cannot be empty)
```

**What did you expect to see?**
Both work.

**What did you see instead? Under which circumstances?**
0.8.0 worked, 0.11.0 failed.

**Environment**
* operator-sdk version:
0.8.0 and 0.11.0

* go version:
go version go1.12.10 linux/amd64

* Kubernetes version information:
NA

* Kubernetes cluster kind: 
NA

* Are you writing your operator in ansible, helm, or go?
Go

**Possible Solution**
I'm not sure if this is a regression in operator-sdk, or if there is some problem in our YAML files that is being detected by the newer version and not the older one.

**Additional context**

**Comment by estroz** [comment]
@alanconway thanks for bringing this to my attention. I was unaware that a default channel is not required if there is only one channel available. I'll push a fix which will be in v0.11.1.
