### ISSUE TITLE
pip command not found on ansible-operator:0.11.0 image

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/operator-sdk#2117]
## Bug Report

**What did you do?**
Tried to install requirements with pip in Dockerfile after upgrading to the ansible-operator:0.11.0 image.

```
RUN pip install kubernetes-validate
```

**What did you expect to see?**
Pip installing kubernetes-validate

**What did you see instead? Under which circumstances?**

`/bin/sh: pip: command not found`

**Environment**
* operator-sdk version: "v0.11.0", commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d", go version: "go1.12.7 linux/amd64"
* Ansible

**Possible Solution**
If I change my Dockerfile to use pip3 instead of pip, it works so maybe just wrap pip to run pip3 instead?

**Comment by camilamacedo86** [comment]
The python version was upgraded in the 0.11. You will be to use pip3 instead of. Note:

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

Also, you are able to check this change in the [CHANGELOG](https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md#breaking-changes)

Please, let us know if it solved your scenario.

**Comment by flickerfly** [comment]
I assumed that would mean pip would become a synonym of pip3. If that is
just a misunderstanding, that is fine.

Thanks

**Comment by camilamacedo86** [comment]
Hi @flickerfly, 

The python version was upgraded in the 0.11, then because of it, the image is using pip3. You can create an alias for the pip calls the same bin used by pip3 if you wish as well.

So, I understand that we can close this one and I am doing it. However, please feel free to re-open if you see that it is required.
