### ISSUE TITLE
Do you have a Kubernetes supported release matrix?

### ISSUE THREAD

**Issue by davidffrench** [operator-framework/operator-sdk#2118]
## Type of question
Documentation question/Release matrix

## Question
Do you have a release matrix for what versions of Kubernetes a specific version of the operator-sdk will work with?

**Context:**
The readme specifically lists kubectl v1.11.3+ so my assumption is that the latest operator-sdk version `v0.11.0` will work on Kubernetes `v1.11.3->v1.15.x`? I know the controller-runtime major version got bumped in the latest release, does this affect the compatibility at all?

**Environment**
* operator-sdk version:
`operator-sdk version: v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170`

* Kubernetes version information:
`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}`

**Comment by hasbro17** [comment]
@davidffrench Unfortunately we don't have a k8s version compatibility matrix yet.
We really do need to generate one. Or better yet, display that info as part of the `operator-sdk version` cmd.

For now though you can check the release notes or the go.mod for each release to see if we've bumped the controller-runtime and the corresponding k8s dependency version.
E.g:
- [v0.11.x is pinned to k8s 1.14.1](https://github.com/operator-framework/operator-sdk/blob/39c65c36159a9c249e5f3c178205cc6e86c16f8d/go.mod#L98)
- [v0.10.x is pinned to k8s 1.13.4](https://github.com/operator-framework/operator-sdk/blob/ff80b17737a6a0aade663e4827e8af3ab5a21170/go.mod#L113)

And I think we probably need to update our README pre-req. 
Our CI currently only tests against the corresponding k8s version. So while the v0.11.x release is tested against Kubernetes 1.14, it may work on k8s 1.11, but there's no guarantee since minor versions of kube might still have breaking changes.

**Comment by davidffrench** [comment]
Thank you very much for the response @hasbro17 .

The way I see this, it boils down to the resource versions in Kubernetes. So my assumption from a bare Kubernetes point of view, as long as I use a version of the resource that is available in Kubernetes 1.11.x and the latest version, it will work perfectly.

What I am unsure of is the dependencies included in the operator-sdk that we use in our operators. So it is a question if as an example, the controller-runtime v0.2.0 has breaking changes but as long as I change how this is used in my code, does it matter what version of Kubernetes is used? This I am unsure of and that is just one of the multiple dependencies.

**Comment by davidffrench** [comment]
@hasbro17 Looks like there is an issue with `v0.11.0` working with Kubernetes `v1.11.x`. The new CRDs generated have a field called `type` at the root of the status sub resource which is not allowed. I have been doing a bit of research into this. 

It looks like you are familiar with this based on this PR https://github.com/operator-framework/operator-sdk/pull/1961. Do you know if there is anything I can set to not include this field by default with the CRD generation? Something to flag the controller-tools to generate it in the old capacity?

**Comment by davidffrench** [comment]
@hasbro17 Pinging again to see if you have an answer to my question in the last comment.

I am also very happy to collaborate with you to discuss k8s and Go versions etc for each operator-sdk version and produce a PR for the compatibility matrix.

**Comment by hasbro17** [comment]
@davidffrench Unfortunately I don't think there is a way to revert controller-tools or the SDK(which just uses controller-tools) to generate CRDs without the `type: object` at the root of spec at `validation.openAPIV3Schema.properties.spec`.

The old behavior in controller-tools (https://github.com/kubernetes-sigs/controller-tools/pull/72) was just a workaround the bug on k8s 1.11 (https://github.com/kubernetes/kubernetes/issues/65293) that never got fixed/back-ported.
That had to fixed around the time 1.15/1.6 came about with [structural schemas](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema) which forces the CRD validation to have the `type: object` at the root.

So if you still have to run on k8s 1.11 then you'll have to work around this bug by either removing `validation.openAPIV3Schema.properties.spec.type` or disabling/removing the subresources.status block.
```
subresources:
    status: {}
```

**Comment by davidffrench** [comment]
Thank you for the response @hasbro17 . We still have an obligation for our operator to support OpenShift 3.11 which is based on Kubernetes 1.11. I imagine many other operators likely will need too also for the time being. 

It is unfortunate that controller-tools does not allow you to generate without a structural schema as it is only mandatory in `apiextensions.k8s.io/v1`, `v1beta1` can still be used up until k8s 1.19 and the generated CRDs from controller-tools `v2.2.2` are still using `apiextensions.k8s.io/v1beta1`. So, unfortunately, it looks like there is no way for the same generated CRD to work in both k8s 1.11 and  >1.11 from the latest version of the operator-sdk. However, the generated CRDs from `operator-sdk v0.10.0/controller-tools v0.1.12` will still work up until k8s 1.19.

I am not a big fan of manually changing the auto generated CRD but this will likely be needed in the future.

**Comment by ricardozanini** [comment]
Hi! I just came up with the same problem related to the generated CRDs to have this block:

```
subresources:
    status: {}
```

The only way to workaround this is to remove it manually every time? :disappointed: 

We have an automate process that generates the artefacts for us, having to hack into the generated CRD will be too troublesome.

**Comment by ron1** [comment]
Note OCP 3.11.188 now includes fix for issue https://bugzilla.redhat.com/show_bug.cgi?id=1803163 referenced here: https://github.com/operator-framework/operator-sdk/issues/2118#issuecomment-549598512.
