### ISSUE TITLE
Permission denied when generating

### ISSUE THREAD

**Issue by mjudeikis** [operator-framework/operator-sdk#213]
Failure on generation:
```
(27/37) Wrote github.com/googleapis/gnostic@v0.1.0
(28/37) Wrote github.com/golang/protobuf@v1.1.0
(29/37) Wrote gopkg.in/yaml.v2@v2.2.1
(30/37) Wrote github.com/gogo/protobuf@v1.0.0
(31/37) Wrote k8s.io/apimachinery@kubernetes-1.9.3
(32/37) Wrote golang.org/x/net@master
(33/37) Wrote k8s.io/api@kubernetes-1.9.3
(34/37) Wrote golang.org/x/sys@master
(35/37) Wrote golang.org/x/crypto@master
(36/37) Wrote k8s.io/client-go@kubernetes-1.9.3
(37/37) Wrote golang.org/x/text@v0.3.0
Run dep ensure done
Run code-generation for custom resources
Error: failed to perform code-generation for CustomResources: (Generating deepcopy funcs
F0501 09:47:48.272123       9 main.go:74] Error: Failed making a parser: unable to add directory "github.com/mjudeikis/example-operator/app-operator/pkg/apis/app/v1alpha1": unable to import "github.com/mjudeikis/example-operator/app-operator/pkg/apis/app/v1alpha1": open /go/src/github.com/mjudeikis/example-operator/app-operator/pkg/apis/app/v1alpha1: permission denied
goroutine 1 [running]:
k8s.io/code-generator/vendor/github.com/golang/glog.stacks(0xc420079200, 0xc4200e8000, 0x173, 0x1c8)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:766 +0xcf
k8s.io/code-generator/vendor/github.com/golang/glog.(*loggingT).output(0x855760, 0xc400000003, 0xc4200e6000, 0x831cbb, 0x7, 0x4a, 0x0)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:717 +0x322
k8s.io/code-generator/vendor/github.com/golang/glog.(*loggingT).printf(0x855760, 0x3, 0x6e1476, 0x9, 0xc4200ddf30, 0x1, 0x1)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:655 +0x14c
k8s.io/code-generator/vendor/github.com/golang/glog.Fatalf(0x6e1476, 0x9, 0xc4200ddf30, 0x1, 0x1)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
	/go/src/k8s.io/code-generator/cmd/deepcopy-gen/main.go:74 +0x221
)
```
My all `go env` is configured to use nonprivileged user.

This runs as root user in the container but not priviledged user:
```
DOCKER_REPO_ROOT="/go/src/{{.RepoPath}}"
IMAGE=${IMAGE:-"gcr.io/coreos-k8s-scale-testing/codegen:1.9.3"}

docker run --rm \
  -v "$PWD":"$DOCKER_REPO_ROOT" \
  -w "$DOCKER_REPO_ROOT" \
  "$IMAGE" \
  "/go/src/k8s.io/code-generator/generate-groups.sh"  \
  "deepcopy" \
  "{{.RepoPath}}/pkg/generated" \
  "{{.RepoPath}}/pkg/apis" \
  "{{.APIDirName}}:{{.Version}}" \
  --go-header-file "./tmp/codegen/boilerplate.go.txt" \
  $@
`
```
and my environment where all go code is located is:
```
[mjudeiki@redhat example-operator]$ ll ./app-operator/pkg/apis/app/v1alpha1/
total 12
-rw-r--r--. 1 mjudeiki mjudeiki  76 May  1 10:47 doc.go
-rw-r--r--. 1 mjudeiki mjudeiki 890 May  1 10:47 register.go
-rw-r--r--. 1 mjudeiki mjudeiki 619 May  1 10:47 types.go
[mjudeiki@redhat example-operator]$ 
```

Lack of access gives permission denied error for this subfolder when trying to access files.

Solution would be either to enhance `gcr.io/coreos-k8s-scale-testing/codegen:1.9.3` container to be able to run code generation as any user so we could add a flag to generate a script:
```
UID=`id -u $(whoami)`
...
--user $UID \ 
```

OR quick solution without changing the image is to make container run as priviledged:
```
docker run --rm \
  -v "$PWD":"$DOCKER_REPO_ROOT" \
  -w "$DOCKER_REPO_ROOT" \
  --privileged \
  "$IMAGE" \
  "/go/src/k8s.io/code-generator/generate-groups.sh"  \
  "deepcopy" \
  "{{.RepoPath}}/pkg/generated" \
  "{{.RepoPath}}/pkg/apis" \
  "{{.APIDirName}}:{{.Version}}" \
  --go-header-file "./tmp/codegen/boilerplate.go.txt" \
  $@
```

Which gives Success:
```
(33/37) Wrote k8s.io/api@kubernetes-1.9.3
(34/37) Wrote k8s.io/apimachinery@kubernetes-1.9.3
(35/37) Wrote k8s.io/client-go@kubernetes-1.9.3
(36/37) Wrote github.com/gogo/protobuf@v1.0.0
(37/37) Wrote golang.org/x/text@v0.3.0
Run dep ensure done
Run code-generation for custom resources

Generating deepcopy funcs
```

**Comment by mjudeikis** [comment]
for the flag fix: https://github.com/operator-framework/operator-sdk/pull/214

**Comment by hasbro17** [comment]
Hi @mjudeikis thanks for reporting the issue. 
Can you please expand a little bit more on:

> My all go env is configured to use nonprivileged user.
> This runs as root user in the container but not privileged user:

If I understand correctly when you run the following script in your app-operator project you get a permission denied because the root process in your container does not have enough priveleges:
```sh
#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

DOCKER_REPO_ROOT="/go/src/github.com/example-inc/app-operator"
IMAGE=${IMAGE:-"gcr.io/coreos-k8s-scale-testing/codegen:1.9.3"}

docker run --rm \
  -v "$PWD":"$DOCKER_REPO_ROOT" \
  -w "$DOCKER_REPO_ROOT" \
  "$IMAGE" \
  "/go/src/k8s.io/code-generator/generate-groups.sh"  \
  "deepcopy" \
  "github.com/example-inc/app-operator/pkg/generated" \
  "github.com/example-inc/app-operator/pkg/apis" \
  "app:v1alpha1" \
  --go-header-file "./tmp/codegen/boilerplate.go.txt" \
  $@
```

How exactly have you configured your containers to run without the default privileges?
https://github.com/moby/moby/blob/master/oci/defaults.go#L14-L30

> OR quick solution without changing the image is to make container run as priviledged

I don't think adding the `--privileged` flag is a good idea since that's not needed by default to run the [codegen](https://github.com/kubernetes/code-generator) container. Also that just seems to override your own default of running the container with no privileges.

> run code generation as any user

If you could run the codegen container as any user how would that give it privileges that the root user does not currently have in your setting?

**Comment by mjudeikis** [comment]
Hey @hasbro17 . I think this is a case where "root in the container is not root outside the container if you are not running privileged" container. Its a question of mapping UID's and GUID's, or having hight enough user (true root) to overwrite them.

So I get permission denied if I try to do simple file operations. My moby installation is the default, and I didn't change any permissions.
`[mjudeiki@redhat]$ id
uid=1004(mjudeiki) gid=1005(mjudeiki) groups=1005(mjudeiki),10(wheel),36(kvm),974(wireshark),986(libvirt),1003(docker) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
` 

 > If you could run the codegen container as any user how would that give it privileges that the root user does not currently have in your setting?

I would try play with `--add-user` flag on the runtime, when generating this container run command. But this is assumption at this point.  Or other way would be inject `code-gen` script to users gopath and run it from host level, and not container level.

**Comment by eparis** [comment]
For me I'm using Fedora 28 with docker-1.13.1-51.git4032bd5.fc28.x86_64
```
$ id
uid=4166(eparis) gid=4166(eparis) groups=4166(eparis),10(wheel),1029(seg),1030(docker), context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[eparis@localhost eparis]$ env | grep GOPATH
GOPATH=/home/eparis/go
```
I run:
```
cd /home/eparis/go/src/github.com/eparis
operator-sdk new cluster-operator-operator --api-version=clusteroperator.openshift.com/v1alpha1 --kind=App
 [output output output]
(38/39) Wrote k8s.io/client-go@kubernetes-1.9.3
(39/39) Wrote golang.org/x/text@v0.3.0
Run dep ensure done
Run code-generation for custom resources
Error: failed to perform code-generation for CustomResources: (Generating deepcopy funcs
F0503 19:44:57.427564      10 main.go:74] Error: Failed making a parser: unable to add directory "github.com/eparis/cluster-operator-operator/pkg/apis/clusteroperator/v1alpha1": unable to import "github.com/eparis/cluster-operator-operator/pkg/apis/clusteroperator/v1alpha1": open /go/src/github.com/eparis/cluster-operator-operator/pkg/apis/clusteroperator/v1alpha1: permission denied
goroutine 1 [running]:
k8s.io/code-generator/vendor/github.com/golang/glog.stacks(0xc420065100, 0xc4200d8000, 0x182, 0x1d7)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:766 +0xcf
k8s.io/code-generator/vendor/github.com/golang/glog.(*loggingT).output(0x855760, 0xc400000003, 0xc4200d6000, 0x831cbb, 0x7, 0x4a, 0x0)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:717 +0x322
k8s.io/code-generator/vendor/github.com/golang/glog.(*loggingT).printf(0x855760, 0x3, 0x6e1476, 0x9, 0xc4200cbf30, 0x1, 0x1)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:655 +0x14c
k8s.io/code-generator/vendor/github.com/golang/glog.Fatalf(0x6e1476, 0x9, 0xc4200cbf30, 0x1, 0x1)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
	/go/src/k8s.io/code-generator/cmd/deepcopy-gen/main.go:74 +0x221
)
```

Looks like we are both in the docker group and thus using our user to access docker, not root.

**Comment by eparis** [comment]
ohhhh, I was wrong what caused it. It was selinux, not uid.  `sudo setenforce 0` made it work.

I think this means we either need to run it with privileged or we need to run it with soemthing `--security-opt=type=spc_t`  (I'm not sure the right incantation. @rhatdan probably knows...

**Comment by eparis** [comment]
This is a stock default on both RHEL and Fedora.

**Comment by hasbro17** [comment]
@eparis Thanks for the fix. @mjudeikis Feel free to reopen the issue if #225 does not resolve the issue for you.

**Comment by rhatdan** [comment]
--security-opt label:disable is what I would prefer,  but the spc_t works also.

**Comment by eparis** [comment]
@rhatdan using `:Z` made it work. which i believe is better than using a different type.  No?

**Comment by spahl** [comment]
FWIW we are gonna get rid of the container for this step: https://github.com/operator-framework/operator-sdk/issues/226

**Comment by rhatdan** [comment]
@eparis Much better.
