### ISSUE TITLE
how to download the specific version of a dependency

### ISSUE THREAD

**Issue by viveksinghggits** [operator-framework/operator-sdk#2139]
## Question

**What did you do?**
I just created a project using `operator-sdk new <operator-name>`  It creates the project successfully with the dependencies that it requires.

**What did you expect to see?**
I wanted to have a specific version of the `controller-runtime` dependency let's say for example `v0.1.4`

**What did you see instead? Under which circumstances?**
The dependency version that was downloaded by default is `v2.0.0`, I tried to install the required version using `go get` and changing the `go.mod` file manually but it doesnt seem to work, I am still on version `v2.0.0`

**Environment**
* operator-sdk version: `operator-sdk version: "v0.11.0", commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d", go version: "go1.12.7 linux/amd64"`

 39c65c36159a9c249e5f3c178205cc6e86c16f8d

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

```

* Kubernetes cluster kind:  minikube

**Comment by camilamacedo86** [comment]
Hi @viveksinghggits,

The deps are defined in the go.mod file. However, if you do not use the specific version used/tested for each SDK release you will may face unexpected issues. So, it would not be recommend at all. 

See that the version of SDK 0.11.0 is using the version `sigs.k8s.io/controller-runtime v0.2.2` and the version 0.12 will use `sigs.k8s.io/controller-runtime v0.3.0`. So, if you would like to use and old version of the `sigs.k8s.io/controller-runtime then you would need still using an old version of SDK. 

Please, let us know the above information answers your question and if we can close this one.

**Comment by viveksinghggits** [comment]
Hi @camilamacedo86,
I totally understood, your response and thank you for that. I was just going through an example and that used the version `v0.1.4` but I understand that it depends on the sdk version. 
Thanks

**Comment by camilamacedo86** [comment]
If you are following the Getting Started, not that we have a PR to update it open. You can follow up it.
