### ISSUE TITLE
Handler should be state machine style

### ISSUE THREAD

**Issue by xiang90** [operator-framework/operator-sdk#215]
> The SDK should provide an API to Create, Update and Delete objects from inside the Handler. This will allow users to write the core operator logic in a more intuitive way by using a sequence of actions and queries.

One of the reason that I designed the handler to take events as input, and take actions as output is to make the handler strictly state machine style. It is easier for reasoning, intercepting, extending, and testing.

If we ever allow the users to write directly to Kubernetes API, the the handler will lose information and its design advantages. Yes, we can design a wrapper funcs to still preserve the semantics, but it will still make reasoning and testing more complicated.

The only advantage of not enforcing the write out is probably to make migration easier (as the example of the vault operator), but I do feel the disadvantages outweigh the advantages.

**Comment by spahl** [comment]
Fully agree with that. This is all still very early and was released as is to allow early comment and cooperation.

I also would like to get the SDK to a point that generates a state machine. It will not only guide the users in the right patterns but like you said above make testing much easier.

Over the coming weeks we will be doing more design and publish proposals that go in that direction.

**Comment by shawn-hurley** [comment]
@spahl @hasbro17 I believe that is this point this discussion should be closed or moved to the controller-runtime.

Unless we are thinking of writing a `Reconcile` wrapper to achieve this?

**Comment by lfrancke** [comment]
I know this is a very old issue and I don't want to debate it at all. I'm just wondering if anyone remembers the context/source for the quote from @xiang90 at the beginning:

> The SDK should provide an API to Create, Update and Delete objects from inside the Handler. This will allow users to write the core operator logic in a more intuitive way by using a sequence of actions and queries.

We're trying to understand best practices etc. around reconciliation loops and state machines and this issue always comes up.

Thank you
