### ISSUE TITLE
Official docker image for cli

### ISSUE THREAD

**Issue by drewwells** [operator-framework/operator-sdk#2152]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Provide a versioned docker container for using the operator-sdk CLI

**Describe the solution you'd like**
Same as above, docker container with the binary in it. Lots of people have created these https://hub.docker.com/search?q=operator-sdk&type=image

**Comment by bharathi-tenneti** [comment]
@drewwells  Can you present your usecase, for this Docker image request. Depending on the usecases, we will consider creating/maintaining officialdocker image for SDK.

**Comment by micahlee** [comment]
A use case I have for this to use the SDK CLI in a CI pipeline to build an operator image. We use docker on CI nodes to run build tools, rather than install the tools directly.

We use a third party image now, but would certainly prefer an officially maintained image.

**Comment by bharathi-tenneti** [comment]
@joelanford  is point of contact for this issue.

**Comment by davidkarlsen** [comment]
since `operator-sdk build` relies on docker it can become a bit tricky.

**Comment by camilamacedo86** [comment]
just to register +1 shows be looking for it in https://github.com/operator-framework/operator-sdk/issues/2978

**Comment by drewwells** [comment]
docker in docker has been around for a long time, it is not challenging to support https://www.docker.com/blog/docker-can-now-run-within-docker/

Even if the docker calls failed, it would be a major improvement to support specific versions of operator-sdk from docker cli. As mentioned above, we need to be able to build CICD pipelines on stable versions of applications. Having an operator-sdk docker image will be very useful to us.

Please reopen, this is still needed.

**Comment by camilamacedo86** [comment]
Re-opened add move to 1.2.0 since the 1.1.0 is released already 👍 
c/c @asmacdo

**Comment by joelanford** [comment]
This was completed in 1.1 and the operator-SDK image is now available at `quay.io/operator-framework/operator-sdk:v1.1.0`

**Comment by toamto94** [comment]
Does the image support in-cluster configuration?
I always get an error when I run `operator-sdk run bundle ...` from a container. It seems it cannot find the in-cluster configuration. `oc` on the other hand works fine.
