### ISSUE TITLE
failed to install release: release name exceeds max length of 53 error

### ISSUE THREAD

**Issue by linuxbsdfreak** [operator-framework/operator-sdk#2154]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

**What did you do?**
We are using the helm operator from operarator-sdk to provision systems using helm charts

**What did you expect to see?**
It is unable to install

**What did you see instead? Under which circumstances?**
```
    - lastTransitionTime: "2019-11-05T08:14:57Z"
      message: 'failed to install release: release name "3637ce1c-3789-4a36-a71e-2cc1f48f30ca-3jrqw365ksmcqiy7817ctzq3q"
        exceeds max length of 53'
      reason: InstallError
      status: "True"
      type: ReleaseFailed
````

**Environment**
* operator-sdk version: v0.8.1

  insert release or Git SHA here

* Kubernetes version information:

  insert output of `kubectl version` here
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:  Gardener

**Additional context**
Add any other context about the question here.

**Comment by camilamacedo86** [comment]
Hi @linuxbsdfreak, 

Thank you or raise it. See that you are using and very old version of  SDK. Also, note that this part wa changed in for the latest one versions. See [here](https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md#changed-2).

In this way, could you try to migrate/use the latest released version of SDK for your project 0.12 first and let us know if the same behaviour still faced on it?

**Comment by linuxbsdfreak** [comment]
Hi @camilamacedo86 @joelanford . I will test and get back to you with a newer version

**Comment by camilamacedo86** [comment]
Hi @linuxbsdfreak, 

Shows that it is sorted out, so I am closing this one. 
However, please feel free to re-open if you see that is required.

**Comment by linuxbsdfreak** [comment]
@camilamacedo86 . You can close it out. We have verified after upgrading and it works.
