### ISSUE TITLE
v0.12.0 upgrade guide

### ISSUE THREAD

**Issue by Slayv** [operator-framework/operator-sdk#2161]
## Type of question

About general context

## Question

Is there any v0.12.0 upgrade guide?

I didn't find any notes about in the relevant [documentation section](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md), but I see breaking changes in release notes, e.g. Go 1.13 is required.

**Comment by camilamacedo86** [comment]
Hi @Slayv,
Following the link for the upgrade version guide. 

https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md 

P.S  I'd like to keep this one for we add the link for the upgrade version guide in https://github.com/operator-framework/operator-sdk/releases.

**Comment by mhenke1** [comment]
@camilamacedo86 The upgrade version guide does not mention 0.12.x explicitly.
Might be worth to add some explicit lines explaining that no special tasks are needed 
after having done the migration to 0.11.x

**Comment by camilamacedo86** [comment]
Hi @mhenke1, 

It is true. I think it is missing the migration doc as well. Really tks I will be working on it. 
In the meantime, I'd recommend you ensure that you are using go 1.13 and replace your go.mod for https://github.com/operator-framework/operator-sdk/blob/master/internal/scaffold/go_mod.go#L40-L69.

**Comment by Slayv** [comment]
@camilamacedo86 thank you for your work
