### ISSUE TITLE
How to get cluster scoped resource?

### ISSUE THREAD

**Issue by paterczm** [operator-framework/operator-sdk#2166]
Hello

I want to create an operator which can manage namespaces and I'm stuck getting namespace by name. I'm trying to use [Client's Get api](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/client.md#get), but it looks designed for namespace scoped resources only (expects `types.NamespacedName` as the second parameter). Please advise.

Thank you

Marek

**Comment by camilamacedo86** [comment]
Hi @paterczm, 

The following doc has all info required as the steps for you change your operator project to be cluster scoped.

https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md

Closing this one, however, feel free o re-open if you think that it still required.

**Comment by paterczm** [comment]
Hello @camilamacedo86 
The doc you linked talks about cluster level RBAC and cluster CRD scope, but it does not explain how to use the Client to get cluster scoped resources.

**Comment by camilamacedo86** [comment]
Hi @paterczm, 

So, your operator project would first all need cluster-scope permissions to check all resources in the cluster. Then, for you change the scope of the operator cluster and allow it has access to all cluster follow up the steps [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md). In this doc you will find how to change the scaffold/init project which by default is namespaced scope to cluster scope. 

To know more about RBCA and permissions to config your role.yaml file see https://kubernetes.io/docs/reference/access-authn-authz/rbac/.

See [here](https://kubernetes.io/docs/tasks/administer-cluster/namespaces/#creating-a-new-namespace) an example over how to create a Namespace resource/object to apply in the cluster. Are you able to create the Namespaces already or you just would like to GET them? 

Did you tried something as follows? Is your project cluster-scoped already? 

```go
	ns := &corev1.Namespace{}
	err = r.client.Get(context.TODO(), types.NamespacedName{Name: memcached.Name}, ns)
```
If after the above information you still facing issues, could you please provide the error faced? Also, let us know if you could sorte out it.

**Comment by paterczm** [comment]
Ah yes, that's what I was looking for, thank you!

Passing `types.NamespacedName{Name: memcached.Name}` or `types.NamespacedName{Name: memcached.Name, Namespace: ""}` to the Get api looks up cluster scoped resources. I was expecting something like `type.CluserescopedName`.

**Comment by camilamacedo86** [comment]
Hi @paterczm, 

The project/operator can be namespaced-scope or cluster-scoped which means have access to all or just 1 specific namespace. If you would like to manage a resource which will be across the cluster then you need to have your project set up for it first. I mean be using ClusterRoles and etc .  Are you project cluster-scope already? 

Then, when you do `types.NamespacedName{Name: memcached.Name}` you are passing the name of the resource that you would like to GET. For example, in the following code, it will get all pods with the labels. If the project is cluster scoped then it will be looking for pods in more than one namespace if not it will look just in a specific namespace. 

```go
	podList := &corev1.PodList{}
	listOpts := []client.ListOption{
		client.MatchingLabels(labelsForMemcached(memcached.Name)),
	}
	err = r.client.List(context.TODO(), podList, listOpts...)
	if err != nil {
		reqLogger.Error(err, "Failed to list pods.", "Memcached.Namespace", memcached.Namespace, "Memcached.Name", memcached.Name)
		return reconcile.Result{}, err
	}
```

If the above info did not help you please let me know and then, could you please provided how you are doing it and what issue are you facing?

**Comment by paterczm** [comment]
Hello @camilamacedo86 

My problem is resolved now, your previous post helped me. I thought that my answer made it clear. I never had a problem with RBAC setup (got that part right at least), just didn't understand Get api usage.

Thanks again
Marek

**Comment by camilamacedo86** [comment]
So, all sort out !! You get how to set up the cluster-scope and how works RBAC and the GET. :-)
Really tks for let me know. I am closing this one.
