### ISSUE TITLE
Switch Ansible test scaffold from k8s_facts to k8s_info module

### ISSUE THREAD

**Issue by geerlingguy** [operator-framework/operator-sdk#2168]
## Feature Request

**Is your feature request related to a problem? Please describe.**

When using the molecule test scaffold shipped with operator-sdk's Ansible option, playbook runs on Ansible 2.9 show a deprecation warning like the following:

```
    TASK [Wait 60s for reconciliation to run] ***************************************
[DEPRECATION WARNING]: The 'k8s_facts' module has been renamed to 'k8s_info'. 
This feature will be removed in version 2.13. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
    ok: [localhost]

```

**Describe the solution you'd like**

This is pretty easy to fix; we just need to change from using `k8s_facts` to `k8s_info`. I verified with a default test setup that this works identically and drops the deprecation warnings.

**Comment by camilamacedo86** [comment]
HI @geerlingguy, 

Thank you for raise it. Also, please feel free to collab with the PR if you wish.

**Comment by geerlingguy** [comment]
Added PR (see above).
