### ISSUE TITLE
Should display the (user) qualifier fields when generating the CSV so that the users can clearly know it

### ISSUE THREAD

**Issue by jianzhangbjz** [operator-framework/operator-sdk#2172]
## Bug Report

**What did you do?**
Use the `operator-sdk olm-catalog gen-csv` to generate the CSV files. 
```console
mac:learn-operator jianzhang$ operator-sdk olm-catalog gen-csv --operator-name learn-operator --csv-version 0.0.1 --csv-channel alpha 
INFO[0000] Generating CSV manifest version 0.0.1        
INFO[0000] Fill in the following required fields in file deploy/olm-catalog/learn-operator/0.0.1/learn-operator.v0.0.1.clusterserviceversion.yaml:
	spec.keywords
	spec.maintainers
	spec.provider 
INFO[0000] Created deploy/olm-catalog/learn-operator/0.0.1/learn-operator.v0.0.1.clusterserviceversion.yaml 
INFO[0000] Created deploy/olm-catalog/learn-operator/learn-operator.package.yaml 
```
But, got errors since lack some basic fileds:
```console
mac:learn-operator jianzhang$ oc create -f deploy/olm-catalog/learn-operator/0.0.1/learn-operator.v0.0.1.clusterserviceversion.yaml 
The ClusterServiceVersion "learn-operator.v0.0.1" is invalid: 
* spec.customresourcedefinitions.owned.displayName: Required value
* spec.customresourcedefinitions.owned.description: Required value
```

**What did you expect to see?**
Should display the [(user) qualifier fields](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/olm-catalog/generating-a-csv.md#csv-fields) when generating the CSV so that the users can clearly know it.

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:
```console
mac:learn-operator jianzhang$ operator-sdk version
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.4 darwin/amd64"
```

* go version:
```go
mac:learn-operator jianzhang$ go version
go version go1.13.1 darwin/amd64
```

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**

Add the `description: An example to show how to make it managed by OLM` and `displayName: Jian's Learn Operator` fields manually, and then, it works. See below:
```console
mac:learn-operator jianzhang$ vim deploy/olm-catalog/learn-operator/0.0.1/learn-operator.v0.0.1.clusterserviceversion.yaml
...
  customresourcedefinitions:
    owned:
    - kind: Learn
      name: learns.app.learn.com
      version: v1
      description: An example to show how to make it managed by OLM
      displayName: Jian's Learn Operator
  description: Placeholder description
  displayName: Learn Operator
...
...
mac:learn-operator jianzhang$ oc create -f  deploy/olm-catalog/learn-operator/0.0.1/learn-operator.v0.0.1.clusterserviceversion.yaml 
clusterserviceversion.operators.coreos.com/learn-operator.v0.0.1 created
```

**Additional context**

**Comment by camilamacedo86** [comment]
Hi @jianzhangbjz, 

It is not really a bug. See the info in  the [Getting Started](https://github.com/operator-framework/getting-started#generate-an-operator-manifest):

> Several fields must be updated after generating the CSV. See the CSV [generation doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/olm-catalog/generating-a-csv.md#csv-fields) for a list of required fields, and the memcached-operator CSV for an example of a complete CSV. 

Also, the RFE for the command generates these values populated is tracked in  #1132 and it has been done in the PR https://github.com/operator-framework/operator-sdk/pull/1162. Also, if you are using the master branch may you can use this PR to help you so far to do it.

In this way, I am closing this one. However, please feel free to re-open if you feel that still required.

**Comment by jianzhangbjz** [comment]
@camilamacedo86 Thanks for your details! Yes, I can see they are marked with a (user) qualifier.
But, this doc lack the `displayName` field. Maybe it needs some updates. For my personal opinion, it's better to display these (user) qualifier fields when generation the CSV file. What do you think?
> spec.customresourcedefinitions: any CRDs the Operator uses. Certain fields in elements of owned will be filled by the SDK.
owned: all CRDs the Operator deploys itself from it's bundle.
name: CRD's metadata.name.
kind: CRD's metadata.spec.names.kind.
version: CRD's metadata.spec.version.
description (user) : description of the CRD.
resources (user) : any Kubernetes resources used by the CRD, ex. Pod's and ConfigMap's.
specDescriptors (user) : UI hints for inputs and outputs of the Operator's spec.
statusDescriptors (user) : UI hints for inputs and outputs of the Operator's status.
required (user) : all CRDs the Operator expects to be present in-cluster, if any. All required element fields must be populated manually.

I reopen this issue and change the title to show the updated requirements.

**Comment by camilamacedo86** [comment]
HI @jianzhangbjz,

Your last point regards the displayName is answered already in another issue.  See https://github.com/operator-framework/operator-sdk/issues/2071#issuecomment-549474792

Closing this one as a duplicatation of.
