### ISSUE TITLE
Removed export GO111MODULE=on from all places since it shows no longer required in 1.13

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#2182]
## Feature Request

Removed export GO111MODULE=on from all places since it shows no longer required in 1.13

**Comment by joelanford** [comment]
@camilamacedo86 this was already completed in https://github.com/operator-framework/operator-sdk/pull/2135

**Comment by camilamacedo86** [comment]
But it shows that still needed @joelanford : https://github.com/operator-framework/operator-sdk/search?q=GO111MODULE&unscoped_q=GO111MODULE

Or, is correct the SDK output the following error when it is off? 

$ operator-sdk generate k8s
FATA[0000] using go modules requires GO111MODULE="on", "auto", or unset. More info: https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#go-modules

**Comment by joelanford** [comment]
Correct. If you look closely, you'll see that those usages are there to ensure that a user's GO111MODULE environment variable is setup correctly.

GO111MODULE _is_ required to be setup correctly. However in Go 1.13, the default behavior when it is unset or `auto` has changed. See https://github.com/golang/go/issues/31857 for details.

**Comment by camilamacedo86** [comment]
Closing it. You are right if we do not set it, that's the same as auto.
Has no need for this task all done.
