### ISSUE TITLE
host operator sdk cli binary for Power (ppc64le)

### ISSUE THREAD

**Issue by clnperez** [operator-framework/operator-sdk#2184]
## Feature Request

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
hosting a ppc64le binary

This PR got the helm image built for ppc64le: https://github.com/operator-framework/operator-sdk/pull/1533. Would it be possible to host that cli binary?

Happy to submit a PR if needed.

**Comment by jmccormick2001** [comment]
https://github.com/operator-framework/operator-sdk/releases/download/v0.12.0/operator-sdk-v0.12.0-ppc64le-linux-gnu

is that it? or am I misunderstanding?

**Comment by clnperez** [comment]
hah, nope! someone was looking for it and I just assumed they'd done their due diligence. I should have done mine. thanks @jmccormick2001!
