### ISSUE TITLE
Add golangci-lint Make target and call in the CI

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#2196]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Improve/ensure the quality of the code and its maintenance ability. 

**Describe the solution you'd like**
Add linter to the project. Following what is expected to get done:

- Add Makefile target to call linter
- Add linter in the CI ( but it should not make the CI fails for now )
- The linter that should be added is [golangci-lint](https://github.com/golangci/golangci-lint)
- See how the [Controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) has been installing it [here](https://github.com/kubernetes-sigs/controller-runtime/blob/15b5243f9fde6794ee298dfa9d21d7072bec3a3f/hack/check-everything.sh#L69-L75)
- See how the [Controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) has been using it [here](https://github.com/kubernetes-sigs/controller-runtime/blob/15b5243f9fde6794ee298dfa9d21d7072bec3a3f/hack/verify.sh#L27-L45)

**Comment by jmrodri** [comment]
We don't want to do the foreach because it won't return a non zero exit code and near impossible to fail the build. I had to fix that in our broker Makefile. https://github.com/openshift/ansible-service-broker/commit/cc9798c432dca0177d4ed2c398eeb1aea6e1e3e6

**Comment by camilamacedo86** [comment]
Hi @jmrodri I think the comment is in the wrong issue? Am I right?
