### ISSUE TITLE
Add application-specific callback to make SDK.Informer more extensible

### ISSUE THREAD

**Issue by orainxiong** [operator-framework/operator-sdk#221]
I have encoded my application-specific logic into **Kubernetes** through **Operator Pattern** over about six months.

It helps me a lot to lower the application development barrier on Kubernetes. Therefore, I can focus on application logic itself. Honestly, It is very meaningful for me. 

If allowed to add filtering callback atop exiting informer, it might be more extensible.

Here are my detailed implementations(I hope it helps):

- A new interface and struct will be added
```
type ResourceEventHandlerCallback interface {
	OnAdd(obj interface{}) error
	OnUpdate(oldObj, newObj interface{}) error
	OnDelete(obj interface{}) error
}

type ResourceEventHandlerCallbackFuncs struct {
	AddCallback    func(obj interface{}) error
	UpdateCallback func(oldObj, newObj interface{}) error
	DeleteCallback func(obj interface{}) error
}

func (r ResourceEventHandlerCallbackFuncs) OnAdd(obj interface{}) error {
	if r.AddCallback != nil {
		if err := r.AddCallback(obj); err != nil {
			return err
		}
	}
	return nil
}

func (r ResourceEventHandlerCallbackFuncs) OnUpdate(oldObj, newObj interface{}) error {
	if r.UpdateCallback != nil {
		if err := r.UpdateCallback(oldObj, newObj); err != nil {
			return err
		}
	}
	return nil
}

func (r ResourceEventHandlerCallbackFuncs) OnDelete(obj interface{}) error {
	if r.DeleteCallback != nil {
		if err := r.DeleteCallback(obj); err != nil {
			return err
		}
	}
	return nil
}
```

- SDK.Informer will be extended with a new field and a new function
```
type informer struct {
...
	resourceEventHandlerCallback ResourceEventHandlerCallback
...
}

func (i *informer) AddEventHandlerCallback(callback ResourceEventHandlerCallback) {
	i.resourceEventHandlerCallback = callback

}
```

- Modify existing handler :

```
func (i *informer) handleUpdateResourceEvent(oldObj, newObj interface{}) {
	key, err := cache.MetaNamespaceKeyFunc(newObj)
	if err != nil {
		panic(err)
	}
	if err := i.resourceEventHandlerCallback.OnUpdate(oldObj, newObj); err != nil {
		glog.V(4).Infof("resource %s skip enqueue %+v", key, err)
		return
	}
	i.queue.Add(key)
}
```

**Demo**

- New an informer as usual

```
informer := sdkInformer.New(resourcePluralName, namespace, resourceClient, resyncPeriod)
```

- Add callback with application-specific logic
```
	informerAddEventHandlerCallback(
		queue.ResourceEventHandlerCallbackFuncs{
			UpdateCallback: dc.updateClusterCallback,
		},
	)
```

**Comment by fanminshi** [comment]
`If allowed to add filtering callback atop exiting informer, it might be more extensible.`

Is there a reason to make the underlying informer more extensible? Isn't the current combination of `sdk.Watch` and `handler` sufficient for most use case? 

Also the purpose of operator-sdk API is to abstract away the lower lvl Kubernete APIs such as informer; so that the developer doesn't have to learn about how it works.

**Comment by xiang90** [comment]
@orainxiong 

We can add an option to watch - withOldObject. In the returned event, we can return the old object when withOldObject is enabled.

**Comment by orainxiong** [comment]
@xiang90 
As you said, it is a preferable way to meet requirements as well as following operator framework convention.
Thx your reply.
I will close this issue,

**Comment by xiang90** [comment]
@orainxiong No problem. It would be great if you can contribute this feature.

**Comment by orainxiong** [comment]
@xiang90 OK. I will try.
I will create a new PR to implement this feature.
