### ISSUE TITLE
operator-sdk scorecard exit status not honored

### ISSUE THREAD

**Issue by jdockter** [operator-framework/operator-sdk#2235]
## Bug Report

Per the operator-sdk scorecard documentation 
https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/scorecard.md#exit-status
```
In version v1alpha2, the scorecard return code is 1 if any of the tests executed did not pass and 0 if all selected tests pass. Version v1alpha1 returns exit code of 0 regardless if tests fail.
the exit status is not honored
```

**What did you do?**
Ran the following commands on operator built with operator-sdk, specifically passing in namespace value that is not present so test would fail, expecting to see return code of 1 but got 0.

Scenario 1
```
jpd@JPD-WIN10:~/go/src/github.ibm.com/jdockter/pingpong-repo/stable/pingpong-case-bundle/operators/pingpong-operator$ operator-sdk version
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.3 linux/amd64"
jpd@JPD-WIN10:~/go/src/github.ibm.com/jdockter/pingpong-repo/stable/pingpong-case-bundle/operators/pingpong-operator$ go vesion
go vesion: unknown command
Run 'go help' for usage.
jpd@JPD-WIN10:~/go/src/github.ibm.com/jdockter/pingpong-repo/stable/pingpong-case-bundle/operators/pingpong-operator$ go version
go version go1.13.4 linux/amd64
jpd@JPD-WIN10:~/go/src/github.ibm.com/jdockter/pingpong-repo/stable/pingpong-case-bundle/operators/pingpong-operator$ operator-sdk scorecard namespace test1 --verbose --version v1alpha2 -o text
DEBU[0000] Debug logging is set                         
INFO[0000] Using config file: /home/jpd/go/src/github.ibm.com/jdockter/pingpong-repo/stable/pingpong-case-bundle/operators/pingpong-operator/.osdk-scorecard.yaml 
ERRO[0073] Plugin `Basic Tests` failed with error (failed to create namespaced resources: failed to get proxyPod: timed out waiting for the condition) 
ERRO[0085] Plugin `OLM Integration` failed with error (failed to create namespaced resources: scorecard currently does not support multiple deployments in the manifests) 

jpd@JPD-WIN10:~/go/src/github.ibm.com/jdockter/pingpong-repo/stable/pingpong-case-bundle/operators/pingpong-operator$ echo $?
0
```

Scenario 2 - test again with namespace that exists and some tests pass and some tests fail, still showing successful scorecode exit code
```
jpd@JPD-WIN10:~/go/src/github.ibm.com/jdockter/pingpong-repo/stable/pingpong-case-bundle/operators/pingpong-operator$ operator-sdk scorecard namespace test1 --verbose --version v1alpha2 -o textDEBU[0000] Debug logging is set                         
INFO[0000] Using config file: /home/jpd/go/src/github.ibm.com/jdockter/pingpong-repo/stable/pingpong-case-bundle/operators/pingpong-operator/.osdk-scorecard.yaml 
basic:
        Status Block Exists                : pass
        Writing into CRs has an effect     : pass
        Spec Block Exists                  : pass
olm:
        CRs have at least 1 example        : pass
        Spec fields with descriptors       : fail
        Status fields with descriptors     : fail
        Provided APIs have validation      : fail
        Owned CRDs have resources listed   : fail
SUGGESTION: Add a spec descriptor for size
SUGGESTION: Add a status descriptor for conditions
SUGGESTION: Add CRD validation for status field `conditions` in Pingpong/v1alpha1
SUGGESTION: If it would be helpful to an end-user to understand or troubleshoot your CR, consider adding resources [configmaps/v1 pingpongs/v1alpha1 replicasets/v1 deployments/v1 services/v1 pods/v1] to the resources section for owned CRD Pingpong

jpd@JPD-WIN10:~/go/src/github.ibm.com/jdockter/pingpong-repo/stable/pingpong-case-bundle/operators/pingpong-operator$ echo $?
0
```

**What did you expect to see?**
Since there was a failure I expected to see a return code of 1

**What did you see instead? Under which circumstances?**
return code 0 even on failure 

**Environment**
* operator-sdk version: 
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.3 linux/amd64"

* go version:
go version go1.13.4 linux/amd64

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+2e5ed54", GitCommit:"2e5ed54", GitTreeState:"clean", BuildDate:"2019-10-10T22:04:13Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?
Ansible 

**Possible Solution**

**Additional context**

**Comment by camilamacedo86** [comment]
c/c @jmccormick2001

**Comment by joelanford** [comment]
@jdockter This feature and the associated docs were merged into `master` more recently than the `v0.12.0` release. To try out the documented exit code functionality, you can build `operator-sdk` from source on the `master` branch.

**Comment by jdockter** [comment]
@joelanford any idea when the next official release is going to be cut that would have this change in it?

**Comment by jdockter** [comment]
@joelanford using v.0.13.0 and still seeing errors when plugin error, ie failed to read csv, see below

$ operator-sdk version
operator-sdk version: "v0.13.0", commit: "1af9c95bb51420c55a7f7f2b7fabebda24451276", go version: "go1.13.3 linux/amd64"

$ operator-sdk scorecard --verbose namespace test1
DEBU[0000] Debug logging is set                         
INFO[0000] Using config file: /home/jpd/go/src/github.ibm.com/jdockter/pingpong-repo/stable/pingpong-case-bundle/operators/pingpong-operator/.osdk-scorecard.yaml 
ERRO[0015] Plugin `OLM Integration` failed with error (failed to read csv: open deploy/olm-catalog/pingpong-operator/0.1.0/pingpong-operator.v0.1.0.clusterserviceversion.yaml: no such file or directory) 

$ echo $?
0

on error of any kind expecting return code 1
