### ISSUE TITLE
ansible operator failed when json_query filter is used

### ISSUE THREAD

**Issue by LuciferInLove** [operator-framework/operator-sdk#2237]
## Bug Report

**What did you do?**
I have ansible operator generated with:
```
operator-sdk new ansible-operator --type ansible --kind TestConfig --api-version test.test/v1alpha1 --generate-playbook
```

I've created the role with json_query filter in some steps. When I run ansible-operator I've got the error.

**What did you expect to see?**
Steps with json_query filter must be succeeded.

**What did you see instead? Under which circumstances?**
I see the error in operator logs:
```
fatal: [localhost]: FAILED! => {"msg": "You need to install \"jmespath\" prior to running json_query filter"}
```

**Environment**
* operator-sdk version:

operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469"

* go version:

go version: "go1.13.3 linux/amd64"

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

ansible

**Possible Solution**
pip jmespath module must be installed in default ansible operator container

**Additional context**

**Comment by camilamacedo86** [comment]
Hi @LuciferInLove,

Are you using the SDK 0.12 for a new project generated with or a project that you upgraded to use it?

**Comment by camilamacedo86** [comment]
It is using python 3 and pip3. See: https://github.com/operator-framework/operator-sdk-samples/blob/master/ansible/memcached-operator/.travis.yml#L5

Are you with python 3 and pip3 installed in your env?

**Comment by LuciferInLove** [comment]
Yes to both questions, but I'll check it out in detail

**Comment by LuciferInLove** [comment]
When I run
```
operator-sdk build my_image
```
I see only building of docker container image.

Dockerfile generated by operator-sdk looks like:
```
FROM quay.io/operator-framework/ansible-operator:v0.12.0

COPY watches.yaml ${HOME}/watches.yaml

COPY roles/ ${HOME}/roles/
COPY playbook.yml ${HOME}/playbook.yml
```

**Comment by LuciferInLove** [comment]
All are working when I add jmethpath installing in Dockerfile manually

**Comment by camilamacedo86** [comment]
HI @LuciferInLove, 

Could you please clarfies the steps performed in `All are working when I add jmethpath installing in Dockerfile manually`? What do you mean with?  Could you please describe the steps?

**Comment by LuciferInLove** [comment]
Hi. When I run
```
operator-sdk new ansible-operator --type ansible --kind TestConfig --api-version test.test/v1alpha1 --generate-playbook
```
I see such files tree:
```
.
├── build
│   ├── Dockerfile
│   └── test-framework
│       ├── ansible-test.sh
│       └── Dockerfile
├── deploy
│   ├── crds
│   │   ├── test.test_testconfigs_crd.yaml
│   │   └── test.test_v1alpha1_testconfig_cr.yaml
│   ├── operator.yaml
│   ├── role_binding.yaml
│   ├── role.yaml
│   └── service_account.yaml
├── molecule
│   ├── default
│   │   ├── asserts.yml
│   │   ├── molecule.yml
│   │   ├── playbook.yml
│   │   └── prepare.yml
│   ├── test-cluster
│   │   ├── molecule.yml
│   │   └── playbook.yml
│   └── test-local
│       ├── molecule.yml
│       ├── playbook.yml
│       └── prepare.yml
├── playbook.yml
├── roles
│   └── testconfig
│       ├── defaults
│       │   └── main.yml
│       ├── files
│       ├── handlers
│       │   └── main.yml
│       ├── meta
│       │   └── main.yml
│       ├── README.md
│       ├── tasks
│       │   └── main.yml
│       ├── templates
│       └── vars
│           └── main.yml
└── watches.yaml
```
Then I edit build/Dockerfile:
```
FROM quay.io/operator-framework/ansible-operator:v0.12.0

USER 0                              <---------- String that I'm adding
RUN pip3 install jmespath <---------- String that I'm adding
USER 1001                       <---------- String that I'm adding

COPY watches.yaml ${HOME}/watches.yaml

COPY roles/ ${HOME}/roles/
COPY playbook.yml ${HOME}/playbook.yml
```
Then I run `operator-sdk build my_image` and deploy this operator image in kubernetes.
All are working great in this case.

**Comment by camilamacedo86** [comment]
Really thank you for your info. It shows an issue.  I am looking on that.

**Comment by LuciferInLove** [comment]
@camilamacedo86 , thank you too)

**Comment by camilamacedo86** [comment]
Just to register I could reproduce this one by using the Memcached sample. Following the error:

```

TASK [Memcached : extract instance tags] ***************************************
task path: /opt/ansible/roles/Memcached/tasks/main.yml:36
fatal: [localhost]: FAILED! => {
    "msg": "You need to install \"jmespath\" prior to running json_query filter"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```
