### ISSUE TITLE
osdk-scorecard yaml migration

### ISSUE THREAD

**Issue by jdockter** [operator-framework/operator-sdk#2239]
## Type of question
using osdk-scorecard.yaml with operator-sdk scorecard

## Question
Is there a full mapping between passing flags and leveraging osdk-scorecard.yaml
https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#scorecard
vs
https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/scorecard.md#config-file

**What did you do?**
Tired to migrate from using flags on the command line to using osdk-scorecard.yaml to run operator-sdk scorecard.

**What did you expect to see?**
I wanted to toggle between basic and olm tests by providing a parameter or override flag, per document https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#scorecard

**What did you see instead? Under which circumstances?**
Always got both set of tests to run, ie basic and olm.  Only way to toggle was to comment out one or the other in the osdk-scorecard.yaml.  Is this do longer possible?

**Environment**
* operator-sdk version: 
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.3 linux/amd64"

* go version:
go version go1.13.4 linux/amd64

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+2e5ed54", GitCommit:"2e5ed54", GitTreeState:"clean", BuildDate:"2019-10-10T22:04:13Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by joelanford** [comment]
@jdockter If you're using `v1alpha2` of scorecard, you should be able to use the `--selector` flag to pass a kubernetes-style label selector to choose which tests to run (e.g. `--selector="suite=basic"`)

**Comment by camilamacedo86** [comment]
Is @jdockter the above answer what you are looking for? If not, could you please let us know what we can do to help you with?

**Comment by jdockter** [comment]
@camilamacedo86 @joelanford thanks that worked both for --selector="suite=basic" and --selector="suite=olm".  Two follow-on questions...
1) when the `olm-deployed` option is leveraged what is the scorecard actually installing to the cluster?  
2) can `olm-deployed` option be passed as a flag on the command line or do I have to toggle that on or off in the osdk-scorecard.yaml?

**Comment by camilamacedo86** [comment]
Hi @jdockter, 

Let's see if I can help you. 

> 1.when the olm-deployed option is leveraged what is the scorecard actually installing to the cluster?

> The scorecard assumes your CSV and relevant CRD's have been deployed onto the cluster using OLM when using olm-deployed.

Ref.: https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/scorecard.md#running-the-scorecard-with-an-olm-managed-operator

> can olm-deployed option be passed as a flag on the command line or do I have to toggle that on or off in the osdk-scorecard.yaml?

Usually, you will use as a flag in the command. However, note that for the plugins config in the yaml file you may would like to use the bool attribute `olm-deployed`.

<img width="953" alt="Screenshot 2019-11-21 at 00 00 44" src="https://user-images.githubusercontent.com/7708031/69288744-5a1c0b80-0bf2-11ea-8c6d-1632b5aeeb5e.png">

Ref.: https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/scorecard.md#basic-and-olm

**Comment by jdockter** [comment]
@camilamacedo86 yes I have read those documents before but it wasn't clear to me what the scorecard was actually doing when olm-deployed is true, is the scorecard just applying the CR to the cluster?  how is it different under the covers from olm-deployed false?

The second question is can I pass the olm-deployed boolean of true or false on the command line vs osdk-scorecard.yaml, something like `operator-sdk scorecard --olm-deployed=true`
per what I assume is an old document now, https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#scorecard

**Comment by camilamacedo86** [comment]
Hi @jdockter, 

> @camilamacedo86 yes I have read those documents before but it wasn't clear to me what the scorecard was actually doing when olm-deployed is true, is the scorecard just applying the CR to the cluster? how is it different under the covers from olm-deployed false?

It will apply the [Cluster Service Version (CSV)](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md) in the cluster which is the file/config required to integrate your project with OLM. 

> The second question is can I pass the olm-deployed boolean of true or false on the command line vs osdk-scorecard.yaml, something like operator-sdk scorecard --olm-deployed=true
> per what I assume is an old document now, https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#scorecard

If you do not use `--olm-deployed` then it will be false.  If you use it will be true. However, if you use it with =false also probably will set the false value.

**Comment by jdockter** [comment]
@camilamacedo86 okay thanks, closing.
