### ISSUE TITLE
The Watch should keep retrying on failure and not panic

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/operator-sdk#224]
Currently if an operator tries to watch a Custom Resource type before the CRD is registered then it will panic because it can't create a resource client for an unregistered type.
https://github.com/operator-framework/operator-sdk/blob/https://github.com/operator-framework/operator-sdk/blob/0b429fb2ef27dd66d19e0028eb33fdfb445ad859/pkg/sdk/api.go#L44-L49/pkg/sdk/api.go#L44-L49

The operator pod will keep crashing and restarting until the CRD is created.

Ideally the Watch should keep retrying when it fails to create a resource client for an unknown type. This way the operator does not crash and will wait until the CRD is created.

This allows us to keep to keep the deployment and CRD manifests separate as well.
ref: https://github.com/operator-framework/operator-sdk/issues/76

**Comment by fanminshi** [comment]
duplicate with https://github.com/operator-framework/operator-sdk/issues/183?

**Comment by hasbro17** [comment]
Closing in favor of #183
