### ISSUE TITLE
Operator courier future

### ISSUE THREAD

**Issue by jdockter** [operator-framework/operator-sdk#2245]
## Type of question

operator-courier 

## Question

In reading this proposal, https://github.com/operator-framework/operator-sdk/blob/master/doc/proposals/openshift-4.3/operator-testing-tool.md#story-3---common-validation, it sounds like the 'operator-courier verify' functionality is going to be rolled into a new `operator-sdk scorecard --bundle ./my-operator' command.  Is that correct?  If so, will other functions also be moving into operator-sdk scorecard? 
@jmccormick2001

**Comment by jmccormick2001** [comment]
the plan is to have a 'bundle validation' test in scorecard, a static validation test, where you can specify a bundle path and it will call a common validation lib to inspect the bundle contents and report back any validation errors.

**Comment by camilamacedo86** [comment]
@joelanford would you like to add some input here to help us to close this one.

**Comment by joelanford** [comment]
The plan is to eventually phase out operator courier when its functionality exists elsewhere. As @jmccormick2001 mentioned, we'll soon have support for the bundle validation in the SDK. In addition the SDK and OLM projects will be working together to introduce functionality for building a bundle image, which (I believe) can then be pushed to a container registry like any other container image. Scorecard is limited to operator verification, so the `build` functionality will be introduced elsewhere in the CLI.

#2076 captures the intent, though I think it is still a WIP.

@ecordell Does that all sound right?
