### ISSUE TITLE
Commands using sed the shell scripts do not work for Mac OS 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#2257]
## Bug Report

**What did you do?**
For example, try to run make test-sanity in a mac os x. 

**What did you expect to see?**
The test be executed with success

**What did you see instead? Under which circumstances?**
An error because of the sed

**Possible Solution**
Check if is mac or Linux and then exec accordingly the command. Or change the implementation in order to not require sed usage.

**Additional context**
See the places: https://github.com/operator-framework/operator-sdk/search?l=Shell&q=sed

**Comment by camilamacedo86** [comment]
c/c @estroz @joelanford

**Comment by joelanford** [comment]
@camilamacedo86 Yeah, that's a known issue, but I'm not sure every single one of our `sed` usages is broken. For this particular issue, which sed invocation is erroring out?

**Comment by joelanford** [comment]
Also, I sometimes use a Mac and I've gotten around this problem by installing GNU sed from homebrew. The version of sed shipped with Mac OS is super old.
```sh
brew install gnu-sed
```

**Comment by camilamacedo86** [comment]
Thanks @joelanford it does not work. I know that we have this issue with some places .. but would be nice to find a better solution which make work in both. For example, now I am unable to run the test sanity without changing it manually :-(

```
+ sed -i 's|github.com/operator-framework/operator-sdk\s\+master||g' go.mod
sed: 1: "go.mod": extra characters at the end of g command

```

**Comment by joelanford** [comment]
Submit a PR with the manual change you made to get it to work on Mac :slightly_smiling_face:
