### ISSUE TITLE
Vendor kubernetes/code-generator instead of using the code-gen image

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/operator-sdk#226]
Currently the SDK relies on running the container image `gcr.io/coreos-k8s-scale-testing/codegen:1.9.3` which packages [kubernetes/code-generator](https://github.com/kubernetes/code-generator) to do code generation for CRDs.

We should decouple the SDK from relying on an externally maintained image and instead vendor `github.com/kubernetes/code-generator` in the SDK to build and do the code generation.

**Comment by danni-m** [comment]
I had the same problem because I wanted to use the defaulters as well as deepcopy generator.
For future reference, I solved it by vendoring the `codegen` package and calling it from my makefile:
1. add `code-generator` to Gopkg.toml:
```
[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.0"
```
2. added 2 make jobs to build deepcopy and defaulters:
```make
generate_deepcopy: $(BINDIR)/deepcopy-gen
	${BINDIR}/deepcopy-gen "$@" \
	 -v 1 --logtostderr \
	 --go-header-file "./tmp/codegen/boilerplate.go.txt" \
	 --input-dirs "github.com/RedisLabs/redis-enterprise-operator/pkg/apis/app/v1alpha1" \
	 --output-file-base "zz_generated.deepcopy"

generate_defaulters: $(BINDIR)/defaulter-gen
	${BINDIR}/defaulter-gen "$@" \
	 -v 1 --logtostderr \
	 --go-header-file "./tmp/codegen/boilerplate.go.txt" \
	 --input-dirs "github.com/RedisLabs/redis-enterprise-operator/pkg/apis/app/v1alpha1" \
	 --output-file-base "zz_generated.defaults"

generate_files: generate_defaulters generate_deepcopy
```
3. add `pkg/apis/app/v1alpha1/doc.go` header:
```go
// +k8s:defaulter-gen=TypeMeta
```
