### ISSUE TITLE
client.Get by types.NamespacedName in namespace scope works only in the namespace where the operator is running

### ISSUE THREAD

**Issue by paterczm** [operator-framework/operator-sdk#2265]
Hello!

I'm observing a strange behavior when getting resources by name and namespace. Please consider:

A snippet from a controller:
```golang
	if err = r.client.Get(context.TODO(), types.NamespacedName{Name: "resource-limits", Namespace: "another-example-team"}, &v1.LimitRange{}); err != nil && errors.IsNotFound(err) {
		reqLogger.Info("Did not find resource-limits in another-example-team")
	}

	if err = r.client.Get(context.TODO(), types.NamespacedName{Name: "resource-limits", Namespace: "another-example-team2"}, &v1.LimitRange{}); err != nil && errors.IsNotFound(err) {
		reqLogger.Info("Did not find resource-limits in another-example-team2")
	}

	if err = r.client.Get(context.TODO(), types.NamespacedName{Name: "resource-limits", Namespace: "another-example"}, &v1.LimitRange{}); err != nil && errors.IsNotFound(err) {
		reqLogger.Info("Did not find resource-limits in example-team")
	}
```

Those limit resources do exist:

```
$ oc get limits --all-namespaces
NAMESPACE               NAME              CREATED AT
another-example-team    resource-limits   2019-11-25T19:59:48Z
another-example-team2   resource-limits   2019-11-25T20:10:16Z
example-team            resource-limits   2019-11-25T20:02:34Z
```

Running the operator in paas-operators namespace:
```
$ oc project paas-operators
$ operator-sdk up local

{"level":"info","ts":1574715334.5000331,"logger":"controller_team","msg":"Did not find resource-limits in another-example-team","Request.Namespace":"","Request.Name":"another-example-team"}
{"level":"info","ts":1574715334.5000432,"logger":"controller_team","msg":"Did not find resource-limits in another-example-team2","Request.Namespace":"","Request.Name":"another-example-team"}
{"level":"info","ts":1574715334.5000532,"logger":"controller_team","msg":"Did not find resource-limits in example-team","Request.Namespace":"","Request.Name":"another-example-team"}
```

None of the limits were found as expected.

Running the operator in another-example-team namespace:
```
$ oc project another-example-team
$ operator-sdk up local

{"level":"info","ts":1574715430.9136941,"logger":"controller_team","msg":"Did not find resource-limits in another-example-team2","Request.Namespace":"","Request.Name":"another-example-team"}
{"level":"info","ts":1574715430.913723,"logger":"controller_team","msg":"Did not find resource-limits in example-team","Request.Namespace":"","Request.Name":"another-example-team"}
```

As you can see, one limit object was found as expected (in the same namespace where the operator run), other 2 weren't found. Moving the operator to another namespace would change the results accordingly.

The RBAC is correct as far as I can tell. The operator created those limits itself, so the problem is only with getting them.

I have no idea what's going on. Please advice. Tested in OpenShift 3.11 and operator-sdk version: "v0.11.0", commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d", go version: "go1.12.7 linux/amd64".

**Comment by camilamacedo86** [comment]
When we run `operator-sdk local` we are running the operator out of the cluster and the operator scope will be namespaced where by default it will be in the namespace where the operator is deployed. 

However, in the cluster, the operator will just be allowed to watch other namespaces if its scope is a cluster one. For further information see the [doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md).

Please, let us know if the above information answered your question and if we can close this or how can we help you with.

**Comment by paterczm** [comment]
Hello Camila

Thanks for clarifying about `operator-sdk up local`, I thought it can be used to run cluster scoped operators (especially since my operator run using this method is able to create objects in other namespaces, but not get them). Are there plans to add cluster operator support to `operator-sdk up local`?

**Comment by camilamacedo86** [comment]
Hi @paterczm,

Could you try export the Env Var's as follows then run the operator-sdk up local?

> export WATCH_NAMESPACE=" "

I believe that it will work since it will be started with the value  " " for WATCH_NAMESPACE which is the cluster scope setup. Please, let me know if it works or not for you.

Also, the project has the https://github.com/operator-framework/operator-sdk/pull/2149 which has been discussed in order to improve the operator-sdk up local configuration regards these options.

**Comment by paterczm** [comment]
I tested this again today. Following has no effect (still can't Get namespace scoped resources from other namespaces):
```
export OPERATOR_NAME=my-operator
export WATCH_NAMESPACE=" "
operator-sdk up local
```

However, this works:
```
operator-sdk up local --namespace ""
```
Namespace parameter has to be blank, specifying the namespace or omitting the parameter reproduces the issue. Hope https://github.com/operator-framework/operator-sdk/pull/2149 will help this work in a more predictable way.

**Comment by camilamacedo86** [comment]
Hi @paterczm, 

Really thank you for your reply. I am glad that  `operator-sdk up local --namespace ""` attend your needs for now. Please, feel free to follow up #2149.

Then, I am closing this one since all shows sort out. However, please feel free to re-open if you think that is required.
