### ISSUE TITLE
gen-csv should find out the latest CSV version

### ISSUE THREAD

**Issue by aliok** [operator-framework/operator-sdk#2267]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Assume this tree:
```
$ tree deploy/
deploy/
└── olm-catalog
    └── knative-eventing-operator
        ├── 0.9.0
        │   ├── 300-eventing-v1alpha1-knativeeventing-crd.yaml
        │   └── knative-eventing-operator.v0.9.0.clusterserviceversion.yaml
        ├── 0.10.0
        │   ├── eventing_v1alpha1_knativeeventing_crd.yaml
        │   └── knative-eventing-operator.v0.10.0.clusterserviceversion.yaml
        └── knative-eventing-operator.package.yaml
```
and assume I want to generate the CSV for version `0.11.0`.

Currently I have to do this:
```
operator-sdk olm-catalog gen-csv            \
  --from-version  0.10.0                    \
  --csv-version   0.11.0                    \
  [...]
```
I have to find out the `from-version` myself and feed it to `operator-sdk olm-catalog gen-csv`, which is not easy (details at the bottom).

**Describe the solution you'd like**

I would like to have a call like this:

```
operator-sdk olm-catalog gen-csv            \
  --from-latest-version                     \
  --csv-version   0.11.0                    \
  [...]
```
and operator-sdk should figure out the `--from-version` for me.

**`--from-latest-version`** (just made it up) is the important thing here! I suggest creating a flag like that.

Outcome would be:
```
$ tree deploy/
deploy/
└── olm-catalog
    └── knative-eventing-operator
        ├── 0.9.0
        │   ├── 300-eventing-v1alpha1-knativeeventing-crd.yaml
        │   └── knative-eventing-operator.v0.9.0.clusterserviceversion.yaml
        ├── 0.10.0
        │   ├── eventing_v1alpha1_knativeeventing_crd.yaml
        │   └── knative-eventing-operator.v0.10.0.clusterserviceversion.yaml
        ├── 0.11.0
        │   ├── eventing_v1alpha1_knativeeventing_crd.yaml
        │   └── knative-eventing-operator.v0.11.0.clusterserviceversion.yaml
        └── knative-eventing-operator.package.yaml
```

**Additional info**
In our project, we want to call `gen-csv` subcommand with a Bash script.
However, finding out the previous version and passing it as `--from-version` is hard with Bash. That is because of semver complexities. For example, `0.10.0` is a greater version than `0.9.0`, but not when you simply sort nested directory names. So, alphabetic sorting won't work.

However, if the CLI would do that for me, that would be great! CLI could simply use https://github.com/coreos/go-semver.

**Comment by aliok** [comment]
cc @camilamacedo86

**Comment by camilamacedo86** [comment]
I am not sure if I follow up properly the feature request here. 

Would you like to run `operator-sdk olm-catalog gen-csv ` and then it automatically set the from and the new version following up semver? Am I right? 

> I think finding out the new version is kind of easy with Bash scripts (we have a version.go file which can be read by the script).

The version.go is not necessarily the same version of CSV. Note that the tags of CSV not necessarily will be or follow up the project tags as well.

**Comment by aliok** [comment]
I am more interested in that cli sets from version automatically.

**Comment by camilamacedo86** [comment]
It still not clear for me. Could you please exemplify as for example?
- For the example in the first comment of this issue; I'd like to run the command `x`
- Then, I would expect the result X.

**Comment by aliok** [comment]
Ok, will do that when I get home

**Comment by aliok** [comment]
@camilamacedo86 Updated the issue description. Let me know if you need further clarification.

**Comment by camilamacedo86** [comment]
Hi @aliok, 

Yes, it is clear enough now. Really thank you for the clarifications. 
It need to be discussed with the team, so I will label it. Also, feel free to collab with a PR if you think that you could easily provide the solution as well.

**Comment by aliok** [comment]
> Also, feel free to collab with a PR if you think that you could easily provide the solution as well.

I was planning to give it a try already :)

**Comment by camilamacedo86** [comment]
Hi @joelanford, @hasbro17 and @estroz, 

WDYT? It shows reasonable for me but low priority. It would be adding new flag as for example `--from-latest-version` to the `operator-sdk olm-catalog gen-csv ` command which would automatically identify the latest tag used for the CSV.

**Comment by estroz** [comment]
@aliok you can sort by semantic version with GNU `sort`:
```console
$ echo -e "0.1.0\n0.2.0\n3.0.0\n0.0.5\n0.0.12" | sort -V
0.0.5
0.0.12
0.1.0
0.2.0
3.0.0
```
You can do something like:
```sh
$ find deploy/olm-catalog/operator-name/* -maxdepth 1 -type d -exec basename {} \; | sort -V | tail -1
```
to get the latest version. Does that solve your issue?

**Comment by aliok** [comment]
hi @estroz 
thanks, it does actually.

I would still prefer the hypothetical `--from-latest-version` though :)
Let me know what you guys think and I can send a PR for that.

**Comment by estroz** [comment]
@aliok sounds good. I'll let a few others comment on this, and if we find its a feature we want in `operator-sdk` then you can spend time on the PR.

One goal of the SDK is to have a low-complexity CLI, so we strive to keep the number of flags to a minimum, especially when there are 1-2 line bash wrappers that give you the same functionality of 10+ lines of Go code. This is the main reason why I hesitate to ok this right now, not that it isn't a useful feature.

**Comment by camilamacedo86** [comment]
Hi @aliok, 
 
After @estroz solution in https://github.com/operator-framework/operator-sdk/issues/2267#issuecomment-558833237 it shows that could be easily solved by adding it as Makefile target. 

In this way, it is the same scenario of https://github.com/operator-framework/operator-sdk/pull/1600#issuecomment-506730405 and then I am afraid that we should NOT move forward with.  As an example of a similar scenario see https://github.com/operator-framework/operator-sdk/issues/1964#issuecomment-542335647. 

So, could we agree in close this one since this need can be easily solved by creating a target in the Makefile with the above solution?
