### ISSUE TITLE
Golang operator's controller reconcilies an unchanging custom resource

### ISSUE THREAD

**Issue by paterczm** [operator-framework/operator-sdk#2282]
Hello

I recently noticed that my controllers wake up and perform reconciliation also when the watched resources aren't changing. I experimented with a single controller and made it watch only one custom resource (using `EnqueueRequestForObject`) and sure enough - I can see in the logs that it reconciles 4 to 5 times every hour, despite the custom resource not being updated. Tried to see what's going on by adding `--zap-devel` argument to the operator startup command, but it doesn't log anything useful.

Am I right to expect the reconciliation to trigger only when a watched resource actually changes? How can I find out why operator-sdk thinks the resource has changed (e.g. by logging the new and old resource)?

I'm using operator-sdk version: "v0.11.0", commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d", go version: "go1.12.7 linux/amd64" and running the operator in OpenShift 3.11.

Thanks for help.

Marek

**Comment by camilamacedo86** [comment]
Hi @paterczm, 

Note that: 

- The reconcile will be trigged by default every 10 hours unless you change it.
- The reconcile will be trigged when any event/change in the resources watched by it be identified. 

Further details

After you apply/create the CR which will trigger the reconcile it is trigged by the watches implementations and/or by the manager each X time. 

#### Watches

By default, you will find the watches for the Primary resources already implemented by each controller that you generated by using the SDK tool as follows. 

```go
// Watch for changes to primary resource Memcached
err = c.Watch(&source.Kind{Type: &cachev1alpha1.Memcached{}}, &handler.EnqueueRequestForObject{})
if err != nil {
    return err
}

```

However, note that in the example has watches implemented for each secondary object controlled/created by it. 

```go
// TODO(user): Modify this to be the types you create that are owned by the primary resource
// Watch for changes to secondary resource Pods and requeue the owner Memcached
err = c.Watch(&source.Kind{Type: &appsv1.Deployment{}}, &handler.EnqueueRequestForOwner{
    IsController: true,
    OwnerType:    &cachev1alpha1.Memcached{},
})
if err != nil {
    return err
}

err = c.Watch(&source.Kind{Type: &corev1.Service{}}, &handler.EnqueueRequestForOwner{
    IsController: true,
    OwnerType:    &cachev1alpha1.Memcached{},
})
if err != nil {
    return err
}
```

#### Reconcile trigged by the manager : (main.go)

If you do not change the following code that is created when you do a new project with the SDK then the Reconcile will be trigged every 10 hours.  

```go
	// Create a new Cmd to provide shared dependencies and start components
	mgr, err := manager.New(cfg, manager.Options{
		Namespace:          namespace,
		MapperProvider:     restmapper.NewDynamicRESTMapper,
		MetricsBindAddress: fmt.Sprintf("%s:%d", metricsHost, metricsPort),
	})
	if err != nil {
		log.Error(err, "")
		os.Exit(1)
	}

```
**Why does it happen? How do I know that?** 

See the Options Struct which is used to create the Manager of the operator project.  

```go
	// SyncPeriod determines the minimum frequency at which watched resources are
	// reconciled. A lower period will correct entropy more quickly, but reduce
	// responsiveness to change if there are many watched resources. Change this
	// value only if you know what you are doing. Defaults to 10 hours if unset.
	SyncPeriod *time.Duration
```

Please, let me know if the above information answered your question and if we can close this one or if it has anything else that you are expecting here.

**Comment by paterczm** [comment]
Thank you for getting back to me so quickly.

The only watch I defined for testing this is:
```
// Watch for changes to primary resource
err = c.Watch(&source.Kind{Type: &mygroup1alpha1.MyResource{}}, &handler.EnqueueRequestForObject{})
if err != nil {
    return err
}
```

I didn't make any modifications to the generated code in `cmd/manage/main.go`, so it should not trigger the reconciliation a few times every hour. 

I doubt it matters, but I'm watching a cluster scoped resource.

I guess what I'm looking for here is more insight into when and why events are raised, ideally by enabling more verbose logging from the sdk. Try and error is expensive here, because the first unexpected reconciliation happens around 15-20 minutes after operator deployment, so debugging iterations are really long.

**Comment by camilamacedo86** [comment]
Hi @paterczm, 

You can print and check logs in the operator pod. Following an example:
Use to log: 

> 	reqLogger := log.WithValues("Request.Namespace", request.Namespace, "Request.Name", request.Name)
> 	reqLogger.Info("Reconciling Memcached.")

See: https://github.com/operator-framework/operator-sdk-samples/blob/master/memcached-operator/pkg/controller/memcached/memcached_controller.go#L92

Use to check:

> kubectl logs  deployment.apps/memcached-operator
  
However, the events are raised in the k8s API. So, you can check the events in the namespace (`kubectl get events -n <namespace>`). If you have just on watch for the primary resource and you are with the default implementation then, it means that the reconcile will be trigged when the CR is applied and after every 10 hours. 

So, if you are seen it be trigged more times it means that something changed the CR which can be indeed the platform, for example, if for some reason it has been recreating the pods and etc ...  

Please, let me know if the above information answered your question and if we can close this one or if it has anything else that you are expecting here.

**Comment by camilamacedo86** [comment]
Hi @paterczm,
 
Important: 

> I'm using operator-sdk version: "v0.11.0", commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d", go version: "go1.12.7 linux/amd64" and running the operator in OpenShift 3.11.

Since SDK 0.9 the OCP 3.11 is no longer compatible with since it will use an old version of k8s api. I'd recommend you use Minkube and/or OCP 4. So, it means that the SDK 0.11 has not support for the cluster version used by you.

**Comment by paterczm** [comment]
I don't see the same problem when I run the operator in OpenShift 4.2, so looks like this is related to the Kubernetes/OpenShift version. Unfortunately, OpenShift 3.11 is the environment I'm targeting for this operator. Do you recommend using an older version of the SDK for OpenShift 3.11? From what you're saying, I understand that SDK 0.8.x should still support OpenShift 3.11?

**Comment by camilamacedo86** [comment]
Hi @paterczm, 

The SDK version 0.8 should work with 3.11, however, note that it is really outdated. So, I do NOT recommend you use an old version of the SDK and go since it may bring others complications and then if you have any issue and etc .. the solution will be to do the upgraded. Shows that you are doing a new project too, so it will be born with tech debt already. In this way, I definitely do not suggest you recommend it.

Also, it is important to highlight that OLM is NOT compatible with OCP 3.11 as well which means that you will not able to integrate the operator with your provide your solution in the https://operatorhub.io/ and/or OCP catalogue. 

I'd recommend you use Miinikube locally since is very easy to install and work with and target OCP 4. Then you will be able to adopt the version 0.12 of SDK, use go 1.13+ and etc ...

**Comment by tobiasdziekanowski** [comment]
Hey @camilamacedo86 
I am not able to switch to openshift 4, since my target openshift version in production is 3.11. 
So, maybe it's a bit off topic, but what is the best approach for using the operator sdk in that version in combination with ansible? sticking to version 0.8.2 of the operator-sdk or go to a higher version? i am getting more and more confused by reading this https://sdk.operatorframework.io/docs/upgrading-sdk-version/
is there any guidance howto deal with openshift 3.11 nowadays?
regards
tobi
