### ISSUE TITLE
Github binary fails to download with curl

### ISSUE THREAD

**Issue by austincunningham** [operator-framework/operator-sdk#2284]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).
Followed the instructions for linux at https://github.com/operator-framework/operator-sdk/blob/master/doc/user/install-operator-sdk.md

- set the var
```bash
~ export RELEASE_VERSION=v0.12.0
```
- download the binary
```bash
~ curl -LO https://github.com/operator-framework/operator-sdk/releases/download/$\{RELEASE_VERSION\}/operator-sdk-$\{RELEASE_VERSION\}-x86_64-linux-gnu
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0     23      0 --:--:-- --:--:-- --:--:--    23
```
- ran the command to chmod and move the binary to /usr/local/bin
```bash
~ chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
chmod: cannot access 'operator-sdk-v0.12.0-x86_64-linux-gnu': No such file or directory
```

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).
- expect the binary to install the binary /usr/local/bin

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

- the binary didn't download , see this in my home
```bash
~ ls -la | grep operator
-rw-r--r--.    1 austincunningham austincunningham      9 Dec  2 08:15 'operator-sdk-$RELEASE_VERSION-x86_64-linux-gnu' 
```
Files size is too small and the name of the file is incorrect. Looks like the curl failed.

**Environment**
* operator-sdk version: v0.12.0

* OS: Fedora 30

**Possible Solution**

Was able to download from https://github.com/operator-framework/operator-sdk/releases/tag/v0.12.0 from the browser 
But upon looking at the binary after install its the wrong verstion
```bash
~ operator-sdk version
operator-sdk version: v0.9.0-19-gfb768122, commit: fb7681220ad6608eb0b7a53c507e136024f9371c
~ which operator-sdk
/usr/local/bin/operator-sdk
```

**Additional context**

**Comment by austincunningham** [comment]
Tried using curl without env var RELEASE_VERSION
```curl -OJL https://github.com/operator-framework/operator-sdk/releases/download/v0.12.0/operator-sdk-v0.12.0-x86_64-linux-gnu
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   628    0   628    0     0   1799      0 --:--:-- --:--:-- --:--:--  1799
100 63.5M  100 63.5M    0     0  1333k      0  0:00:48  0:00:48 --:--:-- 1788k
curl: Saved to filename 'operator-sdk-v0.12.0-x86_64-linux-gnu'
``` 
- looks to have download
- chmod command appears to work
```bash
~ Downloads chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu

~ which operator-sdk
/usr/local/bin/operator-sdk
```
- But looks to be the wrong version again
```bash
~ operator-sdk version
operator-sdk version: v0.9.0-19-gfb768122, commit: fb7681220ad6608eb0b7a53c507e136024f9371c
~ cd /usr/local/bin
   bin ls -la | grep operator-sdk
-rwxr-xr-x.  1 root             root             66594871 Dec  2 09:18 operator-sdk
```

**Comment by camilamacedo86** [comment]
HI @austincunningham, 

**Regards the Donwload:**

It is probably because of the `\` in the middle added by you (`$\{RELEASE_VERSION\}`). See that the description [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/install-operator-sdk.md) is not the same. 

Following the local test. 

```shell
$ export RELEASE_VERSION="v0.12.0"
camilamacedo@Camilas-MacBook-Pro ~/tmp $ curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   628    0   628    0     0   2120      0 --:--:-- --:--:-- --:--:--  2121
100 63.5M  100 63.5M    0     0  6328k      0  0:00:10  0:00:10 --:--:-- 6556k
camilamacedo@Camilas-MacBook-Pro ~/tmp $ ls
operator-sdk-v0.12.0-x86_64-linux-gnu
```

- command used by you: `~ curl -LO https://github.com/operator-framework/operator-sdk/releases/download/$\{RELEASE_VERSION\}/operator-sdk-$\{RELEASE_VERSION\}-x86_64-linux-gnu`
- command described in the doc ` curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu`

**Regards the version**

Over:

> 
> operator-sdk version
> operator-sdk version: v0.9.0-19-gfb768122, commit: fb7681220ad6608eb0b7a53c507e136024f9371c
> ~ cd /usr/local/bin
>    bin ls -la | grep operator-sdk
> -rwxr-xr-x.  1 root             root             66594871 Dec  2 09:18 operator-sdk
 
Shows that version 0.9 was already previously installed. 
Could you try to clean your local env and ensure that you have not any version installed before following the steps? Also, ensure that you have not the SDK  bin in `$GOPTAH/bin/`.

Please let us know if with the above information you could sort it out and if we can close this one.

**Comment by austincunningham** [comment]
Thanks @camilamacedo86 it was the v0.9.0 in the $GOPATH/bin

**Comment by austincunningham** [comment]
Looks like the backslashes are beening added by zshsh, maybe ohmyzsh,
```
➜  ~ curl -LO https://github.com/operator-framework/operator-sdk/releases/download/$\{RELEASE_VERSION\}/operator-sdk-$\{RELEASE_VERSION\}-x86_64-linux-gnu
➜  ~ sh
sh-5.0$ curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
```
```
