### ISSUE TITLE
CRD generation not respecting "// +k8s:openapi-gen=false"

### ISSUE THREAD

**Issue by jpkrohling** [operator-framework/operator-sdk#2285]
## Bug Report

In the Jaeger Operator, we want to skip the generation of the CRD schema for some properties such as `v1.Volume`, as they cause the final CRD to be way too big. Adding `// +k8s:openapi-gen=false` to the fields does make the field to be skipped from `pkg/apis/jaegertracing/v1/zz_generated.openapi.go`, but the field does end up in the CRD.

**What did you do?**

From [this branch (jpkrohling/jaeger-operator/763-Add-openapi-to-generate)](https://github.com/jpkrohling/jaeger-operator/tree/763-Add-openapi-to-generate), run:

1. `operator-sdk generate openapi`
1. check that `schema_pkg_apis_jaegertracing_v1_JaegerAgentSpec` has no `Volume` node
1. the CRD gets updated and the `agent` node (starting on line 604) has a `volume` node (line 1416)
1. bonus point: check that the CRD file has 1.3 MB

**What did you expect to see?**

1. the CRD gets generated without the fields marked with `// +k8s:openapi-gen=false` in `pkg/apis/jaegertracing/v1/jaeger_types.go`, such as the `Volumes` field in the `JaegerCommonSpec`, embedded by `JaegerAgentSpec` (and by other types).

**Environment**
* operator-sdk version: `operator-sdk version: "v0.11.0", commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d", go version: "go1.12.7 linux/amd64"`
* go version: `go version go1.13.4 linux/amd64`
* Kubernetes version information: `not relevant`
* Kubernetes cluster kind:  `not relevant`
* Are you writing your operator in ~ansible, helm,~ or *go*? `go`

**Comment by camilamacedo86** [comment]
Hi @jpkrohling,

I am sure that the annotation is supported for all spec such as the following example. So, could you let us know where you check that the annotation could be used to ignore specific fields and definitions? Could you please share this doc? Also, could you add here a piece of the code over how you are using it?  

```
// Descripttion
// +k8s:openapi-gen=true
type KindStatus struct {
```

```
// Descripttion
// +k8s:openapi-gen=true
type KindSped struct {
```

**Comment by jpkrohling** [comment]
We talked quite a bit in private, and I wanted to summarize the current status before leaving for the day.

1. looks like I left it out from the original description, but the *actual* problem is that the generated [CRD](https://github.com/jpkrohling/jaeger-operator/blob/763-Add-openapi-to-generate/deploy/crds/jaegertracing.io_jaegers_crd.yaml) cannot be applied, as Kubernetes complains about `The CustomResourceDefinition "jaegers.jaegertracing.io" is invalid: metadata.annotations: Too long: must have at most 262144 characters`
1. the CRD works when some fields are left out, like the `volumes`
1. the theory is that "something" is adding annotation data to the CRD during the apply process, which then makes Kubernetes refuse the final CRD

I understand that I cannot simply ignore fields in the CRD, as they would later fail to be passed to my controller's Go type. My current CRD does not specify a validation nor schema, which is why it works today.

Action item for me:
- [ ] check how the annotation field looks like after applying the CRD without the `volumes` node (or a version of the CRD that gets accepted by the Kubernetes server).

**Comment by joelanford** [comment]
@jpkrohling Are you doing `kubectl apply` to create the CRD? If so, the apiserver is probably adding the `kubectl.kubernetes.io/last-applied-configuration` annotation, which contains the entire content of the applied resource. With all of the validation metadata included, I wouldn't be surprised if that pushed that field above 262144 characters.

**Comment by joelanford** [comment]
Seems related to https://github.com/kubernetes-sigs/kubebuilder/issues/1140

**Comment by camilamacedo86** [comment]
Hi @joelanford, 

Yes. It may be the same scenario of kubernetes-sigs/kubebuilder#1140 since theire the say that solved te issue by using the create flag instead of applying. However, I'd like to do more tests in kubebuilder to ensure since there also many info can be used in the scaffolds which is not the case of SDK. For example, the name o the project is used to create the namespace.  Then, I'd like to ensure that there is not required to add more validations as it was done https://github.com/kubernetes-sigs/kubebuilder/pull/1173.

**Comment by jpkrohling** [comment]
You are absolutely right, @joelanford. Using `kubectl create` instead of `kubectl apply` helps me move forward. I'm closing this, thanks!

**Comment by camilamacedo86** [comment]
Hi @jpkrohling,

To know more about see here doc over it: https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/
