### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/operator-sdk#229]
We need to add a CHANGELOG to the repo to keep track of changes to the API/CLI so we can publish those changes as part of the release notes for each release.

The exact format of the CHANGELOG needs to be decided. A few examples:
https://github.com/coreos/etcd-operator/blob/master/CHANGELOG.md
https://github.com/coreos/prometheus-operator/blob/master/CHANGELOG.md
https://github.com/ansible/ansible/blob/devel/CHANGELOG.md

There seems to be no standard format but based on simplicity my preference would be:
https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md
based on https://keepachangelog.com/en/1.0.0/

/cc @spahl @fanminshi

**Comment by fanminshi** [comment]
I think any of them are okay. I would just have the changelog format the same as how we have done for etcd-operator and vault-operator.

**Comment by spahl** [comment]
I don't have an opinion, the etcd operator one looks good to me.
