### ISSUE TITLE
operator-sdk new failed

### ISSUE THREAD

**Issue by riponbanik** [operator-framework/operator-sdk#2294]
**What did you do?**

I ran the following command and it gives me timeout error every time -

operator-sdk new cnat-operator --repo github.com/riponbanik/k8s-example/cnat-operator
INFO[0000] Creating new Go operator 'cnat-operator'.    
INFO[0000] Created go.mod                               
INFO[0000] Created tools.go                             
INFO[0000] Created cmd/manager/main.go                  
INFO[0000] Created build/Dockerfile                     
INFO[0000] Created build/bin/entrypoint                 
INFO[0000] Created build/bin/user_setup                 
INFO[0000] Created deploy/service_account.yaml          
INFO[0000] Created deploy/role.yaml                     
INFO[0000] Created deploy/role_binding.yaml             
INFO[0000] Created deploy/operator.yaml                 
INFO[0000] Created pkg/apis/apis.go                     
INFO[0000] Created pkg/controller/controller.go         
INFO[0000] Created version/version.go                   
INFO[0000] Created .gitignore                           
INFO[0000] Validating project                           
go: github.com/operator-framework/operator-sdk@v0.12.0: Get https://proxy.golang.org/github.com/operator-framework/operator-sdk/@v/v0.12.0.mod: dial tcp: i/o timeout
Error: failed to exec []string{"go", "build", "./..."}: exit status 1

**What did you expect to see?**
Operator creation pass without any error

**What did you see instead? Under which circumstances?**
go: github.com/operator-framework/operator-sdk@v0.12.0: Get https://proxy.golang.org/github.com/operator-framework/operator-sdk/@v/v0.12.0.mod: dial tcp: i/o timeout

**Environment**
* operator-sdk version:
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.3 linux/amd64"

* go version:

go version go1.13.3 linux/amd64

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-22T06:44:59Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
minikube

* Are you writing your operator in ansible, helm, or go?
go

**Possible Solution**
N/A

**Additional context**
Learning on how to build operator

**Comment by camilamacedo86** [comment]
Shows that you have some network issues locally. See `dial tcp: i/o timeout`

**Comment by riponbanik** [comment]
@camilamacedo86  Does not seem to be network issue. I am using 50MBPS internet connection

**Comment by camilamacedo86** [comment]
Hi @riponbanik,

See that I am not facing any issue.

```
$ operator-sdk new cnat-operator --repo github.com/riponbanik/k8s-example/cnat-operator
INFO[0000] Creating new Go operator 'cnat-operator'.    
INFO[0000] Created go.mod                               
INFO[0000] Created tools.go                             
INFO[0000] Created cmd/manager/main.go                  
INFO[0000] Created build/Dockerfile                     
INFO[0000] Created build/bin/entrypoint                 
INFO[0000] Created build/bin/user_setup                 
INFO[0000] Created deploy/service_account.yaml          
INFO[0000] Created deploy/role.yaml                     
INFO[0000] Created deploy/role_binding.yaml             
INFO[0000] Created deploy/operator.yaml                 
INFO[0000] Created pkg/apis/apis.go                     
INFO[0000] Created pkg/controller/controller.go         
INFO[0000] Created version/version.go                   
INFO[0000] Created .gitignore                           
INFO[0000] Validating project                           
go: finding github.com/operator-framework/operator-sdk master
go: downloading github.com/operator-framework/operator-sdk v0.12.1-0.20191205200208-31846a5e480e
go: extracting github.com/operator-framework/operator-sdk v0.12.1-0.20191205200208-31846a5e480e
INFO[0006] Project validation successful.               
INFO[0006] Project creation complete.                   
``` 

Then check that when it will get the module in your logs has a TCP timeout issue

> go: github.com/operator-framework/operator-sdk@v0.12.0: Get https://proxy.golang.org/github.com/operator-framework/operator-sdk/@v/v0.12.0.mod: dial tcp: i/o timeout

Which means that was that from your computer is has been not possible to get the module from the https://proxy.golang.org/. 

**IMPORTANT** 


**Does not seem to be a network issue. I am using 50MBPS internet connection. I changed to use go version 12 and that issue is gone. Now I am seeing timeout for some of the downloads.**

- The version 1.12+ of go is not compatible with the latest version of the operator-SDK
- The 1.13 adopted by default the Proxy. So, check if you have any firewall which is blocking you to get things from https://proxy.golang.org/ and your GOPROXY env var. Can you print here the go env used by you?

**Comment by riponbanik** [comment]
@camilamacedo86 Thanks. Strange things, I never had this before. I run this from a vm virtual box and it used to download all go modules perfectly. Here is go env -

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ripon/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ripon/ws/build/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build773677291=/tmp/go-build -gno-record-gcc-switches"

**Comment by riponbanik** [comment]
@camilamacedo86  I have tested with Go version 12.14 and operator-sdk 11.0. I am not seeing any timeout issue, but the following 

1. operator-sdk new
..............
go: error loading module requirements
Error: failed to exec []string{"go", "build", "./..."}: exit status 1
Usage:
  operator-sdk new <project-name> [flags]

2.  operator-sdk add api
---
INFO[0043] Created deploy/crds/cnat.programming-kubernetes.info_v1alpha1_at_cr.yaml
Error: api scaffold failed: (error loading API roots ["/home/riponb/ws/k8s/cnat-operator/pkg/apis/cnat/v1alpha1"]: go [list -e -json -compiled=true -test=false -export=false -deps=true -find=false -tags ignore_autogenerated -- /home/riponb/ws/k8s/cnat-operator/pkg/apis/cnat/v1alpha1]: exit status 1: go: finding github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
go: finding github.com/gorilla/mux v1.6.2

3.  No error for operator-sdk add controller

**Comment by camilamacedo86** [comment]
HI @riponbanik,

See that you face the same issue. You are unable to download the go modules. 
`go: error loading module requirements` 

Following some suggestions and info. 

1. The go does not work well with more than one version installed locally, so let's try o fix your setup for the latest version with go  1.13+. Could you please remove all go bins that you have and re-duo your local setup for the latest version?
2. Then, could you please run the command `go env` and add the output here. 
3. Note that in the go1.13+ the `GOPROXY=""` by default should be `GOPROXY="https://proxy.golang.org,direct"`
4. After removing all try to run the command line run `go get -u golang.org/x/lint/golint` only. It should work with success if all is ok. 
5. If it works, means that you are able to download the modules. Then, install the latest version of the SDK and try again.
6. If it do not work, please put here the result of  `go env`.Are you in a private LAN or are you trying it from home? If you are in a private LAN, for example in the work could you check with the admins if it has some firewall rules in place which may are be blocking you? 

Please, let me know if it works.

**Comment by riponbanik** [comment]
@camilamacedo86 Thanks for your suggestion. Steps 1-4 were successful, but again failed at step 5

verifying sigs.k8s.io/controller-runtime@v0.3.0/go.mod: sigs.k8s.io/controller-runtime@v0.3.0/go.mod: Get https://proxy.golang.org/sumdb/sum.golang.org/supported: dial tcp: lookup proxy.golang.org on 192.168.1.1:53: read udp 192.168.1.168:52034->192.168.1.1:53: i/o timeout
verifying github.com/operator-framework/operator-sdk@v0.12.0/go.mod: github.com/operator-framework/operator-sdk@v0.12.0/go.mod: Get https://proxy.golang.org/sumdb/sum.golang.org/supported: dial tcp: lookup proxy.golang.org on 192.168.1.1:53: read udp 192.168.1.168:52034->192.168.1.1:53: i/o timeout
Error: failed to exec []string{"go", "build", "./..."}: exit status 1

To verify that I can download the module, I ran  go get  sigs.k8s.io/controller-runtime@v0.3.0 which downloaded the module successfully.

go: finding sigs.k8s.io v0.3.0
go: downloading sigs.k8s.io/controller-runtime v0.3.0
go: extracting sigs.k8s.io/controller-runtime v0.3.0
go: downloading k8s.io/apimachinery v0.0.0-20190817020851-f2f3a405f61d
go: downloading k8s.io/client-go v0.0.0-20190918200256-06eb1244587a
go: extracting k8s.io/apimachinery v0.0.0-20190817020851-f2f3a405f61d
go: extracting k8s.io/client-go v0.0.0-20190918200256-06eb1244587a
go: downloading golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2
go: downloading github.com/prometheus/client_golang v1.0.0
go: extracting golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2
go: extracting github.com/prometheus/client_golang v1.0.0
go: downloading github.com/google/gofuzz v0.0.0-20170612174753-24818f796faf
go: extracting github.com/google/gofuzz v0.0.0-20170612174753-24818f796faf
go: downloading golang.org/x/sys v0.0.0-20190312061237-fead79001313
go: extracting golang.org/x/sys v0.0.0-20190312061237-fead79001313
go: downloading github.com/beorn7/perks v1.0.0
go: extracting github.com/beorn7/perks v1.0.0
go: downloading k8s.io/api v0.0.0-20190918195907-bd6ac527cfd2
go: downloading github.com/prometheus/common v0.4.1
go: extracting k8s.io/api v0.0.0-20190918195907-bd6ac527cfd2
go: extracting github.com/prometheus/common v0.4.1
go: downloading github.com/gogo/protobuf v1.1.1
go: downloading github.com/google/uuid v1.0.0
go: downloading github.com/spf13/pflag v1.0.2
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading k8s.io/apiextensions-apiserver v0.0.0-20190918201827-3de75813f604
go: extracting github.com/google/uuid v1.0.0
go: extracting github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: extracting github.com/spf13/pflag v1.0.2
go: downloading k8s.io/klog v0.3.3
go: extracting k8s.io/apiextensions-apiserver v0.0.0-20190918201827-3de75813f604
go: extracting k8s.io/klog v0.3.3
go: extracting github.com/gogo/protobuf v1.1.1
go: downloading golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: downloading k8s.io/kube-openapi v0.0.0-20190228160746-b3a7cee44a30
go: downloading github.com/prometheus/procfs v0.0.2
go: downloading k8s.io/utils v0.0.0-20190506122338-8fab8cb257d5
go: extracting github.com/prometheus/procfs v0.0.2
go: extracting k8s.io/utils v0.0.0-20190506122338-8fab8cb257d5
go: extracting k8s.io/kube-openapi v0.0.0-20190228160746-b3a7cee44a30
go: extracting golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: downloading golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: extracting golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: downloading github.com/hashicorp/golang-lru v0.5.0
go: extracting github.com/hashicorp/golang-lru v0.5.0
go: downloading github.com/json-iterator/go v1.1.6
go: downloading golang.org/x/text v0.3.1-0.20181227161524-e6919f6577db
go: extracting github.com/json-iterator/go v1.1.6
go: extracting golang.org/x/text v0.3.1-0.20181227161524-e6919f6577db

go env -

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/riponb/.cache/go-build"
GOENV="/home/riponb/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/riponb/ws/golang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build280026331=/tmp/go-build -gno-record-gcc-switches"

**Comment by camilamacedo86** [comment]
Hi @riponbanik, 

Still shows some problem with your local setup. Let's try:

1. Ensure that you have just 1 go version installed (1.13+) 
2. Clean your local env by: 
- // remove all inside of $GOPATH/bin/*

Than;

> 
> $ export GO111MODULE=off
> $ go clean --modcache
> $ go clean
> $ export GO111MODULE=on
> 

And try again without the option `--repo=github.com/riponbanik/k8s-example/cnat-operator`

 If it doesn't work please put here;
- operator-sdk version
- go version
- the path that you are doing it?

**Comment by riponbanik** [comment]
@camilamacedo86 Thanks for assistance to troubleshoot the issue. None of it fixed my issue in my office laptop. I have got a pc at home where I did the installation and it succeeded. It could be the proxy/file system scanner (Application Controll) slowing down and thus timing out. Is there any way to increase timeout or no of retries?

**Comment by camilamacedo86** [comment]
Hi @riponbanik,

Really thank you for let me know. So, shows that my first guess was accurate. You are in some private LAN where a firewall rule is blocking it. I do not think that increase the time will solve it. I'd recommend you speak with the admins of this LAN. They can help find out what rule has been violated with and change the rules to allow you to do it in their network. 

I am closing this as sort out. 
Please, feel free to re-open if you think that is required.

**Comment by mhkarimi1383** [comment]
just used --vendor and worked :)
