### ISSUE TITLE
What is the best practise for operators include multiple resources

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-sdk#2300]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

**What did you do?**
I want to create an monitoring operator, but the operator include components like Prometheus, Grafana, exporter etc.

So I have two options to create my monitoring operator:
- Option 1: Use one operator to manage Prometheus, Grafana, exporter for monitoring.
- Option 2: There are already some operators for prometheus, Grafana etc, so just build my monitoring operator based on the existing operators.

**What did you expect to see?**
Hope to get some comments/suggestions for what is the best practise for my monitoring operator.

**Comment by camilamacedo86** [comment]
HI @grdryn, 

By building an operator via SDK, you can check that the implementation to export the metrics using the Prometheus Operator is done by default. Check the main.go. There a ServiceMonitor will be created to export the Prometheus metrics for the operator and its custom resources. 

To install the Prometheus, follow up https://github.com/coreos/kube-prometheus. It is very straight forward. Then, after you have the Prometheus installed and deploy the operator you will be able to get the metrics already. 

I'd recommend you check the [doc](https://github.com/operator-framework/operator-sdk/blob/491cdf6d9f600514963f5f29ccff34a5bfe9ba4e/doc/user/metrics/README.md#operator-sdk-monitoring-with-prometheus) as well.  

Please, let me know if it is what you are looking for.

**Comment by grdryn** [comment]
> HI @grdryn,

@gyliu513 this is probably for you :)

**Comment by camilamacedo86** [comment]
Autocomplete / GitHub suggestions issues :-P. Tks @grdryn

**Comment by gyliu513** [comment]
Thanks @camilamacedo86 for the always great support! Sorry for not describe clearly, here I was wondering if I can get some guidance for the best practise of `one operators include multiple resources`, and my monitoring operator is just an example :-)

**Comment by camilamacedo86** [comment]
Hi @gyliu513,

Sorry, but for me still not very clear what you are looking for. Note that you can define how many API's can be required for your solution. Could you please give more details for we are able to provide better assistance?

**Comment by gyliu513** [comment]
@camilamacedo86 let me explain the problem in detail, hope this helps.

Assume I have an application a1 which include c1, c2 and c3 as internal components, and now I want to create a operator to manage a1. In my understanding, there are two options for the operator of a1:

- Option 1: Use one operator to manage c1, c2 and c3 for application a1.
- Option 2: Build operators for c1, c2 and c3, then use build operator for application a1 with operators for c1, c2 and c3.

Here I want to get some best practise or guidance for above user scenario.

**Comment by camilamacedo86** [comment]
Hi @gyliu513,

You can have how many CRD/API defined in the projects as your business requires. See a demonstration of this idea in the [blog post](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/) for example.  Also, indeed an operator A can use check resources of an Operator B. 

Also, if you are using OLM, for example, you can define that one operator depends on another one. See [https://github.com/operator-framework/operator-lifecycle-manager#de](https://github.com/operator-framework/operator-lifecycle-manager) 

Hi @gyliu513, 
Is the information provided attending your expectations? Could we close this one? 

Hi @joelanford @shawn-hurley, 
Would you like to supplement any additional information here?

**Comment by joelanford** [comment]
@gyliu513 Either option is reasonable. I think it depends on the complexity of c1, c2, and c3. If they are simple components that are tightly coupled, perhaps a single operator can handle all three.

However if one or more of them have complex reconciliation requirements (e.g. a database that requires backups and data migrations between versions) or they can be managed as standalone components (i.e. they have loose coupling), then separate operators for c1, c2, and c3 might make more sense. Then the a1 operator would only need to be concerned with the high-level abstractions exposed by the CRDs of c1, c2, and c3 operators.

**Comment by gyliu513** [comment]
Thanks @camilamacedo86 and @joelanford , this really helps!!
