### ISSUE TITLE
Cannot upgrade operator-sdk past 0.8.0 because of k8s.io/api

### ISSUE THREAD

**Issue by LouisPlisso** [operator-framework/operator-sdk#2303]
## Bug Report

**What did you do?**
Importing operator-sdk in go.mod running go get and it fails:
```
$ sudo rm -rf ~/go/pkg/mod
$ GOFLAGS="" go get
go: github.com/operator-framework/operator-sdk@v0.12.0 requires
        k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
$ cat go.mod
module github.com/10gen/ops-manager-kubernetes

require (
    github.com/google/uuid v1.1.1
    github.com/imdario/mergo v0.3.8
    github.com/operator-framework/operator-sdk v0.12.0
    github.com/pkg/errors v0.8.1
    github.com/spf13/cast v1.3.0
    github.com/stretchr/testify v1.4.0
    go.uber.org/zap v1.10.0
    k8s.io/api v0.0.0-20191114100237-2cd11237263f // 1.15.6
    k8s.io/apimachinery v0.0.0-20191004115701-31ade1b30762 // 1.15.6
    k8s.io/client-go v0.0.0-20191114101336-8cba805ad12d // 1.15.6
    k8s.io/code-generator v0.0.0-20190612205613-18da4a14b22b // 1.15.6
    sigs.k8s.io/controller-runtime v0.4.0
)

go 1.13
```

**What did you expect to see?**
No error on `go get`

**What did you see instead? Under which circumstances?**
Getting this error:
```
go: github.com/operator-framework/operator-sdk@v0.12.0 requires
        k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**Environment**
* operator-sdk version: any version starting at 0.9.0 with the introductions of go modules

reproduced in this bug report with `v0.12.0`

* go version:

`go version go1.13.4 darwin/amd64`

* Kubernetes version information:

`Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-11-27T18:11:35Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?
`go`

**Possible Solution**
I believe pinning versions in `go.mod` is not recommended and may be the cause of the bug as the version will not be recognised by other packages using go modules

**Additional context**
Kubernetes packages do not use go modules, and are attributed a fake version v0.0.0-date-hash
It seems to break the operator

**Comment by camilamacedo86** [comment]
Hi @LouisPlisso, 

Could you please follow up the steps in [upgrade guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md)? Note that if you are going from 0.8 to 0.12 you need to perform many changes in the code as well.

Regards the go.mod, I also would suggest you check the Memcached sample which is using the 0.12. See [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/memcached-operator/go.mod )

**Comment by LouisPlisso** [comment]
@camilamacedo86 thanks for the quick reply

I think pinning version (with the `replace` directive) is locking and preventing using a newer patch release of k8s (in my case 1.15.6 instead of 1.15.4)

I'll try using the upgrade guide and follow the example: thanks again
