### ISSUE TITLE
Document reporting of vulnerabilities

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/operator-sdk#2307]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I was considering the potential need of reporting vulnerabilities as we begin scanning our operator containers. I found some CVEs related to dbus, but they are considered mitigated by default configs by Red Hat. There are some other less critical ones that I haven't investigated yet.

**Describe the solution you'd like**
Perhaps just fill out the recommended github policy document?
https://github.com/operator-framework/operator-sdk/security/policy

**Comment by camilamacedo86** [comment]
@joelanford, @dmesser and @shawn-hurley. I think we need your help with.

**Comment by robszumski** [comment]
Hey @flickerfly, thanks for pointing out this gap and the new GitHub feature. We have some automation scripts that we use to care for repos and will get this added to all of them.

In the meantime, you can find contact instructions at https://access.redhat.com/security/team/contact. As part of our donation to the CNCF, we would align with their processes as well.
