### ISSUE TITLE
Use Go 1.13 error wrapping

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-sdk#2308]
Now that we've upgraded to Go 1.13, we should find instances in our code base of:
1. `errors.Wrap()`, `errors.Wrapf()`, and replace them with `fmt.Errorf()` with `%w`.
2. `fmt.Errorf()` calls that wrap an error, but use `%s` or `%v`, and replace them with `fmt.Errorf()` with `%w`
3. Any other uses of the `github.com/pkg/errors` package should be transitioned over to Go's standard library `errors` package, if possible.

All `fmt.Errorf()` calls that wrap an error should look like the following:
```go
fmt.Errorf("some context about my error: %w", err)
```

* `%w` should be preceded by `: ` (colon space)
* `%w` should not be in parentheses

**Comment by nrchakradhar** [comment]
@joelanford I can take a shot at this. This will be my first contribution and hence I may take some time. Please let me know if its fine.

**Comment by joelanford** [comment]
@nrchakradhar Awesome thanks! We would welcome this contribution!

**Comment by nrchakradhar** [comment]
@joelanford I hope I have understood the changes to be done. I have written a script that does the change for fmt.ErrorF. I will put some samples here tomorrow. If it looks fine, I will commit the changes.  Thanks for providing me an opportunity to contribute.

**Comment by nrchakradhar** [comment]
Following are some of the sample changes. If its fine, I will submit the changes for all files.
**About 69 files with about 180 changes will be modified.**
<table border=0 cellpadding=0 cellspacing=0 width=1000 style='border-collapse:
 collapse;table-layout:fixed;width:751pt'>
 <col width=33 style='mso-width-source:userset;mso-width-alt:1140;width:25pt'>
 <col width=106 style='mso-width-source:userset;mso-width-alt:3700;width:80pt'>
 <col width=861 style='mso-width-source:userset;mso-width-alt:30045;width:646pt'>
 <tr height=19 style='height:14.5pt'>
  <td height=19 width=33 style='height:14.5pt;width:25pt'>err</td>
  <td width=106 style='width:80pt'>other</td>
  <td width=861 style='width:646pt'>Changes done</td>
 </tr>
 <tr height=77 style='height:58.0pt'>
  <td height=77 style='height:58.0pt'>%v</td>
  <td>none</td>
  <td class=xl65 width=861 style='width:646pt'>operator-sdk\cmd\operator-sdk\printdeps\cmd.go<br>
    LINE:<span style='mso-spacerun:yes'>  </span>47<br>
    		return fmt.Errorf(&quot;print deps failed: %v&quot;, err)<br>
    		return fmt.ErrorF(&quot;print deps failed: %w&quot;, err)'</td>
 </tr>
 <tr height=77 style='height:58.0pt'>
  <td height=77 style='height:58.0pt'>%v</td>
  <td>%v, (%v), %s, %q</td>
  <td class=xl65 width=861 style='width:646pt'>operator-sdk\test\test-framework\test\e2e\memcached_test.go<br>
    LINE:<span style='mso-spacerun:yes'>  </span>91<br>
    		return fmt.Errorf(&quot;could not update memcached CR %q: %v&quot;, key,
  err)<br>
    		return fmt.ErrorF(&quot;could not update memcached CR %q: %w&quot;, key,
  err)</td>
 </tr>
 <tr height=77 style='height:58.0pt'>
  <td height=77 style='height:58.0pt'>(%v)</td>
  <td>none</td>
  <td class=xl65 width=861 style='width:646pt'>operator-sdk\cmd\operator-sdk\add\api.go<br>
    LINE:<span style='mso-spacerun:yes'>  </span>130<br>
    		return fmt.Errorf(&quot;api scaffold failed: (%v)&quot;, err)<br>
    		return fmt.ErrorF(&quot;api scaffold failed: %w&quot;, err)</td>
 </tr>
 <tr height=155 style='height:116.0pt'>
  <td height=155 style='height:116.0pt'>(%v)</td>
  <td>%v, %s, (%v)</td>
  <td class=xl65 width=861 style='width:646pt'>operator-sdk\cmd\operator-sdk\add\api.go<br>
    operator-sdk\cmd\operator-sdk\build\cmd.go<br>
    LINE:<span style='mso-spacerun:yes'>  </span>137<br>
    		return fmt.Errorf(&quot;failed to output build image %s: (%v)&quot;,
  image, err)<br>
    		return fmt.ErrorF(&quot;failed to output build image %s: %w&quot;, image,
  err)</td>
 </tr>
 <tr height=77 style='height:58.0pt'>
  <td height=77 style='height:58.0pt'>%s</td>
  <td>none</td>
  <td class=xl65 width=861 style='width:646pt'>operator-sdk\internal\scaffold\helm\chart.go<br>
    LINE:<span style='mso-spacerun:yes'>  </span>119<br>
    		return nil, nil, fmt.Errorf(&quot;failed to create helm-charts directory:
  %s&quot;, err)<br>
    		return nil, nil, fmt.ErrorF(&quot;failed to create helm-charts directory:
  %w&quot;, err)</td>
 </tr>
</table>
