### ISSUE TITLE
How can I enable multiple crd in helm operator ?

### ISSUE THREAD

**Issue by dongwangdw** [operator-framework/operator-sdk#2334]
I wan to use operator-sdk to create a helm operator.
And I got multiple crd to watch deploy?
I wonder how should I arrange the helm repos?

**Comment by dongwangdw** [comment]
`operator-sdk add ` may be used to add more crds and api.
But as the doc stated, this subcommands will not be supported anymore.

If these two subcommands will not be supported any more, how to add multiple api and crds ?

**Comment by joelanford** [comment]
@dongwangdw To have a helm-operator watch and reconcile two different CRDs for two different charts, there are a few things you need to do:
1. Copy/move your second chart into the `helm-charts` directory in your project root.
2. Add another entry in `watches.yaml` with the `group`, `version`, and `kind` of your CRD and the `chart` that should be reconciled. If you're using `v0.13.0`, the chart path is relative to the project root, so you would use `helm-charts/<chart-name>`
3. Run `operator-sdk add crd --api-version=<apiVersion> --kind=<kind>` (where `<apiVersion>` is `<group>/<version>` and `<kind>` is `<kind>` from your `watches.yaml` file).
4. Update `deploy/role.yaml` as necessary to give the operator permissions to reconcile the resources that the chart contains.

**Comment by dongwangdw** [comment]
Got you. Thanks.
Well, got another question.

If I add more CRDs which seems it will complicate the logic. Then there will be a comparison:
multiple CRDs in one operator VS multiple operators each with a single CRD. The later one seems make more sense from the design perspective.  Any comments?

**Comment by joelanford** [comment]
I think the only reason I would consider using multiple CRDs in a single Helm operator would be if there was a parent-child relationship between the charts. For example, you might have a parent chart for an `App` that deploys an `AppWebsite` and `AppDatabase`, where `AppWebsite` and `AppDatabase` each have their own separate charts. With this model, you can abstract details of what the website and database are and populate shared config once from the main `App` CR.

If you have two distinct charts that do not have this sort of relationship, it probably makes more sense to make separate operators for them.

**Comment by the-scott-hand** [comment]
Hi @joelanford, I was wondering if your above comment is still recommended now that 1.0.0 is out. I have users that are limited to their specific namespace, and I'd like to be able to just submit crs for the various components they need and have those components get installed into that namespace. I also have the possible use case of wanting to support multiple versions of those helm charts. I only intend to install these particular helm charts when I am making a user space. Does it make sense to make one mammoth helm operator with possibly 3-4 different(non parent child) charts, with possibly up to 3 supported versions for each chart? If I split them up into individual, would you recommend keeping the versions together in one operator, or make a new operator for each version?

Thanks!

**Comment by joelanford** [comment]
It doesn't _really_ matter from a technical standpoint. One single operator with multiple charts will work the same as several operators with individual charts.

The use case you describe sounds like a managed SaaS kind of thing? In that case, I can see an argument for grouping all of the charts in a single operator since it sounds like they're all always deployed together and it would be nice to be able to test and guarantee the deployment of the group of apps together.

**Comment by Kanaga13579** [comment]
> I think the only reason I would consider using multiple CRDs in a single Helm operator would be if there was a parent-child relationship between the charts. For example, you might have a parent chart for an `App` that deploys an `AppWebsite` and `AppDatabase`, where `AppWebsite` and `AppDatabase` each have their own separate charts. With this model, you can abstract details of what the website and database are and populate shared config once from the main `App` CR.
> 
> If you have two distinct charts that do not have this sort of relationship, it probably makes more sense to make separate operators for them.

Hi @joelanford , currently I am working on a similar use-case of deploying multiple CR using single helm operator. But I am little confused about establishing parent child relationship between these CR. It would be really great if you could share any project/github repo where this is actually implemented. 

Thanks!
