### ISSUE TITLE
Operator SDK does not support Helm v3 charts

### ISSUE THREAD

**Issue by tapairmax** [operator-framework/operator-sdk#2337]
## Bug Report

**What did you do?**
<my-helmv3-chart> is a Helm chart created thanks to the Helm v3 (Version:"v3.0.1") command.
The API version of such a chart is "apiVersion: v2" (in Chart.yaml file).

$ operator-sdk new <my-operator> --helm-chart <my-helmv3-chart> --type=helm
INFO[0000] Creating new Helm operator 'my-operator'.
Error: failed to create helm chart: failed to fetch chart: apiVersion 'v2' is not valid. The value must be "v1"ope

**What did you expect to see?**
The same result as the one produced when the chart has been created with a helm v2.x command line.

**What did you see instead? Under which circumstances?**
$ operator-sdk new <my-operator> --helm-chart <my-helmv3-chart> --type=helm
INFO[0000] Creating new Helm operator 'my-operator'.
**Error: failed to create helm chart: failed to fetch chart: apiVersion 'v2' is not valid**. The value must be "v1"

**Environment**
* operator-sdk version: "v0.12.0-68-g7a5bb22", commit: "7a5bb22a5c4709130c91b69a478a90e780792d65", go version: "go1.13.4 linux/amd64"
* go version: 1.13.4

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: MicroK8S

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**
As a temporary workaround, replacing the "v2" information by "v1" for "apiVersion" in the Chart.yaml seems do the trick. 

**Additional context**
NA

**Comment by joelanford** [comment]
@tapairmax Helm 3 support is not present in that commit. Please recompile from the latest `master`. If you still experience issues, let us know and we can re-open!

And thanks for testing this out! We'd love to be able to iron out any issues with the Helm 3 change before it makes it into a release.

**Comment by tapairmax** [comment]
Hi, I've upgraded the operator-sdk version up to the latest on the master branch and tested again.
Now, the Helmv3 Chart is no longer and issue, however when I run the Controller I see some errors like this:
```
$ operator-sdk up local
INFO[0000] Running the operator locally.
INFO[0000] Using namespace default.
{"level":"info","ts":1576571116.9778278,"logger":"cmd","msg":"Go Version: go1.13.4"}
{"level":"info","ts":1576571116.9778664,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1576571116.9778714,"logger":"cmd","msg":"Version of operator-sdk: v0.13.0+git"}
...
{"level":"error","ts":1576571818.116149,"logger":"helm.controller","msg":"**Failed to get release manager","namespace":"default","name":"example-orangecockroachdbinsecurek8schart","apiVersion":"charts.helm.k8s.io/v1alpha1","kind":"OrangeCockroachdbInsecureK8SChart","error":"failed to convert releases from v2 to v3: invalid label value: \"example-orangecockroachdbinsecurek8schart-3o49npdtlvxc95vwunmg2xoda\": must be no more than 63 characters","stacktrace":"github.com/go-logr/zapr.(*zapLogger)**.Error\n\t/home/cloud/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/helm/controller.HelmOperatorReconciler.Reconcile\n\t/home/cloud/go/src/github.com/operator-sdk/pkg/helm/controller/reconcile.go:82\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/cloud/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/cloud/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/cloud/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/cloud/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/cloud/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/cloud/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}

```

**Comment by ryandawsonuk** [comment]
@tapairmax I hit that too. Resolved it by changing the apiVersion in my Chart.yaml from v1 to v2.
