### ISSUE TITLE
The tutorial from getting started does not result in a deployment of CR

### ISSUE THREAD

**Issue by sgrzemski** [operator-framework/operator-sdk#2347]
## Bug Report

**What did you do?**
I have installed the operator-sdk version 0.13.0 from [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/install-operator-sdk.md). Then I followed [this getting started guide](https://github.com/operator-framework/getting-started/blob/master/README.md) but the generated code does not create a deployment composed of Custom Resources. Compared to [this example](https://github.com/operator-framework/operator-sdk/blob/master/example/memcached-operator/memcached_controller.go.tmpl) generated controller code does not have any deployment related functions or code. Only one pod is created.

**What did you expect to see?**
A deployment composed of CR.

**What did you see instead? Under which circumstances?**
Pods dependent on size.

**Environment**
* operator-sdk version: 0.13.0

* go version: 1.13.5

* Kubernetes version information: 

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
custom

* Are you writing your operator in ansible, helm, or go?
og
**Possible Solution**

**Additional context**

**Comment by mailzyok** [comment]
Same issue here.

**Comment by joelanford** [comment]
@sgrzemski The getting started guide's ["Add a New Controller" section](https://github.com/operator-framework/getting-started/blob/master/README.md#add-a-new-controller) has a step to replace the generated controller with the example controller code from the [example memcached-operator's controller](https://github.com/operator-framework/operator-sdk/blob/master/example/memcached-operator/memcached_controller.go.tmpl).

Did you miss that step?

@mailzyok That same step is also mentioned in the user guide in the SDK repo.

**Comment by joelanford** [comment]
@sgrzemski @mailzyok Were you able to resolve your issue? If not, we can re-open and keep troubleshooting!
