### ISSUE TITLE
How can I update the operator-sdk binary to the latest commit?

### ISSUE THREAD

**Issue by jianzhangbjz** [operator-framework/operator-sdk#2352]
## Question
Now, my operator-sdk version is `v0.12.0` and commit is `2445fcda834ca4b7cf0d6c38fba6317fb219b469`.
```console
mac:~ jianzhang$ operator-sdk version
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.4 darwin/amd64"
```
But, I find the latest commit is `79e6369540c60a4a75e7227a0cc71b3b436236f1` for the v0.12.0 version.
![image](https://user-images.githubusercontent.com/15416633/71468718-f1800a00-2801-11ea-87e4-66548d553b07.png)
My question is how to update it to this latest commit, not to `v0.13.0`?

```console
Error: operator-sdk 0.12.0 is already installed
To upgrade to 0.13.0, run `brew upgrade operator-sdk`

mac:~ jianzhang$ brew info operator-sdk
operator-sdk: stable 0.13.0 (bottled), HEAD
SDK for building Kubernetes applications
https://coreos.com/operators/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/operator-sdk.rb
==> Dependencies
Required: go ✘
==> Options
--HEAD
	Install HEAD version
```

And then, I reinstall it. But, the commit still is "2445fcda834ca4b7cf0d6c38fba6317fb219b469". 
```console
mac:~ jianzhang$ RELEASE_VERSION=v0.12.0
mac:~ jianzhang$ curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-apple-darwin
mac:~ jianzhang$ chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-apple-darwin && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-apple-darwin /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-apple-darwin

mac:~ jianzhang$ operator-sdk version
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.3 darwin/amd64"
```
Is it as expected? We don't plan to release the latest commit in the v0.12.0 for release-4.3?

**Comment by joelanford** [comment]
@jianzhangbjz the `release-4.3` branch in this repository is managed by the OpenShift bot. It tracked `master` until the larger OpenShift 4.3 release was made, and has nothing to do with our upstream release cycle. The commit for `v0.12.0` is `2445fcda834ca4b7cf0d6c38fba6317fb219b469`.

We probably need to look into disabling the bot's release branch management since this is pretty confusing.

**Comment by jianzhangbjz** [comment]
@joelanford Yeah, it's very confusing. Ok, got it, thanks!
