### ISSUE TITLE
fact gathering still enabled

### ISSUE THREAD

**Issue by kfox1111** [operator-framework/operator-sdk#2358]
**What did you do?**
facts are being gathered. A patch seems to have merged to default to no fact gathering. Not sure why facts are being gathered.

**What did you expect to see?**
no facts being gathered

**What did you see instead? Under which circumstances?**
Operator runs slower as its gathering facts

**Environment**
* operator-sdk version:
operator-sdk version: "v0.13.0", commit: "1af9c95bb51420c55a7f7f2b7fabebda24451276", go version: "go1.13.3 linux/amd64"

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

minikube

* Are you writing your operator in ansible, helm, or go?

ansible

**Comment by fabianvf** [comment]
Are you using a playbook or a role? We may need to set additional options on ansible-runner when running a role directly

**Comment by Frankkkkk** [comment]
Hi,
We have the same problem running roles. Didn't had the time to diagnose it further
Cheers

**Comment by corentin1002** [comment]
Hi, just made a few tests on my side.

I have a role with `gather_facts: no` but it still gathering facts.

I also tried to change the following envvars without any success, my role still gathering facts at every run :
* `ANSIBLE_GATHERING` set to `explicit`
* `DEFAULT_GATHERING` set to `explicit`

**Comment by fabianvf** [comment]
hmm, I bet you the setting is being lost when we run `ansible-runner`, we probably need to make sure that these variables are set by runner when it actually executes the role. Perhaps we should find all `ANSIBLE_` prefixed variables set in our env and ensure they are set in the runner env file https://github.com/operator-framework/operator-sdk/blob/master/pkg/ansible/runner/runner.go#L181-L184

**Comment by corentin1002** [comment]
Hi, 

I have added the environment vars when building my docker image :
```
FROM quay.io/operator-framework/ansible-operator:v0.14.1

ENV TEST_VAR this_is_my_test_var
ENV DEFAULT_GATHERING explicit
ENV ANSIBLE_GATHERING explicit

COPY watches.yaml ${HOME}/watches.yaml

COPY roles/ ${HOME}/roles/
```

Then I have this in one of my roles :
```
- name: my test var
  debug:
    msg: "{{ lookup('env','TEST_VAR') }}"

- name: DEFAULT_GATHERING
  debug:
    msg: "{{ lookup('env','DEFAULT_GATHERING') }}"

- name: ANSIBLE_GATHERING
  debug:
    msg: "{{ lookup('env','ANSIBLE_GATHERING') }}"
```
this give me the following log :
```
TASK [Gathering Facts] *********************************************************
ok: [localhost]
META: ran handlers

TASK [lamp : my test var] ******************************************************
task path: /opt/ansible/roles/myrole/tasks/main.yml:2
ok: [localhost] => {
    "msg": "this_is_my_test_var"
}

TASK [lamp : DEFAULT_GATHERING] ************************************************
task path: /opt/ansible/roles/myrole/tasks/main.yml:6
ok: [localhost] => {
    "msg": "explicit"
}

TASK [lamp : ANSIBLE_GATHERING] ************************************************
task path: /opt/ansible/roles/myrole/tasks/main.yml:10

    "msg": "explicit"
}
ok: [localhost] => {
    "msg": "explicit"
}
```

Of course, if I remove my env vars from my dockerfile, I don't have them in my debug.

**Comment by fabianvf** [comment]
Awesome information, thanks for that debugging. In that case this seems much more bizarre, perhaps we need to actually pass an option to runner directly

**Comment by fabianvf** [comment]
Runner takes the `--role-skip-facts` variable as a toggle for fact gathering, but there doesn't seem to be a way to make it work like `explicit` does.

**Comment by corentin1002** [comment]
Well, I'm looking for how to specify this option, but the ansible container is using the `ansible` command (and not `ansible-runner` command) that do not accept `--role-skip-facts`.
So maybe I could specify this option into the `watches.yaml`, but i can't find, in the doc, how to do. https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md#watches-file

**Comment by fabianvf** [comment]
I don't think there is a way to specify the flag currently, the `ansible-runner` binary is being invoked by the go code and we would need to add this functionality there. The ansible sidecar container is just aggregating logs, it doesn't actually have anything to do with the execution of the playbook/role.

**Comment by camilamacedo86** [comment]
So, it is not a bug at all. It would be an RFE, Am I right @fabianvf?

**Comment by geerlingguy** [comment]
As I'm working on debugging Ansible performance with operators, I'm finding that fact gathering, at least for simple playbooks, adds 30% overhead to each reconciliation for a given CR.

I think we should disable fact gathering by default for role-based operators, and ideally offer a setting/configuration value so people can enable it if needed (the use case for that is very slim IMHO unless we start injecting some extra facts specific to the operator and cluster).
