### ISSUE TITLE
[query]: Helm-operator and configmap update

### ISSUE THREAD

**Issue by mabukar** [operator-framework/operator-sdk#2363]
Hello!

What would be the right way to manage (update/delete) the configmap of installed application releases via Helm operator? The configuration is mounted to volumes and the files are visible in the running pod.

I can get the configmap with "_kubectl get configmap ..._" but unable to modify it with "_kubectl create configmap appconfig --from-file=/tmp/config.json -o json --dry-run | kubectl apply -f -_". The command is executed successfully but the content of the configmap is not changed.

The configmap update works fine if I install the application release manually using "_helm install ..._". The application pod is watching config file via iNotify and properly reacts to config changes.

Or is this even possible with the helm-operator? Am I required to use the GO operator?

Thanks!

**Comment by joelanford** [comment]
@mabukar Is the configmap created as part of the Helm release? If so, the helm-operator will prevent manual changes to the configmap. Instead it will always ensure that the release manifest and deployed resources align with the CR that defined them. This is an intentional design decision of the helm operator, which makes Helm declarative rather than imperative

One way to handle this would be to plumb CR values through to your configmap and then update those plumbed CR values when you need to change your configmap.

**Comment by mabukar** [comment]
@joelanford, thanks a lot. 

Yes, the configmap is created as part of the Helm release. Your explanation makes sense.

Could you please elaborate a bit about the update process you've proposed (preferably with some example commands)? Should I generate a Helm chart with updated configmap values and then re-apply/update the CR (for instance: _kubectl -f apply deploy/cr/my_cr.yaml_ or similar command), or is there a possibility to update the configmap without re-generating the Helm charts?

Essentially what I want to do is just to update the configmap without restarting the app pod ... since my application pod has the logic to watch and re-act to configmap changes on-the-fly.

Thanks once again in advance!

**Comment by joelanford** [comment]
@mabukar Sure!

So basically what I'm suggesting is that your configmap contents should be driven by your CR. The goal is for the CR to fully abstract away all the underlying details of the chart such that users interacting with your operator via CRs don't need any awareness of the implementation details of the underlying chart's resources (that's the role of the operator). They shouldn't even have to know that your operator is based on a Helm chart.

The commands I have in mind are:
1. Deploy operator
2. `kubectl apply -f ./my_cr.yaml` to install the release
3. Edit `./my_cr.yaml` and change a value that is used to template the configmap
4. `kubectl apply -f ./my_cr.yaml` to upgrade the release.

Note that in 4, the Helm operator (and Helm itself, really) won't touch resources that don't change. So you should be able to continue applying CR changes that only affect the contents of the configmap, and you should see that other unaffected resources are left unchanged in the cluster.

**Comment by joelanford** [comment]
> Should I generate a Helm chart with updated configmap values and then re-apply/update the CR

Your configmap template in your chart should have configurable values templated out as chart values such that they can be configured by the CR. For example:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "my-chart.fullname" . }}
data:
  value1: {{ .Values.value1 }}
  value2: {{ .Values.value2 }}
```

**Comment by mabukar** [comment]
@joelanford, thanks for the instructions, I will give a try. My configmap template reads config values from a local file (not variables) ... so I would need to figure out how to modify my CR in order to be able to dynamically change the configmap values.

For example, this is how the configmap roughly looks like:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: appconfig
data:
{{- (.Files.Glob "config/*").AsConfig nindent 2 }}
```

```
# kubectl describe configmap appconfig
Name:         appconfig
Namespace:    default
Labels:       <none>
Annotations:  <none>

Data
====
cfg.json:
----
{
    "local": {
        "host": ":8080"
    },
    "logger": {
        "level": 3
    },
    "db": {
        "host": "localhost",
        "port": 6379
    }
}
```

**Comment by joelanford** [comment]
Since your configmap files are part of your chart that gets built into the operator, those effectively become static, non-overridable configs. What you could do is have a `values.yaml` that defines the defaults (basically what you have in your `config/*` files). And then update your configmap template to use them. 

Maybe something like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: appconfig
data:
  cfg.json: {{ .Values.config | toJson }}
```

```yaml
apiVersion: example.com/v1
kind: MyCR
metadata:
  name: example-app
spec:
  config:
    local:
      host: ":8080"
    logger:
      level: 3
    db:
      host: localhost
      port: 6379
```

**Comment by joelanford** [comment]
@mabukar I'm going to close this issue since I think the original question has been answered, but I can definitely keep helping if you run into more questions about how to get this working!

**Comment by mabukar** [comment]
@joelanford, Sure, I really appreciate your support.

**Comment by mabukar** [comment]
@joelanford, one more question related to Helm operators. Would it be possible to attach own custom hooks, that will be invoked when installing or uninstalling releases via CR? Or what would be the best way to watch such application pod actions (created/deleted)?

This is unrelated to original question, but I can open a new ticket if that is more convenient.

Thanks!

**Comment by mabukar** [comment]
@joelanford, FYI: I have tried out the solution you proposed and it works perfectly! Thanks a lot.
