### ISSUE TITLE
How to keep CR history for rollback purposes ?

### ISSUE THREAD

**Issue by aelbarkani** [operator-framework/operator-sdk#2364]
### Question

Is there an easy way to keep revisions of CRs in order to be able to rollback to a specific revision, the same way we have revisions of deployments,statefulsets, daemonsets or helm releases ? If yes, are there any guides/docs about it ?

Thanks in advance !

**Comment by camilamacedo86** [comment]
Hi @aelbarkani, 

When we apply a new version of the CR the k8s API will add annotations with previous data in the resource. However, I am afraid that it may not attend your needs. If you are using the Go language to develop your operators may you could, for example, define default values and ensure that the CR's will always be update with them in the reconcile. 

Could give more context over your needs and what kind of language you are using to develop the operators for we see if we can help you more assertively?

**Comment by aelbarkani** [comment]
Thanks @camilamacedo86  for your answer. We are using Ansible flavor of operator-sdk to create our operators.

I was targeting something that makes CRs compatible with kubectl rollout commands, but it seems that actually those commands accept only deployments, statefulsets and daemonsets.

````
kubectl rollout --help
Manage the rollout of a resource.
  
 Valid resource types include:

  *  deployments
  *  daemonsets
  *  statefulsets
`
```

**Comment by camilamacedo86** [comment]
Hi @aelbarkani, 

Thank you for your reply. Could you please clarify when would make sense in the operator use a feature to rollout the CR? I mean, what scenario are you trying to solve? What need are you trying to address?

**Comment by camilamacedo86** [comment]
Hi @aelbarkani, 

I am closing this one since we did not receive your reply with the info requested. So, I guessing that you solved your problem but if not let us know and we can re-open to continue troubleshooting!
