### ISSUE TITLE
[Query]: Documentation about Hybrid operators!

### ISSUE THREAD

**Issue by mabukar** [operator-framework/operator-sdk#2370]
Hello!

Are there any documentations or user guides available for Hybrid operators? For instance, how operator developers can extend the functions of Helm operators via Hybrid operator? 

Thanks!

**Comment by bharathi-tenneti** [comment]
@mabukar  As of now, this is something we have in our back log.

**Comment by camilamacedo86** [comment]
Hi @mabukar, 

I just would like to supplement that for the specific question as @bharathi-tenneti described, I am afraid that we have not. 

However, it has guide docs for Ansible and Helm operator and many features and usages documented. See the links in the  [samples](https://github.com/operator-framework/operator-sdk-samples). And then, you also can check all docs in this repo here: https://github.com/operator-framework/operator-sdk/tree/master/doc. Please, feel free to collab with them as well. 

I hope that it helps you as well and please let us know if has anything else that we can do to help with or if we can close this issue.

**Comment by mabukar** [comment]
Hello @bharathi-tenneti and @camilamacedo86, Thanks a lot for the info and yes, we close this for now.
