### ISSUE TITLE
Operator removed all the labels and annotations added to operator service 

### ISSUE THREAD

**Issue by swapnil-zendesk** [operator-framework/operator-sdk#2383]
## Bug Report
I am trying to add labels to the service exposed by the operator. The operator removes labels and annotations from service. We are trying to create a service mesh that would require marking all services with a project and team label.

**What did you do?**
Tried creating service through yaml file.
`---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: xyz-operator
    project: xyz-operator
    role: operator
    team: foundation
  name: xyz-operator
  namespace: fdn-analytics
spec:
  ports:
    - name: metrics
      port: 8383
      protocol: TCP
      targetPort: 8383
  selector:
    name: xyz-operator
    project: xyz-operator
    role: operator
  sessionAffinity: None
  type: ClusterIP`

**What did you expect to see?**
Service used by the operator to use the labels added.

**What did you see instead? Under which circumstances?**
The labels were removed when the operator started to init the service

**Environment**
* operator-sdk version:
 v0.7.0+git

* go version: 
1.12.12

* Kubernetes version information:
v1.16.3

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?
go

**Possible Solution**
https://github.com/operator-framework/operator-sdk/blob/master/pkg/metrics/metrics.go#L84
copy labels here as well.

**Comment by camilamacedo86** [comment]
Hi @swapnil-zendesk,

If you are writing your operator in Go then, I'd like to say that you need to add the labels in the code that gen the resources. See in the Memcached sample [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/pkg/controller/memcached/memcached_controller.go#L235) the labels added in the Service. 

Also, I'd like to say that the go version `1.12.12` is not compatible with the SDK version `v0.7.0+git` and recommend you use the latest ones which are currently: 1.13+ for go and 0.13 for SDK. 

I'd like also to share and recommend to you check the article [Getting started with Golang Operators by using Operator SDK](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/)

I believe that the above information sorted out your question. Please, let us know if we can close this one.

**Comment by swapnil-zendesk** [comment]
Hello @camilamacedo86 ,
Thank you for replying.
It might be confusing but the service I am referring to is the one operator used to communicate with other service/ pods.

`swapnil@jumpbox2:~$ kubectl get all -n namespace
NAME                                          READY   STATUS    RESTARTS   AGE
pod/xyz-operator-74b9c548c4-dqtlq   1/1     Running   0          42m

NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/xyz-operator   ClusterIP   XX.XX.XX.XX   <none>        8383/TCP   109m

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/xyz-operator   1/1     1            1           109m

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/xyz-operator-74b9c548c4   1         1         1       42m
replicaset.apps/xyz-operator-c5755db87    0         0         0       62m`

`service/xyz-operator` (is missing labels), which is created by the operator framework to expose metrics.

**Comment by camilamacedo86** [comment]
Hi @swapnil-zendesk, 

The only services that are created by default in the scaffold, I mean, that the developer did not implemented on it are to allow to expose the operator metrics. See [here](https://github.com/operator-framework/operator-sdk-samples/tree/master/go/memcached-operator#installing) the Memcached sample. 

**Example**

```
NAME                                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/example-memcached            ClusterIP   10.108.124.47   <none>        11211/TCP           63s
service/memcached-operator-metrics   ClusterIP   10.108.67.82    <none>        8383/TCP,8686/TCP   66s
```

They are implemented in the main.go [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/cmd/manager/main.go#L118-L144). See here the implementation of the func [CreateMetricsService](https://github.com/operator-framework/operator-sdk/blob/6d51fa1760b8905acd3f855f95f1f7c11d7626d5/pkg/metrics/metrics.go#L44). And [here](https://github.com/operator-framework/operator-sdk/blob/6d51fa1760b8905acd3f855f95f1f7c11d7626d5/pkg/metrics/metrics.go#L110) the labels added.  

So, if you would like to update their labels it needs to be done programmatically. You can change the default implementation for your own. However, could you let us know why it is important to you change its labels? I mean, could you let us know what is the scenario/business requirement and what you are trying to solve?

**Comment by swapnil-zendesk** [comment]
Hi @camilamacedo86,

Thanks for the response and suggestions.

In order to do this programmatically, we would have to fork the repository and maintain our own library. We would like to avoid that if possible. So the business reason for this is because we are enforced by our DevOps team to have the labels defined at creation time. This is for ease of managing numerous pods that we have at Zendesk. 

Would it possible for this to be a feature request for the metrics service to inherit the labels from the implemented service(xyz-operator)?

Thanks!

**Comment by camilamacedo86** [comment]
Hi @swapnil-zendesk, 

Following some comments inline. 

> In order to do this programmatically, we would have to fork the repository and maintain our own library. 
No. You can do the implementation of the ServiceMonitor in your own project. 

> Would it possible for this to be a feature request for the metrics service to inherit the labels from the implemented service(xyz-operator)?

Could you please open a new issue with the RFE?
Please, let us know why it is important for you to be able to define the labels on it. What problem/need you will solve with. Also, please add the link for this one as a reference. 

In this way, since is your questions are sorted out I am closing this one. 
Thank you for your collaboration with.
