### ISSUE TITLE
Fails to create a new operator using helm chart

### ISSUE THREAD

**Issue by alexcpn** [operator-framework/operator-sdk#2385]
## Bug Report

**What did you do?**
Was trying to generate an Helm operator with existing Helm chart. 
This is similar to #1993
I ran the same command as in #1993 and got this error

`~/coding/k8s$ operator-sdk new kubedb2-helm-operator   --type=helm   --helm-chart=kubedb   --helm-chart-repo=https://raw.githubusercontent.com/appscode/charts/master/stable/ --helm-chart-version=0.12.0 --verbose
DEBU[0000] Debug logging is set                         
INFO[0000] Creating new Helm operator 'kubedb2-helm-operator'. 
Error: failed to create helm chart: failed to fetch chart: failed to load repositories file /home/alex/.helm/repository/repositories.yaml (you might need to run `helm init --client-only` to create and initialize it)`

Note - There is no helm init in hem version 3. https://stackoverflow.com/questions/59261340/helm-init-has-been-removed-in-version-3

**Environment**
* operator-sdk version:

operator-sdk version: "v0.13.0", commit: "1af9c95bb51420c55a7f7f2b7fabebda24451276", go version: "go1.13.3 linux/amd64"

* go version:

go version go1.13.5 linux/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
Minikube

* Are you writing your operator in ansible, helm, or go?
HELM

**Possible Solution**

**Additional context**

**Comment by joelanford** [comment]
@alexcpn SDK v0.13.0 does not include the most recent Helm v3 changes, which are on `master`, but not yet released. We'll be making a release of SDK either today or early next week, so I would encourage you to retry from a build of the current master or once we release v0.14.0.

If you run into the same issue with either of those, we can definitely re-open this issue and help you figure out what's going on.

**Comment by alexcpn** [comment]
Works in release 14.0
