### ISSUE TITLE
Rework molecule test scenarios for Ansible-based operators

### ISSUE THREAD

**Issue by geerlingguy** [operator-framework/operator-sdk#2388]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Yes and no—right now there are two scenarios that are shipped with the operator SDK when you build an Ansible-based operator, e.g.:

    operator-sdk new memcached-operator --api-version=cache.example.com/v1alpha1 --kind=Memcached --type=ansible

The two scenarios are named `test-cluster` and `test-local`.

The `test-local` scenario seems to work well using the Kind docker-based single-node Kubernetes cluster for CI and basic local operator testing and debugging.

The `test-cluster` scenario kinda-sorta works with any generic Kubernetes cluster (though I had to modify it quite a bit to get it to work with any of my operators, and it assumes you've done a lot of manual labor to build and make available your operator).

**Describe the solution you'd like**

I propose the following:

  1. Rename `test-local` to `test-kind` (to be more specific that this scenario makes use of Kind).
  2. Rename `test-cluster` to `test-minikube` (to make it so the scenario can be made to work much more easily with a specific tool for more thorough local testing and debugging).
  3. Abstract some of the shared setup/logic into the `default` scenario to reduce code duplication.
  4. Rework the [Ansible Operator SDK Testing Guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/testing_guide.md) to account for any changes.

We could still try to support a molecule scenario that is generic and applies to any Kubernetes cluster, but I think—especially for the purposes of a test/development framework for the operators—that will be an unmaintainable approach.

**Examples**

I have already been working on these proposed changes in a few of my operators—see the `molecule` subdirectories in a few of my operators, like:

  - https://github.com/geerlingguy/drupal-operator
  - https://github.com/geerlingguy/mariadb-operator
  - https://github.com/geerlingguy/tower-operator

**Comment by geerlingguy** [comment]
cc @fabianvf and @leifmadsen — I know I've discussed this with both of you and would like to hear your thoughts before I start more work down this path.

**Comment by camilamacedo86** [comment]
@fabianvf shows that you have more context to check/help with this one. Could you help us with?

**Comment by leifmadsen** [comment]
@geerlingguy this sounds like an excellent approach. I've looked at using molecule a bit for testing my own Ansible Operators, but never really made it very far because it's not clear how they should even really be used. Doing some of this reword to make it more clear what the `test` scenarios are for and what they should operate against would provide better direction.

I'd also like to see a `test-crc` setup but that could probably either be worked into the proposed `test-minikube` or at least wouldn't deviate too much from it.

**Comment by fabianvf** [comment]
@geerlingguy I've just reworked the scenarios a bit, the `test-cluster`scenario was replaced with a `cluster` scenario that works generically as long as the operator image is available, and the `test-local` scenario just sets up the cluster, makes the image available, and then runs the cluster scenario. I don't think it would be difficult to extend that pattern to account for other cluster technologies

**Comment by camilamacedo86** [comment]
Hi @fabianvf, @asmacdo, 

Is not this task addressed with the new layout ?

**Comment by camilamacedo86** [comment]
Hi @geerlingguy,

It shows addressed already for 1.0+ layout.  Could you please confirm and let us know? If not, what do you would like to change based on the molecule for 1.0+ layout?

**Comment by geerlingguy** [comment]
@camilamacedo86 - Ah, this one is a bit outdated, I think. I think it can be closed now.
