### ISSUE TITLE
Recommended way to run Ansible Operator as a deployment-config rather than a deployment in Openshift

### ISSUE THREAD

**Issue by caggles** [operator-framework/operator-sdk#2400]
## Type of question

Best practices/feature implementation

## Question

**What did you do?**
I updated the deployment definition for the operator to a deployment-config template.

**What did you expect to see?**
Basically the same behaviour as with the deployment definition - the operator pods start as expected, but now with more freedom to redeploy more easily.

**What did you see instead? Under which circumstances?**
I now get the following error message:

`Error: failed to create or get service for metrics: services "artifactory-operator" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>`

I've already checked to make sure that the operator service account (also called artifactory-operator) has update privileges on deployments/finalizers (and deploymentconfigs/finalizers)

**Environment**
* operator-sdk version: v0.8.1

* Kubernetes version information: Openshift 3.11

**Additional context**

This issue makes me wonder if there's another way to do this that I'm missing. The core issue is that I'd like to make it so that the operator redeploys when there's an image update, rather than requiring a new image tag and manual redeployment every time.

**Comment by camilamacedo86** [comment]
Hi @caggles, 

 First at all, I'd like to recommend you use the latest version of SDK. Also, note that OCP 3.11 uses an old version of k8s API which is no longer compatible with any SDK version upper 0.9+.

The error faced is because it is missing the permissions in the role.yaml file to create the metrics. See the [doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/faq.md#i-keep-seeing-errors-like-failed-to-create-metrics-service-how-do-i-fix-this).

I am closing this one as sorted out. However, please feel free to re-open if you see that something still required regards this question/issue.

**Comment by caggles** [comment]
Hi @camilamacedo86 - thanks for you response!

You're right that I'm not using the operator.yml file provided - that's a deployment, so I took that and updated it to a deployment-config template. This is because I noticed that using the deployment prevented the operator from updating when a new operator image was built and uploaded to the registry. Every time the image updated, I had to manually update operator.yml to include a new image tag, otherwise the operator would continue using an older image. This was true regardless of how imagePullPolicy was set.

If there's a way to fix that without updating the deployment to a deployment-config, that would also be acceptable, but it's my understanding that deployment-configs are best practice in openshift anyway, so I'd prefer if I could get the deployment-config to work.

The thing that confuses me is that I do have a version of the operator running the provided steps in Getting Started - it only breaks when I try to update it to a deployment config template. So I don't think it's the operator definition itself that is the problem - I must be missing some other privilege that's required for a deployment-config that isn't necessary with a deployment.

**Comment by estroz** [comment]
@caggles are you still seeing issues with your `DeploymentConfig`? Would it be possible to have a general `example.com/org/name:prod` tag for your operator image, such that image updates will pull a new image under the same tag?

**Comment by camilamacedo86** [comment]
Hi @caggles, 

If the following information does not help you with, I'd like to ask for you provide the steps used to deploy it using `deployment-config `. I mean, I would ask for you provide the files used to deploy the operator that we're customized by you for we are able to reproduce the scenario and have further information. 

Regards the issue `Error: failed to create or get service for metrics:` the legacy layout (before 1.0-alpha) requires permission to create the resources required to export the metrics.  So, shows that your customization is missing the required permissions. I'd recommend you create a project with the same sdk version used and check the roles.yaml file to see if you can figure out that.

**Comment by caggles** [comment]
Updating to the OCP4 version seems to have dealt with the issue I was having!
