### ISSUE TITLE
Unable to set empty "Environment" property in the Operator YAML file

### ISSUE THREAD

**Issue by rareddy** [operator-framework/operator-sdk#2401]
## Bug Report

**Environment**
* operator-sdk version: v0.11.0

**What did you do?**
Unable to set empty "Environment" property in the Operator YAML file like
```
env:
  - name: AB_JOLOKIA_HTTPS
build:
```
Which ends up in an error like
```
The VirtualDatabase "dv-odata" is invalid: []: Invalid value: map[string]interface {}{ "env":[]interface 
{}{map[string]interface {}{"name":"AB_JOLOKIA_PASSWORD", "value":"jolokia"}, map[string]interface {}{"name":"AB_JOLOKIA_PASSWORD_RANDOM"}, map[string]interface {}
{"name":"AB_JOLOKIA_HTTPS"}}, "replicas":1}, "apiVersion":"teiid.io/v1alpha1", "kind":"VirtualDatabase"}: validation failure list:
must validate one and only one schema (oneOf)
spec.env.value in body is required
```

Attempting to use a yaml empty string causes the crd to not even be picked up for deployment by the operator:

```
env:
  - name: AB_JOLOKIA_HTTPS
    value: ''
build:
...
```
**What did you expect to see?**
Empty values should be allowed? There is a default property set on the image, I am trying to remove it using this.

**Environment**
* operator-sdk version: 11.0
* go version: go version go1.13.5 linux/amd64
* Kubernetes version information: kubernetes v1.11.0+d4cacc0

**Comment by hasbro17** [comment]
@rareddy Can you please share the full the CRD manifest with the validation block defined, and the full CR manifest as well.
Also the `pkg/apis/.../..._types.go` file that define your CRD spec and validation as well.
 
I think this is a case of marking a field as nullable which is possible with structural CRDs but since you're on k8s 1.11 I'll have to double check how we do it for that case.

**Comment by rareddy** [comment]
@hasbro17 here is the reference to my project https://github.com/teiid/teiid-operator
CRD - https://github.com/teiid/teiid-operator/blob/master/deploy/crds/virtualdatabase.crd.yaml
CR - https://github.com/teiid/teiid-operator/blob/master/deploy/crs/vdb_from_ddl.yaml
types - https://github.com/teiid/teiid-operator/blob/master/pkg/apis/vdb/v1alpha1/virtualdatabase_types.go

**Comment by hasbro17** [comment]
@rareddy Sorry I forgot to follow up on this. Do you still have this issue?
And are you able to test against a more recent version of k8s > 1.11.x?

**Comment by rareddy** [comment]
I can not recreate anymore in newer version, sure you can close this
