### ISSUE TITLE
Operator generated service account does not have permission in policy API - fails to deploy POD

### ISSUE THREAD

**Issue by alexcpn** [operator-framework/operator-sdk#2405]
## Bug Report

**What did you do?**
Followed the documentation to create a helm based operator

**What did you expect to see?**
After deploying the CR expected the POD to start.

**What did you see instead? Under which circumstances?**
POD did not get created. In the Operator pod log saw this error

```
{"level":"error","ts":1578915836.236557,"logger":"helm.controller","msg":"Release failed","namespace":"default","name":"example-cassandra","apiVersion":"charts.helm.k8s.io/v1alpha1","kind":"Cassandra","release":"example-cassandra","error":"failed to install release: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: poddisruptionbudgets.policy \"example-cassandra-headless\" is forbidden: User \"system:serviceaccount:default:cassandra-helm-operator\" cannot get resource \"poddisruptionbudgets\" in API group \"policy\" in the namespace \"default\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go
```
Tested the permission for service account as was in the logs

```
 kubectl  --insecure-skip-tls-verify  --kubeconfig ~/keys/ee1-kubeconfig.config auth can-i get poddisruptionbudgets.policy --as=system:serviceaccount:default:cassandra-helm-operator
no
```
I then added this to role.yaml

```
- apiGroups:
  - policy
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```
Applied it and tested

```
 kubectl  --insecure-skip-tls-verify  --kubeconfig ~/keys/ee1-kubeconfig.config apply -f deploy/role.yaml 
role.rbac.authorization.k8s.io/cassandra-helm-operator configured

kubectl  --insecure-skip-tls-verify  --kubeconfig ~/keys/ee1-kubeconfig.config auth can-i get poddisruptionbudgets.policy --as=system:serviceaccount:default:cassandra-helm-operator
**yes**

```
Then Applied the CR again  and the POD came up

```
alex@drone-OMEN:~/coding/k8s/cassandra-helm-operator$ kubectl  --insecure-skip-tls-verify  --kubeconfig ~/keys/ee1-kubeconfig.config get pods
NAME                                       READY   STATUS    RESTARTS   AGE
cassandra-helm-operator-7f765ff4cb-vj8mv   1/1     Running   0          18h
example-cassandra-0                        0/1     Pending   0          47m
```

**Environment**
* operator-sdk version:

operator-sdk version: "v0.14.0", commit: "4fb185b9d45682473b4951c9788f845ba2fa5b12", go version: "go1.13.3 linux/amd64"

* go version:
go version go1.12.13 linux/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?
HELM 
**Possible Solution**

Add the Policy API group also to generated role.yaml ?

**Additional context**
None

**Comment by joelanford** [comment]
@alexcpn The SDK can automatically create a default role for your operator, but it is based only on the default values of the chart. If your chart has extra resources enabled via Helm values, it is necessary for the operator developer to define the necessary roles manually. You should have seen a warning like this when creating the project:

```console
WARN[0001] The RBAC rules generated in deploy/role.yaml are based on the chart's default manifest. Some rules may be missing for resources that are only enabled with custom values, and some existing rules may be overly broad. Double check the rules generated in deploy/role.yaml to ensure they meet the operator's permission requirements.
```

**Comment by alexcpn** [comment]
@joelanford thanks for the clarification. I did not notice the warning maybe. Also tested with the sample https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md and it works as expected
