### ISSUE TITLE
Better document custom-api-import in user guide

### ISSUE THREAD

**Issue by michaelgugino** [operator-framework/operator-sdk#2415]
## Feature Request

**Is your feature request related to a problem? Please describe.**

When using the operator-sdk to generate a new operator, it's not obvious how one should reconcile a pre-existing type.

**Describe the solution you'd like**

It appears you can reconcile existing core types, eg Secrets, as such:
```
operator-sdk add controller --api-version=core.k8s.io/v1 --kind=Secret --custom-api-import k8s.io/api/core/v1
```

Previously I was unable to sort this out, but it does seem possible to do what I want (reconcile a core type) without a bunch of modifications.

**Comment by camilamacedo86** [comment]
HI @michaelgugino, 

When you do:

> operator-sdk add controller --api-version=core.k8s.io/v1 --kind=Secret --custom-api-import k8s.io/api/core/v1
 
You will create your own lib `core.k8s.io/v1` with your own Kind Secret. It will not change and/or update and/or overwide the K8S API at all.

I'd like to share with you the blog [Getting started with Golang Operators by using Operator SDK](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/) which I think that can help you have a better idea over this commands and ideas. 

I hope that it helps you and I think that is all sorted out here. So, I am closing this one. However, please feel free to re-open if you think that something still required to be addressed in this issue.

**Comment by michaelgugino** [comment]
Please re-open.  You don't seem to be understanding what I want.

I just want an operator to reconcile secrets (or any pre-existing type that I don't define a CRD for).

I suggest you try the command I pasted and look at the output.  The behavior is desired, we should document the use-case that I'm referring to.

**Comment by camilamacedo86** [comment]
HI @michaelgugino,

> I just want an operator to reconcile secrets (or any pre-existing type that I don't define a CRD for).
I'd like to suggest you read the following blog post. It is small and will help you get that. See that it has some examples as well. 

- [Getting started with Golang Operators by using Operator SDK](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/) 

Basically you will create your API and KIND + Controller and inside of your reconcile you can GET?CREATE/READ/UPDATE secrets like any other Kind of resource from K8S API, and/or your own APIs as any third-party API. 

> I suggest you try the command I posted and look at the output. The behavior is desired, we should document the use-case that I'm referring to.

<img width="1563" alt="Screenshot 2020-01-16 at 16 48 44" src="https://user-images.githubusercontent.com/7708031/72544918-148d5f00-3880-11ea-8a23-a1f59a246e3a.png">

The command will scaffold the files with the data inputted. Could you please described further what do you think that should be documented and why?

**Comment by michaelgugino** [comment]
> I'd NOT recommend you use the K8S api domain and kind

Why do you recommend not doing that?  How else would you reconcile a core type?

**Comment by camilamacedo86** [comment]
What do you mean with `How else would you reconcile a core type?`? What is the need that you would like to achieve?

**Comment by michaelgugino** [comment]
> What do you mean with `How else would you reconcile a core type?`? What is the need that you would like to achieve?

You can create a controller (aka operator) for any type, it doesn't have to be a new CRD.  You can have many operators/controllers for a single type.

Here's specifically what I was trying to do

1. Watch secrets in a given namespace (normal controller/operator behavior here)
1. If secret name == x, hash secret data.
1. Fetch a particular deployment
1. Compare hash to a hash annotation on a deployment.
1. If hash is different, update deployment with new hash to trigger rollout with new secret data.

Here's a concrete code base: https://github.com/michaelgugino/htk-cluster-config-operator/blob/master/pkg/controller/secrets/secret_controller.go

There's not really good documentation around ```--custom-api-import``` option and how one would use it, skipping ```operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=AppService``` step.

**Comment by camilamacedo86** [comment]
Hi @michaelgugino, 

Regards:
> You can create a controller (aka operator) for any type, it doesn't have to be a new CRD. You can have many operators/controllers for a single type.

Technically is possible you have one controller for N Kinds, however, it goes implicit against design set by the [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) and I would recommend you not do that in order to not hurt concepts as single responsibility and cohesion for example as in order to avoid problems regards maintenance ability and/or re-usage at least. 

Regards:

> There's not really good documentation around --custom-api-import option and how one would use it, skipping operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=AppService step.

I agree that we need to improve that. Following its usage. 

**Example**
```
 $ operator-sdk add controller  --api-version=k8s.io.api/v1 --kind=Deployment  --custom-api-import=k8s.io/api/apps
INFO[0000] Generating controller version k8s.io.api/v1 for kind Deployment. 
INFO[0000] Created pkg/controller/deployment/deployment_controller.go 
INFO[0000] Created pkg/controller/add_deployment.go     
INFO[0000] Controller generation complete.       
```
Then, in this controller, we will manage all K8S API Deployments in the reconcile. 

### IHMO: What can be done here to address this concern?

- [ ] improve the desc of the command [here](https://github.com/operator-framework/operator-sdk/blob/master/cmd/operator-sdk/add/controller.go#L63)
- [ ] add an explanation in the user guide over it. (doc/user-guide.md)

I am labelling this issue properly. Please, feel free to contribute with it as well.

**Comment by camilamacedo86** [comment]
k8s.io.api/v1

**Comment by camilamacedo86** [comment]
@michaelgugino,

Sorry, I misunderstood the issue at the first moment. I agree that it has hall to improvements. 

Following its usage.
**Example**

```
 $ operator-sdk add controller  --api-version=k8s.io.api/v1 --kind=Deployment  --custom-api-import=k8s.io/api/apps
INFO[0000] Generating controller version k8s.io.api/v1 for kind Deployment. 
INFO[0000] Created pkg/controller/deployment/deployment_controller.go 
INFO[0000] Created pkg/controller/add_deployment.go     
INFO[0000] Controller generation complete.       
Then, in this controller, we will manage all K8S API Deployments in the reconcile.
```

**IHMO: What can be done here to address this concern?**
• [ ] improve the desc of the command here
• [ ] add an explanation in the user guide over it. (doc/user-guide.md)

I am labelling this issue properly. Please, feel free to contribute with it as well.

**Comment by michaelgugino** [comment]
Yeah, just adding some info to the user-guide I think would be helpful.  Something like a section
"Creating a controller with an API from another project" or similar.
"If your API already exists in another project, and you just want to build a controller for it, you can do xyz" kind of thing.  Using one of the core apis in this section could be a helpful example.

**Comment by YiannisGkoufas** [comment]
Would it be possible to have something similar for the new operator-sdk cli?
Apologies if its documented somewhere already.

**Comment by YiannisGkoufas** [comment]
Invoking @camilamacedo86 :)
I believe it should be something similar (since its very useful) in the operator-sdk cli but I haven't discovered it yet.

**Comment by Athosone** [comment]
I am looking for it to using the new CLI, did you find it @YiannisGkoufas ?

**Comment by Athosone** [comment]
I am looking for it to using the new CLI, did you find it @YiannisGkoufas ?

**Comment by YiannisGkoufas** [comment]
Nope, no luck @Athosone :(

**Comment by Athosone** [comment]
I found a way thanks to an issue on github (I dont find the link anymore)
But you can create controllers easily by using the corev1 resources:

```
import (
	"context"

	"github.com/go-logr/logr"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// SecretReconciler reconciles a Secret object
type SecretReconciler struct {
	client.Client
	Log    logr.Logger
	Scheme *runtime.Scheme
}

// +kubebuilder:rbac:groups=core,resources=secrets,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,resources=secrets/status,verbs=get;update;patch

func (r *SecretReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
	_ = context.Background()
	_ = r.Log.WithValues("secret", req.NamespacedName)

	// your logic here

	return ctrl.Result{}, nil
}

func (r *SecretReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&corev1.Secret{}).
		Complete(r)
}
```

This code has been generated using this command:
```
operator-sdk create api  --group="core"  --version v1 --kind Secret  --resource=false --controller=true
```

**Comment by camilamacedo86** [comment]
Hi @YiannisGkoufas, 

We have in the docs https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#adding-3rd-party-resources-to-your-operator and currently, the tool does not provide too much help to work with external types. See that it has been tracked and discussed in https://github.com/kubernetes-sigs/kubebuilder/issues/1772#issuecomment-723213345. 

However, see that this issue is closed since what should be done here in that time was done. So, I'd kindly ask for you folks raise new issues. Thank you.
