### ISSUE TITLE
Helm resources are created in the operator namespace instead of the CR namespace

### ISSUE THREAD

**Issue by tiagomeireles** [operator-framework/operator-sdk#2416]
## Bug Report

**What did you do?**
I posted about this issue in slack. I've upgraded from 0.10.0 to 0.14.0. The operator is releasing into the same namespace that it is deployed in instead of where the CR's are created. This was confirmed by @joelanford on slack.

**What did you expect to see?**
The resources created by the operator are created in the CR's namespace.

**What did you see instead? Under which circumstances?**
The resources created by the operator are created in the operator's namespace.

**Environment**
* operator-sdk version:
0.14.0

* go version:

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?
Helm

**Possible Solution**

**Additional context**

**Comment by joelanford** [comment]
Thanks @tiagomeireles. I’ve got #2414 already posted to fix this.
