### ISSUE TITLE
Review ALL docs generate by the cli-docs

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#2419]
The `make gen-cli-doc` will generate the cli docs automatically which is great. Because now we can be focused to do improvements the helper's commands and then it will provide better documentation as well. 

However, some characters used in the commands can not be rendered properly or not at all in the Markdown.
So, my suggestion is to format the description/usage of the commands with content that will work for both situations.

**Comment by camilamacedo86** [comment]
c/c @joelanford @asmacdo

**Comment by joelanford** [comment]
> However, some characters used in the commands can not be rendered properly or not at all in the Markdown.

@camilamacedo86 What are some examples of this?

**Comment by camilamacedo86** [comment]
@joelanford Following the example:

- [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/cli/operator-sdk_add_controller.md#synopsis)


We see `pkg/apis// ` when it is `pkg/apis/<group>/<version>`

**Comment by camilamacedo86** [comment]
We are working on to migrate the docs for Hugo. 
So, I think we can close this for now and see if it will still be required in the future.
