### ISSUE TITLE
Operator-sdk scorecard bundlevalidationtest

### ISSUE THREAD

**Issue by jdockter** [operator-framework/operator-sdk#2429]
## Type of question
Operator-sdk scorecard testing 

## Question
What exactly does this new test actually test with the bundle as I can't seem to get it to fail.  

**What did you do?**
I've tried to force a failure with incorrect data in my package.yaml but the only thing that generates a failure is if I change my version directory to something like 0.0.2.

Here is my bundle structure...
$ tree -L 4
.
├── crds
│   ├── cache.example.com_memcacheds_crd.yaml
│   └── cache.example.com_v1alpha1_memcached_cr.yaml
├── olm-catalog
│   └── memcached-operator
│       ├── 0.0.1
│       │   ├── cache.example.com_memcacheds_crd.yaml
│       │   └── memcached-operator.v0.0.1.clusterserviceversion.yaml
│       └── memcached-operator.package.yaml
├── operator.yaml
├── role.yaml
├── role_binding.yaml
└── service_account.yaml

removed values from memcached-operator.package.yaml 
```
$ cat memcached-operator.package.yaml 
channels:
- currentCSV: 
  name: 
defaultChannel: 
packageName: 
```

Running the following always returns pass 

```
operator-sdk scorecard -b deploy/olm-catalog/ namespace default --selector=test=bundlevalidationtest

INFO[0000] Using config file: /home/jpd/go/src/github.ibm.com/jdockter/operator-sdk-samples/ansible/memcached-repo/stable/memcached-case-bundle/operators/memcached-operator/.osdk-scorecard.yaml 
olm:
        Bundle Validation Test              : pass
        Labels: 
                "test":"bundlevalidationtest"
                "necessity":"required"
                "suite":"olm"
        Log:
                time="2020-01-17T17:03:09-06:00" level=info msg="loading Bundles" dir=deploy/olm-catalog/
time="2020-01-17T17:03:09-06:00" level=info msg=directory dir=deploy/olm-catalog/ file=olm-catalog load=bundles
time="2020-01-17T17:03:09-06:00" level=info msg=directory dir=deploy/olm-catalog/ file=memcached-operator load=bundles
time="2020-01-17T17:03:09-06:00" level=info msg=directory dir=deploy/olm-catalog/ file=0.0.1 load=bundles
time="2020-01-17T17:03:09-06:00" level=info msg="found csv, loading bundle" dir=deploy/olm-catalog/ file=memcached-operator.v0.0.1.clusterserviceversion.yaml load=bundles
time="2020-01-17T17:03:09-06:00" level=info msg="loading bundle file" dir=deploy/olm-catalog/memcached-operator/0.0.1 file=cache.example.com_memcacheds_crd.yaml load=bundle
time="2020-01-17T17:03:09-06:00" level=info msg="loading bundle file" dir=deploy/olm-catalog/memcached-operator/0.0.1 file=memcached-operator.v0.0.1.clusterserviceversion.yaml load=bundle
time="2020-01-17T17:03:09-06:00" level=info msg="loading Packages and Entries" dir=deploy/olm-catalog/
time="2020-01-17T17:03:09-06:00" level=info msg=directory dir=deploy/olm-catalog/ file=olm-catalog load=package
time="2020-01-17T17:03:09-06:00" level=info msg=directory dir=deploy/olm-catalog/ file=memcached-operator load=package
time="2020-01-17T17:03:09-06:00" level=info msg=directory dir=deploy/olm-catalog/ file=0.0.1 load=package
```

**What did you expect to see?**
From this doc, https://github.com/operator-framework/operator-registry#manifest-format

When loading manifests into the database, the following invariants are validated:
    Every package has at least one channel
    Every ClusterServiceVersion pointed to by a channel in a package exists
    Every bundle has exactly one ClusterServiceVersion.
    If a ClusterServiceVersion owns a CRD, that CRD must exist in the bundle.
    If a ClusterServiceVersion replaces another, both the old and the new must exist in the package.

**What did you see instead? Under which circumstances?**
Always passed test

**Environment**
* operator-sdk version 0.14.0

operator-sdk version
operator-sdk version: "v0.14.0", commit: "4fb185b9d45682473b4951c9788f845ba2fa5b12", go version: "go1.13.3 linux/amd64"

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+dea7fb9", GitCommit:"dea7fb9", GitTreeState:"clean", BuildDate:"2019-11-19T17:18:37Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by jdockter** [comment]
@joelanford can you provide some insight on what this test is checking?

**Comment by joelanford** [comment]
@jmccormick2001 can you help @jdockter out on this one?

**Comment by jdockter** [comment]
@jmccormick2001 I was passing in the -b flag, but tried it both ways, not getting the validation I thought.  What if anything is `bundlevalidationtest` checking with the package.yaml?  Is the only thing being checked the CSV? If so what extra values are being checked vs test crdshaveresourcestest, specdescriptorstest, and statusdescriptorstest (https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/scorecard.md#olm-integration )

**Comment by jdockter** [comment]
@jmccormick2001 also confirming these were the changes to cut over from operator-courier verify ?

**Comment by jmccormick2001** [comment]
its using the validation API from :  https://github.com/operator-framework/api  ...its limited currently by what that API validates...in testing per your comments I notice that it doesn't validate package manifest it appears currently...it does perform some validation against the CRD and CSV currently.  You might create a Issue for this to validate the package manifest as well so it won't be forgotten.
