### ISSUE TITLE
scrub doc/sdk-cli-reference.md

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#2430]
The doc/sdk-cli-reference.md has no longer the same purpose since the cli doc are gen automatically now and it is probably outdated. However,

By @joelanford  

> There are some things on the CLI reference that don't exist anywhere else (e.g. the operator-sdk new --type=helm usages.
> 
> We should probably do a scrub and make sure we don't lose helpful info. It probably makes the most sense to move things like that to the actual cobra examples in the cmd subcommand definitions.

This task was raised for we get it done. Please, feel free to collab with.

**Comment by estroz** [comment]
Closed by #2682
