### ISSUE TITLE
Not able to find proper documentation on how to query Kubernetes resources. 

### ISSUE THREAD

**Issue by chowmean** [operator-framework/operator-sdk#2432]
## Type of question

Help/Support

## Question

**What did you do?**
We are trying to create an operator in which when I need to get the kubernetes resources for example number of pods with particular label. 

I am not able to find any proper documentation on how to query these resources. Is there any provision for that or I need to use kubernetes go client. 

I have read about using LIST apis and below is my piece of code. 
```
podList := &corev1.PodList{}
err = r.client.List(context.TODO(), podList)
if err != nil && errors.IsNotFound(err) {
	reqLogger.Info("No of pods:", string(len(podList.Items)))
} else {
	reqLogger.Error(err, "Error In getting number of pods")
}
```
But this is giving me errors. Is there any documentation that I can use to see the options and provisions provided by operator SDK.

**Comment by camilamacedo86** [comment]
Hi @chowmean, 

You can pass a list of options to do the filters. Such as: 

```go
// Return all pods in the request namespace with a label of `app=<name>`
	// and phase `Running`.
	podList := &v1.PodList{}
	opts := []client.ListOption{
		client.InNamespace(request.NamespacedName.Namespace),
		client.MatchingLabels{"app", request.NamespacedName.Name},
		client.MatchingFields{"status.phase": "Running"},
	}
	ctx := context.TODO()
	err := r.client.List(ctx, podList, opts...)

``` 
See [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/client.mdhttps://github.com/operator-framework/operator-sdk/blob/master/doc/user/client.md) the doc with examples, indeed the above one, for you know how you can use the client provided.

**Comment by camilamacedo86** [comment]
I am closing this one as sorted out. Please,  feel free to re-open if you need.

**Comment by chowmean** [comment]
Thanks are there any doc which can give more details on it.

**Comment by camilamacedo86** [comment]
HI @chowmean, 

The link is: https://github.com/operator-framework/operator-sdk/blob/master/doc/user/client.md.
I updated the above answer with the link.

**Comment by tobias-zeptio** [comment]
The docs have moved again, and I can't find them.
