### ISSUE TITLE
`bundle` command user documenation

### ISSUE THREAD

**Issue by estroz** [operator-framework/operator-sdk#2442]
Now that [`bundle create`](https://github.com/operator-framework/operator-sdk/blob/3503cc0/doc/cli/operator-sdk_bundle_create.md) has been [added](#2438), users can create operator manifest images from their projects to use in deployment scenarios, ex. OLM. These scenarios, and more basically the reason `bundle build` was added in the first place, need documentation so users can deploy their operators effectively.

More information on bundle images: [operator bundle OEP](https://github.com/openshift/enhancements/blob/master/enhancements/olm/operator-bundle.md).

**Comment by jdockter** [comment]
@estroz so should bundle create now be used instead of `opm alpha bundle build`?

For reference:
https://github.com/operator-framework/operator-registry/blob/master/docs/design/operator-bundle.md#build-bundle-image

**Comment by estroz** [comment]
@jdockter `opm alpha bundle build` == `operator-sdk bundle create` with a few CLI differences:
* `--default` == `--default-channel`
* `opm alpha bundle generate` == `operator-sdk bundle create --generate-only`
* `--overwrite` does not exist in `operator-sdk bundle create`
* `opm alpha bundle build --tag <image-tag>` == `operator-sdk bundle create <image-tag>`

The output and underlying behavior is the same, except nothing will be written to disk if `--generate-only` is unset (the default).

These differences will be documented very soon. Feel free to comment here if you have any further questions about usage.
