### ISSUE TITLE
Invalid Schemavalidation when subresource status is enabled

### ISSUE THREAD

**Issue by MichaelBrandt4994** [operator-framework/operator-sdk#2445]
## Bug Report

**What did you do?**
add ```// +kubebuilder:subresource:status``` above our root struct
After that I have execute ```operator-sdk generate k8s  &&  operator-sdk generate openapi```
Then I applied the generated CRD

**What did you expect to see?**
the CRD should be generated correctly and on apply it should be successfully configured

**What did you see instead? Under which circumstances?**
```
The CustomResourceDefinition "datapipelines.foo" is invalid: spec.validation.openAPIV3Schema: Invalid value: apiextensions.JSONSchemaProps{...}: must only have "properties", "required" or "description" at the root if the status subresource is enabled
``` 
Generated CRD:
```
...
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: a description
      properties: ...
      type: Object
...
```

**Environment**
* operator-sdk version:

operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.3 linux/amd64"

* go version:

go version go1.13.4 linux/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-08-01T23:56:00Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?
go

**Possible Solution**
After the generation of the CRD,  I manually remove ```type: Object```. 
Then it successfully apply the CRD.

**Additional context**
I researched a little bit and I thought that, with our operator-sdk version, the ```type: Object``` should not be set when the status subresource is enabled.

**Comment by bharathi-tenneti** [comment]
Hi, Thank you for reporting. 
Can you please provide which version of controller-tools are you using ? Please see below https://github.com/kubernetes-sigs/controller-tools/issues/375 , it looks like you ran into something similar, and it was fixed in newer versions.

**Comment by MichaelBrandt4994** [comment]
In operator-sdk v0.12.0 it is v0.2.2 for controller-tools.
Yes this might be the problem, but I don't know where I can see which kubebuilder version is used

**Comment by bharathi-tenneti** [comment]
Hi @MichaelBrandt4994 
Are you still seeing this issue?

**Comment by MichaelBrandt4994** [comment]
For us not anymore, we just delete the type and description property.

**Comment by bharathi-tenneti** [comment]
Alright, I am closing the issue.
