### ISSUE TITLE
Allow using different log formats for the Operator

### ISSUE THREAD

**Issue by drf** [operator-framework/operator-sdk#2449]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, Operator SDK uses Zap for logging, but it appears there's no obvious way to tweak the format zap outputs the logs in. For example, if one wishes to use logfmt, he could resort to something like https://github.com/jsternberg/zap-logfmt .

**Describe the solution you'd like**
Make it possible (or document properly, if currently possible) to specify a Zap log format when initializing Operator SDK.

**Comment by joelanford** [comment]
@drf The interface that Operator SDK (and controller-runtime) use for logging is actually `logr`, so any logging implementation that supports the `logr` interface can be used.

We have docs about logging, but they don't go into much detail about more advanced customizations: https://github.com/operator-framework/operator-sdk/blob/master/doc/user/logging.md

Also, there is also some work ongoing in controller-runtime that should make this easier to all controller-runtime consumers. See https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/log/zap. 

To use your own custom zap logger, you just need to use `zapr` to wrap it in a `logr`-supported implementation See https://github.com/go-logr/zapr#usage

We would welcome a PR to update the logging doc with a section about using a custom zap logger :slightly_smiling_face:
