### ISSUE TITLE
Question: Error handling in Memcached example controller

### ISSUE THREAD

**Issue by micahlee** [operator-framework/operator-sdk#2450]
## Type of question

This is a question about the example Memcached controller: 
https://github.com/operator-framework/operator-sdk/blob/master/example/memcached-operator/memcached_controller.go.tmpl

## Question

**What did you do?**
I'm looking at the Memcached example controller, and I noticed in this error handling, it says that this error means the reconciliation step should be requeued, but the returned `reconcile.Result` value doesn't include `Requeue: true`.

https://github.com/operator-framework/operator-sdk/blob/c6848c7b2773b6b917e00debc4c5443d268bba90/example/memcached-operator/memcached_controller.go.tmpl#L104-L106

**What did you expect to see?**
I would have expected to see here:
```golang
// Error reading the object - requeue the request.
reqLogger.Error(err, "Failed to get Memcached")
return reconcile.Result{Requeue: true}, err
```

**Additional context**
I'm trying to understand if this is a mistake in the example, or if there is an implicit requeue logic I should be aware of. Any guidance is greatly appreciated!

**Comment by joelanford** [comment]
@micahlee When returning a non-nil error from the `Reconcile()` method, it is not necessary to use `Requeue: true` because any reconciliations that result in an error will be automatically requeued with built-in backoff (to avoid retrying forever in a tight loop).

**Comment by micahlee** [comment]
Great, thanks so much!

**Comment by pyros2097** [comment]
@joelanford what is the built-in backoff mechanism? How long does it keep retrying and what will be the final status of the object if all retries are exhausted?
