### ISSUE TITLE
operator-sdk tries to download from github

### ISSUE THREAD

**Issue by riponbanik** [operator-framework/operator-sdk#2456]
## Type of question
Develop Locally

## Question

**What did you do?**
I have followed https://github.com/operator-framework/getting-started to build first sdk, but when I run operator-sdk up local --namespace=default, I get the following error, it tries to download from github 

build github.com/example-inc/cmd/manager: cannot load github.com/example-inc/memcached-operator/pkg/apis/cache/v1alpha1: git ls-remote -q https://github.com/example-inc/memcached-operator in $GOPATH/pkg/mod/cache/vcs/4028b6f0655e9f4169a04da4f81a0ebfc2f7ddc671d3b942cf7365270b868d83: exit status 128:
        fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
Error: failed to build operator to run locally: (failed to exec []string{"go", "build", "-o", "build/_output/bin/memcached-operator-local", "github.com/example-inc/cmd/manager"}: exit status 1)

**What did you expect to see?**
I want to develop locally with explicit path in github, even outside of my GOPATH

**What did you see instead? Under which circumstances?**
It seems I need to have repo in github 

**Environment**
* operator-sdk version:

operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.3 linux/amd64"

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
minikube

**Comment by joelanford** [comment]
@riponbanik If I'm understanding your intent, I think this is more of an issue with Go and your Go environment than it is with `operator-sdk`.

To develop locally outside of GOPATH, I think you'll need a full copy of all project dependencies in your project's vendor directory. At that point `operator-sdk` should detect your vendor directory and automatically use `-mod=vendor` when running `go build`.

**Comment by riponbanik** [comment]
@joelanford  Thanks. It is actually a Chicken & Egg issue. The new version of operator-sdk (0.12.x) require Golang 1.13.x and the new Go version cannot detect the source in GOPATH when go.mod is present.

I have resolved the issue by adding the following in go.mod 

replace github.com/example-inc/memcached-operator => ../memcached-operator.
