### ISSUE TITLE
How to store data related to operator in etcd. 

### ISSUE THREAD

**Issue by chowmean** [operator-framework/operator-sdk#2463]
## Type of question
**Help/Support.** 

## Question

**What did you do?**
I want to store some data in etcd. How can I achieve that? Any documentation will be really helpful. Thanks

**Comment by joelanford** [comment]
@chowmean Can you give us a little more context about your use case? Typically, operators don't maintain their own state outside of the Kubernetes API itself since that state can become stale and out-of-sync with the state of the resources the operator is managing in the cluster.

We may be able to point you in the right direction with a little more info.

**Comment by chowmean** [comment]
hey @joelanford, my use case is something like this. 
I want to deploy 2 Statefulsets but I want to keep a difference between these says an hour. 
`Deploy statefulset1 -> wait1 hour -> deploy statefulset2`
For this, I wanted to save data for start time. I guess I can take it from a stateful set launch info also. 
So if I want to maintain a ticker, how to do it and how to trigger the reconcile after an hour?

I may not be able to point out the exact case here. But I am exploring options with operator-SDK right now. So if there is a way to save it in etcd even if it is not recommended, I want to know out of curiosity.
It would be really helpful. Thanks

**Comment by joelanford** [comment]
Interacting directly with etcd is outside the scope of `operator-sdk`, but that doesn't mean you can't do it. You would need to deploy an etcd cluster, and then configure your operator to connect to it (e.g. using the [etcd operator](https://github.com/coreos/etcd-operator) and the [etcd go client](https://github.com/etcd-io/etcd/tree/master/clientv3))

However, there are probably simpler ways to do this directly with your operator and/or your CRD API.

For example, when your operator reconciles the CR that creates your statefulsets, it can check that `statefulset1` exists. If not, create it. If you setup a watch on owned statefulsets, your operator should get re-reconciled as `statefulset1` progresses.

During those subsequent reconciliations, your operator can get the creation timestamp on the `statefulset1` and subtract it from `time.Now()` (e.g. `elapsed := time.Now().Sub(ss1CreationTime)`). If `elapsed` is greater than 1 hour, check if `statefulset2` is deployed. If not, create it. If `elapsed` is less than one hour, you can `return reconcile.Result{RequeueAfter: timeDiff}, nil` to retrigger reconcilation at the exact right time.

This method also helps avoid weird edge cases with persisting cluster state separately from the cluster. It would not be super easy to atomically guarantee that when you create `statefulset1` you also correctly update `etcd`. For example, what if `etcd` goes down right after you successfully create `statefulset1`. You'll be unable to record your start timer.

The guidance with operators is to always do a full reconciliation each and every time. Your reconciler should always do a full assessment of the state of the resources in the cluster that it cares about, and then attempt to make any necessary changes to align the cluster with the spec of your CR.

I hope that helps! I'm happy to answer any follow-ups you may have!

**Comment by chowmean** [comment]
@joelanford thanks a lot. Sure I will raise support requests if I am stuck at anything. Closing this one.
