### ISSUE TITLE
generate k8s command doesn't regenerate build/update scripts

### ISSUE THREAD

**Issue by t0ffel** [operator-framework/operator-sdk#247]
When you create an operator it generates scripts under `./tmp` specifically `tmp/codegen/update-generated.sh` script.
Judging by the name of the folder (tmp) I didn't bother to commit it, as a result when I wanted to update types(`operator-sdk generate k8s`) i was unable to. I've got error:

> Run code-generation for custom resources
> Error: failed to perform code-generation for CustomResources: ()

Maybe it'll be better not to store such scripts under `./tmp`?

**Comment by fanminshi** [comment]
I agree with the naming of `tmp` being confusing. We have a issue to fix that https://github.com/operator-framework/operator-sdk/issues/180.

Sorry for the inconvenience at the moment.

**Comment by t0ffel** [comment]
oh, didn't see that it's a duplicate. sorry.
