### ISSUE TITLE
What happens to Reconcile events in the workqueue if the leader crashes?

### ISSUE THREAD

**Issue by Baisang** [operator-framework/operator-sdk#2473]
## Type of question

Conceptual/contextual question

## Question

Hi, I was reading through past issues like https://github.com/operator-framework/operator-sdk/issues/1906 and just wanted to check my understanding.

So at a high level what is happening as I understand it is changes in...well, whatever is being watched, are seen as events by the operator/controller-runtime internal (EventHandler?) and eventually sent to the controller as Reconcile Requests, upon which we run Reconciler functions to process the event.

If there's >1 event in the workqueue (which seems to just be stored locally in the operator?), and the operator leader crashes before it can finish processing them, are those events just gone forever? How do we make sure that those events can still eventually be processed?

**Comment by joelanford** [comment]
@Baisang when the next operator replica becomes leader and starts the controllers, it will start all of the informers, which do a list (and then watch). All listed objects that match the predicate will be reconciled once, and then the events from the watches will trigger follow-on reconciliations.

**Comment by Baisang** [comment]
@joelanford Gotcha, so to restate what you said (for my understanding), while the past events are lost, once the next operator starts up since it just does a "re-reconcile" it'll regenerate events so that the operator(s) as a whole can still eventually Reconcile all of the resources to the proper state?

That's nice, and much better than my idea of just setting the manager's `SyncPeriod` to be like 10 minutes or something instead
