### ISSUE TITLE
CRD generation : map values must be a named type, not *ast.StarExpr

### ISSUE THREAD

**Issue by erdrix** [operator-framework/operator-sdk#2485]
# Bug Report

## What did you do?

Upgraded the `operator-sdk` to version` v0.15.0`, and used `operator-sdk generate crds`, to generate crd from spec : https://github.com/Orange-OpenSource/casskop/blob/master/pkg/apis/db/v1alpha1/cassandracluster_types.go#L818

## What did you expect to see?

Having my crd object generated with the following logs : 

```sh
$ operator-sdk generate crds
INFO[0000] Running CRD generator.
INFO[0001] CRD generation complete.
```

## What did you see instead? Under which circumstances?

```sh 
$ operator-sdk generate crds  
INFO[0000] Running CRD generator.
/Users/aguitton/workspace/casskop/casskop/pkg/apis/db/v1alpha1/cassandracluster_types.go:819:33: map values must be a named type, not *ast.StarExpr
FATA[0001] error generating CRDs from APIs in pkg/apis: error generating CRD manifests: error running CRD generator: not all generators ran successfull
```

## Environment 

- operator-sdk version : v0.15.0
- go-version : 0.13

## Possible Solution

The operator sdk have a dependency to `sigs.k8s.io/controller-tools v0.2.4`, which perform the schema validation during the crd generation, this module is the root cause of the error. 

To fix this, there is a PR : https://github.com/kubernetes-sigs/controller-tools/pull/317, which is not merged yet. Once the merge will be done, update the dependency should be enough (until it's done we forked the [operator-sdk](https://github.com/erdrix/operator-sdk/tree/v0.15.0-pr137) and the [controller-tool](https://github.com/erdrix/controller-tools/tree/v0.2.4-pr137)).

**Comment by camilamacedo86** [comment]
It should be closed after the pr https://github.com/kubernetes-sigs/controller-tools/issues/287 get merged and SDK be updated/using that gets a new release version of it.

**Comment by estroz** [comment]
This is a controller-tools issue. We can bump the controller-tools version once this bug is fixed upstream.

**Comment by cscetbon** [comment]
@estroz they just released https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.4.0 which fixes it. Can you bump
It ?

**Comment by estroz** [comment]
@cscetbon are you looking for this fix for a legacy project or one created with SDK v0.19+?

**Comment by cscetbon** [comment]
@estroz for the project in the description 😬

**Comment by estroz** [comment]
@cscetbon v0.18 is outside our [backport policy](https://sdk.operatorframework.io/docs/upgrading-sdk-version/backport-policy/) unfortunately. We could probably backport this to v0.19.

**Comment by cscetbon** [comment]
We can upgrade to 0.19 if you backport it. We’re probably not the only ones to have this issue. And in the meantime use that method (will have to try it)
