### ISSUE TITLE
Resources that use `-` in the API group name can't be directly accessed by ansible

### ISSUE THREAD

**Issue by Cerebus** [operator-framework/operator-sdk#2486]
## Bug Report

**What did you do?**
Resource with, e.g.,:
```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
```
Accessing the resource or resource spec as a variable fails.

**What did you expect to see?**
Accessing the variable should work, i.e.:
```
foo: "{{ _cert-manager_io_certificaterequest }}"
```

**What did you see instead? Under which circumstances?**
The variable name is truncated at the `-`, and ansible throws an undefined variable exception:
```
The task includes an option with an undefined variable. The error was: '_cert' is undefined
```

**Environment**
* operator-sdk version:

operator-sdk version: "v0.15.0", commit: "21a93ca379b887ab2303b0d148a399bf205c3231", go version: "go1.13.6 darwin/amd64"

* go version:

go version go1.13.6 darwin/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Single node.  Docker Desktop w/ Kubernetes

* Are you writing your operator in ansible, helm, or go?

Ansible

**Possible Solution**

The resource can be accessed through the array accessor, e.g.:
```
foo: vars["_cert-manager_io_certificaterequest"]
```
**Additional context**
While `-` is not valid in a JSON variable, it is valid in a JSON key name.  However, it will get parsed as a subtraction operation.

**Comment by camilamacedo86** [comment]
Hi @Cerebus, 

Really thank you for share that. Also, please feel free to collab with if you wish.

**Comment by camilamacedo86** [comment]
Hi @fabianvf, @asmacdo 

Could you please give me a hand here and help me to ensure that it is bug and not the expected behaviour?

**Comment by estroz** [comment]
This is a real bug.
