### ISSUE TITLE
Reconciling RoleBindings on openshift 3.11 / 4.x doesn't work

### ISSUE THREAD

**Issue by waseem-h** [operator-framework/operator-sdk#2487]
## Bug Report

**What did you do?**
I have the following code for reconciling rolebindings that I create through my CR:

```go
rolebindings := createRolebindings(instance)

	for _, rolebinding := range rolebindings {
		// Set Ownership instance as the owner and controller
		if err := controllerutil.SetControllerReference(instance, rolebinding, r.scheme); err != nil {
			allErrors = append(allErrors, err)
		}

		found := &rbacv1.RoleBinding{}
		found.SetGroupVersionKind(schema.GroupVersionKind{
			Group:   "authorization.openshift.io",
			Version: "v1",
			Kind:    "RoleBinding",
		})
		err = r.client.Get(context.TODO(), types.NamespacedName{Name: rolebinding.Name, Namespace: rolebinding.Namespace}, found)
		reqLogger.Info("Error is", "err", err.Error())
		if err != nil && errors.IsNotFound(err) {
			reqLogger.Info("Creating a new RoleBinding", "RoleBinding.Name", rolebinding.Name, "Rolebinding.Namespace", rolebinding.Namespace)
			err = r.client.Create(context.TODO(), rolebinding)
			if err != nil {
				allErrors = append(allErrors, err)
			}
		} else if err != nil {
			allErrors = append(allErrors, err)
		} else {
			// RoleBinding already exists - don't requeue
			reqLogger.Info("Skip reconcile: RoleBinding already exists", "RoleBinding.Name", found.Name, "Rolebinding.Namespace", found.Namespace)
		}

	}

func createRolebindings(cr *stakaterv1alpha1.Ownership) (rolebindings []*rbacv1.RoleBinding) {
	for _, namespace := range cr.Spec.Namespaces {
		subjects := []rbacv1.Subject{}

		subjects = append(subjects, rbacv1.Subject{
			APIGroup: "rbac.authorization.k8s.io",
			Kind:     "User",
			Name:     cr.Spec.Owner.Email,
		})

		for _, user := range cr.Spec.Members {
			subjects = append(subjects, rbacv1.Subject{
				APIGroup: "rbac.authorization.k8s.io",
				Kind:     "User",
				Name:     user.Email,
			})
		}

		rolebindings = append(rolebindings, &rbacv1.RoleBinding{
			ObjectMeta: metav1.ObjectMeta{
				Name:      "edit",
				Namespace: namespace,
			},
			TypeMeta: metav1.TypeMeta{
				APIVersion: "authorization.openshift.io/v1",
			},
			RoleRef: rbacv1.RoleRef{
				APIGroup: "rbac.authorization.k8s.io",
				Kind:     "ClusterRole",
				Name:     "edit",
			},
			Subjects: subjects,
		})
	}
	return
}
```

The APIVersion for RoleBinding in openshift is `authorization.openshift.io/v1` which is different from Kubernetes. So I assume this is why it can't find the same resource for a different APIVersion. But I even tried changing the `found` object and specified the openshift's APIVersion in the TypeMeta before doing r.client.Get but that didn't work either. Is there a way to specify a different APIVersion? If there is, then I could make a check for detecting openshift and change the APIVersion to match the openshift one.
**What did you expect to see?**
I expected the resource to be reconciled

**What did you see instead? Under which circumstances?**
I saw the following in the logs when reconciling:
```
{"level":"info","ts":1580428485.2161222,"logger":"controller_ownership","msg":"Error is","Request.Name":"example-ownership","err":"RoleBinding.rbac.authorization.k8s.io \"edit\" not found"}
{"level":"info","ts":1580428485.216156,"logger":"controller_ownership","msg":"Creating a new RoleBinding","Request.Name":"example-ownership","RoleBinding.Name":"edit","Rolebinding.Namespace":"ocp-namespace-2"}
{"level":"error","ts":1580428485.237268,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"ownership-controller","request":"/example-ownership","error":"rolebindings.rbac.authorization.k8s.io \"edit\" already exists\nrolebindings.rbac.authorization.k8s.io \"edit\" already exists","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/waseem.hassan/go/src/github.com/stakater/ownership-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/waseem.hassan/go/src/github.com/stakater/ownership-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/waseem.hassan/go/src/github.com/stakater/ownership-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/Users/waseem.hassan/go/src/github.com/stakater/ownership-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/Users/waseem.hassan/go/src/github.com/stakater/ownership-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/waseem.hassan/go/src/github.com/stakater/ownership-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/waseem.hassan/go/src/github.com/stakater/ownership-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version: 
operator-sdk version: "v0.15.1", commit: "e35ec7b722ba095e6438f63fafb9e7326870b486", go version: "go1.13.6 darwin/amd64"

* go version:

go version go1.13 darwin/amd64

* Kubernetes version information: 

kubectl version
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-02-22T07:05:30Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-10-10T16:48:37Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:  go

**Possible Solution**

**Additional context**

**Comment by waseem-h** [comment]
I just tried with an openshift 4.3 cluster and its still the same issue

**Comment by camilamacedo86** [comment]
Hi @waseem-h, 

First, at all, I'd like to share that the OCP 3.11 is using a very old version of the k8s API which is no longer compatible with the latest versions ( >9.0) of SDK. So, I'd NOT recommend you use the OCP 3.11.

Regards the subject, note that the API `authorization.openshift.io/v1` is specific for OpenShift. Then, it is not a schema added by default in the projects made by using the SDK tool. In order, to use the OCP API's and/or any third-party one is required to add the schema in the project. 

See the [doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#adding-3rd-party-resources-to-your-operator). Have you done it?   

Also, see that the error faced in the logs is : 

> :"/example-ownership","error":"rolebindings.rbac.authorization.k8s.io \"edit\" already exists\nrolebindings.rbac.authorization.k8s.io \"edit\" already exists",

Which means that the object already exists. I'd like to suggest you re-check your business logic implementation as well and I'd recommend you do it such as described in the [Getting Started](https://github.com/operator-framework/getting-started) and [samples](https://github.com/operator-framework/operator-sdk-samples) [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/pkg/controller/memcached/memcached_controller.go#L146). Shows, that you are not checking if the resource exists already before create. See an example:

```
reconcile App {

   // Check if the RoleBinding for the namespace exist, if not create one
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   } 
}
```

Also, I'd recommend you add the owner ref when the resource is created such as [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/pkg/controller/memcached/memcached_controller.go#L222)

I am closing this one as sorted out. Please, feel free to re-open if you see that still required.
