### ISSUE TITLE
Allow ApisDir to be configurable

### ISSUE THREAD

**Issue by Tomcli** [operator-framework/operator-sdk#2493]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We have issues with generating apis deepcopy and CSV with the operators we built on an existing package. Right now the [ApisDir](https://github.com/operator-framework/operator-sdk/blob/master/internal/scaffold/constants.go#L29) is a constant looking for the apis defined at `PkgDir + filePathSep + "apis"` where our package defined the apis under `PkgDir + filePathSep + "apis" + "/apps"`. This creates the missing directory error when generating CSV,
```
INFO[0000] Generating CSV manifest version 0.1.0
INFO[0000] Directory for API kfdef.apps.kubeflow.org/v1, Kind=KfDef does not exist. Skipping CSV annotation parsing for API.
WARN[0000] Required csv fields not filled in file deploy/olm-catalog/kfctl/0.1.0/kfctl.v0.1.0.clusterserviceversion.yaml:
	spec.keywords
	spec.maintainers
	spec.provider
INFO[0000] Created deploy/olm-catalog/kfctl/0.1.0/kfctl.v0.1.0.clusterserviceversion.yaml
```

**Describe the solution you'd like**
We would like to have a configurable way to point to the api directory when generating CSV or deepcopy code.

**Comment by hasbro17** [comment]
@Tomcli Thanks for opening the issue and good timing :) 
@estroz and I are working on this as part of #2407 
We're currently refactoring the CSV generator and `generate csv` command to be more configurable in its inputs and outputs, so it can work on non-default project layouts.
So this should hopefully be addressed quite soon if you want to follow along on that PR.
