### ISSUE TITLE
how to inspect the event of builtin object in operator?

### ISSUE THREAD

**Issue by dongwangdw** [operator-framework/operator-sdk#2496]
when a namespace created/deleted, I will do something in the operator, then I need inspect the namespace event, how can I do this?

**Comment by camilamacedo86** [comment]
Hi @dongwangdw, 

If you would like o to trigger the reconcile when any change/event occurs in a specific resource as for example a namespace you can use the Watch feature.  Are you working with Go projects? 

If yes, I'd like to recommend you check the [Getting Started](https://github.com/operator-framework/getting-started) where you will see that this feature is added in the example as the blog post [Getting started with Golang Operators by using Operator SDK](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/) 
 where you can find further explanations with exemplifications over it as well. 

Please, let us know if it answers your question and if we can close this issue.

**Comment by dongwangdw** [comment]
@camilamacedo86 
thanks for the quick answer. Sorry, I did not make it clearly. I mean not a single namespace, but all the namespace. If any of the namespaces' status got changed. I could get that and do some work accordingly. I initially considered `watch` too. but 
1. I wonder can I get the events (creation/deletion) of all namespaces event directly, since there is already kubernete controller already. I can new a [client](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/client.md#non-default-client) directly and talk to apiserver directly. But not sure it is proper. But this kind of thing is what I want.
2. I am not sure how to get the events with watch. I think I got some missed here. Or can I make this with `watch`.  Not so familiar with the api.

**Comment by joelanford** [comment]
@dongwangdw Check [this FAQ question](https://github.com/kubernetes-sigs/controller-runtime/blob/master/FAQ.md#q-how-do-i-have-different-logic-in-my-reconciler-for-different-types-of-events-eg-create-update-delete) out.

As @camilamacedo86 suggested, a watch is probably what you want. Every time your controller reconciles your CR you should List all namespaces to get the global state of namespaces every time and then apply whatever logic is dictated by the CR based on what namespaces are present (or not present).

**Comment by dongwangdw** [comment]
OK. I will try it.  Thanks @joelanford @camilamacedo86

**Comment by dongwangdw** [comment]
@camilamacedo86 
Yes, this `watch` worked. When I deleted/created a namespace, the reconciler will always get the change namespace. So I can take further action. But the problem is, there are two same object in the queue.  So, when I processed the first one, the second one will mess up my logic. Is there anything I missed?

**Comment by dongwangdw** [comment]
And I make sure each time I return a `reconcile.Result{Requeue: false}`. And this will not requeue the object again. So this does not result from my action.

**Comment by camilamacedo86** [comment]
Hi @dongwangdw, 

Have you the chance for giving a look in the blog post [Getting started with Golang Operators by using Operator SDK](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/)? There you can find an example to know how to work with the reconcile results and watches.

**Comment by dongwangdw** [comment]
@camilamacedo86 
Yes, I read that. But I am sure that if I watch namespace resource, it will reconcile three times when I delete a namespace and two times when I create one. You can reproduce this with very simple code.
1. create a simple operator
2. Watch namespace.
3. just log the request.Name.

You will read the situation from the log. Would you please help confirm this? Thanks very much for your time and patience.

**Comment by camilamacedo86** [comment]
HI @dongwangdw, 

Regards

>  it will reconcile three times when I delete a namespace and two times when I create one

It makes sense. See that the watch will trigger the reconcile when any event that is raised for a resource watched (edit/update/delete/create)

So, when you create the reconcile will be called and will still running until all states in the cluster be as should be ( unless you set to ignore-errors ), however, in the delete operation, more events/actions are required such as to update the resource and flag that they need to be removed, then the API will start to remove all and do the required operations to dealing with finalizers and etc.. 

Note that your main question is pretty sorted out. So, could I ask kindly for you to raise new issues for new questions? 

Really thank you for your attention.

**Comment by dongwangdw** [comment]
@camilamacedo86 
OK. I will open another issue for this.
Thanks very much for your time and patience. Really appreciate it.

**Comment by dongwangdw** [comment]
@camilamacedo86 FYI #2517 . Thanks again.
