### ISSUE TITLE
Extend operator-sdk to autogenerate controller that instantiates argo workflows

### ISSUE THREAD

**Issue by akshaychitneni** [operator-framework/operator-sdk#2497]
## Feature Request

Hi all, I have extended operator-sdk to autogenerate controller and k8s constructs to support argo workflows. It autogenerates controller that maps custom resource spec to workflow parameters. Any update to CR will instantiate workflow. 

This branch has all the implementation. https://github.com/akshaychitneni/operator-sdk/tree/argo
Please let me know if I can merge with operator-sdk. thanks

**Comment by joelanford** [comment]
@akshaychitneni I'm not familiar with Argo (and I'm not sure any of the core maintainers are either). Could you explain in words what it is and how an Argo extension would work with the SDK? 

I'm interested in this:

> Any update to CR will instantiate workflow.

Maybe I'm not understanding, but I'm not sure that's a typical operator model. Typically an operator reconciles CRs with the cluster state, such that when a CR is updated the existing resources associated with that CR are also updated. It seems like instantiating new workflow resources on every CR update would run counter to that model and could fail in surprising ways.

For example, if the operator is down when a couple of CR updates happen, the operator would never know those updates occurred when it starts back up. It would just see the current state.

Also, if a user typos something in an update and then immediately submits another update to fix the typo, does that result in two instantiations of the workflow when the user intent was just one?

**Comment by akshaychitneni** [comment]
Argo allows user to define and instantiate workflow using k8s API. https://github.com/argoproj/argo
Workflow consists of multiple steps which can run in isolated containers.

In general, the operators actualizes the state defined with custom resources. But I would like to move actualization logic into the workflow. So for example, if user updates the CR to a certain state, the operator should just instantiate the workflow with proper params but the workflow defined has all the logic defined by the user to actualize the state. 

This in general can be applied to any workflow, like AWS step functions or fission workflows, where the implementation is declaratively defined by the user in the workflow. 

Hope this helps. thanks

**Comment by camilamacedo86** [comment]
If I understood properly, in the same way, that we have the Ansible and Helm operator, you are looking for an Argo's operator done with SDK. Am I right?

**Comment by akshaychitneni** [comment]
@camilamacedo86  yes. Would also like to generalize and support other workflow providers as well.

**Comment by estroz** [comment]
@akshaychitneni this might be something that could benefit from [kubebuilder plugins](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/extensible-cli-and-scaffolding-plugins-phase-1.md) since we'll be moving to a kubebuilder-based project structure soon.

**Comment by akshaychitneni** [comment]
Thanks @estroz. I will look into it.

**Comment by tengqm** [comment]
/remove-lifecycle stale

pretty interesting idea, let's keep it alive.
