### ISSUE TITLE
How to get old CRD object when updating CRD object spec

### ISSUE THREAD

**Issue by ustcsunshine** [operator-framework/operator-sdk#2501]
Hi team,
When I update CRD object, the operator can only get latest CRD object. How can I get the old CRD object?

Thanks

**Comment by camilamacedo86** [comment]
Hi @ustcsunshine, 

I am assuming that you are speaking over the CR (Custom Resource) since the CRD is not updated. Could you please add the following information which is requested in the issue template for we are able to understand better your needs and help you more assrtivelly? 

> **What did you do?**
> A clear and concise description of the steps you took (or insert a code snippet).
> 
> **What did you expect to see?**
> A clear and concise description of what you expected to happen (or insert a code snippet).
> 
> **What did you see instead? Under which circumstances?**
> A clear and concise description of what you expected to happen (or insert a code snippet).
> 
> 
> **Environment**
> * operator-sdk version:
> 
>   insert release or Git SHA here
> 
> * Kubernetes version information:
> 
>   insert output of `kubectl version` here
> 
> * Kubernetes cluster kind: 
> 
> **Additional context**
> Add any other context about the question here.
>

**Comment by ustcsunshine** [comment]
What did you do?
I want to get old CR and find what difference between the old CR and the new CR. I need these information to do my work.

What did you expect to see?
Is there any template code like the following in the operator?
EventSchema is my CRD.
```
func (r *ReconcileEventSchema) Reconcile(old *v1alpha1.EventSchema, new *v1alpha1.EventSchema) {

}
```

operator-version:  `latest version`

**Comment by camilamacedo86** [comment]
Hi @ustcsunshine, 

When we use the `kubectl apply` the Kubernetes API will add the old data in the annotation `last-applied-configuration` of the CR. I did not check but I believe that the client.update will have the same behaviour. However, Kubernetes API does not keep a history track of all CR's states. 

If you are looking for to perform actions when some resource change, for example, the CR. Then, the watch feature will allow you to do that and will re-trigger the reconcile. Note that the default scaffolded controller for each kind/API added in the project has the watch implementation done by default for the primary resource which is any CR applied of its CRD.

Also, if you did not check this already, I'd like to share and suggest you follow the [Getting Started](https://github.com/operator-framework/getting-started) and see the [post](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/) for a further understanding. It is a low effort, I mean you will not spend more than 1 or 2 hours to do this, and it will give a pretty good idea over how you can solve your needs by using the Framework.

I am closing this one as sorted out. However, please feel free to ask to re-open if you see that you still needing help regards this subject. Also, if it is the case, could you please share a little bit more context and let us know why you need to get the old version? What is the business logic that you are trying to achieve with? Then, may we can help you more with.

**Comment by ustcsunshine** [comment]
@camilamacedo86 
I still don't clear why operator sdk cannot get the old CR. I see `informer` of another operator can get the old one. Here is the link: https://github.com/kubernetes/sample-controller/blob/master/controller.go#L118
```
UpdateFunc: func(old, new interface{}) {
			newDepl := new.(*appsv1.Deployment)
			oldDepl := old.(*appsv1.Deployment)
			controller.handleObject(new)
}
```
