### ISSUE TITLE
How to make Namespaces from Operators

### ISSUE THREAD

**Issue by CheesyFeet** [operator-framework/operator-sdk#2503]
## Type of question

How to implement a specific feature

## Question

I'm trying to create namespaces from a cluster-scoped Operator. When a CRD is created the Operator should create the namespace and various other objects inside of that namespace. I was going to do this using the standard `resolver.client.Get()` and `resolver.client.Create()` methods, but found that these methods use the `NamespacedName` struct. Obviously the namespace object isn't namespaced, so what is the recommended way to CRUD namespaces from within an Operator?

Thanks!

**Environment**
* operator-sdk version: 0.14.0

**Comment by camilamacedo86** [comment]
Hi @CheesyFeet, 

The same question was raised before. See : https://github.com/operator-framework/operator-sdk/issues/2166#issuecomment-551146390

Closing this one as sorted out. However, please, feel free to re-open and/or ping us if you need.

**Comment by camilamacedo86** [comment]
Hi @CheesyFeet, 

This question is very similar/same scenario of another raised before. See: https://github.com/operator-framework/operator-sdk/issues/2166#issuecomment-551146390

Closing this one as sorted out. However, please, feel free to re-open and/or ping us if you need.

**Comment by CheesyFeet** [comment]
Thanks @camilamacedo86 - just what I needed.

I would say that using a *Namespaced*Name construct to query for *Cluster* resources is a bit counter-intuitive, hence why I got confused (and it would seem as did the user in #2166). It looks like this comes from the downstream controllerutil project though so I guess this is the wrong place to address this.

Thanks again!
