### ISSUE TITLE
Unable to initialise Helm Type operator

### ISSUE THREAD

**Issue by Katiyman** [operator-framework/operator-sdk#2507]
## Type of question

**Help around the operator-sdk**

## Question

**What did you do?**
Initialising helm type operator using operator sdk
`operator-sdk new bookstore-operator --api-version=velotio.com/v1alpha1 --kind=BookStore --type=helm --helm-chart=book-store  --helm-chart-repo=https://github.com/akash-gautam/helmcharts.git`

**What did you expect to see?**
Successful generation of operator 

**What did you see instead? Under which circumstances?**
```
INFO[0000] Creating new Helm operator 'bookstore-operator'.
Error: failed to create helm chart: failed to fetch chart: looks like "https://github.com/akash-gautam/helmcharts.git" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/akash-gautam/helmcharts.git/index.yaml : 404 Not Found
Usage:
.
```

**Environment**
* operator-sdk version:
operator-sdk version: "v0.14.0", commit: "4fb185b9d45682473b4951c9788f845ba2fa5b12", go version: "go1.13.3 linux/amd64"
  insert release or Git SHA here

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
single node using kubeadm

**Additional context**

The git url mentioned in the command is accessible from the machine
Need to know what url has to be specified there or any work around for that.

**Comment by camilamacedo86** [comment]
HI @Katiyman, 

Following an example over how to create a project-based in a helm chart from the catalogue. 

> operator-sdk new memcached-operator --api-version=cache.example.com/v1alpha1 --kind=Memcached --type=helm --helm-chart=stable/memcached

For more details and examples see the [Helm CLI reference doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#helm-project).

Then, to attend your need shows that you need to:

```
$ operator-sdk new app-operator --type=helm \
    --helm-chart=app \
    --helm-chart-repo=https://charts.mycompany.com/
```

However, according to the error faced:

> Looks like "https://github.com/akash-gautam/helmcharts" is not a valid chart repository or cannot be reached: Failed to fetch https://github.com/akash-gautam/helmcharts/index.yaml : 404 Not Found

Shows that this project is missing `index.yaml` which is expected. See: https://helm.sh/docs/topics/chart_repository/#create-a-chart-repository

@joelanford, please let me know if I am wrong in something here.

**Comment by joelanford** [comment]
@Katiyman it doesn't seem like GitHub is serving your repository the way you expect it to. Helm's docs about [hosting chart repositories](https://helm.sh/docs/topics/chart_repository/#hosting-chart-repositories) might help.

Since it looks like you have your chart tgz file checked in, you should also be able to do this:
```sh
operator-sdk new bookstore-operator --api-version=velotio.com/v1alpha1 --kind=BookStore --type=helm --helm-chart=https://github.com/akash-gautam/helmcharts/raw/master/book-store-0.1.0.tgz
```

I just tested this and it seems to work, so I'm closing the issue. If you run into any problems with the above, we can re-open!

**Comment by Katiyman** [comment]
@joelanford @camilamacedo86  Thanks for the help seems to work now.
