### ISSUE TITLE
Refactor generator_test.go

### ISSUE THREAD

**Issue by fanminshi** [operator-framework/operator-sdk#252]
Currently, the [`generator_test.go`](https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/generator_test.go) is monolithic where it contains all the tests for code generation; each test ensures that the generated file matches to the expected one. It is hard to navigate through this file and knowing where to add additional tests.

I propose that we break down [`generator_test.go`](https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/generator_test.go) into smaller test files where each test file corresponds to its code generator. In this way, the it is quite clear which test file is corresponding to which function.

For example, the [`gen_main.go`](https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/gen_main.go) that generates the content of `cmd/main.go` file should have a corresponding `gen_main_test.go` test file by moving the [`func TestGenMain(t *testing.T) {}`](https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/generator_test.go#L59) from [`generator_test.go`](https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/generator_test.go) into it.

**Comment by fanminshi** [comment]
Two smaller tasks:
- [ ] Modify `TestGenTypes` to use test constants ref: https://github.com/operator-framework/operator-sdk/pull/260#discussion_r189028527
- [ ] Change the format of testing failure output ref: https://github.com/operator-framework/operator-sdk/pull/260#issuecomment-389935532
cc/ @etiennecoutaud

**Comment by hasbro17** [comment]
@rithujohn191 Are there any more action items related to this issue? If yes we can have @theishshah take over. If not we can close this.

**Comment by rithujohn191** [comment]
None for now. The rest will be handled by @theishshah in his PRs
