### ISSUE TITLE
Any plans to support kubectl plugin ?

### ISSUE THREAD

**Issue by evalsocket** [operator-framework/operator-sdk#2525]
## Feature Request
Context https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/

It would be neat to allow developers to write `kubectl` plugins for their operators. 

**Is your feature request related to a problem? Please describe.**
Every k8s operator developer write some kind of CLI tool to interact with their operator. It would be great idea if operator-sdk provide all tooling for building opertor-cli tool for kubectl plugin. [krew](https://github.com/kubernetes-sigs/krew) is the package manager for these plugins in kubectl ecosystem 

```bash
kubectl sdk new
```

**Describe the solution you'd like**
TBD

**Comment by camilamacedo86** [comment]
Hi @joelanford and @dmesser, 

I think this one requires your eyes on it. 

Note that, what he is looking for is it SDK commands be shipped with kubectl. This is how [kudo](https://kudo.dev/) does as well. See [here](https://kudo.dev/docs/#install-kudo-cli/). Could you please give a hand here? Should we create a proposal for that? WDYT?

**Comment by dmesser** [comment]
I am not sure if the SDK would fit as a kubectl plugin. Primarily it concerns it self with scaffolding, packaging, building, testing and running an Operator - only the latter two are really related to actions happening on a Kubernetes cluster. I think we'd rather look at a plugin that deal with discovering and installing Operators on cluster.

**Comment by evalsocket** [comment]
@dmesser @camilamacedo86  discovering and installing Operators on a cluster will be great and it's an operator-SDK command(addon). Operators are built upon custom logic(custom terminology) which means after installing operators there is only one way to communicate with resources i.e. `kubectl`. But the developer wants to build a custom plugin(who can understand our customer terminology) that uses `controller-runtime`. operator-sdk/kubebuilder  doesn't support plugin that means developers need to build it separately. It's the same feature where we want to scaffold, packaging, building, testing and running the plugin out of the box with operator-sdk.

**Comment by evalsocket** [comment]
We can divide it into two feature
1. operator-sdk plugin with `search` and `install` command for operator discovery (independent to the framework)
2. scaffold, packaging, building, testing and running for `kubectl` plugin who need `controller-runtime` (It's similar to `add controller` command ). ex- `operator-sdk add plugin`

**Comment by dmesser** [comment]
@evalsocket I am interested in the use case of scaffolding a kubectl plugin. Can you give an example of a plugin that needs controller-runtime?

**Comment by evalsocket** [comment]
@dmesser try this use case they are not using `controller-runtime` but they are using `client-go` library. In the above message, I am wrong about the `controller-runtime`. It's a client library that we need to write plugins

**Comment by shawn-hurley** [comment]
If I understand correctly what you want is help to scaffold and potentially some helpers to create a plugin for kubectl that would know how to talk to your operator in new and novel ways. I am thinking of something like is [isitoctl](https://istio.io/docs/reference/commands/istioctl/). 

It seems like we would need to do research into this. I think the [sample](https://github.com/kubernetes/sample-cli-plugin/blob/master/pkg/cmd/ns.go) and [library](https://github.com/kubernetes/cli-runtime) are good places to start.

Do you have a specific plugin that you are attempting to build? It would be good to understand what this feature would need.
