### ISSUE TITLE
Scaffold code and/or provide helper to deploy/manage images

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#2529]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Many operators will at the end have CRD's which will represent a deployment/pod/service of an image:tag. So, I am as oper user I'd like to have a feature to make this process easier.

**Describe the solution you'd like**
- Scaffold code and/or provide a helper to deploy/manage images
- 1 or Many images could be informed in an ENV VAR of the operator.ymal
- Watches and updates status features should be provided easy. 

**Motivation**
- A proposal made in the PR: https://github.com/operator-framework/operator-sdk/pull/2158
- A proposal made in the PR: https://github.com/operator-framework/operator-sdk/pull/2295

**Comment by camilamacedo86** [comment]
From @joelanford  

> we're in the midst of integrating with Kubebuilder such that operator-sdk will soon be generating Go code based on Kubebuilder's scaffolding. The idea is that since Kubebuilder and operator-sdk generate Go projects that heavily depend on controller-runtime, we can join forces on the actual scaffolding of Go project files and we'll make more progress faster working together.
> 
> So having said that, I hesitate to spend much effort doing this for SDK's existing Go scaffolds since we'll be changing those out for Kubebuilder's scaffolds in the next month or two (if all goes to plan).
> 
> [Kubebuilder's controller template](https://github.com/kubernetes-sigs/kubebuilder/blob/55e342048e4381947ffda902f8316b82954ded77/pkg/scaffold/v2/controller/controller.go#L76-L110) is much simpler than SDK's and Kubebuilder already scaffolds a test file alongside the controller, so we may be able to close this with the Kubebuilder integration work.

So, we will probably check how we can address this need after this integration. 
@joelanford @dmesser

**Comment by estroz** [comment]
@zachncst this issue relates to #2158. If you or anyone from the community is still interested in this issue, we can re-open.
