### ISSUE TITLE
Replace deprecated packages from client-go?

### ISSUE THREAD

**Issue by devdattakulkarni** [operator-framework/operator-sdk#254]
NewClientPool function referenced in https://github.com/operator-framework/operator-sdk/blob/master/pkg/k8sclient/client.go#L47

seems to be now deprecated 

https://github.com/kubernetes/client-go/blob/421cf66e414f22e74ac90df608a0ac34811c9ea0/deprecated-dynamic/client_pool.go#L62

**Comment by shawn-hurley** [comment]
It appears that this is deprecated for [k8s 1.11](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.11/release-1.11.md) which has not been released. @spahl @hasbro17 @fanminshi  is this something that you would want to do and get ready for the release? I can do this it if it is.

**Comment by hasbro17** [comment]
@shawn-hurley Feel free to take a stab at it. You would essentially need to bump up the [k8s.io dependencies](https://github.com/operator-framework/operator-sdk/blob/master/Gopkg.toml#L9-L19) to 1.10 first.
And then update how the dynamic client is used, e.g replace [the existing clientpool](https://github.com/operator-framework/operator-sdk/blob/master/pkg/k8sclient/client.go#L66) with [dynamic.NewForConfig()](https://github.com/kubernetes/client-go/blob/master/dynamic/simple.go#L39):
```Go
dc, err := dynamic.NewForConfig(config)
...
resourceClient := dc.Resource(resource).Namespace(ns)
```

This is going to be a big change so make sure you can test out the user-guide example with your changes.

**Comment by joelanford** [comment]
Closing, since this has been fixed and is OBE with switch to controller-runtime in v0.1.0
