### ISSUE TITLE
Operator crashes when --zap-stacktrace-level is used as a CLI parameter

### ISSUE THREAD

**Issue by alex-guenther** [operator-framework/operator-sdk#2542]
## Bug Report

**What did you do?**
I used `--zap-stacktrace-level` as a CLI parameter for my operator and it crashed. I got this from:
https://github.com/operator-framework/operator-sdk/blob/master/doc/user/logging.md

**What did you expect to see?**
I would expect to be using this flag to change when I see stacktraces. Alternatively this parameter could be removed from the doc.

**What did you see instead? Under which circumstances?**

```
unknown flag: --zap-stacktrace-level
Usage of xpro-operator:
      --kubeconfig string                Paths to a kubeconfig. Only required if out-of-cluster.
      --master --kubeconfig              (Deprecated: switch to --kubeconfig) The address of the Kubernetes API server. Overrides any value in kubeconfig. Only required if out-of-cluster.
      --zap-devel                        Enable zap development mode (changes defaults to console encoder, debug log level, and disables sampling)
      --zap-encoder encoder              Zap log encoding ('json' or 'console') (default )
      --zap-level level                  Zap log level (one of 'debug', 'info', 'error' or any integer value > 0) (default info)
      --zap-sample sample                Enable zap log sampling. Sampling will be disabled for integer log levels > 1
      --zap-time-encoding timeEncoding   Sets the zap time format ('epoch', 'millis', 'nano', or 'iso8601') (default )
unknown flag: --zap-stacktrace-level
```

**Environment**
* operator-sdk version:

`operator-sdk version: "v0.15.1", commit: "e35ec7b722ba095e6438f63fafb9e7326870b486", go version: "go1.13.6 linux/amd64"`

* go version:
`go1.13.5 linux/amd64`

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?
I write the Operator in go.

**Possible Solution**

**Additional context**

**Comment by joelanford** [comment]
@alex-guenther This option is currently on `master` but is not released yet. It will be in v0.16.0. The [v0.15.1 docs](https://github.com/operator-framework/operator-sdk/blob/v0.15.1/doc/user/logging.md#default-zap-logger) do not have the option documented.
