### ISSUE TITLE
make dep failing any help on the same ?

### ISSUE THREAD

**Issue by bkannadassan** [operator-framework/operator-sdk#2543]
```
[root@operator-sdk operator-sdk]# make dep
go: github.com/coreos/prometheus-operator@v0.34.0 requires
        github.com/openshift/prom-label-proxy@v0.1.1-0.20191016113035-b8153a7f39f1: invalid pseudo-version: git fetch --unshallow -f https://github.com/openshift/prom-label-proxy in /root/go/pkg/mod/cache/vcs/36ed208787666b452dcb8252277685ddc84bd6f373e697ada8031bc21b94f0b2: exit status 128:
fatal: git fetch-pack: expected shallow list
fatal: The remote end hung up unexpectedly
make: *** No rule to make target `dep'.  Stop.
[root@operator-sdk operator-sdk]#
```
I am facing above issue, any pointers on the same ?.

rgds
Balaji Kamal Kannadassan

**Comment by joelanford** [comment]
@bkannadassan there is no longer a `make dep` target in the Operator SDK Makefile on `master`. Do we have outdated docs somewhere? Can you provide more details about what you're trying to do?

What's the output of `go env`?

**Comment by DarkSkyT9A** [comment]
I am facing the same issue. Any hints on how to solve?

**Comment by nareshdesh** [comment]
Facing the same issue when I run make tidy with the source of master branch
Also even with the binary downloaded from  `https://github.com/operator-framework/operator-sdk/releases/download/v0.17.0/operator-sdk-v0.17.0-x86_64-linux-gnu` , facing the issue with `operator-sdk new`

Error:
`go: github.com/operator-framework/operator-sdk@v0.17.0 requires
        github.com/coreos/prometheus-operator@v0.38.0 requires
        github.com/openshift/prom-label-proxy@v0.1.1-0.20191016113035-b8153a7f39f1: invalid pseudo-version: git fetch --unshallow -f https://github.com/openshift/prom-label-proxy in /code/repo/pkg/mod/cache/vcs/36ed208787666b452dcb8252277685ddc84bd6f373e697ada8031bc21b94f0b2: exit status 128:
        fatal: git fetch-pack: expected shallow list
`


Version:
`go version go1.13.6 linux/amd64`
`operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "unknown", go version: "go1.13.10 linux/amd64"`

**Comment by bvboca** [comment]
check your goproxy env , and change it to GOPROXY=https://proxy.golang.org,direct , if necessary.
