### ISSUE TITLE
Operator SDK doesn't processes items in workqueue simultaneously

### ISSUE THREAD

**Issue by BaluDontu** [operator-framework/operator-sdk#2555]
I see that operator sdk is processing items in workqueue one after the other. 

For example in the sample operator I am working on, the reconciler is taking 5 seconds to process the item in workqueue but items are being added to workqueue every 1 sec. So even though though the 3rd item is added at the end of 2 sec, it is not processed until first 2 items are processed which approx. takes 10 (5+5) sec to process. 

So, I am looking for a way to see if operator SDK provides a way to process these items simultaneously as and when they are added.

**Comment by joelanford** [comment]
@BaluDontu Check out the [`manager.Options` field called `MaxConcurrentReconciles`](https://github.com/kubernetes-sigs/controller-runtime/blob/703858ff1f37d7bf08d48653d1821a0a9fba9c77/pkg/controller/controller.go#L34). You can set this in your controller setup code.

**Comment by joelanford** [comment]
If this doesn't solve it for you, let us know and we can re-open.
