### ISSUE TITLE
go test: mod flag may be set only once

### ISSUE THREAD

**Issue by smiklosovic** [operator-framework/operator-sdk#2556]
Hi,

I am trying to test my operator locally but this is the error I am hitting:

```
$ operator-sdk test local ./test/e2e --up-local --namespace default --go-test-flags "-timeout=20m" --debug --verbose
DEBU[0000] Debug logging is set                         
INFO[0000] Testing operator locally.                    
DEBU[0000] Running []string{"go", "test", "-mod=vendor", "./test/e2e/...", "-namespacedMan", "/tmp/empty.yaml122653018", "-globalMan", "/tmp/global-manifest.yaml427276529", "-root", "/path/tom/my/operator", "-timeout=20m", "-singleNamespace", "-parallel=1", "-localOperator"} 
go test: mod flag may be set only once
run "go help test" or "go help testflag" for more information
Error: failed to build test binary: (failed to exec []string{"go", "test", "-mod=vendor", "./test/e2e/...", "-namespacedMan", "/tmp/empty.yaml122653018", "-globalMan", "/tmp/global-manifest.yaml427276529", "-root", "//path/tom/my/operator", "-timeout=20m", "-singleNamespace", "-parallel=1", "-localOperator"}: exit status 2)
```

It does not matter if I set there `go-test-flags` or I just omit that completely, error is same.

I am on operator-sdk v0.11.0 and go 1.11.13.

**Comment by camilamacedo86** [comment]
Hi @smiklosovic, 

We would need to check what Go version was supported with  `v0.11.0` also. Could you please use the latest version of SDK ( 0.15.x ) with go 1.13+ and let us know if you still facing any issue?

**Comment by smiklosovic** [comment]
I am trying to update to operator 0.13.0 with go 1.13.7, you guys are coding to fast! :)

**Comment by smiklosovic** [comment]
@camilamacedo86 btw there seems to be an error in 0.13 migration guide

https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md#modules-5

This in requires is wrong

```
github.com/operator-framework/operator-sdk v0.13.1
```

There is not such version as 0.13.1

**Comment by camilamacedo86** [comment]
It is a typo issue. It should be ` 0.13.0` instead of ` 0.13.1`. Could you please collab with a PR to fix it?

**Comment by smiklosovic** [comment]
yeah I ll fix it.

I do not want to upgrade to latest / greatest because we need to support operators on clusters as old as 1.14.x and I am not sure what happens when I bump it to 0.15.1, I have not managed to get to that yet.

**Comment by smiklosovic** [comment]
@camilamacedo86 same error with 0.13.0 and go 1.13.7

**Comment by smiklosovic** [comment]
Strangely enough, the solution is to delete `vendor` directory. There is the documentation about go modules in operator's docs which says that deps can be cached to `vendor`. I dont remember I have set that because by default it is said to be false but whatever ... 

Hence having `vendor`dir will automagically add `-mod=vendor` but operator framework is maybe adding more -mod flags and it fails to have multiple of them.

**Comment by camilamacedo86** [comment]
hi @smiklosovic, 

The vendor/dep is no longer supported. So, yes it could cause the issue. 
I am closing this one as solved. Thank you for your reply. 

Please, feel free to let us know if you would like to re-open it for any reason.

**Comment by joelanford** [comment]
Just to be clear, the `vendor` directory _is_ still supported.

Operator SDK detects its presence and automatically adds `-mod=vendor` to the go build and test commands it runs under the hood.

This may be a case where you ALSO have `GOFLAGS` set to include the `-mod=vendor` flag as well. This sounds like https://github.com/golang/go/issues/32471. Can you check to see if that's the case?

**Comment by smiklosovic** [comment]
I have `GOFLAGS` set like this (from `go env`)

```
$ go env | grep FLAG
GOFLAGS=" -mod="
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
....
```
So it seems like it adds `-mod` but if I do not have `vendor` dir, it does nothing / it is empty. Hence if operator somehow adds its own`-mod`, it will be ok as it is as if -mod was ever set in the first place.

**Comment by joelanford** [comment]
> Aha, maybe the problem is that yes, as you suggested, I would have to "unset" GOFLAGS so operator will add its -mod=vendor so -mod is there just once?

Yup! :+1:

If that solves it, I think we can close this issue. If you had `GOFLAGS="-mod=vendor"` we detect that correctly (see https://github.com/operator-framework/operator-sdk/pull/2332), but not `GOFLAGS="-mod="`
