### ISSUE TITLE
Ansible: can we have reconcile interval loop combined with event triggers when resource create/delete/update?

### ISSUE THREAD

**Issue by tomsucho** [operator-framework/operator-sdk#2557]
## Type of question
how to implement a specific feature

## Question
Is it possible to have a period reconcile interval loop timer plus event based triggers for when resources are created, deleted or updated?

**What did you do?**
The following are my observations:
1. When I set "reconcilePeriod: 5m" then I can see reconcile loop runs no matter what happens in my playbook. This is useful in keeping the related resources configured and up to date with the resource spec and also to report their current status conditions. However when I create or delete a resource I'll have to wait 5min to see the effect.
2. When I don't set the "reconcilePeriod: 5m" I can see the reaction to create/delete resource is quicker, less than 1m, but once the playbook run successfully the reconcile loop seem to stop forever. 
3. Setting "reconcilePeriod: 1m" seem like a compromise to have quicker reaction on create/delete but at same time this will trigger a lot of playbook runs, which might be inefficient, flooding related resources with requests. It may become problematic when the operator will have to manage several resources, and needs to run and complete playbooks in under a minute for all of the resources? 

**What did you expect to see?**
I would like to be able to combine both worlds from 1) and 2) above. To have quick reaction on resource create/delete/update, but at same time also to be able to check resources periodically (configurable, say every 5-10min) and make sure they are still up to date, and report their status. Let me know please what you think

**Comment by camilamacedo86** [comment]
Hi @tomsucho
 
Yes, you can. The feature which will allow you to re-trigger the reconcile when something changed ( handle create/delete/update events) is called `watch`. See more info [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md#watches-file). So, you can use the `reconcilePeriod` with the watches config as well.  

 **Example**

```yaml
- version: v1alpha1
  group: app.example.com
  kind: AppService
  playbook: playbook.yml
  reconcilePeriod: 5m
```

So, when an AppService CR be applied/updated/delete the reconcile will be called as each 5m. 

Please, let us know if it was you were looking for and if we can close this one.

**Comment by tomsucho** [comment]
Hi @camilamacedo86 no it does not answer my question. For what I'm thinking about there would have to be two intervals - short one to quickly reconcile create/delete events and then only once something is created it would use the second longer interval just to check if the resource is still alive and up to date. But I don't think this is possible as there is just one global reconcilePeriod timer that can't be changed from the playbook and for a specific resource only?

**Comment by camilamacedo86** [comment]
Hi @tomsucho,

Regards the watch feature will re-trigger the reconcile if anything change. So, if the CR be updated/delete/create then the reconcile will be executed.  

However, regards the option `reconcilePeriod` it will retrigger the playbook/role configured in the watch after X times no matter if have or not changes. 

So, regards:

> I would like to be able to combine both worlds from 1) and 2) above. To have quick reaction on resource create/delete/update, but at same time also to be able to check resources periodically (configurable, say every 5-10min) and make sure they are still up to date, and report their status. Let me know please what you think

So, I  understand that the example provided above would attend your needs. If not, could you please provide the following info. May it will help us understand better your needs and help you more assertively. 

> **What did you do?**
> A clear and concise description of the steps you took (or insert a code snippet).
> 
> **What did you expect to see?**
> A clear and concise description of what you expected to happen (or insert a code snippet).
> 
> **What did you see instead? Under which circumstances?**
> A clear and concise description of what you expected to happen (or insert a code snippet).

**Comment by tomsucho** [comment]
@camilamacedo86
"Regards the watch feature will re-trigger the reconcile if anything change. So, if the CR be updated/delete/create then the reconcile will be executed.

However, regards the option reconcilePeriod it will retrigger the playbook/role configured in the watch after X times no matter if have or not changes."

I'm asking if it is possible to have both of these behaviors combined and working at same time?

**Comment by joelanford** [comment]
@tomsucho 

> I'm asking if it is possible to have both of these behaviors combined and working at same time?

Yes, as @camilamacedo86 explained, the ansible operator will automatically register watches for your CRs and resources created by your operator. These watches will trigger an immediate reconciliation when any of those resources change (you may see a delay if multiple CRs are changing simultaneously since the default maximum concurrent reconciles is 1). This feature is enabled by default, so make sure you don't have `watchDependentResources: false` in your `watches.yaml`.

The `reconcilePeriod` should be in addition to the event-based triggers. Every time a reconciliation happens for a CR, the operator will start a timer based on the reconcile period to reconcile again.

So if you're using this option you should see reconciles at least once every interval AND whenever your CR and dependent resources are created/updated/deleted.

The event-based watches and the reconcilePeriod triggers should work simultaneously.

Can you provide more information about your operator? Logs and information about the CR GVKs and their scope (cluster-scoped vs namespace-scoped) might be helpful.

**Comment by tomsucho** [comment]
indeed it works the way you described, I tested it now and all seem good. I think I used by mistake a wrong image yesterday when testing this and so I couldn't see proper behavior. Thanks for explanations and straightening things up for me :)
