### ISSUE TITLE
Generate validation block for CRDs in OLM catalog

### ISSUE THREAD

**Issue by ericavonb** [operator-framework/operator-sdk#256]
Add [validation](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#validation) schema to the custom resource definitions generated for the OLM catalog.

**Comment by spahl** [comment]
This will need a bit of design

**Comment by mattmb** [comment]
As a newbie I was surprised that this didn't exist already and that it was only a recent addition to k8s itself. It'd be great if running the generate command added the validation section to the YAML definition of the CRD.
