### ISSUE TITLE
Provide possibility to specify imagePullSecret in case of e2e tests on custom image

### ISSUE THREAD

**Issue by smiklosovic** [operator-framework/operator-sdk#2566]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I have a problem to test my operator by e2e framework because my image is in Docker repository I need to authenticate to. Normally, my suspicion is that e2e tests take operator yaml from `deploy` directory. It is possible to specify different image name by `--image` flag for `test` command but since there is not any way how to override credentials, it fails to pull them.

**Describe the solution you'd like**

I would like to specify credentials (imagePullSecrets) for custom image during tests.

EDIT: Specifying `imagePullPolicy` along the way would be nice as well.

**Comment by estroz** [comment]
@smiklosovic can you elaborate on how you would normally deploy your operator? Have you tried adding an [`imagePullSecret`](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret) to your `operator.yaml`?

**Comment by estroz** [comment]
Closing, feel free to re-open with more relevant information.
