### ISSUE TITLE
sample project build using operator-sdk fails 

### ISSUE THREAD

**Issue by davesargrad** [operator-framework/operator-sdk#2569]
## Bug Report

I am following the instructions [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/install-operator-sdk.md) and [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md)

I have operator-sdk installed
**operator-sdk**
![image](https://user-images.githubusercontent.com/48793689/74552552-77c3ed00-4f23-11ea-9fff-27b29c1b27ef.png)

![image](https://user-images.githubusercontent.com/48793689/74554211-f40bff80-4f26-11ea-94ad-358b9ae7e0a9.png)

**Go**
![image](https://user-images.githubusercontent.com/48793689/74553140-b3ab8200-4f24-11ea-8cbf-3e87527afb2e.png)

![image](https://user-images.githubusercontent.com/48793689/74554253-0ede7400-4f27-11ea-8635-1bcee9e2a81b.png)

**k8s**
![image](https://user-images.githubusercontent.com/48793689/74554380-6c72c080-4f27-11ea-9486-87ea45d69523.png)

Per the provided example, I am trying to run the following command
`operator-sdk new memcached-operator --repo=github.com/example-inc/memcached-operator`

I see the following error message:
![image](https://user-images.githubusercontent.com/48793689/74552624-9c1fc980-4f23-11ea-9ca6-c716d4e95adf.png)

The "Get" command seems to reference a URL that is not valid. 

The following was created:
![image](https://user-images.githubusercontent.com/48793689/74554622-f3c03400-4f27-11ea-9737-aba64e64a25a.png)

I get the same problem with this example code:
![image](https://user-images.githubusercontent.com/48793689/74552922-4566bf80-4f24-11ea-8cfa-7ec933a1fbcd.png)

![image](https://user-images.githubusercontent.com/48793689/74552972-557e9f00-4f24-11ea-9c32-2038b5159c9b.png)

![image](https://user-images.githubusercontent.com/48793689/74554481-acd23e80-4f27-11ea-89b6-ced669313cf6.png)

I am using a relatively vanilla install of Centos7

![image](https://user-images.githubusercontent.com/48793689/74553228-e3f32080-4f24-11ea-97e4-38c8d65d3ffb.png)

How do I fix tihs?

**Comment by jmccormick2001** [comment]
can you verify you can reach the proxy https address from within your network?

**Comment by davesargrad** [comment]
Ty Jeff @jmccormick2001 

is there a special way to setup the proxy? I've done the standard export of http_proxy, and https_proxy. But I find that different apps seem to often have their own special way of getting through a proxy.

Does the operator-sdk use http_proxy and https_proxy environment variables? Or does it need something special?

**Comment by jmccormick2001** [comment]
curl https://proxy.golang.org

does that command work on your centos box?

**Comment by davesargrad** [comment]
> curl https://proxy.golang.org
> 
> does that command work on your centos box?

No. Curl itself requires special proxy configuration.. I'll configure curls proxy. Hang a sec.. :)

![image](https://user-images.githubusercontent.com/48793689/74555293-6bdb2980-4f29-11ea-8c97-cf3ba9240d81.png)

**Comment by davesargrad** [comment]
Is this better? 

![image](https://user-images.githubusercontent.com/48793689/74557099-75669080-4f2d-11ea-8d0e-bcd080ef1e88.png)

**Comment by davesargrad** [comment]
Yay.. I'm now good.. Firewall issue... fixed.

Thanks for your fast response

![image](https://user-images.githubusercontent.com/48793689/74558298-0ccce300-4f30-11ea-8ec9-a3917ad3a6d7.png)
