### ISSUE TITLE
Refactoring CRUD functions in sdk package

### ISSUE THREAD

**Issue by devdattakulkarni** [operator-framework/operator-sdk#257]
Currently, various resource functions that make CRUD (and other) calls against the Kubernetes API Server are spread in following three files in the sdk package:

- action.go: Create, Update, Delete
- api.go: Watch
- query.go: Get, List

Is there a reason to keep them separate like this, or can they be combined in a single file?

**Comment by fanminshi** [comment]
They are combined via https://github.com/operator-framework/operator-sdk/pull/242 for now.

**Comment by hasbro17** [comment]
It's just a consequence of the fact that they were all separate packages at initially. #162 

We're currently working on restructuring the SDK into it's logical components to remove all global state #169 and as a result of that we should have better breakdown/grouping of the different modules. For e.g the action and query can just be combined into a CRUD client. So the final layout will change after resolving #169

**Comment by hasbro17** [comment]
Closing this since all the sdk api and client(action and query) are all under the sdk package. This might change later on depending on #162
