### ISSUE TITLE
generated memcache c.Watch in controller does not match user guide 

### ISSUE THREAD

**Issue by bradtopol** [operator-framework/operator-sdk#2572]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).
I ran the operator-sdk and followed the user guide example for generating memcache CRDs and controller.  In the generated memcached_controller.go I expected to see the following as mentioned in the user guide:

err := c.Watch(&source.Kind{Type: &appsv1.Deployment{}}, &handler.EnqueueRequestForOwner{
    IsController: true,
    OwnerType:    &cachev1alpha1.Memcached{},
  })

**What did you see instead? Under which circumstances?**

Instead what I saw in my generated memcached_controller.go I saw the following:
err = c.Watch(&source.Kind{Type: &corev1.Pod{}}, &handler.EnqueueRequestForOwner{
		IsController: true,
		OwnerType:    &cachev1alpha1.Memcached{},
})

**Environment**
* operator-sdk version:
operator-sdk version: "v0.15.0-5-g6b4e137", commit: "6b4e1370f18e5d028b283375b740026d2efb0a44", 

* go version:
go version: "go1.13.3 darwin/amd64"

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**

I would update doc/user-guide.md to instead show what the c.Watch really looks like. So I would update the user guide to instead show this:
err = c.Watch(&source.Kind{Type: &corev1.Pod{}}, &handler.EnqueueRequestForOwner{
		IsController: true,
		OwnerType:    &cachev1alpha1.Memcached{},
})

If you agree this issue is correct I am happy to submit a PR to fix it

**Additional context**

**Comment by bharathi-tenneti** [comment]
Hi @bradtopol . 
Thank you for posting question. As per the user guide, Once scaffold is created, you are supposed to "replace"  memcached_controller.go implementation. Its possible you may have missed this step, and were looking at the original scaffolded file. 

**_This will scaffold a new Controller implementation under pkg/controller/memcached/....

For this example replace the generated Controller file pkg/controller/memcached/memcached_controller.go with the example memcached_controller.go implementation._**

https://github.com/operator-framework/operator-sdk/blob/master/example/memcached-operator/memcached_controller.go.tmpl

Please take a look and let us know of any further concerns.

**Comment by bradtopol** [comment]
Hi @bharathi-tenneti!  Thank you for the helpful response.  Yes, you are correct.  Somehow I missed that step.   Things make a lot more sense now. :-)
