### ISSUE TITLE
invalided pseudo-version reported while building operator-sdk

### ISSUE THREAD

**Issue by elmiko** [operator-framework/operator-sdk#2573]
## Bug Report

**What did you do?**
i was following the [Compile and install from master](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/install-operator-sdk.md#compile-and-install-from-master) instructions in the docs and the make failed.

**What did you expect to see?**
i expected the project to build and to see binaries for operator-sdk.

**What did you see instead? Under which circumstances?**
when i reached the command step that instructs to run `make tidy`, i saw this output:

```
$ make tidy
go: github.com/operator-framework/operator-lifecycle-manager@v0.0.0-20191115003340-16619cd27fa5 requires
        github.com/openshift/api@v3.9.1-0.20190924102528-32369d4db2ad+incompatible: invalid pseudo-version: preceding tag (v3.9.0) not found
go: github.com/operator-framework/operator-lifecycle-manager@v0.0.0-20191115003340-16619cd27fa5 requires
        github.com/openshift/api@v3.9.1-0.20190924102528-32369d4db2ad+incompatible: invalid pseudo-version: preceding tag (v3.9.0) not found
make: *** [Makefile:69: tidy] Error 1
```

**Environment**
* operator-sdk version: master @ 7a3da2f203bab0d6cdca5c050a2544295237518b

* go version: `go version go1.13.6 linux/amd64`

* Kubernetes version information: n/a

* Kubernetes cluster kind: n/a

* Are you writing your operator in ansible, helm, or go? n/a

**Possible Solution**

**Additional context**

**Comment by camilamacedo86** [comment]
Hi @elmiko, 

Could you please try to clean in your local env as follows? 

> $ go clean --modcache
> $ go clean

Then, run make tidy and make install. 

Please, let us know if it solved your scenario.

**Comment by elmiko** [comment]
hi @camilamacedo86,

thanks for the quick response. i tried those clean commands, funnily enough the `go clean` actually returned the same error!

```
$ go clean
go: github.com/operator-framework/operator-lifecycle-manager@v0.0.0-20191115003340-16619cd27fa5 requires
        github.com/openshift/api@v3.9.1-0.20190924102528-32369d4db2ad+incompatible: invalid pseudo-version: preceding ta
g (v3.9.0) not found
```

so, i tried `go clean -cache` and then `go clean` and it worked. next i tried to do the `make tidy` but i hit the same invalid pseudo-version issue.

at this point, i think we can close this issue as it's obviously something wacky with my environment, unless you think there might be a related issue?

**Comment by elmiko** [comment]
oh well, i tried deleting my entire `$HOME/go`, and then rebuilding. same result

```
$ make tidy
go: github.com/operator-framework/operator-lifecycle-manager@v0.0.0-20191115003340-16619cd27fa5 requires
        github.com/openshift/api@v3.9.1-0.20190924102528-32369d4db2ad+incompatible: invalid pseudo-version: preceding tag (v3.9.0) not found
go: github.com/operator-framework/operator-lifecycle-manager@v0.0.0-20191115003340-16619cd27fa5 requires
        github.com/openshift/api@v3.9.1-0.20190924102528-32369d4db2ad+incompatible: invalid pseudo-version: preceding tag (v3.9.0) not found
make: *** [Makefile:69: tidy] Error 1
```

**Comment by elmiko** [comment]
ok, i've made some progress.

i _think_ that due to the go module usage, the `go get` is what messed up. when i checkout this repository to a directory outside of my `$GOPATH` then the `make tidy && make install` will work. so, maybe this should be a doc issue?

**Comment by elmiko** [comment]
i tried this installation method again yesterday, with a freshly installed fedora 31 system and i am still seeing the error, regardless of my build methodology (building in tree or out).

it certainly feels like there is a transitive dependency issue with github.com/openshift/api included by github.com/operator-framework/operator-lifecycle-manager.

**Comment by camilamacedo86** [comment]
HI @elmiko, 

Are you following the above steps and facing any issue? 

```
$ git clone https://github.com/operator-framework/operator-sdk $GOPATH/src/github.com/operator-framework/operator-sdk
$ cd $GOPATH/src/github.com/operator-framework/operator-sdk
$ git checkout master
$ make tidy
$ make install
``` 

If yes, please:
- Check your `GOROOT`.  Try unset GOPROXY
- Check your `GOPROXY`. It should be GOPROXY="https://proxy.golang.org,direct".

If the issue still after that please, let us know the result of `go env `

**Comment by elmiko** [comment]
yes, i was following those instructions.

i checked my `GOROOT` and `GOPROXY`, neither were set. this was on a fresh install of the operating system. i then set `export GOPROXY="https://proxy.golang.org,direct"` and the build worked! :tada: 

i wonder if we should add a note to the documentation about setting `GOPROXY`?

**Comment by camilamacedo86** [comment]
In the GO 1.13+, the GOPROXY is by default `https://proxy.golang.org,direct` so because of this has no need to add in the docs.  For someone reason, your go env was not set up properly.  

Closing this as sorted out.

**Comment by jmccormick2001** [comment]
on Fedora 31, you are required to have GOPROXY set, this is due to the way golang is packaged on Fedora, I found this out when doing the 1.15.0 release on my Fedora server.

**Comment by elmiko** [comment]
@jmccormick2001 is it worth putting a note in the doc about this? (cc @camilamacedo86 )

**Comment by rhmdnd** [comment]
> Hey @elmiko ah! I didn't see it, I think that should be enough. Anyone facing the issue might end up here on this issue so that should be fine. Just linking it here: https://sdk.operatorframework.io/docs/install-operator-sdk/#prerequisites

Installation prerequisite document moved. Updating to make it easier for other readers to follow:

https://sdk.operatorframework.io/docs/installation/
