### ISSUE TITLE
CSV generation: displayName for owned customresources is not automatically added

### ISSUE THREAD

**Issue by miguelsorianod** [operator-framework/operator-sdk#2575]
**What did you do?**
Generate a CSV, upload the CSV and CRDs with operator-courier in a quay.io application repository, deploy a custom catalog pointing to the application repository and try to install the operator once it's available in the catalog.

**What did you expect to see?**
The operator is successfully installed

**What did you see instead? Under which circumstances?**

The operator fails to install. After looking at it, I've observed the InstallPlan has the following error:
```
    message: |-
      error creating csv 3scale-operator-master.v0.0.1: ClusterServiceVersion.operators.coreos.com "3scale-operator-master.v0.0.1" is invalid: []: Invalid value
      ...
      spec.customresourcedefinitions.owned.displayName in body is required
    reason: InstallComponentFailed
    status: "False"
    type: Installed
  phase: Failed
```

It seems for every owned customresourcedefinition, spec.customresourcedefinitions.owned.displayName is required.
Apparently the  `generate csv` command is not adding that field inferring it automatically from the struct field name in the .go file.

If I manually add the line:
```
// +operator-sdk:gen-csv:customresourcedefinitions.displayName="MyDisplayName"
```

CSV annotation I can see then it's added automatically.
If I'm understanding correctly from the documentation (https://github.com/operator-framework/operator-sdk/blob/master/doc/user/olm-catalog/csv-annotations.md) the displayName should be automatically inferred what makes me think this might be a bug.

**Environment**
* operator-sdk version:
```
operator-sdk version: "v0.15.2", commit: "ffaf278993c8fcb00c6f527c9f20091eb8dd3352", go version: "go1.13.3 linux/amd64"
```

* go version:
```
go version go1.13.7 linux/amd64
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.34-202002031224+5cdd27b-dirty", GitCommit:"5cdd27b", GitTreeState:"dirty", BuildDate:"2020-02-03T13:59:07Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+a8c5f5b", GitCommit:"a8c5f5b", GitTreeState:"clean", BuildDate:"2019-08-21T12:56:45Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Are you writing your operator in ansible, helm, or go?

In Go

**Possible Solution**

Infer the displayName automatically for owned resources

**Comment by bharathi-tenneti** [comment]
Hi @miguelsorianod  Can you please provide the command that was used to generate the CSV?

**Comment by miguelsorianod** [comment]
Hi @bharathi-tenneti,

The command was:
```
operator-sdk generate csv --update-crds --csv-version 0.0.1 --operator-name 3scale-operator-master
```

But the same happens when you create a new CSV (without the --update-crds option).

**Comment by estroz** [comment]
@miguelsorianod the docs do not say anywhere that a `customresourcedefinitions[].displayName` is inferred, only `{spec,status}Descriptor.displayName`'s are inferred.

However this inference is trivial (use the kind's type name). Feel free to open a feature request issue!
