### ISSUE TITLE
Ansible: how to expose CR status condition in metrics?

### ISSUE THREAD

**Issue by tomsucho** [operator-framework/operator-sdk#2576]
## Type of question
how to implement a specific feature

## Question
I can see there are some built in metrics endpoints but they provide some overall counts only (like: ansible_operator_reconciles_count or controller_runtime_reconcile_errors_total).
But Is there any way to expose metrics which would allow to quantify how many CRs in Status Condition True|False|Unknown? I think this is sort of a standard as per:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
If we have it as part of the metric label together with CR name and namespace, then one could easily monitor the situation when CR changes status to False|Unknown for example.

**Comment by tomsucho** [comment]
Hey Guys, any thoughts on this one?

**Comment by djzager** [comment]
Disclaimer: not an authoritative source when it comes to controller metrics. I have only tied into the work that @lilic had done to expose custom resource metrics (https://github.com/operator-framework/operator-sdk/pull/1277) for Ansible based operators specifically https://github.com/operator-framework/operator-sdk/pull/1723 and have looked at the [metrics provided by controller-runtime](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/metrics).

Short answer: No. I do not believe that this is currently possible for operator-sdk based operators in general; this issue isn't specific to Ansible.

It looks like kube-state-metrics does something similar for deployments https://github.com/kubernetes/kube-state-metrics/pull/889 but handling this generically for custom resources would probably take some investigation.

**Comment by tomsucho** [comment]
Thanks for checking this. I think it would be a great feature to have :)

**Comment by joelanford** [comment]
Another possible route for having a feature like this would be the hybrid operator approach that we're considering. 

Basically, the idea is that we would work toward making the Ansible (and Helm) operator Go code more reusable and extensible. Then, for example, folks would be able to instantiate an Ansible controller in a Go operator and add custom code to support this kind of thing.
