### ISSUE TITLE
ansible-operator crashes when user not in /etc/passwd: KeyError: 'getpwuid(): uid not found

### ISSUE THREAD

**Issue by lxop** [operator-framework/operator-sdk#2578]
## Bug Report

If the calling user is not present in /etc/passwd, then ansible fails to run, with an output like:
```
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/tmp/ansible-operator/runner/<watched thing>/artifacts/1443635317331776148//stdout
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 63, in <module>
    from ansible.utils.display import Display
  File "/usr/local/lib/python3.6/site-packages/ansible/utils/display.py", line 60, in <module>
    class FilterUserInjector(logging.Filter):
  File "/usr/local/lib/python3.6/site-packages/ansible/utils/display.py", line 65, in FilterUserInjector
    username = getpass.getuser()
  File "/usr/lib64/python3.6/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1000150000'
```

In our case the user is not present in /etc/passwd because it is running in openshift, which picks an arbitrary uid for the container.

**What did you do?**
Set up an ansible operator with not much more than the template provided by operator-sdk.

**What did you expect to see?**
The ansible role run and complete normally

**What did you see instead? Under which circumstances?**
Ansible immediately crashed with a traceback.

**Environment**
* operator-sdk version:

`operator-sdk version: "v0.15.2", commit: "ffaf278993c8fcb00c6f527c9f20091eb8dd3352", go version: "go1.13.3 linux/amd64"`

* go version:

`go version go1.10.4 linux/amd64`

* Kubernetes version information:

`Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-02-18T15:43:04Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind: 

  * Openshift v3.11.0

* Are you writing your operator in ansible, helm, or go?

  * Ansible

**Possible Solution**

Set /etc/passwd to writable in the Dockerfile, then as part of the entrypoint script, add an entry for the currently running user if it doesn't already exist.
https://major.io/2019/03/22/running-ansible-in-openshift-with-arbitrary-uids/
https://blog.openshift.com/jupyter-on-openshift-part-6-running-as-an-assigned-user-id/

**Additional context**
This bug has been rejected by the ansible project as wont-fix: https://github.com/ansible/ansible/issues/39166

This appears to be a regression, based on this report: https://github.com/operator-framework/operator-sdk/issues/1856, which was resolved at the time.

**Comment by lxop** [comment]
I can't quite see how the `quay.io/operator-framework/ansible-operator` image is built, but this may very well be introduced by https://github.com/operator-framework/operator-sdk/pull/2469

**Comment by camilamacedo86** [comment]
Hi @lxop,

First at all, the `Openshift v3.11.0` is not compatible with any SDK version >=`0.9` and it is no longer supported. In this way, I'd like to suggest you use OCP 4.X and/or Minikube. 

Regard your scenario, shows that you built the project with one version and upgrade it with v0.15.2.  Am I right? in this way, you may be missing something as well. 

Then, I'd always recommend you create a new Ansible project from scratch by following the user guide [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md) just to compare with your project and ensure that you updated properly all scaffolded files? Indeed the Dockerfile. Also, you can use it to check if the issue has a bug in the ansible based operators or if it is something related to your project as well. 

If after that, you still facing any issue with your project and an OCP 4.X could you please share a link for your project and/or add here your Dockerfile?

**Comment by lxop** [comment]
Hi @camilamacedo86,

I built the project with v0.15.2 to begin with, following the user guide. After some digging around I tried changing the dockerfile to be based on v0.15.1, and found that it then worked as expected, hence the subsequent comment.

I will try installing OCP 4 and see if that makes a difference.

Thank you

**Comment by camilamacedo86** [comment]
Hi @lxop, 

Thank you for your response, please let us know if it worked for you in OCP 4.X oks?

**Comment by lxop** [comment]
Hi @camilamacedo86,

I am working with OKD, and the preview version of v4 for that is presenting challenges, so I am unable to see if this problem exists in v4 at this stage. I'll simply have to stick to v0.15.1 for the time being.

Thank you

**Comment by camilamacedo86** [comment]
HI @Ixop, 

Note that the 3.11 is old and is using an old version of k8s API which is no longer compatible with any SDK version >= 0.9, in this way, we may face other issues as well and we cannot say what feature will work or not exactly. 

In this way, I truly recommend you use OCP 4.X or Minikube instead of, for example, which is very easy to install locally. Also, we could check that this change passes successfully in all CI jobs which teste it with OCP 4.X so I am closing this one since all lead us to believe that it is probably regards its usage with 3.11. 

However, please to re-open if you see that is required.

**Comment by magick93** [comment]
I'm in the same situation, and am getting the same error.

Its a shame to see support for 3.11 being abandoned with OKD 4x is only in alpha.

**Comment by camilamacedo86** [comment]
HI  @magick93, 

The OCP 3.11 uses and old version of the k8s api lib and then because of this is not possible to keep the compatibility with.  Also, I understand that this project will not be upgraded too. 

See that the issue described here is fixed at 0.15.2 of  SDK as well which again is not compatible with 3.11. I'd recommend you use Minikube to do local tests since it is very easy to install too.

**Comment by jmontleon** [comment]
FWIW, since we're supporting migrations from anywhere back to 3.7 we've had to have our operator working at least that far back.

the passwd errors can be fixed with an adjusted entrypoint script.

https://github.com/konveyor/mig-operator/blob/master/build/entrypoint

**Comment by oweise** [comment]
Just to note it here: In that specific situation this error can also be bypassed by giving an env var USERNAME to the container, as the python method getuser() prefers to read that: 

```
def getuser():
    """Get the username from the environment or password database.

    First try various environment variables, then the password
    database.  This works on Windows as long as USERNAME is set.

    """

    for name in ('LOGNAME', 'USER', 'LNAME', 'USERNAME'):
        user = os.environ.get(name)
        if user:
            return user

    # If this fails, the exception will "explain" why
    import pwd
    return pwd.getpwuid(os.getuid())[0]
```
