### ISSUE TITLE
Read(List/Get) objects from the informer cache

### ISSUE THREAD

**Issue by devdattakulkarni** [operator-framework/operator-sdk#258]
Currently the SDK provides a List function
https://github.com/operator-framework/operator-sdk/blob/master/pkg/sdk/query.go#L59

which is used to setup the List and Watch
https://github.com/operator-framework/operator-sdk/blob/master/pkg/sdk/informer.go#L65

when creating the SharedIndexInformer
https://github.com/operator-framework/operator-sdk/blob/master/pkg/sdk/informer.go#L54

The sample-controller approach (https://github.com/kubernetes/sample-controller) uses 'Listers'
https://github.com/kubernetes/sample-controller/blob/master/pkg/client/listers/samplecontroller/v1alpha1/foo.go#L48

for querying Objects from the local Index.

So I was wondering why Listers are not included in the design of the SDK?

Using a List function which always makes call to the API server can cause load on the server. 
Listers would help reduce these calls, no?

**Comment by spahl** [comment]
Holding off until #169 is done. This will also probably require a bit of discussion about design.

**Comment by hasbro17** [comment]
Resolved via #382 
See the [default client doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/client.md#default-client) or the [delegating client](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/client#DelegatingClient) for more details.
