### ISSUE TITLE
csv generation ends in an unclear error

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/operator-sdk#2583]
## Bug Report

**What did you do?**
operator-sdk generate csv --csv-channel alpha --default-channel --csv-version 0.0.1 --update-crds

**What did you expect to see?**
Complete CSV generation without errors 

**What did you see instead? Under which circumstances?**
INFO[0000] Generating CSV manifest version 0.0.1
INFO[0000] No TypeMeta in deploy/crds/cms.solute.us_syncs_crd.yaml, skipping file
INFO[0000] Skipping manifest cms.solute.us/v1beta1, Kind=Sync
INFO[0000] Created deploy/olm-catalog/sync-operator/0.0.1/sync-operator.v0.0.1.clusterserviceversion.yaml
FATA[0000] error getting TypeMeta from bytes: error converting YAML to JSON: yaml: line 23: mapping values are not allowed in this context

**Environment**
* operator-sdk version:
operator-sdk version: "v0.15.2", commit: "ffaf278993c8fcb00c6f527c9f20091eb8dd3352", go version: "go1.13.3 linux/amd64"

**Possible Solution**
If this is related to the CSV that is generated, line 23 is `strategy: {}` under spec.install.spec.deployments.spec. which I believe is a default value. 

If this is related to the CRD, line 23 is spec.validation.openAPIv3schema.description's apiVersion. It has description and type: string under it. 

**Additional context**
I have the openAPI validation stuff in the CRD so am wondering if that is related, but if I remove the entire validation section, it still shows this error.

**Comment by flickerfly** [comment]
This error turned out to be rouge tabs in the YAML for the CRD. I should have yamllint'd the mess before I reported, but it would be nice if the error indicated the file where the problem is and that it was a syntax issue.

**Comment by estroz** [comment]
@flickerfly agreed, we should at least provide line/col error information on YAML formatting errors. Doing so probably requires an audit of where `operator-sdk` is unmarshalling YAML from files in SDK code to see if we can return better error messages, or if error reporting in the libraries we're using (`github.com/ghodss/yaml` mostly) is too opaque to do so. `operator-sdk` consumes a lot of YAML manifests generated by users, so this is a nice-to-have.

/kind feature
/help-wanted
/good-first-issue

**Comment by varshaprasad96** [comment]
Hi @flickerfly 
I was working on this issue and these are some of the things I noticed.

When there is any issue with the generated yaml files from the command, the following error message is returned by the Operator SDK:
```catalog scaffold failed: error unmarshalling CSV deploy/olm-catalog/memcached-operator/0.0.1/memcached-operator.v0.0.1.clusterserviceversion.yaml: error converting YAML to JSON: yaml: line 42: did not find expected key```

Here, the name of the file and respective line is displayed.

However, the `generate csv` command also tries to parse the crds present in the `deploy/crds` folder. When there is any error caused during the unmarshalling of these yaml files, the error returned is not clear as you had pointed out. 
It is similar to what you had obtained: 
```FATA[0000] error getting TypeMeta from bytes: error converting YAML to JSON: yaml: line 3: mapping values are not allowed in this context```.

I have created a PR to fix this. With it the SDK would return the path of the file where the error has occurred which would be helpful in debugging. Hope this solves the issue.

Please let me know if there are any questions or concerns related to the this.

**Comment by flickerfly** [comment]
That's great! It should help a good deal.
