### ISSUE TITLE
Update Ansible molecule tests to be compatible with Molecule v3

### ISSUE THREAD

**Issue by geerlingguy** [operator-framework/operator-sdk#2588]
## Feature Request

**Is your feature request related to a problem? Please describe.**

[Molecule 3 was released](https://github.com/ansible-community/molecule/issues/2560) yesterday, and requires some changes for molecule configurations which were valid in v2.

I am updating my own Ansible-based operators to work with Molecule 3 (examples: [tower-operator](https://github.com/geerlingguy/tower-operator/commit/27b8ba968ebd1374d7dff5532f96e3fc94a2d2ea), [mcrouter-operator](https://github.com/geerlingguy/mcrouter-operator/commit/8b3ab5e51d7a7e2ea54fd5cf7fb590fd1548fb87)), and I've seen a few things are required:

  1. Since yamllint configs are no longer built into molecule, we can template a `.yamllint` file into the project root with the required rule adjustments (e.g. line length).
  2. linting is no longer fully managed by Molecule, but we can add something like the following to run `yamllint` and `ansible-lint`, if desired:

     ```yaml
     lint: |
       yamllint .
       ansible-lint
     ```

  3. The converge 'playbook.yml' is now named 'converge.yml' by default. (Molecule pops a warning if you don't name it 'converge.yml')
  4. The `platforms.provisioner.lint` configuration in `molecule.yml` is no longer used and should be dropped.
  5. The `scenario.name` parameter in `molecule.yml` is no longer used and should be dropped.

**Describe the solution you'd like**

In addition to fixing the above points, I think it would be nice to have `yamllint` and `ansible-lint` enabled by default, and to make sure the templated files that we build for users pass—mostly it's a matter of fixing values like:

```yaml
something:
- list
- of
- items
```

to be:

```yaml
something:
  - list
  - of
  - items
```

Having linted files will make it easier to ensure projects are more uniformly formatted across the board, which makes cross pollination a bit easier, and sets the bar for future contributions.

**Comment by camilamacedo86** [comment]
Hi @geerlingguy, 

Thank you for your contribution. I'd like to say that you are welcome to contribute with a PR which will upgrade the molecule version as well too. 

JFY @fabianvf
