### ISSUE TITLE
User guide should provide more clarity on registry push step

### ISSUE THREAD

**Issue by bradtopol** [operator-framework/operator-sdk#2592]
## Feature Request

**Is your feature request related to a problem? Please describe.**
In the user guide there is a step when it is time to build the memcached-operator image and push it to a registry.  The user guide provides the following instruction:
"Build the memcached-operator image and push it to a registry"

In the example that follows the above statement quay.io is used.   If the person following the user guide blindly runs the build command and the docker push command and does not have a quay account, the step will fail.  

**Describe the solution you'd like**
It would be nice to have a sentence or two that informs the reader that in order for the build and docker push to succeed,  they need to create their own account on a container registry such as quay.io or docker hub, and that they need to change the quay.io/example/  found in the build and push commands in the user guide to be the name of a valid repository for repo site such as quay.io or docker hub.

If you agree this would be helpful, I am happy to open a PR and take a shot at writing up a few sentences to address this issue.

**Comment by camilamacedo86** [comment]
Hi @bradtopol, 

Really thank you for you collaboration and inputs. Please, feel free to create PRs with your suggestions and ideas. You are very welcome and please let us know if you need any help with.

**Comment by bradtopol** [comment]
Thanks for the feedback @camilamacedo86.  I will create the PR.
/assign
