### ISSUE TITLE
User guide should provide more clarity on reconcile.Result and requeue options used by memcache operator example 

### ISSUE THREAD

**Issue by bradtopol** [operator-framework/operator-sdk#2593]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The user guide provides the following description of reconcile.Result and requeue options used by memcache operator example:

// Reconcile successful - don't requeue
return reconcile.Result{}, nil
// Reconcile failed due to error - requeue
return reconcile.Result{}, err
// Requeue for any reason other than error
return reconcile.Result{Requeue: true}, nil

Unfortunately, while the memcache operator example shows the above options being used, it does explain the reasoning for why each choice was used in different portions of memcached_controller.go

It would be very helpful to folk who are new at writing operations to explain why each reconcile.Result option was chosen for each portion of code in memcached_controller.go
A clear and concise description of what the problem is. Example: "I have an issue when (...)"

**Describe the solution you'd like**
I would like to see a short paragraph added to the user guide that explains why each reconcile.Result option is chosen for the situations encountered in memcached_controller.go.

I am willing to add this paragraph if this issue is approved.  I may need some guidance to make sure why I think each option is being used is actually correct.

**Comment by camilamacedo86** [comment]
Hi @bradtopol,

Please, feel free to create any PRs with your suggestions and ideas. 
It will be great and you are 100% welcome. Please, let us know if you need any help with.

**Comment by bradtopol** [comment]
Thanks @camilamacedo86!  I will create the PR.
/assign
