### ISSUE TITLE
OLM related sub commands don't work with openshift 4.x cluster

### ISSUE THREAD

**Issue by jeyaramashok** [operator-framework/operator-sdk#2595]
## Bug Report

**What did you do?**

operator-sdk subcommands that interact with olm fails. Even though the OLM is installed in the cluster.

```
$ operator-sdk olm status --verbose
DEBU[0000] Debug logging is set
FATA[0002] Failed to get OLM status: no existing installation found

$ operator-sdk run --olm --operator-version 0.1.0 --manifests /Users/jey/workspace/go/src/github.ibm.com/jashokr/pingpong-operator/deploy/olm-catalog/pingpong-operator/0.1.0
INFO[0000] loading Bundles dir=/Users/jey/workspace/go/src/github.ibm.com/jashokr/pingpong-operator/deploy/olm-catalog/pingpong-operator/0.1.0
...
FATA[0001] Failed to run operator using OLM: error getting installed OLM version: no existing installation found
```

I noticed this works with minikube or vanilla kubernetes cluster with OLM installed manually. 

Upon debugging, I figured out that's because the olm namespace is hardcoded to `olm` here https://github.com/operator-framework/operator-sdk/blob/master/internal/olm/client/client.go#L45

But on openshift cluster its installed default in `openshift-operator-lifecycle-manager` namespace, whereas if you choose to [install OLM manually](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/install/install.md), it gets installed in `olm` namespace

**Environment**
* operator-sdk version:
```
$ operator-sdk version
operator-sdk version: "v0.15.0-42-g7a3da2f2", commit: "7a3da2f203bab0d6cdca5c050a2544295237518b", go version: "go1.13.8 darwin/amd64"
```
**Possible Solution**

Suggestion: Should the OLM namespace be configurable using a flag?

**Additional context**

**Comment by camilamacedo86** [comment]
Hi @jeyaramashok, 

Thank you for raise it. We will be looking at it.

**Comment by estroz** [comment]
@jeyaramashok thanks for filing this issue. We should have assumed another namespace could be used instead of hard-coding `"olm"`. An `--olm-namespace=<string>` flag should be sufficient, with a default of `"olm"`. Care to take a crack at this? If not another I can make a PR.

**Comment by jeyaramashok** [comment]
@estroz thanks. that's what I thought as well. Yes I'm interested in creating a PR for this. (using `--olm-namespace`)

**Comment by jeyaramashok** [comment]
@estroz thanks. that's what I thought as well. Yes I'm interested in creating a PR for this. (using `--olm-namespace`)

**Comment by jeyaramashok** [comment]
@estroz created this PR https://github.com/operator-framework/operator-sdk/pull/2613 , pls let me ur thoughts on this.

I was not sure if I had to add any tests, I could not find one. Pls point to any tests if needs to be updated.
