### ISSUE TITLE
 operator-sdk up local how to set the ENV variable

### ISSUE THREAD

**Issue by Katiyman** [operator-framework/operator-sdk#2600]
I am trying to debug my operator by running it outside the cluster.
I am trying to read some env variables in the code
but i don't know how to set them.

Below is the DOCKERFILE
`**FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

ENV OPERATOR=/usr/local/bin/domainproxy-operator \
    USER_UID=1001 \
    USER_NAME=domainproxy-operator \
    RESREQ_DIR=/usr/src/app/resource-reqs \
    DEPLOYMENT_DIR=/usr/src/app

COPY deployment/helm /usr/local/bin/helm
COPY deployment/dp-deployment /usr/src/app/dp-deployment
COPY deployment/resource-reqs /usr/src/app/resource-reqs

RUN chmod -R 770 /usr/src/app/

COPY build/_output/bin/domainproxy-operator ${OPERATOR}

COPY build/bin /usr/local/bin
RUN  /usr/local/bin/user_setup

ENTRYPOINT ["/usr/local/bin/entrypoint"]

USER ${USER_UID}**
`
Error
> "error":"RESREQ_DIR is not set","errorVerbose":"RESREQ_DIR is not set

Kindly help 
Thanks

**Comment by camilamacedo86** [comment]
Hi @Katiyman, 

The ENV VARs can be set in the `deploy/operator.yaml`. Following an example:

```
      env:
            - name: ENVAR
              value: "" 
```

Closing it as sorted out. However, please let us know if you think that it needs to be kept open.

**Comment by Katiyman** [comment]
@camilamacedo86  i will try this and update .. thanks

**Comment by lenardchristopher** [comment]
For anyone looking for a good way to use environmental variables with operator-sdk, I wrote up a post about my solution here: https://dev.to/chrislenard/debug-and-test-operator-sdk-in-vs-code-1gib
