### ISSUE TITLE
unable to retrieve the complete list of server APIs (fixed in helm 3.0.2)

### ISSUE THREAD

**Issue by mikeshng** [operator-framework/operator-sdk#2614]
## Bug Report

**What did you do?**
https://github.com/helm/helm/issues/6361
The current helm version `helm.sh/helm/v3 v3.0.1` contains an issue described in the above URL.

It's claimed to be fixed in `3.0.2` https://github.com/helm/helm/issues/6361#issuecomment-578921598

Could you please move up the version to `3.0.2`?

**What did you expect to see?**
Not see the `unable to retrieve the complete list of server APIs` error when I delete an helm operator CR.

**What did you see instead? Under which circumstances?**
The error: "unable to retrieve the complete list of server APIs"

**Environment**
* operator-sdk version:
master

* go version:

`go version go1.13.5 linux/amd64`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2020-01-14T00:28:37Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
`kind`

* Are you writing your operator in ansible, helm, or go?
`go`

**Possible Solution**
Please move up the version to `3.0.2`

**Additional context**

**Comment by jmrodri** [comment]
Fixed by PR #2621
