### ISSUE TITLE
Error: unknown flag: --watches-file

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#2615]
From channel:

I'm seeing this in our CI runs:
```
Error: unknown flag: --watches-file
Usage:
  operator-sdk run [flags]
Flags:
      --kubeconfig string         The file path to kubernetes configuration file. Defaults to location specified by $KUBECONFIG, or to default file rules if not set
      --namespace string          The namespace where the operator watches for changes.
      --olm                       The operator to be run will be managed by OLM in a cluster. Cannot be set with another run-type flag
      --manifests string          [olm only] Directory containing package manifest and operator bundles.
      --operator-version string   [olm only] Version of operator to deploy
      --install-mode string       [olm only] InstallMode to create OperatorGroup with. Format: InstallModeType=[ns1,ns2[, ...]]
      --include strings           [olm only] Path to Kubernetes resource manifests, ex. Role, Subscription. These supplement or override defaults generated by run/cleanup
      --timeout duration          [olm only] Time to wait for the command to complete before failing (default 2m0s)
      --local                     The operator will be run locally by building the operator binary with the ability to access a kubernetes cluster using a kubeconfig file. Cannot be set with another run-type flag.
      --operator-flags string     [local only] The flags that the operator needs. Example: "--flag1 value1 --flag2=value2"
      --go-ldflags string         [local only] Set Go linker options
      --enable-delve              [local only] Start the operator using the delve debugger
  -h, --help                      help for run
Global Flags:
      --verbose   Enable verbose logging
```
I'm having a hard time following when this flag was removed from the cmd/operator-sdk/run code

**Comment by camilamacedo86** [comment]
Hi @estroz, 

This came from the channel. I was looking and shows that we remove the flag  here: https://github.com/operator-framework/operator-sdk/pull/2441

However, I am still facing the flag in the doc [sdk-cli-reference](https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#run) and I was not able to find this [CHANGELOG.md](https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md). 

In this way, I decide to raise the issue here for:
- Verify if it should be removed ( I understand that yes )
- Update the doc  [sdk-cli-reference](https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#run) by replacing it for `exec-entrypoint ansible --watches-file=/opt/ansible/watches.yaml`. 
- Add a retroactive entry in the changelog with the breaking change. 

Please, let me know if I misunderstood something here.

**Comment by timflannagan1** [comment]
For more context, this is the entrypoint to our ansible-based Operator: https://github.com/operator-framework/operator-metering/blob/master/images/metering-ansible-operator/scripts/entrypoint.sh

I'm able to build and run our origin images locally fine, and the problem only occurs when CI is building and using our OCP images. As a next step, I can try and build the OCP images locally, replacing the `... run ansible --watches-file` with the `exec-entrypoint ansible --watches-file` and hopefully that resolves this issue.

**Comment by camilamacedo86** [comment]
Hi @timflannagan1, 

If you are using the 0.15.x then you entrypoint.sh need to be updated as [here](https://github.com/operator-framework/operator-sdk/blob/v0.15.x/internal/scaffold/ansible/entrypoint.go)

**Comment by estroz** [comment]
The `run` -> `exec-entrypoint` name change is already a breaking change in the changelog. We need to update the release notes and migration guide for `v0.15.x`.
