### ISSUE TITLE
operator-sdk test should be able to run inside Kubernetes cluster

### ISSUE THREAD

**Issue by rodrigovalin** [operator-framework/operator-sdk#2618]
## Feature Request

**Is your feature request related to a problem? Please describe.**

We are using `operator-sdk` to run our operator' e2e tests, unfortunatelly, the operator-sdk expect the tests to be run "locally", and expects a `--kubeconfig` flag to be set. Our use case involves running the tests inside Kubernetes, as Pods, in which case there is not `kubeconfig` file. However, operator-sdk should be capable of configuring itself, by using the Kubernetes environment.

**Describe the solution you'd like**
operator-sdk should be able to run tests inside a Kubernetes cluster (in a Pod), by configuring itself using `client-go`'s [InClusterConfig](https://github.com/kubernetes/client-go/blob/master/rest/config.go#L451).

**Comment by camilamacedo86** [comment]
Hi @rodrigovalin, 

To test your operator we recommend you implement unit tests and or e2e test as described in https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/writing-e2e-tests.md. 

Also, as an alternative, you can use shell scripts as well. 

Please, let me know if the information provided answered your question and if we can close this one.

**Comment by camilamacedo86** [comment]
Also, regards the RFE raised here, I am afraid that it would not be possible to be executed from inside of the cluster as you suggested. Note that when the operator is running in a cluster the info will be obtained from the Pod where it is running  (cfg, err := config.GetConfig()) and it will not be the same and then, any solution would indeed need to support MultiCluster configuration. 

Also, in POV if you would like to test the project by deploying all in the cluster then you can use a shell script, for example, to achieve it and this command is not required at all. 

I am adding the label "needs-discussion" to just allow others also add their point of view here as well. 

c/c @shawn-hurley @hasbro17 @estroz   WDYT?

**Comment by chatton** [comment]
Hi @camilamacedo86, 

In this case we want the pod we deploy to run `operator-sdk test local` to not need to require a `--kubeconfig` value if the pod itself is inside the cluster.

When trying this on the v0.15.2, with the test pod deployed in the same cluster and namespace as the operator, we get the following error.

```
time="2020-03-05T13:16:26Z" level=debug msg="Debug logging is set"
time="2020-03-05T13:16:26Z" level=info msg="Testing operator locally."
time="2020-03-05T13:16:26Z" level=debug msg="Running []string{\"go\", \"test\", \"./test/e2e/...\", \"-namespacedMan\", \"/tmp/namespaced-manifest.yaml322143224\", \"-globalMan\", \"/tmp/global-manifest.yaml681829111\", \"-root\", \"/go\", \"-singleNamespace\", \"-parallel=1\"}"
time="2020-03-05T13:17:14Z" level=fatal msg="Failed to create framework: failed to build the kubeconfig: invalid configuration: no configuration has been provided"
```

Looking at the code, it looks like if no `--kubeconfig` value is passed, it doesn't fall back on a config from the existing cluster (i.e. no `cfg, err := config.GetConfig()`)

I'm not sure I understand why this shouldn't be possible to be executed from inside the cluster.

Everything works as expected when a kubeconfig filed mounted into the pod and provided via `--kubeconfig`.

**Comment by camilamacedo86** [comment]
HI @chatton, 

> We are using operator-sdk to run our operator' e2e tests, unfortunatelly, the operator-sdk expect the tests to be run "locally", and expects a --kubeconfig flag to be set. Our use case involves running the tests inside Kubernetes, as Pods, in which case there is not kubeconfig file. However, operator-sdk should be capable of configuring itself, by using the Kubernetes environment.

If your KUBECONFIG be in the default place `$HOME/.kube/config` then, I understand that it will work without the flag. Could you please verify and let us know? 

> operator-sdk should be able to run tests inside a Kubernetes cluster (in a Pod), by configuring itself using client-go's InClusterConfig.

Regards your RFE, could you please let us know: What is the scenario that you would to achieve by using `operator-sdk test` running the operator inside of the cluster that you cannot achieve currently?

**Comment by chatton** [comment]
Hi @camilamacedo86, 

The location of the kubeconfig file isn't a concern for us, it's the fact that it needs to provided in order for the test to correctly run from inside the kubernetes cluster. Overhead is introduced in ensuring the correct kubeconfig file is in the correct location.

The ideal scenario for us is if we don't need to configure any kubeconfig files at all (which need to be checked that they will be valid when placed into the pod they will then need to be mounted into.)

When running the operator-sdk test command from inside a kubernetes cluster, it should not need to be provided with a kubeconfig file (it should be able to know that based on the cluster it is currently in).

I believe this should be possible using the `cfg, err := config.GetConfig()` you mentioned before.

**Comment by camilamacedo86** [comment]
HI @chatton, 

Note that: 

> The ideal scenario for us is if we don't need to configure any kubeconfig files at all

You will not need to configure the kubeconfig if it is configured in the default place `$HOME/.kube/config`

  
Sorry, but could you please help us understand what is the requirement that makes required you run the test inside of the cluster as you request? What is the scenario that it is not achievable with it as it is currently?  Could please let us know?

**Comment by rodrigovalin** [comment]
Hello @camilamacedo86,

Our current CI environment runs workloads inside Kubernetes clusters, ultimatelly as Pods (as part of a Deployment or, in this case, a Job). The `operator-sdk` functionality is planned to be used inside a Kubernetes cluster, in particular the `operator-sdk test`. In a Pod environment, there is not `$HOME/.kube` directory, but the clients are expected to configure themselves by using incluster configuration.

Unfortunatelly, `operator-sdk` won't be able to configure itself if running inside a Pod in a Kubernetes cluster environment, because it relies on the existence of the `$HOME/.kube` directory, which does not exist. To overcome this limitation, we manually create a kubeconfig file that is mounted into the Pod, which is exactly what we are trying to avoid.

Related to your question about our requirement to run tests inside a cluster, it is because that's our design. For our operator, everything runs in a Kubernetes cluster, including the CI environment *and* the E2E tests runners.

And as your second question. This scenario is achievable by the mechanism described (mounting a manually constructed kubeconfig file into the Pod), but it is not ideal, knowing that the Kubernetes client's code the `operator-sdk` relies on allow in-cluster clients.

**Comment by camilamacedo86** [comment]
Hi @rodrigovalin, 

The `operator-sdk test` is not designed to run inside of the cluster and I'd not recommend you upload a kubeconfig to do it. 

I understand that has not any scenario case that is no achievable with the current implementation, I mean has NOT any need that would only be achievable by allowing the `operator-sdk test` rus the operator inside of the cluster as argumentation for this change be made. Am I right?

**Comment by camilamacedo86** [comment]
Hi @rodrigovalin, 

The request made here is a significant change in the design of this feature as also would be required to evaluate its impacts as viability.  

Note that we have been working to provide improvements in the features to test the projects. See for example the proposals; https://github.com/operator-framework/operator-sdk/pull/2624 and https://github.com/operator-framework/operator-sdk/blob/master/doc/proposals/operator-testing-tool.md. 

In the future when we have integrated Kubebuilder scaffolding, as you can check in the proposal: https://github.com/operator-framework/operator-sdk/blob/master/doc/proposals/kubebuilder-integration.md, this area might be affected as well. And then, we are really looking for changes in the design to bring more flexibility to our users. 

However, IMO for we accepted your request at the current moment we would need at least 1 scenario which justifies and motivate this change. I mean, at least one scenario that cannot be solved and is not achievable with the current design implementation of it. 

Because of this, in the meantime, I would suggest that we close this one and I will do it.  However, please feel free to re-open if you think that it is required as you are very welcome to create any proposal for the project to attend your needs. 

Really thank you for your collaboration with.
