### ISSUE TITLE
Ansible: verbosity level 0 doesn't seem to work

### ISSUE THREAD

**Issue by tomsucho** [operator-framework/operator-sdk#2627]
## Bug Report

**What did you do?**
I tried using verbosity level 0 via:
- annotation on the CR:
  "ansible.operator-sdk/verbosity": "0"
- operator args:
            args:
            - "--ansible-verbosity"
            - "0"
to control what is getting into the logs, but it doesn't seem to work i.e. getting operator errors like:

`{"level":"error","ts":1583486711.1724753,"logger":"runner","msg":"usage: ansible-runner [-h] [--version] [-m MODULE | -p PLAYBOOK | -r ROLE]\n                      [-b BINARY] [--hosts HOSTS] [-i IDENT]\n                      [--rotate-artifacts ROTATE_ARTIFACTS]\n                      [--roles-path ROLES_PATH] [--role-vars ROLE_VARS]\n                      [--role-skip-facts] [--artifact-dir ARTIFACT_DIR]\n                      [--project-dir PROJECT_DIR] [--inventory INVENTORY]\n                      [--forks FORKS] [-j] [-v] [-q] [--cmdline CMDLINE]\n                      [--debug] [--logfile LOGFILE] [-a MODULE_ARGS]\n                      [--process-isolation]\n                      [--process-isolation-executable PROCESS_ISOLATION_EXECUTABLE]\n                      [--process-isolation-path PROCESS_ISOLATION_PATH]\n                      [--process-isolation-hide-paths PROCESS_ISOLATION_HIDE_PATHS]\n                      [--process-isolation-show-paths PROCESS_ISOLATION_SHOW_PATHS]\n                      [--process-isolation-ro-paths PROCESS_ISOLATION_RO_PATHS]\n                      [--directory-isolation-base-path DIRECTORY_ISOLATION_BASE_PATH]\n                      [--limit LIMIT]\n                      {run,start,stop,is-alive} private_data_dir\nansible-runner: error: argument command: invalid choice: '' (choose from 'run', 'start', 'stop', 'is-alive')\n","job":"2015796113853353331","name":"(I removed)","namespace":"(I removed)","error":"exit status 2","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/runner.(*runner).Run.func1\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/runner/runner.go:217"}
{"level":"error","ts":1583486711.1727486,"logger":"reconciler","msg":"Failed to get ansible-runner stdout","job":"2015796113853353331`

**What did you expect to see?**
My plan was to have the ability to control amount of logging as with verbosity 1 there's quite a lot of data printed from a single run of my playbook. For example when looping over a list containing few dozens of big dictionaries, there's all printed and even if I use no_log: True it still prints this useless line "output was censored" for each item in a loop...
With level 0 logging by default I would still be getting each loop item printed, but could use loop_control to print something useful & harmless (since there seem to be no way to stop printing items in a loop in Ansible...), and so I could limit the output to just item.name so a single dict key would be printed and not the whole dict.

**What did you see instead? Under which circumstances?**
Errors occur and reconciliation is not happening at all.

**Environment**
* operator-sdk version: 0.15.2

**Comment by camilamacedo86** [comment]
Hi @tomsucho, 

Following the comments inline. 

Regards `- "--ansible-verbosity"`:

This annotation change the verbosity of Ansible logs and not of the Operator. You added here the Operator logs and not the Ansible ones. The Ansible logs until this version are in the ansible container. Following an example:

- Use the following command to check the operator logs.
`kubectl logs deployment.apps/<name>-operator -c operator -n <namespace>`
- Use the following command to check the Ansible logs.
`kubectl logs deployment.apps/<name>-operator -c ansible -n <namespace>`

Regards `there's all printed and even if I use no_log:`

The `no_log` is valid just for Molecule and will not change the Operator logs. 

And we have not an option for you to change the Operator logs level of verbose in this case. @fabianvf do you think that we could track an RFE for we allow users to configure the zap level [here](https://github.com/operator-framework/operator-sdk/blob/master/internal/scaffold/cmd.go#L107)?

**Comment by tomsucho** [comment]
> This annotation change the verbosity of Ansible logs and not of the Operator. 
that was my intention to limit logs in Ansible container, however when I set that to 0 it didn't work at all - the operator itself logs errors when kicking-off reconcile loop event and so no playbook gets even executed (and as a result no logs at all in Ansible container, but that's not how it should work ;-) at level 0 there should be still some minimal log for each task in a Play)

**Comment by camilamacedo86** [comment]
Hi @tomsucho, 

The Operator Logs are not the same as Ansible Logs. The Ansible Logs came from the ansible used on it when the Operator logs are provided by the operator/controller which is built.  

In this way, the purpose of `--ansible-verbosity` will change it just for Ansible logs, which mean the logs that came from it and you can check in the ansible container.

**Comment by tomsucho** [comment]
@camilamacedo86 
yes I know all that, but what I'm trying to say is when I set this level 0 then this breaks the Operator.. not sure how to say it more concise.. would you be able to set it on any of your CRs and see if your operator will continue to work?

**Comment by camilamacedo86** [comment]
Hi @tomsucho, 

Did you try to do a test using the [Memcached Ansible Sample](https://github.com/operator-framework/operator-sdk-samples/tree/master/ansible/memcached-operator) in order to verify if the error is in the annotation or something else in your project? 

Anyway, I am doing it now. However, I would always recommend you do an isolated test to verify first this kind of scenario and ensure that it is a bug and indeed provide the steps to reproduce.

**Comment by camilamacedo86** [comment]
Hi @tomsucho, 

I could reproduce and check that when the value is == 0 the error is faced and it works fine with 5 for example. Looking on it to provide a fix.
