### ISSUE TITLE
Ansible: is there a way to pass config options to Ansible?

### ISSUE THREAD

**Issue by tomsucho** [operator-framework/operator-sdk#2628]
## Type of question
how to implement a specific feature

## Question
I got lot of conditional checks/logic in the playbook/roles and would like to try to skip from the output all lines that eventually look like:
`
TASK [playbook-name : fail] **************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}
` 
Ansible provides a way of doing this via for examaple setting ENV var:
ANSIBLE_DISPLAY_SKIPPED_HOSTS
https://docs.ansible.com/ansible/latest/reference_appendices/config.html#envvar-ANSIBLE_DISPLAY_SKIPPED_HOSTS

how can I pass this option to the operator? Is there a mechanism to pass arbitrary option / ENV var that would be taken into account by Ansible runner?

Alternatively I could maybe append it to the config file which seem to be this one:
`
Using /etc/ansible/ansible.cfg as config file
`
through modifying Dockerfile commands.
Could you please advise how to do it best way?

**Comment by fabianvf** [comment]
I'm not sure if setting the `ANSIBLE_DISPLAY_SKIPPED_HOSTS` in the operator deployment (on the operator container) would make it all the way through to ansible-runner, but that would be the way to set it. Perhaps it would make sense for us to make sure that all `ANSIBLE_` prefixed environment variables are passed through to the runner environment if it isn't currently working.

I think putting it into the `ansible.cfg` will work, most settings there except for the ones that ansible-runner explicitly overrides (like inventory) should work fine

**Comment by tomsucho** [comment]
Setting options in /etc/ansible/ansible.cfg worked, so closing this.
