### ISSUE TITLE
Under the hood of Operator SDK

### ISSUE THREAD

**Issue by devdattakulkarni** [operator-framework/operator-sdk#263]
I have written a post describing some of the under the hood details of Operator SDK

https://medium.com/@cloudark/under-the-hood-of-the-operator-sdk-eebc8fdeebbf

Let me know if this is correctly capturing Operator SDK's architecture and its interaction points with custom Operators.

**Comment by spahl** [comment]
Thanks for taking the time to understand the sdk and write a blog post. This looks quite correct after a quick read, I will do a more thorough read an let you know.

Would you be interested in contributing some official docs like for example the architecture diagram?

**Comment by devdattakulkarni** [comment]
@spahl Thanks for the reply!

I will be happy to contribute the diagram and the write-up to the docs.

Let me know the steps. Should I just create a PR?

Here is an example of something similar that I contributed to sample-controller:
https://github.com/kubernetes/sample-controller/blob/master/docs/controller-client-go.md

This is linked from the main README of https://github.com/kubernetes/sample-controller under the 'Details' section. I can do something similar here.

Let me know if that makes sense.

**Comment by spahl** [comment]
Sorry for not responding in a while. Truth is the architecture is changing a bit so you might want to hold off until those changes are in. Happy to ping you once it is done.

#169 and #146 are the main ones that affects the diagram.

**Comment by devdattakulkarni** [comment]
Sounds good. 

Let me know once those issues have made enough progress. I can revise the diagram then accordingly and make the PR.

**Comment by shawn-hurley** [comment]
@devdattakulkarni The changes have been made, are you still interested in adding docs?

**Comment by devdattakulkarni** [comment]
@shawn-hurley Sure. Thanks for the note. I will go through the changes to check what all things need to be updated in the description/diagram and then follow up.

**Comment by joelanford** [comment]
@devdattakulkarni just checking in to see if you've had time to update (or if you're still interested in updating) any descriptions or diagrams? If not, no worries!
