### ISSUE TITLE
Helm operator cannot guarantee the install sequence for CRD and CR

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-sdk#2647]
## Bug Report

**What did you do?**
I found that if my helm chart including CRD resources or hooks, I may not able to use helm operator, as the helm operator cannot guarantee the install sequence of CRD and CR, if the CR was installed before CRD, then the helm operator install will be failed.

Any plan to fix this for helm based operator.

**Comment by camilamacedo86** [comment]
Hi @gyliu513, 

Could you please clarification and provide more information over your scenario? What are the steps for we reproduce it with the [Memcached Helm Sample](https://github.com/operator-framework/operator-sdk-samples/tree/master/helm/memcached-operator)?  What do you mean with ` helm operator cannot guarantee the install sequence of CRD and CR, if the CR was installed before CRD, then the helm operator install will be failed.`?

**Comment by gyliu513** [comment]
@camilamacedo86 the use case is as follows:

1) I have a helm chart which has CRD and CR resources, and I can use hook to guarantee the install sequence of CRD and CR and make sure CRD can be installed first.
2) After I covert the helm chart to operators, then both CRD and CR are just YAML templates in the helm operator.
3) When I install the helm operator, sometimes the CR resources was applied before CRD, and this will cause the helm operator install failed, is this clear enough?

**Comment by joelanford** [comment]
@gyliu513 The helm operator is based on Helm 3, which changed how CRDs are handled. See the new [chart hooks documentation](https://helm.sh/docs/topics/charts_hooks/).

Specifically:
> Note that the crd-install hook has been removed in favor of the crds/ directory in Helm 3.

Can you retry using a `crds/` directory and let us know if that solves your problem?

**Comment by gyliu513** [comment]
Thanks @joelanford , let me check.

**Comment by joelanford** [comment]
@gyliu513 Any luck with this? I'll close for now since I think that'll solve your issue, but we can re-open if you still run into issues.
