### ISSUE TITLE
Question (Ansible) - How to have more columns in status (kubectl get)?

### ISSUE THREAD

**Issue by vikas027** [operator-framework/operator-sdk#2654]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

I need some pointers to add more columns to status (`kubectl get <crd> <resource>`).

## Question

**What did you do?**
I have followed the Ansible user [guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md) to deploy a test `Memcache` operator. 

**What did you expect to see?**
I want to have more columns in the `kubectl get` commands, in my example may be the number of pods (just an example)
```bash
$ kubectl get memcacheds.cache.example.com
NAME                AGE   SIZE
example-memcached   38m   3
$
```

**What did you see instead? Under which circumstances?**
```bash
$ kubectl get memcacheds.cache.example.com -o wide
NAME                AGE
example-memcached   38m
$
```

**Environment**
* operator-sdk version: v0.15.2 (ffaf278993c8fcb00c6f527c9f20091eb8dd3352)

* Kubernetes version information:
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
I have spun up a cluster through [kind](https://github.com/kubernetes-sigs/kind)

**Comment by bharathi-tenneti** [comment]
Hi @vikas027 Thanks for reaching out , this is a kubectl cli question. Perhaps a better place would be [here](https://github.com/kubernetes/kubectl/issues).
Having said that, what you are looking for is to be able to add custom columns for `kubectl get crd`. One option for you is to distill information from `kubectl describe memcacheds.cache.example.com`, which gives you a lot more information than `kubectl get`.
Also, found [this](https://github.com/kubernetes/kubernetes/pull/85518) PR ,addressing the same,It has not been merged yet.
Please let us know if you need any further information from Operator-sdk point of view

**Comment by vikas027** [comment]
Hey @bharathi-tenneti ,

AFAIK, this is not a `kubectl` thing. I am new to `operator-sdk` but have used `kopf` (python) operator in which I did not have to anything in `kubectl`. I just had to define an additional column as shown in this [example](https://github.com/zalando-incubator/kopf/blob/master/examples/crd.yaml#L22-L37).

Using GoLang, in `operator-sdk` too you can have the same behaviour. This guy has done it in his [blog](https://medium.com/manikkothu/build-kubernetes-operator-using-kubebuilder-4bfef299757d) and git [repo](https://github.com/hmanikkothu/watchlist-operator). See this output in the blog, it has additional columns - `URL` and `DESIRED`
```bash
$ kubectl get mywatchlist
NAME                 URL                       DESIRED
mywatchlist-sample   http://32.225.23.xxx:8080      1
```
I am just looking for some pointers to do the same in Ansible.

Please let me know if my understanding is incorrect.

**Comment by camilamacedo86** [comment]
Hi @bharathi-tenneti,

I think that @vikas027 is looking for how to create more instances of the pod created by the CR applied. Then, if I understood it properly I'd like to suggest checking the [Ansible Memcached Sample](https://github.com/operator-framework/operator-sdk-samples/tree/master/ansible/memcached-operator). See that the number of instances in this example is defined [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/ansible/memcached-operator/roles/Memcached/defaults/main.yml#L3)   

@vikas027 could you please clarifies and let us know if is it what you are looking for?

**Comment by vikas027** [comment]
Hey @camilamacedo86 ,

Thanks for looking into it. I am not looking to change the number of pods (or memcache instances), but looking to have more columns in the `kubectl get` output.

## What I currently have
```bash
$ kubectl get memcacheds.cache.example.com -o wide
NAME                AGE
example-memcached   38m
$
```

## What I want - a way to add more columns
```bash
$ kubectl get memcacheds.cache.example.com
NAME                AGE   SIZE
example-memcached   38m   3
$
```

Pls see the above comment in which I have explained how I achieved this using `kopf` operator and trying to do the same through `operator-sdk`

**Comment by camilamacedo86** [comment]
Hi @vikas027, 

The CustomResources are from k8s api. See in the k8s docs [here](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/#additional-printer-columns/) how to add more columns on it. 

Note that it is not something specific to any operator tool indeed.

Then, it means that you are free to manually improve your CRD as you wish. See that it is the `deploy/crds/` dir.  

In this way, I think is all sorted out. Please, let us know if we can close this one or if it has anything else that you still needing help here over this subject.

**Comment by vikas027** [comment]
Thanks for the explanation @camilamacedo86 , I think I have got it. I will raise a PR to have the size as well so it is easier to understand the same for others too.

**Comment by camilamacedo86** [comment]
HI @vikas027,

Please, feel free to contribute with PR's to improve the docs if you see that has some need. You are very welcome.
