### ISSUE TITLE
Changing role to ClusterRole and generating a new CSV results in bad CSV

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/operator-sdk#2663]
## Bug Report

**What did you do?**
I changed an operator's role to a clusterRole in `deploy/role.yaml`. I would have rather added it with limited permission, but I understand having both is not currently supported. Then I generated a new CSV. 

**What did you expect to see?**
I expected the new CSV to have a `spec.install.spec.clusterPermissions` value, but not a `spec.install.spec.permissions` value. 

**What did you see instead? Under which circumstances?**
I saw both `spec.install.spec.clusterPermissions` and `spec.install.spec.permissions`. I expect the second set was pulled over from the previous CSV. 

**Environment**
* operator-sdk version:
operator-sdk version: "v0.15.2", commit: "ffaf278993c8fcb00c6f527c9f20091eb8dd3352", go version: "go1.13.3 linux/amd64"

* Are you writing your operator in ansible, helm, or go?
Ansible

**Possible Solution**
When generating a CSV from another, filter out the permissions and only consider the `deploy/role.yaml` as the source of truth for all permissions. Anything else may result in an unexpected level of permissions given to the operator. I'm imagining the potential of removing something from `role.yaml`, but that merging with the previous CSV resulting in the CSV still having the old permissions. That'd be easy to miss, and potentially problematic for security.

**Additional context**

**Comment by camilamacedo86** [comment]
Hi @flickerfly, 

When we gen the CSV by the tool,  it will use the resources files in the deploy dir to generate the CSV. However, if we change these files and would like to reflect this change in the integration with OLM we need re-generate the CSV (usually it will mean a new version/tag of it). 

So, I am not sure if I follow up what exactly you are pointing here in this issue. Were you expecting that change the roles would automatically change the CSV previous generated?  Could you please confirm my understanding?

**Comment by flickerfly** [comment]
Sorry, let me see if I can make it more clear. 

I changed the deploy/role.yaml from a `Kind: Role` to a `Kind: ClusterRole` and generated CSV 2 noting CSV 1 as the CSV to be replaced. The result was CSV 2 with both the Role and the ClusterRole in it.

**Comment by estroz** [comment]
@flickerfly is this still an issue with a more recent version? This may have been fixed by an unrelated PR.

**Comment by estroz** [comment]
Closing this, feel free to re-open if your issue is not fixed in the most recent applicable version.
