### ISSUE TITLE
Support Kubernetes 1.17 in tests

### ISSUE THREAD

**Issue by glothriel** [operator-framework/operator-sdk#2665]
## Feature Request

Molecule test framework for operator-sdk uses `bsycorp/kind` image, that did not release 1.17 version. This makes us unable to test against kubernetes > 1.16

We could evaluate if we can use kindtest:node images instead of custom ones.

**Comment by glothriel** [comment]
It looks like their CI failed for 1.17: https://travis-ci.org/bsycorp/kind/builds/648677096?utm_source=github_status&utm_medium=notification

**Comment by camilamacedo86** [comment]
Hi @glothriel, 

The plan is to upgrade the SDK to use 1.17 k8s api. However, it has dependencies with OLM then, we need to wait for OLM be upgraded first. Note that the 1.17 still not supported yet. 

PS: By checking your errors in https://travis-ci.org/github/bsycorp/kind/jobs/648677100#L403 I am not sure if the 1.17 is properly set up in your test env too.

**Comment by glothriel** [comment]
Hi @camilamacedo86 

> PS: By checking your errors in https://travis-ci.org/github/bsycorp/kind/jobs/648677100#L403 I am not sure if the 1.17 is properly set up in your test env too.

This isn't my test env, it's a build that builds `bsycorp/kind` images, that are used by [OperatorSDK molecule test framework](https://github.com/operator-framework/operator-sdk/blob/master/test/ansible/molecule/test-local/molecule.yml#L16). So even if OperatorSDK itself had support for 1.17, we are unable to ship molecule tests, as there are no `bsycorp/kind:1.17` images.

**Comment by camilamacedo86** [comment]
The default Kube version is 1.16. See; https://github.com/operator-framework/operator-sdk/blob/ff657078952b44bf46fbfd9bf30ed84b500f1973/doc/ansible/dev/testing_guide.md#L95

**Comment by glothriel** [comment]
Oke my upstream issue seems to be resolved: https://github.com/bsycorp/kind/issues/29

**Comment by camilamacedo86** [comment]
Just, to register we are working to upgrade the SDK to use the upper version 1.17 and it will probably be shipped with the next release.
