### ISSUE TITLE
Scorecard failed when the operator generates its seed custom resource. 

### ISSUE THREAD

**Issue by horis233** [operator-framework/operator-sdk#2677]
## Bug Report

**What did you do?**

In order to certify my operator on RedHat and pass the operator config check on the RedHat website, I run the `operator-sdk scorecard` locally to check my operator.

My operator has three CRDs and the operator will generate default instances for two CRs and users just need to create one. The default CRs are the same as alm-example in the CSV.

When running the scorecard check, the scorecard will try to deploy CRs based on the CSV, however,  it will report an `already exist` issue because of two default CRs that have been created. 

My current workaround is changing the order of my CRs in the `alm-example`. I move the CR, which is required to be created by users, in the first place. Then I can avoid pass the scorecard check.

Because when I check the code (`plugin_runner.go`(https://github.com/operator-framework/operator-sdk/blob/master/internal/scorecard/plugins/plugin_runner.go#L329)) in the scorecard, I find scorecard only generates the first CR in the CSV `alm-example` list when olm is deployed.

But, I think generating all CRs in the CSV is in the TODO plan, so If all the CRs are generated,  my workaround will not work.

**What did you expect to see?**

I hope the scorecard can ignore the `IsAlreadyExists` issue when creating the CR. 
For example, in [resource_handler.go ](https://github.com/operator-framework/operator-sdk/blob/master/internal/scorecard/plugins/resource_handler.go#L132) this line 
```
if err != nil {
```
can be changed to
```
if err != nil and !errors.IsAlreadyExists(err)
```

**What did you see instead? Under which circumstances?**

A clear and concise description of what you expected to happen (or insert a code snippet).

I expect the operator-sdk scorecard can support the operator which initialize default instances of CRs. 

**Environment**
* operator-sdk version:
operator-sdk version: "v0.15.2", commit: "ffaf278993c8fcb00c6f527c9f20091eb8dd3352"

* go version:
go version: "go1.13.8 darwin/amd64"

* Kubernetes version information:
1.16

* Kubernetes cluster kind: 
OCP4.3

* Are you writing your operator in ansible, helm, or go?
go

**Possible Solution**

The operator-sdk scorecard can Ignore the `IsAlreadyExists` error when creating CR.

/cc @gyliu513 @chenzhiwei

**Comment by gyliu513** [comment]
Thanks @horis233 , +1 to ignore the error of `IsAlreadyExists`.

@camilamacedo86 @mhrivnak any comments/suggestions for this? Thanks!

**Comment by jmccormick2001** [comment]
I'll check it out and do some testing.

**Comment by jmccormick2001** [comment]
https://github.com/jmccormick2001/operator-sdk/tree/scorecard-cr-exists

would you be able to test your operator out with the above branch?  I've added a check in there for handling an already exists condition when creating objects.

**Comment by horis233** [comment]
@jmccormick2001 
I verified with my operator, operator-sdk from your branch can avoid the  `IsAlreadyExists` issue.

**Comment by jmccormick2001** [comment]
nice, I should have a PR with this out there soon.
