### ISSUE TITLE
Support predicate based filtering of events

### ISSUE THREAD

**Issue by shrinandj** [operator-framework/operator-sdk#268]
Based on current experiments, I see that the handler gets called for all the operations on the CR (add, update and delete). However, there is no information about which of the operations resulted in the handler getting invoked.

Are there plans to add more context to the `types.Event` object (or some other mechanism) to distinguish between various operations?

**Comment by hasbro17** [comment]
@shrinandj Nothing as of yet. In fact with [Finalizers](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#advanced-topics) we're hoping to remove the Delete events altogether. See #270 

Did you have a use case in mind for handling Add/Update events separately? Normally an operator's handler should be able to handle both without distinguishing between the two.

**Comment by shawn-hurley** [comment]
Should this be defined by the resources status field? 

i.e https://github.com/operator-framework/operator-sdk-samples/blob/master/vault-operator/pkg/vault/reconcile.go#L23

**Comment by blaggacao** [comment]
@hasbro17 I wonder though how to query previous (asserted) state during an update? Or are my update funtions supposed to be stateless (which is expensive in code and maybe resources if I need to query actual state in downstream application logic)?

**Comment by hasbro17** [comment]
@blaggacao The operator should act upon the current state of the world and not rely on any previously seen state.
This refers to the level driven vs edge driven convention used in k8s controllers. See point number 3 https://github.com/kubernetes/community/blob/master/contributors/devel/controllers.md#guidelines

**Comment by shrinandj** [comment]
It's good to learn that operators should act upon current state (which implies that everytime the operator is invoked, it should query for the state) and not rely upon who/why it was invoked. I guess this also takes care of edge cases when a single update might invoke the operator more than once.

I don't have a specific use-case in mind yet.

I can close the bug unless others who've commented here have specific needs for distinguishing between add and update.

**Comment by killwing** [comment]
`JobController` will set expectations when a pod is added while not updated:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L214
How could I handle similar case like this?

**Comment by michalrabinowitch** [comment]
What about stateful application where you might need to last “good” configuration to determine if the desired conf is valid?

**Comment by hasbro17** [comment]
@orainxiong You're right. After taking a second look there seem to be quite a few use cases for comparing the old and new objects.
I actually like the predicates approach which is more general. In fact we're currently evaluating the [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) library (which is based on kubebuilder's internals) to redesign the sdk controller components. 
And we'll most likely end up using [predicates](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/predicate/predicate.go#L96-L97) to let users write their own filters for events.

**Comment by joelanford** [comment]
As of 0.1.0, the SDK switched to `controller-runtime` reconciliation, so new operators are able to make use of predicates by passing them in the `controller.Watch` method. See https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg#hdr-Predicate

If you created your operator using an older version of SDK and you'd like to make use of this feature, see our [migration guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/v0.1.0-migration-guide.md).
