### ISSUE TITLE
Feature Request: arm64 binary releases

### ISSUE THREAD

**Issue by MrXinWang** [operator-framework/operator-sdk#2686]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Referencing discussion in [kiali/issues#1091](https://github.com/kiali/kiali/issues/1091), a release of operator-sdk image on arm64 (aarch64) is greatly appreciated.

**Describe the solution you'd like**
An official release of operator-sdk binary. By checking the Makefile, I think it is not very difficult to release that because operator-sdk already supports a lot of architectures.

**Comment by MrXinWang** [comment]
@lilic @AlexNPavel Any comments? Thanks!

**Comment by BlackMix** [comment]
Would be nice to have the arm64

**Comment by MrXinWang** [comment]
@camilamacedo86 Hi! I am wondering if this is possible?

**Comment by BlackMix** [comment]
@MrXinWang just need only add arm64 in Makefile?
I see there only few os: "amd64" "ppc64le" "s390x" hmm

**Comment by MrXinWang** [comment]
@BlackMix Yes fixing the building on arm should be not that difficult as the examples are pretty clear in `Makefile` and the golang scripts that produce the Dockerfiles for images.

But in terms of the official release of arm64 binary, it needs more, at least the community should support this...and we also need some tests...

**Comment by BlackMix** [comment]
@MrXinWang so i'll wait for someone to add arm64, i like kiali and i don't want to use it on a op machine if it can run on a raspberry pi 4, thanks.

**Comment by camilamacedo86** [comment]
Hi folks, 

If you check [here](https://travis-ci.org/github/operator-framework/operator-sdk/builds/666443331?utm_medium=notification&utm_source=github_status) the Travis will build
images with different architectures from master as it has the release for other types as well. See the [release tab for 0.16 for example](https://github.com/operator-framework/operator-sdk/releases/tag/v0.16.0).

The images are created in the release process. See its [doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/dev/release.md). Also, in this process, we call the [release script](https://github.com/operator-framework/operator-sdk/blob/master/release.sh) ( E.g `$ ./release.sh v1.3.0`) which will use the makefile target [make release](https://github.com/operator-framework/operator-sdk/blob/master/Makefile#L113) to build the images. So, new types would need to be added there. Please, feel free to contribute with if you wish and do a PR against the master. 

I think we could add more other types, however, I think we need to discuss it as well and see if others agree to add this other one.

**Comment by MrXinWang** [comment]
Hi @camilamacedo86 , thanks for your reply, hope this is welcomed :)))

@BlackMix Can you please do me a favor and try to raise a PR for this? I would love to do that PR myself but I think I will have to raise an application for a opensource legal approval for this project from my company and it might take some time....If you can do this it will save me from some troubles..Thanks!

**Comment by BlackMix** [comment]
@MrXinWang let me see, need to install go v1.13, if success build so I do PR

**Comment by BlackMix** [comment]
@MrXinWang I got "success" on build, but something got wrong in named file..
now i'll travel for work and i won't be able to finish this
![Kawaii-jwt](https://i.imgur.com/saAyxsd.jpg)

**Comment by MrXinWang** [comment]
Hi @BlackMix ! Great thanks for doing this! Good to see it works :))

For the naming issue, would you please try adding another target named 
`build/operator-sdk-%-arm64-linux-gnu: GOARGS = GOOS=linux GOARCH=arm64` under this line in Makefile: https://github.com/operator-framework/operator-sdk/blob/5104f530ea7bbfb50f4d2d5888cbdc2f26786906/Makefile#L116

Then by running `make build` it should output the correct named file as the others because of the Makefile Pattern Rule.

**Comment by BlackMix** [comment]
hmm, yeah, I did it, build working.
![](https://i.imgur.com/2tVgeOq.png)

**Comment by MrXinWang** [comment]
awesome! @BlackMix

**Comment by BlackMix** [comment]
PR #2722

**Comment by BlackMix** [comment]
Hi @camilamacedo86 
can u look at pr or only others reviews?

**Comment by camilamacedo86** [comment]
Hi @BlackMix,
 
See that the Deploy jobs are NOT executed for the PR's. Just in the master. 
But I will try to look at it as soon as possible. 

Also, @joelanford @hasbro17 are you ok with we add more 1 arch type?

**Comment by BlackMix** [comment]
Thanks @camilamacedo86 
It would be great to have arm64 here, because
other repositories like Istio and kiali supported arm64
istio is almost done and kiali is already finished

the arm64 community will love it :)

**Comment by estroz** [comment]
Meta: testing new build targets doc is needed since, there are some manual steps required to test images built with new targets.

**Comment by BlackMix** [comment]
can close this issue
