### ISSUE TITLE
Scorecard Owned CRDs listed resources

### ISSUE THREAD

**Issue by horis233** [operator-framework/operator-sdk#2698]
## Type of question

I have two questions about the scorecard check 
```
Owned CRDs Have Resources Listed
```

From my understanding, this topic is to make sure all the resources used by CRD listed in its `resources` fields in the CSV.

1.  I read the code. I wonder why the scorecard only checks the resource `version` and `kind` but ignores the resource name (`group`).
https://github.com/operator-framework/operator-sdk/blob/master/internal/scorecard/plugins/olm_tests.go#L290

```
				for _, listedResource := range crd.Resources {
					if matchKind(resource.Kind, listedResource.Kind) &&
						strings.EqualFold(resource.Version, listedResource.Version) {
						foundResource = true
						break
					}
				}
```

2. Since the suggestion message says
```
If it would be helpful to an end-user to understand or troubleshoot your CR, consider adding resources %v to the resources section for owned CRD %s"
```
I wonder if the OLM leverages the `resource` filed in the CSV and if the OCP console will show these resources to the end-user.

Moreover, as I mentioned in question 1, considering the scorecard doesn't compare the resource `group` when OLM or Openshift console uses the `resource` filed, I believe it may cause some issues. For example, two resources use the same `kind` and `version` but in different `groups`.

## Question

**What did you do?**

Run operator-sdk scorecard to certify my operator.
 
**What did you expect to see?**

In the `Owned CRDs Have Resources Listed` check, the operator-sdk scorecard will check `kind` `version` and `group`.

**What did you see instead? Under which circumstances?**

In the `Owned CRDs Have Resources Listed` check, the operator-sdk scorecard only checks `kind` `and version` but not `group`.

**Environment**
* operator-sdk version:

0.16.0

* Kubernetes version information:

1.16

* Kubernetes cluster kind: 

OCP

**Comment by horis233** [comment]
@jmccormick2001 May you help to take a look?

**Comment by horis233** [comment]
For the first question, I think this design may be for the core resources because their groups are empty. 
My concern is why the scorecard doesn't check the resources strictly. For example, for the core resource,like pod, we should add the following into the resources list
```
     - kind: Pod
        name: ""
        version: v1
```
OR
```
     - kind: Pod
        version: v1
```
For other resources like `subscription`
We should specify the group name.
```
      - kind: Subscription
        name: operators.coreos.com
        version: v1alpha1
```

**Comment by jmccormick2001** [comment]
you are correct I think, the scorecard should probably be looking at group/version/kind in that test to be more precise....let me know if you still need a fix for this....in the upcoming scorecard (alpha), we modified that test to more simply just check to see if the resources are filled out instead of comparing each of the individually.

**Comment by horis233** [comment]
@jmccormick2001
Thanks for your reply. Since the upcoming scorecard will use the other method to check the resources, It is ok for me to ignore it. I open this issue is because I found that in the CSVs of some certified operators, they leave all the `name: ` field to empty to pass the scorecard check. I think that is not accurate.
 
Could I ask which version of operator-sdk will the alpha scorecard be integrated into?

**Comment by jmccormick2001** [comment]
you should be able to try out the new scorecard in the new release that just was cut, 0.18.

This is run by 'operator-sdk alpha scorecard', also we included some user docs and sample data for people to try it out with.

**Comment by jmccormick2001** [comment]
please reopen if this is still important, but figured it was not given that the next scorecard is in alpha currently.
