### ISSUE TITLE
An exception occurred during task execution. To see the full traceback, use -vvv.

### ISSUE THREAD

**Issue by xauthulei** [operator-framework/operator-sdk#2699]
Hi team, I am try to use the `operator-sdk` to create a private operator and wish to deploy the cluster for testing, However I got follow errors:

TASK [gateway : create jupyter gateway depoyment "XXX-jupyter-gateway"] *******
task path: /opt/ansible/roles/gateway/tasks/deployment.yml:1
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:                                     ^
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

Could I know how to do this debug to address the error place.  or Is there some ways to debug ? Thanks

My env is :
/tmp/ansible-operator/runner/ibm.com/v1alpha1/Gateway/default/example-gateway/artifacts/605394647632969758//stdout
ansible-playbook 2.8.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/openshift']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Jun 12 2019, 01:12:31) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]

**Comment by camilamacedo86** [comment]
If you are using the SDK latest version 0.16 then, you can add the following envvar in the deploy/operator.yaml to output in the container of your project all Ansible logs. 

```
            - name: ANSIBLE_DEBUG_LOGS
              value: "True"
```

Otherwise, if you are using a version < 0.16.0 you need to check the Ansible logs in the ansible sidecar container by using the command `kubectl logs deployment.apps/<yourproject>-operator -c ansible -n <namespace>`. E.g  `kubectl logs deployment.apps/memcached-operator -c ansible -n memcached`

**Comment by xauthulei** [comment]
@camilamacedo86 ,Thanks for your suggestion, In fact,I remember that the reported error comes from the CMD `kubectl logs deployment.apps/<yourproject>-operator -c ansible -n <namespace>` .  Now I imported the role template liking this:
```
- name: create gateway deployment template
  template:
    src: ../templates/deployment.j2
    dest: "/tmp/{{ release.name }}-deployment.yaml"
- include: "/tmp/{{ release.name }}-deployment.yaml"
```
instead of :
`import_tasks: deployment.yml `

Finally, I got the root causes from the cmd output:
```
fatal: [localhost]: FAILED! => {"reason": "Syntax Error while loading YAML.\n  mapping values are not allowed here\n\nThe error appears to be in '/tmp/xxx-jupyter-gateway-deployment.yaml': line 28, column 75, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n          spec:\n            serviceAccountName: xxx-jupyter-gateway            containers:\n                                                                          ^ here\n"}
```

Thanks again. Meanwhile, Could I know that our ansible role template syntax based on the `jinja`, such as the whitespace control ? I have followed [this link](https://deleforterie.com/wordpress/index.php/2018/10/04/ansible-playing-with-jinja2-and-its-whitespace-control/) fix the error.

**Comment by camilamacedo86** [comment]
Hi @xauthulei, 

I understand that the question raised here is sorted out and then, now you did another one. 
So, could you please raise a new issue with and all required requested info for we are able to help you with? E.g version used and etc ... 

PS.: I'd recommend you try to always upgrade your project to use the latest version as well. 

I am closing it assorted out and I am looking for the new issue. 
Really thank you for your compression. Note that it does not just help us help you better but others that may face the same scenario are are looking for the solutions.
