### ISSUE TITLE
The invalid message for minimum validator need to be adjusted.

### ISSUE THREAD

**Issue by supermqB** [operator-framework/operator-sdk#2701]
## Bug Report
In CR, I have a property with minimum=20 validation. When we set a a value(eg: 10) which is smaller than 20. I got an error likes below:

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# XXXXXXXXXXXXXXXXXXX was not valid:
# * spec.XXXXX.cpuUsage: Invalid value: 20: spec.XXXXXX.cpuUsage in body should be greater than or equal to 20
```
The statement `Invalid value: 20` sounds not reasonable. Perhaps we should show the original value(10) instead,  just likes `Invalid value: 10`

Meanwhile, maximum validation had  the similar issue. it does not report what the value user input, but the maximum one.

Maybe it's problem about kubebuilder, but please help to advise first, thanks.

**Environment**
* operator-sdk version: v0.16.0

* go version: 1.14

* Kubernetes version information: 1.16.2

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?  go

**Comment by joelanford** [comment]
@supermqB What command are you running that results in that error? It looks like `kubectl edit`, maybe?

Operator SDK and Kubebuilder only help you in generating the validations for your CRDs. The actual 
validation occurs when you submit a CR of that type to the cluster. I suspect that error is being returned from the Kubernetes API server, so I'm going to close this since it isn't something that can be fixed by the SDK.

**Comment by supermqB** [comment]
@joelanford 
the error is not only reported in the edit mode, but also can be seen in "kubectl apply"

```
[root@node1 crds]# kubectl apply -f cr.yaml
The ****** "example-******" is invalid:
* spec.***.sysResource.cpuUsage: Invalid value: 20: spec.***.sysResource.cpuUsage in body should be greater than or equal to 20
* spec.***.sysResource.memUsage: Invalid value: 80: spec.mcBlk.sysResource.memUsage in body should be less than or equal to 80
```

**Comment by supermqB** [comment]
@joelanford 
Please help to reopen this issue, if it's a valid one. looks I don't have the permission to do it.

Thanks.

**Comment by camilamacedo86** [comment]
HI @supermqB, 

The point is that the error came from the Kubernetes API server, so **it isn't something that can be fixed by the SDK.** The same previous explanation is valid for any kubectl command. 

I hope that it clarifies why it was closed.

**Comment by supermqB** [comment]
Get it. thanks a lot.

**Comment by supermqB** [comment]
Raised an issue against kubernetes repository. hope it can be fixed later.

https://github.com/kubernetes/kubernetes/issues/90128
