### ISSUE TITLE
Version Documentation

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#2708]
## Versioned Documentation

As a user, I would like to view SDK documentation for the version I am using

This can be accomplished using the docsy "Releases" feature, which adds a Releases dropdown, which can link to arbitrary urls. On release, SDK will need to build a new version (to a new subdomain) and add a link to that version on master.

**Comment by asmacdo** [comment]
See: https://github.com/google/docsy/issues/114#issuecomment-516592637

**Comment by estroz** [comment]
Versioned docs in the website will likely start at the SDK version this is completed in.

**Comment by estroz** [comment]
@asmacdo I think this is done. If not, please re-open.
