### ISSUE TITLE
undefined sdk.Context 

### ISSUE THREAD

**Issue by cscetbon** [operator-framework/operator-sdk#271]
Hey,

Trying to follow the README I get an error when running 
`operator-sdk build quay.io/example/operator` :

```
pkg/stub/handler.go:22:30: undefined: sdk.Context
```

However I can see it in the sdk package :
```
grep Context -m 4 $GOPATH/src/github.com/operator-framework/operator-sdk/pkg/sdk/types.go
// Context is the special context that is passed to the Handler.
// - Context: standard Go context that is used to pass cancellation signals and deadlines
type Context struct {
	Context context.Context
```

**Comment by fanminshi** [comment]
@cscetbon I tested out the master branch and didn't encounter the issue you had. 
Could you update the operator-sdk to the latest master and try again?

**Comment by cscetbon** [comment]
Something has been fixed. I was on commit `0da5a4e66078b0f9963` and now with commit `8a1704d319` it passes

**Comment by fanminshi** [comment]
sounds good. closing.
