### ISSUE TITLE
Released version has `-dirty` string in it

### ISSUE THREAD

**Issue by surajssd** [operator-framework/operator-sdk#2724]
## Bug Report

**What did you do?**

I downloaded the latest version from https://github.com/operator-framework/operator-sdk/releases/tag/v0.16.0 and ran following commands to install it in my $PATH.

```bash
wget https://github.com/operator-framework/operator-sdk/releases/download/v0.16.0/operator-sdk-v0.16.0-x86_64-linux-gnu
mv operator-sdk-v0.16.0-x86_64-linux-gnu operator-sdk
chmod +x operator-sdk
mv operator-sdk ~/.local/bin/
```

And when I run following command to check version:

```console
$ operator-sdk version
operator-sdk version: "v0.16.0-dirty", commit: "55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd", go version: "go1.13.8 linux/amd64"
```

I see that the version has `-dirty` attached to it.

**What did you expect to see?**

I expect to see the version to be `v0.16.0`.

**What did you see instead? Under which circumstances?**

In version I saw `v0.16.0-dirty`.

**Comment by camilamacedo86** [comment]
I did the following test for Mac OS X and I am checking the dirty appended as well. 

See:
```
wget https://github.com/operator-framework/operator-sdk/releases/download/v0.16.0/operator-sdk-v0.16.0-x86_64-apple-darwin

chmod +x operator-sdk-v0.16.0-x86_64-apple-darwin

./operator-sdk-v0.16.0-x86_64-apple-darwin version
operator-sdk version: "v0.16.0-dirty", commit: "55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd", go version: "go1.13.8 darwin/amd64"
```

The same is not checked with 0.15.2. See:

```
 $ ./operator-sdk-v0.15.2-x86_64-apple-darwin version
operator-sdk version: "v0.15.2", commit: "ffaf278993c8fcb00c6f527c9f20091eb8dd3352", go version: "go1.13.3 darwin/amd64"
```

I think it is a minor issue that happened in the release process. Let's discuss it in the bug meeting triaged to see how we can address it.

**Comment by varshaprasad96** [comment]
The binaries for v.0.16.0 have been updated : https://github.com/operator-framework/operator-sdk/releases/tag/v0.16.0
Thank you so much @surajssd for pointing this out :)

**Comment by surajssd** [comment]
Thank you!
