### ISSUE TITLE
Cannot run Ansible operator locally without `roles/` 

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#2726]
## Bug Report
Watches files can now specify a role from an ansible collection, so the `roles` directory should be optional, but without it `operator-sdk run --local` does not know the type of the operator.

```
---
- version: v1alpha1
  group: demo.example.com
  kind: Memcached
  role: asmacdo.memcached_collection.memcached
```

``` 
 operator-sdk run --local
INFO[0000] Running the operator locally in namespace default. 
FATA[0000] Failed to run operator locally: unknown operator type 
```

```
mkdir roles
operator-sdk run --local
INFO[0000] Running the operator locally in namespace default. 
{"level":"info","ts":1585234928.2288132,"logger":"cmd","msg":"Go Version: go1.13.4"}
{"level":"info","ts":1585234928.2288342,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1585234928.2288425,"logger":"cmd","msg":"Version of operator-sdk: v0.16.0+git"}
{"level":"info","ts":1585234928.229738,"logger":"cmd","msg":"Watching single namespace.","Namespace":"default"}
{"level":"info","ts":1585234928.4853928,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
... (it works)
```

**Comment by joelanford** [comment]
@asmacdo When we finish the KB integration and transition the ansible-based operator and scaffolding to a KB plugin, we'll have the project type stored in the `PROJECT` file.

In the meantime, do you think there's another unique indicator in an ansible-based operator project we can use?

**Comment by fabianvf** [comment]
Adding the `--type` override is actually a little trickier than expected, since there are no guards in place in our code specifying the wrong type seems to lead to a segfault most of the time. This means adding it is a much bigger undertaking than initially anticipated. I vote we punt adding the `--type` override until it's explicitly requested, and close this one out with better Ansible detection.
