### ISSUE TITLE
Operator-sdk for Kotlin/java type

### ISSUE THREAD

**Issue by brindasanth** [operator-framework/operator-sdk#2728]
I work for **Software Defined Network(SDN)** Solutioning. Current architecture is completely driven by java based OpenDaylight controller with Netconf protocol and YANG models. We feel that many functionalaties such as Resource Life Cycle Management, Audit, Closed Loop Control, Scheduling, High Performance Data Store, Lifecycle Managements of Network Functions etc are missing or not properly developed in cloud native way. I feel Kubernetes with Operator Framework fills the gap in more efficient way.

I feel the major challenge is migrating the network functions from Java/Kotlin to Go or Ansible Python framework. It involves lot of risk, business knowledge and cost constrains. We have huge amount of code base in java and it requires lot of integration with existing systems. And it is very difficult to transform all resources to GO developer.

So I started similar Operator Framework using Kotlin, Ktor using Kubernetes Java client. We are good in all aspects except Life Cycle Management.

https://github.com/brvith/operator-framework

Sample App : https://github.com/brvith/3k-operator-sdk/tree/master/sample-app

So we looking for information or guidance in developing Operator Life Cycle Management functionality:

Cluster Service Version Generation for type "**Kotlin**".
Bundle Create and Validation  type "**Kotlin**"
Operator Hub deployment  type "**Kotlin**".
using **opertaror-sdk**.

**Comment by estroz** [comment]
@brindasanth thanks for suggesting this. I've created a meta issue for non-Go Operator SDK's (#2745). Note that a feature request for a Java SDK exists (#1568). I suggest checking that out for any info that might help you build an SDK for Kotlin.

**Comment by brindasanth** [comment]
Thanks a lot taking this feature,

FYI : In these projects (https://github.com/brvith/operator-framework and https://github.com/brvith/ric/tree/master/operators/sample-pnf-operator ), I used Kubernetes officially supported java client https://github.com/kubernetes-client/java not kubernetes fabric.

**Comment by camilamacedo86** [comment]
It would be the same case of the other requests for new languages. See: Meta-issue for non-Go Operator SDK's: #2745.
