### ISSUE TITLE
v0.16.x upgrade guide uses incorrect revision

### ISSUE THREAD

**Issue by aharbis** [operator-framework/operator-sdk#2733]
## Bug Report

**What did you do?**

The [v0.16.x upgrade guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md#v016x) includes the following:

```go
require (
	github.com/operator-framework/operator-sdk 0.16.0
	sigs.k8s.io/controller-runtime v0.4.0
)
```

**What did you expect to see?**

The revision for the SDK pkg needs to be `v0.16.0`.

**What did you see instead? Under which circumstances?**

The revision for the SDK pkg is `0.16.0` which yields to the following error during `go mod tidy`:

```
$ go mod tidy
go: finding github.com/operator-framework/operator-sdk 0.16.0
go: finding github.com/operator-framework/operator-sdk 0.16.0
go: errors parsing go.mod:
go.mod:6: require github.com/operator-framework/operator-sdk: version "0.16.0" invalid: unknown revision 0.16.0
```

**Environment**
* operator-sdk version:

```
operator-sdk version: "v0.16.0", commit: "55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd", go version: "go1.13.8 linux/amd64"
```

* go version:

```
go version go1.13.8 linux/amd64
```

* Kubernetes version information:

N/A

* Kubernetes cluster kind: 

N/A

**Possible Solution**

Fix is to update the `require` to:

```go
require (
        github.com/operator-framework/operator-sdk v0.16.0
        sigs.k8s.io/controller-runtime v0.4.0
)
```

**Additional context**

N/A

**Comment by camilamacedo86** [comment]
Hi @aharbis, 

Thank you for check this small typo issue could you please do a PR to fix it in the doc? Please, note that temporary we need also update the files in the .webiste dir which has the same structure. I mean we need to do this update in the doc/ and .website guide.

**Comment by aharbis** [comment]
Sure, I'd be happy to submit the fix.

**Comment by aharbis** [comment]
PR https://github.com/operator-framework/operator-sdk/pull/2735 open.
