### ISSUE TITLE
resource " already exists", when r.client.Get()

### ISSUE THREAD

**Issue by uma-spatil** [operator-framework/operator-sdk#2734]
****** logs *******
{"level":"info","ts":1585324637.7143104,"logger":"controller_trainingmanagement","msg":"Creating a new training resourceQuota","reconcile request detail":"/blr-trainingmgnt","Request.Namespace":"","Request.Name":"blr-trainingmgnt","Request.NamespacedName":"/blr-trainingmgnt","resourceQuota.Name":"blr1-training-rq","foundrq":{"name":""}}
{"level":"error","ts":1585324639.2301235,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"trainingmanagement-controller","request":"/blr-trainingmgnt","error":"resourcequotas \"blr1-training-rq\" already exists","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/vagrant/go_project/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/vagrant/go_project/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/vagrant/go_project/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/vagrant/go_project/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/vagrant/go_project/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/vagrant/go_project/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/vagrant/go_project/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
********* end of logs **********

I'm trying to create a ResourceQuota object after a namespace is created.
Below is the code trying to find the resource before creating it :

********** code ***********
foundrq := &corev1.ResourceQuota{}
		err = r.client.Get(context.TODO(), client.ObjectKey {Namespace: training_ns.Name, Name: training_rq.Name}, foundrq)
		if err != nil && errors.IsNotFound(err) {
			reqLogger.Info("Creating a new training resourceQuota", "resourceQuota.Name", training_rq.Name, "foundrq", foundrq )
			//Not found so creating a new Resource Quota
			err = r.client.Create(context.TODO(), training_rq)
			if err != nil {
			return reconcile.Result{}, err
			}
			//return reconcile.Result{}, nil
		} else if err != nil {
			return reconcile.Result{}, err
		}
********** end of code ***********

When trying to find the resource via r.client.Get(), The resource is not found.
But while creation it says already exists (And this is true, the resource is already created)

**Comment by camilamacedo86** [comment]
Could you please check if you are you getting and creating in the same namespace?
Note that by looking at your code example shows that you are using `training_ns.Name` and `training_rq.Name,`. So, I think is valid to ensure that it is not a result of a small typo issue.

**Comment by uma-spatil** [comment]
Yes, the object name is training_rq.Name is created under Namespace trainings_ns.Name

**Comment by estroz** [comment]
@uma-spatil can you provide a simple example that reproduces your issue, or a link to your controller code?

/triage support
