### ISSUE TITLE
Meta: Operator SDK's in other languages

### ISSUE THREAD

**Issue by estroz** [operator-framework/operator-sdk#2745]
There has been quite a bit of interest in writing an SDK for Java (#1568, #2728) and python (mentioned in slack and community meetings). In general the operator-framework community should support as many Operator SDK's, or one SDK that manages Operators in multiple languages, as possible since Operators are largely language independent. While this repo does not support scaffolding Operators in other languages aside from Go, Ansible, and Helm (yet), we welcome both documentation on how to build an SDK in any language or community projects that provide ergonomic abstractions over their language's k8s client library.

Some project that provide more abstract client libraries that we're aware of:
* Java:
  * https://github.com/fabric8io/kubernetes-client
* Python:
  * https://github.com/zalando-incubator/kopf

There is no official documentation discussing best practices for writing an SDK currently but there are plans to write one. In the mean time here are a few methodologies this SDK followed to become what it is today:
* Scaffold a basic project that can be built immediately and run with few changes
  * Project layout: [Go](https://github.com/operator-framework/operator-sdk/blob/master/doc/project_layout.md), [Ansible](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/project_layout.md), [Helm](https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/project_layout.md)
  * Scaffolding code: [Go](https://github.com/operator-framework/operator-sdk/tree/master/internal/scaffold), [Ansible](https://github.com/operator-framework/operator-sdk/tree/master/internal/scaffold/ansible), [Helm](https://github.com/operator-framework/operator-sdk/tree/master/internal/scaffold/helm)
  * Generators: [controller-gen](https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen)
* Leverage a runtime library that abstracts [client-go](https://github.com/kubernetes/client-go) into ergonomic, high-level APIs for managing Operator resources
  * [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime)
  * Runners that reconcile [Ansible](https://github.com/operator-framework/operator-sdk/blob/master/pkg/ansible/runner/runner.go) and [Helm](https://github.com/operator-framework/operator-sdk/blob/master/pkg/helm/run.go) projects
* A [binary](https://github.com/operator-framework/operator-sdk/blob/master/doc/cli/operator-sdk.md) with packaging and testing features
  * [`operator-sdk build`](https://github.com/operator-framework/operator-sdk/blob/master/doc/cli/operator-sdk_build.md)
  * [`operator-sdk bundle`](https://github.com/operator-framework/operator-sdk/blob/master/doc/cli/operator-sdk_bundle.md)
  * [`operator-sdk test`](https://github.com/operator-framework/operator-sdk/blob/master/doc/cli/operator-sdk_test.md)

Feel free to comment in this meta-issue with links to other SDK-related projects, documentation suggestions, or questions about the above.

/kind documentation
/priority important-longterm

**Comment by brindasanth** [comment]
We shall use Kubernetes official java client project: https://github.com/kubernetes-client/java

**Comment by jkremser** [comment]
fyi https://github.com/jvm-operators/abstract-operator (I don't work for Red Hat anymore, though)

**Comment by asmacdo** [comment]
This is valuable, but not actionable. IMO specific language RFEs should be filed if needed.
