### ISSUE TITLE
Trigger point to re-reconcile all CR instances

### ISSUE THREAD

**Issue by libesz** [operator-framework/operator-sdk#2748]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have a (go-lang) controller, watching a CRD as usual. The exact result of the reconciliation depends on some other cluster settings as well, these are outside of the CRs. The user may change the dependent setting which is not practical to watch in the same controller. In this case the controller needs to re-concile all the CRs in response.

**Describe the solution you'd like**
There shall be an option to re-trigger the full reconciliation, same as which happens at controller startup time.
Alternatives I can think of:
* Runnable interface may have a new method which would trigger the re-reconcile
* Manager could have a Del() option to gracefully remove an already added Runnable, giving the option to the user code to re-add the same controller type, so it will reconcile everything

**Workaround**
Without Operator SDK change, after detecting the dependent setting change outside of the controller, exiting from (and so restarting) the operator process/container may work around the issue, though it is not elegant.

**Comment by joelanford** [comment]
@libesz If I understand your use case correctly, I think the features you need already exist. 

If the dependent setting is in another CR, you can use [`EnqueueRequestsFromMapFunc`](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/handler#EnqueueRequestsFromMapFunc) to watch the other CRD type and write a custom mapping function that lists every CR you need to reconcile.

If the dependent setting is not coming from a watchable Kubernetes resource, then you can use a custom `Source`, for example [`source.Channel`](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/source#Channel), which allows you to send events to a channel to trigger reconciliations.

> The exact result of the reconciliation depends on some other cluster settings as well, these are outside of the CRs. The user may change the dependent setting which is not practical to watch in the same controller.

If you can explain where this setting comes from with a little more detail, we can probably direct you to the right solution.

**Comment by libesz** [comment]
Thanks for the fast response. I couldn't find the mentioned functions for the first sight. Will look into those.

Actually the operator has two controllers. One watches the CRD, the other watches Nodes. The one which watches the nodes is catching deletes, which is not related to the CRD directly. However, the CRD watching controller at reconciliation time uses the actual node's labels, where it is running. Now when the self node's labels are changing, full reconciliation is needed.
The problem is that I don't want to watch the nodes also in the CRD based controller, as the operator is deployed as daemonset on the entire cluster (potentially on large clusters, so would like to keep the K8S API watches on the possible minimal).
So my idea was to extend the node watcher controller to catch the self label change (besides node delete events) and trigger the CRD controller to reconcile everything when this happens.
Is the custom `Source` capable to handle cases like this?

**Comment by joelanford** [comment]
> One watches the CRD, the other watches Nodes. The one which watches the nodes is catching deletes.

Controllers created from the same manager share informers and caches, so if you're already watching Nodes in one controller, there should not be any additional load to also watch Nodes from the CRD controller and use `EnqueueRequestsFromMapFunc`.

> The problem is that I don't want to watch the nodes also in the CRD based controller, as the operator is deployed as daemonset on the entire cluster (potentially on large clusters, so would like to keep the K8S API watches on the possible minimal).

Potentially unrelated question: Are all of the operator daemonset pod instances running and reconciling concurrently and watching the same sets of resources or is there just one leader operator pod actually running at any one time? 

If they're all reconciling concurrently, how do you avoid them trying to reconcile the same resources at the same time?

**Comment by libesz** [comment]
Thanks for the update again!

Yes, they are concurrently reconciling the same CR instances, in all active mode. The derived state is realized and managed locally on every node where the Pods are running (no any derived K8S objects). The CRD watching controller loop only updates the CR status, where all the nodes have a dedicated slot to update. Of course they may conflict in updating the status, but that is gracefully refused by the API so after a few try every node gets the up-to-date status in.

**Comment by joelanford** [comment]
Gotcha, thanks for the details! I think adding a watch for Nodes on the CRD controller with `EnqueueRequestsFromMapFunc` will do exactly what you want with no added load. Let us know if that works!

On a related node, I assume you're doing a `Get` on a `Node` in your CRD reconciler to get the node's labels? If so, you are likely already pulling the Node resource from the cache, which is already populated by an informer that is doing a List (to populate the cache initially) and a Watch (to keep it up-to-date).

**Comment by libesz** [comment]
> On a related node, I assume you're doing a Get on a Node in your CRD reconciler to get the node's labels?

Not yet. Right now the main function fetches the self Node labels at startup and passes that to the CRD controller. So I hit the subject problem when I started improve that :).

Will get back with the results. Thanks!

**Comment by libesz** [comment]
Seems working!
I was able to filter the watch source only to the own node, than trigger only on updates, where labels are changed, using a predicate.

Thanks for the help!
