### ISSUE TITLE
Add support version package to generated code

### ISSUE THREAD

**Issue by andyxning** [operator-framework/operator-sdk#275]
Add support for `k8s.io/kubernetes/pkg/version` package to the generated operator.

**Comment by fanminshi** [comment]
@andyxning Could you elaborate on `Add support for k8s.io/kubernetes/pkg/version package to the generated operator.`? 
I don't think I understand what you have meant by ` k8s.io/kubernetes/pkg/version`.

Did you mean that operator-sdk should also generated some sort of version pkg that contains the version of your operator? for example, etcd-operator has a [version/version.go](https://github.com/coreos/etcd-operator/blob/master/version/version.go)

**Comment by andyxning** [comment]
@fanminshi Sorry for not make myself explained. 

> Did you mean that operator-sdk should also generated some sort of version pkg that contains the version of your operator? for example, etcd-operator has a version/version.go

That's right.

**Comment by andyxning** [comment]
Operator is somewhat a controller manage. And i think it should be better to make controller manager be consistent with Kubernetes components to output the same format version info when `OPERATOR_NAME --version`.

**Comment by andyxning** [comment]
I can help to add this support as i have make it for nsq-operator.
