### ISSUE TITLE
Porting existing Helm Charts to Ansible Operator

### ISSUE THREAD

**Issue by aneeshkp** [operator-framework/operator-sdk#2759]
## Feature Request
I have an issue, where a customer wants to use operator-SDK ansible operator and port their existing helm charts into this operator.

Do you have any plan to include this kind of ability within the SDK to convert charts into ansible or do you have suggestions or tools on how to do this?
 My initial thought was ansible understands jinja2 templates and it be should straight forward task to use a go lang tool to parse helm charts and convert them into templates.
 But then I ran into this problem of parsing  _helper.tpl user-defined function and helm functions etc.

**Describe the solution you'd like**
Like to have a tool to do this or any expert advice on how to implement this?

**Comment by camilamacedo86** [comment]
Hi, @joelanford and @fabianvf could you please give a hand in this one. He asked help and I suggested raise the issue. I think you both will have better insight over it.

**Comment by joelanford** [comment]
@aneeshkp We don't plan to provide features in the SDK to migrate helm charts to ansible roles/playbooks.  One option may be to use ansible's [`helm`](https://docs.ansible.com/ansible/latest/modules/helm_module.html) module as a starting point.

One problem you would run into with converting Helm templates is that many of them use [`sprig` template functions ](http://masterminds.github.io/sprig/) that would have to be ported or translated to ansible jinja2 template functions.

**Comment by aneeshkp** [comment]
Thanks, @joelanford , The goal is to move all the helm charts into ansible operator so they can be part of the operator catalog, managed by OLM,  So using helm module with pure ansible won't help I think.  As you said, we need to build a solution to support sprig function in ansible via jinja2 template functions.

**Comment by joelanford** [comment]
@aneeshkp Maybe I'm not understanding correctly, but there shouldn't be any reason that using the ansible operator with the `helm` module or using the helm operator directly would prevent the operator from being included in the operator catalog and managed by OLM.

**Comment by aneeshkp** [comment]
@joelanford , One of the main reason is helm charts based operator maturity level is, install and upgrades only and ansible operator gives more capabilities and I will let @jsm84 update more about the business decisions.
Q? So  if I use ansible helm modules, can I still get the same capabilities as ansible operators?

**Comment by jsm84** [comment]
@joelanford I was asked to chime in here, so please pardon if I sound like I'm on a soap box. I agree that OLM/operator catalog listing wouldn't be affected by using the helm module in ansible. The issue with using the helm module as part of an automated conversion tool (from helm to ansible) is simply the redundancy. IMO, it defeats the purpose of conversion having go code, that calls ansible code, that calls a helm chart by using the ansible helm module. Especially when helm operator does the same thing without using ansible as a shim.

What we want to enable partners to do, is to migrate simply from helm to native ansible, to enable them to further develop the complexity of what their operator can do versus with helm alone. IIRC, the majority of certified operators are helm-operators, and they chose that development workflow for the ease of transition. Helm charts are relatively easy for devops teams to write and understand, and most partners already have helm charts. Go code has a much higher learning curve versus ansible, and it seems that most of our partners don't have the skillset required for Go. We want a greater number of quality certified operators in our catalog, and I feel that such a tool would do wonders to help us achieve that.

**Comment by joelanford** [comment]
> One of the main reason is helm charts based operator maturity level is, install and upgrades only and ansible operator gives more capabilities

That is definitely true. If you're looking to add some of the higher level maturity features, then you would need to move to ansible or Go.

> Q? So if I use ansible helm modules, can I still get the same capabilities as ansible operators?

Yes, using an ansible operator would enable you to add more logic around the helm lifecycle. The caveat is that if you need fine-grained control of the rollout of what's in the helm release, you probably won't be able to achieve that as easily since helm doesn't have that level of flexibility.

I'm not specifically aware of any ansible-based operators that use the helm module, so I don't know if others have been successful doing something like that.

If you're looking to go all in on an ansible-based operator, I would probably suggest translating the templates to jinja2 and fully embracing the ansible-operator.

Also, @fabianvf is our resident ansible export and may be able to give you more specific tips or tricks to make the transition easier.

**Comment by fabianvf** [comment]
> > Q? So if I use ansible helm modules, can I still get the same capabilities as ansible operators?
> 
> Yes, using an ansible operator would enable you to add more logic around the helm lifecycle. The caveat is that if you need fine-grained control of the rollout of what's in the helm release, you probably won't be able to achieve that as easily since helm doesn't have that level of flexibility.
> 
> I'm not specifically aware of any ansible-based operators that use the helm module, so I don't know if others have been successful doing something like that.

Just a note, the helm module in Ansible core is unmaintained/deprecated and will soon be removed, but it is going to be replaced with modules that ship in the Kubernetes Ansible collection. If you want to follow/try out that work the PR is here: https://github.com/ansible-collections/kubernetes/pull/61

Making use of these modules would definitely allow you to add functionality beyond install/upgrade even without porting all the Helm templates to native Ansible. I would probably recommend starting here, and transitioning pieces out of Helm and into Ansible over time (if possible).

> If you're looking to go all in on an ansible-based operator, I would probably suggest translating the templates to jinja2 and fully embracing the ansible-operator.

:+1:, Unfortunately I don't know of anyone specifically who has ported a complex Helm chart to Ansible (though they are out there), and as far as I am aware we don't have tooling or guidance to help with that currently. I'll reach out to a few people and see if I can find some more helpful information.

**Comment by tima** [comment]
> Making use of these modules would definitely allow you to add functionality beyond install/upgrade even without porting all the Helm templates to native Ansible. I would probably recommend starting here, and transitioning pieces out of Helm and into Ansible over time (if possible).

I agree. Using the 'helm' module is a quick fix/transition to Ansible, but it won't suffice for long and is not the end state you'd want to remain in.

> 👍, Unfortunately I don't know of anyone specifically who has ported a complex Helm chart to Ansible (though they are out there), and as far as I am aware we don't have tooling or guidance to help with that currently. I'll reach out to a few people and see if I can find some more helpful information.

Unfortunately @jsm84 this is not something I am aware exists either though it is on my list of things to develop. I've done a preliminary comparison of helm to (pure) ansible and I don't think a tool to automatic convert one to the other is possible. While similar in concept their operating models are different enough to make the logic too significant to be worth the effort assuming it's even possible. 

I'd be interested in hearing what you have in mind. Contact me directly and we can discuss.

**Comment by aneeshkp** [comment]
@tima I will send you an email with a link to a google doc, where we can discuss the approach we have in mind and see if its feasible solution. 
@fabianvf  I would like to try helm_cli  modules from the PR  you posted, Do you have any link to readme document on how to use it?

**Comment by tima** [comment]
@aneeshkp https://github.com/ansible-collections/kubernetes/pull/61

**Comment by fabianvf** [comment]
@aneeshkp There are now helm modules included in the `community.kubernetes` Ansible collection, I recommend using those. https://galaxy.ansible.com/community/kubernetes

**Comment by tengqm** [comment]
In a project, we have some upstream Helm charts to leverage (rather than reinvent everything) when developing Ansible based operators. What we did was to materialize the charts into k8s manifests using `helm template` conversion. When then manipulate the converted manifests as if we wrote them.

**Comment by aneeshkp** [comment]
Thanks @tengqm @fabianvf @tima . I will try this out with some existing templates, this is very exciting .  Thanks again

**Comment by aneeshkp** [comment]
@tengqm .In your example,  the variables will stay in . Values file, but still able to override via CR Spec and ansible default, right?

**Comment by tengqm** [comment]
@aneeshkp can be overridden by CR spec. that is for sure. variables have precedence orders.
