### ISSUE TITLE
Relocate controller-runtime client doc upstream

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-sdk#2769]
I noticed that we have a document about the [controller-runtime client](https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/golang/references/client.md). Rather than maintaining this in the operator-sdk repo, I would suggest that we contribute this upstream, perhaps with a combination of:
- a new doc under the kubebuilder reference docs: https://book.kubebuilder.io/reference/reference.html
- [testable examples](https://blog.golang.org/examples) in controller-runtime 

This combination would make these documents more discoverable for all controller-runtime users, would be maintained by the controller-runtime community, and would guarantee that the examples actually continue to work since they would become part of the controller-runtime test suite.

**Comment by camilamacedo86** [comment]
/remove-lifecycle stale

@joelanford could not it be backlog as well?
