### ISSUE TITLE
Improve Ansible User Guide documentation for Building/Running the Operator

### ISSUE THREAD

**Issue by ryandgoulding** [operator-framework/operator-sdk#2774]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The existing documentation may cause confusion for new users with respect to building and running the example memcached operator.  Namely, "quay.io/example/v0.0.1" is used in several places without much explanation.  Extracting an environment variable to represent this value could improve usability;  specifically by implying that a user should replace "example" with his or her quay.io username.  Additionally, the user guide is focused on the quay.io docker registry, which is perfectly acceptable.  However, when I ran through the example, I did not realize that the repository must be made public in order for K8S to successfully pull the image.  This might be personal naivete, but I believe the documentation could benefit from explicitly mentioning that the repository should be made public.

**Describe the solution you'd like**
One solution might involve the following steps:
1) Have the documentation extract an environment variable to represent the Docker Image, so that it is consistent throughout and less prone to copy/paste error.
2) Mention that the quay.io docker repository needs to be made public prior to running the subsequent deployment.

**Comment by ryandgoulding** [comment]
I would appreciate the ability to take ownership of this issue.  I am forming a PR that should help give context.

**Comment by estroz** [comment]
@ryandgoulding can you link your PR here? Thanks!

**Comment by tengqm** [comment]
@ryandgoulding Would you raise a PR based on your branch? The issue is inactive for 30 days now.
/remove-lifecycle stale

**Comment by camilamacedo86** [comment]
HI @ryandgoulding,

IMO we can close it with the PR: https://github.com/operator-framework/operator-sdk/pull/3555 where we are adding a quickstart more concise. See the step https://deploy-preview-3555--operator-sdk.netlify.app/docs/building-operators/ansible/quickstart/#building-and-pushing-the-project-image in the preview where your concerns raised here are addressed.  

However, the "tutorials" for all types still with a ton for improvements but it shows beyond the scope of this issue. Also, please feel free to contribute with docs improvements as well. 

c/c @estroz

**Comment by ryandgoulding** [comment]
@camilamacedo86 works for me;  that quickstart is a big improvement.  Thank you for resolving this!
