### ISSUE TITLE
Validation howto ? openapi ?

### ISSUE THREAD

**Issue by akram** [operator-framework/operator-sdk#2784]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
community best practices and how to implement a specific feature

## Question

**What did you do?**
In my CRD, I have two fields that are mutually exclusive. I want kubernetes to perform this validation on create of edit.
Documentation talks about using openapi 3, but it is not clear.

**What did you expect to see?**
Is there any documentation explaining how ?

**Comment by estroz** [comment]
@akram we use controller-gen's OpenAPI schema generator, which is explained here: https://book.kubebuilder.io/reference/generating-crd.html. If that doc answers your question, feel free to close this issue.
