### ISSUE TITLE
Documentation should include instructions for running the operator outside the cluster in dlv

### ISSUE THREAD

**Issue by davesargrad** [operator-framework/operator-sdk#2785]
## Feature Request
I'd like to see the [documentation ](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md)updated to show how to run an operator outside the cluster in the [dlv](https://github.com/go-delve/delve) single step debugger.

Currently the command line invocation of the custom operator is hidden in the documentation through the use of the operator-sdk

![image](https://user-images.githubusercontent.com/48793689/78575519-78795100-77f9-11ea-97e6-3de403393f32.png)

The Operator SDK [User Guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md) is quite useful, however I'd like to see how to start the operator using
`dlv debug`

rather than using operator-sdk

This should include how to set arguments to point properly to .kube-config, namespaces to watch, and anything more that operator-sdk injects when it runs the operator

![image](https://user-images.githubusercontent.com/48793689/78576066-2c7adc00-77fa-11ea-9355-b65a077e448d.png)

**Comment by davesargrad** [comment]
I did figure out how to run in the debugger, and hand it the proper configuration:

![image](https://user-images.githubusercontent.com/48793689/78787498-6f62be00-7978-11ea-956b-aa2af5180a70.png)

**Comment by estroz** [comment]
Glad you figured this out. However this is unrelated to operators themselves, and more of a delve/golang question, so we likely won't document this.
