### ISSUE TITLE
Replace the usage of `gopkg.in/yaml.v3` for `sigs.k8s.io/yaml`

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#2790]
What ?
- Replace the usage of `gopkg.in/yaml.v3` for `sigs.k8s.io/yaml`

Why?
- Just to place is requiring the `gopkg.in/yaml.v3` and then, we can use the module `sigs.k8s.io/yaml` which is already used in the project instead of. 

Where?
- pkg/ansible/watches/watches.go 
- pkg/helm/controller/controller.go 

Notes: After the PR https://github.com/operator-framework/operator-sdk/pull/2786/files# will still 2 places that require some small refractures in order to allow us to remove the need for this dependency.

**Comment by camilamacedo86** [comment]
Hi @estroz, 

I am re-opening it. It still required.

**Comment by joelanford** [comment]
/assign

I've got a few branches for some of this already. I'll submit PRs today or tomorrow.

**Comment by estroz** [comment]
Is this done?

**Comment by camilamacedo86** [comment]
Not yet @estroz. See: https://github.com/operator-framework/operator-sdk/search?q=replace+it+for+yaml+%22sigs.k8s.io%2Fyaml%22&unscoped_q=replace+it+for+yaml+%22sigs.k8s.io%2Fyaml%22

also, when it gets done we will able to remove the dep gopkg.in/yaml.v3 from go.mod

**Comment by joelanford** [comment]
The only place this still remains is in `pkg/ansible/watches/watches.go`. I'll take a look at fixing that file as soon as I get a chance.

**Comment by estroz** [comment]
3 more locations: https://github.com/operator-framework/operator-sdk/search?q=%22gopkg.in%2Fyaml%22&unscoped_q=%22gopkg.in%2Fyaml%22

Bumping this to the backlog since this isn't a bug and shouldn't block a release.

**Comment by varshaprasad96** [comment]
There would be some modifications required after [#3120](https://github.com/operator-framework/operator-sdk/pull/3120) is merged. Usage of `gopkg.in/yaml.v3` is required in the mentioned PR because of dependence on Operator Registry.
