### ISSUE TITLE
"msg": "TemplateNotFound

### ISSUE THREAD

**Issue by xauthulei** [operator-framework/operator-sdk#2793]
## Bug Report

**What did you do?**

In my based k8s secret template, I want to include another template `jupyterhubDockerhubconfigjson.j2` (Even if they are in same directory will failed again with same error):
```
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{% include "../templates/hub/jupyterhubDockerhubconfigjson.j2" | b64encode %}"
```
And, in my role task:
```
- name: create image credentials template
  template:
    src: ../templates/hub/image-credentials-secret.j2
    dest: "/tmp/hub-{{ meta.name }}-image-credentials-secret.yaml"
- include: "/tmp/hub-{{ meta.name }}-image-credentials-secret.yaml"
```
and it reported this error:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "TemplateNotFound: Li4vdGVtcGxhdGVzL2h1Yi9qdXB5dGVyaHViRG9ja2VyaHViY29uZmlnanNvbi5qMg=="}
```
"Li4vdGVtcGxhdGVzL2h1Yi9qdXB5dGVyaHViRG9ja2VyaHViY29uZmlnanNvbi5qMg==" will be 
`../templates/hub/jupyterhubDockerhubconfigjson.j2`

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

a k8s rc template with  including another template one could be created successfully 

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.3 darwin/amd64"

ansible-playbook 2.8.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/openshift']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Jun 12 2019, 01:12:31) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]

* go version:
go version go1.13.5 darwin/amd64

* Kubernetes version information:

lient Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:55:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster kind: 
The k8s cluster of Docker internal 

* Are you writing your operator in ansible, helm, or go?
Ansible
**Possible Solution**

**Additional context**

**Comment by xauthulei** [comment]
After some testing, I change the **include** liking this without `b64encode` :
```
      data:
        .dockerconfigjson: "{% include "jupyterhubDockerhubconfigjson.j2"  %}"
```
output (seems it could find the template `jupyterhubDockerhubconfigjson.j2` )
```
 expected <block end>, but found '<scalar>'\n\nThe error appears to be in '/tmp/hub-example-jupyterhub-image-credentials-secret.yaml': line 23, column 4, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n        .dockerconfigjson: \"{\n  \"auths\": {\n   ^ here\n"}
```
However, I add the `b64encode` , it will get the error again :
input:
```
      data:
        .dockerconfigjson: "{% include "jupyterhubDockerhubconfigjson.j2" |b64encode %}"
```
output
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "TemplateNotFound: anVweXRlcmh1YkRvY2tlcmh1YmNvbmZpZ2pzb24uajI="}
```

How could I encode the json configure here ? Thanks

**Comment by fabianvf** [comment]
This isn't really an operator-related problem, but it looks like the issue is that the b64encode is being applied to the name of the template before it is passed to include. Changing it to

```
"{% (include "../templates/hub/jupyterhubDockerhubconfigjson.j2") | b64encode %}"
```

may work to properly enforce precedence, if not I recommend asking asking in #ansible on IRC freenode or filing an issue against the Ansible repository.

**Comment by xauthulei** [comment]
Thanks @fabianvf. I will have a try.
