### ISSUE TITLE
What is the best solution to change `api-version` and `kind` after code was generated

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-sdk#2819]
After I created the API and Controller with a Kind, can I change the Kind with some script or command?

```
$ operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=Memcached
$ operator-sdk generate k8s
$ operator-sdk generate crds
$ operator-sdk add controller --api-version=cache.example.com/v1alpha1 --kind=Memcached
```

After the above command finished, if I want to change the `api-version` and `kind` due to some product requirement, what can I do? Do I need to change code manually or there are some commands/scripts that I can leverage? Thanks!

**Comment by camilamacedo86** [comment]
The tool do not provide a command to change the API scaffolded already. In this case, I'd recommend creating your new API and copy past the types and then, run the command to generate/update the crd's.

Please, let us know if it answers your question and if we can close this one.

**Comment by gyliu513** [comment]
make sense, thanks @camilamacedo86
