### ISSUE TITLE
error when generating crds using status.Conditions

### ISSUE THREAD

**Issue by raffaelespazzoli** [operator-framework/operator-sdk#2820]
## Bug Report
After adding status.Conditions as per the [documentation](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#manage-cr-status-conditions),
I get the following error when generating the crds:
```shell
operator-sdk generate crds --verbose
DEBU[0000] Debug logging is set                         
INFO[0000] Running CRD generator.                       
github.com/redhat-cop/operator-utils/pkg/apis/example/v1alpha1:-: conflicting types in allOf branches in schema: array vs object
FATA[0000] error generating CRDs from APIs in pkg/apis: error generating CRD manifests: error running CRD generator: not all generators ran successfully
```

The error message is not generous.
Removing the Conditions field, the generation completes successfully. My status struct is the following:

```golang
// MyCRDStatus defines the observed state of MyCRD
// +k8s:openapi-gen=true
type MyCRDStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file
	// Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html

	status.Conditions `json:",inline"`
}
```

**What did you do?**
see above

**What did you expect to see?**
generation completed successfully

**What did you see instead? Under which circumstances?**
the error, see above

**Environment**
```
operator-sdk version
operator-sdk version: "v0.16.0", commit: "55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd", go version: "go1.13.8 linux/amd64"
```

* go version:
```
go version
go version go1.13.6 linux/amd64
```

* Kubernetes version information:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.8-beta.0", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"archive", BuildDate:"2020-01-02T00:00:00Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"aa10b5b", GitTreeState:"clean", BuildDate:"2020-03-16T18:11:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

OpenShift

* Are you writing your operator in ansible, helm, or go?

go

**Possible Solution**
not sure, this seems just like a bug.

**Additional context**
none.

**Comment by camilamacedo86** [comment]
it shows that is missing the var name. See:

Replace :
    
  `status.Conditions `json:",inline"``

 With 

` Conditions status.Conditions `json:"conditions"``

**Comment by raffaelespazzoli** [comment]
for golang the two notation should be essentially equivalent and as expected I'm getting the same error with:
```golang
// MyCRDStatus defines the observed state of MyCRD
// +k8s:openapi-gen=true
type MyCRDStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file
	// Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html

	Conditions status.Conditions `json:",inline"`
}
```

**Comment by camilamacedo86** [comment]
See that the Status structure will represent the status metadata in the CRD and it has an invalid value for this scenario. Replace `json:",inline"` for `json:contionals` for example.

**Comment by raffaelespazzoli** [comment]
it worked.
