### ISSUE TITLE
Feature Request: Generate a Makefile for use instead of requiring operator-sdk for building

### ISSUE THREAD

**Issue by FreedomBen** [operator-framework/operator-sdk#2825]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: "I have an issue when (...)"

Not really, other than I like to minimize project dependencies as much as possible, and would prefer to use the operator-sdk for scaffolding only, rather than as a build tool as well.  I think tools like make are better at that (and indeed operator-sdk itself uses this strategy).

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

I would love to see a new project given a Makefile with the build capabilities injected.  Duplicated functionality is certainly a drawback, and perhaps it's not worth doing this considering it's already implemented in Go code.  But, I thought it might be worth discussing even if we don't do it.

**Comment by camilamacedo86** [comment]
HI @FreedomBen, 

Currently, the SDK has been in a process to be integrated with Kubebuilder.  And then, when this integration is I'm place the Makefile will be provided. We have not an ETA for that, however, you also can follow up the issue https://github.com/operator-framework/operator-sdk/issues/1655 which as this RFE tracked already.

So, far please feel free to create and use a Makefile in your projects as it is done in the Samples. See https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/Makefile.

In this way,  I am closing this one as a duplicate of  #1655. However, please feel free to ping us if you think that would be required for any reason re-open this one.

**Comment by FreedomBen** [comment]
Awesome, thanks @camilamacedo86 !
