### ISSUE TITLE
can centos 8 image be used as a base image for operator docker build ?

### ISSUE THREAD

**Issue by kaushiksrinivas** [operator-framework/operator-sdk#2826]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
General context query on the operator docker image build.

## Question

**What did you do?**
Would like to use centos 8 image as the base image for the docker build of the operator.
default project built using operator sdk fwk provides, rhel registry.access.redhat.com/ubi8/ubi-minimal:latest as the base image for the operator docker.
Can this be replaced with the centos base image ?, if so is there are pre requisites packages which needs to be installed for the operator to run ?

**What did you expect to see?**
Have not tried building yet, asking the query before trying the same.

**What did you see instead? Under which circumstances?**
NA

**Environment**
* operator-sdk version:
"v0.16.0"

  insert release or Git SHA here

* Kubernetes version information:

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by kaushiksrinivas** [comment]
@camilamacedo86 Can you help with this query please.

**Comment by camilamacedo86** [comment]
HI @kaushiksrinivas, 

The images have been using ubi8-minimal since using the minimal one bring many advantages. Could you please let us know why you would like to use the change the image? What is the need that you are trying to solve with?

**Comment by joelanford** [comment]
You should be able to use any base image you want. The `operator-sdk build` command will use your Dockerfile as is.

If you need further info, we can re-open.
