### ISSUE TITLE
Why always generate a file named as tools.go?

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-sdk#2828]
I can see after the code was generated by operator-sdk, there is always a file named as `tools.go` with content as follows:

```go
// +build tools

// Place any runtime dependencies as imports in this file.
// Go modules will be forced to download and install them.
package tools
```

What is the use of this file? Can we remove it? Thanks.

**Comment by joelanford** [comment]
This was added by #1001

We'll be removing this as part of the upcoming Kubebuilder integration.

**Comment by camilamacedo86** [comment]
Hi @joelanford,

could we not close this one since we are already scaffolding the new layout with operator-sdk init?
