### ISSUE TITLE
Local development

### ISSUE THREAD

**Issue by ernoaapa** [operator-framework/operator-sdk#283]
Hi!
The SDK looks interesting!

Is there a way to run the operator locally and use for example `kube proxy` to access Kubernetes API to make the development faster and easier? Or what is the preferred way to develop the operator.

**Comment by etiennecoutaud** [comment]
Hi @ernoaapa 

You can run the operator locally with `operator-sdk up local` 
Associate documentation is [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#2-run-outside-the-cluster)

Run the operator locally is the better way to develop an having a short feedbacks loop. For production use, run the operator inside a pod is prefered.

**Comment by ernoaapa** [comment]
Thank you @etiennecoutaud!
I somehow missed the user guide! Now I hopefully get started, thanks!
