### ISSUE TITLE
Update links that point to CLI docs

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#2832]
Currently there are some links in the website docs that point to CLI docs on GitHub, rather than CLI docs in the site. 
Example: https://operator-sdk.netlify.com/docs/golang/olm-integration/olm-cli/ points to:
https://github.com/operator-framework/operator-sdk/blob/master/doc/cli/operator-sdk_olm_install.md

**Comment by estroz** [comment]
I think this is fixed. Re-open if not.
