### ISSUE TITLE
Correct formatting of log messages in scaffolding

### ISSUE THREAD

**Issue by mansikulkarni96** [operator-framework/operator-sdk#2843]
The log info and error messages that are a part of the operator-sdk scaffolding are not formatted in a structured log format that follows the msg, key, value pair format. It would be better if they are formatted using the standard recommendations given by logr in :https://godoc.org/github.com/go-logr/logr and https://github.com/kubernetes-sigs/controller-runtime/blob/master/TMP-LOGGING.md which suggest specifically avoiding the use of "fmt.Sprintf" inside log.Info messages.

Following the guidelines would help in better debugging and searching to take proper advantage of the logging package. 

To give one such example:
 In file [https://github.com/operator-framework/operator-sdk/blob/master/internal/scaffold/cmd.go](https://github.com/operator-framework/operator-sdk/blob/master/internal/scaffold/cmd.go)
log.Info(fmt.Sprintf("Operator Version: %s", version.Version))
should be structured as : log.Info("operator", "version", version.Version)

**Comment by kensipe** [comment]
It is expected that the move to kubebuilder will reduce the surface area of this issue.

**Comment by estroz** [comment]
Follow up from https://github.com/operator-framework/operator-sdk/issues/2843#issuecomment-616722184: "incorrect" usage of logs will go away for Go operators when `operator-sdk` migrates to kubebuilder's Go scaffolds; ansible/helm operator images may still have incorrectly formatted logs which should be modified going forwards.
