### ISSUE TITLE
Canonical implementation for handling delete events

### ISSUE THREAD

**Issue by blaggacao** [operator-framework/operator-sdk#285]
As an extension of https://github.com/operator-framework/operator-sdk/issues/270, I wonder what should be the canonical way of implementing [delete events](https://github.com/operator-framework/operator-sdk/blob/ef94d7384ebb7385478ed8d1aa332cddfbd6c675/pkg/sdk/types.go#L28)...

My best guess:

```Go
func (h *Handler) Handle(ctx context.Context, event sdk.Event) error {
        if event.Deleted {
		switch o := event.Object.(type) {
        	...
		}
        }
	switch o := event.Object.(type) {
        ...
	}
	return nil
}

```

If this is about right, shouldn't it be bootstrapped [~and documented~](https://github.com/operator-framework/operator-sdk/blob/ef94d7384ebb7385478ed8d1aa332cddfbd6c675/example/memcached-operator/handler.go.tmpl#L32-L34)? Or should that go into the reconcile logic?

-----

Probably [also](https://github.com/operator-framework/operator-sdk-samples/blob/aed6c3b4ef7a0b40d331246ef1ef34c802098f3b/vault-operator/pkg/stub/handler.go#L22):
```Go
- return vault.Reconcile(o)
+ return vault.Reconcile(event)
```
Or even (for avoiding ambiguity in receiver signature):
```Go
- return vault.Reconcile(o)
+ return vault.Reconcile(o, event)
// or
+ return vault.Reconcile(o, event.Deleted)
```
-----

Maybe even out factor [event metadata](https://github.com/operator-framework/operator-sdk/blob/ef94d7384ebb7385478ed8d1aa332cddfbd6c675/pkg/sdk/types.go#L28) in a separate struct to avoid having an explicit receiver but at the same time duplication within the event object?

-----

I see choice where "choice" drives me crazy. :wink:

**Comment by hasbro17** [comment]
@blaggacao Once we switch over to using finalizers then we probably won't have the `Delete` flag in the event metadata and it should be relatively straightforward to detect that a CR is being deleted and do any clean up needed.
In the handler we can look at the deletionTimestamp of the object and then remove the finalizers.
```Go
func (h *Handler) Handle(ctx context.Context, event sdk.Event) error {
    switch o := event.Object.(type) {
    case *v1alpha1.Memcached:
        memcached := o
        if memcached.DeletionTimestamp != nil {
            // Do any clean up necessary and then remove the finalizers
            ...
            memcached.SetFinalizers([]string{})
            err := sdk.Update(memcached)
            if err != nil {
                return fmt.Errorf("failed to update memcached finalizers: %v", err)
            }
            return nil
        }
        ...
    }
}
```

Unless there's something more I think we can close this issue as it falls under #270
