### ISSUE TITLE
New document for describing best practices for troubleshooting reconcile loops

### ISSUE THREAD

**Issue by bradtopol** [operator-framework/operator-sdk#2857]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When discussing https://github.com/operator-framework/operator-sdk/issues/2795 the idea came up that we should have a documentation page that provided best practices for troubleshooting reconcile loops.   The idea was this document would start by providing and aggregated list of pre-req content operator creators should read such as controller runtime docs, the OpenShift Blog on operator best practices, the operator SDK getting started user guide, etc. The document would then provide helpful best practices on how to troubleshoot reconcile loops and some common mistakes to avoid. This document is not intended to provide an exhaustive list of all the mistakes that could be made but instead hopefully provide enough context and detail to help the operator developer troubleshoot their own reconcile loops and avoid well known pitfalls.  Ideally this document will capture a lot of information that is typically considered tribal knowledge and help to aggregate useful references that are spread across multiple locations.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.
A new page in the documentation the meets the goals and objectives described in the above paragraph.

I am willing to take the lead on this but will need guidance from the more senior members of this project to help to capture all the useful troubleshooting techniques that the team is aware of.

**Comment by estroz** [comment]
This is a high-level docs change since it deals with "how kubernetes works". Once we have a clearer picture of our doc organization and maturity we will revisit this issue. Definitely important for v1.0.

In addition: top-level annotated bibliography (links to talks, blog posts, etc) for operator best-practices on SDK website.

**Comment by estroz** [comment]
This probably won't make it into v1.0, but is still important.

/priority important-longterm

**Comment by estroz** [comment]
Work ongoing, part of a larger effort to outline controller patterns and best practices.

**Comment by camilamacedo86** [comment]
This need seems addressed in: https://sdk.operatorframework.io/docs/best-practices/common-recommendation/
See that we are linking the k8s doc https://kubernetes.io/docs/concepts/extend-kubernetes/operator/ as well. 

So, I am closing it as solved. however, please feel free to re-open if you see that we would still be needing to work on this.
