### ISSUE TITLE
Multiple Resources 

### ISSUE THREAD

**Issue by srleyva** [operator-framework/operator-sdk#286]
Is there support (or plans to support) multiple resources that are managed by an operator? An example of this is the Prometheus operator which allows for creation of `Prometheus`, `ServiceMonitor` and `Alertmanager`. It would also be cool to be able to add new resources to an existing project dynamically by using the operator-sdk.

**Comment by hasbro17** [comment]
@srleyva Yes we do plan to support writing an operator that can watch multiple resources.
We have an existing issue #146 tracking that. I've reworded the title to make the issue more clear.
We're currently redesigning the Watch API and the informer/controller abstractions before we can support that.
If there's nothing else that's different from #146 I would recommend closing this issue in favour of that.

**Comment by hasbro17** [comment]
Closing this. Reopen if anything is different from #146
