### ISSUE TITLE
why file "zz_generated.deepcopy.go"  error path?

### ISSUE THREAD

**Issue by shenkonghui** [operator-framework/operator-sdk#2863]
## Bug Report

**What did you do?**
I want add a api

**What did you expect to see?**
"zz_generated.deepcopy.go"  error path, It shoud be in "pkg"

**What did you see instead? Under which circumstances?**

**Environment**
* operator-sdk version:
operator-sdk version: "v0.16.0", commit: "55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd", go version: "go1.13.8 darwin/amd64"

* Kubernetes version information:
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

* go version information:
go version go1.13 darwin/amd64

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**

**Additional context**
gopath
```
"/Users/xxx/work/go:/Users/xxx/go"
```
create project
```
operator-sdk new resource-quota-autoscaler --repo harmonycloud.cn/network/resource-quota-autoscaler

INFO[0000] Creating new Go operator 'resource-quota-autoscaler'.
INFO[0000] Created go.mod
INFO[0000] Created tools.go
INFO[0000] Created cmd/manager/main.go
INFO[0000] Created build/Dockerfile
INFO[0000] Created build/bin/entrypoint
INFO[0000] Created build/bin/user_setup
INFO[0000] Created deploy/service_account.yaml
INFO[0000] Created deploy/role.yaml
INFO[0000] Created deploy/role_binding.yaml
INFO[0000] Created deploy/operator.yaml
INFO[0000] Created pkg/apis/apis.go
INFO[0000] Created pkg/controller/controller.go
INFO[0000] Created version/version.go
INFO[0000] Created .gitignore
INFO[0000] Validating project
```
add api
```
operator-sdk add api --api-version=harmonycloud.cn/v1 --kind=ResourceQuotaAutoscaler

INFO[0000] Generating api version harmonycloud.cn/v1 for kind ResourceQuotaAutoscaler.
INFO[0000] Created pkg/apis/harmonycloud/v1/resourcequotaautoscaler_types.go
INFO[0000] Created pkg/apis/addtoscheme_harmonycloud_v1.go
INFO[0000] Created deploy/crds/harmonycloud.cn_v1_resourcequotaautoscaler_cr.yaml
INFO[0000] RBAC rules in deploy/role.yaml already up to date for the resource (harmonycloud.cn/v1, ResourceQuotaAutoscaler)
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [harmonycloud:[v1], ]
INFO[0009] Code-generation complete.
INFO[0009] Running CRD generator.
INFO[0010] CRD generation complete.
INFO[0010] API generation complete.
```
 file zz_generated.deepcopy.go not int path ./pkg/.. 
![image](https://user-images.githubusercontent.com/10442820/79719699-b3a77400-8311-11ea-822d-85cd81e612da.png)

**Comment by cybertron** [comment]
I'm seeing the same behavior. What did you do to resolve this?

**Comment by camilamacedo86** [comment]
Ensure that you executed the command from the root dir of your project. However, if you still facing problems, could you please raise a new issue and provided all requested information for we are able to help you with?

**Comment by cybertron** [comment]
I ended up re-creating the project from scratch and didn't have this problem the second time around.

**Comment by NoizeMe** [comment]
Sadly I am currently facing the same issue and am pretty lost right now. Any hints on how to resolve this issue?

It happens when I generate an operator outside the GOPATH. I have checked my GOROOT and GOPATH to be correctly set. I have to admit though, that I am running a self-compiled v0.17.0 tag on Windows.

**Comment by drewwells** [comment]
> Ensure that you executed the command from the root dir of your project. However, if you still facing problems, could you please raise a new issue and provided all requested information for we are able to help you with?

We're facing errors as well. Does operator-sdk work if it's a subdirectory inside a go module?
