### ISSUE TITLE
Go: Add OpenCensus

### ISSUE THREAD

**Issue by bclermont** [operator-framework/operator-sdk#2867]
To really achieve the Level IV Operator Capability level, there should be tracing.

I'm manually adding Jaeger/Opentracing to my operators, but I think it should be implemented directly in operator-sdk and add to the APIs that create children span automatically and let developers implement the sub tracing.

This is a major break in API compatibility. but worth it

**Comment by camilamacedo86** [comment]
Hi @bclermont, 

Could you please described what  `Jaeger/Opentracing` provided which and what do you achieve with it? Also, could you please describe what helper did are you asking here as what is the scenario that was solved with?

**Comment by bclermont** [comment]
I have this operator that is super slow and run in few k8s clusters. I added a tons of logs but sometimes things get sluggish and just by looking at the logs it's very difficult to understand.

By using a central jaeger server (like deployed with jaeger operator itself) that constantly ingest traces, I can go look at those instances and see the execution waterfall and pin point where time is spent.

**Comment by camilamacedo86** [comment]
Hi @bclermont, 

Thank you for your reply. I think it would be more clear with the following info added in the first comment. WDYT? Could you please edit it and provided the additional information? PS. I think the versions and vendor used could be helpful as well. 
 

```
**Is your feature request related to a problem? Please describe.**

I have this operator that is super slow and run in few k8s clusters. I added a ton of logs but sometimes things get sluggish and just by looking at the logs it's very difficult to understand.

**What did you expect to see?**

To really achieve the Level IV Operator Capability level, there should be tracing.

I'm manually adding Jaeger/Opentracing to my operators, but I think it should be implemented directly in operator-sdk and add to the APIs that create children span automatically and let developers implement the sub tracing.

By using a central jaeger server (like deployed with jaeger operator itself) that constantly ingest traces, I can go look at those instances and see the execution waterfall and pin point where time is spent.

// TODO: Add an example of its usage as its result to illustrate what do you expect.  

**Environment**
* operator-sdk version:

<!--- Insert operator-sdk release or Git SHA here. -->

* go version:

<!--- Insert the output of `go version` here -->

* Kubernetes version information:

<!--- Insert the output of `kubectl version` here -->

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Additional context**
Add any other context about the problem here.
```
