### ISSUE TITLE
Go: wrap errors in generated golang code

### ISSUE THREAD

**Issue by bclermont** [operator-framework/operator-sdk#2868]
Generated code just do

```go
if  err := x(y); if err != nil {
  return err
}
```

the operator-sdk itself and generated code should `return fmt.Errorf("funcname(%q): %w", y, err)`

instead to allow pin point origin of errors

**Comment by camilamacedo86** [comment]
Hi @bclermont, 

Could you please provide the information requested in the template for we we are able to better understand your request as know what version and etc you are using? 

> **What did you do?**
> A clear and concise description of the steps you took (or insert a code snippet).
> 
> **What did you expect to see?**
> A clear and concise description of what you expected to happen (or insert a code snippet).
> 
> **What did you see instead? Under which circumstances?**
> A clear and concise description of what you expected to happen (or insert a code snippet).
> 
> 
> **Environment**
> * operator-sdk version:
> 
> 
> 
> * go version:
> 
> 
> 
> * Kubernetes version information:
> 
> 
> 
> * Kubernetes cluster kind: 
> 
> * Are you writing your operator in ansible, helm, or go?
> 
> **Possible Solution**
> 
> 
> **Additional context**
> Add any other context about the problem here.
>

**Comment by bclermont** [comment]
Just an example, `pkg/controller/controllger.go`

```
package controller

import (
	"fmt"

	"sigs.k8s.io/controller-runtime/pkg/manager"
)

// AddToManagerFuncs is a list of functions to add all Controllers to the Manager
var AddToManagerFuncs []func(manager.Manager) error

// AddToManager adds all Controllers to the Manager
func AddToManager(m manager.Manager) error {
	for index, f := range AddToManagerFuncs {
		if err := f(m); err != nil {
			return fmt.Errorf("AddToManagerFuncs[%d]: %w", index, err)
		}
	}

	return nil
}
```
