### ISSUE TITLE
Reconcile hangs despite changing primary resource specs

### ISSUE THREAD

**Issue by agill17** [operator-framework/operator-sdk#2871]
## Bug Report

**What did you do?**
I have a controller watching a primary resource. When the resource is initially applied in the cluster, controller runs its reconcile correctly. After some time ( maybe few hours ), if I change the primary resource specs, controller does not perform any reconcile and no logs are outputted. It seems hung, however restarting the controller pod resolves this issue but isn't ideal.

**What did you expect to see?**
Reconcile to run when primary resource is changed

**What did you see instead? Under which circumstances?**
Controller does not run reconcile.

**Environment**
* operator-sdk version: `v0.10.0, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170`

* go version: `go 1.12 darwin/amd64`

* Kubernetes version information:```Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}```

* Kubernetes cluster kind: `AWS using kops`

* Are you writing your operator in ansible, helm, or go?  `go`

**Possible Solution**

**Additional context**
- Manager is created with syncPeriod ( of 30 mins ).
- My reconcile ends with this return
```
return reconcile.Result{Requeue: true}, r.createSvc(cr)
```

**Comment by camilamacedo86** [comment]
Hi @agill17, 

As we spoke about it in the chat could you provide further information for we are able to help with such as the controller implementation and logs?  

Also, it is very important to highlight that you are using an old version of SDK (0.10) which do NOT support the GO version used by you. I am not sure what issues could be caused by it. See: https://github.com/operator-framework/operator-sdk/blob/v0.10.x/go.mod

And then, that you are using go1.14.1 which is not indeed currently supported in the latest version of SDK which is using 1.13.

**Comment by agill17** [comment]
Apologies, thats the go version I am currently using but this binary was compiled with go 1.12.x. I will update the github issue

**Comment by camilamacedo86** [comment]
Hi @agill17,

As we spoke about it in the chat could you provide further information for we are able to help with such as the controller implementation and logs?

**Comment by agill17** [comment]
@camilamacedo86 here is a snippet from main.go
```
	namespace, err := k8sutil.GetWatchNamespace()
	if err != nil {
		log.Error(err, "Failed to get watch namespace")
		os.Exit(1)
	}

	// Get a config to talk to the apiserver
	cfg, err := config.GetConfig()
	if err != nil {
		log.Error(err, "")
		os.Exit(1)
	}

	ctx := context.TODO()
	// Become the leader before proceeding
	err = leader.Become(ctx, "db-operator-lock")
	if err != nil {
		log.Error(err, "")
		os.Exit(1)
	}

	syncPeriod := 30 * time.Minute
	// Create a new Cmd to provide shared dependencies and start components
	mgr, err := manager.New(cfg, manager.Options{
		Namespace:          namespace,
		MapperProvider:     restmapper.NewDynamicRESTMapper,
		MetricsBindAddress: fmt.Sprintf("%s:%d", metricsHost, metricsPort),
		SyncPeriod:         &syncPeriod,
	})
	if err != nil {
		log.Error(err, "")
		os.Exit(1)
	}
```

In operator deployment the value of `WATCH_NAMESPACE` env var is set to `""`
