### ISSUE TITLE
operator-sdk generate csv deprecation few low issues.  

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#2872]
## Bug Report

**What did you do?**
Run the following command with 0.17 SDK. 

```
 $ operator-sdk generate csv --csv-version 0.17.0 --update-crds
INFO[0000] Generating CSV manifest version 0.17.0       
INFO[0007] Fill in the following required fields in file memcached-operator.clusterserviceversion.yaml:
	spec.description
	spec.keywords
	spec.provider 
[Deprecation Notice] Package manifests are deprecated. Run `operator-sdk bundle create --generate-only` to create operator metadata. Refer to the version upgrade guide for more information: https://operator-sdk.netlify.com/docs/migration/version-upgrade-guide
```

INFO[0007] CSV manifest generated successfully          

**What did you expect to see?**
Note see the msgs : 

```
INFO[0000] Generating CSV manifest version 0.17.0       
INFO[0007] Fill in the following required fields in file memcached-operator.clusterserviceversion.yaml:
	spec.description
	spec.keywords
	spec.provider 
```

Since the CSV will not be generated. 

Also, I would not expect changes in the `deploy/olm-catalog/` dir and it happens. see:

<img width="651" alt="Screenshot 2020-04-21 at 18 05 37" src="https://user-images.githubusercontent.com/7708031/79892672-c8ac0200-83fa-11ea-9d84-5fc615116a61.png">
<img width="462" alt="Screenshot 2020-04-21 at 18 05 30" src="https://user-images.githubusercontent.com/7708031/79892679-cb0e5c00-83fa-11ea-91de-fe61c3de8742.png">

**Environment**
* operator-sdk version: 0.17
* go version: 1.13

**Comment by camilamacedo86** [comment]
c/c @estroz

**Comment by estroz** [comment]
Why would the CSV not be generated in this case?

**Comment by camilamacedo86** [comment]
Hi @estroz, 

Regards the depreciation and the current behaviour of this command I think we have 3 issues. 

- A new CSV are no longer been generating and then I understand that it was the expected behaviour with the deprecation of the feature. However, the msg says that it will be. 
- This manifest dir that has been being created and shows that should not.
- I am unable to find the specific info about it in the https://operator-sdk.netlify.com/docs/migration/version-upgrade-guide.

**Comment by estroz** [comment]
A new bundle containing a CSV manifest is generated at `deploy/olm-catalog/<operator-name>/manifests/<operator-name>.clusterserviceversion.yaml`. Package manifests are deprecated; the reason you're seeing that message is because a package manifest already exists in `deploy/olm-catalog/<operator-name>` in your test scenario. The command is working as intended.

**Comment by camilamacedo86** [comment]
Tks for the clarification. Just adding a summary. 
- Now the command will gen the CSV but in the manifest dir and whiteout the tag dir as well.
- We are using the new format: https://github.com/operator-framework/operator-registry/blob/master/docs/design/operator-bundle.md#bundle-manifest-format
