### ISSUE TITLE
The command `operator-sdk bundle create  --generate-only=true` should check if is in the root of the project when no dir arg is informed

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#2876]
## Bug Report

**What did you do?**
Run `operator-sdk bundle create  --generate-only=true` outside of the root of the project

**What did you expect to see?**
The default error saying that it should be executed from the root of the project

**What did you see instead? Under which circumstances?**

```
$ operator-sdk bundle create  --generate-only=true
FATA[0000] error generating bundle image files: stat /Users/camilamacedo/go/src/github.com/operator-framework/operator-sdk-samples/go/memcached-operator/deploy/deploy/olm-catalog/deploy/manifests: no such file or directory 
```

**Environment**
* operator-sdk version: 0.17
* go version: 1.13

**Possible Solution**

- Use the func [MustInProjectRoot()](https://github.com/operator-framework/operator-sdk/blob/master/internal/util/projutil/project_util.go#L77) when the arg `--directory` is empty.

**Comment by estroz** [comment]
Forcing the invoker to be in the project root only some of the time is bad UX. It would be better to ensure the default directory is `stat`'d and if it doesn't exist return a helpful error message.

**Comment by estroz** [comment]
This was actually [fixed](https://github.com/operator-framework/operator-sdk/pull/2944/files#diff-1d8e161f97d3f35b45c2ec48c82757e0R160-R163) in #2944.
