### ISSUE TITLE
The `operator-sdk bundle create --generate-only` do not info where the files were gen. 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#2878]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I'd like to know where the bundle was generated. However, when we run the command this info is not informed. 

```
 $ operator-sdk bundle create --generate-only
INFO[0000] Building annotations.yaml                    
INFO[0000] Generating output manifests directory        
INFO[0000] Building Dockerfile                          
```

**Describe the solution you'd like**
Just output the path/dir.

**Comment by estroz** [comment]
I'd re-create this issue in https://github.com/operator-framework/operator-registry/ since the SDK does not control those log messages from this command.

**Comment by camilamacedo86** [comment]
Hi @estroz, 

I still think that it would be here. We create the dir in SDK when it is not informed. See here: https://github.com/operator-framework/operator-sdk/blob/master/cmd/operator-sdk/bundle/create.go#L119

So, the suggested solution would just log the path. Something such as:

> INFO[0000] Building the bundle in the directory = <value>

**Comment by camilamacedo86** [comment]
I thought better about it and you are right is better it be done there. Very small easy thing btw so I will be working on it. Let's keep the issue open here but I will solve it there.

**Comment by camilamacedo86** [comment]
Closing as suggested since the PR for operator-registry is done already. 
See: https://github.com/operator-framework/operator-registry/pull/296
