### ISSUE TITLE
Generated code should use aliased imports to avoid conflicts

### ISSUE THREAD

**Issue by larham** [operator-framework/operator-sdk#288]
Repro:

`operator-sdk new app-operator --api-version=app.example.com/v1 --kind=App`

Note change above to "v1" instead of "v1alpha1" as in the README.md Quick Start.

https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/handler_tmpl.go#L27

imports "k8s.io/api/core/v1", which can conflict with the generated handler import above it if `{{.Version}}` is "v1"

**Comment by larham** [comment]
CC: @dsharp-pivotal

**Comment by hasbro17** [comment]
Fixed by #299
