### ISSUE TITLE
invalid crd generated

### ISSUE THREAD

**Issue by davidkarlsen** [operator-framework/operator-sdk#2885]
## Bug Report

**What did you do?**
CRD:
```
// GithubActionRunnerSpec defines the desired state of GithubActionRunner
type GithubActionRunnerSpec struct {
	Organization string `json:"organization"`
	MinRunners uint `json:"minRunners"`
	MaxRunners uint `json:"maxRunners"`
	PodSpec v1.PodSpec `json:"podSpec"`
	TokenRef v1.SecretKeySelector `json:"tokenRef"`
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file
	// Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
}
```

**What did you expect to see?**
A valid CRD being generated.

**What did you see instead? Under which circumstances?**
unknown field "x-kubernetes-list-map-keys" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps,
when applying generated CRD

```
k create -f deploy/crds/garo.tietoevry.com_githubactionrunners_crd.yaml 
error: error validating "deploy/crds/garo.tietoevry.com_githubactionrunners_crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.podSpec.properties.topologySpreadConstraints): unknown field "x-kubernetes-list-map-keys" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.podSpec.properties.topologySpreadConstraints): unknown field "x-kubernetes-list-type" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps]; if you choose to ignore these errors, turn validation off with --validate=false
[et2448@Davids-Work-MacBook-Pro github-actions-runner-operator (⎈ |docker-for-desktop:actions-runner)]$ less deploy/crds/garo.tietoevry.com_githubactionrunners_crd.yaml 
```

**Environment**
* operator-sdk version:

```
operator-sdk version
operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "v1.17.2", go version: "go1.14.2 darwin/amd64"
```

* go version:
```
go version
go version go1.14.2 darwin/amd64
```
* Kubernetes version information:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
docker for desktop

* Are you writing your operator in ansible, helm, or go?
go

**Possible Solution**

**Additional context**

**Comment by estroz** [comment]
That scheme property was [introduced](https://kubernetes.io/docs/reference/using-api/api-concepts/#merge-strategy) in v1.16. operator-sdk v0.17 is on k8s version v1.17; the v1.17 `v1.PodSpec` contains a [marker](https://github.com/kubernetes/api/blob/kubernetes-1.17.2/core/v1/types.go#L2154-L2155) to generate this property. Your k8s cluster version is v1.15, so you'll need to use [operator-sdk v0.12](https://github.com/operator-framework/operator-sdk/releases/tag/v0.12.0) which supports k8s v1.15.

**Comment by davidkarlsen** [comment]
Do you have a matrix of operator versions and the k8s versions they fit?
I guess I need to build multiple versions of my operator in order to support different k8s versions.

**Comment by estroz** [comment]
Not right now, see #2118. I would test your operator with all the k8s versions (dependencies and cluster) that it can run on, and make changes when something breaks.

**Comment by sanbornick** [comment]
From what I can tell merge strategy markers are required by the operator SDK but are optional in k8s. So I cannot simply not use markers and use the latest SDK and compile an operator that works on 1.11(3.11 ocp) through latest k8s/ocp.

So either I use an old SDK that produces something that works on 3.11+ or build multiple versions based on multiple SDK's, along with other code differences such as merge strategy inclusion, in order to support different k8s versions. This is not ideal. Am I misunderstanding?

**Comment by estroz** [comment]
@sanbornick the SDK's CRD generator targets specific versions of the CRD scheme, ex. v1 and v1beta1. There's not much we can do if those schema change for whatever reason when the SDK bumps k8s versions in a new release.
