### ISSUE TITLE
Why not use klog as default log management for operator-sdk

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-sdk#2887]
I found the code generated by operator-sdk is not using klog, can anyone show some reason why not use klog as default? I can see kubernetes is using klog, so why not keep this consistent with kubernetes?

**Comment by camilamacedo86** [comment]
HI @gyliu513, 

The [klog](https://github.com/kubernetes/klog) is not used by [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) and [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime). 

Also, by looking its readme we find that `The decision to create klog was one that wasn't made lightly, but it was necessary due to some drawbacks that are present in glog`

So, I'd like to ask in your opinion what advantages the projects would have by using it? What problems would be solved with?

**Comment by gyliu513** [comment]
I can see the major difference is the log format.

This is golog which is in json format:
```
{"level":"info","ts":1587517980.2473092,"logger":"cmd","msg":"Operator Version: 0.0.1"}
{"level":"info","ts":1587517980.2473514,"logger":"cmd","msg":"Go Version: go1.13"}
```

But klog is more reable, including the filename of the log as well:
```
I0422 10:26:16.893389   23689 reconcile_operand.go:54] Reconciling custom resource: ibm-management-ingress-operator
I0422 10:26:16.893403   23689 reconcile_operand.go:89] Looking for the Cluster Service Version in Subscription: ibm-management-ingress-operator
```

**Comment by joelanford** [comment]
@gyliu513 You can use different log formats. Try using `--zap-encoder=console` in your operator deployment.

**Comment by gyliu513** [comment]
Thanks @joelanford but I can see even if using `zap-encode=console`, I still cannot see the file name and line of code for where the log is from based on document here https://github.com/operator-framework/operator-sdk/blob/master/doc/user/logging.md#output-using-custom-zap-logger

```
ts=2020-02-27T23:10:33Z level=info msg="Printing at INFO level"
ts=2020-02-27T23:10:33Z level=info msg="Operator Version: 0.0.1"
ts=2020-02-27T23:10:33Z level=info msg="Go Version: go1.13.8"
ts=2020-02-27T23:10:33Z level=info msg="Go OS/Arch: darwin/amd64"
ts=2020-02-27T23:10:33Z level=info msg="Version of operator-sdk: v0.15.2"
```

**Comment by joelanford** [comment]
@gyliu513 It's possible with zap to include the caller information as well. You would just need to provide a custom logger.

```go
package main

import (
        "errors"
        "os"

        "go.uber.org/zap"
        "go.uber.org/zap/zapcore"
        logf "sigs.k8s.io/controller-runtime/pkg/log"
        zapcr "sigs.k8s.io/controller-runtime/pkg/log/zap"
)

var log = logf.Log.WithName("cmd")

func main() {
        encoderConfig := zap.NewDevelopmentEncoderConfig()
        encoderConfig.EncodeCaller = zapcore.ShortCallerEncoder
        encoderConfig.CallerKey = "caller"
        consoleEncoder := zapcore.NewConsoleEncoder(encoderConfig)

        logger := zapcr.New(zapcr.WriteTo(os.Stdout), zapcr.Encoder(consoleEncoder), zapcr.RawZapOpts(zap.AddCaller()))

        logf.SetLogger(logger)

        log.Info("I'm an info message")
        log.Error(errors.New("bad error"), "I'm an error message")
}

```

It _is_ also possible to use klog with controller-runtime since there is a logr implementation for klog. See https://github.com/kubernetes/klog/tree/master/klogr. Note that it is currently listed as a beta.

**Comment by joelanford** [comment]
Looking at https://github.com/ManageIQ/manageiq-pods/issues/461

You may want this instead:
```go
func main() {
        encoderConfig := zap.NewProductionEncoderConfig()
        encoderConfig.EncodeCaller = zapcore.ShortCallerEncoder
        encoderConfig.CallerKey = "caller"
        consoleEncoder := zapcore.NewJSONEncoder(encoderConfig)

        logger := zapcr.New(zapcr.WriteTo(os.Stdout), zapcr.Encoder(consoleEncoder), zapcr.RawZapOpts(zap.AddCaller()))

        logf.SetLogger(logger)

        log.Info("I'm an info message")
        log.Error(errors.New("bad error"), "I'm an error message")
}
```

**Comment by joelanford** [comment]
I think this answers the question. Also, just to clarify we are not planning to switch from zap to klog. We just wanted to make sure to get back to you about how you can do this with existing functionality before we released v0.18.0.

Let us know if there's anything else we can help with!

**Comment by gyliu513** [comment]
Thanks @joelanford , my major concern is most kubernetes eco-system projects are using klog, why not switch the default log to klog for operator-sdk to keep consistent?

**Comment by lkysow** [comment]
The leader election logger is hard-coded to use klog so you get its log interleaved with a different format:
```
{"level":"info","ts":1601671343.4464586,"logger":"setup","msg":"starting manager"}
I1002 20:42:23.543698       1 leaderelection.go:242] attempting to acquire leader lease  default/......
{"level":"info","ts":1601671343.5438871,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
```
