### ISSUE TITLE
operator-sdk olm status reports no insallation found on OCP 4.3 cluster

### ISSUE THREAD

**Issue by aharbis** [operator-framework/operator-sdk#2915]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

Question about `operator-sdk olm status` functionality / behavior.

## Question

**What did you do?**

```
$ operator-sdk olm status
```

**What did you expect to see?**

OLM status found / green. Verified by:

```
$ oc get deployments -n openshift-operator-lifecycle-manager
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
catalog-operator   1/1     1            1           39d
olm-operator       1/1     1            1           39d
packageserver      2/2     2            2           39d
```

**What did you see instead? Under which circumstances?**

```
$ operator-sdk olm status
FATA[0002] Failed to get OLM status: no existing installation found
```

**Environment**
* operator-sdk version:

```
$ operator-sdk version
operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "unknown", go version: "go1.13.10 linux/amd64"
```

* Kubernetes version information:

```
$ oc version
Client Version: openshift-clients-4.3.0-201910250623-88-g6a937dfe
Server Version: 4.3.0
Kubernetes Version: v1.16.2
```

* Kubernetes cluster kind: 

OCP 4.3

**Additional context**
Add any other context about the question here.

**Comment by estroz** [comment]
@aharbis set `operator-sdk olm status --olm-namespace=openshift-operator-lifecycle-manager`.

**Comment by aharbis** [comment]
🤦‍♂️ Makes sense, thanks!
