### ISSUE TITLE
Accessing cr data in different crd 

### ISSUE THREAD

**Issue by RahulNishad** [operator-framework/operator-sdk#2916]
Is it possible to access different cr data in another crd controller ? if it's possible how we can do it .

**Comment by camilamacedo86** [comment]
Yes, it is. See:

> When following the Getting Started, one of the first steps is to run the command operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=Memcached. The purpose of this command is to generate Custom Resource (CR) and Custom Resource Definition (CRD) resources for the Memcached Kind. This command is creating the API with the group cache.example.com, and version v1alpha1  which uniquely identifies the new CRD of the Memcached Kind.
> 
> Consequently, by using the Operator SDK tool, we can create our APIs and objects that will represent our solutions on these platforms. The Getting Started tutorial adds only a single kind of resource; however, it could have as many Kinds as needed (1…N). Basically, the CRDs are a definition of our customized Objects, and the CRs are an instance of it.

Ref: https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/

So, you can watch create, delete and update a CR of a kind of CRD that is not the controller owner. You can check here in a personal project where in the backup controller I am doing operations with the database CR for example. See: https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/controller/backup/controller.go#L131 

I am closing it as sorted out. However, please feel free to ping us if you think that it should be re-opened.
