### ISSUE TITLE
Missing documentation on test-framework

### ISSUE THREAD

**Issue by JoaoBraveCoding** [operator-framework/operator-sdk#2922]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

Documentation

## Question

In a previous release (0.16) of Operator-SDK there used to be some documentation on how to develop and run tests under `docs/test-framework` since the most recent update (0.17)  this documentation seems to have disappeared. What happened? Was this done by accident, did the documentation got relocated?

link to the previous documentation https://github.com/operator-framework/operator-sdk/tree/55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd/doc/test-framework

**Comment by camilamacedo86** [comment]
HI @JoaoBraveCoding, 

We are in the middle to of a process to move all docs to the website. See in the open PR's that you are able to check a preview of it. E.g https://deploy-preview-2920--operator-sdk.netlify.app/

- The e2e doc is here: https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/golang/e2e-tests.md
- The unit test doc is here: https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/golang/unit-testing.md

In this way, I am closing this one as sorted out. However, please feel free to ask for we re-open if you think that something still required to get done here about this subject.
