### ISSUE TITLE
unable to deploy with operator-sdk run --olm

### ISSUE THREAD

**Issue by raffaelespazzoli** [operator-framework/operator-sdk#2923]
## Bug Report

I'm deploying my operator with this command
```
operator-sdk run --olm --olm-namespace openshift-operator-lifecycle-manager --operator-namespace namespace-configuration-operator --install-mode=OwnNamespace=namespace-configuration-operator --operator-version $new_version
```

the operator deployment hangs in pending state:
![image](https://user-images.githubusercontent.com/6179036/80487949-9e42d300-892b-11ea-9cfa-4f5b1733309a.png)

see in attachment the csv, install plan.
[install-plan.txt](https://github.com/operator-framework/operator-sdk/files/4545746/install-plan.txt)
[csv.txt](https://github.com/operator-framework/operator-sdk/files/4545748/csv.txt)

A hint that something is wrong here is the fact that this operator defines 3 crds: userconfig, groupconfig, namespaceconfig. In the install plan though we can see 4 crds: 2 versions for namespaceconfig and 2 versions for groupconfigs:

![image](https://user-images.githubusercontent.com/6179036/80488508-7142f000-892c-11ea-8c35-77a345bd148c.png)

The operator seems to be stuck when it tries to install the second set of versions.

**What did you do?**
see above

**What did you expect to see?**
operator correctly installed

**What did you see instead? Under which circumstances?**
see above

**Environment**
* operator-sdk version:

```
operator-sdk version
operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "unknown", go version: "go1.13.10 linux/amd64"
```

* go version:

```
go version
go version go1.13.9 linux/amd64
```

* Kubernetes version information:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.8-beta.0", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"archive", BuildDate:"2020-01-02T00:00:00Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"a02f27a", GitTreeState:"clean", BuildDate:"2020-04-13T12:04:13Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

OCP

* Are you writing your operator in ansible, helm, or go?

go

**Possible Solution**
I don't have a workaround.

**Additional context**
First time I'm using the new `run --olm` command and I could be getting something wrong.

**Comment by estroz** [comment]
Can you link the full source for your operator?

/assign
/triage needs-information

**Comment by raffaelespazzoli** [comment]
here is the branch which can be used to reproduce the issue:
https://github.com/raffaelespazzoli/namespace-configuration-operator/tree/preparing-for-v0.2.0
@estroz
