### ISSUE TITLE
Create sub custom resources

### ISSUE THREAD

**Issue by fiftoine** [operator-framework/operator-sdk#293]
Hi,

Is it actually possible for an operator to create custom resources defined in another operator?

Let's say I have an operator op-X to handle CR of kind X.
And I would like in an operator-Y to create, update, delete CRs of kind X (among others).

Actually, importing the operator-X api in operator-Y tells me I can't use the generated CR X definition in the Create method.

```
Error: failed to build: (building environment-operator...
# repo/cloud-native/operator-Y/pkg/stub
pkg/stub/handler.go:74:34: cannot use dgcCr.DeepCopy() (type *"repo/cloud-native/operator-X/pkg/apis/cloud/v1alpha1".CrType) as type sdk.Object in argument to sdk.Create:
	*"repo/cloud-native/operator-x/pkg/apis/cloud/v1alpha1".CrType does not implement sdk.Object (wrong type for DeepCopyObject method)
		have DeepCopyObject() "repo/cloud-native/operator-x/vendor/k8s.io/apimachinery/pkg/runtime".Object
		want DeepCopyObject() "repo/cloud-native/operator-y/vendor/k8s.io/apimachinery/pkg/runtime".Object
)
```
Thanks in advance

**Comment by fiftoine** [comment]
go: go1.10.2
dep : v0.4.1
operator-sdk : 0.0.5+git

It is true the vault example creates an etcd CR using imported API, indeed.

But in my case, it seems that the k8s.io/apimachinery/pkg/runtime package are different from the points of view of the two operators.

OP-X sees repo/cloud-native/operator-x/vendor/k8s.io/...
OP-Y sees repo/cloud-native/operator-y/vendor/k8s.io/...

And from OP-Y, I want to create a CR X using metav1.TypeMeta and metav1.ObjectMeta, go complains about it because it wants something from the OP-Y vendor folder and not from the OP-X vendor folder...

**Comment by shawn-hurley** [comment]
I think that you need to set up `OP-y` to include `OP-x` in `OP-y` vendor folder and remove `OP-x` vendor folder. This is a go dependency problem. 

You should have dep added to your operator if you generated `OP-y` with the command line. I would suggest that you add OP-x as a constraint. This will set up the correct vendor folder structure for `OP-y`

Example: 
```toml
[[constraint]]
  name = "github.com/cloud-native/operator-x"
  branch = "master"
```

Here is the documentation on go dep: https://golang.github.io/dep/docs/introduction.html

@fanminshi Is there something that I missed?

**Comment by fiftoine** [comment]
The problem is that I need to work on both operators at the same time, I can't allow to delete/dep ensure each time I need to switch building operators...

**Comment by chancez** [comment]
@fiftoine You shouldn't be importing packages located in `vendor`, you should be importing the non-vendored path and the Go tool chain will use the copy located in `vendor` if it exists.

**Comment by nicknezis** [comment]
I also ran into this problem. Have both OP-x and OP-y in my GOPATH. Each has its own vendor folder with the same copy of the `k8s.io/` package. I'm somewhat new to Go, should I not have both of these projects co-located in the same GOPATH?

**Comment by shawn-hurley** [comment]
@nicknezis 
To do this you should have either OP-x vendored into OP-y with a tool like `dep` or you should have OP-y vendored into OP-x. If you want to have them both in your go path I would not suggest this approach but you could delete the vendor directories and then in your go path have all the dependancies.

@hasbro17 I think we should close this issue as this is not something that the operator-sdk could fix. Thoughts?

**Comment by joelanford** [comment]
@shawn-hurley I agree, this is an issue with go tooling and not something operator-sdk can fix.

**Comment by BuddhiWathsala** [comment]
I had the same problem. But I followed a different approach and make this work. 

1. First I copied the `OP-X/pkg/apis/<OP-X-Kind>/` to `OP-Y/pkg/apis/`.

1. Then added the new scheme definition in `main.go` file as described in this [doc](https://github.com/operator-framework/operator-sdk/blob/c3a77eee021a1cc6a31861a0efd253dc23fbe591/doc/user-guide.md#register-with-the-managers-scheme).

Then it works perfectly. Hope this comment might help someone.
