### ISSUE TITLE
Do we need to have a seperate controller for reconciling deployment,statefulset

### ISSUE THREAD

**Issue by AdheipSingh** [operator-framework/operator-sdk#2933]
## Type of question

**how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

**What did you do?**
i am implementing a operator which deploys deployments and statefulsets. I have a single controller which reconciles the deployments as well as statefulset workloads. Do i need to have a seperate controller for managing deployment and statefulsets. I haven;t seen any issue so far. Just want  to confirm the best practice. 
- here i deploy the sts
https://github.com/BinaryOmen/druid-operator/blob/master/pkg/controller/druid/reconcile.go#L70
- here i deploy the deployments
https://github.com/BinaryOmen/druid-operator/blob/master/pkg/controller/druid/reconcile.go#L79

**Comment by estroz** [comment]
@AdheipSingh a controller reconciles a single object, which is an instantiation of your `Druid` type. Any operation related to managing that object should be dealt with in that controller, ex. your Deployments and StatefulSets if they are created by a `Druid`.

For more info on controllers, check out this [overview](https://book.kubebuilder.io/cronjob-tutorial/controller-overview.html).

Feel free to re-open this issue if you have follow-up questions.

**Comment by AdheipSingh** [comment]
@estroz thanks a lot for clearing the doubt.
