### ISSUE TITLE
CSV generation configuration

### ISSUE THREAD

**Issue by DTMad** [operator-framework/operator-sdk#2960]
We updated the operator-sdk version to 0.17.0 and now try to use the CSV generation to create the CSV and CRD files accordingly.

Our file structure looks like that:

deploy
├── common
│   ├── clusterrole.yaml
│   ├── deployment.yaml
│   ├── ...
├── cr.yaml
├── crds
│   ├── crd.yaml
├── kubernetes
│   ├── role.yaml
│   ├── rolebinding.yaml
│   ├── ...
├── olm
│   ├── kubernetes
│   │   ├── 0.1.0
│   │   │   ├── ....v0.1.0.clusterserviceversion.yaml
│   │   │   └── ...crd.yaml
│   │   ├── ...
│   │   ├── 0.7.1
│   │   │   ├── ...v0.7.1.clusterserviceversion.yaml
│   │   │   └── ...crd.yaml
│   │   └── xxx.package.yaml
│   └── openshift
│       ├── 0.1.0
│       │   ├── ....v0.1.0.clusterserviceversion.yaml
│       │   └── ...crd.yaml
│       ├── ...
│       ├── 0.7.1
│       │   ├── ...v0.7.1.clusterserviceversion.yaml
│       │   └── ...crd.yaml
│       └── xxx.package.yaml
└── openshift
    ├── deployment.yaml
    ├── role.yaml
    ├── ...

We used to generate the CSV for Kubernetes and Openshift into different folders. Furthermore we keep the .yaml files which they have in common in the corresponding 'common' folder.
The command we used to generate before was:
`operator-sdk generate csv --csv-channel alpha --csv-version 0.X.X --csv-config=<some_config>.yaml --from-version 0.X.X`

Since the `csv-config` parameter got removed and the `from-version` parameter is now deprecated I'm not clear how the command would look like with the new version (and params).

Could you help me out here?
Thanks!

**Comment by estroz** [comment]
@DTMad take a look at the CLI docs for [`generate csv`](https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/cli/operator-sdk_generate_csv.md), there are now flags that correspond to CSV config fields.

Feel free to re-open this issue if you don't find what you need.
