### ISSUE TITLE
Unable to generate lister and informer using generate-groups.sh 

### ISSUE THREAD

**Issue by harche** [operator-framework/operator-sdk#2961]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

Yes - I need some help around operator-sdk

## Question

**What did you do?**
Since `operator-sdk` doesn't generate `client/lister/informer` I am trying to use the [code-generator](https://github.com/kubernetes/code-generator) for that purpose. I created a sample test operator, https://github.com/harche/test-operator and now I am trying to generate `client/lister/informer` for it. 

```bash
$ ./generate-groups.sh all github.com/harche/test-operator/pkg/generated github.com/harche/test-operator/pkg/apis cache:v1alpha1
Generating deepcopy funcs
F0503 12:49:44.542561  341745 main.go:82] Error: Failed making a parser: unable to add directory "github.com/harche/test-operator/pkg/apis/cache/v1alpha1": unable to import "github.com/harche/test-operator/pkg/apis/cache/v1alpha1": go/build: go list github.com/harche/test-operator/pkg/apis/cache/v1alpha1: exit status 1
go: finding module for package github.com/harche/test-operator/pkg/apis/cache/v1alpha1
go: found github.com/harche/test-operator/pkg/apis/cache/v1alpha1 in github.com/harche/test-operator v0.0.0-20200503071214-e2940b6b4fd8
go: github.com/harche/test-operator@v0.0.0-20200503071214-e2940b6b4fd8 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0

```

**What did you expect to see?**
I need to use a static client and an informer for the custom resources that I am introducing in my application, so I was hoping to get that generated while using operator-sdk to write the operator.

**What did you see instead? Under which circumstances?**
Failure mentioned above. 

**Environment**
* operator-sdk version:
```bash
$ operator-sdk version 
operator-sdk version: "v0.16.0", commit: "55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd", go version: "go1.13.8 linux/amd64"
```

  insert release or Git SHA here

* Kubernetes version information:

  insert output of `kubectl version` here

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by estroz** [comment]
@harche can you link your `go.mod` file?

**Comment by harche** [comment]
@estroz thanks for that tip. 

I ran into the same problem even with, `./generate-groups.sh all ./pkg/generated ./pkg/apis cache:v1alpha1` but then I add the absolute path of `generate-groups.sh` to my `$PATH` and executed following command from the source root of my operator and it worked just fine. 

`generate-groups.sh all github.com/harche/kata-operator/pkg/^Cnerated github.com/harche/kata-operator/pkg/apis cache:v1alpha1`

Thanks again for the pointer.
