### ISSUE TITLE
Example for bundle validate does not work

### ISSUE THREAD

**Issue by shawn-hurley** [operator-framework/operator-sdk#2963]
## Bug Report

The help text for `operator-sdk bundle validate` has this section:

```bash
# Ensure the image with modified metadata/Dockerfile is valid.
$ operator-sdk bundle validate quay.io/example/test-operator:v0.1.0
```

I wonder if we can create a repo with an invalid bundle and use that as an example so the example can be executed?

**Comment by estroz** [comment]
Above that line the docs direct you to build and push the image yourself:
```
To build and validate an image:

  # Build and push the image using the docker CLI.
  $ operator-sdk bundle create quay.io/example/test-operator:v0.1.0
  $ docker push quay.io/example/test-operator:v0.1.0

  # Ensure the image with modified metadata and Dockerfile is valid.
  $ operator-sdk bundle validate quay.io/example/test-operator:v0.1.0
```

Perhaps the following would be better so users don't assume the `example` namespace exists:
```
To build and validate an image:

  # Create a registry namespace or use an existing one.
  $ export QUAY_NAMESPACE=<your-namespace>

  # Build and push the image using the docker CLI.
  $ operator-sdk bundle create quay.io/$QUAY_NAMESPACE/test-operator:v0.1.0
  $ docker push quay.io/$QUAY_NAMESPACE/test-operator:v0.1.0

  # Ensure the image with modified metadata and Dockerfile is valid.
  $ operator-sdk bundle validate quay.io/$QUAY_NAMESPACE/test-operator:v0.1.0
```

**Comment by camilamacedo86** [comment]
I will get this one and add it to: https://github.com/operator-framework/operator-sdk/pull/2905

**Comment by camilamacedo86** [comment]
To reproduce a test and see an invalid bundle we can just add any file in the bundle dirs which is not part of the bundle. E.g `cp operator.yml to manifest`

**Comment by camilamacedo86** [comment]
The info suggested above to upgrade the docs are added in the PR: https://github.com/operator-framework/operator-sdk/issues/2963
