### ISSUE TITLE
Could you provide an option to only execute `go build` from operator-sdk build step?

### ISSUE THREAD

**Issue by skycmoon** [operator-framework/operator-sdk#2972]
## Feature Request
Currently, `operator-sdk build {image information}` does two things. First `go build` then `docker build`. The problem is that I need to have to build the executable inside a dockerized container for the limitation of CI/CD infrastructure in my company.
 
For that reason, it would be very useful to provide an option to choose only `go build`, not `docker build` using some flag or simply `operator-sdk build`.

I currently have a workaround to build my project in the dockerized container. But I'm not sure this approach would be safe for the future change of operator-sdk build command.
```
RUN env GOOS=linux CGO_ENABLED=0 \
  go build -o ./build/_output/bin/service-deployment-operator \
  -gcflags="all=-trimpath=$(dirname $PWD)" \
  -asmflags="all=-trimpath=$(dirname $PWD)" \
  ./cmd/manager
```

**Comment by camilamacedo86** [comment]
HI @skycmoon, 
 
It was requested and deferred in the past already. See #1600.

Also, you can check in #2568 all information provided over how it works to allow you to create your makefile target.

Please, let us know if it answers your question and if we can close this one.

**Comment by estroz** [comment]
Since this question has already been addressed, closing.
