### ISSUE TITLE
How to upgrade from package bundle to manifest bundle

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-sdk#2977]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

operator-sdk 0.17.0 support both  package bundle and manifest bundle, my question is does there a upgrade solution for customer to upgrade from package bundle to manifest bundle?

**Comment by estroz** [comment]
@gyliu513 we're currently working on a migration solution. Will keep you posted on this.

@dmesser @shawn-hurley @joelanford 

/triage support

**Comment by dmesser** [comment]
@gyliu513 The `opm` tool will be able to convert a single version of an operator in package manifest format to bundle manifest format. We are currently working on a wrapper script to make this run in a loop to produce bundles for all versions in a package.

**Comment by gyliu513** [comment]
@dmesser what is `opm`?

**Comment by dmesser** [comment]
@gyliu513 A new [tool](https://github.com/operator-framework/operator-registry/blob/master/docs/design/opm-tooling.md) that comes with the new bundle format: https://github.com/operator-framework/community-operators/issues/1680

**Comment by gyliu513** [comment]
FYI @chenzhiwei @DanielXLee @horis233

**Comment by jmrodri** [comment]
Fixed by PR #4718 a command that allows you to convert a packagemanifest into a set of bundles.
