### ISSUE TITLE
Build official docker image with operator-sdk cli

### ISSUE THREAD

**Issue by burov** [operator-framework/operator-sdk#2978]
## Feature Request

**Is your feature request related to a problem? Please describe.**
it a common way to package command tools into docker image and run them inside docker instead of installing binaries on your computer.

As you can see there https://hub.docker.com/search?q=operator-sdk&type=image, hub.docker.com contains a few images, but they didn't have updates for a while, and not official which don't give you enough guarantees.  

**Describe the solution you'd like**
operator-sdk team, can provide official docker image and push it on hub.docker.com, in this case users will have ability to use docker image instead of installing it on computer, as well as write some automation  to simplify development process and onboarding for new developers.

I will be really happy, to contribute this by sending  PR, if it okey. 

Thank you in advance

**Comment by camilamacedo86** [comment]
Hi @burov, 

It is duplicated of https://github.com/operator-framework/operator-sdk/issues/2152. I am closing this one, however, feel free to ping us to re-open if you need. Also, feel free to follow up #2152
