### ISSUE TITLE
default text on website build tab  "Lorem ipsum dolor sit amet"

### ISSUE THREAD

**Issue by yazug** [operator-framework/operator-sdk#2994]
https://sdk.operatorframework.io/build/

CREATE AND DEPLOY AN APP-OPERATOR

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

and 
READ THE USER GUIDES

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Comment by yazug** [comment]
looks like pull request 2992 might be related

**Comment by asmacdo** [comment]
Thanks for filing an issue! Closed by https://github.com/operator-framework/operator-sdk/pull/2992
