### ISSUE TITLE
How to customize container image references when using Operators/OLM?

### ISSUE THREAD

**Issue by mmellin** [operator-framework/operator-sdk#2996]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

This is a general context question relating to the use of Helm-based Operators and OLM.

## Question
I have a use case to deploy applications in various 3rd party airgapped environments. This is defined as one without Internet connectivity, but K8s clusters nodes do have access to a container registry and an internal private network. I have create a set of Helm based Operators from existing Helm charts and would like to use OLM to manage their lifecycle.  However, I've build these images referencing my own private container registry, so OLM catalog image, image references within the CRs/Helm charts all point to my repo.  Here is an example of such usage:

```yaml
image: my-private-registry.com/app1
tag: v1
```

If I want a user to download the catalog image and install my Operator on their airgapped setup, I must first push all container images to their repo (catalog, operator, etc). 

**My question is** how then do I adjust the container image references programmatically to point to this new customer image registry so that the user can successfully install the catalog, operator and application?

The main focus is that whatever environment I install my Operators into, airgapped or not, they will never have access to `my-private-registry.com/` and I will always need to adjust where the images are being pulled from.  To date via searching I have not figured out a good programmatic approach.  Any help is appreciated!

** Additional Context**
These applications (containers, Helm charts or operators) will never be publicly accessible, meaning that we will not be publishing them on the Web for Internet based consumption. Thus the original container image references will be to wherever my build system is (`my-private-registry.com`) and we assume we will not know the destination image registry until installation time.

**Comment by estroz** [comment]
@mmellin does `helm` not provide utilities to manage chart values?

Otherwise have you looked into [`kustomize`](https://github.com/kubernetes-sigs/kustomize/)? You can define variables and apply them to a set of base manifests. I don't think this plays nicely with Helm charts though.

**Comment by mmellin** [comment]
Hi @estroz, thanks for your reply.

We are currently using Helm charts and yes we have no trouble here.  However with OLM the manifests no longer use Helm to install, and furthermore, are "baked" into the containers (such as CatalogSource in the bundle/CSV).  Image references are statically included within a CSV for an operator. This and other manifests are included in a "bundle" and then built into a CatalogSource container.  

So I would need to update the CR for the CatalogSource (not too hard), update the CSVs located within the CatalogSource container (hard - focus of this question), and update the CRs related to the apps (medium-hard) if I wanted to point the `docker pull` for all containers to another location.

I was hoping that OLM may have included a way to do this.  It seems the assumption is that all your containers are located somewhere publicly reachable and the image references will never be changed.  If this is the working assumption, then there are use-cases for which OLM is not a good fit.

I have not looked into `kustomize` but will since you have suggested it.

**Comment by estroz** [comment]
@mmellin thanks for clarifying, I didn’t fully understand the issue. I highly recommend re-opening this issue in the OLM repo. They may have more insight into how such a situation could be handled.

**Comment by mmellin** [comment]
@estroz I will do so! Thanks.

**Comment by estroz** [comment]
@mmellin hopefully filing an issue with OLM helped. If you still think there's something the SDK should be doing that it isn't, feel free to reopen this issue.

**Comment by msugakov** [comment]
What was the corresponding issue in the OLM repo, <https://github.com/operator-framework/operator-lifecycle-manager/issues/1517>? If so, it did not look like there's a ton of useful info there.
