### ISSUE TITLE
Upgrade instructions unclear

### ISSUE THREAD

**Issue by IBMRob** [operator-framework/operator-sdk#2998]
## Bug Report

**What did you do?**

Currently we use the following command to create a manifest directory which contains the csv and CRDs of the operator in question `operator-sdk generate csv --csv-version=1.0.0  --update-crds`
After this we then use `operator-sdk bundle create image:1.0.0 --directory deploy/olm-catalog/operator/ --package operator --channels stable,beta --default-channel stable` to generate our OLM bundle 

When running ` `operator-sdk generate csv` it produces the following warning
```
[Deprecation Notice] Package manifests are deprecated. Run `operator-sdk bundle create --generate-only` to create operator metadata. Refer to the version upgrade guide for more information: https://operator-sdk.netlify.com/docs/migration/version-upgrade-guide
```

Following the link produced doesn't include any information on how to migrate the current mechanism to the new one. 

**What did you expect to see?**
Example commands on how to use the new commands. 

**What did you see instead? Under which circumstances?**
No clear instructions. 

I did attempt to use `operator-sdk bundle create --generate-only` but it returned the error:
```
operator-sdk bundle create --generate-only 
FATA[0000] error generating bundle image files: stat /Users/convery/Documents/GitHub-IBM/ACEcc/ibm-appconnect-operator/stable/ibm-appconnect-bundle/operators/ibm-appconnect/deploy/olm-catalog/ibm-appconnect/manifests: no such file or directory 
```
which is correct,  that directory didn't exist (previously the `operator-sdk generate csv ` command created it)

**Environment**
* operator-sdk version: 0.17
* go version: go version go1.13.5 darwin/amd64
* Kubernetes version information: v1.17.1
* Kubernetes cluster kind:  OCP 4.4
* Are you writing your operator in ansible, helm, or go? Go

**Possible Solution**

**Additional context**

**Comment by camilamacedo86** [comment]
HI @IBMRob, 

- Regards the warning :

Note that the deprecated message will be revert. More info: https://github.com/operator-framework/operator-sdk/issues/2967#issuecomment-624115767 

- Regards the bundle command:

By using the SDK 0.17 when you run `operator-sdk generate csv --csv-version=1.0.0 --update-crds` it will generate the manifest dir in for example : `./deploy/olm-catalog/memcached-operator/`

So, when you run the command `operator-sdk bundle create --generate-only` it expects the manifest in the above directory. However, you are also able to use the flag to inform the manifest dir location as for example:

```
  $ operator-sdk bundle create \
      --generate-only \
      --directory ./deploy/olm-catalog/test-operator/
```

Also, note that the PR: https://github.com/operator-framework/operator-sdk/pull/2905 is open for we are able to improve the command info. Please, feel free to check it and also contribute by giving your feedback. 

Please, let us know if the above information helps you with and let you work with.

**Comment by estroz** [comment]
@IBMRob some instructions on migrating: #2977. More to come.

**Comment by estroz** [comment]
Update: we recently removed the deprecation notice for package manifests, since they are not deprecated in operator-framework tooling (yet).

**Comment by camilamacedo86** [comment]
I think it can be closed with the changes made so far. 
Also, we have the #2977.

**Comment by camilamacedo86** [comment]
HI @IBMRob, 

The information in the docs and command was updated, Also, as described above:

> Update: we recently removed the deprecation notice for package manifests, since they are not deprecated in operator-framework tooling (yet).  

So, I understand that we can close this one. However, please feel free to ping us to re-open if you see that something still missing is addressed here.
