### ISSUE TITLE
CSV not getting generated

### ISSUE THREAD

**Issue by umangachapagain** [operator-framework/operator-sdk#3002]
## Bug Report

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).
```
[ocs-operator] operator-sdk bundle create \
--generate-only \
--directory ./deploy/olm-catalog/ocs-operator/4.5.0 \
--package ocs-operator \
--channels alpha \
--default-channel alpha
```
```
[ocs-operator] tree deploy/olm-catalog/ocs-operator/manifests deploy/olm-catalog/ocs-operator/metadata
deploy/olm-catalog/ocs-operator/manifests
├── ocsinitialization.crd.yaml
├── ocs-operator.clusterserviceversion.yaml
├── storagecluster.crd.yaml
└── storageclusterinitialization.crd.yaml
deploy/olm-catalog/ocs-operator/metadata
└── annotations.yaml
```
```
operator-sdk generate csv --csv-version=4.6.0 --update-crds
```
and,
```
operator-sdk generate csv --csv-version=4.6.0 --update-crds --deploy-dir=./deploy --apis-dir=./pkg/apis/ --output-dir=./deploy/olm-catalog/ocs-operator
```

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).
Successfully generated CSV 

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).
```
FATA[0000] error generating CSV: no CSV manifest in deploy/olm-catalog/ocs-operator/manifests 
```

**Environment**
* operator-sdk version: operator-sdk-v0.17.0-x86_64-linux-gnu

* go version: 1.13

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go? golang

**Possible Solution**

**Additional context**

Repo: https://github.com/openshift/ocs-operator

**Comment by estroz** [comment]
@umangachapagain I am able to reproduce this issue specifically with ocs-operator. Furthermore, a project isn't being detected despite a `build/Dockerfile` existing:
```console
$ git clone --depth 1 git@github.com:openshift/ocs-operator.git
$ cd ocs-operator
$ operator-sdk generate csv --csv-version=4.6.0 --interactive=false
WARN[0000] Could not detect project root. Ensure that this command runs from the project root directory. 
INFO[0000] Generating CSV manifest version 4.6.0        
FATA[0000] error generating CSV: failed to walk manifests directory for CSV updates: lstat deploy: no such file or directory
```
This does not occur for other operator projects I've tested.

/kind bug
/assign

**Comment by estroz** [comment]
Ignore the above comment, my environment was not configured properly. I was actually able to run `generate csv` successfully, both with defaults and the verbose flag usage you posted. @umangachapagain do you have a specific branch you are working on? `master` uses `operator-sdk` v0.10.0, so I'm assuming so.

/triage not-reproducible
/remove-triage support

**Comment by umangachapagain** [comment]
> Ignore the above comment, my environment was not configured properly. I was actually able to run `generate csv` successfully, both with defaults and the verbose flag usage you posted. @umangachapagain do you have a specific branch you are working on? `master` uses `operator-sdk` v0.10.0, so I'm assuming so.
> 
> /triage not-reproducible
> /remove-triage support
>
We are working on moving to sdk 0.17.0 and new bundle format here: https://github.com/openshift/ocs-operator/pull/482
This is where we hit the problem with csv generation.

Using old sdk with old bundle format works fine.

**Comment by estroz** [comment]
This issue is arising from incorrect CSV formatting in the PR and #3015, which will cause an error if `---` isn't removed from a manifest before parsing.
