### ISSUE TITLE
angle brackets in website CLI docs are treated as html

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#3004]
### Problem

In markdown `<` and `>` are special characters, and will render as html. The CLI docs use these characters for variables, which do not render correctly on the website.

https://sdk.operatorframework.io/docs/cli/operator-sdk_generate_k8s/#synopsis
![Screenshot from 2020-05-11 10-32-27](https://user-images.githubusercontent.com/1028657/81573832-07d2d080-9373-11ea-8b37-b1698b77ce18.png)

generate k8s source docs:
```
Long: `k8s generator generates code for custom resources given the API                                                                                                               
specs in pkg/apis/<group>/<version> directories to comply with kube-API                                                                                                                  
requirements. Go code is generated under                                                                                                                                                 
pkg/apis/<group>/<version>/zz_generated.deepcopy.go.                                                                                                                                     
```

The manpage renders correctly:
```operator-sdk generate k8s --help
k8s generator generates code for custom resources given the API
specs in 'pkg/apis/<group>/<version>' directories to comply with kube-API
requirements. Go code is generated under
'pkg/apis/<group>/<version>/zz_generated.deepcopy.go'.
Example:
```

#### Half a solution

We could escape the angle brackets with `&lt;` and `&gt;` fixing the website, but the manpages would look ugly.

![Screenshot from 2020-05-11 10-42-50](https://user-images.githubusercontent.com/1028657/81574736-32715900-9374-11ea-92aa-4503a4b2405b.png)

```
operator-sdk generate k8s --help
k8s generator generates code for custom resources given the API
specs in pkg/apis/&lt;group&gt;/&lt;version&gt; directories to comply with kube-API
requirements. Go code is generated under
pkg/apis/&lt;group&gt;/&lt;version&gt;/zz_generated.deepcopy.go.
```

Maybe cobra will lets us swap them them at doc-generation time, leaving the man pages alone and only fixing this on the website side.

**Comment by estroz** [comment]
This is a tooling feature, the [cli doc generator](https://github.com/operator-framework/operator-sdk/blob/master/hack/generate/cli-doc/gen-cli-doc.go) needs to be updated.
