### ISSUE TITLE
Allow the customization of imagePullPolicy for the generator operator.yaml

### ISSUE THREAD

**Issue by fiftoine** [operator-framework/operator-sdk#301]
Hi,

**Feature request :** customize the imagePullPolicy of the operator

**Case**

On development mode, there are a lot of builds of the operator. 
These builds override the deploy/operator.yaml file and set the imagePullPolicy to Always.
When working with minikube and the adapted docker environment:

`$ eval $(minilkube docker-env)`

the operator image is stored in the minikube docker environment.
But when trying to deploy the operator (kubectl create...), minikube can't pull the image because it want to PULL.

A workaround is to change the imagePullPolicy of the operator.yaml file to "IfNotPresent" then minikube can pull the image successfully.

It would be nice to be able to customize the imagePullPolicy of the operator to prevent edition of the operator.yaml file on each build when working locally.

Thanks

**Comment by hasbro17** [comment]
@fiftoine This falls under the larger issue of what should the `operator-sdk build` command do to existing manifests #84 . Should it overwrite them like it does now, or only update the image field, or only generate the manifests only once and let the user customize them after that point?

Can you please follow up with a comment on that issue explaining your case so we can keep the discussion in one place.

**Comment by joelanford** [comment]
Closing. See #84 for the follow-on discussion.
