### ISSUE TITLE
Documentation about Release Schedules is Missing

### ISSUE THREAD

**Issue by CSdread** [operator-framework/operator-sdk#302]
Our company is looking to adopt the operator-sdk as the basis for a few different internal operators. It would help us make decisions if we had more information about frequency of releases and size of releases, along with a roadmap with timelines. Are these available?

**Comment by spahl** [comment]
You are right we will try to formalize this.

**Comment by jayunit100** [comment]
bump :) cc @jfchevrette  @jmrodri  any roadmap info we can get our hands on ?

**Comment by camilamacedo86** [comment]
Hi, @joelanford @dmesser, 

Have we this already? If not, have we a plan to do it? Could we attend it or it should be closed?
