### ISSUE TITLE
Operator logs are not showing in stdout with -localOperator while running tests

### ISSUE THREAD

**Issue by akram** [operator-framework/operator-sdk#3020]
## Type of question
help around the operator-sdk

## Question

I am trying to run e2e tests using the operator-sdk passing -localOperatorFlags "--debug"

**What did you expect to see?**
I want to see the operator logs in debug mode in stdout with the e2e tests logs.

**What did you see instead? Under which circumstances?**
I see only my e2e logs

**Environment**
* operator-sdk version:
0.17.0

  insert release or Git SHA here

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"e6f1cd7", GitTreeState:"clean", BuildDate:"2020-04-20T06:30:19Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
OpenShift

**Additional context**
nope

**Comment by bharathi-tenneti** [comment]
@akram Can you please try `$ operator-sdk run --local --operator-flags="--zap-level=debug"`

**Comment by camilamacedo86** [comment]
The version 0.17+ is no longer supported. We recommend users upgrade their project to 1.0+. See:
Also, it shows open for a while without a reply which shows fine to be closed. 
However, please feel free to ping us if you think that it should be re-opened.
