### ISSUE TITLE
How do you get an EventRecord when writing unit tests ?

### ISSUE THREAD

**Issue by cscetbon** [operator-framework/operator-sdk#3022]
I can't find a way to create one that is needed during my reconcile. I'm using version v0.15.0 and I can't see any example doing so at https://github.com/operator-framework/operator-sdk-samples

**Comment by kensipe** [comment]
@cscetbon thanks for the issue... could you clarify a couple of things?   The title and desc seem like different things.   Are you looking for help with unit tests?  or are you looking for examples for create EventRecords doing reconcile?   What is the focus of this issue?

**Comment by cscetbon** [comment]
@kensipe sorry nvm I got the answer from guys on the controller-runtime project. That’s was to create a fake recorder for unit tests. I’m closing the ticket. Thanks

**Comment by cscetbon** [comment]
It might be a good idea to Add something about that in your documentation

**Comment by camilamacedo86** [comment]
Also, it shows that it would be similar to https://github.com/kubernetes-sigs/kubebuilder/issues/549#issuecomment-613506558. @cscetbon also I think that would be great if you be able to add here the solution found in order to help others that may face the same. WDYT?

**Comment by cscetbon** [comment]
@camilamacedo86 so actually the goal was to get a recorder in order to call the reconcile which is done when the controller is initialized but not in unit tests. I ended up doing something like 
```
...
fakeClient := fake.NewFakeClient(objs...)
fakeRecorder := record.NewFakeRecorder(3)
MyReconcile{client: fakeClient, scheme: s, recorder: fakeRecorder}
```
the fake recorder is provided by k8s.io/client-go/tools/record
