### ISSUE TITLE
Using unstructured.Unstructured for two CRs mismatch to the handler

### ISSUE THREAD

**Issue by shawn-hurley** [operator-framework/operator-sdk#304]
CRDS:
databases.app.example.com:v1
appservices.app.example.com:v1

Register them with the operator-sdk schema:
```go
         schemeGroupVersion := schema.GroupVersion{Group: gv[0], Version: gv[1]}
         schemeBuilder := k8sruntime.NewSchemeBuilder(func(s *k8sruntime.Scheme) error {
                 s.AddKnownTypeWithName(schema.GroupVersionKind{
                         Group:   app.example.com,
                         Version: v1,
                         Kind:    Database,
                  }, &unstructured.Unstructured{})
                  metav1.AddToGroupVersion(s, schemeGroupVersion)
                  return nil
         })
         k8sutil.AddToSDKScheme(schemeBuilder.AddToScheme)
         schemeGroupVersion = schema.GroupVersion{Group: gv[0], Version: gv[1]}
         schemeBuilder = k8sruntime.NewSchemeBuilder(func(s *k8sruntime.Scheme) error {
                 s.AddKnownTypeWithName(schema.GroupVersionKind{
                         Group:   app.example.com,
                         Version: v1,
                         Kind:    AppService,
                  }, &unstructured.Unstructured{})
                  metav1.AddToGroupVersion(s, schemeGroupVersion)
                  return nil
         })
         k8sutil.AddToSDKScheme(schemeBuilder.AddToScheme)
```

Set `sdk.Watch` to watch both resources.

in your handler you will see if you create a `Database` resource and then a `AppService` resources that one of them will have the wrong GVK in the object that is passed to the handler.

**Comment by hasbro17** [comment]
Looking at your example now you should not be creating your own schemebuilder to add a type into the sdk scheme. This is not how the SDK is expected to be used. 

I'm going to use the [automation-operator](https://github.com/automationbroker/automation-operator) that you linked offline as an example of the way you're registering types withe SDK scheme.
You should not have to explicitly register types with the SDK scheme before you Watch a resource
https://github.com/automationbroker/automation-operator/blob/master/cmd/automation-operator/main.go#L82-L95
https://github.com/automationbroker/automation-operator/blob/master/cmd/automation-operator/main.go#L57-L58

That part should already be done for you by the SDK.
See how the sample vault-operator [registers it's types](https://github.com/operator-framework/operator-sdk-samples/blob/master/vault-operator/pkg/apis/vault/v1alpha1/register.go#L26-L28) with the SDK 

You can see that is registering the concrete VaultService type with the SDK scheme.
https://github.com/operator-framework/operator-sdk-samples/blob/master/vault-operator/pkg/apis/vault/v1alpha1/register.go#L33-L36

Furthermore in your example above, you're registering two different GVKs with the same unstructured.Unstructured type:
```Go
                 s.AddKnownTypeWithName(schema.GroupVersionKind{
                         Group:   app.example.com,
                         Version: v1,
                         Kind:    Database,
                  }, &unstructured.Unstructured{})

                s.AddKnownTypeWithName(schema.GroupVersionKind{
                         Group:   app.example.com,
                         Version: v1,
                         Kind:    AppService,
                  }, &unstructured.Unstructured{})
```
This is just a guess on my part now but I assume this is why the decoder might have problems with mapping an unstructured type to the correct GVK.

But to address your issue. I would recommend that you don't try to manually register `GVK<->Type` mappings in the SDK scheme yourself. That's not how the SDK should be used and is not supported or tested.

Admittedly the SDK does not provide a way to easily define a second Kind into your existing Custom Resource right now so you have to do it manually.
So eventually we need to add support for adding a new Kind to an existing CRD via something like 
```
operator-sdk new x-operator --kind=AppService --api-version=app.example.com/v1
operator-sdk add resource --kind=Database --api-version=app.example.com/v1
```
But until we can try to document how to manually add another Kind/Type.

**Comment by hasbro17** [comment]
@shawn-hurley Going to close this since this issue is about using the SDK in an unsupported way.
Watching multiple custom resources is already tracked by #146
