### ISSUE TITLE
Helm Operator: failed to upgrade if there is job in chart

### ISSUE THREAD

**Issue by liqlin2015** [operator-framework/operator-sdk#3051]
## Bug Report

**What did you do?**
I was using helm operator to manage my application chart.

**What did you expect to see?**
When I publish new version of my operator operator itself was successfully upgraded. But my application helm release was not upgraded because of error
```
{"level":"error","ts":1589528000.5692172,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"app-controller","request":"app/default","error":"failed update (cannot patch \"app-job\" with kind Job: Job.batch \"app-job\" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:\"nginx-ingress-controller-job\", GenerateName:\"\", Namespace:\"\", SelfLink:\"\", UID:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil),
...
: field is immutable
```

The problem is k8s Job itself is readonly, which might be k8s default behaviour. helm just cannot update job as required. Besides there is question whether job will be re-run even the update was successful.

**What did you see instead? Under which circumstances?**
Helm release should be upgraded too.

**Environment**
* operator-sdk version: 0.17.0

* go version:

* Kubernetes version information: 1.16.2

* Kubernetes cluster kind:  OCP

* Are you writing your operator in ansible, helm, or go? helm

**Possible Solution**
None

**Additional context**
None

**Comment by joelanford** [comment]
@liqlin2015 When you're using this chart with the `helm` CLI, are you able to upgrade it? I'm trying to figure out if this is an issue with the Helm operator, or if there is something that is specific to the use of Jobs in Helm charts that causes problems like this.

**Comment by dian-xh** [comment]
I also run into the same issue with the `0.17.1` base image. similar errors are seen (not only to jobs, but also statefulsets) when a deployed cr is patched with fields updates.

The same chart value upgrade works fine with `helm upgrade --force` cli. in the cr, the force annotation is used :
```
            "annotations": {
              "helm.operator-sdk/upgrade-force": "True"
            }
```
thanks!

**Comment by camilamacedo86** [comment]
Closing this one since shows sorted out. However, please feel free to ping us if I misunderstanding something here and you think that something here still needs to be addressed.
