### ISSUE TITLE
ansible extra system packages installation

### ISSUE THREAD

**Issue by odra** [operator-framework/operator-sdk#3053]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

general context and help around the operator-sdk

## Question

**What did you do?**

This is an ansible operator question.

I would like to install extra packages in the operator-sdk ansible image (such as gcc).

I wanted to install extra packages in the operator-sdk image so I can use ansible modules that require such packages (such as the postgresql ones).

**What did you expect to see?**

A success installation message.

**What did you see instead? Under which circumstances?**

```
bash-4.4$ yum install gcc
Not root, Subscription Management repositories not updated
Error: This command has to be run under the root user.
```

The same error happens when doing it in the dockerifle:

```
FROM quay.io/operator-framework/ansible-operator:v0.16.0

RUN dnf install gcc -y

COPY requirements.yml ${HOME}/requirements.yml
RUN ansible-galaxy collection install -r ${HOME}/requirements.yml \
    && chmod -R ug+rwx ${HOME}/.ansible

COPY watches.yaml ${HOME}/watches.yaml

COPY roles/ ${HOME}/roles/
```

**Environment**
* operator-sdk version:

```
 55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: minikube

**Additional context**

No additional context.

**Comment by tengqm** [comment]
You can try this (not sure if legitimate):

```
USER root
RUN dnf install gcc -y

USER ${USER_ID}

COPY requirements ...
```

That is, switch back to root for software install and then back to the user named `ansible-operator`.

**Comment by odra** [comment]
oh ok, let me give it a try

**Comment by odra** [comment]
it did the tick :-)


thanks for the help
