### ISSUE TITLE
use lease-api for leader election to reduce request spam

### ISSUE THREAD

**Issue by grosser** [operator-framework/operator-sdk#3066]
see https://github.com/kubernetes/kubernetes/issues/80289

**Comment by estroz** [comment]
Is there a way to make a [`Lease`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#lease-v1-coordination-k8s-io) object a singleton? It seems as though these leases are timed, i.e. applicable to leader-with-lease not leader-for-life, although it is a standard k8s object and can be used like a `ConfigMap`. Unfortunately there isn't great documentation on usage.

**Comment by grosser** [comment]
I'd assume the lease can be done for a fare future date, have not played
with it much though.

**Comment by grosser** [comment]
I found a nice article here https://carlosbecker.com/posts/k8s-leader-election
it has the basic code / how to use it ... only unknown would be how to make never switch the leader when it's still running, but that could just be setting an infinite interval

**Comment by hasbro17** [comment]
We should address this in the upstream controller-runtime issue for replacing the configmap/endpoints based leader election with the new API: https://github.com/kubernetes-sigs/controller-runtime/issues/460
Probably not much we can change here in the SDK here itself.

**Comment by hasbro17** [comment]
Actually if this is about the SDK's [leader-for-life pkg](https://github.com/operator-framework/operator-sdk/blob/master/pkg/leader/leader.go) then that's probably another discussion.
