### ISSUE TITLE
Update log levels

### ISSUE THREAD

**Issue by awprice** [operator-framework/operator-sdk#307]
**Some of the logs that the SDK emits are either too verbose or have an incorrect log level.**

The following log lines should really be changed from **Info -> Debug**, as they are internal messages about what the informer is doing:

`pkg/sdk/informer-sync.go`, line 65: 
```
logrus.Infof("Object (%s) is deleted", key)
```

`pkg/sdk/informer.go`, line 79:
```
logrus.Infof("starting %s controller", i.resourcePluralName)
```

`pkg/sdk/informer.go`, line 91: 
```
logrus.Infof("stopping %s controller", i.resourcePluralName)
```
---
The following log line should really be changed from **Info -> Warn** as it is something that should be brought to the attention of the user of the SDK:

`pkg/sdk/informer-sync.go`, line 113:
```
logrus.Infof("Dropping key (%v) out of the queue: %v", key, err)
```
---
The user can then modify the log level to use for the operator with the following:
```
logrus.SetLevel(logrus.DebugLevel)
```

I'm happy to submit a PR to change this, but thought I would open an issue first to start the discussion.

**Comment by spahl** [comment]
We would definitely welcome some logging cleanup:-) Feel free to submit the PR.
