### ISSUE TITLE
Scorecard fails with proxyPod timeout, no logs

### ISSUE THREAD

**Issue by aharbis** [operator-framework/operator-sdk#3075]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

Support question with running `operator-sdk scorecard` command.

## Question

**What did you do?**

Set up a basic `.osdk-scorecard.yaml` config which lists only a single `basic` `cr-manifest`.

Run the `operator-sdk scorecard` command.

**What did you expect to see?**

Either success, or a failure with some logs to inform me of what to troubleshoot.

**What did you see instead? Under which circumstances?**

```
$ operator-sdk scorecard
INFO[0000] Using config file: /home/aharbis/go/src/my-operator/.osdk-scorecard.yaml
ERRO[0063] Plugin `Basic Tests` failed with error (failed to create global resources: failed to get proxyPod: timed out waiting for the condition)
        Basic Tests
        CR:
        Labels:
        Errors:
                plugin error
        Log:
                failed to create global resources: failed to get proxyPod: timed out waiting for the condition:
Logs:
```

Even running with the global `--verbose` option did not yield any further logs or context, nor did running with `json` output format.

**Environment**
* operator-sdk version:

```
operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "unknown", go version: "go1.13.10 linux/amd64"
```

* Kubernetes version information:

```
Client Version: openshift-clients-4.3.0-201910250623-88-g6a937dfe
Server Version: 4.3.13
Kubernetes Version: v1.16.2
```

* Kubernetes cluster kind: 

OCP 4.3

**Additional context**
Add any other context about the question here.

**Comment by jmccormick2001** [comment]
you might try doing a 'kubectl get pod' when you run scorecard, take a look at the container logs it spins up, sometimes that sheds light on what could be going wrong.

**Comment by aharbis** [comment]
@jmccormick2001 I tried that, by issuing `oc get pod -w` in a separate terminal window watching the same namespace, and no pods were ever created.

**Comment by aharbis** [comment]
Made a little progress, looking at the ReplicaSets instead. I can see our operator is failing to schedule due to missing ServiceAccount. However, I have the ServiceAccount defined in a bundled RBAC manifest YAML, which is specified in the config via `namespaced-manifest` and `global-manifest`.

Shouldn't the `scorecard` automatically apply those YAMLs before install?

**Comment by jmccormick2001** [comment]
looking at the code, if OLMDeployed is false, then scorecard should create resources from the global and namespaced manifests.

**Comment by aharbis** [comment]
Makes sense. Something seems to be not working, though.

I've definitely got a `ServiceAccount` defined in my `namespaced-manifest`. However, the operator deployment is created and the ReplicaSet fails to schedule pods due to missing `ServiceAccount`.

There are zero helpful logs from the `scorecard` to indicate if it created, failed to create, failed to find, the ServiceAccount or other resources.

We are a cluster-scoped and OLM-enabled operator. However, I wanted to get the `basic` test(s) working prior to adding in the `olm` plugin.

What should we do to progress or resolve this issue?

**Comment by jmccormick2001** [comment]
just to verify I'm on the same page, before I debug into this one, wanted to confirm that you have olm-deployed set to false, you are running only the basic tests, and that you still see this resource creation issue?

**Comment by aharbis** [comment]
That's correct. I was using only a `basic` test with a manually created manifest containing the ServiceAccount, ClusterRole, ClusterRoleBinding, etc.

I've since moved to working on the OLM integration (since we **are** OLM enabled), and I've now run into an issue in which it seems the `scorecard` tries to create the CR before our webhooks have come up.

```
        Log:
                failed to create cr resource: Internal error occurred: failed calling webhook "...": Post https://.../?timeout=2s: dial tcp 10.254.16.36:8443: connect: connection refused:
```

We see this when a CR is created immediately after the Operator Deployment is stood up, as the webhooks take some time to stabilize in the cluster. Any way around this?

**Comment by jmccormick2001** [comment]
looking at the code, there appears to not be a way to specify 'wait for X seconds' before/after a CR is created before proceeding, so I think this would be an enhancement request....note, the new scorecard (alpha) pushes CR creation outside it's responsibility, it just runs tests, setting up resources will be left to frameworks outside of scorecard itself.

**Comment by aharbis** [comment]
Glad to hear there is work being done to lift the CR creation out of scorecard's responsibility. We certainly would welcome such a change.

What's the timeline for that to be released? Is that something we could expect in the near future?

At the moment, `scorecard` tests failing would block us from being able to enter the OperatorHub, even though our operator would pass tests if timing was configurable.

**Comment by jmccormick2001** [comment]
the release we just cut, 0.18 has the alpha scorecard in there to try out.  Run it with 'operator-sdk alpha scorecard', we added some user docs this release as well.

**Comment by aharbis** [comment]
Sure, I will give that a shot.

**Comment by jmccormick2001** [comment]
please reopen if you feel this is still important for us to work on, but with the new scorecard coming out I'm assuming we can close this one.
