### ISSUE TITLE
How long does it take for release images to be published to quay.io?

### ISSUE THREAD

**Issue by pgerv12** [operator-framework/operator-sdk#3076]
## Type of question
Release process

## Question
How long does it take for release images to be published to quay.io? It seems like there's been quite a few days between v0.17.1 release and the images being published to quay.io. 

Specifically, I'm trying to build an updated Helm operator, but the build is failing because the v0.17.1 tagged image doesn't exist even though v0.17.1 has been released for a few days. Is there a process or delay between the two happening? 

**Environment**
* operator-sdk version: v0.17.1

**Comment by estroz** [comment]
@pgerv12 the v0.17.1 tag build is [failing](https://travis-ci.org/github/operator-framework/operator-sdk/builds/687542920) for some reason, looking into it now.

**Comment by pgerv12** [comment]
Ah, ok. So it is driven through Travis. Thanks!
