### ISSUE TITLE
What is the best way to get pod's log through SDK API?

### ISSUE THREAD

**Issue by piontec** [operator-framework/operator-sdk#308]
I can CRUD pods through SDK, but I can't find any way to get log from a pod. Normally, this is possible with `CoreV1Client` and `client.Pods(pod.Namespace).GetLogs(pod.Name, logOptions)`.

**Comment by hasbro17** [comment]
The generic SDK client only provides CRUD right now. So for more advanced use cases like reading logs or exec-ing into pods you will have to fall back to using the k8s clientset.
You should be able to access that in your handler via `k8sclient.GetKubeClient()`.
See #295

**Comment by piontec** [comment]
OK, that will do - thanks!
