### ISSUE TITLE
operator-sdk olm status doesn't work for olm versions with no published assets

### ISSUE THREAD

**Issue by madorn** [operator-framework/operator-sdk#3085]
## Bug Report

**What did you do?**
`operator-sdk olm status --verbose --olm-namespace "openshift-operator-lifecycle-manager"`

**What did you expect to see?**
`Successfully got OLM status`

**What did you see instead? Under which circumstances?**
`Failed to get OLM status: failed to get resources: failed to fetch CRDs: request failed: failed GET 'https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.14.2/crds.yaml': unexpected status code 404, expected 200: Not Found`

**Environment**
* operator-sdk 0.17.0
* OCP 4.4.4
* OLM 0.14.2

**Possible Solution**
Publish assets for all OLM versions at https://github.com/operator-framework/operator-lifecycle-manager/releases

Open an issue in https://github.com/operator-framework/operator-lifecycle-manager ?

**Comment by estroz** [comment]
@madorn see https://github.com/operator-framework/operator-sdk/issues/3095.

**Comment by camilamacedo86** [comment]
Hi @madorn, 

We opened the issue for you already. See #3095. 
In this way, let's close this one as duplicated and please feel free to follow up it.
