### ISSUE TITLE
Set different reconcile period for different controllers

### ISSUE THREAD

**Issue by feicun** [operator-framework/operator-sdk#3086]
## Type of question

How to implement a specific feature

## Question

Let's say I have two controllers, I'm looking for a way to set different reconcile/resync periods for each of the controllers.

**What did you do?**
In `main.go`, I have created a manager with customized resync period, and apply it to all controllers:
```
resyncPeriod := time.Duration(resyncPeriodInt64) * time.Second
// Create a new Cmd to provide shared dependencies and start components
mgr, err := manager.New(cfg, manager.Options{Namespace: ALL_NAMESPACES, SyncPeriod: &resyncPeriod})
if err != nil {
    log.Fatal(err)
}

log.Print("Registering Components.")

// Setup Scheme for all resources
if err := apis.AddToScheme(mgr.GetScheme()); err != nil {
    log.Fatal(err)
}

// Setup all Controllers
if err := controller.AddToManager(mgr); err != nil {
    log.Fatal(err)	
}
```

In my understanding, because all controllers are managed by this Manager object, all controllers will have the same reconcile/resync period. Is there any way to customize different reconcile period for different controllers?

I checked this document https://sdk.operatorframework.io/docs/golang/quickstart/ , which mentioned that `Note: Returning Result with RequeueAfter set is how you can periodically reconcile a CR.`

So I tried to modify the `Reconcile` function like this:
```
func (r *ReconcileAPIRoute) Reconcile(request reconcile.Request) (reconcile.Result, error) {
	processSomeEventsHandler(r.client, request)

	if os.Getenv("customized_resync_period") != "" {
		// If customized resync period has been setted, get the customized resync period.
		resyncPeriod := time.Duration(os.Getenv("customized_resync_period")) * time.Second
		return reconcile.Result{Requeue: true, RequeueAfter: resyncPeriod * time.Second}, nil
	}
	return reconcile.Result{}, nil
}
```

**What did you expect to see?**
The controller will be reconciled with `customized_resync_period`.

**What did you see instead? Under which circumstances?**
The controller still be reconciled by the Manager's reconcile period.

**Environment**
* operator-sdk version: 0.10.1

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-eb1860", GitCommit:"eb1860579253bb5bf83a5a03eb0330307ae26d18", GitTreeState:"clean", BuildDate:"2019-12-23T08:58:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by camilamacedo86** [comment]
HI @feicun, 

The usage of the `RequeueAfter` will NOT interfere in the Manager sync and then, both will trigger the reconcile. Following a further explanation which I hope that helps you better with.

**How works the Reconcile()?**

The reconcile function is responsible for synchronizing the resources and their specifications according to the business logic implemented on them. In this way, it works like a loop, and it does not stop until all conditionals match its implementation. The following is pseudo-code with an example that clarifies it.

```go
reconcile App {

   // Check if a Deployment for the app exists, if not create one
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   } 
   ... 
    
   // If it is at the end of the loop, then:
   // All was done successfully and the reconcile can stop  
   return reconcile.Result{}, nil

}
```

The following are possible return options to restart the Reconcile:

- With the error  (it will requeue imediatelly): `return reconcile.Result{}, err`
- Without an error  (it will requeue imediatelly): `return reconcile.Result{Requeue: true}, nil` 
- Therefore, to **stop** the Reconcile, use: `return reconcile.Result{}, nil`
- Reconcile again after X time , to **stop** the Reconcile, use: `return reconcile.Result{}, nil` 

> And then,  `return reconcile.Result{ RequeueAfter: time.Second, Requeue:      true, }, nil` to reconcile again after X time.

**Using the Watch to reconcile**

By default, you will find the watches for the Primary resources already implemented by each controller that you generated by using the SDK tool as follows.
``` go
// Watch for changes to primary resource Memcached
err = c.Watch(&source.Kind{Type: &cachev1alpha1.Memcached{}}, &handler.EnqueueRequestForObject{})
if err != nil {
    return err
}
```

However, note that in the example has watches implemented for each secondary object controlled/created by it.

```go
// TODO(user): Modify this to be the types you create that are owned by the primary resource
// Watch for changes to secondary resource Pods and requeue the owner Memcached
err = c.Watch(&source.Kind{Type: &appsv1.Deployment{}}, &handler.EnqueueRequestForOwner{
    IsController: true,
    OwnerType:    &cachev1alpha1.Memcached{},
})
if err != nil {
    return err
}
err = c.Watch(&source.Kind{Type: &corev1.Service{}}, &handler.EnqueueRequestForOwner{
    IsController: true,
    OwnerType:    &cachev1alpha1.Memcached{},
})
if err != nil {
    return err
}
```

**Manager Sync**

The [Manager](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager#Manager) will manage all controllers as you said and the default syncPeriod is each 10 hours. See:

```go
    // SyncPeriod determines the minimum frequency at which watched resources are
    // reconciled. A lower period will correct entropy more quickly, but reduce
    // responsiveness to change if there are many watched resources. Change this
    // value only if you know what you are doing. Defaults to 10 hours if unset.
    // there will a 10 percent jitter between the SyncPeriod of all controllers
    // so that all controllers will not send list requests simultaneously.
    SyncPeriod *time.Duration
```
From: https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager#Options

**Note**

So, if besides you have the Watches and the Manager Sync you still in some scenario and/or controller setup to call the reconcile after X time specifically shows reasonable the usage of `RequeueAfter`. 

Please, let us know if it answers your question and if we can close this one.

**Comment by feicun** [comment]
@camilamacedo86 Thanks for all the details! If all controllers managed by the Manager, and all controllers share the same SyncPeriod, is there any way that could let me to modify the SyncPeriod after the Manager has been created?

For example, the Manager has a SyncPeriod as 1 hour, but I would like to let controller A reconciles in 5 seconds period, and controller B reconciles in 10 seconds period?

**Comment by camilamacedo86** [comment]
Hi @feicun, 

I am afraid that would not recommend you reconcile the controller is so short period. And then, shows more appropriated you check the resources and have an idempotent implementation and use the Watch feature which will reconcile when an observed resource is created, 
 or updated and/or deleted.

So, if besides you have the Watches and the Manager Sync you still having some scenario and/or controller where you would like to reconcile after X time specifically shows reasonable the usage of RequeueAfter. 
 
Is it make sense?

**Comment by feicun** [comment]
@camilamacedo86 Thanks for the quick reply! In fact, I use the "5 seconds" or "10 seconds" period only for trying to explain my question. They are not real SyncPeriod I will use.

So my question is, as the Manager will apply SyncPeriod for all controllers, but I need some controllers have different reconcile period besides of the Manager's syncPeriod. Is that possible to achieve that?

Or in other words, I would like to make the reconcile period configurable per controller.

Does it make sense? Thanks!

**Comment by camilamacedo86** [comment]
Hi @feicun, 

In this case, you can use the `RequeueAfter` in all returns of some specific controller and then, the controller will always reconcile after X time as well (10 secs for example). Also, I'd recommend you give a look in issue tracked in the controller-runtime [Why resync default is so large - 10hours](https://github.com/kubernetes-sigs/controller-runtime/issues/521) and check the watch feature that will reconcile only when it observed that has some change which justifies it. 

I am closing this one as sorted out. However, please feel free to ping us if you think that it should still open.

**Comment by feicun** [comment]
@camilamacedo86 Hi, as we discussed above, both of `RequeueAfter` and the Manager's `SyncPeriod` will trigger the reconcile loop. But in my case, I would like to have controller's customized reconcile period "override" the Manager's global `SyncPeriod`.

For example, if I set `RequeueAfter` as 13 seconds, and Manager's `SyncPeriod` as 5 seconds, what I can see is, reconcile happened at:

> 1st second, 5th second, 10th second, `13rd second`, 15th second, 20nd second, 25th second, `26th second`, 30th second etc.

That is not what I want. 

I would like to let the reconcile happens at :

> 1st second, 13rd second, 26 second, etc.

Which means, the controller's customized reconcile period should override the Manager's "SyncPeriod" completely.

Is there anyway to do that? Thanks!

**Comment by camilamacedo86** [comment]
Hi @feicun, 

Yes, the Manger, the RequeueAfter and indeed the Watch features implemented also will call the reconcile. I really do think that would be possible you ignore  Manager's "SyncPeriod" completely. for one controller specifically,

@estroz @fabianvf @hasbro17 Do you see any other option for @feicun do what he is looking for? Do you see anything else that we could to do address it?

**Comment by estroz** [comment]
@feicun From the docs:

>SyncPeriod determines the minimum frequency at which watched resources are reconciled. A lower period will correct entropy more quickly, but reduce responsiveness to change if there are many watched resources. Change this value only if you know what you are doing.

So (from https://github.com/kubernetes-sigs/controller-runtime/issues/521):

>All this [value] does is force a re-reconcile of everything in the cache. Generally, you probably don't want to do this -- it's often expensive, it'll mask subtle bugs, and it's usually not necessary. It's actually probably fine to set this to never, except it might save you in production if you've got bugs in your reconcile logic because you didn't write a level-based controller.

I am not exactly sure of the answer, and in fact what you're trying to do may not have a corresponding feature in controller-runtime. In any case this is a controller-runtime question, so I suggesting re-opening this issue in the controller-runtime repo for a more in-depth response.

Some related issues:
* https://github.com/kubernetes-sigs/controller-runtime/issues/521#issuecomment-518457302
* https://github.com/kubernetes-sigs/controller-runtime/issues/312

**Comment by akashjain971** [comment]
@feicun how about creating two separate manager objects with different sync-period? There is no need to use the same manager object for both.
