### ISSUE TITLE
Unpublished image quay.io/operator-framework/helm-operator:v0.17.1

### ISSUE THREAD

**Issue by pre** [operator-framework/operator-sdk#3089]
## Bug Report

**What did you do?**

Generate a new Helm operator:
- `operator-sdk new lolcat-operator --type=helm --api-version=rdx.net/v1alpha1 --kind=Lolcat`
- build the operator: `operator-sdk build lolcat-operator`

**What did you expect to see?**
Successful build. 

**What did you see instead? Under which circumstances?**

Unpublished image `quay.io/operator-framework/helm-operator:v0.17.1`

```
% cat build/Dockerfile
FROM quay.io/operator-framework/helm-operator:v0.17.1
[..]
```

v0.17.0 is published but v0.17.1 is not:
```
% operator-sdk build lolcat-operator
[..]
manifest for quay.io/operator-framework/helm-operator:v0.17.1 not found: manifest unknown: manifest unknown
FATA[0005] Failed to output build image lolcat-operator: failed to exec []string{"docker", "build", "-f", "build/Dockerfile", "-t", "lolcat-operator", "."}: exit status 1
```
**Environment**
* operator-sdk version: 0.17.1 

**Possible Solution**

Publish the image quay.io/operator-framework/helm-operator:v0.17.1

Latest published tag is `v0.17.0` at the moment.

**Comment by estroz** [comment]
Yes this is a [known issue](https://github.com/operator-framework/operator-sdk/issues/3076#issuecomment-631663450) with our v0.17.1 build. I'm in the process of debugging this.

/priority critical-urgent
/assign

**Comment by estroz** [comment]
@pre images are now available.
