### ISSUE TITLE
operator-sdk olm status is unable to install olm

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3095]
## Bug Report

```
$ /home/pmorie/go/src/github.com/open-cluster-management/nucleus/_output/tools/bin/operator-sdk olm status --olm-namespace openshift-operator-lifecycle-manager
INFO[0002] Fetching CRDs for version "0.14.2"           
FATA[0002] Failed to get OLM status: failed to get resources: failed to fetch CRDs: request failed: failed GET 'https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.14.2/crds.yaml': unexpected status code 404, expected 200: Not Found 
```

**Possible Solution**
- add flag `--version` to allow users to choose the version
- we package a set of OLM manifests with the SDK to use as the default set, and only reach out to github releases if the user specifies another version

**Additional context**
- discussion in slack https://coreos.slack.com/archives/C3VS0LV41/p1590174772452300
- place in the code is: https://github.com/operator-framework/operator-sdk/blob/master/internal/olm/manager.go#L120
- Currently, we get the version from ClusterServiceVersion for then looking for the assets in the GH to install it.

Duplicated: https://github.com/operator-framework/operator-sdk/issues/3095

**Comment by estroz** [comment]
Clarification: `olm status` does not install OLM, it looks up the installed version of OLM then queries OLM's Github release manifests for that version. If those manifests don't exist, `status` (and `uninstall`) will error.

These error messages need to be better _and_ the SDK should both permit `--version` to override the detected version and package its own version of released manifests that gets updated like other dependencies.
