### ISSUE TITLE
Allow CSV to define PodSecurityPolicies (or Openshift SecurityContextConstraints)

### ISSUE THREAD

**Issue by RyuunoAelia** [operator-framework/operator-sdk#3099]
## Feature Request
Some platforms (and probably more and more) are restricting pods to avoid exiting the containers. A good example of that is OpenShift. In that case, some Operators might need to define custom security rules because the ones provided by the platform are too restrictive.
The current status is that each operator will have to define a way to do it by either:
* asking the user to do it as a prerequisite (error prone, a hassle if there are updates to the rights for each version, etc)
* requesting the rights in RBAC to do it itself
* having another operator doing it beforehand (this is actually what Red Hat chose to do in OpenShift Container Storage : https://github.com/openshift/ocs-operator/blob/master/pkg/controller/ocsinitialization/sccs.go )

The problem here is that there is no standard way to do it, and, specially for the two last solutions, there is no easy way to understand the real rights needed by the operator (without even considering the possibility of bug that could break pre-defined PSP/SCC in the cluster).

**Describe the solution you'd like**
Having a section of the CSV defining the PSP/SCC needed by the Operator, there would be the following advantages:
* an easy way to review the actions the operator is able to perform.
* no need for an external setup step on clusters that have these security features in enforcing mode.
* standardise the ecosystem, which is a benefit for the community as a whole.

**Comment by camilamacedo86** [comment]
Hi @RyuunoAelia,

Should not it be raised in the OLM project which is the project responsible for the CSV? See https://github.com/operator-framework/operator-sdk-samples. 

Has any reason for you raised it here (SDK) specifically? If not, wdyt about address it in the project responsible for the CSV and we close this one?

**Comment by RyuunoAelia** [comment]
I raised it here because I wasn't clear on what project is actually responsible for the CSV content. Thank you for clarifying this for me. I now raised it in the OLM project. BTW you pointed the wrong repository.
