### ISSUE TITLE
Deleting svc with error: the server does not allow this method on the requested resource

### ISSUE THREAD

**Issue by lut777** [operator-framework/operator-sdk#3101]
## Background

I configured a CRD and provided the definition of service in the CRD.
When an instance of this CRD is applied by kuberlet, the controller will initialize some services according to the definition of the service in the CRD.

## Type of question

When an instance of CRD is deleted, services defined by this instance also needs to be deleted.
However, I'm having trouble executing the service deletion step in the controller.

I called the client's DeleteAllOf interface, which is https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client#example-Client--DeleteAllOf.
I tried deleting all services once. 
But there is an error like this.
`"logger":"controller_dns","msg":"Deleting service failed due to error.","error":"the server does not allow this method on the requested resource","stacktrace" ......`

## Question

Another option is to get a serviceList and literately delete services. 
But that's a little silly.

Can someone tell me why I got that error?
Is it because of authority? Or is it because you can't use that interface?

**Environment**
* operator-sdk version:  0.17.0

* Kubernetes version information:  1.14.3

**Additional context**
No

**Comment by camilamacedo86** [comment]
Hi @lut777, 

By checking your comment:

> When an instance of CRD is deleted, services defined by this instance also needs to be deleted.

Shows that your scenario would require the usage of a finalizer. See the topic [Handle Cleanup on Deletion](https://sdk.operatorframework.io/docs/golang/quickstart/#handle-cleanup-on-deletion) 

The [DeleteAllOf](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client#example-Client--DeleteAllOf) will delete all resources which would filter by the query informed. The error `the server does not allow this method on the requested resource`, lead to us believe that you are trying to delete a resource that you has no permission. 

In this way, if the information above is not enough to attend your need. Then, could you please provide more information for we try to help you with?  

- What is the [scope](https://sdk.operatorframework.io/docs/operator-scope/#overview) of your project? (The code snippet from the `main.go` where you define the manger options ([example](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/cmd/manager/main.go#L95-L115)) and from the `operator.yaml` where you defined the `WATCH_NAMESPACE`([example](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/deploy/operator.yaml#L24-L27))
- What is the scope of the resource that you are trying to delete? (The code snippet with `DeleteAllOf`)
- Could you provide more info on the logs? Is possible to check what resource could not be deleted? Could you provide the stack as well? 

We are looking for your reply.

**Comment by lut777** [comment]
Thank you for your help~. @camilamacedo86 

Yes, the DeleteAllOf method is called just before removing customized finalizer.

I can not understand what is the `you are trying to delete a resource that you has no permission`. Cause I am trying to delete the resources that I created...
Yes, I created some services in a namespace and I am trying to delete them all.

Could you please give me more information/details about the access rights?

**Comment by estroz** [comment]
@lut777 can you please elaborate on what you mean by "definition of service" in the CRD, perhaps with an example?

In any case this sounds like a permissions issue. Are you able to delete these services via `kubectl delete service <service-name>`?

**Comment by lut777** [comment]
@estroz Well it is simple. I defined some key parameters of the `service` in the CRD. 
When a CRD is instantiated, the controller initializes some `services` based on the service parameters defined in this CRD. 

As an example:
a CRD is defined as following:

```yaml
apiVersion: v1
kind: xxx
metadata:
  name: xxx
spec:
  xxx
  namespace: loadbalancer
  Services:  
  - name: svc-name
    portName: http
    servicePort: 8080
    protocol: TCP  
    loadbalancePort: 12345

```

So the service  `svc-name` will be created in the namespace `loadbalancer`.

So when I need to delete the CRD, I expect to use **DeleteAllOf** method to remove all services in this namespace once for all.
But I failed, with the error shown in my problem.

I will try your suggestions.
But I think it's doable. Because currently the way I delete services is to find the serviceList first and then delete the services one by one.
So...what's why I find it strange...

**Comment by camilamacedo86** [comment]
Hi @lut777, 

1. Could you please provide the code snippet with the implementation that works and with the implementation with DeleteAllOf that is not working?
2. Could you provide more info on the logs? Is possible to check what resource could not be deleted? Could you provide the stack as well? 
3. What is the [scope](https://sdk.operatorframework.io/docs/operator-scope/#overview) of your project? (The code snippet from the `main.go` where you define the manger options ([example](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/cmd/manager/main.go#L95-L115))

**Comment by win5do** [comment]
service not support deletecollection.

ref: https://github.com/kubernetes/client-go/issues/505#issuecomment-440678666

**Comment by zhaogaolong** [comment]
if not set `namespace` , may be have this problem
```go
_,err = k.client.
        Resource(mp.Resource).
        Namespace(k.namespace).
        Create(k.ctx,u,v12.CreateOptions{})
if err != nil {
	fmt.Println(err)
}```
