### ISSUE TITLE
Broken link in doc

### ISSUE THREAD

**Issue by Avni-Sharma** [operator-framework/operator-sdk#3110]
Broken link observed here https://github.com/operator-framework/operator-sdk/blob/ab71095122431788fe6b8775d9606c050895c47d/website/content/en/docs/cli/operator-sdk_run.md#see-also

**Comment by tengqm** [comment]
Looks like these markdown files are used to generate the website content published here: https://sdk.operatorframework.io/docs/cli/operator-sdk_run/

They are not meant to be browsed as raw github contents ...

**Comment by Avni-Sharma** [comment]
Perhaps I missed this, Thanks @tengqm. :+1:  Closing this issue.
