### ISSUE TITLE
is there a way to change watches dynamically?

### ISSUE THREAD

**Issue by nirrozenbaum** [operator-framework/operator-sdk#3123]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

**What did you do?**
developed an ansible operator using the sdk. 

**What did you expect to see?**
all is working

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:
0.16.0
  insert release or Git SHA here
```
operator-sdk version: "v0.16.0", commit: "55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd", go version: "go1.13.8 linux/amd64"
```
* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+a8d983c", GitCommit:"a8d983c", GitTreeState:"clean", BuildDate:"2019-12-23T12:16:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
Regular

**Additional context**
I'm trying to develop an operator that reacts to different types dynamically. f
or that, it could help if watches can be changed dynamically. e.g. having the configuration in a configmap instead of in watches.yaml file.
any other way to modify it dynamically could be helpful.

**Comment by nirrozenbaum** [comment]
@fabianvf hi Fabian, 
still waiting for your answer per this one..

**Comment by kstiehl** [comment]
@nirrozenbaum 
Have you found a solution for that?

I would also be interested whether there is a good solution to do that for a Golang operator

**Comment by nirrozenbaum** [comment]
nope, unfortunately no.

**Comment by fabianvf** [comment]
Terribly sorry, missed those pings. I do not think there is a way to dynamically update the watches for a running ansible operator currently. Some users in the past have used a `watches.yaml` stored in a configmap and mounted that into the operator deployment, so when the content of the watches change the operator is redeployed

**Comment by nirrozenbaum** [comment]
@fabianvf thanks for your comments.
do you know if this option is possible in go operator?
