### ISSUE TITLE
operator-sdk run --help prints a broken link

### ISSUE THREAD

**Issue by pmorie** [operator-framework/operator-sdk#3135]
## Bug Report

**What did you do?**
`operator-sdk run --help`

**What did you expect to see?**
Working links

**What did you see instead? Under which circumstances?**
This link is broken:

```console
Read more about the --olm run mode and configuration options here:
https://github.com/operator-framework/operator-sdk/blob/master/doc/user/olm-catalog/olm-cli.md
```

**Environment**
* operator-sdk version:

0.17.0

**Comment by estroz** [comment]
This has been fixed in v0.18.0.
