### ISSUE TITLE
How are Helm hooks supported with helm Operators?

### ISSUE THREAD

**Issue by mmellin** [operator-framework/operator-sdk#3139]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

General context question regarding use of SDK to convert Helm charts to Helm-based Operators.

## Question

Are helm hooks supported with Helm-based Operators and how do I convert a Helm chart which is using them to an Operator? Are there limitations and/or pitfalls that I need to be aware of?

**Comment by camilamacedo86** [comment]
The helm operator is based on Helm 3. In this way, I'd recommend you check the [Chart Hooks](https://helm.sh/docs/topics/charts_hooks/) docs to know how to work with. Please, let me know if it answers your question and feel free to raise new issues if you face any problem with.

**Comment by mmellin** [comment]
hi @camilamacedo86, all our charts are currently build for Helmv2.  Will we have to rebuild our charts to support helm v3 now? Thanks.

**Comment by camilamacedo86** [comment]
Hi @mmellin, 

I'd recommend you migrate your chart from V2 to V3 and use the latest released version of SDK 0.18 to create your project. In the latest release was removed the automatic migration of Helm releases from v2 to v3. (#2918). More info: [Changelog](https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md#removals) 

Also, note that if you try to use an old version of SDK (automatic migration of Helm releases from v2 to v3) you can end up in situations such as for example: `Note that the crd-install hook has been removed in favour of the crds/ directory in Helm 3.` as described by @joelanford https://github.com/operator-framework/operator-sdk/issues/2647.

See: 
- That you can use a plugin `Helm v3 2to3 plugin` to help you with. More info: [How to migrate from Helm v2 to Helm v3](https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/)
- [Migrating Helm v2 to v3](https://helm.sh/docs/topics/v2_v3_migration/#helm)

@joelanford, could you please let me know if I misunderstood or if I am missing something here.

**Comment by joelanford** [comment]
Helm 3 is backwards compatible with Helm 2 charts, so it shouldn't be necessary to upgrade to Helm 3.

The operator-sdk installs, upgrades, uninstalls releases using the Helm libraries, so all hooks should be supported out of the box. 

We haven't seen too many questions about chart hooks in the context of a running operator, so there may be some gotchas that we're not aware of. 

Are there specific hooks you've tried to use that are not working or doing something unexpected?

**Comment by camilamacedo86** [comment]
Hi @mmellin,

Shows that the information provided above attended your expectation so I am closing this one. However, please feel free to ping us here if you think that it should be re-opened and/or raise new issues. 

Also, if you try any specific hook that not work or see that it is doing something unexpected please let us know.
