### ISSUE TITLE
Support label selector for sdk.Watch

### ISSUE THREAD

**Issue by gkumar7** [operator-framework/operator-sdk#314]
```sdk.Watch``` should also support passing in a set of a labels to further filter the crds being monitored. There seems to be a todo listed in ```pkg/sdk/api.go``` for this: 
  ```TODO: support opts for specifying label selector```.

Has there been any progress for this?

**Comment by rithujohn191** [comment]
@gkumar7 thank you for opening an issue. This feature is definitely useful and has been on our radar. We have not yet begun working on it. We will update this issue when we do.

**Comment by CSdread** [comment]
@hasbro17 
![img_6044](https://user-images.githubusercontent.com/15988634/44485790-ff6ebb00-a60e-11e8-8fa5-ef9f4d6c1cb8.JPG)

lets continue here as this seems to be the right issue. Now that we have support for the functional argument pattern i think we can just add it as a functional argument and then add the labels into the watch functions. Once https://github.com/operator-framework/operator-sdk/pull/418 is merged I will code up a PR.

**Comment by CSdread** [comment]
https://github.com/operator-framework/operator-sdk/pull/428

**Comment by CSdread** [comment]
This is done with the above mentioned PR and can be closed @theishshah
