### ISSUE TITLE
Restore generator unit tests

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/operator-sdk#315]
As part of the generator refactoring #310 we've mistakenly removed all the generator unit tests.
We need to revert that and add them back.

/cc @theishshah

**Comment by hasbro17** [comment]
On second thought this might not actually be an issue since we've combined all the previous generator functions into one.
https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/generator.go#L491
Taking a closer look at our previous unit tests.

**Comment by etiennecoutaud** [comment]
We should add a code coverage indicator to prevent this kind of mistake in the future.

**Comment by hasbro17** [comment]
@theishshah As discussed offline you're right that we've reduced the generator functions down into the [renderWriteFile()](https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/generator.go#L530-L531) function and that code path can be covered by a single unit test like [TestGenVersion()](https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/generator_test.go#L29). Although that is only testing [renderFile()](https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/generator_test.go#L31) and not renderWriteFile().

But the function is not the only thing that the original unit tests were meant to cover. We also need to test all of the templates themselves. So right now if someone accidentally changes any one of the templates there's nothing to test the expected output. So we need to add them back.
