### ISSUE TITLE
Why is operator-sdk so slow ?

### ISSUE THREAD

**Issue by cscetbon** [operator-framework/operator-sdk#3152]
**What did you do?**
operator-sdk is slow at generating deep copy files and openapi files

**What did you expect to see?**
I'd expect it to take less than a minute

**What did you see instead? Under which circumstances?**
```
root@60cc10874998:/go/casskop# time operator-sdk generate k8s --verbose
DEBU[0000] Debug logging is set
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [db:[v1alpha1], ]
INFO[0415] Code-generation complete.

real	6m55.753s
user	0m52.292s
sys	2m16.532s

root@60cc10874998:/go/casskop# find pkg/apis/ -type f -exec du -sh {} \;
4.0K	pkg/apis/apis.go
8.0K	pkg/apis/db/.DS_Store
4.0K	pkg/apis/db/group.go
4.0K	pkg/apis/db/v1alpha1/register.go
4.0K	pkg/apis/db/v1alpha1/testdata/cassandracluster-NoTopo.yaml
4.0K	pkg/apis/db/v1alpha1/testdata/cassandracluster-1DC.yaml
4.0K	pkg/apis/db/v1alpha1/testdata/cassandracluster-2DC5R.yaml
4.0K	pkg/apis/db/v1alpha1/testdata/cassandracluster-2DC.yaml
4.0K	pkg/apis/db/v1alpha1/testdata/cassandracluster-TopoDCNoRack.yaml
4.0K	pkg/apis/db/v1alpha1/testdata/cassandracluster-1DC1R1P.yaml
4.0K	pkg/apis/db/v1alpha1/zz_generated.openapi.go
40K	pkg/apis/db/v1alpha1/cassandracluster_types.go
20K	pkg/apis/db/v1alpha1/cassandracluster_types_test.go
4.0K	pkg/apis/db/v1alpha1/doc.go
16K	pkg/apis/db/v1alpha1/zz_generated.deepcopy.go
4.0K	pkg/apis/addtoscheme_db_v1alpha1.go
```
```
root@60cc10874998:/go/casskop# time operator-sdk generate openapi --verbose
DEBU[0000] Debug logging is set
[Deprecation notice] The 'operator-sdk generate openapi' command is deprecated!

 - To generate CRDs, use 'operator-sdk generate crds'.
 - To generate Go OpenAPI code, use 'openapi-gen'. For example:

      # Build the latest openapi-gen from source
      which ./bin/openapi-gen > /dev/null || go build -o ./bin/openapi-gen k8s.io/kube-openapi/cmd/openapi-gen

      # Run openapi-gen for each of your API group/version packages
      ./bin/openapi-gen --logtostderr=true -o "" -i ./pkg/apis/<group>/<version> -O zz_generated.openapi -p ./pkg/apis/<group>/<version> -h ./hack/boilerplate.go.txt -r "-"

INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [db:[v1alpha1], ]
INFO[0414] Code-generation complete.
INFO[0414] Running CRD generator.
INFO[0445] CRD generation complete.

real	7m25.434s
user	0m55.011s
sys	2m30.661s
```
Interestingly, if I remove all files and keep only one it still takes more than 5 min !!
```
root@8b8eb3a557e9:/go/casskop# find pkg/apis/ -type f -exec du -sh {} \;
4.0K	pkg/apis/db/v1alpha1/register.go
root@8b8eb3a557e9:/go/casskop# time operator-sdk generate k8s --verbose
DEBU[0000] Debug logging is set
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [db:[v1alpha1], ]
INFO[0349] Code-generation complete.

real	5m49.134s
user	0m39.249s
sys	1m51.282s
``` 

**Environment**
* operator-sdk version:
operator-sdk version: "v0.15.0-3-g558b73ea", commit: "558b73ea8d0f2d47a48aa6517652c2cb5ac3f0bb", go version: "go1.13.6 linux/amd64"

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2+k3s1", GitCommit:"698e444a03fe3a705849fc8d9ad9e35f1dffe286", GitTreeState:"clean", BuildDate:"2020-05-07T00:18:01Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
k3d

**Comment by estroz** [comment]
@cscetbon the SDK uses the upstream deepcopy-gen and openapi-gen libraries to generate code, so if the upstream generate script is slow I imagine the SDK will be similarly slow. I personally haven't seen 5 minute runtimes for code generation. Two suggestions:
1. Upgrade to the newest SDK v0.18.0, which has up-to-date generation library versions.
1. Directly use [`controller-gen`](https://github.com/kubernetes-sigs/controller-tools/blob/master/cmd/controller-gen/main.go#L139) to generate code.

**Comment by cscetbon** [comment]
I suspect something with the environment. It runs in docker. When I run the operator-sdk, latest version, outside of docker it takes 28 sec. When I run the same command in docker I get 5+ min for a single file with almost nothing in it... Any idea ?

**Comment by cscetbon** [comment]
If anyone can help here are the steps to follow to see the issue, how the duration goes from 22sec to 5min+ between a local run and a run in docker which doesn't make much sense to me:
```
$ git clone -b operator-sdk --depth 1 git@github.com:cscetbon/casskop.git
Cloning into 'casskop'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 25 (delta 0), reused 19 (delta 0), pack-reused 0
Receiving objects: 100% (25/25), 65.67 KiB | 1.37 MiB/s, done.

$ cd casskop

$ time operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [db:[v1alpha1], ]
INFO[0010] Code-generation complete.
operator-sdk generate k8s  21.84s user 20.22s system 393% cpu 10.690 total

$ time docker run --rm -ti -v $PWD:/source -v $HOME/go/pkg/mod:/go/pkg/mod \
                   -v $HOME/Library/Caches/go-build:/root/.cache/go-build \
                   cscetbon/operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [db:[v1alpha1], ]
INFO[0304] Code-generation complete.
docker run --rm -ti ...    k8s  0.05s user 0.08s system 0% cpu 5:09.31 total
```

**Comment by estroz** [comment]
This could be related to container [resource constraints](https://docs.docker.com/config/containers/resource_constraints/), although I'm not familiar with tuning these or whether these even need setting.

**Comment by cscetbon** [comment]
@estroz it doesn’t seem to be cause I also tried to increase my resources and checked stats and it didn’t change anything.
