### ISSUE TITLE
Cannot create a new app

### ISSUE THREAD

**Issue by chmouel** [operator-framework/operator-sdk#316]
Using Golang 1.9.1 on OSX I am getting an error when running the command from the README : 

```
F0618 09:39:55.518948       9 main.go:74] Error: Failed making a parser: unable to add directory "github.com/chmouel/app/pkg/apis/app/v1alpha1": unable to import "github.com/chmouel/app/pkg/apis/app/v1alpha1": cannot find package "github.com/chmouel/app/pkg/apis/app/v1alpha1" in any of:
	/usr/local/go/src/github.com/chmouel/app/pkg/apis/app/v1alpha1 (from $GOROOT)
	/go/src/github.com/chmouel/app/pkg/apis/app/v1alpha1 (from $GOPATH)
```

It seems that it tries to use `/go/` as $GOPATH, I tried to workaround by symlinking /go to my $GOPATH with no luck.

I am using docker over a remote $DOCKER_HOST if that changes anything,

<details><summary>Detailled traceback</summary>
<pre>
(33/39) Wrote github.com/petar/GoLLRB@master
(34/39) Wrote golang.org/x/sys@master
(35/39) Wrote k8s.io/apimachinery@kubernetes-1.9.3
(36/39) Wrote golang.org/x/net@master
(37/39) Wrote golang.org/x/text@v0.3.0
(38/39) Wrote github.com/gogo/protobuf@v1.0.0
(39/39) Wrote k8s.io/client-go@kubernetes-1.9.3
Run dep ensure done
Run code-generation for custom resources
Error: failed to perform code-generation for CustomResources: (Generating deepcopy funcs
F0618 09:34:41.259945       9 main.go:74] Error: Failed making a parser: unable to add directory "github.com/chmouel/app-operator/pkg/apis/app/v1alpha1": unable to import "github.com/chmouel/app-operator/pkg/apis/app/v1alpha1": cannot find package "github.com/chmouel/app-operator/pkg/apis/app/v1alpha1" in any of:
	/usr/local/go/src/github.com/chmouel/app-operator/pkg/apis/app/v1alpha1 (from $GOROOT)
	/go/src/github.com/chmouel/app-operator/pkg/apis/app/v1alpha1 (from $GOPATH)
goroutine 1 [running]:
k8s.io/code-generator/vendor/github.com/golang/glog.stacks(0xc420079100, 0xc4200ec000, 0x1e1, 0x236)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:766 +0xcf
k8s.io/code-generator/vendor/github.com/golang/glog.(*loggingT).output(0x855760, 0xc400000003, 0xc4200ea000, 0x831cbb, 0x7, 0x4a, 0x0)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:717 +0x322
k8s.io/code-generator/vendor/github.com/golang/glog.(*loggingT).printf(0x855760, 0x3, 0x6e1476, 0x9, 0xc4200dbf30, 0x1, 0x1)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:655 +0x14c
k8s.io/code-generator/vendor/github.com/golang/glog.Fatalf(0x6e1476, 0x9, 0xc4200dbf30, 0x1, 0x1)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
	/go/src/k8s.io/code-generator/cmd/deepcopy-gen/main.go:74 +0x221
)
</pre>
</details>

**Comment by hasbro17** [comment]
@chmouel I suspect it probably has to do with using a remote docker host. Correct me if I'm wrong but I don't think bind mounts `docker run -v` work with a remote docker host.
And that's what the code generation step is essentially doing. It's mounting your local project into the codegen container.
https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/templates.go#L607-L608

I can prioritize vendoring the code generator to avoid running it as a container and that should hopefully let you use a remote docker host.
https://github.com/operator-framework/operator-sdk/issues/226

**Comment by chmouel** [comment]
Sounds good thanks!

**Comment by spahl** [comment]
Closing in favor of #226
