### ISSUE TITLE
Just upgraded and I can't figure out how to run my operator locally anymore

### ISSUE THREAD

**Issue by iamkirkbater** [operator-framework/operator-sdk#3169]
## Bug Report

**What did you do?**
In an attempt to make a minimum viable recreation to an external problem, I used the operator-sdk to create a new operator.  Following the docs to get my new operator running, I ended up having to upgrade operator-sdk, crc, and oc/kubectl to the latest versions.  

When trying to go back to the operator I've been working on, I now can't seem to get it to run.

Previously I used to just be able to run `operator-sdk up local --namespace aws-account-operator` and I've now changed to the `run local --watch-namespace` which wasn't a huge problem, but now when I try to run my operator, I'm getting the following error:

```
> operator-sdk run local --watch-namespace aws-account-operator
INFO[0000] Running the operator locally; watching namespace "aws-account-operator"
build flag -mod=vendor only valid when using modules
FATA[0000] Failed to run operator: failed to exec []string{"go", "build", "-o", "build/_output/bin/aws-account-operator-local", "-mod=vendor", "github.com/openshift/aws-account-operator/cmd/manager"}: exit status 1
```

**What did you expect to see?**
I'm expecting my operator to come up.

**What did you see instead? Under which circumstances?**
After a bit of digging it looks like the error is related to the fact that our operator isn't using go modules, but `dep` as it's a bit older.  When I run the `go build` command that's being executed, I see the build flag error, but when I run the same command with the flag `-mod=` or without that flag entirely it works.

I've attempted to use the `--operator-flags "-mod=''"` flag, but it still outputs the same command on the FATA[0000] line above, even though it would appear that's how I should be passing in the vendor override.

**Environment**
* operator-sdk version:

operator-sdk version: "v0.18.0", commit: "921c33982687d6e9219fe0a1a326515fb37ae040", kubernetes version: "v1.18.2", go version: "go1.14.3 darwin/amd64"

* go version:

go version go1.14.3 darwin/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0-4-g38212b5", GitCommit:"4a4cd759b616cdba344dd73386727c10d3d2dde1", GitTreeState:"clean", BuildDate:"2020-05-25T22:58:48Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1", GitCommit:"b23e21a", GitTreeState:"clean", BuildDate:"2020-05-18T09:20:55Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

Go

Let me know if there's any other information I can provide.

Thanks,
Kirk

**Comment by iamkirkbater** [comment]
Not sure if this is still an issue for y'all, because the `--operator-flags` flag seemed to not actually do anything, at least during the build (maybe a `--build-flags` flag is needed?) but I found out that our operator is too old to use the newer version of the operator-sdk and I have downgraded operator-sdk and it's working again.

I'll leave this open so you can decide if you want to investigate it further, but feel free to close.

**Comment by joelanford** [comment]
Re-opening so we can discuss if we should try to support non Go-module projects still.

I _think_ this particular issue could be solved by only setting `-mod=vendor` if the vendor directory is present AND Go modules are enabled. It seems like we don't consider the latter check right now.

**Comment by joelanford** [comment]
This was discussed at the SDK community triage meeting. The outcome is that we would accept a PR that fixes `operator-sdk build`, `operator-sdk run local`, etc. to support projects that are not Go modules-enabled, but it is low priority.

If anyone is interested in working on this, I can point you in the right direction.
