### ISSUE TITLE
Use of package w/ improper licensing

### ISSUE THREAD

**Issue by magescher** [operator-framework/operator-sdk#3170]
## Bug Report

SDK makes us of open source package without proper license 
bou.ke/monkey v1.0.1/go.mod h1:FgHuK96Rv2Nlf+0u1OOVDpCMdsWyOFmeeketDHE7LIg=
https://github.com/operator-framework/operator-sdk/blob/master/go.sum

License for bou.ke component explicitly notes "I do not give anyone permissions to use this tool for any purpose. Don't use it.I’m not interested in changing this license. Please don’t ask."

https://github.com/bouk/monkey/blob/master/LICENSE.md

**Comment by bouk** [comment]
Hi, I'm the creator of monkey. I can't stress this enough: don't use it.

The reason it's included is because github.com/operator-framework/operator-registry depends on github.com/otiai10/copy which depends on github.com/otiai10/mint where version 1.2.3 depends on bou.ke/monkey

**Comment by joelanford** [comment]
Totally on board for getting this fixed. I'm curious, how was it discovered that this was a problem? I'd be interested in checking on this kind of thing periodically.

**Comment by estroz** [comment]
Once https://github.com/operator-framework/operator-registry/pull/349 is merged we can bump registry versions here and get rid of that dep.
