### ISSUE TITLE
bou.ke/monkey is not allowed to use

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-sdk#3172]
Please refer to LICENSE of https://github.com/bouk/monkey/ , now all of the code generated by operator-sdk will include `bou.ke/monkey` in `go.sum`, I think we need to fix this.

**Comment by gyliu513** [comment]
There is a fix for other repos https://github.com/operator-framework/operator-registry/pull/191

**Comment by joelanford** [comment]
Closing as a duplicate of #3170
