### ISSUE TITLE
Remove unneeded packages which are getting added in all generated operators

### ISSUE THREAD

**Issue by snehahegde7** [operator-framework/operator-sdk#3175]
Currently operator sdk has indirect package dependency on bou.ke/monkey v1.0.1/go.mod 
This package license says to not to use it.
https://github.com/bouk/monkey/blob/master/LICENSE.md

This will make all the operators generated from operator sdk have reference to the same package.

**Comment by snehahegde7** [comment]
Related issue https://github.com/operator-framework/operator-registry/issues/190

**Comment by estroz** [comment]
Closing as duplicate to #3170.
