### ISSUE TITLE
Should I create two controllers for one CRD If their watching predicates are different?

### ISSUE THREAD

**Issue by horis233** [operator-framework/operator-sdk#3182]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

Asking about community best practices

## Question

**What did you do?**
I am developing a go operator using the operator-sdk.

I have a question about what is the best practice for creating an operator with two different watching predicates for one CRD.

I want to create an operator that reconciles some resources only if the CRD `spec` is updated and reconcile some other resources only if the CRD `status` is updated.

My current design is to create two controllers, one watches the `spec` updating/creating, another is for the `status` updating by applying different predicates and append both of them into the `AddToManagerFuncs`, like

```
	AddToManagerFuncs = append(AddToManagerFuncs, crd.AddSpecController, crd.AddStatusController)
```
I want to know if creating two controllers for reconciling one crd is a best practice or there are some community best practices to implement this function.

I hope I can get some suggestions here. Thanks in advance!
 
**Environment**
* operator-sdk version:

0.15.1

  insert release or Git SHA here

* Kubernetes version information:

  insert output of `kubectl version` here

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"a02f27a", GitTreeState:"clean", BuildDate:"2020-04-13T12:04:13Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

OCP

**Additional context**
Add any other context about the question here.

**Comment by DanielXLee** [comment]
Using two controllers for one CR is not a good solution
Currently, our CR status updates are mutually updated, so I think we need a good solution, one controller only updates the owned CR.

**Comment by joelanford** [comment]
@horis233 I would need to understand the use case more, but I think the suggested pattern is to always fully reconcile the entire object in a single run of `Reconcile`.

You would query the existing cluster state for the resources that need to be reconciled based on the `spec` and make any necessary changes. And you would do the same for the `status`.

**Comment by hasbro17** [comment]
> reconcile some other resources only if the CRD status is updated

Can you expand on why you want to do this?

Of the top of my head this seems like an anti-pattern which treats the `status` block effectively like the `spec` block i.e the `spec` should specify the desired state of your application that the controller/operator should be trying to reconcile towards. 
`status` is usually just for surfacing information about the current state of the application.

**Comment by horis233** [comment]
@hasbro17 @joelanford 
Thanks for your responses.
> Can you expand on why you want to do this?

My operator has three CRD. let 's say CRD-1, CRD-2 and CRD-3.
When the `spec` of CRD-1 instance is updated, then the label of the relevant CRD-2 instance will be updated.
When the `status` of CRD-1 instance is updated, then the label of the relevant CRD-3 instance will be updated.

I thought I have to use two reconciles to implement it.
I find we could also add the following `watch` into the controllers for CRD-2 and CRD-3, respectively. Using the `handler.ToRequestsFunc` and `predicate.Funcs` to Implement the functions

```
err = c.Watch(&source.Kind{Type: &CRD-1}, &handler.EnqueueRequestsFromMapFunc{
		ToRequests: mapCRD-1toCRD-2,
	}, predicateSpec)
``` 
and

```
err = c.Watch(&source.Kind{Type: &CRD-1}, &handler.EnqueueRequestsFromMapFunc{
		ToRequests: mapCRD-1toCRD-3,
	}, predicateStatus)
``` 
Then handle label update logic into the controllers for CRD-2 and CRD-3.

@hasbro17 Any suggestion for this plan? Thanks in advance.
