### ISSUE TITLE
doc: no buildable Go source files

### ISSUE THREAD

**Issue by daquinoaldo** [operator-framework/operator-sdk#3191]
## Type of question
**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
General context

## Question
**What did you do?**
```
go doc
```

**What did you expect to see?**
The generated doc for my operator.

**What did you see instead? Under which circumstances?**
```
doc: no buildable Go source files in <operator-dir>
```

**Environment**
* operator-sdk version: "v0.15.2"
commit: "ffaf278993c8fcb00c6f527c9f20091eb8dd3352"
go version: "go1.13.3 linux/amd64"

* go version go1.14 linux/amd64

**Additional context**
`go build` returns `can't load package: package .: build constraints exclude all Go files in <operator-dir>`.

**Comment by camilamacedo86** [comment]
HI @daquinoaldo, 

SDK tool generated Golang projects. So, your questions here are more related how to use the Golang commands than the operator-sdk tool itself. However,  regards the `go build`:

`go build returns can't load package: package .: build constraints exclude all Go files in <operator-dir>.`
 
For you to build a project you need to pass the path `go build ./...`. 

Regards the go doc it also is about its usage. See the [go doc command](https://golang.org/cmd/doc/). 

Example of it working with an SDK operator: 

```
$ go doc --all ./pkg/apis/

package apis // import "test-app/pkg/apis"


VARIABLES

var AddToSchemes runtime.SchemeBuilder
    AddToSchemes may be used to add all resources defined in the project to a
    Scheme


FUNCTIONS

func AddToScheme(s *runtime.Scheme) error
    AddToScheme adds all Resources to the Scheme
```

Closing this one as sorted out.
