### ISSUE TITLE
Memory Usage for Watch Resource with many objects

### ISSUE THREAD

**Issue by arturobrzut** [operator-framework/operator-sdk#3192]
## Type of question
This is a question or feature request

## Question
Can I watch resource with many objects without linear memory consumption.
I need to watch resource Secret in operator in cluster scope
I watch all namespace
In one namespace in my Cluster  I have a lots of secrets
Because of that I check that if I have 1k Secrets in my cluster I need  additional about 100MB memory for cache for this secrets, (If I have 2k Secrets I Need 200MB, and so on)
Because of that It is hard to create operator , because I do not know how many secrets there will be on client cluster. but I need to put memory limitation for POD with operator
I know that I can change my operator to watch one namespace, but my operator need to watch a few namespaces (not all, but more then 2)

from my pprof which dump heap after creating eventHandler, and before Reconcile function starts I can see that 90MB is used by cache.(*Reflector).ListAndWatch.func1.1

This is my add function from controller

```
func add(mgr [manager.Manager,](url) r reconcile.Reconciler) error {
	// Create a new controller
	c, err := controller.New("my-controller", mgr, controller.Options{Reconciler: r})
	if err != nil {
		return err
	}

	// Watch for changes to primary resource
	err = c.Watch(&source.Kind{Type: &operatorv1alpha1.My{}}, &handler.EnqueueRequestForObject{})
	if err != nil {
		return err
	}

	err = c.Watch(&source.Kind{Type: &corev1.Secret{}}, &handler.EnqueueRequestForOwner{
		IsController: true,
		OwnerType:    &operatorv1alpha1.My{},
	})
	if err != nil {
		return err
	}
   return nil
}

```

**What did you expect to see?**
My operator should used constants memory (e.g. 30MB), not matter if I have 1k Secrets or 10k Secrets

**What did you see instead? Under which circumstances?**
My operator use 400MB in my tests environment. And I can not set memory limitation because it depends of client environment

**Environment**
* operator-sdk version: v0.17.0
* Kubernetes version information:
Client Version: openshift-clients-4.3.0-201910250623-88-g6a937dfe
Server Version: 4.3.13
Kubernetes Version: v1.16.2

**Comment by joelanford** [comment]
@arturobrzut Unfortunately this is not easily solved with the existing features in SDK and controller-runtime. It sounds like you need the feature requested in kubernetes-sigs/controller-runtime#244.

In fact, it seems like your use case is specifically mentioned here: https://github.com/kubernetes-sigs/controller-runtime/issues/244#issuecomment-626597011
