### ISSUE TITLE
Unable to create a unit test for controller 

### ISSUE THREAD

**Issue by harche** [operator-framework/operator-sdk#3199]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

Yes

## Question

**What did you do?**
I am trying to write unit tests for the operator controller that I am writing. I am following [Unit Testing With Operator SDK](https://sdk.operatorframework.io/docs/golang/unit-testing/). Here is the sample code for the tests I am trying to write,

```golang
package kataconfig

import (
	"context"
	"testing"

	kataconfigurationv1alpha1 "github.com/openshift/kata-operator/pkg/apis/kataconfiguration/v1alpha1"
	"github.com/openshift/kata-operator/pkg/generated/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
)

func TestKataConfigController(t *testing.T) {
	// A KataConfig object with metadata and spec.
	kataconfig := &kataconfigurationv1alpha1.KataConfig{
		TypeMeta: v1.TypeMeta{
			APIVersion: "kataconfiguration.openshift.io/v1alpha1",
			Kind:       "KataConfig",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "example-kataconfig",
			Namespace: "kata-operator",
			Labels: map[string]string{
				"label-key": "label-value",
			},
		},
	}

	// Objects to track in the fake client.
	objs := []runtime.Object{kataconfig}

	s := scheme.Scheme

	s.AddKnownTypes(kataconfigurationv1alpha1.SchemeGroupVersion, kataconfig)

	if err := kataconfigurationv1alpha1.AddToScheme(s); err != nil {
		t.Fatalf("Unable to add route scheme: (%v)", err)
	}

	// Create a fake client to mock API calls.
	cl := fake.NewFakeClient(objs...)

	// List KataConfig objects filtering by labels
	opt := client.MatchingLabels(map[string]string{"label-key": "label-value"})
	kataConfigList := &kataconfigurationv1alpha1.KataConfigList{}
	err := cl.List(context.TODO(), kataConfigList, opt)
	if err != nil {
		t.Fatalf("list kataconfig: (%v)", err)
	}
}
```
**What did you expect to see?**
A sample test to compile and run successfully. 

**What did you see instead? Under which circumstances?**
```golang
$ go test 
--- FAIL: TestKataConfigController (0.00s)
panic: failed to add object &{{KataConfig kataconfiguration.openshift.io/v1alpha1} {example-kataconfig  kata-operator    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[label-key:label-value] map[] [] []  []} {nil {}} {  0 0 0 0 []}} to fake client: no kind is registered for the type v1alpha1.KataConfig in scheme "pkg/runtime/scheme.go:101" [recovered]
	panic: failed to add object &{{KataConfig kataconfiguration.openshift.io/v1alpha1} {example-kataconfig  kata-operator    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[label-key:label-value] map[] [] []  []} {nil {}} {  0 0 0 0 []}} to fake client: no kind is registered for the type v1alpha1.KataConfig in scheme "pkg/runtime/scheme.go:101"

goroutine 23 [running]:
testing.tRunner.func1.1(0x1146360, 0xc000131290)
	/usr/local/go/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc000154240)
	/usr/local/go/src/testing/testing.go:944 +0x3f9
panic(0x1146360, 0xc000131290)
	/usr/local/go/src/runtime/panic.go:967 +0x166
sigs.k8s.io/controller-runtime/pkg/client/fake.NewFakeClientWithScheme(0xc0002084d0, 0xc000072f40, 0x1, 0x1, 0x8, 0xc000072f60)
	/home/harshal/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/client/fake/client.go:65 +0x37e
sigs.k8s.io/controller-runtime/pkg/client/fake.NewFakeClient(...)
	/home/harshal/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/client/fake/client.go:54
github.com/openshift/kata-operator/pkg/controller/kataconfig.TestKataConfigController(0xc000154240)
	/home/harshal/go/src/github.com/openshift/kata-operator/pkg/controller/kataconfig/kataconfig_controller_test.go:44 +0x261
testing.tRunner(0xc000154240, 0x1345c20)
	/usr/local/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x357
exit status 2
FAIL	github.com/openshift/kata-operator/pkg/controller/kataconfig	0.009s
```

**Environment**
* operator-sdk version:

  `55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd`

* Kubernetes version information:

  insert output of `kubectl version` here

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by camilamacedo86** [comment]
Hi @harche, 

It shows that `kataconfiguration` is a third-party an you are not adding the Kind schema correctly to the fake client.  See the example using the `v1.Route` OCP Kind in [Step 5: Use the API to implement unit tests](https://developers.redhat.com/blog/2020/02/04/how-to-use-third-party-apis-in-operator-sdk-projects/) section of this blog to help you achieve it. 

Also, feel free to check an example of a [client fake](https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/controller/backup/fakeclient_test.go) and [controller test](https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/controller/backup/controller_test.go#L328) in a personal project which can help you know how you can do it as well. 

And then, note that the `TypeMeta. v1.TypeMeta` is injected automatically, so shows not a good practice subscribe to these values. In this way, I'd recommend you not adding "TypeMeta: v1.TypeMeta" at all since we can add a wrong value for it. 

Please, let us know if you could solve it with the above information provided and we can close this one.

**Comment by harche** [comment]
it worked. instead of `NewFakeClient` I had to use `NewFakeClientWithScheme`

thanks for the pointer
