### ISSUE TITLE
Unit testing support

### ISSUE THREAD

**Issue by killwing** [operator-framework/operator-sdk#320]
Because the operator-sdk wraps controller functions in a high level, it's hard to inject test data (e.g.: add test data to the index cache directly) or add some mocks for unit testing. 
Any idea? Or any plan to make the operator-sdk more UT friendly?

related: #284

**Comment by hasbro17** [comment]
@killwing We're currently working on removing the global state and designing the right objects and interfaces that should make it easier to write unit tests and inject test data to the handler and controller #169 
However that's a major redesign which will take some time.

**Comment by killwing** [comment]
Glad to hear that it's in progress.
