### ISSUE TITLE
Running operator-sdk cannot generate custom resources

### ISSUE THREAD

**Issue by rgordill** [operator-framework/operator-sdk#321]
**Environment**

Fedora 28
go version go1.10.3 linux/amd64
dep 0.4.1-2

**Command**: operator-sdk new quay-operator --api-version=quay.redhat.com/v1alpha1 --kind=quay-cluster
...
Run dep ensure done
Run code-generation for custom resources
Error: failed to perform code-generation for CustomResources: (Generating deepcopy funcs
F0619 15:33:39.292050      10 main.go:74] Error: Failed making a parser: unable to add directory "github.com/quay/quay-operator/pkg/apis/quay/v1alpha1": while parsing "/go/src/github.com/quay/quay-operator/pkg/apis/quay/v1alpha1/types.go": /go/src/github.com/quay/quay-operator/pkg/apis/quay/v1alpha1/types.go:9:10: expected type, found '-' (and 3 more errors)
goroutine 1 [running]:
k8s.io/code-generator/vendor/github.com/golang/glog.stacks(0xc420065b00, 0xc4200e4000, 0x169, 0x1be)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:766 +0xcf
k8s.io/code-generator/vendor/github.com/golang/glog.(*loggingT).output(0x855760, 0xc400000003, 0xc4200e2000, 0x831cbb, 0x7, 0x4a, 0x0)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:717 +0x322
k8s.io/code-generator/vendor/github.com/golang/glog.(*loggingT).printf(0x855760, 0x3, 0x6e1476, 0x9, 0xc4200c9f30, 0x1, 0x1)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:655 +0x14c
k8s.io/code-generator/vendor/github.com/golang/glog.Fatalf(0x6e1476, 0x9, 0xc4200c9f30, 0x1, 0x1)
	/go/src/k8s.io/code-generator/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
	/go/src/k8s.io/code-generator/cmd/deepcopy-gen/main.go:74 +0x221

**Comment by hasbro17** [comment]
@rgordill `--kind=quay-cluster` is not a valid. It must be in CamelCase, e.g `--kind=QuayCluster`
https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#types-kinds
Can you try again with a valid Kind name.

**Comment by rgordill** [comment]
My fault. Yep, it works. Sorry for the confusion.
