### ISSUE TITLE
generate csv and bundle creation for Ansible Operators

### ISSUE THREAD

**Issue by aravinder111** [operator-framework/operator-sdk#3211]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
Help with operator-sdk's csv and bundle

## Question

**What did you do?**
1. Whats the use-case or scenario for generating csv in `Bundle format (default)` vs `Package manifests format` as per docs https://sdk.operatorframework.io/docs/olm-integration/generating-a-csv/#output
2. How will `operator-sdk bundle create --generate-only` command work with both types of csv generation ? 
3. When I generate csv in package manifest format for second version, package.yaml doesn't update to latest csv version
```bash
$ tree deploy
deploy
├── crds
│   ├── cache.example.com_memcacheds_crd.yaml
│   └── cache.example.com_v1alpha1_memcached_cr.yaml
├── operator.yaml
├── role.yaml
├── role_binding.yaml
└── service_account.yaml

1 directory, 7 files

$ operator-sdk generate csv --make-manifests=false --csv-version 0.0.1
INFO[0000] Generating CSV manifest version 0.0.1

Display name for the operator (required):
> foo

Description for the operator (required):
> foo

Provider's name for the operator (required):
> foo

Any relevant URL for the provider name (optional):
> foo

Comma-separated list of keywords for your operator (required):
> foo

Comma-separated list of maintainers and their emails (e.g. 'name1:email1, name2:email2') (required):
> foo:foo
INFO[0011] CSV manifest generated successfully

$ tree deploy
deploy
├── crds
│   ├── cache.example.com_memcacheds_crd.yaml
│   └── cache.example.com_v1alpha1_memcached_cr.yaml
├── olm-catalog
│   └── memcached-operator
│       ├── 0.0.1
│       │   └── memcached-operator.v0.0.1.clusterserviceversion.yaml
│       └── memcached-operator.package.yaml
├── operator.yaml
├── role.yaml
├── role_binding.yaml
└── service_account.yaml

4 directories, 9 files

$ cat deploy/olm-catalog/memcached-operator/memcached-operator.package.yaml
channels:
- currentCSV: memcached-operator.v0.0.1
  name: alpha
defaultChannel: alpha
packageName: memcached-operator

$ operator-sdk generate csv --make-manifests=false --csv-version 0.0.2 --from-version 0.0.1
INFO[0000] Generating CSV manifest version 0.0.2
INFO[0000] CSV manifest generated successfully

$ cat deploy/olm-catalog/memcached-operator/memcached-operator.package.yaml
channels:
- currentCSV: memcached-operator.v0.0.1
  name: alpha
defaultChannel: alpha
packageName: memcached-operator

$ tree deploy
deploy
├── crds
│   ├── cache.example.com_memcacheds_crd.yaml
│   └── cache.example.com_v1alpha1_memcached_cr.yaml
├── olm-catalog
│   └── memcached-operator
│       ├── 0.0.1
│       │   └── memcached-operator.v0.0.1.clusterserviceversion.yaml
│       ├── 0.0.2
│       │   └── memcached-operator.v0.0.2.clusterserviceversion.yaml
│       └── memcached-operator.package.yaml
├── operator.yaml
├── role.yaml
├── role_binding.yaml
└── service_account.yaml

5 directories, 10 files

$ cat deploy/olm-catalog/memcached-operator/memcached-operator.package.yaml
channels:
- currentCSV: memcached-operator.v0.0.1
  name: alpha
defaultChannel: alpha
packageName: memcached-operator
```

**What did you expect to see?**
For question#2, I expected to see `deploy/olm-catalog/memcached-operator/memcached-operator.package.yaml` have `currentCSV` field set to `memcached-operator.v0.0.2` instead of `memcached-operator.v0.0.1` as shown in my console putput above

**Environment**
* operator-sdk version:
```
operator-sdk version: "v0.18.0", commit: "921c33982687d6e9219fe0a1a326515fb37ae040", kubernetes version: "v1.18.2", go version: "go1.14.3 darwin/amd64"
```

**Comment by estroz** [comment]
1. A good overview of bundle vs package manifests and why we're transitioning to bundles is https://github.com/operator-framework/community-operators/issues/1680.
1. That command is specifically intended to work with bundles and should not be used for package manifests. That command will be going away in favor of `generate bundle`.
1. You need to specify `--channel=alpha` for your package manifest to update that channel. See `operator-sdk generate csv -h` for more info.

Heads up, [`generate packagemanifests`](#3149) will be landing soon, and `generate csv` will then be deprecated afterwards; `generate bundle` already exists. We're creating these commands to ensure UX around using bundles vs package manifests is clearly different.

**Comment by aravinder111** [comment]
Hello @estroz , Thanks for the reply.

So my end goal here is to run scorecard tests. Currently olm test suite for scorecard requires csv.yaml to be present, if you are gonna move away from csv and only have bundle, will the scorecard requirements change as well ??

Currently I do
1. operator-sdk generate csv
2. operator-sdk bundle create --generate only
3. oeprator-sdk scorecard -b path/to/bundle

Just want to confirm my understanding.
Question#1: Is my implementation correct ?
Question#2: what would future workflow look like ?

**Comment by estroz** [comment]
Your command flow looks correct. You would now do:
```sh
$ operator-sdk generate bundle
$ operator-sdk scorecard -b deploy/olm-catalog/<operator name>/manifests
```
We also have [`operator-sdk alpha scorecard`](https://sdk.operatorframework.io/docs/scorecard/scorecard-alpha/), which you would pass your bundle as an arg:
```sh
$ $ operator-sdk alpha scorecard deploy/olm-catalog/<operator name>/manifests
```

The non-alpha scorecard command will be deprecated once the alpha scorecard command is no longer alpha. For now feel free to continue using the former.

**Comment by aravinder111** [comment]
awesome. Thanks.. your suggestion worked for me.

One suggestion I would request is:
```
$ operator-sdk generate bundle -h
Generates bundle data for the operator

Usage:
  operator-sdk generate bundle [flags]

Flags:
      --apis-dir string          Root directory for API type defintions
      --channels string          A comma-separated list of channels the bundle belongs to (default "alpha")
      --crds-dir string          Root directory for CustomResoureDefinition manifests
      --default-channel string   The default channel for the bundle
  -h, --help                     help for bundle
      --input-dir string         Directory to read an existing bundle from. This directory is the parent of your bundle 'manifests' directory, and different from --manifest-root
      --interactive              When set or no bundle base exists, an interactive command prompt will be presented to accept bundle ClusterServiceVersion metadata
      --manifests                Generate bundle manifests
      --metadata                 Generate bundle metadata and Dockerfile
      --operator-name string     Name of the bundle's operator
      --output-dir string        Directory to write the bundle to
      --overwrite                Overwrite the bundle's metadata and Dockerfile if they exist
  -q, --quiet                    Run in quiet mode
  -v, --version string           Semantic version of the operator in the generated bundle. Only set if creating a new bundle or upgrading your operator

Global Flags:
      --verbose   Enable verbose logging
```

The help doesn't show what are mandatory and what is optional.. I needed to pass `--version` flag to make the command worked.

**Comment by estroz** [comment]
`--version` is only required when generating a new bundle. Do you have existing bundle metadata at `deploy/olm-catalog/<operator name>/manifests`?

The flag help could be improved. Will do so.

**Comment by aravinder111** [comment]
yup sorry I wasn't clear, I was trying to generate a new bundle. Thanks for your help 🙇 

If there is nothing you track from this, you can close this issue.
