### ISSUE TITLE
Migrating from 0.10.x to 0.17.1 

### ISSUE THREAD

**Issue by bhavin192** [operator-framework/operator-sdk#3213]
I was able to successfully migrate from 0.10.x to 0.17.1, all thanks to the great migrations docs :tada: 
There are few minor issues/changes/typos here and there, just trying to list all of them here, once discussed I can raise PR for those changes or create individual issues.
### 0.10.x --> 0.11.x
- [ ] I had to remove an import from tools.go as the package no longer exist in [`sigs.k8s.io/controller-tools@v0.2.0`](https://github.com/kubernetes-sigs/controller-tools/tree/v0.2.0/pkg/crd)
```bash
github.com/yugabyte/yugabyte-k8s-operator imports
	sigs.k8s.io/controller-tools/pkg/crd/generator: module sigs.k8s.io/controller-tools@latest found (v0.3.0), but does not contain package sigs.k8s.io/controller-tools/pkg/crd/generator
```
File: `tools.go`
```diff
 // +build tools
 
 package tools
-
-import (
-	_ "sigs.k8s.io/controller-tools/pkg/crd/generator"
-)
```

### 0.12.0 --> 0.13.0
- [x] There is typo in go.mod related details, it should be `v0.13.0` instead of `v0.13.1`. Raising PR for this right away. Ref: https://github.com/operator-framework/operator-sdk/issues/2556#issuecomment-585308509

### 0.14.x
- [ ] Steps to add `addMetrics()` function. More about this in 0.16.x.

### 0.15.x
- [x] The version `v0.15.2` is available, so we can ask users to use it directly instead of `v0.15.1`. _Raising PR for this._

### 0.16.x
- [x] 1. Typo: cmd/main.go should be `cmd/manager/main.go`. _Raising PR for this._
- [ ] 2. I didn't have `addMetrics()` function as I came from 0.10.x, it was added in 0.14.x https://github.com/operator-framework/operator-sdk/commit/81c6c8ae7e891971fcb234ee0ccd676e45f1d9d7.
- [ ] 3. Should we mention PR #2522 as well as it's also part of the 0.16.0 release and adds support for multiple namespaces.

### 0.17.x
- [x] We can update the version from go.mod to `v0.17.1` instead of `v0.17.0`. _Raising PR for this._

**Comment by estroz** [comment]
Thanks for making PR's for version bumps/typos. Feel free to make another one to add anything else missing!

/kind documentation
