### ISSUE TITLE
Unable to run kubectl apply -f config/samples/ for new layout

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3225]
## Bug Report

**What did you do?**
Follow up the quick-start steps for the new layout. 

```
mkdir $GOPATH/src/example
cd $GOPATH/src/example
operator-sdk init --domain my.domain
operator-sdk create api --group webapp --version v1 --kind Guestbook
make install
kubectl apply -f config/samples/
```

**What did you expect to see?**
All finished successfully. 

**What did you see instead? Under which circumstances?**

Note that when we run `kubectl apply -f config/samples/` it has been falling. 

```
 $ kubectl apply -f config/samples/
error: error validating "config/samples/kustomization.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false

```

```
$ cat config/samples/kustomization.yaml
## This file is auto-generated, do not modify ##
resources:
- webapp_v1_guestbook.yaml
```

**Environment**
* operator-sdk version: master / d2975b1ce3bf14c30fbbdfbe078a2cb096e62dfe

**Possible Solution**

- Not scaffold the `config/samples/kustomization.yaml` (by removing it the issue is solved)

IMO: Note that the config/samples are the dir where we have only the CR's and we should not have a kustomization.yaml on it. However, it has been using by the bundle. 

- To avoid it we need to change the test to ensure that it will follow up the quick-start steps. See: https://github.com/operator-framework/operator-sdk/blob/master/test/e2e-new/e2e_suite.go

**Comment by camilamacedo86** [comment]
@hasbro17 @joelanford  @estroz

**Comment by estroz** [comment]
This isn't a bug, we just need to update documentation to explicitly call

```
$ kubectl apply -f config/samples/cache_v1alpha1_memcached.yaml
```

which is how the Makefile does it (`make deploy`). In fact, the docs should directly use the Makefile whenever possible.

Side note: there's no good way afaik to avoid writing a `config/samples/kustomization.yaml` to include CR samples in `kustomize build config/bundle`, and shouldn't be removed in e2e tests.

/remove-kind bug
/kind documentation

**Comment by camilamacedo86** [comment]
Hi @estroz, 

it is true. I was following the kb one. Also, I checked that our quick is updated already. See: https://github.com/operator-framework/operator-sdk/search?q=kubectl+apply+-f+config%2Fsamples%2F&unscoped_q=kubectl+apply+-f+config%2Fsamples%2F

Closing this one :-)
