### ISSUE TITLE
Missing repo to push new scorecard images 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3228]
## Bug Report

```
WARNING! Your password will be stored unencrypted in /home/travis/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded
The push refers to repository [quay.io/operator-framework/scorecard-test-arm64]
fcfcaf300124: Preparing
1f3055647576: Preparing
d67708ffb6b3: Preparing
1584ba7a350e: Preparing
b4d0bbe32cf9: Preparing
unauthorized: access to the requested resource is not authorized
Makefile:212: recipe for target 'image-push-scorecard-test' failed
make: *** [image-push-scorecard-test] Error 1
The command "make image-push-scorecard-test" exited with 2.
cache.2
store build cache
```

<img width="1373" alt="Screenshot 2020-06-12 at 18 21 36" src="https://user-images.githubusercontent.com/7708031/84529645-b4d59b80-acd9-11ea-86ac-99f597f3944f.png">

See; https://travis-ci.org/github/operator-framework/operator-sdk/jobs/697568022

**Comment by camilamacedo86** [comment]
Hi @jmccormick2001 

See that we need to create the repo for the image in https://quay.io/repository/operator-framework/scorecard-test-arm64?tab=tags as it has for https://quay.io/repository/operator-framework/ansible-operator?tab=tags for example.

**Comment by jmccormick2001** [comment]
repos created for: scorecard-test-ppc64le, scorecard-test-s390x, scorecard-test-amd64, scorecard-test-arm64

**Comment by camilamacedo86** [comment]
Hi @jmccormick2001, 

The user used by the CI still without permissions to push the images/tags. See: https://travis-ci.org/github/operator-framework/operator-sdk/builds/697568002

**Comment by jmccormick2001** [comment]
I just updated the permissions for the repos.

**Comment by camilamacedo86** [comment]
Worked : See : https://travis-ci.org/github/operator-framework/operator-sdk/builds/697724231
closing this one.
