### ISSUE TITLE
ansible operator cannot watch dependent resources in other namespaces

### ISSUE THREAD

**Issue by jmazzitelli** [operator-framework/operator-sdk#3237]
## Bug Report

**What did you do?**

Trying to use this undocumented feature that @fabianvf pointed out: https://github.com/operator-framework/operator-sdk/blob/v0.12.0/pkg/ansible/watches/watches.go#L47

In short, I wanted to watch dependent resources (even those resources created outside the namespace where the CR is) in order for my Ansible playbook to be invoked when those dependent resources are modified or deleted (so my playbook can reconcile those changes).

So in my `watches.yaml`, I put the following settings:

```
watchDependentResources: True
watchClusterScopedResources: True
```

However, it doesn't seem that this works... modifications/removal of resources in other namespaces do not trigger the Ansible playbook.

@fabianvf has been following this in Slack so he knows what's going on  (he asked I submit this issue).

**What did you expect to see?**

When a resource that was created by the Ansible playbook in an external namespace (different from where the CR lives) is modified or deleted by a user, the Ansible playbook should be invoked again, so it gets a chance to reconcile those changes.

**What did you see instead? Under which circumstances?**

Nothing. :) The reconciliation did not happen, the Ansible playbook was not invoked, even though I deleted a resource that the playbook created in an outside namespace (i.e. namespace where the CR is not).

**Environment**
* operator-sdk version: 0.17.0, but would need this to work in the latest production version (today that is 0.12.0, though hopefully that will change soon)
Base image in my testing was `quay.io/operator-framework/ansible-operator:v0.17.0`

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by fabianvf** [comment]
Think I figured it out, if the operator isn't configured to watch the target namespace (via the `WATCH_NAMESPACE` environment variable), then it won't attempt to establish a dependent watch in the target namespace. For example:

If your operator is deployed in `test` and `WATCH_NAMESPACE=test`, then resources deployed into the `default` namespace will not be watched. 

If your operator is deployed in `test` and `WATCH_NAMESPACE="test,default"`, then resources deployed into the `default` namespace will be watched.

If your operator is deployed in `test` and `WATCH_NAMESPACE=""`, then resources deployed into the `default` namespace `will be watched.

The `watchClusterScopedResources` field doesn't affect this behavior, so as long as you have `watchDependentResources` set to `True` and the `WATCH_NAMESPACE` includes all namespaces you want to watch, everything should work fine.

Closing for now but feel free to reopen if you don't see the behavior described above.

**Comment by genialmaniac** [comment]
you closed the issue but does it mean you solved the bug in v0.20 ? This is a seirous bug according to me, whatever an operator creates, even on a "remote" namespace, it should be monitored anyway, regardless of the WATCH_NAMESPACE value

**Comment by fabianvf** [comment]
@genialmaniac the `WATCH_NAMESPACE` envvar allows admins to restrict the namespaces that the operator will watch, so it's intentional that the operator won't establish watches on namespaces that fall outside of the ones specified. Are you trying to have the operator reconcile dependent resources in a namespace where you don't want it to reconcile your primary resource?

**Comment by genialmaniac** [comment]
Hi, thanks to answer, let's take a gitops operator for example. It's namespace scoped, and it's monitoring repository(ies) based on a(some) given CRD. Potentially it'll indeed create external objects/CR in remote namespaces to reconcile the cluster with desired state. Would it means those objects will not be watched by the operator ? Sorry if that sounds abnormal to me.

**Comment by yedukondalurd** [comment]
what are the roles required to use resources in another namespace?
