### ISSUE TITLE
Migration guide for 0.18 is missing upgrade modules section 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3238]
Migration guide here https://sdk.operatorframework.io/docs/migration/v0.18.0/ is missing upgrade modules section : 

```
module github.com/operator-framework/operator-sdk-samples/go/memcached-operator

go 1.13

require (
	github.com/operator-framework/operator-sdk v0.18.1
	github.com/spf13/pflag v1.0.5
	k8s.io/api v0.18.2
	k8s.io/apimachinery v0.18.2
	k8s.io/client-go v12.0.0+incompatible
	sigs.k8s.io/controller-runtime v0.6.0
)

replace (
	github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.2+incompatible // Required by OLM
	k8s.io/client-go => k8s.io/client-go v0.18.2 // Required by prometheus-operator
)
```

**Comment by estroz** [comment]
Unfortunately I don't think the changelog generator would be helpful here. Instead the release doc should include a follow-up to running the generator.

/kind documentation

**Comment by camilamacedo86** [comment]
Changes: https://github.com/operator-framework/operator-sdk-samples/pull/131/files

**Comment by estroz** [comment]
For v0.18 we need a module section. Going forward however the SDK CLI will scaffold kubebuilder projects via a plugin, and PRs that include version increases for that plugin should contain a migration fragment with module version changes.
