### ISSUE TITLE
Installation for non-dep

### ISSUE THREAD

**Issue by Robb-Greathouse** [operator-framework/operator-sdk#324]
Mac High Sierra OS has a problem with "make dep".  Dep is not installed in High Sierra though it was there in previous versions.  There is discussion about adding it.

Could we have a set of non-dep dependent install instructions.

I tried handling the issue by manually installing the dependencies by running "make install" and then correcting the errors by tracking down the dependencies from the error messages and installing them.

After this "make install" ran without errors, however, when I try running "operator-sdk commands" I get the error message "operator-sdk not found"

**Comment by fanminshi** [comment]
` Dep is not installed in High Sierra`
Could you install the Dep tool manually? Is `Mac High Sierra OS ` preventing you from installing the Dep?

`when I try running "operator-sdk commands" I get the error message "operator-sdk not found"`
if you type `which operator-sdk`, is there any output? if not, you might not have the `PATH` setup correctly to look for the `operator-sdk` binary.

**Comment by theishshah** [comment]
In addition to verifying that go is in the PATH and set properly, here is a link to installation instructions for getting dep running on Mac OS. https://github.com/golang/dep#installation

**Comment by Robb-Greathouse** [comment]
make dep calls the makefile under operator-sdk which calls the dep:.  That in turn calls "dep ensure -v".
 The error is "dep file or directory not found".

I have found people encountering the same problem in Rack.  It is seems to be some problem with the C-Compiler in High Sierra.  I'm going to trying reinstalling and see what happens.

**Comment by theishshah** [comment]
Going to close for now, if there are further issues please feel free to re-open
