### ISSUE TITLE
Failed to run Packagemanifests

### ISSUE THREAD

**Issue by brindasanth** [operator-framework/operator-sdk#3252]
➜  sdn-controller operator-sdk run packagemanifests --operator-version v0.1.0
INFO[0000] Running operator from directory deploy/olm-catalog/sdn-controller
**FATA[0000] Failed to run operator: error initializing operator manager: no package manifest** found
➜  sdn-controller tree deploy
deploy
├── crds
│   ├── rpa.brvith.com_networkserviceblueprints_crd.yaml
│   ├── rpa.brvith.com_sdncontrollerplans_crd.yaml
│   ├── rpa.brvith.com_sdncontrollertasks_crd.yaml
│   ├── rpa.brvith.com_sdnnetworkconfigs_crd.yaml
│   ├── rpa.brvith.com_v1_networkserviceblueprint_cr.yaml
│   ├── rpa.brvith.com_v1_sdncontrollerplan_cr.yaml
│   ├── rpa.brvith.com_v1_sdncontrollertask_cr.yaml
│   └── rpa.brvith.com_v1_sdnnetworkconfig_cr.yaml
├── olm-catalog
│   └── sdn-controller
│       ├── manifests
│       │   ├── rpa.brvith.com_networkserviceblueprints_crd.yaml
│       │   ├── rpa.brvith.com_sdncontrollerplans_crd.yaml
│       │   ├── rpa.brvith.com_sdncontrollertasks_crd.yaml
│       │   ├── rpa.brvith.com_sdnnetworkconfigs_crd.yaml
│       │   └── sdn-controller.clusterserviceversion.yaml
│       └── metadata
│           └── annotations.yaml
├── operator.yaml
├── role.yaml
├── role_binding.yaml
└── service_account.yaml

5 directories, 18 files
➜  sdn-controller operator-sdk version
operator-sdk version: "v0.18.1", commit: "7bf7b6886d647dc202525daec16fab67dcc52a3d", kubernetes version: "v1.18.2", go version: "go1.14.3 darwin/amd64"

➜  sdn-controller operator-sdk olm status
INFO[0000] Fetching CRDs for version "0.15.1"
INFO[0001] Fetching resources for version "0.15.1"
INFO[0001] Successfully got OLM status for version "0.15.1"

NAME                                            NAMESPACE    KIND                        STATUS
olm                                                          Namespace                   Installed
subscriptions.operators.coreos.com                           CustomResourceDefinition    Installed
operatorgroups.operators.coreos.com                          CustomResourceDefinition    Installed
installplans.operators.coreos.com                            CustomResourceDefinition    Installed
clusterserviceversions.operators.coreos.com                  CustomResourceDefinition    Installed
aggregate-olm-edit                                           ClusterRole                 Installed
catalog-operator                                olm          Deployment                  Installed
olm-operator                                    olm          Deployment                  Installed
operatorhubio-catalog                           olm          CatalogSource               Installed
olm-operators                                   olm          OperatorGroup               Installed
aggregate-olm-view                                           ClusterRole                 Installed
operators                                                    Namespace                   Installed
global-operators                                operators    OperatorGroup               Installed
olm-operator-serviceaccount                     olm          ServiceAccount              Installed
packageserver                                   olm          ClusterServiceVersion       Installed
system:controller:operator-lifecycle-manager                 ClusterRole                 Installed
catalogsources.operators.coreos.com                          CustomResourceDefinition    Installed
olm-operator-binding-olm                                     ClusterRoleBinding          Installed

**Comment by estroz** [comment]
@brindasanth `run packagemanifests` is meant to be used with the [package manifests format](https://github.com/operator-framework/operator-registry/tree/release-4.3#manifest-format), while your operator is configured with the [bundle format](https://github.com/operator-framework/operator-registry/tree/release-4.3#manifest-format). I'm updating the command help text to make this requirement more explicit.
