### ISSUE TITLE
Is it valid to use the sdk for custom controllers?

### ISSUE THREAD

**Issue by maleck13** [operator-framework/operator-sdk#326]
I believe I understand the concept of Operators and what they are for but wondered would it be valid to use the Operator-sdk within a custom controller also?
They seem very similar in design but different in concept? Being able to have the dependencies "sorted" and the boiler plate all set up, allowing us to just focus on the required logic is very appealing. 
Is there any reason not to use the SDK for the basis of a controller?
Just for clarity, I would see a controller as something watching and working on Kubernetes based resources vs an Operator that watches a Kubernetes based resource and but works on a custom application.

**Comment by hasbro17** [comment]
@maleck13 While the SDK is currently designed to bootstrap an operator project you could change the generated defaults to instead just watch a standard kubernetes resource and write your controller that way.
So for e.g `operator-sdk new my-controller --api-version=cache.example.com/v1alpha1 --kind=Memcached` would scaffold a new project with `pkg/apis/cache/v1alpha1` to define your CRD.

You can ignore that and just change your `cmd/my-controller/main.go` to watch the kubernetes resource of your choice.
```Go
sdk.Watch("apps/v1", "Deployment", namespace, resyncPeriod)
```
In the future we'll probably make it more general by letting the user specify explicitly that they're not using CRDs and just writing a controller but for now that's the workaround.
There are some other limitations that we're currently working on i.e you can't requeue events for a primary resource by watching a secondary resource(like a replication controller would do) #146 but it should work for simple controllers.

**Comment by alecmerdler** [comment]
You would probably be better off using [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder).

**Comment by LiliC** [comment]
Closing this issue, as hopefully your question was answered, but feel free to open a new one in case it wasn't.
