### ISSUE TITLE
Multiple controllers in a single operator?

### ISSUE THREAD

**Issue by walkamongus** [operator-framework/operator-sdk#3263]
## Type of question

Feature/implementation

## Question

**What did you do?**
I have a single operator that has four different controllers. Once of the controllers is an abstraction that watches a single Custom Resource and creates three other Custom Resources, each of which is managed by a respective controller.

This seems to work just fine when the main abstraction CR is created. However, if I update a field in the main abstraction CR that does not result in a change to any of the child CRs, such as moving a value to  a new field thats replacing a deprecated one, I'm still seeing a Generation change in a child CR and a related reconcile trigger on the child CR controller.

**What did you expect to see?**
A change to the main CR that results in no changes to child/owned CRs results in a main controller reconcile trigger, but no triggering of child CR controllers.

**What did you see instead? Under which circumstances?**
I've added extensive logging and object dumps throughout the main abstraction controller to verify it never changes any of the child CRs and I've tried bypassing the caching client with an `apiReader` in the child CR controller to remove the cache from the picture.

After end of the main controller reconciliation loop, which makes no changes to owned CRs (and returns with `reconcile.Result{}, nil`), an unexpected reconciliation occurs in a controller for an owned resource and the `Generation` of the owned resource has increased from what it was in the object dumps in the main controller loop.

**Environment**
* operator-sdk version:

  `operator-sdk version: "v0.17.1", commit: "6d108056f39fa19546cf9235fad6e84b0683114a", kubernetes version: "unknown", go version: "go1.13.10 linux/amd64"`

* Kubernetes version information:

 `Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind: 

vanilla k8s

**Additional context**
Add any other context about the question here.

**Comment by camilamacedo86** [comment]
Hi @walkamongus, 

Let's see if I understood your scenario. You have a controller that manages a KIND. Then, due the reconciliation process, you are creating new CR's of the same KIND. 

> What did you expect to see?
> A change to the main CR that results in no changes to child/owned CRs results in a main controller reconcile trigger, but no triggering of child CR controllers.

If you have a controller which was created to manage of a KIND it means that by default, you will find the watches for the Primary resources already implemented by each controller that you generated by using the SDK tool as follows.
``` go
// Watch for changes to primary resource Memcached
err = c.Watch(&source.Kind{Type: &cachev1alpha1.Memcached{}}, &handler.EnqueueRequestForObject{})
if err != nil {
    return err
}
```

So, if you create/update/delete a CR of the KIND that is managed by it (in the example Memcached ) then the reconcile will be re-trigged. 

**How works the Reconcile()?**

The reconcile function is responsible for synchronizing the resources and their specifications according to the business logic implemented on them. In this way, it works like a loop, and it does not stop until all conditionals match its implementation. The following is pseudo-code with an example that clarifies it.

```go
reconcile App {

   // Check if a Deployment for the app exists, if not create one
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   } 
   ... 
    
   // If it is at the end of the loop, then:
   // All was done successfully and the reconcile can stop  
   return reconcile.Result{}, nil

}
```

**Using the Watch to reconcile**

By default, you will find the watches for the Primary resources already implemented by each controller that you generated by using the SDK tool as follows.
``` go
// Watch for changes to primary resource Memcached
err = c.Watch(&source.Kind{Type: &cachev1alpha1.Memcached{}}, &handler.EnqueueRequestForObject{})
if err != nil {
    return err
}
```

However, note that in the [Mencached sample](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/pkg/controller/memcached/memcached_controller.go#L52-L70) has watches implemented for each secondary object controlled/created by it.

https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/pkg/controller/memcached/memcached_controller.go#L52-L70

Please, let us know if the above information clarifies how it works and if we can close this one. If not, please could you try to clarify better `What did you do?`, `What did you expect to see?`, `What did you see instead? Under which circumstances?` for we try to help you with. Maybe a snippet of the codes can help too. 

Looking for your reply.

**Comment by camilamacedo86** [comment]
Hi @walkamongus, 

Could you please let us know if still anything else that should be addressed here or if the information provided is enough already for you solve your case and we can close this one?

**Comment by walkamongus** [comment]
@camilamacedo86 thank you for the information. It turns out everything works exactly as expected. I ended up having a bad k8s master/etcd member that was causing my operator to spin out of control from resourceVersions jumping around.

**Comment by camilamacedo86** [comment]
hi @walkamongus, 

really tks for letting us know.
