### ISSUE TITLE
operator-sdk should generate a simple restapi client

### ISSUE THREAD

**Issue by sjpotter** [operator-framework/operator-sdk#3264]
## Feature Request

**Is your feature request related to a problem? Please describe.**

go-client is useful for writing programs that interact with the built in resources, as one creates custom resources with operator-sdk, operator-sdk should create the scafolding that makes it easy to include a client that can access the custom resources that one builds with the operator-sdk.

at a simple level, it would enable easier programmatic testing of the operator through the manipulation of the custom resources in test code

**Describe the solution you'd like**

generate code such as 

https://www.martin-helmich.de/en/blog/kubernetes-crd-client.html

**Comment by sjpotter** [comment]
wondering if it's much simpler and this code (or similar) would be what's needed and if so, should it be included in the generated code so that other users don't have to figure out the magic incantation.

```golang
func getClient() (client.Client, error) {
	cfg, err := config.GetConfig()
	if err != nil {
		return nil, err
	}

	mapper, err := apiutil.NewDynamicRESTMapper(cfg)
	if err != nil {
		return nil, err
	}

	err = apis.AddToScheme(scheme.Scheme)
	if err != nil {
		return nil, err
	}

	return client.New(cfg, client.Options{Scheme: scheme.Scheme, Mapper: mapper})
}
```

**Comment by camilamacedo86** [comment]
HI @sjpotter, 

In the default scaffolded project, the client is created and added to the manager. See the `main.go`: 

**(scaffolded by default)**
https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/cmd/manager/main.go#L80-L85

**(scaffolded by default)**
https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/cmd/manager/main.go#L110-L115

Then, users are able to use the Client provide in the controllers with the default scaffold. See: 

**(scaffolded by default)**
https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/pkg/controller/memcached/memcached_controller.go#L27-L36

Example: 

https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/pkg/controller/memcached/memcached_controller.go#L27-L36

So, could you please let us know what you did that was not achievable with the default implementation motivates you to open this RFE? What is the use case? Is not the client provided enough for your scenario?

**Comment by sjpotter** [comment]
the use case is writing integration tests that manipulate the custom resources in a programmatic manner in go.  and ensuring that the live operator does what one expects.

**Comment by camilamacedo86** [comment]
Hi @sjpotter, 

You should not create a new client to use in the test. You should use the [fake client](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client/fake) instead of that or the [env test](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/envtest). See: 
- https://master.sdk.operatorframework.io/docs/golang/legacy/unit-testing/ 
- https://book.kubebuilder.io/reference/testing/envtest.html

**Comment by sjpotter** [comment]
this doesn't help my use case.  Right now I'm building a validating webhook proxy operator.  i.e. validating webhooks are cluster level objects.  but validatig webhooks are also things that namespaced operators would want to use and creating a cluster level object that points to them is problematic on multiple levels (simplest, requires administrator intervention for every namespace that the operator is setup in).  the idea of this operator is to have 2 types of CRs.  1 that the administrator would setup (cluster level) that basically define what validating webhook "rules" should be accepted by this webhook (i.e. it will generate a custer level validatingwebhook that points to itself for all those CRs) and naespaced CRs that individual users running a namespaced operator can use that will tell the operator/proxy to forward requests to it that match its rule (i.e. analogous to a regular cluster wide validatingwebhook configuration resource, just namespaced through the proxy, only forwarding to it for resources that are in its namespace).

I don't think a "fake" kubernetes environment will suffice, I need to be able to run a real kubernetes environment to do proper e2e testing

**Comment by camilamacedo86** [comment]
> I don't think a "fake" kubernetes environment will suffice, I need to be able to run a real kubernetes environment to do proper e2e testing.

I'd recommend you check the [env test](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/envtest) as suggested above which indeed is used to do the tests in the controller-runtime. See: https://github.com/kubernetes-sigs/controller-runtime/tree/master/pkg/cache

Regards your RFE over SDK as lib provide a feature with this implementation or the need over we doc the code in someplace we will discuss it in the next meeting triage and feel free to attend if you wish. Also, please feel free to push a PR with your suggestion for the docs as well.

**Comment by estroz** [comment]
The SDK is getting rid of its native Go scaffolds in favor of kubebuilder's Go plugin, so if this were to be implemented it wouldn't be done here. This may be worth re-opening in [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/), although typically people fake their clients or use envtest. In fact, envtest may do what you're asking for so I suggest investigating that further.
