### ISSUE TITLE
Object returned by the operator has no annotations when it actually does

### ISSUE THREAD

**Issue by cscetbon** [operator-framework/operator-sdk#3268]
## Type of question

Issue with what is on the object returned by the operator

## Question

**What did you do?**
I have an operator that watches resources but many times it can't see annotations on the object. I migrated to 0.18 and got the same issue.
Here is the [object](https://github.com/Orange-OpenSource/casskop/blob/backup-operator/pkg/apis/db/v1alpha1/cassandrabackup_types.go#L83-L90) my operator watches  and the [code](https://github.com/Orange-OpenSource/casskop/blob/backup-operator/pkg/controller/cassandrabackup/cassandrabackup_controller.go#L190-L194) that can't see the annotation

**What did you expect to see?**
I expect the annotation on the object I get by [querying](https://github.com/Orange-OpenSource/casskop/blob/backup-operator/pkg/controller/cassandrabackup/cassandrabackup_controller.go#L156) k8s to have the annotation I see when I query it myself 
```
$ k get cassandrabackups.db.orange.com backup-tests -o json|jq '.metadata.annotations'
{
  "cassandrabackups.db.orange.com/last-applied-configuration": "{\"kind\":\"CassandraBackup\",\"apiVersion\":\"db.orange.com/v1alpha1\",\"metadata\":{\"name\":\"backup-tests\",\"namespace\":\"cassandra-e2e\",\"selfLink\":\"/apis/db.orange.com/v1alpha1/namespaces/cassandra-e2e/cassandrabackups/backup-tests\",\"uid\":\"ddf45752-ff3d-4256-8cd7-925c7bfb99d6\",\"generation\":21,\"creationTimestamp\":\"2020-06-19T12:50:52Z\"},\"spec\":{\"cassandracluster\":\"cassandra-e2e\",\"datacenter\":\"dc1\",\"storageLocation\":\"s3://cscetbon-lab\",\"schedule\":\"@every 2m\",\"snapshotTag\":\"first\",\"entities\":\"k1.standard1\",\"secret\":\"aws-backup-secrets\"}}",
  "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"db.orange.com/v1alpha1\",\"kind\":\"CassandraBackup\",\"metadata\":{\"annotations\":{},\"name\":\"backup-tests\",\"namespace\":\"cassandra-e2e\"},\"spec\":{\"cassandracluster\":\"cassandra-e2e\",\"datacenter\":\"dc1\",\"entities\":\"k1.standard1\",\"secret\":\"aws-backup-secrets\",\"snapshotTag\":\"first\",\"storageLocation\":\"s3://cscetbon-lab\"}}\n"
}
```

**What did you see instead? Under which circumstances?**
Instead no annotations are seen 

**Environment**
* operator-sdk version: **v0.18.1**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10+k3s1", GitCommit:"5e9f690000fc6b16d2a2553801f477702472792b", GitTreeState:"clean", BuildDate:"2020-06-01T16:29:13Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: k3d

**Comment by estroz** [comment]
This very well could be a caching issue, since any cache updates won't occur until an event occurs on the object. Are the annotations never applied, or do they eventually get applied but not immediately?

**Comment by cscetbon** [comment]
@estroz It seems sometimes they get attached to the object and sometimes they don't which doesn't make much sense.

**Comment by camilamacedo86** [comment]
Hi @cscetbon, 

When you say that sometimes they get attached and sometimes they don't, how are you checking it? Are you manually checking the resource in the cluster or are you saying it because the behaviour implemented in the code that should occur when has the annotation sometimes is not performed? Also, are the annotations added by your code logic? 

Just a thought: Are you getting the latest version of the resource before the annotation check (e.g r.client.GET and then, check)? if not, the code might be checking an old version of the object without the annotation.

**Comment by cscetbon** [comment]
@camilamacedo86 whenever the controller's reconcile function gets called I do a GET of the object using the operator's client https://github.com/Orange-OpenSource/casskop/blob/backup-operator/pkg/controller/cassandrabackup/cassandrabackup_controller.go#L156. I checked the annotation by manually debugging the code. I really can't see how at some point there is no annotations on the object returned. You can look at the link I sent you to see the controller's reconcile and the controller's add function too.

**Comment by camilamacedo86** [comment]
Hi @cscetbon, 

The reconcile function works like a loop, and it does not stop until all conditionals match its implementation. So, if we check if the Deployment already exists, if not create a new one:
```go
	deployment := &appsv1.Deployment{}
	err = r.client.Get(context.TODO(), types.NamespacedName{Name: memcached.Name, Namespace: memcached.Namespace}, deployment)
	if err != nil && errors.IsNotFound(err) {
		// todo; if is here is because do not exist and then, we will create
		dep := r.deploymentForMemcached(memcached)
		err = r.client.Create(context.TODO(), dep)
		{...}
	} else if err != nil {
		reqLogger.Error(err, "Failed to get Deployment.")
		return reconcile.Result{}, err
	}
```

Then, check its value in the next step: 

```
       // Ensure the deployment size is the same as the spec
	size := memcached.Spec.Size
	if *deployment.Spec.Replicas != size {
		// do something
	}
```

It will not work. See that the value in the deployment will be `appsv1.Deployment{}` and not the resource that was created in the cluster. We need to GET the deployment from the cluster before performing the check to `ensure the deployment size is the same as the spec`. 

See [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/pkg/controller/memcached/memcached_controller.go#L126) in the Memcached Sample that after we create the resource we return `return reconcile.Result{Requeue: true}, nil` which will call the reconcile again. However, we could either just `r.client.GET`deployment to get the latest version of it from the cluster as well.  Also, beware that between you GET data from the cluster until you decide to make some operation using it something can be changed already. in this way, the solutions require to be idempotent.

Please, let us know if the information provided help you with and if we can agree in close this one.

**Comment by cscetbon** [comment]
@camilamacedo86 I'm not sure how relevant is this information. In order to test it, I am in debug mode and as soon as it starts and does the GET call I check what is in the object return. That's where I can't see the annotations which exist on the object itself. I suspect it's coming from the controller-runtime that we've upgraded.

**Comment by camilamacedo86** [comment]
Hi @cscetbon, 

> In order to test it, I am in debug mode and as soon as it starts and does the GET call I check what is in the object return.hat's where I can't see the annotations which exist on the object itself. 

How do you know that the annotation exist in the object? Are they added fixed in the yaml CR?

**Comment by cscetbon** [comment]
Because I can check the object using kubectl directly. It seems kubectl doesn’t use controller-runtime while the operator does. That might be the track I should follow, what do you think ?

**Comment by camilamacedo86** [comment]
Hi @cscetbon, 

I am closing this one since it has been without interaction for a while and I think you already figure out this problem. 

However, only to register the client provided in the controller will get the object in the same way. Note that, if you do a  client.GET the object and have a var as, for example,  deployment with this value and then change this object on the Cluster then you need to fetch the resource again. The variable will have the info/data related to the moment that it was done.

Please, feel free to raise a new issue or ask to re-open this one if you need.
