### ISSUE TITLE
How does one use the new project layout for building in Docker?

### ISSUE THREAD

**Issue by JoelColledge** [operator-framework/operator-sdk#3271]
I see here that there is a new project layout:
https://github.com/operator-framework/operator-sdk/blob/56656cfb54ae38df108d4fe3dd453e530fe67b37/cmd/operator-sdk/build/cmd.go#L67

This appears to allow builds entirely in Docker, which is great. I would like to use it. Is there any documentation for how to migrate to this structure?

It looks like newly scaffolded projects don't yet use this structure, so I can't generate an example that way.

@camilamacedo86

**Comment by JoelColledge** [comment]
I was able to get the new `operator-sdk build` working by adding these files to the project:
* https://github.com/JoelColledge/piraeus-operator/blob/5a36aa996fcc08162fa59cc4fd2e3a62fc79157d/Dockerfile
* https://github.com/JoelColledge/piraeus-operator/blob/5a36aa996fcc08162fa59cc4fd2e3a62fc79157d/PROJECT

But that created other problems. For instance `operator-sdk generate crds` disappeared. This is extremely unconventional. Usually the available subcommands and flags of a CLI program do not depend on the working directory.

I'm going to use a different solution to my problem, but I'll leave this ticket open, because the new structure will need documentation eventually.

**Comment by camilamacedo86** [comment]
Hi @JoelColledge, 

> This appears to allow builds entirely in Docker, which is great. I would like to use it. Is there any documentation for how to migrate to this structure?

> It looks like newly scaffolded projects don't yet use this structure, so I can't generate an example that way.

Currently, the project has been in process to be integrated with Kubebuilder which means that a new layout of the project will be generated by SDK. To check this, you can run `operator-sdk init` to create the project. 

See: https://github.com/operator-framework/operator-sdk/blob/master/cmd/operator-sdk/main.go#L43-L54

> I was able to get the new operator-sdk build working by adding these files to the project:
{...}
> But that created other problems. For instance operator-sdk generate crds disappeared.

The projects that will be scaffolded in the new layout will have the PROJECT file as you could check. And then, the command `operator-sdk generate crds` no longer is applied for the new layout. The structure changed and this operation will be done via target in makefile which brings more flexibility to its users. 

> I'm going to use a different solution to my problem, but I'll leave this ticket open, because the new structure will need documentation eventually.

In the https://master.sdk.operatorframework.io/docs/golang/ you are able to check the docs over the new layout. You need to choose master: 

<img width="792" alt="Screenshot 2020-06-22 at 16 19 23" src="https://user-images.githubusercontent.com/7708031/85304911-38df0e80-b4a4-11ea-969c-8034b9d85c1e.png">

So, I am closing this issue. However, please feel free to raise new ones if you wish and if you need help.

**Comment by JoelColledge** [comment]
Thanks @camilamacedo86 for the detailed description!
