### ISSUE TITLE
How to create secret using CRD/Operator

### ISSUE THREAD

**Issue by adi658** [operator-framework/operator-sdk#3281]
Hello :)

I am trying to create an Operator which has business logic written in python and gives some output. This output has to be stored as a secret. ANy idea how to proceed on this. I am trying to create CRDs but do not know how that works

**Comment by camilamacedo86** [comment]
Hi @adi658, 

The Secret is a resource as the others from the k8s API and then, you need to create the struct as you do for a Deployment or a Service.  Example:

```go
       &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      cr.Name,
			Namespace: crNamespace,
			Labels:    labelsForCr(m.Name),
		},
		StringData: data,
	}
```
See its API: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#secret-v1-core

Also, I'd like to suggest you check the [blog](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/) to have a better idea of how you can work with. In this way, I am closing this one as sorted out. However, please feel free to open new issues to get a help if you need.
