### ISSUE TITLE
Operator SDK or Kubebuilder, which one takes precedence?

### ISSUE THREAD

**Issue by woohhan** [operator-framework/operator-sdk#3290]
## Type of question
General

## Question
Hello. I am using the Operator SDK very well. I am writing a book for operator development in Korea. However, the operator SDK and Kubebuilder play a similar role, which makes it difficult to prioritize. I have a few questions, can you answer me?

1. If operator SDK and Kubebuilder are merged, which one takes precedence? Are we planning to deprecate either one?

2. Because a book can't be edited, so I need a long-term point of view to select a tool. Which of the two tools do I prefer?

Thanks again for developing a great tool for operator development.

**Comment by estroz** [comment]
`operator-sdk` is a drop-in replacement for `kubebuilder`, so you do not have to make a choice unless you want operator-framework features like bundles for OLM.

From our offline conversation (for posterity):

>The new CLI is already available in master, which can be accessed by running `operator-sdk init` for a new project or migrating an existing one with this guide. we should be cutting a v0.19 release soon. Ansible and Helm are not supported by `init` yet; you can create these project types as normal with `operator-sdk new --type=<ansible|helm>`

**Comment by camilamacedo86** [comment]
Hi @woohhan, 

See that the idea is both projects share the same core-base which means that SDK wins some features that are available for Kubebuilder currently. Note that with we are able to spend more effort in the advantages and facilities that SDK tool can promote on the top of that also, for example, to integrate your project with OLM and allow users distribute their projects on the https://operatorhub.io/  such as described by  @estroz.

Also, I see SDK promoting helpers for its users as a lib which are not available for Kubebuilder too.  For more information over the integration see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/integrating-kubebuilder-and-osdk.md

@joelanford @dmesser wdyt about we have a doc with this info in the SDK website? If you think that it is a good idea, @dmesser could you help us with this doc? IMO you might be able to provide it in a better way.
