### ISSUE TITLE
Need help with alpha scorecard test "olm-crds-have-resources"

### ISSUE THREAD

**Issue by aravinder111** [operator-framework/operator-sdk#3294]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

Support with alpha scorecard test `olm-crds-have-resources`

## Question

**What did you do?**

So I ran `operator-sdk alpha scorecard deploy/olm-catalog/my-operator` on the generated manifests and I got all tests to pass except the scorecard test `olm-crds-have-resources`. I'm using same config file listed here https://github.com/operator-framework/operator-sdk/blob/master/internal/scorecard/alpha/testdata/bundle/tests/scorecard/config.yaml
```
"description": "All Owned CRDs contain a resources subsection",
"errors": [
"Owned CRDs do not have resources specified"
],
"log": "Loaded ClusterServiceVersion: tron-example-operator.v2.0.3\n",
"name": "olm-crds-have-resources",
"state": "fail"
```

I generated my manifest using `operator-sdk generate bundle -v 2.0.3 --overwrite --default-channel alpha` and my CSV yaml looks like
```
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Frontend
      name: frontends.foo.com
      version: v1alpha1
  description: my operator
```

**What did you expect to see?**
I expect CSV to have `spec.customresourcedefinitions.owned[0].resources` fields to exist.

**What did you see instead? Under which circumstances?**
CSV generated didnot have `spec.customresourcedefinitions.owned[0].resources` fields, hence the test `olm-crds-have-resources` is failing.

**Environment**
* operator-sdk version:
```
operator-sdk version: "v0.18.0", commit: "921c33982687d6e9219fe0a1a326515fb37ae040", kubernetes version: "v1.18.2", go version: "go1.14.3 darwin/amd64"
```

**Comment by jmccormick2001** [comment]
I'll take a look.

**Comment by jmccormick2001** [comment]
ok, I recreated this one, and it does not include resources into your owned CRD when you generate it...I seem to recall that this info needs to be manually added by end users after they generate because it was not possible to specify resources without knowledge of the operator logic.  So you can add those resources like this and re-run the test to make it pass:
  customresourcedefinitions:
    owned:
    - kind: Memcached
      name: memcacheds.cache.example.com
      version: v1alpha1
      resources:
        - kind: Service
          name: ''
          version: v1

I think this answers it, but please re-open if you feel I didn't interpret this correctly.

**Comment by aravinder111** [comment]
Can this be documented somewhere ? Looks pretty important to be known to users of scorecard tests.

Will operator-sdk support generating these resources in future for all 3 types GO, ansible, helm _**or**_ is it a bug ? I understand its difficult to generate these resources. I'm particularly interested in ansible one.. But a big note saying to do it manually should do it.

Additional question: Does it matter to have this resources field in the first place if its not auto-generated ? or get rid of the test at all ? nobody will really keep track of all resources owned by a CRD in a CI/CD world.

**Comment by jmccormick2001** [comment]
good questions, I'll ask around as to the value of this test given they are not populated automatically or via a marker.

**Comment by jmccormick2001** [comment]
after thinking about this one, what I'll plan on doing is add a documentation note that tells people the need for a user to fill out the resources in order for this test to pass.

**Comment by aravinder111** [comment]
Thank you @jmccormick2001 🥇
