### ISSUE TITLE
Ansible Operator does not output stdout inside with_items loop

### ISSUE THREAD

**Issue by ktenzer** [operator-framework/operator-sdk#3301]
## Bug Report

**What did you do?**
Ran following inside tasks/main.yaml in role executed by operator sdk running in local mode.
```
- debug:
    msg: "test {{ item }}"```
  with_items:
    - 1
    - 2
    - 3

**What did you expect to see?**
Expected to see "test 1, test 2, test 3" printed to stdout.

**What did you see instead? Under which circumstances?**
I saw no output or stdout.

I tested also that loop iteration is happening and being processed just if you write any stdout within loop it is not sent.


**Environment**
0.18 Ansible operator

[fedora@myfedora pitbull]$ oc version
Client Version: 4.4.3
Server Version: 4.4.3
Kubernetes Version: v1.17.1


* Are you writing your operator in ansible, helm, or go?
Ansible

**Possible Solution**
<!--- Only if you have suggestions on a fix for the bug -->

**Additional context**
Add any other context about the problem here.

**Comment by JieJhih** [comment]
Have you set env `ANSIBLE_DEBUG_LOGS=true`?

**Comment by kensipe** [comment]
@ktenzer any feedback on use of ANSIBLE_DEBUG_LOGS?

**Comment by ktenzer** [comment]
I havent had the chance to test this yet but yes assuming that works then this is acceptable and case can be closed.

**Comment by camilamacedo86** [comment]
Hi @ktenzer, 

You needs to add the ENV VAR as done [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/ansible/memcached-operator/deploy/operator.yaml#L40-L41)then, you will see the Ansible logs in the container as well.  

We have the info in https://sdk.operatorframework.io/docs/ansible/development-tips/#viewing-the-ansible-logs but also IMO would be great add it in the https://sdk.operatorframework.io/docs/ansible/reference/advanced_options/ and/or quick-start as well.
