### ISSUE TITLE
Error is faced when run `make bundle` without apis scaffolded

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3306]
## Bug Report

**What did you do?**
- operator-sdk init
- make
- make bundle

**What did you expect to see?**
All done without errors

**What did you see instead? Under which circumstances?**
```
kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version 0.0.1  
2020/06/28 07:26:45 absolute path error in '/Users/camilamacedo/go/src/example/config/crd' : evalsymlink failure on '/Users/camilamacedo/go/src/example/config/crd' : lstat /Users/camilamacedo/go/src/example/config/crd: no such file or directory
Error: accumulating resources: recursed accumulation of path '../default': accumulating resources: accumulating resources from '../crd': evalsymlink failure on '/Users/camilamacedo/go/src/example/config/crd' : lstat /Users/camilamacedo/go/src/example/config/crd: no such file or directory
```

**Environment**
* operator-sdk version: https://github.com/operator-framework/operator-sdk/commit/15bdeeac514356fceffa96307570810318d7ed7e

**Possible Solution**
Check if has CRD and Samples if not, gen CSV without this info.

**Comment by camilamacedo86** [comment]
c/c @estroz

**Comment by estroz** [comment]
This is expected behavior since no APIs have been created yet.

The correct solution would be to not execute `generate bundle` if `kustomize build` fails, although I'm hesitant to "fix" this since other commands fail in a similar way if `create api` was not run first, ex. `make install`.

The one case I see this being a problem for is a project with only required CRDs (no custom APIs), which is a case I believe the SDK supports. @joelanford @hasbro17 thoughts on this?

**Comment by camilamacedo86** [comment]
It will be a problem for Helm/Ansible as well which has not API's scaffolded at all.

**Comment by estroz** [comment]
Helm and Ansible projects will have CRDs available in `config/crds` (when plugins are implemented).

**Comment by camilamacedo86** [comment]
Hi @estroz, 

It is true. However, still one case. Should we not allow gen the bundle with the project has not API/CRD's ones? I think it can be easily solved by allowing gen with the data existent instead of having the issue. Also, IMO we should allow and raise a WARN info in this case instead of `lstat /Users/camilamacedo/go/src/example/config/crd: no such file or directory`

**Comment by camilamacedo86** [comment]
Hi @estroz it is true. Discussed today in the meeting.

**Comment by estroz** [comment]
Helm/Ansible plugins are implemented, this can be closed.
