### ISSUE TITLE
csv generation fails

### ISSUE THREAD

**Issue by davidkarlsen** [operator-framework/operator-sdk#3309]
## Bug Report

**What did you do?**
```
INFO[0000] Generating CSV manifest version              

Display name for the operator (required): 
> github-actions-runner-operator

Description for the operator (required): 
> Kubernetes operator for GitHub action runners

Provider's name for the operator (required): 
> github-actions-runner-operator

Any relevant URL for the provider name (optional): 
> https://github.com/evryfs/github-actions-runner-operator/

Comma-separated list of keywords for your operator (required): 
> operator,kubernetes,github,actions,runner

Comma-separated list of maintainers and their emails (e.g. 'name1:email1, name2:email2') (required): 
> davidkarlsen:david@davidkarlsen.com
ERRO[0094] ClusterServiceVersion validation: [CSVFileNotValid] (github-actions-runner-operator.vX.Y.Z) metadata.name "github-actions-runner-operator.vX.Y.Z" is invalid:
[a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')] 
FATA[0094] error generating CSV: error building CSV: got ClusterServiceVersion validation errors 
```

**What did you expect to see?**
Should complete, or fail with a correct message. As seen above the input should be allowed.

**What did you see instead? Under which circumstances?**
See above

**Environment**
* operator-sdk version: v0.18.2

* go version:
go version go1.14.4 darwin/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-27T00:38:11Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
docker

* Are you writing your operator in ansible, helm, or go?
go

**Comment by tengqm** [comment]
the `github-actions-runner-operator.vX.Y.Z` is invalid because it contains upper case characters.

**Comment by davidkarlsen** [comment]
No upper-case are input - see copy&paste. Or cannot description contain uppercase chars?

**Comment by tengqm** [comment]
The `vX.Y.Z` segment is invalid, I think.

**Comment by estroz** [comment]
@davidkarlsen what command are you using, and does your project have a `PROJECT` file? The `vX.Y.Z` is the invalid part, and is an artifact of the generation process.

**Comment by davidkarlsen** [comment]
No - no PROJECT file. It was generated with an older version of operator-sdk.
It seems to pass when I add `--version`

**Comment by estroz** [comment]
@davidkarlsen are you running this command to generate a CSV for the first time (none existed beforehand), and if one did exist was it in a directory like `deploy/olm-catalog/<operator name>/1.2.3` or `deploy/olm-catalog/<operator name>/manifests`?

**Comment by davidkarlsen** [comment]
Yes, I am running it for the first time. It seems like bundles is a way to distribute my operator - although I find very little information on it, and the info I find is sometimes conflicting. I was able to get the manifests generated by passing --version

**Comment by estroz** [comment]
@davidkarlsen when generating a CSV for the first time with `generate csv`, the `--version` flag is required because there is no prior CSV to pull a version from. This requirement is not validated so the error message you're seeing is confusing. This will be fixed.

Side note: `generate csv` will be deprecated soon in favor of `generate bundle`, which has informative help text on bundles. You can find more information on bundles [here](https://github.com/operator-framework/operator-registry/#manifest-format).

**Comment by davidkarlsen** [comment]
Thanks. I'll close this
