### ISSUE TITLE
Error: unknown flag: --repo

### ISSUE THREAD

**Issue by peterducai** [operator-framework/operator-sdk#3324]
## Bug Report

**What did you do?**
```
$ operator-sdk new memcached-operator --repo=github.com/example-inc/memcached-operator
Error: unknown flag: --repo
Usage:
  operator-sdk new <project-name> [flags]
.....

FATA[0000] unknown flag: --repo                         
$ operator-sdk version
operator-sdk version: "v0.18.0-76-g8d7c4f80", commit: "8d7c4f801348b95df2d0488dde0b4f70f88b8b4a", kubernetes version: "v1.18.2", go version: "go1.14.3 linux/amd64"
```

issue is that when using from source (not binary) install, you get 0.18.0 and NOT 0.18.2

**What did you expect to see?**
same as noted in https://v0-18-x.sdk.operatorframework.io/docs/golang/quickstart/

**What did you see instead? Under which circumstances?**

https://v0-18-x.sdk.operatorframework.io/docs/golang/quickstart/ should work

**Environment**
* operator-sdk version:

* go version:  go1.14.3 linux/amd64

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

go

**Possible Solution**

**Additional context**

Issue is that all docs are useless if primary/basic example doesn't work

**Comment by peterducai** [comment]
building with version won't change anything:

$ RELEASE_VERSION=v0.18.2
$ make tidy
$ make install
$ operator-sdk version
operator-sdk version: "v0.18.0-76-g8d7c4f80", commit: "8d7c4f801348b95df2d0488dde0b4f70f88b8b4a", kubernetes version: "v1.18.2", go version: "go1.14.3 linux/amd64"

and you still get 0.18.0 instead of 0.18.2, so docs regarding 'building from source' should be fixed

**Comment by estroz** [comment]
@peterducai the version your seeing is a result of how we version the master branch: the master branch stays on the most recent minor release; the version string you see comes from `git describe --dirty --tags --always`. We have separate branches for each minor release so we can release patch versions. You'll notice that if you build the SDK from the v0.18.x branch you'll see
```sh
$ git describe --dirty --tags --always
v0.18.2-1-gfd3d1e48
```

The `RELEASE_VERSION` shell variable you're trying to use is only for expansion in the [download URLs](https://v0-18-x.sdk.operatorframework.io/docs/install-operator-sdk/#download-the-release-binary) used by `curl`, and can't be used in the way you are trying to.

As for your `--repo` question: you're building the SDK from master, which does not have the `--repo` flag available in `new` and has significant CLI changes. You should be using the master Golang quickstart: https://master.sdk.operatorframework.io/docs/golang/quickstart/.

Hope that helps!
