### ISSUE TITLE
Generate CSV with operand CRDs

### ISSUE THREAD

**Issue by Rulox** [operator-framework/operator-sdk#3325]
## Type of question

Sorry but I haven't found any information around this. General context question.

## Question

My operand has certain CRDs that I'd like the OLM to install before the operator runs. If I add all those CRDs manifests in the `deploy/crds` directory and I run `operator-sdk generate csv` I would expect all those crds to be added to the CSV under `owned` crds. However they're not. I believe this is necessary for the Operator to pass RH certification and also to make sure OLM installs those.

Am I missing anything here? or do I have to do this manually?

Thanks

**Environment**
operator-sdk version: "v0.15.1", commit: "e35ec7b722ba095e6438f63fafb9e7326870b486", go version: "go1.13.6 darwin/amd64"

crc version: 1.8.0+0a318dc
OpenShift version: 4.3.8 (embedded in binary)

**Comment by estroz** [comment]
@Rulox they should be added to `spec.customresourcedefinitions.owned`. Can you try running
```
$ operator-sdk generate csv --verbose --version=<your version> --update-crds
```
And posting the output? Thanks.

**Comment by Rulox** [comment]
Hi @estroz 

```
operator-sdk generate csv --verbose --csv-version=0.0.5 --update-crds
DEBU[0000] Debug logging is set                         
INFO[0000] Generating CSV manifest version 0.0.5        
INFO[0008] No kind type found for API k8s.nginx.org/v1alpha1, Kind=GlobalConfiguration. Skipping CSV annotation parsing for API. 
INFO[0021] No kind type found for API k8s.nginx.org/v1alpha1, Kind=TransportServer. Skipping CSV annotation parsing for API. 
INFO[0021] Directory for API k8s.nginx.org/v1, Kind=VirtualServerRoute does not exist. Skipping CSV annotation parsing for API. 
INFO[0021] Directory for API k8s.nginx.org/v1, Kind=VirtualServer does not exist. Skipping CSV annotation parsing for API. 
INFO[0021] Created deploy/olm-catalog/nginx-ingress-operator/0.0.5/nginx-ingress-operator.v0.0.5.clusterserviceversion.yaml 
```

It is a Go operator, this one https://github.com/nginxinc/nginx-ingress-operator.

I assumed those INFO messages had nothing to do with the fact that the CSV didn't add the CRDS. The generated directory is this one:
![image](https://user-images.githubusercontent.com/6643657/86347367-1b553600-bc56-11ea-9e70-ee1d049bbf01.png)


Which is fine, but the `spec.customresourcedefinitions.owned` only has my Operator CRD, not all the operand CRDs.

Is this because I'm using an old version of operator-sdk? (0.15) I wanted to use the latest, but there are a lot of changes that I will have to do in my `main.go` so I wanted to avoid this... I'll try to make it work and try again with 0.18

Appreciate the help, thanks.

**Comment by estroz** [comment]
There may be an issue with matching CRDs to API types in that particular SDK version, and is likely fixed in newer versions. Our [migration guide](https://sdk.operatorframework.io/docs/migration/version-upgrade-guide/) will help get your project up to the latest SDK version.

**Comment by Rulox** [comment]
Ok I'll try to migrate from 0.15 to 0.18, thanks

**Comment by Rulox** [comment]
@estroz 
With 0.18 I got:

```
operator-sdk generate csv --verbose --csv-version=0.0.5 --from-version=0.0.4 --update-crds --make-manifests=false 
DEBU[0000] Debug logging is set                         
INFO[0000] Generating CSV manifest version 0.0.5        
DEBU[0015] No kind type found for API k8s.nginx.org/v1alpha1, Kind=GlobalConfiguration. Skipping CSV annotation parsing for API. 
DEBU[0023] No kind type found for API k8s.nginx.org/v1alpha1, Kind=TransportServer. Skipping CSV annotation parsing for API. 
W0702 18:17:18.810700   62826 parse.go:246] Ignoring child directory pkg/apis/k8s: unable to import "pkg/apis/k8s": package pkg/apis/k8s is not in GOROOT (/usr/local/Cellar/go/1.14.4/libexec/src/pkg/apis/k8s)
W0702 18:17:18.901052   62826 parse.go:246] Ignoring child directory pkg/apis/k8s/v1alpha1: unable to import "pkg/apis/k8s/v1alpha1": package pkg/apis/k8s/v1alpha1 is not in GOROOT (/usr/local/Cellar/go/1.14.4/libexec/src/pkg/apis/k8s/v1alpha1)
FATA[0032] error generating CSV: error generating ClusterServiceVersion base metadata: failed to set CRD descriptors for k8s.nginx.org/v1, Kind=VirtualServer: no package found for v1 
```

I don't understand why `operator-sdk` is trying to import a package that doesn't exist (`k8s.nginx.org/v1` is one of the Operand CRDs, that's why the package is not available in the Operator src code). Am I doing anything wrong here?

Thanks

**Comment by estroz** [comment]
@Rulox what exactly do you mean by "operand CRDs"? Are these CRDs related to another operator, i.e. does your operator require another operator be present?

**Comment by Rulox** [comment]
No, with "operand" I mean the App that the operator installs.

The operator installs this (https://github.com/nginxinc/kubernetes-ingress) And this Ingress Controller has some CRDs. I want OLM to install these CRDs for me when the operator is installed. These CRDs are not part of the operator but part of the App that the operator deploys/manages.

Makes sense?

**Comment by estroz** [comment]
Ah I see what you're trying to do. Typically having one operator install another is not great practice, since OLM will do this for you if you specify that operator as a dependency via [`required` CRDs](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#required-crds) in your CSV.

**Comment by Rulox** [comment]
Well, is not really an operator, it's an application (an Ingress Controller). And that Ingress Controller can't be installed via OLM (again, is not an operator). I'm trying to make my Operator to do a 1 click install of the Ingress Controller (including their CRDs). What I had before was the Operator to register the CRDs using the k8s GO API, but I was told this is not a good practice.

In k8s-slack they told me the idea was to put those CRDs in the CSV, but I don't think this makes sense, I can't find an example of an Operator that manages an Application which uses their own CRDs, is this something crazy?

**Comment by estroz** [comment]
These would still be required CRDs since they're not owned by your operator; it is not recommended that your operator install CRDs. If setting these as `required` is still confusing/doesn't work, I recommend filing a support issue in the OLM repo to discuss your use case. Once you remove these CRDs from `deploy/crds`, the generator should work as documented.

**Comment by Rulox** [comment]
Ok thanks,

So bnasically @estroz , the CRDs must be installed manually in advance, is that correct? I'll follow up with OLM to discuss this. Thanks

**Comment by estroz** [comment]
I _think_ so, although OLM may be able to pull required CRDs from an existing catalog. Something to ask about in your OLM issue.

Feel free to keep this open until your OLM issue is resolved.
