### ISSUE TITLE
Support for supporting multiple kubernetes versions with your operator

### ISSUE THREAD

**Issue by zach-source** [operator-framework/operator-sdk#3328]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Yes. As kubernetes releases new functionality, the underlying APIs change and functionality is deprecated or modified. 

For instance, the CRD version changing from v1beta1 to v1 in version 1.19. Eventually all CRDs must be v1, so there could be a period where we have to support both before removing v1beta1.

Additionally, the APIs may change, or the GroupVersionKind of the resources our operator deploys.

**Describe the solution you'd like**
An ideal solution would handle these two scenarios: 
1. ClusterServiceVersion knows what version it is applicable for and OLM can deploy or not deploy that version if the underlying kubernetes does not match what the operator supports.
1. The operator can be built to handle all versions.

**Comment by zach-source** [comment]
Opening this because of the question I asked from the community call earlier today so we can discuss and follow up.
 
Happy to discuss and brainstorm potential directions.

**Comment by estroz** [comment]
We're going to leave this open as a placeholder for further discussion. This problem is non-trivial and therefore will require an [enhancement proposal](https://github.com/operator-framework/enhancements) be written and agreed upon.
