### ISSUE TITLE
Controller always reconcile on restart

### ISSUE THREAD

**Issue by kotyara85** [operator-framework/operator-sdk#3333]
Hello,
Is there a way to know that the object wasn't modified since last controller restart?
The scaffolding is reconciling everything on restart.
Thanks

**Comment by camilamacedo86** [comment]
Hi @kotyara85,

When you start the project the manager will trigger the reconcile and the solutions which are done with controllers/operators required to be idempotent which means that it would verify the current state of the resources and ensure that all is fine and then, finish succefully. Note that: 

- The reconcile will be trigged by default every 10 hours unless you change it.
- The reconcile will be trigged when any change in the resources watched by it be identified. (it is identified by the events raised )

Further details: 

**(Assuming that your project is Go)**

#### Watches

By default, you will find the watches for the Primary resources already implemented by each controller that you generated by using the SDK tool as follows. 

```go
// Watch for changes to primary resource Memcached
err = c.Watch(&source.Kind{Type: &cachev1alpha1.Memcached{}}, &handler.EnqueueRequestForObject{})
if err != nil {
    return err
}

```

However, note that in the example has watches implemented for each secondary object controlled/created by it. 

```go
// TODO(user): Modify this to be the types you create that are owned by the primary resource
// Watch for changes to secondary resource Pods and requeue the owner Memcached
err = c.Watch(&source.Kind{Type: &appsv1.Deployment{}}, &handler.EnqueueRequestForOwner{
    IsController: true,
    OwnerType:    &cachev1alpha1.Memcached{},
})
if err != nil {
    return err
}

err = c.Watch(&source.Kind{Type: &corev1.Service{}}, &handler.EnqueueRequestForOwner{
    IsController: true,
    OwnerType:    &cachev1alpha1.Memcached{},
})
if err != nil {
    return err
}
```

#### Reconcile trigged by the manager : (main.go)

If you do not change the following code that is created when you do a new project with the SDK then the Reconcile will be trigged every 10 hours.  

```go
	// Create a new Cmd to provide shared dependencies and start components
	mgr, err := manager.New(cfg, manager.Options{
		Namespace:          namespace,
		MapperProvider:     restmapper.NewDynamicRESTMapper,
		MetricsBindAddress: fmt.Sprintf("%s:%d", metricsHost, metricsPort),
	})
	if err != nil {
		log.Error(err, "")
		os.Exit(1)
	}

```
**Why does it happen? How do I know that?** 

See the Options Struct which is used to create the Manager of the operator project.  

```go
	// SyncPeriod determines the minimum frequency at which watched resources are
	// reconciled. A lower period will correct entropy more quickly, but reduce
	// responsiveness to change if there are many watched resources. Change this
	// value only if you know what you are doing. **Defaults to 10 hours if unset.**
	SyncPeriod *time.Duration
```

So, if you set 0 on this value the manager will not longer re-trigger the reconcile after each time. 

More info: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager?tab=doc#example-Manager-Start
Also, the [blog](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/) might help you get a better idea over how to work with it. 

**(Assuming that your project is Ansible or Helm)**

You can set up the `reconcilePeriod: 0s` in the watches.yaml file. You can find more about it the documentations in https://sdk.operatorframework.io/. 

Closing it as sorted out. However, please feel free to ping us and/or raise new issues.

**Comment by kotyara85** [comment]
@camilamacedo86 thank you for the docs.
I have another question, is there a way to transform the object before it pushed to Reconcile func? For example I want to clean status.
Thanks

**Comment by camilamacedo86** [comment]
Could you raise a new issue, please? Also, could you please provide further information for we are able to assist you better? PS. Sorry, but for me is not clear at all what you are trying to achieve.
