### ISSUE TITLE
Unable to create ansible operator image in v0.18.1

### ISSUE THREAD

**Issue by nataraj24** [operator-framework/operator-sdk#3335]
Trying to build ansible operator image and getting below error 
Step 3/6 : RUN ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible
 ---> Running in 221d81089b2f
to see the full traceback, use -vvv
ERROR! Unexpected Exception, this is probably a bug: [Errno 13] Permission denied: b'/opt/ansible/requirements.yml'
The command '/bin/sh -c ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible' returned a non-zero code: 250

**What did you do?**
operator-sdk build <image-name>

**What did you expect to see?**
image should be built without any error

**What did you see instead? Under which circumstances?**
Step 3/6 : RUN ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible
 ---> Running in 221d81089b2f
to see the full traceback, use -vvv
ERROR! Unexpected Exception, this is probably a bug: [Errno 13] Permission denied: b'/opt/ansible/requirements.yml'
The command '/bin/sh -c ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible' returned a non-zero code: 250

**Environment**
* operator-sdk version:
"v0.18.1", 

* go version:
"go1.13.6 linux/amd64"

* Kubernetes version information:

* Kubernetes cluster kind: 
aws eks
* Are you writing your operator in ansible, helm, or go?
ansible
**Possible Solution**

**Additional context**

**Comment by camilamacedo86** [comment]
Hi @nataraj24, 

Are you trying to upgrade your project from a previous version to 0.18.1? 

- If yes:

See that you might need to add and update the scaffolded files in your project. The `requirements.yaml`, for example, was added in the 0.16.0. I'd recommend you check the [migration guide](https://master.sdk.operatorframework.io/docs/migration/version-upgrade-guide). Also, see that from 0.18 release, we started to have a new file for each release. Check it [here](https://master.sdk.operatorframework.io/docs/migration/v0.18.0/).

Another option to upgrade your project can be; create a new one from scratch and compare your project with the new one to be able to identify the changes in the scaffold and what you need to add and/or update. From 0.17 to 0.18 see our [PR](https://github.com/operator-framework/operator-sdk-samples/pull/128) to upgrade the Ansible Memcached Sample, it might help you with it. 

- If not:

If you are facing this issue from scratch then it shows related to the permissions of the env and it a similar scenario of https://github.com/operator-framework/operator-sdk/issues/2648. Then see the comment: https://github.com/operator-framework/operator-sdk/issues/2648#issuecomment-604482681 for example.

Please, let us know if the above information helps you with. If not, could you please provide further details for we can better assist you such as; Are you upgrading a project or creating a new one from scratch? Are you able to face the same issue by just creating a project from scratch in your environment? What are the steps required to reproduce this issue?

**Comment by nataraj24** [comment]
Thank you Camila for your quick respone.  

i had upgraded operator-sdk to 1.18.2 and followed the comment mentioned in #2648.   still getting the same error

Step 1/6 : FROM quay.io/operator-framework/ansible-operator:v0.18.2
 ---> b0d150906bc9
Step 2/6 : COPY requirements.yml ${HOME}/requirements.yml
 ---> Using cache
 ---> bcfc97cfa007
Step 3/6 : RUN ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible  && ln -s ${HOME}/.ansible /.ansible
 ---> Running in acecf6bde656
to see the full traceback, use -vvv
ERROR! Unexpected Exception, this is probably a bug: [Errno 13] Permission denied: b'/opt/ansible/requirements.yml'
The command '/bin/sh -c ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible  && ln -s ${HOME}/.ansible /.ansible' returned a non-zero code: 250

**Comment by camilamacedo86** [comment]
HI @nataraj24, 

Could you please provide further details for we can better assist you such as; Are you upgrading a project or creating a new one from scratch? Are you able to face the same issue by just creating a project from scratch in your environment? What are the steps required to reproduce this issue?

**Comment by nataraj24** [comment]
Hi Camila

Below are steps i had followed.  i did it from scratch only. 

operator-sdk new <some-name> --api-version=fininfra.ansible-operator.com/v1 --kind=<Project-Name> --type=ansible --generate-playbook

it had created project structure.

i had edited roles/<project-name>/tasks/main.yaml with deployment definition.
post this ran
operator-sdk build <image-name>:<tag-name>
 
other than main.yaml i havent modified any of the scaffolded files which got created.  with this also its giving permission error.  with adding comment mentioned in #2648 also its giving permission error.

**Comment by camilamacedo86** [comment]
Hi @nataraj24, 

The error shows related to the permissions and your env `aws eks` such as https://github.com/operator-framework/operator-sdk/issues/2648. See:

> Permission denied: b'/opt/ansible/requirements.yml'
> The command '/bin/sh -c ansible-galaxy collection install -r ${HOME}/requirements.yml && chmod -R ug+rwx 
> ${HOME}/.ansible' returned a non-zero code: 250 

I would say that indeed is a duplicated of #2648 . Setting it as a bug. 

@fabianvf WDYT? any idea for workarounds here?

**Comment by nataraj24** [comment]
Hi @camilamacedo86 

Thank you once again for quick response.  i am facing this issue during operator build time.  

one small clarification required, does operator build depend kubernetes cluster?

Also let me know where i need to provide permissions.  

i am facing the problem with both sdk versions 1.18.1 and 1.18.2.  

any resolution / guidance would be of a great help

**Comment by camilamacedo86** [comment]
Hi @nataraj24, 

Are you saying that the problem faced is when you run `operator-sdk build` and not when you start to run the container? 
the `operators-sdk build` will run `docker build` which means that the docker has no access to these file in your local machine. What permissions your project files has? could you please run ` $ ls -la` and put here? Did you try to chmod the dir project?

**Comment by nataraj24** [comment]
Hi @camilamacedo86 

Thanks a lot for your guidance.  Thank you i had solved the issue.  

The issue was with permissions of the folder which operator-sdk creates.  After providing the execute permissions for other users of folder the operator image build went through.

**Comment by geerlingguy** [comment]
I just wanted to post that I'm seeing the same issue when I run a build inside a GitHub Actions workflow:

```
Step 2/5 : COPY requirements.yml ${HOME}/requirements.yml
 ---> 13a68a03a276
Step 3/5 : RUN ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible
 ---> Running in f638255a0585
to see the full traceback, use -vvv
ERROR! Unexpected Exception, this is probably a bug: [Errno 13] Permission denied: '/opt/ansible/requirements.yml'
```

I'm not quite sure why, though. I'm using Ansible to run the `operator-sdk` command and maybe a path is getting lost in translation here. The broken build is here: https://github.com/geerlingguy/operator-sdk-performance-testing/runs/865998658?check_suite_focus=true#step:6:161
