### ISSUE TITLE
certified images with operator-sdk build

### ISSUE THREAD

**Issue by ryandawsonuk** [operator-framework/operator-sdk#3340]
Producing RedHat-certified images requires a license.txt in the licenses directory and also certain mandatory labels. Can't see any way to tell "operator-sdk build" that I want to set these. I've created a new image using the image built from "operator-sdk build" as a base image but not clear to me if that's the intended route?

**Comment by estroz** [comment]
@ryandawsonuk if by "set" a `license.txt` and labels you mean add them to the built image, you can do so by adding them to the `build/Dockerfile` with `COPY` and `LABEL` directives.

**Comment by ryandawsonuk** [comment]
Just realised I didn't explain this very well. I am indeed [adding in to the built image](https://github.com/SeldonIO/seldon-deploy-operator/blob/6c5bb4ac4e12191b908515ee52987c8d485f9a8d/Dockerfile.certified#L10) by building on top of it. What I was suggesting is that it would be good if the `[operator-sdk build](https://github.com/SeldonIO/seldon-deploy-operator/blob/6c5bb4ac4e12191b908515ee52987c8d485f9a8d/Makefile#L10)` command could support options to add at that point.

**Comment by joelanford** [comment]
@ryandawsonuk I'm going to close this because the `operator-sdk build` command was removed in 1.0.0. Its replacement is the `docker-build` target in the Makefile that is scaffolded by `operator-sdk init`, which you can tweak with your desired image builder, flags, etc.
