### ISSUE TITLE
Is there a plan to further refactor Helm Operator references of "update" to "upgrade"?

### ISSUE THREAD

**Issue by mikeshng** [operator-framework/operator-sdk#3346]
## Type of question

Based on https://github.com/operator-framework/operator-sdk/pull/3269 and https://github.com/operator-framework/operator-sdk/pull/3345 , the Helm Operator start using the verb `Upgrade` instead of `Update`.

Is there a plan to global refactor/rename from `Update` to `Upgrade` for all the relevant code under the `operator-sdk/pkg/helm/` package tree? 

## Question

**What did you do?**

There are a lot of mentions of `Update` instead of `Upgrade` currently under `operator-sdk/pkg/helm/` package.
For example, log entries `log.Info("Updated release", "force", force)`, function name `IsUpdateRequired` etc etc.

**What did you expect to see?**
All the relevant `Update` references rename to `Upgrade` for example:
```
type UpdateOption func(*action.Upgrade) error
```
to
```
type UpgradeOption func(*action.Upgrade) error
```

**What did you see instead? Under which circumstances?**
I see Update instead of Upgrade being used.

**Environment**
* operator-sdk version:

master branch

* Kubernetes version information:

Not relevant

* Kubernetes cluster kind: 

Not relevant

FYI @camilamacedo86

**Comment by camilamacedo86** [comment]
Add : https://github.com/operator-framework/operator-sdk/pull/3404

**Comment by camilamacedo86** [comment]
Closing it since all was done and merged. 
Thank you for the collab. 👍
