### ISSUE TITLE
Remove the code that generate the metrics for the new layout projects

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3354]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, we generate the metrics in the run.go(for the main). See: https://github.com/operator-framework/operator-sdk/blob/master/pkg/helm/run.go#L166

However, for the new layout, the metrics are customized. See that we scaffold a service monitor resource in ./config/prometheus/monitor.yaml. 

**Describe the solution you'd like**
- Remove the roles added for it in internal/plugins/helm/v1/scaffolds/templates/role.go
- Replace the metrics impl from the image used by the new layout to be done as: https://github.com/joelanford/helm-operator/commit/a9bcf842bcc3e4005217e807a58ccd33f3d82bd0
- The main.go added in the https://github.com/operator-framework/operator-sdk/pull/3331 also needs to be updated

**Comment by camilamacedo86** [comment]
Following what I can think about that need to get done here; 

- remove add metrics impl from ansible and helm
- remove the pkg/kube-metrics
- remove what is not longer used from pkg/k8sutil
- check if we have nothing about it to remove from the docs as well

**Comment by estroz** [comment]
@camilamacedo86 I believe this is done. Please re-open if not.

**Comment by camilamacedo86** [comment]
/reopen 

It is not. See that we still need to remove the funcs that were used just in these features in https://github.com/operator-framework/operator-sdk/blob/master/internal/util/k8sutil/k8sutil.go

**Comment by camilamacedo86** [comment]
HI @estroz and @bharathi-tenneti, 
  
After we merge the https://github.com/operator-framework/operator-sdk/pull/3513 we can close this one.
