### ISSUE TITLE
deprecate the flag --max-worker and replace it for max-concurrent-reconciles and use the num of CPU as default value.  

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3360]
The `--max-workers` flag does not align well with the name of the option it configures on the controllers and the new layout. So, we need to deprecate the flag --max-worker and replace it for max-concurrent-reconciles. Also, note the default size should `runtime.NumCPU()`.

Note that we need to update the implementation in `cmd/helm|ansible-operator/main.go` which is used to generate bin. See: https://github.com/operator-framework/operator-sdk/pull/3331

Example:

```go
	//   (MaxConcurrentReconciles). Flag `--max-concurrent-reconciles` should be used instead.
	pflag.IntVar(&defaultMaxWorkers, "max-workers", runtime.NumCPU(), "Default maximum number of concurrent reconciles for controllers.")
	if err := pflag.CommandLine.MarkHidden("max-workers"); err != nil {
		setupLog.Error(err, "failed to hide --max-workers flag")
		os.Exit(1)
	}

....

	// Deprecated: --max-workers flag does not align well with the name of the option it configures on the controller
	//   (MaxConcurrentReconciles). Flag `--max-concurrent-reconciles` should be used instead.
	if pflag.Lookup("max-workers").Changed {
		setupLog.Info("flag --max-workers has been deprecated, use --max-concurrent-reconciles instead")
		if pflag.Lookup("max-concurrent-reconciles").Changed {
			setupLog.Info("ignoring --max-workers since --max-concurrent-reconciles is set")
		} else {
			defaultMaxConcurrentReconciles = defaultMaxWorkers
		}
	}

...

**Comment by tengqm** [comment]
This can be closed?

**Comment by camilamacedo86** [comment]
Hi @tengqm, 

it cannot be closed yet. This need was addressed by @varshaprasad96 for Ansible in https://github.com/operator-framework/operator-sdk/pull/3435 but we still requering to do the same for Helm.

**Comment by varshaprasad96** [comment]
PR for modifications in ansible: https://github.com/operator-framework/operator-sdk/pull/3435 (closed)
PR for modifications in helm:  https://github.com/operator-framework/operator-sdk/pull/3452

**Comment by camilamacedo86** [comment]
Just to register, after a discussion, was decide we no longer support --max-worker for 1.0.0.

**Comment by tengqm** [comment]
my bad. the prs are still under review.

**Comment by camilamacedo86** [comment]
hi @tengqm,
 
All fine, btw really tks for your contributions. 🥇
