### ISSUE TITLE
deprecate OPERATOR_NAME environment variable

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3361]
We need to deprecate: OPERATOR_NAME environment variable is an artifact of the legacy operator-sdk project scaffolding and use `--leader-election-id` should be used instead.

- Note that we need to update the implementation in cmd/helm|ansible-operator/main.go which is used to generate bin. See: #3331 and also the scaffolds. 
- Ensure that the plugins scaffolds are no longer using the OperatorName env var as well.  

The OperatorName is the name of the directory of the operator by default which in go we set the info in the repo attribute in the PROJECT file. However, if we will or not use the repo for Ansible/Helm is an ongoing discussion. See:   https://github.com/operator-framework/operator-sdk/pull/3341#issuecomment-654457871

Example: 

```go
	if operatorName, found := os.LookupEnv("OPERATOR_NAME"); found {
		setupLog.Info("environment variable OPERATOR_NAME has been deprecated, use --leader-election-id instead.")
		if pflag.Lookup("leader-election-id").Changed {
			setupLog.Info("ignoring OPERATOR_NAME environment variable since --leader-election-id is set")
		} else {
			leaderElectionID = operatorName
		}
	}

	options := ctrl.Options{
		MetricsBindAddress:      metricsAddr,
		LeaderElection:          enableLeaderElection,
		LeaderElectionID:        leaderElectionID,
		LeaderElectionNamespace: leaderElectionNamespace,
		NewClient:               manager.NewDelegatingClientFunc(),
	}
```

**Comment by estroz** [comment]
This is done, but there are still a bunch of references to this in testdata.

**Comment by camilamacedo86** [comment]
Hi @estroz, 

IMO this can be closed with https://github.com/operator-framework/operator-sdk/pull/3539
then, we need a new issue to Port the Ansible Molecule tests for the new layout since the env can just be found in these tests.
