### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by aliciafmachado** [operator-framework/operator-sdk#3366]
## Bug Report

Not sure if this should be reported as a bug but anyway:

The documentation is out of date here: https://sdk.operatorframework.io/docs/golang/quickstart/#2-run-locally-outside-the-cluster

The command "operator-sdk run local --watch-namespace=default" should be "operator-sdk run --local --namespace=default".

Just that :)

**Comment by aliciafmachado** [comment]
Here as well: https://sdk.operatorframework.io/docs/golang/quickstart/#create-a-memcached-cr

There's a ">" missing after cat, no?

**Comment by camilamacedo86** [comment]
Hi @aliciafmachado, 

The docs view by. the default is related to the master branch. You are probably using an sdk released version. See that you can choose the specific version to check its docs: 

<img width="370" alt="Screenshot 2020-07-09 at 13 24 23" src="https://user-images.githubusercontent.com/7708031/87039741-89b26f00-c1e7-11ea-97c2-193b3b640c0b.png">

So,  I am closing this one. However, please feel free to raise new questions/issues if you see any problem related the version that you are using as contribute with the project by doing pull requests to update/fix its docs as well.
