### ISSUE TITLE
Does the latest release of the helm-operator use helm 3.2.4?

### ISSUE THREAD

**Issue by the-scott-hand** [operator-framework/operator-sdk#3368]
I can only find notes saying using 3.2.0, wanted to see if this security patch has been adopted yet, and if not in what release will it be in?
"Helm v3.2.4 is the fourth patch release for v3.2, patching a security vulnerability found in Helm's HTTP plugin installer affecting all versions of Helm 3 prior to Helm 3.2.4. Users are encouraged to upgrade to receive the patch."
https://github.com/helm/helm/security/advisories/GHSA-qq3j-xp49-j73f

Thanks!

**Comment by camilamacedo86** [comment]
Hi @the-scott-hand,

The master branch is using Helm 3.2.4 and it will be available to the next released which are planning to do very soon. 
See; https://github.com/operator-framework/operator-sdk/commit/8d7c4f801348b95df2d0488dde0b4f70f88b8b4a

Closing ti as sorted out.
