### ISSUE TITLE
install db clients in operator using rpm -i

### ISSUE THREAD

**Issue by nataraj24** [operator-framework/operator-sdk#3377]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
General Query about installing database clients into application operator image using rpm

## Question

**What did you do?**
Can we install database clients like psql, sqlplus into operator using rpm.  Currently its giving below error when doing operator build
Sending build context to Docker daemon  65.01MB
Step 1/10 : FROM quay.io/operator-framework/ansible-operator:v0.18.2
 ---> b0d150906bc9
Step 2/10 : COPY rpm/ /tmp
 ---> Using cache
 ---> e9390ea3a452
Step 3/10 : RUN rpm -i /tmp/libaio-0.3.107-10.el6.x86_64.rpm
 ---> Running in 2925f5bacbaa
warning: /tmp/libaio-0.3.107-10.el6.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID c105b9de: NOKEY
error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)
The command '/bin/sh -c rpm -i /tmp/libaio-0.3.107-10.el6.x86_64.rpm' returned a non-zero code: 1

**What did you expect to see?**
operator build should go through

**What did you see instead? Under which circumstances?**
error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)

**Environment**
* operator-sdk version: 

operator-sdk version: "v0.18.2",  go version: "go1.13.10 linux/amd64"

  insert release or Git SHA here: commit: "f059b5e17447b0bbcef50846859519340c17ffad"

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: AWS EKS

**Additional context**
Add any other context about the question here.

**Comment by jmrodri** [comment]
@nataraj24 It looks like you are trying to install an rpm as a non-root user. See if this FAQ helps with your problem: https://sdk.operatorframework.io/docs/faq/#my-ansible-module-is-missing-a-dependency-how-do-i-add-it-to-the-image

**Comment by nataraj24** [comment]
Thank you @jmrodri for the information.  it has help me installing the clients into the image.
