### ISSUE TITLE
Throw error if CRD spec contains unknown fields

### ISSUE THREAD

**Issue by harjas27** [operator-framework/operator-sdk#3378]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The client.Client does not throw any error when Get is called and the specification of the custom resource object contains an unknown field.

**Describe the solution you'd like**
Since the CRD already contains OpenAPIV3Schema, the client.Client can validate the specification of the custom resource object against that.

**Comment by camilamacedo86** [comment]
This feature request shows not be part of the SDK domain. Could you please raise it in the https://github.com/kubernetes-sigs/controller-runtime which is responsible and holds the controller implementation and is the project who provides the client?

I am closing this one. however, feel free to ping us if you think that it should be re-opened for any reason.
