### ISSUE TITLE
non-AMD releases of operator-sdk do not seem to behave the same as AMD release

### ISSUE THREAD

**Issue by jmazzitelli** [operator-framework/operator-sdk#3379]
Can someone check both the arm64 and ppc64le releases of operator-sdk for correctness? Specifically, I'm using [0.17.0 from here](https://github.com/operator-framework/operator-sdk/releases/tag/v0.17.0) and those two arch builds fail to validate the exact same CSV that the amd release pass (and I know the CSV is OK - should pass on all arches). Note that this is attempting to validate a manifest that is using the "new bundle format" (this is why travis is not using `operator-courier`, but instead is using `operator-sdk validate`).

My question is - is this behavior correct? Or is there something wrong with the SDK on those two arches?

Here's the details:

Take a look at the [Kiali operator's travis builds here](https://github.com/kiali/kiali-operator/pull/72/checks?check_run_id=857200739). Notice one passed (that's the amd one) but two fail (the arm64 and ppc64le ones).

Here are the logs for the [passing amd build](https://travis-ci.com/github/kiali/kiali-operator/jobs/359634585#L294)
Here are the logs for the [failing arm64 build](https://travis-ci.com/github/kiali/kiali-operator/jobs/359634586#L189)
Here are the logs for the [failing ppc64le build](https://travis-ci.com/github/kiali/kiali-operator/jobs/359634587#L187)

Each build utilizes the same Makefile to download operator-sdk and run "validate" on the same CSV yaml. [The Makefile downloads the SDK here](https://github.com/kiali/kiali-operator/blob/v1.20.0/Makefile#L40) - it is just this command:

```
curl -L https://github.com/operator-framework/operator-sdk/releases/download/v0.17.0/operator-sdk-v0.17.0-$$(uname -m)-linux-gnu > "${OUTDIR}/operator-sdk-install/operator-sdk" ;\
```

Looking at the three travis build logs, notice that they are all downloading the correct 0.17.0 version for the particular arch needed - the travis builds run `operator-sdk version` and here is what they say for each arch build:

* the successful amd build: `operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "unknown", go version: "go1.13.10 linux/amd64"`
* the failed arm64 build: `operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "unknown", go version: "go1.13.10 linux/arm64"`
* the failed ppc64le build: `operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "unknown", go version: "go1.13.10 linux/ppc64le"`

They are all 0.17.0 with the same commit and the go version shows the correct arch for each.

The arm and ppc builds fail to validate the CSV, but the amd build successfully validates the same CSV. Here's [the CSV](https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml) that is getting validated (note: travis [passes in the proper env vars](https://github.com/kiali/kiali-operator/blob/master/.travis.yml#L49) that get replaced via envsubst. You can see travis doing it for all three builds [here](https://travis-ci.com/github/kiali/kiali-operator/jobs/359634585#L296), [here](https://travis-ci.com/github/kiali/kiali-operator/jobs/359634586#L246), and [here](https://travis-ci.com/github/kiali/kiali-operator/jobs/359634587#L247)). Here, also, is the [metadata/annotations.yaml file](https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-ossm/metadata/annotations.yaml) (this becomes important later).

Each travis run of "operator-sdk validate" are:

* amd results in `operator-sdk validate` exiting [with result code 0](https://travis-ci.com/github/kiali/kiali-operator/jobs/359634585#L315)
* arm64 results in `operator-sdk validate` exiting [with result code 1](https://travis-ci.com/github/kiali/kiali-operator/jobs/359634586#L262)
* ppc64le results in `operator-sdk validate` exiting [with result code 1](https://travis-ci.com/github/kiali/kiali-operator/jobs/359634587#L263)

So the amd build succeeds - and take note of [this log message](https://travis-ci.com/github/kiali/kiali-operator/jobs/359634585#L309) from that run:

```
DEBU[0000] Found annotation "operators.operatorframework.io.bundle.mediatype.v1" with value "registry+v1"  bundle-dir=/home/travis/build/kiali/kiali-operator/manifests/kiali-ossm
```

So, it passes validation for that value of mediatpe.v1 of "registry+v1" found in the [annotations.yaml](https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-ossm/metadata/annotations.yaml#L5).

But look at the log messages for the [arm64](https://travis-ci.com/github/kiali/kiali-operator/jobs/359634586#L261) and [ppc64le](https://travis-ci.com/github/kiali/kiali-operator/jobs/359634587#L262) builds for that same line in annotations.yaml - they both fail with the same error message:

```
time="2020-07-10T08:23:45Z" level=fatal msg="Bundle format validation failed: Bundle validation errors: Expecting annotation \"operators.operatorframework.io.bundle.mediatype.v1\" to have value \"plain\" instead of \"registry+v1\"" bundle-dir=/home/travis/build/kiali/kiali-operator/manifests/kiali-ossm
```

Why does the SDK pass validation on amd arch, but fail validation on arm64 and ppc64le when the metadata is exactly the same for all three builds?

**Comment by joelanford** [comment]
Seems like the problem could be that the arm and ppc travis VMs don't have `envsubst` installed in them (see https://travis-ci.com/github/kiali/kiali-operator/jobs/359634586#L247).

I was not able to reproduce this issue with v0.17.0 (and newer) on a raspberry pi 4.
