### ISSUE TITLE
Ansible: How to read status properties from custom resource?

### ISSUE THREAD

**Issue by ploef** [operator-framework/operator-sdk#3386]
operator-sdk version: "v0.18.2", 
kubernetes version: "v1.18.2", 
go version: "go1.14.4 darwin/amd64"

Hi,
I know that I can use the k8s_status module to set the status of a custom resource. But is there any way to read those status properties?

Kind Regards,
Peter

**Comment by camilamacedo86** [comment]
Hi @ploef, 

It is described in the doc: https://sdk.operatorframework.io/docs/ansible/development-tips/#custom-resource-status-management

Closing this one as sorted out. However, feel free to ping us to re-open or if you have other questions please feel free to raise a new issue. I'd recommend 1 topic/questions per issue. Thank you.

**Comment by ploef** [comment]
Hi @camilamacedo86,

Thanks for the quick response! Unfortunately the documentation does explain how to set/update the status but I can't find anything about reading the status. The spec section will be available as extra vars but that seems not the case for the status section. Of course it's also possible that I'm not reading the documentation correctly. :-D

**Comment by ploef** [comment]
Found it!

**Comment by camilamacedo86** [comment]
Oh great. thank you for let me know 👍

**Comment by memelet** [comment]
Found it where? How can ansible access/read the status?
