### ISSUE TITLE
Provide Metrics list

### ISSUE THREAD

**Issue by mattmahoneyrh** [operator-framework/operator-sdk#3387]
Provide documented list of standard metrics emitted by operator SDK.

**Comment by jmazzitelli** [comment]
For the record, the list of metrics that should be documented for ansible operators should be something like this (this is just me looking at kiali's operator metrics - all of which come directly from the ansible operator SDK 0.17.0):

Prometheus query: "{namespace="kiali-operator",app="kiali-operator"}"

```
ansible_operator_reconciles_bucket
ansible_operator_reconciles_count
ansible_operator_reconciles_sum
go_gc_duration_seconds
go_gc_duration_seconds_count
go_gc_duration_seconds_sum
go_goroutines
go_info
go_memstats_alloc_bytes
go_memstats_alloc_bytes_total
go_memstats_buck_hash_sys_bytes
go_memstats_frees_total
go_memstats_gc_cpu_fraction
go_memstats_gc_sys_bytes
go_memstats_heap_alloc_bytes
go_memstats_heap_idle_bytes
go_memstats_heap_inuse_bytes
go_memstats_heap_objects
go_memstats_heap_released_bytes
go_memstats_heap_sys_bytes
go_memstats_last_gc_time_seconds
go_memstats_lookups_total
go_memstats_mallocs_total
go_memstats_mcache_inuse_bytes
go_memstats_mcache_sys_bytes
go_memstats_mspan_inuse_bytes
go_memstats_mspan_sys_bytes
go_memstats_next_gc_bytes
go_memstats_other_sys_bytes
go_memstats_stack_inuse_bytes
go_memstats_stack_sys_bytes
go_memstats_sys_bytes
go_threads
kiali_info
process_cpu_seconds_total
process_max_fds
process_open_fds
process_resident_memory_bytes
process_start_time_seconds
process_virtual_memory_bytes
process_virtual_memory_max_bytes
rest_client_request_latency_seconds_bucket
rest_client_request_latency_seconds_count
rest_client_request_latency_seconds_sum
rest_client_requests_total
scrape_duration_seconds
scrape_samples_post_metric_relabeling
scrape_samples_scraped
scrape_series_added
up
workqueue_adds_total
workqueue_depth
workqueue_longest_running_processor_seconds
workqueue_queue_duration_seconds_bucket
workqueue_queue_duration_seconds_count
workqueue_queue_duration_seconds_sum
workqueue_retries_total
workqueue_unfinished_work_seconds
workqueue_work_duration_seconds_bucket
workqueue_work_duration_seconds_count
workqueue_work_duration_seconds_sum
```

**Comment by jmazzitelli** [comment]
/remove-lifecycle stale

IMO, this should be documented somewhere - otherwise, why expose metrics? As my old boss told me, "If it isn't documented, it doesn't exist" :) These metrics can be helpful to track performance issues in operators, but it would be nice to know WHAT ever metrics there is and WHAT they actually measure.

**Comment by estroz** [comment]
@jmazzitelli these metrics first need to be documented in https://github.com/kubernetes-sigs/controller-runtime/tree/master/pkg/metrics, then SDK docs can simply point to these docs since no extra metrics are added on top of that set. Can you create an issue in controller-runtime to do so?

**Comment by jmazzitelli** [comment]
What then are these? I thought these are SDK-specific, no?
```
workqueue_adds_total
workqueue_depth
workqueue_longest_running_processor_seconds
workqueue_queue_duration_seconds_bucket
workqueue_queue_duration_seconds_count
workqueue_queue_duration_seconds_sum
workqueue_retries_total
workqueue_unfinished_work_seconds
workqueue_work_duration_seconds_bucket
workqueue_work_duration_seconds_count
workqueue_work_duration_seconds_sum
```

**Comment by jmazzitelli** [comment]
> @jmazzitelli these metrics first need to be documented in https://github.com/kubernetes-sigs/controller-runtime/tree/master/pkg/metrics, then SDK docs can simply point to these docs since no extra metrics are added on top of that set. Can you create an issue in controller-runtime to do so?

Looks like there was already a PR - see "document exposed metrics" PR: https://github.com/kubernetes-sigs/controller-runtime/pull/811

**Comment by estroz** [comment]
>Though I don't know how it helps the operator author - what are the "workqueues" used for in the operator SDK? I understand a workqueue in general, but from the operator perspective, what is the SDK using workqueues for? What do these metrics tell the operator user?

These are all controller-relevant metrics, which is why I suggested they be documented in controller-runtime. https://github.com/kubernetes-sigs/controller-runtime/pull/811 doesn't seem to actually document any metrics, rather it adds descriptions to them at runtime.

The following are set up by the ansible-operator (and helm-operator) internally, and so should be discussed in SDK docs:

```
ansible_operator_reconciles_bucket
ansible_operator_reconciles_count
ansible_operator_reconciles_sum
kiali_info
```

/language ansible
/language helm
