### ISSUE TITLE
Watcher - Create

### ISSUE THREAD

**Issue by kotyara85** [operator-framework/operator-sdk#3389]
After the controller restarted it will automatically run createfunc an call reconcile function.
Is there a way to know if the object was changed when controller was down?
Similar to UpdateFunc which has old & new objects.
Thank you

**Comment by camilamacedo86** [comment]
Hi @kotyara85, 

Your question shows a duplicate of https://github.com/operator-framework/operator-sdk/issues/2506. See the comment https://github.com/operator-framework/operator-sdk/issues/2506#issuecomment-583460961. 

Closing it as sorted out. However, feel free to ping us if you think that it should be re-opened and/or to raise new issues/questions.
