### ISSUE TITLE
Creating a ConfigMap with an external file

### ISSUE THREAD

**Issue by iboware** [operator-framework/operator-sdk#3393]
## Type of question
Best Practice

## Question
I am trying to create a ConfigMap, which will be mounted as a Volume and containing a bash file. 
**What did you do?**
I read the bash file with this command from project directory: `preStop, err := ioutil.ReadFile("scripts/pre-stop.sh")` It runs when I run locally, but for example when I use Delve to debug my code the file cannot be found. I am new in Go language, so I don't know the best practice to include a file into my operator.

**What did you expect to see?**
I expect to embed that bash file into my operator, so whenever I create that ConfigMap it will work without problem.

**What did you see instead? Under which circumstances?**
The file cannot be found sometimes.

**Environment**
* operator-sdk version:
version: "v0.18.1", commit: "7bf7b6886d647dc202525daec16fab67dcc52a3d",

* Kubernetes version information:

v1.18.2

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by kensipe** [comment]
@iboware happy to help... this seems less an issue with operator-sdk and more a getting started question.  if you are on https://k8s.slack.com/ hit me up (kensipe) for more help...

It sounds like the file is local and is not copied into a container when running in a pod...  or the PV mappings for the configmap are not correct.    

I'm needing more information to help... if you have a docker image (the Dockerfile could help).  The k8s manifests file is likely helpful.    

You indicate that this works "sometimes"... is it the case that it works locally but not inside a container?

**Comment by iboware** [comment]
Hi @kensipe, thanks. I don't have a docker image, doing local only development for now. 

My code is here, so you can see what I am trying to do: 
https://github.com/iboware/postgres-operator/blob/master/pkg/postgresql/configMap.go

What I meant by "sometimes" is, when I execute operator with `operator-framework run local` it can find the path but when I run it with Delve and try to debug it on VS Code, it cannot find the path.

My main question is what is the best practice to create a ConfigMap from a static file in operator-framework? Where should I store those static files?

**Comment by joelanford** [comment]
@iboware One option would be to embed the full text of the script in your `configMap.go` file like this:

```go
func NewConfigMapForCR() { ... }

const preStop = `#!/bin/bash
# Put your script below
# You can keep adding lines...
# And more lines...
# Everything between the single backticks is a multi-line string...
ls
echo "hello, world"
# etc...
`
```

And then instead of loading `preStop` from file on disk, it's compiled into your operator's code.

**Comment by camilamacedo86** [comment]
If I understood your problem, you might to also solved it by the Dockerfile. See that for helm/ansible we copy the watches files to the container. Example:

```
COPY myfile.yaml ${HOME}/myfile.yaml
```

**Comment by iboware** [comment]
Thank you all for your answers. I think the best solution for my problem is what @camilamacedo86 suggests.

**Comment by camilamacedo86** [comment]
Hi @iboware, 

Thank you for let us know. I am closing this one since it is sorted out, however, please feel free to raise new issues.
