### ISSUE TITLE
Broken Migration Link

### ISSUE THREAD

**Issue by deepak1725** [operator-framework/operator-sdk#3394]
## Bug Report
![cli_issue](https://user-images.githubusercontent.com/21026016/87241856-bc0cd800-c444-11ea-83d2-f57eafbdc618.png)

Link hits 404. (Doesn't Exist)

**What did you do?**
Migrated from operator-sdk v0.17 to v.19 (latest)

**What did you expect to see?**
https://sdk.operatorframework.io/docs/golang/project_migration_guide/

**What did you see instead? Under which circumstances?**

https://sdk.operatorframework.io/docs/golang/migration/project_migration_guide/

**Environment**
* operator-sdk version:

operator-sdk version: "v0.19.0", commit: "8e28aca60994c5cb1aec0251b85f0116cc4c9427", kubernetes version: "v1.18.2", go version: "go1.13.10 linux/amd64"

* go version:

go version go1.13.3 linux/amd64

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
Minikube

* Are you writing your operator in ansible, helm, or go?
Go

**Possible Solution**
Fix here 
https://github.com/operator-framework/operator-sdk/blob/87a7a6f318d0bc52e12fb8a1419460c1fab92c55/cmd/operator-sdk/main.go#L51

**Additional context**

**Comment by camilamacedo86** [comment]
Hi @deepak1725, 

The link is: https://sdk.operatorframework.io/docs/golang/project_migration_guide/. 

I will not recommend you raise a PR to change it against the master because we have the PR https://github.com/operator-framework/operator-sdk/pull/3382 which will organize the docs and then, it will change again. 

Closing it as sorted out.
