### ISSUE TITLE
Invalid Command in Doc

### ISSUE THREAD

**Issue by deepak1725** [operator-framework/operator-sdk#3396]
## Bug Report

Command in Migration Docs is not valid
https://sdk.operatorframework.io/docs/golang/project_migration_guide/#create-an-api

**What did you do?**
`operator-sdk api --group cache --version v1alpha1 --kind Memcached`

**What did you expect to see?**
Scaffold API Code 

**What did you see instead? Under which circumstances?**
![api_error](https://user-images.githubusercontent.com/21026016/87243395-5ecc5300-c453-11ea-9bc4-d385632d3feb.png)

**Environment**
* operator-sdk version:

operator-sdk version: "v0.19.0", commit: "8e28aca60994c5cb1aec0251b85f0116cc4c9427", kubernetes version: "v1.18.2", go version: "go1.13.10 linux/amd64"

* go version:

1.13

* Kubernetes version information:

1.18
* Kubernetes cluster kind: 
minikube
* Are you writing your operator in ansible, helm, or go?
go
**Possible Solution**

**Additional context**

**Comment by camilamacedo86** [comment]
The command is `operator-sdk create api`. Could you collab with by raising a PR against the master to fix it in the doc?

**Comment by camilamacedo86** [comment]
Done a PR: https://github.com/operator-framework/operator-sdk/pull/3399

**Comment by deepak1725** [comment]
Thanks @camilamacedo86 :)

**Comment by deepak1725** [comment]
@camilamacedo86 This Bug reappeared

**Comment by camilamacedo86** [comment]
hi @deepak1725, 

We did big changes in the. docs. It was lost in the rebases. I will check it and see if we do not lose any other change in this doc tks for raise it.

**Comment by camilamacedo86** [comment]
Hi @deepak1725. 

I. checked and the fix is there. See that the website shows by default the docs of the latest release (0.19). Our fix is done in the master, so you need to change to check the master version:

<img width="298" alt="Screenshot 2020-07-19 at 09 45 26" src="https://user-images.githubusercontent.com/7708031/87870961-9b90d080-c9a4-11ea-8a9f-92174c0273cf.png">


See: https://master.sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/

**Comment by deepak1725** [comment]
@camilamacedo86 How soon can we see it in 0.19.

I think it is valid for v0.19.. right..?

**Comment by camilamacedo86** [comment]
Hi @deepak1725, 
 
We make a big refacto

**Comment by camilamacedo86** [comment]
It will be closed with the merge of doc: apply small fixes perform on master on to the migration guide (0.19) #3516

**Comment by camilamacedo86** [comment]
done 👍

**Comment by deepak1725** [comment]
Thanks :)
