### ISSUE TITLE
Reconciliation interval & timeout

### ISSUE THREAD

**Issue by kotyara85** [operator-framework/operator-sdk#3397]
Hello,
Is there a way to specify reconciliation interval and number of attempts or Reconciliation function returns err?
Thank you

**Comment by camilamacedo86** [comment]
HI @kotyara85, 

It is recommended to develop idempotent solutions. See:

> Reconcile()

> The reconcile function is responsible for synchronizing the resources and their specifications according to the business logic implemented on them. In this way, it works like a loop, and it does not stop until all conditionals match its implementation. The following is pseudo-code with an example that clarifies it.

```go
reconcile App {

   // Check if a Deployment for the app exists, if not create one
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   } 
   
   // Check if a Service for the app exists, if not create one 
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   }  

   // Looking for Database CR/CRD 
   // Check the Database Deployments Replicas size
   // If deployment.replicas size != cr.size, then update it
   // Then, go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{Requeue: true}, nil
   }  
   ...
   
   // If it is at the end of the loop, then:
   // All was done successfully and the reconcile can stop  
   return reconcile.Result{}, nil

}
```

> The following are possible return options to restart the Reconcile:
>
> - With the error:
return reconcile.Result{}, err
>
>- Without an error:
>return reconcile.Result{Requeue: true}, nil
>
>- Therefore, to stop the Reconcile, use:
>return reconcile.Result{}, nil
> 
> Note: For more details, check the Reconcile and its Result [implementations](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/reconcile).
From: https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/

Also, see that you can use `result.Result{RequeueAfter: resyncPeriod}, nil` to retrigger the reconcile after X time. And then, note as well that the reconcile is re-trigged by the Watch features when some event of change is raised in a resource observed and by the manager with the sync period of 10 hours by default. For more info: https://github.com/operator-framework/operator-sdk/issues/1906#issuecomment-530822493.

I am closing this one as sorted out. However, please feel free to raise a new issue and I'd like to kindly ask for you fill the template for we know the type of operator and versions used and be able to help you more assertively as possible.

**Comment by ngiii** [comment]
Hi, @camilamacedo86 
regarding
```
And then, note as well that the reconcile is re-trigged by the Watch features when some event of change is raised in a resource observed and by the manager with the sync period of 10 hours by default. For more info: #1906 (comment).
``` 
just want to confirm that does that mean even there is no change in CR, the reconcile will be re-trigged by manager every 10 hours by default?
Thank you!
