### ISSUE TITLE
migration guide cites invalid golang version

### ISSUE THREAD

**Issue by mhrivnak** [operator-framework/operator-sdk#3400]
## Bug Report

**What did you do?**
I read the [migration guide](https://sdk.operatorframework.io/docs/golang/project_migration_guide/)

**What did you expect to see?**
A prerequisite golang version that exists.

**What did you see instead? Under which circumstances?**
Under [Prerequisites](https://github.com/operator-framework/operator-sdk/blob/87a7a6f/website/content/en/docs/golang/project_migration_guide.md#prerequisites): `go version 17.03+.`

**Possible Solution**
Maybe you meant 1.13 or 1.14?

**Comment by camilamacedo86** [comment]
The version is 1.13.
