### ISSUE TITLE
Update CR status field with values from pod output in GO

### ISSUE THREAD

**Issue by raghu017** [operator-framework/operator-sdk#3410]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
Help around operator-sdk

## Question
How can  controller update CR's status fields based on results from CR's pod?

**What did you do?**
I have a CR that has a Job with a pod. CR has a Status struct something like below

```
type CRStatus {
    TestStatus string `json:"testStatus"`
    TestCount int `json:"testCount"`
}
```

Pod within Job does some processing and prints output TestStatus and TestCount values. How can controller update CR's TestStatus and TestCount fields with values from Pod output?

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**
* operator-sdk version:

"v0.17.2", commit: "0258db0119e8e18e15d035532427c329fce1e871"

* Kubernetes version information:

v1.15.3

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by camilamacedo86** [comment]
Hi @raghu017, 

See in the samples: 

https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/pkg/controller/memcached/memcached_controller.go#L161-L183

An example over how to update the status. In this case, it has been updated with the name of the Pods, however, you are able to update it as please you. Is it what you are looking for?

**Comment by camilamacedo86** [comment]
Closing this one since I understand that the example shared is what you are looking for. However, please feel free to ping us if you think that it should be re-opened.

**Comment by raghu017** [comment]
Hello @camilamacedo86  

Getting podnames is fine. But how do I get pod logs? Looking for something like this kubeClient.CoreV1().Pods("default").GetLogs("example", &v1.PodLogOptions{}) mentioned here https://github.com/operator-framework/operator-sdk/pull/295. 

But k8sclient is removed.

**Comment by raghu017** [comment]
I ended up doing this https://stackoverflow.com/a/53870271 using k8 go client.

**Comment by camilamacedo86** [comment]
Hi @raghu017, 

Thank you for share your solution here and help others as well. 

You also can check [here](https://github.com/operator-framework/operator-sdk/blob/master/internal/olm/operator/internal/registry_pod.go#L302) some example over how to get the logs as well. Since it is solved I am closing this one, however, feel free to ping us to re-open if you need or to raise new issues.
