### ISSUE TITLE
apiextensions.k8s.io/v1beta1

### ISSUE THREAD

**Issue by kotyara85** [operator-framework/operator-sdk#3417]
Hello,
Is there a way to generate CRDs compatible with apiextensions.k8s.io/v1beta1 in operator 0.18?
This's required to run operator in k8s < 1.16
Thanks

**Comment by camilamacedo86** [comment]
Hi @kotyara85, 

Yes. You can use the flag `--crd-version=v1beta1` to generate the CRD's in using the old api. Also, note that you can use the flag --help to get all options for the commands or check its docs for the specific version. For example see: https://v0-18-x.sdk.operatorframework.io/docs/cli/operator-sdk_add_crd/. It might help you. 

Closing this one as sorted out.
