### ISSUE TITLE
resyncPeriod for sdk.Watch() is an integer rather then time.Duration

### ISSUE THREAD

**Issue by jzelinskie** [operator-framework/operator-sdk#345]
This parameter [eventually gets converted to a time.Duration before it's passed to an Informer](https://github.com/operator-framework/operator-sdk/blob/25470b7caa370e58f35ae21c319fca9978195f87/pkg/sdk/informer.go#L53). The API would be easier to use and understand if we maintained this type information throughout the SDK.

**Comment by hasbro17** [comment]
@theishshah This should be a simpler change that you can follow up on after #418
