### ISSUE TITLE
Docs: reference to old boilerplate code 

### ISSUE THREAD

**Issue by deepak1725** [operator-framework/operator-sdk#3460]
## Bug Report

Docs are still referring to old Boilerplate code.
https://sdk.operatorframework.io/docs/golang/quickstart/#manager

Docs refers:

`manager.New(cfg, manager.Options{Namespace: namespace})` which doesn't exists.

Example Ref.
https://github.com/operator-framework/operator-sdk-samples/tree/master/go/kubebuilder/memcached-operator

**What did you do?**
Operator Migration v0.18 -> 0.19

**What did you expect to see?**
```
mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		...
		Namespace: 			"mynamespace"
	})
```

**What did you see instead? Under which circumstances?**

`manager.New(cfg, manager.Options{Namespace: namespace})` doesn't exists.

**Environment**
* operator-sdk version: 0.19

* go version: 0.14

* Kubernetes version information: 1.18

* Kubernetes cluster kind: minikube

* Are you writing your operator in ansible, helm, or go? Go

**Possible Solution**
Docs Fix
 
**Additional context**
Please traverse docs and follow each and every instruction written there Practically.
Only then we can identify Gaps.

It's Problematic to raise issues at every step.

**Comment by deepak1725** [comment]
Same for the next Sections

At https://sdk.operatorframework.io/docs/golang/quickstart/#manager
```
mgr, err := manager.New(cfg, manager.Options{
   NewCache: cache.MultiNamespacedCacheBuilder(namespaces),
})
```
and 
```
By default the main program will set the manager’s namespace using the value of WATCH_NAMESPACE env defined in deploy/operator.yaml
```
should be updated as per **v0.19** release

**Comment by estroz** [comment]
This fix needs to be made in master and cherry-picked to the v0.19.x branch.

**Comment by marcstreeter** [comment]
I'm seeing the same thing (walking through the memcached example tutorial) for `config/default/kustomization.yaml` referring to a `../crd` directory that doesn't exist

**Comment by estroz** [comment]
@marcstreeter that directory will exist once you run `create api` then `make manifests`.

**Comment by camilamacedo86** [comment]
Hi @marcstreeter and @deepak1725, 

I did a PR to fix the migration guide and it is https://github.com/operator-framework/operator-sdk/pull/3543 could you please check it and help us with the review. I also will push a PR to update the Memcached Sample with the new layout too :-)

**Comment by camilamacedo86** [comment]
The PR for the samples is https://github.com/operator-framework/operator-sdk-samples/pull/137. We might be able to improve the migration guide and use it as an example too.
