### ISSUE TITLE
Implement the Controller - broken link

### ISSUE THREAD

**Issue by ronaldpetty** [operator-framework/operator-sdk#3470]
A link to the "memcached_controller.go" is incorrect here:

https://sdk.operatorframework.io/docs/golang/quickstart/#implement-the-controller

https://github.com/operator-framework/operator-sdk/blob/master/example/kb-memcached-operator/memcached_controller.go.tmpl (broken)

The link in Git seems to work.

https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/building-operators/golang/quickstart.md 

points to

https://github.com/operator-framework/operator-sdk/blob/master/example/memcached-operator/memcached_controller.go.tmpl

I am not certain if that is the correct content for the website giving other repos and various paths (removes `kb-` prefix).

**Comment by joelanford** [comment]
@ronaldpetty The link in `master` without the `kb-` prefix is the new location for that file. We're doing some housekeeping in `master` to remove all of our docs and code that refer to the legacy project scaffolding.

Unfortunalely, that means any old docs that refer to `master` (like this one) are likely to break. We should update the v0.19.x branch to point to the v0.19.x version of that file.

**Comment by camilamacedo86** [comment]
Closes with the PR: https://github.com/operator-framework/operator-sdk/pull/3519

**Comment by camilamacedo86** [comment]
Done.
