### ISSUE TITLE
operator-sdk generate csv overwriting alm-examples

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [operator-framework/operator-sdk#3480]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

**What did you do?**
Our operator doesn't have a CRD of it's own and it watches for CRs created by other controllers in OpenShift. However we would like to have an example CRD that our operator can react upon so that it shows up in OperatorHub and makes it easier for end-user to create a CR. So, we updated the csv with an example CR but `operator-sdk generate csv` is deleting the entries we made to the CSV manually.

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).
`operator-sdk generate csv` not touching atleast the ` alm-examples:` section in csv if crds directory is empty.

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).
`operator-sdk generate csv` deleting the `alm-examples` entry

**Environment**
* operator-sdk version:
operator-sdk version: "v0.18.1",  go version: "go1.13.6 linux/amd64"

  insert release or Git SHA here
`7bf7b6886d647dc202525daec16fab67dcc52a3d`
* Kubernetes version information:

  insert output of `kubectl version` here
v1.18.2
* Kubernetes cluster kind: 
OpenShift

**Additional context**
Add any other context about the question here.
Example where we noticed this issue first:
https://github.com/openshift/windows-machine-config-operator/pull/81/files#r457726776

**Comment by camilamacedo86** [comment]
The `alm-examples: section in csv if crds directory is empty.` because you have not the CRs with the specs. This fields will be filled with the samples/CRs specs and values. 

Also, I'd suggest you migrate your project to the latest version as well. See: https://sdk.operatorframework.io/docs/building-operators/golang/migration/

**Comment by camilamacedo86** [comment]
Sorry, it was in the backlog and did not get our attention. 

The `operator-sdk generate csv` was replaced by `make bundle` for the latest versions. Note that the examples in the CSV are generating from the cr (config/sample). So, you need to have these files populated with the values wished. 

I am closing this one, however, could you please check it with the latest layout and let us know if you still require help? Thank you for your contribution and understanding.
