### ISSUE TITLE
can't use "operator-sdk new" create go type operator 

### ISSUE THREAD

**Issue by BlueShells** [operator-framework/operator-sdk#3485]
I am trying to create a go based operator by 

`$operator-sdk new $OPERATOR_NAME`

but I got error :

```
Error: required flag(s) "type" not set
Usage:
  operator-sdk new <project-name> [flags]
```

so new command now only allow to create helm and ansible operator ? I have to use init to create a go operator ?

```
operator-sdk version
operator-sdk version: "v0.19.0-50-ga5daa916", commit: "a5daa9165aab65b3f2a1a98baa98fd656b4c09ca", kubernetes version: "v1.18.2", go version: "go1.14.5 darwin/amd64"
```

**Comment by camilamacedo86** [comment]
Hi @BlueShells, 

See the [changelog](https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md#removals) and the [Migration Guide](https://sdk.operatorframework.io/docs/migration/v0.19.0/#migrating-go-projects-to-the-new-kubebuilder-aligned-project-layout): 

> The operator-sdk new command no longer supports scaffolding new Go projects with the --type=Go flag. To scaffold new projects, users are expected to use operator-sdk init as part of the new CLI for Go operators. (#3190)


SDK is in a process to be integrated with KB which means that its project layouts will be aligned. More info : [Integrating Kubebuilder and Operator SDK](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/integrating-kubebuilder-and-osdk.md).  Also, you can check that the quick start in the website is describing the tests with the init command now as well. 

I am closing this one as sorted out. However, feel free to raise new issues if you need.

**Comment by mihail-sky** [comment]
Hi @camilamacedo86, I followed the link you shared, but it seems the migration guide has a broken link - https://master.sdk.operatorframework.io/docs/golang/project_migration_guide/. Is there another link I can follow? I've got an operator built with operator-sdk 0.18.2.
