### ISSUE TITLE
Can annotation in existing helm operator CR be changed automatically after upgrade

### ISSUE THREAD

**Issue by bitscuit** [operator-framework/operator-sdk#3492]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

operator upgrades with OLM

## Question

**What did you do?**
I am developing a helm based operator and have already released a version. In this operator, the CR has the annotation, `helm.operator-sdk/upgrade-force: "True"`. I am working on a new version of the operator right now, but running into issues with upgrading the operator because of that annotation. If I set the annotation to false, the upgrade proceeds successfully, but I have to do this manually right now. Is there any way during the upgrade to automatically overwrite the annotation in the CR?

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:

  insert release or Git SHA here

* Kubernetes version information:

  insert output of `kubectl version` here

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by joelanford** [comment]
@bitscuit There isn't a way to do this with the helm-operator out of the box. 

However, you may be able to write a simple init container that patches all CRs with that change. And include that init container in the deployment for the new operator.

**Comment by bitscuit** [comment]
I see, thanks!
