### ISSUE TITLE
Migration guide from 0.18 to 0.19 not found

### ISSUE THREAD

**Issue by mihail-sky** [operator-framework/operator-sdk#3512]
I'm looking into migrating a golang operator from 0.18 to 0.19. I can see [in the docs](https://sdk.operatorframework.io/docs/migration/v0.19.0/#migrating-go-projects-to-the-new-kubebuilder-aligned-project-layout) there's a link for a guide but it [throws 404](https://master.sdk.operatorframework.io/docs/golang/project_migration_guide/). 

Would you recommend what are the steps for migration? Thanks!

**Comment by camilamacedo86** [comment]
Hi @mihail-sky.

Tks for raise that. We will fix the link in `See the migration guide that walks ...`
The 0.18 to 0.19 is there on the menu, see; 

<img width="223" alt="Screenshot 2020-07-24 at 10 14 26" src="https://user-images.githubusercontent.com/7708031/88377093-906be500-cd96-11ea-9428-dd13d45fbbfd.png">

**Comment by mihail-sky** [comment]
Hi @camilamacedo86, I'm still not sure where to find some information on how to migrate. All I can see in 0.19.0 about this is the information with the broken link.

<img width="711" alt="Screenshot 2020-07-24 at 10 21 12" src="https://user-images.githubusercontent.com/43004087/88377687-88607500-cd97-11ea-9baa-5746b9f549cb.png">

I've also selected form the dropdown 0.19, is the documentation you're referring to somewhere else?
<img width="171" alt="Screenshot 2020-07-24 at 10 22 41" src="https://user-images.githubusercontent.com/43004087/88377760-ac23bb00-cd97-11ea-9321-b154e656b824.png">

**Comment by camilamacedo86** [comment]
We updated the manus and organize it better as you can check in the master docs. However, when you are in  [in the docs](https://sdk.operatorframework.io/docs/migration/v0.19.0/#migrating-go-projects-to-the-new-kubebuilder-aligned-project-layout) see in the lateral the menu with `Migration Reference> v0.19.0 `. It is the guide to migrate from 0.18 to 0.19.

**Comment by mihail-sky** [comment]
Hi @camilamacedo86 are you referring to this guide then - https://sdk.operatorframework.io/docs/migration/v0.1.0-migration-guide/? I thought it's from 0.0.0 to 0.1.0, but probably the concept is the same. I'll give it a read, thanks.

**Comment by camilamacedo86** [comment]
Hi @mihail-sky, 

No. The doc for you migrate your project from 0.18 to 0.19 is:  https://sdk.operatorframework.io/docs/migration/v0.19.0/

**Comment by camilamacedo86** [comment]
Hi @mihail-sky, 

Sorry, I think you are looking for the migration guide from the legacy to the new layout. if yes, it is in: https://master.sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/ (I am suggesting the master link since it has some fixes/updates already)

**Comment by joelanford** [comment]
For legacy Go projects, you want: https://sdk.operatorframework.io/docs/migration/v0.19.0/

To migrate a legacy project to a Kubebuilder-based project, you want: https://sdk.operatorframework.io/docs/golang/project_migration_guide/

**Comment by mihail-sky** [comment]
Thanks both, I followed the [migration guide](https://master.sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/) as suggested and had a peak at the [new quickstart](https://master.sdk.operatorframework.io/docs/building-operators/golang/quickstart/).

It was a bit messy and manual. Would be nice if there was a cli command instead. For example, terraform had two commands when they made breaking changes to 0.12 - [terraform 0.12checklist](https://www.terraform.io/upgrade-guides/0-12.html#terraform-0-12checklist) and terraform 0.12upgrade. 

Otherwise, all looks good now, the operator is aligned to Kubebuilder layout. Thanks again, and feel free to close the ticket.

**Comment by karthequian** [comment]
I agree with @mihail-sky, and while the migration guide was useful, and helped me understand what changed, it was easier to just start with a new 0.19 project and then pull in the required updates. 

I had a 0.18.2 version of the golang operator working and then realized this week that the operator revved to 0.19- I started with the migration guide but then 1/2 way through just ended up building a new 0.19 project and pulling in the reconcile and other functions that i had previously created.

I fully expect this will get better over time, but a weird road right now.

**Comment by camilamacedo86** [comment]
we have a task to improve that. I agree with you @karthequian it has tons for improvements.

**Comment by camilamacedo86** [comment]
close this one since the fix for the broken link which is the "main subject" is solved. 
However, note that we are working on to improve these docs and also please feel free to contribute with it as well.
