### ISSUE TITLE
Handling events and reconciling state

### ISSUE THREAD

**Issue by itaysk** [operator-framework/operator-sdk#354]
I'm starting to wrap my head around the Operator SDK (and Kubernetes controllers/client-go in general), and I have some thoughts that I wanted to validate with you.

The Operator SDK allows me to easily handle CRUD events on my custom resources, as well as to continuously validate and reconcile it's state using regular 'sync' events (controlled by `resyncPeriod` parameter).
As an operator author, I'm now seeing two ways to use this functionality:

1. Provisioning work is done in the event handler (by acting on the recieved event), and the reconceliation handles configuration of the resources, such as replication for instance.
2. All actions , including resource provisioning and configuration are handled by the reconceliation loop, by comparing the desired and actual of the custom resources being watched (in which case the event recieved is meaningless).

My feeling is that the Operator SDK is geared toward option 1, and I was interested in hearing your thoughts about option 2.
If you think this is a valid use case, then there is some additional value that the SDK can provide around the boilerplate of writing this reconciliation loop.

**Comment by estroz** [comment]
@itaysk we've updated the project structure that the SDK generates significantly since your post. Take a look at our updated [memcached-operator](https://github.com/operator-framework/operator-sdk-samples/tree/master/memcached-operator/) and see if these changes clarify your understanding.
