### ISSUE TITLE
Ansible plugin is not scaffolding roles. 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3556]
**What did you do?**

```shell
operator-sdk init --plugins=ansible --group cache --version v1 --kind Memcached
```

**What did you expect to see?**

The same result of `$ operator-sdk new memcached-operator --api-version=cache.example.com/v1 --kind=Memcached --type=ansible`

- The roles directory scaffolded with the Memcached:

```shell
$ tree
.
└── memcached
    ├── README.md
    ├── defaults
    │   └── main.yml
    ├── files
    ├── handlers
    │   └── main.yml
    ├── meta
    │   └── main.yml
    ├── tasks
    │   └── main.yml
    ├── templates
    └── vars
        └── main.yml
```

- The watches updated with  `role: memcached`

```yaml
 $ cat watches.yaml 
---
- version: v1alpha1
  group: cache.example.com
  kind: Memcached
  role: memcached
```

**What did you see instead? Under which circumstances?**
- The roles dir is empty 
- The watches.yaml not updated with ` role: memcached`:

```ymal
$ cat watches.yaml 
---
# Use the 'create api' subcommand to add watches to this file.
- version: v1
  group: cache.my.domain
  kind: Memcached
  # FIXME: Specify the role or playbook for this resource.
# +kubebuilder:scaffold:watch
```

**Environment**
* operator-sdk version: master

**Additional context**
The issue is over a work that is WIP just is master and was tracked just for we know what needs to be done.

**Comment by camilamacedo86** [comment]
c/c @fabianvf

**Comment by asmacdo** [comment]
This is deliberate behavior, a new flag `--generate-role` will scaffold the role.

**Comment by camilamacedo86** [comment]
Oh tks for let me know @asmacdo . Closing it.
