### ISSUE TITLE
Operator-sdk create webhook not available in v0.19

### ISSUE THREAD

**Issue by victorpaulo** [operator-framework/operator-sdk#3561]
## Bug Report

**What did you do?**
I installed the operator-sdk v0.19 and then I tried to create a webhook using the command specified in the [documentation](https://v0-19-x.sdk.operatorframework.io/docs/golang/webhooks/):
`
$ operator-sdk create webhook --group cache --version v1alpha1 --kind Memcached --defaulting --programmatic-validation
`

However there is no create option available in the command;

**What did you expect to see?**
`I expect to have a documentation fix for that or an updated instruction of how to create a web hook using that version;`

**What did you see instead? Under which circumstances?**
```
ictorp:pipeline-operator victorp$ operator-sdk create --help
[Deprecation Notice] Operator SDK has a new CLI and project layout that is aligned with Kubebuilder.
See `operator-sdk init -h` and the following doc on how to scaffold a new project:
https://sdk.operatorframework.io/docs/golang/quickstart/
To migrate existing projects to the new layout see:
https://sdk.operatorframework.io/docs/golang/migration/project_migration_guide/

Error: unknown command "create" for "operator-sdk"
Run 'operator-sdk --help' for usage.
FATA[0000] unknown command "create" for "operator-sdk"  
```

**Environment**
* operator-sdk version:

`operator-sdk version: "v0.19.0", commit: "8e28aca60994c5cb1aec0251b85f0116cc4c9427", kubernetes version: "v1.18.2", go version: "go1.14.5 darwin/amd64"`

* go version:

`go version go1.14.5 darwin/amd64`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", 
GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
`kind v0.8.1 go1.14.4 darwin/amd64`

* Are you writing your operator in ansible, helm, or go?
`I am writing in Go`

**Possible Solution**

`No idea`

**Additional context**

**Comment by joelanford** [comment]
@victorpaulo The `create` subcommands only work in `v0.19+` when you have migrated your project to a Kubebuilder style project. See https://sdk.operatorframework.io/docs/golang/project_migration_guide/

**Comment by joelanford** [comment]
Closing since I'm pretty sure that's the issue. Happy to answer any follows though!
