### ISSUE TITLE
Update Docsy

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#3581]
We carry a patch against Docsy to allow theme customization. This ticket is to

- rebase our Docsy fork
- fix any backwards incompatible changes
- move the Docsy fork into operatorframework org
- update operator-sdk (Also OLM and operatorframework.io) submodules

This will be a breaking change for developers, who will need to update their local submodules. Docs for how to do this should be included, sent to slack, and the developer mailing list.

**Comment by estroz** [comment]
Verification is needed that the fix is in the main docsy tree before it can be used.

**Comment by jmrodri** [comment]
Closing this as the change we made has not been submitted to upstream and I don't see a way to accomplish what we did with upstream docsy. We will be keeping the fork.
