### ISSUE TITLE
Create a shared glossary for OLM + SDK

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#3589]
The glossary could live on operatorframework.io, but this issue is filed against sdk for milestone planning.

**Comment by asmacdo** [comment]
Some words we should define (please add others): 

operator
watch
reconcile
manager

**Comment by camilamacedo86** [comment]
IHMO these words/nomenclatures are definitions made in controller-runtime.

**Comment by asmacdo** [comment]
For words that are defined upstream, I agree we shouldnt refine them locally for the most part. But `manager` for example seems to be [defined upstream in a GoDoc](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager) which is at least uncomfortable for non-go users. This isn't great, because this concept is very important for all operator types. I think a __brief__ explanation and a link is appropriate.

**Comment by camilamacedo86** [comment]
IHMO : 

See that for a basic user they do not care about the Manager at all. Just advanced ones who started to look that deeper will raise question over this kind of detail. Then, I think that we need to make clear that Ansible/Helm at the end all will be a Go operator and in this way use the same nomenclature which shows just required in the advanced topics.
