### ISSUE TITLE
Add e2e test for up local command

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/operator-sdk#361]
We need to have an e2e test that tests out the `operator-sdk up local` command to catch bugs like #356 

The test will be similar to the user-guide example, except we can use the default app-operator example(on the README) to keep it simple.
Rough outline of the test:
- Create new project: `operator-sdk new app-operator --api-version=app.example.com/v1alpha1 --kind=App`
- symlink local `operator-framework/operator-sdk/pkg` to  `vendor/github.com/operator-framework/operator-sdk/pkg`
- Run operator via `operator-sdk up local --namespace=<ns>`
- Test out the operator by creating the CR: `kubectl -n=<ns> create -f deploy/cr.yaml`

/cc @AlexNPavel

**Comment by AlexNPavel** [comment]
Fixed by #365
