### ISSUE TITLE
operator-sdk 1.0 needs a way to use podman instead of docker

### ISSUE THREAD

**Issue by wkulhanek** [operator-framework/operator-sdk#3623]
## Bug Report
**What did you do?**
I am building an operator on a RHEL 8 box. There is no docker on RHEL 8, only podman. It would be good if operator-sdk also supported podman. Could be as simple as adding additional targets to the generated Makefile (podman-build, podman-push, ...).

Using an `ln -s /usr/bin/podman /usr/bin/docker` worked for the most part - but somehow I'm getting an invalid bundle.

**Environment**
* operator-sdk version:

operator-sdk version: "v1.0.0-alpha.1", commit: "b95f052d11025bf6963215cbb9a331e5181b0c4f", kubernetes version: "v1.18.2", go version: "go1.13.11 linux/amd64"

* go version:

* Kubernetes version information:

OpenShift 4.5.4
Client Version: 4.5.2
Server Version: 4.5.4
Kubernetes Version: v1.18.3+012b3ec

* Are you writing your operator in ansible, helm, or go?
Ansible

**Possible Solution**
Add new targets to Makefile - or add flag to `operator-sdk init` to generate podman instead of docker. Actually I'd remove all docker references and use image instead. :-)

**Additional context**
Following my lab guide: 
https://github.com/redhat-cop/openshift-lab-origin/blob/master/OpenShift4/Ansible_Operator_1.0.adoc

**Comment by estroz** [comment]
The Makefile is yours once you've `init`'d your project, so you can modify the image build targets yourself.

**Comment by akaris-redhat** [comment]
Hi,

I'd like to reopen this. Can we add the following default make targets?
~~~
# Build the docker image
podman-build: test
        buildah bud -t ${IMG} .

# Push the docker image
podman-push:
        podman push ${IMG}
~~~

Given the close relationship between operator-sdk, OpenShift, RHEL 8 and given the absence of docker in RHEL 8 I strongly advocate that the operator-sdk and its getting started examples work from the get go with podman.

**Comment by estroz** [comment]
As an operator project owner, you have complete control over your Makefile and can update the default docker targets as needed. You can one-liner this with `sed -i 's/docker/podman/g' Makefile`.

An alternative is writing a phase 2 plugin (when they are implemented, see https://github.com/kubernetes-sigs/kubebuilder/pull/1801) to scaffold podman/buildah instead of docker, but that's still a ways off.

Btw, operator-sdk is a CNCF project that doesn't target a specific platform/os (other than Kubernetes of course).

**Comment by jmccormick2001** [comment]
I haven't documented it (yet), but if you do end up using podman, watch out for the manifest version it creates, I ended up using "--format=docker' to get it to build v2 manifests which are required by the opm command.
