### ISSUE TITLE
Deleting a namespace containing a custom resource with finalizer does not result in a successful deletion of the ns

### ISSUE THREAD

**Issue by Avni-Sharma** [operator-framework/operator-sdk#3625]
Using 
```
avni@localhost service-binding-operator (master)=>>   operator-sdk version
operator-sdk version: "v0.16.0", commit: "55f1446c5f472e7d8e308dcdf36d0d7fc44fc4fd", go version: "go1.13.8 linux/amd64"
```
on OpenShift 4.6 cluster

I have a custom resource which is using finalizers in the controller. When I delete the namespace(ns) I expect the CR to be deleted as well.  However, when I want to delete the whole ns with the CR, the deletion is stuck for the ns due to the finalizers in the CR. Is this expected? 

I tried adding ownerRef of the particular ns in my CR, but that does not help too. 
example- 
```
  ownerReferences:
    - apiVersion: v1
      kind: Namespace
      name: default
      uid: 5f5c4959-7d48-4228-bdb1-6a859c9d6701
```
I tried to delete the CR on the deletion of a resource that is it's owner (in my case suppose ns) so I perform the following in my controller:
`if sbr.GetDeletionTimestamp() != nil && sbr.GetOwnerReferences() != nil {`
`// logic to removeFinalisers()`

Still, the controller is in like a deadlock and is not deleting the CR.
Any leads would be appreciated in this regard.

PS- The above-mentioned logic works if my owner resource is for example a deployment. It fails if the owner is a ns/project.

**Comment by hasbro17** [comment]
> I tried adding ownerRef of the particular ns in my CR, but that does not help to

That shouldn't be necessary. You don't need to manually define an owner for your CR object.

As for your finalizer logic in the reconciler, you also don't need to check for the OwnerReferences of the CR. It should just be looking at the CR's DeletionTimestamp to initiate the Finalizer cleanup logic:
```Go
if sbr.GetDeletionTimestamp() != nil {
    // logic to removeFinalisers()
}
```

Here's a [reference example](https://sdk.operatorframework.io/docs/golang/advanced-topics/#handle-cleanup-on-deletion).

Is your operator in the same namespace as the CR namespace that you're deleting? Just want to double check that the operator isn't deleted before it can perform the cleanup for the finalizer.

If not, can you please post:
- The state of your CR as it's blocked on finalizers/deletion: `kubectl get <cr_kind> <cr_name> -o yaml`
- Your operator reconciler logic for setting finalizers, and the cleanup
- Operator logs.
  - If you could add some logs in the reconciler, right before and after the finalizer cleanup part, we can confirm where exactly is the operator blocking, before or in the finalizer code. Or if it's not even registering the deletion event.

**Comment by Avni-Sharma** [comment]
Closing the issue, as it no longer stands relevant. Thanks @hasbro17
