### ISSUE TITLE
Deploying Operator Programmatically

### ISSUE THREAD

**Issue by iboware** [operator-framework/operator-sdk#3631]
## Type of question

Deploying Operator

## Question

**What did you do?**
I have created an operator and a CLI tool to manage CRs. I want to deploy the operator to Kubernetes (CRD and Controller) programmatically with go-client. Is there an easy/built-in way to do this?

**Environment**
* operator-sdk version: 0.19

8e28aca60994c5cb1aec0251b85f0116cc4c9427

**Comment by camilamacedo86** [comment]
Hi @iboware, 

I am assuming that you are looking to do it because you need to add an operator which depends on another one. Am I right? If yes, the recommendation would be using [OLM Dependency Resolution](https://github.com/operator-framework/operator-lifecycle-manager#dependency-resolution) for it.

**Comment by iboware** [comment]
Hi @camilamacedo86 thank you for your reply. No, I am doing it to make it easy for people who has not much knowledge about Kubernetes and Operators for simplicity. I want to deploy the operator via the CLI utility. 
Simply, I want to achieve something like this:
```bash
pgctl init --kubecluster EU1 #this will deploy the operator to the kubernetes cluster
pgctl create cluster test-postgresql --replicas 5 --kubecluster EU1 #this will apply the CR to the initialized cluster.
```
this is my repo: https://github.com/iboware/postgresql-operator

**Comment by camilamacedo86** [comment]
Hi @iboware, 

Currently, to deploy your project the steps would be only : 

```
make docker-build docker-push IMG=<some-registry>/<project-name>:<tag>
make install
make deploy IMG=<some-registry>/<project-name>:<tag>
```

Also, see that you can customize your makefile. So, I'd recommend you use it, for example:

- You can set here a specific image
```
# Deploy controller in the configured Kubernetes cluster in ~/.kube/config
deploy-master-img:  
	make install
        make deploy IMG=myregistry/myproject:master //Set here the data over an image that is built already
        kubectl apply -f config/samples/mysample.ymal
``` 

Then, to see the operator deployed you would just run `make deploy-master-img` and you can use the kubectl CLI to update the CR specs. So, it would be something as 

```
make deploy-master-img
kubectl patch --namespace=<namespace> <kind> <crName> -p '[{"op":"replace","path":"/spec/replicaCount","value":5}]' --type=json
``` 

which would be equivalent to :

```
pgctl init --kubecluster EU1 #this will deploy the operator to the kubernetes cluster
pgctl create cluster test-postgresql --replicas 5 --kubecluster EU1 #this will apply the CR to the initialized cluster.
```

Also, you can integrate your project with OLM and provide your operator in its catalogue which would allow a user to install/manage the project via cliques and ab UI. See https://operatorhub.io/. 
  
 Please, let us if it help you with.

**Comment by iboware** [comment]
@camilamacedo86 Thank you, your final idea about running make targets seems very appealing. I just did not want to execute any commands thinking of dependencies to be installed. Thanks also for the tips about makefile customizations. I will also look into OLM.
