### ISSUE TITLE
PreserveUnknownFields marker is ignored

### ISSUE THREAD

**Issue by umangachapagain** [operator-framework/operator-sdk#3633]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

**What did you do?**
Added `// +kubebuilder:pruning:PreserveUnknownFields=true` marker to struct in `_type.go`
and `operator-sdk generate crds`

**What did you expect to see?**
`PreserveUnknownFields: true` being set in CRD Spec.

**What did you see instead? Under which circumstances?**
Marker was ignored.

**Environment**
* operator-sdk version: 0.17.0

operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c"

* Kubernetes version information:

1.18.3

* Kubernetes cluster kind: 

**Additional context**
Followed https://book.kubebuilder.io/reference/markers/crd-processing.html

**Comment by joelanford** [comment]
@umangachapagain It looks like `+kubebuilder:pruning:PreserveUnknownFields=true` may only be usable on struct fields, and not structs.

Can you try using `+kubebuilder:validation:XPreserveUnknownFields`? Also don't append `=true` (that is assumed based on the presence of the marker)

It should look something like this:
```go
// +kubebuilder:validation:XPreserveUnknownFields

// FrigateSpec defines the desired state of Frigate
type FrigateSpec struct {
    Foo string `json:"foo,omitempty"`
}
```

**Comment by umangachapagain** [comment]
> @umangachapagain It looks like `+kubebuilder:pruning:PreserveUnknownFields=true` may only be usable on struct fields, and not structs.
> 
> Can you try using `+kubebuilder:validation:XPreserveUnknownFields`? Also don't append `=true` (that is assumed based on the presence of the marker)
> 
> It should look something like this:
> 
> ```go
> // +kubebuilder:validation:XPreserveUnknownFields
> 
> // FrigateSpec defines the desired state of Frigate
> type FrigateSpec struct {
>     Foo string `json:"foo,omitempty"`
> }
> ```

This worked. Thanks.
