### ISSUE TITLE
migration guide 404

### ISSUE THREAD

**Issue by philips** [operator-framework/operator-sdk#3646]
https://master.sdk.operatorframework.io/docs/golang/project_migration_guide/ 404s

That link is provided on this page https://sdk.operatorframework.io/docs/migration/v0.19.0/

**Comment by joelanford** [comment]
Updated `latest` branch so that `sdk.operatorframework.io` now points to v0.19.2 docs. That fixes the broken link.

Also filed #3648 to fix the duplicate link that's on _that_ site.

Closing since it at least no longer 404s
