### ISSUE TITLE
Exiting the up local command on with ^C (SIGINT) leaves behind `go run` processes

### ISSUE THREAD

**Issue by AlexNPavel** [operator-framework/operator-sdk#366]
The `up local` subcommand executes a `go run` command, but doesn't stop it if the `up local` command is closed by SIGINT, which is likely how it will be end since `up local` is a long running command.
Specifically, this function executes the go run command, and thus should have a cleanup implemented for SIGINT: https://github.com/operator-framework/operator-sdk/blob/02cf8522bd996f68eebe9ebec6bcda5a05d0393d/commands/operator-sdk/cmd/up/local.go#L74

**Comment by fanminshi** [comment]
@AlexNPavel Yeah, I am aware of this issue. I believe that the child process do get the (SIGINT) signal. The issue is that the operator's code doesn't catch signal therefore it doesn't shutdown.

**Comment by fanminshi** [comment]
Two approaches:
* We catch signal inside the operator using something like https://golang.org/pkg/os/signal/#Notify; once notified, we exist the operator. This can be a a lot work.
* Another approach is to catch signal inside the `up local` code. Then once the signal is received, we can send a SIGKILL to the child process via `cmd.Process.Kill()` to terminate the child process immediately.  More info about this can be found at [here](https://stackoverflow.com/questions/11886531/terminating-a-process-started-with-os-exec-in-golang)

**Comment by AlexNPavel** [comment]
Resolved in #365
