### ISSUE TITLE
Should there be a `bundle-push` task to align with `docker-build` and `docker-push` tasks?

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-sdk#3667]
See subject :)

**Comment by asmacdo** [comment]
Probably, but since this is an additive change, 1.1 should be fine.

**Comment by joelanford** [comment]
Moving to `Backlog` since there is some open question about what exactly `bundle-push` should do (e.g. should it do anything related to adding the bundle to an index image?)

**Comment by camilamacedo86** [comment]
/remove-lifecycle rotten

It shows very easier tasks to be accomplished. So, wdyt we add it in a milestone? 
c/c @jmrodri @estroz @asmacdo

**Comment by estroz** [comment]
I'd rather change `BUNDLE_IMG` to `IMG` so you can do the following without adding a new target:
```sh
make bundle-build docker-push IMG=foo/bar-bundle:baz
```
This isn't a breaking change because existing projects won't have to change anything.

**Comment by jmrodri** [comment]
The only downside to renaming BUNDLE_IMG to IMG is that if I set an env I could mess myself up by doing make bundle-build IMG=$IMG.

But more than likely I would probably do this:
```
IMG=my operator image
BUNDLE_ING=my bundle image 
make docker-build docker-push IMG=$IMG 
make bundle-build docker-push IMG=$BUNDLE_IMG
```

So I'm OK with renaming BUNDLE_IMG in the Makefile to just IMG.

**Comment by estroz** [comment]
This was done in #4406
