### ISSUE TITLE
Plugin version in the project file shows not accurate 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3669]
**With: 0.19.2**

See: `$ operator-sdk init -h`

` --plugins strings          Name and optionally version of the plugin to initialize the project with. Available plugins: ("go.kubebuilder.io/v2")
`

See: `$ operator-sdk init --plugins=go.kubebuilder.io/v2`:

```
$ cat PROJECT 
domain: my.domain
layout: go.kubebuilder.io/v2
repo: github.com/example-inc/memcached-operator
version: 3-alpha
plugins:
  go.operator-sdk.io/v2-alpha: {}
```

**With master c9348b5e9800c30817e979c5e5234c355c919d0c:**

See: `$ operator-sdk init -h`

`       --plugins strings          Name and optionally version of the plugin to initialize the project with. Available plugins: ("ansible.sdk.operatorframework.io/v1", "go.kubebuilder.io/v2", "helm.sdk.operatorframework.io/v1")
`

```
 $ cat PROJECT 
domain: example.com
layout: go.kubebuilder.io/v2
projectName: memcached-operator
repo: github.com/example-inc/memcached-operator
version: 3-alpha
plugins:
  go.sdk.operatorframework.io/v2-alpha: {}
```

**Concerns**

- It is scaffolding ` go.operator-sdk.io/v2-alpha: {}` or ` go.sdk.operatorframework.io/v2-alpha:` instead of `"go.kubebuilder.io/v2"`
- master and 0.19.2 are with diff plugins versions for GO
- Ansible and Helm plugins are with the domain `sdk.operatorframework.io` when just go is showing as `go.kubebuilder.io`
- Why we should the plugin as `"go.kubebuilder.io/v2"` when actually we are scaffolding the sdk one? PS.: IMO it is not 100% the kb one since we perform customizations for OLM and Scorecard on top.

**Comment by joelanford** [comment]
Any reason we aren't in the `v1` version for this given we're going for v1.0.0 and there's no previous version of this plugin?

**Comment by camilamacedo86** [comment]
@joelanford I updated this one.

**Comment by camilamacedo86** [comment]
Hi @joelanford, 

I  updated this one with all my thought and checks.  Feel free to re-check. Regards

`Any reason we aren't in the v1 version for this given we're going for v1.0.0 and there's no previous version of this plugin?`

I think we could use v1 as well to align it with 1.0 release. But for the other side, the advantage of using v2 would be follow up the kb plugins versions in order to make more intuitive that the sdk plugin version X is based on the upstream plugin version X as well.

**Comment by joelanford** [comment]
> the advantage of using v2 would be follow up the kb plugins versions in order to make more intuitive that the sdk plugin version X is based on the upstream plugin version X as well.

Agreed, but I'm not sure there will always be a need for us to update our plugin version when KB updates the base Go plugin.

Right now our plugin:
- Adds some extra lines to the Makefile
- Adds a `kustomization.yaml` file to `config/samples`

Unless something drastically changes between versions of KB plugins, these things should continue to work.

**Comment by joelanford** [comment]
> Why we should the plugin as "go.kubebuilder.io/v2" when actually we are scaffolding the sdk one? PS.: IMO it is not 100% the kb one since we perform customizations for OLM and Scorecard on top.

We're trying to be forward compatible with eventual phase 2 plugins. What we're doing right now for go is effectively the same as calling `init --plugins=go.kubebuilder.io/v2,go.sdk.operatorframework.io/v2-alpha`, where the KB plugin is the base plugin (what shows up in the layout) and our extras are a "phase 2" plugin that show up in the plugins section.

We're effectively just reserving the name AND putting something in the plugins section to show that we've made some changes in the scaffolded project on top of what's provided by the KB plugin.

**Comment by camilamacedo86** [comment]
Hi @joelanford, 

So, following what in POV needs to be addressed here:

- [ ] Decide if we will keep `go.sdk.operatorframework.io/v2-alpha`. Should it be alpha? 
- [ ] PR against 0.19 in order to ensure that projects generated with will scaffold PROJECT files with the same plugin name E.g`go.sdk.operatorframework.io/v2-alpha`

**Comment by joelanford** [comment]
We're keeping this as is for `operator-sdk v1.0`. `v2-alpha` gives us flexibility to make breaking changes before releasing a `v2` version of the plugin (at that point, we would deprecate `v2-alpha` for the duration of SDK v1, and then remove it in SDK v2)
