### ISSUE TITLE
sdk.Watch   how to watch multiple namespace

### ISSUE THREAD

**Issue by alynlin** [operator-framework/operator-sdk#367]

**Comment by maleck13** [comment]
You can watch all namespaces using an empty string as the namespace value

**Comment by alynlin** [comment]
If you use an empty string as the namespace value, the default namespace is monitored

**Comment by madorn** [comment]
`sdk.Watch` will watch all namespaces if you provide an empty string.

**Comment by fanminshi** [comment]
we probably should provide some useful constants in operator-sdk such as ALL_NAMESPACE to indicate how to watch all namespace.
