### ISSUE TITLE
make bundle interactive mode easier to be used 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3672]
**What did you do?**
- Create a project and generated the bundle
```
mkdir memcached-operator
cd memcached-operator
operator-sdk init --domain=example.com --repo=github.com/example-inc/memcached-operator
operator-sdk create api --group cache --version v1 --kind Memcached --resource=true --controller=true
make bundle
```

**What did you expect to see?**
- The values are checked. 
- we have a way to input the data without the need to be a string separated by commas

**What did you see instead? Under which circumstances?**

```
Comma-separated list of keywords for your operator (required): 
> d/d/

Comma-separated list of maintainers and their emails (e.g. 'name1:email1, name2:email2') (required): 
> jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
jjjjjjjjjjjjjjj
kkkkkkkkkkkkkkkkkk
```

**Comment by camilamacedo86** [comment]
We discuss that in the bug triage meeting and actually the values are not really required and would be great ability to improve this, however, it is a low priority and would be great receive a collab with it.

**Comment by estroz** [comment]
Input is processed (and should be validated) [here](https://github.com/operator-framework/operator-sdk/blob/v1.2.0/internal/generate/clusterserviceversion/bases/metadata.go#L45).

**Comment by AssafKatz3** [comment]
Hi,
Since the creation of this issue,  the process became more complex by far. We already had HELM based operator and wanted to add only bundle, but this process isn't documented. I agree with @camilamacedo86  that this process should be interactive and much easier.
Thanks

**Comment by estroz** [comment]
@AssafKatz3 what do you mean "not documented"? The bundle docs are [here](https://sdk.operatorframework.io/docs/olm-integration/quickstart-bundle/).
