### ISSUE TITLE
operator-sdk init shows not to do go mod init when it is done in the GOPATH

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3675]
## Bug Report

**What did you do?**

```
mkdir $GOPATH/src/anyproject
cd $GOPATH/src/anyproject
operator-sdk init —domain example.com
cat PROJECT
```

**What did you expect to see?**
- Check if is inside of the $GOPATH*:
- If it has been executed **inside of the $GOPATH** and has not a go.mod
- The init command execute `go mod init` before the scaffold and populate the repo with: 

```
 $ cat PROJECT
domain: my.domain
layout: go.kubebuilder.io/v2
projectName: anyproject
repo: anyproject
version: 3-alpha
plugins:
  go.sdk.operatorframework.io/v2-alpha: {}
```

The tool could make clear that  **outside of  $GOPATH**  the repo flag needs to be filled. 

**What did you see instead? Under which circumstances?**

In my case, I checked the following always when the repo is not informed and I did not made `go mod init` before running the command. (inside and outside of the GOPATH)

```
 $ cat PROJECT
domain: my.domain
layout: go.kubebuilder.io/v2
projectName: anyproject
repo: github.com/example-inc/memcached-operator
version: 3-alpha
plugins:
  go.sdk.operatorframework.io/v2-alpha: {}

```

**Environment**
* operator-sdk version: c9348b5e9800c30817e979c5e5234c355c919d0c
* go version: go1.13.12

**Possible Solution**

**Additional context**
The same behaviour has been check with upstream and the  go1.13.12.
If it requires a fix then, needs to be performed in upstream.

**Comment by akoserwal** [comment]
Env
```
operator-sdk version: "v1.0.0-alpha.2-21-gccd621b0",
go1.14.5
KubeBuilderVersion:"2.3.1"
```
# Outside GOPATH:

`operator-sdk init —domain example.com` or `kubebuilder init —domain example.com`
getting:
`Error: outside GOPATH, module path must be specified`

# Inside GOPATH:
`operator-sdk init —domain example.com` or `kubebuilder init —domain example.com`

Both result in generating the project with repo: github.com/<dir-name> (/github.com/test-k)

**Comment by camilamacedo86** [comment]
Hi @akoserwal, 

Thank you for your input. Yes, it has not been done in kubebuilder as well and I tracked this issue as RFE which would be done in the Kubebuilder.

**Comment by camilamacedo86** [comment]
I am closing this one since I am unable to reproduce the issue faced before where the same value for the repo was appearing in all tests instead of the current path be used when it is inside of the GOPATH.
