### ISSUE TITLE
doc: clarify that when is multigroup it is required update the Dockerfile as well

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3678]
**Steps**
- Create a project and API with controller and resource (QuickStart)
- Update project file with multigroup: true
- Run `make docker-build`

**The following issue will be faced**
COPY failed: stat /var/lib/docker/tmp/docker-builder031903601/api: no such file or directory
make: *** [Makefile:73: docker-build] Error 1

**Solution**
Update the Dockerfile. 

Replace:  
`COPY api/ api/`

With: 

`COPY apis/ apis/`

**Goal of this task**
- Update this info in the [Migration Guide](https://master.sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/#check-if-your-project-is-multi-group)
- Check if we should update it other places as well.

**Comment by joelanford** [comment]
Users would also have to move their existing API in `./api` to the appropriate group directory in `./apis`, right?

**Comment by joelanford** [comment]
This should be documented upstream since this is a purely kubebuilder related issue.

**Comment by camilamacedo86** [comment]
hi @joelanford, 

> Users would also have to move their existing API in ./api to the appropriate group directory in ./apis, right?
Yes

> This should be documented upstream since this is a purely kubebuilder related issue.

Upstream has a command to do that. So, the documentation has your note above but not the dockerfile info.

**Comment by miguelsorianod** [comment]
Hi,

I've reproduced the reported issue here.

Is there some way I can help with this?

Thank you.

**Comment by camilamacedo86** [comment]
Hi @miguelsorianod, 

IMO what I think that we really to do is: 

- get merged the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/1691
- bump kubebuilder commit in the SDK
- then, add the edit plugin to SDK as well
- add the edit plugin to SDK as a new RFE
- and then, we can address users to the doc: https://book.kubebuilder.io/migration/multi-group.html

@joelanford wdyt?

**Comment by camilamacedo86** [comment]
Done : https://github.com/operator-framework/operator-sdk/pull/4156/files

**Comment by camilamacedo86** [comment]
It is done in the PR #4156
