### ISSUE TITLE
Operator does not work against GKE

### ISSUE THREAD

**Issue by sttts** [operator-framework/operator-sdk#368]
```
$ operator-sdk up local
INFO[0000] Go Version: go1.10.3
INFO[0000] Go OS/Arch: darwin/amd64
INFO[0000] operator-sdk Version: 0.0.5+git
ERRO[0000] Failed to initialize service object for operator metrics: OPERATOR_NAME must be set
INFO[0000] Watching policy.k8s-go.openshift.org/v1beta1, HealthCheckPolicy, default, 5
panic: No Auth Provider found for name "gcp"
```

**Comment by sttts** [comment]
Also the error message `ERRO[0000] Failed to initialize service object for operator metrics: OPERATOR_NAME must be set` looks suspicious.

**Comment by sttts** [comment]
main.go needs:

```
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
```

**Comment by hasbro17** [comment]
@sttts The error message:
```
ERRO[0000] Failed to initialize service object for operator metrics: OPERATOR_NAME must be set
```
is expected when running the operator via `operator-sdk up local`.

By default on startup an sdk based operator will now create a Service to expose the operator metrics 
https://github.com/operator-framework/operator-sdk/blob/master/pkg/sdk/metrics.go#L14

To do that the SDK relies on the operator name, passed in as an ENV, to be used as the service selector for the operator deployment
https://github.com/operator-framework/operator-sdk/blob/master/pkg/util/k8sutil/k8sutil.go#L167
 https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/templates.go#L434-L435

When running out of cluster with `operator-sdk up local` there is no deployment to select. 
But ideally that shouldn't be an error message and we'll probably skip setting up the metrics service when running locally.

For the gcp auth issue we can update the main template to include the gcp plugin as you've suggested. Even though that's only really needed when running the operator out of cluster.
https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/templates.go#L150  
https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster-client-configuration/main.go#L31-L32
