### ISSUE TITLE
Go tests should cover the features with apis scaffolding using v1 version

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3680]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Ensure that all features work fine for GO when CRD's versions are v1. 

**Describe the solution you'd like**
After we merge the PR https://github.com/operator-framework/operator-sdk/pull/3499 we add another test to check OLM and Scorecard with a project that was scaffolded with the Makefile updated as: 

```
By("Updating Makefile to use crd:crdVersions=v1")
replaceCRDOptions := "crd:trivialVersions=true"
testutils.ReplaceInFile(filepath.Join(tc.Dir, "Makefile"), replaceCRDOptions, "crd:crdVersions=v1")
```

**Comment by estroz** [comment]
This has been done for awhile now.
