### ISSUE TITLE
Use by default the projectName from the Project File when runs operator-sdk cleanup 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3706]
## Feature Request

The tool has the command `operator-sdk cleanup <projectName>`, however, the project name is a value in the Project file. So, would not be required to inform the project name at all since it can be easily obtained by the tool.

NOTE: It is NOT a breaking change, we ONLY allow the users to run and clean the command without need looking for additional info that we already have since the tool just needs to check the project file. 

**Motivation**

Note that when we exec `operator-skd run pkg` manifest the name of the project is not informed which make more weirdo in my POV be mandatory to inform the project name which is a value that is defined in the Project config to cleanup this operation.  So, IMO:
- Users might have difficult to know what value should be informed
- Users will need to check the PROJECT file to see the value. 
- The tool could facilitate it by getting the value from the Project file if/when it was not informed.  
- Shows that the common usage in the biggest part of the cases would be from the project dir run the pkg, then test it and cleanup.
- It simplifies its usage.

**Comment by camilamacedo86** [comment]
c/c @joelanford @estroz

**Comment by camilamacedo86** [comment]
If it is accepted we need to do before the 1.0.  
c/c @joelanford @estroz

**Comment by joelanford** [comment]
See https://github.com/operator-framework/operator-sdk/pull/3707#issuecomment-671330699

Moving to Backlog.

**Comment by camilamacedo86** [comment]
I removed from the backlog because it was added to the backlog for we are able to discuss it again in the bug triage meeting and I update the first comment to make its motivation more clear.

**Comment by camilamacedo86** [comment]
We discussed in the bug triage meeting and then we decided to no mover forward with because actually, we can have more than one pkg running and not necessary it will be the Project Name. Another good argumentation was that we would like to promote run bundle more instead of that.
