### ISSUE TITLE
How to setup Namespaced-scope Helm Operator with 1.0.0?

### ISSUE THREAD

**Issue by pgerv12** [operator-framework/operator-sdk#3722]
## Type of question

How to

## Question

Is changing the RBAC files to `Roles` from `ClusterRoles` enough to make the Helm operator watch a namespace only?
Also, is it possible to add `WATCH_NAMESPACE` to the manager YAML so a namespace doesn't need to be specified? It's unclear if this is possible or what needs to be done for Helm since the doc discusses Go Manager options. 

**Environment**
* operator-sdk version: 1.0.0

**Comment by camilamacedo86** [comment]
Hi @pgerv12, 

The steps are quite similar, however, we need doc it per type as you suggested. We have a doc per type.  See that we have a task for it already.  https://github.com/operator-framework/operator-sdk/issues/3688

Regards your questions: 

If you look [here](https://github.com/operator-framework/operator-sdk/blob/master/internal/cmd/helm-operator/run/cmd.go) it is the implementation of your `main.go` when you are using a Helm-based Operator. 

So, you can use the [WATCH_NAMESPACE](https://github.com/operator-framework/operator-sdk-samples/blob/master/helm/memcached-operator/deploy/operator.yaml#L21-L25) as it was in the legacy layout in the `config/manager/manager.yaml` which allows you inform 1 namespace or a set of them ( multi-namespace scenario that you can see in the [Operator Scope](https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#watching-resources-in-a-set-of-namespaces) doc for Go). 

Also, feel free to contribute to it. Your PR's are very welcome.   🥇  
I will supplement the info in #3688 as well just in case someone decides to collab with it. 

I am closing this one as sorted out. However, please feel free to ping us if you think that it should be re-opened.
