### ISSUE TITLE
Helm operator: unable to deploy nginx-operator cause cannot set finalizers on serviceaccount

### ISSUE THREAD

**Issue by lbroudoux** [operator-framework/operator-sdk#3733]
## Bug Report

**What did you do?**

Just run the [Helm operator tutorial](https://sdk.operatorframework.io/docs/building-operators/helm/tutorial/) on `v1.0.0`. Was using `operator-sdk` binary created from commit `a805491` with `brew install --HEAD operator-sdk` because `1.0.0` not yet available from `brew`.

**What did you expect to see?**

Was expecting to be able to get an Nginx Deployment with 2 replicas as the tutorial goal.

**What did you see instead? Under which circumstances?**

Operator is deployed correctly into `nginx-operator-system` namespace. As soon as I create a `Nginx` custom resource - using the untouched sample - I got following messages in the manager logs:

```
{"level":"error","ts":1597315650.2143824,"logger":"helm.controller","msg":"Release failed","namespace":"nginx-operator-sample","name":"nginx-sample","apiVersion":"example.com/v1alpha1","kind":"Nginx","release":"nginx-sample","error":"failed to install release: serviceaccounts \"nginx-sample\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/operator-framework/operator-sdk/internal/helm/controller.HelmOperatorReconciler.Reconcile\n\tsrc/github.com/operator-framework/operator-sdk/internal/helm/controller/reconcile.go:181\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90"}
{"level":"error","ts":1597315650.2197773,"logger":"controller","msg":"Reconciler error","controller":"nginx-controller","name":"nginx-sample","namespace":"nginx-operator-sample","error":"failed to install release: serviceaccounts \"nginx-sample\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:237\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90"}
```

I've checked some stuffs like: 
* Is the operator pod running with the `default` serviceaccount ? Yes,
* Is the `default` serviceaccount bound to correct role ? Yes,
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginx-operator-manager-rolebinding
  selfLink: >-
    /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/nginx-operator-manager-rolebinding
  uid: df2874fd-ec84-46a8-ac73-e8edc7316fa9
  resourceVersion: '6643568'
  creationTimestamp: '2020-08-13T10:28:56Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"nginx-operator-manager-rolebinding"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"nginx-operator-manager-role"},"subjects":[{"kind":"ServiceAccount","name":"default","namespace":"nginx-operator-system"}]}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: nginx-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-operator-manager-role
```

I have also tried adding permissions on finalizers for `serviceaccounts` and `services` like below in `nginx-operator-manager-role` but no changes on log messages.
```
- verbs:
    - '*'
  apiGroups:
    - ''
  resources:
    - serviceaccounts/finalizers
    - services/finalizers
```

I have also tried upgrading to `quay.io/operator-framework/helm-operator:latest` but see no changes.

Finally, I've also tried using the officiel `operator-sdk`, `helm-operator` and `ansible- operator` from `v1.0.0` release but face the same issue.

**Environment**
* operator-sdk version:

`operator-sdk version: "a805491", commit: "a805491aeee2333b7c271a5da8232c7bc8d28d25", kubernetes version: "v1.18.2", go version: "go1.14.7 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"`

OR 

`operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"`

* go version: 

`go version go1.14.7 darwin/amd64`

* Kubernetes version information:

`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T23:30:39Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1+3f6f40d", GitCommit:"3f6f40d", GitTreeState:"clean", BuildDate:"2020-06-08T07:13:25Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind: 

OpenShift v4.4

* Are you writing your operator in ansible, helm, or go?

Helm

**Possible Solution**

No suggestions...

**Additional context**

Nope.

**Comment by camilamacedo86** [comment]
Hi @lbroudoux,  

I followed up the tutorial with SDK master which is 1.0.0 and I could not check the need to add any new RBAC permission. 
But, I will try to do that again anyway. 

However, by checking your issue I have some comments that following inline: 

- We will check the homebrew formula in https://github.com/operator-framework/operator-sdk/issues/3738  See that you can install it by the binary since the homebrew formula is not working well. See [here](https://sdk.operatorframework.io/docs/installation/install-operator-sdk/#install-from-github-release).
- The [tutorial](https://sdk.operatorframework.io/docs/building-operators/helm/tutorial/) is for 1.0.0. Could you please use the binary as suggest to follow up the steps?
- Also, could you confirm that your Dcokerfile has the 1.0.0 Helm-base SDK image? 

Regards: 

> I have also tried adding permissions on finalizers for serviceaccounts and services like below in nginx-operator-manager-role

For the new layout the RBCA permissions are in defined in `config/rbac/role.yaml:`. So, if you need to add new permissions you should be updating this file. Could you please check and let us know?

**Comment by lbroudoux** [comment]
Hi @camilamacedo86,

Thanks for answer. My first try was with `HEAD` binaries built using brew but then I did a test with official `1.0.0` binaries downloaded from GitHub. I can also confirm I was using the `1.0.0` Helm-base image. Additional RBAC permissions were added in `config/rbac/role.yaml` as required. 

I was not able to re-try today as my cluster is being upgraded (from OpenShift 4.4 to 4.5) but will re-try on tomorrow.

**Comment by lbroudoux** [comment]
Hi @camilamacedo86,

Just retry on my fresh cluster using `1.0.0` official CLI binaries and got the same error:

```
{"level":"error","ts":1597851515.8393357,"logger":"helm.controller","msg":"Release failed","namespace":"nginx-operator-system","name":"nginx-sample","apiVersion":"example.com/v1alpha1","kind":"Nginx","release":"nginx-sample","error":"failed to install release: serviceaccounts \"nginx-sample\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/operator-framework/operator-sdk/internal/helm/controller.HelmOperatorReconciler.Reconcile\n\tsrc/github.com/operator-framework/operator-sdk/internal/helm/controller/reconcile.go:181\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90"}
{"level":"error","ts":1597851515.8459024,"logger":"controller","msg":"Reconciler error","controller":"nginx-controller","name":"nginx-sample","namespace":"nginx-operator-system","error":"failed to install release: serviceaccounts \"nginx-sample\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:237\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90"}
```

Here is my CLI version: `operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"`. The image used by docker build is `quay.io/operator-framework/helm-operator:v1.0.0`.

I'm pretty sure this is a RBAC permission issue cause as soon as I turn the Operator serviceaccount a `cluster-admin` on my OpenShift cluster (using `oc adm policy add-cluster-role-to-user cluster-admin -z default -n nginx-operator-system` command) operator is now working.

I've seen many similar issues ([here](https://github.com/operator-framework/operator-sdk/issues/1736) and [there](https://access.redhat.com/solutions/5085891) and [also there](https://bugzilla.redhat.com/show_bug.cgi?id=1767806)) but was not able to find the correct resources and permissions that should be set for working on OpenShift.

On this afternoon, I've also developed a Go Operator using `0.19.2` and was facing the exact same issue about not being able to set finalizers on deployments resources ... Pretty strange that out-of-the-box operator-sdk could not build operators that re ready to deploy OpenShift ... I should have missed something ...

Do you have any clue on the correct permissions that should be set ?

Many thanks,

**Comment by camilamacedo86** [comment]
Hi @lbroudoux, 

 > I'm pretty sure this is a RBAC permission issue cause as soon as I turn the Operator serviceaccount a cluster-admin on my OpenShift cluster (using oc adm policy add-cluster-role-to-user cluster-admin -z default -n nginx-operator-system command) operator is now working. 

Yes, the tutorial requires that you have admin permission. I just checked that the Helm tutorial is missing in the pre-requirements `User authorized with cluster-admin permissions` as we have for the Go one. Would you like to do a PR to fix it?

**Comment by lbroudoux** [comment]
Yes, I saw this pre-requisite for Go tutorial and I am actually logged as a `cluster-admin`.
The permission issue is for the `default` service account that runs the Operator : the default roles from `config/rbac/role.yaml` do not allow the operator to deploy new Ngynx instance on OpenShift ...
The only workaround I've found is to turn this service account into a `cluster-admin` which is not great ;-(

**Comment by camilamacedo86** [comment]
Hi @lbroudoux, 

What we need to do is: 

- Ensure that all quickstart and tutorial docs for Ansible/Helm/GO has as Prerequisites `User authorized with cluster-admin permissions`
- Also, would be very nice we have a doc on the website with quite similar info of https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#iam-rolebinding-bootstrap to link on the Prerequisites. We cannot link the cloud.google.com doc, however, it is exactly the info that shows missing.

**Comment by lbroudoux** [comment]
Agreed @camilamacedo86 but this not only a documentation related issue. 

I don't think setting the service account of the operator a cluster admin is a good or normal thing. I think it should have only the minimal permissions for the CR and core resources it manages. 

However, when upgrading from previous versions of the SDK to 1.0.0 it appears that default permissions are not enough for OpenShift. The problem being that I'm not able identifying the minimal set of permissions...

**Comment by camilamacedo86** [comment]
HI @lbroudoux, 

> I don't think setting the service account of the operator a cluster admin is a good or normal thing. I think it should have only the minimal permissions for the CR and core resources it manages.

The quickstart and tutorial are examples for the users getting started. So, it usually would be performed locally by using minikube or kind for example which is the default behaviour by the way. 

Also, note that by default the projects are scaffolded with cluster-scope and will require cluster permissions to apply the ClusterRoles. However, users are able to limit the permissions as well by customizing their project which is a topic described in the documentation [Operator Scope](https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/) and we have an issue to track teh need to create a specific one for Helm/Ansible too.  See https://github.com/operator-framework/operator-sdk/issues/3447

> However, when upgrading from previous versions of the SDK to 1.0.0 it appears that default permissions are not enough for OpenShift. The problem being that I'm not able identifying the minimal set of permissions...

Before version 1.0 the tool generated projects with namespaced scoped which did not require permission as cluster level. However, this concept change for 1.0 as described above. It will scaffold a ClusterRole instead of Role which means that users require permission on the cluster level to apply them.

**Comment by lbroudoux** [comment]
Yes you're right. I think that's a good point! I did not notice that but I will pursue my tests on tomorrow trying to reduce the scope to projet see if default roles work better on OpenShift. 

Will post my observations here and see if it can be useful contributing it to documentation.

Thanks for the replies that help me making my mind in this.

**Comment by camilamacedo86** [comment]
Hi @lbroudoux, 

Really thank you for raising it and for your contribution to the project. I very happy and glad that I could help. 
In your case, you need to change the operator scope. See my comment in: https://github.com/operator-framework/operator-sdk/issues/3447#issuecomment-672928605

**Comment by lbroudoux** [comment]
Hi @camilamacedo86 ,

Have retried today with a namespace scoped operator but facing the exact same issue. Just saw #3767 issue and I am thinking it's the same as mine. Will have a check at the workaround proposal.

Cheers,

**Comment by camilamacedo86** [comment]
Hi @lbroudoux, 

I am closing this one in favour we move forward with https://github.com/operator-framework/operator-sdk/issues/3767#issuecomment-679126939. OK. Please, feel free to help and collab with you wish.
