### ISSUE TITLE
Homebrew stuck on 0.19.2

### ISSUE THREAD

**Issue by chasewalden** [operator-framework/operator-sdk#3738]
## Bug Report

**What did you do?**
```
brew install operator-sdk
```

**What did you expect to see?**
```
==> Upgrading 1 outdated package:
operator-sdk 0.19.2 -> 1.0.0
==> Upgrading operator-sdk 0.19.2 -> 1.0.0
...
==> Installing operator-sdk
==> Pouring operator-sdk-1.0.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/operator-sdk/1.0.0 42 files, 1.21GW
```
**What did you see instead? Under which circumstances?**
```
Warning: operator-sdk 0.19.2 is already installed and up-to-date
To reinstall 0.19.2, run `brew reinstall operator-sdk`
```

https://github.com/Homebrew/homebrew-core/pull/59445

**Comment by estroz** [comment]
We haven't added v1.0.0 to homebrew, and will shortly. Aside: there needs to be a release doc improvement for how to add a new release to homebrew, which doesn't work on some environments.

**Comment by jmrodri** [comment]
The instructions on the release guide do not seem to work on Fedora. There are 2 things that should be done.

1. release v1.0.1 to homebrew (can be done from a Mac if need be)
2. update the instructions to work on Fedora

https://v0-19-x.sdk.operatorframework.io/docs/contribution-guidelines/release/#6-updating-the-homebrew-formula

**Comment by Venkat19967** [comment]
This issue has been solved. Homebrew already has the latest version of Operator SDK
