### ISSUE TITLE
Missing helm-operator-s390x:v1.0.0 image on quay.io

### ISSUE THREAD

**Issue by cheewaio** [operator-framework/operator-sdk#3739]
Hello,

Is it intentional that the base helm-operator v1.0.0 image for s390x is removed / not published on quay.io?
Missing quay.io/operator-framework/helm-operator-s390x:v1.0.0

Thanks

**Comment by estroz** [comment]
@cheewaio travis' s390x support was broken at the time of release, so we decided to push forward with the release sans s390x. I believe their s390x support was fixed recently so we will create either a patch image v1.0.1 or a minor release v1.1.0 including s390x binaries and images.

/priority important-soon
/milestone v1.1.0

**Comment by joelanford** [comment]
@cheewaio we don't have 1.0.0 images posted, but this will be resolved in 1.1 with #3855
