### ISSUE TITLE
Is there a way to add field filter support?

### ISSUE THREAD

**Issue by kotyara85** [operator-framework/operator-sdk#3769]
Hello,
Getting this error on resources generated by operator-sdk
```
$ kubectl get test.example.com --field-selector status.phase=Running
Error from server (BadRequest): Unable to find "example.com/v1, Resource=tests" that match label selector "", field selector "status.phase=Running": field label not supported: status.phase
```

Is there a workaround for this?
Thank you

**Comment by camilamacedo86** [comment]
Hi @kotyara85, 

Could you please provide more info such as following?

- What steps do you perform? 
- What is the doc that you are following up? 
- What is the SDK version used? 

PS.; The issue has a template could you please fill that? Otherwise, we have not enough info to try to help you with.

**Comment by nmaupu** [comment]
I have the exact same question, it's a pity one opens an issue but never follow up...
