### ISSUE TITLE
Enable CRD validation generation for Helm and Ansible

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3770]
## Feature Request

**Is your feature request related to a problem? Please describe.**

When we scaffold a project using a chart for example, the CRs will be automatically created with the [chart values](https://github.com/operator-framework/operator-sdk-samples/blob/master/helm/memcached-operator/helm-charts/memcached/values.yaml) but the CRD will not be created with these data.  

For Go, the CRDs are updated when we run `make manifests` via controller-gen and because of this, the projects pass by default in the `scorecard-test olm-crds-have-validation` which is not achievable with Helm or Ansible.   

For reference using helm operator-sdk-sample:

```
$ cd ~/devel/operator-sdk-samples/helm/memcached-operator
$ operator-sdk scorecard ./bundle --selector=suite=olm

SNIP...
--------------------------------------------------------------------------------
Image:      quay.io/operator-framework/scorecard-test:master
Entrypoint: [scorecard-test olm-crds-have-validation]
Labels:
	"suite":"olm"
	"test":"olm-crds-have-validation-test"
Results:
	Name: olm-crds-have-validation
	State: fail

	Suggestions:
		Add CRD validation for spec field `metrics` in Memcached/v1alpha1
		Add CRD validation for spec field `podAnnotations` in Memcached/v1alpha1
		Add CRD validation for spec field `updateStrategy` in Memcached/v1alpha1
		Add CRD validation for spec field `extraContainers` in Memcached/v1alpha1
		Add CRD validation for spec field `image` in Memcached/v1alpha1
		Add CRD validation for spec field `kind` in Memcached/v1alpha1
		Add CRD validation for spec field `pdbMinAvailable` in Memcached/v1alpha1
		Add CRD validation for spec field `replicaCount` in Memcached/v1alpha1
		Add CRD validation for spec field `securityContext` in Memcached/v1alpha1
		Add CRD validation for spec field `tolerations` in Memcached/v1alpha1
		Add CRD validation for spec field `affinity` in Memcached/v1alpha1
		Add CRD validation for spec field `memcached` in Memcached/v1alpha1
		Add CRD validation for spec field `resources` in Memcached/v1alpha1
		Add CRD validation for spec field `serviceAnnotations` in Memcached/v1alpha1
		Add CRD validation for spec field `AntiAffinity` in Memcached/v1alpha1
		Add CRD validation for spec field `nodeSelector` in Memcached/v1alpha1
		Add CRD validation for spec field `extraVolumes` in Memcached/v1alpha1
	Log:
		Loaded 1 Custom Resources from alm-examples
		Loaded CustomresourceDefinitions: [&CustomResourceDefinition{ObjectMeta:{memcacheds.cac
```

**Describe the solution you'd like**

Have a target similar to [make manifests](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/Makefile#L56-L58) for Helm/Ansible. 

Maybe we could implement a similar feature which would: 

- **For Helm:** Parse the [chart values](https://github.com/operator-framework/operator-sdk-samples/blob/master/helm/memcached-operator/helm-charts/memcached/values.yaml) and update the CRD
- **For Ansible:** Parse the [default/main.yaml](https://github.com/operator-framework/operator-sdk-samples/blob/master/ansible/memcached-operator/roles/memcached/defaults/main.yml) and update the CRD

**Comment by joelanford** [comment]
IMO, we should rely on upstream support for schema validation specifications. See Helm v3's new support, for example: https://github.com/helm/helm/issues/5081

**Comment by joelanford** [comment]
See also: https://helm.sh/docs/topics/charts/#schema-files

**Comment by camilamacedo86** [comment]
I will check it as discussed in the meeting triage. 
We might need to push changes in the upstream in order to let us know easily what would be the attributes and types.

**Comment by camilamacedo86** [comment]
Hi @joelanford, 

I could check that a chart schema was implemented already in Helm(https://github.com/helm/helm/pull/5350). See its [doc](https://helm.sh/docs/topics/charts/): 

> values.schema.json  # OPTIONAL: A JSON Schema for imposing a structure on the values.yaml file

So, for Helm, we could address it by using this schema.

**Comment by camilamacedo86** [comment]
The EP https://github.com/operator-framework/enhancements/pull/25 for OLM also shows requires to parse the chart values to create the manifests.

**Comment by joelanford** [comment]
I have a [working branch](https://github.com/joelanford/operator-sdk/tree/helm-schema) that uses `values.schema.json` if it is present in a chart.

While developing it, I noticed that Kubernetes API server is fairly strict on what it expects to be present or not present in the CRD validation section when converting from `values.schema.json`.

This is a UX problem because the CRD generation appears to work correctly, but an error is surfaced much later when one actually attempts to create the CRD in a cluster. IMO that is a bad user experience, and one we should try to avoid.

**Comment by camilamacedo86** [comment]
The end goal of this issue would be we have a makefile target manifests for Ansible/Go. I will update the first comment to clarifies it.  It cames in the survey so, I am removing the milestone for we have the chance to discuss it again in the bug triage.

**Comment by joelanford** [comment]
I think this is what I used experimenting with Helm: https://github.com/karuppiah7890/helm-schema-gen

**Comment by joelanford** [comment]
If someone cares about this and would like to help us investigate or implement, please reach out to the maintainers to continue the discussion about how this could work.

**Comment by camilamacedo86** [comment]
I am re-open this one. I think that would be very helpful if we would be able to move forward with.

**Comment by tlwu2013** [comment]
It's been observed that more charts started to include `values.schema.json` [file](https://helm.sh/docs/topics/charts/#schema-files) for specifying the structure on the `values.yaml` file.

Looks like there's a huge potential that Helm Operator starts to generate CRD validation stanza based on the existence of `values.schema.json`.
