### ISSUE TITLE
Address e2e test suggestion horizontally. 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3771]
This task is for we address the suggestion made in https://github.com/operator-framework/operator-sdk/pull/3499#discussion_r472553300 for all tests/e2e-tests. 

Edit: suggestion is to prefer `Expect(len(podNames)).To(Equal(1))` to `len(podNames) == 1`

**Comment by prafull01** [comment]
Waiting for #3499 PR to be merged, so that all the tests can be fixed horizontally.

**Comment by joelanford** [comment]
I think this can be improved further to `Expect(podNames).To(HaveLen(1))`

**Comment by prafull01** [comment]
Sure @joelanford , I will take care of that :)
