### ISSUE TITLE
Cannot run kubectl exec into operator's manager container. 

### ISSUE THREAD

**Issue by apm-opentt** [operator-framework/operator-sdk#3774]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
Yes.

## Question
I am not able to `kubectl exec` into the operator's manager container.  It seems all the unix commands are not available in the manager container.
**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).
I ran this command on minikube after doing `make deploy`
`kubectl exec -it -c manager monitoring-operator-controller-manager-5795bd6cb-8qct8 -- /bin/sh`
**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).
I am expecting to get a shell from the `manager` container.
**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).
I got the following error:
```
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
command terminated with exit code 126
```

**Environment**
* operator-sdk version:

  insert release or Git SHA here
`operator-sdk version: "v0.19.2", commit: "4282ce9acdef6d7a1e9f90832db4dc5a212ae850", kubernetes version: "v1.18.2", go version: "go1.14.5 darwin/amd64"`
* Kubernetes version information:

  insert output of `kubectl version` here

* Kubernetes cluster kind: 
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T11:09:22Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
**Additional context**
Add any other context about the question here.
I can `kubectl exec` in the default rbac sidecar but not the manager container.  It seems like the manager's image does not allow any unix commands.

**Comment by estroz** [comment]
The [default base image](https://github.com/kubernetes-sigs/kubebuilder/blob/3eba593/pkg/plugin/v3/scaffolds/internal/templates/dockerfile.go#L62) is [distroless](https://github.com/GoogleContainerTools/distroless#distroless-docker-images), which doesn't contain any shells so won't be able to execute your `exec` command. You can substitute the default image for something like `ubuntu:latest` to do what you want.

**Comment by estroz** [comment]
Closing this, feel free to re-open if my suggestion hasn't resolved your issue.
