### ISSUE TITLE
How to trigger reconciliation for the update to objects not owned by the operator

### ISSUE THREAD

**Issue by harche** [operator-framework/operator-sdk#3784]
## Type of question

How to implement a specific feature 

#### What did you do?

I want to trigger a reconciliation when an object gets updated that's not owned by the operator (e.g. Node). In the earlier version of the SDK it was possible to do that by using `handler.EnqueueRequestsFromMapFunc`, but not sure how will this work in v1.0
 

**Operator type:**

/language go 

**Kubernetes cluster type:**

`$ operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.14.6 linux/amd64", GOOS: "linux", GOARCH: "amd64"
`

`$ go version go1.14.6 linux/amd64
` (if language is Go)

#### Additional context

Prior to v1.0 we were [using](https://github.com/openshift/kata-operator/blob/master/pkg/controller/kataconfig/kataconfig_controller.go#L102)  `handler.EnqueueRequestsFromMapFunc` to watch for the node object updates and trigger the reconciliation.

**Comment by harche** [comment]
cc @camilamacedo86

**Comment by joelanford** [comment]
@harche It is still possible to use `handler.EnqueueRequestsFromMapFunc` in 1.0. If your operator is using the new Builder pattern from controller-runtime, there is a `Watches` function that works the similar to the lower-level controller `Watch` function.

**Comment by harche** [comment]
yeah I converted that function into something like this to watch Node object updates. Haven't tested it though.

```golang
func (r *KataConfigKubernetesReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&kataconfigurationv1.KataConfig{}).
		Owns(&appsv1.DaemonSet{}).
		Watches(&source.Kind{Type: &corev1.Node{}}, &handler.EnqueueRequestsFromMapFunc{
			ToRequests: handler.ToRequestsFunc(func(kataConfigObj handler.MapObject) []reconcile.Request {
				kataConfigList := &kataconfigurationv1.KataConfigList{}
				client := mgr.GetClient()

				err = client.List(context.TODO(), kataConfigList)
				if err != nil {
					return []reconcile.Request{}
				}

				reconcileRequests := make([]reconcile.Request, len(kataConfigList.Items))
				for _, kataconfig := range kataConfigList.Items {
					reconcileRequests = append(reconcileRequests, reconcile.Request{
						NamespacedName: types.NamespacedName{
							Name: kataconfig.Name,
						},
					})
				}
				return reconcileRequests
			}),
		}).
		Complete(r)
}
```

**Comment by joelanford** [comment]
That looks exactly like I would expect. I'll leave this open to let you test this out, but I expect that to work.

**Comment by harche** [comment]
@joelanford Thanks. I will take some time to fix rest of the operator.  I am upgrading the operator which used operator-sdk 0.16.0 to 1.0. Plenty of things have changed in the sdk so I might take some time. Fixing them one at a time. 

I will close this bug for now. If we see the code from https://github.com/operator-framework/operator-sdk/issues/3784#issuecomment-680916015 doesn't work for some reason, I will try to re-open this issue.  

Thanks for your help. I really appreciate it.
