### ISSUE TITLE
operator SDK upgrade v0.18.0 > v1.0.0

### ISSUE THREAD

**Issue by aceeric** [operator-framework/operator-sdk#3790]
I am in the process of upgrading a Go language operator to v1.0.0 originally scaffolded with v0.18.0. I'm following the guidance by creating a new project, and copying the code from the prior project.

This operator watches a CR and creates a few secondary resources - one of which is an OpenShift Route. I'm seeing a new behavior in the 1.0.0 operator in which - when reconciling the route, a call to `Get` returns `StatusReasonNotFound` but then immediately the call to `Create` fails with `StatusReasonAlreadyExists`.  This happens once. The reconciler exits with  the error so the event is requeued and then the second time - it works.

It's benign because it sorts itself out but the behavior is inconsistent with Routes as compared to - say - `Service`, `ServiceAccount`, etc. And - as I said - this is new with the migration to 1.0.0. The relevant code fragment follows. It is unchanged from the code in the prior project that did not exhibit this behavior:
```
func (r *MyReconciler) addOrUpdate(name string, namespace string, expected runtime.Object, found runtime.Object) error {
	err = r.Get(context.TODO(), types.NamespacedName{Name: name, Namespace: namespace}, found)
	if err != nil && apierrors.IsNotFound(err) {
		err = r.Create(context.TODO(), expected)
		if err != nil {
			// this error is "already exists" ??
		}
                ...
```
addOrUpdate would be called thus:
```
func (r *MyReconciler) reconcileOpenShiftRoute(...) {
	...
	expected := r.defaultRoute()
	r.addOrUpdate(routeName, instance.Namespace, expected, &routev1.Route{})
	...
```
and...
```
func (r *MyReconciler) defaultRoute(...) *routev1.Route {
...
```

I'm registering the OpenShift Route with this code:
```
func (r *MyReconciler) registerOpenShiftRoute() error {
	const GroupName = "route.openshift.io"
	const GroupVersion = "v1"
	schemeGroupVersion := schema.GroupVersion{Group: GroupName, Version: GroupVersion}
	addKnownTypes := func(scheme *runtime.Scheme) error {
		scheme.AddKnownTypes(schemeGroupVersion,
			&routev1.Route{},
			&routev1.RouteList{},
		)
		metav1.AddToGroupVersion(scheme, schemeGroupVersion)
		return nil
	}
	schemeBuilder := runtime.NewSchemeBuilder(addKnownTypes)
	return schemeBuilder.AddToScheme(r.Scheme)
}
```
And my watches are configured in my controller (using the new 1.0.0 form):
```
func (r *MyReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&myv1alpha1.CustomResource{}).
		Owns(&appsv1.Deployment{}).
		Owns(&corev1.Service{}).
		Owns(&corev1.ServiceAccount{}).
		Owns(&corev1.ConfigMap{}).
		Owns(&corev1.Secret{}).
		Owns(&routev1.Route{}).
		Owns(&v1beta1.Ingress{}).
		Complete(r)
}
```

Do I need to do something different now to configure how these  resources are cached in my operator? Is it a timing thing? Unclear why a Route would behave differently than "built-in" Kubernetes types like Services, etc. This development is being done on CodeReadyContainers v1.13.0:

```
$ ~/codeready/crc version
CodeReady Containers version: 1.13.0+8070bae
OpenShift version: 4.5.1 (embedded in binary)

$ go version
go version go1.14.2 linux/amd64

$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://api.crc.testing:6443
kubernetes v1.18.3+8b0a82f

$ operator-sdk version
operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 linux/amd64", GOOS: "linux", GOARCH: "amd64"
```

**Comment by joelanford** [comment]
@aceeric There shouldn't be anything substantive that changed between 0.18 and 1.0. SDK 0.18 scaffolds projects using controller-runtime 0.6.0, and SDK 1.0 scaffolds projects using controller-runtime 0.6.2.

Maybe the way 1.0 projects are using controller-runtime has changed in some subtle way, but there's nothing that's jumping out at me that would cause this.

Based on what you're describing, it seems like there's a race populating the cache that the client is using. In your `Reconcile` method, is the route the first child resource that's being reconciled?

**Comment by aceeric** [comment]
Here's the reconcile method so you can see the order. This is called by the reconcile stub that is generated by the operator sdk 1.0.0. The `reconcileAccess` method reconciles either an OpenShift Route or Kubernetes Ingress depending on cluster type:
```
func (r *NuxeoReconciler) doReconcile(request reconcile.Request) (reconcile.Result, error) {
	emptyResult := reconcile.Result{}
	r.Log.Info("Reconciling Nuxeo")

	// Get the Nuxeo CR from the request namespace
	instance := &v1alpha1.Nuxeo{}
	err := r.Get(context.TODO(), request.NamespacedName, instance)
	if err != nil {
		if apierrors.IsNotFound(err) {
			r.Log.Info("Nuxeo resource not found. Ignoring since object must be deleted")
			return emptyResult, nil
		}
		return reconcile.Result{Requeue: true}, err
	}
	// only configure service/ingress/route for the interactive NodeSet
	var interactiveNodeSet v1alpha1.NodeSet
	if interactiveNodeSet, err = getInteractiveNodeSet(instance.Spec.NodeSets); err != nil {
		return emptyResult, err
	}
	if err = r.reconcileService(instance.Spec.Service, interactiveNodeSet, instance); err != nil {
		return emptyResult, err
	}
	if err = r.reconcileAccess(instance.Spec.Access, interactiveNodeSet, instance); err != nil {
		return emptyResult, err
	}
	if err = r.reconcileServiceAccount(instance); err != nil {
		return emptyResult, err
	}
	if err = r.reconcilePvc(instance); err != nil {
		return emptyResult, err
	}
	if err = r.reconcileClid(instance); err != nil {
		return emptyResult, err
	}
	// this results in Deployment create/update
	if requeue, err := r.reconcileNodeSets(instance); err != nil {
		return emptyResult, err
	} else if requeue {
		return reconcile.Result{Requeue: true}, nil
	}
	if err := r.updateNuxeoStatus(instance); err != nil {
		return emptyResult, err
	}
	return emptyResult, nil
}
```
By way of troubleshooting, if I simply put `time.Sleep(time.Second)` *after* the call to `reconcileAccess` where the route is created/updated - the double create problem fully goes away. (Oddly in this case the reconciler fires perpetually even when there is no cluster activity but leave that aside for now.)

The way to trigger the issue is to `kubectl` delete the route while the controller is running and - without the sleep, the first create happens, the controller fires again and the second time through the behavior occurs. Here is `reconcileAccess`:
```
func (r *NuxeoReconciler) reconcileAccess(access v1alpha1.NuxeoAccess, nodeSet v1alpha1.NodeSet,
	instance *v1alpha1.Nuxeo) error {
	...
	if util.IsOpenShift() {
		return r.reconcileOpenShiftRoute(access, forcePassthrough, nodeSet, instance)
	} else {
		return r.reconcileIngress(access, forcePassthrough, nodeSet, instance)
	}
}
```
and `reconcileOpenShiftRoute`:
```
func (r *NuxeoReconciler) reconcileOpenShiftRoute(access v1alpha1.NuxeoAccess, forcePassthrough bool,
	nodeSet v1alpha1.NodeSet, instance *v1alpha1.Nuxeo) error {
	...
		if expected, err := r.defaultRoute(instance, access, forcePassthrough, routeName, nodeSet); err != nil {
			return err
		} else {
			_, err = r.addOrUpdate(routeName, instance.Namespace, expected, &routev1.Route{}, util.RouteComparer)
			return err
		}
	...
}
```
The `addOrUpdate` logic is at the top of this issue. So in summary it really looks to me like with no sleep code, when the reconciler is invoked the second time by the controller runtime either the `client.Get` is returning a false negative on the route or - the timing of the route creation is such that between the call to get and create the route becomes created (seems unlikely to be repeatable).

Why would this only manifest for the route type? That's what originally led me to wonder if something about how I was registering the route caused the caching behavior to be different for this type as compared to the various pre-provided types like services, etc.
```
