### ISSUE TITLE
Add changelog fragments to contribution guide

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#3797]
## Feature Request

Changelog fragments should be documented in either/both: 
 - https://github.com/operator-framework/operator-sdk/blob/master/CONTRIBUTING.MD
 - https://sdk.operatorframework.io/docs/contribution-guidelines/

As far as I can tell, the changelog fragments are only documented in the [template](https://github.com/operator-framework/operator-sdk/blob/master/changelog/fragments/00-template.yaml)

**Comment by theishshah** [comment]
PR #5093 now open

**Comment by theishshah** [comment]
PR Merged
