### ISSUE TITLE
Add high level "Why" document to sdk docs.

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#3800]
## Feature Request

Our docs should explain the reasons for using the operator-sdk, specifically highlighting features that we add that are not in Kubebuilder. This should not be competitive with Kubebuilder, and it should highlight the value we add to base kubebuilder. 

Note: Be clear that distinction is only valid for Go operators.

**Comment by estroz** [comment]
This is done in the FAQ: https://sdk.operatorframework.io/docs/faqs/#what-are-the-the-differences-between-kubebuilder-and-operator-sdk.
