### ISSUE TITLE
service_account.yaml migration in operator-sdk 1.0.0

### ISSUE THREAD

**Issue by Kaitou786** [operator-framework/operator-sdk#3805]
## Type of question

How to implement a specific feature

## Question
Hi, on the migration to operator-sdk-v1.0.0 we noticed that, We define roles above each controller's reconcile method like shown in the [guide](https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/#set-the-rbac-permissions). After defining those and running `make manifests` creates `role.yaml` and `role_binding.yaml` inside `config/rbac/` which similar to previous files `deploy/`. I wanted to know what about the Service Account we used to create to bind this role with, in previous iteration of operator-sdk `service_account.yaml` was created by it, is it changed in this iteration or do we need to create this file ourself?

#### What did you do?
Define RBAC markers on the Reconcile loop

#### What did you expect to see?

Creation of role, role_binding and service_account.yaml files

#### What did you see instead? Under which circumstances?
Only role and role_binding.yaml was created

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

`$ operator-sdk version`

`operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 linux/amd64", GOOS: "linux", GOARCH: "amd64"`
`$ go version` (if language is Go)

`go version go1.14 linux/amd64`

`$ kubectl version`

**Comment by joelanford** [comment]
@Kaitou786 in the 1.0 project layout, the assumption is that the operator will be deployed as cluster-scoped and in it's own namespace, so the role bindings in the config/rbac directory use the `default` service account in that namespace.

If you would like to deploy in a shared namespace, you should be able to add a custom service account resource in `config/rbac`, add it to the kustomization.yaml, and update the `config/rbac/role_binding.yaml` to use it.

**Comment by Kaitou786** [comment]
@joelanford, hi currently our operator do not support the cluster-scoped deployment and only the namespace-scoped deployment, So is there any way to set the RBACs accordingly?.I saw [this](https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#changing-the-permissions) in the documentation but adding this marker and then running `make manifests` changes the namespace in the `role.yaml`, but that too is static, previously we had `WATCH_NAMESPACE` env var set in the operator deployment, how to do similar in this new architecture?

P.S: We're targetting to change our operator design so it is cluster-scoped rather than the namespace-scoped. but until then how can upgrade without this kind of issue?

**Comment by camilamacedo86** [comment]
Hi @Kaitou786, 

The section below the section in the link/document shared with you explains how to use the ENV VAR if you wish as well.

**Comment by Kaitou786** [comment]
Hi @camilamacedo86 I followed that guide and added the helper function along with other changes in role.yaml, `manager.yaml`, `role_binding.yaml` creation of `service_account.yaml` and adding in kustomization.yaml .

Few concerns/questions:

1.) After running `make manifests` the role.yaml is updated again with the name of namespace in metadata, which is static if possible want to remove that entirely
2.) The generate CSV although now have `OwnNamespace` as true in installed types but how do I disable to mark `AllNamespaces` as false in the CSV?
3.) We used to have 2 different roles and 2 different SA for matched to them, I tried adding the second role in `role.yaml` manually but after running `make manifests` that also gets deleted. along with the name of the role that I changed

**Comment by joelanford** [comment]
> 1.) After running make manifests the role.yaml is updated again with the name of namespace in metadata, which we specify above the Reconcile loop, which is static if possible want to remove that entirely

To handle `OwnNamespace`, you just need to make sure to have the `permissions` section of the CSV filled in with the necessary permissions and OLM will make sure to include the right role, role binding, and service account in the operator namespace. The CSV generator should handle this for you in general, though the bug described in #3809 seems related.

To handle `SingleNamespace`, I'm not sure if OLM handles hooking up the correct service account to a role/role binding in the watched namespace for you. If it doesn't you would probably need to use a cluster role binding and cluster role.

@estroz do you know more about how this works?

> 2.) The generated CSV although now have OwnNamespace as true in installed types but how do I disable the AllNamespaces as false in install types in the CSV?

This can be disabled by manually updating `config/manifests/bases/<projectName>.clusterserviceversion.yaml`

That file won't be re-generated unless you re-run `operator-sdk generate kustomize manifests` with `--interactive=true`.

3.) We used to have 2 different roles and 2 different SA for matched to them, I tried adding the second role in role.yaml manually but after running make manifests that also gets deleted. along with the name of the role that I changed.

Can you explain this more? The operator can only run with one service account, right? So what was the second service account used by?

**Comment by estroz** [comment]
>I'm not sure if OLM handles hooking up the correct service account to a role/role binding in the watched namespace for you

I am unsure, but you typically need cluster-level RBAC to handle watching a different namespace. @awgreene might be able to shed light here.

**Comment by Kaitou786** [comment]
> > 1.) After running make manifests the role.yaml is updated again with the name of namespace in metadata, which we specify above the Reconcile loop, which is static if possible want to remove that entirely
> 
> To handle `OwnNamespace`, you just need to make sure to have the `permissions` section of the CSV filled in with the necessary permissions and OLM will make sure to include the right role, role binding, and service account in the operator namespace. The CSV generator should handle this for you in general, though the bug described in #3809 seems related.
> 
> To handle `SingleNamespace`, I'm not sure if OLM handles hooking up the correct service account to a role/role binding in the watched namespace for you. If it doesn't you would probably need to use a cluster role binding and cluster role.
It used to handle the hooking up the correct service account, it had its entry in the CSV itself.
> 
> @estroz do you know more about how this works?
> 
> > 2.) The generated CSV although now have OwnNamespace as true in installed types but how do I disable the AllNamespaces as false in install types in the CSV?
> 
> This can be disabled by manually updating `config/manifests/bases/<projectName>.clusterserviceversion.yaml`
Okay, but is there any option or some marker where I can specify that so it generates the CSV according to the config
> 
> That file won't be re-generated unless you re-run `operator-sdk generate kustomize manifests` with `--interactive=true`.
> 
> > 3.) We used to have 2 different roles and 2 different SA for matched to them, I tried adding the second role in role.yaml manually but after running make manifests that also gets deleted. along with the name of the role that I changed.
> 
> Can you explain this more? The operator can only run with one service account, right? So what was the second service account used by?

Yes, so until now we have 2 SAs, one is for the operator used for deployment of the services offered by it, the other one we used to have for the services which were managed by the operator, the 2nd SA had very fewer perms for the services to query the k8s APIs like for `svc`

**Comment by estroz** [comment]
>is there any option or some marker where I can specify that so it generates the CSV according to the config

No, all you need to do is remove `AllNamespaces` support in your CSV base's (`config/manifests/bases/<projectName>.clusterserviceversion.yaml`) `spec.installModes`:
```yaml
spec:
  ...
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false # Make sure this is false
    type: AllNamespaces
```

This base will be used every time `make bundle` is run, so your CSV in `bundle/manifests/<projectName>.clusterserviceversion.yaml` will always have the same permissions.

>Yes, so until now we have 2 SAs, one is for the operator used for deployment of the services offered by it, the other one we used to have associated with the services which were managed by the operator

If the "other" `ServiceAccount` and `Role` manifests are specified in `config/rbac/kustomization.yaml`, they should be included in any bundle generated by `make bundle`, since that is how `kustomize build config/manifests` includes RBAC files in output:

```yaml
resources:
- role.yaml # Contains "other" role created from markers in controller.go
- other_service_account.yaml # Contains the "other" service account definition
...
```

> I tried adding the second role in role.yaml manually but after running make manifests that also gets deleted

If the marker exists in your controller file, `make manifests` should generate the `Role` you've specified with your marker in `role.yaml`. Are you saying this is not the case?
