### ISSUE TITLE
Instructions on the Getting Started page is mostly outdated for Operator SDK v1.x

### ISSUE THREAD

**Issue by msatyan** [operator-framework/operator-sdk#3816]
Since the Operator SDK v1.x has released, it will be great help if you could update the [Getting Started page](https://github.com/operator-framework/getting-started)  based on this version. The current information in this page is mostly outdated for this version, the project creation itself will fail.

```
operator-sdk new memcached-operator
```
There is no `new` command with this version, for example this is what a user gets.

```
operator-sdk new memcached-operator
Error: unknown command "new" for "operator-sdk"
Run 'operator-sdk --help' for usage.
FATA[0000] unknown command "new" for "operator-sdk"
```
- [v1.x: operator-sdk CLI](https://sdk.operatorframework.io/docs/cli/)
- [v1.x: Quickstart guid](https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/)
There is a Quick start guide for the release version, look like it also has incomplete instruction, it give me error during `make install` phase. Operator SDK is a grate tool, without right set of information it will be difficult for a new users like me to make use of it. Thanks a lot for the grate work.

```
make install
-- -- -- -- --
-- -- -- -- --
/work/dev/go/proj1/bin/kustomize build config/crd | kubectl apply -f -
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
The CustomResourceDefinition "memcacheds.cache.example.com" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
make: *** [install] Error 1
```

FYI: The SDK that I have installed for studying the concept is
```
operator-sdk  version
operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 linux/amd64", GOOS: "linux", GOARCH: "amd64"
```

**Comment by camilamacedo86** [comment]
Thank you for your input, however, the plan is deprecated and archive this repo. 
A lot of improvements as been planned as part of the milestone  [Post 1.0 docs](https://github.com/operator-framework/operator-sdk/milestone/12).

Duplicated of https://github.com/operator-framework/operator-sdk/issues/3741

**Comment by arivatibm** [comment]
I also have this error when using the operator sdk 1.1 quickstart:

```
make install
/Users/ariv/.go/bin/kustomize build config/crd | kubectl apply -f -
The CustomResourceDefinition "memcacheds.cache.example.com" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
make: *** [install] Error 1
```

I'm using operator-sdk version:
operator-sdk version: "v1.1.0", commit: "9d27e224efac78fcc9354ece4e43a50eb30ea968", kubernetes version: "v1.18.2", go version: "go1.15.2 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"
