### ISSUE TITLE
Use the controller-runtime to replace the existing Watch and Handle APIs

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/operator-sdk#382]
The [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) project is a set of libraries used to build controllers.

We've been discussing the use of the controller-runtime to refactor and redesign our existing APIs for a while now to resolve a number of design related issues e.g removing global state(#169), reducing the API surface(#160), support watching multiple custom resources(#146) filtering events on predicates (#268)  

We'll use this issue to track the work needed for refactoring the SDK's informer and client APIs to use the controller-runtime.

**Comment by CSdread** [comment]
Is there a design document for this yet? or will it be hashed out here.

**Comment by hasbro17** [comment]
@CSdread Sorry for the delayed response. There's no design document yet.

Right now we're trying out a basic implementation of the SDK that uses controller-runtime. 
Specifically this entails overhauling the SDK generator pkg to use the [controller-tools generators](https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd) so it can scaffold an operator project that uses the controller-runtime directly (without any abstractions or wrappings from the SDK). 
An example of such a project structure would be something like https://github.com/kubernetes-sigs/controller-tools/tree/master/test
Most likely that will be a separate branch so the reviewers can try it out.

Based on that we can have a design doc or further discussion on how much(if at all) the SDK should encapsulate the controller-runtime library to provide its own APIs. That's still a WIP and I'll update here once we have a reference implementation.

**Comment by hasbro17** [comment]
Tracking the reference implementation for the controller-runtime based SDK in the branch [refactor/controller-runtime](https://github.com/operator-framework/operator-sdk/tree/refactor/controller-runtime)

TODO:
- [x] Make code-generator(only deepcopy) work with multiple apis under pkg/apis https://github.com/operator-framework/operator-sdk/commit/5eb5814c2f5a34d8e653f33dd921eb4956b72336
- [ ] Refactor `operator-sdk new <project>`
    - Only scaffolds a new project with `pkg/cmd/manager`
    - Scaffolds everything except `pkg/apis` `pkg/controller`
- [ ] Add cmd for creating a new api and controller 
    - `operator-sdk add —kind=<Kind> —apiversion=<APIVersion>`
    - Generates pkg/apis and pkg/controller
    - Possibly have sub commands or flags for generating only a new api or new controller
- [ ] Update user-guide and examples for new commands
- [ ] Remove unused sdk pkgs for the dynamic client and handler

Will update the above as I get more into the refactoring.

One thing that the refactoring is partially blocked on is support for namespaced controllers. Trying to fix that upstream https://github.com/kubernetes-sigs/controller-runtime/issues/124

**Comment by hasbro17** [comment]
When the refactor branch is rebased(or merged) on the master, any conflicts should be resolved by overwriting with the refactor branch's changes.
So before merging we need to cherry pick(and modify) the following changes from the master into the refactor branch to make sure the refactor branch has all the changes needed to correctly overwrite the master:
- [ ] Ansible-operator CLI changes. Modified for the new scaffold file generator.
- [ ] Ansible-operator e2e tests to make sure the CI passes for the updated CLI changes
- [ ] Other fixes and improvements to the ansible pkgs on the master #599 

The new docs added for ansible-operator won't conflict with the refactor branch so they strictly don't need to be brought into the refactor branch.

**Comment by shawn-hurley** [comment]
@hasbro17 Can we close this issue now?

**Comment by hasbro17** [comment]
@shawn-hurley Yes thanks for the reminder.
We should be able to close the several other early issues that motivated this one as well.
