### ISSUE TITLE
Kustomize 3.8.2 is not creating the Namespace with the namePrefix

### ISSUE THREAD

**Issue by prometherion** [operator-framework/operator-sdk#3826]
## Bug Report

Using Kustomize 3.8.2 I'm facing this issue as reported [here](https://github.com/clastix/capsule/runs/1056806387)

```
/snap/bin/kustomize build config/default | kubectl apply -f -
namespace/system created
customresourcedefinition.apiextensions.k8s.io/tenants.capsule.clastix.io created
clusterrole.rbac.authorization.k8s.io/capsule-proxy-role created
clusterrole.rbac.authorization.k8s.io/capsule-metrics-reader created
clusterrolebinding.rbac.authorization.k8s.io/capsule-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/capsule-proxy-rolebinding created
mutatingwebhookconfiguration.admissionregistration.k8s.io/capsule-mutating-webhook-configuration created
validatingwebhookconfiguration.admissionregistration.k8s.io/capsule-validating-webhook-configuration created
Error from server (NotFound): error when creating "STDIN": namespaces "capsule-system" not found
Error from server (NotFound): error when creating "STDIN": namespaces "capsule-system" not found
Error from server (NotFound): error when creating "STDIN": namespaces "capsule-system" not found
Error from server (NotFound): error when creating "STDIN": namespaces "capsule-system" not found
Error from server (NotFound): error when creating "STDIN": namespaces "capsule-system" not found
```

`kustomize` is not creating the expected namespace with the prefix (for this OS project, `capsule-system`) but just `system`

#### What did you do?

Using `kustomize@3.8.2`

#### What did you expect to see?

Despite any version, able to install the scaffolded Operator using `make deploy`

#### What did you see instead? Under which circumstances?

I cannot install my scaffolded Operator using `kustomize@3.8.2`

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

N.R.

`$ operator-sdk version`

```
operator-sdk version: "v0.19.2", commit: "4282ce9acdef6d7a1e9f90832db4dc5a212ae850", kubernetes version: "v1.18.2", go version: "go1.13.10 linux/amd64"
```

`$ go version` (if language is Go)

```
go version go1.13.8 linux/amd64
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

#### Possible Solution

Informing with version pinning to 3.8.1 is mandatory, but that would be awkward! :)

#### Additional context

N.R.

**Comment by prometherion** [comment]
Ok, it seems [this](https://github.com/kubernetes-sigs/kustomize/pull/2742) is an expected side-effect.

**Comment by camilamacedo86** [comment]
HI @prometherion, 

if you check the Makefile https://github.com/clastix/capsule/blob/master/Makefile#L106 it specifies the Kustomize version that is supported/tests with the project. However, you should not find issues with a lower upper version since it theoretically has no breaking changes.  

could you please confirm that you just see that issue when you are using this version?

**Comment by prometherion** [comment]
I was able to use `kustomize` without any issue until `3.8.1` and just the `3.8.2` seems to break it.

The issue is that version has been published on `snap` today, so probably nothing to do on Operator SDK side, but just reporting this in case other people would face the same issue due to PATH precedence.

**Comment by camilamacedo86** [comment]
From kustomize 3.8.1 to 3.8.2 should not have breaking changes. I think it shows a bug with could you please raise it there or in kubebuilder(upstream)? 
And then, I think we can agree to close this one. WDYT?

**Comment by joelanford** [comment]
@camilamacedo86 Reading https://github.com/kubernetes-sigs/kustomize/pull/2742, it seems like this change _was_ the bugfix.

@prometherion If you'd like to use `kustomize` 3.8.2+, you can also update the Namespace name in `config/manager/manager.yaml` to the full name (and probably bump the kustomize version in the scaffolded Makefile).

I'll close this since the currently supported kustomize version is 3.5.4 and manually updating the Namespace name in the kustomize base seems to be a working solution as well.

**Comment by camilamacedo86** [comment]
Shows that we need to check that with upstream. Tracked: https://github.com/kubernetes-sigs/kubebuilder/issues/1657
We need to upgrade the dep to solve tech debts and investigate this scenario.

**Comment by basickarl** [comment]
ddfff

**Comment by basickarl** [comment]
> @camilamacedo86 Reading [kubernetes-sigs/kustomize#2742](https://github.com/kubernetes-sigs/kustomize/pull/2742), it seems like this change _was_ the bugfix.
> 
> @prometherion If you'd like to use `kustomize` 3.8.2+, you can also update the Namespace name in `config/manager/manager.yaml` to the full name (and probably bump the kustomize version in the scaffolded Makefile).
> 
> I'll close this since the currently supported kustomize version is 3.5.4 and manually updating the Namespace name in the kustomize base seems to be a working solution as well.

@joelanford  How would one update the `config/manager/manager.yaml` file exactly? What is the `full name`? Is it the `metadata.namespace:`? And if so what should I write there?
