### ISSUE TITLE
[v1] implementing a Watch for a CRD to trigger reconcile loop for another CRD

### ISSUE THREAD

**Issue by balpert89** [operator-framework/operator-sdk#3848]
## Type of question
How to implement a specific feature

#### What did you do?

In pre v0.19.0 operator-sdk versions I have configured watches for one CRD so changes to other CRDs are also triggering a reconcile loop for my CRD. Looks like this:

```
	err = c.Watch(
		&source.Kind{Type: &Contract{}}, &handler.EnqueueRequestsFromMapFunc{
			ToRequests: handler.ToRequestsFunc(func(a handler.MapObject) []reconcile.Request {
				return []reconcile.Request{
					{NamespacedName: types.NamespacedName{
						Name:      "config",
						Namespace: "",
					}},
				}
			}),
		})
	if err != nil {
		return err
	}
```

So changes to `Contract` will trigger the reconcile loop with a `Request` that has the name "config". It is a bit similar to the cluster CRDs found in OpenShift were you also have exactly one instance of the CRD.

#### What did you see instead? Under which circumstances?

In v1 operator-sdk style projects I cannot find to do similar `Watch` definitions. What is the recommended way to solve my use case?

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:** OCP

`$ operator-sdk version`
```
operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 linux/amd64", GOOS: "linux", GOARCH: "amd64"
```

`$ go version` (if language is Go)
```
go version go1.13.15 linux/amd64
```

`$ kubectl version`
```
oc version
Client Version: 4.5.6
Server Version: 4.5.6
Kubernetes Version: v1.18.3+002a51f
```

**Comment by balpert89** [comment]
I think I have solved it myself but I want to await some more thoughts of it.

This is my approach right now:

```
	return ctrl.NewControllerManagedBy(mgr).
		For(&Consumption{}).
		Watches(
		&source.Kind{Type: &Billing{}}, &handler.EnqueueRequestsFromMapFunc{
			ToRequests: handler.ToRequestsFunc(func(a handler.MapObject) []reconcile.Request {
				return []reconcile.Request{
					{NamespacedName: types.NamespacedName{
						Name:      "config",
						Namespace: "",
					}},
				}
			}),
		}).
		Complete(r)
```

**Comment by carlosedp** [comment]
Hi @balpert89, I need to do something pretty similar where my controller needs to watch changes to the cluster Nodes and trigger a reconciliation loop for each CR. The problem with this approach is that there is no CR info (name, namespace) in the `EnqueueRequestsFromMapFunc` function.

Do you have any tips on how I can trigger it? Thanks!

**Comment by carlosedp** [comment]
I ended up watching the external nodes and filtering on some changes, then I trigger a reconciliation for all my CRs.

**Comment by camilamacedo86** [comment]
I understand that, to create a watch for CR's of Kind defined in the operator it would work as any secondary resource that is not managed by the controller such as in the example https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/controller/backup/controller.go#L60-L63 where I am watching a resource that is managed by another controller. 

Note that one of the attributes that can be informed is IsController as false:

```go

      err := c.Watch(&source.Kind{Type: obj}, &handler.EnqueueRequestForOwner{
		IsController: isConttroller,
		OwnerType:    owner,
	})

```

More info: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/handler#EnqueueRequestForOwner

Did you try to solve it in this way?

**Comment by carlosedp** [comment]
I ended up doing something a little more complex as can be seen on:

https://github.com/carlosedp/lbconfig-operator/blob/7c67a134f2681ef656913ffa45a7698019892097/controllers/externalloadbalancer_controller.go#L271

But it worked 👍

**Comment by camilamacedo86** [comment]
It shows answered in the comment https://github.com/operator-framework/operator-sdk/issues/3848#issuecomment-710090557. So, I am closing this one, however, please feel free to ping us if you think that it should be re-opened.
