### ISSUE TITLE
RFE: higher-level object reconciliation

### ISSUE THREAD

**Issue by squeed** [operator-framework/operator-sdk#385]
Something like a `CreateOrUpdate(obj)` method that short-circuits when `obj` already matches the apiserver's object.

It would save a lot of boilerplate to be able to pass a desired state to the operator-sdk, and let it handle the reconciliation with the apiserver.

**Comment by squeed** [comment]
Actually, I still would like something that is more object-aware.

For example, Services can't have the ClusterIP set after creation, so anything that updates a Service needs to pull the ClusterIP from the existing object. Deployments should have their Generation updated. Annotations and Labels need to be merged for all objects. And so on. This is a lot of logic, and it doesn't differ between operators.

**Comment by shawn-hurley** [comment]
This does sound like it might be some nice helpers that we write here, but I am having a hard time determining how. It sounds like a util to merge annotation and merge labels would be helpful.

I am a little more confused on how the first two points would be implemented or even that they are generic enough to include. I very well could be missing something, but once the ClusterIP is set, you should just be getting the object and updating and it failing if ClusterIP is not set seems like the correct thing. I also don't know why an operator should be changing the Generation.

**Comment by estroz** [comment]
@squeed if you've got an idea of how this would be designed/implemented, feel free to make a design doc PR so we can discuss your idea in-depth. Doc template and guidelines are [here](https://github.com/operator-framework/operator-sdk/tree/master/doc/proposals).
