### ISSUE TITLE
How to manage CRDs on a cluster with multiple developers

### ISSUE THREAD

**Issue by tomqwpl** [operator-framework/operator-sdk#3858]
## Type of question

Best practices

## Question

I'm wondering what the best method of managing the custom resource definitions on a cluster is when there are multiple people developing an operator, or as the custom resources evolve. Or dealing with having a "live" version of a CRD alongside a "development" version as it is being developed.

Custom resources are cluster scoped. So if two people are working on changes to the operator that involve additions to the custom resource definitions, those definitions will clash -- there can only be one version of a given CRD installed on the cluster at once. 

Does the operator SDK provide any facilites for this, using kustomize for example, to modify the API group of the CRD to make them unique perhaps?

Or do people deal with this by treating it as a versioning problem, so if you need to change the CRD in any way, create a new version? (my understanding is that this is not the intention in kubernetes -- you are supposed to be make additions to CRDs without changing the versions as I understand it).

Thanks.

**Comment by tomqwpl** [comment]
The page in the documentation entitled "CRD Scope" seems to hint at something, but I don't understand the page. The two example yamls at the bottom are identical as far as I can see, apart from the "scope" value, and this controls whether the CRs that you create that are instances of this CRD are namespace scoped or not, not whether the CRD itself is namespaced, which is what the page seems to be talking about.

**Comment by camilamacedo86** [comment]
Hi @tomqwpl 

**Regards your first comment:** 

shows that your problem is you have more than one person trying to test the same project in the same cluster for development purpose. However, since the CRD is cluster scope it will be a problem because it is valid for all cluster.  

So, first question: Cannot the developers test the operator in their own development environment? Such as in their local machine with minikube or kind? Or have its own OCP instance for example? Why do developers need to share a development environment? 

**Regards your second comment:** 

A CRD with cluster-scoped is valid for all cluster when a CRD with a namespaced scope is valid just for the namespace where it is applied. 

> The two example yamls at the bottom are identical as far as I can see,

If you look the [doc](https://sdk.operatorframework.io/docs/building-operators/golang/crds-scope/) you will see that one CRD has the `spec.scope: Namespaced` and the other `spec.scope: Cluster`.  So, they are not the same. 

To change the CRD scope to namespaced you can do that when you create an API such as `operator-sdk create api --group batch --version v1 --kind CronJob --namespaced=true` or by adding a marker on its `type.go` where the resource is defined and by running `make manifests` to update them.  See the marker ` +kubebuilder:resource:scope=Cluster` on the following example:

```go
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster

// CronJob2 is the Schema for the cronjob2s API
type CronJob2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec   CronJob2Spec   `json:"spec,omitempty"`
	Status CronJob2Status `json:"status,omitempty"`
}
```

**Comment by tomqwpl** [comment]
My comment was:

> are identical as far as I can see, apart from the "scope" value,

I understand scoping as it applies to kubernetes custom resources, but I found this page of the documentation confusing. But let's put that to one side.

You suggest that normal practice, best practice is for developers to have their own local cluster, via Docker Desktop for example. Currently that's against our policy and we are supposed to use the shared development cluster. But even apart from that, the fact that there can only be one CRD of a given Name/Group/Version causes problems for build/test environments as well, or implies that each of those has to be run in its own cluster.

We have experimented with a rather complicated setup where the Group is modified for each developer (me.example.com and you.example.com). It's not ideal, but it would be the kind of thing that would be much better provided by operator-sdk itself. it also realistically means we can't upgrade to a later version of operator-sdk. I'm much rather use vanilla generated operator-sdk code and Makefiles and so on.

**Comment by camilamacedo86** [comment]
Hi @tomqwpl, 

Sorry, but your comments are not clear for me at all. Operator-sdk is a tool responsible to scaffold the project and provide some helpers for developers to build their operator projects to integrate them with OLM. The projects which are scaffold by the default requires cluster-scoped permissions.  However, users are able to customize them as they wish. 

> You suggest that normal practice, best practice is for developers to have their own local cluster, via Docker Desktop for example. Currently that's against our policy and we are supposed to use the shared development cluster. 

I suggest each developer has your own environment. Such as install locally Minikube for example (brew install minikube).
However, if you need to use a shared environment with many people working in the same project then, you cannot use cluster scope permissions. They would need to change all to work just in a namespace for example. However, it would not really make sense if the project requirements and business rules itself requires cluster permissions.  

> that there can only be one CRD of a given Name/Group/Version causes problems for build/test environments as well, or implies that each of those has to be run in its own cluster.

If you create a CRD that is cluster scope then a cluster can have just one CRD. However, it has no relation with SDK at all. It is how Kubernetes API works. See: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/

> We have experimented with a rather complicated setup where the Group is modified for each developer (me.example.com and you.example.com). 

When you create API (CRD) you are extending K8S API and create your own API. The controller will manage any instance of this Kind and by following the design purpose by [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime)  each CRD/KIND should be managed by its own controller. So, I am afraid that it goes against its purposes. 

See that change how CRDs API work is not part of the domain of the SDK tool at all.  

I hope that the above information clarifies. In this way, shows that we have nothing else to address here and I am closing this one. However, please feel free to open issues and your ping us if you need.

**Comment by tomqwpl** [comment]
Kubernetes doesn't allow you to have more than one custom resource definition (i.e resource of Kind CustomResourceDefinition) with the same GVK in the same cluster. This therefore potentially causes problems when trying to develop and test custom resource definitions and operators, so it feels like operator sdk could be in a good place to help with this issue.

One way of solving the problem is to change the api group. If you have two custom resource definitions with the same Kind and Version but different groups, you can run two "versions" of the operator/CRDs at once, they don't interact. You could have a "staging" one for example, or you could have a "tomqwpl" one for a personal development copy. Having to have cluster permissions to install CRDs and so on is an issue, but at least you can run two things side by side.

There are two basic things you need to change. The code of the operator needs to know the Group. This can be achieved by setting an environment variable, in much the same way as is done to communicate which namespaces to watch.
The harder problem is that changes are needed to the kubernetes resource yaml files. The CustomResourceDefinitions need to be modified, as do the Roles/ClusterRoles, and some other things. 

However, now the operator SDK scaffolding makes heavy use of kustomize, it's actually in quite a good position to be able to make these changes as part of that process. It's fairly straightforward to write a kustomize plugin that performs the necessary transformations on the resources, changing the API groups where necessary to add a custom prefix (say). 
It's not a perfect solution. For development I need higher cluster permissions that is ideal. But it would work quite well for creating test or staging versions for example that can then easily be run alongside the "production" one. We can write such a plugin, and we can easily add it into the kustomization file, but if the operatorsdk did it, other people with the same problem would benefit more easily.

The real point of the original question was "why does no one encounter this problem?".  If the answer is that "everyone else has their own personal clusters for development, and has separate clusters for test/staging etc and so the problem doesn't arise" then fine, I can buy that, this is a problem only us or a very small number of people see so it's not worth operatorsdk doing anything about.

**Comment by camilamacedo86** [comment]
Hi @tomqwpl,

The development process as the test process should be done in isolate environments. It is not recommended to test applications in production environments either. 

What you are trying to do shows against the good practices, purpose and design of Kubernetes API. The Kubernetes API allows you to work with multi-versions of the same Kind but its purpose is not for development purposes as you are looking for and you can use the SDK tool to create how many APIs you wish or need.    

> here are two basic things you need to change. The code of the operator needs to know the Group.

What do you mean with?

**Comment by tomqwpl** [comment]
I should perhaps say I'm primarily concerned with a software development environment. I was using "production", "staging" as purely illustrative.
There  are good reasons to use a common shared cluster for development rather than using personal local clusters. In a software development environment, if you're developing, testing and building software that includes custom resources and an operator, the fact that you can can't isolate instances things in a natural way is restrictive. An ordinary kubernetes application I can install multiple copies of it on the same cluster and they don't interact, you just put them in separate namespaces. I can have a development version of the application installed, and someone else can be testing a different version and that's fine. As soon as there's an operator and customer resources involved you can no longer do that, that's the basic driver for this.

With reference to your question, there are two basic places where the Group is references. One is in the go code of the operator, and one is in the kubernetes resources that you have to deploy to cluster (the CRD definition and the operator deployment etc). These can both be reasonably easily dealt with, meaning that it becomes possible, at least in some form, for multiple versions of this application to exist side by side.

**Comment by camilamacedo86** [comment]
Hi @tomqwpl, 

> An ordinary kubernetes application I can install multiple copies of it on the same cluster and they don't interact, you just put them in separate namespaces. I can have a development version of the application installed, and someone else can be testing a different version and that's fine. As soon as there's an operator and customer resources involved you can no longer do that, that's the basic driver for this.

Yes, you can. As described above SDK is just a tool. By creating CRD's you are extending the Kubernetes API. The operators and controller all are from Kubernetes API. Then, If you want to make a CRD available just in a namespace then you need to change its scope from cluster to namespace. Cluster and namespaced scopes are also definitions from Kubernetes API. By default the tool scaffold the projects as cluster scope. However, users are able to change it. 

The steps were described above. See: https://github.com/operator-framework/operator-sdk/issues/3858#issuecomment-688462302

Any resource in Kubernetes API that is cluster-scoped will be valid for all cluster and again it is how Kubernetes works.

> With reference to your question, there are two basic places where the Group references. One is in the go code of the operator, and one is in the Kubernetes resources that you have to deploy to cluster (the CRD definition and the operator deployment etc). These can both be reasonably easily dealt with, meaning that it becomes possible, at least in some form, for multiple versions of this application to exist side by side.

You can use the command `operator-sdk create api` and create how much resources with Group, Kinds and versions as please you. However, as described above the purpose of having a GroupKind with version v1 and other with betav1, for example, has no relation with development purposes.  For further information see Kubernetes doc [Versions in CustomResourceDefinitions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/)

**Comment by camilamacedo86** [comment]
Hi @tomqwpl, 

> An ordinary kubernetes application I can install multiple copies of it on the same cluster and they don't interact, you just put them in separate namespaces. I can have a development version of the application installed, and someone else can be testing a different version and that's fine. As soon as there's an operator and customer resources involved you can no longer do that, that's the basic driver for this.

Yes, you can. As described above SDK is just a tool. By creating CRD's you are extending the Kubernetes API. The operators and controller all are from Kubernetes API. Then, If you want to make a CRD available just in a namespace you need to change its scope from `Cluster` to `Namespaced`. `Cluster` and `namespaced` scopes are also definitions from Kubernetes API. By default the tool scaffold the projects as cluster scope. However, users are able to change it. 

The steps were described above. See: https://github.com/operator-framework/operator-sdk/issues/3858#issuecomment-688462302

Any resource in Kubernetes API that is cluster-scoped will be valid for all cluster and again it is how Kubernetes works.

> With reference to your question, there are two basic places where the Group references. One is in the go code of the operator, and one is in the Kubernetes resources that you have to deploy to cluster (the CRD definition and the operator deployment etc). These can both be reasonably easily dealt with, meaning that it becomes possible, at least in some form, for multiple versions of this application to exist side by side.

You can use the command `operator-sdk create api` and create how much resources with Group, Kinds and versions as please you. However, as described having a GroupKind with version, for example, `v1` and another with `betav1` has not this purpose. For further information see the Kubernetes doc [Versions in CustomResourceDefinitions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/)

I hope that the above info clarifies.

**Comment by tomqwpl** [comment]
I think we're talking at cross purposes in terms of namespace scoped CRDs. I understand that I can define a CRD with "scope=namespace" such that the CRs that you create are themselves namespaced. So I can define a new resource type in kubernetes "Cheeses" so that when I create an instance of a Cheese it will be within a namespace. That's not what I'm talking about. 
I'm talking about this: https://github.com/kubernetes/kubernetes/issues/65551

It's fine. You clearly don't see a problem, so that's fine. We're obviously doing things differently to other people, so will have to solve this ourselves.

**Comment by jlamillan** [comment]
I see this issue is closed, but for sake of clarification and support for the original issue:

- Custom Resource Definitions (CRDs) are only **a cluster cluster-wide resource**, which poses challenges in a multi-developer or multi-tenant environment.
 
- Custom Resources (CRs), which are _instances_ of the CRD, can be namespaced, but that's not what the author is talking about here. 

I agree with the author and wish this issue wouldn't have been closed. It would be nice if Kubernetes had support for or a better answer to actual namespaced CRDs.
