### ISSUE TITLE
Bump to 1.11 dependencies

### ISSUE THREAD

**Issue by rphillips** [operator-framework/operator-sdk#386]
The `node.spec.ConfigMap` API has changed between 1.10 and 1.11; the API uses a ConfigMapRef versus a ConfigMap in the updated version. Perhaps there is a way to do something like this with the older API, but KubeletConfigKey and these structures do not exist:

```go
node.Spec.ConfigSource = &corev1.NodeConfigSource{
		ConfigMap: &corev1.ConfigMapNodeConfigSource{
			Namespace:        cm.Namespace,
			Name:             cm.Name,
			KubeletConfigKey: "kubelet",
		},
}
```

**Comment by joelanford** [comment]
We're on 1.11 dependencies as of 0.0.7, and `master` currently has `1.12` dependencies.
