### ISSUE TITLE
Operator-sdk run packagemanifests does not work on Openshift

### ISSUE THREAD

**Issue by Doout** [operator-framework/operator-sdk#3863]
#### What did you do?
Nothing

#### What did you expect to see?
Operator deploy with `run packagemanifests`

#### What did you see instead? Under which circumstances?
Pod crashloopbackoff with the following log
```
Error: unable to open database file
Usage:
   [flags]

Flags:
  -h, --help               help for this command
  -m, --manifests string   relative path to directory of manifests (default "manifests")
  -o, --output string      relative path to a sqlite file to create or overwrite (default "bundles.db")
      --permissive         allow registry load errors

panic: unable to open database file
```

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`
Latest version

`$ go version` (if language is Go)

1.14.x

`$ kubectl version`

```bash
$ oc version
Client Version: v0.0.0-unknown
Server Version: 4.3.13
Kubernetes Version: v1.16.2
```

#### Possible Solution

Cd into `/tmp` over `/registry`

I also tested it to make sure it works on OCP 4.5.x https://github.com/operator-framework/operator-sdk/compare/master...Doout:fix-ocp-deployment

Another fix will be to give all users write access to `/registry` when building the image. 
#### Additional context

When I debug the pod (oc debug) and found that I get permission denied with touch which I assume the SQL package will also hit this (unable to open database file coming from SQL package)

```
/registry $ touch bundle.db
touch: bundle.db: Permission denied
```

When I run it as root, I face no issues. I assume the permission for /registry folder is not correct when it get deploy on OCP.
On OCP, UID is random while /registry ownership is root and no write access for any user

```
drwxr-xr-x    3 root     root            23 Sep  8 13:12 registry
```

**Comment by camilamacedo86** [comment]
c/c @joelanford

**Comment by joelanford** [comment]
Just posted #3867 to resolve this. 

@Doout Can you test that PR?

**Comment by Doout** [comment]
@joelanford No, I try something very similar to what you did and it fail on `registry-server` part.

Your PR also hit the same issue, I did not have time to look into what `registry-server` try to do but I assume it tries to open some file within the same folder

```
INFO[0000] skipping hidden directory                     dir=/registry/manifests file=..2020_09_10_03_29_09.040564734 load=package
INFO[0000] skipping hidden file                          dir=/registry/manifests file=..data load=package
Error: open db-072840076: permission denied
Usage:
   [flags]

Flags:
  -d, --database string          relative path to sqlite db (default "bundles.db")
  -h, --help                     help for this command
  -p, --port string              port number to serve on (default "50051")
      --skip-migrate             do  not attempt to migrate to the latest db revision when starting
  -t, --termination-log string   path to a container termination log file (default "/dev/termination-log")

time="2020-09-10T03:30:43Z" level=panic msg="open db-072840076: permission denied"
panic: (*logrus.Entry) (0x1138d00,0xc000276150)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000fa000, 0xc0002650e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2db
github.com/sirupsen/logrus.(*Entry).Log(0xc0002760e0, 0xc000000000, 0xc000197f40, 0x1, 0x1)
	/build/vendor/github.com/sirupsen/logrus/entry.go:268 +0xeb
github.com/sirupsen/logrus.(*Logger).Log(0xc0000fa000, 0x0, 0xc000197f40, 0x1, 0x1)
	/build/vendor/github.com/sirupsen/logrus/logger.go:192 +0x7d
github.com/sirupsen/logrus.(*Logger).Panic(...)
	/build/vendor/github.com/sirupsen/logrus/logger.go:233
github.com/sirupsen/logrus.Panic(...)
	/build/vendor/github.com/sirupsen/logrus/exported.go:129
main.main()
	/build/cmd/registry-server/main.go:52 +0xbe
/build $
```
