### ISSUE TITLE
How to watch all CRs with a specific label?

### ISSUE THREAD

**Issue by arivatibm** [operator-framework/operator-sdk#3865]
## Type of question

<-- General operator-related help -->

#### What did you do?

could not find documentation on how to watch all CRs that have a specific label

#### What did you expect to see?

Documentation about this feature

#### What did you see instead? Under which circumstances?

I found this issue - but not sure it is related: https://github.com/kubernetes-sigs/controller-runtime/issues/244

#### Environment

**Operator type:**

<-- /language go -->

**Kubernetes cluster type:**

<-- "OpenShift" -->

`$ operator-sdk version`

operator-sdk version: "v1.0.0-27-g7d672a12", commit: "7d672a1279bc5205e0f5e3c048c5b47dbe364e4e", kubernetes version: "v1.18.2", go version: "go1.15 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"

note that I'm writing the operator based on documentation of v0.19 because v1.0.0 was very buggy and unusable

`$ go version` (if language is Go)

go version go1.15 darwin/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1+3288478", GitCommit:"3288478", GitTreeState:"clean", BuildDate:"2020-07-23T22:24:05Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

#### Additional context

I'm writing an operator that will watch all CRs in a specific namespace and wrap them as Deployables (to be then deployed to a multicluster using IBM MCM or RedHat ACM)

**Comment by estroz** [comment]
https://github.com/kubernetes-sigs/controller-runtime/issues/244 is indeed related. Once that feature is proposed/implemented in controller-runtime, Go projects scaffolded by `operator-sdk` will support it. Since a corresponding issue exists upstream, I'm closing this one.
