### ISSUE TITLE
Ability to use different 'stdout_callback' or set 'callback_whitelist' with Ansible

### ISSUE THREAD

**Issue by geerlingguy** [operator-framework/operator-sdk#3868]
#### Describe the problem you need a feature to resolve.

I would like to debug the performance of my Ansible-based operator, and I want to try to track timing information for the tasks that are run by Ansible in my operator.

In general, when I do this with Ansible outside of an operator, I can add an `ansible.cfg` file to my project or in the default path `/etc/ansible/ansible.cfg` with the following contents:

```
[defaults]
callback_whitelist = profile_tasks
```

This outputs timing information for each task, which is helpful in monitoring if certain tasks perform slowly.

I tried modifying my operator's `Dockerfile` to `COPY` over an ansible.cfg, but it seemed to not affect the output from the operator (manager) container at all; instead, it seems there is some more custom output that displays "Ansible Task Status Event StdOut", with some custom output for the Operator, and 'PLAY RECAP' (which looks like Ansible's output, but without the normal task-by-task output Ansible gives).

I was following logs with:

```
kubectl logs -n memcached-operator-system -l control-plane=controller-manager -c manager -f
```

#### Describe the solution you'd like.

It would be great if there was a way I could use one of Ansible's callback plugins, or had some other way of profiling tasks inside operator runs. I know there's an [`ANSIBLE_DEBUG_LOGS`](https://github.com/operator-framework/operator-sdk/blob/9adf15540db110eb46ea247f8e86bb8068c1a498/website/content/en/docs/building-operators/ansible/development-tips.md#viewing-the-ansible-logs) setting available, but it does not help with profiling tasks or playbook run times, as far as I can tell.

Ideally I could just copy an `ansible.cfg` into place in the `Dockerfile`, and then it would be picked up and used, but it seems the output from (I guess) Ansible Runner might not work cleanly with Ansible callback plugins?

/language ansible

**Comment by fabianvf** [comment]
@geerlingguy the output coming from the container log might not reflect the configuration you provide, as there's a few levels of indirection between the binary, ansible-runner and ansible. The profiling information may show up on the filesystem where runner stores the stdout though, that should be located in `/tmp/ansible-operator/runner/{g}/{v}/{k}/{namespace}/{name}/artifacts/latest/stdout` (where g/v/k/namespace/name match the resource being reconciled)

**Comment by geerlingguy** [comment]
@fabianvf - Ah, perfect! It looks like my custom `ansible.cfg` is getting picked up after all!

I looked at the file `/tmp/ansible-operator/runner/cache.example.com/v1alpha1/Memcached/default/memcached-00/artifacts/latest/stdout` inside the operator manager container, and it had the timings in it:

```
PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Thursday 10 September 2020  18:01:43 +0000 (0:00:02.482)       0:00:03.904 **** 
=============================================================================== 
Gathering Facts --------------------------------------------------------- 1.29s
 ------------------------------------------------------------------------------
start memcached --------------------------------------------------------- 2.48s
/opt/ansible/roles/memcached/tasks/main.yml:4 ---------------------------------
```

**Comment by geerlingguy** [comment]
Just leaving a reciprocal link to the repo where I'm working on this: https://github.com/geerlingguy/operator-sdk-performance-testing/issues/14
