### ISSUE TITLE
SDK provides a test-framework library to let operators run e2e tests

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/operator-sdk#387]
E2e tests are the most common way to test the reconciliation logic of an operator.
e.g: [etcd-operator e2e](https://github.com/coreos/etcd-operator/tree/master/test/e2e), [prometheus-operator e2e](https://github.com/coreos/prometheus-operator/tree/master/test).
Currently users have to write their own  e2e frameworks from scratch to test their SDK based operators. 

The SDK can provide a test-framework library that would abstract out the common functionality needed by all e2e tests e.g setup/teardown (namespace, rbac, operator deployment) along with any other necessary testing utilities.
The SDK could also provide a standard way to run a users e2e tests e.g 
`operator-sdk test <path-to-e2e-tests> --kubeconfig=<kubeconfig>`

Since the goal is to make it easier to write and run e2e tests for SDK based operators we'll need to determine how much value would such a test-framework actually provide.
This can be determined by considering:
- how much duplication and work can the test-framework abstractions actually reduce vs providing thin wrappers around existing utilities
- how simple is the workflow of using the test-framework vs writing your own framework from scratch and running `go test ...` 

#377 provides a starting point for what such a framework could look like. We'll use that to iterate on the workflow and abstractions of the test-framework library.

**Comment by AlexNPavel** [comment]
Initial framework was implemented and merged with #377. Further work that will be added as separate PRs:
- [ ] Allow users to pass abritraru flags and arguments to `go test`
- [ ] Allow a user to add their own scheme to the dynamic client and get rid of some of the hacky CRClient stuff

**Comment by hasbro17** [comment]
Closing this. We have the follow up work for packaging the e2e tests with the operator outlined in #435
