### ISSUE TITLE
RHSA-2020:3658 vulnerability found in Helm operator docker image 1.0.0 

### ISSUE THREAD

**Issue by ccgagnon** [operator-framework/operator-sdk#3870]
#### What did you do?
Scanning the Docker image with Snyk and got High vulnerabilities

#### What did you expect to see?
No vulnerabilities

#### What did you see instead? Under which circumstances?
librepo package versions <0:1.11.0-3.el8_2 affects the current image https://quay.io/repository/operator-framework/helm-operator/manifest/sha256:a6e23dc4f9a14253f2b13c4a1aa4fb1fc116ed347916f3fbdd4b3579d33ea491

https://app.snyk.io/vuln/SNYK-RHEL8-LIBREPO-610057

https://access.redhat.com/errata/RHSA-2020:3658

#### Environment

**Operator type:**

Helm operator

#### Additional context

Dockerfile base image:
`FROM registry.access.redhat.com/ubi8/ubi-minimal:latest`
The latest deployed ubi8 image has the vulnerability fix, but the helm operator one wasn't updated

**Comment by joelanford** [comment]
@ccgagnon We don't rebuild existing images upstream. We've added this to the v1.0.1 milestone, so this will be resolved when we release v1.0.1 (and the latest base image fixes are automatically pulled in).

**Comment by ccgagnon** [comment]
Thank you @joelanford. Do you have an ETA to when 1.0.1 would be released?

**Comment by joelanford** [comment]
@ccgagnon we just finished the v1.0.1 release. The `latest` and `v1.0.1` now pass the security scan.

**Comment by ccgagnon** [comment]
> @ccgagnon we just finished the v1.0.1 release. The `latest` and `v1.0.1` now pass the security scan.

Perfect thank you!
