### ISSUE TITLE
Custom column output that combines struct values

### ISSUE THREAD

**Issue by dbainbri-ciena** [operator-framework/operator-sdk#3872]
## Type of question

Best practices
How to implement a specific feature

#### What did you do?

for `kubebuilder:printcolumn` I would like to combine several fields from a sub-resource. I tried several things including

JSONPath="{.spec.Sub.Foo}/{.spec.Sub.Bar}" // which works with `kubectl -o jsonpath`, but is rejected when i do a `make` as not "simple"

JSONPath="{.spec.Sub.*}" // again works with `kubectl -o jsonpath`, compiles and gives "random?" output 

#### What did you expect to see?

I would like an output of either `val1/val2` or `val1 val21`, really something more human-readable than `map[...]`

#### What did you see instead? Under which circumstances?

either build failed or output was blank or random value from sub resource

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

vanilla

`$ operator-sdk version`

```
operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.14.2 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"
```

`$ go version` (if language is Go)

```
go version go1.14.2 darwin/amd64
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by joelanford** [comment]
The `kubebuilder:printcolumn` marker is used to populate the CRD's [`spec.versions.additionalPrinterColumns` fields](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns). 

The underlying tool that's used to generate the CRD (controller-gen) is populating the `spec.versions.additionalPrinterColumns.jsonPath` field from the marker value.

Are you able to directly set a "complex" `jsonPath` value on the CRD? I suspect that this is a constraint of the Kubernetes CRD API, not something in controller-gen or operator-sdk.

**Comment by dbainbri-ciena** [comment]
confirmed that this error is coming when `kubectl apply -f` is being called, so not related to operator-sdk. i wonder if you can added a customer "format" to manage this. sort of disappointing if you can't somehow customize this.

**Comment by joelanford** [comment]
@dbainbri-ciena [This issue](https://github.com/kubernetes/kubernetes/issues/67268) seems to be the closest I can find to discussion about what you're asking for. It looks like there was some appetite for improvement here, but so far no one has pushed this along.

**Comment by dbainbri-ciena** [comment]
Thanks. Appreciate the pointer. It does look like interest has faded.
