### ISSUE TITLE
Helm RBAC roles scaffolded are not idempotent

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3873]
#### What did you do?

Generate the Helm Sample using the [script](https://github.com/operator-framework/operator-sdk-samples/blob/master/helm/.generate/gen-helm-memcached.sh) with a Kind cluster up and without a cluster running. 

#### What did you expect to see?

- I would expect to see more roles when the plugin is able to get a kubeconfig than when it is NOT.
- I would expect to see in all scenarios the verbs instead of `*` 

#### What did you see instead? Under which circumstances?

- The roles "better" populated when the kubeconfig is not found  (no cluster up).
- The roles with `*` instead of the verbs when the kubeconfig is found. 

#### Environment

**Operator type:**

/language helm 

**Kubernetes cluster type:**

Kind

`$ operator-sdk version`

b9bf0f436b0eddce80ec6f6c41278cb8e2a77684

#### Possible Solution

- Remove the `NewDiscoveryClientForConfig` and keep it with an idempotent result. 

#### Additional context

Code;

https://github.com/operator-framework/operator-sdk/blob/24d73f782af630f26d3600530fb9b46e6878fc57/internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/manager_role.go#L97-L103

Changes/diff : 

<img width="1283" alt="Screen Shot 2020-09-12 at 02 09 02" src="https://user-images.githubusercontent.com/7708031/92983897-23bfbd80-f49e-11ea-8628-96da377e9b6a.png">

**Comment by camilamacedo86** [comment]
c/c @joelanford

**Comment by joelanford** [comment]
> I would expect to see more roles when the plugin is able to get a kubeconfig than when it is NOT.

When there isn't a cluster available, the role generator will use the [default ruleset](https://github.com/operator-framework/operator-sdk/blob/4fe0e7316150cfe02d38d83debeba9dc0420cf8a/internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/manager_role.go#L171-L204), which is fairly broad in order to allow most charts that use built-in APIs to work without further modification.

When there is a cluster available, the role generator will template the default chart, lookup each of the resources in the generated manifest using the discovery API, and then generate a rule set that is tailored to those resources.

There is no expectation that the generated rule set from the manifest and lookup will be smaller or larger than the default rule set because some charts will have a small number of resources, and others will have a large number of resources.

> I would expect to see in all scenarios the verbs instead of *

Is there a reason that an explicit set of verbs is better than [`*`, which means all verbs](https://github.com/kubernetes/api/blob/c34296b27d3387ab4473d3bf565acf20fe5192e9/rbac/v1/types.go#L31)?

---

In an ideal world, we would use the discovery API during sample generation, which would give us the more tailored rule set. The implication is that we would need a cluster available during the sanity tests, which would definitely increase the time it takes to setup (and therefore run) the sanity tests.

We'll have to decide if that's a trade-off we're willing to make.

**Comment by camilamacedo86** [comment]
Hi @joelanford 

Thank you for your reply. Following some comments: 

**Keep the `NewDiscoveryClientForConfig ` based on (see [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege)) shows go against the strattgey adopted ** 

If we are following the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege)) why we would grant cluster-scoped permissions instead of the namespaced one? 

Shows not concise and accurate the project tries to persuade the goal of following the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege)) for Helm RBAC roles when granting cluster-scope permissions (it shows an inconsistent strategy across the board. Or we will follow this principle and be ok to make harder users getting started with since they usually will face issues or we are permissive related to the permissions and make it easier for them. However, in POV we need a consistence strategy here. Otherwise, the idea that they need to be customized the RBAC permission according to their business is not clear enough. 

**`NewDiscoveryClientForConfig` is not precisely anyway and the tool asks for users check the RBAC. So, what is the real value on keeping it for users and us? How helpful this behaviour is for them?**

Check the msg/output when it is used:

> WARN[0000] The RBAC rules generated in config/rbac/role.yaml are based on the chart's default manifest. Some rules may be missing for resources that are only enabled with custom values, and some existing rules may be overly broad. Double check the rules generated in config/rbac/role.yaml to ensure they meet the operator's permission requirements

They need to customize their RBAC permissions anyway.  

**IHMO: I am as users and/or maintainer would prefer an idempotent behaviour and a consistency strategy across the project**

> Is there a reason that an explicit set of verbs is better than *, which means all verbs?

See: Replace Role verb `"*"` with a list of verb strings in generated files so the Role is compatible with OpenShift and Kubernetes. ([#2175](https://github.com/operator-framework/operator-sdk/pull/2175))

**Comment by joelanford** [comment]
> See the issue #671 which motivates us to replace * by the verbs.

It seems like we could do this, but is generally unrelated to this issue.

> If we are following the principle of least privilege, why we would grant cluster-scoped permissions instead of the namespaced one?

We made a broader decision based on Kubebuilder defaults (and the fact that CRDs and webhooks are cluster-scoped objects) to default operator projects to be cluster-scoped. Given that decision, the principal of least privilege would direct us to give the operator the minimal set of permissions to enable it to do its job across the cluster.

> What is the real value on keeping it for users and maintainers?

Users get actual RBAC rules tailored to their operator. While not perfect, it gets them _MUCH_ closer than the default rules do AND it does it without giving the operator unnecessary privileges.

> How helpful or not is this behaviour for both?

IMO, very helpful. It means users don't have to spend as much time figuring out what permissions are necessary for their operator.

> Is theNewDiscoveryClientForConfig bringing advantages that justify the cost of maintaining this behaviour?

IMO, yes.

This is one of the _killer_ features of the Helm operator. It enables users to focus their time and effort of developing their helm chart, and then using the operator-sdk to package it into an operator with extremely low effort (to the point that some users may be building and packaging an operator entirely in a CI pipeline).

---

Lastly, users running `operator-sdk create api` in a script to automatically generate operators from charts would be broken. Therefore getting rid of the role generation would be a breaking change, so we can't remove it until _at least_ 2.0 anyway.

**Comment by joelanford** [comment]
Closing since we can't make this change right now.
