### ISSUE TITLE
Dynamically set namespaced in Golang example

### ISSUE THREAD

**Issue by danielc103** [operator-framework/operator-sdk#3875]
## Type of question

Best practices 
How to implement a specific feature

#### What did you do?

Followed instructions on https://sdk.operatorframework.io/ to setup Golang memcached-operator.  I want to dynamically set namespaced operator scope.  Following the instructions I created the helper function and modified the `manager.yaml` as described and modified the `role.yaml` and `role_binding.yaml` to use role and rolebinding. 

#### What did you expect to see?

The memcached-operator to deploy and work only in set namespace

#### What did you see instead? Under which circumstances?

ClusteRoles install and permissions error on operator.  Memcached manager role still gets installed as ClusterRole.

```cli
2020-09-13T12:58:53.095Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"ConfigMap","namespace":"default","name":"f7b7e447.cats","uid":"7068dba9-8970-4cb1-a747-e4c7d040c82f","apiVersion":"v1","resourceVersion":"746"}, "reason": "LeaderElection", "message": "memcached-operator-controller-manager-68f5b47c84-66k8r_ce5841f8-5346-4493-bb20-d06a47e3a6f1 became leader"}
E0913 12:58:53.100861       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1alpha1.Memcached: memcacheds.cache.cats is forbidden: User "system:serviceaccount:default:default" cannot list resource "memcacheds" in API group "cache.cats" in the namespace "default"
E0913 12:58:54.439101       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1alpha1.Memcached: memcacheds.cache.cats is forbidden: User "system:serviceaccount:default:default" cannot list resource "memcacheds" in API group "cache.cats" in the namespace "default"
E0913 12:58:56.742417       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1alpha1.Memcached: memcacheds.cache.cats is forbidden: User "system:serviceaccount:default:default" cannot list resource "memcacheds" in API group "cache.cats" in the namespace "default"
E0913 12:59:01.309650       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1alpha1.Memcached: memcacheds.cache.cats is forbidden: User "system:serviceaccount:default:default" cannot list resource "memcacheds" in API group "cache.cats" in the namespace "default"
E0913 12:59:12.111160       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1alpha1.Memcached: memcacheds.cache.cats is forbidden: User "system:serviceaccount:default:default" cannot list resource "memcacheds" in API group "cache.cats" in the namespace "default"
```

Make install keeps switching role back to clusterrole.

#### Environment

**Operator type:**

 /language go

**Kubernetes cluster type:**

minikube 1.12.1
kuberentes 1.183

`$ operator-sdk version`

v1.0.0

`$ go version` (if language is Go)

 go1.14.5 linux/amd64

`$ kubectl version`

```cli
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

#### Additional context

I'm sure I'm missing something, any help or direction would be greatly appreciated. 

 `make manifest` command modifies the role every time. The instructions suggest modifying the RBAC markers but that requires a hard coding of the namespace.

**Comment by camilamacedo86** [comment]
@estroz one of these steps required to be done manually. See that we have an issue open in KB regards this specific step: https://github.com/kubernetes-sigs/kubebuilder/issues/1496

**Comment by danielc103** [comment]
```golang
// +kubebuilder:rbac:groups=webapp.my.domain,namespace=default,presources=guestbooks,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=webapp.my.domain,namespace=default,resources=guestbooks/status,verbs=get;update;patch
```

Does changing the kubebuilder tag with namespace default "hard code" that default namespace into role and binding?

**Comment by estroz** [comment]
@danielc103 it does, but when you run `make deploy`, `kustomize` will substitute that `Role`'s namespace with whatever is in your `config/default/kustomization.yaml`. You can set `namespace=default` for your purposes.

You will also have to update `config/default/role_binding.yaml` to bind your new `Role` by removing "Cluster" from the file (ex. `ClusterRoleBinding` -> `RoleBinding`).

If this works, feel free to close this issue.

**Comment by danielc103** [comment]
@estroz , @camilamacedo86  that worked, thank you.  I also some artifacts left over from earlier testing (didn't cleanup well).
