### ISSUE TITLE
make manifest (controller-gen) ignores config kustomization.yaml

### ISSUE THREAD

**Issue by drewwells** [operator-framework/operator-sdk#3880]
#### What did you do?

1. modified config/crd/crd/kustomization.yaml to include commonAnnotations.
2. execute make manifests (which executes controller-gen)
3. see that CRDs were not updated to include mutations.

#### What did you expect to see?

I expected to see the output given this kustomize command which produces a slight variation of the CRD definitions.
```
kustomize build config/crd
```

#### What did you see instead? Under which circumstances?

The CRDs are generated by controller-runtime, but any changes in kustomize.yaml is ignored. This is also true for the config/rbac/kustomization.yaml file that generates rbac yaml.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**
vanilla, kind

`$ operator-sdk version`
```
operator-sdk version                                                  
operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 linux/amd64", GOOS: "linux", GOARCH: "amd64"
```

`$ go version` (if language is Go)
1.14.2

`$ kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"f3add640dbcd4f3c33a7749f38baaac0b3fe810d", GitTreeState:"clean", BuildDate:"2020-05-20T14:00:52Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-28T22:11:08Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aemperador** [comment]
@drewwells could you provide your Makefile or your Make `manifests` target? My assumption is that the `kustomize build` isn't being applied to the cluster. The `kustomize build` will provide the new yaml, but it needs to be piped/placed somewhere. Ex: https://kubernetes-sigs.github.io/kustomize/guides/offtheshelf/#4-bring-up-variants

**Comment by drewwells** [comment]
Sorry I'm not clear in the description, operator-sdk uses controller-gen to generate the CRD yaml. However, controller-gen is not picking up any settings in kustomization.yaml.

**Comment by joelanford** [comment]
@drewwells `controller-gen` doesn't know about `kustomize`. It generates base files from your API definitions and then `kustomize build` reads those base files and applies any configurations and patches that are defined by `kustomization.yaml`.

The default project configuration does not directly persist the kustomize output. Instead `kustomize` is used in other make targets (i.e. `install`, `deploy`, `bundle`, etc.) to generate the final desired output on the fly.

**Comment by drewwells** [comment]
Okay thanks. So we can’t inject common annotations in one step, it has to be layered on top of the controller gen output.

**Comment by joelanford** [comment]
You _could_ do something like this in your Makefile if you wanted a single step to build the full resource manifests:

``` Makefile
deploy.yaml: manifests
	kustomize build config/default > deploy.yaml
```

And then running `make deploy.yaml` would run controller-gen and then immediately run `kustomize` to output the final manifest containing all of the patches, commonAnnotations, and any other `kustomize`-based changes.
