### ISSUE TITLE
Use `Expect(err).NotTo(HaveOccurred())` instead of `Expect(err).Should(Succeed())`

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-sdk#3896]
> Nit: I know this is a backport and this line is basically unchanged in this PR but for better readability this probably should be:
> ```Go
> Expect(err).NotTo(HaveOccurred())
> ```
> `Succeed()` is used more for the function itself:
> ```Go
> Ω(DoSomethingSimple()).Should(Succeed())
> ```
> https://onsi.github.io/gomega/#handling-errors

_Originally posted by @hasbro17 in https://github.com/operator-framework/operator-sdk/pull/3895#discussion_r489929125_

**Comment by DanielXLee** [comment]
@joelanford can I take this issue?

**Comment by camilamacedo86** [comment]
HI @DanielXLee, 

Please, feel free to help with.

**Comment by DanielXLee** [comment]
Thanks @camilamacedo86
/assign DanielXLee
