### ISSUE TITLE
[Website] Link in Envtest Setup page is broken

### ISSUE THREAD

**Issue by abkieling** [operator-framework/operator-sdk#3900]
#### What did you do?

1. Open the Operator SDK website
1. Navigate to the Envtest Setup page: https://sdk.operatorframework.io/docs/building-operators/golang/references/envtest-setup/
1. Click on "this script" link in the first paragraph

#### What did you expect to see?

I expected to see the script source

#### What did you see instead? Under which circumstances?

A "404: Not Found" error message

**Comment by camilamacedo86** [comment]
It is solved for master branch already. See: https://master.sdk.operatorframework.io/docs/building-operators/golang/references/envtest-setup/

It will get fixed when we release a new 1.0.X version. 

Thank you for raise. 👍
