### ISSUE TITLE
[helm operator] cluster resources were not cleaned up after a installation failure

### ISSUE THREAD

**Issue by liqlin2015** [operator-framework/operator-sdk#3911]
## Bug Report

Sometimes cluster resource like clusterrole, scc were not cleaned up after a installation failure

#### What did you do?

Tried to install by helm based operator in OCP 4.5 cluster. Sometimes the operator failed to install the helm release due to the failure that resource already exists. See the error from operator
```
{"level":"error","ts":1600391663.8330877,"logger":"controller","msg":"Reconciler error","controller":"nginxingress-controller","name":"default","namespace":"services","error":"failed to install release: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole \"ingress-clusterrole\" in namespace \"\" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key \"app.kubernetes.io/managed-by\": must be set to \"Helm\"; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to \"default\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be set to \"services\"",
```

#### What did you expect to see?

Helm release should be able to install successfully even the resource already existed.

#### What did you see instead? Under which circumstances?

Helm release failed to install.

#### Environment

**Operator type:**

OCP 4.5

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by joelanford** [comment]
@liqlin2015 The Helm operator uses Helm's underlying installation, upgrade, and uninstall code to give users a familiar and predictable experience. As far as I know, Helm does not have a mechanism to allow adopting existing resources during installation. That would need to be a new feature added to Helm.

May I ask how those existing resources were initially created? Is this a situation where the there was some sort of partial helm-operator-based installation that failed and those resources weren't properly cleaned up before attempting a re-installation?
