### ISSUE TITLE
Negative integer default values for schema generation are generated as string literals

### ISSUE THREAD

**Issue by mjovanovic0** [operator-framework/operator-sdk#3913]
#### What did you do?

I want to generate OpenAPIv3 schema that has a field with default value of -1 (or any negative number).
This is probably bug within kubebuilder rather then operator-sdk.

In go struct I have following:

```go
// +kubebuilder:default=-1 
ConnectionLimit int `json:"connectionLimit"`
```

This will generate OpenAPIv3 schema as following:

```yaml
connectionLimit:
  default: "-1"
  type: integer
```

Default value is setted as string literal instead of number when default value is negative value.
For positive numbers, schema is generated correctly:

```go
// +kubebuilder:default=3
ConnectionLimit int `json:"connectionLimit"`
```

Would output:

```yaml
connectionLimit:
  default: 3
  type: integer
```

#### What did you expect to see?

Expected following OpenAPIv3 schema to be generated:

```yaml
connectionLimit:
  default: -1
  type: integer
```

#### What did you see instead? Under which circumstances?

Default value for any negative number would be generated as string literal. Zero and positive number will be properly generated.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

Not applicable but, tested with: 
- minikube v1.12.3
- OpenShift v3.11.216 (Kubernetes v1.11.0+d4cacc0)
- OpenShift v4.5.8 (Kubernetes v1.18.3+6c42de8)

`$ operator-sdk version`
```
operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.14.7 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"
```

`$ go version` (if language is Go)
```
go version go1.15 darwin/amd64
```

`$ kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"5e7af8cc3c5694f7cc22ae3f2f1e54cccc485afe", GitTreeState:"clean", BuildDate:"2020-08-28T03:42:46Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+6c42de8", GitCommit:"6c42de8", GitTreeState:"clean", BuildDate:"2020-08-29T05:03:41Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by camilamacedo86** [comment]
HI @mjovanovic0, 

Thank you for raising that. See that this implementation came from the controller-tools and it has been addressed in the upstream/kubebuilder into the issue: https://github.com/kubernetes-sigs/kubebuilder/issues/1634.

Could you please try use `// +kubebuilder:default="-1"` and answer in there? 

I am closing this one here since it has been addressed in the upstream already.
