### ISSUE TITLE
"make tidy" fails to finish when trying to build operator-sdk from source ( build from master )

### ISSUE THREAD

**Issue by ekuric** [operator-framework/operator-sdk#3923]
#### What did you do?
trying 

$ git clone https://github.com/operator-framework/operator-sdk
$ cd operator-sdk
$ git checkout master
$ make tidy
$ make install

following instructions from 
->  https://sdk.operatorframework.io/docs/installation/install-operator-sdk/#compile-and-install-from-master

#### What did you expect to see?
`make tidy` to finish 

#### What did you see instead? Under which circumstances?

```
$ make tidy
go: k8s.io/kubectl@v0.18.2 requires
	vbom.ml/util@v0.0.0-20160121211510-db5cfe13f5cc: unrecognized import path "vbom.ml/util": https fetch: Get "https://vbom.ml/util?go-get=1": dial tcp: lookup vbom.ml on 10.38.5.26:53: no such host
make: *** [Makefile:83: tidy] Error 1
```

#### Environment
Fedora 32
$ go version 
go version go1.14.7 linux/amd64

**Operator type:**
language go

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)
go version go1.14.7 linux/amd64

#### Possible Solution
in this link 
https://github.com/operator-framework/operator-sdk/issues/3859
it says that it will work with older go version, but Fedora 32 ships  go1.14.7  version and it would be good if building operator with it works too

**Comment by ekuric** [comment]
seems this note `Note: Ensure that your GOPROXY is set with its default value for Go versions 1.13+ which is https://proxy.golang.org,direct.` from https://sdk.operatorframework.io/docs/installation/install-operator-sdk/#compile-and-install-from-master is necessary in order to make this working. Works after setting GOPROXY to above value. ... I think this can be closed.

**Comment by camilamacedo86** [comment]
Thank you @ekuric.
I am closing this one. Feel free to raise new issues if you need.
