### ISSUE TITLE
Unable to set apiextensions.k8s.io/v1 using crd-version args in operator-sdk v1.0.1

### ISSUE THREAD

**Issue by kprasad99** [operator-framework/operator-sdk#3924]
## Type of question

 General operator-related help

#### What did you do?

Trying to generate CRD using `operator-sdk` `v1.0.1`, since my target k8s cluster is v1.19.0, want to generate CRD with `apiVersion` `v1` instead of `v1beta1`. as per the release note of [v0.17.0](https://github.com/operator-framework/operator-sdk/releases/tag/v0.17.0) an argument was added to `new/add api` commands. However these commands have been replaced with `init and create` command respectively but there is no crd-version argument. 

#### What did you expect to see?

Generate CRD with `apiVersion` as v1 either by default or through arguments while using `create api` command.

#### What did you see instead? Under which circumstances?

Generated CRD file has `apiVersion`  `v1beta1` in file `./config/crd/bases/<filename>.yaml`

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
```

#### Environment

**Operator type:** Ubuntu.20.04
**K8s Flavor:** Microk8s
**K8s Version:** 1.19.0

/language go

**Kubernetes cluster type:**

vanilla,[microk8s]

`$ operator-sdk version`

```
operator-sdk version: "v1.0.1", commit: "4169b318b578156ed56530f373d328276d040a1b", kubernetes version: "v1.18.2", go version: "go1.13.15 linux/amd64", GOOS: "linux", GOARCH: "amd64"
```
`$ go version` (if language is Go)

```
go version go1.15.2 linux/amd64
```

`$ kubectl version`

```
lient Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-34+09a4aa08bb9e93", GitCommit:"09a4aa08bb9e9328ae83e818c400278f5c43db3a", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:25Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by joelanford** [comment]
For Go operators, Operator SDK now uses `kubebuilder`'s Go plugin for scaffolding files, and that plugin does not currently support a flag to choose the CRD version.

However, this is now configurable in your Makefile. Find the line that sets `CRD_OPTIONS` and add `crdVersions={v1}`, then re-run `make manifests`. E.g.:
```sh
CRD_OPTIONS ?= "crd:crdVersions={v1},trivialVersions=true"
```

**Comment by camilamacedo86** [comment]
@joelanford we have an open issue to track it already. See: https://github.com/operator-framework/operator-sdk/issues/3580

**Comment by kprasad99** [comment]
@joelanford Yeah figured it out this way, but was looking for more elegant way similar to --crd-version

**Comment by kprasad99** [comment]
@camilamacedo86 you can close this issue, since there is already an issue tracker id.
