### ISSUE TITLE
Remove outdated docs from master

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3930]
#### Describe the problem you need a feature to resolve.

The following docs are very outdated shows that have no reason for we keep them around in the SDK. Also, I understand that all EP's are now addressed in https://github.com/operator-framework/enhancements so shows that we have no need to have a proposals dir as well. 

- https://github.com/operator-framework/operator-sdk/tree/master/proposals
- https://github.com/operator-framework/operator-sdk/tree/master/design

#### Describe the solution you'd like.

- Remove both dirs

**Comment by estroz** [comment]
Should we be removing `proposals/`? There are some SDK-specific proposals that aren't relevant to the operator-framework as a whole, so aren't necessarily fitting for the enhancements repo. I said as much in a recent bug triage meeting.

**Comment by estroz** [comment]
There should be contributor docs pointing to the correct enhancements location.

/assign

**Comment by camilamacedo86** [comment]
Hi @estroz, 

Let's consider that we can close it by removing the design docs. 

Regards `Should we be removing proposals/? There are some SDK-specific proposals that aren't relevant to the operator-framework as a whole, so aren't necessarily fitting for the enhancements repo. I said as much in a recent bug triage meeting.` I think we can discuss it in the future since it shows confuse have 2 places for EP's. Note that, for example,  EP's for the CLI commands run bundle which are specific for SDK are in the https://github.com/operator-framework/enhancements. 

So, let's keep it out of the scope of this issue. 👍 
Following the PR open to remove the design dir which shows that we all agreed to remove: https://github.com/operator-framework/operator-sdk/pull/3982/files
