### ISSUE TITLE
Need to keep the Ansible log of first reconcile

### ISSUE THREAD

**Issue by YanFenGuo** [operator-framework/operator-sdk#3931]
#### Describe the problem you need a feature to resolve.

Ansible Operator keep reconciling and the log of first reconcile maybe overwritten, but for problem definition, the log of the first reconcile is very important and some error may only exist in first reconcile.

#### Describe the solution you'd like.

Keep the log of first reconcile, don't overwrite it.

**Comment by aemperador** [comment]
@YanFenGuo do you have repro steps for this scenario?

**Comment by YanFenGuo** [comment]
> @YanFenGuo do you have repro steps for this scenario?

Yes see if this description make it clear, I'm using Ansible operator-sdk 0.17.2, for watch.yaml, I set `reconcilePeriod: 5m` so Operator will continue reconciling. 
When I check Ansible log under `/tmp/ansible-operator/runner/<group>/<version>/<kind>/<namespace>/<name>.`, I found it only keep logs of latest 20 reconcile? What I'm expecting is we can keep the log of first reconcile, don't overwrite it.

**Comment by YanFenGuo** [comment]
We've implemented this in our own Operator code, so this is not urgent for us now.
