### ISSUE TITLE
have some way to know what dependent resource was touched to trigger ansible operator reconciliation

### ISSUE THREAD

**Issue by jmazzitelli** [operator-framework/operator-sdk#3945]
## Feature Request

When a dependent resource is changed, and it triggers a reconciliation, the user should have some way to know why the reconciliation was triggered (i.e. the user should have a way to figure out WHAT dependent resource changed).

Right now, when a reconciliation happens due to a change in a dependent resource, you do not know which resource changed. This would be really helpful when a dependent resource was unexpectedly changed and the operator admin wasn't expecting a reconciliation to happen.

#### Describe the solution you'd like.

I don't know of a good way to do this. Perhaps an entry in the Kiali CR `status` field to indicate WHY a reconciliation happened (a list of dependent resources that were touched, for example).

/language ansible

**Comment by jmazzitelli** [comment]
@fabianvf asked that I submit this issue ... slack conversation:

```
mazz : is there ANY way to determine what watched dependent resources changed that triggered a reconciliation? I've now got a second user claiming this operator is infinitely executing reconciliation loops, and I have no idea what dependent resource was changed that triggered it.

fabianvf : not currently but it seems like it should be a priority. Was there a GH issue for this already? I can bump it if so
```

**Comment by asmacdo** [comment]
I've file an upstream issue with controller-runtime since this seems like it would be a generally useful behavior. https://github.com/kubernetes-sigs/controller-runtime/issues/1186

As a backup (if they don't want this change upstream) this could also be implemented by creating a LogPredicate, which always returns true and has the side effect of logging the event.

**Comment by fabianvf** [comment]
/lifecycle frozen

we don't want to lose this one, it's pretty critical information for debugging infinite controller loops

**Comment by jmrodri** [comment]
I spent the past couple days trying to debug an issue. There wasn't much information at all in the runner or reconciler stating what was going on.
