### ISSUE TITLE
Operator-scope doc suggestion for improvements

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3947]
#### Describe the problem you need a feature to resolve.

improve the operator scope doc with the suggestions made by @estroz.
 
#### Describe the solution you'd like.

 However I'd like to see a differently structured approach. Each type of watch (single, multi, all namespace) should have its own section, with changes required to permissions for each. This is much clearer than the current jumble. Something like:

```markdown
## Overview

## Watch all namespaces (default)

### Manager changes

None

### Permissions changes

None

## Watch single namespace

### Manager changes

...

### Permissions changes

...

### Watch multiple namespaces

### Manager changes

...

### Permissions changes

...
```

**Comment by digitole** [comment]
Hi! Does this include the docs for the ansible operator scope? It seems that there is none for the ansible operator, only for golang.

**Comment by estroz** [comment]
@digitole yep this does. I haven't gotten around to making this doc yet, and may not have time for awhile.

**Comment by jberkhahn** [comment]
blocked pending #4837

**Comment by asmacdo** [comment]
It looks like there is not much that can be consolidated, so this issue is to create an operator-scope document for Ansible/Helm. If there is redundancy, we can revisit #4837
