### ISSUE TITLE
infinite reconcile loop on Openshift 4.5.8

### ISSUE THREAD

**Issue by wzhanw** [operator-framework/operator-sdk#3950]
#### What did you do?
We have an ansible based operator to manage our resources, service, deployment, etc.
I set below settings in watches.yml:
```
  reconcilePeriod: 0s
  watchDependentResources: True
```

#### What did you expect to see?
I expected the reconcile run once at the 1st start time and don't run again unless the watched subresource has a update. 

#### What did you see instead? Under which circumstances?
There is an infinite reconcile loop happened, the reconcile will not stop on Openshift 4.5.
My cr's status is always:
```
status:
  conditions:
  - lastTransitionTime: "2020-09-28T14:58:27Z"
    message: Running reconciliation
    reason: Running
    status: "True"
    type: Running
```
I checked the debug logs of the ansible operator,  there are a lot of Reconciling events. In fact, we didn't update those sub-resources at all. 
```
{"level":"debug","ts":1601305249.4027252,"logger":"predicate","msg":"Reconciling due to dependent resource update","name":"root-issuer","namespace":"qxuqxu","apiVersion":"cert-manager.io/v1alpha2","kind":"Issuer"}
{"level":"debug","ts":1601305252.6910276,"logger":"predicate","msg":"Reconciling due to dependent resource update","name":"ca-crt","namespace":"qxuqxu","apiVersion":"cert-manager.io/v1alpha2","kind":"Certificate"}
{"level":"debug","ts":1601305255.8381672,"logger":"predicate","msg":"Reconciling due to dependent resource update","name":"ca","namespace":"qxuqxu","apiVersion":"cert-manager.io/v1alpha2","kind":"Issuer"}
{"level":"debug","ts":1601305266.8398612,"logger":"predicate","msg":"Reconciling due to dependent resource update","name":"auth-rest","namespace":"qxuqxu","apiVersion":"apps/v1","kind":"Deployment"}
{"level":"debug","ts":1601305268.7478693,"logger":"predicate","msg":"Reconciling due to dependent resource update","name":"infoservice","namespace":"qxuqxu","apiVersion":"v1","kind":"PersistentVolumeClaim"}
{"level":"debug","ts":1601305273.0109222,"logger":"predicate","msg":"Reconciling due to dependent resource update","name":"infoservice","namespace":"qxuqxu","apiVersion":"v1","kind":"PersistentVolumeClaim"}
{"level":"debug","ts":1601305273.0143301,"logger":"predicate","msg":"Reconciling due to dependent resource update","name":"infoservice","namespace":"qxuqxu","apiVersion":"v1","kind":"PersistentVolumeClaim"}
{"level":"debug","ts":1601305273.7374358,"logger":"predicate","msg":"Reconciling due to dependent resource update","name":"infoservice","namespace":"qxuqxu","apiVersion":"apps/v1","kind":"Deployment"}
{"level":"debug","ts":1601305273.7539766,"logger":"predicate","msg":"Reconciling due to dependent resource update","name":"infoservice","namespace":"qxuqxu","apiVersion":"apps/v1","kind":"Deployment"}
{"level":"debug","ts":1601305273.7708573,"logger":"predicate","msg":"Reconciling due to dependent resource update","name":"infoservice","namespace":"qxuqxu","apiVersion":"apps/v1","kind":"Deployment"}
{"level":"debug","ts":1601305279.2638485,"logger":"predicate","msg":"Reconciling due to dependent resource update","name":"msd-mss-cert","namespace":"qxuqxu","apiVersion":"cert-manager.io/v1alpha2","kind":"Certificate"}
{"level":"debug","ts":1601305284.4058373,"logger":"predicate","msg":"Reconciling due to dependent resource update","name":"msd","namespace":"qxuqxu","apiVersion":"apps/v1","kind":"Deployment"}
{"level":"debug","ts":1601305284.4195504,"logger":"predicate","msg":"Reconciling due to dependent resource 
update","name":"mss","namespace":"qxuqxu","apiVersion":"apps/v1","kind":"Deployment"}
```

I found that, on the Openshift 4.5.8 (Kubernetes Version: v1.18.3+6c42de8), all the resources will be mutated with a new section: `managedFields`,  not sure whether it is the root cause,  looks like operator SDK consider it as the resource update and trigger the reconcile.
```
 managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:app: {}
        f:strategy:

```

#### Environment
Openshift version:
Client Version: 4.5.8
Server Version: 4.5.8
Kubernetes Version: v1.18.3+6c42de8

**Operator type:**

**Kubernetes cluster type:**
OpenShift

`$ operator-sdk version`
quay.io/operator-framework/ansible-operator:v1.0.0

`$ go version` (if language is Go)

`$ kubectl version`
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+6c42de8", GitCommit:"6c42de8", GitTreeState:"clean", BuildDate:"2020-08-29T05:03:41Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

#### Possible Solution
I have to set `watchDependentResources` to false.

**Comment by wzhanw** [comment]
I found those types (`ServiceAccount` and `PersistentVolumeClaim`) of resources cannot be watched on any version of openshift, because the openshift will inject some secrets to the service account,   and PVC will be updated with bounded PV after it bounded a Persistent Volume.

**Comment by Dimss** [comment]
any updates on this one? 
I'm facing with the same issue on Azure AKS 18.3 cluster

**Comment by Dimss** [comment]
thanks for repose @jmrodri , any chances  this issue related to this one #4258
