### ISSUE TITLE
Can't install necessary binaries in Ansible operator

### ISSUE THREAD

**Issue by michael-niemand** [operator-framework/operator-sdk#3958]
## Type of question

How to implement a specific feature
General operator-related help
Open question

#### What did you do?

I want to write an operator that does mysql tasks using Ansible. In order to use the mysql ansible modules, additional binaries are required accoring to the Ansible documentation.
Trying to install these using yum results in an error message, not allowing installation of said binaries.

#### What did you expect to see?

I was expecting to be able to install packages within the Docker file.

#### What did you see instead? Under which circumstances?

I added:
```
USER root
RUN yum install -y mysql
```
to the Dockerfile, right below `FROM quay.io/operator-framework/ansible-operator:v1.0.0`

This results in the following error message:
```
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Red Hat Universal Base Image 8 (RPMs) - BaseOS  2.4 MB/s | 769 kB     00:00    
Red Hat Universal Base Image 8 (RPMs) - AppStre 9.2 MB/s | 4.0 MB     00:00    
Red Hat Universal Base Image 8 (RPMs) - CodeRea  80 kB/s |  12 kB     00:00    
No match for argument: mysql
```

I also tried other packages like MySQL-python and mariadb with the same result

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

vanilla AKS cluster 1.17

`$ operator-sdk version`

1.0.0

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"5737fe2e0b8e92698351a853b0d07f9c39b96736", GitTreeState:"clean", BuildDate:"2020-06-24T19:54:11Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by michael-niemand** [comment]
turns out the mysql python module, installed via pip, does it for this use case, but I'll leave the question open for other possible 3rd-party installs an operator might need ...

**Comment by asmacdo** [comment]
It is possible to install binaries using yum or pip. In this case it wasn't working because mysql is not available in the default ubi8 repositories. Installing via pip should be fine, but if you want to install the rpm, you'll have to enable the appropriate repo.
