### ISSUE TITLE
Attempting to Build Operator, customresourcedefinitions coming empty in CSV

### ISSUE THREAD

**Issue by ajeetas** [operator-framework/operator-sdk#3962]
## Type of question
How to CRD definition come up properly in Operator
Steps:
1.operator-sdk init --project-name citrix-adc-istio-ingress-gateway-operator --plugins=helm --kind=Citrix-adc-istio-ingress-gateway --group=Citrix --helm-chart=/Users/ajeeta/operator-ingress-2020/citrix-adc-istio-ingress-gateway
2. make bundle 
3. docker  build -t  quay.io/ajeetas/citrix-adc-istio-ingress-gateway-operator2:v1.0.2   -f bundle.Dockerfile .
4. docker push  quay.io/ajeetas/citrix-adc-istio-ingress-gateway-operator2:v1.0.2
5.  opm index add     --bundles quay.io/ajeetas/citrix-adc-istio-ingress-gateway-operator2:v1.0.2     --tag quay.io/ajeetas/cia-ingress-operator-index2:v1.0.2
6. docker push  quay.io/ajeetas/cia-ingress-operator-index2:v1.0.2

Check CSV file here:
```
https://github.com/ajeetas/citrix-istio-ingress-operator-bundle/blob/master/bundle/manifests/citrix-adc-istio-ingress-gateway-operator.clusterserviceversion.yaml
```

Please check crd section `customresourcedefinitions: {}`

When I deploy into the OpenShift cluster, there no API is created.

bundle validation 
```
operator-sdk bundle validate   quay.io/ajeetas/citrix-adc-istio-ingress-gateway-operator2:v1.0.2
INFO[0000] Unpacking image layers
INFO[0000] running /usr/local/bin/docker pull quay.io/ajeetas/citrix-adc-istio-ingress-gateway-operator2:v1.0.2
INFO[0006] running docker create
INFO[0006] running docker cp
INFO[0007] running docker rm
INFO[0007] Found annotations file                        bundle-dir=/var/folders/m6/q6096r6s17q4vyk78tnwvgdc0000gn/T/bundle-799946170 container-tool=docker
INFO[0007] Could not find optional dependencies file     bundle-dir=/var/folders/m6/q6096r6s17q4vyk78tnwvgdc0000gn/T/bundle-799946170 container-tool=docker
INFO[0007] All validation tests have completed successfully
```

where bundle.Dockerfile is as follows:
```
FROM scratch

LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=citrix-adc-istio-ingress-gateway-operator
LABEL operators.operatorframework.io.bundle.channels.v1=alpha
LABEL operators.operatorframework.io.bundle.channel.default.v1=
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.0.1
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=helm.sdk.operatorframework.io/v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1

LABEL com.redhat.openshift.versions="v4.5,v4.6"
LABEL com.redhat.delivery.operator.bundle=true
LABEL com.redhat.delivery.backport=true

COPY bundle/manifests /manifests/
COPY bundle/metadata /metadata
```

 

#### What did you expect to see?
API should come in Operator.

#### Environment

**Operator type:**
-Certified Operator
-helm based Operator

`$ operator-sdk version`
1.0.1

`$ Openshift version`
 4.5.7

<img width="1432" alt="ingress-operator-view" src="https://user-images.githubusercontent.com/55227963/94768161-39087780-03cc-11eb-9283-5e2d4bcdc00c.png">

NO K8s API provided when I deploy operator on openshift cluster.

**Comment by estroz** [comment]
A few questions:

1. Did you run `operator-sdk create api`? 
1. Did you run `make bundle`?
1. Does `./config/crd` exist?

/language helm
/triage support
/assign

**Comment by ajeetas** [comment]
Did you run operator-sdk create api?
>>>>>>>>>>>>>>>>>
I am following this doc, there is option of `operator-sdk init`
https://redhat-connect.gitbook.io/certified-operator-guide/helm-operators/building-a-helm-operator
Did you run make bundle?
>>>>>>>>>>
yes I ran `make bundle`.
bundle  structure like this have two directoies: manifests, metadata
to check proper structure Please check github location: `https://github.com/ajeetas/citrix-istio-ingress-operator-bundle/`
Does ./config/crd exist?
>>>>>>>>>>>>
yes, if I add crd file to bundle/manifest folder and try to validate if gives below error:
 ```
operator-sdk bundle validate bundle/
INFO[0000] Found annotations file                        bundle-dir=bundle container-tool=docker
INFO[0000] Could not find optional dependencies file     bundle-dir=bundle container-tool=docker
ERRO[0000] Error: Value Citrix.my.domain/v1alpha1, Kind=Citrix-adc-istio-ingress-gateway: CRD "Citrix.my.domain/v1alpha1, Kind=Citrix-adc-istio-ingress-gateway" is present in bundle "citrix-adc-istio-ingress-gateway-operator.v0.0.1" but not defined in CSV
ERRO[0000] Error: Field metadata.name, Value citrix-adc-istio-ingress-gateways.Citrix.my.domain: metadata.name: Invalid value: "citrix-adc-istio-ingress-gateways.Citrix.my.domain": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
ERRO[0000] Error: Field spec.group, Value Citrix.my.domain: spec.group: Invalid value: "Citrix.my.domain": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Comment by ajeetas** [comment]
here is tree of the Project:
Ajeetas-MBP-f484:cia-operator ajeeta$ tree
.
├── Dockerfile
├── Makefile
├── PROJECT
├── bin
│   └── kustomize
├── bundle
│   ├── manifests
│   │   ├── Citrix.my.domain_citrix-adc-istio-ingress-gateways.yaml. // this I have copied form config/crd
│   │   └── citrix-adc-istio-ingress-gateway-operator.clusterserviceversion.yaml
│   └── metadata
│       └── annotations.yaml
├── bundle.Dockerfile
├── config
│   ├── crd
│   │   ├── bases
│   │   │   └── Citrix.my.domain_citrix-adc-istio-ingress-gateways.yaml
│   │   └── kustomization.yaml
│   ├── default
│   │   ├── kustomization.yaml
│   │   └── manager_auth_proxy_patch.yaml
│   ├── manager
│   │   ├── kustomization.yaml
│   │   └── manager.yaml
│   ├── manifests
│   │   ├── bases
│   │   │   └── citrix-adc-istio-ingress-gateway-operator.clusterserviceversion.yaml
│   │   └── kustomization.yaml
│   ├── prometheus
│   │   ├── kustomization.yaml
│   │   └── monitor.yaml
│   ├── rbac
│   │   ├── auth_proxy_client_clusterrole.yaml
│   │   ├── auth_proxy_role.yaml
│   │   ├── auth_proxy_role_binding.yaml
│   │   ├── auth_proxy_service.yaml
│   │   ├── citrix-adc-istio-ingress-gateway_editor_role.yaml
│   │   ├── citrix-adc-istio-ingress-gateway_viewer_role.yaml
│   │   ├── kustomization.yaml
│   │   ├── leader_election_role.yaml
│   │   ├── leader_election_role_binding.yaml
│   │   ├── role.yaml
│   │   └── role_binding.yaml
│   ├── samples
│   │   ├── Citrix_v1alpha1_citrix-adc-istio-ingress-gateway.yaml
│   │   └── kustomization.yaml
│   └── scorecard
│       ├── bases
│       │   └── config.yaml
│       ├── kustomization.yaml
│       └── patches
│           ├── basic.config.yaml
│           └── olm.config.yaml
├── helm-charts
│   └── citrix-adc-istio-ingress-gateway
│       ├── Chart.yaml
│       ├── README.md
│       ├── templates
│       │   ├── _helpers.tpl
│       │   ├── citrix-adc-ingressgateway-deployment.yaml
│       │   ├── ingressgateway-service.yaml
│       │   ├── metrics-exporter-service.yaml
│       │   └── secret.yaml
│       └── values.yaml
├── test-operatorsource.yaml
└── watches.yaml

**Comment by ajeetas** [comment]
@estroz Just following up on this.

**Comment by estroz** [comment]
@ajeetas some of the validation errors are pretty clear: you need to lower-case `Citrix` everywhere. These errors likely stem from an incorrect `init` invocation:
- the `--kind` value needs to be a camel-cased string, so instead of `--kind=Citrix-adc-istio-ingress-gateway` it should be something like `--kind=CitrixAdcIstioIngressGateway`
- the `--group` value needs to be lower-cased, so instead of `--group=Citrix` use `--group=citrix`.
