### ISSUE TITLE
SDK tool with an standard to report/output a list of errors. 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3966]
#### Describe the problem you need a feature to resolve.

**The problem here is that instead of the command scorecard and bundle has a standard to return the result with a list of errors we have a different implementation to achieve the same for each command which reduces the maintainability as make it harder for who will consume the result via a pipeline for example.** 

See that the bundle validate uses the following implementation to return a list of errors in the project:

```go
result = NewResult()
result.AddError(errors.New(string.fmt(("operator deployment %q not available: %s", ds.Name, s.Reason))))
```

Then, another subcommand of the same bundle command, ( bundle run ), has another implementation done in the PR: https://github.com/operator-framework/operator-sdk/pull/3908 to achieve the same. 

#### Describe the solution you'd like.

So, IMO we should move the  [result](https://github.com/operator-framework/operator-sdk/blob/16403cbe1c152d3ee7f21987aacb88444fc9cf80/internal/cmd/operator-sdk/bundle/internal/result.go) implementation for internal/util and keep it a standard to output a list of errors.

**Comment by joelanford** [comment]
This might help: https://github.com/hashicorp/go-multierror

**Comment by camilamacedo86** [comment]
Hi @estroz, 

I am waiting for the PR : https://github.com/operator-framework/operator-sdk/pull/3908/files to push my suggestion to replace the code add-in https://github.com/operator-framework/operator-sdk/pull/3908/files#diff-d99b4452be120b4094387171182b4470R51-R82

**Comment by jmrodri** [comment]
This is a good idea to make the bundle validate and scorecards use the same Result struct. Putting this on the backlog for now as it isn't high priority. Removed priority longterm.
