### ISSUE TITLE
Re-add Black Lives Matter banner (without Red Hat branding)

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-sdk#3975]
## Feature Request

See #3932

> Related: operator-framework/operator-framework.io#13
>
> Due to the CNCF donation, this Red Hat/Paul Cormier message should be removed. Note this PR is not attempting to pass an opinion on the message but to comply with a request from a legal team. I suggest we discuss a replacement in a follow up issue.

**Comment by joelanford** [comment]
@robszumski Were you working on a replacement for this, or do we need to get this assigned?

**Comment by robszumski** [comment]
@joelanford I am not working on anything, it's an open issue

**Comment by asmacdo** [comment]
I plan to steal this from: https://github.com/kubernetes-sigs/kubebuilder/pull/1553
