### ISSUE TITLE
`operator-sdk generate kustomize manifests -q` generates invalid config/manifests/kustomization.yaml

### ISSUE THREAD

**Issue by mdbooth** [operator-framework/operator-sdk#3979]
## Bug Report

Trying to work out why my generated CSV was incomplete after executing `make bundle`:

```
$ make bundle
/home/mbooth/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
operator-sdk generate kustomize manifests -q
cd config/manager && /usr/bin/kustomize edit set image controller=ovn-central-controller:latest
/usr/bin/kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version 0.0.1
Error: rawResources failed to read Resources: Load from path ../default failed: '../default' must be a file (got d='/home/mbooth/src/osp-k8s/ovn-central-operator/config/default')

INFO[0000] Building annotations.yaml
INFO[0000] Writing annotations.yaml in /home/mbooth/src/osp-k8s/ovn-central-operator/bundle/metadata
INFO[0000] Building Dockerfile
INFO[0000] Writing bundle.Dockerfile in /home/mbooth/src/osp-k8s/ovn-central-operator
operator-sdk bundle validate ./bundle
INFO[0000] Found annotations file                        bundle-dir=bundle container-tool=docker
INFO[0000] Could not find optional dependencies file     bundle-dir=bundle container-tool=docker
ERRO[0000] error validating content in bundle/manifests: error loading objs in directory: bundle manifests dir has hidden file: bundle/manifests/.ovn-central-operator.clusterserviceversion.yaml.swp
make: *** [Makefile:125: bundle] Error 1
```

From the above, `failed to read Resources: Load from path ../default failed` appears to be because the generated config/manifests/kustomization.yaml is invalid. The contents of this file are:

```
resources:
- ../default
- ../samples
- ../scorecard
```

This file is generated by `operator-sdk generate kustomize manifests -q`. Guessing resources should be bases there, but there's a secondary issue. I fixed the file manually to contain:

```
bases:
- ../default
- ../samples
- ../scorecard
```

but then I get:

```
$ kustomize build config/manifests
Error: AccumulateTarget: found conflict between different patches
&resource.Resource{Kunstructured:(*kunstruct.UnstructAdapter)(0xc000010168), options:(*types.GenArgs)(0xc0003bb700)} doesn't deep equal &resource.Resource{Kunstructured:(*kunstruct.UnstructAdapter)(0xc0000102c0), options:(*types.GenArgs)(0xc0003bb700)}
```

AFAICT this is a limitation of kustomize: (https://github.com/kubernetes-sigs/kustomize/issues/642)

To work round it I commented out scorecard:

```
bases:
- ../default
- ../samples
#- ../scorecard
```

And now it works and `make bundle` generates a complete CSV.

#### Environment

**Operator type:**

 /language go

**Kubernetes cluster type:**

OpenShift

`$ operator-sdk version`

operator-sdk version: "v1.0.1", commit: "4169b318b578156ed56530f373d328276d040a1b", kubernetes version: "v1.18.2", go version: "go1.13.15 linux/amd64", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.13.15 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.8-beta.0", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"archive", BuildDate:"2020-01-02T00:00:00Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+b0068a8", GitCommit:"b0068a8", GitTreeState:"clean", BuildDate:"2020-09-11T20:03:06Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by cliveseldon** [comment]
So this default is wrong?
https://github.com/operator-framework/operator-sdk/blob/adcef86d6e337cb98a3bd10e8e6bddf921f17e9f/internal/cmd/operator-sdk/generate/kustomize/manifests.go#L154-L159

**Comment by cliveseldon** [comment]
Actually looks like the `bases` folder is just used in `operator-sdk enerate bundle` where assumes the name of the csv file from the project name.

**Comment by estroz** [comment]
@mdbooth the `kustomization.yaml` file is not invalid; the `bases` directive has been deprecated since v2.1.0, and is superseded by `resources`. What `kustomize` version are you using? Can you try doing:
```sh
rm -f $(command -v kustomize)
make kustomize bundle
```
