### ISSUE TITLE
Unregister controllers

### ISSUE THREAD

**Issue by kotyara85** [operator-framework/operator-sdk#3989]
Hello,
Is there a way to dynamically unregister controllers?

Current code is 

```
// AddToManager adds all Controllers to the Manager
func AddToManager(m manager.Manager) error {
	for _, f := range AddToManagerFuncs {
		if err := f(m); err != nil {
			return err
		}
	}
	return nil
}
```

Thank you

**Comment by estroz** [comment]
Once you've added a controller to the manager you cannot remove it. This is more of a [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/issues/) question, so feel free to create a new issue there if you'd like to discuss your use case!
