### ISSUE TITLE
[ci] - changes in the docs has been trigging the test jobs

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3994]
#### What did you do?

Push a PR with changes in the docs only

#### What did you expect to see?

The tests are skipped
 
#### What did you see instead? Under which circumstances?

The tests have been executed. See; https://travis-ci.org/github/operator-framework/operator-sdk/builds/733699483

**Comment by estroz** [comment]
The PR you linked has an update to `testdata/`, which I think is unintentional. Other docs-only PRs do not trigger full test suites, ex. [this build](https://travis-ci.org/github/operator-framework/operator-sdk/builds/733439141).

**Comment by camilamacedo86** [comment]
Thank you for check that. I missed it. Good point.
