### ISSUE TITLE
Status Descriptor Test fail for OLM Example with Scorecard

### ISSUE THREAD

**Issue by cliveseldon** [operator-framework/operator-sdk#3999]
#### What did you do?

`operator-sdk scorecard bundle`

#### What did you expect to see?

All tests pass.

#### What did you see instead? Under which circumstances?

```
Image:      quay.io/operator-framework/scorecard-test:v1.0.1
Entrypoint: [scorecard-test olm-status-descriptors]
Labels:
	"suite":"olm"
	"test":"olm-status-descriptors-test"
Results:
	Name: olm-status-descriptors
	State: fail

	Log:
		Loaded ClusterServiceVersion: seldon-operator.v1.3.0-dev
		Loaded 1 Custom Resources from alm-examples
```

The above seems to be running:

https://github.com/operator-framework/operator-sdk/blob/537799091b792173574756ff8534f48868585d5d/internal/scorecard/tests/olm.go#L199-L207

Which calls:

https://github.com/operator-framework/operator-sdk/blob/537799091b792173574756ff8534f48868585d5d/internal/scorecard/tests/olm.go#L209-L227

which looks like it will fail at 

https://github.com/operator-framework/operator-sdk/blob/537799091b792173574756ff8534f48868585d5d/internal/scorecard/tests/olm.go#L235-L239

Why should my olm-example CR need to have a `status` section?

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

Kind

`$ operator-sdk version`

1.0.1

`$ go version` (if language is Go)

go version go1.14.7 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by cliveseldon** [comment]
I validated above by changing my "sample" to 

```
File Edit Options Buffers Tools Javascript Help                                                       
{
  "apiVersion": "machinelearning.seldon.io/v1",
  "kind": "SeldonDeployment",
  "metadata": {
    "name": "model"
  },
  "spec": {
    "name": "test-deployment",
    "predictors": [
      {
        "componentSpecs": [
          {
            "spec": {
              "containers": [
                {
                  "image": "seldonio/mock_classifier_rest:1.3",
                  "name": "classifier"
                }
              ]
            }
          }
        ],
        "graph": {
          "children": [],
          "endpoint": {
            "type": "REST"
          },
          "name": "classifier",
          "type": "MODEL"
        },
        "name": "example",
        "replicas": 1
      }
    ]
  },
    "status":{}
}
```

And now the scorecard passes

**Comment by estroz** [comment]
The scorecard is intended to promote operator best-practices, one of which is having a status on a CR.
Statuses are recommended by the [k8s API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status):

>All objects that represent a physical resource whose state may vary from the user's desired intent SHOULD have a "spec" and a "status".

However it also says the following:

>Objects whose state cannot vary from the user's desired intent MAY have only "spec", and MAY rename "spec" to a more appropriate name.

Are you saying your CRD defines CRs of the latter type?

/triage support

**Comment by cliveseldon** [comment]
Maybe I am getting confused on the purpose of the olm-example section. I would as a user assume the `status` section is added by the k8s api-server. One does not apply CRs with a `status` field. My CRD obviously has a `status` section.

**Comment by estroz** [comment]
That's correct, but given that the values in `olm-examples` are examples, I _think_ they should display what status fields are possible. @dinhxuanvu @awgreene can you weigh in on whether examples should have a status?

**Comment by dinhxuanvu** [comment]
olm-examples/alm-examples are not really examples in traditional sense because it is used to drive the UI I believe. So when users use web console to create CR, it will use those yaml to create the CR on the cluster. That's why we validate it.

**Comment by estroz** [comment]
In that case, these examples' `status` fields should not be validated. Instead `scorecard` should only be checking whether `statusDescriptors` exist for a GVK.

/ping @jmccormick2001 

/remove-triage support
/kind bug

**Comment by varshaprasad96** [comment]
Closing the issue as #4141 and #4093 have been merged
