### ISSUE TITLE
Unable to init project use operator-sdk 1.0.1

### ISSUE THREAD

**Issue by MrYourM** [operator-framework/operator-sdk#4003]
Hi
  my operator-sdk version info:
```
operator-sdk version
operator-sdk version: "v1.0.1", commit: "4169b318b578156ed56530f373d328276d040a1b", kubernetes version: "v1.18.2", go version: "go1.13.15 linux/amd64", GOOS: "linux", GOARCH: "amd64"
```
When I init a new project
```
mkdir memcached-operator
cd memcached-operator
operator-sdk init --domain=example.com --repo=github.com/example-inc/memcached-operator
```
It occurs an err
`FATA[0041] failed to initialize project with version "3-alpha": exit status 2 `

Please help
tks

**Comment by MrYourM** [comment]
I find this (issue)[https://github.com/operator-framework/operator-sdk/issues/3889], but it is not useable

**Comment by varshaprasad96** [comment]
Hi @MrYourM 
Could you please upgrade your go version to 1.15 and check. The go version which is used with this particular version of the tool seems to be 1.15.

**Comment by MrYourM** [comment]
@varshaprasad96 
Thanks, when i first to use operator-sdk 1.0.1, go verison is 1.15.2, but it also produce this erro
`FATA[0041] failed to initialize project with version "3-alpha": exit status 2`

my os verison: 
`ubuntu 18.04.3 LTS`
could you tell me how to trouble shoot or other possible reasons？

**Comment by camilamacedo86** [comment]
HI @varshaprasad96, 

The change in the PR https://github.com/operator-framework/operator-sdk/pull/3987 is not released yet. The version 1.0.1 uses 1.13+. See: https://github.com/operator-framework/operator-sdk/blob/v1.0.1/go.mod. 

Hi @MrYourM, 

I am unable to reproduce this scenario. It shows to be related to your local env setup. So, I'd recommend checking it by:

- Ensure that you have just 1 go version installed
- Check your go installation. See: https://golang.org/doc/install/source#testing
- A common problem is related to the Go env vars setup. Try to `export GOROOT=$(go env GOROOT)` and check if it will solve.
- Also, check if your GOPROXY has the `GOPROXY="https://proxy.golang.org,direct"`
- try to create a new project and download some go module to check if you have permission to it in your env 

```
mkdir test
cd test
go mod init
go get github.com/operator-framework/operator-lib
```

If the above info is not enough for you to solve the problem, could you please add here the output of `go env` for we try to help you with? Also, could you please try to do the same inside of the $GOPATH to see if it will change `mkdir $GOPATH/src/mkdir memcached-operator`?
