### ISSUE TITLE
How to properly do List right after Update/Create

### ISSUE THREAD

**Issue by GreaTdANie1** [operator-framework/operator-sdk#4013]
## Type of question

General operator-related help

#### What did you do?

I'm currently trying to add Update request handling for my cluster. Say I have a StatefulSet which has several pods and one of my application is deployed in each of them. Now I want to handle an Update request that want more pods in this StatefulSet. What I want to do in my Reconcile() is first change the size of my StatefulSet (using `r.Client.Update(ctx, sts)`), then **right after that** I want to list all the newly created pods (using `r.Client.List(ctx, podList, listOpts...)` with my selector) and do custom configuration for my application in each of them. 

The problem is the interval between these two operations is so small, that maybe the new pods are not yet created or maybe the read cache in `r.Client` doesn't get a chance to flush before I do `List()`. As a result, I'm not able to get the new pods and perform my configuration. **So, how do you make sure that the List right after Update can get me the proper results?** Is there anyway I can perform a "sync" before calling `List()`?

#### What did you expect to see?

A `List()` call right after `Update()` can give me all the newly created pods.

#### What did you see instead? Under which circumstances?

A `List()` call right after `Update()` is not able to give me the proper results.

#### Possible Solutions

- **Sleep for a (few) second(s) before calling `List()`.** Not a robust solution.

- **Do Requeue after `Update()`.** Need to refactor a huge part of my code. And, does it make sure I can get the newly created pods, if so, how does it do it?

#### Environment

**Operator type:**

/language go

`$ operator-sdk version`

operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 linux/amd64", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.14 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-tk8s.1", GitCommit:"b050d81c44c53f0eeb2a72142ca2e9d6d46ee6fa", GitTreeState:"clean", BuildDate:"2020-04-23T13:23:39Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-tk8s.1", GitCommit:"b050d81c44c53f0eeb2a72142ca2e9d6d46ee6fa", GitTreeState:"clean", BuildDate:"2020-04-23T13:23:39Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by estroz** [comment]
The idea behind a reconcile loop is to take advantage of Kubernetes' eventual consistency concept, meaning that _eventually_ the state of the system (cluster) will look how you want it to after you apply some changes. On each run of your controller's `Reconcile()` method, your operator is effectively checking if the state of the cluster is what you programmed it to look like; if it doesn't, it will eventually (assuming there are no issues external to your operator or bugs in your operator's code), so continue checking cluster state.

Effectively: you should never be blocking within `Reconcile()`, and instead should be [requeuing](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#reconcile-loop) when you don't get the results you want from `List()`.

Hopefully this explanation helps!

/triage support

**Comment by GreaTdANie1** [comment]
> The idea behind a reconcile loop is to take advantage of Kubernetes' eventual consistency concept, meaning that _eventually_ the state of the system (cluster) will look how you want it to after you apply some changes. On each run of your controller's `Reconcile()` method, your operator is effectively checking if the state of the cluster is what you programmed it to look like; if it doesn't, it will eventually (assuming there are no issues external to your operator or bugs in your operator's code), so continue checking cluster state.
> 
> Effectively: you should never be blocking within `Reconcile()`, and instead should be [requeuing](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#reconcile-loop) when you don't get the results you want from `List()`.
> 
> Hopefully this explanation helps!
> 
> /triage support

Thank you for your reply! 

Now I think understand the logic behind requeuing. It's like dividing my operation into different stages, before moving on to the next stage (i.e. configure the new pods), I should check if the current stage is satisfied (i.e. new pods are already created), and requeue if it is not, until it is ready for the next stage. 

The only problem here though is, since my applications in the cluster are highly complicated and involve many steps of configuration, to divide them and allow requeuing means I need to add tons of stage checks (`if-else`es). I guess that's the pain I have to undergo then XD.

**Comment by camilamacedo86** [comment]
Hi @GreaTdANie1, 

Just to supplement the info provided already. 

The reconcile solution ought to be idempotent which means that it will be looking for the state in the cluster in order to have the desired state at the end.

See that, the reconcile function is responsible for synchronizing the resources and their specifications according to the business logic implemented on them. In this way, it works like a loop, and it does not stop until all conditionals match its implementation. The following is pseudo-code with an example that clarifies it.

```go
reconcile App {
 
   // Check if a Deployment for the app exists, if not create one
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   } 
    
   // Check if a Service for the app exists, if not create one 
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   }  
 
   // Looking for Database CR/CRD 
   // Check the Database Deployments Replicas size
   // If deployment.replicas size != cr.size, then update it
   // Then, go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{Requeue: true}, nil
   }  
   ...
    
   // If it is at the end of the loop, then:
   // All was done successfully and the reconcile can stop  
   return reconcile.Result{}, nil
 
}
```

The following are a few possible return options to restart the Reconcile:

- With the error:
```go
return ctrl.Result{}, err
```

- Without an error:
```go
return ctrl.Result{Requeue: true}, nil
```

- Therefore, to stop the Reconcile, use:
```go
return ctrl.Result{}, nil
```

- Reconcile again after X time:
```go
return ctrl.Result{RequeueAfter: nextRun.Sub(r.Now())}, nil
```

**Note:** For more details, check the Reconcile and its [Reconcile godoc](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile). The changes proposed in https://github.com/operator-framework/operator-sdk/pull/4021, which might help you better get its idea.  

However, shows that your question is answered so I am closing this one. However, please, feel free to ping us and/or raise new issues.
