### ISSUE TITLE
Scaffolded operators should depend on latest community.kubernetes collection

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#4015]
## Feature Request

/language ansible 

Currently, Ansible-based operators depend on `community.kubernetes<1.0.0`, but we should upgrade to the latest.

**Comment by asmacdo** [comment]
Bumping to 1.3 and assigning Jesus.

**Comment by jmrodri** [comment]
Related to PR #4190

**Comment by estroz** [comment]
@asmacdo @jmrodri @fabianvf does this dependency bump depend on any changes upstream? Is this blocked?

**Comment by jmrodri** [comment]
This was addressed in PRs: #4594 and #4734
