### ISSUE TITLE
watch on namespaces

### ISSUE THREAD

**Issue by tobiasdziekanowski** [operator-framework/operator-sdk#4024]
## Type of question

i want to build a controller, that has a watch on namespaces with a certain label within ansible, that applies some secrets and a deployment to the given namespaces, w/o triggered by a cr.

#### What did you do?
reading the documentation, it seems not to be possible, googleing didn't help that much. 

#### What did you expect to see?
i wanted to build a controller, that does not need external input to do things, with ansible

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**
OpenShift
`$ operator-sdk version`

operator-sdk version: v0.8.2, commit: 28bd2b0d4fd25aa68e15d928ae09d3c18c3b51da

`$ go version` (if language is Go)

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc
#### Additional context

is there a way to solve it via ansible or do i need to switch to go?

**Comment by asmacdo** [comment]
This should be possible using the `selector` field in the watches file. https://sdk.operatorframework.io/docs/building-operators/ansible/reference/watches/

Looks like the `selector` feature was added in `1.1.0`, so you will need to upgrade. https://sdk.operatorframework.io/docs/upgrading-sdk-version/

**Comment by asmacdo** [comment]
If that doesn't solve your issue, please reopen.
