### ISSUE TITLE
Remove our changes to kubebuilder generated makefiles

### ISSUE THREAD

**Issue by jberkhahn** [operator-framework/operator-sdk#4044]
Followup to #3692

Once https://github.com/kubernetes-sigs/kubebuilder/pull/1711 gets merged upstream and we bump our version of kubebuilder, we will need to revert the changes in #3983.

**Comment by jberkhahn** [comment]
So, in the previous issue we wanted to change the Makefiles generated by OperatorSDK so they do not require additional changes to run out of the box. It was determined that the best place to make this change was upstream, in Kubebuilder. However, this was an important enough issue that we were blocking release 1.1 on it, and the upstream change wasn't going to be merged in time. So we added a bit to manually change it on our end in PR #3983. These changes will need to be reverted once the upstream PR is merged and we bump our Kubebuilder dependency, which is what this issue is tracking.

**Comment by estroz** [comment]
This may never be completed because the changes being discussed here could be considered breaking changes to the go/v2 plugin, hence will never be applied upstream. However these changes are already present in the go/v3-alpha plugin.

**Comment by camilamacedo86** [comment]
it is solved for go/v3. We can close this one. 
Please, feel free to re-open if you see that is required.
