### ISSUE TITLE
example is missing for memcached-operator

### ISSUE THREAD

**Issue by majorinche** [operator-framework/operator-sdk#4060]
follow up this link: https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/

try to the step "make manifests"
/root/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
Error: go [list -e -json -compiled=true -test=false -export=false -deps=true -find=false -tags ignore_autogenerated -- ./...]: exit status 1: build github.com/example-inc/memcached-operator: cannot load github.com/example/memcached-operator/api/v1alpha1: **cannot find module providing package github.com/example/memcached-operator/api/v1alpha1**

i checked in github, this repo already gone, any other example we can use?

**Comment by camilamacedo86** [comment]
Hi @majorinche, 


The   `github.com/example/memcached-operator/api/v1alpha1` is an example of the import for the API scaffold in your project and not for any external repo. You can check a final example in the https://github.com/operator-framework/operator-sdk/tree/master/testdata/go/memcached-operator as well. 

The tutorial describes the steps that ought to be followed by users. The example which exists on that is for you know and validate the code implemented in the controller methods. These imports should be accordingly with your project. I mean, accordingly with the data used by you to run the commands in your local environment. The imports in the controller ought to point out the files in your project, for this scenario your api. 

So, check your go.mod and it will be your module + `api/<version of your api>` scaffolded.  E.g

- See the module in https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/memcached-operator/go.mod#L1
- See the api scaffolded in: https://github.com/operator-framework/operator-sdk/tree/master/testdata/go/memcached-operator/api/v1alpha1
- And then, see the import in the controller: https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/memcached-operator/controllers/memcached_controller.go#L35

I am closing this one as solved. However, please feel free to ping us if you need and/or to raise new issues.

**Comment by majorinche** [comment]
hi @camilamacedo86 
i try your example, and successfully get controller and memcache instance up, but when i checked log of controller, find some errors

E1021 00:53:19.613142       1 reflector.go:383] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to watch *v1.Pod: unknown (get pods)
E1021 00:53:25.112223       1 reflector.go:383] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to watch *v1.Pod: unknown (get pods)
E1021 00:53:37.115191       1 reflector.go:383] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to watch *v1.Pod: unknown (get pods)

i try delete one of instances, and the instance can restore ok, so i am not sure this error make any sense or not
