### ISSUE TITLE
Unable to use upstream Conditions as described in documentation

### ISSUE THREAD

**Issue by mikeandersen** [operator-framework/operator-sdk#4063]
## Bug Report

[The documentation](https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#manage-cr-status-conditions) was recently updated (#3997) to suggest using the upstream Conditions [from apimachinery](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go) for handling resource statuses. However, these resources appear to be new in 1.19+ and it looks like we can't update to that version due to a dependency conflict with the controller-runtime (kubernetes-sigs/controller-runtime#1033).

#### What did you do?

Attempted to follow the instructions under [Advanced Topics / Manage CR status conditions](https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#manage-cr-status-conditions).

```golang
import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type DatabaseUserStatus struct {
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}
```

#### What did you expect to see?

Access to the Condition struct and the various helper methods for handling Conditions.

#### What did you see instead? Under which circumstances?

I get an `Unresolved type 'Condition'` and none of the helper methods are available.

Attempting to upgrade apimachinery to `v0.19.2` makes it fail to build with the follow errors:
```
$ make

go: creating new go.mod: module tmp
go: found sigs.k8s.io/controller-tools/cmd/controller-gen in sigs.k8s.io/controller-tools v0.3.0
/Users/mikeandersen/.asdf/installs/golang/1.15.3/packages/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
# sigs.k8s.io/controller-runtime/pkg/log
../../.asdf/installs/golang/1.15.3/packages/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/log/null.go:48:32: undefined: logr.InfoLogger
# github.com/go-logr/zapr
../../.asdf/installs/golang/1.15.3/packages/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:133:34: undefined: logr.InfoLogger
make: *** [vet] Error 2
```

#### Environment

**Operator type:**
/language go

**Kubernetes cluster type:**
EKS

`$ operator-sdk version`

```
operator-sdk version: "v1.1.0", commit: "9d27e224efac78fcc9354ece4e43a50eb30ea968", kubernetes version: "v1.18.2", go version: "go1.15.2 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"
```

`$ go version`

```
go version go1.15.3 darwin/amd64
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by joelanford** [comment]
@mikeandersen are you able to use `github.com/operator-framework/operator-lib@v0.1.0/status.Conditions` until you're able to update to use k8s 1.19.x?

**Comment by joelanford** [comment]
Alternatively, you should be able to resolve the controller-runtime logr bump issue by explicitly requiring `github.com/go-logr/logr v0.2.1`

**Comment by joelanford** [comment]
If neither of these is sufficient, please re-open!

**Comment by mikeandersen** [comment]
Thanks @joelanford, installing `github.com/operator-framework/operator-lib@v0.1.0` works. 👍 

Might still be worth considering an update to the documentation since this may trip up other developers until [kubernetes-sigs/controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) v0.7 gets released. Not sure if there's an estimated release date but it's currently in alpha.
