### ISSUE TITLE
Generate zz_generated.deepcopy.go for new api version 

### ISSUE THREAD

**Issue by UdayVishwakarma** [operator-framework/operator-sdk#407]
Hi ,

I have to create a new apiversion for my operator. I have created new folder under `apis/<operator-name>/<new-api-version>`. I have created a new `types.go`. I need to generate the deep copy functions so that I can use it.

I run `operator-sdk generate k8s` it did not generate the deep copy functions. I have tried modifying `update-generated.sh` did not work.

Someone please help me how to do this?

Thanks

**Comment by UdayVishwakarma** [comment]
I have followed below steps to achieve it. I am not sure if this is the recommended way

- Manually created a folder under `apis/<operator-name>/<new-api-version>`
- Manually created `types.go`, `doc.go` and `register.go`
- Updated `tmp/codegen/updated-generated.sh` with new command as below

```
vendor/k8s.io/code-generator/generate-groups.sh \
deepcopy \
github.com/<operator-name>/pkg/generated \
github.com/<operator-name>/pkg/apis \
"<operator-name>:<new-api-version>" \
--go-header-file "./tmp/codegen/boilerplate.go.txt"
```

**Comment by theishshah** [comment]
Going to close this for now, as `generate k8s` is working as documented [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#define-the-memcached-spec-and-status)
