### ISSUE TITLE
What kind of license should be used for the GPL-3.0 License plug-in used in the operator

### ISSUE THREAD

**Issue by zhouhao3** [operator-framework/operator-sdk#4070]
#### What did you do?
We are going to make a new operator:

```
# Dockerfile at <project-name>/build/Dockerfile

FROM quay.io/operator-framework/ansible-operator

COPY roles/ ${HOME}/roles
COPY watches.yaml ${HOME}/watches.yaml

# New 'COPY' build step for playbook.yaml
COPY playbook.yaml ${HOME}/playbook.yaml

# Install the plug-in with a license of GPL-3.0
RUN ansible-galaxy collection install fos
```
When the subsequent playbook.yaml is executed, the functions of these plug-ins will be called.

Because we use some GPL-3.0 License plug-ins in the image, we are not sure what to use for the operator license we made.
So we want to hear your suggestions. thank you very much!

/language ansible

**Comment by jmrodri** [comment]
It looks like you are looking for a license suggestion for your operator. As we are not lawyer, we suggest you speak to your legal team to determine which license you should use for your operator.

I can tell you that the `ansible-operator`, `operator-sdk` and `helm-operator` are licensed under Apache 2.0: https://github.com/operator-framework/operator-sdk/blob/master/LICENSE

Also, I was able to find this on the Apache site which may help you: https://www.apache.org/licenses/GPL-compatibility.html
