### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#4080]
Our current CI on travis-ci.org will be EOL on December 31, 2020. 

travis-ci.com will still have free builds for open source projects but we need to migrate.

More info:

- [the newsletter](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom)
- [migration docs](https://docs.travis-ci.com/user/migrate/open-source-repository-migration)

**Comment by joelanford** [comment]
Big :+1: from me. I've been wanting to do this for awhile.

**Comment by joelanford** [comment]
This is complete.
