### ISSUE TITLE
FATA[0002] failed to initialize project with version "3-alpha": exit status 1

### ISSUE THREAD

**Issue by ming-ddtechcg** [operator-framework/operator-sdk#4098]
$ operator-sdk init --domain=example.com --repo=github.com/example-inc/memcached-operator
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.6.2
go: sigs.k8s.io/controller-runtime@v0.6.2 requires
        k8s.io/apiextensions-apiserver@v0.18.6 requires
        github.com/go-openapi/validate@v0.19.5 requires
        github.com/go-openapi/analysis@v0.19.5 requires
        github.com/go-openapi/loads@v0.19.0 requires
        github.com/globalsign/mgo@v0.0.0-20180905125535-1ca0a4f7cbcb: invalid version: git fetch --unshallow -f origin in /home/kubeeadm/go/pkg/mod/cache/vcs/0eb69f2163bb2fb915dbc4b9c83a68ab02240cc5c1aaa829e77cb6f9fd51e98d: exit status 128:
        fatal: git fetch-pack: expected shallow list
Error: failed to initialize project with version "3-alpha": exit status 1
Usage:
  operator-sdk init [flags]

Examples:
  \# Scaffold a project using the apache2 license with "The Kubernetes authors" as owners
  operator-sdk init --project-version=2 --domain example.org --license apache2 --owner "The Kubernetes authors"

Flags:
      --domain string            domain for groups (default "my.domain")
      --fetch-deps               ensure dependencies are downloaded (default true)
  -h, --help                     help for init
      --license string           license to use to boilerplate, may be one of 'apache2', 'none' (default "apache2")
      --owner string             owner to add to the copyright
      --plugins strings          Name and optionally version of the plugin to initialize the project with. Available plugins: ("ansible.sdk.operatorframework.io/v1", "go.kubebuilder.io/v2", "helm.sdk.operatorframework.io/v1")
      --project-name string      name of this project
      --project-version string   project version, possible values: ("2", "3-alpha") (default "3-alpha")
      --repo string              name to use for go module (e.g., github.com/user/repo), defaults to the go package of the current working directory.
      --skip-go-version-check    if specified, skip checking the Go version

Global Flags:
      --verbose   Enable verbose logging

FATA[0002] failed to initialize project with version "3-alpha": exit status 1

`$ operator-sdk version`

operator-sdk version: "v1.0.1", commit: "4169b318b578156ed56530f373d328276d040a1b", kubernetes version: "v1.18.2", go version: "go1.13.15 linux/amd64", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)
go version go1.15.2 linux/amd64

`$ kubectl version`
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by camilamacedo86** [comment]
Hi @ming-ddtechcg,

See the error faced by you: 
 
`github.com/globalsign/mgo@v0.0.0-20180905125535-1ca0a4f7cbcb: invalid version: git fetch --unshallow -f origin in /home/kubeeadm/go/pkg/mod/cache/vcs/0eb69f2163bb2fb915dbc4b9c83a68ab02240cc5c1aaa829e77cb6f9fd51e98d: exit status 128:`

Shows that you are unable to fetch/download the deps. So, it can be a firewall, for example, your  LAN has restrictions in place which not allows you to download it. However, a common scenario is your $GOPROXY not be set up with its default values for 1.13+ which are: `GOPROXY="https://proxy.golang.org,direct"` you can check it with `go env`.

Could you please ensure your GOPROXY and let us know?

**Comment by ming-ddtechcg** [comment]
Thanks for the feedback.

The host that I ran is capable to reach internet directly without the proxy setting.   

```
$ echo $GOPROXY

$
```

**Comment by camilamacedo86** [comment]
HI @ming-ddtechcg, 

The  `https://proxy.golang.org,direct` is the default setup for Golang. When you init an app it will require to get the dependencies and as you can see the error faced by you is `"invalid version: git fetch --unshallow"`. 

You need to set these values in your go env, otherwise, you would need to have the exactly the same versions required in your repository. More info: https://proxy.golang.org/.

**Comment by joelanford** [comment]
@ming-ddtechcg Can you try running `go clean -modcache` and retry the `operator-sdk init` command from an empty directory?

**Comment by joelanford** [comment]
@ming-ddtechcg I am not able to reproduce this after clearing my module cache. I tried with both `GOPROXY=https://proxy.golang.com,direct` and `GOPROXY=direct`. If you're able to provide more details about how to reproduce this issue, we can take another look!

**Comment by bhkamath** [comment]
Similar issue to me as well on my MacOS environment.  I have followed the cleanup and proxy setting but has no effect.  I suspect it is failing to fetch sumdb.

operator-sdk init --domain=example.com --repo=github.com/example-inc/memcached-operator
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.6.3
warning: GOPATH set to GOROOT (/usr/local/go) has no effect
go: sigs.k8s.io/controller-runtime@v0.6.3/go.mod: verifying module: sigs.k8s.io/controller-runtime@v0.6.3/go.mod: open /usr/local/go/pkg/sumdb/sum.golang.org/latest: no such file or directory
Error: failed to initialize project with version "3-alpha": exit status 1
Usage:
  operator-sdk init [flags]

Examples:
  # Scaffold a project using the apache2 license with "The Kubernetes authors" as owners
  operator-sdk init --project-version=2 --domain example.org --license apache2 --owner "The Kubernetes authors"


Flags:
      --domain string            domain for groups (default "my.domain")
      --fetch-deps               ensure dependencies are downloaded (default true)
  -h, --help                     help for init
      --license string           license to use to boilerplate, may be one of 'apache2', 'none' (default "apache2")
      --owner string             owner to add to the copyright
      --plugins strings          Name and optionally version of the plugin to initialize the project with. Available plugins: ("ansible.sdk.operatorframework.io/v1", "go.kubebuilder.io/v2", "helm.sdk.operatorframework.io/v1")
      --project-name string      name of this project
      --project-version string   project version, possible values: ("2", "3-alpha") (default "3-alpha")
      --repo string              name to use for go module (e.g., github.com/user/repo), defaults to the go package of the current working directory.
      --skip-go-version-check    if specified, skip checking the Go version

Global Flags:
      --verbose   Enable verbose logging

FATA[0001] failed to initialize project with version "3-alpha": exit status 1 

----------------------------------------------------------------------------------------

operator-sdk version                                                                   
operator-sdk version: "v1.2.0", commit: "215fc50b2d4acc7d92b36828f42d7d1ae212015c", kubernetes version: "v1.18.8", go version: "go1.15.4", GOOS: "darwin", GOARCH: "amd64"

go version                                                                             
warning: GOPATH set to GOROOT (/usr/local/go) has no effect
go version go1.15.5 darwin/amd64

kubectl version                                                                        
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by devrajmaker** [comment]
@camilamacedo86 hey i am getting the same error did everything i can do u but i am not able to solve it.

cgo: exec gcc: exec: "gcc": executable file not found in $PATH
Makefile:51: recipe for target 'vet' failed
make: *** [vet] Error 2
Error: failed to initialize project with version "3-alpha": exit status 2
Usage:
  operator-sdk init [flags]

Examples:
  # Scaffold a project using the apache2 license with "The Kubernetes authors" as owners
  operator-sdk init --project-version=2 --domain example.org --license apache2 --owner "The Kubernetes authors"

FATA[0004] failed to initialize project with version "3-alpha": exit status 2

**Comment by Sadiquedeveloper** [comment]
> @ming-ddtechcg I am not able to reproduce this after clearing my module cache. I tried with both `GOPROXY=https://proxy.golang.com,direct` and `GOPROXY=direct`. If you're able to provide more details about how to reproduce this issue, we can take another look!

can you please tell me how did you solve that error ?
