### ISSUE TITLE
Experiencing panic/crash while obtaining yaml package dependency

### ISSUE THREAD

**Issue by advancedwebdeveloper** [operator-framework/operator-sdk#4099]
Hi there.

I have an issue/bug [here ](https://github.com/kubernetes-sigs/yaml/issues/41).

I am using [gollvm](https://go.googlesource.com/gollvm/) - you can reproduce the bug, by installing my "release" build [from here](https://drive.google.com/file/d/1goBZhc2st89x4LswJivTFOpIbydJUi50/view?usp=sharing).
If someone curious about gollvm("llvm-goc") itself - you can find my build folder, compressed, [out here](https://drive.google.com/file/d/1da4__85ixcp9Jy-JRPOQ2tfC8HZMFe9B/view?usp=sharing).

**Comment by jberkhahn** [comment]
This seems unrelated to the SDK, seems to be a go tooling issue.
