### ISSUE TITLE
FATA[0120] Failed to run bundle: install plan is not available for the subscription: timed out waiting for the condition

### ISSUE THREAD

**Issue by shimron** [operator-framework/operator-sdk#4100]
#### What did you do?

operator-sdk run bundle 

#### What did you expect to see?

operator installed

#### What did you see instead? Under which circumstances?

`operator-sdk run bundle {host}/zhenjin-operator-bundle:0.0.1 -n operators `

`INFO[0013] Successfully created registry pod: {host}-zhenjin-operator-bundle-0-0-1`

`INFO[0013] Created CatalogSource: zhenjin-operator-catalog `

`INFO[0013] Created Subscription: zhenjin-operator-v0-0-1-sub `

`FATA[0120] Failed to run bundle: install plan is not available for the subscription zhenjin-operator-v0-0-1-sub: timed out waiting for the condition`

#### Environment

**Operator type:**

 /language go 

**Kubernetes cluster type:**

tencent kuberneters engine

`$ operator-sdk version`

`operator-sdk version: "v1.1.0", commit: "9d27e224efac78fcc9354ece4e43a50eb30ea968", kubernetes version: "v1.18.2", go version: "go1.15 linux/amd64", GOOS: "linux", GOARCH: "amd64"`

`$ kubectl version`

`Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.3-tke.11", GitCommit:"43d7ff3fae76c311692393308feeca4ceb740ebc", GitTreeState:"clean", BuildDate:"2020-10-12T03:32:22Z", GoVersion:"go1.12.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.3-tke.11", GitCommit:"43d7ff3fae76c311692393308feeca4ceb740ebc", GitTreeState:"clean", BuildDate:"2020-10-12T03:37:10Z", GoVersion:"go1.12.14", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by ica10888** [comment]
Through the log print out, perhaps the operator deployment has not ready when timed out waiting for the condition.
Could execute this commd
``` shell 
kubectl get pod 
```
watch the operator deployment  and operator-controller-manager deployment  is ready
my cluster is shown as follows
``` shell
NAME                                                              READY   STATUS              RESTARTS   AGE
38690f29336a04428b319ebecf75ae4839a338f273250e7868985bb9c9gk9kd   0/1     Completed           0          19m
docker-io-xxx-test-operator-v1-0-0                           1/1     Running             0          19m
test-operator-controller-manager-55d8749c57-g2psh                 0/2     ImagePullBackOff    0          17m
```
So I set the operator-controller-manager images which can pulled and it worked.

**Comment by ica10888** [comment]
https://github.com/operator-framework/operator-sdk/issues/3691
The same question.
