### ISSUE TITLE
Clarify purpose of ansible-operator and helm-operator binaries

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-sdk#4106]
The Operator SDK project officially builds and distributes `ansible-operator` and `helm-operator` binaries in our GitHub releases.

In our docs, we should clarify what the purpose of these release binaries is.

They are used in the ansible and helm operator base images, and they are used by the scaffolded project ansible and helm Makefiles for `make run`, which runs the operator locally.

/language ansible
/language helm

**Comment by asmacdo** [comment]
+1, though I am not really sure **where** would make sense.

**Comment by jberkhahn** [comment]
We discussed this and decided to make the binaries output help text that they are not supposed to be manually used, and their purpose is to be used by the scaffolded projects.
