### ISSUE TITLE
Generate release binary signatures with a consistent GPG key

### ISSUE THREAD

**Issue by jharmison-redhat** [operator-framework/operator-sdk#4114]
#### Describe the problem you need a feature to resolve.

I have an issue when using CI to download and validate the signature of releases of the Operator SDK. At the moment, the binary signing process appears to be done manually by the releaser, and the releaser is not consistent between versions.

I do not want to wholesale accept GPG keys programatically based on whoever signed the release, and so I validate the signatures and identity of the signer personally as much as possible before adding the signature to my list to be imported during CI processes. This means that, every time a new release is generated with a key I have not whitelisted before, I have a failed build when tracking the latest release or bumping SDK versions.

My use case is that the `operator-sdk` binaries generate and validate bundles as part of a release flow for some community operators I work on.

#### Describe the solution you'd like.

I would like it if a CI process for the Operator SDK generated releases signed by a common, trusted, and widely published GPG key. This would enable my whitelist to remain static between releases and increase community trust in the validity of the signatures.

The drawbacks would be that team members would not be able to release ad-hoc binary releases with signatures in the current workflow that they appear to be using (I am unfamiliar with the way it is currently actually occurring).

An alternate approach that I would consider reasonably acceptable is a published list of all member GPG key IDs. I would likely not scrape it programatically still, and my whitelist could potentially drift from the current state of that published list, but I think failure to validate signatures would be less common in this scenario.

**Comment by joelanford** [comment]
This is good timing! We're planning to do as you suggest and use a release-specific GPG key to sign release binaries published to the GitHub release page.

If you're interested in the nitty-gritty details, you can peruse our proposal here:
https://github.com/operator-framework/operator-sdk/blob/master/proposals/automating-releases.md

**Comment by jharmison-redhat** [comment]
Ah, terrific!

I did search all issues (including closed) for the word `gpg`, but didn't peruse the proposals.

I appreciate the link! Looks like it meets my needs exactly!
