### ISSUE TITLE
Create a test to ensure that user-facing deps are installed in ansible base image

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4123]
#### Describe the problem you need a feature to resolve.

The [old mock data](https://github.com/operator-framework/operator-sdk/blob/v0.19.x/test/ansible-memcached/secret/tasks/main.yml#L16-L20) for Ansible has a task whcih is broke/invalid. I mean, if we add this task in the Memcached sample and deploy and test the project we will face the error: 

```
  --------------------------- Ansible Task StdOut -------------------------------
2480        
2481         TASK [Check if jmespath is installed] ******************************** 
2482        fatal: [localhost]: FAILED! => {"msg": "Error in jmespath.search in json_query filter plugin:\n'app' is undefined"}
2483        
```

See that this task has not been called/executed and tests at all. However,  after a chat over it with @asmacdo we decided that: 
- It is fine to remove it since it is useless 
- we should raise an issue to check if we should have a check to ensure that jmespath is installed 
- and might is also valid re-check if we should really have the jmespath installed by default. 

#### Describe the solution you'd like.

IMO (@camilamacedo86) 

- **regards the test:** we do not need to ensure check if the pre-requirements from the images are installed since it is properly tested indirectly. I mean, if some need not be installed in the image then, the tests will fail as well. So, nothing required to be done. 
- **regards remove the need to install the jmespath:** I think we cannot do that now because it would mean a breaking change, however, if it is not required for all users and is not used in the 80% I do not see a reason to keep that in the image which means that we can track a specific issue to remove and doc how users can use this feature which could be addressed only for v2+ ansible plugin.

**Comment by camilamacedo86** [comment]
Hi @asmacdo @fabianvf, 

Would you like to add your input?

**Comment by asmacdo** [comment]
+1 to adding this test because there is nothing in the sdk repo that uses jmespath but removal could be a user-facing backwards incompatible. (operator authors may be using `json_query`)

**Comment by asmacdo** [comment]
The test doesn't need to take the same form, it would probably be better to use [python requirements module ](https://docs.ansible.com/ansible/latest/collections/community/general/python_requirements_info_module.html)

**Comment by fabianvf** [comment]
Agree with Austin, we can validate that it's installed with the requirements module (and maybe we should do the same for the other python libraries we install, ie, kubernetes and openshift)

**Comment by camilamacedo86** [comment]
Just to clarifies: 

The check `Check if jmespath is installed` has not been called and its code is invalid. We can easily check it by looking on the e2e-ansible task output of any CI job. E.g search for `Check if jmespath is installed` in https://travis-ci.com/github/operator-framework/operator-sdk/jobs/420868963
