### ISSUE TITLE
How to provide ServiceMonitor of an operator with OLM

### ISSUE THREAD

**Issue by miguelsorianod** [operator-framework/operator-sdk#4124]
## Type of question

General operator-related help

## Question

Hi,

I'm working on migrating an operator from v0.x to v1.1.0. One of the changes I've noticed is that the ServiceMonitor does not seem to be created by the operator anymore, and it's a standalone object in config/prometheus.

However, when I generate the bundle the object is not there. Thus, when I install the operator using OLM through the bundle the ServiceMonitor is not there.

Take into account that Prometheus might be or might not be installed in the destination cluster. This is, the API type that deals with ServiceMonitors might not be defined in the K8s API (because it's only defined when Prometheus K8s CRDs have been installed)
Additionally, the destination cluster might be a cluster where the old packagemanifests format is the image format used too.

What would be the recommended approach there?

Thank you.

**Comment by camilamacedo86** [comment]
Hi @miguelsorianod, 

For the new layout (>= +1.0), you will update the kustomize.yml file to enable the Prometheus metrics. See an example in the `testdata/` samples: https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/memcached-operator/config/default/kustomization.yaml#L26-L27

For further information see the doc: https://book.kubebuilder.io/reference/metrics.html. 

I will close this one as sorted out. However, please feel free to raise new issues with new questions and/or ping us if the info provided above does not answer the specific question.

**Comment by miguelsorianod** [comment]
Hi @camilamacedo86,

Even if you enable prometheus the ServiceMonitor does NOT automatically end up in the bundle.

**Comment by camilamacedo86** [comment]
Hi @miguelsorianod, 

You need to enable tthe metrics as described in https://github.com/operator-framework/operator-sdk/issues/4124#issuecomment-719544629. However, regards its integration with OLM shows that it will be addressed in PR #4137. @joelanford let me know if I missed something about the #4137 change.

**Comment by miguelsorianod** [comment]
Hi @camilamacedo86,

When enabling the metrics as described in https://github.com/operator-framework/operator-sdk/issues/4124#issuecomment-719544629 the ServiceMonitor is not automatically added to the bundle. I think https://github.com/operator-framework/operator-sdk/pull/4137 that you are referencing might solve that.

However, I think #4137 might not address this part of the comment:
```
Additionally, as commented above even if that is added in the bundle there will be issues when the destination cluster might or might not have Prometheus installed. When you offer your operator you cannot anticipate to that fact.
```

**Comment by camilamacedo86** [comment]
Hi @miguelsorianod, 


The error faced occurs because the cluster has not Prometheus installed. We discussed this issue in the bug triage and OLM might have an option to solve this kind of dependency if you cannot ensure that Prometheus will be installed on the cluster. 

From the SDK side, we can say that it solves with #4137. Could you please raise this question in OLM repository? Its maintainers might able to give a better answer over how we can define that a pre-requirements such as Prometheus is required for the project.   

In this way, I am closing this issue as was decided in the bug triage meeting. However, please feel free to raise new issues if you need.
