### ISSUE TITLE
Steps in golang tutorial under Cleanup are not sufficient 

### ISSUE THREAD

**Issue by fgiloux** [operator-framework/operator-sdk#4146]
#### What did you do?

I followed the steps here:
https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#cleanup

#### What did you expect to see?

that all resources created by the tutorial are deleted
 
#### What did you see instead? Under which circumstances?

remaining resources:

clusterRoles
- manager-role 
- memcached-operator-manager-role 
- memcached-operator-metrics-reader 
- memcached-operator-proxy-role

ClusterRoleBindings
- memcached-operator-manager-rolebinding
- memcached-operator-proxy-rolebinding

In addition there are the following instructions
$ kubectl delete deployments,service -l control-plane=controller-manager
$ kubectl delete role,rolebinding --all

The second line is a bit hazardous for an existing namespace as it will also delete role and rolebindings that have been created outside of the tutorial.

It may make sense to either
- state that a new namespace should be created for the tutorial and delete it at the end
- or be more specific to the roles and rolebindings that should be deleted:
$ kubectl delete role memcached-operator-leader-election-role
$ kubectl delete rolebinding memcached-operator-leader-election-rolebinding

#### Environment

Tested with OpenShift 4.5 but apply to other Kubernetes distributions.

#### Possible Solution

See above

#### Additional context

If this makes sense to you I am happy to create a pull request to amend the documentation

**Comment by camilamacedo86** [comment]
Hi @fgiloux, 

When the SDK supports by default the v3+ plugin it will be solved because the following target will be in the Makefile:

```
# UnDeploy controller from the configured Kubernetes cluster in ~/.kube/config
undeploy:
	$(KUSTOMIZE) build config/default | kubectl delete -f -
````

Could you please try to add this target and check if it will clean all ?

**Comment by fgiloux** [comment]
Hi @camilamacedo86 

first thing it did:
namespace "memcached-operator-system" deleted

If you want to keep it this way I would recommend to state in the tutorial to create a new namespace and not to use an existing one.
Next it delete crd, cluster roles ,etc which is good.
One little thing is that it also tries to delete deployment and service inside the deleted namespace

**Comment by camilamacedo86** [comment]
Hi @fgiloux, 

 > If you want to keep it this way I would recommend to state in the tutorial to create a new namespace and not to use an existing one.

The new namespace for the operator is created by default it is the projectname + system. The tutorial is based on the version > v1.0. 


Note that the target suggested is how it is done for v3+ plugin in upstream which means that when SDK supports v3+ plugin by default it would be solved at this way.

**Comment by fgiloux** [comment]
Hi @camilamacedo86

I have created the PR (as you can see). I also modified the deployment namespace to something different than "default", which already exists in kubernetes clusters to avoid having resources created in this namespace prior to the tutorial being deleted as well. I hope this makes sense to you.
