### ISSUE TITLE
README Quick Start needs to clarify some assumptions

### ISSUE THREAD

**Issue by benjaminapetersen** [operator-framework/operator-sdk#415]
Just pointing out some more items that would be helpful to clarify to reduce friction.  As I mentioned in my prev issue #372, I'm fairly new to golang and don't work directly on kubernetes.  I do however consume the API & build UI on top of it.

When I got to the section: 

`Create and deploy an app-operator using the SDK CLI:`  

I found that this line specifically:

`$ operator-sdk build quay.io/example/app-operator`

needs some explanation.

- `operator-sdk build` is not similar to `docker build`.  IE, you cannot `operator-sdk build .` and expect it to work.  It needs a specific path, which happens to be what is defined after your `$GOPATH`, the directory in which your operator code was generated, however, you cannot include the `$GOPATH`.  So, if the path is `~/go/src/github.com/my-operator`, and `$GOPATH` is `~/go`, then you must `operator-skd build github.com/my-operator`.  Even if your `cwd` is this directory (part why the `operator-sdk build .` error was puzzling).
- The path in `operator-sdk build quay.io/example/app-operator` does not match the `--api-version=app.example.com/v1alpha1` path in the line `operator-sdk new app-operator --api-version=app.example.com/v1alpha1 --kind=App`.  It seems sensible they should potentially match, but in fact, it is not important (as far as I understand).
- `operator-sdk build <path>` followed by `docker push <path>` still implies relationship to `docker build` (because a container is built), and some explanation here would be helpful.  Perhaps my container registry is not `quay.io`, its `registry.gitlab.com` or `hub.docker.com` or any other registry that does not happen to match the path where my operator lives (or perhaps its pushed to more than one registry for *reasons*).

Thanks!

**Comment by joelanford** [comment]
@benjaminapetersen `operator-sdk build` is an opinionated `docker build` that uses specific paths and files from your operator-sdk project, so your third point is how you should interpret it.

There's more documentation for `operator-sdk build` [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#build), or users can run `operator-sdk build -h` to get mostly the same information.

I noticed that we don't link to the SDK CLI reference from the README or User Guide, so I submitted #863 to make that document more prominent.
