### ISSUE TITLE
The makefile target bindata has showing errors (Mac)

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4152]
#### What did you do?

`make bindata`

#### What did you expect to see?

Generate the bindata succefully 

#### What did you see instead? Under which circumstances?

```
 $ make bindata
./hack/generate/olm_bindata.sh 0.15.1
Deleting previous versions of olm-bindata files if they exist
downloading olm manifests for version 0.15.1
./hack/generate/olm_bindata.sh: line 6: wget: command not found
./hack/generate/olm_bindata.sh: line 7: wget: command not found
go: github.com/kisielk/errcheck upgrade => v1.4.0
go: golang.org/x/lint upgrade => v0.0.0-20200302205851-738671d3881b
go: golang.org/x/xerrors upgrade => v0.0.0-20200804184101-5ec99f83aff1
go: golang.org/x/tools upgrade => v0.0.0-20201031021630-582c62ec74d0
go: downloading golang.org/x/tools v0.0.0-20201031021630-582c62ec74d0
go: golang.org/x/mod upgrade => v0.3.0
go: downloading golang.org/x/net v0.0.0-20201021035429-f5854403a974
go: downloading golang.org/x/sys v0.0.0-20200930185726-fdedc70b468f
```

#### Environment

- Mac

> operator-sdk version: "v1.1.0-7-gcc409fb3", commit: "cc409fb3b0b8785a794e503e2d2238fd950652ce", kubernetes version: "v1.18.8", go version: "go1.15.2 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"

#### Possible Solution

Replace the command wget for a command/logic that is supported in Mac and Linux.

**Comment by camilamacedo86** [comment]
c/c @varshaprasad96

**Comment by varshaprasad96** [comment]
Mac does not come with `wget`. We could use `curl` instead.
