### ISSUE TITLE
check link docs fails when we add a new document

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4157]
#### What did you do?

Add a new command to the tool and run make generate to update the CLI docs

#### What did you expect to see?

The docs link check NOT fail in the CI when we add a new doc

#### What did you see instead? Under which circumstances?

```
- /target/docs/cli/operator-sdk_edit/index.html
  *  External link https://github.com/operator-framework/operator-sdk/edit/master/website/content/en/docs/cli/operator-sdk_edit.md failed: 404 No error
htmlproofer 3.15.0 | Error:  HTML-Proofer found 1 failure!
Makefile:113: recipe for target 'test-links' failed
make: *** [test-links] Error 1
The command "make test-links" exited with 2.
```

**Comment by camilamacedo86** [comment]
c/c @asmacdo

**Comment by asmacdo** [comment]
We have new links on every docs page 
![Screenshot from 2020-11-02 14-03-44](https://user-images.githubusercontent.com/1028657/97908137-4c349d00-1d14-11eb-877b-3c8e6caa2a16.png)

"Edit this page" links to github. This will break our link checker for every PR that adds a new doc. We need 

Option 1add a mechanism  to skip links 
Option 2 remove this feature.

**Comment by asmacdo** [comment]
I pushed the following diff to @camilamacedo86's PR https://github.com/operator-framework/operator-sdk/pull/4156

```
docker run --rm -v sdk-html:/target mtlynch/htmlproofer /target --empty-alt-ignore --http-status-ignore 429 --allow_hash_href
docker run --rm -v sdk-html:/target mtlynch/htmlproofer /target \
  --empty-alt-ignore \
  --http-status-ignore 429 \
  --allow_hash_href \
  --url-ignore "https://github.com/operator-framework/operator-sdk/edit/master/*"
```

This will ignore all the "edit this page" links in the link checker.

**Comment by asmacdo** [comment]
Fixed by https://github.com/operator-framework/operator-sdk/pull/4205
