### ISSUE TITLE
Ansible operator needs a way to pass vars as "unsafe"

### ISSUE THREAD

**Issue by agaffney** [operator-framework/operator-sdk#4169]
#### Describe the problem you need a feature to resolve.

I'm writing an operator that accepts values that look like Jinja templates but aren't. Ansible is attempting to interpret these and blowing up.

#### Describe the solution you'd like.

Ansible (since 2.8-ish) allows you to specify vars as "unsafe" via JSON (such as when submitted via extra vars). You can do this via the following syntax:

```json
{"some_var": {"__ansible_unsafe": "some unsafe value with {{templates}} in it"}}
```

This results in `some_var: some unsafe value with {{templates}} in it` and Ansible will not evaluate (what appears to be) Jinja templates in it.

It would be nice if there was a way to tell the Ansible Operator SDK to use this notation with any vars passed to the playbook/role.

**Comment by agaffney** [comment]
Just for some extra context, the noted JSON "unsafe" syntax is the equivalent of using the `!unsafe` YAML tag. An alternative is passing the extra vars in YAML format and using that tag.

**Comment by agaffney** [comment]
This same problem is being attacked a different way via https://github.com/ansible/ansible/pull/72547, which will appear in the next major Ansible version. This will allow referencing a "complex" var passed by the operator using the `!unsafe` tag and have it apply to all nested strings.

**Comment by fabianvf** [comment]
I think it would make sense to have values from the CR be tagged unsafe by default, I don't think we should be evaluating those unless the author explicitly opts in

**Comment by agaffney** [comment]
Probably, but I suggested making it opt-in to not break any cases where people are currently relying on this behavior.

**Comment by jmrodri** [comment]
Moving this to milestone v1.5.0 as it will not be done in time for v1.4.0
