### ISSUE TITLE
How to restart a virtual service from controller in OperatorSDK v1.0.0

### ISSUE THREAD

**Issue by anusood** [operator-framework/operator-sdk#4171]
Once a pod is recreated from inside the controller, I want a Virtual Service of Istio to be recreated as well. What package/third party API can help me with it.

**Comment by jberkhahn** [comment]
So, if you take a look at the [example controller implementation](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/memcached-operator/controllers/memcached_controller.go) you can see how to use the reconciler API to query and manipulate deployments and other core kubernetes types. You can follow this same pattern with custom types such as those implemented in the Istio operator, assuming those types are present on your cluster. You would have to import whatever library those Istio types are declared in and use them the same way. 

The Istio operator itself also might offer more support for hooking into things, but I am not familiar with its exact functionality.
