### ISSUE TITLE
Quickstart Makefile doesn't work

### ISSUE THREAD

**Issue by witchbutter** [operator-framework/operator-sdk#4177]
## Type of question

Open question

## Question
I am running through the tutorial here: https://sdk.operatorframework.io/docs/building-operators/helm/quickstart/
I am using MacOS Catalina.  It does not work and there seems to be nowhere else to ask about it but here.

#### What did you do?
Follow the directions to the letter until the step (obviously I substituted a real registry and project):
`make docker-build docker-push IMG=<some-registry>/<project-name>:<tag>`

Which fails every time with this error:
```
nginx-operator/bin: No such file or directory
make: *** [docker-build] Error 127
```
In the makefile I see that the bin directory should be generated but I have no idea why it isn't generated.  A minikube cluster is available and its context selected and I am using the registry at my personal docker hub account.

#### What did you expect to see?

I expect a quickstart to actually work

#### What did you see instead? Under which circumstances?

A dead end with no clear way to troubleshoot

#### Environment

**Operator type:**
/language helm

**Kubernetes cluster type:**
```
😄  minikube v1.14.2 on Darwin 10.15.7
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=8192MB, Disk=20000MB) ...
❗  This VM is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.18.8 on Docker 19.03.12 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" by default
```
**operator-sdk version**
`operator-sdk version: "v1.1.0", commit: "9d27e224efac78fcc9354ece4e43a50eb30ea968", kubernetes version: "v1.18.2", go version: "go1.15.2 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"`

**go version**
`go version go1.15.3 darwin/amd64`

**kubectl version**
`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by joelanford** [comment]
I'm not able to reproduce this on my Linux machine.

Looking at the Dockerfile, there are no references to `bin`, so this error seems to be something going on in the Makefile. Also, the `docker-build` and `docker-push` targets have no make dependencies, so I would think that you would see this error with _any_ make targets. This seems like an issue with your environment somehow. Can you try running other make targets to see if any of them work?

@camilamacedo86 is our resident macOS contributor. She can probably try to reproduce on her machine as well, though I suspect she'll be unable to reproduce since she hasn't mentioned this problem yet.

**Comment by witchbutter** [comment]
I do see the error with any make targets.  `docker build` and `docker-push` work.

**Comment by camilamacedo86** [comment]
I have a mac as well although it has no relation at with the SO kind. 

Note that:

The error `nginx-operator/bin: No such file or directory` is faced because it is looking for the bin/ directory which is **ONLY** required and added when we would run the operator locally with the make target `make run`. The quick-start do not cover it since it has not this step. 

So, you probably executed another step, such as `make run` and faced some issue to download the bin. PS. It also worked successfully for me.

**Comment by witchbutter** [comment]
I did not previously run make run.  I can delete minikube and the folder and start from scratch and still get the exact same output:
```
witchbutter@localhost > minikube start --vm-driver=hyperkit --memory 8192 --kubernetes-version=1.18.8
😄  minikube v1.14.2 on Darwin 10.15.7
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=8192MB, Disk=20000MB) ...
❗  This VM is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.18.8 on Docker 19.03.12 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" by default
witchbutter@localhost > mkdir nginx-operator                                                        (minikube/default)
witchbutter@localhost > cd nginx-operator                                                           (minikube/default)
witchbutter@localhost > operator-sdk init --plugins=helm                             (minikube/default)
Next: define a resource with:
$ operator-sdk create api
witchbutter@localhost > operator-sdk create api --group demo --version v1 --kind Nginx
Created helm-charts/nginx
Generating RBAC rules
WARN[0000] The RBAC rules generated in config/rbac/role.yaml are based on the chart's default manifest. Some rules may be missing for resources that are only enabled with custom values, and some existing rules may be overly broad. Double check the rules generated in config/rbac/role.yaml to ensure they meet the operator's permission requirements.
witchbutter@localhost > make docker-build docker-push IMG=witchbutter/testoperator:0.0.2
env: Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/opt/puppetlabs/bin:/opt/puppetlabs/pdk/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/witchbutter/.rvm/bin:/Users/witchbutter/nginx-operator/bin: No such file or directory
env: Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/opt/puppetlabs/bin:/opt/puppetlabs/pdk/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/witchbutter/.rvm/bin:/Users/witchbutter/nginx-operator/bin: No such file or directory
docker build . -t witchbutter/testoperator:0.0.2
env: Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/opt/puppetlabs/bin:/opt/puppetlabs/pdk/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/witchbutter/.rvm/bin:/Users/witchbutter/nginx-operator/bin: No such file or directory
make: *** [docker-build] Error 127
```

**Comment by joelanford** [comment]
> env: Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/opt/puppetlabs/bin:/opt/puppetlabs/pdk/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/witchbutter/.rvm/bin:/Users/witchbutter/nginx-operator/bin: No such file or directory
env: Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/opt/puppetlabs/bin:/opt/puppetlabs/pdk/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/witchbutter/.rvm/bin:/Users/witchbutter/nginx-operator/bin: No such file or directory

I've never seen lines like this in anything the SDK or Makefile would output, but it looks like it _could_ be related to a combination of your shell or environment and this line in the Makefile:

```Makefile
SHELL := env PATH=$(PATH) /bin/sh
```

Can you try removing or tweaking this line?

**Comment by witchbutter** [comment]
I rewrote the lines to a sensible default:
`SHELL := env PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin /bin/sh`
The path you see above is created by homebrew and I wonder if maybe it is just too long for /bin/sh to handle.  It is working with the reduced path.
