### ISSUE TITLE
Trying to write a validating webhook 

### ISSUE THREAD

**Issue by harche** [operator-framework/operator-sdk#4179]
#### What did you do?
I want to restrict the number of CRs that users are allowed to create, and to do so I am writing an admission webhook. I implemented a basic [ValidateCreate](https://github.com/harche/kata-operator/blob/webhook/api/v1/kataconfig_webhook.go#L47) by following the operator sdk [tutorial](https://v1-0-x.sdk.operatorframework.io/docs/building-operators/golang/webhooks/) on admission webhooks.

#### What did you expect to see?
I was expecting that when I am trying to create a CR of type KataConfig, a webhook will verify if there is any CR of that type already exists or not and prevent the user from creating one if one already exists. 

#### What did you see instead? Under which circumstances?
I saw in the manager logs that the webhook is getting initialized properly, 

```
2020-11-04T07:33:54.245Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": "127.0.0.1:8080"}
2020-11-04T07:33:57.048Z	INFO	controller-runtime.builder	skip registering a mutating webhook, admission.Defaulter interface is not implemented	{"GVK": "kataconfiguration.openshift.io/v1, Kind=KataConfig"}
2020-11-04T07:33:57.048Z	INFO	controller-runtime.builder	Registering a validating webhook	{"GVK": "kataconfiguration.openshift.io/v1, Kind=KataConfig", "path": "/validate-kataconfiguration-openshift-io-v1-kataconfig"}
2020-11-04T07:33:57.048Z	INFO	controller-runtime.webhook	registering webhook	{"path": "/validate-kataconfiguration-openshift-io-v1-kataconfig"}
2020-11-04T07:33:57.049Z	INFO	setup	starting manager
I1104 07:33:57.049337       1 leaderelection.go:243] attempting to acquire leader lease  kata-operator-system/290f4947.kataconfiguration.openshift.io...
2020-11-04T07:33:57.049Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
2020-11-04T07:33:57.049Z	INFO	controller-runtime.webhook.webhooks	starting webhook server
2020-11-04T07:33:57.050Z	INFO	controller-runtime.certwatcher	Updated current TLS certificate
2020-11-04T07:33:57.050Z	INFO	controller-runtime.certwatcher	Starting certificate watcher
2020-11-04T07:33:57.051Z	INFO	controller-runtime.webhook	serving webhook server	{"host": "", "port": 9443}
```

But when I am trying to create multiple CRs of type KataConfig, I don't see any interruptions by the webhook at all for those requests. 

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

`$ operator-sdk version`
operator-sdk version: "v1.0.1-10-g3efd819c", commit: "3efd819c712f96fa9ce85133c6b660f0c37bb23f", kubernetes version: "v1.18.2", go version: "go1.15.2 linux/amd64", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)
go version go1.15.2 linux/amd64

`$ kubectl version`

**Comment by camilamacedo86** [comment]
hI @harche, 

To work with webhooks you need to have the cert-manager installed on the cluster. My guess is that it is missing. Also, note that it gets a few minutes to be fully installed. You need to follow the instructions in: https://cert-manager.io/docs/installation/kubernetes/

also, see that for this scenario you can check the sample https://github.com/operator-framework/operator-sdk-samples/tree/master/go/memcached-operator or here in the [testdata/go/memcached-operator]https://github.com/operator-framework/operator-sdk/tree/master/testdata/go/memcached-operator] dir which does the same. 

IMO we need to add the info over the cert-manager on the docs. Would you like to collab with this project by pushing a PR for that? WDYT?

**Comment by absynth76** [comment]
Hello, I somehow disagree with the response, you don't need cert manager, you need to instruct kubernetes to consume your webhook as described here https://sdk.operatorframework.io/docs/building-operators/ansible/reference/webhooks/
It's not because you are using cert-manager in a test that you are forced to use a cert-manager issued test (even if I don't disagree with the fact that cert-manager is the de-facto standard for certificate management within a cluster)

The certificate here helps kubernetes api to trust your webhook server, so be sure you are using a CA it knows or add it to the truststore , (the memcached operator sample is generating a selfsign with help of cert-manager in that sense).

When you'll deploy your ValidatingWebhookConfiguration the value for
webhooks[*].clientConfig.caBundle will have to match that certificate (or CA in case you don't use a self sign)

**Comment by varshaprasad96** [comment]
Hi @absynth76, yes, cert-manager is not the only solution. But as provided in the kubebuilder [tutorial](https://book.kubebuilder.io/cronjob-tutorial/cert-manager.html) any third-party solutions work as long as certs are in the desired location. 

We may have to look at the scaffolded CRD (or the scaffolded project - if possible), just to ensure that the webhookClientConfig is right and if there is anything missing. Some reasons which I can think of for this are:
1. Is the webhook registered with the manager ? Typically this should happen when you use `create webhook` command. You can have a look at [this](https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation.html) section for reference. 
2. If you using any other certificate authority, you can also specify the CA info while setting up the webhook with manager (ex: [here](https://github.com/varshaprasad96/memcached-operator/blob/conv-wh-specify-config/api/v1/memcached_webhook.go#L42-L46)). Is the location of cert at the same place where controller-runtime expects it to be ([ref](https://github.com/kubernetes-sigs/controller-runtime/blob/011cd8ae62dba632cf63f0637971cbca813cbf29/pkg/manager/manager.go#L209))
3. If you have followed the tutorial as it is, can you also please check if the[ `ValidatingWebhookConfiguration`](https://book.kubebuilder.io/cronjob-tutorial/cert-manager.html) exists in the cluster (`Kubectl get ValidatingWebhookConfiguration --all-namespaces`)
