### ISSUE TITLE
Implement CertGenerator 

### ISSUE THREAD

**Issue by fanminshi** [operator-framework/operator-sdk#419]
There are 5 cases that the CertGenerator impl needs to handle:

- [x] case: Both TLS encryption key and cert and CA are in the cluster. ref: 
https://github.com/operator-framework/operator-sdk/pull/412
- [x] Testing above. ref: https://github.com/operator-framework/operator-sdk/pull/439
- [x] case: TLS encryption key and cert are in the cluster but not the CA. ref: https://github.com/operator-framework/operator-sdk/pull/444
- [x] Testing above. ref: https://github.com/operator-framework/operator-sdk/pull/444
- [x] case: TLS encryption key and cert not in the cluster but the CA is. ref: https://github.com/operator-framework/operator-sdk/pull/446
- [x] Testing above. ref: https://github.com/operator-framework/operator-sdk/pull/446
- [x] case: None of the TLS encryption key and cert and the CA are in the cluster. ref: https://github.com/operator-framework/operator-sdk/pull/450
- [x] Testing above. ref: https://github.com/operator-framework/operator-sdk/pull/450
- [ ] case: CA is passed in.
- [ ] Testing above

**Comment by hasbro17** [comment]
The TLS cert generation pkg at `pkg/tls` is, for all intents and purposes, not supported anymore.
It was an early stage experimental effort to make it easier for operators to issue TLS certs to their applications but there are more complete solutions that exist like https://github.com/jetstack/cert-manager.

The SDK may support generating cert-manager manifests in the future.
