### ISSUE TITLE
Basic Scorecard Test not Working

### ISSUE THREAD

**Issue by lsalazar1** [operator-framework/operator-sdk#4193]
## Type of question

How to implement a specific feature

## Question
I'm trying to get a scorecard to work for an operator we created at work. We thought something as simple as defining an .osdk-scorecard.yaml and running `operator-sdk scorecard` would work. Unfortunately, the results say were encountering a fatal error[0000] (a bundle image or directory is required). What would I need to do to get this scorecard to work?

#### What did you do?
1) Clone repo
2) Create .osdk-scorecard in project root
    
![Screen Shot 2020-11-04 at 11 45 29 PM](https://user-images.githubusercontent.com/42328472/98202695-20720c80-1ef8-11eb-9aad-52e12b765c95.png)

#### Environment

**Operator type:**

 /language go

**Kubernetes cluster type:**

Openshift 4.3

`$ operator-sdk version`

operator-sdk version: "v1.1.0", commit: "9d27e224efac78fcc9354ece4e43a50eb30ea968", kubernetes version: "v1.18.2", go version: "go1.15 linux/amd64", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.15.3 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"a02f27a", GitTreeState:"clean", BuildDate:"2020-04-13T12:04:13Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by camilamacedo86** [comment]
Hi @lsalazar1, 

Could you please provide further information to let us know the following?

- What is the command used to run the scorecard ? Is it `operator-sdk scorecard  bundle --selector=suite=basic --output=json --wait-time=60s`?
- Did you build the bundle (make bundle) and its image before running the scorecard (make bundle IMG=<some-registry>/<project-name>:<tag>)?
- Could you please provide the full output of the error?

**Comment by jmccormick2001** [comment]
.osdk-scorecard.yaml  was the older style scorecard configuration, you will want to be using the new scorecard config.yaml file, there is a sample of it in the SDK repo and it also gets scaffolded out when you create a new project.

**Comment by lsalazar1** [comment]
Ah okay, I was running v1.1.0 when I should've been using v.0.17.0 (squad set this version as mandatory). The scorecard command has been somewhat functional. 

We've had times were it will output what we're expecting
![Screen Shot 2020-11-05 at 11 21 04 AM](https://user-images.githubusercontent.com/42328472/98291283-800bfe80-1f70-11eb-8400-5de46ecbebd4.png)

and other times we're it says that it failed due to some namespaced resources not being created.
![Screen Shot 2020-11-05 at 12 08 08 PM](https://user-images.githubusercontent.com/42328472/98291480-cc573e80-1f70-11eb-9a5f-d30a728b6620.png)

Is there a way to update this config file to locate the correct role and role binding files? Our team uses cluster roles and cluster role bindings.

**Comment by jmccormick2001** [comment]
namespaced-manifest	string	manifest file with all resources that run within a namespace. By default, the scorecard will combine service_account.yaml, role.yaml, role_binding.yaml, and operator.yaml from the deploy directory into a temporary manifest to use as the namespaced manifest.....that is from the 0.17 documentation for scorecard...however, not sure if it will cover your situation but its something you might experiment with.
