### ISSUE TITLE
csv markers fail to generate for embedded types in sdk 1.1.0

### ISSUE THREAD

**Issue by mrhillsman** [operator-framework/operator-sdk#4196]
#### What did you do?

I created two projects using version 0.18.2 and 1.1.0 of the sdk. For both versions, I created an embedded type defined in a types.go file alongside memcached_types.go. When generating the CSV markers from the embedded type defined in the types.go file do not appear when using version 1.1.0 of the sdk but do appear when using version 0.18.2 of the sdk.

You can see the issue clearly here:

Using sdk v0.18.2 - https://github.com/mrhillsman/demo-operator/blob/master/deploy/olm-catalog/demo-operator/manifests/demo-operator.clusterserviceversion.yaml#L23-L43

Using sdk v1.1.0 - https://github.com/mrhillsman/demc-operator/blob/master/bundle/manifests/demc-operator.clusterserviceversion.yaml#L25-L37

#### What did you expect to see?

CSV markers regardless of the sdk version used.

#### What did you see instead? Under which circumstances?

Markers translated properly in 0.18.2 but not in 1.1.0

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

OpenShift

`$ operator-sdk version`

operator-sdk version: "v1.1.0", commit: "9d27e224efac78fcc9354ece4e43a50eb30ea968", kubernetes version: "v1.18.2", go version: "go1.15 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.15.3 darwin/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"074039a0a9c137967fba3e667b9849d60e5054d8", GitTreeState:"clean", BuildDate:"2020-10-08T07:26:24Z", GoVersion:"go1.15.0", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1+45f8ddb", GitCommit:"45f8ddb", GitTreeState:"clean", BuildDate:"2020-09-26T11:14:22Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mrhillsman** [comment]
@estroz

**Comment by estroz** [comment]
Current workaround: add a `spec=true` or `status=true` marker to skipped parent(s) field(s).
