### ISSUE TITLE
make test shows source: not found

### ISSUE THREAD

**Issue by sayboras** [operator-framework/operator-sdk#4203]
## Bug Report

`make test` shows below error for golang project

```shell script
/bin/sh: 1: source: not found
/bin/sh: 1: fetch_envtest_tools: not found
/bin/sh: 1: setup_envtest_env: not found
```

#### What did you do?

Follow steps in https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/, and run `make test`

#### What did you expect to see?

`make test` should not show any error

#### What did you see instead? Under which circumstances?

```shell script
make test
...
/bin/sh: 1: source: not found
/bin/sh: 1: fetch_envtest_tools: not found
/bin/sh: 1: setup_envtest_env: not found
...
```

#### Environment

**Operator type:**

/language go 

**Kubernetes cluster type:**

NA

`$ operator-sdk version`

operator-sdk version: "v1.1.0", commit: "9d27e224efac78fcc9354ece4e43a50eb30ea968", kubernetes version: "v1.18.2", go version: "go1.15 linux/amd64", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.15.3 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

#### Possible Solution

Makefile uses `/bin/sh` as default shell, override it by adding default line in Makefile

```
SHELL := /bin/bash
```

**Comment by jmrodri** [comment]
@sayboras out of curiosity what Linux version are you using? `uname -a`

**Comment by sayboras** [comment]
oh right, I am running with ubuntu

```
$ uname -a                         
Linux ubuntu20 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by jmrodri** [comment]
> oh right, I am running with ubuntu
> 
> ```
> $ uname -a                         
> Linux ubuntu20 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> ```

Thanks. So based on the default Ubuntu installation `/bin/sh` is a symlink to `dash` a different shell. Changing `source SCRIPT` to `. SCRIPT` would work but that can't be done in the SDK.  I'll look at your PR now.

**Comment by estroz** [comment]
Relates to https://github.com/kubernetes-sigs/controller-runtime/issues/1300

**Comment by estroz** [comment]
This will be fixed by https://github.com/kubernetes-sigs/kubebuilder/pull/2149
