### ISSUE TITLE
Requeuing Reconcile stops working after 15 requeues

### ISSUE THREAD

**Issue by pprokopi** [operator-framework/operator-sdk#4209]
#### What did you do?

Created the following Reconcile function in my controller 

```
func (r *ReconcileJBossWebServer) Reconcile(request reconcile.Request) (reconcile.Result, error) {
	reqLogger := log.WithValues("Request.Namespace", request.Namespace, "Request.Name", request.Name)
	reqLogger.Info("Reconciling")
	if condition{
		return reconcile.Result{}, nil
	}
	return reconcile.Result{Requeue: true}, nil 
```

#### What did you expect to see?

A endless loop of requeues (counted using the log messages that appear), or at least a bit enough number of them.

#### What did you see instead? Under which circumstances?

It always stopped requeuing around 15 requeues.
If I trigger a reconciliation by altering the cr yaml and updating the resource, it only runs once and fails to requeue.

If I trigger another reconciliation and set the condition as true (it depends on one of the values of my cr yaml file) it runs once and resets the requeues.

Then if I trigger it again (with the condition evaluating as false), it runs another 15 times and then stops requeuing again.

#### Environment

/language go

**Kubernetes cluster type: "minishift" **

```
$ operator-sdk version
 operator-sdk version: "v0.17.2-1-g53b00d12", commit: "53b00d125fb12515cd74fb169149913b401c8995", kubernetes version: "v1.17.2", go version: "go1.14.6 linux/amd64"
```

```
$ go version 
1.14.6
```

```
$ oc version
 Client Version: 4.6.1
Kubernetes Version: v1.11.0+d4cacc0
```

```
$ kubectl version
 Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:27:52Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-11-05T22:01:50Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by camilamacedo86** [comment]
Hi @pprokopi, 

Sorry for the late response in this one. The reconcile function is responsible for synchronizing the resources and their specifications according to the business logic implemented on them. In this way, it works like a loop, and it does not stop until all conditionals match its implementation. The following is pseudo-code with an example that clarifies it.

```gio
reconcile App {

   // Check if a Deployment for the app exists, if not create one
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   } 
   
   // Check if a Service for the app exists, if not create one 
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   }  

   // Looking for Database CR/CRD 
   // Check the Database Deployments Replicas size
   // If deployment.replicas size != cr.size, then update it
   // Then, go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{Requeue: true}, nil
   }  
   ...
   
   // If it is at the end of the loop, then:
   // All was done successfully and the reconcile can stop  
   return reconcile.Result{}, nil

}
```

The following are possible return options to restart the Reconcile:

- With the error: return reconcile.Result{}, err
- Without an error: return reconcile.Result{Requeue: true}, nil
- Therefore, to stop the Reconcile, use: return reconcile.Result{}, nil

For more details, check https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile

Then, the`reconcile.Result{Requeue: true}, nil ` will re-rigger the reconcile always. So, in your scenario, I can see only 2 options; the CR used in the reconcile was removed or after a while the conditional is true and the reconcile result is `return reconcile.Result{}, nil` which will stop it. 

So, wdyt about add logs before the returns for you be sure that it always returns the `reconcile.Result{Requeue: true},`?

Also, it is important to highlight that `v0.17.2` is no longer supported and then, recommend you migrate your project to 1.0+. See https://sdk.operatorframework.io/docs/building-operators/golang/migration/. 

Could you please let us know if you are able with the provided info sorted out it and we close this one? If not, then we will need steps required to reproduce your scenario. Are you able to reproduce it with the sample https://github.com/operator-framework/operator-sdk/tree/master/testdata/go/memcached-operator ? If yes, could you please share the required steps for we are able to check it as well.

**Comment by pprokopi** [comment]
Hello, I simplified the function and added logs and this is the result.
The requeue runs for approximately 15 times and then hangs.
If I trigger a reconciliation manually by modifying my CR, a single log appears, which means the reconciliation runs once and the requeuing hangs again.
I haven't had a chance to try it with 1.0+ or your sample yet.

`
func (r *ReconcileOperator) Reconcile(request reconcile.Request) (reconcile.Result, error) {
	log.Info("Requeuing")
	return reconcile.Result{Requeue: true}, nil
}`

`{"level":"info","ts":1606404822.4713156,"logger":"controller_operator","msg":"Requeuing"}
{"level":"info","ts":1606404822.4768126,"logger":"controller_operator","msg":"Requeuing"}
{"level":"info","ts":1606404822.4872603,"logger":"controller_operator","msg":"Requeuing"}
{"level":"info","ts":1606404822.5079126,"logger":"controller_operator","msg":"Requeuing"}
{"level":"info","ts":1606404822.5498152,"logger":"controller_operator","msg":"Requeuing"}
{"level":"info","ts":1606404822.630438,"logger":"controller_operator","msg":"Requeuing"}
{"level":"info","ts":1606404822.7925591,"logger":"controller_operator","msg":"Requeuing"}
{"level":"info","ts":1606404823.113166,"logger":"controller_operator","msg":"Requeuing"}
{"level":"info","ts":1606404823.7541807,"logger":"controller_operator","msg":"Requeuing"}
{"level":"info","ts":1606404825.034422,"logger":"controller_operator","msg":"Requeuing"}
{"level":"info","ts":1606404827.5946553,"logger":"controller_operator","msg":"Requeuing"}
{"level":"info","ts":1606404832.7165632,"logger":"controller_operator","msg":"Requeuing"}
{"level":"info","ts":1606404842.9568563,"logger":"controller_operator","msg":"Requeuing"}
{"level":"info","ts":1606404863.4372146,"logger":"controller_operator","msg":"Requeuing"}
{"level":"info","ts":1606404904.397503,"logger":"controller_operator","msg":"Requeuing"}`

**Comment by pprokopi** [comment]
Upon further testing, I discovered that if I add a delay by replacing the Requeue:true with RequeueAfter: 100*time.Millisecond, this doesn't happen and an infinite loop is created (as expected).
But it's not the delay that's fixing it. I tried introducing my own delay delay using time.Sleep (1000 * time.Millisecond) before requeuing and the bug still happened when I used Requeue:true

**Comment by camilamacedo86** [comment]
Hi @pprokopi,

We create a simple project with an api and just the queue true to check this scenario.  Note that each time that we re-triger the reconcile the item is added to the queue and in this case its time will take exponantionally longer to process each item:

```
2020-12-01T20:04:07.452Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:04:07.459Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:04:07.470Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:04:07.491Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:04:07.531Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:04:07.612Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:04:07.773Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:04:08.093Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:04:08.734Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:04:10.015Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:04:12.576Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:04:17.663Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:04:27.903Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:04:48.351Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:05:29.289Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:06:51.156Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
2020-12-01T20:09:34.883Z	INFO	controllers.Frigate	it ought to Requeue again	{"frigate": "default/frigate-sample"}
```

So, it has not a fixed limit in 15, as you can check it was executed more times than 15. However, if your controller is not configuring a [RateLimiter](https://github.com/kubernetes-sigs/controller-runtime/blob/8d0107636985eeedeb8c3c666abda5f602aa92be/pkg/controller/controller.go#L42-L45) then it will use the default one see: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controller.go#L107-L109. For further information check: https://github.com/kubernetes-sigs/controller-runtime/issues/631

**NOTE**: If your project was built with SDK version 0.17 then the controller-runtime version used is 0.5.2 which shows that have the same behaviour regards this subject. See: https://github.com/kubernetes-sigs/controller-runtime/blob/release-0.5/pkg/controller/controller.go#L83-L85

So, if would like to know how to customize the [rateLimiter](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/ratelimiter#RateLimiter) for your controllers maybe would be a better place get this info by raising an issue against the [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) project.

In this way, I hope that it is fine we close this one. However, feel free to ping us if you think that it should be re-opened.
