### ISSUE TITLE
Operator-sdk help for Helm/Ansible shows that GO text

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4210]
#### What did you do?

Run `operator-sdk -h` in a Helm/Ansible project (it is possible to use the testdata/ samples to check)

#### What did you expect to see?

A specific helper message according to the type

#### What did you see instead? Under which circumstances?

The GO help message. 

#### Environment

**Operator type:**

/language ansible
/language helm

- operator-sdk version: master (1cba71cfbc496879dce1ecc12ed421ba009d6f76)

#### Possible Solution

Update the CLI helper based on the type. See: `internal/cmd/operator-sdk/cli/cli.go`

**Comment by estroz** [comment]
Duplicate of #3798
