### ISSUE TITLE
Darwin binary for v1.2.0 incorrectly compiled for Linux

### ISSUE THREAD

**Issue by brandentimm** [operator-framework/operator-sdk#4216]
#### What did you do?

Downloaded the v1.2.0 binary from the releases page (https://github.com/operator-framework/operator-sdk/releases/download/v1.2.0/operator-sdk-v1.2.0-x86_64-apple-darwin) and attempt to execute it on Mac OS.

#### What did you expect to see?

The operator-sdk binary successfully execute.

#### What did you see instead? Under which circumstances?

zsh: exec format error: ./operator-sdk-v1.2.0-x86_64-apple-darwin

Comparing the `file` output between v1.1.0 and v1.2.0:
➜  bin file operator-sdk-v1.1.0-x86_64-apple-darwin
operator-sdk-v1.1.0-x86_64-apple-darwin: Mach-O 64-bit executable x86_64
➜  bin file operator-sdk-v1.2.0-x86_64-apple-darwin
operator-sdk-v1.2.0-x86_64-apple-darwin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=9w3pq684DNUDLvvLbhrR/bQ1LiUDolR5OVESzkZOV/rhQEKESEVZMZmNNCpLXM/BMgR4QtmYmvfzfmOD0ek, not stripped

#### Environment

**Operator type:**

N/A

**Kubernetes cluster type:**

N/A

`$ operator-sdk version`

N/A

`$ go version` (if language is Go)

N/A

`$ kubectl version`

N/A

#### Possible Solution

Recompile for darwin x86_64

**Comment by joelanford** [comment]
Thanks for the report. We'll get these rebuilt ASAP!

**Comment by joelanford** [comment]
New binaries are uploaded. Could you download again and retry?
