### ISSUE TITLE
CLI implementation shows options/commands which are not supported by the project type 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4217]
#### What did you do?

In the root dir of a Helm/Ansible project, executed the commands which are listed via `$ operator-sdk -h`.

#### What did you expect to see?

Able to use any command that is listed by the CLI helper

#### What did you see instead? Under which circumstances?

Errors, as follows, are faced when/if we try to execute a command that is not valid for tthe specific type and only exists for Go. Such as create webhook or edit, see:

```
 $ operator-sdk create webhook 
Error: layout plugin "helm.sdk.operatorframework.io/v1" does not support a webhook creation plugin
Usage:
  operator-sdk create webhook [flags]
```

```
 $ operator-sdk edit
Error: layout plugin "helm.sdk.operatorframework.io/v1" does not support a edit project plugin
Usage:
  operator-sdk edit [flags]
```

#### Environment

**Operator type:**

 /language ansible 
 /language helm 

#### Possible Solution

In the https://github.com/operator-framework/operator-sdk/blob/master/internal/cmd/operator-sdk/cli/cli.go#L57-L87 perform the following implementation to hidden commands based on the type. 

```go
// GetPluginsCLIAndRoot returns the plugins based CLI configured to use operator-sdk as the root command
// This CLI can run kubebuilder commands and certain SDK specific commands that are aligned for
// the kubebuilder project layout
func GetPluginsCLIAndRoot() (cli.CLI, *cobra.Command) {
	...
	// Hidden commands which are based operator type
	hiddenCommands(root)

	return c, root
}

// hiddenCommands will hidden commands based on the operator type
func hiddenCommands(root *cobra.Command) {
	if !isGoOperator() {
		for _, cmd := range root.Commands() {
			// The edit command is valid only for Go based- operators
			if cmd.Name() == "edit" {
				cmd.Hidden = true
			}
 			// The create webhook command is valid only for Go based- operators
			if cmd.Name() == "create webhook" {
				cmd.Hidden = true
			}                       
		}
	}
}

// isGoOperator returns true when the cli is called from a Go operator
func isGoOperator() bool {
	cfg, err := projutil.ReadConfig()
	if err == nil && cfg != nil {
		return projutil.PluginKeyToOperatorType(cfg.Layout) == projutil.OperatorTypeGo
	}
	return false
}

```

#### Additional context

Also, see: https://github.com/operator-framework/operator-sdk/issues/4210

**Comment by estroz** [comment]
@camilamacedo86 since kubebuilder's `pkg/cli` manages what commands are available for a plugin, can you re-create this issue upstream? There should be some functionality that only prints commands available to a plugin after running `init` or `init --plugins=<key>`.

**Comment by estroz** [comment]
Duplicate of #3798

**Comment by jberkhahn** [comment]
Closed as duplicate.
