### ISSUE TITLE
User "system:serviceaccount:test-namespace:default" cannot list resource

### ISSUE THREAD

**Issue by barryzhounb** [operator-framework/operator-sdk#4223]
Our team developed an xxxx Operator with Operator-sdk framework v1.0, basically it worked. Somehow we got issue,we could not find the root cause.

1. Development environments:
go 1.13

require (
        github.com/go-logr/logr v0.1.0
        github.com/onsi/ginkgo v1.14.2
        github.com/onsi/gomega v1.10.3
        k8s.io/api v0.18.6
        k8s.io/apimachinery v0.18.6
        k8s.io/client-go v0.18.6
        sigs.k8s.io/controller-runtime v0.6.2
)

2. Issue background

we deploy 3  xxxx Operators in the differnent namespace in the same cluster. Initially it worked, somehow we get the following issue, then controller seems not to reconcile any Custom resource.

The logs was grabbed from namespace "test-namespace"
```
E1111 14:27:43.129782       1 reflector.go:383] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to watch *v1.Deployment: unknown (get deployments.apps)
E1111 14:27:44.435006       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:test-namespace:default" cannot list resource "deployments" in API group "apps" in the namespace "test-namespace"
E1111 14:27:46.631244       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:test-namespace:default" cannot list resource "deployments" in API group "apps" in the namespace "test-namespace"
E1111 14:27:50.593543       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:test-namespace:default" cannot list resource "deployments" in API group "apps" in the namespace "test-namespace"
E1111 14:34:03.600671       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1alpha1.Mycustomresource: Mycustomresources.bird.com is forbidden: User "system:serviceaccount:test-namespace:default" cannot list resource "Mycustomresources" in API group "bird.com" in the namespace "test-namespace"
E1111 14:34:30.066145       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:test-namespace:default" cannot list resource "deployments" in API group "apps" in the namespace "test-namespace"
E1111 14:34:35.840234       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:test-namespace:default" cannot list resource "secrets" in API group "" in the namespace "test-namespace"
E1111 14:34:39.842596       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:test-namespace:default" cannot list resource "services" in API group "" in the namespace "test-namespace"
E1111 14:34:58.563342       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1alpha1.Mycustomresource: Mycustomresources.bird.com is forbidden: User "system:serviceaccount:test-namespace:default" cannot list resource "Mycustomresources" in API group "bird.com" in the namespace "test-namespace"
```

The question is:
(1) what is User "system:serviceaccount:test-namespace:default"? What is its meaning? It seems that I have not defined it.
(2) Why User "system:serviceaccount:test-namespace:default" cannot list resource ?
(3) How to fix it?

**Comment by estroz** [comment]
A few possibilities
- It looks like your RBAC doesn't have the "list" verb specified for certain types. What does your `config/rbac/role.yaml` look like?
- The namespace used (test-namespace) does not look like the one created by default. How are you deploying your operator? Are you using `make deploy`?

/triage support

**Comment by barryzhounb** [comment]
Hi @estroz ,
This is a piece of role.yaml, since it is too long, I could not show all here. I saw here for deployments, there are a few of verbs(create/delete/get/list)
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```

**Comment by estroz** [comment]
@barryzhounb when you run `make deploy`, `kustomize` applies the [namespace](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/config/default/kustomization.yaml#L2) in `config/default/kustomization.yaml` to all resources. If this name does not equal the one you're trying to deploy in, then your role binding will not bind the role to the correct service account. If you update that line to `test-namespace` then run `make deploy`, those errors should go away.

**Comment by BAIYIMING520** [comment]
I have been met same problem like this
make-deploy can't update all resource that my controller want to use in rbac

my pod log  has create these error log

 1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Deployment: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:opdemo-system:default" cannot list resource "deployments" in API group "apps" at the cluster scope
E0724 08:00:55.020734       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Deployment: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:opdemo-system:default" cannot list resource "deployments" in API group "apps" at the cluster scope
E0724 08:01:27.222765       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Deployment: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:opdemo-system:default" cannot list resource "deployments" in API group "apps" at the cluster scope
