### ISSUE TITLE
Unable to run operator-sdk x86_64-linux-gnu binary since version v0.19.0

### ISSUE THREAD

**Issue by secat** [operator-framework/operator-sdk#4229]
## Bug Report

Running the downloaded binary from GitHub doesn't work anymore starting from version `v0.19.0`

```
$ operator-sdk --help
FATA[0000] version format must match ^(v)?([1-9][0-9]*)(-alpha|-beta)?$
```

> **NOTE:** It works for version lower are equal to `v0.18.2`

#### What did you do?

I ran the following commands in a bash shell to install the operator-sdk:
```
$ export RELEASE_VERSION=v1.2.0
$ curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
$ chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
```

where `RELEASE_VERSION` where:
- `v0.19.0`
- `v0.19.3`
- `v0.19.4`
- `v1.2.0`

#### What did you expect to see?

The operator-sdk binary to work as expected (by example version `v0.18.2` works fine)

#### What did you see instead? Under which circumstances?

A returned error:
```
FATA[0000] version format must match ^(v)?([1-9][0-9]*)(-alpha|-beta)?$
```

#### Environment

**Operator type:**

language go

**Kubernetes cluster type:**

`$ operator-sdk version`

> Impossible to output since it doesn't work

`$ go version` (if language is Go)

```
go version go1.15.3 linux/amd64
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

#### Additional context

Running on windows WSL.

**Comment by joelanford** [comment]
Do you have a `PROJECT` file in your root directory? If so, it sounds like the `version` field is invalid or maybe not present.

Starting at v0.19, SDK added support for Kubebuilder-based projects, and this sounds like SDK is identifying your project as such based on the presence of the `PROJECT` file.

Here are the migration docs (if you haven't found them already): https://sdk.operatorframework.io/docs/building-operators/golang/migration/

**Comment by secat** [comment]
@joelanford effectively, the `PROJECT` file is missing from the root directory of my project.

Thank you.

However, I would have expected the tool to report this kind of thing with an explicit message saying that the `PROJECT` file is missing at the root of the director project.

**Comment by joelanford** [comment]
In v0.19, both old and new project layouts are supported, so SDK should be switching on the presence of that file.

In v1+, only Kubebuilder style projects are allowed. So if there isn't a `PROJECT` file, the SDK assumes there isn't a project in this directory.

If you don't have a `PROJECT` file _at all_ that's definitely a weird error message. Are you able to write up some steps to reproduce this, starting from no project files existing?

**Comment by secat** [comment]
I created a project following this doc: https://sdk.operatorframework.io/docs/building-operators/golang/migration/ and I was using the version `v0.18.2` instead of `v0.19.4`.

The problem happens when switching to `v0.19.4` in a projected created with `v0.18.2` following the migration doc.

However, if I go in my on operator which doesn't have a `PROJECT` file, it works using `v0.19.4`.

Thank you for your help! 

You can close this issue.
