### ISSUE TITLE
Error in vendor directory when running make dep make install

### ISSUE THREAD

**Issue by benjaminapetersen** [operator-framework/operator-sdk#423]
I experienced this error after a `make dep && make install`:

```
# github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/client
vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go:30: syntax error: unexpected = in type declaration
make: *** [install] Error 2
```
- The first time I experienced it was after a `git pull && make dep && make install`, following the readme.  I was attempting to update my local copy
- Second, just to verify it was not my local system, I cloned the repo down fresh followed by a `make dep && make install`

Let me know if I can provide any other assistance.  Thanks!

**Comment by hasbro17** [comment]
@benjaminapetersen I couldn't reproduce this on the master branch.

Looking at the error however it might be a Go version issue. [Type alias](https://golang.org/doc/go1.9#language) was introduced in Go 1.9
```Go
type ObjectKey = types.NamespacedName
```

What Go version are you using?

**Comment by benjaminapetersen** [comment]
Closing this out.  `gvm` related, changing `go versions` doesn't necessarily update `$GOPATH`.  My googling reveals `$GOPATH` woes are common to those new to `go`.  😮
