### ISSUE TITLE
The status conditionals helper form operator-lib was removed and the docs were not updated

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4235]
#### What did you do?

Check the doc:https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#manage-cr-status-conditions.

#### What did you expect to see?

It updated with the changes made in: https://github.com/operator-framework/operator-lib/pull/35

#### What did you see instead? Under which circumstances?

The doc with the outdated info.

**Comment by varshaprasad96** [comment]
@camilamacedo86 
We still haven't upgraded k8s to 1.19+ and the `metav1.Condition` was released in k8s 1.19. That was the reason we reverted the docs, and have added a [note](https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#manage-cr-status-conditions) instead in the same section:
```
NOTE: The status package was removed in operator-lib v0.2.0 in deference to the upstream metav1.Condition type, so your project must depend on version v0.1.0 to use status.Conditions:

go get github.com/operator-framework/operator-lib@v0.1.0
```

**Comment by camilamacedo86** [comment]
Really thank you for share that info here. It shows fine. So, we only an issue to track this need when the release gets done.

**Comment by estroz** [comment]
#3997 needs to be re-committed.

/assign @varshaprasad96

**Comment by estroz** [comment]
This depends on go/v3-alpha being stabilized, since this is the only plugin that will use k8s v1.19+.
