### ISSUE TITLE
How can we do functional tests in CI/CD pipeline by mocking kubernetes resources for GO operators

### ISSUE THREAD

**Issue by anusood** [operator-framework/operator-sdk#4239]
How can we do functional tests in CI/CD pipeline by mocking kubernetes resources for GO operators. Apart from envTest, as no services/pod from inside the tests are created in envtest.

#### What did you do?

Creating a GO operator for our project.

#### What did you expect to see?

functional end-to-end test for the operator and check the resources created

#### What did you see instead? Under which circumstances?
No able to check the resources created

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**
Openshift

`$ operator-sdk version`

v1.0.0

`$ go version` (if language is Go)

1.15

`$ kubectl version`

**Comment by estroz** [comment]
>Apart from envTest, as no services/pod from inside the tests are created in envtest.

What do you mean by this? You can create any k8s object for which a scheme is registered with envtest using the `*rest.Config` returned by [`envtest.Environment.Start()`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest#Environment.Start). I recommend creating functional tests this way.

Alternatively you can create custom tests using [scorecard custom tests](https://sdk.operatorframework.io/docs/advanced-topics/scorecard/custom-tests/), which requires your operator be running in a cluster beforehand. However custom tests should be used to test operator states and not necessarily end-to-end scenarios.

/triage support

**Comment by anusood** [comment]
can we manage a new image resource  pod created from inside the controller in the Reconcile method and communicate with it.? Also, if I delete the CR object, would the service and pods for that deployment be deleted automatically in the envTest environment as it does on openshift?
