### ISSUE TITLE
User Guide: explain what the build command does

### ISSUE THREAD

**Issue by benjaminapetersen** [operator-framework/operator-sdk#424]
Running this code:

```
# Build and push the app-operator image to a public registry such as quay.io
$ operator-sdk build quay.io/example/app-operator
```
Will output some docker related code && also print `Create deploy/operator.yaml`.

There are a few questions:

- `/deploy/operator.yaml` is generated.  Should this be manually edited at this point?  The assumption is that it should not.  If so, ideally print something at the top of the file, like `# GENERATED FILE DO NOT EDIT`
- Other files under `/deploy` already exist from the initial `operator-sdk new`  Should these be edited directly, or should we assume everything under `/deploy` is generated?
- does `operator-sdk build` do any other interesting things that should be noted?

Thanks!

**Comment by PhilipGough** [comment]
I'm also wondering if the generated yaml should not be edited manually, should the build process not support the passing of some flags to allow the output to be customised yet consistent.

The first use case that comes to mind is the the ability to pass it a service account name. To me, defaulting to using the default service account and then expecting to grant it a set of permissions does  not seem correct.

**Comment by joelanford** [comment]
I think we can call this one finished. 

We've got the `build` command documented in the [SDK CLI Reference](https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#use). To answer the question directly, we've scoped the `build` command down to just building a docker image. It no longer modifies files in the `./deploy` directory.
