### ISSUE TITLE
docs: make OLM integration quickstart quick(er)

### ISSUE THREAD

**Issue by estroz** [operator-framework/operator-sdk#4241]
#### Describe the problem you need a feature to resolve.

The OLM integration "quickstart" is not a quickstart in the same manner as Go/Ansible/Helm quickstarts.

#### Describe the solution you'd like.

The existing OLM integration quickstart needs to be moved to a long-form "tutorial" page, and an actual quickstart needs to be written then linked to/inserted into existing Go/Ansible/Helm quickstarts.

/kind documentation

**Comment by jberkhahn** [comment]
note: add blurb at top of new tutorial section about difference between bundle generation (which is an operator-developer task), and actually installing/upgrading operators (which is a cluster operator task, and might involve brain surgery), although the operator developer still needs to have their bundle be correct, even if they shouldn't have to actually know about the OLM APIs
