### ISSUE TITLE
can we ue spock/groovy for testing operator-sdk  operator functional tests?

### ISSUE THREAD

**Issue by anusood** [operator-framework/operator-sdk#4243]
## Type of question

General operator-related help

#### What did you do?

Project specific operator writing

#### What did you expect to see?

functional tests for operator using groovy/spock

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

"OpenShift" 

`$ operator-sdk version`

v1.0.0

`$ go version` (if language is Go)

go 1.15

**Comment by kensipe** [comment]
Hey @anusood , looking to understand what are interested in with this question.   First I think we need to establish the meaning of words... What specifically are you looking to do?  what does "functional tests" mean to you?
Most of my experience with spock is BDD unit and integration tests against groovy / java.  I have friends using Geb to provide testing against browsers (wrapper around selenium).   Is this the kind of tests you are looking to do?

Currently as a Go project the unit /integration tests are Go.   Generally speaking testing against the API server / operator is scorecard and KUTTL.   As I think more deeply about it... I do like the idea of a groovy / java wrapper around kube api-server to have spock instrument tests.   But first... is this the level of testing you are asking about?   If so, what you are asking isn't available to my knowledge.
