### ISSUE TITLE
Custom resource does not delete the resources created in another namespace - No ownerReferences set

### ISSUE THREAD

**Issue by jayeshnazre** [operator-framework/operator-sdk#4251]
#### What did you do?

**step 1:** I created a sample memcached-operator via the operator-sdk using ansible.
Used the below commands
mkdir memcached-operator
cd memcached-operator
operator-sdk init --plugins=ansible --domain=example.com
operator-sdk create api --group cache --version v1 --kind Memcached --generate-role 

Basically I followed the steps listed in [quickstart](https://sdk.operatorframework.io/docs/building-operators/ansible/quickstart/)

**step 2:** 
Just to simplify things, I gave cluster-admin ClusterRole to my operator in "ClusterRoleBinding" as shown below
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
 kind: ServiceAccount
  name: default
  namespace: system

**step3:** I used the below tasks in my Ansible role (under tasks/main.yml)
- name: create busybox namespace
  community.kubernetes.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'mywfns.yml') | from_yaml }}"
- name: create busybox deployment
  community.kubernetes.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'mywfdeploy.yml') | from_yaml }}"
- name: create service
  community.kubernetes.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'mywfservice.yml') | from_yaml }}"
- debug:
    msg: operatername {{ ansible_operator_meta.name }} operaternamespace {{ ansible_operator_meta.namespace }}

**step4:** I created the Custom Resource in a different name space than the resources created in "step3" above
My Custom Resource namespace is "mytest-ns" and all my Resources in the "step3" above are created in "sample3-ns" namespace

**step5:** I now delete the Custom Resource in namespace "mytest-ns", the resources in step3 are not cleaned up. I also do not see any "ownerReferences" section attached to any of my resources created in step3 - I am guessing that is why those are not getting deleted.

#### What did you expect to see?

I expect the resources created by my custom resource in a different namespace to be deleted as soon as I delete my custom resource which is in a different namespace. 

#### What did you see instead? Under which circumstances?

The resources created by my custom resource  are not deleted. This works if these resources are created in the same namespace as the custom resource,

#### Environment
Ubuntu 
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**Operator type:**

/language ansible

**Kubernetes cluster type:**

minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty

`$ operator-sdk version`

operator-sdk version: "v1.2.0", commit: "215fc50b2d4acc7d92b36828f42d7d1ae212015c", kubernetes version: "v1.18.8", go version: "go1.15.3", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

#### Additional context

[memcached-operator.zip](https://github.com/operator-framework/operator-sdk/files/5585673/memcached-operator.zip)

**Comment by fabianvf** [comment]
@jayeshnazre ownerReferences aren't actually supported across namespaces, if you want to clean up cluster-level, other-namespaced or otherwise external resources you need to do it manually using a finalizer.
