### ISSUE TITLE
Can we run the controller of the operator in one namespace and the image we want to run/manage from inside the operator in another namespace?

### ISSUE THREAD

**Issue by anusood** [operator-framework/operator-sdk#4260]
## Type of question

General operator-related help

#### What did you do?

We have an operator where we want to create a pod of an image we pass in CR.yml in another namespace

#### Environment

**Operator type:**

 /language go

**Kubernetes cluster type:**

Openshift

`$ operator-sdk version`

v1.0.0

`$ go version` (if language is Go)

go 1.15

`$ kubectl version`

**Comment by camilamacedo86** [comment]
So, I understand that you are looking for: 

- Apply a CR in the namespace A
- Then, the operator will be observing it and will reconcile this CR
- In the reconciliation, you would like to create the Pod (k8s resource) in namespace B 

In this way, you need code your reconcile to do that. See here in the Memcached sample that the namespace where the Deployment resource will be created is defined when it is initialized in the code:

https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/memcached-operator/controllers/memcached_controller.go#L135-L139

I am closing this one as sorted out. However, please feel free to ping us to re-open or raise new issues if you need to.
