### ISSUE TITLE
[Sugestion] Generate README.md file explaining make targets and overall strategies for using operator

### ISSUE THREAD

**Issue by wtrocki** [operator-framework/operator-sdk#4268]
Hi

It is quite common for generators to explain project structure and available commands in README.md
I'm quite happy to contribute that change to the repository if that is something that will be valuable. 

## What readme can have

- [x] Links to getting started
- [x] Explanation of the make commands (this can be done also using make help)`
- [x] Folder structure
- [x] Links to general information about tools used in the framework. Think https://github.com/kubernetes-sigs/kustomize 
- [x] General required reading https://kubernetes.io/docs/setup/

**Comment by wtrocki** [comment]
CC @camilamacedo86

**Comment by camilamacedo86** [comment]
Hi @wtrocki, 

IMO it is an RFE that should be done against upstream/kubebuilder then when it gets done there we can get the changes in the SDK. Could you please raise your suggestion against https://github.com/kubernetes-sigs/kubebuilder?

**Comment by wtrocki** [comment]
@camilamacedo86 Thank you so much. Created https://github.com/kubernetes-sigs/kubebuilder/issues/1866
Hoping for the best. That will be cool way to start contributing

**Comment by camilamacedo86** [comment]
I am closing this one in the SDK repo. Let's follow up and centralize this discussion in Kubebuilder which shows the best place.
Realy thank you for your collab with it.
