### ISSUE TITLE
Add custom fields to default status for Ansible Operators

### ISSUE THREAD

**Issue by jenoOvchi** [operator-framework/operator-sdk#4269]
#### Describe the problem you need a feature to resolve.

It will be great to combine standard status of Ansible Operator with custom fields to see status of Ansible Tasks and manage additional information about execution results.

#### Describe the solution you'd like.

Add settings to watch.yaml to set combined status management and create standard Ansible Tasks to set and check additional fields in Custom Resources.

/language ansible

**Comment by asmacdo** [comment]
If you want to set custom fields on the status, you can use the k8s_status module. https://github.com/operator-framework/operator-sdk-ansible-util/blob/master/plugins/modules/k8s_status.py#L17

This is part of the sdk util collection. https://galaxy.ansible.com/operator_sdk/util

**Comment by asmacdo** [comment]
If that doesn't give you what you need please reopen!
