### ISSUE TITLE
deps: k8s v1.20

### ISSUE THREAD

**Issue by estroz** [operator-framework/operator-sdk#4274]
#### Describe the problem you need a feature to resolve.

Kubernetes v1.20 will be released soon (second week of December 2020).

#### Describe the solution you'd like.

Projects should support v1.20 as soon as possible.

TODO's:
- [x] bump controller-runtime to k8s v1.20, release v0.8.0
	- [x] https://github.com/kubernetes-sigs/controller-runtime/pull/1268
- [ ] bump go.kubebuilder.io/v3 to controller-runtime v0.8.0
- [ ] update operator-sdk dependencies to k8s v1.20 and kubebuilder (either commit or next release with this bump)

/area dependency
/language go
/language ansible
/language helm

**Comment by varshaprasad96** [comment]
The next release after kubebuilder 3.0.0 (stable) will be having k8s bumped to 1.20. Blocked on https://github.com/kubernetes-sigs/kubebuilder/issues/1997

**Comment by estroz** [comment]
Closed by #4863
