### ISSUE TITLE
docs: add `run bundle` documentation

### ISSUE THREAD

**Issue by estroz** [operator-framework/operator-sdk#4275]
#### Describe the problem you need a feature to resolve.

I would like an explanation of how to use `operator-sdk run bundle`, in both short and longer form.

#### Describe the solution you'd like.

Additions to the OLM integration docs [quickstart](https://sdk.operatorframework.io/docs/olm-integration/quickstart-bundle/#testing-bundles), [CLI overview](https://sdk.operatorframework.io/docs/olm-integration/cli-overview/#bundles), and [testing](https://sdk.operatorframework.io/docs/olm-integration/testing-deployment/) docs.

/kind documentation

**Comment by wtrocki** [comment]
@estroz +100. I have been struggling to get my head around this. The fact that OLM is separately documented requires installation of the serv

See also: https://github.com/operator-framework/operator-sdk/issues/4277

Quickstart is confusing. Requires developers to go to some other repository readme as last step (which you can forget/ommit) but later phases will not work. Any reason why Operator and OLM are different docs/cli. From newbie point of viw I should have one docs for development and deploying operators to production etc.
