### ISSUE TITLE
e2e-integration has been facing an issue with the latest released version of OLM 0.17.0 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4284]
#### What did you do?

- Add 0.17.0 OLM bindatata to SDK https://github.com/operator-framework/operator-sdk/pull/4242
- Update the integration tests (which were no using the previous one to use 0.16.0) to use the 0.17.0 - **Important: This error might be faced since the 0.16.0 version of OLM and not ONLY now.**   

#### What did you expect to see?

All tests work successfully. 

#### What did you see instead? Under which circumstances?

After the PR get merged the following the e2e integration tests starts o fail:

```
    operator_olm_test.go:122: 
        	Error Trace:	operator_olm_test.go:122
        	Error:      	Received unexpected error:
        	            	error waiting for CSV to install: csv failed: reason: "UnsupportedOperatorGroup", message: "OwnNamespace InstallModeType not supported, cannot configure to watch own namespace"
        	Test:       	TestOLMIntegration/PackageManifestsOwnNamespace
    operator_olm_test.go:117: get installed CSV "": resource name may not be empty
=== RUN   TestOLMIntegration/PackageManifestsMultiplePackages
    operator_olm_test.go:265: 
        	Error Trace:	operator_olm_test.go:265
        	Error:      	Received unexpected error:
        	            	create catalog: error creating catalog source: catalogsources.operators.coreos.com "memcached-operator-catalog" already exists
        	Test:       	TestOLMIntegration/PackageManifestsMultiplePackages
    operator_olm_test.go:267: 
        	Error Trace:	operator_olm_test.go:267
        	Error:      	Received unexpected error:
        	            	get installed CSV "": resource name may not be empty
        	Test:       	TestOLMIntegration/PackageManifestsMultiplePackages
--- FAIL: TestOLMIntegration (32.00s)

```
more: https://github.com/operator-framework/operator-sdk/pull/4056/checks?check_run_id=1502143766#step:4:713

#### Additional context

- It shows a bug with OLM since the tests that work with 0.15.1 should work with 0.16.0 and 0.17.0
- OLM maybe has a bug to the `InstallModeTypeOwnNamespace` or we have an issue in the [CSV mocked]()https://github.com/operator-framework/operator-sdk/blob/master/test/integration/integration_helpers.go#L64-L196 which has been checked in the latest versions.  
- Workaround in place until we are able to fix it is #4283

**Comment by camilamacedo86** [comment]
c/c @estroz @varshaprasad96

**Comment by varshaprasad96** [comment]
@camilamacedo86 This seems to be an error during the uninstall [(here)](https://github.com/operator-framework/operator-sdk/blob/master/internal/olm/operator/uninstall.go#L65). Was this including Webhooks scaffolded in csv ?
I tried this out by scaffolding a sample memcached operator (without Webhooks) and running package manifests command in olm 0.17.0. Im not able to reproduce this error. It seems to uninstall correctly:
```
➜  memcached-operator /build/operator-sdk cleanup memcached-operator -n memcached-operator-system
INFO[0000] subscription "memcached-operator-v0-0-1-sub" deleted
INFO[0000] customresourcedefinition "memcacheds.cache.example.com" deleted
INFO[0000] clusterserviceversion "memcached-operator.v0.0.1" deleted
INFO[0000]  "memcached-operator-catalog" deleted
INFO[0001] operatorgroup "operator-sdk-og" deleted
INFO[0001] Operator "memcached-operator" uninstalled
```
for olm version: 
```
➜  memcached-operator operator-sdk olm status
INFO[0000] Fetching CRDs for version "0.17.0"
INFO[0000] Fetching resources for resolved version "v0.17.0"
```

**Comment by camilamacedo86** [comment]
Hi @varshaprasad96, 

The error faced is in the [integration tests](https://github.com/operator-framework/operator-sdk/blob/master/test/integration/). These tests use a simple init project with an API and a CSV mocked. So, I do not see any relation with webhooks at all. See the error `reason: "UnsupportedOperatorGroup", message: "OwnNamespace InstallModeType not supported, cannot configure to watch own namespace"`

Shows that was not possible to install the operator with `OwnNamespace` model type.

**Comment by varshaprasad96** [comment]
This is the installMode section in the csv which I used:
```
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
```
Ill scaffold an operator as done in integration tests and check this out.

**Comment by estroz** [comment]
I'm fairly certain these tests are running up against a caching issue, where a previously installed set of manifests is being used.
