### ISSUE TITLE
Need Suggestion: Create Statefulsets as replicas of a Custom Resource.

### ISSUE THREAD

**Issue by naeemkhan12** [operator-framework/operator-sdk#429]
I have a usecase where I have a custom statefulset manifest, which I need to replicate as specified by the number by user, the same way deployment are scale up and down with replicas in kubernetes. And for that I am thinking about creating an kubernetes-operator, I need your suggestions, would it be right approach or anything simpler can be done to achieve this goal, and I need to manage those statefulsets as a single deployment or unit as per say.
For example this is what i want to achieve

```
apiVersion: "sts.example.com/v1alpha1"
metadata:
...
units: 3
replicas: 2


```
Here units represent the number of statefulsets and replicas represents the number of replicas in each statefulset and it means there would be 3 different statefulsets each having 2 replicas.

**Comment by joelanford** [comment]
@naeemkhan12 Sorry we never got back to you on this! You may have already decided on your approach, but if not, it does sound like a reasonable use case for an operator.

If you have follow-up questions, please feel free to re-open this issue!
