### ISSUE TITLE
Best practices for using private git-repositories?

### ISSUE THREAD

**Issue by jkmw** [operator-framework/operator-sdk#4291]
## Type of question

- Best practices
- Open question

#### What did you do?

We have written a kubernetes operator which imports a library from a private git repository.
If we try to create the operator image with `docker build` or `make docker-build`, it fails because the Dockerfile has no credentials to access the private repository:

```sh
> make docker-build
[...]
Step 5/14 : RUN go mod download
 ---> Running in 35ce193ea8be
go: private-git.example.com/some/project/v2@v2.0.41: reading private-git.example.com/some/project/go.mod at revision project/v2.0.41: unknown revision project/v2.0.41
The command '/bin/sh -c go mod download' returned a non-zero code: 1
make: *** [Makefile:74: docker-build] Error 1
```

#### What did you expect to see?

We wonder if there is a best practice or recommendation how to pass the private repository credentials (for example a `.netrc` file) to the docker image?

#### What did you see instead? Under which circumstances?

Since we have several operators and the deployment is completely automated at a central location, it feels inelegant to adjust the Dockerfile for each operator by hand.
Most of all because we think it is maybe possible that the Dockerfile could be completely autogenerated by the operator-sdk in future versions?

#### How to reproduce

- Create an empty operator:
```sh
operator-sdk init --domain=example.com --repo=github.com/example/com
```

- Insert a path from an private repository into the `go.mod`
```go
module github.com/example/com

go 1.13

require (
	k8s.io/apimachinery v0.18.6
	k8s.io/client-go v0.18.6
	sigs.k8s.io/controller-runtime v0.6.3
	private-git.example.com/some/project/v2 v2.0.41
)
```

- Run `make docker-build`

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:** OpenStack

**operator-sdk version:**
```
"v1.2.0", commit: "215fc50b2d4acc7d92b36828f42d7d1ae212015c", kubernetes version: "v1.18.8", go version: "go1.15.3", GOOS: "linux", GOARCH: "amd64"
```

**go version:** `go version go1.15.6 linux/amd64`

**kubernetes version:**
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aemperador** [comment]
this may be a naive question/answer, but does ssh not work in this case? could you pass the ssh key somehow?

**Comment by kensipe** [comment]
@jkmw The question seems to be centered around Go /  Go Modules with the use of private repositories.
The following is a medium article I found that likely can shed some light:  https://medium.com/cloud-native-the-gathering/go-modules-with-private-git-repositories-dfe795068db4

Additionally, here is a stackoverflow response:  https://stackoverflow.com/questions/53516358/go-modules-private-repos-and-gopath

Closing for now... feel free to reopen if needed.
