### ISSUE TITLE
HELP !

### ISSUE THREAD

**Issue by whaike** [operator-framework/operator-sdk#4295]
```
$ go get github.com/operator-framework/operator-sdk/pkg/metrics
go get github.com/operator-framework/operator-sdk/pkg/metrics: module github.com/operator-framework/operator-sdk@upgrade found
(v1.2.0), but does not contain package github.com/operator-framework/operator-sdk/pkg/metrics

```
Is there something wrong with your go mod ? I guess.

**Comment by camilamacedo86** [comment]
The github.com/operator-framework/operator-sdk no longer provide any pkg. It is only the tool so you ought to not go get it. The lib features provided that be used in the projects are in the project: https://github.com/operator-framework/operator-lib. 

Also,  shows nice to share that if your project is lower than 1.0 we would like to recommend your project for the new layout. See https://sdk.operatorframework.io/docs/building-operators/golang/migration/.

Closing it as sort out. However, please feel free to ping us or raise new issues if you need to.
