### ISSUE TITLE
bump operator-framework/api dependency to v0.3.22

### ISSUE THREAD

**Issue by exdx** [operator-framework/operator-sdk#4304]
#### What did you do?

Run custom category validation

#### What did you expect to see?

Success

#### What did you see instead? Under which circumstances?

Failure to parse the custom categories from the CSV file successfully 

#### Possible Solution

This issue was addressed by https://github.com/operator-framework/api/pull/78
and published in https://github.com/operator-framework/api/releases/tag/v0.3.22
Bumping the api dep to this version and publishing a new z stream sdk release should resolve the issue for users 

#### Additional context

Community-operators pipelines will have a new feature supporting custom categories. So this feature being fixed will help contributors

**Comment by varshaprasad96** [comment]
We would be releasing SDK 1.3.0 soon with the latest release of operator-framework/api ([0.4.0](https://github.com/operator-framework/api/releases/tag/v0.4.0) at this time). However, we can also have a v1.2 patch with updated api version to solve the issue of allowing multiple categories.

**Comment by estroz** [comment]
Bumping to v0.3.22 causes dependency conflicts since it includes a k8s v1.19 bump, so bumping operator-sdk v1.2 to v0.3.22 won't happen (another good reason to cut minor releases for k8s bumps). As @varshaprasad96 mentioned, operator-sdk v1.3 will include a bump to v0.4.0 to fix the described issue.

**Comment by J0zi** [comment]
So we are waiting for #4305 and release afterwards.

**Comment by estroz** [comment]
@J0zi #4294 superseded #4305 and has already merged.
