### ISSUE TITLE
The file `config/rbac/role.yaml` has not been updated with the APIs which are created

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4310]
#### What did you do?

- Create an Ansible project
- Then scaffold a rule and a playbook 

#### What did you expect to see?

The tool uses properly the marker `+kubebuilder:scaffold:rules` as it is done for Helm to update the watch file with the required rbac roles for the APIs scaffolded in the project

#### What did you see instead? Under which circumstances?

The tool only adds RBAC role for the first API scaffolded. 

#### Environment

**Operator type:**

**Comment by estroz** [comment]
Referring to [this `role.yaml` generated file](https://github.com/operator-framework/operator-sdk/blob/master/testdata/ansible/memcached-operator/config/rbac/role.yaml#L57).

**Comment by camilamacedo86** [comment]
I faced this issue when I was manually upgrading nd changing the advanced e2e molecule tests. after check it better I could ensure that it is working. The problem was related to changes done manually. ( it was probably missing or adding a wrong marker.)  

we can ensure that works well expected by checking the testsdata generated for the advanced e2e molecule in the PR https://github.com/operator-framework/operator-sdk/pull/4312.
