### ISSUE TITLE
Using secrets in CR spec

### ISSUE THREAD

**Issue by michael-niemand** [operator-framework/operator-sdk#4319]
## Type of question

General operator-related help

#### What did you do?

I want to use a secret in my CR spec. 

I built a simple operator that creates a database on a managed DB server. For each CR "MySqlDb" a user, password and database name are passed in the spec and a database and a user are created accordingly. Works all well, but right now I pass the DB password in clear text, which I obviously don't want to do. 
Ideally I could use k8s native secrets in my CR spec, but I'd like to hear different approaches as well if that's not possible!

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

Azure AKS

`$ operator-sdk version`

1.0

**Comment by jberkhahn** [comment]
Hey there, this isn't really an operator-specific question, but here are a few things that might help.

First off, please don't ever store anything sensitive as plaintext. Secrets are the correct way to handle this sort of thing. 

As far as I'm aware, there isn't functionality in CRD's to include secretRefs, so you'll have to do so manually. This would entail having some field in your spec that is the name of the secret storing the username/password or whatever. Have the reconcile loop pull that secret through the Kube API (you'll have to give it permissions to do that), decode it, and use it to create the MySQL cluster. You could also make your controller check to see if the a secret was provided/exists, and go and generate a secret containing a new username/password.

I'm not entirely certain what you mean by non k8s native secrets. You have some external system that is storing them? You'd either have to make your controller interface with that system to extract it, or see if there's someway to get it into k8s as a volume or something.
