### ISSUE TITLE
How to use NewSimpleClientset in the unit tests.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [operator-framework/operator-sdk#4322]
#### What did you do?
I tried to write `Unit test` with fake.NewSimpleClientset:

```golang
package controller

import (
	"testing"

	cachev1alpha1 "github.com/example-inc/memcached-operator/pkg/apis/cache/v1alpha1"
	apiv1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	testclient "k8s.io/client-go/kubernetes/fake"
	"k8s.io/client-go/kubernetes/scheme"
)

func TestGetNodeIP(t *testing.T) {
	scheme := scheme.Scheme
	scheme.AddKnownTypes(cachev1alpha1.SchemeGroupVersion, &cachev1alpha1.Memcached{}, &cachev1alpha1.MemcachedList{})
	testclient.AddToScheme(scheme)
	testclient.NewSimpleClientset(&apiv1.NodeList{Items: []apiv1.Node{{
		ObjectMeta: metav1.ObjectMeta{
			Name: "demo",
		},
		Status: apiv1.NodeStatus{
			Addresses: []apiv1.NodeAddress{
				{
					Type:    apiv1.NodeInternalIP,
					Address: "10.0.0.1",
				},
			},
		},
	}}},
	 &cachev1alpha1.MemcachedList{Items: []cachev1alpha1.Memcached{
		{
			TypeMeta: metav1.TypeMeta {
				APIVersion: "cache.example.com/v1alpha1",
				Kind: "Memcached",
			},
			ObjectMeta: metav1.ObjectMeta{
				Name:      "memcached",
				Namespace: "memcached-operator",
			},
		},
	}},
    )
}

```

#### What did you expect to see?

Test passed: ok

#### What did you see instead? Under which circumstances?

Strange an error:

--- FAIL: TestGetNodeIP (0.00s)
panic: no kind is registered for the type v1alpha1.Memcached in scheme "pkg/runtime/scheme.go:101" [recovered]
	panic: no kind is registered for the type v1alpha1.Memcached in scheme "pkg/runtime/scheme.go:101"

#### Environment

**Operator type:**
language go 

**Kubernetes cluster type:**

`$ operator-sdk version`

operator-sdk version: "v0.17.2", commit: "0258db0119e8e18e15d035532427c329fce1e871", kubernetes version: "unknown", go version: "go1.13.10 linux/amd64"

`$ go version` (if language is Go)

go version go1.14.1 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+2cf11e2", GitCommit:"2cf11e2", GitTreeState:"clean", BuildDate:"2020-08-13T03:13:18Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

P.S. strange, but if I live only node object, then test is ok. But it fails with Memcached object.

**Comment by estroz** [comment]
Try
```go
package controller

import (
	"testing"

	cachev1alpha1 "github.com/example-inc/memcached-operator/pkg/apis/cache/v1alpha1"
	testclient "k8s.io/client-go/kubernetes/fake"
	"k8s.io/client-go/kubernetes/scheme"
)

var scheme = scheme.Scheme

func init() {
	utilruntime.Must(cachev1alpha1.AddToScheme(scheme)) // Use Memcached's SchemeBuilder
	utilruntime.Must(testclient.AddToScheme(scheme))
}

func TestGetNodeIP(t *testing.T) {
	testclient.NewSimpleClientset(...)
}
```

**Comment by AndrienkoAleksandr** [comment]
Looks like, I incorrectly tried to set up scheme to the NewSimpleClientset. I debugged code and I clear see, that fake NewSimpleClientset doesn't support it. But fake lib provides another way how to include desired api. For example:

```go
clientSet := fakeclientset.NewSimpleClientset()
fakeDiscovery, ok := clientSet.Discovery().(*fakeDiscovery.FakeDiscovery)
fakeDiscovery.Fake.Resources = []*metav1.APIResourceList{
        {
	        GroupVersion: "packages.operators.coreos.com/v1",
	        APIResources: []metav1.APIResource{
		        {
			        Kind: "PackageManifest",
		        },
	        },
        },
}
```
