### ISSUE TITLE
rationale for using logrus?

### ISSUE THREAD

**Issue by bparees** [operator-framework/operator-sdk#433]
All k8s and openshift use glog for the logging infrastructure, what was the reason for choosing logrus here?

Converting the glog would be nice since it would keep our code bases more closely aligned (for all the operators we are implementing) and also ensure that enabling verbose logging can have the same experience regardless of whether the component is an operator or an infrastructure component.

**Comment by fanminshi** [comment]
@bparees I think it was used in etcd-operator. Then we decided use it here because it works. I am fine with using glog to keep logging mechanism consistent with rest of the k8s and openshift.

cc/ @hasbro17

**Comment by shawn-hurley** [comment]
Because we are moving to controller runtime I suggest that we use their logger and not `glog`, @bparees The reason that controller runtime did not use `glog` can be found here: 
https://github.com/kubernetes-sigs/controller-runtime/pull/114#discussion_r212665868

**Comment by LiliC** [comment]
Closing as https://github.com/operator-framework/operator-sdk/pull/707 was merged. See https://github.com/operator-framework/operator-sdk/issues/503 for the full discussion about logging.
