### ISSUE TITLE
Unable to inject the time to my status

### ISSUE THREAD

**Issue by gowrisankar22** [operator-framework/operator-sdk#4339]
## Bug Report

when I tried adding time utc to my field actually I am getting an error like below.

```
api/v1alpha1/zz_generated.deepcopy.go:109:20: in.LastUpdatedTime.DeepCopyInto undefined (type time.Time has no field or method DeepCopyInto)
```

**Kubernetes cluster type:**

`$ operator-sdk version`

operator-sdk version: "v1.2.0", commit: "215fc50b2d4acc7d92b36828f42d7d1ae212015c", kubernetes version: "v1.18.8", go version: "go1.15.5", GOOS: "darwin", GOARCH: "amd64"

`$ go version` (if language is Go)

1.15

`$ kubectl version`

Client Version: v1.19.2
Server Version: v1.16.15

**Comment by estroz** [comment]
@gowrisankar22 try using [`metav1.Time`](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#Time).

/language go
/triage support
