### ISSUE TITLE
New Version Tag

### ISSUE THREAD

**Issue by mphamapti** [operator-framework/operator-sdk#434]
So it happened today. sdk.Watch method's signature re-sync period is change to time.Duration. Even though it's a minor thing but it did take me quite sometimes to figure out why my build pipeline fails. Considering it is a signature change and also there has not been any new version since April, may I request a new version tag?

Thank you,

Minh

**Comment by hasbro17** [comment]
Apologies for the breaking changes. We're going to try and cut a release at the end of the week so users don't have to keep versioning the master branch and have a more up to date tag. 
We'll need one especially before the master becomes more unstable with the changes for the controller-runtime refactoring.

**Comment by AlexNPavel** [comment]
v0.0.6 released
