### ISSUE TITLE
How to make r.Delete return until the resource is deleted

### ISSUE THREAD

**Issue by mrpre** [operator-framework/operator-sdk#4345]
## Type of question

Best practices
How to implement a specific feature

#### What did you do?

delete a resource

#### What did you expect to see?

`r.client.Delete` returns until the resource is totally deleted.  
I want find an api like `kubectl delete` which will wait the resource deleted. 

#### What did you see instead? Under which circumstances?

call r.client.Delete  and it returns and the deletion is running background.

#### Environment

**Operator type:**

go

**Kubernetes cluster type:**

`$ operator-sdk version`

operator-sdk version: "v0.18.2", commit: "f059b5e17447b0bbcef50846859519340c17ffad", kubernetes version: "v1.18.2", go version: "go1.13.10 darwin/amd64"

`$ go version` (if language is Go)
go version go1.15 darwin/amd64

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyun.1", GitCommit:"4f7ea78", GitTreeState:"", BuildDate:"2020-05-08T07:29:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by joelanford** [comment]
@mrpre The best practice here is that you shouldn't block your reconcile loop waiting for certain things to happen or states to exist. If you do, you can starve your worker thread pool and cause your operator not to scale well.

Rather, you should structure your reconciler to issue the non-blocking delete call and then return without error if the deleted object still exists. When the object is actually deleted, your reconciler should be triggered again, and that same part of your reconciler logic can continue on with the deletion logic.

If you _really_ want to block your reconciler, you can issue the delete call, and then enter a [wait](https://godoc.org/k8s.io/apimachinery/pkg/util/wait) loop that does a Get on the resource and doesn't exit until you get [`apierrors.IsNotFound(err)`
](https://godoc.org/k8s.io/apimachinery/pkg/api/errors#IsNotFound)
