### ISSUE TITLE
When we click on the `Create documentation issue` the documentation label is not set

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4349]
#### What did you do?

Click on in : 

<img width="412" alt="Screen Shot 2020-12-23 at 13 11 22" src="https://user-images.githubusercontent.com/7708031/102999112-5f980380-4520-11eb-9b3a-90063d202aa3.png">

#### What did you expect to see?

- The new open with the label `kind documentation`

#### What did you see instead? Under which circumstances?

No label added

**Comment by lenardchristopher** [comment]
The link doesn't have the `labels` query param. However, I don't think it will matter because GitHub permissions are blocking labels. [This doc](https://docs.github.com/en/rest/reference/issues#create-an-issue) says 
> NOTE: Only users with push access can set labels for new issues. Labels are silently dropped otherwise.

Also, I can't add a label an issue, even if I created it.
