### ISSUE TITLE
Doc in the Operator-SDK the difference between kubebuilder and operator-sdk

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4350]
#### Describe the problem you need a feature to resolve.

This question is common see: https://github.com/operator-framework/operator-sdk/issues/1758

#### Describe the solution you'd like.

I think that would be great have a section to describe it in the https://sdk.operatorframework.io/ or at least which would link the post https://www.openshift.com/blog/operator-sdk-reaches-v1.0

**Comment by jberkhahn** [comment]
TODO: add a section to the top of the FAQ docs that answers the question "whats the difference between Operator-SDK and Kubebuilder?" Include a link to https://www.openshift.com/blog/operator-sdk-reaches-v1.0 which discusses the current (post 1.0) differences and https://github.com/operator-framework/operator-sdk/issues/1758 which discusses legacy (pre 1.0) differences.
