### ISSUE TITLE
Installation: gpg recv-keys fails

### ISSUE THREAD

**Issue by jdewinne** [operator-framework/operator-sdk#4351]
#### What did you do?

Following the [github installation](https://sdk.operatorframework.io/docs/installation/#install-from-github-release) guide. When executing `gpg --recv-keys 052996E2A20B5C7E` I get `gpg: keyserver receive failed: No data`

#### What did you expect to see?

Something like "Key imported"

#### What did you see instead? Under which circumstances?

I get: `gpg: keyserver receive failed: No data`. Verbose output:
```
gpg: data source: https://hkps.pool.sks-keyservers.net:443
gpg: keyserver receive failed: No data
```

#### Environment

**Operator type:**

Archlinux installation: 5.9.14
GPG version: gpg (GnuPG) 2.2.25
language go

**Kubernetes cluster type:**

Not relevant

`$ operator-sdk version`
Trying to install v1.3.0

`$ go version` (if language is Go)
go version go1.15.6 linux/amd64

`$ kubectl version`
v1.19.4

#### Possible Solution
Maybe specify the keyserver to be used (if the key is correct). Or provide the correct key?

#### Additional context

You can also go to https://keyserver.ubuntu.com/ and try searching for the key.

**Comment by rshetye** [comment]
1. `$ gpg --recv-keys 052996E2A20B5C7E`
does not work
`gpg: keyserver receive failed: No data`
Tried with different key servers. Searched for the key on different keyservers ( http://keys.gnupg.net/ , https://pgp.mit.edu/ , https://keyserver.ubuntu.com/ ) . Key is not found on various online PGP databases.

2. `$ gpg -u "Operator SDK (release) <cncf-operator-sdk@cncf.io>" --verify checksums.txt.asc`
says
`gpg: assuming signed data in 'checksums.txt'`
`gpg: Signature made Thu 17 Dec 2020 09:33:09 PM CST`
`gpg:                using RSA key 2A859D08BF9886DB`
`gpg: Can't check signature: No public key`
But

3. `$ gpg --recv-keys 2A859D08BF9886DB`
also does not work.
`gpg: keyserver receive failed: No data`
Tried with different key servers. Searched for the key on different keyservers. Key is not found on various online PGP databases.

**Comment by kansberry** [comment]
Same issue and error. Unable to import key using "gpg --recv-keys 052996E2A20B5C7E" command.

**Comment by estroz** [comment]
The key has been re-uploaded, can you retry @jdewinne?

**Comment by joelanford** [comment]
Can confirm that I was able to pull this key from `keyserver.ubuntu.com`

**Comment by jdewinne** [comment]
:+1: Works for me. Closing it.

**Comment by rshetye** [comment]
You also need to specify the correct keyserver. Default keyserver on Ubuntu 20.04.1 LTS did not work. (added -v for verbose to show default keyserver versus explicit keyserver)

WORKED for me:
`$ gpg -v --recv-keys --keyserver hkp://hkps.pool.sks-keyservers.net 052996E2A20B5C7E`
```
gpg: data source: http://hkps.pool.sks-keyservers.net:11371
gpg: armor header: Version: SKS 1.1.6
gpg: armor header: Comment: Hostname: sks.pod02.fleetstreetops.com
gpg: pub  rsa4096/052996E2A20B5C7E 2020-10-30  Operator SDK (release) <cncf-operator-sdk@cncf.io>
gpg: /home/user/.gnupg/trustdb.gpg: trustdb created
gpg: using pgp trust model
gpg: key 052996E2A20B5C7E: public key "Operator SDK (release) <cncf-operator-sdk@cncf.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

DID NOT WORK for me.
`$ gpg -v --recv-keys 052996E2A20B5C7E`
```
gpg: data source: https://keys.openpgp.org:443
gpg: keyserver receive failed: No data
```
