### ISSUE TITLE
ansible: use kustomize with ClusterServiceVersion resources

### ISSUE THREAD

**Issue by flozzone** [operator-framework/operator-sdk#4353]
#### Describe the problem you need a feature to resolve.

When working with Ansible based operators, the ClusterServiceVersion resource is generated by `operator-sdk generate kustomize manifests`, which generates a yaml file under e.g. `config/manifests/bases/sample-operator.clusterserviceversion.yaml`. To provide further operator metadata, I modified the file `sample-operator.clusterserviceversion.yaml` and provided specDescriptors, statusDescriptors, descriptions, icon, ... The file grows and keeping the overview gets hard when I add more CustomResources.

From what it looks, the `sample-operator.clusterserviceversion.yaml` file is consumed by `operator-sdk generate bundle`, when releasing an operator as bundle. It seems it doesn't invoke `kustomize` to process the CSV resource file as with the other configuration files. (At least, I couldn't find any references to this bases)

#### Describe the solution you'd like.

Involve `kustomize` when consuming the ClusterServiceVersion resource file (in `operator-sdk generate bundle`), to give a operator developer the ability to use `kustomize` functionality to extend the ClusterServiceVersion in a Ansible based operator project. It should be possible to split up the ClusterServiceVersion into several parts e.g. patches for each owned CustomResource.

/language ansible

**Comment by estroz** [comment]
You can actually do this as of v1.3 by passing a CSV through stdin (see [the docs](https://sdk.operatorframework.io/docs/olm-integration/generation/#clusterserviceversion-manifests)).

**Comment by flozzone** [comment]
As from what I have seen it already passes the CSV through stdin with the default Makefile command `make bundle`. But I don't know where to put a `patchesStrategicMerge` or a `patchesJson6902` to add multiple owned customresourcedefinitions in the CSV from different files.

At the end I would like to have such a directory structure, or similar:
```
config
  manifests
    bases
      custom-cr1.customresourcedefinitions.yaml
      custom-cr2.customresourcedefinitions.yaml
      custom-cr2.customresourcedefinitions.yaml
      my-operator.clusterserviceversion.yaml
```
A kustomize instruction should then add custom-cr[1-3].customresourcedefinitions.yaml to the CSVs `spec.customresourcedefinitions.owned`
