### ISSUE TITLE
Bundle validation fails with CRD not found

### ISSUE THREAD

**Issue by umangachapagain** [operator-framework/operator-sdk#4374]
#### What did you do?
`operator-sdk bundle validate ./deploy/bundle --verbose`

#### What did you expect to see?
Bundle is valid.

#### What did you see instead? Under which circumstances?
Error that says some of the owned CRDs are not found, even though it is included in the bundle.

```
ERRO[0000] Error: Value ceph.rook.io/v1, Kind=CephCluster: owned CRD "ceph.rook.io/v1, Kind=CephCluster" not found in bundle "ocs-operator.v4.8.0" 
ERRO[0000] Error: Value ceph.rook.io/v1, Kind=CephBlockPool: owned CRD "ceph.rook.io/v1, Kind=CephBlockPool" not found in bundle "ocs-operator.v4.8.0" 
ERRO[0000] Error: Value ceph.rook.io/v1, Kind=CephObjectStore: owned CRD "ceph.rook.io/v1, Kind=CephObjectStore" not found in bundle "ocs-operator.v4.8.0" 
ERRO[0000] Error: Value ceph.rook.io/v1, Kind=CephObjectStoreUser: owned CRD "ceph.rook.io/v1, Kind=CephObjectStoreUser" not found in bundle "ocs-operator.v4.8.0" 
ERRO[0000] Error: Value ceph.rook.io/v1, Kind=CephNFS: owned CRD "ceph.rook.io/v1, Kind=CephNFS" not found in bundle "ocs-operator.v4.8.0" 
ERRO[0000] Error: Value ceph.rook.io/v1, Kind=CephClient: owned CRD "ceph.rook.io/v1, Kind=CephClient" not found in bundle "ocs-operator.v4.8.0" 
ERRO[0000] Error: Value ceph.rook.io/v1, Kind=CephFilesystem: owned CRD "ceph.rook.io/v1, Kind=CephFilesystem" not found in bundle "ocs-operator.v4.8.0" 
ERRO[0000] Error: Value ceph.rook.io/v1, Kind=CephRBDMirror: owned CRD "ceph.rook.io/v1, Kind=CephRBDMirror" not found in bundle "ocs-operator.v4.8.0" 
ERRO[0000] Error: Value ceph.rook.io/v1, Kind=CephObjectRealm: owned CRD "ceph.rook.io/v1, Kind=CephObjectRealm" not found in bundle "ocs-operator.v4.8.0" 
ERRO[0000] Error: Value ceph.rook.io/v1, Kind=CephObjectZoneGroup: owned CRD "ceph.rook.io/v1, Kind=CephObjectZoneGroup" not found in bundle "ocs-operator.v4.8.0" 
ERRO[0000] Error: Value ceph.rook.io/v1, Kind=CephObjectZone: owned CRD "ceph.rook.io/v1, Kind=CephObjectZone" not found in bundle "ocs-operator.v4.8.0"
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

OpenShift

`$ operator-sdk version`
`operator-sdk version: "v1.2.0", commit: "215fc50b2d4acc7d92b36828f42d7d1ae212015c", kubernetes version: "v1.18.8", go version: "go1.15.3", GOOS: "linux", GOARCH: "amd64"`

`$ go version` (if language is Go)
`go version go1.15.2 linux/amd64`

`$ kubectl version`
`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"ffd68360997854d442e2ad2f40b099f5198b6471", GitTreeState:"clean", BuildDate:"2020-11-13T23:53:02Z", GoVersion:"go1.15.0", Compiler:"gc", Platform:"linux/amd64"}`

#### Additional context

https://github.com/openshift/ocs-operator/tree/master/deploy/bundle is the bundle generated by sdk that I am trying to validate.

**Comment by camilamacedo86** [comment]
Could you share the bundle.Dockerfile content please?

**Comment by umangachapagain** [comment]
> Could you share the bundle.Dockerfile content please?

https://github.com/openshift/ocs-operator/blob/master/deploy/Dockerfile

**Comment by camilamacedo86** [comment]
HI @umangachapagain, 

Following some questions

1. What the motivations for these changes in the default layout? Because if you move the things you need to customize the commands and makefile and etc .. to make all still working and you will face problems to upgrade the project for further versions. So, why these changes are required at all? What problems are you trying to solve it?

2. How are you generating the bundle?

**Comment by estroz** [comment]
@camilamacedo86 will open an issue for this in the api repo, since this issue is caused by duplicate CSV values not generating warnings.

**Comment by camilamacedo86** [comment]
Done: https://github.com/operator-framework/api/issues/93
