### ISSUE TITLE
 operator-sdk bundle validate ./bundle is not returning all errors

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4375]
#### What did you do?

- create a project
- run make bundle
- then run, operator-sdk bundle validate ./bundle 

#### What did you expect to see?

I would expect that when I do not inform an optional suite of test the validate would make AlL checks
then, it should fail:

```
operator-sdk bundle validate ./bundle --select-optional suite=operatorframework

INFO[0000] Found annotations file                        bundle-dir=bundle container-tool=docker
INFO[0000] Could not find optional dependencies file     bundle-dir=bundle container-tool=docker
ERRO[0000] Error: Value : (testhelm.v0.0.1) csv.Spec.Icon elements should contain both data and mediatype 
```

#### What did you see instead? Under which circumstances?

```
$   operator-sdk bundle validate ./bundle 
INFO[0000] Found annotations file                        bundle-dir=bundle container-tool=docker
INFO[0000] Could not find optional dependencies file     bundle-dir=bundle container-tool=docker
INFO[0000] All validation tests have completed successfully 
```

```
 operator-sdk bundle validate ./bundle --select-optional name=operatorhub
INFO[0000] Found annotations file                        bundle-dir=bundle container-tool=docker
INFO[0000] Could not find optional dependencies file     bundle-dir=bundle container-tool=docker
ERRO[0000] Error: Value : (testhelm.v0.0.1) csv.Spec.Icon elements should contain both data and mediatype 
```

**Comment by camilamacedo86** [comment]
c/c @estroz

**Comment by estroz** [comment]
@camilamacedo86 you're saying that all optional validators should be run when `bundle validate` runs without `--select-optional`? This was explicitly not what we wanted when this feature was implemented, and I continue to think they should not be run by default, since those validators are optional and might actually conflict (in the future). Regardless this is not a bug, but a feature request.

/kind feature
/remove-kind bug
/triage needs-information

**Comment by camilamacedo86** [comment]
Hi @estroz, 

Since you have a better context about the feature and based in your point of view could you please help me understand;

- What that means get a valid bundle result when we run `operator-sdk bundle validate ./bundle` without the --select-optional? Is this bundle valid for what if we are not checking what is mandatory to have the bundle pushed to OCP catalogue or opertorhub.io?

**Comment by estroz** [comment]
A valid bundle is defined by the [bundle spec](https://github.com/operator-framework/operator-registry/blob/master/docs/design/operator-bundle.md), therefore the "base" (required) validators make sure a bundle conforms to that spec. Optional validators check a superset of requirements of a bundle, ex. for operatorhub.io, but _not requirements for a valid bundle_.

Consider the following scenario: I want to validate a bundle only to make sure it is a valid bundle accord to the spec. I run
```console
$ operator-sdk bundle validate ./bundle
INFO[0000] Found annotations file                        bundle-dir=bundle container-tool=docker
INFO[0000] Could not find optional dependencies file     bundle-dir=bundle container-tool=docker
ERRO[0000] Error: Value : (testhelm.v0.0.1) csv.Spec.Icon elements should contain both data and mediatype 
ERRO[0000] Error: foo validator says your bundle sucks
```
The error I see corresponds to operatorhub.io and foo validators, but I don't care about these. Now I need to turn off those validators so I can only ensure my bundle is valid according to the spec.
```console
$ operator-sdk bundle validate ./bundle --select-optional name!=operatorhub,name!=foo
INFO[0000] Found annotations file                        bundle-dir=bundle container-tool=docker
INFO[0000] Could not find optional dependencies file     bundle-dir=bundle container-tool=docker
INFO[0000] All validation tests have completed successfully 
```
The more optional validators `bundle validate` supports, the more `name!=<name>` I have to specify. This is way worse UX. Furthermore, what if foo and operatorhub validators conflict? Then these two validators can never be run together and `bundle validate` will always fail by default.

**Comment by camilamacedo86** [comment]
Hi @estroz, 

Really thank you. It makes sense. I push a pr with a little more info to the cmd desc which i think that would not let me have this question in the first place. https://github.com/operator-framework/operator-sdk/issues/4375

closing this one.
