### ISSUE TITLE
Options to use operator-sdk bundle validate ./bundle --select-optional are confuse

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4376]
By check-in the options available in `operator-sdk bundle validate ./bundle --select-optional` we have: 

-  operator-sdk bundle validate ./bundle --select-optional suite=operatorframework
- operator-sdk bundle validate ./bundle --select-optional name=operatorhub

1. Why we have to use suite for `operatorframework` and name for `operatorhub`? 
2. Why do we need to use the `suite` and `name` at all?  Why it is not only `operator-sdk bundle validate ./bundle --select-optional=[operatorframework|operatorhub]`
3. The `--select-optional name=operatorhub` lead to me easier to understand that it will check if my bundle is ok to be pushed to the operatorhub.io. however, what means `suite=operatorframework`? Is the OCP catalogue opinion instead? 
4. Why the following command has not a description for operatorframework? 

```
$   operator-sdk bundle validate ./bundle --list-optional
NAME           LABELS                     DESCRIPTION
operatorhub    name=operatorhub           OperatorHub.io metadata validation
               suite=operatorframework    

```

**Comment by camilamacedo86** [comment]
c/c @dmesser @estroz @jmrodri @joelanford

**Comment by estroz** [comment]
Selectors are commonly used in k8s code/manifests (including the existing `operator-sdk` CLI), so users are likely familiar with how they work. In the case of `bundle validate`, `suite` specifies a suite of optional validators, and `name` specifies a specific optional validator. If we add another optional validator related to operator-framework, then it would have `suite=operatorframework` and `name=other-validator`; then both `operatorhub` and `other-validator` can be run with one selector `--select-optional suite=operatorframework`.

1. See above
2. To align with other `operator-sdk` commands, ex. `scorecard`, a label selector CLI was used. This is similar to `kubectl <verb> --selector`.
3. See above. `suite` could be documented in the [OLM integration docs](https://sdk.operatorframework.io/docs/olm-integration/generation/#validation) since it is an operator-sdk specific construct.
4. Same as 3.

/triage support

**Comment by camilamacedo86** [comment]
Hi @estroz, 

I already checked the doc suggested [OLM integration docs](https://sdk.operatorframework.io/docs/olm-integration/generation/#validation) and it does not really help me out :-(. So, I hope that you can help me getting this better for we check how can others could understand that as well. 

Let's go step by step as any user. I executed: 

```
$ operator-sdk bundle validate --list-optional
NAME           LABELS                     DESCRIPTION
operatorhub    suite=operatorframework    OperatorHub.io metadata validation
               name=operatorhub           

```

Then, it makes me very confusing because;

1 - We have the name in the table then name as lebels. How should I suppose know what it means and how/when use them? 

2 - Is its idea have a suite the tests where could I select a specific test from these suites? So, let's see if I got your explanation. The relation here is 1 suite of validations can have 1..N (labels/name/specific checks) is that? Then, it means that I could;

- `operator-sdk bundle validate ./bundle --select-optional suite=operatorframework name=testA` 
- `operator-sdk bundle validate ./bundle --select-optional suite=operatorframework name=testB`

Then, if yes the following command should work:

```
$ operator-sdk bundle validate ./bundle --select-optional suite=operatorframework name=operatorhub
Error: invalid command args: an image tag or directory is a required argument
Usage:
  operator-sdk bundle validate [flags]

Examples:
This example assumes you either have a *pullable* bundle image,
or something similar to the following operator bundle layout present locally:
```
 
**NOTE** The command does not work and the error does not really help me out figure out why and what is wrong. 

3 - According to your explanation I understand that we have only `operatorframework`(suite) with `operatorhub`(name/label/test) and the both commands `operator-sdk bundle validate ./bundle --select-optional suite=operatorframework` and `operator-sdk bundle validate ./bundle --select-optional name=operatorhub` are doing the same check. Is that right? 

4 - `operator-sdk bundle validate` has the purpose to validate the bundle with OLM. Then, I understand that we would have validation for who is trying to publish the bundle in operatorhub.io and another specific for OCP catalogue which is the only options currently.  

So, if we sdk can have 1...N suite of tests with 1..N checks that it means that we have the idea of support to introduce new suites/tests/checks in the future. Do you have a use case example of what is planned that justified it and not let it fail in the anti-Pattern Premature Optimization?

**Comment by estroz** [comment]
1. We could document these label selectors better.
2. You passed labels incorrectly, the invocation should be
	```sh
	operator-sdk bundle validate ./bundle --select-optional suite=operatorframework,name=testA
	```
	Error messaging could be better though.
3. Yes. As more validators are added I expect `suite=operatorframework` to be larger than just one validator.
4. This is incorrect, as I've stated above. `bundle validate` validates a bundle against a spec. Bundles are an effort larger than just OLM/operator framework. Furthermore you can use OLM to install an operator via bundle without using operatorhub.io.

>Do you have a use case example of what is planned that justified it and not let it fail in the anti-Pattern Premature Optimization?

Yeah, more validators being added in the future. Anyone can contribute a validator. Also I think you're conflating premature optimization with extensibility here.

**Comment by camilamacedo86** [comment]
Hi @estroz, 

Thank you for the answers and to share your knowledge over it.  So, IMO what we can do here to address these scenarios and make easier the understanding for the others too are: 

- [ ] - See if we can find a better way to output the info `$ operator-sdk bundle validate --list-optional` to illustrate this idea
- [ ] - Improve the cmd output of --select-optional -h to clarifies the labels their usage. Maybe add examples
- [ ] - Improve the error faced when;

```
$ operator-sdk bundle validate ./bundle --select-optional suite=operatorframework name=operatorhub
Error: invalid command args: an image tag or directory is a required argument
Usage:
  operator-sdk bundle validate [flags]
```

To make clear that the usage of the command is wrong in this case

- [ ] - Address this clarifications in https://sdk.operatorframework.io/docs/olm-integration/generation/#validation

**Comment by estroz** [comment]
Closing since this seems to be completed by #4379
