### ISSUE TITLE
The options for customize the channels and versions for the bundle target is not clear.

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4377]
#### What did you do?

I checked the Makefile; 

```
# Current Operator version
VERSION ?= 0.0.1
# Default bundle image tag
BUNDLE_IMG ?= controller-bundle:$(VERSION)
# Options for 'bundle-build'
ifneq ($(origin CHANNELS), undefined)
BUNDLE_CHANNELS := --channels=$(CHANNELS)
endif
ifneq ($(origin DEFAULT_CHANNEL), undefined)
BUNDLE_DEFAULT_CHANNEL := --default-channel=$(DEFAULT_CHANNEL)
endif
BUNDLE_METADATA_OPTS ?= $(BUNDLE_CHANNELS) $(BUNDLE_DEFAULT_CHANNEL)
``` 

- How I am a user of the tool can customize the channels and versions of my projects? 
- What is the difference here between `DEFAULT_CHANNEL` and `BUNDLE_DEFAULT_CHANNEL`? It is not clear for users and if they export `BUNDLE_DEFAULT_CHANNEL` instead of `DEFAULT_CHANNEL` it will fail.  
- How users would know that they can export the ENVVAR to update the values such as : 

```
$ export DEFAULT_CHANNEL=preview
$ export VERSION=1.0.0
$ make bundle
```

#### What did you expect to see?

The instructions to cover how users can customize the target to set their default channels and versions as to how they can export ENVVARs or that in the Makefile.

**Comment by estroz** [comment]
These variables could be documented with comments.
