### ISSUE TITLE
unable to use `operator-sdk generate bundle --input-dir` to generate a bundle from a pre-existent one

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4380]
#### What did you do?

Try to create a new bundle from another one that already exists with `operator-sdk generate bundle --input-dir`

#### What did you expect to see?

The command should say what args are missing for I generate my new bundle from a pre-existent one
and successfully perform this action. 

#### What did you see instead? Under which circumstances?

Error: invalid command options: --deploy-dir must be set if not reading from stdin

#### Environment
`$ operator-sdk version`

"v1.2.0-56-g8c31ab8f", commit: "8c31ab8fdbbe572a94a10c8f0dff33bbb53beb38", kubernetes version: "v1.19.4", go version: "go1.15.2", GOOS: "darwin", GOARCH: "amd64

#### Additional context

by @estroz;

so --input-dir was originally required for metadata generation through the operator-registry library, but manifests were only re-generated from stdin or --deploy-dir/--crds-dir
i.e. the --input-dir functionality was never added for manifests generation

**Comment by camilamacedo86** [comment]
Was not this one solved?

**Comment by estroz** [comment]
Closed by #4514
