### ISSUE TITLE
Migration guide from 0.19 to 1.0+ is outdate and missing steps after 1.3.0 release 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4392]
#### What did you do?

Try to upgrade a project which is 0.19 to. the latest version available by following https://sdk.operatorframework.io/docs/building-operators/golang/migration/ 

#### What did you expect to see?

All worked by following the steps provided.

#### What did you see instead? Under which circumstances?

It will not work because with the plugin v3 released by default in the 1.3.0 release it is missing steps such as: 

- Check [sigs.k8s.io/controller-runtime release docs from 0.7.0+ version]( https://github.com/kubernetes-sigs/controller-runtime/releases ) for breaking changes.

Replace:

```go 
func (r *<MyKind>Reconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
    ctx := context.Background() 
	log := r.Log.WithValues("cronjob", req.NamespacedName)
```
With:
```go 
func (r *<MyKind>Reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log := r.Log.WithValues("cronjob", req.NamespacedName)
```

#### Environment

**Operator type:**
 /language go 

$ operator-sdk version: 1.3.0

#### Additional context

To know more about the changes between v2 to v3 plugin versions check the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/1916/

**Comment by camilamacedo86** [comment]
c/c @estroz @joelanford @jmrodri

**Comment by estroz** [comment]
The migration guide should specifically be used to migrate from < v0.19 to v1.0, and not to migrate to the latest minor version (migration guides exist for each minor version already).

**Comment by camilamacedo86** [comment]
Hi @estroz, 

I see that we have here 2 approaches to follow up. 

**Option A** (based in your comment/pov)

We need to provide 2 docs;

1 - How to upgrade from 0.19 to 1.3.0 (default plugin v3) 
2- How to upgrade from 1.2.0 to 1.3.0 (v2 to v3 plugin)

For item 2 we can use the upstream doc when the pr kubernetes-sigs/kubebuilder#1916 get merged. However, the SDK doc will still be missing item 1. Also, then it means clarifies that in the doc which shows not currently. We would need to have 2 sections in or find a better way to make it clear:

<img width="210" alt="Screen Shot 2021-01-12 at 18 45 28" src="https://user-images.githubusercontent.com/7708031/104358445-5ccc7500-5506-11eb-936e-822adb18bcdd.png">


**Option B** (initial suggestions)

- Ensure that the migration doc 1.0+ (from old layout 0.19 to the lastest 1.0 + layout provided ) is covering all steps
- And then, users are able to check the versioned doc for the specific releases if they need/wish:

<img width="598" alt="Screen Shot 2021-01-12 at 18 43 52" src="https://user-images.githubusercontent.com/7708031/104358327-33134e00-5506-11eb-923c-f118f919dd2b.png">

Because of this, IMO the option b shows the most straightforward and intuitive approach. 

c/c @jmrodri @joelanford @asmacdo  wdyt?

**Comment by estroz** [comment]
>1 - How to upgrade from 0.19 to 1.3.0 (default plugin v3)

I am not suggesting this. Instead I suggest the following:
1. How to upgrade from 0.19 to 1.0
2. How to upgrade from 1.0 to 1.1 (migration guide was generated during release)
3. ...
4. How to upgrade from 1.A to 1.B (migration guide was generated during release)

That way SDK maintainers do not have to update the "0.19 to 1.0+" doc whenever a new release is created, since a migration guide already exists for that new release; instead users can step through all minor version migration guides starting from "1.0 to 1.1".

**Comment by camilamacedo86** [comment]
Hi @estroz, 

Do you think that is easier/less effort ask for the users follow up N docs instead of just one? 
I mean, see that the biggest part of the users has their projects using a version lower than 1.0. So, if we follow up your suggestion it means:

- Migrate 0.19 to 1.0 - Recreate the project from the scratch and perform a lot of changes
- MIgrate from 1.0 to 1.1 - Small changes
- MIgrate 1.2 (go v2 )to 1.3 (go v3): Recreate the project from the scratch again. 

When we can just add a few steps in the existent doc [migrate from legacy to the new layout](https://sdk.operatorframework.io/docs/building-operators/golang/migration/) and they can do all by once and just recreate the project once.

**Comment by estroz** [comment]
On second thought, I agree with your idea. We should retitle the document to `Migrating Projects from pre-v1.0.0 to latest release` and keep it up to date with the latest release.

**Comment by camilamacedo86** [comment]
hi @jmrodri @estroz @rashmigottipati,

IMO it is quite important and if we leave in the backlog it might not get done. WDYT about we prioritize it for 1.5.0 milestone?

**Comment by estroz** [comment]
@camilamacedo86 that depends on if @rashmigottipati can do this by v1.5.0

**Comment by rashmigottipati** [comment]
I'm good with prioritizing this and moving it to v1.5.0 milestone.
