### ISSUE TITLE
how to get the api version of the cr instance in the reconcile function ?

### ISSUE THREAD

**Issue by kaushiksrinivas** [operator-framework/operator-sdk#4394]
Trying to upgrade an api version from one version to another.
But do not want the old controller to reconcile the cr of a newer version.

How can we figure out the api version of the cr instance which caused the reconcile for the given controller ?

**Comment by kaushiksrinivas** [comment]
@camilamacedo86 Need inputs

**Comment by camilamacedo86** [comment]
Hi @kaushiksrinivas, 

> Trying to upgrade an api version from one version to another.
> But do not want the old controller to reconcile the cr of a newer version.

Following the steps; 

1. Create the new API

$  operator-sdk create api --group=cache --kind=Memcached --version=v2 --resource=true --controller=false

2. See that when you run the command `create api` you are creating this object/struct representation in `api/version/`; Then, in the controller, you end up importing your own APIS which would mean that the old controller would have; 

```go
import (
	cachev1 "github.com/example/memcached-operator/api/v1" // import for my Memcached api with the v1 version
...

func (r *MemcachedReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log := r.Log.WithValues("memcached", req.NamespacedName)

	// Fetch the Memcached instance
	memcached := &cachev1.Memcached{}
```

So it means that you can be replicated the same approach for the controllers as well whcih would like;

<img width="314" alt="Screen Shot 2021-01-13 at 12 44 58" src="https://user-images.githubusercontent.com/7708031/104454017-2a218b80-559d-11eb-97e2-808b210a1684.png">
  
Note that each controller and suite test will work with its own API version. You will need to manually copy and past the old controller and suite test to the new dir version. 

3. Then, ensure that you updated the main.go to start both such as; 

```go
import (
	...

	cachev1 "github.com/example/memcached-operator/api/v1"
	cachev1alpha1 "github.com/example/memcached-operator/api/v1alpha1"
	controllersv1 "github.com/example/memcached-operator/controllers/v1"
	controllersalphav1 "github.com/example/memcached-operator/controllers/v1alpha1"
	// +kubebuilder:scaffold:imports
)

...

if err = (&controllersalphav1.MemcachedReconciler{
		Client: mgr.GetClient(),
		Log:    ctrl.Log.WithName("controllers").WithName("Memcached").WithValues("version", "alphav1"),
		Scheme: mgr.GetScheme(),
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "Memcached alphav1")
		os.Exit(1)
	}
	if err = (&cachev1alpha1.Memcached{}).SetupWebhookWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create webhook", "webhook", "Memcached alphav1")
		os.Exit(1)
	}

	if err = (&controllersv1.MemcachedReconciler{
		Client: mgr.GetClient(),
		Log:    ctrl.Log.WithName("controllers").WithName("Memcached").WithValues("version", "v1"),
		Scheme: mgr.GetScheme(),
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "Memcached v1")
		os.Exit(1)
	}
```

Then, in the end, each controller version will be responsible to reconcile each api version. Is it make sense? Did you tried to do it?

**Comment by camilamacedo86** [comment]
I am closing this one since the previous comment shows sorted out your questions. However, please feel free to raise new issues if you still needing help with. Also, please let us know what do you did, what was there result faced and what is the result expected in this case.
