### ISSUE TITLE
Operator Capability Levels - Unclear meaning of items marked with "**"

### ISSUE THREAD

**Issue by joefuzz** [operator-framework/operator-sdk#4397]
When viewing the Operator Capability Levels documentation page, several points have "**" marks at the end. However, I do not see anything written on that same page explaining what that notation means in context. Is there clarification elsewhere that I missed, or was a footnote left off in error? 

Is it possible for someone to clarify the meaning of the "**" denotation on the referenced page?  

Reference: https://sdk.operatorframework.io/docs/advanced-topics/operator-capabilities/operator-capabilities/#upgrade-of-the-managed-workload

![2021-01-14_10-17-41](https://user-images.githubusercontent.com/14001366/104610121-c2794800-5651-11eb-967d-a9f8dcd062a0.png)

**Comment by estroz** [comment]
Those appear to be leftover markdown syntax rather than footnote signifier. Any chance you could submit a PR to remove them?

/kind documentation

**Comment by joefuzz** [comment]
I’d be happy to! I am green with this kind of stuff so forgive me if it takes me a little to submit my PR, but I will checkout and read the contributor docs.
