### ISSUE TITLE
Golang Quick-Start master changes brings confusion 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4415]
We can check the diffs between https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/ (release) and master (https://master.sdk.operatorframework.io/docs/building-operators/golang/quickstart/). Following the points

- Ansible/Helm/Golang now has no longer the same steps and are no longer equals
- The idea of the quick start is to be very quick and just give the commands for the users to create and deploy an operator in order to offer a basic experience. However, now it is too much more verbose. 
- The following NOTE was removed. This NOTE is required since new users usually do not understand that the repository where the image will be pushed needs to be set as public. (It was a very common issue raised in the past which shows solved well with the note.)

<img width="642" alt="Screen Shot 2021-01-21 at 01 44 19" src="https://user-images.githubusercontent.com/7708031/105268512-4a97aa00-5b8a-11eb-83ad-3d430ef8c134.png">

- Why we need to use quay.io? It is not a requirement and by adding that lead the understanding that users should mandatorily use it. Also, note that a lot of developers will not indeed know that it is a kind of registry since docker hub is the most used.

- Also, why we need these exports at all? They make the instruction more verbose and in POV harder to understand and copy and paste.  

Original instruction: 

```
make docker-build docker-push IMG=<some-registry>/<project-name>:<tag>
```

Was replaced in master by: 

```
export USERNAME=<quay-namespace>
export OPERATOR_IMG="quay.io/$USERNAME/memcached-operator:v0.0.1"
make docker-build docker-push IMG=$OPERATOR_IMG
``` 

- The following NOTE shows not fit well in the quick start. See that it is very similar to the topics in the FAQ. Then, IMO it should be moved to the FAQ section. 

<img width="690" alt="Screen Shot 2021-01-21 at 01 48 37" src="https://user-images.githubusercontent.com/7708031/105268911-e88b7480-5b8a-11eb-8565-2928de9569b2.png">

- The following instruction is confusing. To much verbose and I do not think that we should add notes in the instructions because it goes against the idea of making it easier for users just copy and past:

```
make bundle IMG=$OPERATOR_IMG
# Note the "-bundle" component in the image name below.
export BUNDLE_IMG="quay.io/$USERNAME/memcached-operator-bundle:v0.0.1"
make bundle-build BUNDLE_IMG=$BUNDLE_IMG
make docker-push IMG=$BUNDLE_IMG
```

Suggestion:

```
make bundle IMG=<some-registry>/<project-name>:<tag>
make bundle-build docker-push BUNDLE_IMG=<some-registry>/<project-name-bundle>:<tag>
```

- Also, see that the section OLM Integration has a doc that shows more a tutorial but is named as a quick start. So, IMO we should fix that to be a real quick-start as we discussed and agreed before (@joelanford, @asmacdo and I) regards its standards and just link in the Next section the bundle quick start. Note that we discussed the quick start approach a lot for the release 1.0.0. (E.g see the bundle quick start to know how to deploy your operator using the bundle). Note that the steps add regards to the bundle are not completed too. It should speak about the interface mode that will appear for the users and then, by adding it to the building operators sections starts to get too verbose and confuse. Also shows go out of its scope and purpose.

**Comment by camilamacedo86** [comment]
c/c @asmacdo @jmrodri @estroz

**Comment by estroz** [comment]
>Ansible/Helm/Golang now has no longer the same steps and are no longer equals

That isn't really true. In fact, they are more equal than they were in the latest release (v1.3).

>The idea of the quick start is to be very quick and just give the commands for the users to create and deploy an operator in order to offer a basic experience. However, now it is too much more verbose.

Each quickstart takes ~3000 pixels (3 page-length scrolls on a 1080p monitor) to get to the bottom. That includes headers, footers, etc. IMO this _is_ very quick.

>The following NOTE was removed

This should be added back.

>Why we need to use quay.io

We don't, it is an example. Feel free to make it more generic.

>Also, why we need these exports at all

Feel free to change those.

>The following NOTE shows not fit well in the quick start. See that it is very similar to the topics in the FAQ.

Agreed

>The following instruction is confusing. To much verbose and I do not think that we should add notes in the instructions because it goes against the idea of making it easier for users just copy and past

Sure. #4406 makes these commands even easier to run inline.

>Also, see that the section OLM Integration has a doc that shows more a tutorial but is named as a quick start. So, IMO we should fix that to be a real quick-start as we discussed and agreed before

There's already an issue for this: #4241
