### ISSUE TITLE
Running generate bundle again removes 'replaces' field

### ISSUE THREAD

**Issue by font** [operator-framework/operator-sdk#4418]
#### What did you do?

Execute `make bundle` twice:

```shell
make bundle
make bundle
```
The specific line in the `Makefile` recipe is the following:
```shell
$(KUSTOMIZE) build config/manifests | operator-sdk generate bundle -q --overwrite --version $(VERSION) $(BUNDLE_METADATA_OPTS)
```

#### What did you expect to see?

A CSV that does not change after a `make bundle` was previously run. This is useful for CI/CD testing to make sure the bundle is up-to-date.

The first time `make bundle` was run with a new updated version `v0.0.1-rc.2` it generated the following CSV diff:

```shell
→ git diff --staged bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
diff --git a/bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml b/bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
index a7045d3..1ee80a4 100644
--- a/bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
+++ b/bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
@@ -29,7 +29,7 @@ metadata:
     capabilities: Basic Install
     operators.operatorframework.io/builder: operator-sdk-v1.2.0
     operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
-  name: gatekeeper-operator.v0.0.1-rc.1
+  name: gatekeeper-operator.v0.0.1-rc.2
   namespace: placeholder
 spec:
   apiservicedefinitions: {}
@@ -268,7 +268,7 @@ spec:
                 - --enable-leader-election
                 command:
                 - /manager
-                image: quay.io/gatekeeper/gatekeeper-operator:0.0.1-rc.1
+                image: quay.io/gatekeeper/gatekeeper-operator:v0.0.1-rc.2
                 imagePullPolicy: Always
                 name: manager
                 resources:
@@ -369,4 +369,5 @@ spec:
   maturity: alpha
   provider:
     name: Red Hat
-  version: 0.0.1-rc.1
+  replaces: gatekeeper-operator.v0.0.1-rc.1
+  version: 0.0.1-rc.2
```

#### What did you see instead? Under which circumstances?

After running `make bundle` again e.g. via CI/CD testing, the following `replaces` field was removed:

```shell
→ git diff bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
diff --git a/bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml b/bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
index 1ee80a4..de9044c 100644
--- a/bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
+++ b/bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
@@ -369,5 +369,4 @@ spec:
   maturity: alpha
   provider:
     name: Red Hat
-  replaces: gatekeeper-operator.v0.0.1-rc.1
   version: 0.0.1-rc.2

```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

`$ operator-sdk version`

``operator-sdk version: "v1.2.0", commit: "215fc50b2d4acc7d92b36828f42d7d1ae212015c", kubernetes version: "v1.18.8", go version: "go1.15.3", GOOS: "linux", GOARCH: "amd64"``

#### Additional context

I imagine `operator-sdk` is using the existing CSV to determine if a newly generated CSV is replacing a previous one. But if that CSV contains a `replaces` field, what does/should `operator-sdk` do?

Also, what's the best practice for ensuring a bundle is up-to-date in CI/CD?

**Comment by estroz** [comment]
This was a bug that was fixed in v1.3. Since there's no reliable way to figure out what version is being upgraded from using the existing CSV (as you said), we decided that having devs add a `spec.replaces` field to their base CSV (`config/manifests/bases/<operator name>.clusterserviceversion.yaml`) is the best fix. This field will not be overwritten when you run `make bundle`. Hope that helps!
