### ISSUE TITLE
Github Action to Install Operator-SDK

### ISSUE THREAD

**Issue by adambkaplan** [operator-framework/operator-sdk#4421]
#### Describe the problem you need a feature to resolve.

`operator-sdk run` can be used to test if an SDK operator successfully deploys via OLM.
Installing operator-sdk via a GitHub action would let users easily install the sdk and run their desired tests via GitHub actions.

#### Describe the solution you'd like.

A GitHub action published on GitHub's action marketplace which installs operator-sdk. Additional desired features:

1. Ability to select sdk version
2. Use the action cache to reduce network activity/unnecessary downloads.

[1] https://github.com/marketplace?type=actions

**Comment by adambkaplan** [comment]
Note that there is an action on the marketplace that may cover the desired feature set: https://github.com/marketplace/actions/setup-operator-sdk-action

**Comment by estroz** [comment]
@adambkaplan this is a great idea. Do you want to work on this? If not, @jmrodri will.

**Comment by asmacdo** [comment]
In the meantime, you should be able to use a docker image we publish that contains the binary.

**Comment by planetf1** [comment]
+1 on this request - having just started building an operator it's one of the first things I looked for (with samples), though I now have some more detailed info & understanding of how to approach. GitHub actions are increasingly possible, so showing how this might be done neatly with operator sdk and providing the elements to make that easy, such as an action, would be really useful

**Comment by jmrodri** [comment]
There are no plans to do this.
