### ISSUE TITLE
Golang Based Operator Tutorial

### ISSUE THREAD

**Issue by ShinojEdakkara** [operator-framework/operator-sdk#4425]
**Implement the Controller**
For this example replace the generated controller file controllers/memcached_controller.go with the example memcached_controller.go implementation.

For the above section in https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/ , I copied the example from : https://github.com/operator-framework/operator-sdk/blob/v1.2.0/testdata/go/memcached-operator/controllers/memcached_controller.go

In the example, the import has this entry : 
cachev1alpha1 "github.com/example/memcached-operator/api/v1alpha1"

Unless I change the import to  this below one, I can't get the sample working : 

cachev1alpha1 "github.com/example-inc/memcached-operator/api/v1alpha1"

**Comment by rashmigottipati** [comment]
@ShinojEdakkara 
PR #4393 that was merged to master fixes this issue, it should be available in the next SDK release.

**Comment by camilamacedo86** [comment]
Closing this one as solved in the master already,
