### ISSUE TITLE
watch permission need to be added on pods in the examples.

### ISSUE THREAD

**Issue by ErezArbell** [operator-framework/operator-sdk#4433]
## Bug Report

Following issue https://github.com/operator-framework/operator-sdk/issues/4059
I had the same issue.
I can confirm that the correct solution is https://github.com/operator-framework/operator-sdk/issues/4059#issuecomment-712858011

So the 'watch' need to be added in the relevant places. It is not there now.

**Comment by estroz** [comment]
I think the RBAC files are not being regenerated after adding the appropriate marker comments. Will investigate.
