### ISSUE TITLE
Document Compatibility with OLM

### ISSUE THREAD

**Issue by njhale** [operator-framework/operator-sdk#4438]
In some cases, recent versions of SDK are incompatible with older versions of OLM. In these scenarios, users may _incorrectly_ attribute a failed operator installation via OLM to OLM itself. This leads to a [backlog of issues]() on OLM, which I think we could avoid by providing a compatibility matrix in SDK's docs.

(If such docs already exist, please link in the comments and feel free to close this out!)

**Comment by estroz** [comment]
`operator-sdk` recently started packaging a set of versioned OLM manifests as bindata internally to declare explicit support for these versions and permit offline installations (assuming referenced images are present in-cluster). As of now, 0.15.1, 0.16.1, and 0.17.0 are supported, but support is not documented anywhere.

P.S. @njhale the link on "backlog of issues" in this issue's description is missing.
