### ISSUE TITLE
Webhook mount location is incompatible with older versions of OLM

### ISSUE THREAD

**Issue by njhale** [operator-framework/operator-sdk#4439]
#### What did you do?

Attempt to deploy an operator with webhooks generated by SDK v1.1.0 against the `release-4.6` version of OLM.

#### What did you expect to see?

The operator falls back to the _old_ default serving cert mount locations for the `release-4.6` version of OLM if the _newer_  locations aren't populated: 

_older_ `release-4.6` locations:

- `/apiserver.local.config/certificates/apiserver.crt`
- `/apiserver.local.config/certificates/apiserver.key`

_newer_ `master` locations:

- `/tmp/k8s-webhook-server/serving-certs/tls.cert`
- `/tmp/k8s-webhook-server/serving-certs/tls.key`

#### What did you see instead? Under which circumstances?

The operator attempted to use _only_ the new, unpopulated, serving cert mount locations and failed to be deployed:

```sh
$ kubectl get events -n operators

55s         Warning   Failed                pod/opentelemetry-operator-controller-manager-9bdd9fcc4-ctr8k     Error: cannot find volume "apiservice-cert" to mount into container "kube-rbac-proxy"
55s         Warning   Failed                pod/opentelemetry-operator-controller-manager-9bdd9fcc4-ctr8k     Error: cannot find volume "apiservice-cert" to mount into container "manager"
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

OpenShift

`$ operator-sdk version`

v1.1.0

#### Possible Solution

- Fall back to older default mount locations when current locations aren't populated
- Document OLM compatibility

#### Additional context

- A patch has been introduced into OLM that mounts serving certs in both the old and new locations. This **will not** be backported to 4.6 or any earlier releases since it would amount to supporting _forwards compatibility_ with SDK.
- [Original Issue](https://github.com/operator-framework/operator-lifecycle-manager/issues/1839)
- [Issue: documenting SDK/OLM compatibility](https://github.com/operator-framework/operator-sdk/issues/4438)

**Comment by varshaprasad96** [comment]
+1. We may have to document the OLM compatibility in general. Also for this specific issue, we could point out that for previous versions of OLM, the workaround is to specify the location of certs while setting up webhook with controller-runtime manager (ex: [here](https://github.com/varshaprasad96/memcached-operator/blob/conv-wh-specify-config/api/v1/memcached_webhook.go#L38-L48)).
