### ISSUE TITLE
Identify the leader pod

### ISSUE THREAD

**Issue by gowrisankar22** [operator-framework/operator-sdk#4440]
I have the below use case:

1. Running operator in 3 replicas[HA]
2. I would like to run a sidecar container with the operator pod to check certain things,  based on that, I will just make an update in the CR so that controller will reconcile. Now I want to identify from the sidecar container, which operator pod is running as a leader (I am running operator in 3 pods in 3az) before the sidecar is starting to check.

Can someone help ?

**Comment by rashmigottipati** [comment]
@gowrisankar22 

You should be able to find out the leader from your own application using sidecar, simply by accessing `http://localhost:4040` from the sidecar container and get a JSON response back that contains the name of the elected leader pod.

Have you already tried this?

**Comment by gowrisankar22** [comment]
@rashmigottipati by default 4040 port is exposed by the operator pod? I couldnot access the 4040 port

**Comment by rashmigottipati** [comment]
@gowrisankar22 I will do some investigation on that and let you know.

**Comment by gowrisankar22** [comment]
@rashmigottipati that will be really great

**Comment by rashmigottipati** [comment]
You probably need to expose the port. 
Here's some information on identifying leader pod - https://kubernetes.io/blog/2016/01/simple-leader-election-with-kubernetes/#leader-election-with-sidecars

**Comment by rashmigottipati** [comment]
@gowrisankar22 here's some information on identifying leader pod: 
https://kubernetes.io/blog/2016/01/simple-leader-election-with-kubernetes/#leader-election-with-sidecars
