### ISSUE TITLE
operator-sdk generate bundle -h has no instructions/examples for Non-SDK projects

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4442]
#### What did you do?

Checking the operator-sdk generate bundle -h help  

#### What did you expect to see?

I'd like to see in the help examples over how to use them when the project is non-sdk as well

#### What did you see instead? Under which circumstances?

Only steps valid for sdk layout projects

#### Environment

operator-sdk version: df8186c446c7e8d260bcd42216e59b4a08ce7185

**Comment by estroz** [comment]
The command docs could be made more general, but catering to non-SDK projects isn't a strict goal of this project.

/kind documentation
/assign

**Comment by camilamacedo86** [comment]
Hi @estroz, 

IMO the output and docs are missing an example over how to use the command for a project that is no-skd. See that we have none examples over that at all.
