### ISSUE TITLE
Mocking SDK calls

### ISSUE THREAD

**Issue by bakito** [operator-framework/operator-sdk#445]
Hi

I was missing the functionality of mocking the sdk API calls. (similar to https://github.com/operator-framework/operator-sdk/issues/284)
Therefore I created a small module with an additional layer over the sdk functions. The new layer can then be mocked via a gomock generated implementation.

https://github.com/bakito/operator-sdk-mock

By using this I can do mocked tests without having a fake client behind the sdk.

Perhaps you could implement something like this into the framework itself.

Regards,

Marc

**Comment by estroz** [comment]
@bakito you can now test your API calls with controller-runtime's fake client. Check out our [unit testing doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/unit-testing.md) for a walkthrough.
