### ISSUE TITLE
reconcilePeriod set to 0s is not working

### ISSUE THREAD

**Issue by tobernguyen** [operator-framework/operator-sdk#4459]
#### What did you do?

I have my `watches.yaml` set to following:

```
- version: v1alpha1
  group: X (redacted)
  kind: Y (redacted)
  role: X (redacted)
  manageStatus: False
  snakeCaseParameters: False
  watchDependentResources: True
  watchClusterScopedResources: True
  reconcilePeriod: "0s"
```

#### What did you expect to see?

I expected the reconcile run once at the 1st start time and don't run again unless the watched subresource has a update.

#### What did you see instead? Under which circumstances?

The reconciliation still runs periodically (about 1 minute).
The ansible playbook was run successfully without any errors or resulted in any changes. It will wait for about 1 minute and run again.

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

Kubernetes Kops on AWS. 

`$ operator-sdk version`

```
operator-sdk version: "v1.3.0", commit: "1abf57985b43bf6a59dcd18147b3c574fa57d3f6", kubernetes version: "v1.19.4", go version: "go1.15.6", GOOS: "darwin", GOARCH: "amd64"
```

`$ go version` (if language is Go)

```
go version go1.15.7 darwin/amd64
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

#### Possible Solution

Not found yet. I tried to set `reconcilePeriod` to `8760h` (1 year) but it still runs reconciliation every about 1-2 minutes.

#### Additional context

Might relate to this issue: https://github.com/operator-framework/operator-sdk/issues/3950

**Comment by estroz** [comment]
We've had quite a few issues that reference using `reconcilePeriod: "0s"` for a variety of reasons, one in particular being the "run immediately then reconcile as usual". However this will not work because 0 seconds is actually the zero value for that option, and causes the reconciler to run only [when a change to a CR occurs](https://github.com/operator-framework/operator-sdk/issues/1978#issuecomment-535994565). Theoretically the default value is [1 minute](https://sdk.operatorframework.io/docs/building-operators/ansible/reference/watches/) which is used when that value isn't set in a watch, which is why you would see reconciliation happen every ~1 min. However, I don't actually see this default value getting passed to [anisble-operator's reconciler](https://github.com/operator-framework/operator-sdk/blob/545eb37/internal/cmd/ansible-operator/run/cmd.go#L176), so I'm not really sure what's going on. Perhaps I'm missing something and @fabianvf or @asmacdo can shed light on this situation.

Potentially related issues (including the one you linked):
- #3950 
- #4258 
- #1679

/triage support

**Comment by fabianvf** [comment]
@estroz the defaults for watches are set when the watches are loaded (https://github.com/operator-framework/operator-sdk/blob/545eb37b7820c15cb872a8428b6dce88e42dcfed/internal/ansible/watches/watches.go#L149-L151). The type for `ReconcilePeriod` in the struct that's used for loading the yaml is `*metav1.Duration` so nil should be the zero value, `0s` should be properly recognized as a non-nil non-default. Not sure why that wouldn't be respected though, we definitely should dig into this ASAP

**Comment by tobernguyen** [comment]
> anisble-operator's reconciler

I have enabled the debug log for ansible-operator and here is what I found. Looks like the operator-sdk sees the changes in HPA as dependent change so it runs the reconciliation. HPA is changed constantly by kubeapi but only things nested inside the status field of HPA are being changed and I expect the operator should ignore the changes to the status field of dependent resources, right?

```
{"level":"debug","ts":1612415191.6589468,"logger":"predicate","msg":"Reconciling due to dependent resource update","name":"notification-svc","namespace":"notification-svc","apiVersion":"autoscaling/v2beta2","kind":"HorizontalPodAutoscaler"}
```

**Comment by tobernguyen** [comment]
> I have enabled the debug log for ansible-operator and here is what I found. Looks like the operator-sdk sees the changes in HPA as dependent change so it runs the reconciliation. HPA is changed constantly by kubeapi but only things nested inside the status field of HPA are being changed and I expect the operator should ignore the changes to the status field of dependent resources, right?
> 
> ```
> {"level":"debug","ts":1612415191.6589468,"logger":"predicate","msg":"Reconciling due to dependent resource update","name":"notification-svc","namespace":"notification-svc","apiVersion":"autoscaling/v2beta2","kind":"HorizontalPodAutoscaler"}
> ```

And if I watch that HPA with kubeapi

```
kubectl get hpa notification-svc -n notification-svc -w
```

And every time I get a response from kubeapi, ansible-operator triggers a reconciliation.

**Comment by fabianvf** [comment]
@tobernguyen status field changes are monitored by the operator, if e.g. a Pod goes from a running to a failing state, that's reflected in the status and is likely of interest to the operator. Obviously that's got some bad implications with HPA, so I could totally see adding a filter that specifically discards events where it's only the expected and noisy fields that are changing. In the meantime, you can use the `blacklist` field in your `watches.yaml` to avoid setting a watch on HPA resources (https://sdk.operatorframework.io/docs/building-operators/ansible/reference/watches/).

Would look like this:
```yaml
- version: v1alpha1
  group: X (redacted)
  kind: Y (redacted)
  role: X (redacted)
  manageStatus: False
  snakeCaseParameters: False
  watchDependentResources: True
  watchClusterScopedResources: True
  reconcilePeriod: "0s"
  blacklist:
  - group: autoscaling
    version: v1
    kind: HorizontalPodAutoscaler
```
* Note, the version for HPA may differ based on your cluster version. It's v1 in latest kube I believe.

**Comment by estroz** [comment]
@fabianvf the default [set in flags](https://github.com/operator-framework/operator-sdk/blob/545eb37b7820c15cb872a8428b6dce88e42dcfed/internal/ansible/flags/flag.go#L48) is the one [documented](https://sdk.operatorframework.io/docs/building-operators/ansible/reference/watches/) though, but that flag default is not used. Also `reconcilePeriodDefault = metav1.Duration{Duration: time.Duration(0)}` which is equivalent to "0s" when parsed, and if `tmp.ReconcilePeriod == nil` then it is overridden by `time.Duration(0)`, so the pointer doesn't really matter in this code.

```go
parsed, _ := time.ParseDuration("0s")
fmt.Println(parsed == time.Duration(0)) // true
```

Based on what you're saying, "0s" should be treated differently than it not being set. However when you requeue a request with `RequeueAfter: 0` it is treated the same as [not being set at all](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.8.1/pkg/internal/controller/controller.go#L303-L316) and the request is never requeued.

**Comment by tobernguyen** [comment]
> @tobernguyen status field changes are monitored by the operator, if e.g. a Pod goes from a running to a failing state, that's reflected in the status and is likely of interest to the operator. Obviously that's got some bad implications with HPA, so I could totally see adding a filter that specifically discards events where it's only the expected and noisy fields that are changing. In the meantime, you can use the `blacklist` field in your `watches.yaml` to avoid setting a watch on HPA resources (https://sdk.operatorframework.io/docs/building-operators/ansible/reference/watches/).
> 
> Would look like this:
> 
> ```yaml
> - version: v1alpha1
>   group: X (redacted)
>   kind: Y (redacted)
>   role: X (redacted)
>   manageStatus: False
>   snakeCaseParameters: False
>   watchDependentResources: True
>   watchClusterScopedResources: True
>   reconcilePeriod: "0s"
>   blacklist:
>   - group: autoscaling
>     version: v1
>     kind: HorizontalPodAutoscaler
> ```
> 
> * Note, the version for HPA may differ based on your cluster version. It's v1 in latest kube I believe.

That's neat. I didn't realize we have blacklist in watch file. I have tried it and it worked. The reconciliation is no longer being triggered after an HPA change. So I believe the operator is working as expected now and I'm good with closing this issue. Thanks for the support guys.

By the way, we are using autoscaling v2beta2 so here is the setting:

```
  ....
  reconcilePeriod: "0s"
  blacklist:
    - group: autoscaling
      version: v2beta2
      kind: HorizontalPodAutoscaler
```
