### ISSUE TITLE
Fail to find compatible kubebuilder-tools when run tests in makefile in my arm64 machine

### ISSUE THREAD

**Issue by Xiaoyang-Gu** [operator-framework/operator-sdk#4467]
#### Compatible error?

I made Quickstart for Go-based Operators to build a new operator on my arm64 machine.  After I init my operator and `Build and push the operator image`. I found I cannot fetch compatible kubebuilder-tools and get the error like the picture below.
<img width="792" alt="1" src="https://user-images.githubusercontent.com/41043187/106694422-806d7180-6613-11eb-9edc-4b7ff1e6fb58.png">
I investigated the error. And I  found when I run makefile I need to download the `kubebuilder-tools-1.19.2-linux-arm64.tar.gz` from [dowmurl](https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-1.19.2-linux-arm64.tar.gz) . But I only find amd64.tar.gz files. No `kubebuilder-tools-1.19.2-linux-arm64.tar.gz` to download.

#### What did you expect to see?
I need to find `kubebuilder-tools-1.19.2-linux-arm64.tar.gz` for my machine. 
Or I just want to know whether the new version of operator-SDK is compatible for arm64.

#### Environment

<img width="803" alt="2" src="https://user-images.githubusercontent.com/41043187/106695723-2621e000-6616-11eb-8012-3d1f6ddfb448.png">

**Comment by estroz** [comment]
For some reason I assumed this was the case, but right now only [amd64 for linux and darwin](https://github.com/kubernetes-sigs/kubebuilder/tree/tools-releases#how-this-workshow-to-update) is supported in kubebuilder. There was a previous [issue](https://github.com/kubernetes-sigs/kubebuilder/issues/966) that discussed releasing control plane binaries for other arches, but got closed. I'll re-open that issue.

**Comment by Xiaoyang-Gu** [comment]
@estroz Thanks for your help. Can I build an arm64 envtest package for further test job by finding control plane binary files(etcd, kube-apiserver and kubectl)？What do I need to pay attention?

**Comment by estroz** [comment]
PR that fixes this: https://github.com/kubernetes-sigs/kubebuilder/pull/1992

**Comment by estroz** [comment]
arm64 (and ppc64le) tarballs are present remotely!
