### ISSUE TITLE
Operator's Service account placement in versions 1.3.0

### ISSUE THREAD

**Issue by Avni-Sharma** [operator-framework/operator-sdk#4468]
In versions 0.16.0 and 0.17.0 I had observed that the deploy/ folder had roles, rolebindings, crds, deployment and service account. After migrating to a new version 1.3.0 I can find the crds, roles and rolebindings placed at various folders but however, I am not able to locate the operator's service account. 

For making a single release yaml for our operator, we initially used to curate everything present under the deploy/ folder under a single yaml file for a single file installation of the operator. 

Currently, I am trying to extract the deployment, roles and crds from the already present bundle image's csv and other data under manifests/. However, the service account resource yaml does not exist. Is there any way wherein I can achieve to create a single release artifact yaml, for quick kubectl create -f installation.yaml of the operator in vanilla k8s

**Comment by estroz** [comment]
The default service account is used for a particular namespace by default. Creating and using a separate service account involves a few steps:
1. Create `service_account.yaml` and put it in `config/rbac/`
2. Add a `service_account.yaml` to the list of `resources` in `config/rbac/kustomization.yaml`
3. Change all `ServiceAccount`-type `subjects[].name` to the service account name in all `RoleBinding`/`ClusterRoleBinding` manifests in `config/rbac`
4. Set the pod template spec's [`serviceAccountName`](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server) to the service account name in your `config/manager/manager.yaml`
5. Rerun `make bundle`

This needs to be documented for all operators.

/kind documentation

**Comment by estroz** [comment]
This is fixed by https://github.com/kubernetes-sigs/kubebuilder/pull/2070 upstream.
