### ISSUE TITLE
Handling Delete and Update Events?

### ISSUE THREAD

**Issue by cnuss** [operator-framework/operator-sdk#447]
Greetings!

I've been digging through the SDK code and have seen `informer` code to handle Update and Delete events, but I haven't seen any documentation or code samples on how to handle an event such as `kubectl delete -f deploy/cr.yaml`. 

Could someone offer some guidance?

Cheers, and thanks in advance!

**Comment by CSdread** [comment]
@cnuss also if you have resources that your CRD owns that you need to do shutdown work on you can use finalizers to stop the cascading delete and do the processes you have to do. You can also use finalizers to catch the delete on the CRD object itself

**Comment by cnuss** [comment]
thank you @lilic! I will give that a shot, and thank you for a link to the docs too.

thank you @csdread.  is there example usage of finalizers or docs I could reference?  that sounds like a very handy feature

**Comment by LiliC** [comment]
You are welcome @cnuss!

I would suggest leaving the issue open until we add some more docs on this.

**Comment by cnuss** [comment]
@LiliC hello again!

I think I might use a little hand holding through this.  I'll PR some docs once I figure this out as payment :).

I'm using operator-sdk v0.0.7.  I created a new operator with the `operator new` command so we easily look at the same code...

I'm assuming I would receive `kubectl delete` commands in my `Handler` (`pkg/stub/handler.go`), correct?: 

```
func (h *Handler) Handle(ctx context.Context, event sdk.Event) error {
	switch o := event.Object.(type) {
	case *v1alpha1.Database:
		err := sdk.Create(newbusyBoxPod(o))
		if err != nil && !errors.IsAlreadyExists(err) {
			logrus.Errorf("failed to create busybox pod : %v", err)
			// increment error metric
			h.metrics.operatorErrors.Inc()
			return err
		}
	}
	return nil
}
```

What would I need to add or change in this function to receive a `kubectl delete -f deploy/cr.yaml`?  I found `sdk.Delete(...)` but I'm hoping that I can watch something so I could call a theoretical `deletebusyBoxPod(o)` function.

Thanks!

**Comment by LiliC** [comment]
@cnuss No problem! So if you want to act upon on a deleted resource you can use the `event` you get and do something along the lines of:

```go
func (h *Handler) Handle(ctx context.Context, event sdk.Event) error {
  switch o := event.Object.(type) {
  // replace `v1alpha1.Memcached` with the type of object you want to react on when it gets deleted
  case *v1alpha1.Memcached:
    if event.Deleted {
      // the object `v1alpha1.Memcached` was deleted
      // handle the delete event here
    }
    return nil
  }
}
```

The `sdk.Delete(...)` deletes a resource you pass it, it's a helper function.

As for finalizers here is some kubernetes docs on that https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#finalizers

Hope that helps! We are always happy to have docs contributed, currently the operator-sdk is going through a change and the above might be out of date soon for next release, so maybe we can wait on the docs for a week or so.

**Comment by cnuss** [comment]
Using `event.Deleted` will do wonderfully, thanks @LiliC!

**Comment by estroz** [comment]
@cnuss any more questions regarding resource deletion, or can I close this issue? Note that we've updated our docs a bunch recently, such as our [user guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md). If not, I can help answer further questions. Thanks!

**Comment by cnuss** [comment]
Thanks @estroz ... I'll close this issue!
