### ISSUE TITLE
Is there anyway to know the user id that created the CR

### ISSUE THREAD

**Issue by maleck13** [operator-framework/operator-sdk#448]
It could be useful to know the user that created the CR. The reason for this is so that the operator could apply a rolebinding to the user. For example if the operator created a new namespace for the service it was provisioning and wanted to allow the user view access on the namespace.

Is there anyway to know this currently?

**Comment by maleck13** [comment]
Would there by scope here with custom resources to have the API server annotate the resource with the user id. Perhaps something better off asked in k8s

**Comment by shawn-hurley** [comment]
I think that this is something for a [mutating admissions webhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook)

I think that this will allow you to get the user info for a request.

**Comment by maleck13** [comment]
Thanks
