### ISSUE TITLE
How to install operator using OLM in kubernetes/openshift cluster

### ISSUE THREAD

**Issue by SAbdulRahuman** [operator-framework/operator-sdk#4481]
Hi,
I'm using operator-sdk version 1.3 and developed operator for microservice deployment and lifecycle management. 
We have created operator and able to build using `make docker-build docker-push` and also able to deploy to cluster using `make deploy ...`. Also build operator bundle using `make bundle` 

My question is how to deploy built operator image and bundle using OLM in kubernetes / openshift cluster ?. Could you share steps to install operator using OLM ?.

## Type of question

 How to implement a specific feature 
 General operator-related help 

## Question
  How to install operator using OLM in Kubernetes/openshift cluster ?

#### What did you do?
Create operator and build and pushed to cluster. Able to deploy using `make deploy`.

#### What did you expect to see?

Need to deliver operator to users/clients, So Need to install operator to User's  kubernetes cluster using OLM.
Steps to install operator using OLM

#### What did you see instead? Under which circumstances?

Now, I'm able to deploy in my test cluster using `make deploy`

#### Environment

**Operator type:**

 /language go 

**Kubernetes cluster type:**
Vannila Kubernetes and Openshift

`$ operator-sdk version`

operator-sdk version: "v1.3.0", commit: "1abf57985b43bf6a59dcd18147b3c574fa57d3f6", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.15.6 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by varshaprasad96** [comment]
@SAbdulRahuman if you have built a bundle for the operator, you can use the `run bundle` command. Here is some documentation on testing operator deployment with OLM - https://sdk.operatorframework.io/docs/olm-integration/testing-deployment/.

**Comment by SAbdulRahuman** [comment]
@varshaprasad96 Thanks for swift response and the link (following the link to deploy bundle).  :+1:

**Comment by estroz** [comment]
For an in-depth discussion of production OLM usage, see the OLM docs: https://olm.operatorframework.io/docs/tasks/.
