### ISSUE TITLE
Updating existing CRs container images while updating the operator itself 

### ISSUE THREAD

**Issue by beatrausch** [operator-framework/operator-sdk#4492]
## Type of question
How to implement a specific feature
Best practices 

## Question
Hi, what’s the best way to update Custom Resources container images owned by the operator while updating the operator itself. Short example

- Lets says the memcache operator in version 1.0.1 creates deployments with the memcache image memcache:1.3.0
- With the update to the memcache operator version 1.1.0. The operator uses the memcache image memcache:1.6.9
- How to update already created CRs to the new container image memcache:1.6.9?

My first thought was to simply requeue every created resource with a certain delay to be able to check the container image after a operator update. 

#### What did you expect to see?

I would like to know if there is any best practices or even a better way to do so. 
**Operator type:**

/language go

**Kubernetes cluster type:**

Azure kubernetes 

`$ go version` (if language is Go) 1.15.6
go version go1.15.6 linux/amd64

**Comment by estroz** [comment]
Assuming memcached v1.3.0 and v1.6.9 are compatible with each other, you can check if a CR's deployment has the old image, and if so [patch](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client#Writer) it with the updated image. You shouldn't need to update the Memcached CRD in this case.

If those versions are not compatible with each other or you are changing the CRD in a breaking way, then you should increment the [CRD version](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/), ex. from v1alpha1 to v1alpha2, write a [conversion webhook](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-conversion), and rewrite your controller logic to handle v1alpha2.

**Comment by beatrausch** [comment]
> Assuming memcached v1.3.0 and v1.6.9 are compatible with each other, you can check if a CR's deployment has the old image, and if so [patch](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client#Writer) it with the updated image. You shouldn't need to update the Memcached CRD in this case.

Does it mean that the controller will observe all already existing CRs and its owned resources in its Reconcile loop after a new/redeployment of the operator. If not I am not aware of how to patch the container image, as I won't see it in the Reconcile loop.
 
> If those versions are not compatible with each other or you are changing the CRD in a breaking way, then you should increment the [CRD version](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/), ex. from v1alpha1 to v1alpha2, write a [conversion webhook](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-conversion), and rewrite your controller logic to handle v1alpha2.

Thanks for this additional information. Until now I was not aware of CRD conversions. When will a conversion be triggered for a CRD?

**Comment by estroz** [comment]
>Does it mean that the controller will observe all already existing CRs and its owned resources in its Reconcile loop after a new/redeployment of the operator

Yes. When you redeploy your operator, the same group-kind watch is established.

>When will a conversion be triggered for a CRD?

From the [docs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#writing-reading-and-updating-versioned-customresourcedefinition-objects):

>If you update an existing object, it is rewritten at the version that is currently the storage version. This is the only way that objects can change from one version to another.

**Comment by beatrausch** [comment]
> > Does it mean that the controller will observe all already existing CRs and its owned resources in its Reconcile loop after a new/redeployment of the operator
> 
> Yes. When you redeploy your operator, the same group-kind watch is established.

Great :smiley:  
I'll check it on Monday.

**Comment by beatrausch** [comment]
```
2021-02-08T09:01:50.424+0100    INFO    controllers.Cache       Handeld Cache: Cache    {"cache": "playground/sample-cache"}
2021-02-08T09:01:50.424+0100    DEBUG   controller-runtime.controller   Successfully Reconciled {"controller": "cache", "request": "playground/sample-cache"}
2021-02-08T09:01:50.424+0100    INFO    controllers.Cache       Handeld Cache: Cache    {"cache": "playground/inmemorycache-sample"}
2021-02-08T09:01:50.424+0100    DEBUG   controller-runtime.controller   Successfully Reconciled {"controller": "cache", "request": "playground/inmemorycache-sample"}
2021-02-08T09:01:50.424+0100    INFO    controllers.Cache       Handeld Cache: Cache    {"cache": "playground/sample-cache"}
2021-02-08T09:01:50.424+0100    DEBUG   controller-runtime.controller   Successfully Reconciled {"controller": "cache", "request": "playground/sample-cache"}
```

I could observe what you said. Each CR that already exists will be observed by the reconcile loop after a restart of the controller. 
But I am a bit wondered why the sample-cache is observed two times after the restart.  There was no change on the CR. Do you have any ideas?
