### ISSUE TITLE
CSV Field Markers are not collected if they are in another go file

### ISSUE THREAD

**Issue by IBMRob** [operator-framework/operator-sdk#4499]
#### What did you do?

In my operator project, we have a number of common structs that are used across multiple CRDs. These are stored in a file common_types.go. I've annotated some of its fields with operator-sdk CSV markers, like:

```yaml
type LicenseList struct {
   // Accept Terms and Conditions 
   // +operator-sdk:csv:customresourcedefinitions:type=spec,order=3
   // +operator-sdk:csv:customresourcedefinitions:type=spec,xDescriptors={"urn:alm:descriptor:com.tectonic.ui:booleanSwitch","urn:alm:descriptor:com.tectonic.ui:fieldGroup:License"}
   Accept bool `json:"accept"`
}
```

Then I ran make bundle to generate the bundle manifests.

There was an issue for this previously - https://github.com/operator-framework/operator-sdk/issues/3744 but this was meant to be fixed in v1.3.1 but I have tested both v1.3.1 and 1.4.0 and both are still showing the same issue. 

#### What did you expect to see?

The generated CSV would have specDescriptors for the license fields

#### What did you see instead? Under which circumstances?

The generated CSV did not have any specDescriptors for fields in the shared go file. 

#### Environment

**Operator type:**

language go

**Kubernetes cluster type:**

`$ operator-sdk version`
```
operator-sdk version: "v1.4.0", commit: "67f9c8b888887d18cd38bb6fd85cf3cf5b94fd99", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "darwin", GOARCH: "amd64"
operator-sdk version: "v1.3.1", commit: "af8bc8ddbc81bf0012705fbff7124ed1d09a757e", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "darwin", GOARCH: "amd64"
```
this is also occurring in earlier versions too. This used to work in 0.17.0

`$ go version` (if language is Go)
```
go version go1.15.8 darwin/amd64
```

`$ kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T16:06:08Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by estroz** [comment]
@IBMRob thanks for bringing this up, I've confirmed that this bug still exists. There were unit tests written that should have covered this case but looking over them I don't think that they actually cover it. I'm re-opening #3744 and closing this as a duplicate.
