### ISSUE TITLE
missing GetAnnotations method

### ISSUE THREAD

**Issue by cuttingedge1109** [operator-framework/operator-sdk#4500]
I am developing an operator using operator-sdk.
When execute `go vet`, I got such errors.
go version:15.5
operator-sdk version: 1.18.8
k8s.io/client-go: v0.20.0
sigs.k8s.io/controller-runtime: v0.7.0
k8s.io/api v0.20.0
k8s.io/apimachinery v0.20.0

```
pkg/utils/k8s/k8s_utils.go:25:38: cannot use obj (type runtime.Object) as type client.Object in argument to controllerutil.CreateOrUpdate:
	runtime.Object does not implement client.Object (missing GetAnnotations method)
pkg/utils/k8s/k8s_utils.go:49:17: cannot use obj (type runtime.Object) as type client.Object in argument to c.Delete:
	runtime.Object does not implement client.Object (missing GetAnnotations method)
Makefile:66: recipe for target 'vet' failed
make: *** [vet] Error 2

```

**Comment by estroz** [comment]
@cuttingedge1109 these are go dependency issues, and outside of what operator-sdk supports (you're using an old operator-sdk version with a newer version of controller-runtime, which is incompatible with the k8s deps you're using). I recommend [upgrading](https://sdk.operatorframework.io/docs/upgrading-sdk-version/) your operator-sdk version.
