### ISSUE TITLE
Upgrading from kubebuilder v2 layout to v3

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [operator-framework/operator-sdk#4501]
I have an operator up and running against `operator-sdk v1.2.0` and `kubebuilder layout v2`. I want to update it to the latest operator-sdk version i.e. v1.4.0 and go.kubebuilder.io/v3. This is a requirement since I want to use the latest api-versions for CRD and certmanager, webhook CRs.

How can one achieve this ?

**Comment by camilamacedo86** [comment]
c/c @jmrodri @estroz

**Comment by estroz** [comment]
@ahmedwaleedmalik the v2 to v3 PR is in-flight upstream (https://github.com/kubernetes-sigs/kubebuilder/pull/1916), and there is an operator-sdk v1.2.0 -> v1.3.0 -> v1.4.0 [set of migration guides](https://sdk.operatorframework.io/docs/upgrading-sdk-version/). The v1.3.0 migration guide will be updated with the upstream migration doc as soon as it is merged.

/kind documentation
/priority important-soon

**Comment by ahmedwaleedmalik** [comment]
Thank you @estroz and @camilamacedo86 for the response. Let's keep this issue open for tracking. I'll keep an eye on the relevant PRs as well.

**Comment by estroz** [comment]
@ahmedwaleedmalik the v1.3.0 migration guide link was updated in v1.3.2. Thanks for bringing this up.
