### ISSUE TITLE
Support for additional fields for bundle generation when using --input-dir and --kustomize-dir

### ISSUE THREAD

**Issue by kyguy** [operator-framework/operator-sdk#4503]
#### Describe the problem you need a feature to resolve.
Using the `operator-sdk generate bundle` command, we can generate bundles based on existing bundles using `--input-dir <INPUT_DIR>` and/or kustomize files using `--kustomize-dir <KUSTOMIZE_DIR>`. The generator will create a new bundle based on these files, copying over the supported CSV fields [1] from the provided bundle or kustomize base file.

```
operator-sdk generate bundle --metadata --manifests  --kustomize-dir <KUSTOMIZE_DIR> --input-dir <INPUT_DIR> --crds-dir <CRD_DIR>  --deploy-dir <DEPLOY_DIR> 
```
The problem is that the generator will not copy over unsupported CSV fields(e.g. fields not labelled as (_user_) here [1]), leaving them blank in the newly generated bundle CSV file.

#### Describe the solution you'd like.
Could we add support for the following csv fields?
- `metadata.annotations.alm-examples`
- `spec.install.spec.permissions`
- `spec.relatedImages`
- `spec.minKubeVersion`

[1] https://sdk.operatorframework.io/docs/olm-integration/generation/#csv-fields

**Comment by estroz** [comment]
Before I suggest some solutions, can you answer a few questions for me:
1. I've seen this use case a few times. Can you tell me why you're using `generate bundle` directly and not `make bundle` which calls that command indirectly?
2. `spec.relatedImages` isn't a field in the [CSV spec](https://github.com/operator-framework/api/blob/master/pkg/operators/v1alpha1/clusterserviceversion_types.go#L268), so it definitely won't be copied. Is this field from an older spec version perhaps?

**Comment by kyguy** [comment]
@estroz Thanks for looking into this and sorry for the delay, to answer your questions from before:

> Can you tell me why you're using generate bundle directly and not make bundle which calls that command indirectly?

I misunderstood that we could use the `operator-sdk` tool this way, I stumbled upon these docs [1] and thought we may be able to use this method for our specific use case [1].

> spec.relatedImages isn't a field in the CSV spec, so it definitely won't be copied. Is this field from an older spec version perhaps?

Yes, you are right, `spec.relatedImages`is not part of the CSV spec. We add this a company specific field we add to the CSV files at Red Hat but and I misunderstood it to be part of the upstream spec. Sorry for the misunderstanding!

**For more context on our use case**:
We were hoping to automate the process of generating OLM bundles for our operator project [2] using the `operator-sdk` tool. [2] We heard that the `operator-sdk` tool could generate new bundles from existing bundles and CRD files. This would really help us since our operator is written in Java we cannot use the `operator-sdk` as it was originally designed. Since our project predates the operator-framework, we had to create our own CRD generator which our project is now dependent on.  We hoping to use the `operator-sdk` tool for using the CRDs created from our CRD generator to create new bundles so we don't have to write a bundle generator ourselves.


[1] https://sdk.operatorframework.io/docs/cli/operator-sdk_generate_bundle/
[2] https://github.com/strimzi/strimzi-kafka-operator

**Comment by estroz** [comment]
If you have a base CSV containing your up-to-date `.spec.customresourcedefinitions` along with other metadata, and either a directory containing all of your manifests or the [ability](https://github.com/operator-framework/operator-sdk/blob/v1.5.0/testdata/go/v3/memcached-operator/Makefile#L144) to `kustomize build` them, then you can use the command to do what you want by putting the base in `<some-dir>/bases/<package-name>.clusterserviceversion.yaml` ([example](https://github.com/operator-framework/operator-sdk/tree/master/testdata/go/v3/memcached-operator/config/manifests)):

```sh
# With a directory "prod" and <some-dir> as "manifests"
operator-sdk generate bundle --input-dir=./prod --kustomize-dir=./manifests --version=1.2.3
# With a `kustomize build`-able dir "config" and <some-dir> as "manifests"
kustomize build config/ | operator-sdk generate bundle --kustomize-dir=./manifests --version=1.2.3
```

I hope that helps.

**Comment by kyguy** [comment]
Thanks for the response @estroz especially after I was so late. I followed the method provided:
```
# With a directory "prod" and <some-dir> as "manifests"
operator-sdk generate bundle --input-dir=./prod --kustomize-dir=./manifests --version=1.2.3
```
and was able to generate a bundle using an existing CSV as a base. Everything copies over perfectly into the generated CSV file except the following fields:
- `metadata.annotations.alm-examples`
- `spec.install.spec.permissions`

From what I understand these fields are not supported since they are not labelled as (user) here [1]. Is there any specific reason these fields are left out during the generation process? Could I add an RFE for these to fields to be supported?

[1] https://sdk.operatorframework.io/docs/olm-integration/generation/#csv-fields
