### ISSUE TITLE
Setup event based reconciliation based on changes of non-dependent resources

### ISSUE THREAD

**Issue by zoopp** [operator-framework/operator-sdk#4505]
## Type of question

How to implement a specific feature

## Is it possible to setup event based reconciliation of custom resources based on changes of non-dependent resources?

I have two types of custom resources (App1 and App2) which I use to manage instances of two different types of apps. Many instances of App2 can communicate with an instance of App1's Service.

I want to have a way to control to which App1 instance a group of App2 instances will communicate with. Moreover, I want to be able to change the App1 instance to which a group is associated without having to update the spec of App1s.

With this in mind I came up with the following:

![example](https://user-images.githubusercontent.com/1645023/107498729-d48cce80-6b9c-11eb-9685-cf080c6e57f4.png)

#### What did you do?

I created APIs for each type of CRD (App1, AppBinding, App2) and wrote the ansible playbook and role to handle them.

- The playbook and role for App1 handles deployments for the App1 instances.
- The playbook and role for App2 looks up AppBinding resources based on the binding selector and if present uses the information present in its status to setup the App2 instance.
- The playbook and role for AppBinding looks up App1 resources based on the app selector and populates its status field appropriately.

I want to be able to reconcile the whole chain. Specifically:

- If an App1 changes (looking at labels here), I want to reconcile AppBindings.
- If an AppBinding changes (looking at labels and status), I want to reconcile App2s.

#### What did you expect to see?

A way to implement this type of event based triggering of reconciliation based on non-dependent resources.

#### What did you see instead? Under which circumstances?

The obvious way that I see for handling the whole the reconciliation chain would be to rely on timer based reconciliation for each resource type (i.e. reconcile every couple of seconds). However, I'm afraid that it will become problematic because:

- I expect to deal with a lot of instances.
- If reconciliation isn't done in the correct order then some things will break until reconciliation is done again (e.g. if App2s are reconciled before AppBindings then they might use the wrong App1 instance).

The other alternative that I see would be to invert the way the change is propagated. E.g.:

- When an App1 instance is updated/created, find AppBindings that need updating and update them.
- When an AppBinding is updated, find App2s that need updating and update them.

Both solutions don't feel right, so I'm looking to get for your opinion on how to best handle this usecase.

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

GKE.

```
$ operator-sdk version
operator-sdk version: "v1.3.0", commit: "1abf57985b43bf6a59dcd18147b3c574fa57d3f6", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.12-gke.1205", GitCommit:"160736941f00e54acb1c0a4647166b6f6eb211d9", GitTreeState:"clean", BuildDate:"2021-01-05T23:44:13Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by zoopp** [comment]
I owe an update on the issue so here we go: In the end I did not find a good way to deal with this using the ansible runner and ended up experimenting with other frameworks. 

Being more familiar with python, I ended up implementing things using [kopf](https://github.com/nolar/kopf) so the original problem no longer applies to me. I can answer additional questions if there are any otherwise I'm okay with closing the issue as is.

**Comment by nikhil-thomas** [comment]
Great 👍 

So how does we connect events on resources not managed by an operator to one of our CRD (primary resource).
It would be great, if you could share a link to the code. so that I can better understand the flow.


In [tektoncd/operator](https://github.com/tektoncd/operator), (built with [knative/pkg](https://github.com/knative/pkg#knative-common-packages)) we had to deal with something similar. We wanted one of our Reconcilers to be triggered, on events on namespaces. The namespaces were not created by operator, so there was no owner reference or label to extract the keyRef of the primary resource.

We ended making a hack, where we set the name of a CR we want in the namespace event, before it gets enqueued.
https://github.com/tektoncd/operator/blob/8734ca2ea98e2220127b3159b13e0521dc943ab5/pkg/reconciler/kubernetes/tektonconfig/controller.go#L86 . 

This particular, CRD (primary resource) is a "singleton" CRD so we know the `name`.

**Comment by zoopp** [comment]
Unfortunately I can't share the code as it lives in a private repository outside of github but I can happily describe what I did and hopefully that clarifies it.

I realized that in my case it made sense to have all custom resources collectively managed by a single (kopf) operator. Thus, I ended up adapting the 'alternative' solution that I was talking about in my first message:

> When an App1 instance is updated/created/deleted, find AppBindings that need updating and update them.
> When an AppBinding is updated/created/deleted, find App2s that need updating and update them.

Instead of actually updating the affected objects directly, I trigger the update handler (reconciler) by programatically adding a temporary annotation to each resource that needs updating. This works pretty well and to make the lookups efficient, I make use of [in-memory indexing](https://kopf.readthedocs.io/en/latest/indexing/) over the labels and match-labels in order to figure out what objects are affected.

On a first glance it does not look like your use-case has a lot of similarity to mine, nonetheless, I hope it helps.

**Comment by nikhil-thomas** [comment]
Thanks :heart: 
> I trigger the update handler (reconciler) by programatically adding a temporary annotation to each resource that needs updating.

Interesting, this would work in our situation too.
Less hacky and more clear for a code reader. :technologist: :+1:
