### ISSUE TITLE
OLM Integration Bundle Quickstart is not quick

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4527]
## Bug Report

OLM integration quick start is not quick and it is not following the approach/standard defined for that in the docs.  See: https://sdk.operatorframework.io/docs/olm-integration/quickstart-bundle/

#### What did you do?

Try to follow the OLM integration guidelines. 

#### What did you expect to see?

- A quick start for SDK projects and for Non-SDK projects (A section with 2 docs)

```
├── OLM Integration
    ├── QuickStart
           ├── For SKD projects
           ├── For Non-SKD projects
```

- The sequence be how to build the bundle and then how to test it with OLM
- The OLM Quick-Start following the same approach/standard adopted for the Golang/Ansible/Helm QuickStarts with the goal to be very direct and just provide the commands for users copy and past and check how its work. 

IMO, new users do not know what means OLM. So, we also need to clarify on the top/header that by integration projects with OLM they can distribute them via OperatorHub.io and/or OCP catalogue.  

#### What did you see instead? Under which circumstances?

- It has not a guide/quick start for a Non-SDK project
- The sequence is confusing. 
- The information is too verbose and are not direct commands to just copy and past

PS.: The content of this document shows that would fit better in a tutorial instead.

**Comment by estroz** [comment]
Duplicate, see #4241

/triage duplicate
/close
