### ISSUE TITLE
Where to place setup code in go operator?

### ISSUE THREAD

**Issue by asaff1** [operator-framework/operator-sdk#4550]
## Type of question

 **Best practices** 
 **How to implement a specific feature** 

#### What did you do?
I'm trying to implement a setup code that reads existing CRs from the cluster, and update their statuses if needed.
I don't want to run the setup code in each `Reconcile()` call. 

I've tried to place my code in the `SetupWithManager()` call at the controller file:

```
func (r *AppReconciler) SetupWithManager(mgr ctrl.Manager) error {
	r.Sync() // <-- tried to add here

	return ctrl.NewControllerManagedBy(mgr).
		For(&servicesv1.App{}).
		Owns(&batchv1.Job{}).
		Complete(r)
}
```

The `Sync()` function calls `r.List()` but gets the error: **the cache is not started, can not read objects**
Is it possible to get the initial list of objects that the manager gets at the beginning? Or what is the best practice here?

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**
kind cluster

`$ operator-sdk version`

operator-sdk version: "v1.3.0", commit: "1abf57985b43bf6a59dcd18147b3c574fa57d3f6", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go1.15.2

**Comment by estroz** [comment]
@asaff1 if you read the [`manager.Manager` docs](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Manager), you'll see the `Add()` method, which will inject a [`Runnable`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Runnable) into the Manager that is started at runtime. The reason you're seeing that error is because `Manager.Start()` hasn't been called yet, so the client/cache hasn't been initialized yet. If that answers your question, feel free to close this issue.

**Comment by edubois10** [comment]
Hi Estroz, I am not sure then were to place setup code. I tried to add some code in `main.go` after the `Manager.start()` have been called but I have the feeling that any code after `Manager.Star()` is not run. I am pretty new to golang and I am not yet clear how an operator and controllers are started.
setupLog.Info("starting manager")

main.go
```
if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {
		setupLog.Error(err, "problem running manager")
		os.Exit(1)
	}

	// Getting vsphere configuration

	//client := mgr.GetClient()
	setupLog.Info("Getting VSphere credentials")
	vsphereConfig, err := controllers.GetVSphereConfFromSecrets(reconciler.Client)
	if err != nil {
		setupLog.Error(err, "Unable to fetch VSphere configuration.")
		os.Exit(1)
	}
```

**Comment by Lxrdknows77** [comment]
> Hi Estroz, I am not sure then were to place setup code. I tried to add some code in `main.go` after the `Manager.start()` have been called but I have the feeling that any code after `Manager.Star()` is not run. I am pretty new to golang and I am not yet clear how an operator and controllers are started.
> 
> Here follows what I added after mgr.Start, but nothing is called. main.go
> 
> ```
> setupLog.Info("starting manager")
> if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {
> 		setupLog.Error(err, "problem running manager")
> 		os.Exit(1)
> 	}
> 
> 	setupLog.Info("Getting VSphere credentials")
> 	vsphereConfig, err := controllers.GetVSphereConfFromSecrets(reconciler.Client)
> 	if err != nil {
> 		setupLog.Error(err, "Unable to fetch VSphere configuration.")
> 		os.Exit(1)
> 	}
> ```

Did you solve it?

**Comment by xagent003** [comment]
Looking for a solution here too. I need to create some dependencies and deployments, as well as get/list some resources, before I init my reconcilers and start the manager. Is there a way to start the cache before starting the manager and controllers?

**Comment by Tharsanan1** [comment]
Hi, Can you give a code example on how to create a separate client.Client? I am trying to retrieve all the CR object of a particular CRD before starting the reconciler.

**Comment by Lxrdknows77** [comment]
> Hi, Can you give a code example on how to create a separate client.Client? I am trying to retrieve all the CR object of a particular CRD before starting the reconciler.

`
cfg := ctrl.GetConfigOrDie()
	client, err := client.New(cfg, client.Options{})
	if err != nil {
		// depends how you proceed with errors
		os.Exit(1)
	}
`
