### ISSUE TITLE
Update minimum Kubernetes cluster versions.

### ISSUE THREAD

**Issue by jmrodri** [operator-framework/operator-sdk#4560]
### What is the URL of the document?

https://sdk.operatorframework.io/docs/building-operators/golang/installation/#additional-prerequisites

### Which section(s) is the issue in?

Additional prerequisites

### What needs fixing?

Update the minimum Kubernetes cluster requirements. At a minimum verify what we have there is still valid.

**Comment by varshaprasad96** [comment]
Would this be covered in issue - https://github.com/operator-framework/operator-sdk/issues/4385 ?

**Comment by estroz** [comment]
Yes, these prereqs need to point to the matrix created in #4385.

**Comment by estroz** [comment]
Closed by #4574
