### ISSUE TITLE
operator-sdk bundle validate ./bundle allow --output=json as scorecard

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4562]
#### Describe the problem you need a feature to resolve.

I'd like to run `operator-sdk bundle validate ./bundle --output=json` such as I can run `operator-sdk scorecard bundle --output=json --selector=suite=basic` so that, I can aggregate the results

#### Describe the solution you'd like.

I'd like to see both features using the same lib/format and options to output the results

**Comment by estroz** [comment]
The `--output=json-alpha1` option exists but is hidden and can be made visible.
