### ISSUE TITLE
helm: unable to find one of 'kustomization.yaml',

### ISSUE THREAD

**Issue by jmrodri** [operator-framework/operator-sdk#4575]
#### What did you do?

Created a new helm operator project using a helm chart.

```
$ mkdir rabbit-operator
$ cd rabbit-operator
$ operator-sdk init --plugins helm --helm-chart /tmp/rabbitmq-8.9.2.tgz 
$ export OPERATOR_IMG="quay.io/jesusr/rabbit-operator:v0.0.1"   
$ make docker-build docker-push IMG=$OPERATOR_IMG
$ make bundle IMG=$OPERATOR_IMG
operator-sdk generate kustomize manifests -q

Display name for the operator (required): 
> rabbit-operator

Description for the operator (required): 
> rabbit-operator

Provider's name for the operator (required): 
> rabbit-operator

Any relevant URL for the provider name (optional): 
> 

Comma-separated list of keywords for your operator (required): 
> rabbit,operator

Comma-separated list of maintainers and their emails (e.g. 'name1:email1, name2:email2') (required): 
> jesusr:jmrodri@example.com
cd config/manager && /home/devel/jesusr/dev/bin/kustomize edit set image controller=quay.io/jesusr/rabbit-operator:v0.0.1
/home/devel/jesusr/dev/bin/kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version 0.0.1  
Error: accumulating resources: couldn't make target for path '/home/devel/jesusr/dev/rabbit-operator/config/samples': unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/home/devel/jesusr/dev/rabbit-operator/config/samples'
```

#### What did you expect to see?

No error about missing kustomization.yaml file

#### What did you see instead? Under which circumstances?

```
/home/devel/jesusr/dev/bin/kustomize build config/manifests
Error: accumulating resources: couldn't make target for path '/home/devel/jesusr/dev/rabbit-operator/config/samples': unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/home/devel/jesusr/dev/rabbit-operator/config/samples'
```

#### Environment

**Operator type:**

/language helm

**Kubernetes cluster type:**

`$ operator-sdk version`

```
operator-sdk version: "v1.4.0-24-g34a55dd5", commit: "34a55dd5ff27d9d87f96846eb5d17828d0e7b450", kubernetes version: "v1.19.4", go version: "go1.15.8", GOOS: "linux", GOARCH: "amd64"
```

`$ go version` (if language is Go)

go version go1.15.8 linux/amd64

`$ kubectl version`

#### Additional context

Command continues despite the error.

```
cd config/manager && /home/devel/jesusr/dev/bin/kustomize edit set image controller=quay.io/jesusr/rabbit-operator:v0.0.1
/home/devel/jesusr/dev/bin/kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version 0.0.1  
Error: accumulating resources: couldn't make target for path '/home/devel/jesusr/dev/rabbit-operator/config/samples': unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/home/devel/jesusr/dev/rabbit-operator/config/samples'
INFO[0000] Building annotations.yaml                    
INFO[0000] Writing annotations.yaml in /home/devel/jesusr/dev/rabbit-operator/bundle/metadata 
INFO[0000] Building Dockerfile                          
INFO[0000] Writing bundle.Dockerfile in /home/devel/jesusr/dev/rabbit-operator 
operator-sdk bundle validate ./bundle
INFO[0000] Found annotations file                        bundle-dir=bundle container-tool=docker
INFO[0000] Could not find optional dependencies file     bundle-dir=bundle container-tool=docker
INFO[0000] All validation tests have completed successfully 
```

**Comment by jmrodri** [comment]
Here is the rabbitmq chart used.

[rabbitmq-8.9.2.tar.gz](https://github.com/operator-framework/operator-sdk/files/6032780/rabbitmq-8.9.2.tar.gz)

**Comment by estroz** [comment]
@jmrodri if you generate an API first, this works. This isn't specifically a helm or operator-sdk problem, but an undocumented prerequisite to deploy or bundle your operator (`config/crds` must exist). If you try running `make deploy` in a vanilla kubebuilder project before running `create api` you'll see the same errors but for `config/crds`.

The best way to solve this is adding the `set -o errexit` shellopt equivalent in the Makefile, and document this behavior.

**Comment by camilamacedo86** [comment]
Hi @estroz, 

The init call the create api, so it should be the same as init and then call create api. In this way, IMO it still a bug.

**Comment by Adirio** [comment]
> `$ operator-sdk init --plugins helm --helm-chart /tmp/rabbitmq-8.9.2.tgz`

Aren't you missing the `--group <group> --version <version> --kind <kind>` flags?

**Comment by estroz** [comment]
>The init call the create api, so it should be the same as init and then call create api. In this way, IMO it still a bug

@camilamacedo86 if you set GVK flags as @Adirio suggested, this issue won't pop up.

**Comment by camilamacedo86** [comment]
Hi @estroz, @Adirio 

<img width="691" alt="Screen Shot 2021-02-24 at 20 46 57" src="https://user-images.githubusercontent.com/7708031/109063751-7524d780-76e1-11eb-91b5-99ebed82f3bd.png">

See ^ : https://sdk.operatorframework.io/docs/building-operators/helm/tutorial/

This shows that we have an issue here in the chart code implementation where the group, version, kind has not been set. OR
- We need to validate it and raise the error
- Update the docs properly

**Comment by estroz** [comment]
Ah I see. How are GVK being encoded in `PROJECT` in this case? Seems like `--helm-chart` may cause other bugs if that information isn't being encoded.

**Comment by camilamacedo86** [comment]
Hi @estroz, 

I understand that we create the resource from the chart here: https://github.com/operator-framework/operator-sdk/blob/master/internal/plugins/helm/v1/chartutil/chart.go#L162

However,  if it works when we just create api --helm-chart then, shows that the manifest plugin did not made the init job before to create api.

**Comment by Adirio** [comment]
> Hi @estroz, @Adirio
> 
> <img alt="Screen Shot 2021-02-24 at 20 46 57" width="691" src="https://user-images.githubusercontent.com/7708031/109063751-7524d780-76e1-11eb-91b5-99ebed82f3bd.png">
> 
> See ^ : https://sdk.operatorframework.io/docs/building-operators/helm/tutorial/

I haven't found any evidence of this behavior in the plugins (I have them pretty fresh from the alignment with kb plugin phase 1.5).

**Comment by joelanford** [comment]
I just re-ran @jmrodri's reproducer with the latest master and I'm seeing a correctly scaffolded PROJECT file that aligns with the docs.

```
domain: my.domain
layout: helm.sdk.operatorframework.io/v1
plugins:
  manifests.sdk.operatorframework.io/v2: {}
  scorecard.sdk.operatorframework.io/v2: {}
projectName: rabbit-operator
resources:
- api:
    crdVersion: v1
    namespaced: true
  domain: my.domain
  group: charts
  kind: Rabbitmq
  version: v1alpha1
version: "3"
```

It seems like all that's missing here is the creation of the kustomization.yaml at the right time. I tried with both `init --helm-chart` and `create api --helm-chart` and both resulted in a missing `config/samples/kustomization.yaml`

**Comment by joelanford** [comment]
Looks like this never worked properly. I think the problem is that when the GVK is auto-detected, it is not being persisted in the CreateOptions that are used by the phase 2 plugin to decide whether or not to create a kustomization file.
