### ISSUE TITLE
Nit: Improve output of bundle validate

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4577]
#### Describe the problem you need a feature to resolve.

Small nit change in the bundle validate help command output. The motivation for this issue came up from the comment: https://github.com/openshift/enhancements/pull/661#discussion_r579717587

#### Describe the solution you'd like.

Replace `To validate a bundle with a superset of requirements for operatorhub.io specifically:`
With: `To validate a bundle against operatorhub.io requirements specifically, in addition to the standard bundle validation:`

**Comment by camilamacedo86** [comment]
@bparees  would the above suggestion address your concern?

**Comment by bparees** [comment]
+1, thanks @camilamacedo86
