### ISSUE TITLE
PATH issue with WSL2

### ISSUE THREAD

**Issue by mrethers** [operator-framework/operator-sdk#4579]
#### What did you do?

Running Ubuntu on WSL2

make docker-build

#### What did you expect to see?

The build completes succesfuly

#### What did you see instead? Under which circumstances?

```$ make docker-build docker-push
env: ‘Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_2004.2020.812.0_x64__79rhkp1fndgsc:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program’: No such file or directory```

The error is related to the Windows path with white spaces.

I was able to get passed it by quoting the the PATH variable in the SHELL:

SHELL := env PATH="\"$(PATH)\"" /bin/sh

#### Environment

Windows 10 Pro
WSL2
Ubuntu

**Comment by varshaprasad96** [comment]
@mrethers - Can I know which operator you were building? If its ansible/helm, we just removed the `PATH` variable and instead are looking for binaries directly in $(PWD)/bin

**Comment by varshaprasad96** [comment]
@mrethers you are doing the right thing. However, since there is no official support for windows, I'm closing this issue. Please feel free to reopen this if you have any questions.
