### ISSUE TITLE
Not able to use the variables meta.name and meta.namespace in operator-sdk v1.4.2

### ISSUE THREAD

**Issue by AnilKumarBandi27** [operator-framework/operator-sdk#4589]
Hi,

Earlier, I was using the operator-sdk v0.16.0 and I have updated to v1.14.2. Operator-sdk throwing the errors meta.name and meta.namespace is not defined in the v1.14.2 which was working fine in older versions. 

I have changed the meta.name and meta.namespace to ansible_operator_meta.name and ansible_operator_meta.namespace respectively. the operator has executed all the tasks successfully.

why I am not able to use meta.name and meta.namespace ?

Please let me know, if this causes any issues during the upgrade and rollback of the operator and operand?

**Comment by varshaprasad96** [comment]
@AnilKumarBandi27 These variable names have been renamed from SDK 1.0 release onwards, though their functionality remains the same. Here is the documentation regarding that - https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.0.0/#ansible-operator-meta-variable-renamed-to-ansible_operator_meta

**Comment by varshaprasad96** [comment]
I am closing this issue, as this is documented in the migration guide. Please feel free to reopen if you have any questions.
