### ISSUE TITLE
Query regrading transition of existing workloads on k8s to Operator

### ISSUE THREAD

**Issue by someshnistala** [operator-framework/operator-sdk#4590]
Is there a procedure/option to transition the existing workloads on k8s cluster, deployed using helm charts, to an Helm based operator.

The objective asking this question is to convert the existing deployments into an operator, and manage the life cycle/upgrades of the application and the operator using OLM.

No  references found on the Operator-SDK Documentation on given scenario, and no on-line help on the similar scenarios.

### What is the URL of the document?

Operator-SDK documentation.

### Which section(s) is the issue in?

No relevant information in the Operator-SDK documentation

### What needs fixing?

Providing the references on the brown field upgrade scenarios will be helpful

**Comment by kensipe** [comment]
cc: @joelanford

**Comment by someshnnv** [comment]
@kensipe @joelanford 
Our goal is to migrate the existing helm-chart deployments on k8s to Operator (Helm-chart based).
In the lab env, as a part of Helm-chart to Operator migration process, we are creating the helm Operator from the existing Helm chart, installing the operator image, then bringing-up the application into service by applying the cr.yaml 

With the help of Operator-SDK we can convert the existing helm value.yaml to cr.yaml, would like to know if there is a script/tool available to convert the existing helm value.yaml to cr.yaml in the live environments to facilitate the migration process.
