### ISSUE TITLE
How to create an ImagePullSecret in another namespace from the operator controller. My operator is in another namespace

### ISSUE THREAD

**Issue by anusood** [operator-framework/operator-sdk#4591]
## Type of question

How to implement a specific feature

#### What did you do?

How to create an ImagePullSecret in another namespace from the operator controller. My operator is in another namespace

#### What did you expect to see?

An imagepulllscret in the namespace i specify with the credentials i give in the code(hardcoded for now), 

#### Environment

**Operator type:**

 /language go 

**Kubernetes cluster type:**

OpenShift

`$ operator-sdk version`

v1.0.0

`$ go version` (if language is Go)

go version go1.15 darwin/amd64

`$ kubectl version`

**Comment by kensipe** [comment]
@anusood  The question posted is more a k8s concern than an Operator concern.  According the the k8s docs: https://kubernetes.io/docs/concepts/configuration/secret/#details
secrets can only be referenced by Pods in that same namespace.

you will either need to duplicate the secrets or use another solution to secrets like vault.   

Hope this helps!

**Comment by vishal-yadav** [comment]
Assuming that both secret and the pod consuming the secret are in the same namespace (different from operator), I think **cluster-scoped** operator should be able to create secret in different namespace.
