### ISSUE TITLE
MutatingWebhookConfiguration v1

### ISSUE THREAD

**Issue by BugMaster510945** [operator-framework/operator-sdk#4602]
#### What did you do?

I've created a custom CRD with Mutating Webhook (defaulter) and a simple reconciler which do nothing except applying status and finalizer on object issued from CRD.

#### What did you expect to see?

All works 😃 

#### What did you see instead? Under which circumstances?

When I Add a ressource, defaulter do the job, but adding finalizer fail with 
```
ERROR	controller-runtime.manager.controller.project	Reconciler error	{"reconciler group": "foo", "reconciler kind": "Bar", "name": "test", "namespace": "test", "error": "Internal error occurred: failed calling webhook \"vbar.kb.io\": webhook returned response.patchType but not response.patch"}
```

After a week of headhache, I finally found https://github.com/kubernetes/apiserver/blob/master/pkg/admission/plugin/webhook/request/admissionreview.go#L87 and found root issue (I think).

This error come from a new test introduced in `v1` of admission mutate webhook.
I've force use of `v1beta1` and It works.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

`$ operator-sdk version`
`operator-sdk version: "v1.3.0", commit: "1abf57985b43bf6a59dcd18147b3c574fa57d3f6", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"`

`$ go version`
`go version go1.15.6 linux/amd64`

`$ kubectl version`
`Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
`

#### Possible Solution

Force only `v1beta1` while waiting patch.

Change this :
```
// +kubebuilder:webhook:path=/mutate-....,mutating=true,...,name=vfoo.kb.io,admissionReviewVersions={v1,v1beta1}
```
to this (no more `v1` in admissionReviewVersions):
```
// +kubebuilder:webhook:path=/mutate-....,mutating=true,...,name=vfoo.kb.io,admissionReviewVersions={v1beta1}
```

**Comment by estroz** [comment]
@BugMaster510945 what controller-runtime version is your operator using?

/triage support

**Comment by BugMaster510945** [comment]
Hi @estroz,

how can I get controller-runtime ? 
In doubt, here my `go.mod`, generated by operator-sdk :
```
module ...

go 1.15

require (
	github.com/go-logr/logr v0.3.0
	github.com/onsi/ginkgo v1.14.1
	github.com/onsi/gomega v1.10.2
	github.com/pkg/errors v0.9.1
	k8s.io/api v0.19.2
	k8s.io/apimachinery v0.19.2
	k8s.io/client-go v0.19.2
	sigs.k8s.io/controller-runtime v0.7.0
)
```

**Comment by estroz** [comment]
@BugMaster510945 try bumping to v0.7.2, which contains a bugfix for webhook patches.

**Comment by BugMaster510945** [comment]
Hi @estroz,

Indeed v0.7.2 contains fixes which solve my issue.

Thanks for your time
