### ISSUE TITLE
Bundle creation failed when webhook enabled (golang)

### ISSUE THREAD

**Issue by jlpedrosa** [operator-framework/operator-sdk#4615]
## Bug Report
When generating a new operator, the yaml generated for the webhook is invalid, enabling it causes the bundle not to be generated with error:
```
ERRO[0000] Error: Field spec.conversion.webhookClientConfig.service.port, Value 0: spec.conversion.webhookClientConfig.service.port: Invalid value: 0: port is not valid: must be between 1 and 65535, inclusive 
ERRO[0000] Error: Field spec.conversion.conversionReviewVersions, Value : spec.conversion.conversionReviewVersions: Required value 
```

#### What did you do?
This pseudo script shows how to reproduce:

```bash
mkdir memcached-operator
cd memcached-operator
operator-sdk init --domain example.com --repo github.com/example/memcached-operator
operator-sdk create api --group cache --version v1alpha1 --kind Memcached --resource --controller
operator-sdk create webhook --group cache --version v1alpha1 --kind Memcached --defaulting --programmatic-validation
#un-comment relevant lines for [CERTMANAGER] and [WEBHOOK] on: 
# * config/default/kustomization.yaml
# * config/crd/kustomization.yaml
make bundle
```

#### What did you expect to see?
The bundle generated correctly

#### What did you see instead? Under which circumstances?
See code sample in previous section

#### Environment
/language go

```
operator-sdk version: "v1.4.2", commit: "4b083393be65589358b3e0416573df04f4ae8d9b", 
kubernetes version: "1.19.4", 
go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
```

**Comment by varshaprasad96** [comment]
@jlpedrosa - `webhookClientConfig.service.port` and `conversionReviewVersions` are required fields for having conversion webhooks in CSV. #4346 brings in support for this. Will work on getting this PR merged.

**Comment by illeatmyhat** [comment]
You are not generating a conversion webhook, so there's no reason for you to enable the conversion webhook in `crd/kustomization.yaml`
```yaml
patchesStrategicMerge:
- patches/webhook_in_mlmodels.yaml # enables conversion webhook
```
Actually, the above patch interferes with the `defaulting` and `programmatic-validation (aka admission and mutating webhooks).

**Comment by estroz** [comment]
@jlpedrosa can you retitle this to include info about conversion webhooks not being supported? Thanks!

**Comment by varshaprasad96** [comment]
this is close to getting finished, but since its not a release blocker, bumping it to next milestone.

**Comment by varshaprasad96** [comment]
closing this as #4346 is merged
