### ISSUE TITLE
xunit support in scorecard output

### ISSUE THREAD

**Issue by jmccormick2001** [operator-framework/operator-sdk#4616]
#### Describe the problem you need a feature to resolve.

within Red Hat, the QE teams make use of xunit test output, to enable them to utilize scorecard for QE testing
they would like to have scorecard produce test results in xunit format.

#### Describe the solution you'd like.

an output option of xunit for scorecard so that users can pass a flag to scorecard and have the test results formatted in xunit
format.

**Comment by jmccormick2001** [comment]
ncredi@redhat.com

**Comment by theishshah** [comment]
Addressed with #5048

**Comment by apodhrad** [comment]
Hi @jmccormick2001 @theishshah IMO the xunit output is not valid. I have raised a new issue at #5457 please check it.
