### ISSUE TITLE
scorecard - add new identifier field to config.yaml

### ISSUE THREAD

**Issue by jmccormick2001** [operator-framework/operator-sdk#4617]
#### Describe the problem you need a feature to resolve.

allow for a unique test ID to reference a scorecard test, this would support xunit output processing for example.

#### Describe the solution you'd like.

today, scorecard has a simple test name for each test, for some systems that process test results, it would be beneficial to allow a user to specify a unique ID 

https://source.redhat.com/groups/public/polarion/polarion_importer_documents/polarion_results_xunit_importer#jive_content_id_Using_the_default_Custom_id_of_Test_Case_ID

So, within the scorecard config.yaml, maybe a solution is to add another field within the expected config.yaml schema that lets users enter an ID if they choose, this would be an optional field.

**Comment by jmccormick2001** [comment]
ncredi@redhat.com

**Comment by nellyc** [comment]
Thanks @jmccormick2001 
This ask directly ties into the junit/xunit feature requests[1]
I can provide more details if needed

[1] https://github.com/operator-framework/operator-sdk/issues/4616 & https://github.com/operator-framework/operator-sdk/issues/4488 we can probably close 1 of them if we can agree on 1 schema .

**Comment by theishshah** [comment]
added in API pr110
