### ISSUE TITLE
operator-sdk up local creates an ERRO[0000] that cannot be resolved by the user

### ISSUE THREAD

**Issue by benjaminapetersen** [operator-framework/operator-sdk#462]
As far as I understand, the following error:

```bash
$ user@host on master > operator-sdk up local
INFO[0000] Go Version: go1.11
INFO[0000] Go OS/Arch: darwin/amd64
INFO[0000] operator-sdk Version: 0.0.5+git
ERRO[0000] failed to initialize service object for operator metrics: OPERATOR_NAME must be set
```

![screen shot 2018-09-06 at 4 43 45 pm](https://user-images.githubusercontent.com/280512/45184149-13f8a900-b1f4-11e8-9fca-efdf3e723ae2.png)

Cannot be resolved by the user who is running the sdk locally.  My preference would be not to see it, unless there is a way that I can do something meaningful to resolve the message properly.

@fanminshi @robszumski @hasbro17 fyi, thanks!

**Comment by estroz** [comment]
Setting `OPERATOR_NAME` in your shell or removing `sdk.ExposeMetricsPort()` from file `cmd/${your_operator}/main.go` should resolve this issue.

**Comment by fanminshi** [comment]
@estroz yeah, your approach works. However, we should prevent this warning from happening if the user is running the operator locally.

**Comment by LiliC** [comment]
I would suggest we set the environment variable `OPEATOR_NAME` as part of `up local` process, we have the operator name as we parse the config file which contains `ProjectName` https://github.com/operator-framework/operator-sdk/blob/280ebfaef7d43ff6712fe7358480c69e750a29cc/pkg/generator/gen_config.go#L30.

That would fix the error msg and also generate the metrics service file, but maybe the best solution would be come up with a different way on how to get the operator name in general.

**Comment by hasbro17** [comment]
@LiliC Reopening this since it got closed when #564 got merged. We decided not to fix it in #564 and instead go with the approach you've suggested above, to pass in the env var to `operator-sdk up local`. We'll have to do that in another PR.

**Comment by sebgoa** [comment]
hi, meanwhile, a note in the user-guide would be nice. Because going through the guide you hit this right away

**Comment by LiliC** [comment]
Think this should actually be fixed now, both leader election and metrics do not fail when running locally, just log the errors. Feel free to reopen if it's still an issue.
