### ISSUE TITLE
Question about helm based Operators

### ISSUE THREAD

**Issue by devdattakulkarni** [operator-framework/operator-sdk#4629]
Hello,

I had a question about helm chart based Operators. Our helm chart requires a certain attribute value to be provided on command-line as part of the 'helm install' command (using set). 

```
helm install kp-hook ./kp-hook --set caBundle=$(kubectl get secret/crdhook-cert-tls-secret -n default -o jsonpath='{ .data.ca\.crt }')
```

I am wondering when we create an Operator for this Helm chart using operator-sdk, how would this attribute's value be provided when instantiating the corresponding Custom Resource.

Thanks!

**Comment by joelanford** [comment]
You would set `spec.caBundle` in the CR.
