### ISSUE TITLE
Question about creating Operator bundle image for OLM

### ISSUE THREAD

**Issue by devdattakulkarni** [operator-framework/operator-sdk#4634]
Hi,

I am following https://sdk.operatorframework.io/docs/building-operators/helm/tutorial/

to create our Operator from our Helm chart. I am stuck at the 'Run the operator' step. Specifically I am using the 'Deploy your Operator with OLM' option.

OLM installation went fine (no errors - I see the olm namespace created and there are bunch of Pods running in that ns).
The next step of bundling the Operator is where I am stuck now. Here are the steps (copied from above link).

```
make bundle IMG=$OPERATOR_IMG
# Note the "-bundle" component in the image name below.
export BUNDLE_IMG="quay.io/$USERNAME/nginx-operator-bundle:v0.0.1"
make bundle-build BUNDLE_IMG=$BUNDLE_IMG
make docker-push IMG=$BUNDLE_IMG
```

In this I am not sure what should be the value set for OPERATOR_IMG.

When I tried running above command, I am seeing following error:

```
$ make bundle IMG=kubeplus-operator-bundle
operator-sdk generate kustomize manifests -q
cd config/manager && /Users/me/go/src/github.com/cloud-ark/kubeplus/bin/kustomize edit set image controller=kubeplus-operator-bundle
/bin/sh: line 1: 81127 Killed: 9               /Users/me/go/src/github.com/cloud-ark/kubeplus/bin/kustomize edit set image controller=kubeplus-operator-bundle
make: *** [bundle] Error 137
```
I am not sure what above error means and how to resolve it.

Thanks for the help!

**Comment by estroz** [comment]
Looks like an environment issue. Check out [this stackoverflow](https://unix.stackexchange.com/questions/184371/what-does-line-19-12364-killed-mean-in-crontab-error-message) for some help with debugging.
Feel free to re-open this if you think this issue is Operator SDK-related.
