### ISSUE TITLE
Best practices Advice concerning update of conditions or events

### ISSUE THREAD

**Issue by Athosone** [operator-framework/operator-sdk#4635]
## Type of question

Best practices
How to implement a specific feature

## Question

Hi all ! :)

I am building an operator using your SDK (awesome SDK btw).

My team and I got questions about best practices concerning feed back for the user.

Briefly our operator run a pipeline, it downloads stuff, create configs and then spawn applications.
Each CRD represent the desired state for an application.

The question we have is what is the best way to advertise for the progress of our operator.

For example how to say "Hey I am currently downloading the needed stuff", "Hey I have downloaded 3 out of 10"

These information would be used by another app which will display feedback to our user.

My opinion is to use Conditions for the steps:
"
-Downloading
-Configuring
-Installing
-Done

And Events to signal the progress of each of the conditions (progress of download for example).

Does it look like a good design to you? 

Regards,

Ayrton
#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

vanilla

**Comment by estroz** [comment]
@Athosone that seems reasonable. Do you need one CRD per application state, instead of just one CRD with different status conditions?

Side note: your description sounds like some components of https://github.com/argoproj/argo-cd. Have you looked into using its APIs?

/remove-lifecycle stale

**Comment by Athosone** [comment]
Yeah we looked into it as well fluxcd which looks great but we are in an hybrid scenario (on premise with support for airgapped and cloud) which does not work well with these GitOps tools.

For example when you want to install a release we need to transfer the images from our remote registry to a local registry to ensure high availability in poor network environment. Then we persist the digests of these images to prevent unauthorized image to be spawn etc..

We also receive app updates according to rules determined by business logic.

Sure we could hack it around these tools but it did not seems right especially when the only part we need from these tools is to install an app with helm.

There is something which is more of a helm issue but for example fluxcd install a helm release inside its helm controller. The issue with that approach is that if you self-update the helm controller, the pod will die while the new one spawn, it could interrupt helm and you end up in corrupt state which required manual intervention. We cannot take such risk when we distribute our apps to our on premise clients...

Moreover these tools offer a lots of features that we won't be able to use (user management, GitOps etc..)
