### ISSUE TITLE
FATA[0003] failed to initialize project with version "3-alpha": exit status 2 

### ISSUE THREAD

**Issue by devrajmaker** [operator-framework/operator-sdk#4645]
## Bug Report
What I am expecting:

operator-sdk init --domain=example.com --repo=github.com/example/memcached-operator
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.6.3
Update go.mod:
$ go mod tidy
Running make:
$ make
go: creating new go.mod: module tmp
go: found sigs.k8s.io/controller-tools/cmd/controller-gen in sigs.k8s.io/controller-tools v0.3.0
/home/sadique/go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
go build -o bin/manager main.go
Next: define a resource with:

What i am getting:
 operator-sdk init --domain=example.com --repo=github.com/example/memcached-operator
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.6.3
Update go.mod:
$ go mod tidy
Running make:
$ make

go: creating new go.mod: module tmp
go: found sigs.k8s.io/controller-tools/cmd/controller-gen in sigs.k8s.io/controller-tools v0.3.0
/home/devraj/go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
# runtime/cgo
cgo: exec gcc: exec: "gcc": executable file not found in $PATH
Makefile:51: recipe for target 'vet' failed
make: *** [vet] Error 2
Error: failed to initialize project with version "3-alpha": exit status 2
Usage:
  operator-sdk init [flags]

Examples:
  # Scaffold a project using the apache2 license with "The Kubernetes authors" as owners
  operator-sdk init --project-version=2 --domain example.org --license apache2 --owner "The Kubernetes authors".

**Comment by Sadiquedeveloper** [comment]
Try this GOPROXY=https://proxy.golang.com,direct and GOPROXY=direct

**Comment by estroz** [comment]
Sounds like a go environment problem. Regardless, the `init` command no longer runs `make` (in the next release).

**Comment by devrajmaker** [comment]
> Sounds like a go environment problem. Regardless, the `init` command no longer runs `make` (in the next release).

What can i do to solve the environment issue because i did what i can.

**Comment by Sadiquedeveloper** [comment]
> Sounds like a go environment problem. Regardless, the `init` command no longer runs `make` (in the next release).

But it's working fine for me and we have the same environment.
