### ISSUE TITLE
Capture Liveness event in update section

### ISSUE THREAD

**Issue by psaini79** [operator-framework/operator-sdk#4648]
## Type of question

<-- Best practices -->

## Question
How do we capture liveness event change in the update section in eventFilterPredicate function? 

#### What did you do?

```
func (r *MyAppReconciler) eventFilterPredicate() predicate.Predicate {
        return predicate.Funcs{
                CreateFunc: func(e event.CreateEvent) bool {
                        return true
                },

                UpdateFunc: func(e event.UpdateEvent) bool {
                             return true
                },
```

I want to know how do we capture the Liveness probe event when it changes from healthy to unhealthy and vice versa?  or if there is an increment in failure or success count?

#### Environment

**Operator type:**

<-- /language go -->

**Kubernetes cluster type:**

`$ operator-sdk version`

`operator-sdk version: "v1.2.0", commit: "215fc50b2d4acc7d92b36828f42d7d1ae212015c", kubernetes version: "v1.18.8", go version: "go1.15.3", GOOS: "linux", GOARCH: "amd64"` 

`$ go version` (if language is Go)

`go version go1.15.8 linux/amd64`

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"336ccfb2560ff170c7ad8aad56944e43e4f6a170", GitTreeState:"clean", BuildDate:"2020-06-09T22:13:31Z", GoVersion:"go1.13.8 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by estroz** [comment]
You could implement your own [`healthz.Checker`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/healthz#Checker) that updates some external state on failed liveness/readiness. You might be able to do this in a predicate, but using the Checker callback would be easier.

This is a question about the controller-runtime library, so I'm going this out here. If you have further questions, please recreate this issue in the [controller-runtime repo](https://github.com/kubernetes-sigs/controller-runtime/issues/).
