### ISSUE TITLE
How to generate the openapi/swagger.json for an operator?

### ISSUE THREAD

**Issue by zenglian** [operator-framework/operator-sdk#466]
How to generate the openapi/swagger.json for an operator (e.g., Prometheus Operator)? 
I searched "swagger" in this repo but no result returned.

**Comment by joelanford** [comment]
@zenglian Sorry no one ever responded to your question! We have since added the `operator-sdk generate openapi` command, which will add an OpenAPI spec to your CRDs.

If that doesn't solve your problem or is not what you were asking, re-open the ticket with more details and we'll take another look.
