### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Kosmas** [operator-framework/operator-sdk#4661]
Trying to download the checksums file and its signature from the installation guide does not work
 
`$ curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt`

The latest tag is pointing to a different place 

https://github.com/operator-framework/operator-sdk/releases/tag/scorecard-kuttl%2Fv2.0.0

**Comment by gngeorgiev** [comment]
This breaks the instructions from this page https://sdk.operatorframework.io/docs/installation/#install-from-github-release

**Comment by Kosmas** [comment]
@gngeorgiev I was following the instructions from this page.
I believe that the problem is that the latest tag points to the wrong release (see link above).

**Comment by gngeorgiev** [comment]
That's correct. This is a script that works for specific versions in a Dockerfile:

```
ARG OPERATOR_SDK_VERSION="v1.5.0"
RUN export ARCH=$(case $(arch) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(arch) ;; esac) && \
    export OS=$(uname | awk '{print tolower($0)}') && \
    export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION} && \
    curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH} && \
    gpg --keyserver keyserver.ubuntu.com --recv-keys 052996E2A20B5C7E && \
    curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt && \
    curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt.asc && \
    gpg -u "Operator SDK (release) <cncf-operator-sdk@cncf.io>" --verify checksums.txt.asc && \
    grep operator-sdk_${OS}_${ARCH} checksums.txt | sha256sum -c - && \
    chmod +x operator-sdk_${OS}_${ARCH} && mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk && \
    operator-sdk version
```

It's a better idea to use a version, rather than latest as the script suggests either ways.

**Comment by Kosmas** [comment]
Thanks @gngeorgiev!
So that probably means that the installation instructions need to change so they follow the same idea as your Dockerfile code above?

**Comment by jfrancin** [comment]
Yes, the instructions in https://sdk.operatorframework.io/docs/installation/ "Install from GitHub release" are just plain wrong.

Either make the reality match the docs or change the docs.

**Comment by estroz** [comment]
The plan is to set up a download resource on the SDK’s website to redirect to the correct release download links. Hoping to have this set up by Friday, and update the latest docs.

**Comment by estroz** [comment]
In the meantime, I've changed the non-binary-containing release as a pre-release so the doc link still works.
