### ISSUE TITLE
MigrationGuide is missing the step to bump the images 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4671]
## Bug Report

New migration guides which are autogenerated since 1.0 are missing the step to bump the Ansible/Helm image version

#### What did you do?

checked https://sdk.operatorframework.io/docs/upgrading-sdk-version/

#### Suggested Solution

Add to the process that generates the migration guides this step by default since users will always need to bump de versions for Ansible/Helm. Example;

```
For Ansible/Helm-based operators:
In the Dockerfile, replace  `v1.5.0` with `v1.6.0`
```

**Comment by jberkhahn** [comment]
maybe take a look in here: https://github.com/operator-framework/operator-sdk/blob/master/release/changelog/gen-changelog.go

**Comment by jmrodri** [comment]
No plans to do this.
