### ISSUE TITLE
Memcached Sample and tutorial using Status Conditionals

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4679]
#### Describe the problem you need a feature to resolve.

it is recommended to manage the status as described in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties

#### Describe the solution you'd like.

Then, I think that would be nice to see the Memcached sample and tutorial using status conditionals instead of update status using the pod names. See; 

https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/controllers/memcached_controller.go#L113-L136
 

#### Environment

/language go

**Comment by jberkhahn** [comment]
FYI we already have a section in 'advanced topics' that covers this: https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#manage-cr-status-conditions
