### ISSUE TITLE
Memcached Sample with controller covered by tests

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4681]
#### Describe the problem you need a feature to resolve.

We recommend users to cover their project controller with tests using envtest

#### Describe the solution you'd like.
Then, I think that would be nice if we could make the https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/controllers/ covered by tests using envtest. See; https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html

#### Environment

/language go

**Comment by jberkhahn** [comment]
I think this is a good idea, but it seems complicated. Would these tests be run in CI or are they merely meant to provide an example to users? If they are meant as an example to the users, it might be more helpful to write a 'how to test' tutorial rather than just providing examples. Would we write these tests manually and have to be responsible for making sure they don't drift? If someone pushes a commit and they blow up, how do we know why they blew up?

**Comment by petebowden** [comment]
I would love this. I spent a fair amount of time getting tests working based on the kubebuilder tutorial (segfault). Once I got it going, it's fairly straightforward to write tests.

I think a very simple test with the proper initialization would be sufficient. I'd hope that before someone pushes a commit to the memcached sample operator, they ensure that the test passes.

**Comment by camilamacedo86** [comment]
@petebowden we could not decide if it would be better in the samples or just in a new section in the tutorial. However, your help is more than welcome always :-) . I understand that add a doc with this example has no objections at all and it is very desirable. 

We can indeed (f it is decided) just add the example from the doc in the samples. 

@jmrodri wdyt? Have you any objections to that? Please, let me know if I misunderstood something as well.

**Comment by estroz** [comment]
I'm in favor of both a tutorial and samples. @petebowden if you'd like to work on one or both parts of this, feel free to assign yourself.

/kind feature
/kind documentation

**Comment by petebowden** [comment]
@estroz happy to take a stab at it. FYI I don't have permission to assign this task to myself.

**Comment by estroz** [comment]
Thanks!

/assign @petebowden
