### ISSUE TITLE
Samples and tutorials using the env var to for the Memcached image

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4688]
#### Describe the problem you need a feature to resolve.

We recommend users inform the image:tag via the manager envvar. However, we do not provide an example

#### Describe the solution you'd like.
Then, I think that would be nice if we could make the ansible/helm/go tutorials and samples are using the env var to define the Memcached image and tag

#### Environment

/language go
/language ansible 
/language helm

**Comment by jberkhahn** [comment]
this seems like a good topic for the 'best practices' section

**Comment by camilamacedo86** [comment]
We might need to change here the label for docs. WDYT?

**Comment by estroz** [comment]
There are examples of `IMG` usage in [all quickstarts](https://master.sdk.operatorframework.io/docs/building-operators/golang/quickstart/#direct-deployment), and a full section about this in [all tutorials](https://master.sdk.operatorframework.io/docs/building-operators/golang/tutorial/#configure-the-operators-image-registry).
