### ISSUE TITLE
bundle format ignoring default channel in annotations

### ISSUE THREAD

**Issue by saada** [operator-framework/operator-sdk#4691]
#### What did you do?

I'm trying to set the default channel on the [flux](https://github.com/operator-framework/community-operators/blob/master/upstream-community-operators/flux/0.9.1/metadata/annotations.yaml#L2-L3) package.
I can't figure out a way to set the default channel in this page: https://operatorhub.io/operator/flux

#### What did you expect to see?

I expected that the annotations.yaml defaultChannel would be picked up automatically.

#### What did you see instead? Under which circumstances?

It shows alpha instead of stable channel effectively ignoring the default set in annotations.yaml.

#### Possible Solution

Please add/share documentation with steps to fix this.

**Comment by camilamacedo86** [comment]
Hi @saada, 

See the section in the doc: https://master.sdk.operatorframework.io/docs/overview/cheat-sheet/#updating-bundle-channels

Then, could you please let us know if it solves your problem?

**Comment by estroz** [comment]
If this is a bug, it would likely be in https://github.com/operator-framework/operator-registry, as operator-sdk does not interpret this value in any way. One alternative that I can think of is your annotation key is not correct. It should be `operators.operatorframework.io.bundle.channel.default.v1` and set on both `bundle/metadata/annotations.yaml` _and_ `bundle.Dockerfile`.

**Comment by saada** [comment]
the annotations.yaml seems correct. But I don't have a bundle.Dockerfile. Do I have to have bundle.Dockerfile ?

**Comment by saada** [comment]
This issue seems to be the root of the problem https://github.com/operator-framework/operator-registry/issues/330

**Comment by estroz** [comment]
@saada are you a maintainer of the flux package/operator? If so you should have access to some Dockerfile for building bundles, and be able to follow the instructions in https://github.com/operator-framework/operator-registry/issues/330#issuecomment-764734595 with `opm v1.15.3` to get the behaviour you want.

**Comment by saada** [comment]
I'm the maintainer, yes. However, I don't have any Dockerfile. Does the Dockerfile affect the OperatorHub default channel shown here: https://operatorhub.io/operator/flux?

**Comment by estroz** [comment]
Ah your operator is being registered from https://github.com/operator-framework/community-operators. The latest version of flux published on operatorhub.io is 0.7.7, which uses [alpha as the default channel](https://github.com/operator-framework/community-operators/blob/master/upstream-community-operators/flux/0.7.7/metadata/annotations.yaml#L2) and why you're seeing alpha appear as the default. I would open an issue in community-operators to figure out upgrading flux on the published catalog.

**Comment by saada** [comment]
That's incorrect. The latest one I pushed there was [0.9.1 on the stable channel](https://github.com/operator-framework/community-operators/blob/master/upstream-community-operators/flux/0.9.1/metadata/annotations.yaml#L2-L3). Their UI shows 0.7.7 incorrectly. I already reported in their repo and they just closed my ticket without reading or following up https://github.com/operator-framework/community-operators/issues/3309

And it looks like you're doing the same here

**Comment by estroz** [comment]
There's nothing I can do about what's being displayed on operatorhub.io, sorry. I'll comment on that issue though.
