### ISSUE TITLE
Cannot build v0.4.0 - current directory is not in a module

### ISSUE THREAD

**Issue by dfishburn** [operator-framework/operator-sdk#4692]
We are on an older version, but I can't build.
Wondering if anyone has any suggestions?
Really, I am wondering why there is not go.mod file?

The instructions I followed were:
```
$ mkdir -p $GOPATH/src/github.com/operator-framework
$ cd $GOPATH/src/github.com/operator-framework
$ git clone https://github.com/operator-framework/operator-sdk
$ cd operator-sdk
$ git checkout <RELEASE TAG>
$ make dep
$ make install
```

And environment:
```
$ env | grep GO
GOPATH=/home/blah/go_4_iots
GOROOT=/home/blah/go
GOBIN=/home/blah/go/bin
```

```
YKFN34338057A:~/go_4_iots/src/github.com/operator-framework/operator-sdk$ go version
go version go1.16.2 linux/amd64

YKFN34338057A:~/go_4_iots/src/github.com/operator-framework/operator-sdk$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

YKFN34338057A:~/go_4_iots/src/github.com/operator-framework/operator-sdk$ git status
On branch v0.4.x
Your branch is up to date with 'origin/v0.4.x'.

nothing to commit, working tree clean

YKFN34338057A:~/go_4_iots/src/github.com/operator-framework/operator-sdk$ git checkout v0.4.0
Note: checking out 'v0.4.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at cc5fe885 *: release v0.4.0 (#957)

YKFN34338057A:~/go_4_iots/src/github.com/operator-framework/operator-sdk$ make dep

YKFN34338057A:~/go_4_iots/src/github.com/operator-framework/operator-sdk$ make install
go install: version is required when current directory is not in a module
        Try 'go install github.com/operator-framework/operator-sdk/commands/operator-sdk@latest' to install the latest version
Makefile:44: recipe for target 'install' failed
make: *** [install] Error 1
```

Thank you,
David

**Comment by jmrodri** [comment]
@dfishburn what version of go are you using? There is no `go.mod` file in this release because it a very old release when we used `dep`. So the error you are seeing means go needs to be told NOT to use go modules. Is there a reason you need to rebuild such an old release? You should be able to get the binary directly https://github.com/operator-framework/operator-sdk/releases/tag/v0.4.0

**Comment by jmrodri** [comment]
Looking at the travis.yml v0.4.0 was built with golang 1.10.3 so you will likely need an older version of go and have the project in your GOPATH.

**Comment by jmrodri** [comment]
Yeah, I don't think you can use `go version go1.16.2 linux/amd64` to build such an old version of operator-sdk. Let me know why you need to rebuild such an old version, you might be better off switching to the latest or just using the prebuilt binary.

**Comment by dfishburn** [comment]
> Looking at the travis.yml v0.4.0 was built with golang 1.10.3 so you will likely need an older version of go and have the project in your GOPATH.

Ah, ok.
We inherited the project, and it is on the list to upgrade.

**Comment by dfishburn** [comment]
Built successfully, much obliged.

**Comment by jmrodri** [comment]
@dfishburn If you choose to upgrade it and have questions feel free to reach out in slack at https://kubernetes.slack.com/archives/C017UU45SHL 

Unfortunately, with a project that old it would likely be a lot of migrations to get to the current version:
v0.2.x to v0.17.x : https://sdk.operatorframework.io/docs/upgrading-sdk-version/version-upgrade-guide/

All upgrades:  https://sdk.operatorframework.io/docs/upgrading-sdk-version/

I will close this issue as resolved.
