### ISSUE TITLE
Warning while new API CRD for custom operator.

### ISSUE THREAD

**Issue by ila-001** [operator-framework/operator-sdk#4706]
## Type of question

<-- General operator-related help -->

#### What did you do?

I am new to operators, While adding new API CRD for our custom operator
[xxx@localhost xxx-xxx]$ operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=xxx
INFO[0000] Generating api version app.example.com/v1alpha1 for kind xxx.
INFO[0000] Created pkg/apis/app/v1alpha1/xxx_types.go
INFO[0000] Created pkg/apis/addtoscheme_app_v1alpha1.go
INFO[0000] Created pkg/apis/app/v1alpha1/register.go
INFO[0000] Created pkg/apis/app/v1alpha1/doc.go
INFO[0000] Created deploy/crds/app_v1alpha1_xxx_cr.yaml
W0328 06:35:25.843417    5146 parse.go:239] Ignoring child directory github.com/ila-001/xxx-xxx/pkg/apis/app: unable to import "github.com/ila-001/xxx-xxx/pkg/apis/app": go/build: importGo github.com/ila-001/xxx-xxx/pkg/apis/app: exit status 1
package github.com/ila-001/xxx-xxx/pkg/apis/app: no Go files in /home/xxx/nodename-xxx/src/github.com/ila-001/xxx-xxx/pkg/apis/app

INFO[0030] Created deploy/crds/app_v1alpha1_xxx_crd.yaml
INFO[0079] Running deepcopy code-generation for Custom Resource group versions: [app:[v1alpha1], ]
INFO[0115] Code-generation complete.
INFO[0153] Running OpenAPI code-generation for Custom Resource group versions: [app:[v1alpha1], ]
2021/03/28 06:38:00 Code for OpenAPI definitions generated
INFO[0185] Created deploy/crds/app_v1alpha1_xxx_crd.yaml
INFO[0185] Code-generation complete.
INFO[0185] API generation complete.

The CRD is created, however the Custom resource gives me this warning/error. Kindly let me know what to do?

#### Environment

**Operator type:**

language go 

**Kubernetes cluster type:**

 "OpenShift" 

`$ operator-sdk version` 

operator-sdk version: v0.8.0, commit: 78c472461e75e6c64589cfadf577a2004b8a26b3

`$ go version` (if language is Go)

go version go1.16.2 linux/amd64

`$ kubectl version`

oc v3.7.23
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://XXXXXXXXX.dev.corp:443
openshift v3.11.374
kubernetes v1.11.0+d4cacc0

**Comment by estroz** [comment]
v0.8.0 is a _very_ old version of operator-sdk, which you're using with a new Go version. I suggest upgrading to a newer version of operator-sdk, or using an older Go version (go1.11 probably).

**Comment by ila-001** [comment]
Thanks Eric. It worked with newer version of operator-sdk
