### ISSUE TITLE
did not receive playbook_on_stats event

### ISSUE THREAD

**Issue by slehlib** [operator-framework/operator-sdk#4709]
## Question

I try to create ansible operator and after apply cr file, i have this msg :+1: 

#### Environment

**Operator type:** ansible

**Kubernetes cluster type: minikube

`$ operator-sdk version` v1.5.0

`$ go version` (if language is Go)

`$ kubectl version`v1.20.5

#### Additional context

*************************************\n\u001b[0;34m1 plays in /tmp/ansible-operator/runner/foo.example.com/v1alpha1/Foo/default/foo-sample/project/fb6152263010473fa8b9ce60ef7050e7\u001b[0m\n\r\nPLAY [localhost] ***************************************************************\n\r\nTASK [Gathering Facts] *********************************************************\n\u001b[0;32mok: [localhost]\u001b[0m\n\u001b[0;34mMETA: ran handlers\u001b[0m\n\u001b[0;34mredirecting (type: action) community.kubernetes.k8s to community.kubernetes.k8s_info\u001b[0m\n\r\nTASK [foo : set ConfigMap example-config to present] ***************************\r\n\u001b[1;30mtask path: /home/saber/foo-operator/roles/foo/tasks/main.yml:4\u001b[0m\n\u001b[0;34mredirecting (type: action) community.kubernetes.k8s to community.kubernetes.k8s_info\u001b[0m\n\u001b[0;34mredirecting (type: action) community.kubernetes.k8s to community.kubernetes.k8s_info\u001b[0m\n\u001b[0;33mchanged: [localhost] => {\"changed\": true, \"method\": \"create\", \"result\": {\"apiVersion\": \"v1\", \"kind\": \"ConfigMap\", \"metadata\": {\"creationTimestamp\": \"2021-03-30T18:38:37Z\", \"managedFields\": [{\"apiVersion\": \"v1\", \"fieldsType\": \"FieldsV1\", \"fieldsV1\": {\"f:metadata\": {\"f:ownerReferences\": {\".\": {}, \"k:{\\\"uid\\\":\\\"95ab01b2-91b2-4e6b-9682-1977d81c0d1d\\\"}\": {\".\": {}, \"f:apiVersion\": {}, \"f:kind\": {}, \"f:name\": {}, \"f:uid\": {}}}}}, \"manager\": \"OpenAPI-Generator\", \"operation\": \"Update\", \"time\": \"2021-03-30T18:38:37Z\"}], \"name\": \"example-config\", \"namespace\": \"default\", \"ownerReferences\": [{\"apiVersion\": \"foo.example.com/v1alpha1\", \"kind\": \"Foo\", \"name\": \"foo-sample\", \"uid\": \"95ab01b2-91b2-4e6b-9682-1977d81c0d1d\"}], \"resourceVersion\": \"1722\", \"uid\": \"0c1de256-2277-46f6-bc53-4772f793efee\"}}}\u001b[0m\n\u001b[0;34mMETA: ran handlers\u001b[0m\n\u001b[0;34mMETA: ran handlers\u001b[0m\n\r\nPLAY RECAP *********************************************************************\r\n\u001b[0;33mlocalhost\u001b[0m                  : \u001b[0;32mok=2   \u001b[0m \u001b[0;33mchanged=1   \u001b[0m unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   \r\n\n","job":"3510942875414458836","name":"foo-sample","namespace":"default","error":"did not receive playbook_on_stats event","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/operator-framework/operator-sdk/internal/ansible/controller.(*AnsibleOperatorReconciler).Reconcile\n\tinternal/ansible/controller/reconcile.go:229\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:297\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:252\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:215\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}
{"level":"error","ts":1617129517.9915116,"logger":"controller-runtime.manager.controller.foo-controller","msg":"Reconciler error","name":"foo-sample","namespace":"default","error":"did not receive playbook_on_stats event","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:301\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:252\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:215\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}

**Comment by estroz** [comment]
@slehlib how did you run your operator, with `make run` or `make deploy`? That error could mean ansible-runner-http is not installed.

/triage support

**Comment by morningspace** [comment]
@estroz May I know how to install ansible-runner-http? I didn't find it in README.md in its repo.

**Comment by caatclaudia** [comment]
> @estroz May I know how to install ansible-runner-http? I didn't find it in README.md in its repo.

You can use the command: `pip install ansible-runner-http`
