### ISSUE TITLE
Service account and tokens not deleted

### ISSUE THREAD

**Issue by jaydeepva** [operator-framework/operator-sdk#4710]
## Type of question

General operator-related help

## Question

Operator when installed creates service account for the operator. Service account token secrets are created for service account. When operator is uninstalled, is service account for operator is expected to be deleted? OR Is the service account expected to be deleted manually?

#### What did you do?

1. Create a service account for operator
2. Include service account yaml in config/rbac folder. 
```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: my-operator-service-account
  labels:
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/managed-by: my-operator
    app.kubernetes.io/name: my-operator
    release: 1.0.0
imagePullSecrets:
  - name: my-key
```
3. Add service account yaml name to config/rbac/kustomization.yaml
```
resources:
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- service_account.yaml
```
4. Run `make bundle`. The service account yaml is included in bundle folder
```
$ pwd
/operators/my-operator/bundle/manifests
$ ls -l
-rwxrwxrwx 1 elm elm   311 Feb 27 10:40 my-operator-service-account_v1_serviceaccount.yaml
-rwxrwxrwx 1 elm elm 47659 Feb 27 10:40 my-operator.clusterserviceversion.yaml
```
5. Verify that service account name is present in csv file at `install.spec.deployments[0].spec.template.spec.serviceAccount,  install.spec.deployments[0].spec.template.spec.serviceAccountName` and `install.spec.permissions.rules.serviceAccountName`
6. Deploy the operator. Ensure that service account is created. Also verify that token secrets for service account are created
7. Uninstall the operator

#### What did you expect to see?

1. The service account should get deleted
2. The service account tokens should be deleted

#### What did you see instead? Under which circumstances?

1. Service account and service account tokens are not deleted
```
$ oc get sa
NAME                               SECRETS   AGE
builder                            2         119d
default                            2         119d
deployer                           2         119d
my-operator-service-account   2         70d

$ oc get secrets
NAME                                               TYPE                                  DATA   AGE
builder-dockercfg-276cc                            kubernetes.io/dockercfg               1      119d
builder-token-f8znw                                kubernetes.io/service-account-token   4      119d
builder-token-mmwpw                                kubernetes.io/service-account-token   4      119d
default-dockercfg-llg5c                            kubernetes.io/dockercfg               1      119d
default-token-rhz7d                                kubernetes.io/service-account-token   4      119d
default-token-x2gxj                                kubernetes.io/service-account-token   4      119d
deployer-dockercfg-xw8qt                           kubernetes.io/dockercfg               1      119d
deployer-token-6hssq                               kubernetes.io/service-account-token   4      119d
deployer-token-9hzs7                               kubernetes.io/service-account-token   4      119d
my-operator-service-account-dockercfg-jqjcg   kubernetes.io/dockercfg               1      70d
my-operator-service-account-token-k8hzw       kubernetes.io/service-account-token   4      70d
my-operator-service-account-token-s8dd8       kubernetes.io/service-account-token   4      70d
my-operator-service-account-token-z9fzd       kubernetes.io/service-account-token   4      70d
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

OpenShift

`$ operator-sdk version`

operator-sdk version: "v1.2.0", commit: "215fc50b2d4acc7d92b36828f42d7d1ae212015c", kubernetes version: "v1.18.8", go version: "go1.15.3", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.13.8 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+65bd32d", GitCommit:"65bd32d", GitTreeState:"clean", BuildDate:"2021-01-27T04:24:26Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by estroz** [comment]
This is likely a bug in OLM, since OLM deletes [all RBAC it creates](https://olm.operatorframework.io/docs/tasks/uninstall-operator/#step-3-delete-the-operators-clusterserviceversion-csv) when uninstalling an operator. This bug may be fixed but not released as there have been a bunch of service account-related PRs/bugfixes in OLM since v0.17.0. Regardless I would file an issue in https://github.com/operator-framework/operator-lifecycle-manager.

**Comment by estroz** [comment]
On further review this does not look like a bug in OLM (or SDK for that matter). From https://github.com/operator-framework/operator-lifecycle-manager/issues/2078:

>OLM intentionally does not delete service accounts that exist prior to operator installation. OLM will ownerref a service account contained in a bundle to the bundle's CSV, so when the CSV is deleted the service account should be as well.

Going to close this since it is being handled in the OLM repo.
