### ISSUE TITLE
Operator sdk version and PROJECT version breaking change related query

### ISSUE THREAD

**Issue by kaushiksrinivas** [operator-framework/operator-sdk#4719]
We see from the release notes, operator sdk version 1.5.0 no longer supports PROJECT version 3-alpha and instead is replaced by 3.
**Breaking change: PROJECT config version 3-alpha has been upgraded to version 3.**

But if we try to build a operator-sdk project with v1.5.0 , but keeping the PROJECT version 3-alpha only, the build still works. Project is built successfully. Can you please elaborate on this PROJECT version change and the impact of it with older projects having version as 3-alpha ?

**Comment by camilamacedo86** [comment]
Hi @kaushiksrinivas, 

If you do not fix the project file then it means that you will be unable to still using the SDK tool and its helpers.  Also, see that if you did not follow the guidelines properly it might mean face issues with what is scaffolded by the tool and/or future help. 

I'd indeed suggest you check out: https://master.sdk.operatorframework.io/docs/faqs/#can-i-customize-the-projects-initialized-with-operator-sdk

In this way, I am closing this one as sorted out. However, please feel free to re-open if you need.
