### ISSUE TITLE
`generate bundle` should not add unserved CRDs to owned section

### ISSUE THREAD

**Issue by phantomjinx** [operator-framework/operator-sdk#4722]
#### Describe the problem you need a feature to resolve.
When running `operator-sdk generate bundle ...` (version 1.5), any older versions of CRDs API contained in the `versions` section of the CRD are [added](https://github.com/operator-framework/operator-sdk/blob/master/internal/generate/clusterserviceversion/clusterserviceversion_updaters.go#L240) to the `owned` section of the CSV. 
These references are added even though they were not included when executing `operator-sdk generate kustomize manifests ...`.

These older versions have been marked as `unserved` hence consided deprecated.

An undesirable effect of these APIs appearing in the `owned` section is that multiple sections are displayed in the Provided APIs section of the Openshift Console, identically labelled. This may be a defect with the Console but does end up being an unfortunate result that will do nothing but confuse users.

#### Describe the solution you'd like.
The operator-sdk generator code should consider APIs marked as unserved, ie. deprecated, and not add them to the `owned` section or consider only the latest version of an API and only add that to the owned section. This will fix the problem with multiple Provided API entries in the Openshift Console.

However, if the `owned` section of the CSV has additional functions and deprecated/multiple versions of the same API should appear in this section of the CSV then an explanation would be appreciated.

/language go

**Comment by phantomjinx** [comment]
![syndesis-console](https://user-images.githubusercontent.com/1634180/113853616-c242a180-9795-11eb-92b3-d49a309035c7.png)

Screenshot showing 3 Owned APIs of differing versions

**Comment by estroz** [comment]
This fix may also need to be applied to scorecard, although not certain about that. Needs to be investigated.
