### ISSUE TITLE
operator-sdk unable to pull the docker image

### ISSUE THREAD

**Issue by psaini79** [operator-framework/operator-sdk#4729]
#### What did you expect to see?

operator-bundle must be able to pull the docker image.

#### What did you see instead? Under which circumstances?
`operator-sdk run bundle $BUNDLE_IMG -n test-odb`

The above command is throwing the following error:

```
FATA[0000] Failed to run bundle: pull bundle image: error pulling image my-reg-server/mytenancy/db-repo/my-operator-bundle:v0.0.1: error resolving name : no scope specified for token auth challenge
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

`Minikube`

` operator-sdk version`

 `operator-sdk version: "v1.2.0", commit: "215fc50b2d4acc7d92b36828f42d7d1ae212015c", kubernetes version: "v1.18.8", go version: "go1.15.3", GOOS: "linux", GOARCH: "amd64"` 

`$ go version` (if language is Go)

 `go version go1.15.8 linux/amd64` 

`$ kubectl version`

`Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by camilamacedo86** [comment]
Are you able to pull the image without the sdk command? 
It shows that you have no access to the image/registry to pull that.

**Comment by psaini79** [comment]
@camilamacedo86 

Yes, using docker pulll, I am able to pull the docker image from same registry server. However, I id docker login before docker pull.

**Comment by camilamacedo86** [comment]
After you do the docker login and store those credentials did you try to use the command again? Seems that the error is because was not possible to pull the image and then, the command will not have that to work.

**Comment by psaini79** [comment]
@camilamacedo86 

Where should I store the credentials? Are there any steps for operator-sdk to pull the images from private registries?

**Comment by varshaprasad96** [comment]
This issue maybe similar to #4650

**Comment by estroz** [comment]
Docs will be updated in the next release. For now you can see the requested functionality explained [here](https://master.sdk.operatorframework.io/docs/olm-integration/cli-overview/#private-bundle-and-catalog-image-registries).

**Comment by stevelaclasse** [comment]
I got the same problem and i could solve it by creating a secret of type **kubernetes.io/dockerconfigjson**  , by running the command : **kubectl create secret docker-registry secret_name --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>**
I have created the secret in the same namespace as the serviceaccount or others manifest file generated by the framework.
 you edit the serviceaccount yaml file by adding 
**imagePullSecrets:
- name: secret_name**

And the make deploy IMG= ........   should work.

**Comment by vhosakot** [comment]
update for previous comment https://github.com/operator-framework/operator-sdk/issues/4729#issuecomment-1487002895:

I'm able to run the operator-sdk bundle by prefixing `docker.io` like `operator-sdk run bundle docker.io/vhosakot/nginx-operator-bundle:v0.0.1`.

```
% operator-sdk run bundle --help                                                        
...
If using a docker.io image, you must specify docker.io(/<namespace>)?/<bundle-image-name>:<tag>.
...
```

But I see many such pods failing and restarting:
```
% kubectl get pods | grep 20ed3bdb54db8de8b2a12 | wc -l
    1232
```

<img width="1297" alt="Screenshot 2023-03-28 at 5 32 42 PM" src="https://user-images.githubusercontent.com/8882663/228373160-9deaa8ff-3569-42f9-8151-d10909cacaa7.png">

I see this error in the above pods like:

`% kubectl logs 20ed3bdb54db8de8b2a12deaafa934b3aca92f140692f73cd07a18ccdfvt6ks`
`Error: error loading manifests from directory: ConfigMap "20ed3bdb54db8de8b2a12deaafa934b3aca92f140692f73cd07a18ccdf3af79" is invalid: [data[demo.vhosakot_nginxes.yaml]: Invalid value: "demo.vhosakot_nginxes.yaml": duplicate of key present in binaryData, data[nginx-operator-controller-manager-metrics-service_v1_service.yaml]: Invalid value: "nginx-operator-controller-manager-metrics-service_v1_service.yaml": duplicate of key present in binaryData, data[nginx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml]: Invalid value: "nginx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml": duplicate of key present in binaryData, data[nginx-operator.clusterserviceversion.yaml]: Invalid value: "nginx-operator.clusterserviceversion.yaml": duplicate of key present in binaryData]`
