### ISSUE TITLE
RBAC roles required for operator's 

### ISSUE THREAD

**Issue by britoaldan** [operator-framework/operator-sdk#4737]
We see that without adding the below roles operator functionality fails.
apiGroups: [""]
resources: ["configmaps/status"]
verbs: ["get", "update", "patch"]

apiGroups: [""]
resources: ["events"]
verbs: ["create", "patch"]

We understand that the configmap resource is for the leader election, 
can anyone elaborate on how to avoid these roles.
And also explain the need for events.

**Comment by britoaldan** [comment]
@camilamacedo86  can you please help us here..

**Comment by estroz** [comment]
@britoaldan can you please fill out the issue template so we have version information. Then we can help debug your issues. FWIW configmaps/status should never be necessary, and events are not used by default with configmap+leases leader election. You should also post runtime logged errors here.

/triage needs-information

**Comment by jmrodri** [comment]
This is why the events RBAC is required for leader election: https://github.com/kubernetes-sigs/kubebuilder/issues/1474

**Comment by camilamacedo86** [comment]
HI @britoaldan, 

Are you not using the latest version of the project. Am I right? 
So, I'd suggest you move forward and upgrade your project to use the latest. 

See the rbac roles configured for them with go/v3 : 

- https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/config/rbac/role.yaml
- https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/config/rbac/leader_election_role.yaml

The `configmaps/status` will not be present by default.

Regarding the event's permissions, you can find more info in https://github.com/kubernetes-sigs/kubebuilder/issues/1474.

**Comment by britoaldan** [comment]
hi @camilamacedo86 hi @jmrodri, 
Can you please let me know the importance of the lease resource required

**Comment by estroz** [comment]
They're needed for the leader election lock, see [`manager.Options`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Options). If you do not want RBAC containing permissions for configmaps or leases, then you cannot use leader election and must turn it off in the Options I linked. As @camilamacedo86 has said, `configmaps/status` was added in error and has been removed in the latest scaffolds, but `configmaps` is still necessary for leader election.

If you have more questions, feel free to reopen this issue with a thorough description of your concerns.

**Comment by britoaldan** [comment]
Thanks all for the support
