### ISSUE TITLE
Helm Operator base image contains high severity vulnerabilities

### ISSUE THREAD

**Issue by nestorsalceda** [operator-framework/operator-sdk#4738]
#### What did you do?

I'm upgrading my helm based operators and when upload them to redhat registry they becomes rejected because of **free_of_critical_vulnerabilities** check.

I checked the base image and upgraded to latest: 

FROM quay.io/operator-framework/helm-operator:v1.5

But it contains a vulnerability: 

https://quay.io/repository/operator-framework/helm-operator/manifest/sha256:1fe42cea202bb552436364cdf10378d40595cf7fd4513ea5d1762f239700138e?tab=vulnerabilities

#### What did you expect to see?

I do expect base images without high severity vulnerabiltiies.

#### Environment

**Operator type:**

/language helm

**Kubernetes cluster type:**

`$ operator-sdk version`

1.5.0

`$ go version` (if language is Go)

go version go1.16.3 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"archive", BuildDate:"2021-03-25T19:02:48Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

#### Possible Solution

In the security report it tells:

https://quay.io/repository/operator-framework/helm-operator/manifest/sha256:1fe42cea202bb552436364cdf10378d40595cf7fd4513ea5d1762f239700138e?tab=vulnerabilities

That this is fixed in `1:1.1.1g-15.el8_3` so I would upgrade the base images

**Comment by estroz** [comment]
@nestorsalceda please read our [SECURITY.md](https://github.com/operator-framework/operator-sdk/blob/master/SECURITY.md) for reporting security vulnerabilities.
