### ISSUE TITLE
api/v1alpha1/zz_generated.deepcopy.go is not compliant with goimport format

### ISSUE THREAD

**Issue by fjammes** [operator-framework/operator-sdk#4743]
#### What did you do?

Run build script for an operator and notice that command below generates a file non-compliant with `goimports` standards.

```
$ /home/fjammes/go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
$ git status
On branch tickets/DM-29567
Your branch is up to date with 'origin/tickets/DM-29567'.

nothing to commit, working tree clean
$ goimports -w api/v1alpha1/zz_generated.deepcopy.go api/v1alpha1/zz_generated.deepcopy.go 
$ git status
On branch tickets/DM-29567
Your branch is up to date with 'origin/tickets/DM-29567'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   api/v1alpha1/zz_generated.deepcopy.go

no changes added to commit (use "git add" and/or "git commit -a")
$ git --no-pager diff                                                                      
diff --git a/api/v1alpha1/zz_generated.deepcopy.go b/api/v1alpha1/zz_generated.deepcopy.go
index e55de09..8a38007 100644
--- a/api/v1alpha1/zz_generated.deepcopy.go
+++ b/api/v1alpha1/zz_generated.deepcopy.go
@@ -21,7 +21,7 @@ limitations under the License.
 package v1alpha1
 
 import (
-	"k8s.io/api/core/v1"
+	v1 "k8s.io/api/core/v1"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 	runtime "k8s.io/apimachinery/pkg/runtime"
 )
```

#### What did you expect to see?

Line 21 in `api/v1alpha1/zz_generated.deepcopy.go` should be generated using format compliant with `goimports`

#### What did you see instead? Under which circumstances?

Line 21 in  `api/v1alpha1/zz_generated.deepcopy.go` is not generated using a format compliant with `goimports`. This might break static code analysis job in CI.

#### Environment

**Operator type:**

/language go 

**Kubernetes cluster type:**

Kind

`$ operator-sdk version`
operator-sdk version: "v1.5.0", commit: "98f30d59ade2d911a7a8c76f0169a7de0dec37a0", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"

`$ go version`
go version go1.16.3 linux/amd64

`$ kubectl version`
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

#### Possible Solution

Replace line 21 in `api/v1alpha1/zz_generated.deepcopy.go` by
```
v1 "k8s.io/api/core/v1"
```
in the go code generating this file.

**Comment by estroz** [comment]
This import is written by [`controller-gen`](https://github.com/kubernetes-sigs/controller-tools/blob/master/cmd/controller-gen/main.go) so needs to be fixed there. For now, a workaround is just run `goimports` on the project once `controller-gen` has been run (add this to your Makefile).

/triage support
