### ISSUE TITLE
consider add `operator-sdk version` to prerequisites in order to prove documentation consistency

### ISSUE THREAD

**Issue by Dentrax** [operator-framework/operator-sdk#4745]
### What is the URL of the document?

i.e.: https://sdk.operatorframework.io/docs/building-operators/golang/installation/

### Which section(s) is the issue in?

`Prerequisites`

### What needs fixing?

Consider add `$ operator-sdk version`.

#### Additional context

We could not reproduce the documentation because the commands may incomplete to the current version of `operator-sdk`. ( i.e. see #4744) It would be nice to see which version this doc is made for.

**Comment by estroz** [comment]
So you're asking for a short section about looking at the correct docs version based on your `operator-sdk version` output? If so I agree.

**Comment by jberkhahn** [comment]
also, there are links to the docs for older versions of the sdk at the top under 'releases'

**Comment by pravarag** [comment]
@estroz can I work on this issue if nobody else is working on it? As I'm new to the `operator-framework` community, will help me in getting my first issue :)

**Comment by pravarag** [comment]
@estroz  just wanted to check as I was looking to make the relevant changes. If my understanding is correct, we want to include the current `operator-sdk version` somewhere here in this document: https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/installation/_index.md to identify if we are pointed to correct version or not? One strange thing I found out, the existing `Releases` tab isn't compatible to direct the user with relevant `operator-sdk` version when selected.
