### ISSUE TITLE
Unable to create webhook for core type

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [operator-framework/operator-sdk#4747]
#### What did you do?

I am trying to add a webhook for an existing core resource but unable to do so. Reproducible with the following steps:

```bash
operator-sdk create api --group "apps" --kind "Deployment" --version "v1" --resource=false --controller=true
operator-sdk create webhook --group "apps" --kind "Deployment" --version "v1" --defaulting --programmatic-validation
```

#### What did you see instead? Under which circumstances?

Got the following error:

```
Error: failed to create webhook with "go.kubebuilder.io/v2": operator-sdk create webhook requires an api with the group, kind and version provided
Usage:
  operator-sdk create webhook [flags]

Examples:
  # Create defaulting and validating webhooks for CRD of group ship, version v1beta1
  # and kind Frigate.
  operator-sdk create webhook --group ship --version v1beta1 --kind Frigate --defaulting --programmatic-validation

  # Create conversion webhook for CRD of group shio, version v1beta1 and kind Frigate.
  operator-sdk create webhook --group ship --version v1beta1 --kind Frigate --conversion


Flags:
      --conversion                if set, scaffold the conversion webhook
      --defaulting                if set, scaffold the defaulting webhook
      --group string              resource Group
  -h, --help                      help for webhook
      --kind string               resource Kind
      --programmatic-validation   if set, scaffold the validating webhook
      --resource string           resource Resource
      --version string            resource Version

Global Flags:
      --verbose   Enable verbose logging

FATA[0000] failed to create webhook with "go.kubebuilder.io/v2": operator-sdk create webhook requires an api with the group, kind and version provided 
```

#### Environment

Openshift v4.6.13

**Operator type:**

/language go

**Kubernetes cluster type:**

`$ operator-sdk version`

```
operator-sdk version: "v1.4.0", commit: "67f9c8b888887d18cd38bb6fd85cf3cf5b94fd99", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
```

`$ go version` (if language is Go)

`go version go1.16 linux/amd64`

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+3b01205", GitCommit:"3b012051f912a6e29337c4087fcfc8161651690b", GitTreeState:"clean", BuildDate:"2021-01-16T09:10:53Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by camilamacedo86** [comment]
As we spoke about core/external types are not fully supported yet and you need to create the api with resource true as a workaround and do manually the ajusts. See: https://github.com/kubernetes-sigs/kubebuilder/issues/1999

**Comment by estroz** [comment]
`create webhook` does not support core types yet, as [this comment](https://github.com/kubernetes-sigs/kubebuilder/issues/1999#issuecomment-818040163) says. There should be an error returned by `create webhook` for core types until some library/convenience function/scaffold is created to establish core type webhooks.

/kind feature

**Comment by estroz** [comment]
Created an issue in kubebuilder to return an error: https://github.com/kubernetes-sigs/kubebuilder/issues/2141

**Comment by camilamacedo86** [comment]
Hi @estroz, 

> create webhook does not support core types yet, as this comment says. 

I do not agree that is true. See; https://book.kubebuilder.io/reference/webhook-for-core-types.html

The KB/SDK CLI tool is what does not supported that because it is not implemented.

**Comment by camilamacedo86** [comment]
Hi @ahmedwaleedmalik, 

See; https://book.kubebuilder.io/reference/webhook-for-core-types.html

The KB/SDK CLI tool is what does not support that because it is not implemented with IHMO should be addressed as part of RFE: kubernetes-sigs/kubebuilder#1999.  However, I hope that this doc helps you with.
