### ISSUE TITLE
Require ansible 2.10.7 with ansible operator

### ISSUE THREAD

**Issue by theabmitra** [operator-framework/operator-sdk#4749]
#### What did you do?
Hello,

I noticed current operator supports following version of ansible 
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/openshift']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, Aug 18 2020, 08:56:04) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

I am in need of certain ansible features which are supported ion 2.10.x. Hence on my mac my playbooks work 
ansible 2.10.7

Questions :- 
1. Is there a version of the operator where updated ansible version is present 
2. If not, how do i customize the base image , since its locked down to non sudo at the bottom

**Comment by estroz** [comment]
Ansible 2.10 contains breaking changes, so will not be supported within the operator-sdk v1.y timeframe. If you want this Ansible version, you can try upgrading your ansible-operator image by following the 2.10 port guide during image build by adding steps to your `Dockerfile`, although I do not recommend this.

@fabianvf we may want to add an FAQ to answer this, since it is confusing that ansible-operator does not support an Ansible v2.y release.

/triage support
/language ansible

**Comment by muranant** [comment]
Any details or pointers on what kind of breaking changes were observed when moving to ansible 2.x ?

**Comment by estroz** [comment]
Take a peek at https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.10.html

**Comment by muranant** [comment]
Thanks @estroz . Couple more questions.
- I looked at the above release notes. Was there any one thing that broke the operator-sdk? 
- When is the v2 version of operator-sdk expected? i helps us make a decision either way...

-Thanks

**Comment by theabmitra** [comment]
> Ansible 2.10 contains breaking changes, so will not be supported within the operator-sdk v1.y timeframe. If you want this Ansible version, you can try upgrading your ansible-operator image by following the 2.10 port guide during image build by adding steps to your `Dockerfile`, although I do not recommend this.
> 
> @fabianvf we may want to add an FAQ to answer this, since it is confusing that ansible-operator does not support an Ansible v2.y release.
> 
> /triage support
> /language ansible

 I did try to modify the "base.Dockerfile" t include ansible 2.10.X however it errors out at the pipfile section .  It would be great if you share an example.
We cannot directly use the normal docker image and modify as its locked down with user

**Comment by kensipe** [comment]
Best if we add to FAQ
