### ISSUE TITLE
Version 1.5.0 cause issue with GVK

### ISSUE THREAD

**Issue by alejandrojnm** [operator-framework/operator-sdk#4753]
#### What did you do?

I import a 3rd party lib "kubevirt" and register the schema in the main, after that I add a watcher to the controller to watch `VirtualMachine`

#### What did you expect to see?

I expect everything work 

#### What did you see instead? Under which circumstances?

I saw this error when i run the operator using `make run`:
`2021-04-13T09:06:37.620-0400    ERROR   setup   problem running manager {"error": "multiple group-version-kinds associated with type *v1.VirtualMachine, refusing to guess at one"}`

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

BareMetal 1.20

`$ operator-sdk version`

operator-sdk version: "v1.5.0", commit: "98f30d59ade2d911a7a8c76f0169a7de0dec37a0", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "darwin", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.16 darwin/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by estroz** [comment]
@alejandrojnm this problem is a result from double-registering a scheme containing `v1.VirutalMachine`.

Are you saying that prior versions of your project worked with prior k8s dependency versions, and is only now breaking?

/triage support

**Comment by alejandrojnm** [comment]
Yes, we use the operator-sdk v1.3 and the same kubevirt lib and work, them i create a new operator with the last version 1.5 and i got that error

**Comment by soodpr** [comment]
even with operator sdk 1.4.2, I am facing the same issue.

**Comment by estroz** [comment]
This is likely a bug in controller-runtime, see https://github.com/kubernetes-sigs/controller-runtime/issues/362. I recommend either commenting on 362 or opening up a new issue in that repo.

**Comment by alejandrojnm** [comment]
The problem is we need pass this env VAR at the moment of run the operator:
`KUBEVIRT_CLIENT_GO_SCHEME_REGISTRATION_VERSION=v1alpha3` 
and the reference is this: https://github.com/kubevirt/kubevirt/pull/4749

**Comment by estroz** [comment]
Nice find, I would've never guessed this was a bug caused by an upstream toolchain.
