### ISSUE TITLE
Release binary files

### ISSUE THREAD

**Issue by nicolaferraro** [operator-framework/operator-sdk#476]
It would be really nice if you could publish the `operator-sdk` binary file, compiled for common architectures, together with the source files in the release page.

People working on a operator-sdk based project now need to:
- Clone the operator-sdk project into their gopath
- Install it to create the binary file
- Delete the source from the gopath, otherwise source files would clash with their counterpart in the project's vendor dir

It's also difficult to communicate which version of the sdk they have to install and how to do it.

If the binary file was available, they would just need to curl it into a location in their $PATH.

**Comment by estroz** [comment]
Very relevant question. We are currently in pre-alpha but plan to have versioned releases in the near future. An in-depth discussion of the release process will be had amongst the maintainers in the coming weeks!

**Comment by LiliC** [comment]
This was resolved when the above PR was merged and we now release binaries.
