### ISSUE TITLE
Missing docs on how to effectively use scaffolded resources from `operator-sdk create webhook`

### ISSUE THREAD

**Issue by komish** [operator-framework/operator-sdk#4765]
### What is the URL of the document?

https://master.sdk.operatorframework.io/docs/building-operators/golang/

### Which section(s) is the issue in?

N/A

### What needs fixing?

It seems like this section is missing information on what's scaffolded when making a call to `operator-sdk create webhook`. 

The command help text exists in the documentation at this location - https://master.sdk.operatorframework.io/docs/cli/operator-sdk_create_webhook/ - but it doesn't quite clarify what a user's next steps are (e.g. in the case of conversion webhooks, defining their hub and spokes).

#### Additional context

I don't think it's beneficial to reimplement the docs as they exist here in the Kubebuilder book - https://book.kubebuilder.io/multiversion-tutorial/conversion-concepts.html - but I do think some docs on what gets scaffolded and why would be beneficial. Next steps pointing to the Kubebuilder docs, considering this is probably a kubebuilder-based task in its entirety seems sufficient.

In the past, this document existed and goes more in depth - https://v0-19-x.sdk.operatorframework.io/docs/golang/webhooks/. I'm not sure if this was intentionally left behind because how things worked changed or otherwise, but figured I would mention it.

**Comment by varshaprasad96** [comment]
@komish yes, as you had pointed out the reason for removing documentation on the next steps was because it is already available in the [Kubebuilder](https://book.kubebuilder.io/multiversion-tutorial/conversion.html) docs so I think replicating it in SDK docs would not be needed. 
Keeping this open to discuss in triage meeting.

**Comment by komish** [comment]
@varshaprasad96 Understood! I'll attend and see if there's any questions I can help with.

**Comment by jberkhahn** [comment]
Ok. Going to close this, please reopen if you have any further issues.

**Comment by varshaprasad96** [comment]
Issue to handle referencing of upstream docs: #4831
