### ISSUE TITLE
Document how to add 3rd party resources, such as OpenShift resources

### ISSUE THREAD

**Issue by benjaminapetersen** [operator-framework/operator-sdk#477]
When attempting to `sdk.Watch` an OpenShift `Route` via:

```go
sdk.Watch("route.openshift.io/v1", "Route", namespace, resyncPeriod)
```

I get errors like:

```bash 
ERROR: logging before flag.Parse: E0911 17:24:14.258632   57519 runtime.go:66] Observed a panic: &errors.errorString{s:"failed to decode json data with gvk(route.openshift.io/v1, Kind=Route): no kind \"Route\" is registered for version \"route.openshift.io/v1\""} (failed to decode json data with gvk(route.openshift.io/v1, Kind=Route): no kind "Route" is registered for version "route.openshift.io/v1")
$HOME/go/src/github.com/openshift/console-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
$HOME/go/src/github.com/openshift/console-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
$HOME/go/src/github.com/openshift/console-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/Cellar/go/1.11/libexec/src/runtime/asm_amd64.s:522
/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513
/// etc
```

However, this seems to have fixed the problem:

```go
func init() {
    k8sutil.AddToSDKScheme(route.Install)
}
```
I'm suggesting one of two solutions:
- Initially at least the User Guide should include a section for installing unknown resources
- Alternatively, if `sdk.Watch` can be modified to handle resources generically, that may avoid the previous need.

**Comment by hasbro17** [comment]
@benjaminapetersen adding new types to the SDK scheme via `k8sutil.AddToSDKScheme()` is the way to do it. That's how the custom resources are added right now.

I think just documenting it on the user-guide or somewhere else should be sufficient.
`sdk.Watch` can't do much to watch unknown resources. It comes back to all types being registered with the underlying scheme.

**Comment by eivantsov** [comment]
@benjaminapetersen @hasbro17 same approach if I need to create a route from within the operator? Is there any simple example operator that creates and watches deployment, service and route which is typical for a webapp?

**Comment by shawn-hurley** [comment]
Whichever types you want to use in your operator need to be added to the scheme. for the core APIs (empty group) we add those by default. 

https://github.com/operator-framework/operator-sdk/blob/4179b6ac459b2b0cb04ab3a1b438c280bd28d1a5/pkg/util/k8sutil/k8sutil.go#L45


If you want Deployments you will have to register `apps/v1`. 

Example of how: 
`
...First couple lines of main.go...
k8sutil.AddToSDKScheme(appsv1.AddToScheme)`
`

**Comment by benjaminapetersen** [comment]
@eivantsov my snippet above was for a route, that was my exact use case as well.

**Comment by benjaminapetersen** [comment]
@eivantsov in total my `main.go` has this, its not a lot:

```go
inport 	routev1 "github.com/openshift/api/route/v1"
// init will run before main
func init() {
	k8sutil.AddToSDKScheme(route.Install)
}

func watch(apiVersion, kind, namespace string, resyncPeriod int) {
	logrus.Infof("Watching %s, %s, %s, %d", apiVersion, kind, namespace, resyncPeriod)
	sdk.Watch(apiVersion, kind, namespace, resyncPeriod)
}

// and off we go
func main() {
        resyncPeriod := 60 * 60 * 10  // 10hrs.  no less. 
  	watch(routev1.GroupVersion.String(), "Route", namespace, resyncPeriod)
	watch(myResourceGroupVersion, "MyResource", namespace, resyncPeriod)
	sdk.Handle(stub.NewHandler())
	sdk.Run(context.TODO())    
}
```

**Comment by eivantsov** [comment]
@benjaminapetersen thanks but for some reason, a simple

```
import (
	route "github.com/openshift/api/route"
	k8sutil "github.com/operator-framework/operator-sdk/pkg/util/k8sutil"
)

func init() {
	k8sutil.AddToSDKScheme(appsv1.AddToScheme)
	k8sutil.AddToSDKScheme(route.Install)
}
```

Results in 

```
cannot use route.Install (type func(*"github.com/openshift/api/vendor/k8s.io/apimachinery/pkg/runtime".Scheme) error) as type k8sutil.addToSchemeFunc in argument to k8sutil.AddToSDKScheme

```

**Comment by benjaminapetersen** [comment]
You added the dependencies via `dep`, `openshift/api `? 
You should have `/vendor/openshift/api` directory if so.

**Comment by benjaminapetersen** [comment]
(thats my guess)

**Comment by benjaminapetersen** [comment]
Nice!

**Comment by eivantsov** [comment]
@benjaminapetersen thanks for your help. I think a short:

1. Add to your imports
2. Add to scheme
3. Use in your function

with code snippets would be **very** helpful for those not familiar with Operators or k8s go lib in general. 

I was able to write a simple operator that creates deployment, service account, rolebinding, service and a route exploring available examples and using some help from @benjaminapetersen

**Comment by shawn-hurley** [comment]
Closed by #509

**Comment by camilamacedo86** [comment]
Hi folks,

It shows not work more in this way. Could you please give me a hand in https://github.com/operator-framework/operator-sdk/issues/1365?  

c.c @eivantsov @hasbro17 @benjaminapetersen @shawn-hurley @jfchevrette

**Comment by eivantsov** [comment]
@camilocot https://github.com/operator-framework/operator-sdk/pull/509 works for me. 

https://github.com/eclipse/che-operator/blob/master/pkg/controller/che/che_controller.go#L71

**Comment by camilamacedo86** [comment]
@eivantsov it worked the issue was just because I was adding the "routev1.AddToScheme(mgr.GetScheme())" after the "controller.AddToManager(mgr);" then the schema could not be added on it.
