### ISSUE TITLE
Bump Goreleaser to support darwin_arm64 arch

### ISSUE THREAD

**Issue by w3st3ry** [operator-framework/operator-sdk#4773]
#### Describe the problem you need a feature to resolve.

Asked myself if you plan to bump Go to `1.16.x` and then bump Goreleaser to [v0.156.0](https://github.com/goreleaser/goreleaser/releases/tag/v0.156.0) to support/build `darwin_arm64` as a release. 😄

#### Describe the solution you'd like.

A brew cask `darwin_arm64` to prevent the Go dependency install from brew.

**Comment by w3st3ry** [comment]
@estroz thanks for the change. IMO your PR answer part of the issue.
Maybe we shall let it open waiting a bump of Go version + `darwin_arm64` as target in Goreleaser?

**Comment by estroz** [comment]
It sounded like you mainly wanted goreleaser bumped. Can you retitle the issue to say something about go 1.16 + darwin_arm64 support and reopen the issue?

**Comment by estroz** [comment]
#4828 captures the go 1.16 bump.

**Comment by w3st3ry** [comment]
@estroz sorry for the late answer, I just did it! Btw I can't re-open the issue on my side.
