### ISSUE TITLE
operator-sdk should use updated ubi base image

### ISSUE THREAD

**Issue by bitscuit** [operator-framework/operator-sdk#4774]
In the recent releases of operator-sdk, v1.6.1 and v1.5.1, there are three high level vulnerabilities according to quay https://quay.io/repository/operator-framework/helm-operator/manifest/sha256:3f557aa662ce3af3693d7bea42b41a7339857d6c7abaeec3bbe9f1a89f63f15f?tab=vulnerabilities. 

Most likely because the image is relying on an older ubi8 image https://github.com/operator-framework/operator-sdk/blob/master/images/operator-sdk/Dockerfile#L20. The latest ubi8-minimal is `8.3-298`

**Comment by estroz** [comment]
Closed by #4766
