### ISSUE TITLE
init fails with common existing files

### ISSUE THREAD

**Issue by planetf1** [operator-framework/operator-sdk#4796]
#### What did you do?

Tried to create a new project with: `operator-sdk init --domain egeria-project.org --license apache2 --owner 'Contributors to the Egeria project' --project-name 'egeria-k8s-operator' --repo 'github.com/odpi/egeria-k8s-operator'` into a nearly empty github project

#### What did you expect to see?

Iniitalized skeleton project being created

#### What did you see instead? Under which circumstances?

A failure message - 

`FATA[0000] failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v3": target directory is not empty (only go.mod, go.sum, LICENSE, README.md, and files and directories with the prefix "." are allowed); found existing file "CODEOWNERS" 
`

CODEOWNERS is a well established github file which may be created in the early stages of project creation

I didn't check, but other typical files may include those under .github -- these aren't just for building code but may be, for example, for stale issue management workflow

#### Environment

**Operator type:**

</language go>

**Kubernetes cluster type:**

OpenShift
`$ operator-sdk version`

operator-sdk version: "v1.6.1", commit: "e6981d812a759442a583d8ee2fae269507c408d4", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "darwin", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.15.11 darwin/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+d46d32f", GitCommit:"d46d32fbc3f0c35d2855a4589062aaf6335acd48", GitTreeState:"clean", BuildDate:"2021-03-11T01:16:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1

#### Additional context

I had the same issue with a few other files - DEVELOP.md, NOTICE, SECURITY.md, doc (this was a subdirectory of design docs), and finally 'old' (where I had moved the old operator code to)

I understand the need to be building a clean project, but the current approach does seem a little too limiting - it would (IMO!) be more appropriate if only selected subdirectories were tested, along with key top level files that are being checked. Additionally reporting the errors one file at a time is painful vs providing a failed-validation list.

Another option of course is to build into a subdir, yet many of the files created are appropriate to a top level dir in any case 
With files removed th

**Comment by camilamacedo86** [comment]
I think that would be OK to add CODEOWNERS as an exception as well. Would you like to collab with it? This change needs to be done in Kubebuider. See; 

https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/init.go#L175-L179

As a workaround, you can move the file to the scaffold and after came back that as well.

**Comment by planetf1** [comment]
I'd be happy to give making a PR a go if you're not in a rush .. I've not built kubebuilder before but it would be good practice :-)
Any thoughts on the other files? I know projects do vary...
There is perhaps the broader question of handling existing files - which would be more of a design change

**Comment by w3st3ry** [comment]
@planetf1 I would say any capitalized files name (in addition of `LICENSE` pr e.g) or containing a `.md` extension.

**Comment by w3st3ry** [comment]
[The related PR](https://github.com/kubernetes-sigs/kubebuilder/pull/2160) has been merged.

**Comment by kensipe** [comment]
@camilamacedo86  @w3st3ry has this issue been closed with the last PR merge?
