### ISSUE TITLE
run bundle{-upgrade} should able to pull image from insecure registry

### ISSUE THREAD

**Issue by avalluri** [operator-framework/operator-sdk#4815]
## Feature Request

Optional support for `operator-sdk run bundle/bundle-upgrade`  pulling the bundle image from an insecure container registry.

#### Describe the problem you need a feature to resolve.

I run a local insecure docker image for testing. I push the generated operator bundle image to the local docker registry.
Running the `operator-sdk run bundle localhost:5000/pmem-csi-bundle:v0.9.0` fails to install the operator:

```
$ operator-sdk run bundle localhost:5000/pmem-csi-bundle:v0.9.0 --verbose
FATA[0000] Failed to run bundle: pull bundle image: error pulling image localhost:5000/pmem-csi-bundle:v0.9.0: error resolving name : failed to do request: Head "https://localhost:5000/v2/pmem-csi-bundle/manifests/v0.9.0": http: server gave HTTP response to HTTPS client 
```

#### Describe the solution you'd like.

The `opm` tool already supports pulling images from the insecure registery when asked using `--skip-tls`, `operator-sdk` could make used of this to support insecure registries. Provide a command-line argument for `operator-sdk run bundle` to enable/disable the `--skip-tls` :

     `$ operator-sdk run bundle <bundleImage> [--allow-insecrue]`

**Comment by jmrodri** [comment]
@avalluri Thank you for the PR and issue. We have @Venkat19967 working on part of this and realized we were going down the same path as you with the skiptls :) 

@Venkat19967 is working on using a local registry to allow us to e2e test the run bundle feature in CI.

**Comment by Venkat19967** [comment]
@avalluri Thank you for working on this flag. It is very helpful

**Comment by hj-johannes-lee** [comment]
Hello, I am trying to run with insecure registry running on localhost as the example in the issue.

`$operator-sdk run bundle localhost:5000/test:devel -n testoperator --skip-tls
$kubectl logs -n testoperator   localhost-5000-test-devel
time="2022-04-12T21:30:43Z" level=info msg="adding to the registry" bundles="[localhost:5000/test:devel]"
time="2022-04-12T21:30:43Z" level=info msg="trying next host" error="failed to do request: Head \"http://localhost:5000/v2/test/manifests/devel\": dial tcp 127.0.0.1:5000: connect: connection refused" host="localhost:5000"
time="2022-04-12T21:30:43Z" level=error msg="permissive mode disabled" bundles="[localhost:5000/test:devel]" error="[error resolving name : failed to do request: Head \"http://localhost:5000/v2/test/manifests/devel\": dial tcp 127.0.0.1:5000: connect: connection refused, image \"localhost:5000/test:devel\": not found]"
Error: [error resolving name : failed to do request: Head "http://localhost:5000/v2/test/manifests/devel": dial tcp 127.0.0.1:5000: connect: connection refused, image "localhost:5000/test:devel": not found]
Usage:
  opm registry add [flags]

Flags:
  -b, --bundle-images strings   comma separated list of links to bundle image
      --ca-file string          the root certificates to use when --container-tool=none; see docker/podman docs for certificate loading instructions
  -c, --container-tool string   tool to interact with container images (save, build, etc.). One of: [none, docker, podman] (default "none")
  -d, --database string         relative path to database file (default "bundles.db")
      --debug                   enable debug logging
  -h, --help                    help for add
      --mode string             graph update mode that defines how channel graphs are updated. One of: [replaces, semver, semver-skippatch] (default "replaces")
      --permissive              allow registry load errors

Global Flags:
      --skip-tls-verify   skip TLS certificate verification for container image registries while pulling bundles
      --use-http          use plain HTTP for container image registries while pulling bundles
$kubectl describe pod -n testoperator   localhost-5000-test-devel
...
    Command:
      sh
      -c
      mkdir -p /database && \
      opm registry add -d /database/index.db -b localhost:5000/test:devel --mode=semver --skip-tls=true && \
      opm registry serve -d /database/index.db -p 50051
`
It still does not work for the 'localhost' the container's localhost is not the host's localhost.

**Comment by laxmikantbpandhare** [comment]
@hj-johannes-lee - Which Operator SDK version you are using? Could please share those details.
