### ISSUE TITLE
Operators installed in different namespaces with manual approval strategy are upgrading automatically by approving in one namespace.

### ISSUE THREAD

**Issue by AnilKumarBandi27** [operator-framework/operator-sdk#4819]
Hi,

Operators installed on different namespaces in the same cluster with the manual approval strategy are upgrading automatically by approving the upgrade in one namespace.

1. I have installed three operators on two different namespaces with a manual approval strategy.
2. I have released updates for all three operators.
3. I have seen the option upgrade available for all three operators, in both the namespaces.
4. When I clicked on upgrade available for one operator and approved the update. I have seen all the three operators got updated. Also, the same operators which are installed on different namespaces got updated.

Is there a way to avoid operator upgrade until we approve it for each operator?
Why operators in different namespace B are getting upgraded when we approve in namespace A?
Why all the three operators in the same namespace are getting upgraded when we approve one operator?

#### Environment

Ansible Operator:
Operator-SDK v1.4.2
OCP Clusters 4.5.x, 4.6.x, and 4.7,x

**Comment by estroz** [comment]
This sounds like an OLM/OCP question. Can you please reopen this issue in https://github.com/operator-framework/operator-lifecycle-manager? Thanks.
