### ISSUE TITLE
operator-sdk supports Go version 1.16

### ISSUE THREAD

**Issue by Zubnix** [operator-framework/operator-sdk#4828]
#### What did you do?

brew install operator-sdk && operator-sdk init --domain example.com --repo github.com/example/memcached-operator

#### What did you expect to see?

a working operator-sdk

#### What did you see instead? Under which circumstances?

Error: failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v3": go version 'go1.16.3' is incompatible because 'requires 1.13 <= version < 1.16'.

#### Environment

**Operator type:**

/language go 

`$ operator-sdk version`

operator-sdk version: "v1.6.2", commit: "b131ca8ec77c96b9898470eba9560c30af0f23f3", kubernetes version: "v1.19.4", go version: "go1.16.3", GOOS: "linux", GOARCH: "amd64

`$ go version` (if language is Go)

go version go1.16.3 linux/amd64

**Comment by jpriebe** [comment]
I found a workaround - I downgraded go to 1.15 using this technique: https://blog.notmyhostna.me/posts/downgrade-go-installed-with-homebrew/

**Comment by estroz** [comment]
The project and its dependencies have not been upgraded to go 1.16 yet. Support will be coming soon.

**Comment by estroz** [comment]
Additionally you can set `operator-sdk init --skip-go-version-check` to skip this check. Initialization should support go 1.16 out of the box. The check is in place to prevent untested initialization.

**Comment by estroz** [comment]
Kubebuilder issue: https://github.com/kubernetes-sigs/kubebuilder/issues/2067

**Comment by estroz** [comment]
@Zubnix would you mind updating the title to `operator-sdk supports Go version 1.16`? Thanks!

**Comment by sgloutnikov** [comment]
The standard `brew` install on MacOS looks to be broken as well at the moment until the 1.16 support is in. The install depends on the `go` formula which points to `1.16`.  Workaround with `1.15` installed:

`brew install --ignore-dependencies operator-sdk`

**Comment by sTb1337** [comment]
i am also having this problem.. *bump*

**Comment by gadiener** [comment]
Hi @estroz, 
can we reopen this issue, please? I'm having the same issue pointed out by @sTb1337. 
Thanks

**Comment by gadiener** [comment]
I was able to use the CLI with Go 1.16. I think the problem is in the documentation, we need to update the docs in here https://sdk.operatorframework.io/docs/building-operators/golang/installation/ to specify the requirement of Go 1.16.

**Comment by estroz** [comment]
Can you create a new issue specific to the brew issues you're seeing?

/cc @jmrodri @sujil02

**Comment by nmahajan-jpmc** [comment]
@gadiener I  just tried this and got the same issue. I am on go 1.17. and am getting the same error
_"failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v3": go version 'go1.17' is incompatible"_
so did you do something special to use the cli?

**Comment by gadiener** [comment]
@nmahajan-jpmc I'm using go 1.16, no special arguments.

**Comment by quangthe** [comment]
It works with Go 1.16 on Mac Big Sur. The document said Go 1.15 🤔

`go version
go version go1.16.8 darwin/amd64`

`operator-sdk version
operator-sdk version: "v1.12.0", commit: "d3b2761afdb78f629a7eaf4461b0fb8ae3b02860", kubernetes version: "v1.21", go version: "go1.17", GOOS: "darwin", GOARCH: "amd64"`

`operator-sdk init --domain example.com --repo gitlab.com/go-labs-101/memcached-operator
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.9.2
go: downloading github.com/evanphx/json-patch v0.5.2
go: downloading k8s.io/client-go v1.5.2
Update dependencies:
$ go mod tidy
go: downloading github.com/onsi/gomega v1.13.0
go: downloading github.com/go-logr/zapr v0.4.0
go: downloading go.uber.org/zap v1.17.0
go: downloading github.com/Azure/go-autorest v14.2.0+incompatible
go: downloading go.uber.org/goleak v1.1.10
go: downloading cloud.google.com/go v0.54.0
go: downloading gopkg.in/check.v1 v1.0.0-20200227125254-8fa46927fb4f
go: downloading github.com/Azure/go-autorest/autorest v0.11.12
go: downloading golang.org/x/lint v0.0.0-20200302205851-738671d3881b
go: downloading github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e
go: downloading go.uber.org/atomic v1.7.0
go: downloading go.uber.org/multierr v1.6.0
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/Azure/go-autorest/autorest/adal v0.9.5
go: downloading github.com/Azure/go-autorest/autorest/mocks v0.4.1
go: downloading github.com/Azure/go-autorest/logger v0.2.0
go: downloading github.com/Azure/go-autorest/tracing v0.6.0
go: downloading github.com/Azure/go-autorest/autorest/date v0.3.0
go: downloading github.com/form3tech-oss/jwt-go v3.2.2+incompatible
Next: define a resource with:
$ operator-sdk create api`

**Comment by swallretu** [comment]
i also hit this issue. firstly i used operator-sdk v1.1.6.0 & go 1.17, then i  used brew unlink/link downgrade my mac go version to 1.16
```
➜  memcached-operator go version
go version go1.16.13 darwin/amd64
➜  memcached-operator operator-sdk version
operator-sdk version: "v1.16.0", commit: "560044140c4f3d88677e4ef2872931f5bb97f255", kubernetes version: "v1.21", go version: "go1.17.5", GOOS: "darwin", GOARCH: "amd64"
```
after these when i run `operator-sdk create api --group cache --version v1alpha1 --kind Memcached --resource --controller` still hit error, in this time i also tried re-install go & operator-sdk but all no works。then i reviewed the error message, i found `xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun`, that because my xcode is not the latest version, then i update my xcode tools. finally `operator-sdk create api` was success in my mac. 
```
➜  memcached-operator operator-sdk create api --group cache --version v1alpha1 --kind Memcached --resource --controller
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
api/v1alpha1/memcached_types.go
controllers/memcached_controller.go
Update dependencies:
$ go mod tidy
Running make:
$ make generate
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: failed to create API: unable to run post-scaffold tasks of "base.go.kubebuilder.io/v3": exit status 1
```
successful output
```
➜  memcached-operator operator-sdk init --domain example.com --repo github.com/example/memcached-operator
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.10.0
Update dependencies:
$ go mod tidy
Next: define a resource with:
$ operator-sdk create api
➜  memcached-operator operator-sdk create api --group cache --version v1alpha1 --kind Memcached --resource --controller
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
api/v1alpha1/memcached_types.go
controllers/memcached_controller.go
Update dependencies:
$ go mod tidy
Running make:
$ make generate
go: creating new go.mod: module tmp
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.7.0
go: downloading sigs.k8s.io/controller-tools v0.7.0
go: downloading github.com/spf13/cobra v1.2.1
go: downloading golang.org/x/tools v0.1.5
go: downloading github.com/fatih/color v1.12.0
go: downloading k8s.io/api v0.22.2
go: downloading k8s.io/apimachinery v0.22.2
go: downloading k8s.io/apiextensions-apiserver v0.22.2
go: downloading github.com/gobuffalo/flect v0.2.3
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading k8s.io/utils v0.0.0-20210819203725-bdf08cb9a70a
go: downloading golang.org/x/sys v0.0.0-20210616094352-59db8d763f22
go: downloading github.com/google/go-cmp v0.5.6
go: downloading golang.org/x/mod v0.4.2
go get: added sigs.k8s.io/controller-tools v0.7.0
/Users/qujianfei/gitProject/go_local/operator/memcached-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
Next: implement your new API and generate the manifests (e.g. CRDs,CRs) with:
$ make manifests
➜  memcached-operator go version
go version go1.16.13 darwin/amd64
➜  memcached-operator operator-sdk version
operator-sdk version: "v1.16.0", commit: "560044140c4f3d88677e4ef2872931f5bb97f255", kubernetes version: "v1.21", go version: "go1.17.5", GOOS: "darwin", GOARCH: "amd64"
➜  memcached-operator
```
