### ISSUE TITLE
operator-sdk run bundle with an image from the registry

### ISSUE THREAD

**Issue by max3903** [operator-framework/operator-sdk#4830]
## Type of question

Best practices
Open question

## Question

How can I run a bundle from the OpenShift internal registry?

#### What did you do?

I created an operator for a private application.
The application, the operator and the bundle images are being built by my OKD instance and stored in the internal registry.

I ran:
```
export VERSION=0.0.1
export BUNDLE_IMG="image-registry.openshift-image-registry.svc:5000/my-operator/my-operator-bundle:$VERSION"
operator-sdk run bundle $BUNDLE_IMG
```

#### What did you expect to see?

My operator being created and installed in the list of "Installed Operators"

#### What did you see instead? Under which circumstances?

```
$ operator-sdk run bundle $BUNDLE_IMG
FATA[0001] Failed to run bundle: pull bundle image: error pulling image image-registry.openshift-image-registry.svc:5000/my-operator/my-operator-bundle:0.0.1: error resolving name : failed to do request: Head "https://image-registry.openshift-image-registry.svc:5000/v2/my-operator/my-operator-bundle/manifests/0.0.1": dial tcp: lookup image-registry.openshift-image-registry.svc on 127.0.0.53:53: no such host 
```

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

OKD 4.7.0-0.okd-2021-04-11-124433

```
$ operator-sdk version
operator-sdk version: "v1.5.0", commit: "98f30d59ade2d911a7a8c76f0169a7de0dec37a0", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"2513fdbb36e2ddf13bc0b17460151c03eb3a3547", GitTreeState:"clean", BuildDate:"2021-04-09T04:34:48Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-1056+c8905da1d144e4-dirty", GitCommit:"c8905da1d144e4625c8355643d8c034692accdcd", GitTreeState:"dirty", BuildDate:"2021-04-07T09:21:03Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by max3903** [comment]
@estroz Thanks for the reply. I will have to check on how to do this. Hopefully by the end of the month.

**Comment by vhosakot** [comment]
I see same issue and `operator-sdk` isn't pulling image from docker hub. Even though the [docs](https://sdk.operatorframework.io/docs/olm-integration/cli-overview/#private-bundle-and-catalog-image-registries) say:
> By default, projects are configured to push to and pull from a [docker.io](https://hub.docker.com/) registry ...

it appears this is not the case and I see this failure:
```
% operator-sdk run bundle vhosakot/nginx-operator-bundle:v0.0.1
INFO[0000] trying next host                              error="failed to do request: Head \"https://vhosakot/v2/nginx-operator-bundle/manifests/v0.0.1\\": dial tcp: lookup vhosakot: no such host" host=vhosakot
FATA[0000] Failed to run bundle: pull bundle image: error pulling image vhosakot/nginx-operator-bundle:v0.0.1: error resolving name for image ref vhosakot/nginx-operator-bundle:v0.0.1: failed to do request: Head "https://vhosakot/v2/nginx-operator-bundle/manifests/v0.0.1": dial tcp: lookup vhosakot: no such host
```

But, the above image `vhosakot/nginx-operator-bundle:v0.0.1` can be pulled successfully [from docker hub](https://hub.docker.com/r/vhosakot/nginx-operator-bundle/tags) **without** `operator-sdk` and **without** logging in:

```
% docker logout

% docker pull vhosakot/nginx-operator-bundle:v0.0.1
v0.0.1: Pulling from vhosakot/nginx-operator-bundle
cb0203051ca7: Pull complete 
e9003718854e: Pull complete 
e74c3b37fda4: Pull complete 
Digest: sha256:51446129be61b46744279df3b1f0d7643fe165e54de9013cee94292734ec081d
Status: Downloaded newer image for vhosakot/nginx-operator-bundle:v0.0.1
docker.io/vhosakot/nginx-operator-bundle:v0.0.1

% docker images
REPOSITORY                       TAG       IMAGE ID       CREATED             SIZE
vhosakot/nginx-operator-bundle   v0.0.1    9dd77c503ae3   About an hour ago   13.3kB
```

I referred https://sdk.operatorframework.io/docs/building-operators/helm/quickstart/ and did the following steps (used `vhosakot` instead of `example.com`):
```
mkdir nginx-operator
cd nginx-operator
operator-sdk init --domain vhosakot --plugins helm
operator-sdk create api --group demo --version v1alpha1 --kind Nginx
make docker-build docker-push IMG="vhosakot/nginx-operator:v0.0.1"
```
`operator-sdk olm install` failed and I installed it using the [steps in this comment](https://github.com/operator-framework/operator-sdk/issues/5951#issuecomment-1189896347).
```
% operator-sdk olm install
INFO[0004] Fetching CRDs for version "latest"           
INFO[0004] Fetching resources for resolved version "latest"
FATA[0007] Failed to install OLM version "latest": detected existing OLM resources: OLM must be completely uninstalled before installation

kubectl create -f https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/crds.yaml
kubectl create -f https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/olm.yaml

make bundle IMG="vhosakot/nginx-operator:v0.0.1"
make bundle-build bundle-push IMG="vhosakot/nginx-operator:v0.0.1"
```
Below is the error when pulling the `vhosakot/nginx-operator-bundle:v0.0.1` image from docker hub:
```
% operator-sdk run bundle vhosakot/nginx-operator-bundle:v0.0.1
INFO[0000] trying next host                              error="failed to do request: Head \"https://vhosakot/v2/nginx-operator-bundle/manifests/v0.0.1\\": dial tcp: lookup vhosakot: no such host" host=vhosakot
FATA[0000] Failed to run bundle: pull bundle image: error pulling image vhosakot/nginx-operator-bundle:v0.0.1: error resolving name for image ref vhosakot/nginx-operator-bundle:v0.0.1: failed to do request: Head "https://vhosakot/v2/nginx-operator-bundle/manifests/v0.0.1": dial tcp: lookup vhosakot: no such host
```
Is there any solution / workaround for this issue?

**Comment by vhosakot** [comment]
update for previous comment https://github.com/operator-framework/operator-sdk/issues/4830#issuecomment-1487003198:

I'm able to run the operator-sdk bundle by prefixing `docker.io` like `operator-sdk run bundle docker.io/vhosakot/nginx-operator-bundle:v0.0.1`.

```
% operator-sdk run bundle --help                                                        
...
If using a docker.io image, you must specify docker.io(/<namespace>)?/<bundle-image-name>:<tag>.
...
```

But I see many such pods failing and restarting:
```
% kubectl get pods | grep 20ed3bdb54db8de8b2a12 | wc -l
    1232
```

<img width="1297" alt="Screenshot 2023-03-28 at 5 32 42 PM" src="https://user-images.githubusercontent.com/8882663/228373160-9deaa8ff-3569-42f9-8151-d10909cacaa7.png">

I see this error in the above pods like:

`% kubectl logs 20ed3bdb54db8de8b2a12deaafa934b3aca92f140692f73cd07a18ccdfvt6ks`
`Error: error loading manifests from directory: ConfigMap "20ed3bdb54db8de8b2a12deaafa934b3aca92f140692f73cd07a18ccdf3af79" is invalid: [data[demo.vhosakot_nginxes.yaml]: Invalid value: "demo.vhosakot_nginxes.yaml": duplicate of key present in binaryData, data[nginx-operator-controller-manager-metrics-service_v1_service.yaml]: Invalid value: "nginx-operator-controller-manager-metrics-service_v1_service.yaml": duplicate of key present in binaryData, data[nginx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml]: Invalid value: "nginx-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml": duplicate of key present in binaryData, data[nginx-operator.clusterserviceversion.yaml]: Invalid value: "nginx-operator.clusterserviceversion.yaml": duplicate of key present in binaryData]`
