### ISSUE TITLE
Clarify resyncPeriod & ensure 5 seconds is a good default value

### ISSUE THREAD

**Issue by benjaminapetersen** [operator-framework/operator-sdk#484]
The user guide implies `resyncPeriod` can default to 5 seconds.  Is this excessive?  If a number of operators are running on a cluster, will the frequent listing of resources cause strain?  Perhaps there are some application-specific guidelines that might ensure sensible values are chosen.

**Comment by shawn-hurley** [comment]
Hi Ben,

I believe that once we move to controller runtime we will be using their defaults. I believe that this will be more in line with every other controller. 

You can find these defaults here https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager#Options.

**Comment by benjaminapetersen** [comment]
Great that's helpful! 

So meanwhile, any suggestions to find a middle ground between the `10hrs` default per `controller-runtime` and the `5secods` given in the examples?  I'm guessing most should land somewhere in the middle.

**Comment by deads2k** [comment]
@benjaminapetersen you should set the value to something very high, 10-24 hours.  A tight resync period will hide bugs in your controller around proper error handling and is unnecessarily expensive.  A resync does not contact the server for fresh data.  It iterates over all cached values and re-adds them to the processing queue.  It can hide logic that doesn't properly backoff and retry on errors.

**Comment by benjaminapetersen** [comment]
@deads2k great, that is the nature of my question.  I think the examples should be updated ASAP with a clear explanation about this value.  I've looked over a lot of the operators springing up under `github.com/openshift`, I think all of them leave a `5 second` resync (per the user guide examples).

**Comment by LiliC** [comment]
> you should set the value to something very high, 10-24 hours. A tight resync period will hide bugs in your controller around proper error handling and is unnecessarily expensive.

I agree with @deads2k on this, but just wanted to add that sometimes it's not really necessary to have a resync period at all and it can be set to 0. You only need a resync period if you’re actually reconciling something external to Kubernetes.

**Comment by zaidenwerg** [comment]
> You only need a resync period if you’re actually reconciling something external to Kubernetes.

Hi, @lilic
We want to develop an operator that will sync and reconcile the status of a CRD and configuration of StorageClasses between our system and many kubernetes clusters.

I have read comments by you and by @camilamacedo86, here and on issue [3086](https://github.com/operator-framework/operator-sdk/issues/3086), that it is not recommended to set SyncPeriod to 5 or even 10 seconds.

Have you encountered a similar use case or a solution? 

Also this issue is quite old and not exactly the same, do you think I should open a new one?
