### ISSUE TITLE
Helm operator image not using newest ubi 8 image, possibly Dependabot bug

### ISSUE THREAD

**Issue by bitscuit** [operator-framework/operator-sdk#4868]
#### What did you do?

Noticed the latest helm-operator image has 2 high security vulnerabilities https://quay.io/repository/operator-framework/helm-operator?tag=latest&tab=tags. 

The latest ubi8 image is `8.3-298.1618432845` https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?gti-tabs=unauthenticated, but I do not think Dependabot is picking this up as the Dockerfile is still using `8.3-298` https://github.com/operator-framework/operator-sdk/blob/master/images/helm-operator/Dockerfile#L20

#### What did you expect to see?

Dockerfile to be using ubi8 image with tag `8.3-298.1618432845` since that fixes the vulnerabilities in `8.3-298`

#### What did you see instead? Under which circumstances?

Dockerfile using `8.3-298` ubi8

#### Environment

**Operator type:**

/language helm

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

#### Possible Solution

Probably a Dependabot issue, but this could be fixed by manually opening PR to update base image for now

**Comment by estroz** [comment]
Closed by #4873
