### ISSUE TITLE
`generate bundle`: explicitly support `.spec.relatedImages` and `.spec.skips`

### ISSUE THREAD

**Issue by estroz** [operator-framework/operator-sdk#4884]
#### Describe the problem you need a feature to resolve.

Recently, two fields not previously officially a part of the ClusterServiceVersion spec were [officially added](https://github.com/operator-framework/api/commit/4f51a5d0bab048fa7d3751396ebef662cf8b69a5):
- `.spec.relatedImages`: list any related images, or other container images that your Operator might require to perform their functions. This list can include operand images as well. All image references should be specified by digest (SHA) and not by tag.
- `.spec.skips`: the names of one or more CSVs that should be skipped in a catalog's upgrade graph. These values should match the `.metadata.name` field of the skipped CSV.

It is important to note that both fields are only used during catalog creation and play no part in cluster runtime.

#### Describe the solution you'd like.

Document how these fields should be set. They are currently carried over to bundles generated by `operator-sdk generate bundle` when set in the base CSV (`config/manifests/bases/<package name>.clusterserviceversion.yaml`).

/kind feature

**Comment by joelanford** [comment]
> All image references should be specified by digest (SHA) and not by tag.

It would be interesting to see if tags (i.e. non-SHAs) could be automatically looked up and rendered as SHAs in the generated CSV in the bundle.

**Comment by estroz** [comment]
@joelanford it's possibly quite easy by shelling out to a container tool or using containerd libs, but I'm hesitant to add such a feature given operator-sdk's history with internalizing such things. Still worth considering.

**Comment by djzager** [comment]
While I think it would be possible, and maybe nice to have, the ability to auto-populate the digest via something like (`--image-by-digest=true`)...I think it would be more straightforward to think through how to say `kustomize edit set image my-image=${my_image_digest}` and the CSV generated from: `kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version ${OPERATOR_VERSION} --output-dir ${BUNDLE_OUTPUT_DIR} ${BUNDLE_METADATA_OPTS}` include the images referenced by digest.

**Comment by tlwu2013** [comment]
> @joelanford it's possibly quite easy by shelling out to a container tool or using containerd libs, but I'm hesitant to add such a feature given operator-sdk's history with internalizing such things. Still worth considering.

+1 on the idea Joe brought up. That could bring a huge improvement in terms of the UX. But also agreed as folks discussed in the community call in tracking that as a separated feature request.

**Comment by estroz** [comment]
If there is interest in a digest lookup feature, feel free to create a separate issue.

I fully agree with @djzager here due to the can of worms image lookup can be. Proxied images? Custom registry CA's? Image tool configuration? Which image tag does `operator-sdk` use from a list returned by `docker inspect --format '{{.RepoDigests}}' <image>`? I'd rather just document that a digest tag is needed and how to get it with common image tools (which [exists already](https://master.sdk.operatorframework.io/docs/olm-integration/generation/#csv-fields)) and call it a day.

**Comment by tlwu2013** [comment]
This feature is [designed and implemented in issue #5511](https://github.com/operator-framework/operator-sdk/issues/5511) and released in [version 1.17](https://github.com/operator-framework/operator-sdk/milestone/37?closed=1).
