### ISSUE TITLE
enable per custom resource vault password usage in ansible operator 

### ISSUE THREAD

**Issue by absynth76** [operator-framework/operator-sdk#4890]
#### Describe the problem you need a feature to resolve.

As an ansible operator user, I would like to be able to configure the vault password used to eventually decrypt secrets encrypted with ansible-vault.

#### Describe the solution you'd like.

I would like to be able to put a specific secret name in the custom resource watched by the operator, like: "vaultPasswordSecretRef" or similar

Based on that parameter, during the reconciliation, the underlying ansible command would be launched with the "-e vault-password=<my_vault_password_secret_ref.data.password|b64decode>" (or dumping a temporary file in the container and using vault-password-file).

This way I would be able to use one of the most interesting feature of ansible; encryption of parameters, and this on a per custom resource bases. 

The only way I found at the moment is to declare the default vault password on an environment variable at operator deployment time, which is not multi-tenant (I can only use one password per ansible operator deployment). 

I did not consider vault password id in the solution, I would like to keep - `one secret = one set of custom resources` - logic.

/language ansible

**Comment by absynth76** [comment]
Adding on the story, 

- the Secret reference(s) could be a list instead of a single reference
- the key used in the Secret data could be a parameter, potentially a list - with a defaulted value - default value could be all keys values or a single key value 
Secret reference sample:
```
apiVersion: v1
kind: Secret
type: Opaque
data:
  vaultPassword1: "b64(password1)"
  vaultPassword2: "b64(password2)"
  vaultPassword3: "b64(password3)"
```

- the CustomResource could read the secret references in multiple ways, maybe the specifications is not the most appropriate, it could also be "a" or "some" annotation(s), this way it will not impact the CRD specifications at all. For example something like:
```
ansible.sdk.operatorframework.io/vaultSecretReference<Name>:  <Secret name in the same namespace as the CR>
ansible.sdk.operatorframework.io/vaultSecretReference<Name>Keys: <comma separated list of keys to consume - default to all (or "password" for example)>
```

**Comment by absynth76** [comment]
@fabianvf, @camilamacedo86 
Sorry to disturb you, I think you are relevant people to contact when it comes to ansible operators, but could you give your opinion on this idea? Would it be possible? Do you think it worth it?

**Comment by absynth76** [comment]
With who that discussion must be initiated? Can somebody act upon it ?

**Comment by estroz** [comment]
@fabianvf and @asmacdo would be the best contacts here.
