### ISSUE TITLE
[Helm] Reconciliation does not replace json lists but adds new items instead

### ISSUE THREAD

**Issue by SimonBaeumer** [operator-framework/operator-sdk#4901]
## Bug Report

If an kubernetes object is watched and reconciled by the Helm Chart operator the reconciliation does not replace json lists, instead it adds new items as the used patch type seems to just work like this.

## Steps to reproduce

Create a nginx helm chart operator

```
$ mkdir -p /tmp/nginx-operator
$ cd /tmp/nginx-operator
$ operator-sdk init --domain example.com --plugins helm
$ operator-sdk create api --group demo --version v1alpha1 --kind Nginx --helm-chart nginx --helm-chart-repo https://charts.bitnami.com/bitnami

# Start the operator
$ make install run
```

Reproduce it: 

```
# install an nginx instance
$ kubectl apply -f config/samples/demo_v1alpha1_nginx.yaml

# change the nginx port from 80 to 81:
$ kubectl edit svc nginx-sample
```

Now spectate logs generated by the controller:

```
{"level":"error","ts":1620637792.814479,"logger":"helm.controller","msg":"Failed to reconcile release","namespace":"default","name":"nginx-sample","apiVersion":"demo.example.com/v1alpha1","kind":"Nginx","release":"nginx-sample","error":"patch error: Service \"nginx-sample\" is invalid: spec.ports[1].name: Duplicate value: \"http\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/operator-framework/operator-sdk/internal/helm/controller.HelmOperatorReconciler.Reconcile\n\toperator-sdk-20210313-3771-u8kq3b/internal/helm/controller/reconcile.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:297\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:252\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:215\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}
```

Extracted error msg form Helm: `Service \"nginx-sample\" is invalid: spec.ports[1].name: Duplicate value: \"http\"`

The problem seems to be that a `StrategicMergePatchType` does not replace lists, instead it adds an item to it.

I.e. changing the port in the service to `81` inside the helm-chart results in an invalid patch like this which includes the manually changed value and the original value derived from the helm chart (here duplicate port names are invalid):

```
apiVersion: v1
kind: Service
spec:
  ports:
  - name: http
    nodePort: 32489
    port: 80
    protocol: TCP
    targetPort: http
  - name: http
    nodePort: 32489
    port: 81
    protocol: TCP
    targetPort: http
```

#### Environment

**Operator type:**

/language helm 

**Kubernetes cluster type:**

vanilla

`$ operator-sdk version`

`operator-sdk version: "v1.5.0", commit: "98f30d59ade2d911a7a8c76f0169a7de0dec37a0", kubernetes version: "v1.19.4", go version: "go1.16.1", GOOS: "darwin", GOARCH: "amd64"`

`$ go version` (if language is Go)

`go version go1.16.2 darwin/amd64`

`$ kubectl version`

`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`

#### Possible Solution

Use `JSONPatchType` worked for me, tested it with a simple hard coded fix for Service objects in [manager.go](https://github.com/operator-framework/operator-sdk/blob/master/internal/helm/release/manager.go#L313-L317):

```
if isUnstructured || isCRD || existing.GetObjectKind().GroupVersionKind().Kind == "Service" {
    // fall back to generic JSON merge patch
    patch, err := createJSONMergePatch(existingJSON, expectedJSON)
    return patch, apitypes.JSONPatchType, err
}
```

**Comment by VenkatRamaraju** [comment]
Hi @SimonBaeumer,

I got the following logs while attempting to reproduce the issue in `operator-sdk v1.9.0`:

```{"level":"error","ts":1625071555.9902122,"logger":"helm.controller","msg":"Release failed","namespace":"default","name":"nginx-sample","apiVersion":"demo.example.com/v1alpha1","kind":"Nginx","release":"nginx-sample","error":"failed upgrade (cannot patch \"nginx-sample\" with kind Service: Service \"nginx-sample\" is invalid: spec.ports[1].name: Duplicate value: \"http\") and failed rollback: failed to replace object: Service \"nginx-sample\" is invalid: spec.clusterIP: Invalid value: \"\": field is immutable" .. }```

I believe this has to do with using `kubectl apply` and `kubectl edit` in tandem.

The service was created by **applying** the CR, i.e., 
``kubectl apply -f config/samples/demo_v1alpha1_nginx.yaml``

The `edit` command works directly on cluster resources and does not update the annotations that the `apply` command depends on. It looks like `kubectl edit svc` thinks the service ports don't exist and attempts to add its own, causing the name conflict we see. If `kubectl apply` was used to create the resource, it is generally suggested to use `kubectl apply` to update the resources as well.

If we change the service port in the CR and `apply`, the upgrades/reconciliations occur correctly without error. 

Since `apply` also generates a `StrategicMergePatchType` and the `apply` command causes successful upgrades, I do not think the error has to do with the `StrategicMergePatchType`.

**Comment by SimonBaeumer** [comment]
Hey @VenkatRamaraju,
I double-checked it and it looks like you are correct.
As this is not an issue regarding the helm-operator I'll close this. 

Thanks for your investigations, did not knew about these differences!
