### ISSUE TITLE
Generated Makefile uses bash-only construct but doesn't specify SHELL=bash

### ISSUE THREAD

**Issue by adrian-kiwibank** [operator-framework/operator-sdk#4905]
#### What did you do?

make test

#### What did you expect to see?

test execution output

#### What did you see instead? Under which circumstances?

When /bin/sh is not an alias for bash:
```sh
mkdir -p /home/vagrant/src/cip/apps/kubernetes-namespace-enhancer/testbin
test -f /home/vagrant/src/cip/apps/kubernetes-namespace-enhancer/testbin/setup-envtest.sh || curl -sSLo /home/vagrant/src/cip/apps/kubernetes-na
mespace-enhancer/testbin/setup-envtest.sh https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/v0.7.2/hack/setup-envtest.sh
source /home/vagrant/src/cip/apps/kubernetes-namespace-enhancer/testbin/setup-envtest.sh; fetch_envtest_tools /home/vagrant/src/cip/apps/kubernetes-namespace-enhancer/testbin; setup_envtest_env /home/vagrant/src/cip/apps/kubernetes-namespace-enhancer/testbin; go test ./... -coverprofile cover.out
/bin/sh: 1: source: not found
/bin/sh: 1: fetch_envtest_tools: not found
/bin/sh: 1: setup_envtest_env: not found
```

#### Environment

```sh
 $ uname -a
Linux Vagrant-KB36QG3G2L 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
**Operator type:**
```

/language go

**Kubernetes cluster type:**

 vanilla

`$ operator-sdk version`

`operator-sdk version: "v1.6.2", commit: "b131ca8ec77c96b9898470eba9560c30af0f23f3", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"`

`$ go version` (if language is Go)

go version go1.16.3 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

#### Possible Solution

```diff
diff --git a/internal/plugins/envtest/v1/init.go b/internal/plugins/envtest/v1/init.go
index e4638ed4..dece6671 100644
--- a/internal/plugins/envtest/v1/init.go
+++ b/internal/plugins/envtest/v1/init.go
@@ -69,6 +69,7 @@ const (
 test: manifests generate fmt vet
        go test ./... -coverprofile cover.out`
        makefileTestTarget = `# Run tests
+SHELL = /bin/bash
 ENVTEST_ASSETS_DIR = $(shell pwd)/testbin
 test: manifests generate fmt vet
        mkdir -p $(ENVTEST_ASSETS_DIR)
```

**Comment by estroz** [comment]
This was [fixed](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.7.1/#gov3-set-the-makefiles-shell-variable-to-the-systems-bash-binary) in the most recent release.

**Comment by estroz** [comment]
master's testdata [has the fix](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/Makefile#L53).

**Comment by adrian-kiwibank** [comment]
> master's testdata [has the fix](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/Makefile#L53). If you try to initialize a new project, you'll also see the fix created.

Thanks, I didn't see the change where I was expecting to but I have now noted that the generated Makefile now has changed.
