### ISSUE TITLE
Can't generate CRD with a required spec

### ISSUE THREAD

**Issue by paterczm** [operator-framework/operator-sdk#4912]
Hello!

I'm trying to use kubebuilder required marker on the Spec field, but it is being ignored when I do `make manifests` in an operator-sdk golang operator project. The markers work as expected inside the Spec, but not on the Spec field. From what I can see, CRD supports marking the Spec as required. Am I doing something wrong?

```
$ operator-sdk version
operator-sdk version: "v1.4.2", commit: "4b083393be65589358b3e0416573df04f4ae8d9b", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"

type CustomResourceExampleSpec struct {
	(...)
}

//+kubebuilder:resource:path=customresourceexample,scope=Cluster
type CustomResourceExample struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// +kubebuilder:validation:Required
	Spec   CustomResourceExampleSpec   `json:"spec,omitempty"`
	Status CustomResourceExampleStatus `json:"status,omitempty"`
}
```

**Comment by estroz** [comment]
You need to remove `omitempty` from that field's JSON tag. See https://github.com/kubernetes-sigs/controller-tools/issues/479.
