### ISSUE TITLE
FATA[0004] failed to initialize project: unable to scaffold with "base.go.kubebuilder.io/v3": exit status 2

### ISSUE THREAD

**Issue by rajendragosavi** [operator-framework/operator-sdk#4919]
#### What did you do?
I tried to create new operator - using operator-sdk.

I hit the command - operator-sdk init --verbose --owner rajendra_gosavi --project-name my-first-opeator

#### What did you expect to see?
The Operator should have created the opeartor and boilerplate code related.

#### What did you see instead? Under which circumstances?
I got an error -

```

DEBU[0000] Debug logging is set
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.8.3
internal/unsafeheader
k8s.io/apimachinery/pkg/selection
unicode/utf8
internal/nettrace
unicode/utf16
crypto/internal/subtle
encoding
math/bits
internal/race
container/list
unicode
# internal/unsafeheader
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# k8s.io/apimachinery/pkg/selection
compile: version "go1.15.6" does not match go tool version "go1.15.12"
runtime/internal/sys
# unicode/utf16
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# internal/nettrace
compile: version "go1.15.6" does not match go tool version "go1.15.12"
vendor/golang.org/x/crypto/cryptobyte/asn1
# unicode/utf8
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# math/bits
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# encoding
compile: version "go1.15.6" does not match go tool version "go1.15.12"
internal/cpu
crypto/subtle
sync/atomic
vendor/golang.org/x/crypto/internal/subtle
runtime/internal/atomic
# unicode
compile: version "go1.15.6" does not match go tool version "go1.15.12"
golang.org/x/sys/internal/unsafeheader
# internal/race
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# container/list
compile: version "go1.15.6" does not match go tool version "go1.15.12"
k8s.io/utils/integer
# crypto/internal/subtle
compile: version "go1.15.6" does not match go tool version "go1.15.12"
google.golang.org/protobuf/internal/flags
# vendor/golang.org/x/crypto/cryptobyte/asn1
compile: version "go1.15.6" does not match go tool version "go1.15.12"
github.com/google/go-cmp/cmp/internal/flags
k8s.io/utils/buffer
# runtime/internal/sys
compile: version "go1.15.6" does not match go tool version "go1.15.12"
k8s.io/apimachinery/pkg/types
# crypto/subtle
compile: version "go1.15.6" does not match go tool version "go1.15.12"
runtime/cgo
# vendor/golang.org/x/crypto/internal/subtle
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# k8s.io/utils/integer
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# google.golang.org/protobuf/internal/flags
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# github.com/google/go-cmp/cmp/internal/flags
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# internal/cpu
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# golang.org/x/sys/internal/unsafeheader
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# runtime/internal/atomic
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# k8s.io/apimachinery/pkg/types
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# sync/atomic
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# k8s.io/utils/buffer
compile: version "go1.15.6" does not match go tool version "go1.15.12"
# runtime/cgo
compile: version "go1.15.6" does not match go tool version "go1.15.12"
Error: failed to initialize project: unable to scaffold with "base.go.kubebuilder.io/v3": exit status 2
Usage:
  operator-sdk init [flags]

Examples:
  # Initialize a new project with your domain and name in copyright
  operator-sdk init --plugins go/v3 --domain example.org --owner "Your name"

  # Initialize a new project defining an specific project version
  operator-sdk init --plugins go/v3 --project-version 3


Flags:
      --component-config         create a versioned ComponentConfig file, may be 'true' or 'false'
      --domain string            domain for groups (default "my.domain")
      --fetch-deps               ensure dependencies are downloaded (default true)
  -h, --help                     help for init
      --license string           license to use to boilerplate, may be one of 'apache2', 'none' (default "apache2")
      --owner string             owner to add to the copyright
      --project-name string      name of this project
      --project-version string   project version (default "3")
      --repo string              name to use for go module (e.g., github.com/user/repo), defaults to the go package of the current working directory.
      --skip-go-version-check    if specified, skip checking the Go version

Global Flags:
      --plugins strings   plugin keys to be used for this subcommand execution
      --verbose           Enable verbose logging

FATA[0004] failed to initialize project: unable to scaffold with "base.go.kubebuilder.io/v3": exit status 2

```

#### Environment
go version - go version go1.15.12 darwin/amd64
Opeartor version - "v1.7.2", commit: "6db9787d4e9ff63f344e23bfa387133112bda56b", kubernetes version: "v1.19.4", go version: "go1.16.3", GOOS: "darwin", GOARCH: "amd64"

**Operator type:**

**Kubernetes cluster type:**
**EKS - Kubernetes version - 1.19**

`$ operator-sdk version`
"v1.7.2", commit: "6db9787d4e9ff63f344e23bfa387133112bda56b", kubernetes version: "v1.19.4", go version: "go1.16.3", GOOS: "darwin", GOARCH: "amd64"

`$ go version` (if language is Go)
go1.15.12 darwin/amd64

`$ kubectl version`
**Client Version**: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}

**Server Version**: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by rajendragosavi** [comment]
I do not have any .git .md files. The directory just has go.mod file created after go mod init

**Comment by rashmigottipati** [comment]
Hi @rajendragosavi,

Looks like the error is occurring due to incompatible go version. Suggest bumping your go version from go1.15.12 to go1.16.4 and then re-trying the `init` command on a fresh directory.

**Comment by rajendragosavi** [comment]
@rashmigottipati  I tried with 1.16.3 it does not work either. 
Error: failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v3": go version 'go1.16.3' is incompatible because 'requires 1.13 <= version < 1.16'. You can skip this check using the --skip-go-version-check flag

**Comment by rashmigottipati** [comment]
@rajendragosavi Can you try setting the flag `operator-sdk init --skip-go-version-check` and skip the check? 

The project dependencies aren't upgraded to go 1.16 yet.

**Comment by rashmigottipati** [comment]
PR to upgrade go version in kubebuilder: https://github.com/kubernetes-sigs/kubebuilder/pull/2182

**Comment by rashmigottipati** [comment]
I tried it on my end and it's able to initialize it when I skip the version. 

Please feel free to close this issue if it's resolved.

**Comment by rashmigottipati** [comment]
Also curious if you have installed operator-sdk using homebrew and if that's causing any env issues. If your issue is not resolved yet, can you try installing the binary from the releases page instead: https://github.com/operator-framework/operator-sdk/releases and give it a shot?

**Comment by rashmigottipati** [comment]
Here's some more info: https://stackoverflow.com/questions/46693653/compile-version-go1-9-does-not-match-go-tool-version-go1-9-1/53661370#53661370v 

Closing this issue, please feel to re-open if issue persists. Thanks!
