### ISSUE TITLE
Create API is not calling make targets and is not generating the CRD

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4928]
#### What did you do?

Create an API : ` operator-sdk create api --group=cache --kind=Test2 --version=v1
`

#### What did you expect to see?

The target `make manifests` be called as a post-action of the command. 

#### What did you see instead? Under which circumstances?

That has not been called and then we cannot check the crd created. 
 
#### Environment

**Operator type:**

 /language go 

`$ operator-sdk version`

operator-sdk version: "v1.5.0-113-gf5213a34", commit: "f5213a3407f53ea58f425e29de901d73bb63b1cf", kubernetes version: "v1.19.4", go version: "go1.15.2", GOOS: "darwin", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.15.2

#### Possible Solution

The problem seems to be in Kubebuilder: 

https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/api.go#L181-L193

I understand that we should call the target make and make ought to call all targets indeed the manifests one.

**Comment by camilamacedo86** [comment]
c/c @estroz

**Comment by estroz** [comment]
Since you think this is a bug in kubebuilder can you reopen it there? Thanks. I'd be fine with `make manifests` being run if a resource was created.
