### ISSUE TITLE
Create a RoleBinding from the Operator

### ISSUE THREAD

**Issue by eivantsov** [operator-framework/operator-sdk#494]
Maybe I'm missing smth obvious but I have not found RoleBinding in types. The installation of an application that my Operator handles implies creation of a service account and a RoleBinding (to give either admin or edit rights for that SA in a target namespace) that the application will use then.

**Comment by eivantsov** [comment]
@shawn-hurley yes, thanks, worked perfectly well with Deployment and other resources in `apps/v1`

A pointer to RoleBinding and Route will be greatly appreciated though! :)

**Comment by hasbro17** [comment]
@eivantsov You should be able to create a RoleBinding object using the sdk client, similar to how you would create any other core k8s resource like Deployment or Pod:
```Go
import rbacv1 "k8s.io/api/rbac/v1"
...
roleBinding := &rbacv1.RoleBinding{
    TypeMeta: metav1.TypeMeta{
			APIVersion: "rbac.authorization.k8s.io/v1",
			Kind:       "RoleBinding",
		},
		...
}

sdk.Create(roleBinding)
```

And lets use #477 to cover how to add 3rd party resources like Route the sdk scheme.

**Comment by hasbro17** [comment]
Closing for now. Feel free to reopen this if you still have issues creating a RoleBinding via the client.

**Comment by eivantsov** [comment]
@hasbro17 thanks for your help.

I figured it out with deployments and routes. With RoleBinding, however I face the following issue:

```
time="2018-09-18T18:07:36Z" level=error msg="failed to create Che roleBinding : the server could not find the requested resource"
```

My function:

```
func createRoleBinding(cr *v1alpha1.App) *rbac.RoleBinding {
	labels := map[string]string{"app": "che"}
	return &rbac.RoleBinding{
		TypeMeta: metav1.TypeMeta{
			Kind:       "RoleBinding",
			APIVersion: rbac.SchemeGroupVersion.String(),
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "che",
			Namespace: cr.Namespace,
			Labels:    labels,
		},
		Subjects: []rbac.Subject{
			{
				Kind: "ServiceAccount",
				Name: "che",
			},
		},
		RoleRef: rbac.RoleRef{
			Name: "edit",
		},
	}
}
```

In my rbac.yaml:

```
- apiGroups:
  - "*"
  resources:
  - "*"
```

**Comment by eivantsov** [comment]
@hasbro17 @shawn-hurley thanks for your help. I was able to create all objects the operator required.
