### ISSUE TITLE
Can I just update base image version to bump up Golang with ansible operator

### ISSUE THREAD

**Issue by niuxiaojuan-github** [operator-framework/operator-sdk#4942]
## Type of question

General operator-related help

#### What did you do?
My ansible operator is built based on 0.17.2, I'm using base image quay.io/operator-framework/ansible-operator:v0.17.2

I need to upgrade golang to 1.15.7+ to solve security issue, Can I update base image version to v1.5.0 directly? will rest of code work with v1.5.0 base image?

Do I have to restructure my operator for golang upgrade?  Is there easy way to do it?

**Operator type:**
 
/language ansible

**Comment by varshaprasad96** [comment]
@niuxiaojuan-github There have been quite a few changes in the ansible base image from 0.17.x to 1.5.0. You may have to migrate your project to be compatible with the post 1.0+ changes. Here is the migration guide which maybe helpful https://sdk.operatorframework.io/docs/building-operators/ansible/migration/

**Comment by asmacdo** [comment]
+1, that will definitely require manual migration steps.
