### ISSUE TITLE
'operator-sdk run bundle'  can't pull image

### ISSUE THREAD

**Issue by Akiya95** [operator-framework/operator-sdk#4959]
## Bug Report
I use the 'operator-sdk run bundle' command to deploy an operator, but the result shows that it fails to pull the image.  

`
[root@master1 memcached-operator]# operator-sdk run bundle 10.167.14.138:8082/memcached-operator-bundle:v0.0.1 --skip-tls
FATA[0120] Failed to run bundle: create catalog: error creating registry pod: get database path: get index image labels: error pulling image quay.io/operator-framework/upstream-opm-builder:latest: failed to copy: context deadline exceeded
[root@master1 memcached-operator]#
`

#### What did you do?
......  
make docker-build docker-push IMG="10.167.14.138:8082/memcached-operator:v0.0.1"  
make bundle IMG="10.167.14.138:8082/memcached-operator:v0.0.1"  
make bundle-build bundle-push  
operator-sdk run bundle 10.167.14.138:8082/memcached-operator-bundle:v0.0.1 --skip-tls  

#### What did you expect to see?
'operator-sdk run bundle' can successfully pull the image.  

#### What did you see instead? Under which circumstances?
`
[root@master1 memcached-operator]# operator-sdk run bundle 10.167.14.138:8082/memcached-operator-bundle:v0.0.1 --skip-tls
FATA[0120] Failed to run bundle: create catalog: error creating registry pod: get database path: get index image labels: error pulling image quay.io/operator-framework/upstream-opm-builder:latest: failed to copy: context deadline exceeded
[root@master1 memcached-operator]#
`
Before executing the command, the image has been downloaded on the host in advance. And manually executing docker pull can also download normally.
`
[root@master1 memcached-operator]# docker images|grep quay.io/operator-framework/upstream-opm-builder  
quay.io/operator-framework/upstream-opm-builder                             latest                         8e7dff444129        3 weeks ago         64.2MB  
`

#### Environment
`
[root@master1 memcached-operator]# operator-sdk version  
operator-sdk version: "v1.8.0", commit: "d3bd87c6900f70b7df618340e1d63329c7cd651e", kubernetes version: "1.20.2", go version: "go1.16.4", GOOS: "linux", GOARCH: "amd64"
`
`
[root@master1 memcached-operator]# go version   
go version go1.14.7 linux/amd64
`
`
[root@master1 memcached-operator]# git version
git version 2.17.1
`
`
[root@master1 memcached-operator]# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
`

**Operator type:**
go

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

#### Additional context
When I deployed operator(go) for the first time, it was possible to pull the image normally. But when I wanted to deploy the second operator (helm), the above error appeared. Then when I redeployed the first operator (go), the above error also appeared.

**Comment by estroz** [comment]
@Akiya95 what kind of cluster are you using? Are you able to `docker pull` the `upstream-opm-builder` locally?

/triage support

**Comment by Akiya95** [comment]
> @Akiya95 what kind of cluster are you using? Are you able to `docker pull` the `upstream-opm-builder` locally?
> 
> /triage support

Bare-metal k8s deployed by kubespray.
```shell
kubectl version   
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}   
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

Yes

**Comment by akihikokuroda** [comment]
Hi!  I see this problem, too.  I'm not sure if this is a doc issue or code issue.   The command described in `Building Operators`-> `Go` -> `Quickstart` and `Tutorial` 
```
operator-sdk run bundle example.com/memcached-operator-bundle:v0.0.1
```
fails to pull the bundle image.  The argument should be prefixed with the IP address of the registry like (for docker registry case)
```
operator-sdk run bundle docker.io/example.com/memcached-operator-bundle:v0.0.1
```

It is not same (consistent) way to specify the image for the make command
```
make bundle IMG="example.com/memcached-operator:v0.0.1"
```
but it may be easier to change the doc instead of changing the `opertor-sdk run bundle` command.

**Comment by akihikokuroda** [comment]
[`OLM Integration` -> `Bundle Tutorial` ](https://sdk.operatorframework.io/docs/olm-integration/tutorial-bundle/#deploying-an-operator-with-olm) has this 
```
$ make bundle-build bundle-push BUNDLE_IMG=<some-registry>/memcached-operator-bundle:v0.0.1
```
So the dock should be updated.

**Comment by akihikokuroda** [comment]
[OLM Integration->Bundle Tutorial->Testing bundles](https://sdk.operatorframework.io/docs/olm-integration/tutorial-bundle/#testing-bundles) has this.
```
$ operator-sdk run bundle <some-registry>/memcached-operator-bundle:v0.0.1

So the doc should be corrected.
```
