### ISSUE TITLE
Add api group `operators.coreos.com` to `clusterPermissions` by default.

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-sdk#4960]
#### What did you do?

```console
make bundle
```

The CSV `clusterPermissions` does not include api group as `operators.coreos.com`, and this will cause I cannot use OLM to manage this operator.

![image](https://user-images.githubusercontent.com/4461983/120264140-becc2200-c2cf-11eb-8949-80f61ac41edb.png)

#### What did you expect to see?

Suggest add api group `operators.coreos.com` to `clusterPermissions` by default.

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by estroz** [comment]
Are you trying to create subscriptions and catalogsources from within your operator? Otherwise these permissions are not needed.

/triage needs-information

**Comment by gyliu513** [comment]
> Are you trying to create subscriptions and catalogsources from within your operator? Otherwise these permissions are not needed.

@estroz sorry for late, the answer is yes.

**Comment by estroz** [comment]
Not all operators use these resources; in fact most do not. Therefore adding these by default is not useful and is a security hole. Add them to your project only if absolutely necessary.
