### ISSUE TITLE
Wrong repo link for scorecard tests examples

### ISSUE THREAD

**Issue by SimonBaeumer** [operator-framework/operator-sdk#4962]
### What is the URL of the document?

https://sdk.operatorframework.io/docs/advanced-topics/scorecard/custom-tests/#building-test-image

### Which section(s) is the issue in?

`Building test image: `

### What needs fixing?

The link  in the "here" from

> The sample test image repository present here has the following project structure:

links to the operator-sdk repo which does not reflect the given structure of a memcached operator.

**Comment by estroz** [comment]
@jmccormick2001 which repo was that link supposed to link to?
