### ISSUE TITLE
Memcached deployment crashes after applying CR

### ISSUE THREAD

**Issue by mustanish** [operator-framework/operator-sdk#4966]
## Type of question
Trying to setup a go based operator using operator sdk (v1.8.0)

#### What did you do?
I am following this https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/ tutorial to setup a memcached operator

#### What did you expect to see?
I expect to see the exact result mentioned in the tutorial after applying the CR

#### What did you see instead? Under which circumstances?
After running the make deploy command, I can see memcached-operator-controller pod running, which is what I am expecting but when I apply the CR(config/samples/cache_v1alpha1_memcached.yaml) memcached-operator deployment goes into crashLoopBackOff.

#### Environment

**Operator type:**
Go

**Kubernetes cluster type:**

`$ operator-sdk version`

operator-sdk version: "v1.8.0", commit: "d3bd87c6900f70b7df618340e1d63329c7cd651e", kubernetes version: "1.20.2", go version: "go1.16.4", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.15.3 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

#### Additional context
I am using minikube on my local machine for the environment. I have added logs of the failed pod which I get after applying the CR.
[error.txt](https://github.com/operator-framework/operator-sdk/files/6603064/error.txt)

Thanks

**Comment by varshaprasad96** [comment]
@mustanish The error log which you have provided states this while reconciling:
```sh
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```
This is causing seg fault. Can you cross check your sample project with the [testdata](https://github.com/operator-framework/operator-sdk/tree/master/testdata/go/v3/memcached-operator) present in the repository (especially the reconciler logic).

**Comment by asmacdo** [comment]
If you have it handy, could you send me a link to your operator?

**Comment by mustanish** [comment]
@asmacdo, here is the link to operator https://github.com/mustanish/memcached-operator

**Comment by mustanish** [comment]
@varshaprasad96 I followed all the steps in the tutorial, even where it says to replace the generated controller with the one present inside the [testdata](https://github.com/operator-framework/operator-sdk/blob/v1.3.0/testdata/go/v3/memcached-operator/controllers/memcached_controller.go). The reconciler logic is inside the controller, I will try to set up the entire thing again and replace the generated controller with the controller present inside the testdata.

**Comment by varshaprasad96** [comment]
@mustanish I believe the error is probably caused by not instantiating the log ([here](https://github.com/operator-framework/operator-sdk/blob/v1.3.0/testdata/go/v3/memcached-operator/controllers/memcached_controller.go#L60)). Using the `memcached-controller.go` from the master branch would be helpful, as we use the controller-runtime logging. Can you try using the controller code from [here](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/controllers/memcached_controller.go). This would solve the issue.

**Comment by vladsf** [comment]
I have the same problem even with v4 of the sample memcached controller.
