### ISSUE TITLE
How to create webhook for subscriptions without creating an API for it?

### ISSUE THREAD

**Issue by iamniting** [operator-framework/operator-sdk#4967]
## Type of question

How to implement a specific feature

## Question
How to create a webhook for subscriptions?
I wanted to create a webhook for the subscriptions which can mutate channels for specific subscriptions.

#### What did you do?
`operator-sdk create webhook --group operators --version v1alpha1 --kind Subscription --defaulting --programmatic-validation`

#### What did you expect to see?
Webhook for subscription created

#### What did you see instead? Under which circumstances?
FATA[0000] failed to create webhook: unable to inject the resource to "base.go.kubebuilder.io/v3": operator-sdk create webhook requires a previously created API

#### Environment
Fedora

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`
operator-sdk version: "v1.7.2", commit: "6db9787d4e9ff63f344e23bfa387133112bda56b", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)
go version go1.16.3 linux/amd64

`$ oc version`
Client Version: 4.7.7
Server Version: 4.7.7
Kubernetes Version: v1.20.0+c8905da

**Comment by estroz** [comment]
Currently you cannot define one with `operator-sdk create webhook`. We use kubebuilder's `create webhook` command for Go operator projects, for which there is already a feature request for this (https://github.com/kubernetes-sigs/kubebuilder/issues/1999). Once that has been implemented in kubebuilder, operator-sdk will get the same feature via vendoring.

You can write your own admission webhook for Subscriptions using the [`Handler`](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.8.3/pkg/webhook/admission#Handler) interface.
