### ISSUE TITLE
User guide for TLS util pkg

### ISSUE THREAD

**Issue by rithujohn191** [operator-framework/operator-sdk#498]
The newly introduced [`tlsutil` pkg ](https://github.com/operator-framework/operator-sdk/tree/master/pkg/tlsutil) needs docs to inform users about the step by step process of how they can use this package

**Comment by hasbro17** [comment]
We won't be advertising the tlsutil pkg going forward. We'll actually need to remove that from the SDK.

While the tlsutil pkg was a foray into seeing how to make the management of TLS certs easier for operators, there are more tried and tested, complete solutions out there for TLS cert issuance and management e.g [cert-manager](https://github.com/jetstack/cert-manager)
