### ISSUE TITLE
Slow down release cadence?

### ISSUE THREAD

**Issue by jberkhahn** [operator-framework/operator-sdk#4985]
We had an issue come up today that wanted us to rebuild the helm operator image for 1.3.0. Officially we support version n-1, but with a release cadence of every 3 weeks or so that means an operator built ~3 months ago is no longer supported. Should we slow down our release cadence? We originally had a fast cadence to get in the stuff that didn't make it into 1.0.0, is there still a need for this?

**Comment by jberkhahn** [comment]
we're going to discuss this at the next release planning session. We had 2 ideas:

1. Slow down the release cycle (more time before release)
2. Cut a minor version release (1.2.0 -> 1.2.1 instead of 1.3)

**Comment by mhrivnak** [comment]
The SDK supports various "day 2" operations, such as adding a controller or CRD to an existing project. Devs need the ability to do those things for the lifetime of their project, so whether the compatibility is 3 months or 12 months doesn't really solve that problem. It seems that the SDK has three choices:
* Expect projects to end up using one version of the SDK forever.
* Expect projects to eventually accomplish those day 2 operations without the SDK.
* Preserve backward compatibility for those operations for much longer, and clearly communicate breaking changes (for example with semantic versioning). Provide upgrade paths on those rare occasions when compatibility must be broken.

There might still be good reason to slow down the release cadence, but it's worth at least recognizing that the compatibility problem will still exist and could merit a broader discussion.

**Comment by estroz** [comment]
I think the decision here was no. @jberkhahn @kensipe @asmacdo can we close this out?

**Comment by kensipe** [comment]
I support the current cadence and motion to close this issue

**Comment by jberkhahn** [comment]
I'm fine with closing this.
