### ISSUE TITLE
Trigger reconcile on events of cluster-scoped objects created by a namespaced CR.

### ISSUE THREAD

**Issue by m-yosefpor** [operator-framework/operator-sdk#4986]
#### Describe the problem you need a feature to resolve.

Following https://github.com/operator-framework/operator-sdk/issues/1914:

Consider the following example:

```
func (r *GslbReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&somev1alpha1.NamespacedCR{}).
		Owns(&somev1alpha1.ClusterScopedCR{}). 
		Complete(r)
}
```

This controller watches events of a CR named `somev1alpha1.NamespacedCR`, and trigger the Reconcile logic.
In Reconcile, we create some cluster-scoped objects corresponding to this CR, named `somev1alpha1.ClusterScopedCR`.

Now if:
NamespacedCR is created -> ClusterScopedCR is created
NamespacedCR is deleted -> ClusterScopedCR is deleted
ClusterScopedCR is deleted -> ClusterScopedCR is NOT recreated - this is the issue

I know that according to [k8s documentation](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents) and [controller-runtime library](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllerutil/controllerutil.go#L150), Cluster-scoped dependents can only specify cluster-scoped owners, however I'm not askig for having OwnerRefrence for cluster Scope object (i.e. `ctrl.SetControllerReference`), but rather calling `Owns(&somev1alpha1.ClusterScopedCR{}).` should implement required code to trigger reconcile on cluster scoped events, and map it to corresponding NamespacedCR (as described [in this comment](https://github.com/operator-framework/operator-sdk/issues/1914#issuecomment-532257704)].

#### Describe the solution you'd like.

We can set a label on ClusterScopedCR, based on UID of the NamespacedCR, and watch events on ClusterScopedCR, map it to NamespacedCR by getting the UID label of it, and trigger Reconcile for it. Then users should not have to worry about implementing all the repetitive logic required for this. Operator-sdk can implement this logic in `.Own` calls, or at least provide a method so it can be re-used.

Something like this:

```
func (r *GslbReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&gslbv1alpha1.Gslb{}).
		// Watches all Gslbcontents and trigger reconcile on the corresponding gslb
		// since cluster-scoped gslbcontent can not be owned by namespaced glsb resource
		Watches(
			&source.Kind{Type: &gslbv1alpha1.GslbContent{}}, handler.EnqueueRequestsFromMapFunc(func(obj client.Object) []reconcile.Request {
				gslbID := obj.GetLabels()[glsbIDlabel]
				listOpts := []client.ListOption{
					client.MatchingLabels(labelsForGsbl(gslbID)),
				}
				cli := mgr.GetClient()
				gslbList := &gslbv1alpha1.GslbContentList{}
				err := cli.List(context.TODO(), gslbList, listOpts...)
				if err != nil {
					return []reconcile.Request{}
				}
				var reconcileRequests []reconcile.Request
				var rec reconcile.Request
				for _, g := range gslbList.Items {
					rec = reconcile.Request{
						NamespacedName: types.NamespacedName{
							Name:      g.Name,
							Namespace: g.Namespace,
						},
					}
					reconcileRequests = append(reconcileRequests, rec)
				}
				return reconcileRequests
			}),
		).
		Complete(r)
}

```

Should be as easy as:

```
func (r *GslbReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&gslbv1alpha1.Gslb{}).
		Owns(&gslbv1alpha1.GslbContent{}).
		Complete(r)
}
```

P.S. The hacky solution here is to label the CR itself with its UID, as [it's not currently possible to get objects by their UID](https://github.com/kubernetes/kubernetes/issues/20572). An alternative solution for this is to get the List of all the objects and check if obj.GetUID() == labelUID, which is more costly performance-wise, but is a much cleaner solution.

**Comment by asmacdo** [comment]
@m-yosefpor This is a controller-runtime issue, could you please refile with them?
