### ISSUE TITLE
Log rotation

### ISSUE THREAD

**Issue by lukczarnota** [operator-framework/operator-sdk#4989]
#### Describe the problem you need a feature to resolve.

There is no solution for log rotations.
When operator is handling a lot of workloads then logs are exceeding storage.

#### Describe the solution you'd like.

Possibility to manage log retention by date or size of logs etc.

**Comment by matihost** [comment]
My problem is probably related but it is generar problem of using ansible runner approach in /tmp directory:
https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/building-operators/ansible/reference/scaffolding.md#the-volume-mount-path

Each reconciliation is a job and bunch of files for a run - it is not cleaned.
WHen CR is deleted - old ansible-runner directory is not cleaned also - making this directory only growing when a lot of create CustomResource and Delete CustomResource are happening.

**Comment by estroz** [comment]
@lukczarnota I assume you are talking about manager logs only and not operand/application logs? What operator type are you interested in? The solution could probably be generalized, and there are likely existing products/libs out there to do this already.

/triage needs-information
