### ISSUE TITLE
config/webhook/manifests.yaml not being scaffolded by `operator-sdk create webhook`

### ISSUE THREAD

**Issue by jberkhahn** [operator-framework/operator-sdk#4999]
config/webhook/kustomization.yaml imports configs/webhook/manifests.yaml as a resource, but manifests.yaml isn't being created, so `make deploy` or `make bundle` are blowing up with unhelpful kustomize errors when trying to scaffold a conversion webhook. I can't find anything in our or the kubebuilder docs that mention this, but commenting out the line importing it seems to work fine. Is this intended?

**Comment by varshaprasad96** [comment]
To include webhooks, we would have to uncomment the `[WEBHOOK]` section in `config/default/kustomization.yaml`. It is mentioned in the kubebuilder book here (https://book.kubebuilder.io/cronjob-tutorial/running-webhook.html#deploy-webhooks).

**Comment by tlwu2013** [comment]
there's a related [SDK doc issue](https://github.com/operator-framework/operator-sdk/issues/4831) that could be helpful for this issue.

**Comment by jberkhahn** [comment]
upstream issue: https://github.com/kubernetes-sigs/kubebuilder/issues/2231
