### ISSUE TITLE
Multi deployment operators: best practices

### ISSUE THREAD

**Issue by eivantsov** [operator-framework/operator-sdk#500]
Since I failed to find examples similar to my use case, let me ask a few questions:

1. What are the best practices to accomplish the following?

* create a database deployment
* verify the database deployment replica count is 1 (or whatever makes sense for me)
* run web server deployment afterward since when starting, this web server will connect to a db, and if the db is not up yet, it will fail.

Yes, liveness and readiness probes will do the trick, cancel and redeploy web server but it just takes too much time.

Alternativelt, I can run init containers in each deployment to verify the required deployment has a running pod and an endpoint. But maybe there are better solutions?

2. Having created an object, how do I GET its definition?

* create a Route
* get this route's `spec.host` and save it to env
* run a deployment only once this env gets a value 

I think the answer to both question would be an example of GETTing an object in the namespace and extracting its details, like spec or status.

Thanks

**Comment by eivantsov** [comment]
The way I do it now is a `for` loop where I get current replica count and compare it to the desired one, and do not return anything until replica count is 1 (with reasonable timeout and attempt count)

```
	sdk.Get(deployment)
	replicas := deployment.Status.AvailableReplicas
```

Just wonder if there are better/different solutions.

**Comment by shawn-hurley** [comment]
So, What I would do is use the eventually consistant model and do the following.

1. Set up my CR.Status to know about the stages/what is run.
2. Write my controller loop to
	1. Start the database deployment and update the status to note it was started. return with requeue set to a small amount of time
	2. when you get the event check to see if the status has started, if it has verify the deployment. If the verify fails, requeue, if not update the status to mark the replicas to the correct number. Move on to the webserver. same process as above.
	3. check to see if the webserver is up and running if so mark the status and you should be done reconciling. 

This does get tricky because you will need to handle the scenarios where you can have the webserver up and had completed but then the database pods go down and you may have to jump back in at 2. those sorts of things. 

Let me know if this makes sense would love to hear what others think /cc @hasbro17

**Comment by mhrivnak** [comment]
I agree with @shawn-hurley. Given that it sounds like your web app will crash if the DB isn't available, I'd probably:
* use a readinessprobe to know when the database is working. The `TCPSocket` type makes it real easy.
* If the database is ready, ensure the web app's `Deployment` exists as expected.
* If the database is not ready, ensure the web app's `Deployment` is scaled to zero, or in whatever state is safe for that condition.

**Comment by eivantsov** [comment]
@mhrivnak this is basically what I ended up doing. I do have readiness and liveness probes for all deployments, so when deployment is scaled at 1 it means readiness probe passed and a web server can safely start.

**Comment by joelanford** [comment]
@eivantsov Closing this since it looks like you were able to resolve your issue.
