### ISSUE TITLE
Keycloak crds not getting deployed using ansible operator sdk.

### ISSUE THREAD

**Issue by majidma-ag** [operator-framework/operator-sdk#5001]
## Type of question

Open question

#### What did you do?

Used the latest version of keycloak CRDs and deployed using ansible operator sdk.

1. Took the latest keycloak CRDs from the link: https://github.com/keycloak/keycloak-operator/tree/master/deploy/crds and deployed using ansible operator sdk, this used to work earlier with older version of keycloak CRDs.
2. when i apply the CR, i see the following error messages in the controller manager logs.

` EXEC /bin/sh -c '( umask 77 && mkdir -p \"` echo /opt/ansible/.ansible/tmp `\"&& mkdir \"` echo /opt/ansible/.ansible/tmp/ansible-tmp-1624349093.4731135-2457-242197385141122 `\" && echo ansible-tmp-1624349093.4731135-2457-242197385141122=\"` echo /opt/ansible/.ansible/tmp/ansible-tmp-1624349093.4731135-2457-242197385141122 `\" ) && sleep 0'\nUsing module file /opt/ansible/.ansible/collections/ansible_collections/community/kubernetes/plugins/modules/k8s.py\n<localhost> PUT /opt/ansible/.ansible/tmp/ansible-local-2451biawuow9/tmpz_67n52n TO /opt/ansible/.ansible/tmp/ansible-tmp-1624349093.4731135-2457-242197385141122/AnsiballZ_k8s.py\n<localhost> EXEC /bin/sh -c 'chmod u+x /opt/ansible/.ansible/tmp/ansible-tmp-1624349093.4731135-2457-242197385141122/ /opt/ansible/.ansible/tmp/ansible-tmp-1624349093.4731135-2457-242197385141122/AnsiballZ_k8s.py && sleep 0'\n<localhost> EXEC /bin/sh -c '/usr/bin/python3.6 /opt/ansible/.ansible/tmp/ansible-tmp
-1624349093.4731135-2457-242197385141122/AnsiballZ_k8s.py && sleep 0'\n<localhost> EXEC /bin/sh -c 'rm -f -r /opt/ansible/.ansible/tmp/ansible-tmp-1624349093.4731135-2457-242197385141122/ > /dev/null 2>&1 && sleep 0'\nn get\r\n    return self.request('get', path, **kwargs)\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/client.py\", line 49, in inner\r\n    return serializer(self, jso
n.loads(resp.data.decode('utf8')))\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 285, in __init__\r\n    self.attributes = self.__deserialize(instance)\r\n  File
 \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in __deserialize\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-pa
ckages/openshift/dynamic/resource.py\", line 291, in <dictcomp>\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\"
, line 291, in __deserialize\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in <dictcomp>\r\n    k:
 self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 294, in __deserialize\r\n    return [self.__deserialize(item) for
item in field]\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 294, in <listcomp>\r\n    return [self.__deserialize(item) for item in field]\r\n  File \"/usr/local
/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in __deserialize\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/opensh
ift/dynamic/resource.py\", line 291, in <dictcomp>\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, i
n __deserialize\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in <dictcomp>\r\n    k: self.__deser
ialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in __deserialize\r\n    k: self.__deserialize(v) for k, v in field.items()
\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in <dictcomp>\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/
site-packages/openshift/dynamic/resource.py\", line 291, in __deserialize\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/res
ource.py\", line 291, in <dictcomp>\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in __deserialize
\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in <dictcomp>\r\n    k: self.__deserialize(v) for k
, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in __deserialize\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/u
sr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in <dictcomp>\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/o
penshift/dynamic/resource.py\", line 291, in __deserialize\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", lin
e 291, in <dictcomp>\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in __deserialize\r\n    k: self
.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in <dictcomp>\r\n    k: self.__deserialize(v) for k, v in field.it
ems()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in __deserialize\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/py
thon3.6/site-packages/openshift/dynamic/resource.py\", line 291, in <dictcomp>\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynami
c/resource.py\", line 291, in __deserialize\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in <dict
comp>\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in __deserialize\r\n    k: self.__deserialize(
v) for k, v in field.items()\r\n  File \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in <dictcomp>\r\n    k: self.__deserialize(v) for k, v in field.items()\r\n  File
 \"/usr/local/lib/python3.6/site-packages/openshift/dynamic/resource.py\", line 291, in __deserialize\r\n    k: self.__deserialize(v) for k, v in field.items()\r\nTypeError: __init__() got multiple values
 for argument 'self'\r\nfailed: [localhost] (item=keycloak.org_keycloakrealms_crd.yaml) => {\r\n    \"ansible_loop_var\": \"item\",\r\n    \"changed\": false,\r\n    \"item\": \"keycloak.org_keycloakrealms_crd.yaml\",\r\n    \"module_stderr\": \"Traceback (most recent call last):\\n  File \\\"/opt/ansible/.ansible/tmp/ansible-tmp-1624349093.4731135-2457-242197385141122/AnsiballZ_k8s.py\\\", line 102, in <module>\\n    _ansiballz_main()\\n  File \\\"/opt/ansible/.ansible/tmp/ansible-tmp-1624349093.4731135-2457-242197385141122/AnsiballZ_k8s.py\\\", line 94, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\\"/opt/ansible/.ansible/tmp/ansible-tmp-1624349093.4731135-2457-242197385141122/AnsiballZ_k8s.py\\\", line 40, in invoke_module\\n    runpy.run_module(mod_name='ansible_collections.community.kubernetes.plugins.modules.k8s', init_globals=None, run_name='__main__', alter_sys=True)\\n  File \\\"/usr/lib64/python3.6/runpy.py\\\", line 205, in run_module\\n    return _r
un_module_code(code, init_globals, run_name, mod_spec)\\n  File \\\"/usr/lib64/python3.6/runpy.py\\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\\"/usr/lib64
/python3.6/runpy.py\\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\\"/tmp/ansible_community.kubernetes.k8s_payload_79u6tueq/ansible_community.kubernetes.k8s_payload.zip/ansible_collec
tions/community/kubernetes/plugins/modules/k8s.py\\\", line 269, in <module>\\n  File \\\"/tmp/ansible_community.kubernetes.k8s_payload_79u6tueq/ansible_community.kubernetes.k8s_payload.zip/ansible_collections/community/kubernetes/plugins/modules/k8s.py\\\", line 265, in main\\n  File \\\"/tmp/ansible_community.kubernetes.k8s_payload_79u6tueq/ansible_community.kubernetes.k8s_payload.zip/ansible_collections/community/kubernetes/plugins/module_utils/raw.py\\\", line 192, in execute_module\\n  File \\\"/tmp/ansible_community.kubernetes.k8s_payload_79u6tueq/ansible_community.kubernetes.k8s_payload.zip/ansible_collections/community/kubernetes/plugins/module_utils/raw.py\\\", line 256, in perform_action\\n  File \\\"/usr/local/lib/python3.6/site-packages/openshift/dynamic/client.py\\\", line 94, in get\\n    re`

#### What did you expect to see?

The keycloak CRDs should be able to deploy after running the CR

#### What did you see instead? Under which circumstances?

I see a bunch of error logs as stated above when i applied the CR.

#### Environment

**Operator type:**

language ansible

**Kubernetes cluster type:**

EKS

`$ operator-sdk version`

operator-sdk version: "v1.1.0", commit: "9d27e224efac78fcc9354ece4e43a50eb30ea968", kubernetes version: "v1.18.2", go version: "go1.15.2 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"

`$ go version` (if language is Go)

`$ kubectl version`

kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by absynth76** [comment]
What do you mean by "deployed with operator-sdk" ?? The sdk is helping on building operators, not to deploy custom resource definitions in the cluster afaik

**Comment by jhcook-ag** [comment]
@absynth76 operators can manage other operators in a multi-tenant scenario or perhaps application dependencies. After all, the entire point of an operator is to capture SRE domain-specific logic.
