### ISSUE TITLE
The v1.9 docs link in the Releases dropdown is broken

### ISSUE THREAD

**Issue by davidlanouette** [operator-framework/operator-sdk#5004]
### What is the URL of the document?

Any page with the main nav bar.  Click on Releases and select v 1.9.

### Which section(s) is the issue in?

The link to release v 1.9 tries to navigate to https://v1-9-x.sdk.operatorframework.io/.  But the v1-9-x subdomain doesn't exist.

### What needs fixing?

The link to v1.9 specific docs is broken.  Maybe the build didn't complete 100% and the subdomain didn't get created.

#### Additional context

I looked at the code briefly, but I can't see how the subdomains (for each release) are generated.

**Comment by asmacdo** [comment]
Yup this was broken, its fixed now
