### ISSUE TITLE
Unable to run memcached

### ISSUE THREAD

**Issue by motty-seed-x** [operator-framework/operator-sdk#5009]
Hi

After trying to install operator sdk memcached following the [instructions](https://sdk.operatorframework.io/docs/building-operators/golang/).
[Attaching](https://gist.github.com/motty-seed-x/622d45189fd98a9a2ba3830b2f969084) the flow of the operations.
If anyone has any idea I would love to hear.

**Comment by varshaprasad96** [comment]
@motty-seed-x can you elaborate on the error which you are getting? I'm not able to see any errors in the logs which you have attached.
