### ISSUE TITLE
prometheus metric scrape connections refused if pod is not leader

### ISSUE THREAD

**Issue by mstrYoda** [operator-framework/operator-sdk#5017]
## Bug Report
Operator pods refuses connections if they are not leader pod. This causes error on prometheus while scraping metrics.
Only leader pod returns metrics data, other pods are blocking while trying to becoming leader.

I am using old version of operator sdk, upgrading to new versions is not possible for any time soon. It is basically resolved by adding a label to leader pods.

I am volunteer to make a contribution to resolving this.

#### What did you do?

Running operator.

#### What did you expect to see?

I expect all pods returns metrics or requests should go to only leader pod.

#### What did you see instead? Under which circumstances?

Only leader pod returns data other pods refuses connections.

#### Environment

**Operator type:**

 /language go

**Kubernetes cluster type:**

`$ operator-sdk version`
`operator-sdk version: "v0.18.2", commit: "f059b5e17447b0bbcef50846859519340c17ffad", kubernetes version: "v1.18.2", go version: "go1.14.4 darwin/amd64"`

`$ go version` (if language is Go)
`go version go1.14.4 darwin/amd64`

`$ kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.11", GitCommit:"436254b798f772bcb8e67dcfe122e46500eeb254", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:28Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

#### Possible Solution

Adding label to leader pod and adding selector to service of operator will resolve this issue.

**Comment by varshaprasad96** [comment]
@mstrYoda The latest versions of Operator SDK follow a different approach to [expose](https://book.kubebuilder.io/reference/metrics.html) metrics. We definitely appreciate the contributions made to Operator SDK, but unfortunately 0.18.2 is a very old version which is not being supported. I'd strongly suggest in updating the SDK version whenever possible.

**Comment by mstrYoda** [comment]
> @mstrYoda The latest versions of Operator SDK follow a different approach to [expose](https://book.kubebuilder.io/reference/metrics.html) metrics. We definitely appreciate the contributions made to Operator SDK, but unfortunately 0.18.2 is a very old version which is not being supported. I'd strongly suggest in updating the SDK version whenever possible.

Thank you for your answer. Currently it looks quite hard to move our current operator to the latest version. In a free time I will move the code to the new operator version.

Until then, I resolved my problem by adding a label to leader pod and updating service selector in main.go. Here the code:

```
func main() {
.
.
.
workingNs,_:=k8sutil.GetOperatorNamespace()

client, err := crclient.New(cfg, crclient.Options{})
checkError(err, "failed to create new client")

leaderPod, err := k8sutil.GetPod(ctx, client, workingNs)
checkError(err, "failed to get leader pod")

leaderPod.Labels["leader"] = "true"
err = client.Update(ctx, leaderPod)
checkError(err, "failed to label leader pod")

operatorName, err := k8sutil.GetOperatorName()
checkError(err, "failed to get operator name")

existingService := &v1.Service{}
err = client.Get(ctx, types.NamespacedName{
	Name:      fmt.Sprintf("%s-metrics", operatorName),
	Namespace: workingNs,
}, existingService)
checkError(err, "failed to get metrics service")

existingService.Spec.Selector["leader"] = "true"
err = client.Update(ctx, existingService)
checkError(err, "failed to label metrics service")
.
.
.
}

func checkError(err error, msg string) {
	if err != nil {
		log.Error(err, msg)
		os.Exit(1)
	}
}

```
