### ISSUE TITLE
Separate webhook and API definition

### ISSUE THREAD

**Issue by chrispatmore** [operator-framework/operator-sdk#5024]
## Feature Request

More of a debate and potential feature request than an outright feature request

#### Describe the problem you need a feature to resolve.

We have multiple operators that import APIs between each other. And we import the APIs of other open operators or operators written by separate internal teams. This causes a dependency version nightmare, because a long with importing the go API we have to import the webhook code. 

The problem with this is whilst the go API defn is very structured and at most will import other APIs, such as the meta API etc. An operators webhook code may import a wide range of other go modules. For example older operators imported 
`"sigs.k8s.io/controller-runtime/pkg/runtime/log"` in controller-runtime `0.6.3` which is removed in favour of `"sigs.k8s.io/controller-runtime/pkg/log"` in controller-runtime `0.8.3`. This means when I import the API of an operator that has not upgraded their controller-runtime dependency. I am also stuck on `0.6.3` of controller-runtime. Even though that import has nothing to do with the API I want and is only there for their webhook code, which I did not need. 

Now arguably this problem exists regardless of whether the webhook code is in the API package or not as you could cause the same problem with a broken change in an API import. Though to me at least that feels a lot less likely.

If we consider the kube APIs they are completely separated (thinking about, core, meta, apps etc.)

Additionally, though it's not something I have done yet. Having the webhook defined where it is feels like it makes setting up a webhook that manages multiple API versions more complicated. Though this could be because I haven't done it yet, so am just missing something

#### Describe the solution you'd like.

A debate around what best practise is here?
Whether we should consider separating webhook code by default?

/language go

**Comment by estroz** [comment]
I recommend defining your shared APIs in separate repo(s), similar to how operator-framework has the api repo https://github.com/operator-framework/api.

**Comment by chrispatmore** [comment]
Ah, that's an interesting thought. You're right that is probably the best solution. I guess the problem is you never really know when someone is going to want to import and use your api as part of some larger solution. But operator-sdk also clearly can't default to generating two separate projects. So maybe there is not a lot we can do here. Thanks for the thought though. I'm happy to close this one out if you are

**Comment by estroz** [comment]
Happy to help! As a rule of thumb, when dependencies become an issue it's time to move shared code into a separate repo.

I will close this issue.
