### ISSUE TITLE
Best practice to maintain a multi-channel catalog image

### ISSUE THREAD

**Issue by fantapsody** [operator-framework/operator-sdk#5026]
## Type of question

Best practices

#### What did you do?

I would like to maintain a catalog source image (`operator-catlog:latest` for example) with multiple channels, e.g., `alpha`, `beta`, `stable`. A specific version of the operator should generally appear in channel `alpha` first, then channel `beta`, and finally `stable` if everything goes well for a while. However, the tools and scripts (`operator-sdk` or the generated [`Makefile`](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/Makefile)) do not seem to support this usage very well:
- The tag of the catalog image can only be `v${VERSION}`
- the information of which channels the operator bundle is in is built into the image of the bundle and can only be rebuilt if you want to move the operator to other channels
- the `operator-registry` doesn't support adding operator bundles with the same name multiple times, so it's hard to add the rebuilt bundle to the catalog image unless the bundle name is changed if you want to move the operator bundle to other channels (e.g., `v0.1` was in `alpha` only, but now you want it to be in `alpha` and `beta`) 

#### What did you expect to see?

A clear way to maintain a multi-channel catalog source image using scripts in CI/CD pipelines.

#### What did you see instead? Under which circumstances?

Problems just as I described.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

Cloud-managed Kubernetes clusters like GKE, EKS, etc.

`$ operator-sdk version`

operator-sdk version: "v1.8.0", commit: "d3bd87c6900f70b7df618340e1d63329c7cd651e", kubernetes version: "v1.20.2", go version: "go1.16.4", GOOS: "darwin", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.16.5 darwin/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}

**Comment by estroz** [comment]
Some great questions here.

>The tag of the catalog image can only be v${VERSION}

What are you trying to set `VERSION` to? Note that version can have build info like `1.0.0-alpha.0`.

>the information of which channels the operator bundle is in is built into the image of the bundle and can only be rebuilt if you want to move the operator to other channels

This is a design decision from the first iteration of bundles that is being corrected with [declarative configs](https://github.com/operator-framework/enhancements/blob/master/enhancements/declarative-index-config.md#motivation). For now I am unsure of the best way to work around this issue. Perhaps @gallettilance has insight.

>the operator-registry doesn't support adding operator bundles with the same name multiple times

The root cause of this question is the same as that for the above question: channels should be package-level data and not part of an image's content hash.

**Comment by fantapsody** [comment]
I think it's covered in the [file-based catalogs](https://olm.operatorframework.io/docs/reference/file-based-catalogs/) now.
