### ISSUE TITLE
operator-sdk is dropping RBAC definitions from config/rbac when "make bundle" is run

### ISSUE THREAD

**Issue by cc83851** [operator-framework/operator-sdk#5029]
#### What did you do?
 
We have been using operator-sdk and  “make deploy” to deploy a particular operator. We are now moving to using olm for deployment and in the process of shifting to using “make bundle” to create the manifests for olm to use for deploying the operator.
 
Crudely put, “make deploy” does
`$(KUSTOMIZE) build config/default | kubectl apply -f –`
 
“make bundle” does
`$(KUSTOMIZE) build config/manifests | operator-sdk generate bundle -q --overwrite --version $(VERSION) $(BUNDLE_METADATA_OPTS)`
 
#### What did you expect to see?
 
We expected all the RBAC defined in config/rbac to end up somewhere in a file (CSV file or seperate file) in bundle/manifests
 
#### What did you see instead? Under which circumstances?

Initially we started using operator-sdk 1.7.0
 
What we found is that with “make bundle” the 1 role defined in config/rbac/role.yaml and the 3 role bindings defined in config/rbac/role_binding.yaml (both appended below) WERE being generated by the  “$(KUSTOMIZE) build config/manifests” step but that the subsequent “operator-sdk generate bundle" step was not putting the roles and role bindings defined in those config files into any file in bundle/manifests. Consequently, when the operator was deployed, it installed o.k. but then failed to run due to missing permissions.
 
We then moved to using v1.9.0, in case the dropping of RBAC definitions was a known issue. With this later version, SOME of the definitions from role.yaml and role_binding.yaml are now being added into bundle/manifests, but not others. Specifically, the ClusterRoleBindings called view-rolebinding and edit-rolebinding were added, but the role binding manager-rolebinding and the clusterRole manager-role still are not.
 
So clearly something changed (improved) between 1.7.0 and 1.9.0, but why are some roles / role_bindings definitions being dropped by the “operator-sdk generate bundle" in 1.9.0, and what can we do to force them to be included?
 
 
#### RBAC files
 
```html
$ cat role_binding.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: system-sa
  namespace: system
 
# The manager needs global view access so it can delegate the view role to consumers of the Jenkins Namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: system-sa
  namespace: system
 
# The manager needs global edit access so it can delegate the edit role to the Jenkins Service Account in the Jenkins Namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edit-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: system-sa
  namespace: system
 
 
 
$ cat role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Rules for aws.lightspeed.citi.com/v1alpha1, Kind: LSAwsJenkins
  ##
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - rolebindings
    - roles
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - aws.lightspeed.citi.com
    resources:
    - lsawsjenkins
    - lsawsjenkins/status
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - vault.controlplane.io
    resources:
    - vaultkuberoles
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
```
 
#### Environment
 
**Operator type:**
/language ansible
 
**Kubernetes cluster type:**
The type of cluster used for testing/deployment was "OpenShift"
 
`$ operator-sdk version`
1.9.0

**Comment by estroz** [comment]
Are the manager-role's permissions present in your CSV's `spec.install.spec.clusterPermissions`?

/triage support

**Comment by cc83851** [comment]
Sadly not. manager-role does not appear in any of the files (inc the CSV) in bundle/manifests. The clusterPermissions section of the CSV is included below for information. Thank you for your quick response.

```
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          - roles
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aws.lightspeed.citi.com
          resources:
          - lsawsjenkins
          - lsawsjenkins/status
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - vault.controlplane.io
         resources:
          - vaultkuberoles
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: ls-aws-operator-system-sa

**Comment by estroz** [comment]
Those permissions are identical to those in `manager-role` because they are taken from that manifest. They are created by OLM for your, and do not have to be a separate file in your bundle's manifests dir. In general, all roles and cluster roles that are bound to the operator's service account by default, in this case `ls-aws-operator-system-sa`, are added to their corresponding permissions field by `generate bundle`. Hopefully this clarifies things.

**Comment by cc83851** [comment]
Ah! I was expecting an explicitly named "manger-role" clusterRole and associated binding to appear somewhere within the bundle files, but I do now see that this same information has made it into the CSV file. Thank you very much for pointing this out to me.
