### ISSUE TITLE
Improve docs on versioning and migrations

### ISSUE THREAD

**Issue by jberkhahn** [operator-framework/operator-sdk#5032]
From discussion on #4985, it seems most of the pressure points from our release cadence arise not from the frequency of releases, but from misunderstandings about what versions we support and what that means.

Our [current backport policy](https://sdk.operatorframework.io/docs/upgrading-sdk-version/backport-policy/) and [the upgrade guide](https://sdk.operatorframework.io/docs/upgrading-sdk-version/version-upgrade-guide/) are technically accurate to our current policy, but elide the specific detail that minor version upgrades should be strictly additive, so you don't need to upgrade your operator unless you want to take advantage of new features. You should be able to bump the image dependency, rebuild your operator, and be good to go. 

We need to improve the existing documentation to make this more apparent.

**Comment by jberkhahn** [comment]
@estroz your thoughts?

**Comment by estroz** [comment]
>you don't need to upgrade your operator unless you want to take advantage of new features. You should be able to bump the image dependency, rebuild your operator, and be good to go.

The key takeaway that should be written in the header of https://sdk.operatorframework.io/docs/upgrading-sdk-version/, specifying that this is the case within a major version, i.e. for any 1.y version.

**Comment by asmacdo** [comment]
Closing, fixed by #5185
