### ISSUE TITLE
How to remote debug latest sdk 1.9.x like done in 0.17.x using --enable-delve

### ISSUE THREAD

**Issue by wondersong** [operator-framework/operator-sdk#5055]
## Type of question
In the latest 1.9.x operator  SDK, can not remote debug it like done in ealier release.
## Question
$ operator-sdk up local  -- namespace=integreatly-operator  -- enable-delve

INFO[0000] Running the operator locally.
INFO[0000] Using namespace integreatly-operator.
INFO[0000] Delve debugger enabled with args [ - listen=:2345 - headless=true - api-version=2 exec build/_output/bin/integreatly-operator-local - ]
API server listening at: [::]:2345
#### What you do expect?
New operator-sdk support remote debug using -- enable-delve

**Comment by estroz** [comment]
This command was removed because it was a wrapper around `delve ansible-operator run`, which you can now call yourself. We don't plan on adding a debug command now because calling `delve` or your debugger of choice directly is a more flexible option.
