### ISSUE TITLE
helm operator for a chart with some dependencies keeps upgrading every sync loop

### ISSUE THREAD

**Issue by wscheele** [operator-framework/operator-sdk#5056]
#### What did you do?
Deploy a helm operator to manage a helm chart with a number of dependencies.

#### What did you expect to see?

Upgrades only when either the chart or the cr contained spec values change. 

#### What did you see instead? Under which circumstances?

the isUpgrade method (in current master at)
internal/helm/release/manager.go:168
always returns `true`.

after some debugging, i figured that this happens because the chart from the manager (`m.chart` in that method) only contains Values coming from the main chart's `values.yaml`; while the chart from the release (`deployedRelease.Chart` in that code) contains (non-empty, non-null) defaults from the dependencies charts' `values.yaml` files as well.
therefore `ok, err := equalJSONStruct(m.chart, deployedRelease.Chart)` always sets ok to `false` (Values never matches).

#### Environment

**Operator type:**

/language helm

`$ operator-sdk version`

v1.8.0
but v1.8.1 operator image, as well as current master build have the same behavior.

`$ go version` (if language is Go)
`go version go1.16.5 linux/amd64`

#### Possible Solution

i don't have any experience with go (other than two or three debugging attempts).
am testing an approach where the `manager_factory` enriches the `manager` chart Values with the (non-null, non-empty) defaults from the dependencies charts as well. this does look promising. but having no knowledge in go, nor experience with helm apis, i find it very hard to determine whether that makes sense.

#### Additional context
something seems misaligned between the Values view of `loader.LoadDir(f.chartDir)` in manager_factory vs those returned by `m.getDeployedRelease()`

if there is something i need to adjust in either my chart definition, or the way i deploy the operator to align the values, i would love to know. but couldn't find.

**Comment by cndoit18** [comment]
Thank you very much, I will work with you on this issue recently. Do you have the chart to facilitate me to reproduce and troubleshoot it?

**Comment by cndoit18** [comment]
I tried to generate a pr, can you help to verify it together?

**Comment by wscheele** [comment]
did you manage to reproduce the issue?

**Comment by cndoit18** [comment]
> will run my case against your pr to verify.

Sad news, it did not solve #4936

**Comment by wscheele** [comment]
it also doesn't solve my case. keeps upgrading.

**Comment by wscheele** [comment]
the approach in the above patch works fine for me.

**Comment by cndoit18** [comment]
Hi, I updated it, can you verify it again? thanks @wscheele

**Comment by wscheele** [comment]
same problem, still keeps upgrading

**Comment by cndoit18** [comment]
I'll try to reproduce the problem by adding a unit test first. Can you help me to verify it again? @wscheele

**Comment by wscheele** [comment]
yeah, i have vested interest ;)
will test when you have something.

**Comment by cndoit18** [comment]
can you test it, this should solve the problem. thank you @wscheele @chlam4

**Comment by jberkhahn** [comment]
Hey @cndoit18 assigned this to you because of your open PR. Assigned this to the 1.11.0 milestone, but if it doesn't get in by then it's fine.

**Comment by cndoit18** [comment]
> Hey @cndoit18 assigned this to you because of your open PR. Assigned this to the 1.11.0 milestone, but if it doesn't get in by then it's fine.

Thank you very much

**Comment by bitscuit** [comment]
I'm seeing a similar issue, but my chart has no dependencies https://github.com/operator-framework/operator-sdk/issues/5072

**Comment by cndoit18** [comment]
> I'm seeing a similar issue, but my chart has no dependencies #5072

thank you. I will test it together

**Comment by estroz** [comment]
Added this to the backlog pending discussion in the PR.

**Comment by jmrodri** [comment]
We removed the priority/important-soon label because the PR that was introduced by this issue was reverted. And we have not heard of this loop coming back since then.
