### ISSUE TITLE
Helm chart based manager hits OOM

### ISSUE THREAD

**Issue by sqqqrly** [operator-framework/operator-sdk#5060]
#### What did you do?
Used osdk to scaffold and build a helm-based operator and bundle.

#### What did you expect to see?
An operator that runs without hitting OOM.  OOM occurs because helm operators use much more memory. It was suggested to use 1Gi rather than 90Mi by @madorn.

#### What did you see instead? Under which circumstances?
controller manager OOM restarts.  It was not immediately obvious what the cause/soln was.  This will happen until the memory is boosted to 1Gi.

#### Environment

**Operator type:**

 /language helm

**Kubernetes cluster type:**

╰─➤  operator-sdk version
operator-sdk version: "v1.9.0", commit: "205e0a0c2df0715d133fbe2741db382c9c75a341", kubernetes version: "1.20.2", go version: "go1.16.5", GOOS: "linux", GOARCH: "amd64"

╰─➤  crc version
WARN A new version (1.29.1) has been published on https://cloud.redhat.com/openshift/create/local
CodeReady Containers version: 1.27.0+3d6bc39d
OpenShift version: 4.7.11 (embedded in executable)

╰─➤  kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+75370d3", GitCommit:"75370d3fb99594d6f0263f3de0bd08237381b77d", GitTreeState:"clean", BuildDate:"2021-05-09T17:55:51Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}

#### Possible Solution
This is my work-around.  Since osdk knows the type of operator, it could set the memory accordingly.
```
.PHONY: hack-manager
hack-manager:  ## Fix memory in osdk generated manager.yaml
    @cd $(_projects_dir)/$(_project) && \
        sed -i.bak \
        -e 's|memory: 90Mi|memory: 1Gi|' \
        config/manager/manager.yaml; \
    cd -
```

**Comment by jkupferer** [comment]
I am also seeing OOM errors with my helm-based operator and trying to figure out what is happening. For our use case there is no reason I can see why our operator would be using anywhere near this much memory... Looking at the logs I see indications that the operator is pulling data from just about every API endpoint on the cluster for no reason I can discern:

```
$ oc logs -n openshift-operators deployment/anarchy-operator-controller-manager -c manager | grep Throttling | tail
I0719 13:44:17.199354       1 request.go:655] Throttling request took 1.045405319s, request: GET:https://172.30.0.1:443/apis/autoscaling.openshift.io/v1?timeout=32s
I0719 13:44:35.388230       1 request.go:655] Throttling request took 1.047742484s, request: GET:https://172.30.0.1:443/apis/machine.openshift.io/v1beta1?timeout=32s
I0719 13:45:20.981753       1 request.go:655] Throttling request took 1.045451199s, request: GET:https://172.30.0.1:443/apis/cert-manager.io/v1alpha3?timeout=32s
I0719 13:45:39.707687       1 request.go:655] Throttling request took 1.04584692s, request: GET:https://172.30.0.1:443/apis/migration.k8s.io/v1alpha1?timeout=32s
I0719 13:46:25.089629       1 request.go:655] Throttling request took 1.045522994s, request: GET:https://172.30.0.1:443/apis/authentication.k8s.io/v1beta1?timeout=32s
I0719 13:46:44.592121       1 request.go:655] Throttling request took 1.045221219s, request: GET:https://172.30.0.1:443/apis/scheduling.k8s.io/v1beta1?timeout=32s
I0719 13:47:29.335438       1 request.go:655] Throttling request took 1.045639497s, request: GET:https://172.30.0.1:443/apis/batch/v1?timeout=32s
I0719 13:47:49.016099       1 request.go:655] Throttling request took 1.045825839s, request: GET:https://172.30.0.1:443/apis/acme.cert-manager.io/v1?timeout=32s
I0719 13:48:33.397188       1 request.go:655] Throttling request took 1.045673661s, request: GET:https://172.30.0.1:443/apis/config.openshift.io/v1?timeout=32s
I0719 13:48:53.878529       1 request.go:655] Throttling request took 1.045245525s, request: GET:https://172.30.0.1:443/apis/cert-manager.io/v1?timeout=32s
```

**Comment by jkupferer** [comment]
Any update on this? We are continuing to see mysteriously large memory consumption from our helm-based operator. For no apparent reason it is attempting to use over 1GiB of memory! We are having to increase its resources again, but there seems to be no reasonable explanation why it would be using anywhere near this amount of memory.

**Comment by 9strands** [comment]
Confirming - we have had to increase our master-node sizes 3x times until each node has 128G each just to stay alive with this error.  It's becoming very expensive.

**Comment by camilamacedo86** [comment]
Hi @sqqqrly, 

Probably the content in https://github.com/operator-framework/operator-sdk/pull/5353 can help you understand it better. See that the memory is largely based on the number of primary resources that exist (multiplied by some factor based on the number of operand resources they need to watch as a result) via informer caches.

In this way, in your Helm operator, you might be watching too many resources which are causing it. WDYT about yu review what are the resourced watched by your project? Are you using the selector option to filter what your project should watch/cache? More info: https://sdk.operatorframework.io/docs/building-operators/helm/reference/watches/

**Comment by sqqqrly** [comment]
Thanks for the reply.  Researching this...

**Comment by jkupferer** [comment]
Any update?

I know for our Helm based operator we are only watching one resource kind (https://github.com/redhat-cop/anarchy/blob/main/commune-operator/watches.yaml) and our cluster has less than a dozen instances of this resource kind, yet the helm based operator is consistently using a huge amount of memory and reporting throttling errors like the above where it appears to be hitting every API endpoint on the cluster.

**Comment by sqqqrly** [comment]
To support larger clusters, we had to boost the limit to `4Gi` !!!   We see memory usage of up to 2.2Gi.

**Comment by camilamacedo86** [comment]
Hi @jkupferer, 

> Any update on this? We are continuing to see mysteriously large memory consumption from our helm-based operator. For no apparent reason it is attempting to use over 1GiB of memory! We are having to increase its resources again, but there seems to be no reasonable explanation why it would be using anywhere near this amount of memory.

You can check the doc, to know to manage resources: https://sdk.operatorframework.io/docs/best-practices/managing-resources/

Also, as shared in https://github.com/operator-framework/operator-sdk/issues/5060#issuecomment-976380853 you might want to check what you have been configured to be watched by your Operator. 

> Memory: largely based on the number of primary resources that exist (multiplied by some factor based on the number of operand resources they need to watch as a result) via informer caches.

So, I think we can close this one.

**Comment by michaelcourcy** [comment]
@camilamacedo86 I may be wrong but I don't see how the [document](https://sdk.operatorframework.io/docs/best-practices/managing-resources/) you're pointing to is solving the problem reported 

> We are continuing to see mysteriously large memory consumption from our helm-based operator. For no apparent reason it is attempting to use over 1GiB of memory! We are having to increase its resources again

The document explain the good use of request and limit but does not give any solution to the increase of memory usage that people reported here. Did I miss something ?
