### ISSUE TITLE
`make tidy` is no longer a valid make target

### ISSUE THREAD

**Issue by osilkin98** [operator-framework/operator-sdk#5063]
### What is the URL of the document?

[Install the Operator SDK](https://v0-19-x.sdk.operatorframework.io/docs/install-operator-sdk)

### Which section(s) is the issue in?

[Compile and Install From Master](https://v0-19-x.sdk.operatorframework.io/docs/install-operator-sdk/#compile-and-install-from-master)

### What needs fixing?

`make tidy` should be removed from the install instructions, since it is no longer a valid make target.

**Comment by varshaprasad96** [comment]
@osilkin98 - The document which referred here is from 0.19.x branch. It has been updated for the latest releases: https://master.sdk.operatorframework.io/docs/contribution-guidelines/developer-guide/.

**Comment by osilkin98** [comment]
> @osilkin98 - The document which referred here is from 0.19.x branch. It has been updated for the latest releases: https://master.sdk.operatorframework.io/docs/contribution-guidelines/developer-guide/.

Ah okay, that makes more sense. I did not see that link before.
