### ISSUE TITLE
OLM and Bundle CLI Overview

### ISSUE THREAD

**Issue by schneiderdotme** [operator-framework/operator-sdk#5070]
The word namespace is spelled incorrectly on this page of the docs:
https://sdk.operatorframework.io/docs/olm-integration/cli-overview/#private-bundle-and-catalog-image-registries

<img width="745" alt="Screen Shot 2021-07-19 at 9 57 18 AM" src="https://user-images.githubusercontent.com/82610054/126181002-705beac3-e131-42f9-9d35-84bd7947ec79.png">

**Comment by estroz** [comment]
@schneiderdotme if you'd like to submit a PR to fix this, feel free! Otherwise I can.

/kind documentation

**Comment by schneiderdotme** [comment]
@estroz yeah, would love to! I should be able to get to that within 48 hours if that's not too late.
