### ISSUE TITLE
Helm based operator constantly upgrading release

### ISSUE THREAD

**Issue by bitscuit** [operator-framework/operator-sdk#5072]
#### What did you do?

Installed helm based operator https://github.com/IBM/ibm-platform-api-operator

#### What did you expect to see?

The controller's logs should be relatively clean and there should only be one ServiceAccount token for the operand

#### What did you see instead? Under which circumstances?

The controller's logs have the following repeated
```console
I0718 18:30:07.427595       1 request.go:655] Throttling request took 1.030403368s, request: GET:https://172.21.0.1:443/apis/operators.coreos.com/v1?timeout=32s
{"level":"info","ts":1626633010.9435072,"logger":"helm.controller","msg":"Upgraded release","namespace":"ibm-common-services","name":"platform-api","apiVersion":"operator.ibm.com/v1alpha1","kind":"PlatformAPI","release":"platform-api","force":false}
 ---
 # Source: platform-api/templates/platform-api-rbac.yaml
 apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: ibm-platform-api-operand
   labels:
     name: ibm-platform-api-operand
     app.kubernetes.io/instance: platform-api
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/name: platform-api
     helm.sh/chart: platform-api
 ---
.
.
.
<k8s resources for the operator>
```

It seems like the operator is constantly trying to upgrade the operand, but there have been no updates to the CR and the operand continues running with no changes.

This is a significant issue because every time the operator does this "empty" upgrade, it looks like OLM or Kubernetes is creating a new ServiceAccount token for the operand. These secrets are not getting cleaned up, so the behaviour is similar to a memory leak issue, i.e. resources are constantly being created, but never cleaned. There have been over 100 secrets created after having the operator installed for ~ 5 days.

```yaml
$ oc get secrets | grep ibm-platform-api-operand-token | wc -l
134
```

```yaml
$ oc get secrets | grep ibm-platform-api-operand-token
ibm-platform-api-operand-token-24p4h                   kubernetes.io/service-account-token   4      5d6h
ibm-platform-api-operand-token-26l2x                   kubernetes.io/service-account-token   4      5d6h
.
.
.
```

#### Environment

**Operator type:**

/language helm

**Kubernetes cluster type:**

Openshift

`$ operator-sdk version`

```
operator-sdk version: "v1.9.0", commit: "205e0a0c2df0715d133fbe2741db382c9c75a341", kubernetes version: "1.20.2", go version: "go1.16.5", GOOS: "linux", GOARCH: "amd64
```

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by bitscuit** [comment]
I have seen this issue even with operator-sdk version 1.7.2

**Comment by cndoit18** [comment]
Hi, can you provide a `PlatformAPI` that works? I'm directly applying the `PlatformAPI` in `config/simple` and it seems to have problems

**Comment by bitscuit** [comment]
The sample is a valid one. What is the specific error you are hitting?

**Comment by bitscuit** [comment]
@cndoit18 I forgot to mention, you will want to change the operator image tag to `3.11.0` because the latest tag points to a really old image https://github.com/IBM/ibm-platform-api-operator/blob/master/bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml#L273. You can see the available tags here https://quay.io/repository/opencloudio/ibm-platform-api-operator?tab=tags.

The upgrade issue is present in both `3.10.0` and `3.11.0`

**Comment by cndoit18** [comment]
> @cndoit18 I forgot to mention, you will want to change the operator image tag to `3.11.0` because the latest tag points to a really old image https://github.com/IBM/ibm-platform-api-operator/blob/master/bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml#L273. You can see the available tags here https://quay.io/repository/opencloudio/ibm-platform-api-operator?tab=tags.
> 
> The upgrade issue is present in both `3.10.0` and `3.11.0`

Thanks, I'll try it later

**Comment by bitscuit** [comment]
@cndoit18 while you are working on the fix, is there any sort of workaround to force the operator to stop trying to do these upgrades? My current workaround is to just scale down the operator pod to 0 once the operand is deployed to avoid my cluster being overwhelmed by the number of secrets that are created.

**Comment by bitscuit** [comment]
okay, so the fix has already been merged. Any idea when the release will come out?

**Comment by estroz** [comment]
@bitscuit the fix is being backported now, so hopefully this week!

**Comment by bitscuit** [comment]
thank you, I no longer see the issue, so closing
