### ISSUE TITLE
Can I initialize project with multiple plugins?

### ISSUE THREAD

**Issue by sagar-jadhav** [operator-framework/operator-sdk#5075]
## Type of question

General operator-related help

#### What did you do?

Run the following command:

```
operator-sdk init --plugins go.kubebuilder.io/v2,helm.sdk.operatorframework.io/v1
```

#### What did you expect to see?

Project should initialize with both the plugins without any error.

#### What did you see instead? Under which circumstances?

After running the command I got following output:

```
Error: duplicate initialization plugins (go.kubebuilder.io/v2, helm.sdk.operatorframework.io/v1), use a more specific plugin key
FATA[0000] duplicate initialization plugins (go.kubebuilder.io/v2, helm.sdk.operatorframework.io/v1), use a more specific plugin key
```

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`

operator-sdk version: "v1.3.0", commit: "1abf57985b43bf6a59dcd18147b3c574fa57d3f6", kubernetes version: "v1.19.4", go version: "go1.15.5", GOOS: "darwin", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.15.6 darwin/amd64

`$ kubectl version`

#### Additional context

I run `operator-sdk init` command with multiple plugins after looking at the following help doc:

```
--plugins strings          Name and optionally version of the plugin to initialize the project with. Available plugins: ("ansible.sdk.operatorframework.io/v1", "go.kubebuilder.io/v2", "go.kubebuilder.io/v3", "helm.sdk.operatorframework.io/v1")
```

Now here option is `plugins` which means multiple plugins can be used. If that's not true then please change the documentation.

**Comment by varshaprasad96** [comment]
@sagar-jadhav We cannot combine multiple base plugins for now. If you are specifically looking for helm+go operator, we do have a [hybrid](https://github.com/operator-framework/helm-operator-plugins) operator plugin which is in alpha stage and would be releasing soon along with Operator SDK.

**Comment by sagar-jadhav** [comment]
Hello @varshaprasad96 Thank you for clarification. I will surely try `Hybrid Operator` plugin. 

But I have also mention one more issue in description. Could you please help me with that?

> I run `operator-sdk init` command with multiple plugins after looking at the following help doc:
> 
> ```
> --plugins strings          Name and optionally version of the plugin to initialize the project with. Available plugins: ("ansible.sdk.operatorframework.io/v1", "go.kubebuilder.io/v2", "go.kubebuilder.io/v3", "helm.sdk.operatorframework.io/v1")
> ```
> 
> Now here option is `plugins` which means multiple plugins can be used. If that's not true then please change the documentation.

If we cannot combine multiple base plugins then instead of using `--plugins` as CLI option we should use `--plugin`. `--plugins` is bit confusing.

Please share your opinion here.

**Comment by varshaprasad96** [comment]
I understand. Having this documented somewhere would be helpful. On a side note, in near future we would soon be having support for chaining of plugins [ref: Kubebuilder plugins phase 2](url). Meanwhile, would you like to create a PR to have this documented in SDK [website](https://sdk.operatorframework.io/docs/building-operators/golang/)?

**Comment by sagar-jadhav** [comment]
Thank you @varshaprasad96 for your response.

Sorry I won't be able to create a PR for this documentation update. But I will be happy If we have this documented. Can you please ask someone else or create an issue for this so that others can contribute?  I think it's a good candidate for the `good first issue` label.
