### ISSUE TITLE
Handler should have filtering function

### ISSUE THREAD

**Issue by benjaminapetersen** [operator-framework/operator-sdk#508]
If an operator watches a few resources such as:

```go
sdk.Watch(routev1.GroupVersion.String(), "Route", namespace, resyncPeriod)
sdk.Watch(corev1.SchemeGroupVersion.String(), "Service", namespace, resyncPeriod)
sdk.Handle(stub.NewHandler())
sdk.Run(context.TODO())
```
The handler will fire for every `route` and `service` in the namespace, however, the handler is probably only interested in a specific set of these resources.  If a user creates additional services/routes in the namespace, the operator probably does not care about these other resources.  

It seems like the handler should have a filtering mechanism.

**Comment by LiliC** [comment]
You may have already seen this but there is the `labelSelector` option you can specify when adding `Watch` to a resource.

Or were you thinking of something else?

**Comment by hasbro17** [comment]
@benjaminapetersen This will be supported once we use the controller-runtime.
This is essentially filtering on some predicate which the controller-runtime supports.
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/predicate/predicate.go#L26-L39
With the controller-runtime you should be able to define your own predicate( e.g check labels, resourceVersion, annotation etc) to filter out Add,Update,Delete events that get sent to your reconciler/handler.

We have an older issue tracking requesting this feature already #268 
With the amount of issues open it's a bit cumbersome to comb through older issues to look for duplicates so I've updated the title of the older issue to make it more clear.

Feel free to reopen this if you meant something different.

**Comment by benjaminapetersen** [comment]
Yeah I was initially thinking something like, I want to watch `Route` by name `foo`.  Because if someone creates additional routes in my namespace, I don't want my operator getting distracted, churning, doing more work.
