### ISSUE TITLE
Documentation: Needs clarification for selfhosted docker registry. 

### ISSUE THREAD

**Issue by qubusp** [operator-framework/operator-sdk#510]
Needs clarification for self hosted docker registry

**Comment by qubusp** [comment]
I think it needs a clarification which is not only quay.io related in the readme.md

**Comment by AlexNPavel** [comment]
The instructions are the same for any registry. The commands we supplied are in a standard docker style. If your registry is my-registry.com, for example, simply use `my-registry.com/example/app-operator` as you image name instead of `quay.io/example/app-operator`

**Comment by AlexNPavel** [comment]
Closing the issue. If you have problems using your own image name, you can reopen.
