### ISSUE TITLE
preserveUnknownFields is removed from CRDs by operator-sdk generate bundle

### ISSUE THREAD

**Issue by aharbis** [operator-framework/operator-sdk#5102]
## Bug Report

We need to explicitly set `preserveUnknownFields: false` to support upgrades between `v1beta1` CRDs and `v1` CRDs. In the past, we've used YAML post-processing on the CRD files to set this property explicitly. I'm working on upgrading our project to Operator SDK `v1.3.2`, and so now we can leverage `kustomize` for some of this "post-processing" of CRDs.

I've configured `kustomize` patches, for example:

```
$ cat config/crd/patches/pruning_in_datapowerservices.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datapowerservices.datapower.ibm.com
spec:
  preserveUnknownFields: false
```

I have validated those are outputting correctly for our two CRDs:

```
$ kustomize build config/manifests | grep preserveUnknownFields
  preserveUnknownFields: false
  preserveUnknownFields: false
```

Our `bundle` make target looks like this:

```Makefile
# Generate bundle manifests and metadata.
bundle: manifests kustomize
        operator-sdk generate kustomize manifests
        cd config/manager && $(KUSTOMIZE) edit set image controller=$(IMG)
        $(KUSTOMIZE) build config/manifests | operator-sdk generate bundle $(BUNDLE_METADATA_OPTS)
```

As the `kustomize build config/manifests` is the input to `operator-sdk generate bundle`, and I know the properties exist in that input, it narrows the point of omission to the `operator-sdk` copying of these files to the `bundle/manifests` output directory.

#### What did you do?

`make bundle`

#### What did you expect to see?

CRDs output in `bundle/manifests` should retain `preserveUnknownFields: false`.

CRDs output in `bundle/manifests` should match the output from `kustomize build config/manifests`.

#### What did you see instead? Under which circumstances?

The `preserveUnknownFields` property is stripped from the CRDs when placed into `bundle/manifests`.

```
$ grep -R -c preserveUnknownFields bundle/manifests
...
bundle/manifests/datapower.ibm.com_datapowermonitors.yaml:0
bundle/manifests/datapower.ibm.com_datapowerservices.yaml:0
...
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

OCP 4.6 / 4.7

`$ operator-sdk version`

```
operator-sdk version: "v1.3.2", commit: "5dd883dc90085da6a6e75bb05443b4d491a39143", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
```

`$ go version` (if language is Go)

```
go version go1.15.8 linux/amd64
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+d670f74", GitCommit:"d670f744c7507b1afebfa72ef3f79bf924ad5467", GitTreeState:"clean", BuildDate:"2021-05-21T13:35:23Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by varshaprasad96** [comment]
@aharbis One more way could be to set this in controller-gen options. Can you try setting this in `Makefile` (similar to this): https://github.com/operator-framework/operator-sdk/blob/6351af55dd38c88ca19114d0c165eadec5c82143/testdata/go/v3/memcached-operator/Makefile#L41

**Comment by aharbis** [comment]
@varshaprasad96 Yes, except that's broken for `v1` CRDs: https://github.com/kubernetes-sigs/controller-tools/issues/476

**Comment by jberkhahn** [comment]
If this happens soonish we can backport it to a patch release for 1.12.0, but otherwise we think this is fine for 1.13.0.

**Comment by laxmikantbpandhare** [comment]
We investigated the issue, and found that the kustomize generates the yaml fields by taking inputs from the patch/ dir, while generating bundle we Marshal the crd to bytes so that it is written to a file. While marshalling, as the preserveUnknownFields has the omitempty tag on it, its default value is false and hence its not explicitly written. This brings us to the same problem as faced in controller-gen which is mentioned in [here](https://github.com/kubernetes-sigs/controller-tools/issues/476#issuecomment-890263574).

The only option we found it to write it explicitly into yaml file using script.

Script is:

```
function generate_preserveUnknownFieldsdata() {
    for j in config/crd/patches/*.yaml ; do
        if grep -qF "preserveUnknownFields" "$j";then
            variable=`awk '/metadata/{flag=1} flag && /name:/{print $NF;flag=""}' "$j"`
            for k in config/crd/bases/*.yaml ; do
                if grep -qF "$variable" "$j";then
                    filename=`awk 'END{ var=FILENAME; split (var,a,/\//); print a[4]}' "$k"`
                    awk '/^spec:/{print;print "  preserveUnknownFields: false";next}1' "bundle/manifests/$filename" > testfile.tmp && mv testfile.tmp "bundle/manifests/$filename"
                fi
            done
        fi
    done
}

generate_preserveUnknownFieldsdata
```

Also, modified the **make bundle** in **Makefile** as shown in below:

```
.PHONY: bundle
bundle: manifests kustomize ## Generate bundle manifests and metadata, then validate generated files.
	operator-sdk generate kustomize manifests -q
	cd config/manager && $(KUSTOMIZE) edit set image controller=$(IMG)
	$(KUSTOMIZE) build config/manifests | operator-sdk generate bundle -q --overwrite --version $(VERSION) $(BUNDLE_METADATA_OPTS)
	operator-sdk bundle validate ./bundle | ./preserve_script.sh
```

We are planning to document these as a FAQ to the docs section.

**Comment by laxmikantbpandhare** [comment]
We investigated the issue, and found that the kustomize generates the yaml fields by taking inputs from the patch/ dir, while generating bundle we Marshal the crd to bytes so that it is written to a file. While marshalling, as the preserveUnknownFields has the omitempty tag on it, its default value is false and hence its not explicitly written. This brings us to the same problem as faced in controller-gen which is mentioned in [here](https://github.com/kubernetes-sigs/controller-tools/issues/476#issuecomment-890263574).

The only option we found it to write it explicitly into yaml file using script.

Script is:

```
function generate_preserveUnknownFieldsdata() {
    for j in config/crd/patches/*.yaml ; do
        if grep -qF "preserveUnknownFields" "$j";then
            variable=`awk '/metadata/{flag=1} flag && /name:/{print $NF;flag=""}' "$j"`
            for k in config/crd/bases/*.yaml ; do
                if grep -qF "$variable" "$j";then
                    filename=`awk 'END{ var=FILENAME; split (var,a,/\//); print a[4]}' "$k"`
                    awk '/^spec:/{print;print "  preserveUnknownFields: false";next}1' "bundle/manifests/$filename" > testfile.tmp && mv testfile.tmp "bundle/manifests/$filename"
                fi
            done
        fi
    done
}

generate_preserveUnknownFieldsdata
```

Also, modified the **make bundle** in **Makefile** as shown in below:

```
.PHONY: bundle
bundle: manifests kustomize ## Generate bundle manifests and metadata, then validate generated files.
	operator-sdk generate kustomize manifests -q
	cd config/manager && $(KUSTOMIZE) edit set image controller=$(IMG)
	$(KUSTOMIZE) build config/manifests | operator-sdk generate bundle -q --overwrite --version $(VERSION) $(BUNDLE_METADATA_OPTS)
	operator-sdk bundle validate ./bundle | ./preserve_script.sh
```

We are planning to document these as a FAQ to the docs section.
