### ISSUE TITLE
Documentation RFE: Advanced Topics - ComponentConfig

### ISSUE THREAD

**Issue by fgiloux** [operator-framework/operator-sdk#5104]
I could not find any reference to ComponentConfig in operator-sdk documentation:
https://book.kubebuilder.io/component-config-tutorial/tutorial.html

This is an important aspect for controlling any advance functionality of the controller:
- cleansing policies
- sync period
- logging level
- feature gates

IMHO this should be part of best practices for development of any advanced operator.

The current alternative of relying on feature flags has several limitations, for instance:
- any configuration change requires the controller deployment to be changed and the controller to be restarted
- this does not support any data structure / validation and little self documentation
- this is not gitOps friendly: the deployment is created at installation time and needs to be patched afterwards, whereas a configuration resource can just be applied onto the default one.

**Comment by jberkhahn** [comment]
should probably go in this section: https://sdk.operatorframework.io/docs/best-practices/

**Comment by laxmikantbpandhare** [comment]
I can take a look into it. I recently worked on `--component-config` flag enablement in Kubebuilder. /assign

**Comment by scotRinga-MayaDog** [comment]
***@***.***
