### ISSUE TITLE
Link to scorecard is invalid within https://sdk.operatorframework.io/docs/faqs/

### ISSUE THREAD

**Issue by planetf1** [operator-framework/operator-sdk#5116]
### What is the URL of the document?

https://sdk.operatorframework.io/docs/faqs/

### Which section(s) is the issue in?

Within the section

What are the the differences between Kubebuilder and Operator-SDK?

In text

Operator SDK scorecard, a tool for ensuring operator best-practices and developing cluster tests

### What needs fixing?

A correct url for scorecard documentation

The link currently is https://sdk.operatorframework.io/docs/advanced-topics/scorecard/ which is invalid

Possibly

https://sdk.operatorframework.io/docs/testing-operators/scorecard/

**Comment by estroz** [comment]
The suggested link is correct. You can actually specify `/docs/testing-operators/scorecard` as the link. Feel free to submit a fix, otherwise someone else will! If so please assign yourself here.

**Comment by planetf1** [comment]
Sure, I can do a pr tomorrow

**Comment by planetf1** [comment]
It looks as if this was fixed by @timflannagan in 820764f26d506f748ef8928f35731091e34f3ad4 on 2 Aug
The definition of '[scorecard-doc]' was incorrect.
So this looks ok in master.

Whilst the website at  https://sdk.operatorframework.io/docs/faqs/ is still showing the old link , by explicitly navigating to master, this page becomes https://master.sdk.operatorframework.io/docs/ where the link is correct.

So I presume the docs will be published for the next release of the sdk and will then be corrected.

Good to understand more about the docs.. Closing
