### ISSUE TITLE
operator-sdk bundle regression - no longer honours --input-dir and/or --output-dir

### ISSUE THREAD

**Issue by phantomjinx** [operator-framework/operator-sdk#5143]
#### What did you do?
Syndesis [project](https://github.com/syndesisio/syndesis/tree/1.13.x/install/operator/config) has been using operator-sdk 1.5.0 for bundle generation. Due to historical circumstances, the Makefile & PROJECT files were located in the config directory and all paths to `config/` were updated to `.`.

Therefore the [command](https://github.com/syndesisio/syndesis/blob/1.13.x/install/operator/config/Makefile#L245) for generating the `config/manifests` directory looks like this:
```
operator-sdk generate kustomize manifests \
  --apis-dir ../api \
  --input-dir manifests \
  --output-dir manifests
```

However, an update of the operator-sdk to 1.9.2 causes problems.

Rather than the existing `config/manifests` directory being observed and used, a new arbitrary `config/config/manifests` directory is created instead. This means any customisations to the base CSV are ignored and the resulting bundle produced incorrectly.

#### Reproduced Using memcached Tutorial
1. Created a template memcached project ([commit](https://github.com/phantomjinx/memcached-operator/commit/0f72494e6f13a3a7a60893421c480e42636114ba)) using the [tutorial](https://v1-9-x.sdk.operatorframework.io/docs/building-operators/golang/tutorial/);
2. Moved the Makefile and PROJECT into the config directory and customized accordingly (see [commit](https://github.com/phantomjinx/memcached-operator/commit/78fb1c8787ff428ae5e863585a6c74876269cc5c));
3. Downgraded ([commit](https://github.com/phantomjinx/memcached-operator/commit/0fa034e3b10730031ccdf3e05015ad76edd5e47f)) to kubebuilder v2 to be compatible with operator-sdk 1.5.0 and executed `make bundle` ---> Bundle created correctly and no new config directory;
4. Switched to operator-sdk 1.5.1 and repeated `make bundle` --> Bundle created correctly and no new config directory;
5. Switched to operator-sdk 1.6.1 and repeated `make bundle` --> New `config/config/manifests` directory created ([commit](https://github.com/phantomjinx/memcached-operator/commit/875e7aeac6892bf346640e1352a0976ff532a43c)).

#### What did you expect to see?
- `make bundle` observe existing `config/manifests` directory;
- No new `config/config/manifests` directory

#### What did you see instead? Under which circumstances?
- `config/config/manifests` directory created from scratch

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

`$ operator-sdk version`

1. operator-sdk version: "v1.5.0", commit: "98f30d59ade2d911a7a8c76f0169a7de0dec37a0", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
2. operator-sdk version: "v1.5.1", commit: "b1db0a5863923d4d37f562f16541f68bc7ab9ed5", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
3. operator-sdk version: "v1.6.1", commit: "e6981d812a759442a583d8ee2fae269507c408d4", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
4. operator-sdk version: "v1.9.2", commit: "319e77f2fff57c6c862bddd64ecf9c562f2d2161", kubernetes version: "1.20.2", go version: "go1.16.6", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)
go version go1.15.8 linux/amd64

`$ kubectl version`
Client Version: 4.7.1
Server Version: 4.8.2
Kubernetes Version: v1.21.1+051ac4f

#### Possible Solution
Code change between 1.5.1 and 1.6.1 meant `--input-dir` and/or `--output-dir` no longer respected?

**Comment by phantomjinx** [comment]
Tested `1.11.0` and `1.10.1` - both fail like `1.6.1`.

**Comment by phantomjinx** [comment]
![bisect](https://user-images.githubusercontent.com/1634180/129370542-b9984454-e25e-4161-949e-2ebca33b742f.png)

`git bisect` showing regression
```
operator-sdk version: "scorecard-kuttl/v2.0.0-21-g163c6575", commit: "163c657565ad136fc1f6c453803e1af8306f0b63", kubernetes version: "v1.19.4", go version: "go1.15.8", GOOS: "linux", GOARCH: "amd64"
```

**Comment by phantomjinx** [comment]
The result of the bug in Syndesis is that the manager directory is not included, leading to no deployment is the final bundle. The reason for this is that the `manifest/kustomization.yaml` [file](https://github.com/syndesisio/syndesis/blob/1.13.x/install/operator/config/manifests/kustomization.yaml#L26) does not include a `../default` path whereas the default version does.
This makes a difference because the deployment is included in the bundle in my memcached-operator example since it uses the standard `./default` directory.

Anyway, have create a [PR](https://github.com/operator-framework/operator-sdk/pull/5144) which solves the issue and works when `outputDir` is both set and unset.

**Comment by varshaprasad96** [comment]
Closing this as we have the PR merged.
