### ISSUE TITLE
Helm operator: Reconciler error, Operation cannot be fulfilled, the object has been modified

### ISSUE THREAD

**Issue by kkujawa-sumo** [operator-framework/operator-sdk#5145]
#### What did you do?

I observe following error in logs for https://github.com/SumoLogic/sumologic-kubernetes-collection-helm-operator which bases on operator-sdk v1.11.0:
```
{"level":"error","ts":1628873504.7538075,"logger":"controller-runtime.manager.controller.sumologiccollection-controller","msg":"Reconciler error","name":"mock-openshift","namespace":"sumologic-system","error":"Operation cannot be fulfilled on sumologiccollections.helm-operator.sumologic.com \"mock-openshift\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214"}
```
The object was not modified by me.
Checking changes in related resource I see that differences are in `time` and `resourceVersion`:
```
$ diff collection1.yaml collection2.yaml
53c53
<     time: "2021-08-13T16:49:42Z"
---
>     time: "2021-08-13T16:52:34Z"
56c56
<   resourceVersion: "43327"
---
>   resourceVersion: "44517"
```

Despite the fact that mentioned error appears in logs I don't see any issue with functional work of Helm operator. 

**Steps to reproduce**
- Deploy [Sumologic Kubernetes Collection Helm Operator](https://github.com/SumoLogic/sumologic-kubernetes-collection-helm-operator)
```
kubectl apply -f "https://raw.githubusercontent.com/SumoLogic/sumologic-kubernetes-collection-helm-operator/v2.1.4-0-rc.2/bundle.yaml"
```

- Deploy receiver mock (needed to test Sumologic Kubernetes Collection Helm Operator)
```
kubectl apply -f "https://raw.githubusercontent.com/SumoLogic/sumologic-kubernetes-collection/release-v2.1/vagrant/k8s/receiver-mock.yaml"
```

- Wait for Helm Operator to be ready
```
kubectl wait --for=condition=ready --timeout 300s pod -l control-plane=sumologic-kubernetes-collection-helm-operator -n sumologic-system
```

- Create resource for Sumologic Kubernetes Collection Helm Operator
```
kubectl apply -f "https://raw.githubusercontent.com/SumoLogic/sumologic-kubernetes-collection-helm-operator/v2.1.4-0-rc.2/config/samples/receiver_mock_openshift.yaml" -n sumologic-system
```

- Wait for Pods related to Sumologic Kubernetes Collection to be created, example list of pods:
```
$ kubectl get pods -n sumologic-system
NAME                                                   READY   STATUS    RESTARTS   AGE
mock-openshift-fluent-bit-52tzf                        1/1     Running   0          76s
mock-openshift-fluent-bit-6bnz7                        1/1     Running   0          76s
mock-openshift-fluent-bit-7tpn2                        1/1     Running   0          76s
mock-openshift-fluent-bit-kc7l6                        1/1     Running   0          76s
mock-openshift-fluent-bit-krdbt                        1/1     Running   0          76s
mock-openshift-fluent-bit-pmpmx                        1/1     Running   0          76s
mock-openshift-fluent-bit-px2z8                        1/1     Running   0          76s
mock-openshift-fluent-bit-sn9cm                        1/1     Running   0          76s
mock-openshift-kube-promet-operator-666fbc98f8-smz6h   1/1     Running   0          76s
mock-openshift-kube-state-metrics-7f974b5494-g4v2l     1/1     Running   0          76s
mock-openshift-prometheus-node-exporter-5nf4q          1/1     Running   0          76s
mock-openshift-prometheus-node-exporter-6hqkr          1/1     Running   0          76s
mock-openshift-prometheus-node-exporter-6xwsv          1/1     Running   0          76s
mock-openshift-prometheus-node-exporter-7h9rr          1/1     Running   0          76s
mock-openshift-prometheus-node-exporter-dbgbm          1/1     Running   0          76s
mock-openshift-prometheus-node-exporter-hjn5c          1/1     Running   0          76s
mock-openshift-prometheus-node-exporter-qlvwb          1/1     Running   0          76s
mock-openshift-prometheus-node-exporter-wnx77          1/1     Running   0          76s
mock-openshift-sumologic-fluentd-events-0              0/1     Running   0          76s
mock-openshift-sumologic-fluentd-logs-0                0/1     Running   0          76s
mock-openshift-sumologic-fluentd-logs-1                0/1     Running   0          76s
mock-openshift-sumologic-fluentd-logs-2                0/1     Running   0          76s
mock-openshift-sumologic-fluentd-metrics-0             0/1     Running   0          76s
mock-openshift-sumologic-fluentd-metrics-1             0/1     Running   0          76s
mock-openshift-sumologic-fluentd-metrics-2             0/1     Running   0          76s
prometheus-mock-openshift-kube-promet-prometheus-0     3/3     Running   1          54s
sumologic-helm-operator-5544b4fc8f-hvc7j               2/2     Running   0          3m45s
```
- Save current state of `SumologicCollection` (custom resource for Sumologic Kubernetes Collection Helm Operator)

```
kubectl get SumologicCollection -n sumologic-system mock-openshift -o yaml > collection1.yaml
```
- Observe logs and wait for `Reconciler error`

- Save new state of `SumologicCollection`

```
kubectl get SumologicCollection -n sumologic-system mock-openshift -o yaml > collection2.yaml
```

- Compare differences:
```
$ diff collection1.yaml collection2.yaml
53c53
<     time: "2021-08-13T16:49:42Z"
---
>     time: "2021-08-13T16:52:34Z"
56c56
<   resourceVersion: "43327"
---
>   resourceVersion: "44517"
```
<img width="1385" alt="diff" src="https://user-images.githubusercontent.com/73836361/129569905-ab131453-4ab6-4158-9d4c-6898e67aa924.png">

#### What did you expect to see?

No errors in logs related to Reconciler.
I'm not sure if `resourceVersion` and `time` should be changed between reconciliation loops.

#### What did you see instead? Under which circumstances?

I see reconciler error saying that the object was modified and operation cannot be fulfilled but the object was not modified by me. I don't observe any issue with functional work of Helm operator.

#### Environment

**Operator type:**

/language helm

**Kubernetes cluster type:** OpenShift 4.6.4

`$ operator-sdk version` v1.11.0 (base image for sumologic-kubernetes-collection-helm-operator)
https://github.com/SumoLogic/sumologic-kubernetes-collection-helm-operator bases on operator-sdk v1.11.0, see [here](https://github.com/SumoLogic/sumologic-kubernetes-collection-helm-operator/blob/a724dd72b159f201934659a2fdcfb0cca5619385/Dockerfile#L2)

`$ go version` (if language is Go)

`$ kubectl version` 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13", GitCommit:"53c7b65d4531a749cd3a7004c5212d23daa044a9", GitTreeState:"clean", BuildDate:"2021-08-09T20:35:06Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+9f84db3", GitCommit:"9f84db336d1a77cba52684ecb51bfb197e9b4533", GitTreeState:"clean", BuildDate:"2020-10-30T09:33:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by kkujawa-sumo** [comment]
On OpenShift 4.7.6 I see this error in only once - after creation of `SumologicCollection` resource.

**Comment by kkujawa-sumo** [comment]
I think that it explains what is happening https://github.com/kubernetes/kubernetes/issues/84430#issuecomment-638376994, probably in this scenario k8s needs more time to handle previous update from operator and in the meantime operator does not see changes in the cluster and it tries to update again

some people try to handle this error in following way:
- https://github.com/kubernetes/kubernetes/issues/28149#issuecomment-738712722
- https://github.com/goharbor/harbor-operator/pull/496
- https://github.com/cockroachdb/cockroach-operator/pull/597

**Comment by declum** [comment]
What is the best way to recover from this error?

> {"level":"info","ts":1640235907.168132,"logger":"helm.controller","msg":"Reconciled release","namespace":"default","name":"laravel-git-vanilla","apiVersion":"app.letout.io/v1alpha1","kind":"Laravel","release":"laravel-git-vanilla"}
> {"level":"info","ts":1640235907.399596,"logger":"helm.controller","msg":"Reconciled release","namespace":"default","name":"laravel-git-horizon","apiVersion":"app.letout.io/v1alpha1","kind":"Laravel","release":"laravel-git-horizon"}
> 
> {"level":"info","ts":1640235908.289975,"logger":"helm.controller","msg":"Reconciled release","namespace":"default","name":"laravel-git-vanilla","apiVersion":"app.letout.io/v1alpha1","kind":"Laravel","release":"laravel-git-vanilla"}
> {"level":"info","ts":1640235908.435151,"logger":"helm.controller","msg":"Reconciled release","namespace":"default","name":"laravel-git-horizon","apiVersion":"app.letout.io/v1alpha1","kind":"Laravel","release":"laravel-git-horizon"}
> {"level":"error","ts":1640235908.6716218,"logger":"controller.laravel-controller","msg":"Reconciler error","name":"laravel-git-vanilla","namespace":"default","error":"Operation cannot be fulfilled on laravels.app.letout.io \"laravel-git-vanilla\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227"}
> {"level":"error","ts":1640235908.821305,"logger":"controller.laravel-controller","msg":"Reconciler error","name":"laravel-git-horizon","namespace":"default","error":"Operation cannot be fulfilled on laravels.app.letout.io \"laravel-git-horizon\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227"}
