### ISSUE TITLE
Go Operator Tutorial does not provide working memcached operator

### ISSUE THREAD

**Issue by alex-treebeard** [operator-framework/operator-sdk#5146]
Thanks for this tutorial!

As far as I can see (from running through the tutorial), this tutorial does not provide controller logic for creating Memcached pods. I can deploy my operator but when I create my CR, the controller takes no meaningful action.

(Note: I'm pretty inexperienced with Go, may be missing something).

The following just prints `0` for the spec size whenever I apply CR changes.

```go
//+kubebuilder:rbac:groups=cache.example.com,resources=memcacheds,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=cache.example.com,resources=memcacheds/status,verbs=get;update;patch
//+kubebuilder:rbac:groups=cache.example.com,resources=memcacheds/finalizers,verbs=update
//+kubebuilder:rbac:groups=apps,resources=deployments,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=core,resources=pods,verbs=get;list;

func (r *MemcachedReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	_ = log.FromContext(ctx)

	memcached := &cachev1alpha1.Memcached{}
	println(memcached.Spec.Size)
	err := r.Get(ctx, req.NamespacedName, memcached)

	return ctrl.Result{}, err
}
```

**Comment by VenkatRamaraju** [comment]
Hi,

The [tutorial](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#implement-the-controller) links to a sample Memcached controller [implementation](https://github.com/operator-framework/operator-sdk/blob/latest/testdata/go/v3/memcached-operator/controllers/memcached_controller.go) that can be used to reconcile the operator to the desired state. Is this what you are looking for?

**Comment by alex-treebeard** [comment]
> Hi,
> 
> 
> 
> The [tutorial](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#implement-the-controller) links to a sample Memcached controller [implementation](https://github.com/operator-framework/operator-sdk/blob/latest/testdata/go/v3/memcached-operator/controllers/memcached_controller.go) that can be used to reconcile the operator to the desired state. Is this what you are looking for?

Thanks, I should read more carefully 🙂
