### ISSUE TITLE
Add labels to CRD YAML files

### ISSUE THREAD

**Issue by matancarmeli7** [operator-framework/operator-sdk#5152]
## Type of question

General operator-related help

## Question
Hi,
how can I add labels to a CRD YAML file
#### What did you do?
I tried to add this code in the `kustomization.yaml` file but it didn't help (it worked with `role.yaml`):
```
patchesStrategicMerge:
- patches/labels_patch.yaml
```
There is something that I can do to do it?
thanks
#### Environment

**Operator type:**

language go

**Kubernetes cluster type:**

`$ operator-sdk version`
```
operator-sdk version: "v1.9.0-11-gad645e4b", commit: "ad645e4bc6d6ae85fa5f0bffcad3bc871690608c", kubernetes version: "v1.20.2", go version: "go1.15", GOOS: "linux", GOARCH: "amd64"
```

`$ go version` (if language is Go)
```
go version go1.15.14 linux/amd64
```

**Comment by kensipe** [comment]
@matancarmeli7 this issue looks upstream related... this question is better handled within the kustomize community.  Closing for now... but please re-open if there is a operator sdk specific concern to address.  thanks again!
