### ISSUE TITLE
unable to inject the resource to "base.helm.sdk.operatorframework.io/v1": repo ~ not found 

### ISSUE THREAD

**Issue by weiwendi** [operator-framework/operator-sdk#5158]
## Type of question

General operator-related help

## Question
unable to inject the resource to "base.helm.sdk.operatorframework.io/v1": repo ~ not found 
#### What did you do?
1. Clone my chart from Github repository.
2. Use operator-sdk init project.

`$ operator-sdk init --plugins=helm --domain=quay.io --helm-chart=~/learn-helm/helm-charts/charts/player-stats --kind player-stats`

#### What did you expect to see?
I expect the command to pass without errors.

#### What did you see instead? Under which circumstances?
Writing kustomize manifests for you to edit...
Creating the API:
$ operator-sdk create api --kind player-stats --helm-chart ~/learn-helm/helm-charts/charts/player-stats
Error: failed to create API: unable to inject the resource to "base.helm.sdk.operatorframework.io/v1": repo ~ not found
Usage:
  operator-sdk create api [flags]

FATA[0000] failed to create API: unable to inject the resource to "base.helm.sdk.operatorframework.io/v1": repo ~ not found 
Error: failed to initialize project: unable to run post-scaffold tasks of "base.helm.sdk.operatorframework.io/v1": exit status 1
Usage:
  operator-sdk init [flags]

#### Environment

**Operator type:**

 /language helm

**Kubernetes cluster type:**
Kubernetes Cluster.

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by weiwendi** [comment]
Add operator-sdk version: v1.11.0
        kubectl version: v1.21.1

**Comment by weiwendi** [comment]
Command error.

**Comment by weiwendi** [comment]
Kind: must start with an uppercase character

**Comment by varshaprasad96** [comment]
@weiwendi  Resource kind does [need](https://github.com/kubernetes-sigs/kubebuilder/blob/5ca8884a1929e2995e10339fc87122b1ccabefa1/pkg/model/resource/gvk.go#L79) to start with Upper case. This is being validated in the plugin. Does that fix the issue?

**Comment by kensipe** [comment]
Thanks for helping to make the operator sdk project better.  It seem the original issue was resolved.  If there is another issue to address please follow up with another issue.  thanks again!

**Comment by rubenhak** [comment]
The error message is misleading. I was getting the same error if the path indicated in **--helm-chart** does not exist. Hope it would be helpful for someone else struggling with this error.
