### ISSUE TITLE
Ansible docs - zap logging

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#5161]
https://sdk.operatorframework.io/docs/building-operators/golang/references/logging/#default-zap-logger

zap logging config is mentioned in the go docs, but not for Ansible. Should this info be moved to a non-specific language section or added to Ansible?

**Comment by kensipe** [comment]
For helpful insights chat with @asmacdo

**Comment by anupchandak** [comment]
Any plan to address this?
