### ISSUE TITLE
go-get-tool fails if project directory path contains spaces

### ISSUE THREAD

**Issue by planetf1** [operator-framework/operator-sdk#5163]
#### What did you do?

Tried to run a Makefile build by operator-idk, known to work
The exact directory had already been used to build an operator, and tools were already downloaded including in 'bin'
However I had rebooted, and running a different OS version (Monterey vs Big Sur), but with the same directory used for my source

#### What did you expect to see?
Previously downloaded tools such as customise, already in bin/ would just be used by make as normal

#### What did you see instead? Under which circumstances?

```
$ make controller-gen                                                                                                 [10:44:49]
bash: line 1: [: /Volumes/Macintosh: binary operator expected
go: creating new go.mod: module tmp
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.6.1
bash: line 1: HD/Users/jonesn/IdeaProjects/egeria-k8s-operator/bin: No such file or directory
make: *** [controller-gen] Error 127
jonesn:egeria-k8s-operator/ (opdev1*) $        
```

The issue appears to be the SPACE in the directory now being used, caused by the Makefile entry:
```
PROJECT_DIR := $(shell dirname $(abspath $(lastword $(MAKEFILE_LIST))))
define go-get-tool
@[ -f $(1) ] || { \
set -e ;\
TMP_DIR=$$(mktemp -d) ;\
cd $$TMP_DIR ;\
go mod init tmp ;\
echo "Downloading $(2)" ;\
GOBIN=$(PROJECT_DIR)/bin go get $(2) ;\
rm -rf $$TMP_DIR ;\
}
endef
```

As can be seen, my cwd has spaces:
```
jonesn:egeria-k8s-operator/ (opdev1*) $ pwd                                                                                                                 [10:45:54]
/Volumes/Macintosh HD/Users/jonesn/IdeaProjects/egeria-k8s-operator
```

If instead I am in
```
jonesn:egeria-k8s-operator/ (opdev1*) $ pwd                                                                                                                 [10:49:01]
/Users/jonesn/IdeaProjects/egeria-k8s-operator
```

Then all works fine

So this isn't really about Monterey vs Big Sur, or the different environment, it's just about the variable expansion and
errors if the directory contains a space (maybe other chars). Needs quoting in the function

#### Environment
macOS Monterey, homebrew, go 1.16

**Operator type:**
go

/language go

**Kubernetes cluster type:**
OpenShift 4.7

`$ operator-sdk version`

 operator-sdk version                                                                                                [10:51:55]
operator-sdk version: "v1.11.0", commit: "28dcd12a776d8a8ff597e1d8527b08792e7312fd", kubernetes version: "v1.20.2", go version: "go1.16.6", GOOS: "darwin", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.16.6 darwin/amd64

`$ kubectl version`

 $ kubectl version                                                                                                     [10:52:27]
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+87cc9a4", GitCommit:"87cc9a4ade7ebee64def2489b78c9d8ae5d6fdf9", GitTreeState:"clean", BuildDate:"2021-06-19T03:11:54Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1

**Comment by kensipe** [comment]
In the triage meeting today, we identified that this is a good first issue.  It seems isolated to `make` and scripts.  @planetf1 thanks for raising the issue here... we welcome a pull request if you are up for it.  We have a number of people here or on slack that can provide feedback and guidance if needed.

thanks for helping to make operator sdk awesome

**Comment by pravarag** [comment]
@kensipe can I work on this issue if there is no-one already working on it?

**Comment by planetf1** [comment]
@pravarag I've unfortunately not had the chance yet so ok by me
