### ISSUE TITLE
Add the service account field to the custom scorecard test configuration

### ISSUE THREAD

**Issue by dirgim** [operator-framework/operator-sdk#5169]
#### Describe the problem you need a feature to resolve.
Currently, the `operator-sdk scorecard` command has the `service-account` option to specify a non-standard service account that the operator developer wants to use when testing their operator. This is entirely sufficient for manual testing where the developers/testers are aware of their testing setup and configuration.

However, when attempting to run the same tests within an automated pipeline (such as CVP), there is no way for the pipeline to determine which service account needs to be used because that information doesn't carry over from the development environment as it's not specified within the bundle's contents.

#### Describe the solution you'd like.
Adding the service account field to the custom scorecard test configuration at `tests/scorecard/config.yaml` would allow the `operator-sdk scorecard` command to automatically use the specified service account without the need for users (or, more importantly, the testing pipelines) to manually specify it when running the command.

The CLI command option can, of course still override the one specified in the test configuration.

**Comment by jberkhahn** [comment]
This is a good idea, but would be good to have definitive behavior if the specified service account does not exist - such as erroring out to avoid undefined behavior. Also have to think about whether to put this in the single scorecard config or make a separate file - maybe containing the other cluster-specific flag(s?) such as namespace to run the tests in. Also keep in mind backwards-compatability of whatever solution we go with.

**Comment by maneeshmehra** [comment]
@theishshah: When you get a chance, can you please also provide an ETA on this item ? Please note that this is blocking CVP-2275 story on the Container Verification Pipelines team. This story happens to be the last story on the epic on custom functional testing of operators (CVP-762) and we'd like to understand if we will be able to close this committed epic in Q3 timeframe or not. Thanks in advance for your help.

**Comment by dirgim** [comment]
@theishshah can you give us an update on this item? I can see that a [PR implementing this request](https://github.com/operator-framework/api/pull/153) is in review, but have seen no changes in the last 15 days.

**Comment by maneeshmehra** [comment]
HI SDK team: Please note that this item is blocking CVP team on CVP-2275 and in-return, managed service operator product team(s). We'd really appreciate if someone from the team could provide us with an ETA on when this issue will be resolved and when the CVP team will be able to adopt the next version of the SDK containing the fixes. Thanks.

**Comment by jmrodri** [comment]
Move this issue back to 1.13, it is a blocker for 1.13.

**Comment by theishshah** [comment]
#5245 is the SDK side implementation of the configurable setting added to the API repo. Following an API release and merge into the SDK we can bring in the above PR and have this done.

**Comment by theishshah** [comment]
Feature has merged on the SDK, it will be included in the upcoming release.

**Comment by maneeshmehra** [comment]
That's awesome ! Thanks for all your help.
