### ISSUE TITLE
pkgman-to-bundles does not propagate channels from channel heads

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-sdk#5170]
#### What did you do?

```
git clone https://github.com/k8s-operatorhub/community-operators
cd community-operators/operators
operator-sdk pkgman-to-bundle etcd etcd-bundles
cat etcd-bundles/bundle-0.9.0/bundle/metadata/annotations.yaml
```

#### What did you expect to see?

I expected the command to automatically traverse the replaces chain from each channel head to set the correct channels for all bundles. For example, I expected 0.9.0 to be in channels:
- `clusterwide-alpha` due to being in replaces chain of `0.9.4-clusterwide`
- `singlenamespace-alpha` due to being in the replaces chain of `0.9.4`

Also side note (this does not happen for this operator): I would NOT expect bundles to be added to the default channel as a default unless they're actually in the replaces chain for that channel. Put another way, I would expect bundles to _only_ be added to channels based on traversing `replaces` values from channel heads.

#### What did you see instead? Under which circumstances?

In the `operator-sdk pkgman-to-bundle etcd etcd-bundles` output, I see:

```
INFO[0000] Supported channels cannot be identified from CSV etcdoperator.v0.9.0, using default channel singlenamespace-alpha 
```

In the `0.9.0/metadata/annotations.yaml` file, I see:
```
  operators.operatorframework.io.bundle.channels.v1: singlenamespace-alpha
```

#### Environment

**Operator type:**

N/A

**Kubernetes cluster type:**

N/A

`$ operator-sdk version`

```
operator-sdk version: "v1.11.0-4-g47d8d671", commit: "47d8d6714e75d858297f42088ce2ec32bd809e00", kubernetes version: "v1.21", go version: "go1.16.7", GOOS: "darwin", GOARCH: "arm64"
```

`$ go version` (if language is Go)

```
go version go1.16.7 darwin/arm64
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by varshaprasad96** [comment]
@rashmigottipati would we be able to get this in v1.16.0 milestone? If not we can bump it to the next one.
