### ISSUE TITLE
Have we considered a plugin writers library?

### ISSUE THREAD

**Issue by jmrodri** [operator-framework/operator-sdk#5173]
#### Describe the problem you need a feature to resolve.

While writing the java-operator-plugins, I have found myself copying some of the useful [utility functions](https://github.com/operator-framework/operator-sdk/blob/master/internal/util/utils.go) currently hidden in `internal` directories.

#### Describe the solution you'd like.

I know we've tried to keep public APIs out of operator-sdk since v1.0.x, I think we should keep doing that. But what if we create an `sdk-plugin-lib` project or we can call it `skafos` a ship in greek and sounds like scaffold which plugins typically do :) I know I'm reaching now.

But having some of these utilities that we have in SDK public to use in external plugins would be great. I know this doesn't solve the issue for plugins written in other languages, but still it will be good examples for those languages to model as well.

/language go
/language java

**Comment by jberkhahn** [comment]
TODO: refactor the util stuff that was needed for the Java plugin, and we'll reconvene and discuss what the solution for that looks like WRT moving more stuff around.
