### ISSUE TITLE
Running alternative namespace with own SCCs when bundled

### ISSUE THREAD

**Issue by jaredoconnell** [operator-framework/operator-sdk#5175]
I am trying to have my ansible operator use a separate namespace with its own serviceaccount and SCCs that allow my operator to deploy a daemonset with the ability to use hostnetwork.

I got it working when using "make deploy" by creating a section of kustomizaiton that doesn't have its items prefixed, and it deploys the namespace, serviceaccount, and security context constraint.

However, the problem is when it's bundled. Bundled, it throws out the namespacing and the SCCs.
Here is the relevant folder: https://github.com/redhat-performance/cluster-impairment-operator/tree/0c504f03f5a2ac874f95aa165ca204ed7b02779c/config/network-access

What is the best way to resolve this issue? Thank you.

**Comment by varshaprasad96** [comment]
@jaredoconnell Do you mean that the manifests are not being included in the bundle directory? We could add additional service accounts with `--extra-service-accounts` flag in the `operator-sdk generate bundle` command. Also to add additional manifests to the bundle, we can include them to a `--deploy-dir` and specify the path using the flag.

**Comment by jberkhahn** [comment]
Also see this issue in OLM: https://github.com/operator-framework/operator-lifecycle-manager/issues/1547

It seems currently OLM bundles do not support creation of SCCs.

**Comment by jaredoconnell** [comment]
It looks like I will need to use a manual workaround for now (by manually applying the SCC). Thanks for the help.
