### ISSUE TITLE
The ako-operator.v1.4.2 unexpectedly fails the legacy operator-sdk scorecard test

### ISSUE THREAD

**Issue by dirgim** [operator-framework/operator-sdk#5176]
#### What did you do?

Run the operator-sdk scorecard test against the `ako-operator.v1.4.2` operator that's deployed on the cluster.

After running the following command:
```
operator-sdk scorecard --version=v1alpha2 --verbose --config /tmp/operator-test/osdk-scorecard.yml 
```
with the following osdk-scorecard.yml contents: http://pastebin.test.redhat.com/989990
the operator fails the `Status Block Exists` test.

The CRD that's being tested contents: http://pastebin.test.redhat.com/989991
The CR under test (extracted from the alm-examples) content: http://pastebin.test.redhat.com/989995

#### What did you expect to see?

A passing test for the `Status Block Exists` test.

#### What did you see instead? Under which circumstances?

The following result:
```
{
      "name": "Status Block Exists",
      "description": "Custom Resource has a Status Block",
      "labels": {
        "necessity": "required",
        "suite": "basic",
        "test": "checkstatustest"
      },
      "state": "fail",
      "suggestions": [
        "Add a 'status' field to your Custom Resource"
      ]
    }
```

#### Environment

**Kubernetes cluster type:**

OpenShift v4.5.41

`$ operator-sdk version`

operator-sdk version: "v0.15.2", commit: "ffaf278993c8fcb00c6f527c9f20091eb8dd3352", go version: "go1.13.3 linux/amd64"

`$ kubectl version`

Client Version: 4.4.13
Server Version: 4.5.0-0.nightly-2021-08-11-224754
Kubernetes Version: v1.18.3+d8ef5ad

#### Additional context

The operator is being tested as a backported bundle for v4.5.

**Comment by camilamacedo86** [comment]
@dirgim, 

If we run the same test for the same operator with sdk latest releases is this issue faced as well?

**Comment by jberkhahn** [comment]
It seems your pastebins aren't publically accessible? Can you post them somewhere everyone can access them?
