### ISSUE TITLE
Have support for building multi-arch operator images in Makefile and Dockerfile 

### ISSUE THREAD

**Issue by fgiloux** [operator-framework/operator-sdk#5180]
#### Describe the problem you need a feature to resolve.

Make easier the build of multi-arch operators.
Today the Dockerfile generated by operator-sdk init is explicitly setting GOARCH to amd64
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager main.go
The Makefile generated by the same command is explicitly using "docker build":
docker build -t ${IMG} .

Support for multi-arch builds have been requested a few times in the past, like here:
https://github.com/operator-framework/operator-sdk/issues/3071

#### Describe the solution you'd like.

A possible approach would be to add a --multi-arch flag to operator-sdk init with default value to false for backward compatibility. When set to true
- the generated Dockerfile would have:
RUN CGO_ENABLED=0 GOOS=linux GOARCH=$TARGETPLATFORM GO111MODULE=on go build -a -o manager main.go
- the Makefile would use buildx:
docker buildx build --platform ${TARGET_PLATFORMS} -t ${IMG}.
TARGET_PLATFORMS could default to amd64 in the Makefile

A similar approach could be used for more customization like using buildah/podman instead of docker

Benefits:
- Better user experience: multi-arch builds supported directly by setting a flag. No need to retrieve the required commands and change generated files
- Control by the SDK project of the Makefile and Dockerfile customization so that upgrades to newer versions of the SDK may not override changes made by users for supporting multi-arch builds

/language go

**Comment by varshaprasad96** [comment]
cc: @jmrodri

**Comment by camilamacedo86** [comment]
That is a request in KB: https://github.com/kubernetes-sigs/kubebuilder/issues/2175
The issue author raise a PR to address this solution: https://github.com/kubernetes-sigs/kubebuilder/pull/2197

But it did not land because @estroz let us know that: 
> --platform is a docker buildx feature and will not work with vanilla docker build (unless a new docker release added support that I do not know about).

**Comment by fgiloux** [comment]
/remove-lifecycle stale
this should most probably get implemented in kubebuilder but still an issue operator-sdk.
multi-arch is more and more becoming a thing.
