### ISSUE TITLE
Operator should work seamlessly with HPA

### ISSUE THREAD

**Issue by sxnguyen** [operator-framework/operator-sdk#5181]
## Feature Request
Operator should work seamlessly with HPA

#### Describe the problem you need a feature to resolve.

When HPA is created inside Operator, the issue was reported in [3367](https://github.com/operator-framework/operator-sdk/issues/3367)

#### Describe the solution you'd like.
I think there could be at least two possible solutions:
1. Operator should detect when a HPA is created, then detach itself from object that HPA is monitoring.
2. Operator should detect when a HPA is created, then monitor the `desiredReplicas` of the HPA, and update the `replicas` field of the deployment field when `desiredReplicas` > `replicas`

Thanks,

**Comment by jmrodri** [comment]
For other readers coming in later, HPA = Horizontal Pod Autoscaler.

**Comment by jmrodri** [comment]
@sxnguyen what operator type are you using? ansible? helm? go?

It also sounds like the operator is doing what it was designed to do. It is attempting to make the operand deployment as it was configured to do. So you have 2 controllers acting on the same object. Can you not build the operator such that it has a config that tells it HPA is active and not to reconcile the desired replicas? 

In option 2, are you suggesting that the operator monitors the HPA and does the work on behalf of HPA?

**Comment by sxnguyen** [comment]
@jmrodri : Thank you for reviewing the item.
We're using Ansible operator right now, but we do have plans to move to Go in the future.
 ```
Can you not build the operator such that it has a config that tells it HPA is active and not to reconcile the desired replicas?
```
---> I'm thinking of detaching the `ownerReferences`  of the object when it has HPA attach to it.  Would that be the right way to do it? If not, do you have any other ideas?

```
In option 2, are you suggesting that the operator monitors the HPA and does the work on behalf of HPA?
```
Sorry for not being clear.  Basically, I'm asking if it's possible to get Operator to take care of this [work-around](https://github.com/operator-framework/operator-sdk/issues/3367#issuecomment-673405140) automatically.  
If Operator can monitor HPA's `desiredReplicas` of the object (eg: deployment, sts, etc...), and update the object's `min_replicas`  with the value of `desiredReplicas`  when `desiredReplicas` != `min_replicas`.
For example:
HPA is configured on a deployment with `min/max`  as `2/4`.  Operator would deploy the deployment object with the `min_replicas: 2` initially.  In between reconcile, HPA scales to 4 due to load.  When Operator comes around, it detects there's a change, and will scale the deployment back to the original value of 2.

Thank you,
Scott
