### ISSUE TITLE
Ansible operator available at quay.io/operator-framework/ansible-operator are having vulnerabilities 

### ISSUE THREAD

**Issue by deeghuge** [operator-framework/operator-sdk#5184]
## Bug Report
Recent images of ansible operator are showing the multiple vulnerabilities. 

Details of Vulnerabilities --> [here](https://quay.io/repository/operator-framework/ansible-operator/manifest/sha256:193dbc046ffbf5606f8c86bf285945483907a9b9505c244e430eaa2033bda338?tab=vulnerabilities)

We are using **quay.io/operator-framework/ansible-operator** as base image to build image for operator

#### What did you do?

We are using this as base image to build image for operator

#### What did you expect to see?

Image with fixes for vulnerabilities. 

#### Environment

**Operator type:**

 /language ansible 

Thanks

**Comment by deeghuge** [comment]
Seems like the vulnerability are propagated from [ansible-operator-base](https://quay.io/repository/operator-framework/ansible-operator-base?tag=latest&tab=tags)

**Comment by camilamacedo86** [comment]
@Jainbrt Are you using the latest version available for ansible? 
Could you please let us know what is tag where are you checking it?

c/c @fabianvf @jmrodri

**Comment by Jainbrt** [comment]
@camilamacedo86 quay.io/operator-framework/ansible-operator:v1.11.0 base image only shows 4 high severity vulnerabilities only.

**Comment by Jainbrt** [comment]
@camilamacedo86 @fabianvf @jmrodri Could you please help us understand for the fix update, if any progress is there ?

**Comment by Jainbrt** [comment]
@jberkhahn @asmacdo thanks for your attention. When do we expect v1.13.0 to be released, as we are dependent for this fix to be in for our next product release in next 10 days?

**Comment by asmacdo** [comment]
@Jainbrt the base-base image is rebuilt, the user-facing base image will be rebuilt when I cut the v1.13.0 release today.

Apologies for the slow response, we get a lot of GH pings, so they are easy to miss. If it is important for us to get something looked at quickly, please feel free to chat with us on Kubernetes slack #operator-sdk-dev. Also feel free to join our community triage meetings. https://github.com/operator-framework/community/

**Comment by Jainbrt** [comment]
Thanks @asmacdo for your kind response and help on this issue. Sure I will chat with you if anything urgent comes up. 

BTW I still see 3 medium vulnerabilities with master image, do we have any plan to fix them also in coming releases ?

**Comment by asmacdo** [comment]
@Jainbrt yes, I ran another build and the security scan showed no vulnerabilities. This image will be included in the v1.13.0 release. 
![Screenshot from 2021-09-29 11-11-49](https://user-images.githubusercontent.com/1028657/135304305-d5f46a0e-4bd7-4c4a-8c88-5b0bee117789.png)



We had an undocumented manual step that was required in the release process. This gap has been identified and documented, so these images should not be this far out of date again. https://github.com/operator-framework/operator-sdk/pull/5261

**Comment by Jainbrt** [comment]
Thanks @asmacdo for the help here.
