### ISSUE TITLE
CRs are automatically updated in namespaces when CRD version is upgraded

### ISSUE THREAD

**Issue by huzefa51** [operator-framework/operator-sdk#5189]
#### What did you do?

We have our own operator which is running in all the namespaces with CR and CRD pointing to v1 version. 
Now we tried to update our CRD file with v2 version which includes some addition in spec definition.
After rolling this CRD with v2 version we have observed that all the CRs in all our namespaces automatically updated to v2 version. Our guess is this happened by our operator which is running in all the namespaces.
Would like to know what function in the code exactly doing this change? Because this behavior is bit strange as we don't want to get the CRs updated automatically in all namespaces.

#### What did you expect to see?
CRs should not be updated automatically in all the namespaces when new CRD version is rolled out.

#### What did you see instead? Under which circumstances?

All the CRs updated in all the namespaces to version v2.

#### Environment

**Operator type:**
Go Lang operator created using operator-sdk version v1.0.1, GO version go1.13.15

 /language go 

**Kubernetes cluster type:**

`$ operator-sdk version`
operator -sdk version: "v1.0.1"

`$ go version` (if language is Go)
go1.13.15

`$ kubectl version`
It's on Openshift version 4.5.0

**Comment by jberkhahn** [comment]
This should only happen if you implemented a conversion webhook. Is the old API (v1) of the CR still defined in your CRD? It's pretty normal to have multiple API versions of a resource exist on your cluster simultaneously to avoid this kind of  thing.

**Comment by jberkhahn** [comment]
Closing this due to lack of response.
