### ISSUE TITLE
How do we programmatically know what operator manages what operands?

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-sdk#5190]
## Question

Each operator can manage a group of operands, does there are any best practise to enable end user can know the operator and operands mapping? Like how do we programmatically know what operator manages what operands?

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by jberkhahn** [comment]
Who is trying to get this information, and from where? There are a variety of sources of information on this. Is this from an end user's perspective, or the operator's author, or someone else? Is it happening while writing the operator, trying to get this information from a running cluster that the operator is deployed on, or somewhere else?

**Comment by jberkhahn** [comment]
Closing this due to lack of response.
