### ISSUE TITLE
Skip creation of certain objects

### ISSUE THREAD

**Issue by ghost** [operator-framework/operator-sdk#521]
When the operator starts watching for a particular resource it starts creating deployments, routes, services, etc. However, for some deployments I need one time operations, i.e. I do not need the operator to try it again after sync timeout.

For example, deploy postgres and provision user and db there or deploy Red Hat SSO and provision realm only once. Also, such operations require credentials, that can be changed over time (otherwise I'd just check if a db or realm exists and skip execution of code) so the only time I can be sure they are valid is the initial start of an operator

As an example, what would be recommendations for a hello-world operator that deploys busybox pod and immediately runs exec into it. And I need that exec to be run once.

**Comment by xiang90** [comment]
We originally have the idea of filter chain, where you can implement an "exact once" filter for certain objects.

**Comment by eivantsov** [comment]
@xiang90 thanks for your reply - good to know it's not smth that is jus tin my cvrazy mind :)

For now, I just create pods with restart policy never, so they do their jobs and just sit there. However, once deleted, the operator will recreate them, and they will fail since things to be created already exist. This does not break anything of course, but it'd be great not to watch those at all and let them fail if they fail.

**Comment by estroz** [comment]
@eivantsov you might be able to get the functionality you want by using watch predicates to filter events. Check out our [event filtering guide](https://github.com/estroz/operator-sdk/blob/master/doc/user/event-filtering.md) to get a sense of how to filter events for resource types by object metadata.

**Comment by camilamacedo86** [comment]
Hi @eivantsov,

We are doing exactly in this way for all resources that are created/managed by the operator in the Mobile Security Service Operator [project](: https://github.com/aerogear/mobile-security-service-operator). I hope that it can be helpful to you. Note that it shows that approach suggested by the Getting Started example as well. 

### Approach example/description:

Specifying one Watch for each resource kind and kind owner. 

```go
	err := c.Watch(&source.Kind{Type: &corev1.ConfigMap{}}, &handler.EnqueueRequestForOwner{
		IsController: true, 
		OwnerType:    &mobilesecurityservicev1alpha1.MobileSecurityServiceApp{},
	})
```
In the reconcile fetch/check the resource as the following example. 

```go
	configMap := &corev1.ConfigMap{}
	err := r.client.Get(context.TODO(), types.NamespacedName{Name: getSDKConfigMapName(instance), Namespace: instance.Namespace}, configMap)
```

Then, note that you will find in the reconcile controller of this project the following code which is doing it and just creating the resource/object if it not exist. Following an example. 

```go
	//Check if Deployment for the app exist, if not create one
	deployment, err := r.fetchDeployment(reqLogger, instance)
	if err != nil {
		return r.create(instance, reqLogger, DEPLOYMENT, err)
	}
```
**NOTE** This project is trying to faithfully follow the same approach present in the operator-framework documentation. See [here](https://github.com/operator-framework/getting-started)

I hope that it is what you are looking for.

**Comment by camilamacedo86** [comment]
Hi @ghost,

I hope that the information provides above attended your expectations. Please, could you let us know if you concern raised here is solved or if has anything else about this subject that still missing address in this issue?

**Comment by camilamacedo86** [comment]
Hi @ghost, 

I am closing this one since shows that your questions were already answered here. Please, feel free to re-open if it is required.
