### ISSUE TITLE
Order of generated webhooks still not stable after v1.12

### ISSUE THREAD

**Issue by amisevsk** [operator-framework/operator-sdk#5215]
## Bug Report
Follow-up to https://github.com/operator-framework/operator-sdk/issues/5022, which I cannot reopen.

#### What did you do?
After updating to `v1.12`, `operator-sdk generate bundle` still does not write CSV webhookDefinitions in a stable order. From looking at https://github.com/operator-framework/operator-sdk/pull/5177, webhookDefinitions are sorted based on type, but within types the order can still vary. In our project, we have two conversion webhooks (one for each of two CR kinds), and so cannot use `operator-sdk generate bundle` in PR checks, etc. without additional workarounds -- currently, we use
```bash
yq -iY '.spec.webhookdefinitions |= sort' deploy/bundle/manifests/devworkspace-operator.clusterserviceversion.yaml
```

#### What did you expect to see?

Webhook definitions are always in same order

#### What did you see instead? Under which circumstances?

Running `operator-sdk generate bundle` multiple times will make unnecessary changes to files.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

OpenShift

`$ operator-sdk version`

```
operator-sdk version: "v1.12.0", commit: "d3b2761afdb78f629a7eaf4461b0fb8ae3b02860", kubernetes version: "1.21", go version: "go1.16.7", GOOS: "linux", GOARCH: "amd64"

```

`$ go version` (if language is Go)

```
go version go1.16.6 linux/amd64
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

#### Possible Solution
More fields for sorting seem to be needed, at least for conversion webhooks.

#### Additional context

To reproduce, clone https://github.com/amisevsk/devworkspace-operator/tree/update-operator-sdk-v1.12 and run `make generate_olm_bundle_yaml` a few times:
```bash
while [ -z "$(git status -s)" ]; do make generate_olm_bundle_yaml; done
```

cc: @jmrodri

**Comment by varshaprasad96** [comment]
This does seem to be a bug. We would have to sort each webhook type.
/kind bug
