### ISSUE TITLE
3rd Party Resources notifications into Operator -- Incompatible Languages

### ISSUE THREAD

**Issue by pplavetzki** [operator-framework/operator-sdk#5217]
## Type of question

How to implement a specific feature

## Question

I'm having difficulty trying to use the operator-sdk to add 3rd party resources into my operator.   Can you get notified of state change on a 3rd Party Resource, where you do not have access to the source code, cannot import it due to this closed api and the 3rd party api code is written in a different language than my `golang` operator?

#### What did you do?

 I've reviewed the other issues here #1578, #477, etc..., plus the blogs here: [Discovery Content](https://developers.redhat.com/blog/2020/01/22/why-not-couple-an-operators-logic-to-a-specific-kubernetes-platform#how_to_get_the_cluster_version_information), [3rd Party Resources](https://developers.redhat.com/blog/2020/02/04/how-to-use-third-party-apis-in-operator-sdk-projects#step_4__use_the_api_in_the_controllers).

I don't have access to the source code to import the module and it's written in `C#`.  Which I see done here:

```
import (
	...
	routev1 "github.com/openshift/api/route/v1"
	...
)

        route := &routev1.Route{}
        err = r.client.Get(context.TODO(), types.NamespacedName{Name: memcached.Name, Namespace: memcached.Namespace}, route)
```

#### What did you expect to see?

I expect to be notified of custom resources deployed into the api server, regardless if I have access to import the modules into my operator.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

Azure Kubernetes Service

`$ operator-sdk version`

operator-sdk version: "v1.11.0", commit: "28dcd12a776d8a8ff597e1d8527b08792e7312fd", kubernetes version: "1.20.2", go version: "go1.16.7", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.16.4 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by varshaprasad96** [comment]
@pplavetzki Thanks for raising the issue. It seems a bit unclear on what you are expecting. Are you trying to use a third party library written in a different language inside the operator code. Or would you like to use a crd generated externally in the operator? We would highly encourage you to bring this up in the [operator-sdk-dev](https://kubernetes.slack.com/archives/C017UU45SHL) channel of the Kubernetes slack group. Also, please feel free to join the [community](https://sdk.operatorframework.io/docs/contribution-guidelines/issue-lifecycle/#triage) meetings tp raise this issue.
