### ISSUE TITLE
Debug scorecard tests using a debugger

### ISSUE THREAD

**Issue by jmrodri** [operator-framework/operator-sdk#5218]
#### Describe the problem you need a feature to resolve.

A user requested the ability to debug scorecard test.  

> i'd like to use vscode to debug a scorecard test... can anyone share how this is done? is operator-sdk calling another executable for
> scorecard that i need to run in debugger instead of operator-sdk itself?
> with some hacking i got scorecard-test/main.go to run

#### Describe the solution you'd like.

* Document how to debug scorecard tests
* If needed, change scorecard to make it easier to debug

/language go
/language ansible
/language helm

**Comment by varshaprasad96** [comment]
@thomasmckay could you please mention more about the workaround you did to get the debugging on scorecard pods?
