### ISSUE TITLE
Where exactly in the operator-sdk code is the command under artifacts formed?

### ISSUE THREAD

**Issue by zohiba** [operator-framework/operator-sdk#5221]
#### What did you do?

I want to find out where exactly in the operator-sdk code is the extravars linked to the ansible-playbook command? 
#### What did you expect to see?

I want want to know where exactly in the operator-sdk code is the extravars linked to the ansible-playbook command? How is the -e flag passed in?

#### What did you see instead? Under which circumstances?

I have seen extravars file being created under env but I don't see how that file is psased in with -e flag
#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by zohiba** [comment]
Runner Input Directory Hierarchy (https://ansible-runner.readthedocs.io/en/stable/intro.html)
This directory contains all necessary inputs. Here’s a view of the demo directory showing an active configuration.

Note that not everything is required. Defaults will be used or values will be omitted if they are not provided.

.
├── env
│   ├── envvars
│   ├── extravars
│   ├── passwords
│   ├── cmdline
│   ├── settings
│   └── ssh_key

Another question is, can we somehow add multiple files for extravars?

**Comment by asmacdo** [comment]
This might also be helpful to you https://github.com/operator-framework/operator-sdk/blob/19750cdf19969e9de51a6089bca8852d400c3cbd/internal/ansible/runner/runner.go#L336

Could you elaborate on what you are trying to do? If a discussion would be easier, feell free to ask in the Kubernetes slack #kubernetes-operators or #operator-sdk-dev

**Comment by zohiba** [comment]
I was basically, trying to add some variables as extravars and I think if I add it to makeParameters function it will be written to extravars file, so that works, exactly what you pointed out!
