### ISSUE TITLE
How to uninstall operator-sdk if installed via Makefile?

### ISSUE THREAD

**Issue by ZarifS** [operator-framework/operator-sdk#5222]
## Type of question
Support Question

## Question
How do I uninstall the operator-sdk binary if I installed via the makefile as mentioned here: https://sdk.operatorframework.io/docs/installation/#compile-and-install-from-master

I see a makefile but no uninstall file. Not sure how this should be uninstalled properly on my system as I need a different version.
#### What did you do?
Looked at docs, tried running make uninstall.

#### What did you expect to see?
Files to be uninstalled and operator-sdk no longer in my system.

#### Environment
MacOS Big Sur

**Kubernetes cluster type:**

`$ operator-sdk version`

operator-sdk version: "v1.6.2", commit: "b131ca8ec77c96b9898470eba9560c30af0f23f3", kubernetes version: "v1.19.4", go version: "go1.17", GOOS: "darwin", GOARCH: "amd64"
**Operator type:**

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by varshaprasad96** [comment]
@ZarifS If you are using `make install` the binary would be present in the [go install directory](https://golang.org/doc/tutorial/compile-install) in your system. You can delete the binary from that location.
