### ISSUE TITLE
Document ansible "turbo mode" environment variable 

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#5223]

**Comment by asmacdo** [comment]
https://github.com/ansible-collections/kubernetes.core#ansible-turbo-mode-tech-preview

**Comment by asmacdo** [comment]
blocked by https://github.com/operator-framework/operator-sdk/issues/5227

**Comment by jobcespedes** [comment]
May I suggest including changes for `operator_sdk.util` to be ready for turbo mode, too? I opened [an issue for it](https://github.com/operator-framework/operator-sdk-ansible-util/issues/24).
