### ISSUE TITLE
Ansible: Unable to load the manager config file","error":"scheme not supplied to controller configuration loader

### ISSUE THREAD

**Issue by cdjohnson** [operator-framework/operator-sdk#5224]
#### What did you do?
1. Download and install `operator-sdk` version `1.12.0` on ubuntu 
2. `mkdir test`
3. `cd test`
4. `operator-sdk init --plugins=ansible --domain tt.example.com`
5. `operator-sdk create api --group test --version v1alpha1 --kind TTTest --generate-role`
6. `export IMAGE_TAG_BASE=docker.io/cdjohnson/test`
7. edit  `test/config/default/kustomization.yaml`
    Comment-out `-manager_auth_proxy_patch.yaml`
    Uncomment-out `- manager_config_patch.yaml`
8. `export IMG="docker.io/cdjohnson/test-operator:v0.0.1"`
9. `make docker-build docker-push`
10. `export VERSION=0.0.1`
11. `make bundle bundle-build bundle-push`
12. `operator-sdk run bundle docker.io/cdjohnson/test-bundle:v$VERSION  `

#### What did you expect to see?
I expected the Manager pod to start.

#### What did you see instead? Under which circumstances?
CrashLoopBackOff with the following error:
```json
{"level":"error","ts":1632160303.1950827,"logger":"cmd",
"msg":"Unable to load the manager config file",
"error":"scheme not supplied to controller configuration loader",
"stacktrace":"github.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.run\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:101\ngithub.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.NewCmd.func1\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:79\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897\nmain.main\n\t/workspace/cmd/ansible-operator/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
```
#### Environment

**Operator type:**

 /language ansible

**Kubernetes cluster type:**

OpenShift 4.8.2

`$ operator-sdk version`

`operator-sdk version: "v1.12.0", commit: "d3b2761afdb78f629a7eaf4461b0fb8ae3b02860", kubernetes version: "1.21", go version: "go1.16.7", GOOS: "linux", GOARCH: "amd64"`

`$ go version` (if language is Go)

`$ kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v0.21.0-beta.1", GitCommit:"1077b0516d5baf6f2717e4cb34f58236c0fb7a8c", GitTreeState:"clean", BuildDate:"2021-06-29T17:57:28Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+38b3ecc", GitCommit:"38b3eccb7e23fd950b6c7b5ec1cc3075b630aac3", GitTreeState:"clean", BuildDate:"2021-07-29T23:59:54Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

#### Possible Solution

I noticed that there is a discrepancy between the generated code and the public doc, so I renamed the object in the configmap from `ControllerManagerConfig` to `ControllerManagerConfiguration` and deleted the pod, but the error still happened.

It seems like there is something wrong in the Ansible runtime that's not setting the Schema object in the struct prior to using it.

**Comment by perdasilva** [comment]
I've managed to reproduce this on `kind`. Thanks for the great instructions. I'll see if I can figure out the issue.

**Comment by perdasilva** [comment]
So, the above PR fixes part of the issue. The other part is getting the `--config` argument to point to a valid location. The way it is currently specified, it expects the file to be in the current directory. However, the ansible-operator image sets the workdir to the home directory, which results in a file not found. I need a more experienced person to help guide me with the fix for this. Whether it ought to be here or upstream in the kubebuilder project.
