### ISSUE TITLE
bad bundle image env var in Quickstart for Go-based Operators

### ISSUE THREAD

**Issue by thoraxe** [operator-framework/operator-sdk#5237]
```
make bundle IMG="example.com/memcached-operator:v0.0.1"
make bundle-build bundle-push
```

This should be `BUNDLE_IMG`

**Comment by varshaprasad96** [comment]
@thoraxe Thanks for bringing up this issue. Would you like to submit a PR? The commit you have mentioned would be helpful and can fix the issue.

**Comment by rashmigottipati** [comment]
@thoraxe created a [PR](https://github.com/operator-framework/operator-sdk/pull/5238) for it last week.
It looks good, it's just missing commit sign-off before it can be merged.
