### ISSUE TITLE
Move rerun actions repo into OF org

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#5239]
CI uses Eric's action to give contributors the ability to rerun their actions. Since its part of CI, we should move it into the org.

https://github.com/estroz/rerun-actions

**Comment by jberkhahn** [comment]
todo:
-fork repo
-find out which repos need to be changed over to point at the new repo

**Comment by jmrodri** [comment]
This issue is NOT a release blocker since it is simply moving a repo over to the framework.

**Comment by jmrodri** [comment]
What's left is to find out which repos need to be changed over to point at the new repo
