### ISSUE TITLE
OLM Integration Bundle Tutorial

### ISSUE THREAD

**Issue by thoraxe** [operator-framework/operator-sdk#5280]
There's no mention of `OperatorGroup`. When (mostly) following the tutorial and then trying to install the created operator bundle with OLM, you need a `CatalogSource`, a `Subscription`, and an `OperatorGroup`:

Additionally, the instructions only refer to _upgrading_ an operator. They don't provide an example of installation without `run bundle`. As the [testing bundles](https://sdk.operatorframework.io/docs/olm-integration/tutorial-bundle/#testing-bundles) section output indicates an `OperatorGroup` is created when using `run bundle`, it would also be nice if there was a way for the SDK to generate the subscription, catalog source, and operator group manifests directly to disk.

**Comment by jmrodri** [comment]
> If I remember correctly, I was trying to install the operator manually (via the `kubectl/oc` CLI) to validate it, and not install it using the UI.
> 
> When installing an operator via the CLI, you need a `CatalogSource`, a `Subscription` and an `OperatorGroup`. Unfortunately, none of the provided commands seem to generate those manifests/artifacts.
> 
> Not everyone who uses Kubernetes/OLM/OpenShift is going to use a web console, and, additionally, GitOps approaches do not use web consoles. Having the SDK generate the manifests would allow someone to easily validate / automatically test that a non-UI approach works.

@thoraxe I completely agree they won't use a web console. That's why we created `run bundle` to make it easier to test out your operator bundles. Using `operator-sdk run bundle` will take your bundle and create the relevant bits that need to be there like the `CatalogSource` etc. https://sdk.operatorframework.io/docs/olm-integration/tutorial-bundle/#deploying-an-operator-with-olm

**Comment by camilamacedo86** [comment]
/lifecycle frozen

c/c @asmacdo @jmrodri

**Comment by jmrodri** [comment]
Closing as there are no plans to do this.
