### ISSUE TITLE
How to remove catalog source

### ISSUE THREAD

**Issue by adhikarexuss** [operator-framework/operator-sdk#5299]
## Type of question
General operator-related help

#### What did you do?

I was following the installation guide for OCI Service Operator for Kubernetes (OSOK) from the following this link:
https://github.com/oracle/oci-service-operator/blob/main/docs/installation.md

I have successfully installed the operator-sdk and OLM.
However, when I wanted to deploy OSOK, I missed the step of pulling the docker image.
So, I straight away ran this command:
```operator-sdk run bundle iad.ocir.io/oracle/oci-service-operator-bundle:1.0.0```

according to the installation guide, I should've pull the docker image first
```$ docker pull iad.ocir.io/oracle/oci-service-operator-bundle:1.0.0```

so, it gave me an error like this:
```
INFO[0028] Successfully created registry pod: iad-ocir-io-oracle-oci-service-operator-bundle-1-0-0 
INFO[0028] Created CatalogSource: oci-service-operator-catalog 
INFO[0029] OperatorGroup "operator-sdk-og" created    
INFO[0029] Created Subscription: oci-service-operator-v1-0-0-sub 
FATA[0124] Failed to run bundle: install plan is not available for the subscription oci-service-operator-v1-0-0-sub: timed out waiting for the condition
```
I noticed that it created a pod called "iad-ocir-io-oracle-oci-service-operator-bundle-1-0-0" so I deleted the pod
```kubectl delete pod iad-ocir-io-oracle-oci-service-operator-bundle-1-0-0```

And it gave me this message
```pod "iad-ocir-io-oracle-oci-service-operator-bundle-1-0-0" deleted```

Then when I ran the command
```operator-sdk run bundle iad.ocir.io/oracle/oci-service-operator-bundle:1.0.0```

It returned with the following error message
FATA[0004] Failed to run bundle: create catalog: error creating catalog source: catalogsources.operators.coreos.com "oci-service-operator-catalog" already exists

How can I remove that catalog completely so I can execute the ```operator-sdk run bundle``` command again?

#### Environment

**Kubernetes cluster type:**

Kubernetes on Oracle Cloud Infrastructure

`$ operator-sdk version`

```operator-sdk version: "v1.13.0", commit: "6e84414b468029c5c3e07352cabe64cf3a682111", kubernetes version: "1.21", go version: "go1.16.8", GOOS: "linux", GOARCH: "amd64"```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"50317190d44dbdb51ae7ff430917b32ba96188b5", GitTreeState:"clean", BuildDate:"2021-06-30T14:20:31Z", GoVersion:"go1.15.13 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

**Comment by varshaprasad96** [comment]
We can use `operator-sdk cleanup` command ([ref](https://sdk.operatorframework.io/docs/cli/operator-sdk_cleanup/)) to delete all the resources created by run bundle so that it can run again.
