### ISSUE TITLE
Advanced Topics: Should there be an else condition in the finalizer example?

### ISSUE THREAD

**Issue by kgibm** [operator-framework/operator-sdk#5309]
On this page: https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#external-resources

The example ends with:

```
    // Add finalizer for this CR
    if !controllerutil.ContainsFinalizer(memcached, memcachedFinalizer) {
        controllerutil.AddFinalizer(memcached, memcachedFinalizer)
        err = r.Update(ctx, memcached)
        if err != nil {
            return ctrl.Result{}, err
        }
    }

    ...

    return ctrl.Result{}, nil
```

I put my normal reconciliation logic in place of "..." but intermittently hit:

```
2021-10-13T21:31:07.077Z	ERROR	[...] "error": "Operation cannot be fulfilled on [...]: the object has been modified; please apply your changes to the latest version and try again"}
```

This seems to be because the finalizer was added which drove `r.Update` but in the non-error case, it didn't return `ctrl.Result{}, nil`, so then it falls down to the normal reconciliation logic in "..." which then also did an update, and depending on timing, this could cause that update to conflict with the next reconciliation driven by the `r.Update` on the finalizer.

It seems to me that it should always return after successfully updating the finalizer as the `r.Update` will re-drive the reconciliation?

**Comment by asmacdo** [comment]
The triage group thanks you for filing the issue AND ap PR!!!!!!!! :)

**Comment by kgibm** [comment]
To add: I understand now that we can always `Get` before `Update` (although that wasn't clear to me before so this might be confusing to other beginners) and your following point is true:

> You are only stoping the reconcile and then when it is re-trigged again the error is not faced because you do not go inside in the !controllerutil.ContainsFinalizer(memcached, memcachedFinalizer) because the finalizer already exists

However, my point is: Why should the example drive the developer to add more complexity when we can simply `return ctrl.Result{}, nil` after successfully adding the finalizer and let the `Reconcile` come back in and skip the finalizer section. It avoids the potential of the `object has been modified` error and makes the logic much simpler. As far as I understand, the finalizer addition will always drive a subsequent `Reconcile` so either the developer has to deal with concurrency issues, or they can have cleaner logic.

**Comment by camilamacedo86** [comment]
Hi @kgibm, 

I am glad that I could help you out. Not sure if I understand your comment. Note that if you  `return ctrl.Result{}, nil after successfully adding the finalizer` then, the following operations in the sample will not be executed. This statement will **stop** the reconcile.

**Comment by kgibm** [comment]
@camilamacedo86 

> Note that if you `return ctrl.Result{}, nil` after successfully adding the finalizer then, the following operations in the sample will not be executed. This statement will stop the reconcile.

I have demonstrated with [the example](https://github.com/operator-framework/operator-sdk/issues/5309#issuecomment-946877041) that this is not true, but I think we have reached an impasse so I'm okay with closing this issue. Users will just learn how to handle this themselves.
