### ISSUE TITLE
Scorecard basic checks is not considering the scenarios where the CRD can be without spec

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#5313]
#### What did you do?

Check a project where I have the CRD only to share status across the components and without spec defined 

#### What did you expect to see?

Not fail because is missing spec
Not warning because is missing the examples for an API that does not have specs  

#### Possible Solution

The following suggestion should only appear only when a spec is provided

```
"suggestions": [
              "Warning: Value binding.operators.coreos.com/v1alpha1, Kind=BindableKinds: provided API should have an example annotation"
            ]
```

We ought to not raise the error: https://github.com/operator-framework/operator-sdk/blob/master/internal/scorecard/tests/basic.go#L49-L60

**Comment by asmacdo** [comment]
Lets make this Error into a Warning with a clear explanation (not mandatory but strongly suggested) so it can still pass since the spec is not strictly required but this test is an important part of the pipeline.

**Comment by laxmikantbpandhare** [comment]
I am taking look into it.
