### ISSUE TITLE
Only one [Validating|Mutating]Webhook per operator should be created

### ISSUE THREAD

**Issue by raffaelespazzoli** [operator-framework/operator-sdk#5318]
## Feature Request

Today when a csv is created by operator-sdk, the webhooks are split apart in several definition one webhook per CRD type.
If an operator defines several types each with both mutating and validating webhook, this results in a proliferation of object.
This could be avoided as the [Mutating|Validating]WebhookConfiguration CRDs support defining multiple endpoints within one configuration.

This refers to golang operator,  I have not tested this situation with the other types of operators.

**Comment by raffaelespazzoli** [comment]
`It would be very difficult to change the API now that it has been out for a few releases` I don't really like this answer, this is like saying: fixing the api design issue is hard, therefore we won't do it.
Anyway, how do you suggest to fix this issue? Where would you open the issue, considering that the objective is to have one webhook defined not many at the actual deployment time.

**Comment by awgreene** [comment]
> I don't really like this answer, this is like saying: fixing the api design issue is hard, therefore we won't do it.

@raffaelespazzoli This is a fairpoint and probably stems from the lack of background I omitted from my response.

Changing a CRD's API can introduce a number of breaking changes if not done in a backwards compatible way. There are a number of operators that have been packaged using the existing API and are running on clusters. Simply changing the API to allow multiple webhooks per configuration will invalidate the existing ecosystem and attempts to update existing CSV CRs that do not adhere to the new API will fail. We cannot support a non-backwards compatible change.

If we were to introduce a backwards compatible change, we would need to:
- Introducing the new version of the API you proposed, bumping the APIs version, and setting it as the stored version
- Introduce a conversion webhook that allows OLM to convert from the old and new versions.

While the above is possible, it represents a non-negligible amount of development work. I suspect that this work would not be prioritized over the existing efforts to introduce a new set of APIs for managing operators, which is where I believe that this work should be done.

**Comment by awgreene** [comment]
>Anyway, how do you suggest to fix this issue? Where would you open the issue, considering that the objective is to have one webhook defined not many at the actual deployment time.

Someone would need to write a proposal, but there are two possibles paths that I see:
1. Provide users a way to specify that these webhookDescriptions should exist within a single webhookConfigration. Shortcomings to this approach include expanding the existing api and introducing a manual process.
2. Have OLM resolve when to include two or more webhookDescriptions in a single webhookConfiguration. Shortcomings to this approach include a change to existing behavior and possible unexpected merging of webhooksDescriptions by OLM.
