### ISSUE TITLE
Ansible operator takes a long time to reconcilie on KinD clusters

### ISSUE THREAD

**Issue by israel-hdez** [operator-framework/operator-sdk#5319]
#### What did you do?

I'm seeing this issue with the [Kiali Operator](https://github.com/kiali/kiali-operator).

```
kind create cluster --name test
helm repo add kiali https://kiali.org/helm-charts
helm install --namespace kiali-operator --create-namespace kiali-operator kiali/kiali-operator
cat <<EOF | kubectl apply -f - -n kiali-operator
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec: {}
EOF
```

#### What did you expect to see?

Reconciliation should start quickly.

#### What did you see instead? Under which circumstances?

Apparently, reconciliation is being triggered. However, operator playbooks are taking about 10 minutes to start running. After that 10 minutes delay, I start seeing the logs of the operator playbooks.

Once playbooks start running, reconciliation finish quite quickly. It's that 10 minute delay that is providing a bad experience. Reconciliation does not seem to fail. It's simply being delayed.

This happens consistently when creating, updating and deleting a CR. I've seen this issue only in [KinD](https://kind.sigs.k8s.io/) clusters.

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

[KinD](https://kind.sigs.k8s.io/)

`$ operator-sdk version`

I'm not using `operator-sdk` to build the docker image.

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

#### Additional context

* It is uncertain if there is some issue with KinD or with the operator framework. I'm seeing this issue only in KinD. Minikube seems to be working properly.
* Currently, I'm seeing this issue when using the `quay.io/openshift/origin-ansible-operator:4.7.0` base image. (Very) o
lder base images of the ansible operator works OK. For example, using `quay.io/operator-framework/ansible-operator:v1.3.0` works OK in KinD.
* I'm attaching a package of the `/tmp/ansible-operator/runner/kiali.io/v1alpha1/Kiali/kiali-operator/kiali` that is inside the operator container, which hopefully has some logs that may give some insight:
  * [kiali-operator-artifacts.tar.gz](https://github.com/operator-framework/operator-sdk/files/7393086/kiali-operator-artifacts.tar.gz)
* A side effect that I'm seeing is that on that 10 minute delay, there is an `/usr/libexec/platform-python /usr/bin/ansible-runner` process that is consuming a lot of CPU. Once reconciliation finishes, the high CPU usage ceases.

**Comment by fabianvf** [comment]
Are you still seeing this? I've been unable to reproduce it using the instructions provided with the `quay.io/kiali/kiali-operator:v1.44.0` image. I was using a vagrant environment to try to reproduce it, here is my Vagrantfile in case that's useful:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.configure(2) do |config|
  config.vm.box = "generic/ubuntu1804"
  
  config.vm.provision :shell, :inline => <<-EOF
    set -x

    # install docker
    curl -sSL https://get.docker.com/ | sh
    usermod -a -G docker vagrant

    # install kubectl
    curl -Lo ./kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install ./kubectl /usr/local/bin/kubectl

    # Install kind
    curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
    install ./kind /usr/local/bin/kind

    # Install helm
    curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  EOF

  config.vm.provision :shell, :inline => <<-EOF
    set -x

    kind create cluster --name test

    helm repo add kiali https://kiali.org/helm-charts
    helm install --namespace kiali-operator --create-namespace kiali-operator kiali/kiali-operator

    cat <<- CR | kubectl apply -f - -n kiali-operator
    apiVersion: kiali.io/v1alpha1
    kind: Kiali
    metadata:
      name: kiali
    spec: {}
CR
  EOF
end
```

**Comment by jmazzitelli** [comment]
@israel-hdez @jshaughn see above ^^^

**Comment by jmazzitelli** [comment]
@fabianvf try it with Kiali v1.43 and see what happens. You can see [here](https://github.com/kiali/kiali-operator/commit/07371b09052acd0b5a72e6e8b7a1b6a6294cae97) v1.44 switched to using the upstream base image, and as mentioned in this issue's description, the problem doesn't happen when using that upstream base image.

**Comment by fabianvf** [comment]
@jmazzitelli I added `--set image.tag=v1.43.0` to the helm install command, but still saw instant reconciliation

**Comment by asmacdo** [comment]
Lets close for now, this is a weird one that is not reproducing on command. If anyone sees this please reopen.
