### ISSUE TITLE
Install from the source ask for KB binaries

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#5325]
## Bug Report

Install from the source is asking for KB binaries: 

```
$ make install
go install -gcflags "all=-trimpath=/Users/camilamacedo86/go/src/github.com/operator-framework" -asmflags "all=-trimpath=/Users/camilamacedo86/go/src/github.com/operator-framework" -ldflags " -X 'github.com/operator-framework/operator-sdk/internal/version.Version=v0.7.0+git' -X 'github.com/operator-framework/operator-sdk/internal/version.GitVersion=v0.7.0-1686-ge3005bfa-dirty' -X 'github.com/operator-framework/operator-sdk/internal/version.GitCommit=e3005bfa8677eadf5b3f34fd14275f8414c80fc8' -X 'github.com/operator-framework/operator-sdk/internal/version.KubernetesVersion=v1.21' -X 'github.com/operator-framework/operator-sdk/internal/version.ImageVersion=v1.13.0' "  ./cmd/{operator-sdk,ansible-operator,helm-operator}
unable to fetch checksum for requested version: unable fetch metadata for kubebuilder-tools-1.21.1-darwin-amd64.tar.gz -- got status "404 Not Found" from GCS

```

#### What did you do?

From a new/fresh local env:
- Clone the SDK project
- Run make install

#### What did you expect to see?

Build and install the Operator SDK from the source

#### What did you see instead? Under which circumstances?

It is asking for Kubebuilder binaries when seems that should not.

**Comment by varshaprasad96** [comment]
Ah yeah, this needs a small fix in Makefile. We were [exporting](https://github.com/operator-framework/operator-sdk/blob/15d7d7f8c362d6a2924c4f32af728e8353fe9519/Makefile#L150) KB assets for envtest setup since its no longer downloaded at the default location. This was causing KB assets to be downloaded even while building binaries.
#5336 closes this
