### ISSUE TITLE
Helm operator https://quay.io/repository/operator-framework/helm-operator have a lot of vulnerabilities

### ISSUE THREAD

**Issue by ccgagnon** [operator-framework/operator-sdk#5328]
## Bug Report

Recent image of helm operator have 100+ vulnerabilities. 

#### What did you do?

`docker scan quay.io/operator-framework/helm-operator:v1.13.1 `

#### What did you expect to see?

At least only low vulnerabilities compared to what is reported on quay.io.

#### What did you see instead? Under which circumstances?

I saw **around 50** reported **medium severity** vulnerabilities

quay.io reports no vulnerabilities
https://quay.io/repository/operator-framework/helm-operator/manifest/sha256:c28823eb93569e93ac31984ec7a54f37951509b403d287e5cc7d505de1cb4f97?tab=vulnerabilities

#### Environment

**Operator type:**

/language helm

Thanks

**Comment by jmrodri** [comment]
@ccgagnon quay is what we use to determine the images vulnerabilities. It shows it's clean and built 5 days ago: 
![image](https://user-images.githubusercontent.com/17137/141040126-da1e62a3-82ae-4a4d-8de2-3f616e44b2ff.png)

I'm not able to run `docker scan`, do you have a report that it generated?

**Comment by jmrodri** [comment]
Moving this to Backlog for now. It is not a v1.15.0 blocker.

**Comment by jmrodri** [comment]
I was able to get someone to run a `docker scan`. There were a few medium and low severity items. After analyzing the mediums, many of them were fixed recently in the latest UBI update. I will update the base to use UBI 8.5.

**Comment by jmrodri** [comment]
Moving this BACK to v1.15.0 as a blocker.

**Comment by jmrodri** [comment]
Fixed by PR #5358
