### ISSUE TITLE
operator-sdk kustomize destroys markdown formatting

### ISSUE THREAD

**Issue by thomasmckay** [operator-framework/operator-sdk#5338]
#### What did you do?

Running `operator-sdk generate kustomize manifests -q` changes this...
```
description: >
  line one


  line two
  * bullet one
  * bullet two
```
to
```
description: |
  line one

  line two * bullet one * bullet two
```

#### What did you expect to see?

Expect to format of this section to remain functionally correct. It could, for example, combine markdown paragraph lines into a prettier format but the end result should be displayed equivalently.

#### What did you see instead? Under which circumstances?

See above

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

`$ operator-sdk version`

operator-sdk version: "v1.13.1", commit: "1659ab58a073999463e6dcdf18bdc359a315e091", kubernetes version: "1.21", go version: "go1.16.8", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.16.9 linux/amd64

`$ kustomize version`

{Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T20:53:03Z GoOs:linux GoArch:amd64}

#### Additional context

This is happening when editing the `description` here https://github.com/gatekeeper/gatekeeper-operator/blob/master/config/manifests/bases/gatekeeper-operator.clusterserviceversion.yaml#L15 and then running `make bundle`

**Comment by asmacdo** [comment]
Reopening this as a docs issue. It would be nice to have a resources page for Ansible operators which could include https://yaml-multiline.info/

**Comment by joelanford** [comment]
@asmacdo This is a general concern of any YAML multi-line string field, right? In this case the CSV description is almost always multi-line and applies to all OLM operators.

**Comment by jchunkins** [comment]
Note that in order for the formatting to survive you need to use the `\` syntax and not the `>` syntax. The docs should probably indicate this in some fashion to make this clear.
