### ISSUE TITLE
[community] combine monthly Operator SDK meetings with triage

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#5340]
We've canceled our monthly meeting about half the time due to a lack of agenda topics, and our issue triage meetings have been moving quickly and ending early. 

I propose that we cancel all future Operator SDK monthly meetings, and start working out of a meeting doc for triage similar to what the java community uses: https://docs.google.com/document/d/1d_x7JHnjhKh8DgUO9F83kZ43Y3Ladl6sHWzst2ugV84/edit#heading=h.r7rcdcldar2r (Note: You should gain access to this document by subscribing to the Operator Framework google group.

**Comment by jberkhahn** [comment]
TODO: 
1. insert link to OLD community meeting agenda to the triage meeting section in community repo
2. change format of agenda to include triage meeting stuff
