### ISSUE TITLE
RFE: configurable backoff

### ISSUE THREAD

**Issue by jsafrane** [operator-framework/operator-sdk#535]
Current SDK gives up requeueing  an object if `Handler` fails for 15 times. This should be configurable, with possibility to retry forever with very long frequency (once in an hour or so).

**Comment by joelanford** [comment]
@jsafrane Operator SDK has transitioned to the `controller-runtime`. By default the controller uses client-go's [`NamedRateLimitingQueue`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controller.go#L87), which works like you describe. Operator developers are also able to choose a different implementation if they'd like.

If you experience similar issues with operator-sdk projects that use controller-runtime, feel free to re-open this issue.
