### ISSUE TITLE
RFE: interfaces for unit testing

### ISSUE THREAD

**Issue by jsafrane** [operator-framework/operator-sdk#536]
I probably miss something obvious, but I haven't found any interface to abstract the Kubernetes client providied by the SDK. I want to create an unit test that runs `Handle` with an event and checks that it calls `sdk.Create` (and other functions) to create the expected objects.

But `sdk.Create` is just a function, not an interface. That adds unnecessary complexity in writing a custom framework to abstract these calls and either provide fake objects or inject errors to check for error cases.

It would be great to have a test framework so an unit could do simple steps:

- Fill some fake client with instances to make sure `Get()`/`Modify()`/`Delete()` works as the test needs.
- Run `Handler()`.
  - All calls to client could be intercepted by the unit test to inject errors.
  - By default, the test framework would track objects created / modified / deleted by `Handler`.
- When `Handler` finishes, the test can list created/modified/deleted by `Handler` to check that the changes were correct.

**Comment by estroz** [comment]
@jsafrane check out our [unit testing doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/unit-testing.md) which covers using controller-runtime's fake client to mock API calls in a reconcile loop. Feel free to close this issue if the doc answers your questions. Thanks!

**Comment by jsafrane** [comment]
Indeed, controller runtime handles clients better, at least the client is an interface and not functions. (Their fake client is unusable, see https://github.com/kubernetes-sigs/controller-runtime/issues/168, but that's another story).

/close

**Comment by hasbro17** [comment]
@jsafrane I think that particular bug has been fixed with the fake client. Unless you're seeing other problems with the fake client in which case we can follow it up upstream.
