### ISSUE TITLE
operator-sdk scorecard does not work when run inside a container

### ISSUE THREAD

**Issue by mcurran-us** [operator-framework/operator-sdk#5370]
#### What did you do?

Inside of a container, I ran the  operator-sdk scorecard command specifying the serviceaccount and namespace options.
operator-sdk scorecard ... --namespace=mynamespace --service-account=my-sa ...
#### What did you expect to see?
I expected to see the scorecard tests running using the serviceaccount that I specified.

#### What did you see instead? Under which circumstances?
I saw the following error after issuing the operator-sdk command:  
 Error: error running tests error creating ConfigMap configmaps is forbidden: User "system:serviceaccount:pw-xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx:default" cannot create resource "configmaps"
 
The serviceaccount specified is not correct and does not exist.
#### Environment

**Operator type:**

/language go 

**Kubernetes cluster type:**

OpenShift 4.7

`$ operator-sdk version`

operator-sdk version: "v1.6.4", commit: "3cd22bdcce2ebe150f69afca75c1320799e476cf", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

"go1.15.5", GOOS: "linux", GOARCH: "amd64"

`$ kubectl version`

**Comment by jmccormick2001** [comment]
scorecard does create a ConfigMap when it runs, it stores the bundle contents in that ConfigMap essentially, as part of scorecard's cleanup it removes the ConfigMap as well.  As scorecard runs tests (as Pods), it will mount that ConfigMap into each test pod so that each test can have access to the bundle contents.

So, whatever context that scorecard runs in, it needs to run using a ServiceAccount that allows for creating ConfigMaps.  You might verify that your ServiceAccount that you are using to execute scorecard within has those rbac privs.

**Comment by mcurran-us** [comment]
The service account that I specified on the command does have the necessary rbac privileges.  The problem is that it is not using that serviceaccount when it tries to create the ConfigMap as shown in the error:  User "system:serviceaccount:pw-xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx:default" cannot create resource "configmaps"  
That is not the serviceaccount that was specified on the command. 
In addition, this works fine if I do not run the operator-sdk command from within a container.  Is running the operator-sdk scorecard command supported inside of a container.

**Comment by jmccormick2001** [comment]
the test Pods that get created will specify the ServiceAccount you are passing on the command line, not the actual operator-sdk container that you are running.  So, the Pod that you are running the operator-sdk command from, does that specify a ServiceAccount that has the ConfigMap create priv?

**Comment by mcurran-us** [comment]
No, the pod that is running the operator-sdk command does not specify a ServiceAccount that has ConfigMap create priv.

**Comment by jmccormick2001** [comment]
ok, that would be the issue, you would need to provide that priv to the pod since operator-sdk scorecard requires that priv to work.

**Comment by asmacdo** [comment]
Looks like this was addressed, closing for now. Please feel free to reopen if you aren't all set.
