### ISSUE TITLE
Allow make run for webhooks

### ISSUE THREAD

**Issue by pavolloffay** [operator-framework/operator-sdk#5372]
#### Describe the problem you need a feature to resolve.

I would like to run `make run` to run the operator that uses webhooks (e.g. defaulting, validating etc.). At the moment this is not supported if the operator uses webhooks.

#### Describe the solution you'd like.

`make run` that runs operator on my host and the webhooks are functional. 

In my other project I have created a webhook and I was able to run it from my host. It requires managing certificates for the webhook which is not super intuitive, but it can be done.

Related links:
* https://github.com/open-telemetry/opentelemetry-operator/issues/461
* https://github.com/open-telemetry/opentelemetry-operator/blob/main/CONTRIBUTING.md#deployment-with-webhooks

**Comment by camilamacedo86** [comment]
PS.: Rose Crisp also is another user that got stuck because was unable to know it. So, if we are unable to make the webhooks work with `make run` I would suggest we raise a WARN at least.

**Comment by rocrisp** [comment]
Be great to get a recipe for make run with webhooks for development testing.
So far, I haven't been able to make it work. I used Ngrok, with proxy and that just didn't work for me.
Please let me know if you decide to do this.

**Comment by varshaprasad96** [comment]
Operator with webhooks can be run locally, but it will require us to generate and set up certificates at the right location. Here is the reference: https://book.kubebuilder.io/cronjob-tutorial/running.html#running-webhooks-locally

**Comment by asmacdo** [comment]
Looks like you're all set, closing. Please feel free to reopen if its not covered.

**Comment by pavolloffay** [comment]
> Looks like you're all set, closing. Please feel free to reopen if its not covered.

As I mentioned in the first comment on this issue. I know it is possible to run the webhooks locally. 

This ticket was about making it easy and simple ;)

**Comment by rocrisp** [comment]
@pavolloffay Can you share how do you 
1. configure a proxy between the Kubernetes API server and your host, so that it can contact the webhook in your local machine

**Comment by varshaprasad96** [comment]
@rocrisp I don't think setting up a proxy server is needed to communicate between the K8s api server and the host. But ill reopen this issue so that its picked up in the next triage. looks like it needs more discussion.

**Comment by varshaprasad96** [comment]
@pavolloffay could you please explain the steps you had followed to set this up locally also the error that you had faced. It would be really nice to document this. We haven't tried this yet, hence if the effort is less it would be helpful to document this for other users. 

We need to investigate to check if `ENABLE WEBHOOKS` is set to true, the webhooks run successfully locally. If not, we need to log warning and mention the steps need to run webhooks.

**Comment by pavolloffay** [comment]
I haven't configured this locally with the operator-sdk. However, I did run vanilla webhook locally once with certs on macos and docker desktop, it was a long time ago and I don't have my notes anymore.

**Comment by camilamacedo86** [comment]
Hi @varshaprasad96, 

The ENABLE WEEBHOOKS is only useful for the tutorial. See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/main.go#L118-L124 

That is saying to run false since make run does not work without the local config.

**Comment by varshaprasad96** [comment]
For now, if the webhook is deployed locally (outside the cluster in which operator is deployed) then the API server has no way to identify it. We haven't tested this out using proxy. I'm closing this issue for now since this feature would turn out to be more complicated if we would like to implement it. Please feel free to reopen this issue, or a new issue to introduce supporting of webhooks running locally outside the cluster in which operator is deployed (since it needs more discussion).
