### ISSUE TITLE
Operator Bottleneck

### ISSUE THREAD

**Issue by ib-steffen** [operator-framework/operator-sdk#538]
I'm right now dealing with some very weird issue. Basically we have an operator which can, at some point, not keep up with the events anymore. First try was to increase the number of workers, but this did not help. Interestingly by increasing the number of workers from 1 to 5 the time for handling an event (basically I measured how long the Handle() function takes) went up by a factor of 5 (from 200ms to 1s). So it handles now 5 events in parallel but each takes 5x longer! I also checked the API Server logs and it looks like each request just takes a few ms. So it doesn't look like an issue in API Server side.

To reproduce the problem I did the following:
1. Clone the samples repo and modify the memcached operator
2. Change the rsync period to 2 seconds (just needed so we don't have to create many CRs later on)
3. Keep the number of workers as 1
4. Measure execution time of Handle()
5. Build the operator and deploy it
6. Create one CR

In my cluster it takes about 10ms with one CR. As soon as I create more than 5 CRs the execution time suddently increases to 400ms. Changing the number of workers to 5 leads to an execution time of 2 second.

Any idea on what could cause this behavior?

**Comment by estroz** [comment]
Can you link your modified memcached operator code?

**Comment by LiliC** [comment]
@ib-steffen I am closing this issue under the assumption you solved the problem. But please feel free to reopen! :)

**Comment by ib-steffen** [comment]
The issue is not solved. We are right now trying to workaround it, but it still exists and is causing problems.

**Comment by estroz** [comment]
@ib-steffen please include version information any sample code/log data you can. Thanks!
