### ISSUE TITLE
Ansible Operator Should use status writer 

### ISSUE THREAD

**Issue by shawn-hurley** [operator-framework/operator-sdk#540]
per @hasbro17 comment on PR #473 

> Don't need to change this now but it might be worth looking into the Status client to see if there's a benefit to using that if we're just updating the status:
kubernetes-sigs/controller-runtime:pkg/client/unstructured_client.go@master#L136-L151
The default manager client comes with a status writer:
kubernetes-sigs/controller-runtime:pkg/client/split.go@master#L32

**Comment by shawn-hurley** [comment]
Moving this to blocked. We want the ansible operator to support k8s 1.10 which means that the status subresource is not on by default.

**Comment by joelanford** [comment]
Closed by #787
