### ISSUE TITLE
Go Operator Tutorial

### ISSUE THREAD

**Issue by lhaendler** [operator-framework/operator-sdk#5409]
After replacing memcached_controller.go (step implement the controller) some dependencies are missing. It would be great if instructions on how to install them are added to the tutorial

**Comment by varshaprasad96** [comment]
@lhaendler Thanks for raising the issue. The tutorial directs users to use the memcached_controller as an example, and the imports are with respect to the sample testdata repository which we have [here](https://github.com/operator-framework/operator-sdk/tree/latest/testdata). Could you specify the specific errors with dependencies which you are facing?

**Comment by lhaendler** [comment]
After placing the example memcached_conroller.go into the project generated using the instructions of the tutorial when running `make manifests` the following error occurs:  
```
/memcached-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
Error: err: exit status 1: stderr: go: updates to go.mod needed; to update it:
	go mod tidy
```
While it is quite simple to fix by running the command provided in the error message, i think it would be better to add an instruction for the reader of the tutorial to do so without making them handle an error message

**Comment by varshaprasad96** [comment]
@lhaendler thanks for bringing this up. Would you like to contribute by adding this as a `NOTE` in the tutorial?

**Comment by aemperador** [comment]
I have submitted a PR to try to quickly add the NOTE specified above

**Comment by aemperador** [comment]
This can be closed. The PR was merged.
