### ISSUE TITLE
Move build.sh into the sdk binary

### ISSUE THREAD

**Issue by AlexNPavel** [operator-framework/operator-sdk#541]
The build.sh script is mostly unnecessary and does not provide any benefits over handing the building from the operator-sdk's binary. In addition, any updates that the sdk gets will not be reflected in existing project as `build.sh` is generated on `new`. Currently, this will cause issues for people created a project before the `--enable-tests` flag was added to the sdk and then try to use `--enable-tests`.

In addition, we should look into the way that dockerfiles are managed in cases like this. Currently, the above situation (trying to build an image with tests on a project that was generated before that was supported) will not work even with the build script merge because it will be missing the test-framework dockerfile. For now, we can just check if it exists and generate it if it doesn't, but in the long-term, we should find a better solution for managing these files.

**Comment by hasbro17** [comment]
Elaborating on the current issue. 
Before #469  `operator-sdk build` would run the build script `tmp/build/build.sh`
```sh
#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if ! which go > /dev/null; then
	echo "golang needs to be installed"
	exit 1
fi

BIN_DIR="$(pwd)/tmp/_output/bin"
mkdir -p ${BIN_DIR}
PROJECT_NAME="memcached-operator"
REPO_PATH="github.com/operator-framework/operator-sdk-samples/memcached-operator"
BUILD_PATH="${REPO_PATH}/cmd/${PROJECT_NAME}"
echo "building "${PROJECT_NAME}"..."
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ${BIN_DIR}/${PROJECT_NAME} $BUILD_PATH
```

But now with `operator-sdk build --enable-tests` it expects the script to build the test binary as well:
```sh
#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if ! which go > /dev/null; then
	echo "golang needs to be installed"
	exit 1
fi

BIN_DIR="$(pwd)/tmp/_output/bin"
mkdir -p ${BIN_DIR}
PROJECT_NAME="memcached-operator"
REPO_PATH="github.com/operator-framework/operator-sdk-samples/memcached-operator"
TEST_PATH="${REPO_PATH}/${TEST_LOCATION}"
BUILD_PATH="${REPO_PATH}/cmd/${PROJECT_NAME}"
echo "building "${PROJECT_NAME}"..."
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ${BIN_DIR}/${PROJECT_NAME} $BUILD_PATH
if $ENABLE_TESTS ; then
	echo "building "${PROJECT_NAME}-test"..."
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go test -c -o ${BIN_DIR}/${PROJECT_NAME}-test $TEST_PATH
fi
```

So for projects with the older script the `operator-sdk build --enable-test` command will fail. So we should stop generating helper scripts and just implement them as Go code in the binary.

I've already done the same for the codegen script `tmp/codegen/update-generated.sh` in the controller-runtime refactor branch.
https://github.com/operator-framework/operator-sdk/commit/5eb5814c2f5a34d8e653f33dd921eb4956b72336
