### ISSUE TITLE
Dependabot alerts on GHA

### ISSUE THREAD

**Issue by fjammes** [operator-framework/operator-sdk#5411]
## Type of question

General operator-related help

#### What did you do?

In my project: https://github.com/lsst/qserv-operator:
- I use latest version of operator-sdk (1.15.0) 
- I have enabled GHA's "Dependabot alerts"

#### What did you expect to see?

I do not want to have "Dependabot alerts"

#### What did you see instead? Under which circumstances?

I have two "Dependabot alerts" related to  dependencies provided by "operator-sdk": 
https://github.com/lsst/qserv-operator/security/dependabot

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

kind

`$ operator-sdk version`
operator-sdk version: "v1.15.0", commit: "f6326e832a8a5e5453d0ad25e86714a0de2c0fc8", kubernetes version: "1.21", go version: "go1.16.10", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)
go version go1.16.3 linux/amd64

`$ kubectl version`
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by asmacdo** [comment]
I forked so i could see the dependabot warnings. 
![Screenshot from 2021-11-29 14-41-42](https://user-images.githubusercontent.com/1028657/143932062-fd6236b8-6ff4-4e76-894d-ec8f59a3b35a.png)

**Comment by ryantking** [comment]
Hi @fjammes, I just made a fresh repo with a new operator SDK project, and am not seeing any dependabot alerts. The versions locked in the `go.sum` files match. Can we get confirmation that you are still seeing these alerts?

**Comment by fjammes** [comment]
Thanks @ryantking , yes I am still seeing the two alerts. Could you please provide me your `go.sum`? Here is two extract of mine:
```
$ cat go.sum| grep jwt-go
github.com/dgrijalva/jwt-go v3.2.0+incompatible/go.mod h1:E3ru+11k8xSBh+hMPgOLZmtrrCbhqsmaPHjLKYnJCaQ=
github.com/form3tech-oss/jwt-go v3.2.2+incompatible/go.mod h1:pbq4aXjuKjdthFRnoDwaVPLA+WlJuPGy+QneDUgJi2k=
github.com/form3tech-oss/jwt-go v3.2.3+incompatible h1:7ZaBxOI7TMoYBfyA3cQHErNNyAWIKUMIwqxEtgHOs5c=
github.com/form3tech-oss/jwt-go v3.2.3+incompatible/go.mod h1:pbq4aXjuKjdthFRnoDwaVPLA+WlJuPGy+QneDUgJi2k=
```
```
$ cat go.sum| grep miekg 
github.com/miekg/dns v1.0.14/go.mod h1:W1PPwlIAgtquWBMBEV9nkV9Cazfe8ScdGz/Lj7v3Nrg=
```

The vulnerabilities are on `github.com/miekg/dns <= 1.1.25` and `dgrijalva/jwt-go <= 3.2.0`

**Comment by ryantking** [comment]
@fjammes here are the same commands you executed:
```
$ cat go.sum| grep jwt-go
github.com/dgrijalva/jwt-go v3.2.0+incompatible/go.mod h1:E3ru+11k8xSBh+hMPgOLZmtrrCbhqsmaPHjLKYnJCaQ=
github.com/form3tech-oss/jwt-go v3.2.2+incompatible/go.mod h1:pbq4aXjuKjdthFRnoDwaVPLA+WlJuPGy+QneDUgJi2k=
github.com/form3tech-oss/jwt-go v3.2.3+incompatible h1:7ZaBxOI7TMoYBfyA3cQHErNNyAWIKUMIwqxEtgHOs5c=
github.com/form3tech-oss/jwt-go v3.2.3+incompatible/go.mod h1:pbq4aXjuKjdthFRnoDwaVPLA+WlJuPGy+QneDUgJi2k=
```

```
$ cat go.sum| grep miekg 
github.com/miekg/dns v1.0.14/go.mod h1:W1PPwlIAgtquWBMBEV9nkV9Cazfe8ScdGz/Lj7v3Nrg=
```

The versions look the same to me.

[Here is my test repo](https://github.com/ryantking/test-operator)

**Comment by fjammes** [comment]
@ryantking thanks so much! On my side the Dependabot alert have disappeared from Github webpage of my project for an unknown reason... So I will close this one.

**Comment by ryantking** [comment]
@fjammes Great! Feel free to reopen if something else crops up.
