### ISSUE TITLE
Remove the Remove the Optional(stage: alpha) Community Operator bundle 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#5422]
#### Describe the problem you need a feature to resolve.

For SDK release 1.18.0, remove the Optional(stage: alpha) Community Operator bundle since we move its implementation to  the [external validator](https://github.com/redhat-openshift-ecosystem/ocp-olm-catalog-validator/).

#### Describe the solution you'd like.

- Just perform the changes in: https://github.com/operator-framework/operator-sdk/pull/5412
- also, remove the warning added in: https://github.com/operator-framework/operator-sdk/pull/5414
- Then, ensure that we remove that from the API as well: https://github.com/operator-framework/api/pull/196

**considered drawbacks**
- Check if its main consumers were not able to move forward and adopted the external validator before remove. (ping @camilamacedo86 and/or @gallettilance )

**Comment by camilamacedo86** [comment]
c/c @jmrodri

**Comment by asmacdo** [comment]
I've added this as a release blocker. This has been deprecated for some time, and I am guessing that this will prevent some more problems for @camilamacedo86 with operatorframework/api version bumps

**Comment by asmacdo** [comment]
After speaking with @camilamacedo86 this is not ready to be done yet. I am moving to the backlog under priority/important-soon so this will be discussed at the next backlog grooming meeting.

**Comment by camilamacedo86** [comment]
We might want to add something here that it is blocked until we ensure that its consumers are no longer using it.

**Comment by jmrodri** [comment]
@camilamacedo86 who are the "consumers" of this?

**Comment by camilamacedo86** [comment]
Hi @jmrodri, 

>who are the "consumers" of this?

These are the users/places which "consume" the validator. 
Our concern here is that many places still using this validator so far. 
We might need to wait a long period to be able to remove the alpha check without impact nobody.

Therefore, I think we could add this one to the 2.x milestone.
