### ISSUE TITLE
Document status writer in Helm Operator Tutorial

### ISSUE THREAD

**Issue by ktsakos** [operator-framework/operator-sdk#5423]
The overview section refers to the : Update the Nginx CR status using the status writer with the names of the CR’s pods

It seems that we cannot do that with the helm based operators or it is not explained in the tutorial.

**Comment by varshaprasad96** [comment]
@ktsakos Thanks for bringing this up. Would you mind submitting a PR to fix this in the SDK documentation? Please let us know if you need any help.
