### ISSUE TITLE
Updating only status subresource does not trigger reconciliation in ansible based operator

### ISSUE THREAD

**Issue by jobcespedes** [operator-framework/operator-sdk#5424]
#### What did you do?
1. Create CR, kind X, named X-sample using ansible based operator
2. Create CR, kind Y, named Y-sample using ansible based operator
3. Update X-sample status subresource from Y-sample reconciling loop using [k8s_event module](https://github.com/operator-framework/operator-sdk-ansible-util/blob/master/plugins/modules/k8s_status.py). The only modification is inside status subresources.

#### What did you expect to see?
* X-sample reconciliation triggered because of its status update

#### What did you see instead? Under which circumstances?
* X-sample CR `resourceVersion` is incremented and status updated
* No X-sample reconciliation triggered

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

Minikube
`$ operator-sdk version`

```
operator-sdk version: "v1.15.0", commit: "f6326e832a8a5e5453d0ad25e86714a0de2c0fc8", kubernetes version: "1.21", go version: "go1.16.10", GOOS: "linux"
, GOARCH: "amd64"
```
`$ go version` (if language is Go)
N/A

`$ kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", B
uildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", B
uildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
```

#### Additional context

* I'm looking for a way to trigger reconciliation from a different CR using Ansible

**Comment by jobcespedes** [comment]
I just remembered that an Ansible based CR has its status update every reconcile loop when managed status is enabled (default). That makes me think that status subresource update not triggering reconciliation is the expected behavior. I'm closing this one.

**Comment by wangqymro** [comment]
This is still an issue. Not every resource is handled by the Ansible operator, and the the option exists to not having the operator manage the status. CR's status often times indicates the result of the reconcile such as generated content. It is valid for the ansible operator that watches this resource to be notified of the change.
