### ISSUE TITLE
Operator bundle images flagged as running as root

### ISSUE THREAD

**Issue by nschambu** [operator-framework/operator-sdk#5453]
#### Describe the problem you need a feature to resolve.

We are getting reports that the Operator bundle images are being flagged by an image scanner as running as root. It would appear that the scanner is doing a docker inspect or podman inspect and seeing that the Config.User field is "" which they consider to mean running as root.

I understand that as a scratch image, the user doesn't mean anything, but setting a user will prevent false positives like this one in image scanners.

I had originally created the issue in the operator-registry repo (https://github.com/operator-framework/operator-registry/issues/825) and was asked to move it here.

#### Describe the solution you'd like.

I would like to see a user field added to the default bundle.Dockerfile that is created by the `make bundle` command so that bundle images created by this Dockerfile have a non-blank user field.

**Comment by theishshah** [comment]
Looks like we would have 3 options for going about this:
1) Set a default user in the bundle image with no user config (forces users to edit bundle after the fact if it needs to change)
2) Set a default user in the bundle but allow the user to set a different option in the config before running `make bundle`
3) No default, force a user to choose/set a user value for the bundle image before generating

**Comment by jmrodri** [comment]
@joelanford @kevinrizza @camilamacedo86 so looking at this issue, what impact would adding `USER nonroot` to the bundles have? I'm leery of making this change because while it seems trivial, I'm afraid of causing a huge problem.

**Comment by camilamacedo86** [comment]
I think we can : 

a) Just replace the [FROM scratch](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/bundle.Dockerfile#L1) with [FROM gcr.io/distroless/static:nonroot](http://gcr.io/distroless/static:nonroot)
](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/Dockerfile#L22) such as we do for the Operator docker image. 

So that the bundle.Dockerfile image when inspect will: 

```
  "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "65532",
            "AttachStdin": false,
            "AttachStdout": false,
```

The change would need to be made in the boilerplate : https://github.com/operator-framework/operator-sdk/blob/master/internal/util/bundleutil/template.go#L28

**Comment by joelanford** [comment]
We should keep using the scratch image. Using anything else would add extra/unnecessary files that would bloat the image size and potentially be in violation of the spec.

From a purity standpoint, I wonder if this is really just a bug in the scanner. The image does not have an entrypoint or command set, so there's no way to run it.

I tried building the testdata/go/v3 bundle and then running it:
```console
$ docker run example.com/memcached-operator-bundle:v0.0.1
docker: Error response from daemon: No command specified.
See 'docker run --help'.
```

IMO, the scanner should be updated to only flag an image that can run as root if the image has a command/entrypoint set.

**Comment by jmrodri** [comment]
I agree with @joelanford on this one. The bundles are just data. I am closing this issue if you feel that it should not be closed, please reopen with an explanation as to why.

**Comment by nschambu** [comment]
I think that's a reasonable take. I'll try and take it up with the scanning tool product that's hitting this. Thanks.
