### ISSUE TITLE
Add support for k8s 1.23

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#5469]
https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/

**Comment by asmacdo** [comment]
This is not yet triaged, but IMO this is could a blocker for 1.16 release unless there is a time sensitive need for that release

**Comment by varshaprasad96** [comment]
Related issue in KB: https://github.com/kubernetes-sigs/kubebuilder/issues/2448
We can still bump the version in SDK binary though

**Comment by varshaprasad96** [comment]
There are 2 things to this:
1. Bumping SDK binary to use 1.23
2. Bump the deps in project scaffoldings to use 1.23.
(2) is still dependent on [kubernetes-sigs/kubebuilder#2448](https://github.com/kubernetes-sigs/kubebuilder/pull/2471) to be merged.

**Comment by camilamacedo86** [comment]
That is ready to fly now. We can bump master kb branch and also update controller-runtime and tools as well.

**Comment by varshaprasad96** [comment]
Closing this, as we have bumped everything to 1.23
