### ISSUE TITLE
Suggestion : add a parameter to generate a project for a specific version of openshift/kubernetes

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#549]
When we execute the command `operator-sdk new` to create an API and operator, then the go project is created using the go dependencies defined within the upstream sdk project

I would like to suggest to add a parameter to tell the version to be used for openshift/kubernets clients `3.10 to 3.11` to be populated within the `gopkg.toml` file

e.g

```
operator-sdk new spring-boot-operator --version=3.11 --api-version=springboot.snowdrop.me/v1alpha1 --kind=SpringBoot
```

For `3.11`, then we should get such versions

```
[[override]]
  name = "k8s.io/code-generator"
  # revision for tag "kubernetes-1.11.2"
  revision = "6702109cc68eb6fe6350b83e14407c8d7309fd1a"

[[override]]
  name = "k8s.io/api"
  # revision for tag "kubernetes-1.11.2"
  revision = "2d6f90ab1293a1fb871cf149423ebb72aa7423aa"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  # revision for tag "kubernetes-1.11.2"
  revision = "408db4a50408e2149acbd657bceb2480c13cb0a4"

[[override]]
  name = "k8s.io/apimachinery"
  # revision for tag "kubernetes-1.11.2"
  revision = "103fd098999dc9c0c88536f5c9ad2e5da39373ae"

[[override]]
  name = "k8s.io/client-go"
  # revision for tag "kubernetes-1.11.2"
  revision = "1f13a808da65775f22cbf47862c4e5898d8f4ca1"

[[override]]
  name="github.com/openshift/client-go"
  branch="release-3.11"
```

**Comment by fanminshi** [comment]
@cmoulliard the idea is sound but it is not simple to just generate a gopkg.toml that works out of box. Wha't the mapping between 3.11 to the version tag/ revision of the `k8s.io/code-generator`, `k8s.io/apimachinery`, and etc. if we do figure out how to do that, can operator-sdk guarantee that that k8s version works with operator-sdk api.  For now, the default  gopkg.toml is guarantee to work because we run e2e test for it. Hence, I am not in favor to add the `--version` flag because I don't think the operator-sdk can make any guarantee.

**Comment by shawn-hurley** [comment]
I agree with @fanminshi, I don't think that it is a trivial change.

I think that this might be something interesting to add to the release doc. Is this something that we should consider as apart of the release? Should instead we let the X.X.X version of the binary only works with Y.Y.Y version of kubernetes. 

I don't think we should have any specific logic relating to openshift IMO.

**Comment by cmoulliard** [comment]
If you provide such a table within the README.md page mentioning which SDK version has been tested according to openshift (okd, ocp) version x.y.z, that will be already a great plus
Something like this : https://github.com/openshift/kubernetes-client-go#compatibility-matrix
