### ISSUE TITLE
How to use operator-sdk with ansible 

### ISSUE THREAD

**Issue by slaurencelle** [operator-framework/operator-sdk#5498]
## Type of question

General operator-related help

## Question
I like to know how i can implement and use operator-sdk for ansible to be able to run existing role or playbook to configure and deploy apps. Also is it possible to choose another version of the OS when deploying new CR wit the operator because when using the default one with the operator after creating this one he is using 
#### What did you do?
Hello,

I was able to deploy and have my sdk-operator for ansible working but it is unable to deploy any cr, it is just giving me this error : 

TASK [Packages] ******************************** 
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "dnf install -y python3-dnf", "msg": "Could not import the dnf python module using /usr/bin/python3.8 (3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]). Please install `python3-dnf` package or ensure you have specified the correct ansible_python_interpreter.", "rc": 1, "results": [], "stderr": "Error: This command has to be run with superuser privileges (under the root user on most systems).\n", "stderr_lines": ["Error: This command has to be run with superuser privileges (under the root user on most systems)."], "stdout": "Not root, Subscription Management repositories not updated\n", "stdout_lines": ["Not root, Subscription Management repositories not updated"]}
-------------------------------------------------------------------------------
{"level":"error","ts":1642173330.323661,"logger":"logging_event_handler","msg":"","name":"intranet-sample","namespace":"default","gvk":"web-intranet.dgeq.qc.ca/v1alpha1, Kind=Intranet","event_type":"runner_on_failed","job":"2161481606465480353","EventData.Task":"Packages","EventData.TaskArgs":"","EventData.FailedTaskPath":"/opt/ansible/roles/intranet/tasks/main.yml:19","error":"[playbook task failed]"}
{"level":"error","ts":1642173330.5026891,"logger":"runner","msg":"ansible-playbook 2.9.26\r\n  config file = /etc/ansible/ansible.cfg\r\n  configured module search path = ['/usr/share/ansible/openshift']\r\n  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible\r\n  executable location = /usr/local/bin/ansible-playbook\r\n  python version = 3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]\r\nUsing /etc/ansible/ansible.cfg as config file\r\nSkipping callback 'actionable', as we already have a stdout callback.\nSkipping callback 'awx_display', as we already have a stdout callback.\nSkipping callback 'counter_enabled', as we already have a stdout callback.\nSkipping callback 'debug', as we already have a stdout callback.\nSkipping callback 'dense', as we already have a stdout callback.\nSkipping callback 'dense', as we already have a stdout callback.\nSkipping callback 'full_skip', as we already have a stdout callback.\nSkipping callback 'json', as we already have a stdout callback.\nSkipping callback 'minimal', as we already have a stdout callback.\nSkipping callback 'null', as we already have a stdout callback.\nSkipping callback 'oneline', as we already have a stdout callback.\nSkipping callback 'selective', as we already have a stdout callback.\nSkipping callback 'skippy', as we already have a stdout callback.\nSkipping callback 'stderr', as we already have a stdout callback.\nSkipping callback 'unixy', as we already have a stdout callback.\nSkipping callback 'yaml', as we already have a stdout callback.\n\r\nPLAYBOOK: 2adfdbd994bb40c39ba3216fa35e3cdc *************************************\n1 plays in /tmp/ansible-operator/runner/web-intranet.dgeq.qc.ca/v1alpha1/Intranet/default/intranet-sample/project/2adfdbd994bb40c39ba3216fa35e3cdc\n\r\nPLAY [localhost] ***************************************************************\nMETA: ran handlers\n\r\nTASK [intranet : Packages] *****************************************************\r\ntask path: /opt/ansible/roles/intranet/tasks/main.yml:19\nfatal: [localhost]: FAILED! => {\"changed\": false, \"cmd\": \"dnf install -y python3-dnf\", \"msg\": \"Could not import the dnf python module using /usr/bin/python3.8 (3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]). Please install `python3-dnf` package or ensure you have specified the correct ansible_python_interpreter.\", \"rc\": 1, \"results\": [], \"stderr\": \"Error: This command has to be run with superuser privileges (under the root user on most systems).\\n\", \"stderr_lines\": [\"Error: This command has to be run with superuser privileges (under the root user on most systems).\"], \"stdout\": \"Not root, Subscription Management repositories not updated\\n\", \"stdout_lines\": [\"Not root, Subscription Management repositories not updated\"]}\n\r\nPLAY RECAP *********************************************************************\r\nlocalhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   \r\n\n","job":"2161481606465480353","name":"intranet-sample","namespace":"default","error":"exit status 2"}
----- Ansible Task Status Event StdOut (web-intranet.dgeq.qc.ca/v1alpha1, Kind=Intranet, intranet-sample/default) -----

This is in the manager log of the operator after creating my cr

here is the code in my cr file to deploy my apps

apiVersion: web-intranet.dgeq.qc.ca/v1alpha1
kind: Intranet
metadata:
  name: intranet-sample
spec:
  # Add fields here
  state: present
  size: 1
  containers:
  - name: intranet-container
    image: docker.io/wglacier/rhel7.9
    imagePullPolicy: IfNotPresent
    command: [ "sleep" ]
    args: [ "infinity" ]

#### What did you expect to see?
i was expecting a new pod starting a rhel 7.9 container and executing the task in my ansible role that i associate with the new operator.

#### What did you see instead? Under which circumstances?
But instead , i got no new pod create and only the manager tryning to execute the task in my ansible role but being stuck at the step i 
documented.

#### Environment
The installation i have is:
Kubernetes k8s version 1.21.3 install on rhel 7.9, the cluster is 2 master nodes and 2 workers nodes
the opeartor-sdk version i use is 1.15.0

**Operator type:**
operator type:  ansible

/language ansible
Using existing role and playbook 

**Kubernetes cluster type:**
on premise k8s built from the open source version with rhel 7.9 node

kubernetes cluster vanilla deployment on rhel 7.09
`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

#### Additional context

Hope someone cal help me with this :( 
this is my first run creating an kubernetes operator using operator-sdk so maybe i have a bad understanding of what i can do with it.

Regards,

Stephane

**Comment by fabianvf** [comment]
@slaurencelle Ansible-based Operators generally interact with the kubernetes API, by default there is only one host (localhost), which is the operator pod itself. It sounds like what you want to do is create a pod, add it to your inventory, and then target it as a host and run a series of commands against it. Commands like `dnf install -y python3-dnf` will not work in the operator pod itself as it does not run as root.

In order to do what I think you want to, you would want to have a playbook structure something more like this:

```
- hosts: localhost
  tasks:
    - name: Create target pod
      kubernetes.core.k8s:
        # here you would add the code that takes your `containers` field and turns it into a pod/deployment/whatever you actually want to create in the cluster
    - name: Add the previously created host to inventory
      add_host:
        name: targets # Name of the pod that you want to target
        groups: # whatever group name you want the host to belong to
        kubectl_container: # The name of the container in the pod you are targeting
        kubectl_namespace: # The namespace of the pod you deployed

- hosts: targets
  tasks;
    # here you can now put whatever you wanted to do in order to provision the container with dnf etc etc
```

This is fairly advanced usage for the k8s ansible collection, and generally you want to use pre-built images rather than provisioning them after they've been deployed, but if you wanted to provision containers in a cluster that's pretty much how you'd do it
