### ISSUE TITLE
Add ginkgo tests for go/operator-sdk memcached example

### ISSUE THREAD

**Issue by MathieuCesbron** [operator-framework/operator-sdk#5500]
Hello,

I have followed the tutorial to create an operator. I find it globally straight to the point and excellent. 

I struggled a bit to add ginkgo tests because it is not part of the example even though ginkgo is preinstalled.

I would like to do a PR to add ginkgo tests for the memcached operator, do you accept the feature ?

Have a good day,

**Comment by varshaprasad96** [comment]
Yes, thanks a lot! Please feel free to create a PR! We appreciate that.

**Comment by asmacdo** [comment]
IMO 
To keep this working, we'll need to run it during CI so ideally it should be very minimal, I'm thinking just a sanity test that shows that the tests run and pass that can be easily referenced by operator authors.

If folks are comfortable adding tests for the memcached logic too, maybe we could include that part just as an example and not run those tests every PR somehow.

**Comment by shubham-cmyk** [comment]
@varshaprasad96 Is there some example or reference in this repo about adding Ginkgo + Gomega based test case? 

I am trying to write integration testing that could use `Envtest Binaries Manager`. 
Any link to other good resources would also be a great help to me.!
