### ISSUE TITLE
Unable to new projects on MacOSX - when validating project  Error "FATA[0000] failed to exec []string{"go", "build", "./..."}: exit status 1" is faced

### ISSUE THREAD

**Issue by wuyingjun-lucky** [operator-framework/operator-sdk#5502]
#### What did you do?

INFO[0000] Creating new Go operator 'test-operator'.    
INFO[0000] Created go.mod                               
INFO[0000] Created tools.go                             
INFO[0000] Created cmd/manager/main.go                  
INFO[0000] Created build/Dockerfile                     
INFO[0000] Created build/bin/entrypoint                 
INFO[0000] Created build/bin/user_setup                 
INFO[0000] Created deploy/service_account.yaml          
INFO[0000] Created deploy/role.yaml                     
INFO[0000] Created deploy/role_binding.yaml             
INFO[0000] Created deploy/operator.yaml                 
INFO[0000] Created pkg/apis/apis.go                     
INFO[0000] Created pkg/controller/controller.go         
INFO[0000] Created version/version.go                   
INFO[0000] Created .gitignore                           
INFO[0000] Validating project                           
go: github.com/operator-framework/operator-sdk@v0.18.2: missing go.sum entry; to add it:
        go mod download github.com/operator-framework/operator-sdk
go: github.com/operator-framework/operator-sdk@v0.18.2: missing go.sum entry; to add it:
        go mod download github.com/operator-framework/operator-sdk
FATA[0000] failed to exec []string{"go", "build", "./..."}: exit status 1 

#### Environment

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wuyingjun/Library/Caches/go-build"
GOENV="/Users/wuyingjun/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/wuyingjun/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/wuyingjun/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cj/b9tly79d02585rzmksfdsll40000gn/T/go-build2034096447=/tmp/go-build -gno-record-gcc-switches -fno-common"

operator-sdk version : v0.18.2 
(v 1.x won't faced)

**Comment by camilamacedo86** [comment]
Hi @wuyingjun-lucky, 

The version v0.18.2 is very old and no longer supported.
We would like to recommend you upgrade your project to use the latest SDK version. See: https://sdk.operatorframework.io/docs/building-operators/golang/migration/

Regards your issue, see that the v0.18.2 did not support the go version that you are using. 
You must use 1.13 with it. See: https://github.com/operator-framework/operator-sdk/blob/v0.18.1/go.mod#L3

**Comment by wuyingjun-lucky** [comment]
> 

I can init a new project with latest sdk version succussfully. 
I faced the same error under 1.13 & 1.16 & 1.17

**Comment by camilamacedo86** [comment]
Hi @wuyingjun-lucky, 
>I can init a new project with latest sdk version successfully.

That is great.  

Regards the version 0.18.2 it is really no longer supported so I'd recommend you do not use it. 
In this way, I am not sure if we ought to spend time investigating it. Is that make sense?
Could you please use the latest SDK version and close this one?

**Comment by wuyingjun-lucky** [comment]
The time 0.18.2 released is 2020.6 and some projects also used it .

**Comment by camilamacedo86** [comment]
HI @wuyingjun-lucky, 

> The time 0.18.2 released is 2020.6 and some projects also used it .

But any version < 1.0.0 is no longer supported. In this way, we recommend upgrading the projects to the latest version. See: https://sdk.operatorframework.io/docs/building-operators/golang/migration/

**Comment by wuyingjun-lucky** [comment]
> 

OK, I closed the issue
