### ISSUE TITLE
SecurityContextConstraints cant be applied on envtest, even after being added to schema

### ISSUE THREAD

**Issue by DanArlowski** [operator-framework/operator-sdk#5514]
#### What did you do?

When Creating A `security.openshift.io/v1` SCC using operator-sdk - when working against an openshift4 cluster (using the built in `make run` command or running inside the cluster as a deployment) the operator manage to create the SCC object

but when running with the unittests using the envtest suite, the test fail with the error:
```
<TIMESTAMP>    ERROR   controller-runtime.manager.controller.sosivio   Reconciler error        {"reconciler group": "<GROUP>", "reconciler kind": "<KIND>", "name": "<NAME>", "namespace": "", "error": "no matches for kind \"SecurityContextConstraints\" in version \"security.openshift.io/v1\""}
```

test_suite.go:
```go
...
import (
...
	routev1 "github.com/openshift/api/route/v1"
	securityv1 "github.com/openshift/api/security/v1"
	apiextensionv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
...
)
...
	err = apiextensionv1.AddToScheme(scheme.Scheme)
	Expect(err).NotTo(HaveOccurred())

	err = routev1.Install(scheme.Scheme)
	Expect(err).NotTo(HaveOccurred())

	err = securityv1.Install(scheme.Scheme)
	Expect(err).NotTo(HaveOccurred())
...
```

main.go

```go
...
import (
...
	routev1 "github.com/openshift/api/route/v1"
	securityv1 "github.com/openshift/api/security/v1"
	apiextensionv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
...
)
...
	utilruntime.Must(routev1.AddToScheme(scheme))
	utilruntime.Must(securityv1.AddToScheme(scheme))
	utilruntime.Must(apiextensionv1.AddToScheme(scheme))
...

```

#### What did you expect to see?

The SCC should have been created in the tests

#### What did you see instead? Under which circumstances?

SCC failed with the logs above,
any other resources that was added to the scheme created successfully

when commenting out the SCC from the operator, the openshift route is creating as it should on the test environement.

the SCC is the only resource that fails.

we checked that the SCC is correctly configured into the scheme:
```go

	for k := range scheme.Scheme.AllKnownTypes() {
		if k.Kind == "SecurityContextConstraints" {
			fmt.Println(k)
		}
	}
```
which in-fact prints the SecurityContextConstraints in the correct group/version

#### Environment

**Operator type:**
/language go

**Kubernetes cluster type:**

Openshift & envtest

```
$ operator-sdk version
operator-sdk version: "v1.16.0", commit: "560044140c4f3d88677e4ef2872931f5bb97f255", kubernetes version: "1.21", go version: "go1.16.13", GOOS: "linux", GOARCH: "amd64"
```

`$ go version` (if language is Go)
`go version go1.17.6 linux/amd64`

`$ kubectl version`
`client - 1.23.1`

#### Possible Solution

Couldn't find any workarounds, even when trying to register the SCC kind manually using [this guide](https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#if-3rd-party-resource-does-not-have-addtoscheme-function)

#### Additional context

envtest version - 1.21
tried to delete the binaries and redownload `make test` to no avail

the SAME EXACT SCC object is getting applied and accepted by OCP4 cluster version `4.7.34`

**Comment by DanArlowski** [comment]
guys - any news on that?

**Comment by DanArlowski** [comment]
@jmrodri  @kensipe  @jberkhahn  @varshaprasad96 
Care To explain the root cause of the issue?I
I feel thats an important part of the Open Source community is sharing the root cause of the issues - If you'd done that I might've contributed it for the 1.18 milestone as its important to us...

**Comment by varshaprasad96** [comment]
@DanArlowski sorry for the delay. Will make sure to bring this up again in the next triage meeting and discuss about it.

**Comment by DanArlowski** [comment]
Small Update from my side
Seems like the Project kind of openshift have the same behaviour (cant be applied in the envtest, is applied in the actual cluster(s)

My Guess as the only common between the 2, which is only different than the Openshift Route CR, is that they are both Cluser-Wide resources, and not namespaces, 
So I think that might be relevant for the issue.

**Comment by jmrodri** [comment]
@DanArlowski I don't know the root cause of the issue :) sorry for punting this from release to release. I see you have a controller-runtime issue open, so that should get some more eyes on the issue.

**Comment by jmrodri** [comment]
@DanArlowski your issue looks pretty similar to this old issue: https://github.com/kubernetes-sigs/controller-runtime/issues/1191 there was a PR to add an FAQ: https://github.com/kubernetes-sigs/controller-runtime/pull/1393/files  in that issue the following question was supposed to be added.

---
### Q: When using envtest with a third party API, why do I see the error: `no matches for kind "Kind" in version "<group>/<version>"`?

**A**: While testing a third party API with `envtest`, in addition to registering the API type with the test client, you would also
have to register it with the test server. To do so, download the associated CustomResourceDefinition's manifest locally
and add its path to [`Environment.CRDDirectoryPaths`](https://pkg.go.dev/github.com/kubernetes-sigs/controller-runtime/pkg/envtest#Environment).

For example, to use `customapiv1` in `envtest`:
- Register the API type with test client by adding it to the `scheme` used in the tests:

```go
...
var _ = BeforeSuite(func (done Done)) {
  ...
  testScheme := scheme.Scheme
  err := customapiv1.AddToScheme(testScheme)
  Expect(err).NotTo(HaveOccurred())
}
```

- Specify the CRD path to install it in the test environment:

```go
...

---

The CRD for security seems to be located here: https://github.com/openshift/api/tree/master/security/v1
var _ = BeforeSuite(func(done Done) {
  ...
	By("bootstrapping test environment")
	testEnv = &envtest.Environment{
		CRDDirectoryPaths: []string{<location_of_the_CRD_for_`customapi`>},
	}
...

**Comment by DanArlowski** [comment]
For feature guys - Apply the CRD in Addition o adding the scheme.
