### ISSUE TITLE
Request: Timeframe for next release with go v1.17 update.

### ISSUE THREAD

**Issue by raghuvenkat1** [operator-framework/operator-sdk#5521]
## Type of question

Open question

#### What did you do?
Operator development.

#### What did you expect to see?
Need to know the timeframe of release tags.
 
#### What did you see instead? Under which circumstances?
We see `operator-framework / ansible-operator:v1.16 ` as the last release candidate. We want a release candidate containing the latest go v1.17 update. We would like to know if these changes can be pushed with the release tag ASAP.

#### Environment
Openshift

**Operator type:**

/language ansible 

**Kubernetes cluster type:**
Openshift

#### Additional context

When we can expect the next release.

**Comment by varshaprasad96** [comment]
An upstream SDK release is scheduled for tomorrow (SDK 1.17.0). Have created an issue to track the same: https://github.com/operator-framework/operator-sdk/issues/5528

**Comment by jberkhahn** [comment]
Hopefully this answers your question. Please reopen if you need more information.

**Comment by raghuvenkat1** [comment]
Thank you @varshaprasad96 and @jberkhahn.
