### ISSUE TITLE
Release SDK 1.17

### ISSUE THREAD

**Issue by varshaprasad96** [operator-framework/operator-sdk#5528]
Release Operator SDK 1.17 version

**Comment by jberkhahn** [comment]
ping austin before we make the release branch

**Comment by raghuvenkat1** [comment]
@varshaprasad96 @jberkhahn , any update on this please.

**Comment by littleamigo** [comment]
is it released meanwhile?

**Comment by jberkhahn** [comment]
Yes, we cut the release last week.
