### ISSUE TITLE
Debug operator when it starts locally

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#553]
With the help of this command, we can start locally the Operator

```
OPERATOR_NAME=spring-boot-operator operator-sdk up local
INFO[0000] Go Version: go1.10.2                         
INFO[0000] Go OS/Arch: darwin/amd64                     
INFO[0000] operator-sdk Version: 0.0.6+git              
INFO[0000] Metrics service spring-boot-operator created 
INFO[0000] Watching springboot.snowdrop.me/v1alpha1, SpringBoot, default, 5000000000 
```

Is it possible to also start it in DEBUG mode ?

**Comment by allamand** [comment]
if using logrus you can configure it `logrus.SetLevel(logrus.DebugLevel)`

**Comment by allamand** [comment]
I uses LOG_LEVEL env var to configure my log level. I don't uses operator-sdk up neither

**Comment by LiliC** [comment]
@cmoulliard I already opened an issue to add different log levels in https://github.com/operator-framework/operator-sdk/issues/503 Closing this in favor of that, but please comment with suggestions there! Thanks!
