### ISSUE TITLE
Standardise get custom resource at start of reconcile

### ISSUE THREAD

**Issue by MathieuCesbron** [operator-framework/operator-sdk#5530]
Hello,

In every reconcile loop that I've seen, we start to GET the resource the same way every time:

<img width="540" alt="Screenshot 2022-02-01 at 20 40 00" src="https://user-images.githubusercontent.com/45229023/152039277-85201c7f-2690-4626-bf1d-53acb1b85484.png">

I cannot imagine a case scenario where we would do something else than this. 

Would it be interesting to make a function to do that or to standardise it in other ways ? Since every reconcile need to do it.

Have a good day,

**Comment by VenkatRamaraju** [comment]
Hey,

Operator-SDK leverages [kubebuilder's create api](https://book.kubebuilder.io/cronjob-tutorial/new-api.html) command to generate controllers, so this suggestion can probably be made upstream at [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) and discussed there as well.

**Comment by VenkatRamaraju** [comment]
Hey @MathieuCesbron,

Just wanted to check in on the status of this issue. Feel free to ping me if you have any questions.

**Comment by VenkatRamaraju** [comment]
@MathieuCesbron closing this. Feel free to re-open it if you want to discuss this further.
