### ISSUE TITLE
operator-sdk bundle validate should have an option to turn warnings into errors 

### ISSUE THREAD

**Issue by wallrj** [operator-framework/operator-sdk#5544]
## Feature Request

`operator-sdk bundle validate --permissive=false`

The documentation advises bundle authors to check their bundle  using `operator-sdk bundle validate` and that:

> Any warnings here might turn into failing pipeline tests here. Please correct all issues displayed. A list of fields that are scanned can also be reviewed with [this list](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-required-fields.md).

-- https://github.com/operator-framework/community-operators/blob/1591b5e18d47129ed14e83ac2f9832d6cb41bb40/docs/testing-operators.md#L234-L250

So it would be nice if there was a way to run the tool in CI pipelines and have it fail if there are warnings, 
so that the problems can be fixed proactively.

And indeed there is a comment in the code to this effect: 

https://github.com/operator-framework/operator-sdk/blob/836a088eee1195515657fb223cf9274cf6e963ed/internal/cmd/operator-sdk/bundle/validate/validate.go#L71-L72

There is some discussion about this in Slack here: https://kubernetes.slack.com/archives/C017UU45SHL/p1644400918179439

/cc @estroz @camilamacedo86

**Comment by camilamacedo86** [comment]
Hi @wallrj, 

> So it would be nice if there was a way to run the tool in CI pipelines and have it fail if there are warnings,
so that the problems can be fixed proactively.

I think your suggestion is very interesting. The only cons that I can see are that WARNINGs might only be raised to let you know that you should ensure something that might not be required be fixed or in your specific use case would not make sense apply any change.

**Comment by camilamacedo86** [comment]
@jmrodri @tlwu2013 wdyt?

**Comment by jberkhahn** [comment]
This sounds reasonable, would you be interested in submitting this via pull request? An optional flag would be an easy way to do this.

**Comment by wallrj** [comment]
In https://github.com/operator-framework/api/issues/172#issuecomment-981503547 #5542 
> I thought we had pluggable test suites these days. If so, then making the test fail should not be an issue as long as the user can decide whether or not they want to execute these tests.

Which makes me think that perhaps there should instead be:

```console
$ operator-sdk bundle validate ./bundle --select-optional suite=operatorframework

vs

$ operator-sdk bundle validate ./bundle --select-required suite=operatorframework

```

I'll try and create a PR with the simple `--permissive=false` flag as a starting point for discussion.
