### ISSUE TITLE
Quickstart for go based operators needs kubebuilder in /usr/local.  I do not see this mentioned in the quickstart or its pre-reqs

### ISSUE THREAD

**Issue by bradtopol** [operator-framework/operator-sdk#5546]
### What is the URL of the document?

https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/

### Which section(s) is the issue in?

Build and push your operator’s image:
make docker-build docker-push IMG="example.com/memcached-operator:v0.0.1"

### What needs fixing?

I decided to try to follow the steps in the Quickstart for go based operators.  When I get to the following step:

make docker-build docker-push IMG="example.com/memcached-operator:v0.0.1"

I get this error:
 Unexpected error:
      <*fmt.wrapError | 0xc0003328c0>: {
          msg: "failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory",
          err: {
              Op: "fork/exec",
              Path: "/usr/local/kubebuilder/bin/etcd",
              Err: 0x2,
          },
      }
      failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory

I tracked this down and realized that I needed to have kubebuilder installed in /usr/local.   Once I did that everything worked fine.

I rechecked all the pre-req docs for the Quickstart for go operators and nowhere could I find it written that you needed to have kubebuilder installed in that exact location for the command to work.  If I missed where it says can you let me know?  Otherwise this should be mentioned somewhere and I am happy to add it.

#### Additional context

I know this issue was encountered before and it was closed and marked resolved a few years ago.  But I didn't see in the quick start or any of its pre-req links that kubebuilder needs to be installed in /usr/local

**Comment by varshaprasad96** [comment]
@bradtopol can you mention the version of SDK being used here? We don't need the KB binary itself for scaffolding projects, but the error looks like the binaries required for running envtest (Kubebuilder assets) are missing. The location for these binaries was changed from `/usr/local/kubebuilder/bin/etcd` to an os specific dir and we are setting the location of KB assets [here](https://github.com/operator-framework/operator-sdk/blob/836a088eee1195515657fb223cf9274cf6e963ed/testdata/go/v3/memcached-operator/Makefile#L96) (/usr/local/kubebuilder/bin/etcd), so this should not occur.

**Comment by bradtopol** [comment]
Hi @varshaprasad96 I thought I was running of master but it I did an operator-sdk version and it looks like I'm picking up and old version.   So I'm thinking thats my issue.   I think we can close this.  Thanks for pointing me in the right direction!
