### ISSUE TITLE
No status descriptor error on empty status

### ISSUE THREAD

**Issue by mshitrit** [operator-framework/operator-sdk#5548]
#### What did you do?
When I run `operator-sdk scorecard bundle`

I'm getting the following error:
 
**"ERROR" poisonpillremediationtemplates.poison-pill.medik8s.io does not have a status descriptor**

Here is how the status code looks like
```
// PoisonPillRemediationTemplateStatus defines the observed state of PoisonPillRemediationTemplate
type PoisonPillRemediationTemplateStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file
}
```

Since the PoisonPillRemediationTemplateStatus has no fields I'm unable to add  CSV markers.

I've tried removing it but getting the following error:

```
[mshitrit@fedora poison-pill]$ make bundle
/gitRepos/forked/medik8s/poison-pill/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
./bin/operator-sdk generate kustomize manifests -q
FATA[0000] Error generating kustomize files: error getting ClusterServiceVersion base: error generating ClusterServiceVersion definitions metadata: no status found for type PoisonPillRemediationTemplate 
make: *** [Makefile:165: bundle] Error 1
```
I suspect that it was added in the first place just to resolve this error.

#### What did you expect to see?
I'm expecting either not to have scoreboard errors on an empty status or for it not to be mandatory or to have another way to resolve this.

#### What did you see instead? Under which circumstances?

Either
**"ERROR" poisonpillremediationtemplates.poison-pill.medik8s.io does not have a status descriptor** 
on `operator-sdk scorecard bundle`

or an 

```
[mshitrit@fedora poison-pill]$ make bundle
/gitRepos/forked/medik8s/poison-pill/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
./bin/operator-sdk generate kustomize manifests -q
FATA[0000] Error generating kustomize files: error getting ClusterServiceVersion base: error generating ClusterServiceVersion definitions metadata: no status found for type PoisonPillRemediationTemplate 
make: *** [Makefile:165: bundle] Error 1
```
when trying to remove the status.

#### Environment

**Operator type:**
Poison Pill 
Repo: https://github.com/medik8s/poison-pill/tree/release-0.3

/language go

**Kubernetes cluster type:**

OpenShift cluster

`$ operator-sdk version`
operator-sdk version: "v1.17.0-1-g836a088e", commit: "836a088eee1195515657fb223cf9274cf6e963ed", kubernetes version: "v1.21", go version: "go1.17.6", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)
 go1.17.6 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v0.21.0-beta.1", GitCommit:"96e95cef877ba04872b88e4e2597eabb0174d182", GitTreeState:"clean", BuildDate:"2021-12-15T01:45:40Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0+60f5a1c", GitCommit:"a9d041aef96a6942cb969df17e698d5564455b03", GitTreeState:"clean", BuildDate:"2022-01-14T05:45:57Z", GoVersion:"go1.17.2", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (0.21) and server (1.23) exceeds the supported minor version skew of +/-1

**Comment by camilamacedo86** [comment]
It shows for me that we need to check:
Should the error occur when the status is not provided? Is the status mandatory? Is the marker not used correctly?

**Comment by phantomjinx** [comment]
> It shows for me that we need to check: Should the error occur when the status is not provided? Is the status mandatory? Is the marker not used correctly?

Also that an empty status is ok to include but does not trigger the scorecard fail?

**Comment by phantomjinx** [comment]
This is an example of an empty Status from our CRDs:
https://github.com/apache/camel-k/blob/main/pkg/apis/camel/v1/camelcatalog_types.go#L76

**Comment by varshaprasad96** [comment]
The outcome of the discussion was to have a flag that allows users to opt-in and run a test if needed.

**Comment by camilamacedo86** [comment]
Hi @varshaprasad96, @theishshah 

> The outcome of the discussion was to have a flag that allows users to opt-in and run a test if needed.

What do you mean with a flag? What does this flag?

**Let's check the error:**

We have the scorecard test olm-status-descriptors-test which has the purpose to ensure that all specs defined in the status have a description. Then, we have here a scenario where the user/author does not define any spec for the status. In this way, he cannot add a description for something that does not exist.

So, it seems that the validator should not return an error and that is a bug.

c/c @jmrodri

**Comment by varshaprasad96** [comment]
@camilamacedo86 If I remember right, the discussion was that these scorecard tests are optional. If a user feels that their CRD need not be tested for status descriptors, they should not run this test at all. These are good practices, and if the user decides otherwise, its uptown them to skip the test. cc: @theishshah - pl feel free correct me if I'm wrong.
The introduction of flag is for the exact same reason. Having a flag would let the user run this test or skip it if they want.

**Comment by camilamacedo86** [comment]
Hi @varshaprasad96, 

All scorecard tests are configured via https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml#L58-L67

So, a user can remove the image from the config and that is how someone can enable/disable or indeed add custom scorecard tests. In this way, adding flags for this feature does not seems to make sense. 

Therefore, it does not solve the bug. Why we cannot only : 

```
if hasSpecDefined for the CRD {

    check if has a descriptions and fail if not

} // Otherwise do nothing
```

**Comment by camilamacedo86** [comment]
Hi @mshitrit,

Could you also please let us know why your CRD does not implement a status in this scenario for you have no descriptors?

**Comment by camilamacedo86** [comment]
Hi @mshitrit, @phantomjinx,

Could you also please let us know why your CRD does not implement a status in this scenario for you have no descriptors? Are not your CRD case under the scenario:

> All objects that represent a physical resource whose state may vary from the user's desired intent SHOULD have a spec and a status.

**Comment by phantomjinx** [comment]
Hey @camilamacedo86

For camel-k's perspective, we have 6 CRDs of which 5 have populated status structs. The 6th (pointed to above) has a status struct but currently no properties. Maybe on time it will but since it does not change state, such properties have not been required.

Therefore,  in my opinion the error in the failing test is not correct as, by definition,  there cannot be any descriptors if there are no properties. A warning to the effect of "you have an empty status" would make more sense, although it really is a design decision of the project and only a convention of the k8s spec, rather than a requirement.

The suggestion above of `if len(spec.props) > 0) { check-prop-desc)` seems most appropriate, IMHO.

**Comment by camilamacedo86** [comment]
Hi @varshaprasad96 @theishshah, 

I am proposing a solution for this one  https://github.com/operator-framework/operator-sdk/pull/5940
IMO it is a bug and we should be sorted it out as proposed in this PR.

**Comment by mshitrit** [comment]
Hi @camilamacedo86 ,
For Poison Pill, I suspect that the status is not needed in the CRD. 
I'm pretty sure it was added in order to avoid the error we got when omitting it (see [here](https://github.com/operator-framework/operator-sdk/issues/5548#issue-1138684531)).
