### ISSUE TITLE
Problem of AWS dependency to use operator SDK

### ISSUE THREAD

**Issue by ar-bella-jeong** [operator-framework/operator-sdk#5562]
## Type of question

Open question

#### What did you do?
Our system is consisted of AWS resources such as EKS, ECR and so on.
I plan to use Operator SDK to develop k8s operators because it is already working like kubebuilder especially in case of go based operator.
However, unfortunately ECR provides only IAM authentication to make the authorization token, Operator sdk provides only CA authentication method to use private image registry. That's why I can't  use whole solutions in aws environment.

#### What did you expect to see?
I wonder someone uses AWS resources with operator sdk who also uses OLM.
I worry about that we have to use kubebuilder instead of operator sdk due to AWS vendor dependency.
Is there anyone use aws resources with operator sdk? If you know and don't mind, please give me any advice.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**
AWS EKS v1.20

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by jmrodri** [comment]
@ar-bella-jeong have you already done this with kubebuilder? Also, what specifically is failing on `operator-sdk` for you?

**Comment by acornett21** [comment]
@ar-bella-jeong I think you should look at AWS's ACK project [here](https://github.com/aws-controllers-k8s). They have controllers for alot of AWS services. They are available via `helm` and via OLM ie OpertorHub.io and OperatorHub inside of an OpenShift cluster.

**Comment by ar-bella-jeong** [comment]
@jmrodri 
I'm trying to use operator sdk yet. I found the solution ECR credential helper and then I'm testing the solution to use OLM.
https://github.com/awslabs/amazon-ecr-credential-helper

**Comment by ar-bella-jeong** [comment]
@acornett21 
Oh. I saw it at the first time. It might help me use all AWS resources with k8s.
Thanks for the recommendation!
