### ISSUE TITLE
reconcile-period and default value

### ISSUE THREAD

**Issue by jfgosselin** [operator-framework/operator-sdk#5565]
### What is the URL of the document?

(https://sdk.operatorframework.io/docs/building-operators/helm/)

### Which section(s) is the issue in?

Reference for Helm-based Operators

### What needs fixing?

For the  Helm-based Operators you can pass the parameter --reconcile-period but what's the default value ?

Is there a way to set it per CR in the watches.yaml like Ansible ?

**Comment by VenkatRamaraju** [comment]
Hey @jfgosselin,

Thanks for bringing this up.

The default value for the `--reconcile-period` flag is 1m, as indicated [here](https://github.com/operator-framework/operator-sdk/blob/master/internal/helm/flags/flag.go#L60). One way to specify the reconcile period outside of the command line flag (similar to ansible) would be in the CR's annotations like:
```
metadata:
  name: nginx-sample
  annotations:
    helm.operator-sdk/reconcile-period: "5s"
```

However, I realized we are currently ignoring this value that is set in the custom resource's annotations. It's definitely something we should fix, along with adding the relevant documentation. I'll take this up soon.
