### ISSUE TITLE
operators.operatorframework.io.bundle.channel.default.v1 annotation ought to be OPTIONAL 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#5569]
## Bug Report

```
time="2022-02-11T05:06:51Z" level=error msg="error validating format in ../preflight-3031960168/fs: Bundle validation errors: Expecting annotation \"operators.operatorframework.io.bundle.channel.default.v1\" to have non-empty value"
```

#### What did you do?

Tried to build/validate a bundle without the annotation: operators.operatorframework.io.bundle.channel.default.v1

See: [https://github.com/redhat-openshift-ecosystem/certified-operators/pull/486/files#diff-6dd35511658d7b1c202d1add2f8[…]63af05aba09357592c62f764e7eecdR7](https://github.com/redhat-openshift-ecosystem/certified-operators/pull/486/files#diff-6dd35511658d7b1c202d1add2f83a0581863af05aba09357592c62f764e7eecdR7)

#### What did you expect to see?

The bundle check does not fail since it is defined as OPTIONAL at https://github.com/operator-framework/operator-registry/blob/master/docs/design/operator-bundle.md:

> The label operators.operatorframework.io.bundle.channel.default.v1 reflects the default channel an operator should be subscribed to when installed from a registry. This label is optional if the default channel has been set by previous bundles and the default channel is unchanged for this bundle.

#### What did you see instead? Under which circumstances?

```
time="2022-02-11T05:06:51Z" level=error msg="error validating format in ../preflight-3031960168/fs: Bundle validation errors: Expecting annotation \"operators.operatorframework.io.bundle.channel.default.v1\" to have non-empty value"
```

#### Environment

**Operator type:**

 /language go 
 /language ansible 
/language helm

**Comment by camilamacedo86** [comment]
From master the error is:

```
ERRO[0000] error validating format in testdata/go/v3/memcached-operator/bundle: Bundle validation errors: Expecting annotation "operators.operatorframework.io.bundle.channels.v1" to have non-empty value
```

**Comment by camilamacedo86** [comment]
@jmrodri the error came from the check done in https://github.com/operator-framework/operator-registry/blob/master/pkg/lib/bundle/validate.go#L213-L218. 

According to the doc, it should be OPTIONAL, however, I think we need to confirm with the OLM maintainers.
@dinhxuanvu @anik120 do you know if the doc or the code is not accurate in this case? Should the annotation https://github.com/operator-framework/operator-registry/blob/master/pkg/lib/bundle/validate.go#L213-L218 be or not optional?

**Comment by jmrodri** [comment]
@camilamacedo86 how do I verify this? I tried the following commands on that PR:

`operator-sdk bundle validate 2.0.4`

and

`operator-sdk bundle validate  --select-optional name=community 2.0.4`

What command do I run to get the error you are exhibiting?

**Comment by jmrodri** [comment]
You will get this error if the channel is set to an empty string `""`. You either have to omit the annotation OR set it to a valid value.

**Comment by camilamacedo86** [comment]
Hi @jmrodri, 

The documentation describes that it should be OPTIONAL.
So, what I was expecting here would be:
- Check if the option should or not be optional
- If the doc is right that we articulate the fix
- if the doc is wrong could we articulate a change on there

Did we check it out and the conclusion was that the doc is wrong or should we re-open this one?

**Comment by arewm** [comment]
While my issue is related, I think that the one that I opened is caused because the `operator-sdk` version is old (`1.0.1`). Upgrading to the latest version _appears_ to fix _my_ issue -- it no longer injects an empty string into the default channel.
