### ISSUE TITLE
Error: failed to initialize project: unable to scaffold with "base.go.kubebuilder.io/v3": exit status 2

### ISSUE THREAD

**Issue by shibumi** [operator-framework/operator-sdk#5582]
## Bug Report

I installed Go on my Fedora 35, downloaded the operator-sdk binary from Github and tried creating my first operator via:

operator-sdk init --domain example.com --repo github.com/shibumi/my-first-operator 

#### What did you do?

```
sudo dnf install go
mkdir -p $HOME/bin
cd $HOME/bin
url "https://github.com/operator-framework/operator-sdk/releases/download/v1.18.0/operator-sdk_linux_amd64" -Lo operator-sdk
cd $HOME
git clone github.com/shibumi/my-first-operator # it is empty
operator-sdk init --domain example.com --repo github.com/shibumi/my-first-operator 
```

#### What did you expect to see?

I expected a successful first initialization

#### What did you see instead? Under which circumstances?

Instead I see Go errors:
```
❯ operator-sdk init --domain example.com --repo github.com/shibumi/my-first-operator                         
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.11.0
# sigs.k8s.io/json/internal/golang/encoding/json
../go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
../go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
Error: failed to initialize project: unable to scaffold with "base.go.kubebuilder.io/v3": exit status 2
```

#### Environment

**Operator type:** Go

**Kubernetes cluster type:** None yet.

`$ operator-sdk version`

operator-sdk version: "v1.18.0", commit: "c9c61b6921b29d731e64cd3cc33d268215fb3b25", kubernetes version: "1.21", go version: "go1.17.7", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.16.14 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b3b92b2", GitCommit:"b3b92b2", GitTreeState:"clean", BuildDate:"2021-07-23T00:05:28Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: getting credentials: exec plugin didn't return a token or cert/key pair

#### Possible Solution

I don't know

#### Additional context

None

**Comment by shibumi** [comment]
Workaround:

export PATH=/home/crebisch/sdk/go1.17.7/bin:$PATH

**Comment by ZoeShaw101** [comment]
Got same error here.

**Comment by kkumarDMS** [comment]
I am also got same error here
