### ISSUE TITLE
Reconcile period CLI flag for Ansible operators not working

### ISSUE THREAD

**Issue by VenkatRamaraju** [operator-framework/operator-sdk#5594]
#### What did you do?

Used the `--reconcile-period` flag while running an Ansible-based operator. 

#### What did you expect to see?

Reconciliation in the specified intervals of time.

#### What did you see instead? Under which circumstances?

Reconciliations do not get requeued.

**Operator type:**

/language ansible

#### Possible Solution

[Here](https://github.com/operator-framework/operator-sdk/blob/master/internal/cmd/ansible-operator/run/cmd.go#L226), it looks like _only_ the watches reconcile period is used in the controller. The reconcile period from the CLI flag (`f.reconcilePeriod`) does not get used at all.

Fix: Check for both `f.reconcilePeriod` and `w.reconcilePeriod`.

#### Additional context

I just wanted to make sure that this wasn't intentional. The fix for this would follow the same precedence order for the reconcile period speciication that was [discussed](https://github.com/operator-framework/operator-sdk/pull/5585#discussion_r823223775) for Helm: CLI flag < `watches.yaml` < CR annotations.

**Comment by varshaprasad96** [comment]
@VenkatRamaraju Curious, on whether this was intentional by design or bug? Hybrid Helm does not accept `reconcilePeriod` from command line either, so if this PR was made to be in sync with Helm (present in Operator SDK), I would say that may not be the right approach, because eventually we would have to deprecate the specific command line flag from Helm too. If docs specify this in ansible, and it is indeed a bug, then it makes perfect sense to go ahead.

**Comment by VenkatRamaraju** [comment]
@varshaprasad96 although I cannot find an explicit mention of this feature in our Ansible docs, I do see the flag [exposed](https://github.com/operator-framework/operator-sdk/blob/master/internal/ansible/flags/flag.go#L28) from the command line.

```
$ ansible-operator run --help
Run the operator

Usage:
  ansible-operator run [flags]

--reconcile-period duration            Default reconcile period for controllers (default 1m0s)

```

It's noteworthy that the watches reconcile period feature [is documented](https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/building-operators/ansible/reference/watches.md). If that's an indication that the `--reconcile-period` flag wasn't meant to be used (and will eventually be deprecated), then I will close this issue and the corresponding PR. Let me know how we should proceed with this.

**Comment by varshaprasad96** [comment]
Since the flag appears to be a part of the command already, looks like this maybe a bug. It should be fine adding it. Thanks for finding this bug!
