### ISSUE TITLE
Error "unable to retrieve the complete list of server APIs: metrics.k8s.io" when any K8s resource is being created by operator through ansible K8s module.

### ISSUE THREAD

**Issue by subrnath** [operator-framework/operator-sdk#5596]
#### What did you do?

We are trying to deploy a CNF in K8s cluster 1.23.1 with ansible operator from quay.io and following error is coming. This is seen when the metrics-server is installed. If metrics-server is deleted, this error is not seen and all the K8s resources are created fine by the Operator.

_{"level":"error","ts":1646985248.079765,"logger":"proxy","msg":"Unable to determine if virtual resource","gvk":"/v1, Kind=Service","error":"unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: an error on the server (\"Internal Server Error: \\\"/apis/metrics.k8s.io/v1beta1?timeout=32s\\\": the server could not find the requested resource\") has prevented the request from succeeding","stacktrace":"github.com/operator-framework/operator-sdk/internal/ansible/proxy.(*cacheResponseHandler).ServeHTTP\n\t/workspace/internal/ansible/proxy/cache_response.go:97\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2879\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1930"}_

Note 1: This issue is not seen in the previous version of K8s. Issue is coming after upgrade to K8s 1.23.

Note:  In the role used by the operator, metrics.k8s.io is added.

  - apiGroups:
    - metrics.k8s.io
    resources:
    - '*'
    verbs:
    - '*'

#### What did you expect to see?

No error when a k8s resource is created by operator through ansible k8s module.

- name: Create Headless services 
  tags: deploy
  k8s:
    state: present
    definition: "{{ lookup('template', 'app_services.j2') | from_yaml  }}"
    namespace: "{{ ansible_operator_meta.namespace }}"

#### What did you see instead? Under which circumstances?

any ansible task used by the operator through the ansible K8s module, throwing the error.

Issue is seen only when metrics-server is installed in K8s 1.23. If metrics-server is deleted, this issue is not seen.

#### Environment

**Operator type:** Ansible

language ansible. We are using the Operator image from https://quay.io/repository/operator-framework/ansible-operator version 1.18. ansible version 2.9.26.

**Kubernetes cluster type:**

vanilla

`$ operator-sdk version`

NA

`$ go version` (if language is Go)

NA

`$ kubectl version`

1.23.1

#### Additional context

No issue if the K8s version is < 1.23.

**Comment by jmrodri** [comment]
Related kube issue: https://github.com/kubernetes/kubernetes/issues/108657

**Comment by jmrodri** [comment]
I've assigned @theishshah and @asmacdo as they are looking at the downstream related downstream bug.

**Comment by subrnath** [comment]
After upgrading the metric-server image to latest 0.6, problem is fixed.

As per https://github.com/kubernetes-sigs/metrics-server

 
0.6.x	metrics.k8s.io/v1beta1	1.19+
0.5.x	metrics.k8s.io/v1beta1	*1.8+
0.4.x	metrics.k8s.io/v1beta1	*1.8+
0.3.x	metrics.k8s.io/v1beta1	1.8-1.21

We were using the image 0.3 which was not compatible with K8s 1.23.

**Comment by gabe-l-hart** [comment]
We're seeing this issue crop up in a customer cluster that we don't have full authority over, so a client-side fix in the `ansible-operator` would be a great improvement. I'll look at emulating [the helm fix](https://github.com/helm/helm/blob/49819b4ef782e80b0c7f78c30bd76b51ebb56dc8/pkg/action/action.go#L257) for the `ansible-operator`. My first guess on where to fix this is [here in `proxy.go`](https://github.com/operator-framework/operator-sdk/blob/77dd4e2ff165c0317254d55ff01ec1f8d0f1c34a/internal/ansible/proxy/proxy.go#L341).
