### ISSUE TITLE
operator-sdk run bundle is unable to skip tls

### ISSUE THREAD

**Issue by J0zi** [operator-framework/operator-sdk#5598]
#### Describe the problem you need a feature to resolve.

`operator-sdk run bundle kind-registry:5000/operator_testing/aqua:v6.5.2` is unable to run bundle on a local registry due to failing opm:

`https://kind-registry:5000/v2/test-operator/aqua/manifests/v6.5.2\": x509: certificate signed by unknown authority, image \"kind-registry:5000/test-operator/aqua:v6.5.2\": not found`

1. there is a bug calling `opm` with deprecated parameter:

Flag --skip-tls has been deprecated, use --use-http and --skip-tls-verify instead

2. we need https anyway, but registry is local on kind cluster. So sdk could provide an option to ignore certificates.

#### Describe the solution you'd like.

operator-sdk run bundle kind-registry:5000/operator_testing/aqua:v6.5.2 --skip-tls-verify

which will run bundle using https without checking certificates

It will help us implement operator upgrade testing feature. Thank you.

**Comment by J0zi** [comment]
@laxmikantbpandhare what is ETA on this. It is blocking us releasing a new feature - operator update testing for operatorhub.io
Thank you.

**Comment by J0zi** [comment]
@laxmikantbpandhare @joelanford any ETA?

**Comment by laxmikantbpandhare** [comment]
> @laxmikantbpandhare what is ETA on this? It is blocking us releasing a new feature - operator update testing for operatorhub.io Thank you.

@J0zi _ this issue is targetted for 1.20. 1.20 will be released by 27 April.

**Comment by laxmikantbpandhare** [comment]
Fix for this issue is done and merged in SDK. It will be released in the upcoming 1.19 SDK release.
