### ISSUE TITLE
[Feature request] Have a command to rename an existing API and code consuming it

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#560]
What is the best approach to rename an API / CRD + operator's code ?

- I have generated the code of my first API using this command `operator-sdk new spring-boot-operator --api-version=springboot.snowdrop.me/v1alpha1 --kind=SpringBoot`,
- developed the code of the operator and 
- now I would like to rename the API to `pkg/apis/component/v1alpha1` + CRD + ... files

**Comment by lli-hiya** [comment]
+1, I found it to be very hard to manually do this after it was generated using sdk.

**Comment by LiliC** [comment]
@cmoulliard you can for now just do a `sed` to rename it in the code. As far as I am aware there is no command for that in the `operator-sdk`. But if you can change the title of this to turn this question into a feature request instead?

**Comment by cmoulliard** [comment]
Title renamed.

**Comment by riccardomc** [comment]
I'd be also interested in this.

**Comment by aravindhp** [comment]
I also ran into this went wanting to change the `Group` and `Version` of my operator's CRD  operator-framework/operator-marketplace#139. It is also preferable to be able to handle both versions in the same operator allowing code to be shared.

**Comment by hasbro17** [comment]
I'm unsure if the SDK should support rewriting/renaming an existing API and all the associated manifest and controller files that are using that API.
It's much cleaner(although more painful) in my opinion to define a new type and controller and copy over the reconcile loop for the new type.

In any case this isn't on our radar at the moment (and why this was ignored for so long) so proposals are appreciated if this seems to be a common workflow.

**Comment by buffalo1024** [comment]
Met this problem too.
