### ISSUE TITLE
Pass uid as ansible_operator_meta.uid

### ISSUE THREAD

**Issue by venkataramanam** [operator-framework/operator-sdk#5602]
#### Describe the problem you need a feature to resolve.

There are times during an Ansible Operator reconcile, when a k8s resource is created outside of Operator process. In order to help clean-up such resources by making them owned by the custom resource that is being reconciled, we will need to get hold of the `uid` of the custom resource. We can always fetch the custom resource in the Operator reconcile and get hold of the `uid`, but the custom resource might already have been fetched by the SDK and it can pass `uid` as `ansible_operator_meta.uid`. That would save an extra fetch on the custom resource. 

#### Describe the solution you'd like.

Described above as part of problem statement.
Passing the `uid` as `ansible_operator_meta.uid` is an additive change and should not affect any Ansible Operator adopter

/language ansible

**Comment by jberkhahn** [comment]
>when a k8s resource is created outside of Operator process
Don't really understand what you mean by this. If a resource is created outside the operator process, it should be handled by whatever created it, not the operator's controller. Do you have an example of what you mean here?

The only thing like that I can think if is when you create something like a Deployment which has dependent resources, those _should_ be handled by the controller for the Deployment resource.

**Comment by venkataramanam** [comment]
> The only thing like that I can think if is when you create something like a Deployment which has dependent resources, those should be handled by the controller for the Deployment resource.

There are two examples in the usecase that I work on...

1. When a StatefulSet is created, the PVCs that get created from the `volumeClaimTemplates` of StatefulSet are not owned by anyone. The ownerReferences for the PVCs needs to be specified in the `StatefulSet.volumeClaimTemplates`

2. In the CloudPak for Data platform from IBM that I work on, we have a usecase where certain resources like ConfigMap objects get created in a different container which is owned by the platform (triggered via a REST API call from Operator). Those ConfigMap objects which are created outside need to be owned later upon creation  (not really an atomic operation though).
