### ISSUE TITLE
scorecard gives error 'the server has asked for the client to provide credentials'

### ISSUE THREAD

**Issue by sachinmahale** [operator-framework/operator-sdk#5615]
## Bug Report

On our OCP 4.8 environment we are getting below error for scorecard test: 

```
# operator-sdk scorecard bundle
--------------------------------------------------------------------------------
Image:      [quay.io/operator-framework/scorecard-test:v1.4.2](http://quay.io/operator-framework/scorecard-test:v1.4.2)
Entrypoint: [scorecard-test olm-crds-have-resources]
Labels:
        "suite":"olm"
        "test":"olm-crds-have-resources-test"
Results:
        State: fail

        Errors:
                the server has asked for the client to provide credentials ( pods/log scorecard-test-m2jb)
```

We are already logged into ocp but still its throwing this error. Verbose also doesn't show any additional details. 

If we login to another OCP environment it works fine with same command. 

#### What did you do?

Ran scorecard test command 'operator-sdk scorecard bundle' but its giving error 'the server has asked for the client to provide credentials'. 

#### What did you expect to see?

Image:      quay.io/operator-framework/scorecard-test:v1.4.2
Entrypoint: [scorecard-test olm-crds-have-resources]
Labels:
        "suite":"olm"
        "test":"olm-crds-have-resources-test"
Results:
        Name: olm-crds-have-resources
        State: pass

        Log:
                Loaded ClusterServiceVersion: XXXXXXXXXX

#### What did you see instead? Under which circumstances?

        Errors:
                the server has asked for the client to provide credentials ( pods/log scorecard-test-m2jb)

#### Environment

**Operator type:**

language ansible

**Kubernetes cluster type:**

Fyre envrionment
`$ operator-sdk version`

operator-sdk version: "v1.4.2", commit: "4b083393be65589358b3e0416573df04f4ae8d9b", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v0.21.0-beta.1", GitCommit:"96e95cef877ba04872b88e4e2597eabb0174d182", GitTreeState:"clean", BuildDate:"2021-11-15T14:54:31Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6+b82a451", GitCommit:"cefce093e4e5bc9a1916eb5a489ed37c7d467f6f", GitTreeState:"clean", BuildDate:"2022-02-05T06:58:30Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (0.21) and server (1.21) exceeds the supported minor version skew of +/-1

**Comment by camilamacedo86** [comment]
c/c @theishshah could you give a hand on this one?
