### ISSUE TITLE
tests should run against a single test cluster 

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#5621]
Tests currently run on 2 kind clusters, `osdk-test` and `operstor-sdk-e2e`, which use more resources and takes more time. We should probably consolidate these to run in the same cluster.

From @ima1mai:
It seems another reason why Kind test with memcached-molecule-operator was slow is that the test creates another kind cluster osdk-test in addition to the kind cluster operator-sdk-e2e that is used in other test cases. It seems running two kind clusters made execution of the testing slow on my local environment.

**Comment by ryantking** [comment]
This has been resolved by #5653
