### ISSUE TITLE
envtest: Pre-requisite binaries download script URL is broken

### ISSUE THREAD

**Issue by sidharthjs** [operator-framework/operator-sdk#5629]
### What is the URL of the document?
https://v0-19-x.sdk.operatorframework.io/docs/golang/references/env-test-setup/

Commit: https://github.com/operator-framework/operator-sdk/commit/ef73f4ee61d17bae0e63fdde31f98e6b0d5f70bc#diff-59538d93a1102a4f8ef3c0dce716b7ba3f81894434134895d1a40dd1cbeba2fcR13

### Which section(s) is the issue in?
Installation prerequisites

### What needs fixing?
The URL of the script which downloads the binaries to /testbin directory is broken. The URL returns 404.

**Comment by kensipe** [comment]
@sidharthjs thanks for the report!... it turns out that v0.19 is old and not supported any longer.   This report resulted in a to-do centered around documentation... so again thanks!.   I'm closing for now, but if you feel something was missed or not as expected... please reopen.
