### ISSUE TITLE
Use commit operator-sdk was built from to lock in vendor 

### ISSUE THREAD

**Issue by LiliC** [operator-framework/operator-sdk#568]
Currently when installing the `operator-sdk` from master and when you create a new project the lock in vendor is set to the latest release. Instead, it should use the commit the operator-sdk was built from in the first place to lock the vendoring of the operator-sdk imports, as the user wanted to use the features of master anyways. At least that is what I was expecting.

**Comment by hasbro17** [comment]
@LiliC if you build the operator-sdk from the master it should pin the SDK dependency to the head of the master branch in Gopkg.toml
https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/templates.go#L297-L299

And for a release tag it should pin it to that tag.
https://github.com/operator-framework/operator-sdk/commit/cb89692cdd145f084798749c16baaf44a6e62cac#diff-e35d7b9b13729eab0761345f9ffbf202R299

But yeah if you build from any other commit(that's not a release tag) then it would still use the master branch.

If we pass the commit sha when building the operator-sdk binary then we could generate the Gopkg.toml file to have the sdk checked out to that exact revision. But that would fail if say you're building from a commit on your local branch that's not on the remote. Which is most of the time for PRs. So I don't know if we should do that by default.
