### ISSUE TITLE
Add documentation for Pull request process

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#5685]
What i have in mind is something similar to https://docs.pulpproject.org/pulpcore/contributing/pull-request-walkthrough.html

Specifically, I don't see in our docs that we require 2 approvals to merge.

**Comment by varshaprasad96** [comment]
@asmacdo would be available to help in resolving this issue.

**Comment by varshaprasad96** [comment]
Anyone working on this issue, please contact one of the maintainers to know more about the process. We are here to help!

**Comment by varshaprasad96** [comment]
@jberkhahn are you still working on this?
