### ISSUE TITLE
Problem with "make: *** [generate] Error 127"

### ISSUE THREAD

**Issue by thomassuedbroecker** [operator-framework/operator-sdk#5689]
#### What did you do?

```sh
operator-sdk init --domain myproblemfix.net --repo github.com/myproblemfix/myproblemfix
operator-sdk create api --group myproblemfix --version v1alpha1 --kind Myproblemfix --resource --controller
```

#### What did you expect to see?

No error!

#### What did you see instead? Under which circumstances?

Creates following problem:  _make: *** [generate] Error 127_

```sh
/fixproblem/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
/fixproblem/bin/controller-gen: No such file or directory
make: *** [generate] Error 127
Error: failed to create API: unable to run post-scaffold tasks of "base.go.kubebuilder.io/v3": exit status 2
```

Simply the `bin` directory with the needed `controller-gen`,  `kustomize` and  `setup-envtest` files, wasn't created by operator-sdk commands.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

`$ operator-sdk version`

```sh
operator-sdk version: "v1.19.1", commit: "079d8852ce5b42aa5306a1e33f7ca725ec48d0e3", kubernetes version: "v1.23", go version: "go1.18.1", GOOS: "darwin", GOARCH: "amd64"
```

`$ go version` (if language is Go)

```sh
go version go1.18.1 darwin/amd64
```

`$ kubectl version`

```sh
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5+IKS", GitCommit:"fdfd7e9e0e8243bfb4084651da5d18e7c74dce10", GitTreeState:"clean", BuildDate:"2022-03-17T13:32:26Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

#### Possible Solution

**Copy and past** an existing `bin` directory with the files from an **_existing working_** project to that **_not working project_**.

#### Additional context

No additional context.

**Comment by everettraven** [comment]
I believe this may be because you are using Go 1.18. Currently operator-sdk (and the underlying dependencies such as kubebuilder and controller-runtime) don't have support for Go 1.18. 

I believe there is some work being done to add support for Go 1.18 but I can't say for sure when that will be.

The current workaround is to downgrade to Go 1.17.x.

If you give the workaround a try, please update this issue with the results. Thanks!

**Comment by thomassuedbroecker** [comment]
Hi @everettraven, thanks for your feedback but why following information is available on [brew formula](https://formulae.brew.sh/formula/operator-sdk) ?

The required version of golang for the actual operator-sdk is `go 1.18.1`

<img width="522" alt="operator-problem" src="https://user-images.githubusercontent.com/12815392/165689102-8835fa65-c181-4f6a-9404-99a37a4533c8.png">

**Comment by thomassuedbroecker** [comment]
Hi @everettraven, I created a blog post how it works for me [MAKE: *** [GENERATE] ERROR 127](https://wp.me/paelj4-15y).

**Comment by aairom** [comment]
Having the same issue as @thomassuedbroecker

**Comment by nheidloff** [comment]
Hi team, we like the operator SDK A lot.

Please fix the issue above! The first time experience of the SDK is not good right now.

Thomas, Alain, I and others have built this repo to promote operators: https://github.com/IBM/operator-sample-go The missing bin files are a blocker to get lots of people to build operators right now. We don't want to loose time telling people how to get the missing bin files first but start right away with value like automation of day 2 tasks.

**Comment by camilamacedo86** [comment]
Hi @nheidloff, 

The go 1.18 is not supported yet. This issue does not occur with 1.17. 
See that we are blocked here and we will only be able to provide this support when 1.24 k8s be released as others deps.

**Comment by everettraven** [comment]
@thomassuedbroecker Thanks for pointing out that Homebrew shows go 1.18 as a dependency! I will take a look at what needs to be changed.

**Comment by camilamacedo86** [comment]
Hi @everettraven,

I do not think that we maintain the brew formula. 
But the solution here would make the brew formula use 1.17 instead.

**Comment by everettraven** [comment]
@camilamacedo86 we may not maintain it, but seeing as it is an installation method we support I figured it would likely impact a decent number of our users. 

I found that the formula for operator-sdk can be found here: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/operator-sdk.rb

I am thinking to make a PR to modify the dependency on `go` to be on `go@1.17`.

**Comment by thomassuedbroecker** [comment]
Hi @camilamacedo86  @everettraven ,

thanks for taking care. A **PR** would be great!

From my point of view `brew install operator-sdk` simply should work and handle the right dependencies.

A user shouldn’t not run into any problem, when he follows the awesome simple brew installation that s described in the operator-sdk documentation.

Optimal would be, if the operator-sdk would support to install different versions with brew ;-)

The reason for that is handle the golang dependencies can be challenging, and I loved that all of these was simplify fixed, when I used the simple brew installation of the operator-sdk on macOS. 


_Note:_ By the way it also worked for me with ubuntu with brew here my [blog post](https://suedbroecker.net/2022/03/18/setup-an-operator-sdk-on-ubuntu-in-a-virtual-service-instance/) and the [GitHub project with the bash script](https://github.com/thomassuedbroecker/example-tools-build-container-image/blob/main/scripts/setup-on-ubuntu-vsi-brew-operator-sdk.sh))

**Comment by everettraven** [comment]
PR has been created in the Homebrew/homebrew-core repo here: https://github.com/Homebrew/homebrew-core/pull/100353

@thomassuedbroecker I believe that this should resolve any problems when installing with Homebrew and not having had an existing Go installation. Once we have support for go 1.18 I will make sure to update the formula again

**Comment by nheidloff** [comment]
Nice! Thanks @everettraven and @camilamacedo86 !

**Comment by thomassuedbroecker** [comment]
Awesome! Thanks @everettraven and @camilamacedo86 !

**Comment by everettraven** [comment]
Created a newer PR to resolve some issues I was having with git: https://github.com/Homebrew/homebrew-core/pull/101238

**Comment by everettraven** [comment]
Closing this issue as the PR was merged and should be resolved as of: https://github.com/Homebrew/homebrew-core/commit/7e5afcbb3383815d68167dc14744b424acb0706e
