### ISSUE TITLE
Issue triage/grooming process audit

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#5690]
## Requirements
- avoid an infinitely growing backlog of no-longer-relevant issues
- issues that are not being actively worked on should be unassigned so anyone can pick them up

Just a placeholder for now, more to come :)

**Comment by everettraven** [comment]
Here are some of my thoughts on this:

---

### Issue Assignment
Issues should only be assigned if someone speaks up that they would like to take the issue (either during triage or on the GitHub issue itself)

If all issues are assigned, this could deter potential contributors. In my experience it is common to search for issues by filtering by labels and assignee. If an issue is already assigned it is often considered that the assignee is already (or will soon) be working on changes to resolve the issue.

### Labels
I feel as though we already make a good use of labels, however we could add more to make issues even more descriptive at a glance.

Suggestions:
- implementing labels that represent an estimate of how long it may take to resolve an issue. (EX: complexity/M)
  - This would help maintainers with Jira integration by having a predetermined scale of tag estimate -> story points estimate
  - This would help potential contributors determine whether they have the bandwidth to commit to working on an issue

- implementing labels that signify that an issue needs to be re-triaged. This could be based on a time cycle like is currently implemented for marking issues stale.
  - This would prevent issues from sitting around in the backlog for forever by them being brought back up in triage every so often.
  - Ideally if an issue has been floating around long enough it could be closed

--- 
 
@asmacdo @ryantking what do you think?

**Comment by asmacdo** [comment]
A few minor suggestions, but this is fantastic thanks @everettraven 

> implementing labels that signify that an issue needs to be re-triaged. 

Another option: the bot could simply remove the milestone rather than close this issue. This can also be done by hand (that's how I trigger a discussion for triage today.) Milestone and labels both require `triage` permissions, so it should basically be equivalent. It would also be nice to preconstruct some queries like goodfirstissue+unassigned and add links to contributor pages.

> This would help maintainers with Jira integration by having a predetermined scale of tag estimate -> story points estimate

+1. 
ihink it will be helpful for anyone picking any issue, especially volunteers. For anyone unaware, the Red Hat folks are making an effort to sync Red Hats internal tracker for the Operator-SDK with GitHub. The hope is that this will help the project get more and better feedback by being open-by-default. 


> implementing labels that represent an estimate of how long it may take to resolve an issue. (EX: complexity/M)

How many tiers? Small medium large [huge]?


#### IMO 
These are small enough changes that we could implement them pretty quickly, I suggest we check for consensus at the next community meeting and go ahead with it starting Monday.(please speak up if you have concerns!)

**Comment by everettraven** [comment]
> Another option: the bot could simply remove the milestone rather than close this issue

+1
I like this better than the option I proposed because it removes the milestone and brings it back up for the next triage meeting.

> It would also be nice to preconstruct some queries like goodfirstissue+unassigned and add links to contributor pages.

+1
I agree that this could be incredibly helpful for potential contributors

> How many tiers? Small medium large [huge]?

I am thinking something along the lines of (all estimates being if you dedicated time only to the issue):
  - XS (extra-small) -> likely can be done within the span of a few hours
  - S (small) -> likely can be done in ~ 1 day
  - M (medium) -> likely can be done in ~ 3 days
  - L (large) -> likely can be done in ~ 1 week
  - XL (extra-large) -> will take a significant amount of time (would likely need deeper discussion)
  
I am by no means hard set on the above timings for approximation and think the actual amounts would need to be determined during a community meeting.
