### ISSUE TITLE
Does sdk.Update(object) supports a k8s list

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#570]
Does sdk.create(object) supports a k8s list ?
When I execute this code 

```
err = sdk.Update(obj)
```
I get this error 

```
error syncing key (my-spring-app/my-spring-boot): failed to get name for object: object does not implement the Object interfaces 
```

as there is no namespace defined for the k8s's list and it can't be specified using this code

```
// Define the namespace for the object
if metaObject, ok := obj.(metav1.Object); ok {
	metaObject.SetNamespace(namespace)
}
```

![screenshot 2018-10-04 14 58 49](https://user-images.githubusercontent.com/463790/46482010-f28bdc80-c7f4-11e8-870e-524f592d30a8.png)

**Comment by LiliC** [comment]
@cmoulliard Can you paste a bit more of the code where you call `sdk.Update(obj)`. What kind of an object are you trying to update?

Also you mentioned in the title you are interested in `Create` but mention `Update` in the description of the issue.

**Comment by shawn-hurley** [comment]
I do not believe that any of the clients that we use support update/create/patch on a List type of object. (List objects do not have ObjectMeta). I believe that even the controller runtime client will not support this. Can someone double check this understanding?

**Comment by estroz** [comment]
Seems to be resolved, closing.
