### ISSUE TITLE
config.toml-E file got generated after release process (make prerelease)

### ISSUE THREAD

**Issue by laxmikantbpandhare** [operator-framework/operator-sdk#5713]
## Bug Report

config.toml-E file got generated after the release process (make prerelease)

#### What did you expect to see?

only config.toml file gets generated

#### What did you see instead? Under which circumstances?

both config.toml and config.toml-E file got generated

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`

v1.19.0

`$ go version` (if language is Go)

1.17.9

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"2c6062082e8dbbf36936b35dcc27c6882d3a2f67", GitTreeState:"clean", BuildDate:"2022-01-11T19:37:02Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

#### Possible Solution

Not sure

**Comment by VenkatRamaraju** [comment]
I'll update this issue after `v1.20` gets released.

**Comment by VenkatRamaraju** [comment]
Didn't replicate in v1.21.0 release.
