### ISSUE TITLE
Add more detailed explanation to `operator-sdk run bundle` command docs

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-sdk#5721]
### What is the URL of the document?

https://sdk.operatorframework.io/docs/cli/operator-sdk_run_bundle/

### Which section(s) is the issue in?

Description of the command

### What needs fixing?

There should be a more detailed explanation of the `--index-image` flag and why the `operator-sdk run bundle` command should fail if the bundle already exists in the index image.

#### Additional context

See issue #5710 for more details

**Comment by jmrodri** [comment]
@everettraven this page is auto generated from the CLI help. So whatever we do it will likely need to go into the command itself. https://github.com/operator-framework/operator-sdk/blob/master/internal/olm/operator/bundle/install.go#L48-L57
