### ISSUE TITLE
Improvement for Best Practices single API multiple implementations

### ISSUE THREAD

**Issue by john-a-joyce** [operator-framework/operator-sdk#5732]
### What is the URL of the document?

https://sdk.operatorframework.io/docs/best-practices/best-practices/ 

### Which section(s) is the issue in?

The text "In the case where an API exists but with multiple implementations"

### What needs fixing?

The best practice to follow for "API exists but with multiple implementations" is not clear.   It almost appears as if the response got truncated.   The wording suggests that one should create a no-op operator for that API.   Additionally there doesn't seem to be much in the way of reference implementations for a no-op operator.  So if there are additional references available that might also help.   

#### Additional context

Discuss briefly on #kubernetes-operators slack channel.

**Comment by joelanford** [comment]
The canonical upstream example is `Ingress` and `IngressClass`

The premise is that `Ingress` is just an API. There's no built-in controller for it. The way it starts to get reconciled is by setting its `ingressClassName` (or relying on a default ingress class, as defined by an annotation on exactly one `IngressClass` resource), and then deploying a controller that can lookup its controller name in `IngressClass` objects and then find the `Ingress` objects its supposed to reconcile from there.
