### ISSUE TITLE
Unpin `cryptography ` Python dep for Ansible Operators

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#5739]
We've got this version pinned
https://github.com/operator-framework/operator-sdk/blob/master/images/ansible-operator/Pipfile#L13-L16

It looks like the rust toolkit is available for UBI 8 now, so I think we can start bumping this dep.

Might affect https://github.com/operator-framework/operator-sdk/issues/5619

**Comment by asmacdo** [comment]
This should be pretty easy if anyone wants to pick it up, I'd be willing to coach.

**Comment by asmacdo** [comment]
Hi @rudradevpal thank you for picking this up! 

For this one, you can start by updating the pipfile and then using pipenv to update the .lock file. (Let me know if you need some docs links to figure that out.)

From there, you can use `make image-build ansible-operator` to build the image.

https://github.com/operator-framework/operator-sdk/blob/9762aa24be11521165ebf7568b674146c6a7da32/Makefile#L84

Try out the new image with any ansible-based operator (Memcached tutorial is fine) to make sure it all works. 

Repeat for Ansible 2.11 preview image.

Let me know if you could use any assistance!

**Comment by rudradevpal** [comment]
@asmacdo can you please share docs for 

> pipenv to update the .lock file
> for testing

**Comment by rudradevpal** [comment]
@asmacdo can you please help on this

**Comment by asmacdo** [comment]
Let's unpin for now.

Use pipenv to install dependencies (from the pipfile) into a temp virtualenv, and it should update the lock file.
 https://pipenv.pypa.io/en/latest/

**Comment by asmacdo** [comment]
For building and testing, take a look at the makefile. `make image-build ansible-operator` (also ansible-operator-2.11-preview) will build the images. 

Once the images are building, you should be ok to push a PR and let CI run.

**Comment by varshaprasad96** [comment]
@rudradevpal Would you like still pick up this issue. If not feel free to unassigned yourself.
