### ISSUE TITLE
Update Homebrew Formula when Go 1.18 is supported.

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-sdk#5740]
#### Describe the problem you need a feature to resolve.
At the time of writing, Operator SDK does not support Go 1.18. This resulted in changing the Homebrew Formula for operator-sdk to be dependent on Go 1.17.

#### Describe the solution you'd like.
When Go 1.18 is supported the Homebrew Formula for operator-sdk needs to be updated to have the proper Go dependency.

**Comment by asmacdo** [comment]
Should be good to go on this as soon as https://github.com/operator-framework/operator-sdk/pull/5843/ merges

**Comment by camilamacedo86** [comment]
Hi @everettraven ,

We do not maintain the homebrew formula.

However, when we do the release from master it will work fine because the problem was that homebrew install go 1.18 and SDK and Go 1.18 was not supported yet.

**Comment by everettraven** [comment]
@camilamacedo86 This issue was created here so the maintainers in the homebrew-core repo would allow me to downgrade go to 1.17 when we did not support go 1.18. I am going to link them to this issue when upgrading the homebrew formula to support go 1.18.

**Comment by camilamacedo86** [comment]
That is fine. Thank you for share
