### ISSUE TITLE
is there a way to find the list of k8s objects created by k8s operator when CustomResource created for that operator

### ISSUE THREAD

**Issue by sreenichelikam-hpe** [operator-framework/operator-sdk#5744]
##  i want to get the list of k8s objects created by the operator ?

Basically i want to monitor and send success or failure of the k8s objects created by the operator. So i want to know the list of k8s objects to monitor the state.

**Comment by everettraven** [comment]
@sreenichelikam-hpe I think a way you could do this is to have all objects that the operator creates have a specific label, and potentially add each unique GroupVersionKind to a list. You can then use a k8s client like the [controller-runtime client](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client) or the [client-go dynamic client](https://pkg.go.dev/k8s.io/client-go/dynamic) to get an `unstructured.UnstructuredList` of objects corresponding to a specific GroupVersionKind. 

There may be a way to get a list of objects based on a label without specifying the GroupVersionKind, but if there is I am unaware of it.

I hope this helps a bit!
