### ISSUE TITLE
Execute commands in a pod to outside

### ISSUE THREAD

**Issue by caatclaudia** [operator-framework/operator-sdk#5757]
## Context
I'm creating a Kubernetes operator, through Ansible, that allows me to monitor the node's state from a Kubernetes Cluster, namely that allows me to understand the CPU and disk state of the same. For this, my main.yml file executes the following commands:

```
- name: Verify CPU Usage
  shell: "kubectl top node | awk '{ sum+=$3} END {print sum}'"
  register: XXXX
                  
- name: Verify Memory Usage
  shell: "kubectl top node | awk '{ sum+=$5} END {print sum}'"
  register: XXXX
```

This file runs correctly when I run the following commands:
```
make install
kubectl create namespace <NAMESPACE>

kubectl config set-context --current --namespace=<NAMESPACE>
ansible-operator run local

kubectl create -f config/samples/<FILE NAME>.yaml -n <NAMESPACE>
```

However when I use the commands, the pod cannot execute the commands correctly, as it does not show output for these commands. 
```
make docker-build docker-push IMG=<DOCKER USER>/<REPOSITORY>:latest
make deploy IMG=<DOCKER USER>/<REPOSITORY>:latest
kubectl get deployment -n <NAMESPACE>
kubectl create -f config/samples/<FILE NAME>.yaml -n <NAMESPACE>
kubectl get pods -n <NAMESPACE>
kubectl logs --follow <POD ID> -n <NAMESPACE>
```

## Question
How can I resolve this issue?

**Comment by varshaprasad96** [comment]
@caatclaudia Could you please provide more context on the project and if possible can you link the project repository so that we can run it locally and test it out.

**Comment by everettraven** [comment]
@caatclaudia Without more context what I think is happening is that `kubectl` is not installed in the container that the operator is running in. I think there are a few potential solutions but I am not sure which would work the best without testing locally.

Potential solutions:
1.  Modify the scaffolded Dockerfile to install `kubectl`
2. Run `kubectl` in a sidecar container (some more information on this can potentially be found here: https://kubernetes.io/docs/concepts/workloads/pods/#workload-resources-for-managing-pods)
3. Using something like `curl` to query the API server directly instead of using something like `kubectl` (This Kubernetes doc might be helpful: https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/)

**Comment by caatclaudia** [comment]
Thank you! Here is the folder I am using for the operator: [operator-verify.zip](https://github.com/operator-framework/operator-sdk/files/8703327/operator-verify.zip)

And the commands I used to run the pod were the following:
```
make docker-build docker-push IMG=<DOCKER USER>/operator-verify:latest
make deploy IMG=<DOCKER USER>/operator-verify:latest
kubectl get deployment -n operator-verify-system
kubectl create -f config/samples/cache_v1_hello.yaml -n operator-verify-system
kubectl get pods -n operator-verify-system
kubectl logs --follow <POD ID> -n operator-verify-system
```

Thank you so much for your help!

**Comment by caatclaudia** [comment]
> @caatclaudia Without more context, what I _think_ is happening is that `kubectl` is not installed in the container that the operator is running in. I think there are a few potential solutions but I am not sure which would work the best without testing locally.
> 
> Potential solutions:
> 
> 1. Modify the scaffolded Dockerfile to install `kubectl`
> 2. Run `kubectl` in a sidecar container (some more information on this can potentially be found here: https://kubernetes.io/docs/concepts/workloads/pods/#workload-resources-for-managing-pods)
> 3. Using something like `curl` to query the API server directly instead of using something like `kubectl` (This Kubernetes doc might be helpful: https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/)

Following your feedback, I modified the playbook with the following lines
```
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
```

In the tasks file, I modified it to use ".kubectl"
And I repeated the procedure again, what happens now is, inside the pod I can run the commands:
![image](https://user-images.githubusercontent.com/56655085/168799933-4912e483-952e-4322-96e7-5ac08518b0e1.png)

But when I see the logs of the pod I am not able to see any information
![image](https://user-images.githubusercontent.com/56655085/168800073-4afeba7e-43b7-4b58-a1cd-4453a37f5484.png)

**Comment by everettraven** [comment]
@caatclaudia Would you mind providing the full log output? I made what I believe are the same modifications that you made and it seems like there is an issue with using the `ping` command. I believe that the base image that is used for running an Ansible operator on cluster is based on the Red Hat Universal Base Image (UBI) 8. From what I can tell, the `iputils` package that installs the `ping` command is not provided as a part of the UBI8 image and therefore is not available within the container.

I also noticed that when looking at the detailed logs that it could not find `./kubectl` and I instead had to change it to `/opt/ansible/kubectl`. After getting that working I noticed this error:
```
task path: /opt/ansible/roles/verify/tasks/main.yml:4
changed: [localhost] => {"changed": true, "cmd": "/opt/ansible/kubectl top node | awk '{ sum+=$3} END {print sum}'", "delta": "0:00:00.220553", "end": "2022-05-17 20:15:28.668149", "rc": 0, "start": "2022-05-17 20:15:28.447596", "stderr": "error: Metrics API not available", "stderr_lines": ["error: Metrics API not available"], "stdout": "", "stdout_lines": []}
```
I received this error and my output looked similar to yours, so I wonder if you are running into the same issue. I am using KinD to create my cluster for testing, and I don't believe it has the metrics-server by default. What type of Kubernetes cluster are you running?

To output more detailed logs, you should be able to follow the steps in this doc: https://sdk.operatorframework.io/docs/building-operators/ansible/development-tips/#viewing-the-ansible-logs

I think for the most part the resolution here is just going to be making minor modifications to get all the dependencies you need for your operator installed into the container (whether that is during the building of the image or some other way) and then debugging to resolve any lingering errors that may occur. 

I am happy to help if you run into any further issues, but I think that the next things to try is:
1. Get more verbose Ansible logs enabled
2. Get `ping` working
3. Get metrics server running

**Comment by caatclaudia** [comment]
Thank you for your answer and clarification.

My Cluster Kubernetes is k3s.
I used this base image because I follow a tutorial that used this one. But there is another base image (e.g. that already contains `iputils` package) that you can advise? Thank you for your help and for your time

**Comment by everettraven** [comment]
> I used this base image because I follow a tutorial that used this one. But there is another base image (e.g. that already contains `iputils` package) that you can advise?

I think that the image that should be used is the base image you are using, but you likely just need to make a few Dockerfile modifications. 

@asmacdo @fabianvf Are there any other images that can be used when building an Ansible operator that may include more pre-installed packages?

For installing the `iputils` package on the currently used image, I would probably recommend using a multistage build and changing your current Dockerfile from:
```dockerfile
FROM quay.io/operator-framework/ansible-operator:v1.20.0

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl

COPY requirements.yml ${HOME}/requirements.yml
RUN ansible-galaxy collection install -r ${HOME}/requirements.yml \
 && chmod -R ug+rwx ${HOME}/.ansible

COPY watches.yaml ${HOME}/watches.yaml
COPY roles/ ${HOME}/roles/
COPY playbooks/ ${HOME}/playbooks/
```
to:
```dockerfile
FROM fedora:28 as dep_installer # <-- add this

RUN dnf update -y && dnf install -y iputils && dnf clean all -y # <-- add this

FROM quay.io/operator-framework/ansible-operator:v1.20.0

COPY --from=dep_installer /usr/bin/ping /usr/bin/ping # <-- add this

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl

COPY requirements.yml ${HOME}/requirements.yml
RUN ansible-galaxy collection install -r ${HOME}/requirements.yml \
 && chmod -R ug+rwx ${HOME}/.ansible

COPY watches.yaml ${HOME}/watches.yaml
COPY roles/ ${HOME}/roles/
COPY playbooks/ ${HOME}/playbooks/
```

According to this k3s doc metrics server should be included by default: https://rancher.com/docs/rke/latest/en/config-options/add-ons/metrics-server/

So you are likely good to go on the metrics server side of things, and hopefully the above multistage build helps to get the `ping` command working for you until @asmacdo or @fabianvf can provide a bit more information on alternative images that can be used.

**Comment by caatclaudia** [comment]
Thank you so much. It works!
