### ISSUE TITLE
Additional debug logs from DependentPredicate

### ISSUE THREAD

**Issue by cliles** [operator-framework/operator-sdk#5764]
#### Describe the problem you need a feature to resolve.

When using an ansible-operator I have an issue when my operator starts looping reconciliation due to dependent resource updates. It is difficult to quickly pinpoint the cause. The current debug logging level helps by providing the information as to what dependent resource triggered the update, but there is no verbosity that can be enabled to show the why or delta on that resource from the predicate function.

#### Describe the solution you'd like.

It would be helpful to have the diff between old and new objects printed in debug log level. Maybe some extra verbosity is appropriate, and bonus points to be able to enable/disable it via a CR annotation.

https://github.com/operator-framework/operator-lib/blob/main/predicate/dependent.go#L86

**Comment by jmrodri** [comment]
@cliles what are you currently seeing? What level would you like to see the additional information?

**Comment by cliles** [comment]
Hi @jmrodri!

The current level of debug is at https://github.com/operator-framework/operator-lib/blob/main/predicate/dependent.go#L101

I would like to also see the actual diff output as performed at https://github.com/operator-framework/operator-lib/blob/main/predicate/dependent.go#L98
