### ISSUE TITLE
Make Badrobot work with SDK

### ISSUE THREAD

**Issue by jberkhahn** [operator-framework/operator-sdk#5798]
Hey,

At Kubecon I attended a [talk about operators as a threat vector to cluster security](https://kccnceu2022.sched.com/event/ytpr/tweezering-kubernetes-resources-operating-on-operators-kevin-ward-controlplane?iframe=no). I spoke with Kevin Ward (@wakeward), one of the maintainers on the project, about possibly integrating the tool they built, [BadRobot](https://github.com/controlplaneio/badrobot). This issue is a place to discuss that.

Taking a look at the tool, it looks like the tool currently consumes a single yaml manifest that has been collated from the ones to provision the operator. I wonder if it would be possible to make it work on Bundles, at which point it could be packaged as a Validator, once we have External Validators working.

**Comment by jberkhahn** [comment]
When I say Bundles, I mean the off-cluster artifact that is produced by SDK when you package an operator for OLM, see example [here](https://github.com/operator-framework/operator-sdk/tree/master/testdata/go/v2/memcached-operator/bundle). This is what is hosted on Operator Hub, and what our validators are run against. Due to rukpak it is likely the exact contents of a Bundle is going to change in the future, however.

**Comment by ryantking** [comment]
For reference, here's the very WIP PR on that: https://github.com/operator-framework/rukpak/pull/396/files
