### ISSUE TITLE
Pause and Resume watch/reconcile of custom resource by helm-operator

### ISSUE THREAD

**Issue by sukhil-suresh** [operator-framework/operator-sdk#5803]
#### Describe the problem you need a feature to resolve.

For a particular scenario, we temporarily scale down a deployment (which is part of our product) by updating the replica value to zero in the spec.  However, it seems the helm-operator-controller interferes with this and scales it back up to the replica count set for the operand install.

#### Describe the solution you'd like.

It would be very helpful if the helm controller could temporarily pause reconciliation for a resource and then resume later. Maybe this could be triggered by a `paused` annotation on the resource?

The `operator-lib` project has support for such a feature - https://github.com/operator-framework/operator-lib/pull/60

If such a feature already exists for the `helm-operator`, kindly guide us with the related resource.
 
/language helm

**Comment by varshaprasad96** [comment]
@sukhil-suresh Unfortunately, we don't have this feature in Helm operators. The available set of annotations for Helm operators are here: https://sdk.operatorframework.io/docs/building-operators/helm/reference/advanced_features/annotations/.

**Comment by sukhil-suresh** [comment]
@varshaprasad96 Thanks for sharing the annotations supported by the Helm operator. 

We have an (untested) workaround for the problem we faced, which involves updating the operand spec to have support for the deployment replica. The assumption is that the helm operator will respect the operand spec value change.

Feel free to close the issue, if needed. I still believe there is value in an annotation that allows pause/unpause of the helm-based operator reconciliation.
