### ISSUE TITLE
 Failed to start container "memcached": Error response from daemon: failed to create shim: OCI runtime create failed

### ISSUE THREAD

**Issue by kavyamani596** [operator-framework/operator-sdk#5812]
Hello,

So I tried deploying the memcached operator, instead of pushing the image ,I build it locally and tried to use it for getting up the container, but when I apply the /config/samples/cache_v1alpha1_memcached.yaml file,
It has problem running the containers.

NAME                                READY   STATUS              RESTARTS   AGE
memcached-sample-85c7664985-nq7ql   0/1     RunContainerError   0          15s
memcached-sample-85c7664985-qpcv7   0/1     RunContainerError   0          15s
memcached-sample-85c7664985-sxhk2   0/1     RunContainerError   0          15s

when I describe the pod, I see this

Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  25s               default-scheduler  Successfully assigned default/memcached-sample-85c7664985-nq7ql to clustervm
  Normal   Pulled     7s (x3 over 23s)  kubelet            Container image "example.com/memcached-operator:0.0.1" already present on machine
  Normal   Created    7s (x3 over 23s)  kubelet            Created container memcached
  Warning  Failed     7s (x3 over 23s)  kubelet            **Error: failed to start container "memcached": Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "memcached": executable file not found in $PATH: unknown**
  
 
So without building the image, when I apply the file, it pulls the image from dockerhub which is https://hub.docker.com/_/memcached/
memcached                                              1.4.36-alpine   e36e3b0dc88c   4 years ago     6.91MB

when I exec-ed into the pod of this I was able to see memcached under /usr/local/bin/memcached

but I was not able to see the same in the running container of the image I created.

Let me know what is missed in the code for this

Thank you.

**Comment by jberkhahn** [comment]
So, it looks like you're trying to deploy the regular memcached docker image - which is just a container that has memcached in it, not intended to be an operator controller. You need to build your operator image and either host it on an image registry like Docker Hub or upload it to the cluster manually before deploying your operator.
