### ISSUE TITLE
ansible-operator reconcile-period options are not documented

### ISSUE THREAD

**Issue by cliles** [operator-framework/operator-sdk#5837]
### What is the URL of the document?

Mentioned already briefly at: https://sdk.operatorframework.io/docs/building-operators/ansible/development-tips/
Should be also added in detail somewhere under: https://sdk.operatorframework.io/docs/building-operators/ansible/reference/advanced_options/

### Which section(s) is the issue in?

#annotations-for-custom-resource

### What needs fixing?

The recent behavior change for reconcile-period as introduced in PR#5600 is not documented. It was not documented in the changelog for 1.19.0 and is not documented on the doc site either.

Please add documentation around the 3 ways to set reconcile-period, the order of precedence they are applied, and the default value(s). It would be helpful to provide examples as well.

#### Additional context

https://github.com/operator-framework/operator-sdk/pull/5600
https://github.com/operator-framework/operator-sdk/releases/tag/v1.19.0
https://github.com/operator-framework/operator-sdk/issues/5780

**Comment by VenkatRamaraju** [comment]
Hi @cliles,

Thanks for bringing this up. I agree, we should have documented this for Ansible when the change went in. We have a [document](https://sdk.operatorframework.io/docs/building-operators/helm/reference/advanced_features/annotations/#helmsdkoperatorframeworkioreconcile-period) for Helm that explains the precedence. I will add a similar document for Ansible.
