### ISSUE TITLE
Unable to identify where is the error with the lint checks implemented on the Ansible projects

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#5838]
## Bug Report

See:

```
Warning: [indentation] wrong indentation: expected 12 but found 14
Warning: [indentation] wrong indentation: expected 12 but found 10
Error: [trailing-spaces] trailing spaces
Error: [trailing-spaces] trailing spaces
Error: [trailing-spaces] trailing spaces
Error: [trailing-spaces] trailing spaces
Warning: [indentation] wrong indentation: expected 12 but found 14
Warning: [empty-lines] too many blank lines (1 > 0)
ERROR: Lint failed: Command 'set -e
An error occurred during the test sequence action: 'lint'. Cleaning up.
yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" .
' returned non-zero exit status 1.: Command 'set -e
--> Scenario: 'default'
yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" .
' returned non-zero exit status 1.
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
--> Scenario: 'default'
```

#### What did you do?

Changes in the scaffold and tested it with default molecule tests scaffolded for advanced molecule sample

#### What did you expect to see?

Be able to know where is the error `Error: [trailing-spaces] trailing spaces`. What is the file? what is the line?

#### What did you see instead? Under which circumstances?

Only errors and warnings without any info which makes it very harder we are able to sort them out. 

#### Environment

**Operator type:**

 /language ansible 

`$ operator-sdk version`

master

See the ci test with : https://github.com/operator-framework/operator-sdk/runs/6790333018?check_suite_focus=true#step:5:1816

**Comment by varshaprasad96** [comment]
This issue seems to be related to ansible's linter. We would have to check if the linter accepts any arguments to give us a verbose error with filenames and line numbers. If not, the next step would be to open an issue with anisble's linter project and follow up with them.
