### ISSUE TITLE
prevent object delete?

### ISSUE THREAD

**Issue by zetaab** [operator-framework/operator-sdk#584]
Lets say that I have crd foobar.com/v1alpha1. How I can prevent users deleting those objects?

Currently I have code like this
``` 
func (h *Handler) Handle(ctx context.Context, event sdk.Event) error {
	switch o := event.Object.(type) {
	case *v1alpha1.S3user:
		if event.Deleted {
			err := deleteUser(o)
			if err != nil {
				logrus.Errorf("failed to remove user : %v", err)
			}
...
```

However, if the `deleteUser` fail. I have situation that user still exist outside kube cluster, but the object is deleted from cluster. (or should I create it again in kube cluster if it fails?) The only problem is that this Handle is called after the real objects is deleted already?

**Comment by maleck13** [comment]
Couple of ways.
If you want users to be able to delete an object but don't want the object to be removed until you are sure everything is cleaned up, you can use finalizers https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#finalizers

If you want to prevent users from deleting the object at all then RBAC would be the way to go

**Comment by LiliC** [comment]
> Lets say that I have crd foobar.com/v1alpha1. How I can prevent users deleting those objects?

You can recreate those objects once it has been deleted. But as far as I know you can't prevent the user deleting them, well unless you limit the users actions via RBAC, but that needs to be done on cluster level.

> However, if the deleteUser fail. I have situation that user still exist outside kube cluster, but the object is deleted from cluster. (or should I create it again in kube cluster if it fails?)

Not sure I understand the second part of the question, maybe you can give more details on that. 

>  The only problem is that this Handle is called after the real objects is deleted already?

Yes these are triggered by events and by the reconcile time, so depending on what case you reconcile the state, in your case it is indeed when the `event.Deleted` is deleted.

**Comment by joelanford** [comment]
Yes, it sounds like a finalizer is exactly what you need. 

When a new object is created, your handler should add a finalizer to the object. Then, when that object is deleted, Kubernetes will set `metadata.deletionTimestamp`, which you can check for in your handler.

It won't actually delete the object until all finalizers have been removed, so `event.Deleted` will be `false` in this case.

If the deletion timestamp AND your finalizer are present, that's when you'd call your backend. If your backend call succeeds, remove the finalizer. If the call fails, leave the finalizer in place and you'll be able to retry the backend call during the next reconciliation.

**Comment by LiliC** [comment]
@zetaab if you have any other questions, feel free to reopen or open a new issue, closing this one for now.
