### ISSUE TITLE
Create issue and PR templates

### ISSUE THREAD

**Issue by LiliC** [operator-framework/operator-sdk#585]
As discussed before, we should have templates for issues and PRs.

The issues usually fall under one of the 3 categories: bug, feature request, or a question. A template like this would be useful:
```
<!-- Thanks for filing an issue! Before hitting the button, please answer these questions.-->

**Is this a BUG REPORT, QUESTION or FEATURE REQUEST?** (choose one):

<!--

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.

If this is a BUG REPORT or QUESTION, please:
  - Fill in as much of the template below as you can. If you leave out
    information, we can't help you as well.

In both cases, be ready for followup questions, and please respond in a timely
manner.  If we can't reproduce a bug or think a feature already exists, we
might close your issue.  If we're wrong, PLEASE feel free to reopen it and
explain why.
-->

Please provide the following details:

**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* operator-sdk version:

	insert release or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

```

Heavily inspired by other projects, open to suggestions.

**Comment by joelanford** [comment]
Great idea! This looks pretty good to me for an issue template.

Also for reference (I didn't know how github issue and PR templates worked): https://help.github.com/articles/about-issue-and-pull-request-templates/

One feature that caught my eye is support for multiple issue templates. The babel project uses them, and serves as a nice example:
* https://github.com/babel/babel/tree/master/.github/ISSUE_TEMPLATE
* https://github.com/babel/babel/issues/new/choose

Our issue template may be so simple that multiple templates don't make sense, but I figured I'd throw that out there for discussion as well.

@LiliC - Do you have a PR template in mind? If not, happy to help you come up with one!

**Comment by LiliC** [comment]
> One feature that caught my eye is support for multiple issue templates. The babel project uses them, and serves as a nice example:

@joelanford That is great! I will do a PR for this, and we can decide on the wording there, much easier that way I feel.

> @LiliC - Do you have a PR template in mind? If not, happy to help you come up with one!

Can do the PR template in the same PR as well, if you have any ideas for improvement straight away, otherwise I was thinking of including just simple things like `Fixes x` `Closes x` and we can work from there.
