### ISSUE TITLE
Should we define "dependency watchers"?

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#5855]
We have many deps that only get bumped when there is a problem, or when we do an audit. One alternative would be have defined watchers for each dep and bump as soon as we can.

**Comment by camilamacedo86** [comment]
Could you provide an example of dep that we are not watching in the bot?

**Comment by varshaprasad96** [comment]
+1, would be helpful to some examples. There are many cases where we necessarily **not want** to bump deps immediately and wait for some other dependency to start the chain. For example, we don't immediately bump a helm version, till we have a compatible k8s/kb/c-r in place. Also, does the github's dependabot help us here?
