### ISSUE TITLE
Default Memcached sample does work on Openshift and fails with `Error "failed calling webhook`

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#5859]
## Bug Report

By using the go/v3/testdata/memcached-operator to build a new catalog and test it with OLM/Openshift the following error is faced because of webhooks:

```
Error "failed calling webhook "mmemcached.kb.io": Post "https://memcached-operator-controller-manager-service.openshift-operators.svc:443/mutate-cache-example-com-v1alpha1-memcached?timeout=10s": no endpoints available for service "memcached-operator-controller-manager-service"" for field "undefined".
```

#### What did you do?

1) Update the Makefile `IMAGE_TAG_BASE ?= example.com/memcached-operator` to build the images in my registry instead (IMAGE_TAG_BASE ?= cmacedo/memcached-operator)
2) Update the file `config/manager/kustomization.yaml` by replacing `newName: quay.io/example/memcached-operator ` with `newName: cmacedo/memcached-operator` to use by dockerhub registry
3) Update the CSV to use my image `cmacedo/memcached-operator:v0.0.1` so that I can test the operator
4) Build operator/bundle/catalog images:

```
make docker-build docker-push IMG="cmacedo/memcached-operator:v0.0.1"
make bundle-build bundle-push BUNDLE_IMG=cmacedo/memcached-operator-bundle:v0.0.1
make bundle-build bundle-push catalog-build catalog-push
```

5) In an Openshift instance, I create a new source using my test catalog created above and pushed to dockerhub `cmacedo/memcached-operator-catalog`:

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: my-test-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: cmacedo/memcached-operator-catalog:v0.0.1
```
More info: https://k8s-operatorhub.github.io/community-operators/testing-operators/#1-create-the-catalogsource

6) I tried to install the Operator and create a Memcached instance:

<img width="704" alt="Screenshot 2022-06-12 at 11 59 46" src="https://user-images.githubusercontent.com/7708031/173229969-1663f36b-1d26-4330-aa37-49454d12bf57.png">

#### What did you expect to see?

The default sample works successfully on Openshift/OLM without any additional steps

#### What did you see instead? Under which circumstances?

Errors regard then usage of webhooks

#### Environment

**Kubernetes cluster type:** OpenShift 4.8

$ operator-sdk version: master branch

**Comment by camilamacedo86** [comment]
c/ @jmrodri @tlwu2013

**Comment by camilamacedo86** [comment]
@rashmigottipati @varshaprasad96 do you know what are the manual steps to make the sample with Webhooks be installed on OCP or if is not possible?

**Comment by varshaprasad96** [comment]
@camilamacedo86 A few follow up questions:
1. How does the CSV look like? Does it have all the required fields for the deployment of webhook? Here are some details from OLM's end:
https://olm.operatorframework.io/docs/advanced-tasks/adding-admission-and-conversion-webhooks/#defining-conversion-webhooks-in-the-clusterserviceversion

2. The logs state that: `no endpoints available for service "memcached-operator-controller-manager-service"" for field "undefined"`. This seems weird and sounds like a networking issue. `No endpoints available for service` usually occurs when the cluster does not have enough underlying nodes for the service to run. Do openshift clusters have any specific debugging steps for this?

**Comment by camilamacedo86** [comment]
Hi @varshaprasad96,

The test above was made with the sample without changing anything on that.
See the steps in the description, I just create build the operator and bundle and create a catalog to test it on OCP.
Therefore, I would expect that work but it fails.
