### ISSUE TITLE
make target catalog build creating a fbc index

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#5865]
## Feature Request

The catalog-build target is using SQLIndex, see:

```
# Build a catalog image by adding bundle images to an empty catalog using the operator package manager tool, 'opm'.
# This recipe invokes 'opm' in 'semver' bundle add mode. For more information on add modes, see:
# https://github.com/operator-framework/community-operators/blob/7f1438c/docs/packaging-operator.md#updating-your-existing-operator
.PHONY: catalog-build
catalog-build: opm ## Build a catalog image.
	$(OPM) index add --container-tool docker --mode semver --tag $(CATALOG_IMG) --bundles $(BUNDLE_IMGS) $(FROM_INDEX_OPT)
```

https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/Makefile#L229-L232

Could we change this one to create the mock catalog as a helper to test the bundle with OLM using FBC instead?

**Comment by camilamacedo86** [comment]
c/c @Lance @gallettilance

**Comment by rashmigottipati** [comment]
This issue seems to be a duplicate of https://github.com/operator-framework/operator-sdk/issues/5832

**Comment by camilamacedo86** [comment]
So we can close this on @rashmigottipati
