### ISSUE TITLE
Use of overrideValues in watches.yaml in helm operator

### ISSUE THREAD

**Issue by Kanaga13579** [operator-framework/operator-sdk#5873]
## Type of question

General operator-related help 

#### What did you do?

Need to know the use of overrideValues field in watches.yaml

#### Environment

**Operator type:**

 /language helm

**Kubernetes cluster type:**

`$ operator-sdk version`

operator-sdk version: "v1.21.0", commit: "89d21a133750aee994476736fa9523656c793588", kubernetes version: "1.23", go version: "go1.17.10", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.18.3 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

#### Additional context

I would like to know the use of "overrideValues" in watches.yaml. If the values from values.yaml can be overridden by adding the fields in CR spec, then what is the use of adding overrideValues field again in watches.yaml? It would be really grateful if it can be explained with an example. I have already gone through the documentation from https://sdk.operatorframework.io/docs/building-operators/helm/reference/advanced_features/override_values/ .  When "overrideValues" will be preferred over setting the values in CR spec? How is it different from mentioning the values in CR spec? Please elaborate on this.

Thanks!

**Comment by ericdurandsymphony** [comment]
It can be used for example to define values which are common at the cluster level. So that all CRs don't have in fact to define any of those values, as they will be overriden by the operator at deployment.
Then different sets of such override values can be set on different clusters.

**Comment by Kanaga13579** [comment]
> It can be used for example to define values which are common at the cluster level. So that all CRs don't have in fact to define any of those values, as they will be overriden by the operator at deployment. Then different sets of such override values can be set on different clusters.

Okay. Thanks for clearing my doubt @ericdurandsymphony . I know we have an option to set the overrideValues from environment variables. In this case, if the overrideValues changes, will the operator reconcile? or operator reconciles only for the changes in CR spec values?

Thanks!

**Comment by everettraven** [comment]
@Kanaga13579 My understanding is that the `overrideValues` in the `watches.yaml` file are bundled with your operator deployment and are static. In order to change these values you would have to re-bundle your operator and deploy it again. Regarding the CR spec changes, I do believe that this would kick off a reconcile. 

I am going to close this issue, but if you have any more questions feel free to reopen and I will answer as soon as I can. Thanks!
