### ISSUE TITLE
Make install target is broken because try to install the kustomize when it is installed already

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#5875]
#### What did you do?

call make install twice 

#### What did you expect to see?

Not fail and just install the kustomize if that is not installed already

#### What did you see instead? Under which circumstances?

The following error in the second time because the bin is in the dir already

```
$ make install
/Users/camilamacedo86/go/src/guestbook/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- 3.8.7 /Users/camilamacedo86/go/src/guestbook/bin
/Users/camilamacedo86/go/src/guestbook/bin/kustomize exists. Remove it first.
make: *** [Makefile:123: /Users/camilamacedo86/go/src/guestbook/bin/kustomize] Error 1
```
#### Environment

**Operator type:**

 /language go 
/language ansible 
 /language helm 

`$ operator-sdk version`

master

**Comment by camilamacedo86** [comment]
c/c @ryantking

**Comment by jchunkins** [comment]
This seems like the make target for installing kustomize just needs to be changed to this simple bash expression:

```
KUSTOMIZE_INSTALL_SCRIPT ?= "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
.PHONY: kustomize
kustomize: $(KUSTOMIZE) ## Download kustomize locally if necessary.
$(KUSTOMIZE): $(LOCALBIN)
	test -s $(LOCALBIN)/kustomize || { curl -s $(KUSTOMIZE_INSTALL_SCRIPT) | bash -s -- $(subst v,,$(KUSTOMIZE_VERSION)) $(LOCALBIN); }
```

**Comment by jberkhahn** [comment]
TODO: do we need to bump kubebuilder to get this?

**Comment by asmacdo** [comment]
Still need to bump kubebuilder it seems, we updated to 3.5.0, which i assume doesnt have this change @camilamacedo86 ?

**Comment by camilamacedo86** [comment]
@asmacdo you can check that the change was made in the PR linked: https://github.com/kubernetes-sigs/kubebuilder/pull/2774

Therefore, you can see that it is only in master and that we do have not this update here, see our testdata samples: 

https://github.com/operator-framework/operator-sdk/blob/87cdc50247832a53e26b713a2ecab6e2215bdb52/testdata/go/v3/memcached-operator/Makefile#L169-L173

**Comment by camilamacedo86** [comment]
Sorted out.
