### ISSUE TITLE
CR spec overrides the entire key value from Values.yaml in helm-operator

### ISSUE THREAD

**Issue by Kanaga13579** [operator-framework/operator-sdk#5882]
#### What did you do?

I have created a helm operator for an existing chart which watches a CR. I am creating this CR by extending k8s API, through go code. While creating the CR through code, I am just adding some fields under container. Values.yaml have same key values. The CR spec replaces the entire key from Values.yaml. But I want to use some values from Values.yaml under same key. Is it possible to do this?
This is my Values.yaml
-----------------------------
containers:
  - name: image-manager
    tag: 3.0.2_dg300_60_2022-02-25_14-43-31
    cwfqdn: 'https://10.10.92.103:30607'
    cdgid: '2c7851e7-a9ae-4575-b22d-c2c217537cbf'
    env:
    - name: DG_COMPONENT
      value: IMAGE-MANAGER
    - name: DG_HOSTNAME
      value: cdg-1 
-------------------------------
This is my CR spec
-----------------------
apiVersion: cdg.infra.com/v1alpha1
kind: InfraServices
metadata:
  name: infraservices-sample
spec:
  # Default values copied from <project_dir>/helm-charts/cdg-infra/values.yaml
  containers:
  - name:image-manager
    cdgid: 2c7851e7-a9ae-4575-b22d-c2c217537cbf
    cwfqdn: https://10.10.92.103:30607
    tag: 4.0

----------------------------------------
#### What did you expect to see?

I want to access the env variable from Values.yaml when CR spec is deployed

#### What did you see instead? Under which circumstances?

I want to use the fields from CR spec to deploy a container and i have to use the env variable from Values.yaml under same key. Currently it is not possible

#### Environment

**Operator type:**

 /language helm

**Kubernetes cluster type:**

minikube

`$ operator-sdk version`

operator-sdk version: "v1.21.0", commit: "89d21a133750aee994476736fa9523656c793588", kubernetes version: "1.23", go version: "go1.17.10", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.18.3 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by varshaprasad96** [comment]
@Kanaga13579 closing the issue here, since we haven't received a response yet. Please feel free to reopen if this doesn't answer your question.
