### ISSUE TITLE
Ansible operator is munging keys

### ISSUE THREAD

**Issue by larsks** [operator-framework/operator-sdk#5887]
#### What did you do?

I have a CRD that defines properties named `quotaName` and `quotaDefinition`.

#### What did you expect to see?

I expected these keys to be exposed in the corresponding Ansible role as variables `quotaName` and `quotaDefinition`.

#### What did you see instead? Under which circumstances?

The keys have been renamed to `quota_name` and `quota_definition`, which  makes no sense: the original names were perfectly valid Ansible variable names.

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

OpenShift

`$ operator-sdk version`

```
operator-sdk version: "v1.22.0", commit: "9e95050a94577d1f4ecbaeb6c2755a9d2c231289", kubernetes version: "1.24.1", go version: "go1.18.3", GOOS: "linux", GOARCH: "amd64"
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+b93fd35", GitCommit:"3a0f2c90b43e6cffd07f57b5b78dd9f083e47ee2", GitTreeState:"clean", BuildDate:"2022-02-11T05:26:59Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

#### Possible Solution

Stop renaming keys!

**Comment by loganmc10** [comment]
This is mentioned a few places in the docs: https://sdk.operatorframework.io/docs/building-operators/ansible/reference/watches/

You can set ```snakeCaseParameters``` to false in watches.yaml to disable the behaviour you're talking about

**Comment by larsks** [comment]
@loganmc10 thanks, that's helpful. Now that I know what to look for I do see the note in [the tutorial](https://sdk.operatorframework.io/docs/building-operators/ansible/tutorial/), but since the behavior is surprising I would like to see it emphasized (and perhaps added to the [quickstart](https://sdk.operatorframework.io/docs/building-operators/ansible/quickstart/) as well.

I'll try to get around to make a docs pr. Thanks for your help!
