### ISSUE TITLE
Samples - Change the memcached image used in the samples so that we do not need to use RunAsUser

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#5934]
## What is the problem

I cannot run the samples on Openshift

## Why

Because we are setting RunAsUser(1001) therefore, it will not work on OCP

## Proposed Solution

Change the Memcached image: https://github.com/docker-library/memcached/pull/79 ( To have the USER ID define )

OR 

maintain a short Dockerfile that's auto-built with just FROM memcached \n USER 11211:11211 (if it has to be baked into the image itself)

**Comment by camilamacedo86** [comment]
c/c @everettraven

**Comment by camilamacedo86** [comment]
Done a PR to see if we can update the image: https://github.com/docker-library/memcached/pull/79

It was tested locally and the Pod worked successfully: 
> pod/foozjpc-sample-654c75bf8f-fgbvv                1/1     Running   0          115s

**Comment by asmacdo** [comment]
blocked until https://github.com/docker-library/memcached/pull/79 merges, but @camilamacedo86 will keep an eye on it.

**Comment by camilamacedo86** [comment]
I am unable to get the PR https://github.com/docker-library/memcached/pull/79 merged. 

Therefore, the other solution is to maintain a short Dockerfile that's auto-built with just FROM memcached \n USER 11211:11211 (if it has to be baked into the image itself)

Remove the assignment to allow others to work on this one.
Also, I improved the description to make it more clear.
