### ISSUE TITLE
Retrieval of Owned deleted resources fails as the resource is not found

### ISSUE THREAD

**Issue by dacamposol** [operator-framework/operator-sdk#5949]
#### What did you do?

I have defined my setup function as:

```golang
func (r *MyCustomReconciler) SetupWithManager(mgr ctrl.Manager, debugLabelValue string) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&v1alpha1.MyResource{}).
		Owns(&v1alpha1.MyChildResource{}, builder.WithPredicates(
			predicate.Funcs{
				CreateFunc: func(event event.CreateEvent) bool {
					return false
				},
				DeleteFunc: func(deleteEvent event.DeleteEvent) bool {
					return true
				},
				UpdateFunc: func(updateEvent event.UpdateEvent) bool {
					return false
				},
				GenericFunc: func(genericEvent event.GenericEvent) bool {
					return false
				},
			})).
		Complete(r)
}
```

The resource `MyChildResource` gets created as part of the reconciliation cycle of `MyResource`, so I'd like to watch it so in case it gets deleted, the reconciliation cycle of `MyResource` runs again and recreates it.

#### What did you expect to see?

The `Reconcile` method of `MyCustomReconciler` to be executed upon deletion of `MyChildResource`.

#### What did you see instead? Under which circumstances?

The following error on the controller logs:

```json
{
  "level": "error",
  "service": "custom-operator",
  "controllerKind": "MyResource",
  "myChildResource": {
    "name": "test",
    "namespace": "test-namespace"
  },
  "namespace": "test-namespace",
  "name": "test",
  "reconcileID": "db613860-5bee-4092-a45c-e3110850a01e",
  "error": "MyChildResource.example.com \"test\" not found",
  "time": "2022-07-19T12:14:35+02:00",
  "caller": "/Users/dacamposol/development/code/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:326",
  "message": "Reconciler error"
}
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

"Vanilla"

`$ operator-sdk version`

```
operator-sdk version: "v1.22.1", commit: "46ab175459a775d2fb9f0454d0b4a8850dd745ed", kubernetes version: "v1.24.1", go version: "go1.18.3", GOOS: "darwin", GOARCH: "arm64"
```

`$ go version` (if language is Go)

```
go version go1.18.4 darwin/arm64
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:51:36Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```

#### Possible Solution

I understand that the problem is the controller is trying to retrieve the actual object from the K8s cluster upon receiving the delete request.

Is it there any way to apply just the `Owns` method to the request, without needing to attach the actual object to the event?

I have tried as well by using the `Watches` method and providing my own EventHandler, but since the retrieval of the object is performed before, to attach it to the Event itself, there is not much I can do.

**Comment by camilamacedo86** [comment]
Hi @dacamposol, 

All resources which are "children" of your CR and created in its reconciliation should have the owner ref which will be added when you use the method `ctrl.SetControllerReference` [example](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/controllers/memcached_controller.go#L200-L202)

Therefore, you can watch ( and re-trigger the reconciliation ) when any event to change them is raised by using OWNS, see the example: https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/controllers/memcached_controller.go#L224

More info, see the controller-runtime implementation: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/builder/controller.go#L72-L123

**Comment by dacamposol** [comment]
Hello @camilamacedo86,

Thank you for your quick response. I didn't find anything on the documentation regarding that case, so I opened a PR so this is clearly stated in the tutorial (feel free to reject it if you think that these is supposed to be common knowledge).
