### ISSUE TITLE
Add ability to prune unreferenced resources in ansible operators

### ISSUE THREAD

**Issue by fbladilo** [operator-framework/operator-sdk#5957]
## Feature Request

Add the capability to prune non-referenced resources to ansible operator , the need is essentially the same as addressed by :

[Resource Pruning](https://sdk.operatorframework.io/docs/best-practices/resource-pruning/) for Go operators.

#### Describe the problem you need a feature to resolve.

Allow ansible operator users to remove un-referenced resources

#### Reproduce

1. Use ansible operator to deploy an application
2. Have an application spawn jobs/pods without reference
3. Delete watched CR (and watch un-pruned resources leftover)

#### Describe the solution you'd like.

Perhaps a collection that is included by Operator SDK and allows cleaning up by label or similar within operator's namespace.

**Comment by asmacdo** [comment]
@fbladilo Have you tried using finalizers? If so, can you elaborate on why they are insufficient?

**Comment by fbladilo** [comment]
@asmacdo The resources we are trying to delete are actually k8s resources in the watched operator namespace, my understanding of finalizers is to provide a way to perform more complex tasks outside k8s (cleaning up 3rd party APIs , etc). That is the reason I pointed to example of resource pruning helpers in Go documentation in the issue, because the use case falls along those lines.

It is plausible that we could use a finalizer to perform k8s deletion of resources in our own namespace once the CR gets marked for deletion but I don't think that is the best use case for them.
