### ISSUE TITLE
Extend sdk to support additional operations

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#597]
Is it possible to extend `operator-sdk/pkg/sdk` in order to support by example such additional request able to create a subresource for a DeploymentConfig ?

https://goo.gl/uCxqWY
```
// Instantiate takes the representation of a deploymentRequest and creates it.  Returns the server's representation of the deploymentConfig, and an error, if there is any.
func (c *deploymentConfigs) Instantiate(deploymentConfigName string, deploymentRequest *v1.DeploymentRequest) (result *v1.DeploymentConfig, err error) {
	result = &v1.DeploymentConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("deploymentconfigs").
		Name(deploymentConfigName).
		SubResource("instantiate").
		Body(deploymentRequest).
		Do().
		Into(result)
	return
}
```

**Comment by shawn-hurley** [comment]
We are moving closer to using the controller runtime and we will be using their client. You can find the documentation here https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client#Client.

It appears that they also do not have support for subresources besides `/status`.

I am going to close this issue in favor of https://github.com/kubernetes-sigs/controller-runtime/issues/172. We can re-open this feature request depending on the outcome of that issue.
