### ISSUE TITLE
operator-sdk olm install should be able to specify context

### ISSUE THREAD

**Issue by atimgraves** [operator-framework/operator-sdk#5981]
#### Describe the problem you need a feature to resolve.

operator-sdk olm install (and other commands) uses the default context, there doesn't seem to be any clear way to switch to a different context (when for example installing in multiple clusters)

The only solution I have found is to copy the kube config file, change the default context in the copy then run the operator-sdk after setting the KUBECONFIG environment variable run the operator-sdk command which picks up the new context

#### Describe the solution you'd like.
the operator-sdk run command supports the --kubecontext flag, this could be added to the operator-sdk olm (install / upgrade / uninstall)

**Comment by asmacdo** [comment]
Seems reasonable, @atimgraves would you be interested in adding this functionality?

**Comment by atimgraves** [comment]
Hi There
I don't have any experience with coding in go (my background is Java). I'll
have a look, but don't think I have the skills
Thanks, Tim
