### ISSUE TITLE
make docker-build with proxy support

### ISSUE THREAD

**Issue by ric79** [operator-framework/operator-sdk#5990]
#### What did you do?

`make docker-build` does not run properly behind a corporate proxy. I need to pass http_proxy and https_proxy in order to execute `RUN ansible-galaxy... `

#### What did you expect to see?

```
.PHONY: docker-build
docker-build: ## Build docker image with the manager.
        docker build -t ${IMG} --build-arg http_proxy=${http_proxy} --build-arg https_proxy=${http_proxy} \.

```

**Operator type:**

**Kubernetes cluster type:**
minikube

```
$ operator-sdk version
operator-sdk version: "v1.22.2", commit: "da3346113a8a75e11225f586482934000504a60f", kubernetes version: "1.24.1", go version: "go1.18.4", GOOS: "linux", GOARCH: "amd64"

```

**Comment by asmacdo** [comment]
This could be reasonable, but we werent sure how widely this is needed. 

For now, I suggest modifying your Makefile to fit your needs, and if others need to pass custom `docker build` build-args as well please feel free to reopen. Or if you think this would be useful in the FAQ please feel free to open a PR.
