### ISSUE TITLE
Replace tutorial sample to use as base deploy-image/v1-alpha as scaffold

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#5991]
#### Describe the problem you need a feature to resolve.

We have the Golang tutorial and sample which is done by we injecting the code via : https://github.com/operator-framework/operator-sdk/tree/master/hack/generate/samples/internal/go/memcached-with-webhooks

SDK could simplify and improve its maintainability by using the  [deploy.image/v1-alpha](https://master.book.kubebuilder.io/plugins/deploy-image-plugin-v1-alpha.html) plugin as a base and just add the next instructions on top. Therefore, it can also take advantage of any improvement/suggestion that can be made by the community.

Another good point that I can see on this one is that the deploy-image plugin uses conditional status which is our best practice recommendation. In the tutorial/sample, we are creating the status using the node name which does not seems fit to a real use case. 

#### Describe the solution you'd like.

- Update the code to use the plugin instead
- Update the tutorial accordingly 

/language go

**Comment by NikhilSharmaWe** [comment]
I would like to work on it.
/assign

**Comment by camilamacedo86** [comment]
To do this one we will mainly need to: 

**(To update the sample)**

- call the deploy image plugin [here](https://github.com/operator-framework/operator-sdk/blob/master/hack/generate/samples/internal/go/memcached-with-webhooks/memcached_with_webhooks.go#L68-L84)
- pass the Memcached image [here](https://github.com/operator-framework/operator-sdk/blob/master/hack/generate/samples/internal/go/memcached-with-webhooks/memcached_with_webhooks.go#L86-L92)
-  change the inplenetation of [this methocs](https://github.com/operator-framework/operator-sdk/blob/master/hack/generate/samples/internal/go/memcached-with-webhooks/memcached_with_webhooks.go#L97-L101) to remove the code that now is no longer required. 

**(To update the tutorial)**

Then, we need to ensure that the tutorial to explain how to build the Operators using the Memcached sample is also updated accordingly. 

- See that we will update the code example regards to define the specs and status here: https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#define-the-api
- Also we need to update the RBAC permissions here: https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#specify-permissions-and-generate-rbac-manifests
- And we need to add the spect to export the MEMCACHED envvar to run locally here: https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#1-run-locally-outside-the-cluster
