### ISSUE TITLE
Upgrading kube-rbac-proxy is done twice in the upgrade instructions to 1.23.0

### ISSUE THREAD

**Issue by iblancasa** [operator-framework/operator-sdk#6002]
### What is the URL of the document?
https://v1-23-x.sdk.operatorframework.io/docs/upgrading-sdk-version/v1.23.0/

### Which section(s) is the issue in?
There are two sections for `Upgrade kube proxy image gcr.io/kubebuilder/kube-rbac-proxy`: [one to upgrade from v0.11.0 to v0.12.0](https://v1-23-x.sdk.operatorframework.io/docs/upgrading-sdk-version/v1.23.0/#upgrade-kube-proxy-image-gcriokubebuilderkube-rbac-proxy-from-v0110-to-v0120) and [other to upgrade from v0.12.0 to v0.13.0](https://v1-23-x.sdk.operatorframework.io/docs/upgrading-sdk-version/v1.23.0/#update-gcriokubebuilderkube-rbac-proxy-from-0120-to-0130).

### What needs fixing?
The first step (bumping the version to `0.12.0`) can be removed.

**Comment by everettraven** [comment]
Closing as https://github.com/operator-framework/operator-sdk/pull/6003 was merged
