### ISSUE TITLE
What is the difference between cluster mode operator and namespace mode operator ？

### ISSUE THREAD

**Issue by aiyijing** [operator-framework/operator-sdk#6005]
> Generally speaking, the cluster mode operator will watch the CR of allnamespace, 
and the namespace mode/multi namespace mode operator will only watch the CR of 
the specified ns

> In fact, many operators do not just watch a single ns or multiple ns as I understand. 
I found that there is no permission to control components in OLM.

> Therefore, I would like to ask what is the difference between the namespace mode 
and the cluster mode. As an operator developer, how can we use the namespace mode 
in the OperatorHub.

**Comment by everettraven** [comment]
Hi @aiyijing , there are currently 3 different "modes" an operator can be set up with for watching Kubernetes resources:
- All namespaces
    - This means that the operator is configured and expects to have the permissions to watch all necessary resources in all namespaces. This essentially equates to give me permissions to see everything I want to see at the cluster level.
- Single namespace
    - This means that the operator is configured to only watch resources in a single namespace. The operator expects to have similar permissions as the all namespaces configuration but only in a single namespace. This is normally used whenever an operator only needs to perform operations in a single namespace instead of across multiple namespaces or the entire cluster.
- Multi namespace
    - This means the operator is configured to only watch resources in a defined set of namespaces (i.e `foo`, `bar`, and `baz`). Again, the operator expects to have similar permission as the all namespaces configuration but only in the namespaces in which the operator is configured to watch. This is normally used when the operator only needs to operate in a small set of namespaces rather than across the entire cluster or a single namespace

As for how these modes can be configured when developing an Go operator I would recommend taking a look into `controller-runtime`'s `cache` and `manager` packages:
- `cache` package: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/cache
- `manager` package: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager

Here are some links to some examples of each mode being configured for a `controller-runtime` `manager.Manager`:
- All Namespace mode: https://github.com/kubernetes-sigs/controller-runtime/blob/d9593cf31dc001bad45ddd6185e51a8a70977d36/pkg/manager/example_test.go#L37-L51
- Multi Namespace mode: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/example_test.go#L53-L69
- Single Namespace mode: No direct example, but it would be as simple as:
    - Setting the `Namespace` field in the `manager.Options` parameter being passed to the `cache.New` function in the All Namespace mode example
    - Only using a single namespace in the list for the Multi Namespace mode example

In Go projects scaffolded with `operator-sdk` you can configure the `Manager` in the `main.go` file, you can see an example here:
https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/main.go#L71-L89

I hope this helps!

**Comment by aiyijing** [comment]
Oh, thanks

**Comment by everettraven** [comment]
Closing this issue. If you have any other questions, please feel free to reopen the issue!
