### ISSUE TITLE
Go Operator Tutorial fails to start when following the demo when using `master` branch

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-sdk#6008]
#### What did you do?

Followed the [Go Operator Tutorial](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/) steps to create the Memcached Operator.

For the controller I copied and pasted the contents from the `testdata/go/v3/memcached-operator/controllers/memcached_controller.go` file on the `master` branch (docs currently use the `latest` branch but wanted to make sure changes on `master` still worked).

#### What did you expect to see?

When running `make install run`, the operator starts successfully.

#### What did you see instead? Under which circumstances?

The operator fails to start due to a missing package named `github.com/example/memcached-operator/monitoring`
```
test -s /home/bpalmer/testing/issues/GH6006-go-tutorial/memcached/bin/controller-gen || GOBIN=/home/bpalmer/testing/issues/GH6006-go-tutorial/memcached/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2
/home/bpalmer/testing/issues/GH6006-go-tutorial/memcached/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
controllers/memcached_controller.go:37:2: no required module provides package github.com/example/memcached-operator/monitoring; to add it:
	go get github.com/example/memcached-operator/monitoring
Error: not all generators ran successfully
run `controller-gen rbac:roleName=manager-role crd webhook paths=./... output:crd:artifacts:config=config/crd/bases -w` to see all available markers, or `controller-gen rbac:roleName=manager-role crd webhook paths=./... output:crd:artifacts:config=config/crd/bases -h` for usage
make: *** [Makefile:90: manifests] Error 1
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

KinD

`$ operator-sdk version`
```
operator-sdk version: "v1.23.0-5-g76f1a1e1", commit: "76f1a1e1a7742863c992307b36bb8d1c57d0f407", kubernetes version: "v1.24.2", go version: "go1.18.3", GOOS: "linux", GOARCH: "amd64"
```

`$ go version` (if language is Go)

```
go version go1.18.3 linux/amd64
```

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

#### Possible Solution
I believe this bug was introduced by #5972. When following the current Go Operator Tutorial there is no mention made of the `monitoring` library and it is not part of the default scaffolding produced by the `operator-sdk` commands used in the tutorial.

It may best to have the following lines commented out to prevent this error from occurring:
https://github.com/operator-framework/operator-sdk/blob/76f1a1e1a7742863c992307b36bb8d1c57d0f407/testdata/go/v3/memcached-operator/controllers/memcached_controller.go#L36

And:
https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/controllers/memcached_controller.go#L102

It may also be nice to add a description with the commented out lines stating that there is a tutorial for how to enable custom metrics in an operator and a link to the tutorial.

**Comment by camilamacedo86** [comment]
@assafad, could you please help on this one?

**Comment by camilamacedo86** [comment]
I think the @everettraven makes sense, ihmo we can:
a) Comment both lines and add a description on top so that when users copy and past the content following the basic tutorial all will work fine and is clear that both lines are useful only for the custom metrics 
b) We need to have a follow-up tutorial was we have the webhooks one where we will describe how to add custom metrics and we will ask for uncommenting these lines from the sample.

**Comment by everettraven** [comment]
> is that your suggestion either right?

@camilamacedo86 Yes, that is my suggestion :)

**Comment by everettraven** [comment]
#6018 was merged and that should resolve this issue.
