### ISSUE TITLE
ansible-operator reconciliation time interval 

### ISSUE THREAD

**Issue by rayankiy** [operator-framework/operator-sdk#6016]
Hi, 

We are using ansible-operator built out of the version `quay.io/operator-framework/ansible-operator:v1.22.0` and we observe their is a operator reconciliation triggered  after every 9-10 hours intervals .

Is this expected ? 

I found a defect https://github.com/operator-framework/operator-sdk/issues/3397#issuecomment-871076205 where it is mentioned  that every 10 hours default reconciliation kicks in even without any change in Custom Resource (CR) .

Is their a option or flag to control the reconciliation ?

**Comment by jmrodri** [comment]
The `ansible-operator` has a reconcilePeriod built in which defaults to 10 hours: https://github.com/operator-framework/operator-sdk/blob/master/internal/ansible/flags/flag.go#L99

You can read more about reconcile-period here:
https://sdk.operatorframework.io/docs/building-operators/ansible/reference/advanced_options/#ansiblesdkoperatorframeworkioreconcile-period-custom-resource-annotation

**Comment by everettraven** [comment]
Closing this issue with the assumption that @jmrodri 's comment provided the information needed since there has been no follow up questions. If you are still encountering this issue, please feel free to reopen this issue and ping me.
