### ISSUE TITLE
Quarkus Operator SDK version is outdated

### ISSUE THREAD

**Issue by andreaTP** [operator-framework/operator-sdk#6031]
## Feature Request

The Quarkus Operator SDK template generating the project stub seems to be outdated:

```xml
<quarkus-sdk.version>3.0.7</quarkus-sdk.version>
<quarkus.version>2.7.5.Final</quarkus.version>
```

while latest is:
```xml
<quarkus-sdk.version>4.0.1</quarkus-sdk.version>
<quarkus.version>2.12.2.Final</quarkus.version>
```

cc. @metacosm

**Comment by laxmikantbpandhare** [comment]
Let me take a look into it

**Comment by laxmikantbpandhare** [comment]
Raised PR on java-operator-pkugins https://github.com/operator-framework/java-operator-plugins/pull/102

**Comment by andreaTP** [comment]
Thanks @laxmikantbpandhare for redirecting this to the correct project!

**Comment by laxmikantbpandhare** [comment]
This issue raised here is correct. `operator-sdk` release needs to happen for getting those changes available.

**Comment by laxmikantbpandhare** [comment]
Modified milestone to `v1.24.0`

**Comment by laxmikantbpandhare** [comment]
Pointed to most latest now:

```
    <quarkus-sdk.version>4.0.3</quarkus-sdk.version>
    <quarkus.version>2.13.1.Final</quarkus.version>
```

**Comment by laxmikantbpandhare** [comment]
1.25 SDK release will take care of this.

**Comment by laxmikantbpandhare** [comment]
PR for the same: https://github.com/operator-framework/operator-sdk/pull/6044

**Comment by metacosm** [comment]
Note that 4.0.3 is functionally equivalent to 4.0.2, this was just needed to publish more artifacts to better integrate with the Quarkus ecosystem.

**Comment by jmrodri** [comment]
https://github.com/operator-framework/java-operator-plugins/blob/main/pkg/quarkus/v1alpha/scaffolds/internal/templates/pomxml.go#L54-L61
