### ISSUE TITLE
Dependencies.yaml under bundle/metadata

### ISSUE THREAD

**Issue by zohiba** [operator-framework/operator-sdk#6051]
I am trying to install some licensing operator in a different namespace as a dependency when my operator is getting installed.  I found this https://docs.openshift.com/container-platform/4.8/operators/understanding/olm/olm-understanding-dependency-resolution.html#olm-bundle-format-dependencies_olm-understanding-dependency-resolution helpful, but is there a way I can tell this dependency to get installed in a different namespace rather than the same namespace where my operator is getting installed?

**Comment by varshaprasad96** [comment]
Hi @zohiba, this issue seems to be related to Operator Lifecycle Manager's task on resolving dependencies before installing the operator. Could you please raise an issue in https://github.com/operator-framework/operator-lifecycle-manager.
