### ISSUE TITLE
Disable Cache for objects: documentation out-dated

### ISSUE THREAD

**Issue by jolbax** [operator-framework/operator-sdk#6052]
### What is the URL of the document?

[After deploying my operator, I see errors like “Failed to watch ”](https://master.sdk.operatorframework.io/docs/faqs/#after-deploying-my-operator-i-see-errors-like-failed-to-watch-external-type)

### Which section(s) is the issue in?
after-deploying-my-operator-i-see-errors-like-failed-to-watch-external-type

### What needs fixing?
The code provided cannot be applied 
```
ClientBuilder: manager.NewClientBuilder().WithUncached(&imagev1.ImageStreamTag{})
```

My solution was to add 
```
ClientDisableCacheFor:  []client.Object{&imagev1.ImageStreamTag{}},
```

**Comment by varshaprasad96** [comment]
@jolbax Thanks for pointing this issue out. That's right, this is due to the change in controller-runtime where we reverted to using `NewClientFunc` instead of `ClientBuilder` (https://github.com/kubernetes-sigs/controller-runtime/pull/1409). Would you like to submit a PR to fix this documentation?

**Comment by Rahilsiddique** [comment]
hey can you assign this issue to me, I have understood the problem and can fix it, thanks

**Comment by jmrodri** [comment]
@Rahilsiddique any movement on this issue?

**Comment by Rahilsiddique** [comment]
apologies for messing up the last pr, can i create a new pr for this issue ?

**Comment by everettraven** [comment]
Hi @Rahilsiddique sure thing, feel free to close the old PR and open a new one

**Comment by everettraven** [comment]
Fixed as of https://github.com/operator-framework/operator-sdk/pull/6239
