### ISSUE TITLE
be able to manually request a reconciliation [ansible operator]

### ISSUE THREAD

**Issue by jmazzitelli** [operator-framework/operator-sdk#6063]
I asked around, and the consensus seems to be this is not a feature today. If this is possible today, let me know how, and I can retract this enhancement request.

#### Describe the problem you need a feature to resolve.

_<tl;dr>In general, the problem is: if a CR contains dynamic values that when evaluated at different times can produce different values (such as, for example, regular expressions as described below), it would be nice to be able to manually ask the operator to immediately perform a reconciliation, even though nothing changed in the CR.</tl;dr>_

I have an [ansible operator](https://github.com/kiali/kiali-operator) that does not [watch for dependent resources nor reconciles periodically](https://github.com/kiali/kiali-operator/blob/v1.57.0/watches.yaml#L6-L8). So the enhancement request is specifically in regards to ansible operators.

The operator contains a specific feature that allows the user to declare in the CR a list of namespaces that are important to the operand - this list of namespaces supports regex. For example:

```yaml
spec:
  deployment:
    accessible_namespaces:
    - istio-system
    - my-mesh.*
```

This allows the operand to access those namespaces by way of Role resources created by the operator at install time (the rest of the operand is installed by the operator at the same time, as a normal operator would do). So, for example, if I have a set of namespaces `my-mesh1` and `my-mesh2`, and I create a CR with the yaml above, the operator will see those two namespaces (because they match the regex `my-mesh.*`) and create a Role in each of the two namespaces which provides the necessary permissions required for the operand to work.

The problem is: namespaces that the user creates AFTER the operand is already installed are not picked up. Because we do not reconcile periodically (it would be too resource intensive for the operator to continually re-reconcile all the CRs every X seconds), and because we do not watch dependent resources (for legacy reasons), any "my-meshX" namespaces the user creates AFTER the operand is installed and AFTER the CR has been reconciled, those extra my-meshX namespaces will not get the necessary Roles created by the operator and the operand will fail to access those namespaces (even though they should be - the user created them to match the regex precisely because the user wants the operand to process those namespaces).

#### Describe the solution you'd like.

Today, there are already a few ways you can force the operator to immediately reconcile the CR, all have drawbacks I want to avoid.
1. I could scale down the operator deployment, and scale it back up - thus restarting the operator and thus forcing it to re-reconcile all CRs in the system. The drawbacks are twofold: (1) this requires the user to have admin rights (or, at minimum, rights to scale the operator - if installed by OLM, these are high-level admin rights that regular users do not have) and (2) this forces the operator to re-reconcile ALL the CRs in the system - I only want the one CR to be reconciled.
2. I could ask the user to manually update the CR in a trivial way that doesn't alter the config of the operand in any important way. The drawback here is the operator will not reconcile the CR if changes are made to labels or annotations (say, I add a label or annotation, "reconcile: now") nor are reconciliations triggered if I alter or delete the "status" field of the CR (say, via `kubectl patch <CRD name> <CR name> --subresource='status' --type=json -p '[{"op":"remove","path":"/status"}]'`. Through my testing, I have seen reconciliations triggered only when changes are made to the CR `spec` field. So this means the operator will need to support a specific field in `spec` to trigger a reconciliation (e.g. "reconcileNow: true") or I would need the user to change a trivial config (even though it may operationally affect the operand - say, something like, change `spec.logLevel` to `debug` from its current value of `info` (assuming something like `spec.logLevel` is supported by the CRD schema).
3. Turn on watch-dependent-resources and then scale down the operand's Deployment, which will force a reconciliation. The drawback here is I've now taken down my operand's pod - and in the general case, this may not be preferable (for example, maybe the only thing I need the operator to do is create new Roles, which will allow the running pod to obtain additional permissions without having to be taken down). I suppose the alternative is to have the operator create a "dummy" resource (like an empty ConfigMap) which is used solely for the purpose of watching when it disappears which is the trigger to the operator to run a new reconciliation. This is a bit hacky and seems ugly to ask the operator to create a dummy resource solely for this purpose.The second point, however, is, this would force the operator to enable watch-dependent-resources when in some cases we do NOT want the operator to watch dependent resources.

What is the solution I would like? I do not know :) Something that makes it non-intrusive (such as no dummy resources required, and does not require the operator or the operand pod to be restarted) yet easy for a non-admin owner of the CR to do.

Perhaps the best way to do this is by asking the user to add an annotation to the CR:

`kubectl annotate <CRD name> <CR name> ansible.sdk.operatorframework.io/reconcileNow='true'`

The problem with this is - it doesn't seem like the operator sees changes to annotations (at least it doesn't process them - I'm fairly sure k8s watches will report changes to annotations - I suspect the ansible operator SDK is ignoring them, or at least isn't triggering reconciliations on changes to annotations). Perhaps this will require a new setting in `watches.yaml` such as "reconcileOnAnnotationChange: true` or something like that.

/language ansible

**Comment by jmrodri** [comment]
This sounds like a decent idea, but I'm not sure this will ever get implemented. If you feel like this should be a part of the ansible operator and would like to contribute a proposed PR, we can re-evaluate.

**Comment by jmazzitelli** [comment]
Actually, I think this might already be implemented in a recent release. Did I see something where the operator will run a reconciliation if an annotation is changed in a watched resource? "WatchAnnotation" in watches.yaml or something like that? That actually does what I was asking for.

**Comment by jmazzitelli** [comment]
Here: https://github.com/operator-framework/operator-sdk/releases/tag/v1.23.0

`Add an option, WatchAnnotationsChanges, to trigger reconciliations on annotation changes on watched resources.`

https://github.com/operator-framework/operator-sdk/pull/5611

```
This change adds an option watchAnnotationsChanges to ansible watches. When this option is used on a watch, any annotation change will trigger a reconciliation.
```

So if I set WatchAnnotationChanges in watches.yaml, and I add an annotation to the Kiali CR, that will trigger a reconciliation now. Correct?

This is exactly what this issue was asking for, when I say in the description:

```
Perhaps the best way to do this is by asking the user to add an annotation to the CR:
...
The problem with this is - it doesn't seem like the operator sees changes to annotations...
I suspect the ansible operator SDK is ignoring them ...
Perhaps this will require a new setting in watches.yaml such as
"reconcileOnAnnotationChange: true` or something like that.
```

:)
