### ISSUE TITLE
Small typo in the operator output

### ISSUE THREAD

**Issue by bmm-alc** [operator-framework/operator-sdk#6078]
#### What did you do?
there is a typo in the output of the command `make bundle` ("suceessfully" instead of "successfully")

```
time="2022-10-12T14:48:47Z" level=info msg="Creating bundle.Dockerfile"
time="2022-10-12T14:48:47Z" level=info msg="Creating bundle/metadata/annotations.yaml"
time="2022-10-12T14:48:47Z" level=info msg="Bundle metadata generated suceessfully"
```

#### Environment

**Operator type:** I'd say common 

**Kubernetes cluster type:** Irrelevant

`$ operator-sdk version` 1.24.0

#### Possible Solution

edit https://github.com/operator-framework/operator-sdk/blob/735678238f2ce54ecc063265906be856cd3858d4/internal/util/bundleutil/bundleutil.go#L140 to fix the string

#### Additional context

na !

**Comment by laxmikantbpandhare** [comment]
Closing this as fix got merged.
