### ISSUE TITLE
Add possibility to choose podman instead of docker for building golang operator, bundle and catalog image

### ISSUE THREAD

**Issue by stanislavulrych** [operator-framework/operator-sdk#6089]
#### Description

Currently, the docker is used as a build tool for operator images. Other container tools could be used to build the images. Since podman cli has syntax compatible with docker, it could be easily used by just allowing a change of the tool.

- In order to change the container tool for image build, it has to be changed on mulltiple locations in the Makefile. 
- The suggested feature would introduce the Makefile variable CONTAINER_TOOL to allow setting of the container tool for build. 
- The default value of the CONTAINER_TOOL would be docker, hence this feature is backward compatible and does not impact the current usage.

/language go

**Comment by mhrivnak** [comment]
+1. I've had success both doing a find/replace in the Makefile, and installing the `podman-docker` package in fedora, which just creates a shell alias. Either way, the workflows in the Makefile seem completely compatible.

**Comment by everettraven** [comment]
#6090 was created to address this. In the process of creating the PR it was determined that changes upstream in Kubebuilder would need to be made to add conditional logic to run a different set of commands for building multi-arch images when using `podman` instead of `docker`.

@stanislavulrych mentioned trying to take this on in a comment on the PR: https://github.com/operator-framework/operator-sdk/pull/6090#issuecomment-1285578929

**Comment by stanislavulrych** [comment]
@everettraven I am sorry for the delay, I tried to address the issue in kubebuilder, but I am not familiar with the code much, so it will take me more time. I am still interested in the feature.

**Comment by everettraven** [comment]
@stanislavulrych No worries! I was asked during our community meeting to add an update comment so that's all that comment is supposed to be

**Comment by varshaprasad96** [comment]
This seems to be blocked by Kubebuilder. Removing this from milestone and adding to the backlog. If anyone is interested in picking this up, please feel free to assign yourself.

**Comment by redhatrises** [comment]
@everettraven @varshaprasad96 feel free to assign me to it. I will work on getting it into kubebuilder if no one else has.

**Comment by redhatrises** [comment]
Upstream PR: https://github.com/kubernetes-sigs/kubebuilder/pull/3371

**Comment by KevinMGranger** [comment]
It's merged upstream, woo! So what's the next step now?

**Comment by everettraven** [comment]
So it looks like we do have an implementation for the go/v4 plugin in place here but is still in "alpha":
https://github.com/operator-framework/operator-sdk/blob/6a6edfd34ccbd82b7ba6be6f7c07da9d7f764d5c/internal/cmd/operator-sdk/cli/cli.go#L92-L99

When we bump our kubebuilder dependency we need to:
- Update the `go/v4` plugin to be stable (unmark it as alpha)
- Remove the `go/v2` plugin (earlier in the file that contains the code I shared above)
- Mark the `go/v3` plugin as deprecated (earlier in the file that contains the code I shared above)
- Make `go/v4` the default plugin used (if not already)

IIUC the changes made in Kubebuilder, once this is done we should inherit those changes
