### ISSUE TITLE
Numerous Ansible Operator Versions Causes Unexpected Reconcile of Daemonsets

### ISSUE THREAD

**Issue by acornett21** [operator-framework/operator-sdk#6094]
#### What did you do?

We were upgrading an Ansible operator from operator-sdk version 1.14 to the latest version of operator-sdk and Ansible runtime, following the migration/upgrade documentation.

#### What did you expect to see?

I'd expect that following the migration documents that an operator that worked with version 1.14, would work with 1.24.

#### What did you see instead? Under which circumstances?

With the versions of operator-sdk mentioned below one of two things happened
- The pods managed by the `Daemonset` would restart after 60 seconds and never stay running.
- The pods managed by the `Daemonset` would restart after once or twice in a 24 hour period.

I use the word `restart` above to indicate that the controller manager would re-run and re-apply the `Daemonset` Ansible `Tasks`, without any indication of why a reconcile was happening, no matter the log level or verbosity level set on the CR's.

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

OpenShift: 4.8, 4.9, 4.10, 4.11

`$ operator-sdk version` 1.15, 1.16, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24
To add more clarity, if the above operator-sdk range isn't clear, versions 1.17 and 1.18 work perfectly fine.

`$ go version` (if language is Go)

`$ kubectl version`

#### Possible Solution

N/A

#### Additional context

It's worth noting that multiple versions of OpenShift as well as operator-sdk were tested, and all combinations yielded the same results. It is also worth noting that if the `Damenset` is applied manually to the cluster, outside of the operator (there are various CR's in the operator, one that controls the `Deployment` and `Daemenset` and another that just controls the `Deployment`), the `restarting` mentioned above does not happen.

[Here](https://github.com/PaloAltoNetworks/prisma-cloud-compute-operator) is a community version of the base operator that we were experience this issue with, however it was the certified version that resides in a different private fork, that we were updating, but there are no differences in Tasks between the two. I should note that to apply a CR for this operator access tokens to the partners product are needed.

**Comment by bcrochet** [comment]
Assign me please.

**Comment by bcrochet** [comment]
After some investigation, it seems that the role tasks in this particular operator were not idempotent. It seems that what was happening is that when a reconcile occurs, it is applying a yaml for the daemonset causing the daemonset to recreate the pods. When the daemonset is unchanged, and an apply is not even attempted, this behavior no longer occurs.

**Comment by everettraven** [comment]
Closing as per https://github.com/operator-framework/operator-sdk/issues/6094#issuecomment-1293940337
