### ISSUE TITLE
unable to run bundle stored on private repository/registry

### ISSUE THREAD

**Issue by imperialguy** [operator-framework/operator-sdk#6095]
## Type of question

General operator-related help 

## Question
How can I run a bundle stored as a private repo on `quay.io` registry.  

#### What did you do?

On Openshift (crc) cluster:
-  I created a project/namespace called "sample"
-  Created a secret called "quay" in the namespace "sample", and added my quay.io credentials to it
```
oc create secret docker-registry quay --docker-server=quay.io/testproject --docker-username=tester --docker-password=testpassword
```
- Ran the following command on command line:

```
operator-sdk run bundle quay.io/testproject/testrepo:1.0.0 --pull-secret-name quay --namespace sample --skip-tls --skip-tls-verify
```

#### What did you expect to see?

Expected it to pull the bundle image and deploy it in the OSP cluster

#### What did you see instead? Under which circumstances?

Here's the error I see:

```
FATA[0000] Failed to run bundle: pull bundle image: error pulling image quay.io/testproject/testrepo:1.0.0: error resolving name : unexpected status code [manifests 1.0.0]: 401 UNAUTHORIZED
```

#### Environment

**Operator type:**
/language helm 

**Kubernetes cluster type:**

"OpenShift"

`$ operator-sdk version`

operator-sdk version: "v1.23.0", commit: "1eaeb5adb56be05fe8cc6dd70517e441696846a4", kubernetes version: "1.24.2", go version: "go1.18.5", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.17.12 linux/amd64

`$ kubectl version`

clientVersion:
  buildDate: "2022-08-02T07:42:46Z"
  compiler: gc
  gitCommit: 70750898e45ff4a349995b08e1d64a359e4c4880
  gitTreeState: clean
  gitVersion: v1.24.1
  goVersion: go1.18.4
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-08-19T00:38:59Z"
  compiler: gc
  gitCommit: 0a57f1f59bda75ea2cf13d9f3b4ac5d202134f2d
  gitTreeState: clean
  gitVersion: v1.24.0+b62823b
  goVersion: go1.18.4
  major: "1"
  minor: "24"
  platform: linux/amd64

I also added the qua.io credentials to the `pull-secret` secret object in `openshift-config` namespace. I am logged in as `kubeadmin`. What else am I missing here?

**Comment by jberkhahn** [comment]
Hey there,

been working on this and have a solution to allow auth using the default keychain, but we weren't able to get it in in time, so bumping this to 1.27
