### ISSUE TITLE
list all object

### ISSUE THREAD

**Issue by sstarcher** [operator-framework/operator-sdk#611]
I have a use-case where on startup I want to hit a API to get all existing objects from a third party API and I want to get a list of all of the CRs so I can reconcile them.

I was trying to use `err = sdk.List(ns, dashboards)`, but the generated types are pointer receivers and are also missing `GetObjectKind` method to be used as `sdk.Object`.

Is this currently not supported or am I missing something.  I could certainly create my own object to do that, but I would of of expected the generated code to match.

**Comment by shawn-hurley** [comment]
There is no need for you to get all the resources you are watching in the cluster. By default the list watch on set up with do this for you and you will get these events to the reconcile/handler function.

I am a little confused on what dashboards are in the code above. Is this the third party resource? The sdk commands are only for interacting with sdk.Objects which is an interface that defines kubernetes resources. If dashboards does not conform to this interface and is unknown to the cluster then this will not work.

Does that help explain the current state of things?

**Comment by sstarcher** [comment]
@shawn-hurley dashboards is this object defined by me that has the generated methods - https://github.com/sstarcher/newrelic-operator/pull/1/files#diff-54eb37f95035a9e5b4730f3baf297654R20

My specific usecase is I want to take a action on start up and to take that action I need a full list of every resource.

In my cluster CRDs I have resources A, B, C, D.  In the thing I'm managing that is outside of me I have resources A, B, C, X, Y, Z.

Only if I know all of my resources at once can I say that resource X, Y, Z is not managed by the controller to remove those resources.  Hence on startup I would like to be able to get all of the resources so I can do reconciliation.

Do you have a better recommendation?

**Comment by shawn-hurley** [comment]
Ok, so now I think I see the problem you're passing a slice to `sdk.List` is that correct? 

That is not going to be understood by the api, you will need to pass a `List` type. Example: https://godoc.org/k8s.io/api/core/v1#PodList
Or in your case: 
https://github.com/sstarcher/newrelic-operator/pull/1/files#diff-54eb37f95035a9e5b4730f3baf297654R12

**Comment by sstarcher** [comment]
@shawn-hurley ahh perfect let me try that.  Thanks for all of the quick assistance.

**Comment by sstarcher** [comment]
@shawn-hurley similar issue 
```
cannot use list (type v1alpha1.DashboardList) as type sdk.Object in argument to sdk.List:
    v1alpha1.DashboardList does not implement sdk.Object (DeepCopyObject method has pointer receiver)
```

**Comment by shawn-hurley** [comment]
Can you paste the code leading up to the list command? I think that you may need something like

```go
dashboards := &v1alpha1.DashboardList{}
sdk.List(ns, dashboards)
```

This is because of golang and interfaces and pointer receivers I believe

**Comment by sstarcher** [comment]
You are correct that was a dumb mistake on my part.  I'm now getting
```
panic: failed to get resource client for (apiVersion:, kind:, ns:): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(/, Kind=): no matches for kind "" in version ""
```

**Comment by shawn-hurley** [comment]
This is most likely because you have not registered the types with the schema. please see this method: https://github.com/operator-framework/operator-sdk/blob/master/pkg/util/k8sutil/k8sutil.go#L67

and examples: https://github.com/kubernetes/api/blob/master/core/v1/register.go

**Comment by sstarcher** [comment]
It's been added.  The CRD works perfectly fine and I get events etc.  I can create, update, delete so it should be registered correctly 
https://github.com/sstarcher/newrelic-operator/pull/1/files#diff-07473f5a7edfc6cb5e919d36db3d5e0bR35

**Comment by shawn-hurley** [comment]
@sstarcher I am looking through the code that you sent in the last PR, I don't see sdk.List. Is there another place to look to see the call that is failing?

**Comment by sstarcher** [comment]
I took it out due to it failing.  The code was placed in the `func NewHandler` and looks like the following

```
	list := &v1alpha1.DashboardList{}
	err = sdk.List("", list)
	if err != nil {
		panic(err)
	}
```
When ran I get
```
INFO[0000] Go Version: go1.11
INFO[0000] Go OS/Arch: darwin/amd64
INFO[0000] operator-sdk Version: 0.0.6+git
INFO[0000] Metrics service newrelic-operator created
panic: failed to get resource client for (apiVersion:, kind:, ns:): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(/, Kind=): no matches for kind "" in version ""

goroutine 1 [running]:
github.com/sstarcher/newrelic-operator/pkg/stub.NewHandler(0xc00030d9c0, 0x0, 0x0)
	/Users/sstarcher/go/src/github.com/sstarcher/newrelic-operator/pkg/stub/handler.go:24 +0x2d0
main.main()
	/Users/sstarcher/go/src/github.com/sstarcher/newrelic-operator/cmd/newrelic-operator/main.go:30 +0xb1
exit status 2
Error: failed to run operator locally: exit status 1
```

**Comment by shawn-hurley** [comment]
@hasbro17 Do you need to explicitly set the GVK for the resource here?

@sstarcher another thing to keep in mind is that we are moving to controller runtime for the client. This is coming very soon, so please be on the look out.

**Comment by sstarcher** [comment]
@shawn-hurley thanks and appreciate all the great work that is going into the `operator-framework`.  Thanks for answering all of my questions.

**Comment by shawn-hurley** [comment]
Actually @sstarcher you need to set the TypeMeta I believe.

So example is
```go
list := &v1alpha1.DashboardList{
	TypeMeta: etav1.TypeMeta{
			APIVersion: "newrelic.shanestarcher.com/v1alpha1",
			Kind:       "DashboardList",
		},
}
err = sdk.List("", list)
	if err != nil {
		panic(err)
	}
```

**Comment by sstarcher** [comment]
So I think my next issue is I'm trying to do this in `func NewHandler(m *Metrics) sdk.Handler {`, but the register.go is not called yet.  I added the import of the `v1aplha1` to force the register.go to get called first

```
panic: failed to get resource client for (apiVersion:newrelic.shanestarcher.com/v1alpha1, kind:DashboardList, ns:): failed to get resource type: failed to get the resource REST mapping for GroupVersionKind(newrelic.shanestarcher.com/v1alpha1, Kind=DashboardList): no matches for kind "DashboardList" in version "newrelic.shanestarcher.com/v1alpha1"
```

**Comment by shawn-hurley** [comment]
@sstarcher I think that I'm going to close this issue as we moved from using the libraries and methods in the issue. If you're still having issues with the controller-runtime libraries please re-open so we can help.
