### ISSUE TITLE
Using an operator to deploy a complex microservices system

### ISSUE THREAD

**Issue by piotrpersona** [operator-framework/operator-sdk#6111]
## Type of question

General operator-related help

## Question

> Is it recommended to use operator framework to deploy an entire complex system?

I was going through some docs and Youtube videos about the purpose of k8s operators. Most of them says that perfect use case would be to deploy and operate a stateful application such as database or the monitoring system.
I wonder if the operator pattern can be applied to a complex web system which is composed of microservices, but I couldn't find any resources on the web about such approach.

Let's suppose that there are few applications in a system. Some of them depends on databases and message queues, may be exposed via ingress and there may be a monitoring system like Prometheus with Grafana plus ELK stack. In general, there are many k8s resources to manage, and the deployment process is complex.

I can imagine an operator which will install all the monitoring systems and databases first and then deploy stateless applications to a Kubernetes cluster. Hence, the operator will automate the system deployment process.

Questions:
1. Is this a proper way of using an operator pattern? 
1. Is it possible, and recommended, to deploy the entire system using one operator and then manage stateful applications using dedicated operators? For example, I deploy the entire system with an operator, then I want to manage/scale a previously deployed database using another operator, assuming that the first operator was using database CRDs.
1. If this approach is implemented, is it possible to deploy/update a single application in a system without the need of calling other services?
1. Should I use operator framework for rather very complex systems or simple ones?

**Comment by varshaprasad96** [comment]
@piotrpersona Thanks for bringing up this issue. Answering the questions inline:
As you mentioned the idea of operators is to automate stateful application or even a bunch of such applications co-existing in an ecosystem. To summarize your need, I can image your ecosystem to be a bunch of independent stateless applications which are dependent on each other. Fortunately, operator framework does have a few projects that can support your use-case.
1. Imo, this system can be considered to be a use case to follow operator pattern. Reason being, each independent application's lifecycle is to be automated, and they are "stateful".
2. We can have each of microservices to be managed by an operator, and then have Operator Lifecycle Manager (https://olm.operatorframework.io) to manage the overall lifecycle of each of them. This way, we have OLM to manage the independent lifecycle of each of them, their upgrades and dependencies.
3. We do have a bunch of users who have multiple operators installed through OLM. Here are some examples, (though these may/maynot be exactly similar: https://operatorhub.io)
4. Operator Framework does provide a set of tools to make this easier. We have:
Operator SDK - tool to build your operator for each micro service.
Operator Lifecycle Manager - tool to manage those multiple operators.
Operator Package Manager - tool to package the operator content into bundle and send it to OLM.
 The tools can serve multiple use-cases, whether a simple one - dealing with one operator, or a complex system - dealing with multiple microservices.

**Comment by asmacdo** [comment]
I've heard of very complex applications that use "top level" operator that uses APIs provided by other operators. 

This makes sense and (IMO) fits with Kubernetes design principles. For instance, you might create a Deployment, and the deployment controller will create replica sets, which are then managed by the ReplicaSets controller. Operators offer a nice way of abstracting out the complexity of the smaller parts, and can simplify the whole system in that way. 

One caveat is that each operator is another process that must always run on the cluster, so it might consume more resources when done this way.

Also, be very sure to keep the abstractions separate. Having multiple controllers managing a single resource is definitely an anti-pattern that causes all kinds of pain like infinite reconciliation.

**Comment by piotrpersona** [comment]
@varshaprasad96 @asmacdo Thank you for response.
I think it's clear that operator framework with OLM would fit into my system's design.
