### ISSUE TITLE
helm overrideValues will not work for booleans

### ISSUE THREAD

**Issue by xrow** [operator-framework/operator-sdk#6115]
#### What did you do?

When susing the helm operator sdk I have an issue with override vars not being strings.

My watches looks like this
```
---
- version: v1
  group: xrow.com
  kind: Ibexa
  chart: /opt/helm/helm-charts/ibexa
  watchDependentResources: false
  overrideValues:
    installation.enabled: true
```

#### What did you expect to see?

no issue when using my operator

#### What did you see instead? Under which circumstances?

From the pod log from the operator:

`{"level":"error","ts":1666869259.3604903,"logger":"helm.controller","msg":"Failed to sync release","namespace":"test1","name":"ibexa","apiVersion":"xrow.com/v1","kind":"Ibexa","release":"ibexa","error":"failed to get candidate release: values don't meet the specifications of the schema(s) in the following chart(s):\nibexa:\n- installation.enabled: Invalid type. Expected: boolean, given: string\n","stacktrace":"github.com/operator-framework/operator-sdk/internal/helm/controller.HelmOperatorReconciler.Reconcile\n\t/workspace/internal/helm/controller/reconcile.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}`

#### Environment

**Operator type:**

language helm

**Kubernetes cluster type:**

OpenShift 3.11

`$ operator-sdk version`

1.25.0

`$ kubectl version`

not applicable 

#### Possible Solution

make false, true, False, True not quoted or keep the type somehow.

#### Additional context

My chart has a schema json that can validate the values

such as 

```
    "installation": {
      "type": "object",
      "properties": {
          "enabled": {
              "type": "boolean"
          },
          "package": {
              "type": "string"
          },
          "script": {
              "type": "string"
          }
      }
    },
```

**Comment by xrow** [comment]
https://github.com/operator-framework/operator-sdk/blob/f5e15be6c282d9df1662dd3febcfbd782c2b94f0/internal/helm/controller/reconcile.go#L54

A map of strings per default.

**Comment by varshaprasad96** [comment]
@xrow As you have pointed out correctly, this is because the `overrideValues` option takes in a map of strings as key/value type (https://github.com/operator-framework/operator-sdk/blob/v1.25.0/internal/helm/controller/reconcile.go#L54). This seems a reasonable feature, we may have to look into the implementation details as the override values can also be environment variables.

/kind feature

**Comment by skattoju** [comment]
Trying to do something like this so that OverrideValues don't have to be set in spec : https://github.com/skattoju/airflow-hybrid-operator/blob/afd9e854876fe487ce503285a34c5935c8bb064e/watches.yaml#L9

**Comment by skattoju** [comment]
One way to resolve this is by passing a value translator function to the reconciler[1] 

[1] https://github.com/operator-framework/helm-operator-plugins/blob/7eacb666f7941ae3f1084c5b01fc26811e715379/pkg/reconciler/reconciler.go#L451 
[2] https://github.com/skattoju/airflow-hybrid-operator/blob/4a8760ed45aa5df6957304f47785e166508c4f7f/main.go#L158
