### ISSUE TITLE
External resource management using operator

### ISSUE THREAD

**Issue by speedfl** [operator-framework/operator-sdk#6117]
## Type of question

Open question

#### What did you do?

Hello. This follows a discussion we had during the kubecon 2022 in Detroit with @asmacdo from RedHat.
More than an issue it is a *Philosophical* question about external resource management using an operator. It could be nice to have a consensus and recommendations in the documentation.

When using a standard operator it is possible to [watch resources that are owned and managed by the controller](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#resources-watched-by-the-controller) so that reconcile loop is called on the child resource's events (ie: Pod crash)

More and more companies are trying to manage external resources using operators:

- Strimzi standalone topic operator manages topics on any Kafka Cluster
- AWS controller for Kubernetes provisions resources in AWS such as EC2 instances / RDS databases...
- Azure Service Operator is doing the same for Azure cloud.

With external resources it is not possible to trigger the reconcile loop with standard Events to quickly react and reflect your desired state (on system fault for example).

ACK made the choice to stop reconciliation when the desired state has been met and triggers a reconciliation after 10 hours. Therefore if RDS is unavailable during this period (or drifted), no reconcile loop is triggered.
    - https://aws-controllers-k8s.github.io/community/docs/community/how-it-works/#drift-detection-and-remediation  
    - https://github.com/aws-controllers-k8s/runtime/blob/13496a878abc8dd9f784d84c6452638a0d736df3/pkg/runtime/reconciler.go#L880
    - https://github.com/aws-controllers-k8s/runtime/blob/13496a878abc8dd9f784d84c6452638a0d736df3/pkg/runtime/reconciler.go#L50
    - https://github.com/aws-controllers-k8s/ec2-controller/blob/main/pkg/resource/instance/manager_factory.go#L85

But what if you need to react quickly to such a situation ?

#### What did you expect to see?

- If the resource fails for an unexpected reason (system fault), I want to react quickly and update the Custom Resource status

```yaml
status:
  phase: Failed
  conditions:
    - type: Ready
      status: False
      reason: Dead
      message: Resource state transitioned from Running to Dead 
```

- If the resource fails for an unexpected reason I may want to restart it.

- If the resource succeeded I want to update the status:

```yaml
status:
  phase: Succeeded
```

- Status could be enriched with relevant information such as a log url, an id...

#### What did you see instead? Under which circumstances?

N/A

#### Environment

N/A

#### Force reconciliation

Reconciliation can be forced using `RequeueAfter` even when the desired state has been met. 

Rabbitmq allows to [force reconciliation](https://www.rabbitmq.com/kubernetes/operator/using-topology-operator.html#sync-period) with environment variable `SYNC_PERIOD`

#### Use an Agent Pod

The Operator [owns Pods](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#resources-watched-by-the-controller). 
The Operator launch an *Agent* Pod to poll the external resource, report interesting information in the Custom Resource Status. 

If the External resource fails (or drift), the *Agent* Pod container exits with a status `!= 0` allowing the Operator having its reconcile loop triggered in order to take actions (ie: Relaunch the resource and reschedule Pod).

Here 2 sub-possibilities

##### Agent is only polling

The Operator creates, updates, deletes the external resource. 
The *Agent* Pod monitors the external resource status and reports it in the Custom Resource Status.

##### Agent is creating the external resource and creates it

The Operator creates, update and delete the *Agent* Pod.

When starting, the *Agent* Pod creates/updates the external resource. 
The *Agent* Pod monitors the external resource status and report changes in the Custom Resource Status.
The *Agent* Pod `preStop` deletes the external resource

**Comment by varshaprasad96** [comment]
Hi @speedfl, thanks for bringing this up. This is an interesting topic - triggering reconcile from events which are external to the cluster. We had a discussion about this and Michael Hrivnak (@mhrivnak) suggested a solution of using controller-runtime's `source.Channel` (https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/source#Channel). The idea is use the Channel source and push `GenericEvents` into the queue that eventually trigger reconciliation. We could have a webhook setup that triggers a generic event during a change happening in an external resource that can then be passed into controller-runtime's watch (This way we need not spend resources in having an agent pod to poll the external resource continuously). Eg:

```
err := ctrl.Watch(
		&source.Channel{Source: events},
		&handler.EnqueueRequestForObject{},
	)
```

There is some documentation regarding the same: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/source#Channel, and some piece of code that explains its usage in simple tests: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/source/source_test.go#L294-L338

**Comment by mhrivnak** [comment]
Thanks Varsha for relaying that.

A channel source is indeed a good tool for this circumstance. You can either listen for some inbound notification, such as listening on an http endpoint or an external message bus, or you can use a goroutine to poll the state of an external resource. The choice will depend on the capabilities and nature of the external entity you want to watch. Either way, this can happen in your controller process, with no need for an extra Pod.

**Comment by asmacdo** [comment]
As it happens I --just-- write up another issue about this. 

https://github.com/operator-framework/operator-sdk/issues/6122

Thanks for starting the conversation, folks can feel free to close my issue.

**Comment by caspereijkens** [comment]
@varshaprasad96 This is a very interesting idea. Have you explored it any further or do you know if there are new insights in how to deal with external state?

**Comment by caspereijkens** [comment]
I think I have a working mechanism.

In the controller I have to add `WatchesRawSource(&source.Channel{Source: Events}, &handler.EnqueueRequestForObject{}).` to the builder like this:
```
import "sigs.k8s.io/controller-runtime/pkg/event"
var Events = make(chan event.GenericEvent)
// SetupWithManager sets up the controller with the Manager.
func (r *MemcachedReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&cachev1alpha1.Memcached{}).
		WatchesRawSource(&source.Channel{Source: Events}, &handler.EnqueueRequestForObject{}).
		Complete(r)
}
```

Then in `cmd/main.go` I kick off a http listener on a go routine that puts `GenericEvents` on the `Events` channel based on webhooks. 

```
		typeNamespacedName := types.NamespacedName{
			Name:      "target-memcached",
			Namespace: "target-namespace",
		}
		memcached := &cachev1alpha1.Memcached{}
                // do a get request using the k8s client of the controller-manager
		err := h.Client.Get(ctx, typeNamespacedName, memcached)
		if err != nil {
			<error handling>
		}
		controller.Events <- event.GenericEvent{
			Object: memcached,
		}
```

Not sure if there are better approaches but I am pretty happy with the result.
