### ISSUE TITLE
Update helm operator container image's latest tag

### ISSUE THREAD

**Issue by skattoju** [operator-framework/operator-sdk#6118]
## Bug Report

Helm operators built using [quay.io/operator-framework/helm-operator:latest](http://quay.io/operator-framework/helm-operator:latest) can no longer be published due to a vulnerability. The [vulnerability](https://access.redhat.com/errata/RHSA-2022:7089) being reported has already been fixed in ubi8/ubi-minimal 

#### What did you do?

Built a helm operator and submitted for scanning.

#### What did you expect to see?

Helm operator does not have any major vulnerabilities.

#### What did you see instead? Under which circumstances?

Helm operator has major [vulnerabilities](https://access.redhat.com/errata/RHSA-2022:7089) that have already been fixed in ubi8/ubi-minimal 

#### Environment

**Operator type:**
Helm Operator

/language helm

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by nitishdsharma** [comment]
operator-sdk version: "v1.18.1"
kubernetes version: "1.21"

**Comment by jmrodri** [comment]
* verify that fresh image task is running
* verify latest branch points to latest release

**Comment by tkrishtop** [comment]
Hi @everettraven @jmrodri our Telco partner reported a similar issue. They used the latest version of operator-sdk 1.25.0 to build a helm operator, and that produced an operator that did not pass oscap-podman vulnerability check required for the RH certification.

I checked today and discovered that quay.io/operator-framework/helm-operator:v1.25.0 was rebuilt 20h ago. It is now passing oscap-podman, the oval-report is fully green. 

```
$ sudo -i
# cd health_check_test/
# wget -O - https://www.redhat.com/security/data/oval/v2/RHEL8/rhel-8.oval.xml.bz2 | bzip2 --decompress > rhel-8.oval.xml
# ls
rhel-8.oval.xml

# podman pull quay.io/operator-framework/helm-operator:v1.25.0
# podman images
REPOSITORY                                TAG         IMAGE ID      CREATED        SIZE
quay.io/operator-framework/helm-operator  v1.25.0     7dfaaa52c849  20 hours ago   167 MB

# oscap-podman 7dfaaa52c849 oval eval --report oval-report-helm.html rhel-8.oval.xml
```

**Comment by everettraven** [comment]
Hi @tkrishtop, I believe @jmrodri has been running some of our GitHub actions to update these images and is planning on making some updates to the actions to prevent these images from becoming out of date again. 

From offline conversations we have had it isn't as easy - with how our existing actions are setup - to automatically update the latest tag of the images. This is something we have been discussing as what the best route to go about fixing these actions are, but hopefully @jmrodri or I will have an update to share soon.

We will also post here to notify when the latest tags have been updated

**Comment by acornett21** [comment]
@tkrishtop Thanks for clarifying, that's good info to have! Much appreciated!

**Comment by everettraven** [comment]
@acornett21 all the images for operator-sdk that are on quay are built and pushed as part of our GitHub Actions. We have an action that will run nightly to update the images for our latest 2 release tags but it was omitted in that action to also update the images for our latest tag. There is also some funky time based logic that was preventing some of our latest 2 release tags to have their images updated. @jmrodri is working on updating these actions to run as expected and once this is done it should prevent the issue where our latest tag and n-1 version tags become out of date from the UBI images we depend on. Hopefully this helps clear it up a bit!

**Comment by everettraven** [comment]
As an update, the latest tag should have been updated as of 11/09/2022 since we released a patch release (`v1.25.1`) of Operator SDK. For the long term, I believe @jmrodri is still working on fixing our automated refresh GitHub Action

**Comment by acornett21** [comment]
@everettraven Thanks for the update!

**Comment by tkrishtop** [comment]
Hello @everettraven it seems like 1.25.1 takes ubi8.6 while the latest now is ubi8.7, [it was released 6 days ago](https://catalog.redhat.com/software/containers/ubi8/5c647760bed8bd28d0e38f9f).

Could you please issue one more patch release please? 

```
$ podman inspect quay.io/operator-framework/helm-operator:v1.25.1 | jq -r '.[0].Labels'
{
  "architecture": "x86_64",
  "build-date": "2022-10-26T11:07:47",
  "com.redhat.component": "ubi8-minimal-container",
  "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
  "description": "The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
  "distribution-scope": "public",
  "io.buildah.version": "1.26.2",
  "io.k8s.description": "The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
  "io.k8s.display-name": "Red Hat Universal Base Image 8 Minimal",
  "io.openshift.expose-services": "",
  "io.openshift.tags": "minimal rhel8",
  "maintainer": "Red Hat, Inc.",
  "name": "ubi8-minimal",
  "release": "994",
  "summary": "Provides the latest release of the minimal Red Hat Universal Base Image 8.",
  "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8-minimal/images/8.6-994",
  "vcs-ref": "50293e4ba66ca2194d8ee5a149a665cb9a375c71",
  "vcs-type": "git",
  "vendor": "Red Hat, Inc.",
  "version": "8.6"
}
```

**Comment by everettraven** [comment]
@tkrishtop Thanks for pointing that out! I will take a look!

**Comment by everettraven** [comment]
This image should now be updated as of the `v1.25.2` patch release. 

To track updating the `freshen-images` GitHub Action fix I created: https://github.com/operator-framework/operator-sdk/issues/6200

Closing this issue, but please feel free to reopen if there is still an issue with this image.
