### ISSUE TITLE
types from dependencies as crd values

### ISSUE THREAD

**Issue by sstarcher** [operator-framework/operator-sdk#612]
Is it currently possible to use structs from a third party library or do I need to keep all types used in for the CRD to types built in or defined in the types.go in the apis package?

Due to the generated nature structs defined elsewhere do not seem work
```
pkg/apis/newrelic/v1alpha1/zz_generated.deepcopy.go:75:9: in.Derp.DeepCopyInto undefined (type newrelic.AlertsChannel has no field or method DeepCopyInto)
```

Any way around this or do I just need to redefine all of those types myself?

I was attempting to use https://github.com/IBM/newrelic-cli/blob/f16d177767b4eb445696e0a66941057fb17a8882/newrelic/alerts_channels.go#L115

**Comment by shawn-hurley** [comment]
Every object that kubernetes uses needs certain methods. DeepCopyInto is an example of one of those methods. This is because the generated functions expect this. 

The generate scripts attempt to add these functions for you, but if your types are vendored then it can not add these methods onto the structs.

You could attempt to write your own deep copy into function for the  CRD struct that would not use the deep copy into function for the vendored struct but then you will not be able to use generation I believe.

Does this answer your question?

**Comment by sstarcher** [comment]
@shawn-hurley you did thank you.

**Comment by chinglinwen** [comment]
I've got same error here.

```
type ProjectSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file
	// Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html

	project.Project
}
```

project struct

```
type Project struct {
	// Namespace string    `yaml:"namespace,omitempty" json:"namespace,omitempty"`
	Project   string    `yaml:"project,omitempty" json:"project,omitempty"` // event.Project.PathWithNamespace
	Branch    string    `yaml:"branch,omitempty" json:"branch,omitempty"` 
	Env       string    `yaml:"env,omitempty"`
	UserName  string    `yaml:"user_name,omitempty" json:"user_name,omitempty"`
	UserEmail string    `yaml:"user_email,omitempty" json:"user_email,omitempty"`
	Message   string    `yaml:"message,omitempty" json:"message,omitempty"`
	Time      time.Time `yaml:"time,omitempty" json:"time,omitempty"`
}
```


## sdk v0.9.0
```
// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteMonitorSpec) DeepCopyInto(out *SiteMonitorSpec) {
	*out = *in
	out.SiteMonitor = in.SiteMonitor
	return
}
```

## sdk v0.10.0
```
// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	in.Project.DeepCopyInto(&out.Project)
	return
}
```
for sdk v0.10.0, so the following error

```
[wen@234 k8snew manager]$ go build
# wen/project-operator/pkg/apis/project/v1alpha1
../../pkg/apis/project/v1alpha1/zz_generated.deepcopy.go:75:12: in.Project.DeepCopyInto undefined (type project.Project has no field or method DeepCopyInto)
[wen@234 k8snew manager]$ 
```

Will i change  `in.Project.DeepCopyInto(&out.Project)` to `out.Project = in.Project` work the same way? @shawn-hurley
