### ISSUE TITLE
Simplify pattern of reconcililing based on a non-standard event

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#6122]
As an Operator author, I want my operator to start reconciliation based on a custom event source.

Typically, operators begin a reconciliation when either the Primary or the Secondary resources change (and create an event). This story covers less common cases:
 - Reconcile if resources outside of the cluster are misbehaving
 - Running reconciliation based on metrics

If I understand correctly, this can be done by using a separate goroutine that emits a GenericEvent, add the goroutine as a Source, and adding that Source to the Channel. 

It would be nice if there was a helper for this so operator authors don't need to go that deep into Controller Runtime, but if that isn't practical, this should be a documentation issue.

**Comment by asmacdo** [comment]
This belongs in best-practices doc IMO

**Comment by varshaprasad96** [comment]
Closing this issue in favor of https://github.com/operator-framework/operator-sdk/issues/6117
