### ISSUE TITLE
 Query Memory usage by operator SDK

### ISSUE THREAD

**Issue by jmrodri** [operator-framework/operator-sdk#6131]
Kiali-operator uses operator sdk and looks like operator sdk generate logs in runner volume which is EmptyDir which uses host resource. 

Any idea how much size it can consume on node, any thoughts on memory usage of this folder would be great?

https://github.com/kiali/kiali/discussions/4374

**Comment by varshaprasad96** [comment]
We would need to run a profiler to check the memory consumption. If this is a go based operator we could use the go’s pprof library, however, if its ansible we already have a community project to help us to do so: [ansible-community/operator-sdk-performace-testing](https://github.com/ansible-community/operator-sdk-performance-testing). We initially thought of having an endpoint exposed to make profiling of operator-sdk based projects easier. However, there wasn't much action taken on that end, but here is an investigation doc which captures different possibilities to so: https://docs.google.com/document/d/19JMAON6Ez38NYP0ViQlYJW5G6KNU6veD2pk3t_e3VU0/edit
