### ISSUE TITLE
compile from source says golang 1.18

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#6138]
### What is the URL of the document?

https://sdk.operatorframework.io/docs/installation/#compile-and-install-from-master

should be 1.19 I think

**Comment by varshaprasad96** [comment]
Let's have an env variable that takes the value from the go version check and accordingly modifies this doc. That way we need not worry about our documentation getting out of sync.

**Comment by varshaprasad96** [comment]
Alternative is to have a script that pulls the version from go.mod and update docs.

**Comment by everettraven** [comment]
The core of this issue is resolved with #6253 - should we keep this issue open to facilitate the creation of a script that automatically updates this version?
