### ISSUE TITLE
`memcached-sample` GitHub Action e2e test is flaky

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-sdk#6140]
## CI Bug Report
The [memcached-sample/e2e](https://github.com/operator-framework/operator-sdk/actions/workflows/test-sample-go.yml) GitHub Action is flaky due to a [metrics counter assertion check that fails](https://github.com/operator-framework/operator-sdk/blob/dc8c40b72ff93135e32f02614c601365e46dca0d/testdata/go/v3/memcached-operator/test/e2e/e2e_test.go#L257). The expectation seems to consistently be for the counter to have a value of 5 but I have seen runs where the value fluctuates and has been 6, 7, or 8 in various runs.

We should try to avoid having flaky CI checks as much as possible.

#### Possible solutions
- Remove the check
- Update the test/check to be more robust

**Comment by varshaprasad96** [comment]
This would be a part of #6142
