### ISSUE TITLE
Add monitoring to the testdata operator

### ISSUE THREAD

**Issue by sradco** [operator-framework/operator-sdk#6142]
## Feature Request
Add a separate monitoring project to the testdata operator, where developers can see what is deployed when adding monitoring to the operator and having a Memcached example with monitoring.

#### Describe the problem you need a feature to resolve.

Currently the testdata operator is missing scaffolding metrics, alerts, runbooks and other things related to monitoring.
When new operators developers want to add monitoring to their operator, currently they don't have examples, tooling and best practices that will help them with the initial ramp up.

#### Describe the solution you'd like.

We would like to add monitoring to the testdata operator, that will help developers to start implementing monitoring and provide them with tooling, examples and best practices.

Since this is not considered as part of a basic operator deployment, we would like to add it as a separate project, that is based on the testdata operator and will deploy the testdata operator with the recommended structure and tooling for metrics, alerts, runbooks and all that is needed for monitoring with Prometheus here, https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata.
And provide command lines for adding them like here, https://book.kubebuilder.io/plugins/grafana-v1-alpha.html#basic-usage for Grafana.

Note: Since the Grafana add-on is very much related to monitoring, we think it should be merged into the monitoring project.

In addition, we would like the developers to be able to deploy the memcached operator with monitoring, so we would also like to add it as a separate project here, https://github.com/operator-framework/operator-sdk/tree/master/testdata/go and create a `v4-alpha/memcached-operator-with-monitoring`.

We would add to the operator-sdk the needed documentation to reference to it for developers that want to start adding monitoring to their operator.

**Comment by varshaprasad96** [comment]
Adding documentation and scaffolding around best practices will be a great addition to operator authors who would like to include monitoring stack. Since this is an optional feature (though a suggested best practice to get metrics out of reconciler), adding a separate sample project as KB does (https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata) makes it easier for users to know the difference between a level 1 and higher capability operator model. +1 to this addition!

**Comment by varshaprasad96** [comment]
Listing the sub tasks as discussed in the community meeting:
- Adding a separate folder that scaffolds a sample go memcached project with the best practices for collecting metrics.
- Including the scaffolded project in Makefile, so as to test the scaffolding : https://github.com/operator-framework/operator-sdk/blob/498e0c407a2096af3cfac421eca726e55e8f00d1/Makefile#L162
- Fixing the test flakes in #6140, by moving all monitoring related scaffolding to a single location.

**Comment by varshaprasad96** [comment]
Adding the 3 PRs which were created for this issue:

- [ ] 1. https://github.com/operator-framework/operator-sdk/pull/5975 - Merged
- [ ] 2. https://github.com/operator-framework/operator-sdk/pull/6135 - Merged
- [ ] 3. https://github.com/operator-framework/operator-sdk/pull/6114

**Comment by assafad** [comment]
Hi @varshaprasad96 @everettraven, would it make sense to add a monitoring tutorial under [advanced-topics](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs/advanced-topics)?
It will guide how to add custom metrics and alerts, and will use our work on `monitoring/memcached-operator` as a reference. 

Please see https://issues.redhat.com/browse/CNV-21038

**Comment by varshaprasad96** [comment]
@assafad that would be really helpful! Could you create a separate issue for the documentation. We just closed this issue because the 3 major PRs were done, and we would be cutting the release soon.
