### ISSUE TITLE
Run bundle-upgrade is failing because is unable to fit into a ConfigMap, too large

### ISSUE THREAD

**Issue by J0zi** [operator-framework/operator-sdk#6144]
#### What did you do?

```
operator-sdk run bundle quay.io/operatorhubio/strimzi-kafka-operator:v0.31.1 -n testupgrade --skip-tls-verify
...
INFO[0119] OLM has successfully installed "strimzi-cluster-operator.v0.31.1" 

operator-sdk run bundle-upgrade quay.io/operatorhubio/strimzi-kafka-operator:v0.32.0 -n testupgrade --skip-tls-verify
INFO[0001] Found existing subscription with name strimzi-cluster-operator-v0-31-1-sub and namespace testupgrade 
INFO[0001] Found existing catalog source with name strimzi-kafka-operator-catalog and namespace testupgrade 
INFO[0014] Generated a valid Upgraded File-Based Catalog 
FATA[0014] Failed to run bundle upgrade: update catalog error: error creating registry: error building registry pod definition: configMap error: error updating ConfigMap: ConfigMap "operator-sdk-run-bundle-config" is invalid: []: Too long: must have at most 1048576 bytes
```

#### What did you expect to see?

Bundle upgraded

#### What did you see instead? Under which circumstances?

ConfigMap "operator-sdk-run-bundle-config" is invalid: []: Too long: must have at most 1048576 bytes

#### Environment

`$ operator-sdk version`

```
operator-sdk version: "v1.25.0", commit: "3d4eb4b2de4b68519c8828f2289c2014979ccf2a", kubernetes version: "1.25.0", go version: "go1.19.2", GOOS: "linux", GOARCH: "amd64"
```

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by varshaprasad96** [comment]
This issue seems to be similar to: https://github.com/operator-framework/operator-sdk/issues/5880

**Comment by abdennour** [comment]
may because you have icon with big size. i mean `csv.spec.icon[*].base64data`

**Comment by J0zi** [comment]
@everettraven any update?
@abdennour this is not my operator :) `v0.31.1` has also big icon and was able to be installed. Upgrade should not fail on the same or similar size icon.

**Comment by everettraven** [comment]
@J0zi This was on my radar to take a dive into but I got distracted and totally forgot to take a look. Thanks for the ping, I will make sure I take a look today!
