### ISSUE TITLE
Go Operator Tutorial

### ISSUE THREAD

**Issue by nunojca** [operator-framework/operator-sdk#6166]
This doesn't seem to be correct and coherent with the code snippet:

> "and a MemcachedStatus.Nodes field to store a CR’s Pod names
> 
> Note The Node field is just to illustrate an example of a Status field. In real cases, it would be recommended to use [Conditions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties)"

**Comment by everettraven** [comment]
Hi @chiukapoor, thanks for picking up this issue!

I will go ahead and assign you. Let me know if you have any questions!

/assign @chiukapoor

**Comment by chiukapoor** [comment]
The `make test-sanity` is failing due to #6191 #6190, waiting for the fix to get merged before creating a PR for this issue.
