### ISSUE TITLE
`operator-sdk bundle validate` doesn't check type correctness of all values

### ISSUE THREAD

**Issue by arewm** [operator-framework/operator-sdk#6168]
## Bug Report

Bundle validation passes when values within the CSV do not have appropriate types. 

This has been encountered multiple times. We traced down the suspected offending lines to when the `spec.version` was a string as well as when `metadata.annotations.*` were not strings, for example,

```
metadata:
  annotations:
    certified: true
```

#### What did you do?

Ran `opm render` and `opm bundle add ` resulting in an error message 

```
Error: unrecognized type: string
```

When trying to track the source of the issue, we ran `operator-sdk bundle validate`, but no errors were raised.

#### What did you expect to see?

An error message indicating which values have the wrong type

#### What did you see instead? Under which circumstances?

Validation passed without errors

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`

```
operator-sdk version: "v1.25.1", commit: "162690ff23f3542c0565e1420223e30dfae5dd49", kubernetes version: "1.25.0", go version: "go1.19.2", GOOS: "linux", GOARCH: "arm64"
```

`$ go version` (if language is Go)

`$ kubectl version`

#### Additional context

These issues were encountered when trying to add bundles to an index image. We traced it down to improper types which bundle validation did not catch. 

Related image in operator-registry: https://github.com/operator-framework/operator-registry/issues/1039

**Comment by varshaprasad96** [comment]
@theishshah would you be working on this before the next release (1.28). If its difficult to get in, please feel free to move it to the next one.

**Comment by varshaprasad96** [comment]
@theishshah would it be possible to get this in before the next release due on July 24 (1.31). If not, please feel free to bump it to the next one.

**Comment by varshaprasad96** [comment]
@theishshah following up on this issue? Would it be possible to get this in before 1.32

**Comment by varshaprasad96** [comment]
@theishshah Is it fine if we unassign you from this issue, and add a help wanted label. It would helpful if you could mentor anyone working on this issue since you have knowledge on where the codebase lives.
