### ISSUE TITLE
gpg key used to verify release expired on 2022-10-31

### ISSUE THREAD

**Issue by kriswuollett** [operator-framework/operator-sdk#6185]
Followed directions at https://sdk.operatorframework.io/docs/installation/#2-verify-the-downloaded-binary to install. Signature and checksums match, but signature key has expired on 2022-10-31.

```shell
gpg --list-keys 052996E2A20B5C7E
pub   rsa4096 2020-10-30 [C] [expired: 2022-10-31]
      3B2F1481D146238080B346BB052996E2A20B5C7E
uid           [ expired] Operator SDK (release) <cncf-operator-sdk@cncf.io>
```

**Comment by jmrodri** [comment]
@kriswuollett can you try again? We recently updated the expiration of the key. I pushed it up to the keyserver tonight. See if that helps.

**Comment by jberkhahn** [comment]
i can confirm the new key works
