### ISSUE TITLE
FATA[0000] Failed to build operator binary: failed to exec []string

### ISSUE THREAD

**Issue by KailashPatilKP** [operator-framework/operator-sdk#6198]
#### What did you do?

I'm trying to execute the command (docker push <DOCKER_REGISTRY_URL>/<USER_NAME>/siddhi-operator:<TAG>) but it's failing with below error.

`panic: modindex.GetPackage called with empty modroot

goroutine 19 [running]:
cmd/go/internal/modindex.GetModule({0x0, 0x0})
	/usr/local/Cellar/go/1.19.3/libexec/src/cmd/go/internal/modindex/read.go:157 +0x125
cmd/go/internal/modindex.GetPackage({0x0, 0x0}, {0xc0000ee680, 0x7e})
	/usr/local/Cellar/go/1.19.3/libexec/src/cmd/go/internal/modindex/read.go:135 +0x31
cmd/go/internal/modload.scanDir({0x0?, 0x7e?}, {0xc0000ee680, 0x7e}, 0x0?)
	/usr/local/Cellar/go/1.19.3/libexec/src/cmd/go/internal/modload/load.go:2105 +0x4b
cmd/go/internal/modload.(*loader).load(0xc000155380, {0x172f930, 0xc0000b2000}, 0xc000155520)
	/usr/local/Cellar/go/1.19.3/libexec/src/cmd/go/internal/modload/load.go:1734 +0x35f
cmd/go/internal/modload.(*loader).pkg.func1.1()
	/usr/local/Cellar/go/1.19.3/libexec/src/cmd/go/internal/modload/load.go:1517 +0x29
cmd/go/internal/par.(*Queue).Add.func1()
	/usr/local/Cellar/go/1.19.3/libexec/src/cmd/go/internal/par/queue.go:58 +0x7d
created by cmd/go/internal/par.(*Queue).Add
	/usr/local/Cellar/go/1.19.3/libexec/src/cmd/go/internal/par/queue.go:56 +0x225
FATA[0000] Failed to build operator binary: failed to exec []string{"go", "build", "-o", "/Users/kailash.patil/Downloads/operator-sdk-v0.19.0/operator-sdk/vendor/github.com/siddhi-io/siddhi-operator/build/_output/bin/siddhi-operator", "-gcflags", "all=-trimpath=/Users/kailash.patil/Downloads/operator-sdk-v0.19.0/operator-sdk/vendor/github.com/siddhi-io", "-asmflags", "all=-trimpath=/Users/kailash.patil/Downloads/operator-sdk-v0.19.0/operator-sdk/vendor/github.com/siddhi-io", "-mod=vendor", "Users/kailash.patil/Downloads/operator-sdk-v0.19.0/operator-sdk/vendor/github.com/siddhi-io/siddhi-operator/cmd/manager"}: exit status 2 ` 

#### What did you expect to see?

Command executed successfully and image is created.

#### What did you see instead? Under which circumstances?

Encountered issue while executing the command.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

docker-desktop

`$ operator-sdk version`

operator-sdk version: "v0.19.0", commit: "8e28aca60994c5cb1aec0251b85f0116cc4c9427", kubernetes version: "v1.18.2", go version: "go1.13.10 darwin/amd64"

`$ go version` (if language is Go)

go version go1.19.3 darwin/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}

**Comment by everettraven** [comment]
@KailashPatilKP do you have to use Operator SDK version `v0.19.0`? That is a version we no longer support and I would highly recommend trying to upgrade and use the [latest release](https://github.com/operator-framework/operator-sdk/releases/tag/v1.25.2) of Operator SDK which is version `v1.25.2`.

If you absolutely *need* to use Operator SDK version `v0.19.0` it seems like this is related to using a Go version that wasn't intended to be used when building it from source. From the version information it seems to me that Operator SDK `v0.19.0` is intended to be built with Go `v1.13`, but it appears you are attempting to build it with Go `v1.19`. My recommendation would be to try building the binary with Go `v1.13` and see if that works.

I hope this helps!

**Comment by varshaprasad96** [comment]
Additionally, I would also highly recommend to either scaffold the project in the [GOPATH](https://go.dev/doc/gopath_code) or [activate](https://github.com/golang/go/wiki/Modules#how-to-install-and-activate-module-support) module support. This error usually happens in Go when it assumes that the package is outside a module (https://cs.opensource.google/go/go/+/refs/tags/go1.19.3:src/cmd/go/internal/modindex/read.go;l=157). However, maintaining the supported SDK+Go version compatibility will be helpful to avoid any unexpected errors.
