### ISSUE TITLE
`freshen-images` doesn't rebuild images for the `latest` tag

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-sdk#6200]
#### What did you do?

Ran the `freshen-images` GitHub Action

#### What did you expect to see?

The `latest` tag for all rebuilt images is also rebuilt and pushed

#### What did you see instead? Under which circumstances?

The n-1 version tags `v*` are rebuilt and pushed but not the `latest` tag

#### Possible Solution

Update the `freshen-images` GitHub Action to also update the `latest` image tag, as it currently only updates the n-1 version tags for images.

**Comment by jmrodri** [comment]
@everettraven `latest` isn't a tag. I first thought oh I can hardcode `latest` in the list. So the logic is more complicated, it will need to know how to change into the `latest` branch. 

OR

if there is a way for it to know which is the most recent github tag, then push that to `latest` as well. For example, once it determines that the 2 tags to rebuild are `v1.25.2` and `v1.24.1` then it knows that `v1.25.2` is the latest, it can just build and push to both `v1.25.2` and `latest` tags in quay.io.

**Comment by everettraven** [comment]
@jmrodri that makes sense to me. There has to be some way to do it,  I guess it is more just a matter of _how_.

**Comment by varshaprasad96** [comment]
We update the logic in (https://github.com/operator-framework/operator-sdk/blob/a1b976e7d40e4c8c5c3800283de0c0905c06bd56/.github/workflows/freshen-images/lib.sh#L31) to find the latest tag and push it to quay's latest tag.
