### ISSUE TITLE
Deployment of operator missing helm option

### ISSUE THREAD

**Issue by xrow** [operator-framework/operator-sdk#6205]
#### Describe the problem you need a feature to resolve.

Currently main option of a clean deployment is the deploying the operator via OLM.

#### Describe the solution you'd like.

A common pattern of deployment is also that operator image is deployed to a kubernetes cluster via a helm chart including the operator and helm chart including the operator crd like explained here https://helm.sh/docs/chart_best_practices/custom_resource_definitions. My desire is that the sdk is able to create them on the fly too.

like:

make helm-chart
make helm-chart-drc

The benefit is to install the operator to kubernetes systems where olm is not an option.

The guide https://helm.sh/docs/chart_best_practices/custom_resource_definitions also explaines a combined use as option 1, but I did find that problematic to use, since the crds in the crd folder are not versioned by helm.

/language go
/language ansible
/language helm

**Comment by jberkhahn** [comment]
Hey there,

So, we currently don't have any plans to add support for generating Helm charts. Operators are extremely likely to involve versioning of CRDs and we don't really want to point someone towards a solution that will have that problem down the road. However, it wouldn't be hard to add this to your makefile yourself, and we encourage this sort of thing - once you generate the operator, it's yours to keep. It would be pretty easy to generate an OLM bundle, grab the concat'd yaml out of that and make a Helm chart that way.

**Comment by xrow** [comment]
@jberkhahn Thanks for your feedback. I think I understand the point in versioning crds even tough charts could publish multiple versions too.
