### ISSUE TITLE
Golang Tutorial is broken

### ISSUE THREAD

**Issue by jberkhahn** [operator-framework/operator-sdk#6212]
The example controller code makes reference to a memcached.spec.port field, which doesn't exist in the spec and status objects that you copy+paste from the tutorial docs.

**Comment by michalmedvecky** [comment]
The tutorial is way more broken. The `operator-sdk init` command ends with:

```
FATA[0000] failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v3": go version 'go1.18.9' is incompatible because 'plugin requires go1.19 <= version < go2.0alpha1'. You can skip this check using the --skip-go-version-check flag 
```
The Tutorial specifies that 1.18 is required. 

With go 1.19.4 (latest atm) the previous command does not fail, but later I get:
```
$ make docker-build docker-push IMG="example.com/memcached-operator:v0.0.1"
mkdir -p /Users/michalmedvecky/Documents/go/memcached-operator/bin
test -s /Users/michalmedvecky/Documents/go/memcached-operator/bin/controller-gen || GOBIN=/Users/michalmedvecky/Documents/go/memcached-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.10.0
/Users/michalmedvecky/Documents/go/memcached-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/Users/michalmedvecky/Documents/go/memcached-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
test -s /Users/michalmedvecky/Documents/go/memcached-operator/bin/setup-envtest || GOBIN=/Users/michalmedvecky/Documents/go/memcached-operator/bin go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
go: sigs.k8s.io/controller-runtime/tools/setup-envtest@latest: module sigs.k8s.io/controller-runtime@latest found (v0.13.1), but does not contain package sigs.k8s.io/controller-runtime/tools/setup-envtest
make: *** [/Users/michalmedvecky/Documents/go/memcached-operator/bin/setup-envtest] Error 1
```

**Comment by varshaprasad96** [comment]
There are 3 issues discussed in this issue:
1. @jberkhahn mentioned - The documentation is not updated in SDK side to reflect the API spec as modified by the deploy image plugin. This is a documentation issue. The link to doc where we need to update the spec: https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#define-the-api
2. @michalmedvecky - The docs do need to be updated to mention the right golang version. This is being handled by https://github.com/operator-framework/operator-sdk/issues/6138
3. `make docker-build` fails - This needs to be investigated. Our CI does run tests which scaffold a test project from scratch using SDK. @jberkhahn will be looking into this.
