### ISSUE TITLE
controller-gen & grpc / protobuf version incompatible ?

### ISSUE THREAD

**Issue by davidcheng0922** [operator-framework/operator-sdk#6235]
#### What did you do?

(1) operator-sdk init & create api
(2) add grpc / protobuf in my application 
(3) make manifests
(4) make generate -> Fail

#### What did you expect to see?

should generate success

#### What did you see instead? Under which circumstances?

/home/david/go/src/test-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
panic: interface conversion: ast.Expr is *ast.CompositeLit, not *ast.Ident

goroutine 920 [running]:
sigs.k8s.io/controller-tools/pkg/loader.(*referenceCollector).Visit(0xc007779a20, {0xcf6d48?, 0xc0063ef638})
        /home/david/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/refs.go:136 +0xff
go/ast.Walk({0xcf4940?, 0xc007779a20?}, {0xcf6d48?, 0xc0063ef638?})
        /usr/lib/go-1.18/src/go/ast/walk.go:52 +0x62
go/ast.walkExprList({0xcf4940, 0xc007779a20}, {0xc0064d4760?, 0x1, 0xcf6de8?})
        /usr/lib/go-1.18/src/go/ast/walk.go:26 +0x91
go/ast.Walk({0xcf4940?, 0xc007779a20?}, {0xcf67a8?, 0xc0064d1f80?})
        /usr/lib/go-1.18/src/go/ast/walk.go:145 +0xa8b
go/ast.Walk({0xcf4940?, 0xc007779a20?}, {0xcf6730?, 0xc0063ffb60?})
        /usr/lib/go-1.18/src/go/ast/walk.go:154 +0xfc5
go/ast.Walk({0xcf4940?, 0xc007779a20?}, {0xcf6640?, 0xc0063ffb90?})
        /usr/lib/go-1.18/src/go/ast/walk.go:164 +0x1e49
go/ast.Walk({0xcf4940?, 0xc007779a20?}, {0xcf6988?, 0xc0064d1fc0?})
        /usr/lib/go-1.18/src/go/ast/walk.go:75 +0x37c
go/ast.Walk({0xcf4940?, 0xc007779a20?}, {0xcf69b0?, 0xc0063ffbc0?})
        /usr/lib/go-1.18/src/go/ast/walk.go:86 +0x227a
go/ast.Walk({0xcf4940?, 0xc007779a20?}, {0xcf6de8?, 0xc0063ef650?})
        /usr/lib/go-1.18/src/go/ast/walk.go:169 +0x19a5
sigs.k8s.io/controller-tools/pkg/loader.(*referenceSet).collectReferences(0xc00777f1c0, {0xcf9a40?, 0xc0063ef650}, 0xc3cbe8)
        /home/david/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/refs.go:107 +0xd4
sigs.k8s.io/controller-tools/pkg/loader.allReferencedPackages.func1(0xc000fd1a40?, 0xc000fd1a60?, 0xc0064d1e80)
        /home/david/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/refs.go:164 +0x52
sigs.k8s.io/controller-tools/pkg/loader.(*typeVisitor).Visit(0xc0015ca948?, {0xcf6e60?, 0xc0064d1e80?})
        /home/david/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/visit.go:64 +0xe9
go/ast.Walk({0xcf4960?, 0xc007716210?}, {0xcf6e60?, 0xc0064d1e80?})
        /usr/lib/go-1.18/src/go/ast/walk.go:52 +0x62
go/ast.Walk({0xcf4960?, 0xc007716210?}, {0xcf6aa0?, 0xc0064e2000?})
        /usr/lib/go-1.18/src/go/ast/walk.go:345 +0x21ea
go/ast.walkDeclList({0xcf4960, 0xc007716210}, {0xc0063f2500?, 0xd, 0x0?})
        /usr/lib/go-1.18/src/go/ast/walk.go:38 +0x91
go/ast.Walk({0xcf4960?, 0xc007716210?}, {0xcf69d8?, 0xc0063acc80?})
        /usr/lib/go-1.18/src/go/ast/walk.go:367 +0x1890
sigs.k8s.io/controller-tools/pkg/loader.EachType(0xc0056d6520, 0xc0077161f8)
        /home/david/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/visit.go:38 +0x96
sigs.k8s.io/controller-tools/pkg/loader.allReferencedPackages(0xc0056d6520, 0xc3cbe8)
        /home/david/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/refs.go:162 +0x266
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc002b75728, 0xc0056d6520)
        /home/david/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/refs.go:235 +0x147
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x55?)
        /home/david/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/refs.go:243 +0x65
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check
        /home/david/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/loader/refs.go:241 +0x18d
make: *** [Makefile:89: generate] Error 2

go.mod 

require (
	github.com/go-logr/logr v1.2.3
	google.golang.org/grpc v1.51.0
	google.golang.org/protobuf v1.28.1
	k8s.io/apimachinery v0.26.0
	k8s.io/client-go v0.26.0
	sigs.k8s.io/controller-runtime v0.14.1
)

#### Environment

operator-sdk version: "v1.26.0-4-gee2e3fa8", commit: "ee2e3fa8548fb4cd4945810609bcdd9531946ad6", kubernetes version: "v1.25.0", go version: "go1.18.1", GOOS: "linux", GOARCH: "amd64"

go version : go1.18.1 linux/amd64

protoc version : libprotoc 3.12.4

#### Possible Solution

If I remove the pkg 	"google.golang.org/grpc v1.51.0" & "google.golang.org/protobuf v1.28.1" and do it again.
"make generate" can work properly.

require (
	github.com/go-logr/logr v1.2.3
	k8s.io/apimachinery v0.26.0
	k8s.io/client-go v0.26.0
	sigs.k8s.io/controller-runtime v0.14.1
)

**Comment by davidcheng0922** [comment]
google.golang.org/grpc v1.40 is fine.

**Comment by everettraven** [comment]
@davidcheng0922 Thanks for raising this issue!

Based on the version string:
```
operator-sdk version: "v1.26.0-4-gee2e3fa8", commit: "ee2e3fa8548fb4cd4945810609bcdd9531946ad6", kubernetes version: "v1.25.0", go version: "go1.18.1", GOOS: "linux", GOARCH: "amd64"
```
It seems that you are not using the latest release but manually built from the `master` branch. `v1.26.0` of Operator-SDK is meant to be built with go 1.19 and it seems yours was built with go 1.18.1

If you instead use the latest release of Operator-SDK (`v1.26.0`) and `go 1.19` does the issue still persist? I am suspecting that the problem has to do with the go version mismatch, but can't be sure as I've never encountered this issue myself.

**Comment by davidcheng0922** [comment]
@everettraven Thank you for replying !
I update the go version to 1.19, but the problem still exists.

david@david:~/go/src/test-v2$ make generate
/home/david/go/src/test-v2/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
panic: interface conversion: ast.Expr is *ast.CompositeLit, not *ast.Ident

goroutine 350 [running]:
sigs.k8s.io/controller-tools/pkg/loader.(*referenceCollector).Visit(0xc001e11d90, 0xdc41c0, 0xc002d50228, 0xa79762, 0xdc3f90)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/refs.go:136 +0x14a
go/ast.Walk(0xdbf700, 0xc001e11d90, 0xdc41c0, 0xc002d50228)
        /usr/local/go/src/go/ast/walk.go:52 +0x63
go/ast.walkExprList(0xdbf700, 0xc001e11d90, 0xc002d48830, 0x1, 0x1)
        /usr/local/go/src/go/ast/walk.go:26 +0x9e
go/ast.Walk(0xdbf700, 0xc001e11d90, 0xdc3c48, 0xc002d3fdc0)
        /usr/local/go/src/go/ast/walk.go:137 +0xfc5
go/ast.Walk(0xdbf700, 0xc001e11d90, 0xdc3bd0, 0xc002d4ca80)
        /usr/local/go/src/go/ast/walk.go:146 +0x17a5
go/ast.Walk(0xdbf700, 0xc001e11d90, 0xdc3ae0, 0xc002d4cab0)
        /usr/local/go/src/go/ast/walk.go:156 +0x2d74
go/ast.Walk(0xdbf700, 0xc001e11d90, 0xdc3e28, 0xc002d3fe00)
        /usr/local/go/src/go/ast/walk.go:74 +0xb1f
go/ast.Walk(0xdbf700, 0xc001e11d90, 0xdc3e50, 0xc002d4cae0)
        /usr/local/go/src/go/ast/walk.go:84 +0x156
go/ast.Walk(0xdbf700, 0xc001e11d90, 0xdc4260, 0xc002d50240)
        /usr/local/go/src/go/ast/walk.go:161 +0x2634
sigs.k8s.io/controller-tools/pkg/loader.(*referenceSet).collectReferences(0xc001f47c80, 0xdce0a0, 0xc002d50240, 0xc002b01fe0)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/refs.go:107 +0xbb
sigs.k8s.io/controller-tools/pkg/loader.allReferencedPackages.func1(0xc002d42500, 0xc002d3fe40, 0xc002d4ca20)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/refs.go:164 +0x7b
sigs.k8s.io/controller-tools/pkg/loader.(*typeVisitor).Visit(0xc001fea4f8, 0xdc42d8, 0xc002d4ca20, 0x0, 0x0)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/visit.go:64 +0x151
go/ast.Walk(0xdbf720, 0xc001fea4f8, 0xdc42d8, 0xc002d4ca20)
        /usr/local/go/src/go/ast/walk.go:52 +0x63
go/ast.Walk(0xdbf720, 0xc001fea4f8, 0xdc3f40, 0xc002d3fe40)
        /usr/local/go/src/go/ast/walk.go:331 +0xe89
go/ast.walkDeclList(0xdbf720, 0xc001fea4f8, 0xc001dace00, 0xd, 0x10)
        /usr/local/go/src/go/ast/walk.go:38 +0x9e
go/ast.Walk(0xdbf720, 0xc001fea4f8, 0xdc3e78, 0xc002d42500)
        /usr/local/go/src/go/ast/walk.go:353 +0x2446
sigs.k8s.io/controller-tools/pkg/loader.EachType(0xc002b10aa0, 0xc001fea4e0)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/visit.go:38 +0xaa
sigs.k8s.io/controller-tools/pkg/loader.allReferencedPackages(0xc002b10aa0, 0xc002b01fe0, 0xc002b10aa0, 0x1240860, 0xdc4300)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/refs.go:162 +0x2c5
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc001435e30, 0xc002b10aa0)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/refs.go:249 +0x148
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0xc001c35674, 0xc001435e30, 0xc002b10aa0)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/refs.go:257 +0x5d
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/refs.go:255 +0x1d8
make: *** [Makefile:80: generate] Error 2

david@david:~/go/src/test-v2$ go version
go version go1.19 linux/amd64

**Comment by davidcheng0922** [comment]
@everettraven   Thank you for the reply.
I upgrade the go version to 1.19, but the problem still exists.

FYI
--------------------------------------------------------------------------------------------------
david@david:~/go/src/test-v2$ make generate
/home/david/go/src/test-v2/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
panic: interface conversion: ast.Expr is *ast.CompositeLit, not *ast.Ident

goroutine 350 [running]:
sigs.k8s.io/controller-tools/pkg/loader.(*referenceCollector).Visit(0xc001e11d90, 0xdc41c0, 0xc002d50228, 0xa79762, 0xdc3f90)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/refs.go:136 +0x14a
go/ast.Walk(0xdbf700, 0xc001e11d90, 0xdc41c0, 0xc002d50228)
        /usr/local/go/src/go/ast/walk.go:52 +0x63
go/ast.walkExprList(0xdbf700, 0xc001e11d90, 0xc002d48830, 0x1, 0x1)
        /usr/local/go/src/go/ast/walk.go:26 +0x9e
go/ast.Walk(0xdbf700, 0xc001e11d90, 0xdc3c48, 0xc002d3fdc0)
        /usr/local/go/src/go/ast/walk.go:137 +0xfc5
go/ast.Walk(0xdbf700, 0xc001e11d90, 0xdc3bd0, 0xc002d4ca80)
        /usr/local/go/src/go/ast/walk.go:146 +0x17a5
go/ast.Walk(0xdbf700, 0xc001e11d90, 0xdc3ae0, 0xc002d4cab0)
        /usr/local/go/src/go/ast/walk.go:156 +0x2d74
go/ast.Walk(0xdbf700, 0xc001e11d90, 0xdc3e28, 0xc002d3fe00)
        /usr/local/go/src/go/ast/walk.go:74 +0xb1f
go/ast.Walk(0xdbf700, 0xc001e11d90, 0xdc3e50, 0xc002d4cae0)
        /usr/local/go/src/go/ast/walk.go:84 +0x156
go/ast.Walk(0xdbf700, 0xc001e11d90, 0xdc4260, 0xc002d50240)
        /usr/local/go/src/go/ast/walk.go:161 +0x2634
sigs.k8s.io/controller-tools/pkg/loader.(*referenceSet).collectReferences(0xc001f47c80, 0xdce0a0, 0xc002d50240, 0xc002b01fe0)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/refs.go:107 +0xbb
sigs.k8s.io/controller-tools/pkg/loader.allReferencedPackages.func1(0xc002d42500, 0xc002d3fe40, 0xc002d4ca20)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/refs.go:164 +0x7b
sigs.k8s.io/controller-tools/pkg/loader.(*typeVisitor).Visit(0xc001fea4f8, 0xdc42d8, 0xc002d4ca20, 0x0, 0x0)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/visit.go:64 +0x151
go/ast.Walk(0xdbf720, 0xc001fea4f8, 0xdc42d8, 0xc002d4ca20)
        /usr/local/go/src/go/ast/walk.go:52 +0x63
go/ast.Walk(0xdbf720, 0xc001fea4f8, 0xdc3f40, 0xc002d3fe40)
        /usr/local/go/src/go/ast/walk.go:331 +0xe89
go/ast.walkDeclList(0xdbf720, 0xc001fea4f8, 0xc001dace00, 0xd, 0x10)
        /usr/local/go/src/go/ast/walk.go:38 +0x9e
go/ast.Walk(0xdbf720, 0xc001fea4f8, 0xdc3e78, 0xc002d42500)
        /usr/local/go/src/go/ast/walk.go:353 +0x2446
sigs.k8s.io/controller-tools/pkg/loader.EachType(0xc002b10aa0, 0xc001fea4e0)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/visit.go:38 +0xaa
sigs.k8s.io/controller-tools/pkg/loader.allReferencedPackages(0xc002b10aa0, 0xc002b01fe0, 0xc002b10aa0, 0x1240860, 0xdc4300)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/refs.go:162 +0x2c5
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc001435e30, 0xc002b10aa0)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/refs.go:249 +0x148
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0xc001c35674, 0xc001435e30, 0xc002b10aa0)
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/refs.go:257 +0x5d
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check
        /home/david/go/bin/pkg/mod/sigs.k8s.io/controller-tools@v0.4.1/pkg/loader/refs.go:255 +0x1d8
make: *** [Makefile:80: generate] Error 2

david@david:~/go/src/test-v2$ go version
go version go1.19 linux/amd64
