### ISSUE TITLE
In-Cluster Client configuration is not working

### ISSUE THREAD

**Issue by Obirah** [operator-framework/operator-sdk#6242]
#### What did you do?

I tried to run the operator-sdk image as a Kubernetes Job in order to install OLM with the `operator-sdk olm install` command from within the cluster.

#### What did you expect to see?

I expected the operator-sdk to start the OLM installation.

#### What did you see instead? Under which circumstances?

The operator-sdk is returning the error `Failed to install OLM version \"latest\": failed to get Kubernetes config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable` which is indicating that the Kubernetes client is not configured for in-cluster usage since the pod is running with a ServiceAccount which has proper permissions.

#### Environment

**Operator type:**

Not applicable.

**Kubernetes cluster type:**

AWS EKS with Kubernetes 1.24

`$ operator-sdk version`

1.26.0

`$ go version` (if language is Go)

1.19

`$ kubectl version`

Not applicable.

#### Possible Solution

Make the Kubernetes client that the operator-sdk uses aware of the in-cluster config.

**Comment by Obirah** [comment]
Resolved the issue myself, I am sorry for the spam. I just recently upgraded from 1.23 to 1.24 and from 1.24 the `automountServiceAccountToken` property for pods is false by default, so you have to explicitly set that.

**Comment by everettraven** [comment]
@Obirah Thanks for updating the issue, I'm glad you were able to resolve it!
