### ISSUE TITLE
Upgrade SDK Version

### ISSUE THREAD

**Issue by coriaedu** [operator-framework/operator-sdk#6268]
The documentation update for v1.26.0 went missing.

**Comment by everettraven** [comment]
@coriaedu Thanks for raising this issue! I'm working on getting this fixed

**Comment by coriaedu** [comment]
@everettraven  UPDATE: looks like it is fixed: 

<img width="215" alt="image" src="https://user-images.githubusercontent.com/4521835/215147163-359d9443-da70-4c03-bb16-44145650c679.png">

This morning, instead of showing `v1.26.0`, it was showing all the patch versions of `v1.25.x` instead.

I tried looking into it, but I am not sure how the menu is assembled. :/

I guess this can be closed? Unless we want to see if anything actually changed in the last 30 minutes

**Comment by everettraven** [comment]
This was due to a teeny mistake made in the process of releasing v1.25.4 -  I just had to reset the branch that our site is served from to point to the correct release tag so if it is fixed now we should be good to go!

**Comment by everettraven** [comment]
Closing since it is resolved, but feel free to open this again if it happens again for some reason
