### ISSUE TITLE
Consolidate operator type constants

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-sdk#627]
We use two different sets of constants to define operator types:

One set is used for parsing command line options, which necessarily need to be strings:
https://github.com/operator-framework/operator-sdk/blob/04f1a67a260d18df795f72ab355f5b57b79f6f8e/commands/operator-sdk/cmd/new.go#L80-L81

The other set is used when we detect the type of operator on disk, e.g. for `operator-sdk up local`:
https://github.com/operator-framework/operator-sdk/blob/04f1a67a260d18df795f72ab355f5b57b79f6f8e/commands/operator-sdk/cmd/cmdutil/util.go#L31-L36

As we add more operator types (e.g. helm), we'll have to be careful to add new types to both sets of constants, and keep track what each set is used for.

Does it make sense to consolidate these to the iota-based consts in the `cmdutil` package and add a helper function to the cmdutil package to convert a type string to the constant?

**Comment by shawn-hurley** [comment]
@estroz Should we close this issue after #642 has been merged?

**Comment by hasbro17** [comment]
@estroz Is #648 related to this? Or is that more of a refactoring for the `pkg/scaffold` constants.

**Comment by estroz** [comment]
@hasbro17 refactoring is outside the scope of this issue. Closing as #642 has been merged.
