### ISSUE TITLE
Does operator-sdk support file-based catalogs?

### ISSUE THREAD

**Issue by murphd40** [operator-framework/operator-sdk#6288]
## Type of question

Open question

## Question

I'm adding OLM support to my operator. When running `make catalog-build` I see a warning saying that Sqlite-based catalogs are deprecated. Since this is a new catalog, I don't want to build it with a deprecated technology. What can I do? Thanks!

PS Sorry if this question has been asked before. I searched the issues and couldn't find it.

#### What did you do?

```
operator-sdk init --project-name ${project} --domain ${domain} --repo ${repo}
```

```
$ make catalog-build
```

#### What did you expect to see?

No deprecation warning

#### What did you see instead? Under which circumstances?

```
...
WARN[0000] DEPRECATION NOTICE:
Sqlite-based catalogs and their related subcommands are deprecated. Support for
them will be removed in a future release. Please migrate your catalog workflows
to the new file-based catalog format.
...
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

N/A

`$ operator-sdk version`

```
operator-sdk version: "v1.26.0", commit: "cbeec475e4612e19f1047ff7014342afe93f60d2", kubernetes version: "1.25.0", go version: "go1.19.3", GOOS: "darwin", GOARCH: "arm64"
```

`$ go version` (if language is Go)

N/A

`$ kubectl version`

N/A

**Comment by everettraven** [comment]
@murphd40 Thanks for raising this issue! This is a known issue and we have an existing issue to track this (https://github.com/operator-framework/operator-sdk/issues/5832). Unfortunately we aren't decided on the best way to move forward with implementing a generalized approach and is something we are hoping to come to a decision on as we get more overall feedback on how FBC is utilized in developer workflows.

For the time being, you may be able to modify the make target yourself to use the `opm migrate` command to migrate from the SQLite bundle format to the FBC format.

I hope this helps!

**Comment by murphd40** [comment]
Thanks @everettraven 👍

**Comment by everettraven** [comment]
Closing this issue since FBC support is already tracked in #5832
