### ISSUE TITLE
ClusterServiceVersion Struct for RedHat Certified & OperatorHub

### ISSUE THREAD

**Issue by DanArlowski** [operator-framework/operator-sdk#6289]
## Type of question

General operator-related help 

## Question

What are the `ClusterServiceVersion` structs to verify the RedHat-Certified CSV and the public OperatorHub CSV?

#### What did you do?

Were shifting from a bash script `ClusterServiceVersion` generator 
to a Golang based Generator.
as part of the generation/testing, to make sure we're aligned with the CSV spec,
we're running the  `runtime.DefaultUnstructuredConverter.FromUnstructuredWithValidation`
test from `k8s.io/apimachinery/pkg/runtime`. like so:
```golang
import 	operatorsv1alpha1 "github.com/operator-framework/api/pkg/operators/v1alpha1"
....
	csvStruct := &operatorsv1alpha1.ClusterServiceVersion{}
	err = runtime.
		DefaultUnstructuredConverter.
		FromUnstructuredWithValidation(unstructuredCsv, csvStruct, true)
```

#### What did you expect to see?

geting a spec confirmation to both Red Hat Certified ClusterServiceVersion and the public OperatorHub ClusterServiceVersion.

#### What did you see instead? Under which circumstances?

when testing for the first time we've got the following error:
```
failed to convert from unstructured: strict decoding error: unknown field "metadata.operators.openshift.io/infrastructure-features", unknown field "metadata.operators.openshift.io/valid-subscription"
```

which are of course a valid fields under the [certified operator spec](https://docs.openshift.com/container-platform/4.9/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-manual-annotations_osdk-generating-csvs)
but not so valid under the OpertaorHub :)

#### Environment

**Operator type:**

but not relevant directly :)

**Kubernetes cluster type:**

Openshift & Vanilla

#### Additional context

-

**Comment by everettraven** [comment]
@DanArlowski Thanks for raising this issue! I took a brief look at this, and it looks like you may have placed these values under the wrong field in the `ClusterServiceVersion` type. 

According to this error:
```
failed to convert from unstructured: strict decoding error: unknown field "metadata.operators.openshift.io/infrastructure-features", unknown field "metadata.operators.openshift.io/valid-subscription"
``` 
it looks like when parsing it is expecting a field `metadata.operator` to exist but that is not possible. The [ClusterServiceVersion Go type](https://pkg.go.dev/github.com/operator-framework/api/pkg/operators/v1alpha1#ClusterServiceVersion) uses the [metav1.ObjectMeta type](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#ObjectMeta) for metadata and should have some fields for storing custom key-value pairs (I think labels and annotations). Looking at the [certified operator spec](https://docs.openshift.com/container-platform/4.9/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-manual-annotations_osdk-generating-csvs) you shared, it mentions that these fields you are trying to set should be set under the `metadata.annotations` field.

I *think* simply updating the fields to be under the `metadata.annotations` field should resolve this particular conversion error (no promises you won't run into more :))

I hope this helps!

**Comment by DanArlowski** [comment]
@everettraven
very embarrassing opening an issue due to wrong indentation. 
It should be popping on the PR CI though, as it might be missed by others ( I guess there is not validation on additional fields as part ot the operatorhubs CI )

Thanks!
