### ISSUE TITLE
make bundle throws accumulateFile error and accumulateDirector error

### ISSUE THREAD

**Issue by awsprof** [operator-framework/operator-sdk#6319]
#### What did you do?

Ran the command 

`make bundle IMG="<domain>.com/example-operator:v0.1"`

#### What did you expect to see?

The following output

```
INFO[0001] Creating bundle.Dockerfile                   
INFO[0001] Creating bundle/metadata/annotations.yaml    
INFO[0001] Bundle metadata generated successfully       
operator-sdk bundle validate ./bundle
INFO[0000] All validation tests have completed successfully 
```

#### What did you see instead? Under which circumstances?

```
WARN[0059] Skipping definitions parsing: APIs root dir "api" does not exist 
cd config/manager && /Users/<username>/git/guru-operator-project/bin/kustomize edit set image controller=<domain>.com/example-operator:v0.1
/Users/<username>/git/guru-operator-project/bin/kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version 0.0.1  
Error: accumulating resources: 2 errors occurred:
        * accumulateFile error: "accumulating resources from '../default': '/Users/<username>/git/guru-operator-project/config/default' must resolve to a file"
        * accumulateDirector error: "recursed accumulation of path '/Users/<username>/git/guru-operator-project/config/default': accumulating resources: 2 errors occurred:\n\t* accumulateFile error: \"accumulating resources from '../crd': evalsymlink failure on '/Users/<username>/git/guru-operator-project/config/crd' : lstat /Users/<username>/git/guru-operator-project/config/crd: no such file or directory\"\n\t* loader.New error: \"error loading ../crd with git: url lacks host: ../crd, dir: evalsymlink failure on '/Users/<username>/git/guru-operator-project/config/crd' : lstat /Users/<username>/git/guru-operator-project/config/crd: no such file or directory, get: invalid source string: ../crd\"\n\n"


INFO[0000] Creating bundle.Dockerfile                   
INFO[0000] Creating bundle/metadata/annotations.yaml    
INFO[0000] Bundle metadata generated successfully       
make: *** [bundle] Error 1
```

I understood that the error is being caused by the kustomize tool. 

All within the config folder ...

Then I added the **crd** folder under the config folder with a default **kustomization.yaml**. This got past the first error. However it failed expecting a **default** folder, a **samples** folder and a file called **role.yaml** within the **rbac** folder.

I then added the default folder with an empty kustomization.yaml file, a samples folder with an empty kustomization.yaml file  and an empty role.yaml within the rbac folder.

Ultimately the error went away and I got the following successful message

```
test -s /Users/<username>/git/guru-operator-project/bin/controller-gen || GOBIN=/Users/<username>/git/guru-operator-project/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.10.0
/Users/<username>/git/guru-operator-project/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
operator-sdk generate kustomize manifests -q
WARN[0000] Skipping definitions parsing: APIs root dir "api" does not exist 
cd config/manager && /Users/<username>/git/guru-operator-project/bin/kustomize edit set image controller=<domain>.com/example-operator:v0.1
/Users/<username>/git/guru-operator-project/bin/kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version 0.0.1  
INFO[0001] Creating bundle.Dockerfile                   
INFO[0001] Creating bundle/metadata/annotations.yaml    
INFO[0001] Bundle metadata generated successfully       
operator-sdk bundle validate ./bundle
INFO[0000] All validation tests have completed successfully 
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

k3d cluster

`$ operator-sdk version`

operator-sdk version: "v1.27.0", commit: "5cbdad9209332043b7c730856b6302edc8996faf", kubernetes version: "v1.25.0", go version: "go1.19.5", GOOS: "darwin", GOARCH: "arm64"

`$ go version` (if language is Go)

go version go1.19.6 darwin/arm64

`$ kubectl version`

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:24Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6+k3s1", GitCommit:"9176e03c5788e467420376d10a1da2b6de6ff31f", GitTreeState:"clean", BuildDate:"2023-01-26T00:30:33Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/arm64"}

#### Possible Solution

- Within the config folder, Create default, crd and samples folders with an empty kustomization.yaml file
- Create a role.yaml file within the config/rbac folder

#### Additional context

N/A

**Comment by everettraven** [comment]
@awsprof Thanks for raising this issue! This is a bit of an interesting issue because IIRC these folders and kustomize configurations should be scaffolded by default when running `operator-sdk init ...`. Would you mind sharing the commands you used to generate your project so we can try to diagnose why these files weren't generated by default?

**Comment by awsprof** [comment]
> @awsprof Thanks for raising this issue! This is a bit of an interesting issue because IIRC these folders and kustomize configurations should be scaffolded by default when running `operator-sdk init ...`. Would you mind sharing the commands you used to generate your project so we can try to diagnose why these files weren't generated by default?

Hi @everettraven - These are the following commands I issued when generating the initial scaffold

`
operator-sdk olm install
operator-sdk init --domain <domain>.com --repo github.com/awsprof/memcached-operator --plugins=go/v4-alpha
make bundle IMG="oper-registry.example.com:5000/memcached-operator:v0.0.1"
make bundle-build bundle-push BUNDLE_IMG="oper-registry.example.com:5000/memcached-operator-bundle:v0.0.1"
operator-sdk run bundle oper-registry.example.com:5000/memcached-operator-bundle:v0.0.1 --skip-tls --skip-tls-verify --use-http
`

Further to raising this ticket, I realized that the crd, rbac and samples errors can be ignored (if we create our first api - which then populates these folders). But out of the box scaffolding should not cause any errors in my humble opinion.

I was also following a tutorial on the internet that was outdated. Once I followed all the steps in the original operator-sdk docs, things worked fine. 

A further side-effect that I have see is 

`operator-sdk cleanup memcached-operator`

Does not cleanup my operator at all. Keeps coming back with a memcached-operator not found error.

**Comment by everettraven** [comment]
@awsprof Yeah, I think the expectation is that if you are creating an operator you will be defining a set of apis and controllers. Just running the `operator-sdk init` command only initializes your project structure and it is up to you to call further commands like `operator-sdk create api`. 

I totally agree that the `operator-sdk init` command should produce things that "work", but changing what is scaffolded as part of each command is a much larger ask as it has a significant impact on our users who already expect things to be a specific way upon running a specific command. For now, I think this is something that we will leave as is.

As far as the `operator-sdk cleanup` command not working I'll have to take a look into that.

**Comment by everettraven** [comment]
I'm going to close this issue since the original issue was resolved. If you are still encountering a problem with the `operator-sdk cleanup` command, feel free to create a new issue. Thank you!
