### ISSUE TITLE
Managing different versions of CRD in the operator-idk controller

### ISSUE THREAD

**Issue by akularaja** [operator-framework/operator-sdk#6324]
## Type of question

General operator-related help

#### What did you do?

I have setup a new Operator for this CRD called `foo`. I followed the steps in the Go tutorial, so everything with regards to the Controller is the same as in that tutorial.

`foo` has two versions, `v1alpha1` and `v2beta1`. There are some drastic changes between these version. `v2beta1` has a complete different Spec and Status. Currently, we have another service (another controller that was written from scratch, not using the operator-idk) that operates on the `v1alpha` version. 

I recently added this new `v2beta1` version, and I am in the process of setting up the controller using the operator-idk to reconcile on this version. 

It seems that the `scheme`, `GroupVersion` and all that is setup properly when creating the `Manager` and setting up the controller. 

In the Kube cluster, I have two Foo resources created and deployed, `foo1` and `foo2`. The former is a `v1alpha1` version and the latter is `v2beta1`

In the `Reconcile` method, when I do the following:
```
foo := &v2beta1.Foo{}
err := r.Get(ctx, req.NamespacedName, foo)
...
```

It retrieves `foo1` which is of `v1alpha1` version. Another weird thing is that when I do
```
fmt.Println(foo1.APIVersion)
```
It prints `v2beta1`. 

#### What did you expect to see?

I expect that in the `Reconcile` method, when I do:
```
r.Get(ctx, req.NamespacedName, foo)
```
I only retrieve the `v2beta1` version of the `foo` resources. 

#### What did you see instead? Under which circumstances?

I am seeing that my `Get` call is retrieving both `v1alpha1` and `v2beta1` versions. 

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

vanilla

`$ operator-sdk version`

operator-idk version: "v1.26.0", commit: "cbeec475e4612e19f1047ff7014342afe93f60d2", kubernetes version: "v1.25.0", go version: "go1.19.4", GOOS: "darwin", GOARCH: "arm64"

`$ go version` (if language is Go)

go version go1.18.10 darwin/arm64

`$ kubectl version`

Client Version: v1.24.4

**Comment by varshaprasad96** [comment]
@akularaja In k8s clusters on creation of a resource, the apiserver stores it on a persistent storage called [`etcd`](https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/). Though multiple version are supported, the etcd uses only version when persisting the resources for storage. I suspect that in your case, `v1alpha1` is the storage version. You can check if it is so, by looking at the `storage:` field in CRD. If it is set to true, it means that this is the version in which your resources will be stored in etcd, which is possibly why when you fetch resources you see `v1alpha` objects.

In general, if you have multiple versions, only one should be marked as `storage`, the others must be set to `storage: false`. To be able to use multiple versions you would have to use [conversion webhooks](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-conversion) such that the apiserver knows how to convert objects between 2 versions. More documentation on the same: https://book.kubebuilder.io/multiversion-tutorial/conversion.html
