### ISSUE TITLE
New operator-sdk doesn't work with already generated repositories

### ISSUE THREAD

**Issue by dmage** [operator-framework/operator-sdk#633]
The new operator-sdk binary expects to have ./build/Dockerfile, but it wasn't generated by the previous version of operator-sdk binary. The API is also changed drastically.

What is the migration path for existing operators? Do we have to vendor the operator-sdk tool and forget about updates or are we supposed to rewrite everything from scratch with every new version of operator-sdk?

/cc @bparees @legionus

**Comment by estroz** [comment]
@dmage we're working on documentation to explain the change and help migrate existing projects to the new structure. See #635 for WIP docs.

**Comment by hasbro17** [comment]
Closing this issue since we now have a migration guide on how to update your project to use the new controller-runtime APIs and project structure for v0.1.0:
https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/v0.1.0-migration-guide.md
