### ISSUE TITLE
Pv,PVC helm chart deployment using helm operator facing issue

### ISSUE THREAD

**Issue by annu-mishraa** [operator-framework/operator-sdk#6331]
#### What did you do?

I am trying to deploy pv ,pvc helm chart using helm operator but its nit creating all the persistent volume mentioned. Does it support or not ?

#### What did you expect to see?

I am expecting to create persistentvolumeclaim with the pv and pvc yaml configuration.

#### Environment

**Operator type:**

 language helm

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by varshaprasad96** [comment]
@annu-mishraa Could you please let us know if there are any errors in the logs. If possible could you also share your project so that we can replicate it. Helm operator should support creation of any K8s resources, if not we would need more information to know what's happening.

**Comment by annu-mishraa** [comment]
@varshaprasad96 We could see PV's - & PVC's getting deployed , but pvc's are stuck in pending state and also we see the same chart is getting correctly deployed via helm install and are not in pending state.

kubectl get persistentvolumeclaim -n odim
NAME                        STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
etcd-conf-pvc               Pending                                      manual         34s
etcd-data-pvc               Pending                                      manual         34s
kafka-conf-pvc              Pending                                      manual         34s
kafka-data-pvc              Pending                                      manual         34s
odimra-log-claim            Pending                                      manual         34s
redis-inmemory-data-claim   Pending                                      manual         34s
redis-ondisk-data-claim     Pending                                      manual         34s
zookeeper-conf-pvc          Pending                                      manual         34s
zookeeper-data-pvc          Pending                                      manual         34s
-----------------------------------------------------------------------------------------------------------------------------------
kubectl describe persistentvolumeclaim etcd-conf-pvc -n odim
Name:          etcd-conf-pvc
Namespace:     odim
StorageClass:  manual
Status:        Pending
Volume:
Labels:        app.kubernetes.io/managed-by=Helm
Annotations:   meta.helm.sh/release-name: volumeclame-sample
               meta.helm.sh/release-namespace: odim
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason              Age                            From                         Message
  ----     ------              ----                           ----                         -------
  Warning  ProvisioningFailed  <invalid> (x3 over <invalid>)  persistentvolume-controller  storageclass.storage.k8s.io "manual" not found
