### ISSUE TITLE
`make bundle` exhausts memory and crashes

### ISSUE THREAD

**Issue by npaton** [operator-framework/operator-sdk#6338]
#### What did you do?

Run `make bundle`

#### What did you expect to see?

The bundle to be created.

#### What did you see instead? Under which circumstances?

After adding the metadata interactively (display name, description...), `operator-sdk generate kustomize manifests` starts eating memory until it (quickly, within seconds) exhaust all system memory (~30GB) and crashes.

#### Environment

**Operator type:**

language go

**Kubernetes cluster type:**

vanilla

`$ operator-sdk version`

operator-sdk version: "v1.27.0", commit: "5cbdad9209332043b7c730856b6302edc8996faf", kubernetes version: "1.25.0", go version: "go1.19.5", GOOS: "linux", GOARCH: "amd64"

Also tested with 1.26.0 and 1.24.1.

`$ go version`

go version go1.19.4 linux/amd64

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

#### Possible Solution

🤷‍♂️

#### Additional context

Tested on 2 machines:
- Ubuntu 20.04.5 LTS with 5.4.0-139-generic
- MANJARO  with 5.15.91-1-MANJARO

Tested with:
- controller-gen 0.10.0 and 0.11.3
- kustomize 3.8.7 and 4.5.7

**Comment by madorn** [comment]
Hi @npaton,

Can you please provide the exact steps you ran prior to `make bundle`?

Specifically, the `operator-sdk init` and `operator-sdk create` steps as well as any modifications to your `_types.go` file.

Wondering if you are running into [this bug](https://github.com/operator-framework/operator-sdk/issues/4990) or similar.

**Comment by npaton** [comment]
Hey @madorn. Thank you for pointing that ticket out. I saw it early on and didn't realize it would help me find the issue(s). Sorry for the goose chase.

I've encountered 2 somewhat related issues running `operator-sdk generate kustomize manifests`, both I of which I could work around:
- 2 types sharing the same base name will lead to an infinite loop in the ast traversal (in [`generator.getMarkedChildrenOfField`](https://github.com/operator-framework/operator-sdk/blob/v1.27.0/internal/generate/clusterserviceversion/bases/definitions/ast.go#L96)). In my case, I had a local `ServiceSpec`, and I was importing `k8s.io/api/core/v1.ServiceSpec`, and it was included as a field in the local `ServiceSpec` (whether that's a good idea or not…) Renaming the local `ServiceSpec` to something else bypassed the issue. 
#4990 points to the same problem. It might be stemming from the assumption that `ast.Ident` is always going to point to a local type, while it can actually have a package identifier attached.
- we have a recursive data structure in our spec, which also hits an infinite loop in the same function. The work around here is to no have a recursive structure. I simply created a few layers for our recursive type. It is better this way and I don't know if recursive structures should be supported. But ideally, the generator should not fall into this loop, or maybe even detect the recursive loop and print a warning about it.

I am no longer blocked by this issue. Thank you very much for your help!

Here's a minimal reproducible example for both issues:

```go
import corev1 "k8s.io/api/core/v1"

type MySpec struct {
	ServiceSpec *ServiceSpec `json:"serviceSpec,omitempty"`
	Recursive *Recursive `json:"recursive,omitempty"`
}

type ServiceSpec struct {
	Spec *corev1.ServiceSpec `json:"serviceSpec,omitempty"`
}

type Recursive struct {
	Recursive *Recursive `json:"recursive,omitempty"`
}
```

And the workarounds:

```go
import corev1 "k8s.io/api/core/v1"

type MySpec struct {
	ServiceSpec *MyServiceSpec `json:"myServiceSpec,omitempty"`
	Recursive *Recursive `json:"recursive,omitempty"`
}

type MyServiceSpec struct {
	ServiceSpec *corev1.ServiceSpec `json:"serviceSpec,omitempty"`
}

type Recursive struct {
	Recursive *Recursive2 `json:"recursive,omitempty"`
	Something string `json:"something,omitempty"`
}

type Recursive2 struct {
	Recursive *Recursive3 `json:"recursive,omitempty"`
	Something string `json:"something,omitempty"`
}

type Recursive3 struct {
	Something string `json:"something,omitempty"`
}
```

**Comment by npaton** [comment]
Oh, my apologies, I missed that in the docs! Thank you again for your help. 🙏 

I let you close the issue, or keep it open if you want to track adding to the docs.
