### ISSUE TITLE
Ansible operator limit logging

### ISSUE THREAD

**Issue by sxnguyen** [operator-framework/operator-sdk#6343]
## Type of question

How to implement a specific feature

## Question
Hi,
Currently, I have an Ansible operator deployed, and noticed the logs are stored at
`/tmp/ansible-runner/xxxx`
I want to know if it's possible to limit the number of logs.
I search the operator-sdk documentation and could not find anything.
#### What did you expect to see?
A configurable setting that can control logging either by size or number of logs.

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

`$ operator-sdk version`
1.24.1

`$ go version` (if language is Go)

`$ kubectl version`
1.26

**Comment by varshaprasad96** [comment]
We could control the verbosity of ansible operator logs by using the annotation `ansible.sdk.operatorframework.io/verbosity` in the Custom Resource. Details on the same are here: https://sdk.operatorframework.io/docs/building-operators/ansible/development-tips/#viewing-the-ansible-logs. Also, there is an option to enable/disable the debug logs. Hope this helps!

**Comment by sxnguyen** [comment]
I know about the configuration of the verbosity of Ansible log, but it may not work if there are requirements for the operator pod to implement `ephemeral` request/limit.  Once the `/tmp` dir reach the ephemeral limit, the operator pod get evicted with 
```
Status:       Failed
Reason:       Evicted
Message:      Pod ephemeral local storage usage exceeds the total limit of containers 500Mi.
```
We do not have a reliable way to estimate the size of `/tmp` currently.  
My question is that if it's able to configuration some sort of log rotation (eg: based on number of logs file, base on size , etc..) for Ansible operator.
Thank you,
Scott
