### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by jacobxy** [operator-framework/operator-sdk#6361]
kustomize build config/crd | kubectl apply -f -
Error: must build at directory: not a valid directory: evalsymlink failure on 'config/crd' : lstat /Users/config/crd: no such file or directory

**Comment by everettraven** [comment]
@jacobxy Thanks for raising this issue! I think this typically has to do with the `operator-sdk create api ...` subcommand not being run before attempting to run `make install`.

Would you mind sharing the exact steps you took until you got this error?
