### ISSUE TITLE
`RequeueAfter` doesn't seem to requeue

### ISSUE THREAD

**Issue by dharmit** [operator-framework/operator-sdk#6366]
## Type of question

Open question

## Question
The `RequeueAfter` method doesn't seem to be re-queueing after _x_ number of seconds.

#### What did you do?

I am learning Operators. Taking a cue from [this blog](https://ishankhare.dev/posts/6/), I created an `at` Operator, but using operator-sdk instead of kubebuilder. The code for my operator is available [here](https://github.com/dharmit/at-operator).

The Operator runs a command at the specified time. If it's not yet time to run the command, it does [RequeueAfter](https://github.com/dharmit/at-operator/blob/65fd173929e50ddf00a208514cc5b1f352c0ebe9/controllers/at_controller.go#L76-L79) the amount of time.

Example manifest:
```yaml
apiVersion: at.example.com/v1alpha1
kind: At
metadata:
  name: sample-at
spec:
  schedule: "2023-03-17T10:33:00Z"
  command: "echo hello world"
```

#### What did you expect to see?

I expected the Reconcile loop to be triggered after the remaining number of seconds (~20 seconds in below output):
```
1.6790551601926785e+09	INFO	Schedule parsing done	{"controller": "at", "controllerGroup": "at.example.com", "controllerKind": "At", "At": {"name":"sample-at","namespace":"default"}, "namespace": "default", "name": "sample-at", "reconcileID": "177312e4-157d-4506-a387-2b3aaa024790", "Result": "19.807326069s"}
```
#### What did you see instead? Under which circumstances?

Reconcile loop isn't getting triggered. However, if I modify the manifest using `kubectl edit at sample-at`, it seems to get triggered and create a Pod as I expect it to.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

minikube 1.29.0

`$ operator-sdk version`

1.27.0

`$ go version` (if language is Go)

go version go1.19.5 linux/amd64

`$ kubectl version`
```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```
#### Additional context

- I don't think this is a bug anywhere. It's probably got to do with my understanding of how things work in the Operator world. 
- I also don't think that this is `operator-sdk` specific thingy. The behaviour might very well be the same if I were to use kubebuilder. But I'm posting the question here since I'm trying to learn more about Operator SDK. :)

**Comment by asmacdo** [comment]
I didn't look very closely, but this jumped out at me: https://github.com/dharmit/at-operator/blob/65fd173929e50ddf00a208514cc5b1f352c0ebe9/controllers/at_controller.go#L138'

Could it be that this isn't re-qeueuing because 2006 is in the past?

**Comment by asmacdo** [comment]
Even if that is working as just a layout, you may have better luck hardcoding it to wait 30 seconds to check everything is working as expected.

**Comment by dharmit** [comment]
@asmacdo thanks for your pointers. The 30 seconds idea worked and got me thinking.

Here's the diff that works as I expected:
```diff
@@ -78 +78 @@ func (r *AtReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Re
-                       return ctrl.Result{RequeueAfter: diff * time.Second}, nil
+                       return ctrl.Result{RequeueAfter: diff}, nil

```
The value returned by the function is already of `time.Duration` type. Multiplying it by `time.Second` was preventing the `RequeueAfter` from actually triggering. However, I can't fathom an explanation as to why it wasn't working. 😕

**Comment by dharmit** [comment]
I was finally [able to wrap my head around what's causing this](https://gophers.slack.com/archives/C029RQSEE/p1679129285130729). `time.Second` is an integer constant with value `10^9`. So multiplying `diff` (which is a few seconds), leads to multiplication with `10^9`. Hence, the issue.

@asmacdo thanks for your help. :)

**Comment by asmacdo** [comment]
Fun fact I learned because of this:

Since 1967, the second has been defined as exactly "the duration of 9,192,631,770 periods of the radiation corresponding to the transition between the two hyperfine levels of the ground state of the caesium-133 atom".

https://en.wikipedia.org/wiki/Second
