### ISSUE TITLE
Controller-gen is not upgraded with 'make controller-gen'

### ISSUE THREAD

**Issue by steknowis** [operator-framework/operator-sdk#6368]
#### What did you do?

I am using this configuration for controller-gen as in master:
```Makefile
CONTROLLER_TOOLS_VERSION ?= v0.8.0

.PHONY: controller-gen
controller-gen: $(CONTROLLER_GEN) ## Download controller-gen locally if necessary. If wrong version is installed, it will be overwritten.
$(CONTROLLER_GEN): $(LOCALBIN)
	test -s $(LOCALBIN)/controller-gen && $(LOCALBIN)/controller-gen --version | grep -q $(CONTROLLER_TOOLS_VERSION) || \
	GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-tools/cmd/controller-gen@$(CONTROLLER_TOOLS_VERSION)
```

Installing controller-gen:
```shell
> make controller-gen                           
test -s /Users/ste/go/my-operator/bin/controller-gen && /Users/ste/go/my-operator/bin/controller-gen --version | grep -q v0.8.0 || \
        GOBIN=/Users/ste/go/my-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.8.0

> bin/controller-gen --version
Version: v0.8.0
```

Now I want to upgrade the version of controller-gen to 0.10.0. After setting `CONTROLLER_TOOLS_VERSION ?= v0.10.0`:
```shell
> make controller-gen         
make: Nothing to be done for `controller-gen'.

# still old version
> bin/controller-gen --version
Version: v0.8.0
```

#### What did you expect to see?

As the comment in the Makefile suggests, it should automatically update and override controller-gen

#### What did you see instead? Under which circumstances?

It returns that nothing was done and controller-gen is still installed with old version. Reliably reproducible.
 
#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

OpenShift

`$ operator-sdk version`

`operator-sdk version: "v1.27.0", commit: "5cbdad9209332043b7c730856b6302edc8996faf", kubernetes version: "1.25.0", go version: "go1.19.5", GOOS: "darwin", GOARCH: "amd64"`

`$ go version` (if language is Go)

`go version go1.19.7 darwin/amd64`

`$ kubectl version`

`WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7`

#### Possible Solution

I am not very familiar with Makefiles but I noticed that the command works when executed manually in terminal:
```shell
> test -s bin/controller-gen && bin/controller-gen --version | grep -q v0.10.0 || GOBIN=/Users/ste/go/my-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.10.0

# now it is updated
> bin/controller-gen --version                                                                                                                             
Version: v0.10.0
```

**Comment by acornett21** [comment]
Hi @steknowis thanks for the question. The migration docs for `v1.21.0` already had a fix for this which can be found [here](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.21.0/#for-golang-based-operators--change-makefile-targets-to-replace-go-get-with-go-install). Hope this helps.


Testing below.
```
make controller-gen 
GOBIN=/Users/acornett/go/src/github.com/acornett21/operator-certification-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.8.0
go: downloading golang.org/x/tools v0.1.6-0.20210820212750-d4cc65f0b2ff
go: downloading golang.org/x/sys v0.0.0-20210831042530-f4d43177bf5e
╭─acornett at acornett-mac in ~/go/src/github.com/acornett21/operator-certification-operator on main✘✘✘
╰─± make controller-gen
GOBIN=/Users/acornett/go/src/github.com/acornett21/operator-certification-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.10.0
╭─acornett at acornett-mac in ~/go/src/github.com/acornett21/operator-certification-operator on main✘✘✘
╰─± bin/controller-gen --version
Version: v0.10.0
```
