### ISSUE TITLE
Missing upgrade / migration guide for v1.28.0

### ISSUE THREAD

**Issue by aharbis** [operator-framework/operator-sdk#6379]
### What is the URL of the document?

https://sdk.operatorframework.io/docs/upgrading-sdk-version/

https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.28.0/ <-- doesn't exist

### Which section(s) is the issue in?

**v1.28.0** - missing

### What needs fixing?

There is no `v1.28.0` upgrade / migration guide.

#### Additional context

All other versions, even when no migrations are needed, are accounted for on this page. `v1.28.0` has notable changes with controller-runtime etc. so I'd expect at least some content to exist here, but there is no guide for this version.

**Comment by everettraven** [comment]
@aharbis Thanks for raising this issue!

So it looks like everything was done correctly for the v1.28.0 release but our Netlify deployment failed for the release. Looking into it now.

**Comment by everettraven** [comment]
Kicked the Netlify deployment process off again and it succeeded. I was able to see the v1.28.0 migration guide live now.

Closing this issue since it should be resolved, but feel free to reopen if you are still encountering this issue.

**Comment by aharbis** [comment]
Thanks for the quick fix!
