### ISSUE TITLE
Request to find a WG time that is also CET friendly

### ISSUE THREAD

**Issue by oceanc80** [operator-framework/operator-sdk#6380]
There are members of the community who are in the Central European Timezone who would like to participate in our working group meetings. 
Is it possible to do a poll to identify a time that works for more people to participate in our meetings?

**Comment by jberkhahn** [comment]
i'll see if i can set up something on the google group

**Comment by jberkhahn** [comment]
So, based on the poll the most available meeting time is the current one (11 AM PST). We could maybe move it to 9 AM pst without too much trouble based on the responses to the poll, but based on discussion in the group meeting today several people have conflicting meetings at that time? I don't think we can really find a better time than it is now, unfortunately :/
