### ISSUE TITLE
certificate issue with kubebuilder.io breaks sanity/docs (pull_request) CI

### ISSUE THREAD

**Issue by grokspawn** [operator-framework/operator-sdk#6387]
## Bug Report

We're seeing consistent failures in this CI task for PRs with errors like 

```
  *  External link https://master.book.kubebuilder.io/plugins/creating-plugins.html failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL peer certificate or SSH remote key was not OK
```

Attempting to reach those links in a browser w/o a specific security exemption for the `kubebuilder.io` domain yields a message that the certificate for the domain is only valid for names `*.netlify.app` and `netlify.app`.  
It looks like maybe someone pushed the wrong cert to their server, or that they were using netlify perhaps for doc previews and ended up overwriting the main domain cert somehow. 

The whois info for the domain is the usual .io garbage, but I see that they have channel #kubebuilder in the k8s slack, so I'll try to scare up an admin over there.   Edit:  [slack message](https://kubernetes.slack.com/archives/CAR30FCJZ/p1680548083640599). 

Interestingly enough, the issue is ONLY for master.book.kubebuilder.io subdomain, and the same URI without 'master' (e.g. book.kuberbuilder.io) seems to have identical content.  

I've asked for guidance on that forum.

**Comment by grokspawn** [comment]
Applying a very brute force comparison, there are some subtle differences between master.book.* and book.* domains. 

Using a bash snippet
```bash
for i in `find . -type f -exec grep -i master.book.kubebuilder.io {} \; | sed -e 's/^.*https:\(.*\)\.html.*$/https:\1.html/'| sort -u` ; do j=`echo $i | sed -e 's/master\.//'`; mkdir -p /tmp/kubebuilder.io/master.book /tmp/kubebuilder.io/book; pushd /tmp/kubebuilder.io/master.book; curl --insecure -O $i; popd; pushd /tmp/kubebuilder.io/book; curl -O $j; popd; done
```

to pull all the master.book.kubebuilder.io URIs out of a local copy of the repo, fetching their variants from each domain into a tree that looks like 
```tree
/tmp/kubebuilder.io
├── book
│   ├── creating-plugins.html
│   ├── deploy-image-plugin-v1-alpha.html
│   ├── grafana-v1-alpha.html
│   ├── plugins.html
│   ├── project-config.html
│   ├── tutorial.html
│   └── v2vsv3.html
└── master.book
    ├── creating-plugins.html
    ├── deploy-image-plugin-v1-alpha.html
    ├── grafana-v1-alpha.html
    ├── plugins.html
    ├── project-config.html
    ├── tutorial.html
    └── v2vsv3.html
```

The changes can be classified as

1. master.book.* sidebar scrollbox has a hidden 6.1.3.1 entry called `kustomize/v1 (Deprecated)` which is called `kustomize/v1` in book.*
2. master.book.* sidebar scrollbox has a 6.1.1.3 entry called `go/v4` which is called `go/v4-alpha` in book.*
3. master.book.*/creating-plugins.html refers to `go/v4` which is called `go/v4-alpha` in book.*
4. master.book.*/project-config.html is missing a project config present in book.*
5. master.book.*/v2vsv3.html refers to a plugin for apple wilicon using `go/v4` which is called `go/v4-alpha` in book.*, and book.* also has references to how the go/v4-alpha plugin is unstable.

The original thesis was that we could satisfy the certificate domain problem by switching which domain we sourced kubebuilder docs, but this looks increasingly nontrivial and opinionated. 

Need to get more kubebuilder team info on this one to proceed.

**Comment by camilamacedo86** [comment]
What we can do here is replace the master branch link with the official/public docs.
That means: 
- Replace: https://master.book.kubebuilder.io/plugins/creating-plugins.html
- With: https://book.kubebuilder.io/plugins/plugins.html

**Comment by varshaprasad96** [comment]
If the specific links mentioned in the SDK docs do not dwell with these changes, when an immediate fix would be to just change the domain. However, the long term solution is to renew the certificates for which we have no idea on who owns it.

**Comment by varshaprasad96** [comment]
Its fixed. The CI for failing PRs need to be restarted. Just checked on [this](https://github.com/operator-framework/operator-sdk/actions/runs/4672370579/jobs/8318418792) one, and looks like all the KB links are working.

**Comment by kensipe** [comment]
It is believed this is resolved but needs some verification... we are needing to kick off several CI builds to confirm

**Comment by varshaprasad96** [comment]
Fixed in KB. Had to renew the certs, the links work now.
