### ISSUE TITLE
How to remove the persistent volume claim (pvc) created for stateful set?

### ISSUE THREAD

**Issue by TristanCacqueray** [operator-framework/operator-sdk#6390]
## Type of question

General operator-related help.

#### What did you do?

- I created a go based operator for a resource named SoftwareFactory (SF).
- This operator creates a StatefulSet with a VolumeClaimTemplates using this implementation: https://github.com/softwarefactory-project/sf-operator/blob/b57908ffc5de72a4d107dd7c2ecad1a3d0bb2a0d/controllers/utils.go#L274-L332
- The StatefulSet has the ownerReference set to the new SF resource (using `controllerutil.SetControllerReference`)
- I apply the test SF resource and run the operator with `make run`.
- Running `kubectl get pvc` shows a new pvc bound to the statefulset created by the operator.
- I remove the test SF resource.

#### What did you expect to see?

I expected the pvc to be removed.

#### What did you see instead? Under which circumstances?

The pvc is left-over, and doing a re-deployment re-use the pvc and the data created previously.

So the question is: how to ensure a new SF resource uses a new empty PVC.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

microshift version 4.12

`$ operator-sdk version`

operator-sdk version: "v1.22.0", commit: "9e95050a94577d1f4ecbaeb6c2755a9d2c231289", kubernetes version: "1.24.1", go version: "go1.18.3", GOOS: "linux", GOARCH: "amd64"

`$ go version`

go version go1.19.3 linux/amd64

`$ kubectl version`

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"b05f7d40f9a2dac30771be620e9e9148d26ffd07", GitTreeState:"clean", BuildDate:"2023-02-28T00:59:02Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"77bec7ab3573494f228fbaa4967c76e3d2df0fb3", GitTreeState:"clean", BuildDate:"2022-12-22T12:54:23Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

#### Additional context

Here is what I tried:

-  Add the owner reference to the pvc template.

That fails with: `FailedCreate   statefulset-controller   create Pod gerrit-0 in StatefulSet gerrit failed error: failed to create PVC gerrit-gerrit-0: persistentvolumeclaims "gerrit-gerrit-0" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>`

The failure seems to be caused by https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement

The operator framework suggestion ( https://sdk.operatorframework.io/docs/faqs/#after-deploying-my-operator-why-do-i-see-errors-like-is-forbidden-cannot-set-blockownerdeletion-if-an-ownerreference-refers-to-a-resource-you-cant-set-finalizers-on- ) doesn't seem to work for PVC, e.g. even after authorizing the service account to create/update/delete pvcs and pvcs/finalizer.

- https://kubernetes.io/blog/2021/12/16/kubernetes-1-23-statefulset-pvc-auto-deletion/

As proposed in: https://softwarefactory-project.io/r/c/software-factory/sf-operator/+/27978 . That doesn't work either, perhaps because microshift is missing the StatefulSetAutoDeletePVC feature gate.

**Comment by jberkhahn** [comment]
So, I think this is intended behavior on Kubernetes' part - PVCs are supposed to be Persistent so they don't get cleaned up via owner references when the parent object is removed. You could add intentional logic to your reconciliation loop to manually remove the PVC.

**Comment by kensipe** [comment]
this is expected behavior... @TristanCacqueray looking to hear from you to see if you need any additional help / support.

**Comment by TristanCacqueray** [comment]
Thank you for confirming this is the expected behavior. I guess we'll have to handle the PVC removal manually. Could this be documented somewhere though? It is a bit surprising that a deployment may re-use left-over data after a delete/apply cycle.

**Comment by OchiengEd** [comment]
Hi @TristanCacqueray, the pvc created by a StatefulSet `volumeClaimTemplate` is considered stable storage and would not be deleted when the statefulset is deleted. This is  how StatefulSets are expected to behave as ships with Kubernetes. 

This is documented in the [Kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/). Specifically, the [VolumeClaimTemplates](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#volume-claim-templates) and [Stable storage](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-storage) sections.

The good news is there is a feature that is expected to be beta in Kubernetes 1.17 which will allow for the user to set the desired behavior when the statefulset is either deleted or scaled down. See [https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention) for more information on this.
