### ISSUE TITLE
kubectl apply -f config/samples/cache_v1alpha1_memcached.yaml not work

### ISSUE THREAD

**Issue by t00350320** [operator-framework/operator-sdk#6404]
reference "https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/"
env:
1)operator-sdk version
operator-sdk version: "v1.26.1", commit: "4582a8414e65f40ebea65c74729f121e1f3e3b9a", kubernetes version: "1.25.0", go version: "go1.19.5", GOOS: "linux", GOARCH: "amd64"

2)go version go1.20.3 linux/amd64
3)Kustomize Version: v4.5.7
4)kind v0.17.0 go1.19.2 linux/amd64

local k8s env, 
when execute as testdata's config files , memcached-operator-controller seems work,
```
memcached-operator-system   memcached-operator-controller-manager-6587fdd7f4-zgp2g   2/2     Running   0          16m
```
but "kubectl apply -f config/samples/cache_v1alpha1_memcached.yaml " not create any deployment service about memcached, nothing changed and no logs pop up from pod "memcached-operator-controller-manager-6587fdd7f4-zgp2g "

**Comment by emmajiafan** [comment]
@t00350320  Could you help provide your operator's controllers/memcached_controller.go file and the logs of manager container please?

$ kubectl logs memcached-operator-controller-manager-6587fdd7f4-zgp2g -c manager
