### ISSUE TITLE
Need information on licensing requirement for operator-sdk generated boiler plate code

### ISSUE THREAD

**Issue by hkumar00** [operator-framework/operator-sdk#6420]
## Type of question

General operator-related help

#### What did you do?

I am using operator-sdk to write a custom operator that helps manage certain resources in our cluster.
Operator-sdk generated some code which I accordingly modified.

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

#### Additional context

I need some information from the contributors on licensing of code generated by operator-sdk. I am aware that operator-sdk itself is licensed under Apache-2.0. But for the manifest files generated by sdk under config folder does not keep any license markings.
Can you please help clarify if the generated code and manifests also come under Apache-2.0 ?

**Comment by varshaprasad96** [comment]
This was brought up in the community meeting, but we didn't have much context on the licensing intricacies. Raising this issue in the K8s #operator-sdk dev channel.

**Comment by varshaprasad96** [comment]
The issue has been replied in the slack thread which is linked in the previous comment, hence closing the issue. @hkumar00 please feel free to reopen if you have any other questions. Thanks!

**Comment by varshaprasad96** [comment]
@hkumar00 based on the discussion, here are a few inputs. Hope these answer your question:
- There is a `--license` flag in the [tool](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#create-a-new-project) which could be used while scaffolding the boilerplate for the project. 
- The code written on top of the boilerplate can be further used until the original notices are preserved.
- It is ultimately unto the plugin authors to license the code under any location of the repository (including config/ files).
