### ISSUE TITLE
ansible-operator: Add Leader Election Resource Lock Options 

### ISSUE THREAD

**Issue by IzzyMusa** [operator-framework/operator-sdk#6427]
#### Describe the problem you need a feature to resolve.

Currently, the Ansible operator lacks options to customize the leader election resource lock behavior. This limits the flexibility of the operator and prevents users from adjusting lease duration and renew deadline according to their specific needs.

#### Describe the solution you'd like.

Introduce ```--leader-elect-lease-duration``` flag to allow users to define the duration that non-leader candidates will wait to force acquire leadership. The default duration is set to 15 seconds.
Introduce ```--leader-elect-renew-deadline flag```, enabling users to set the renew deadline, which determines the duration that the acting control plane will retry refreshing leadership before giving up. The default duration is set to 10 seconds.

**Comment by IzzyMusa** [comment]
I created a [PR](https://github.com/operator-framework/operator-sdk/pull/6426). Please let t me know if any further modifications are required.

**Comment by oceanc80** [comment]
https://github.com/operator-framework/operator-sdk/pull/6426 merged, so closing this
