### ISSUE TITLE
Support updating status subresource

### ISSUE THREAD

**Issue by jsafrane** [operator-framework/operator-sdk#643]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I did not find a way how an operator can set status subresource of a CR it manages. `sdk.Update` does not update status if it is declared as a subresource.

**Describe the solution you'd like**
I know you're moving to controller-runtime and it has `StatusWriter` interface, so it's most probably going to be fixed by that. Posting here just to make sure an operator has access to the interface when that change happens.

**Comment by shawn-hurley** [comment]
@jsafrane the change to controller runtime happened in PR #615 I am going to close this as it is accessible by as you stated by `client.Status().Update(ctx, object)`
