### ISSUE TITLE
operator-sdk run bundle giving  `FATA[0120] Failed to run bundle: error waiting for CSV to install: timed out waiting for the condition`

### ISSUE THREAD

**Issue by kavyamani596** [operator-framework/operator-sdk#6432]
#### What did you do?
1.I have a operator in working condition, I wanted to use OLM to create bundle and run it.
2.I created bundle and pushed it to private registry
3.I used `operator-sdk run bundle  --use-http xx.xx.xx.xx:<port>/abc/operator-bundle:v1.0.0` to pull the image and run the bundle

#### What did you expect to see?
1. Expected to see OLM successfully installing operator

#### What did you see instead? Under which circumstances?
Encountered this error

hxs@kavya-node1: ~ /operators/old/operator/bundle/manifests$ operator-sdk run bundle --use-http xx.xx.xx.xx:5000/abc/operator-bundle:v1.0.0
INFO[0008] Creating a File-Based Catalog of the bundle "xx.xx.xx.xx:5000/abc/operator-bundle:v1.0.0"
INFO[0008] Generated a valid File-Based Catalog
INFO[0013] Created registry pod: xx-xx-xx-xx-5000-abc-operator-bundle-v1-0-0
INFO[0013] Created CatalogSource: server-operator-catalog
INFO[0013] OperatorGroup "operator-sdk-og" created
INFO[0013] Created Subscription: operator-v1-0-0-sub
INFO[0019] Approved InstallPlan install-94dwx for the Subscription: operator-v1-0-0-sub
INFO[0019] Waiting for ClusterServiceVersion "default/operator.v1.0.0" to reach 'Succeeded' phase
INFO[0019]   Waiting for ClusterServiceVersion "default/operator.v1.0.0" to appear
FATA[0120] Failed to run bundle: error waiting for CSV to install: timed out waiting for the condition
hxs@kavya-node1:~/operators/old/operator/bundle/manifests$

#### Environment

**Operator type:**

**operator-sdk version**
operator-sdk version: "v1.28.0-5-gaf140625", commit: "af14062577914e4c79c77d8a31d2cf808e5ed76b", kubernetes version: "v1.26.0", go version: "go1.19", GOOS: "linux", GOARCH: "amd64"

 **kubectl version**
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:12:04Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}

#### Additional context
An additional question, is there a way to run the bundle without pushing it to the docker registry?
Since `operator-sdk run bundle` always tries to pull the image
**operator-sdk run bundle ./bundle**
FATA[0000] Failed to run bundle: pull bundle image: error pulling image ./bundle: error resolving name for image ref ./bundle: object required

**Comment by varshaprasad96** [comment]
@kavyamani596 We currently do not support running of bundles without pushing it to a registry endpoint. Regarding the error mentioned previously, based on the logs that have been provided, we guess that a local registry is being used. Does the cluster have access to pull the image from the registry endpoint which you have provided. Also could you share if the install plan or the csv prints out any errors in their statuses?

**Comment by kavyamani596** [comment]
@varshaprasad96 , yes I have used a local registry, pushed and pulled from there. Yes the cluster has the permissions.
 >>Waiting for ClusterServiceVersion "default/operator.v1.0.0" to appear --> actually the csv didnt even get created
 
hxs@kavya-node1: ~ kubectl get csv 
No resources found in default namespace.

**Comment by kavyamani596** [comment]
@varshaprasad96 ,
So i did this,
1.operator-sdk run bundle --use-http xx.xx.xx.xx:5000/abc/operator-bundle:v1.0.0
2.Applied operator.clusterserviceversion.yaml from operator/bundle/manifests

saw this change

hxs@kavya-node1: ~ /operators/old/operator/bundle/manifests$ operator-sdk run bundle --use-http xx.xx.xx.xx:5000/abc/operator-bundle:v1.0.0
INFO[0008] Creating a File-Based Catalog of the bundle "xx.xx.xx.xx:5000/abc/operator-bundle:v1.0.0"
INFO[0008] Generated a valid File-Based Catalog
INFO[0013] Created registry pod: xx-xx-xx-xx-5000-abc-operator-bundle-v1-0-0
INFO[0013] Created CatalogSource: server-operator-catalog
INFO[0013] OperatorGroup "operator-sdk-og" created
INFO[0013] Created Subscription: operator-v1-0-0-sub
INFO[0019] Approved InstallPlan install-94dwx for the Subscription: operator-v1-0-0-sub
INFO[0019] Waiting for ClusterServiceVersion "default/operator.v1.0.0" to reach 'Succeeded' phase
INFO[0019] Waiting for ClusterServiceVersion "default/operator.v1.0.0" to appear
**INFO[0029]   Found ClusterServiceVersion "server-op/server-operator.v1.0.0" phase: Pending**
FATA[0120] Failed to run bundle: error waiting for CSV to install: timed out waiting for the condition
hxs@kavya-node1:~/operators/old/operator/bundle/manifests$

**Comment by kavyamani596** [comment]
I see this in status of csv:

status:
    cleanup: {}
    conditions:
    - lastTransitionTime: "2023-05-26T11:02:31Z"
      lastUpdateTime: "2023-05-26T11:02:31Z"
      message: requirements not yet checked
      phase: Pending
      reason: RequirementsUnknown
    - lastTransitionTime: "2023-05-26T11:02:31Z"
      lastUpdateTime: "2023-05-26T11:02:31Z"
      message: one or more requirements couldn't be found
      phase: Pending
      reason: RequirementsNotMet
    lastTransitionTime: "2023-05-26T11:02:31Z"
    lastUpdateTime: "2023-05-26T11:02:31Z"
    message: one or more requirements couldn't be found
    phase: Pending
    reason: RequirementsNotMet
   requirementStatus:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      message: CRD is not present
      name: someObject.infra
      status: NotPresent
      version: v1
  - group: ""
      kind: ServiceAccount
      message: Service account does not exist
      name: abc_nscontroller-manager
      status: NotPresent
      version: v1


Could you please let me know how I can apply the service account because it has been merged with the namespace

**Comment by kavyamani596** [comment]
@varshaprasad96 
I stumbled on this https://github.com/operator-framework/operator-lifecycle-manager/issues/1174 thread, so when I checked the install plan, I found this 


conditions:
      - message: bundle contents have not yet been persisted to installplan status
        reason: BundleNotUnpacked
        status: "True"
        type: BundleLookupNotPersisted
      - lastTransitionTime: "2023-05-29T05:42:12Z"
        message: 'unpack job not completed: Unpack pod(abc/fc48695709a92967310055e62137e7feea4c98671f2c13c1e98918cfc2xjxlj)
          container(pull) is pending. Reason: ImagePullBackOff, Message: Back-off
          pulling image "xx.xx.xx.xx:5000/odimra/server-operator-bundle:v1.0.0"'
        reason: JobIncomplete
        status: "True"
        type: BundleLookupPending
      - lastTransitionTime: "2023-05-29T05:52:12Z"
        message: Job was active longer than specified deadline
        reason: DeadlineExceeded
        status: "True"
        type: BundleLookupFailed


and then when I described the pod fc48695709a92967310055e62137e7feea4c98671f2c13c1e98918cfc2xjxlj

I saw this msg

error="failed to do request: Head \"https://xx.xx.xx.xx:5000/v2/abc/operator-bundle/manifests/v1.0.0\": http: server gave HTTP response to HTTPS client" host="xx.xx.xx.xx:5000"
FATA[0000] Failed to run bundle: pull bundle image: error pulling image xx.xx.xx.xx:5000/abc/operator-bundle:v1.0.0: error resolving name for image ref xx.xx.xx.xx:5000/abc/operator-bundle:v1.0.0: failed to do request: Head "https://xx.xx.xx.xx:5000/v2/abc/operator-bundle/manifests/v1.0.0": http: server gave HTTP response to HTTPS client

the registry i'm using is a http server, hence ive used 
operator-sdk run bundle  **--use-http** xx.xx.xx.xx:<port>/abc/operator-bundle:v1.0.0

still im facing this pull issue.. could you please let me know if this feature will pull from a http server
cause its description mentions so: 
**--use-http                                  use plain HTTP for container image registries while pulling bundles**

**Comment by SaranyaMeiyyappan** [comment]
I am facing the same issue. My error logs are below. Can anyone help me with the fix.

![image](https://github.com/operator-framework/operator-sdk/assets/18000346/ae847381-b44c-46e0-a1c6-3e60a925adee)

@varshaprasad96 @kavyamani596
