### ISSUE TITLE
Sanity/Docs CI check is failing

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-sdk#6434]
## Bug Report
The sanity/docs CI check is failing on a 404 to this repository settings tab because of the release guide in our docs.

#### What did you do?
sanity/docs CI check was run against a PR

#### What did you expect to see?
sanity/docs check passes

#### What did you see instead? Under which circumstances?
sanity/docs check fails consistently with the following broken link message:
```
 - /target/docs/contribution-guidelines/releasing/index.html
  *  External link https://github.com/operator-framework/operator-sdk/settings/access failed: 404 No error
```

**Comment by varshaprasad96** [comment]
For now we can remove the link and specify the steps to lock the respective branch in detail in the contributing guide. 

If there is time, it would be helpful if someone could look into the script for link checker and probably create an option to whitelist a set of links.
