### ISSUE TITLE
Add documentation for metrics  

### ISSUE THREAD

**Issue by LiliC** [operator-framework/operator-sdk#644]
We should have more documentation about how to best handle metrics and how to use the `ExposeMetricsPort()` and `GenerateServiceMonitor()` helper functions.

Currently blocked until metrics PR land in controller-runtime.

**Comment by primeroz** [comment]
@LiliC Is anything happening on this documentation ? I might have just misunderstood the whole thing but an operator I use was updated to version "0.6.0" of the sdk and looking at https://github.com/operator-framework/operator-sdk/pull/786 It should now expose Metrics

```
kubectl logs vault-operator-5df59cfdff-99t4p | grep sdk   
{"level":"info","ts":1554476387.2531166,"logger":"cmd","msg":"operator-sdk Version: v0.6.0"}
```

I can see port 8080 listening but i get no metrics out of it 
```
~ $ wget localhost:8080/metrics -O-
Connecting to localhost:8080 (127.0.0.1:8080)

~ $
```

Is there anything i need to do to get those metrics ?

**Comment by LiliC** [comment]
@primeroz Hello, there is already documentation, I guess we forgot to close this issue. Default metrics are exposed on port `:8383`. Let me know if this works or if you are running into any more problems.

https://github.com/operator-framework/operator-sdk/tree/master/doc/user/metrics
