### ISSUE TITLE
v1.28.1 operator-sdk version fails on scorecard execution

### ISSUE THREAD

**Issue by sarroutbi** [operator-framework/operator-sdk#6448]
#### What did you do?

I executed the `operator-sdk scorecard` test with v1.28.1 version. To do so, I executed:
```bash
operator-sdk scorecard --wait-time=2m quay.io/sec-eng-special/tang-operator-bundle:v0.0.27
...
FATA[0121] error running tests context deadline exceeded 
```

#### What did you expect to see?

I would expect scorecard command to execute appropriately

#### What did you see instead? Under which circumstances?

I see the command is timing out. Apart from that, it seems there are issues on scorecard pods start up:

```bash
 $ oc get pods
NAME                  READY   STATUS                  RESTARTS   AGE
scorecard-test-5c8j   0/1     Init:ImagePullBackOff   0          4m54s
....
scorecard-test-zpld   0/1     Init:ImagePullBackOff   0          4m54s
```
When describing any of the pods that are failing, it is found that the scorecard images are not retrievable:
```bash
$ oc describe pod scorecard-test-5c8j
  Normal   Pulling    27s (x2 over 44s)  kubelet            Pulling image "quay.io/operator-framework/scorecard-untar@sha256:56c88afd4f2
0718dcd4d4384b8ff0b790f95aa4737f89f3b105b5dfc1bdb60c3"
  Warning  Failed     24s (x2 over 41s)  kubelet            Failed to pull image "quay.io/operator-framework/scorecard-untar@sha256:56c8
8afd4f20718dcd4d4384b8ff0b790f95aa4737f89f3b105b5dfc1bdb60c3": rpc error: code = Unknown desc = Error response from daemon: manifest for
 quay.io/operator-framework/scorecard-untar@sha256:56c88afd4f20718dcd4d4384b8ff0b790f95aa4737f89f3b105b5dfc1bdb60c3 not found: manifest 
unknown: manifest unknown
  Warning  Failed     24s (x2 over 41s)  kubelet            Error: ErrImagePull
  Normal   BackOff    12s (x2 over 40s)  kubelet            Back-off pulling image "quay.io/operator-framework/scorecard-untar@sha256:56
c88afd4f20718dcd4d4384b8ff0b790f95aa4737f89f3b105b5dfc1bdb60c3"
```
If I downgrade version to v1.26.1, scorecard tests work appropriately. I have also verified that v1.28.0 also works. So this seems to be an issue introduced in v1.28.1.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

Minikube

```bash
$ operator-sdk version
operator-sdk version: "v1.28.1", commit: "b05f6a56a176a98b7d92c4d4b36076967e0d77f7", kubernetes version: "1.26.0", go version: "go1.19.8", GOOS: "linux", GOARCH: "amd64"
```

```bash
$ go version
go version go1.20.4 linux/amd64
```

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.4", GitCommit:"f89670c3aa4059d6999cb42e23ccb4f0b9a03979", GitTreeState:"archive", BuildDate:"2023-04-16T00:00:0
0Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z
", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```
#### Additional context
As mentioned before, it seems an issue particular to version v1.28.1. If I downgrade version to v1.26.1, scorecard tests work appropriately. I have also verified that v1.28.0 also works fine. So this seems to be an issue introduced in v1.28.1.

Example of the issue running on Github action:
https://github.com/latchset/tang-operator/actions/runs/5077685755/jobs/9121259717?pr=100

**Comment by acornett21** [comment]
This is a known issue and PR's have been raised to address this and will be fixed in 1.29 release. The root case is that the release process, re-relates the  `scorecard-untar` and `scorecard-storage` images, so the `shas` referenced in 1.28.1 no longer exist in quay.

**Comment by sarroutbi** [comment]
Hello @acornett21. Thanks for your quick response. May I leave the issue opened until v1.29 version is released? Do you prefer me to close taking into account that PRs are already raised?

**Comment by acornett21** [comment]
@sarroutbi I've tested 1.29 and this issue should be resolved. Please let us know if you are seeing different. I'm not a maintainer, so I don't have access to close.
