### ISSUE TITLE
Helm operator versions upgrading documentation

### ISSUE THREAD

**Issue by ricosega** [operator-framework/operator-sdk#6470]
Hi there,

Just been trying now the Operator built with Helm and I cannot find the operative to work with it and versioning.
When you start the project you run the command:
```
operator-sdk create api --helm-chart test --helm-chart-repo=https://chart.url --helm-chart-version 1.0.0
```
So it downloads the specified chart version.
But, what are the steps to follow when the chart must be updated?
Should we remove the content of `charts/test` and download new version and untar the content again in that path?

**Comment by varshaprasad96** [comment]
In helm-operators, each chart version can be considered like a version of Custom Resource. The operator manages and reconciles the chart. So updating to a new of version of chart, means that a new version of api in the operator project is getting created. The new chart version would translate to a new API version, which means we would have to scaffold a multi-version operator project if you would like to have both the chart versions. More on multi-version API projects and steps to scaffold it can be found here: https://book.kubebuilder.io/multiversion-tutorial/tutorial.html. If you would like to completely remove the old version, then rescaffolding is the only option.
