### ISSUE TITLE
missing upgrade docs for v1.30.0

### ISSUE THREAD

**Issue by aharbis** [operator-framework/operator-sdk#6480]
### What is the URL of the document?

https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.30.0/

### Which section(s) is the issue in?

![image](https://github.com/operator-framework/operator-sdk/assets/20443310/bd3052d2-9827-43e5-91c0-599b8c332fb6)

### What needs fixing?

Migration docs are missing for `v1.30.0`.

#### Additional context

https://github.com/operator-framework/operator-sdk/releases/tag/v1.30.0

**Comment by everettraven** [comment]
@aharbis Thanks for bringing this up! I don't think there are actually any migrations for the 1.30.0 release and a changelog slipped through with our changelog migration template text populated. I'll look into getting the page updated and redeployed to prevent future confusion

**Comment by aharbis** [comment]
Just a quick note that this issue still exists.
