### ISSUE TITLE
Best Practices: Should there be a section that talks about support k8s resources like configmap, secrets, PVs etc etc

### ISSUE THREAD

**Issue by alberttwong** [operator-framework/operator-sdk#6484]
node affinity and taints, TLS certs.

The problem I see is that I see some operators don't support those options.  I feel that it would have been better that they should have these configuration options in the v1 of their operator.

**Comment by alberttwong** [comment]
'm talking about configmaps, secrets, PVs, node affinity, taints, TLS certs, maybe even other items like chaos monkey, being able to use telepresense, toplogy aware routing, limit ranges, resource quotas, controlling pod to node assignment, autoscaler?

**Comment by everettraven** [comment]
@alberttwong Thanks for raising this issue! I'm a little lost as to what kind of documentation you are looking to be added, would you mind elaborating a bit more about what content you would like to see for this topic?

**Comment by alberttwong** [comment]
I would love to see also recommendations on what the operator should have in terms of capability.   I've seen operators built without the ability to add configmaps or secrets or even using PVs or even supporting TLS certs.   I'm afraid that many operators developers think that just using the SDK is enough to be called an "operator".

**Comment by varshaprasad96** [comment]
@alberttwong We already have an operator capability model which decides on the level of maturity of an operator. 

> I feel that it would have been better that they should have these configuration options in the v1 of their operator.

I believe what you are looking for is to mention the set of actions in terms resource limitations, network configurations, storage options etc so as to define an operator to be entirely stable and of the highest capability. To do so we already have a model defined which defines the list of functionalities an operator needs to implement for it to be considered matured (https://sdk.operatorframework.io/docs/overview/operator-capabilities/). For example, an operator being able to collect metrics and provide insights would be a level IV operator - the method in which it is implemented could be using prometheus and grafana or through any other 3rd party solution (say Sensu or Scope)
