### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by PureRaidenCloud** [operator-framework/operator-sdk#6488]
## What is the URL of the document?
https://v1-30-x.sdk.operatorframework.io/docs/building-operators/golang/installation/#additional-prerequisites
## Which section(s) is the issue in?
![image](https://github.com/operator-framework/operator-sdk/assets/63286100/11771ced-1daa-4b3c-b4cc-9a57c27b7f00)

## What needs fixing?

Version of Go should be 1.19 instead of 1.18
## Additional context
```shell
$ go version
go version go1.18.3 linux/amd64

$ operator-sdk version
operator-sdk version: "v1.30.0", commit: "b794fe909abc1affa1f28cfb75ceaf3bf79187e6", kubernetes version: "1.26.0", go version: "go1.19.10", GOOS: "linux", GOARCH: "amd64

$ operator-sdk init --domain example.com --repo github.com/example/memcached-operator
Error: failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v3": go version 'go1.18.3' is incompatible because 'plugin requires go1.19 <= version < go2.0alpha1'. You can skip this check using the --skip-go-version-check flag
```

**Comment by everettraven** [comment]
@PureRaidenCloud Thanks for pointing this out! Would you be interested in creating a PR to fix this?

**Comment by emily-zall** [comment]
looks like this has been resolved and can be closed

**Comment by PureRaidenCloud** [comment]
> looks like this has been resolved and can be closed

Have you checked the documentation [here](https://v1-30-x.sdk.operatorframework.io/docs/building-operators/golang/installation/)?

I checked the documentation again just now, and the version of Go is still `1.18`.

**Comment by rashmigottipati** [comment]
@PureRaidenCloud Please see [PR comment](https://github.com/operator-framework/operator-sdk/pull/6492#pullrequestreview-1535188486) that mentions rebase that went wrong. Once the rebase issue is fixed, we can merge the documentation fix.

**Comment by everettraven** [comment]
Redeployed on Netlify and it appears to be fixed. Thanks @PureRaidenCloud !
