### ISSUE TITLE
failed to deploy an operator

### ISSUE THREAD

**Issue by abdelghanimeliani** [operator-framework/operator-sdk#6491]
i built some operator and it worked fine first on a fedora cluster.  then wanted to deploy it in some ubuntu cluster, first i run **make install** to install CRDs , it works fine, when in run **make deploy** i get 
```
/root/migrator_operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
cd config/manager && /root/migrator_operator/bin/kustomize edit set image controller=controller:latest
/root/migrator_operator/bin/kustomize build config/default | kubectl apply -f -
Error: no matches for OriginalId apps_v1_Deployment|system|controller-manager; no matches for CurrentId apps_v1_Deployment|system|controller-manager; failed to find unique target for patch apps_v1_Deployment|controller-manager
error: no objects passed to apply
make: *** [Makefile:163: deploy] Error 1
```

## Type of question

 General operator-related help 
Open question 

#### What did you do?

i tried to update golang from 1.19. to 1.20.5 and i get the same error

#### What did you expect to see?

i expected to see my operator running

#### Environment

**Operator type:**

/language go 

**Kubernetes cluster type:**

 operator-sdk version
operator-sdk version: "v1.30.0", commit: "b794fe909abc1affa1f28cfb75ceaf3bf79187e6", kubernetes version: "1.26.0", go version: "go1.19.10", GOOS: "linux", GOARCH: "amd64"

$ go version
go version go1.20.5 linux/amd64

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by varshaprasad96** [comment]
@abdelghanimeliani Could you specify the Kustomize version you have been using and also the sample repository to replicate this? 
This error seems to be stemming from running `kustomize build` with overlays (which is what we do while generating CRDs). This could happen when a particular value to be added during Kustomize build is specified differently (or not specified at all) in kustomization.yaml, base and patch which causes the json patch plugin (in kustomize) to fail. A detailed explanation on this scenario is here: https://github.com/kubernetes-sigs/kustomize/issues/1351.

**Comment by abdelghanimeliani** [comment]
thanks @varshaprasad96 it was similar to first usecase in the issue that you mention, it works now, the version of kustomize was 3.x.x, thanks again.
