### ISSUE TITLE
Playbook stalling when activated via a CR

### ISSUE THREAD

**Issue by shhangandrews** [operator-framework/operator-sdk#6493]
#### What did you do?

I am running a simple ansible playbook to install apache. The playbook will run properly using **ansible-playbook <playbook> -i <inventory file>**. However when I do a **make docker-build docker-push deploy** and run the CR in my VM to install apache, the playbook will stall indefinitely.

#### What did you expect to see?

Playbook to run successfully or at least an error statement.

#### What did you see instead? Under which circumstances?

**Two things happen:**

- When I run the playbook with localhost as my host, the playbook will run 

- When I run the playbook on my VM, the playbook will stall and no output is provided: 

----- Ansible Task Status Event StdOut (infra.jump.juniper.net/v1alpha1, Kind=Host, apache-install/default) -----

PLAY RECAP *********************************************************************

----------

#### Environment

**Operator type: Ansible Operator**

**Kubernetes cluster type: vanilla**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`
clientVersion:
  buildDate: "2023-06-15T02:15:11Z"
  compiler: gc
  gitCommit: 25b4e43193bcda6c7328a6d147b1fb73a33f1598
  gitTreeState: clean
  gitVersion: v1.27.3
  goVersion: go1.20.5
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-06-15T00:36:28Z"
  compiler: gc
  gitCommit: 25b4e43193bcda6c7328a6d147b1fb73a33f1598
  gitTreeState: clean
  gitVersion: v1.27.3
  goVersion: go1.20.5
  major: "1"
  minor: "27"
  platform: linux/amd64

#### Possible Solution

At first I thought it was a gather_task or gather_facts issue but I believe it has something to do with the ssh connection because localhost works 

#### Additional context

**Playbook: **

---
- name: Ansible Playbook to Install Apache
  hosts: linux
  become: yes
  become_user: root
  gather_facts: False
  tasks:
    - name: Install latest version of Apache
      apt:
        name: apache2
        state: latest
        update_cache: yes
        async: 60
        poll: 60

**Comment by everettraven** [comment]
@shhangandrews Thanks for raising this issue! Would you mind sharing all the logs that are output by your ansible operator? I'm not sure what may be causing this stalling behavior but I'm hoping the log outputs might provide a bit more insight as to what may be happening

**Comment by shhangandrews** [comment]
Sorry for the late reply. This issue was resolved but here are the logs to provide some insite.

Thank you,
Shang Andrews




Juniper Business Use Only
From: Bryce Palmer ***@***.***>
Date: Monday, July 10, 2023 at 12:10 PM
To: operator-framework/operator-sdk ***@***.***>
Cc: Shang Andrews ***@***.***>, Mention ***@***.***>
Subject: Re: [operator-framework/operator-sdk] Playbook stalling when activated via a CR (Issue #6493)
[External Email. Be cautious of content]


@shhangandrews<https://urldefense.com/v3/__https:/github.com/shhangandrews__;!!NEt6yMaO-gk!EbVW8Ywk3rewTM4olT_L2Ig4EcY7IzmTA1AAbLsberRV1El4JJikE-doHU6FweJ95jj_B41XHGnD2m3P4lHehCfKyA$> Thanks for raising this issue! Would you mind sharing all the logs that are output by your ansible operator? I'm not sure what may be causing this stalling behavior but I'm hoping the log outputs might provide a bit more insight as to what may be happening
