### ISSUE TITLE
Kubernetes Version Compatibility is unclear

### ISSUE THREAD

**Issue by emily-zall** [operator-framework/operator-sdk#6497]
I want to know what version of operator-sdk is compatible with Kubernetes 1.25. I can see the latest version is made for 1.26 but I see no way of finding which version is for 1.25. The compatibility matrix is not helpful: https://sdk.operatorframework.io/docs/overview/#kubernetes-version-compatibility

**Comment by varshaprasad96** [comment]
@emily-zall As mentioned in the docs, the client-go version present in `go.mod` of operator-sdk determines the k8s version with which the binary is compatible. For example, you can see that operator-sdk version 1.27.0, in its go.mod file (https://github.com/operator-framework/operator-sdk/blob/5cbdad9209332043b7c730856b6302edc8996faf/go.mod#L41), contains client-go 0.25.3. This relates to K8s version 1.25+ (https://github.com/kubernetes/client-go#versioning). 

Also, checking the `go.mod` file of the scaffolded project would be helpful to make sure that the scaffolding supports the k8s version you want. Hope this helps!
