### ISSUE TITLE
logrus and go-restful vulnerabilities in ansible-operator

### ISSUE THREAD

**Issue by venkataramanam** [operator-framework/operator-sdk#6502]
The following security vulnerabilities are detected by Twistlock image security scanner against latest `ansible-operator:v1.30.0` binary. Could we have these fixed please. Thank you.

| severity | cve | link | hasfix | status | packageType | packageName | packageVersion | packagePath | description |
|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| M | PRISMA-2023-0056 | https://github.com/sirupsen/logrus/issues/1370 | Y | fixed in v1.9.3 | go | github.com/sirupsen/logrus | v1.9.2 | /usr/local/bin/ansible-operator | The github.com/sirupsen/logrus module of all versions is vulnerable to denial of service. Logging more than 64kb of data in a single entry without newlines causes the log writer function to hang indefinitely. |
| H | PRISMA-2022-0227 | https://github.com/emicklei/go-restful/issues/497 | Y | fixed in v3.10.0 | go | github.com/emicklei/go-restful/v3 | v3.9.0 | /usr/local/bin/ansible-operator | github.com/emicklei/go-restful/v3 module prior to v3.10.0 is vulnerable to Authentication Bypass by Primary Weakness. There is an inconsistency in how go-restful parses URL paths. This inconsistency could lead to several security check bypass in a complex system. |

**Comment by acornett21** [comment]
- Relates: #6383
