### ISSUE TITLE
operator-sdk does not copy the configs from the given index image

### ISSUE THREAD

**Issue by iamniting** [operator-framework/operator-sdk#6505]
#### What did you do?

I am using operator-sdk to install the operator with the below command and expect the new catalog to have the dependent operators as I am passing the index image which has the dependent operators inside it under the `configs` directory.

`operator-sdk run bundle quay.io/nigoyal/odf-operator-bundle:latest --timeout=10m --security-context-config restricted -n openshift-storage --index-image quay.io/nigoyal/odf-operator-catalog:odf-deps`

#### What did you expect to see?

I am expecting my operator to get installed with the dependencies but it is stuck as it can not resolve the deps. Because the new catalog does not copy the configs directory into the `odf-operator-catalog-configs`

#### What did you see instead? Under which circumstances?

```
$ bin/operator-sdk run bundle quay.io/nigoyal/odf-operator-bundle:latest --timeout=10m --security-context-config restricted -n openshift-storage --index-image quay.io/nigoyal/odf-operator-catalog:odf-deps
INFO[0015] Creating a File-Based Catalog of the bundle "quay.io/nigoyal/odf-operator-bundle:latest" 
INFO[0018] Rendering a File-Based Catalog of the Index Image "quay.io/nigoyal/odf-operator-catalog:odf-deps" to verify if bundle "odf-operator.v4.14.0" is present 
INFO[0028] Generated the extra FBC for the bundle image "odf-operator.v4.14.0" 
INFO[0028] Generated a valid File-Based Catalog         
INFO[0037] Created registry pod: quay-io-nigoyal-odf-operator-bundle-latest 
INFO[0037] Created CatalogSource: odf-operator-catalog  
INFO[0038] OperatorGroup "operator-sdk-og" created      
INFO[0039] Created Subscription: odf-operator-v4-14-0-sub 
FATA[0602] Failed to run bundle: install plan is not available for the subscription odf-operator-v4-14-0-sub: timed out waiting for the condition


$ oc exec quay-io-nigoyal-odf-operator-bundle-latest -- ls -lhR odf-operator-catalog-configs
Defaulted container "registry-grpc" out of: registry-grpc, registry-grpc-init (init)
odf-operator-catalog-configs:
total 0      
drwxrwsrwx    2 root     10006200      27 Jul 21 06:11 odf-operator-catalog-configmap-partition-1

odf-operator-catalog-configs/odf-operator-catalog-configmap-partition-1:
total 8K     
-rw-r--r--    1 10006200 10006200    7.3K Jul 21 06:11 extraFBC.yaml


$ oc exec quay-io-nigoyal-odf-operator-bundle-latest -- ls -lhR configs
Defaulted container "registry-grpc" out of: registry-grpc, registry-grpc-init (init)
configs:
total 1M     
-rw-r--r--    1 root     root       58.6K Jul 20 07:10 csiaddons.yaml
-rw-r--r--    1 root     root      142.9K Jul 20 07:10 ibm.yaml
-rw-r--r--    1 root     root         704 Jul 20 07:07 index.yaml
-rw-r--r--    1 root     root      214.6K Jul 20 07:10 noobaa.yaml
-rw-r--r--    1 root     root      693.0K Jul 20 07:10 ocs.yaml

```

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`
```
operator-sdk version
operator-sdk version: "v1.30.0", commit: "b794fe909abc1affa1f28cfb75ceaf3bf79187e6", kubernetes version: "1.26.0", go version: "go1.19.10", GOOS: "linux", GOARCH: "amd64"

```

`$ go version` (if language is Go)
```
go version
go version go1.20.5 linux/amd64
```

`$ kubectl version`
```
$ oc version
Client Version: 4.10.9
Server Version: 4.14.0-0.nightly-2023-07-20-215234
Kubernetes Version: v1.27.3+4aaeaec
```

#### Possible Solution

Possible solution would be to create the new directory which operator-sdk creates under the `configs` itself and serve from `configs` or copy the `configs` data inside new directory.

#### Additional context

slact thread: https://redhat-internal.slack.com/archives/C3VS0LV41/p1689838697181879

**Comment by everettraven** [comment]
A workaround for now would be to create another `CatalogSource` using your index image which should spin up a registry pod that is serving the catalog contents that contains the dependencies.

I *think* the bug lies somewhere in here:
https://github.com/operator-framework/operator-sdk/blob/888ea7f53781894f4c66f2470151cbeb7b25c0d9/internal/olm/operator/bundle/install.go#L186-L226
It looks like we are only returning the "extra" FBC contents instead of returning the "extra" + index FBC content

**Comment by iamniting** [comment]
Thanks @everettraven for pointing this out. I tried to fix it and it did work well in my testing. I will raise a PR.
