### ISSUE TITLE
"make install" for operator sdk does not work (error: "/bin/sh: gpgconf: command not found")

### ISSUE THREAD

**Issue by spanichellazhaw** [operator-framework/operator-sdk#651]
## Bug Report

**What did you do?**
I followed the instruction reported here:
https://github.com/operator-framework/operator-sdk
to work with the operator-sdk

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

Everything fine until typing "make install"  I see the following 
error: "/bin/sh: gpgconf: command not found".
Thus, I'm not able to install again the operator-sdk.

I did not have this problem in the version of a couple of weeks ago, which at least allow me to run the commands of "operator-sdk"

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

Everything fine until typing "make install"  I see the following 
error: "/bin/sh: gpgconf: command not found".
Thus, I'm not able to install again the operator-sdk.

**Environment**
* operator-sdk version:

  Insert operator-sdk release or Git SHA here:

https://github.com/operator-framework/operator-sdk/tree/5c50126e7a112d67826894997eca143e12dc165f

* Kubernetes version information:

  Insert output of `kubectl version` here

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-10-12T17:04:15Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

I'm using minishift.

* Are you writing your operator in ansible or go?

Go.

**Additional context**
I did not have this problem in the version of a couple of weeks ago, which at least allow me to run the commands of "operator-sdk"

**Comment by hasbro17** [comment]
@spanichellazhaw I think is the result of our new Makefile having a variable that gets evaluated for the release and build step.
https://github.com/operator-framework/operator-sdk/blob/master/Makefile#L47

@AlexNPavel @estroz We should probably suppress that error message if a user is just trying to build the binary with `make build` without trying to signing it. That's more for our release process.

@spanichellazhaw However your `operator-sdk` should have been build after doing `make install` despite the error message.
Can you try checking `$GOPATH/bin/operator-sdk` and try out the rest of the user guide with it.

**Comment by spanichellazhaw** [comment]
Thanks for fixing the problem guys!
