### ISSUE TITLE
Upgrade SDK Version v1.30.0 Documentation

### ISSUE THREAD

**Issue by BenRub** [operator-framework/operator-sdk#6510]
Hello,
I don't fully understand the "Upgrade SDK Version" page for v1.30.0.
It looks like a template that wasn't edited yet.

**Comment by everettraven** [comment]
@BenRub Thanks for raising this issue! That is indeed a template that snuck it's way in and results in the migration page for v1.30.0. I don't believe there are any actual migrations needed and I've been meaning to look at fixing this page but just haven't had the chance. 

There is also this previous issue highlighting the same problem: https://github.com/operator-framework/operator-sdk/issues/6480
