### ISSUE TITLE
operator-sdk build error -> missing DeepCopyObject method, plz Help

### ISSUE THREAD

**Issue by Bruslan** [operator-framework/operator-sdk#652]
I have this Issiue after Updating my operator-sdk to version 0.0.7
I try to run the Command operator-sdk build (registry)

My System: Mac OS Mojave
Error:
2018/10/22 19:23:58 failed to build operator binary: exit status 2 (# github.com/example-inc/app-operator/pkg/controller/appservice
pkg/controller/appservice/appservice_controller.go:47:29: cannot use v1alpha1.AppService literal (type *v1alpha1.AppService) as type runtime.Object in field value:
	*v1alpha1.AppService does not implement runtime.Object (missing DeepCopyObject method)
pkg/controller/appservice/appservice_controller.go:56:3: cannot use v1alpha1.AppService literal (type *v1alpha1.AppService) as type runtime.Object in field value:
	*v1alpha1.AppService does not implement runtime.Object (missing DeepCopyObject method)
pkg/controller/appservice/appservice_controller.go:87:45: cannot use instance (type *v1alpha1.AppService) as type runtime.Object in argument to r.client.Get:
	*v1alpha1.AppService does not implement runtime.Object (missing DeepCopyObject method)
)

**Comment by Bruslan** [comment]
Okay i Somehow Debugged the Error, and this Error ist just a result of an another error:

2018/10/22 19:37:51 failed to perform code-generation: (exit status 127)

**Comment by AlexNPavel** [comment]
You most likely need to run `operator-sdk generate k8s`. That will rerun the code generation based on your types file to be up to date.

**Comment by hasbro17** [comment]
@Bruslan Make sure to rebuild your operator-sdk binary to v0.0.7 and then run `operator-sdk generate k8s`:
```sh
$ git checkout v0.0.7
$ dep ensure
$ make install
```

**Comment by Bruslan** [comment]
Somehow every version, except v.0.0.5 are buggy,

The version 0.0.7 is Windows optimized ->  Error: failed to perform code-generation for CustomResources: (env: bash\r: No such file or directory
)
Is there any solution for \r -> \n

**Comment by AlexNPavel** [comment]
Does this issue still happen if you create a project from scratch? We don't use carriage returns in any of our code, and neither does the code in our `vendor`. We test our code on linux based systems and some of our developers use macOS as well, and we haven't seen this issue occur.

**Comment by AlexNPavel** [comment]
It is also possible that your git client is configured to use CRLF line endings instead of LF, so that may be worth looking into, since we do a `git init` when you create a new project.

**Comment by Bruslan** [comment]
@AlexNPavel Thank you mate, it worked. You were right, my git line endings were on auto, i changed it to false.
