### ISSUE TITLE
FATA[0120] Failed to run bundle: error waiting for CSV to install: timed out waiting for the condition

### ISSUE THREAD

**Issue by SaranyaMeiyyappan** [operator-framework/operator-sdk#6524]
#### What did you do?

I am trying to install the example ansible operator mentioned in the documentation called "memcached-operator" via olm.

#### What did you expect to see?

memcached-operator needs to be installed.

#### Environment

**Operator type:**

language ansible

**Kubernetes cluster type:**

vanilla kubernetes and Kind

`$ operator-sdk version`

user@G7RGSDK3E:~/projects/memcached-operator$ operator-sdk version
operator-sdk version: "v1.31.0", commit: "e67da35ef4fff3e471a208904b2a142b27ae32b1", kubernetes version: "1.26.0", go version: "go1.19.11", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

user@G7RGSDK3E:~/projects/memcached-operator$ go version
go version go1.20.6 linux/amd64

`$ kubectl version`

user@G7RGSDK3E:~/projects/memcached-operator$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-22T05:25:21Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}

#### Additional context

Below are the logs - 

FATA[0120] Failed to run bundle: error waiting for CSV to install: timed out waiting for the condition

**Comment by jberkhahn** [comment]
This is usually due to some misconfiguration resulting in the bundle image being inaccessible. Are you sure you're using the same name and location of the bundle image everywhere? Are you sure the cluster has access to wherever you're hosting the bundle image?

**Comment by SaranyaMeiyyappan** [comment]
Yes, I fixed the issue. Thanks
