### ISSUE TITLE
Operator-SDK setup on Windows10 not working

### ISSUE THREAD

**Issue by snjonnal** [operator-framework/operator-sdk#6530]
#### What did you do?
Tried installing operator-sdk from github release https://sdk.operatorframework.io/docs/installation/#install-from-github-release
git clone https://github.com/operator-framework/operator-sdk
cd operator-sdk
git checkout master
make install

#### What did you expect to see?

Successful Installation of operator-sdk on windows10

#### What did you see instead? Under which circumstances?

'test' is not recognized as an internal or external command,
operable program or batch file.
go install -gcflags "all=-trimpath=" -asmflags "all=-trimpath=" -ldflags " -X 'github.com/operator-framework/operator-sdk/internal/version.Version=v1.31.0+git' -X 'github.com/operator-framework/operator-sdk/internal/version.GitVersion=v1.31.0' -X 'github.com/operator-framework/operator-sdk/internal/version.GitCommit=e67da35ef4fff3e471a208904b2a142b27ae32b1' -X 'github.com/operator-framework/operator-sdk/internal/version.KubernetesVersion=v1.26.0' -X 'github.com/operator-framework/operator-sdk/internal/version.ImageVersion=v1.31.0' "  ./cmd/{operator-sdk,ansible-operator,helm-operator}

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`

latest version from git 

`$ go version` (if language is Go)

go version go1.20.5 windows/amd64

`$ kubectl version`

kustomizeVersion: v5.0.1

**Comment by jberkhahn** [comment]
We don't officially support Windows, but the CLI itself is probably functional. This error looks like a Golang error rather than anything OSDK specific, it looks like maybe your GOPATH isn't set correctly?

**Comment by gerbil** [comment]
How do you managed to build operator-sdk on windows? Is there any place I can download it?

**Comment by jberkhahn** [comment]
@gerbil as previously mentioned, we don't officially support windows, which is why we don't provide binaries for it. that said, golang is usually pretty good about platform cross compatibility, but we have a lot of dependencies so I wouldn't be surprised if you had to finangle things to get it to work.
