### ISSUE TITLE
Remote repository for helm 

### ISSUE THREAD

**Issue by piksida** [operator-framework/operator-sdk#6532]
## Type of question

!-- General operator-related help --

#### What did you do?

I use operator for Helm. In watches.yml it states a directory to get helm charts which is copied from my local repository during docker build. 

#### What did you expect to see?

However, I d like Operator to get helm charts from a remote repository and not from its local directory. Is this possible? 

#### What did you see instead? Under which circumstances?

Unfortunately I didn’t find any reference for this problem in documentation.

#### Environment

**Operator type:**

!-- /language helm --

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by varshaprasad96** [comment]
Yes, that is possible. We can use the `--helm-chat-repo` flag to do that. Here is some documentation around that: https://sdk.operatorframework.io/docs/building-operators/helm/tutorial/#use-an-existing-chart

**Comment by piksida** [comment]
That flag would only upload templates from a remote repository locally and these templates will be used to build operator However if templates change in the remote repository after the deployment of operator they won’t be updated inside of it

**Comment by varshaprasad96** [comment]
@piksida Scaffolding the project with specified APIs is a static process. We would not want the APIs to change dynamically as and when the remote help chart gets updated. If there is any change in the helm chart's contents, it warrants a separate API.

**Comment by varshaprasad96** [comment]
@piksida To add more details, you can imagine a Helm chart to be the Operand that the Operator reconciles. If you would like to change the values of the chart, you can do so by modifying the CR. But if you would like to change the chart itself, it translates to having a separate spec and thereby means a separate API.  

Hope this helps, I'm closing this issue. Please feel free to reopen if you think otherwise.
