### ISSUE TITLE
Ansible Operator `up local` doesn't react to CR creation

### ISSUE THREAD

**Issue by cpitman** [operator-framework/operator-sdk#654]
## Bug Report

**What did you do?**
I am trying to debug an ansible operator. I have built the operator sdk, and am trying to run `operator-sdk up local` from the ansible operator directory.

**What did you expect to see?**
Activity based on the creation/modification/deletion of CRs.

**What did you see instead? Under which circumstances?**
Nothing is logged after the startup sequence, and the only observable side effect is that the resource has a status phase "Creating":

```
[vagrant@localhost project-pipeline-demo-operator]$ ~/go/bin/operator-sdk up local --namespace project-pipeline
INFO[0000] Go Version: go1.10.4
INFO[0000] Go OS/Arch: linux/amd64
INFO[0000] operator-sdk Version: 0.0.6+git
INFO[0000] watching namespace: project-pipeline
INFO[0000] Watching cop.redhat.com/v1alpha1, ProjectPipeline
INFO[0000] Starting to serve on 127.0.0.1:8888
```
```
apiVersion: cop.redhat.com/v1alpha1
kind: ProjectPipeline
metadata:
  clusterName: ""
  creationTimestamp: 2018-10-23T04:55:05Z
  generation: 1
  name: example-projectpipeline
  namespace: project-pipeline
  resourceVersion: "9039"
  selfLink: /apis/cop.redhat.com/v1alpha1/namespaces/project-pipeline/projectpipelines/example-projectpipeline
  uid: cea24b5e-d67f-11e8-afe3-08002724fbb6
spec:
  friendlyName: An Example Project Pipeline
status:
  changed: 0
  completion: 0001-01-01T00:00:00
  failures: 0
  ok: 0
  phase: Creating
  skipped: 0
```

Note: If I build the actual docker image, and deploy it to the cluster, the operator reacts to CR changes and runs the playbook.

**Environment**
* operator-sdk version:  f7a8fd3

* Kubernetes version information:
```
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.99.101:8443
openshift v3.10.0+456651d-57
kubernetes v1.10.0+b81c8f8
```

**Additional context**
This is all in an attempt to debug why one task in the ansible playbook is failing. The current logs by the ansible-operator are not particularly helpful.

**Comment by mhrivnak** [comment]
> This is all in an attempt to debug why one task in the ansible playbook is failing. The current logs by the ansible-operator are not particularly helpful.

The best way to get at that debugging info is to exec into the operator's pod and look in ansible-runner's input directory, which includes an [artifacts](https://ansible-runner.readthedocs.io/en/latest/intro.html#runner-artifacts-directory-hierarchy) section. In there, you'll see the usual stdout from ansible.

You can find it under `/tmp/ansible-operator/runner/` and then by GVK.

That said, we'll still check out this bug report of course. Thanks for filing it.

**Comment by shawn-hurley** [comment]
I bet this is the ansible runner could. Or find the playbook I don’t think we are error if there yet.

**Comment by cpitman** [comment]
Thanks, the in-container output was very helpful.

Does the watch file need to be updated with the playbook path on host? The usual path assumes everything is running in the container.

**Comment by shawn-hurley** [comment]
We merged this [doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/developer_guide.md) does this help?

I think it is true that you would need to change the paths, and you may even need to change the roles path with an environment variable I believe.

**Comment by LiliC** [comment]
@cpitman Closing this as doc was added, but feel free to open a new issue if you run into any other problems, thanks!
