### ISSUE TITLE
Current client-go version (v0.26.2) contains possible panic in discovery

### ISSUE THREAD

**Issue by seans3** [operator-framework/operator-sdk#6540]
Please update `operator-sdk` client-go version to v0.26.4+

Why: Possible panic when using client-go v0.26.0 - v0.26.3 (looks like current client-go is affected: v0.26.2) for discovery.

https://github.com/operator-framework/operator-sdk/blob/master/go.mod#L41

kubernetes issue: https://github.com/kubernetes/kubernetes/issues/119840

**Comment by varshaprasad96** [comment]
This PR (https://github.com/operator-framework/operator-sdk/pull/6545) fixes the client-go bumps in SDK binary. Individual plugins need to fix this in their scaffolding and it needs to come from Kubebuilder. Also, this needs to back ported to SDK 1.31 release (https://github.com/operator-framework/operator-sdk/blob/v1.31.0/go.mod#L41).
