### ISSUE TITLE
How to check the FIPS mode of each OCP worker node?

### ISSUE THREAD

**Issue by YanFenGuo** [operator-framework/operator-sdk#6544]
Hi, I'm build our Operator based on `quay.io/operator-framework/ansible-operator:v1.28.1` and running it on OCP 4.12, I have a feature requirement to check FIPS mode of each worker node, wondering what's the best approach to do this?

I'm thinking of create an inventory file like this:
```
[my_workers]
worker1.cp4a-dev.cp.fyre.ibm.com
worker2.cp4a-dev.cp.fyre.ibm.com
# Add more worker nodes as needed
```
Then run a playbook like this:
```
- name: Check FIPS Mode on OpenShift Worker Nodes
  hosts: openshift-worker
  gather_facts: yes

  tasks:
    - name: Run command to check FIPS status
      shell: cat /proc/sys/crypto/fips_enabled
      register: fips_result

    - name: Display FIPS status
      debug:
        msg: "FIPS Mode is {{ fips_result.stdout == '1' | ternary('Enabled', 'Disabled') }} on {{ inventory_hostname }}"
```
And execute it with `ansible-playbook -i inventory.ini check_fips.yml`, is this the right way? How to run `ansible-playbook` in Ansible Operator?

**Comment by acornett21** [comment]
Hi @YanFenGuo Below are some resources that can help:

Suggested approach for checking FIPS on a RHEL can be found [here](https://access.redhat.com/discussions/3293631)
Suggested approach for checking if an OCP cluster is FIPS enabled can be found [here](https://access.redhat.com/solutions/6525331)
Suggested tutorial for building an ansilbe operator can be found [here](https://sdk.operatorframework.io/docs/building-operators/ansible/tutorial/) and more info about watches (how the operator reconciles) can be found [here](https://sdk.operatorframework.io/docs/building-operators/ansible/reference/watches/)

Hope this helps.

**Comment by YanFenGuo** [comment]
Hi @acornett21 Thank you for your reply but those links don't help much.
I know how to check FIPS mode of an OCP Cluster, the requirement is I need to check FIPS mode of each worker node, I can easily do it with a command out of OCP with kubeadmin for example with below command:
```
[root@cp4a1 2023.2]# for node in $(oc get no --no-headers -o name); 
> do 
>   oc debug $node -- chroot /host sh -c "fips-mode-setup --check"
> done
Creating debug namespace/openshift-debug-node-z9dfl ...
Starting pod/master0gyfguo-devcpfyreibmcom-debug ...
To use host binaries, run `chroot /host`
Installation of FIPS modules is not completed.
FIPS mode is disabled.

Removing debug pod ...
```

But it is not easy to achieve this in Operator, I'm thinking of launching a pod in each node and do the check.

**Comment by YanFenGuo** [comment]
Launch a pod on each worker node and check the fips mode can work, I'm closing this, thank you @acornett21 for checking this issue.
