### ISSUE TITLE
How to add multiple active versions of operator

### ISSUE THREAD

**Issue by Nilesh20** [operator-framework/operator-sdk#6548]
## Type of question

I have operator and currently wanted to have multiple active versions of it.

ex: Previously

bundle versions were 100 -> 110> 200 -> 300 (Here new version replaces the new one when published)
Now I want update on 110 i.e 110->120-> 130 and meanwhile expecting update on 300 like 300 -> 400 

How I can achieve this ?

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by OchiengEd** [comment]
Hi Nile, I am not quite clear on what you are attempting to achieve. Would you please provide some context?

Based on your current question, it seems you could either be looking to publish multiple versions of your operator in an operator catalog or installing multiple versions of the same operator on a cluster?

**Comment by Nilesh20** [comment]
Hi @OchiengEd Thanks for reply, Yes I am trying to publish multiple version of operator in an operator catalogue.

currently I have published version sequence as below
100 -> 200 -> 210 -> 300 (latest active one)

And in future expecting to publish 220 (on top of 210, here I will need to active versions) and 400 (on top of 300)

**Comment by varshaprasad96** [comment]
@Nilesh20 would you mind opening this issue in operator-lifecycle-manager org. This seems to be related to how OLM manages upgrades, and that would be the right place where folks can help you out. If this is related to construction of upgrade graphs, please open it in: https://github.com/operator-framework/operator-registry, if not we can have that in https://github.com/operator-framework/operator-lifecycle-manager and the maintainers can point to the right place. 

Closing this issue.
