### ISSUE TITLE
Update to K8s 1.28

### ISSUE THREAD

**Issue by Neo2308** [operator-framework/operator-sdk#6549]
1.28 got recently released. Can we create the meta issue for tracking the bumping up versions in all the dependencies since this usually takes considerable time?

**Comment by varshaprasad96** [comment]
@Neo2308 would you mind creating a meta issue to track down the dependent repositories/projects which need to be updated. It would be similar to: https://github.com/operator-framework/operator-sdk/issues/6381. 

Please feel free to assign it, if you would like to work on it. Thank you so much for raising this, and we appreciate the contributions!

**Comment by acornett21** [comment]
- Relates: #6554

**Comment by Neo2308** [comment]
Closing since meta issue has been created for tracking.
