### ISSUE TITLE
Contributing.md needs to explain the DCO

### ISSUE THREAD

**Issue by jberkus** [operator-framework/operator-sdk#6550]
### What is the URL of the document?

https://github.com/operator-framework/operator-sdk/blob/master/CONTRIBUTING.MD

### Which section(s) is the issue in?

Missing section

### What needs fixing?

OF uses a DCO for SDK contributions.  However, the contributor guide doesn't mention the DCO, or the need to sign commits, at all.

#### Additional context

OLM has text for this, you can just copy it.

**Comment by jiyanpatil07** [comment]
I would like to work on this!

**Comment by jiyanpatil07** [comment]
I have fixed the issue and created a PR for the same.
Please have look.
I apologies for the closed PR that was by mistake.
