### ISSUE TITLE
Go-Operator : Embed k8s native workload in CRD spec

### ISSUE THREAD

**Issue by suneelkumarch** [operator-framework/operator-sdk#6551]
## Type of question

How to implement a specific feature 

## Question

using Operator-SDK to develop K8s operator. 
Requirement is to listen to CR and perform actions like create secrets and configmaps then update the k8s workload(Deployment/DaemonSet/StatefulSet) by mounting the created secrets and configmaps. Until CR is reconciled k8s workload should be in pending state or not applied.

One option that I am trying is: 
In the CRD spec, embed k8s Deployment, StatefulSet or DaemonSet objects. Once pre-processing is done by the operator, it adjusts the embedded k8s workload and apply the k8s workload to cluster.

    type Foo struct{
	  metav1.TypeMeta   `json:",inline"`
	  metav1.ObjectMeta `json:"metadata,omitempty"`

	   Spec   FooSpec   `json:"spec,omitempty"`
	   Status FooStatus `json:"status,omitempty"`
    }
    type FooSpec struc{
       Template <Deployment|DaemonSet|StatefulSet>Spec `json:"template,omitempty"`
    }

Above is the CRD sample. In this `Template` can be of deployment or statefulSet  or DaemonSet. 

How to define such a CRD spec using operator-sdk in golang?

How to cast the `Template`, in reconciliation loop, to the actual object(Deployment/DaemonSet/StatefulSet)?

#### Environment

**Operator type: Go**

**Kubernetes cluster type: **

`$ operator-sdk version : 1.22.2`

operator-sdk version: "v1.22.2", commit: "da3346113a8a75e11225f586482934000504a60f", kubernetes version: "1.24.1", go version: "go1.18.4", GOOS: "linux", GOARCH: "amd64">

`$ go version` (if language is Go)

go version go1.20.6 linux/amd64

`$ kubectl version`

**Comment by suneelkumarch** [comment]
tried using `runtime.Object` in `spec`  as follows, but the manifest generation failed with `"unsupported AST kind *ast.InterfaceType"` error

```
type FooSpec struc{
   Template runtime.Object `json:"template,omitempty"`
}
```

**Comment by varshaprasad96** [comment]
@suneelkumarch If I'm understanding right, you would like to specify a custom object type in the spec of a CRD. If its a native K8s type, you can directly declare it as done here: https://github.com/aerogear/mobile-security-service-operator/blob/e74272a6c7addebdc77b18eeffb5e888b35f4dfd/pkg/apis/mobilesecurityservice/v1alpha1/mobilesecurityservice_types.go#L90 - where you specify the typed object being embedded that already has existing deep copy methods implemented.

If you would like to use it fill in any typed/untyped object and deserialize it into the spec, the right way would be declare it as unstructured and implement a deepcopy method. Here are some reference comments on the same:

Adding an unstructured object: https://github.com/operator-framework/operator-sdk/issues/1795#issuecomment-800174990.

Also, controller-tools provides an option to validate an embedded resource in the spec, using the marker: https://book.kubebuilder.io/reference/markers/crd-validation.html?highlight=embed#crd-validation.

Hope this helps!

**Comment by varshaprasad96** [comment]
@suneelkumarch we discussed this in the community meeting, though using `unstructured` is a workaround to store contents of different types in a single format, the design of having it serialize different objects - deployment or daemonsets, seems a weird design. Would having spec contain these three different objects separately be an issue in your design?

**Comment by suneelkumarch** [comment]
@varshaprasad96  CRD Indeed spec containing three different objects separately(mutually exclusive to each other) an option that was thought of, however, it means CRD schema YAML size grows beyond the maximum request size allowed by etcd 1MiB/1.5MiB(default)
