### ISSUE TITLE
Go Operator : ObjectMeta struct in CRD spec leads to incorrect spec YAML generation

### ISSUE THREAD

**Issue by suneelkumarch** [operator-framework/operator-sdk#6558]
## Bug Report

```
// WorkloadSpec defines the desired state of Workload
type FooSpec struct {
	FooTemplate appsv1.DeploymentSpec `json:"fooTemplate,omitempty"`
}

type Foo struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   FooSpec   `json:"spec,omitempty"`
	Status FooStatus  `json:"status,omitempty"`
}
```
Here  `FooTemplate`  is of type `DeploymentSpec` which contains a `ObjectMeta` in its `PodTemplateSpec`.  
In the generated CRD yaml, `PodTemplateSpec.ObjectMeta` is turned-out as type `object`
![image](https://github.com/operator-framework/operator-sdk/assets/13213776/cfdda271-8f07-4ac1-96fe-699702fd3e82)

When the CR is applied of type `Foo`, with foo.Spec.fooTemplate.template.metadata.labels` set as follows
![image](https://github.com/operator-framework/operator-sdk/assets/13213776/15729457-0ff2-481c-8cbc-50b45144f654)

following error is seen

`error when creating "foo-cr.yaml": Foo in version "v1alpha1" cannot be handled as a Foo: strict decoding error: unknown field "spec.fooTemplate.template.metadata.labels"`
#### What did you do?

Performed as described above

#### What did you expect to see?

CR of type `Foo` with '"spec.fooTemplate.template.metadata.labels"applied to cluster without an issue

#### Environment

**Operator type:**

/language go 

**Kubernetes cluster type:**

minikube

`$ operator-sdk version`

operator-sdk version: "v1.22.2", commit: "da3346113a8a75e11225f586482934000504a60f", kubernetes version: "1.24.1", go version: "go1.18.4", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.20.6 linux/amd64
`$ kubectl version`

Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4

**Comment by varshaprasad96** [comment]
Afaik by default controller gen does not generate any embedded metadata of the object. Could you try by passing `generateEmbeddedObjectMeta` to true in the generator? In your makefile, along with the crd gen command you can pass, something like: `controller-gen crd:maxDescLen=0,generateEmbeddedObjectMeta=true ...` and check if that works. There is some documentation regarding this in kubebuilder regarding the format of the command: https://book.kubebuilder.io/reference/controller-gen.html?highlight=generateEmbeddedObjectMeta#generators. Hopefully this works!

**Comment by eminetto** [comment]
I tried what @varshaprasad96 suggested and changed the `Makefile` from:

```
$(CONTROLLER_GEN) rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
```
to 
```
$(CONTROLLER_GEN) rbac:roleName=manager-role crd:generateEmbeddedObjectMeta=true webhook paths="./..." output:crd:artifacts:config=config/crd/bases
```

And you can see the diff in the results of `make manifest`:

<img width="1438" alt="Captura de Tela 2023-10-07 às 17 05 03" src="https://github.com/operator-framework/operator-sdk/assets/197939/23632097-b460-4a0e-b31e-adde931354be">

This is what you expected @varshaprasad96? Does this solve your problem @suneelkumarch?
