### ISSUE TITLE
Go operator-sdk : is it possible to create mutating web hook for deployment type 

### ISSUE THREAD

**Issue by suneelkumarch** [operator-framework/operator-sdk#6559]
## Type of question

 How to implement a specific feature 

## Question

Using `operator-sdk` CLI is it possible to create an admission(mutating) webhook for k8s `Deployment` workload.?
Its possible to create web hooks for the CRs those are create using `operator-sdk` CLI in the same project. But I have requirement to create a mutating webhook for k8s Deployment object under the operator project

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

minikube

`$ operator-sdk version`

operator-sdk version: "v1.22.2", commit: "da3346113a8a75e11225f586482934000504a60f", kubernetes version: "1.24.1", go version: "go1.18.4", GOOS: "linux", GOARCH: "amd64"

$ go version (if language is Go)

go version go1.20.6 linux/amd64
$ kubectl version

Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4

**Comment by varshaprasad96** [comment]
Operator SDK (and Kubebuilder) doesn't support scaffolding validating/mutating webhooks for default k8s types by default. But it can be done by making some changes manually to the kubebuilder markers that use controller-gen. Here is a documentation on scaffolding admission WHs for pods (it would be similar for deployment): https://book.kubebuilder.io/reference/webhook-for-core-types. Also, controller runtime has an example for this in its repo: https://github.com/kubernetes-sigs/controller-runtime/blob/main/examples/builtins/mutatingwebhook.go
