### ISSUE TITLE
Alignment of words is colliding in operator SDK documentation

### ISSUE THREAD

**Issue by octonawish-akcodes** [operator-framework/operator-sdk#6565]
#### What did you do?
I was going through the operator SDK documentation and found that the alignment of some words is colliding with each other.

#### What did you expect to see?
Proper alignment of words.

#### What did you see instead? Under which circumstances?
If you visit to [this](https://sdk.operatorframework.io/build/) page you can find the issue.
![image](https://github.com/operator-framework/operator-sdk/assets/76171953/014f013f-d94a-4cc5-98ad-d6f4766ab4cc)

#### Possible Solution
Proper alignment should be there.

**Comment by varshaprasad96** [comment]
@octonawish-akcodes Looks like this appears to be an issue when we try to re-size the page. Would you be open to looking into this and submitting a fix. This could be an issue not only with this page, but with everything under Operator framework site. Thank you so much for bringing this up!

**Comment by professorabhay** [comment]
Hey @varshaprasad96 and @everettraven, I debugged that issue and would like to raise PR. Please assign it to me !
Sample ->   Changes some properties !

![image](https://github.com/operator-framework/operator-sdk/assets/76243309/d1f6c48d-2c1a-4f86-a094-52c55755f960)
