### ISSUE TITLE
Dockerhub rate limiting causes `run bundle` to fail

### ISSUE THREAD

**Issue by sebsoto** [operator-framework/operator-sdk#6578]
#### What did you do?

Attempt to deploy an operator using `operator-sdk run bundle 

#### What did you expect to see?

The operator deploying correctly

#### What did you see instead? Under which circumstances?

[The forced use of the image docker.io/library/busybox](https://github.com/operator-framework/operator-sdk/blob/8f24aa560c1b8a8ea7bbc062016347b4012e499c/internal/olm/operator/registry/fbcindex/fbc_registry_pod.go#L352) causes issues for organizations making use of operator-sdk run bundle. Dockerhub rate limits container image pulls. The rate limiting will cause operator-sdk run bundle to fail.
```
Failed to run bundle: create catalog: error creating registry pod: registry pod did not become ready: error waiting for registry pod 57e700e00227f725a6cc1ccb50d6436cec81cae719edf808d10099d5bffa467 to run: timed out waiting for the condition
```

From a cluster event:
```
            "message": "Failed to pull image \"docker.io/library/busybox:1.36.0\": rpc error: code = Unknown desc = initializing source docker://busybox:1.36.0: reading manifest 1.36.0 in docker.io/library/busybox: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit",
```

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

OpenShift

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

#### Possible Solution

A command line option to customize the image could be added. [This is done already for scorecard
](https://github.com/operator-framework/operator-sdk/blob/8f24aa560c1b8a8ea7bbc062016347b4012e499c/website/content/en/docs/testing-operators/scorecard/custom-tests.md?plain=1#L258)

**Comment by varshaprasad96** [comment]
@sebsoto Thanks for raising the issue. This seems reasonable. Would you be open to submitting a PR to fix this?

**Comment by sebsoto** [comment]
@varshaprasad96
Sure, I can give it a shot
