### ISSUE TITLE
Designing Lean Operators

### ISSUE THREAD

**Issue by fgiloux** [operator-framework/operator-sdk#6581]
The page needs to be updated.

There was [a breaking change in controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/pull/2300) so that `BuilderWithOptions` has been removed.
The use case should now be covered by cache.Options, [the ByObject field being now a map](https://github.com/kubernetes-sigs/controller-runtime/pull/2166).

Controller-runtime design document: https://github.com/kubernetes-sigs/controller-runtime/blob/main/designs/cache_options.md

**Comment by acornett21** [comment]
This is the page in question:
https://master.sdk.operatorframework.io/docs/best-practices/designing-lean-operators/

- Relates: #6381

**Comment by fgiloux** [comment]
Changes introduced in [v0.15.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0)
SDK currently using  v0.14.1.
Thanks for linking the bump issue.

**Comment by fgiloux** [comment]
More relevant than even since https://github.com/operator-framework/operator-sdk/pull/6613 has merged
