### ISSUE TITLE
usage of metrics-reader ClusterRole

### ISSUE THREAD

**Issue by mohammadne** [operator-framework/operator-sdk#6587]
## Type of question

Open question

#### What did you do?

I want to know what is the usage of `metrics-reader` ClusterRole in rbac, because I don't see any ClusterRoleBinding defined for it and it's always unusable.

#### What did you expect to see?

I want to delete `metrics-reader` ClusterRole or define a ClusterRoleBinding and subject it to the ServiceAccount used by the Deployment

#### Environment

**Operator type:** /language go

**Kubernetes cluster type:** k8s cluster deployed via kubespray

`$ operator-sdk version` v1.31.0

`$ go version` (if language is Go) 1.19.11

`$ kubectl version` 1.27

**Comment by varshaprasad96** [comment]
This cluster role is scaffolded to allow the prometheus server to scrape metrics. The creation of cluster role binding is left to the user, depending on the namespace where prometheus is available. 

More details on its use and on how to create the cluster role binding for the cluster role are available here; https://book.kubebuilder.io/reference/metrics.html?highlight=prometheus#exporting-metrics-for-prometheus
