### ISSUE TITLE
Generate bundle ignore RelatedImages from config/manifests/bases

### ISSUE THREAD

**Issue by rollandf** [operator-framework/operator-sdk#6590]
#### What did you do?

generate bundle using kustomize with RelatedImages in config/manifests/bases/my.clusterserviceversion.yaml

#### What did you expect to see?

The generated CSV should include the provided `RelatedImages`

#### What did you see instead? Under which circumstances?
The generated CSV does not include the provided `RelatedImages`
used to worked until v1.19.0

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**
vanilla

`$ operator-sdk version`
v1.19.1
(worked with v1.19.0)

`$ go version` (if language is Go)

`$ kubectl version`

#### Possible Solution
Merge the provided RelatedImages with the auto detected.
Suspected PR that introduced the change: #5656

**Comment by acornett21** [comment]
Hi @rollandf, does this issues exist with a recent version of operator-sdk? v1.19.1 is well over a year and a half old, just trying to gauge if this issue still exists. Thanks.

**Comment by rollandf** [comment]
Hi, yes it still exists in latest version.

Example of base yaml:
https://github.com/Mellanox/network-operator/blob/master/config/manifests/bases/nvidia-network-operator.clusterserviceversion.yaml#L78

**Comment by acornett21** [comment]
Thanks for confirming...As a workaround, operator-sdk can build the related images section in the csv with the following:

```
USE_IMAGE_DIGESTS=true make bundle
```

This pins the images to the proper sha value and also builds the related images section.
