### ISSUE TITLE
Workflow failed, but there is no instructions what to do

### ISSUE THREAD

**Issue by adishaull** [operator-framework/operator-sdk#6601]
https://github.com/k8s-operatorhub/community-operators/pull/3354

**Comment by varshaprasad96** [comment]
@adishaull Operator SDK does not own or manage the CI in operatorhub/community-operators. I think opening an issue there would be more helpful. 
Meanwhile, looking at the CI logs, seems like upgrade of your operator has failed. I'm not sure who owns/written the `test_operator_update : Update status if wrong` task (whether its a part of your operator or a test by the community-operator CI), but looks like it is failing. And the suggestion is trying out locally using `operator-sdk run bundle-upgrade` command. If there are any particular issues you face while running the command, let us know.

**Comment by acornett21** [comment]
This failure was due to an issue with a step in CI itself, which has been resoled. This issue can be closed.

**Comment by everettraven** [comment]
Closing as per @acornett21
