### ISSUE TITLE
Advanced Topics - Leader Election in case of multiple replicas triggered for High Availability purposes

### ISSUE THREAD

**Issue by antaloala** [operator-framework/operator-sdk#6612]
I think it would be good to add, to the **Leader election** section, the use-case about running several instance of the custom controller workload/pod (i.e., only one being 'active') in order to increase the High Availability characteristics of your operator's controller (so the operator deployer has higher control on how fast a "blocked" currently 'active' controller instance is being replaced by another running (but not yet 'active') instance.

Adding this HA related  use-case to the one currently described (related to a Deployment upgrade where new and old pod instance are running in parallel) would better show where this **leader election** support from Operator SDK can be used.

**Comment by varshaprasad96** [comment]
@antaloala Thanks for raising this issue. Though every operator need not be HA enabled, having documentation on this use case would be helpful. Would you be open to submitting a PR for this?

**Comment by AHB102** [comment]
I am new to open source, can I have a go at this ? I don't exactly know what is going on in the issue, but would love to contribute.
