### ISSUE TITLE
Rebuild of operator sdk to incorporate http2 fixes

### ISSUE THREAD

**Issue by vkrizan** [operator-framework/operator-sdk#6615]
## Type of question

General operator-related help

## Question

Would it be possible to rebuild the images to incorporate golang updates, specifically #6600?

#### What did you expect to see?

golang.org/x/net updated with the http2 fix https://github.com/golang/net/commit/b225e7ca6dde1ef5a5ae5ce922861bda011cfabd 

#### Environment

**Operator type:**

/language go
/language ansible 

`<!-- $ kubectl version` -->

#### Additional context

Thank you!

**Comment by varshaprasad96** [comment]
The PR is merged, we should go ahead and cut a patch release.

**Comment by vkrizan** [comment]
Hi @varshaprasad96, do you happen to know the plan to do a patch release? 
Thank you.

**Comment by varshaprasad96** [comment]
@vkrizan will update soon on the patch release. Sorry for the delay. 
cc: @everettraven

**Comment by vkrizan** [comment]
@varshaprasad96 @everettraven any news on this? Thank you.
