### ISSUE TITLE
[go] v1.18.0 Migration - Missing `generate bundle` requirement for "control-plane" label

### ISSUE THREAD

**Issue by adambkaplan** [operator-framework/operator-sdk#6617]
When migrating from operator-sdk v1.17.0 to v1.18.0, `generate bundle` now looks for a deployment with the `control-plane: controller-manager` label pair. The main container must also be named `manager`.

Previously, developers were free to rename the main container or drop the "control-plane" label (or it was never generated in the first place).

This was not documented in the migration guide [1].

[1] https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.18.0/

**Comment by varshaprasad96** [comment]
@adambkaplan This was a known change brought from Kubebuilder. Sorry, for missing this in the documentation. Unfortunately, SDK is now on 1.33 release, and 1.18 seems too old, we currently do not support more than n-3 releases. It would be difficult to make this change in the documentation, but if there are any particular concerns we can address them through issues.
