### ISSUE TITLE
GHSA-jq35-85cj-fj4p security issue is found for github.com/docker/docker v20.10.24  in twistlock scan

### ISSUE THREAD

**Issue by lihongbj** [operator-framework/operator-sdk#6621]
#### What did you do?
When we use this  git repo to build helm-operator binary, a medium security issue GHSA-jq35-85cj-fj4p is found for github.com/docker/docker v20.10.24 in latest master branch during security twistlock scan.

#### What did you expect to see?

We expect the GHSA-jq35-85cj-fj4p  is fixed in future to upgrade github.com/docker/docker to v24.0.7 at least.

**Comment by varshaprasad96** [comment]
This would also be handled when bumping k8s to 1.27
