### ISSUE TITLE
Change `./bin` to `LOCALBIN`

### ISSUE THREAD

**Issue by mateusoliveira43** [operator-framework/operator-sdk#6637]
#### Describe the problem you need a feature to resolve.

Path to some tools binaries is hard coded with `./bin`, instead of using `LOCALBIN` (https://github.com/kubernetes-sigs/kubebuilder/blob/3c9cf656ce4d62a10c8e78a1c0f066de47c983db/pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go#L185).

Example
https://github.com/operator-framework/operator-sdk/blob/e001847a67f16d7173ae4fee7cff57cd4405edbb/internal/plugins/manifests/v2/init.go#L207

#### Describe the solution you'd like.

It would be also nice if tools binaries variables (`OPERATOR_SDK`, `OPM`, `OPERATOR_SDK_VERSION` and `OPM_VERSION`, which does not exist) could be grouped in here https://github.com/kubernetes-sigs/kubebuilder/blob/3c9cf656ce4d62a10c8e78a1c0f066de47c983db/pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go#L189-L196

**Comment by lunarwhite** [comment]
/assign
I'd like to help this issue.
