### ISSUE TITLE
operator-sdk build fails with 'not enough arguments in call to r.Create'

### ISSUE THREAD

**Issue by petomalina** [operator-framework/operator-sdk#664]
## Bug Report

**What did you do?**
Followed the steps to install operator SDK, create a new operator, add custom resource and a controller, then tried `operator-sdk build` to build my operator

**What did you expect to see?**
That my operator will be correctly built

**What did you see instead? Under which circumstances?**
```
operator-sdk build gelidus/krane-operator
2018/10/28 19:12:23 failed to build operator binary: exit status 2 (go: creating new go.mod: module github.com/petomalina/krane
go: finding github.com/operator-framework/operator-sdk/pkg/util/k8sutil latest
go: finding github.com/operator-framework/operator-sdk/version latest
go: finding github.com/operator-framework/operator-sdk/pkg/util latest
go: finding github.com/operator-framework/operator-sdk/pkg latest
go: finding k8s.io/apimachinery/pkg/runtime latest
go: finding k8s.io/apimachinery/pkg/apis/meta latest
go: finding sigs.k8s.io/controller-runtime/pkg/handler latest
go: finding sigs.k8s.io/controller-runtime/pkg/source latest
go: finding sigs.k8s.io/controller-runtime/pkg/runtime/signals latest
go: finding sigs.k8s.io/controller-runtime/pkg/manager latest
go: finding sigs.k8s.io/controller-runtime/pkg/client/config latest
go: finding sigs.k8s.io/controller-runtime/pkg/client latest
go: finding sigs.k8s.io/controller-runtime/pkg/runtime/scheme latest
go: finding k8s.io/client-go/plugin/pkg/client/auth/gcp latest
go: finding k8s.io/apimachinery/pkg latest
go: finding k8s.io/apimachinery/pkg/apis latest
go: finding sigs.k8s.io/controller-runtime/pkg latest
go: finding sigs.k8s.io/controller-runtime/pkg/runtime latest
go: finding k8s.io/apimachinery latest
go: finding k8s.io/client-go/plugin/pkg/client/auth latest
go: finding sigs.k8s.io/controller-runtime/pkg/reconcile latest
go: finding k8s.io/client-go/plugin/pkg/client latest
go: finding k8s.io/apimachinery/pkg/types latest
go: finding sigs.k8s.io/controller-runtime/pkg/controller latest
go: finding sigs.k8s.io/controller-runtime/pkg/controller/controllerutil latest
go: finding k8s.io/apimachinery/pkg/runtime/schema latest
go: finding k8s.io/apimachinery/pkg/api/errors latest
go: finding k8s.io/client-go/plugin/pkg latest
go: finding k8s.io/apimachinery/pkg/api latest
go: finding k8s.io/client-go/plugin latest
go: finding k8s.io/api/core latest
go: finding k8s.io/api latest
go: finding github.com/google/gofuzz latest
go: finding golang.org/x/oauth2/google latest
go: finding github.com/go-logr/logr latest
go: finding golang.org/x/crypto/ssh/terminal latest
go: finding github.com/gregjones/httpcache/diskcache latest
go: finding github.com/gregjones/httpcache latest
go: finding github.com/golang/glog latest
go: finding golang.org/x/oauth2 latest
go: finding golang.org/x/crypto/ssh latest
go: finding github.com/gogo/protobuf/proto latest
go: finding github.com/gogo/protobuf/sortkeys latest
go: finding golang.org/x/crypto latest
go: finding github.com/mattbaird/jsonpatch latest
go: finding github.com/go-logr/zapr latest
go: finding github.com/golang/groupcache/lru latest
go: finding github.com/golang/groupcache latest
go: finding github.com/golang/protobuf/proto latest
go: finding k8s.io/kube-openapi/pkg/util/proto latest
go: finding golang.org/x/time/rate latest
go: finding k8s.io/kube-openapi/pkg/util latest
go: finding k8s.io/kube-openapi/pkg latest
go: finding golang.org/x/time latest
go: finding golang.org/x/net/http2 latest
go: finding k8s.io/kube-openapi latest
go: finding github.com/googleapis/gnostic/OpenAPIv2 latest
go: finding golang.org/x/net latest
go: finding github.com/davecgh/go-spew/spew latest
go: finding go.uber.org/zap/zapcore latest
go: finding golang.org/x/sys/unix latest
go: finding golang.org/x/text/unicode/bidi latest
go: finding golang.org/x/text/secure/bidirule latest
go: finding golang.org/x/text/unicode/norm latest
go: finding github.com/google/btree latest
go: finding github.com/modern-go/concurrent latest
go: finding golang.org/x/text/unicode latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/text/secure latest
go: finding cloud.google.com/go/compute/metadata latest
go: finding cloud.google.com/go/compute latest
# github.com/petomalina/krane/krane-operator/pkg/apis/krane/v1alpha1
pkg/apis/krane/v1alpha1/canary_types.go:44:25: cannot use Canary literal (type *Canary) as type runtime.Object in argument to SchemeBuilder.Register:
        *Canary does not implement runtime.Object (missing DeepCopyObject method)
pkg/apis/krane/v1alpha1/canary_types.go:44:36: cannot use CanaryList literal (type *CanaryList) as type runtime.Object in argument to SchemeBuilder.Register:
        *CanaryList does not implement runtime.Object (missing DeepCopyObject method)
# sigs.k8s.io/controller-runtime/pkg/client
/home/peto/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.6/pkg/client/unstructured_client.go:49:20: not enough arguments in call to r.Create
        have (*unstructured.Unstructured)
        want (*unstructured.Unstructured, v1.CreateOptions, ...string)
/home/peto/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.6/pkg/client/unstructured_client.go:67:20: not enough arguments in call to r.Update
        have (*unstructured.Unstructured)
        want (*unstructured.Unstructured, v1.UpdateOptions, ...string)
/home/peto/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.6/pkg/client/unstructured_client.go:145:26: not enough arguments in call to r.UpdateStatus
        have (*unstructured.Unstructured)
        want (*unstructured.Unstructured, v1.UpdateOptions)
```

**Environment**
* operator-sdk version: 5a9f7d1c7dd3bfe1f19c53679eced252674e8d8c (master)

* Are you writing your operator in ansible or go?
Go

**Possible Solution**
There may be a version mismatch with the newest kubernetes go-client, which causes the methods `r.Create`, `r.Update` and `r.UpdateStatus` to have 2 arguments instead of a single

**Comment by LiliC** [comment]
@petomalina Hello, master is not compatible with previous releases. You can either switch to the [latest release](https://github.com/operator-framework/operator-sdk/tree/v0.0.7) or even better can have a look at the [migration-guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/v0.1.0-migration-guide.md) for more information on how to switch to new API. 

Closing this, but feel free to ask any more questions about the new API. Thanks!

**Comment by petomalina** [comment]
Hi @LiliC, I am trying to use the latest master and created a new project, so I believe there is nothing to migrate for me (I don't have any previous versions).

**Comment by LiliC** [comment]
@petomalina can you share the code snippet where you call the `Create` function?

**Comment by petomalina** [comment]
@LiliC I am sharing my whole operator [here](https://github.com/petomalina/krane/tree/master/operator). I believe this may have something to do with my switch from `dep` to go mod, but the same error happened for me during new operator creation. I may get to this again tomorrow and try to reproduce the error in a sandbox.

**Comment by hasbro17** [comment]
@petomalina I would suggest to keep using `dep` since we haven't tested go modules yet.

Also can you please share the error that you see from doing:
```
$ operator-sdk new krane-operator
$ operator-sdk add api --api-version=krane.petomalina.com/v1alpha1 --kind=Canary
$ operator-sdk add controller --api-version=krane.petomalina.com/v1alpha1 --kind=Canary
```

I can see a few other discrepancies as well from the expected project structure that should be there from `operator-sdk new`.
Mainly that `cmd/krane-operator/main.go` should be `cmd/manager/main.go`

See the example memcached-operator for an example of the expected layout.
https://github.com/operator-framework/operator-sdk-samples/tree/master/memcached-operator

**Comment by LiliC** [comment]
@petomalina I tried the same command and it worked for me, using master:
```
○ operator-sdk add api --api-version=krane.petomalina.com/v1alpha1 --kind=Canary
Create pkg/apis/krane/v1alpha1/canary_types.go
Create pkg/apis/addtoscheme_krane_v1alpha1.go
Create pkg/apis/krane/v1alpha1/register.go
Create pkg/apis/krane/v1alpha1/doc.go
Create deploy/crds/krane_v1alpha1_canary_cr.yaml
Create deploy/crds/krane_v1alpha1_canary_crd.yaml
Running code-generation for custom resource group versions: [krane:v1alpha1, ]
Generating deepcopy funcs
```

Are the deepcopy files now generated as it seems to have failed right before that? Can you maybe double check, thank you!

**Comment by petomalina** [comment]
@LiliC @hasbro17 thank you both for help during debugging. I had my `GO111MODULE` set to `on` which caused the generate to fail (still don't know why tho). After setting the env to `auto`, the problem disappeared.

Should I open a new issue for this? It would be awesome to reset the variable for the time of installation or support it.

**Comment by hasbro17** [comment]
@petomalina We can open up a separate issue for that. The issue being that the SDK should support and be tested with Go modules. 
We're still on Go 1.10 and I think [modules](https://github.com/golang/go/wiki/Modules) are experimental in 1.11.
So it might be a while until we can prioritize that.

**Comment by petomalina** [comment]
Thank you, closing

**Comment by petomalina** [comment]
@hasbro17 @LiliC I am just giving one more update - I won't be creating a new issue:
Creating the operator completely from the SDK and then running `go mod init` will copy the lock files and the build passes without problems. I initialized the go mod without the lock files previously, which caused the `go mod init` to download newest versions that conflict with the current sdk.
