### ISSUE TITLE
 type.go  file use PodSpec   find error   "The CustomResourceDefinition "mydeployments.mygroup.my.copy" is invalid:"

### ISSUE THREAD

**Issue by yeliangn1** [operator-framework/operator-sdk#6656]
when I  make intsall to create  CRD  but find error:

> The CustomResourceDefinition "mydeployments.mygroup.my.copy" is invalid:
> * spec.validation.openAPIV3Schema.properties[spec].properties[podTemplate].properties[spec].properties[volumes].items.properties[ephemeral].properties[volumeClaimTemplate].properties[spec].properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
> * spec.validation.openAPIV3Schema.properties[spec].properties[podTemplate].properties[spec].properties[ephemeralContainers].items.properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
> * spec.validation.openAPIV3Schema.properties[spec].properties[podTemplate].properties[spec].properties[initContainers].items.properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
> * spec.validation.openAPIV3Schema.properties[spec].properties[podTemplate].properties[spec].properties[containers].items.properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set

My type.go  is
```
type MyDeploymentSpec struct {
	Replicas    *int32          `json:"replicas,omitempty"`
	PodTemplate PodTemplateSpec `json:"podTemplate"`
	// Foo is an example field of MyDeployment. Edit mydeployment_types.go to remove/update
	Foo string `json:"foo,omitempty"`
}
type PodTemplateSpec struct {
	Metadata metav1.ObjectMeta `json:"metadata"`

	Spec cv1.PodSpec `json:"spec"`
}
```
is there any problem  when I use PodSpec?

**Comment by everettraven** [comment]
This should be possible. I found https://github.com/kubernetes-sigs/kubebuilder/issues/3303 which seems to be similar to your issue and looks like the resolution was to upgrade the `k8s.io/api` dependency to v0.26.1 (although I don't know what your current version is) 

I would also look into using the https://pkg.go.dev/k8s.io/api/core/v1#PodTemplate type instead of creating your own.
