### ISSUE TITLE
make docker-build - CHAIN_ADD failed (nf_tables)

### ISSUE THREAD

**Issue by gerbil** [operator-framework/operator-sdk#6658]
## Bug Report

```
ERRO[0000] no such file or directory
error running container: did not get container start message from parent: EOF
Error: building at STEP "RUN go mod download": setup network: plugin type="bridge" failed (add): 
cni plugin bridge failed: failed to list chains: 
running [/usr/sbin/iptables -t nat -S --wait]: exit status 4: iptables v1.8.5 (nf_tables):  
CHAIN_ADD failed (No such file or directory): chain PREROUTING
```

#### What did you do?

make docker-build

#### What did you expect to see?

Successfull build

#### What did you see instead? Under which circumstances?

Run operator-sdk container
Try to build operator via `make docker-build`

#### Environment

**Operator type:**

 language go

`$ operator-sdk version`

operator-sdk version
operator-sdk version: "v1.33.0", commit: "542966812906456a8d67cf7284fc6410b104e118", kubernetes version: "v1.27.0", go version: "go1.21.5", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

#### Possible Solution

To use latest ubi base image

**Comment by gerbil** [comment]
Full error:

```
[1/2] STEP 8/12: RUN go mod download
WARN[0178] Failed to load cached network config: network podman not found in CNI cache, falling back to loading network podman from disk
WARN[0178] 1 error occurred:
        * plugin type="bridge" failed (delete): cni plugin bridge failed: running [/usr/sbin/iptables -t nat -D POSTROUTING -s 10.88.0.2 -j CNI-e3a3a0ee7099669efd3b9823 -m comment --comment name: "podman" id: "buildah-buildah1631898944" --wait]: exit status 2: Warning: Extension comment revision 0 not supported, missing kernel module?
iptables v1.8.5 (nf_tables): Chain 'CNI-e3a3a0ee7099669efd3b9823' does not exist
Try `iptables -h' or 'iptables --help' for more information.


WARN[0000] pkg/bind: error detaching "/var/tmp/buildah1631898944/mnt/buildah-bind-target-10": no such file or directory
WARN[0000] pkg/bind: error removing "/var/tmp/buildah1631898944/mnt/buildah-bind-target-10": no such file or directory
WARN[0000] pkg/bind: error detaching "/var/tmp/buildah1631898944/mnt/rootfs": no such file or directory
WARN[0000] pkg/bind: error removing "/var/tmp/buildah1631898944/mnt/rootfs": no such file or directory
WARN[0000] pkg/bind: error detaching "/var/tmp/buildah1631898944/mnt": no such file or directory
WARN[0000] pkg/bind: error removing "/var/tmp/buildah1631898944/mnt": no such file or directory
ERRO[0000] no such file or directory
error running container: did not get container start message from parent: EOF
Error: building at STEP "RUN go mod download": setup network: plugin type="bridge" failed (add): cni plugin bridge failed: failed to list chains: running [/usr/sbin/iptables -t nat -S --wait]: exit status 4: iptables v1.8.5 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING
```

**Comment by everettraven** [comment]
This looks like an error returned from the container tool you are using (it seems like you have `docker` aliased to `podman`?). Do you run into this error if you try to manually build the image (i.e not using the `make` target)?

**Comment by gerbil** [comment]
Im using standard operator-sdk image btw and seems like your assumption is correct:
```
sh-4.4# which podman
/usr/bin/podman
sh-4.4# which docker
/usr/bin/docker
sh-4.4# podman -v
podman version 4.6.1
sh-4.4# docker -v
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
podman version 4.6.1
```

As for local build - it goes fine. So the problem is only inside operator-sdk image (with make)

**Comment by everettraven** [comment]
I found this issue that seems similar to yours https://github.com/containers/podman/issues/14843

I don't think this is an operator-sdk issue and rather a podman issue. Can you provide more information as to the environment you are running on? It looks like this is a known issue on WSL - is that the environment you are running these commands in?

**Comment by gerbil** [comment]
> > As for local build - it goes fine. So the problem is only inside operator-sdk image (with make)
> 
> Gotcha. As a sanity check, it fails like this every time with `make docker-build`?

Yes

> I found this issue that seems similar to yours [containers/podman#14843](https://github.com/containers/podman/issues/14843)
> 
> I don't think this is an operator-sdk issue and rather a podman issue. Can you provide more information as to the environment you are running on? It looks like this is a known issue on WSL - is that the environment you are running these commands in?

Maybe; Im using operator-sdk image built from https://github.com/operator-framework/operator-sdk/blob/master/images/operator-sdk/Dockerfile

**Comment by everettraven** [comment]
> > I found this issue that seems similar to yours [containers/podman#14843](https://github.com/containers/podman/issues/14843)
> > I don't think this is an operator-sdk issue and rather a podman issue. Can you provide more information as to the environment you are running on? It looks like this is a known issue on WSL - is that the environment you are running these commands in?
> 
> Maybe; Im using operator-sdk image built from https://github.com/operator-framework/operator-sdk/blob/master/images/operator-sdk/Dockerfile

I don't think the Dockerfile itself has anything to do with this issue. It is weird that you can build it just fine outside of the `make docker-build` command, but I'm hoping to get some more information as to the actual environment you are running these commands in. 

To start, what OS are you running?

**Comment by gerbil** [comment]
I can built it locally (win pc), but not from within container (executed from operator-sdk image);

Env:
- sh-4.4# uname -a
Linux 34863d6eacf3 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- docker run command
docker run -it -v %cd%:/home --privileged --security-opt seccomp:unconfined --device /dev/fuse --workdir /home --name operator-sdk

**Comment by gerbil** [comment]
Sure, but there are also other parts of the operator-sdk - like make file for instance, that im trying to use within a container to build an image; Can't do the same on my windows pc unfortunately.

**Comment by everettraven** [comment]
>Sure, but there are also other parts of the operator-sdk - like make file for instance, that im trying to use within a container to build an image; Can't do the same on my windows pc unfortunately.

In order to build an image you need to have access to a container runtime to build it (i.e docker, podman, containerd, etc.) and projects scaffolded by the operator-sdk default to using docker. You can totally change this manually in your makefile if you prefer to use a runtime other than docker. Regardless of your runtime of choice though, if you are attempting to build an image within a container you need to ensure that container has access to a runtime. There are various resources available on how to do this with docker (also known as docker-in-docker), here is a blog post from Docker on this: https://www.docker.com/blog/docker-can-now-run-within-docker/

This sounds like a build environment issue that is completely separate from the Operator-SDK and not something we can fix for you. I'm going to close this issue due to this reason, but do feel free to reopen if you feel this has been closed in error.

**Comment by gerbil** [comment]
Even if the route cause of the issue is not Operator-sdk itself, I still think that Dockerfile provided for Operator-sdk image should support every feature available in makefile regardless of the environment. Or at least provide a guidance for win based users to work within Operator-sdk based container.
