### ISSUE TITLE
operator-sdk throws error due to GOPATH (dep related)

### ISSUE THREAD

**Issue by embano1** [operator-framework/operator-sdk#666]
## Bug Report

**What did you do?**
Followed the [user guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md) and `operator-sdk new` throws a `dep` related error (see below). It fails in an unclean state (i.e. `git init` post deployment steps are not done).

**What did you expect to see?**
Correct project initialization as described in the tutorial leaving the project in a clean state. 

**What did you see instead? Under which circumstances?**

```bash
# Operator SDK HEAD
$ git rev-parse --short HEAD
5a9f7d1
```

```bash
$ dep version
dep:
 version     : v0.5.0
 build date  : 2018-07-26
 git hash    : 224a564
 go version  : go1.10.3
 go compiler : gc
 platform    : darwin/amd64
 features    : ImportDuringSolve=false
```

**Trigger the error**

```bash
$ operator-sdk --version
operator-sdk version 0.0.7+git
$ echo $GOPATH
/Users/mgasch/GO
$ echo $PWD
/Users/mgasch/GO/src/github.com/embano1
$ operator-sdk new whalesay-operator
Create cmd/manager/main.go
Create build/Dockerfile
Create deploy/service_account.yaml
Create deploy/role.yaml
Create deploy/role_binding.yaml
Create deploy/operator.yaml
Create pkg/apis/apis.go
Create pkg/controller/controller.go
Create version/version.go
Create .gitignore
Create Gopkg.toml
**Run dep ensure ...
/Users/mgasch/_Devbox/GO/src/github.com/embano1/whalesay-operator is not within a known GOPATH/src
2018/10/29 16:26:35 failed to exec dep []string{"ensure", "-v"}: exit status 1**
```

Clearly it's an issue with `dep` here as it wants to execute within the project folder (and not parent where I am asked to execute `operator-sdk new`.

* Are you writing your operator in ansible or go?
go

**Comment by joelanford** [comment]
@embano1 It looks like when `dep` runs, it's from `/Users/mgasch/_Devbox/GO/...`, but your GOPATH is `/Users/mgasch/GO`. Do you have `/Users/mgasch/GO` symlinked to `/Users/mgasch/_Devbox/GO`? If so, I think that's your issue. See https://github.com/golang/dep/issues/1899.

**Comment by embano1** [comment]
Fantastic @joelanford! I wasn't aware of this symlink issue as it always worked with dep when I was executing **in** the git repo. 

However, I think this issue shows that we should do a better job of cleaning up when operator-sdk fails in an intermediate state.
