### ISSUE TITLE
About 1.34.0 release

### ISSUE THREAD

**Issue by chenrui333** [operator-framework/operator-sdk#6689]
👋 it looks like 1.34.0 release was not completed, ie the release did not get marked as latest release, raise this issue for some awareness! Thanks!

cc @oceanc80 

relates to https://github.com/Homebrew/homebrew-core/pull/164694

**Comment by chenrui333** [comment]
it is mostly just a label thing

![image](https://github.com/operator-framework/operator-sdk/assets/1580956/f9d20491-ac6c-4425-9909-c7dbf0bb103b)

**Comment by metacosm** [comment]
All the binaries are missing, which also breaks automation (e.g. GitHub actions)…

**Comment by metacosm** [comment]
Hopefully this will be addressed soon, this is kind of blocking because CI runs are failing because of this, thus preventing proper checking of changes.

**Comment by metacosm** [comment]
To be more explicit, this breaks https://github.com/redhat-actions/openshift-tools-installer, which cannot install the latest `operator-sdk` version anymore.

**Comment by chenrui333** [comment]
close via https://github.com/Homebrew/homebrew-core/pull/165131
