### ISSUE TITLE
OperatorStatus-style reporting

### ISSUE THREAD

**Issue by squeed** [operator-framework/operator-sdk#669]
## Feature Request

Operators should have a generic way of reporting back their status. The operator-sdk should provide code to simplify that task.

For example, in the Openshift world we need to generate an OperatorStatus object. Since the operator-sdk knows everything we're creating, it could easily do it.

**Comment by joelanford** [comment]
@squeed Just pinging to see if this is still something you need, and if so if you could help us understand what you're asking for.

**Comment by joelanford** [comment]
@squeed I'm closing this issue since there isn't much detail. Please feel free to re-open if this is still something you think would be valuable and you can give us an example of what you'd like to see.
