### ISSUE TITLE
Support for Go version 1.21

### ISSUE THREAD

**Issue by BrimstoneXmk** [operator-framework/operator-sdk#6722]
#### What did you do?

ref to this issue: https://github.com/operator-framework/operator-sdk/issues/6644 

#### What did you expect to see?

Support for Go 1.21 PR to be merged for release 1.34.1 branch for ansible-operator-plugin

#### What did you see instead? Under which circumstances?

The ansible-operator-plugin for 1.34.1 release branch doesn't have the [Bump go to 1.21](https://github.com/operator-framework/ansible-operator-plugins/pull/56) PR cherry-picked which directly could have resolved this issue [Support for Go version 1.21](https://github.com/operator-framework/operator-sdk/issues/6644). This issue is marked as resolved Overall, from the changelog point of view, this hasn't been resolved yet in 1.34.1 or 1.34.0 version.

#### Environment

**Operator type:** Ansible

**Kubernetes cluster type:**

`$ operator-sdk version`: v1.34.1

`$ go version` (if language is Go): go1.20.14

`$ kubectl version`: v1.28.0

#### Possible Solution

The ansible-operator-plugin for 1.34.1 release branch doesn't have the [Bump go to 1.21](https://github.com/operator-framework/ansible-operator-plugins/pull/56) PR cherry-picked which directly can resolve this issue.

**Comment by BrimstoneXmk** [comment]
@oceanc80, @rashmigottipati can this issue be fixed promptly?

**Comment by tarunkalra7** [comment]
FYI @everettraven @varshaprasad96 Any update on this? Facing same issue

**Comment by jberkhahn** [comment]
We need to cut a release of ansible-operator-plugins and then bump our dependency on this and cut a release.

**Comment by acornett21** [comment]
- Relates: operator-framework/operator-sdk#6651
 
Waiting on
- operator-framework/ansible-operator-plugins#67

**Comment by BrimstoneXmk** [comment]
@jberkhahn Till when can we expect the next release?

**Comment by BrimstoneXmk** [comment]
We can see that the latest release has happened for Ansible as well as for helm.
New version of operator SDK is available now : 1.34.2.
Checked Go version used in this new release.
For helm-operator, its upgraded to 1.21.10. Refer below output. 

> bash-4.4# helm-operator version
> helm-operator version: "v1.34.2", commit: "81dd3cb24b8744de03d312c1ba23bfc617044005", kubernetes version: "v1.28.0", go version: "go1.21.10", GOOS: "linux", GOARCH: "amd64"

But for ansible-operator, new release is using Go 1.21.9 . Refer below output.

> 
> bash-4.4# ansible-operator version
> ansible-operator version: "v1.34.2", commit: "1c1f3931cc40b75a6fd6f1dd48847f288abc748a", kubernetes version: "v1.28.0", go version: "go1.21.9", GOOS: "linux", GOARCH: "amd64"

can anyone explain why is this difference?

**Comment by stefanb** [comment]
Go 1.21 will become unsupported in August, so i opened an issue:
* https://github.com/operator-framework/operator-sdk/issues/6788

**Comment by acornett21** [comment]
Going to close this since `v1.36.0` addresses this.
