### ISSUE TITLE
Operator-SDK version 1.34.1 removed RBAC privs that previous versions were correctly generating from Helm

### ISSUE THREAD

**Issue by mpryc** [operator-framework/operator-sdk#6731]
#### What did you do?

Used operator-sdk 1.34.1 to recreate pelorus operator files.

We have number of calls to the operators-sdk wrapped in automation to recreate entire operator.

Lines 260; 270; 290; 308:
https://github.com/dora-metrics/pelorus/blob/master/scripts/update_projects_version.py#L260

We also apply this patch in the middle of ran just before line 308 from the above script:
https://github.com/dora-metrics/pelorus/blob/master/scripts/pelorus-operator-patches/03_pelorus_operators_roles.diff

As a result rbac privs are not correctly generated. All the RBAC from the above patch are not included in the final pelorus-operator/config/rbac/role.yaml file.

This did not happen in the previous versions of operator-sdk.

As a result the operator fails to install.

#### What did you expect to see?

Properly included RBAC privs from the path that ends up in the pelorus-operator/config/rbac/role.yaml file.

#### What did you see instead? Under which circumstances?

Using operator-sdk 1.34.1 those RBAC are not properly included (they are missing)

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by acornett21** [comment]
- Duplicate: #6698

**Comment by acornett21** [comment]
Closing as duplicate.
