### ISSUE TITLE
Failed to initialize project: unable to scaffold with "base.ansible.sdk.operatorframework.io/v1"

### ISSUE THREAD

**Issue by saadahmed9** [operator-framework/operator-sdk#6739]
### Bug Report
I installed all the prerequisites before initializing the project,  downloaded the operator-sdk binary from Github and tried creating my first operator via below command mentioned in the operator-sdk docs:

operator-sdk init --domain example.com --plugins ansible

### Environment: 

      operator-sdk version: "v1.34.1", commit: "edaed1e5057db0349568e0b02df3743051b54e68", kubernetes version: "1.28.0", go 
      version: "go1.21.7", GOOS: "darwin", GOARCH: "amd64"

What did you expect to see?
I expected a successful first initialization.

What did you see instead? Under which circumstances?
I saw the below error: 

    FATA[0000] failed to initialize project: unable to scaffold with "base.ansible.sdk.operatorframework.io/v1": error updating init 
    manifests: error updating kustomization.yaml files: remove config/default/kustomization.yaml patch and vars blocks: unable to 
    find the content to be replaced 

### However, project init was succesfull, when I tried go and helm plugins.

**Comment by acornett21** [comment]
- Relates: operator-framework/ansible-operator-plugins#61

**Comment by acornett21** [comment]
closing as duplicate
