### ISSUE TITLE
Unable to remove an operator

### ISSUE THREAD

**Issue by marrip** [operator-framework/operator-sdk#6742]
## Type of question

General operator-related help

#### What did you do?

We are running a k3s cluster and installed `olm` via `operator-sdk` which worked perfectly. We started adding a couple of operators and wrongly placed one of them into the namespace `stackgres` and "moved" the operator later to the namespace `operators`, however, the initial one is still there even after a complete `uninstall` and new `install` of `olm` via the cli.

#### What did you expect to see?

We expect the operator to be deleted after "moving" to a different namespace and we also expect it to be deleted after reinstalling everything.

#### What did you see instead? Under which circumstances?

The operator is present for both the `stackgres` and the `operators` namespace.

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`

`operator-sdk version: "v1.34.1", commit: "edaed1e5057db0349568e0b02df3743051b54e68", kubernetes version: "1.28.0", go version: "go1.21.7", GOOS: "linux", GOARCH: "amd64"`

`$ go version` (if language is Go)

`$ kubectl version`

`Major:"1", Minor:"27", GitVersion:"v1.27.10+k3s2", GitCommit:"5b2ac8816958c90888150efb848fc2e2e2c29153", GitTreeState:"clean", BuildDate:"2024-02-06T01:35:14Z", GoVersion:"go1.20.13", Compiler:"gc", Platform:"linux/amd64"`

**Comment by acornett21** [comment]
Hi @marrip It's unclear if you are having an issue with `operator-sdk` or with `olm` what is the workflow you are following? Are you running `operator-sdk run bundle`?

**Comment by marrip** [comment]
we installed `olm` via `operator-sdk install olm`. We got rid of the `stackgres` operator after removing finalizers on different associated resources. However, we came to the conclusion that it was an issue with `olm` and not `operator-sdk`. Sorry about opening it here.
