### ISSUE TITLE
update ownership handling for consistency

### ISSUE THREAD

**Issue by grokspawn** [operator-framework/operator-sdk#6745]
Currently, OWNERS* files are ignored because the repo does not have a prow instance governing it. (Instead, authentication falls back on github groups.)  

We should integrate with [prow-github-actions](https://github.com/jpmcb/prow-github-actions) to support authentication via the established OWNERS* files.

**Comment by jberkhahn** [comment]
This is something we had looked into in the past, but it was a large amount of work. This is also something that would probably need to be done at the org level and shared between the various OF subprojects?
