### ISSUE TITLE
Can't generate ansible type operator with the latest operator-sdk

### ISSUE THREAD

**Issue by emmajiafan** [operator-framework/operator-sdk#6746]
#### What did you do?

operator-sdk version:
operator-sdk version: "v1.34.0-10-gc762768c", commit: "c762768c8a128563147dd99218e4ba9ecc035557", kubernetes version: "v1.28.0", go version: "go1.21.4", GOOS: "linux", GOARCH: "amd64"
generate the ansible type operator
$operator-sdk init --plugins=ansible --domain=example.com

#### What did you expect to see?

generate ansible type operator success

#### What did you see instead? Under which circumstances?

$ operator-sdk init --plugins=ansible --domain=example.com
INFO[0000] Writing kustomize manifests for you to edit... 
Error: failed to initialize project: unable to scaffold with "base.ansible.sdk.operatorframework.io/v1": error updating init manifests: error updating kustomization.yaml files: remove config/default/kustomization.yaml patch and vars blocks: unable to find the content to be replaced
.........

FATA[0000] failed to initialize project: unable to scaffold with "base.ansible.sdk.operatorframework.io/v1": error updating init manifests: error updating kustomization.yaml files: remove config/default/kustomization.yaml patch and vars blocks: unable to find the content to be replaced

**Comment by acornett21** [comment]
- Relates: operator-framework/ansible-operator-plugins#61

**Comment by acornett21** [comment]
@manas-d2 There isn't a fix yet, you could downgrade to `1.33.0` and that should work.
