### ISSUE TITLE
Add --skip-git to allow skipping git initialization within the newly created folder

### ISSUE THREAD

**Issue by petomalina** [operator-framework/operator-sdk#675]
## Feature Request (minor)

**Is your feature request related to a problem? Please describe.**
I am trying to add an operator into an already existing project - thus already having the git repo initialized in the root folder.

**Describe the solution you'd like**
We could simply add a `--skip-git` flag into `operator-sdk new` command, so the git repo won't be initialized.

**Comment by LiliC** [comment]
@petomalina The `operator-sdk new` command has a `--skip-git-init` flag. Let me know if you run into any problems with the flag, thanks.

**Comment by petomalina** [comment]
Ahh, thank you @LiliC I updated the CLI from master and you are right. Closing this. Thank you :slightly_smiling_face:
