### ISSUE TITLE
Go Operator Tutorial

### ISSUE THREAD

**Issue by ShockleyJE** [operator-framework/operator-sdk#6762]
In this section of [golang operator tutorial](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#a-note-on-dependency-management) documentation: 

> Note If your local environment is Apple Silicon (darwin/arm64) use the go/v4-alpha plugin which provides support for this platform by adding to the init subCommand the flag --plugins=go/v4-alpha

`-alpha` can be removed since the plugin is [now stable](https://github.com/kubernetes-sigs/kubebuilder/discussions/3217)

If y'all would like I can make these changes myself, would just need the relevant permissions. Happy to create additional PR's as well for anything I find to support y'all's work 👍 👍

**Comment by acornett21** [comment]
Hi @ShockleyJE  thanks for the issue, there is already a PR open for this. Help is always welcome, since this project is very low on maintainers right now. Feel free to pull stuff from the backlog.

- Relates: #6732
