### ISSUE TITLE
Go Operator Tutorial: plugins version issue

### ISSUE THREAD

**Issue by hjeongb0320** [operator-framework/operator-sdk#6778]
- related: #6762 

Hi, recently, I'm following the quick start of operator sdk. In the process, I found that there was an error in the plugin-related docs in the middle, and I confirmed that it was fixed. However, there is the same part in the "tutorial" documentation, not the "quick-start" documentation (because the content itself is a process of re-installing and learning the principle from scratch), and that part was not modified. Recently, the correct issue was uploaded, and this seems to be a problem caused by confusion between quick start and tutorial, so I am reporting the issue.

[What needs to be revised]

- before: Note If your local environment is Apple Silicon (darwin/arm64) use the go/v4-alpha plugin which provides support for this platform by adding to the init subCommand the flag --plugins=go/v4-alpha
- after: Note If your local environment is Apple Silicon (darwin/arm64) use the "go/v4" plugin which provides support for this platform by adding to the init subCommand the flag --plugins="go/v4"

Thank you for your hard work, managers.

**Comment by acornett21** [comment]
Hi @hjeongb0320 I'm not sure I understand this issue. `go/v4` plugin has moved for the `alpha` phase to be GA, so the pull request that was merged is correct. If docs are incorrect, can you link to those pages in the issue?

**Comment by hjeongb0320** [comment]
Hi, I mean in this docs, [Create a new project] !
https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/
