### ISSUE TITLE
Documentation uses deprecated examples of defining namespace scope in manager options

### ISSUE THREAD

**Issue by NymanRobin** [operator-framework/operator-sdk#6796]
While reading the [operator-scope section](https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope), I noticed that the documentation contains a mix of current and deprecated method for defining the namespace to watch in the manager options.

When introducing the manager watch options it correctly defines it according to the current standard

```
mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
    Scheme:             scheme,
    MetricsBindAddress: metricsAddr,
    Port:               9443,
    LeaderElection:     enableLeaderElection,
    LeaderElectionID:   "f1c5ece8.example.com",
    Cache: cache.Options{
      DefaultNamespaces: map[string]cache.Config{"operator-namespace": cache.Config{}},
    },
})
```

However, further down in the document when giving a [code examples](https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#configuring-namespace-scoped-operators) it gives the old and deprecated syntax of giving the Namespace option directly.

```
watchNamespace, err := getWatchNamespace()
if err != nil {
    setupLog.Error(err, "unable to get WatchNamespace, " +
       "the manager will watch and manage resources in all namespaces")
}

mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
    Scheme:             scheme,
    MetricsBindAddress: metricsAddr,
    Port:               9443,
    LeaderElection:     enableLeaderElection,
    LeaderElectionID:   "f1c5ece8.example.com",
    Namespace:          watchNamespace, // namespaced-scope when the value is not an empty string
})
```

Noticed that the [tutorial](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#manager) also uses examples with the deprecated Namespace variable when introducing the Manager.

I think it would make sense to unify the documentation and only use the new style of giving the Namespace

**Comment by jameskim0987** [comment]
@acornett21 Hi, I was just browsing issues with help wanted and saw this one. From looking at the linked PR, it seems like this issue has been resolved. If that's the case, perhaps I'm wondering if this issue could be closed? Thanks!
