### ISSUE TITLE
Missing Enable ClusterMonitoring Label in Operator Namespace

### ISSUE THREAD

**Issue by Lucifergene** [operator-framework/operator-sdk#6825]
According to the OKD Docs for [enabling metrics for custom operators](https://docs.okd.io/4.16/operators/operator_sdk/osdk-monitoring-prometheus.html#osdk-monitoring-custom-metrics_osdk-monitoring-prometheus), it mentions to add the following label to the namespace of the operator:
```
oc label namespace <operator_namespace> openshift.io/cluster-monitoring="true"
```
This label is missing in the example memcached-operator with monitoring: 
https://github.com/operator-framework/operator-sdk/blob/d2366bef634034fa3179629cfef3b7d68cde1727/testdata/go/v4/monitoring/memcached-operator/config/manager/manager.yaml#L4

Is there no current requirement for this label?

**Comment by acornett21** [comment]
Hi @Lucifergene this is an upstream project, so it has no vendor specific labeling requirements. If OKD requires that then operator authors targeting OKD would need to add this on their own.
