### ISSUE TITLE
Using kubebuilder's built-it mechanizm to secure /metrics instead of using kube-rbac-proxy in helm-operator

### ISSUE THREAD

**Issue by dchirikov** [operator-framework/operator-sdk#6844]
#### Describe the problem you need a feature to resolve.

Hi Team. In helm-operator code the /metrics endpoint is exposed and is using 3rd party component `kube-rbac-proxy` to secure access to it. The image is being used is being currently hosted on gcr.io. There is a plan to retire container registry on GCP so image will not be available from March 18, 2025

#### Describe the solution you'd like.

The proposed solution is to migrate to built-in authn/authz mechanism added to kubebuilder `WithAuthenticationAndAuthorization`. More details are described on the kubebuilder's page:
https://book.kubebuilder.io/reference/metrics

/language helm

**Comment by acornett21** [comment]
Hi @dchirikov With the below issue, we'll move to kubebuilder 4.1.1 and away from scaffolding the kube-rbac-proxy, there is nothing stopping you from moving your project to the latest controller runtime to pickup these changes if you need them before operator-sdk's work is finished.

- #6730
