### ISSUE TITLE
test command fails when the expected deploy manifests are missing

### ISSUE THREAD

**Issue by darkowlzz** [operator-framework/operator-sdk#701]
## Bug Report

**What did you do?**
I created e2e tests as per this [doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/writing-e2e-tests.md) and on running them got errors:
```
$ operator-sdk test local ./test/e2e
2018/11/04 17:13:39 could not find role manifest: open deploy/role.yaml: no such file or directory
```

I removed the default role.yaml file because it's not needed for my operator. I create a service account and rolebinding.
Creating an empty role.yaml file and running results in a panic:
```
panic: interface conversion: interface {} is nil, not map[interface {}]interface {} [recovered]
	panic: interface conversion: interface {} is nil, not map[interface {}]interface {}

goroutine 47 [running]:
testing.tRunner.func1(0xc000254700)
	/usr/local/go/src/testing/testing.go:792 +0x387
panic(0xff8220, 0xc00056d770)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/darkowlzz/operator/vendor/github.com/operator-framework/operator-sdk/pkg/test.setNamespaceYAML(0xc0001e8095, 0x19f, 0x19f, 0xc00004818f, 0x12, 0xc000426400, 0x0, 0x0, 0xc00045a780, 0xc000353800)
	/home/darkowlzz/go/src/github.com/darkowlzz/operator/vendor/github.com/operator-framework/operator-sdk/pkg/test/resource_creator.go:58 +0x27b
github.com/darkowlzz/operator/vendor/github.com/operator-framework/operator-sdk/pkg/test.(*TestCtx).createFromYAML(0xc0002b6040, 0xc0001e8000, 0x754, 0x954, 0x900, 0xc000426400, 0x0, 0x104a640)
```

This happens due to the empty yaml section in the generated deploy/test/namespace-manifests.yaml file
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-sa
  namespace: default

---

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
...
```

**What did you expect to see?**
The tests run as expected.

**Environment**
* operator-sdk version: v0.1.0

* Are you writing your operator in ansible or go? Go.

**Possible Solution**

The test command should not fail, but maybe raise warnings when the expected files are missing. And a check on the file content before appending it with the other manifests.

**Comment by AlexNPavel** [comment]
Thanks for reporting this bug. The most immediate fix for this bug would be manually creating your namespaced manifests yaml file with the correct manifests and using the `--namespaced-manifest` flag for the test (See https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#test).

I do agree that it would be better for the tests command to simply print a warning when a manifest file is not found and not crash if there is an empty section in the manifests file. I will try to get a fix up for those 2 issues soon.
