### ISSUE TITLE
Authentication using oidc

### ISSUE THREAD

**Issue by allamand** [operator-framework/operator-sdk#710]
## Feature Request

**Is your feature request related to a problem? Please describe.**

When developping my operator, I need to connect using my local kube/config file.
To authenticate on our kubernetes cluster we are using Dex so the oidc authentication, but it panic : 

```
panic: No Auth Provider found for name "oidc"
```

**Describe the solution you'd like**

I found a workaround to my problem by adding this line in the vendor/operator-framework/operator-sdk/pkg/k8sclient/client.go : 

```
_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
```

Is it possible to add this line in the official release ? or is there a way I can configure this elsewhere ?

thanks

**Comment by joelanford** [comment]
@allamand  I'm not positive this will work, but have you tried adding that import line to your main.go?

Here's an example of a similar import (albeit with the latest SDK version that uses controller-runtime): https://github.com/operator-framework/operator-sdk-samples/blob/4c6934448684a6953ece4d3d9f3f77494b1c125e/memcached-operator/cmd/manager/main.go#L12

**Comment by allamand** [comment]
Thanks, @joelanford for replying. Unfortunately, I already try to put this in my main.go but it doesn't work.
I've not yet migrated on the latest SDK, maybe the behavior is different then, since the file I referenced above seams to not exists in new version : https://github.com/operator-framework/operator-sdk-samples/tree/4c6934448684a6953ece4d3d9f3f77494b1c125e/memcached-operator/vendor/github.com/operator-framework/operator-sdk/pkg

**Comment by joelanford** [comment]
@hasbro17 Any ideas on this?

**Comment by hasbro17** [comment]
@allamand The SDK has no longer has `pkg/k8sclient`. It uses the [controller-runtime's client](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/client.md) now.

The `No Auth Provider` is a common issue since the plugins aren't included by default and you have to import them like you did. We had to do the same for the gcp plugin a while back #376 (although I just realized that needs to be added to the main.go scaffold again after the refactoring).

However I'm surprised it isn't working when you import `_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"` in main.go. That SDK version shouldn't really matter. 

I'll need to test out this out to see why this isn't working because if we support these plugins by default I'm not sure where else we would import them for v0.1.0.

**Comment by hasbro17** [comment]
Yeah the gcp auth plugin works fine when included in main.go.
And it panics if I remove `_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"` from main.go run the operator out of cluster against GKE:
```
$ operator-sdk up local
2018/11/07 11:45:37 Go Version: go1.10.2
2018/11/07 11:45:37 Go OS/Arch: darwin/amd64
2018/11/07 11:45:37 operator-sdk Version: 0.1.1+git
panic: No Auth Provider found for name "gcp"
...
```

Not sure how to test out the oidc case though.

**Comment by shawn-hurley** [comment]
@hasbro17 Should we add this to documentation (about adding an auth plugin) rather than adding them to the scaffold?

**Comment by hasbro17** [comment]
@shawn-hurley Yes we should add a note somewhere(probably in the `up local` section) to import any necessary auth plugins in `main.go` in order to run out of cluster.
https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth

**Comment by allamand** [comment]
Hello,

I made new try and found that it works in the main.go, but the order import is important : 

this don't works : 
```
        "github.com/operator-framework/operator-sdk/pkg/sdk"
	_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
	
```

this order works : 
```
	_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
	"github.com/operator-framework/operator-sdk/pkg/sdk"
```

The bad thing is that my goland IDE plugin automatically change the order of my imports and put it in the order where it don't works :(

**Comment by joelanford** [comment]
@allamand We ended up adding all of the client-go auth plugins in #1199, which will be included in our next release, so this should be fixed.
