### ISSUE TITLE
[question] Which function replace k8sutil.RuntimeObjectFromUnstructured

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#725]
Since the new release of the operator-sdk, this utility function part of the release `0.0.7` doesn't exist anymore

[k8sutil.RuntimeObjectFromUnstructured](https://github.com/operator-framework/operator-sdk/blob/v0.0.7/pkg/util/k8sutil/k8sutil.go#L72)

Is there a package/function replacing it ?

**Comment by shawn-hurley** [comment]
Why do you need this function? what is the use case?
