### ISSUE TITLE
Can't add a new api ->  'operator-sdk add api' can only be run for Go operators.

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#726]
## Bug Report

The following command 

```
operator-sdk add api --api-version=component.k8s.io/v1alpha1 --kind=Component 
```
executed within my project : https://github.com/snowdrop/component-operator/tree/operator-0.1.1

generates this error

```
2018/11/09 10:34:27 'operator-sdk add api' can only be run for Go operators.
```

## Version used

```
operator-sdk version v0.1.1+git
```

**Comment by LiliC** [comment]
@cmoulliard Hello, what kind of an operator were you building? Ansible or go?

**Comment by cmoulliard** [comment]
go operator

**Comment by cmoulliard** [comment]
This command also generates the same error 

```
operator-sdk generate k8s
2018/11/09 10:57:21 'operator-sdk generate k8s' can only be run for Go operators.
```
when executed at the root of my project

**Comment by LiliC** [comment]
@cmoulliard The error is because operator-sdk is expecting the `main.go` file to be at `cmd/manager/main.go` path.

**Comment by cmoulliard** [comment]
Many thanks. Can you update please then the migration guide as I don't think that this is documented ?

**Comment by LiliC** [comment]
@cmoulliard There is a mention of it, but feel free to maybe point out how we can be more clear in that so we can update it: https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/v0.1.0-migration-guide.md#copy-changes-from-maingo Thanks!

**Comment by cmoulliard** [comment]
I propose to do 2 things: 

- Add another section within the Guide or Migration Guide to mention that it mandatory that the `main.go` file is created under the path `cmd/manager` due to the fact the `operator-sdk` is scanning this path to determine if the project is a `Go Operator` vs something else
- Update the message reported by the `operator-sdk` client to explain why it thinks that the project is not a `Go Operator` and what should be the rules validated
