### ISSUE TITLE
Ansible Operator runs continually

### ISSUE THREAD

**Issue by aweiteka** [operator-framework/operator-sdk#729]
## Bug Report

**What did you do?**
Created a simple operator to declare objects under config management. Source: https://github.com/aweiteka/opsconfig-operator 

I annotated the [custom resource](https://github.com/aweiteka/opsconfig-operator/blob/master/deploy/ops_v1alpha1_opsconfig_cr.yaml) `ansible.operator-sdk/reconcile-period: "30s"`

**What did you expect to see?**
I expected the operator to watch the custom resource and run playbook if the cr changes. Otherwise I expected the playbook to wait until next reconcile-period (30s) 

**What did you see instead? Under which circumstances?**
The playbook runs constantly. Unclear what this error is: `did not receive playbook_on_stats event` (full output below)

**Environment**
* operator-sdk version: v0.1.0+git

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-11-09T01:25:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: minishift

* Are you writing your operator in ansible or go? Ansible

**Additional context**

OUTPUT

```
$  operator-sdk up local --namespace opsconfig
INFO[0000] Go Version: go1.9.7                          
INFO[0000] Go OS/Arch: linux/amd64                      
INFO[0000] operator-sdk Version: v0.1.0+git             
INFO[0000] watching namespace: opsconfig                
INFO[0000] Starting to serve on 127.0.0.1:8888          
INFO[0000] Watching ops.openshift.com/v1alpha1, Opsconfig 
INFO[0004] ansible-runner exited successfully            component=runner job=4544230080896754932 name=post-install namespace=opsconfig
ERRO[0004] did not receive playbook_on_stats event      
INFO[0008] ansible-runner exited successfully            component=runner job=5677574673867650771 name=post-install namespace=opsconfig
ERRO[0008] did not receive playbook_on_stats event      
INFO[0013] ansible-runner exited successfully            component=runner job=1646352905985815204 name=post-install namespace=opsconfig
ERRO[0013] did not receive playbook_on_stats event      
INFO[0018] ansible-runner exited successfully            component=runner job=6349805690248942967 name=post-install namespace=opsconfig
ERRO[0018] did not receive playbook_on_stats event 
```

**Comment by mhrivnak** [comment]
I think something in your ansible code is failing. If you build from the latest master, you should see more info in the log.

**Comment by LiliC** [comment]
@aweiteka Did you manage to add more logs or resolve the problem?

**Comment by aweiteka** [comment]
I haven't been able to resolve it due to some environment issues but let's close this now and I'll open a new issue with more detail if there's still an issue. Thanks.
