### ISSUE TITLE
Improve error message when no resources have been added to operator

### ISSUE THREAD

**Issue by jroper** [operator-framework/operator-sdk#732]
If you create a new operator, and then run `operator-sdk generate k8s` without first creating any custom resources, as the getting started guide was instructing people to do until https://github.com/operator-framework/getting-started/issues/30 fixed it, you get this less than helpful error message:

```sh
$ operator-sdk generate k8s
Running code-generation for custom resource group versions: []
2018/11/12 14:32:03 failed to perform code-generation: (exit status 255)
```

This could be improved to something more informative so that if people do do this (for example, if they accidentally miss the step that I added to the getting started guide), they have some hope of working out what they did wrong.

**Comment by hasbro17** [comment]
We forgot to print out the combined output (stdout and stderr) when the command fails. Right now we're only doing it after it succeeds. We need to make the following change:
```Go
log.Fatalf("failed to perform code-generation: (%v) %v", err, out)
``` 
https://github.com/operator-framework/operator-sdk/blob/master/commands/operator-sdk/cmd/generate/k8s.go#L78

**Comment by estroz** [comment]
#707 sends errors to Stdout.
