### ISSUE TITLE
Reconcile does not keep status for CRDs without spec defined

### ISSUE THREAD

**Issue by yanirq** [operator-framework/operator-sdk#733]
## Bug Report

**What did you do?**
1. Created an ansible operator that watches an existing CRD (that is part of a kubevirt/openshift cluster):

``operator-sdk new templates-ansible-operator --api-version=template.openshift.io/v1  --kind=Template --type=ansible``

The Template CRD is defined by openshift and the assumption is we cannot change its structure.
This resource does not contain a spec field under its root structure:
see [how to write Openshift templates](https://docs.openshift.com/container-platform/3.11/dev_guide/templates.html#writing-templates)  and [openshift template structure](https://github.com/openshift/origin/blob/a7f822da48080b80aebdc8e3ae611564b79ab01f/pkg/template/apis/template/types.go#L13).

2. Created a simple playbook which watches.yaml refers locally. 
3. Deployed on the cluster service_account, role and role_binding
4. Ran operator-sdk up local 
5. Create a template object in the cluster.

**What did you expect to see?**
The ansible operator should have detected the newly created Template, run the playbook and stop until the next change to the Template resource.

**What did you see instead? Under which circumstances?**
Ansible operator start by first issuing a warning message:

``WARN[0557] spec was not found for CR:template.openshift.io/v1, Kind=Template - default in rhel7-generic-small`` 

Then runs the playbook which exists successfully:
``INFO[0588] ansible-runner exited successfully            component=runner job=678987871726972421 name=rhel7-generic-small namespace=default``

And eventually starts this whole process again in an endless loop.

Checking further more, it seems that if the operator watches CRDs that do not contain spec under their structure (e.g. as defined in api/types.go) it will either fail and exit or do nothing when trying to [update the resource](https://github.com/operator-framework/operator-sdk/blob/fa72147bd448d70816a2ffc6b8cdecb842235512/pkg/ansible/controller/reconcile.go#L111) with the current status and conditions. 
In my case, there was no failure, but the Template resource didn't get updated with a spec.status field (since it does not have spec defined in its struct) 

**Environment**
* operator-sdk version:
https://github.com/operator-framework/operator-sdk/commit/fa72147bd448d70816a2ffc6b8cdecb842235512 

* Kubernetes version information:
oc v3.10.0+0c4577e-1
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.10.0+456651d-57
kubernetes v1.10.0+b81c8f8

* Kubernetes cluster kind: 
Openshift 3.10.0

* Are you writing your operator in ansible or go?
ansible

**Comment by shawn-hurley** [comment]
Hi @yanirq 

I have a couple of questions.

> In my case, there was no failure, but the Template resource didn't get updated with a spec.status field (since it does not have spec defined in its struct)

Nothing should have a `spec.status` I don't understand what you're expecting to happen here?

It seems to me that you are watching and running a playbook.
> WARN[0557] spec was not found for CR:template.openshift.io/v1, Kind=Template - default in rhel7-generic-small

> Then runs the playbook which exists successfully:
> INFO[0588] ansible-runner exited successfully component=runner job=678987871726972421 name=rhel7-generic-small namespace=default

This appears to be watching the resources correctly is that the correct take away?

We are adding the ability to "turn off" the ansible operator managing the status of a resource, but I want to caution you on the direction this is going. Are you attempting to make a controller for the openshift templates backed by ansible? I am sorry that I could not help more directly hopefully we can figure out what you need and get this working for you. 

Thanks!

**Comment by yanirq** [comment]
After a discussion and some clarifications with @shawn-hurley closing this issue: 
- We could get openshfit templates watch process to kick in in case of any change to the openshift template without running reconcile over and over for each event by: 
1. setting reconcile period to 0,.
2. Disabling status changes on the object (which isn't really possible right now when dealing with openshift template CRDs)

(a new issue/rfe might be opened for the need of integrating an idempotent observation when watching CRDs that are not generated by the operator-sdk using ansible playbooks)
