### ISSUE TITLE
Default metrics port is in ip_local_port_range

### ISSUE THREAD

**Issue by squeed** [operator-framework/operator-sdk#735]
The default metrics port of 60000 is in the `ip_local_port_range`, which means it can collide with TCP connections:

```
[root@test1-master-0 core]# sysctl net.ipv4.ip_local_port_range
net.ipv4.ip_local_port_range = 32768    60999
```

It is best practice not to listen in that range, as you can collide with existing tcp outgoing connections.

**Comment by LiliC** [comment]
@squeed thanks for this, I am in the middle of redoing the metrics story, will keep this in mind by choosing a default port outside of this range, but also add the ability to override that.

**Comment by LiliC** [comment]
Fixed in https://github.com/operator-framework/operator-sdk/pull/786
