### ISSUE TITLE
Populate ClusterRole and ClusterRoleBinding files 

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#736]
## Feature Request

The current scaffolding's feature generates operator's code, API like also the k8s files needed to install the resources such as sa, rbac, ... but [no files are generated](https://goo.gl/kPs6eP) in order to let the operator to been able to operate as `scope: cluster`

I propose, using maybe an additional parameter, to offer the possibility to also generate ClusterRole and ClusterRoleBinding files

**Comment by joelanford** [comment]
There is a related open issue about supporting cluster-scoped operators (#236).

We could add a new `--cluster-scoped` boolean flag to the new command to generate a cluster-scoped operator, but [there's potentially more involved](https://github.com/operator-framework/operator-sdk/issues/236#issuecomment-396329803) than just changing the RBAC resources to be cluster-scoped.

Another problem we'd have to solve is that generating a valid `ClusterRoleBinding` requires a namespace for the subject service account, which the scaffolding does not currently support.

To solve that problem, the two options I can think of are:
* The SDK generates the `ClusterRoleBinding` with namespace set to `default` and we document that the user would need to change that according to their environment.
* We add another flag (`--namespace` or similar), which we could use to insert the provided operator namespace into the scaffolded files.

In the meantime, would it suffice if we added a section to the docs about how to migrate the generated `role.yaml` and `rolebinding.yaml` to be a ClusterRole and a ClusterRoleBinding?

**Comment by cmoulliard** [comment]
> if we added a section to the docs

Adding a section to the doc with an example is of course a first step and I agree on that

**Comment by cmoulliard** [comment]
> To solve that problem, the two options I can think of are

This solution LGTM ;-)

**Comment by LiliC** [comment]
@joelanford I like the following suggestion a bit more:

> The SDK generates the ClusterRoleBinding with namespace set to default and we document that the user would need to change that according to their environment.

We already have places in the generated manifests where the user needs to replace it with their own image for example. So we could add a placeholder namespace that would error out by k8s to prevent from accidental `ClusterRoleBinding` creation. Something like `<REPLACE_NAMESPACE>` comes to mind :) The drawback is it requires extra documentation. 

But a flag works as well, just we would default to "default" ns in case the flag is not passed or error out?
