### ISSUE TITLE
Generate API docs from CRD Go type comments

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#742]
## Feature Request

I think that it could be very interesting to offer as `kubebuilder` does a command to generate the doc of the API and also of the Manager which exposes the logic that a user will use

Example : `kubebuilder doc` [command](https://book.kubebuilder.io/beyond_basics/generating_documentation.html)

**Comment by hasbro17** [comment]
Tracking this upstream in controller-tools to see if that isn't a better place for an API docs generator.
https://github.com/kubernetes-sigs/controller-tools/issues/240

Also kubebuilder no longer seems to have the `docs` command in v2.
