### ISSUE TITLE
Add flag to allow running operator locally for tests

### ISSUE THREAD

**Issue by AlexNPavel** [operator-framework/operator-sdk#745]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, users must build an image and point their `operator.yaml` or deployment section in their namespaced manifest file to the newly built image. It must also be accessible to be pulled by the kubernetes cluster running the tests. This can be a bit complicated for CI.

**Describe the solution you'd like**
We should add a flag that allows the user to run the operator itself on the local machine for testing (similar to the way `up local` works). This is a bit complicated to handle with regards to working with the test framework, but definitely doable.

cc @aravindhp

**Comment by ravisantoshgudimetla** [comment]
@AlexNPavel - IIUC, you're trying to add a flag to run tests locally. If you are adding the flag, I think you can use the same flag to skip the `WaitForDeployment` function, in case the flag is set and properly documenting that it this function will be skipped if that flag is set makes sense.

**Comment by AlexNPavel** [comment]
@ravisantoshgudimetla That could break the tests though. The `WaitForDeployment` function can be used for any deployments you expect to be created. The `memcached-operator` sample's tests waits until the memcached deployment reaches first 3 replicas and then 4 replicas during its test. Skipping `WaitForDeployment` would cause the test to skip these checks and thus the tests would pass even if there is a problem with the operator.

**Comment by ravisantoshgudimetla** [comment]
@AlexNPavel. I believe you are talking about https://github.com/operator-framework/operator-sdk-samples/blob/master/memcached-operator/test/e2e/memcached_test.go#L117. Just to be clear, I was not asking `WaitForDeployment` to be skipped everytime but only for the operator deployment if the mentioned flag in my previous comment is set, so that we can proceed with other steps. The operator deployment step would be replaced with starting the operator manually or using the binary built. Let me know, if I am missing something

**Comment by AlexNPavel** [comment]
I will implement this by adding a new function. We will keep `WaitForDeployment` the same in order to prevent breakage and add a new `WaitForOperatorDeployment` function that should be used for operators. They will both act the same overall and call an unexported function that takes a bool to specify if it should check the global test framework variable and skip the wait if a bool is set to `true`. This should allow us to use keep the old method signatures while also allowing us to implement this new functionality without code duplication.
