### ISSUE TITLE
example operator-sdk build quay.io/example/app-operator fails

### ISSUE THREAD

**Issue by rigazilla** [operator-framework/operator-sdk#748]
## Bug Report

**What did you do?**
Followed the example in the readme

**What did you expect to see?**
The example app-operator working

**What did you see instead? Under which circumstances?**
The build process fails:
```
✔ ~/go/src/github.com/rigazilla/app-operator [master L|✚ 1…9] 
15:30 $ operator-sdk build quay.io/example/app-operator
# github.com/rigazilla/app-operator/pkg/controller/appservice
pkg/controller/appservice/appservice_controller.go:85:15: undefined: reqLogger
FATA[0008] failed to build operator binary: (exit status 2) 
```

**Environment**
* operator-sdk version:

  commit 273df3f64337d9e6cb56cb12833fa036c962402d

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-11-15T02:24:36Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

* Are you writing your operator in ansible or go?

go
```
15:49 $ go version
go version go1.11.1 linux/amd64
```

**Possible Solution**
use operator-sdk version v0.1.1

**Additional context**

**Comment by LiliC** [comment]
Thanks for your bug report! I can confirm I can recreate this.
