### ISSUE TITLE
Issue removing finalizers when namespace containing operator and CR is deleted

### ISSUE THREAD

**Issue by philbrookes** [operator-framework/operator-sdk#762]
## Bug Report

**What did you do?**
I have created a repo with a simple operator that reproduces the bug:
https://github.com/philbrookes/finalizer-operator

The gist of the bug is: 
- Create an operator and a custom resource in a namespace 
- Have the operator add a finalizer to the custom resource
- Delete the namespace
- Operator is deleted before it can remove the finalizer from the custom resource

**What did you expect to see?**
The operator given the opportunity to remove it's finalizers and clean up, before being deleted.

**What did you see instead? Under which circumstances?**
The operator was deleted before removing it's finalizers

**Environment**
* operator-sdk version: 0.0.6

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-11-15T14:18:49Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
go

**Comment by hasbro17** [comment]
@philbrookes Yeah that's a common problem with all operators/controllers. If your operator isn't around, it can't be expected to cleanup and remove finalizers.
Can you explain the use case where you would want to delete the namespace before deleting the CRs. I know it's an easy way to cleanup everything.

@chancez I might be wrong but I seem to recall you brought up this issue once before. Any idea if we can prevent the operator from being deleted by the namespace?
One possibility might be to have a [pre stop hook](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks) to remove all finalizers.

**Comment by chancez** [comment]
You could add a finalizer to the operator pod itself potentially. Generally speaking though, an operator could depend on resources in the cluster to clear finalizers, so it may still get stuck itself. Generally I've learned that operators _are special_ and probably need to live in a location separate from the resources they manage (eg operator runs in one namespace, but watches a different namespace, or all namespaces). Otherwise it just gets really complicated to prevent you, and anything you depend on (which you may not own) from being deleted as an operator.

**Comment by chancez** [comment]
Also, a `pre stop hook` would be delivered when the container receives any termination event, including in scaling.

**Comment by philbrookes** [comment]
I'm not sure that moving the operator into it's own namespace solves the overall problem (though it does solve my specific example); if the operator namespace is deleted before the resources namespace, the resources namespace would still be unable to cleanly terminate.

So I wonder if the solution for now, is to put a finalizer on the deployment for the operator and move the operator into it's own namespace, then when the pre-stop hook is called, check if the deployment has a deletion timestamp, and if so, remove the finalizer from the deployment as well as from any other resource the operator has ever added the finalizer to?

If so, then if the operator was redeployed after this, it would need to re-add the finalizer to any object it interacts with, that is missing the finalizer it should have?

**Comment by chancez** [comment]
That sounds about right.
