### ISSUE TITLE
Support watching a set of namespaces

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/operator-sdk#767]
## Feature Request

Support restricting the operator to only watch a set of namespaces.

The controller-runtime's manager currently only allows the cache to be restricted to a single namespace or all namespaces. This forces the permissions model to either be a ClusterRole/ClusterRoleBinding to watch all namespaces, or a Role/RoleBinding to watch a single namespace.

When watching resources across a set of namespaces however we can have a ClusterRole with multiple RoleBindings(each referring to the operator's service account).

**Proposed fix:**
Long term: Follow up on https://github.com/kubernetes-sigs/controller-runtime/issues/124#issuecomment-417489171 upstream and add support for the [MultiListWatcher](https://github.com/coreos/prometheus-operator/blob/d1af6132437ba2796cc7cc625893768b67733273/pkg/listwatch/listwatch.go#L103-L105) to support this in the controller runtime.

Short term: While it might take some time to add the change upstream we can have our own cache implementation in SDK that supports a set of namespaces, and override the manager's [GetCache()](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/manager.go#L74-L75) method for all dependent objects.

e.g:
```Go
type OurManager struct {
     manager.Manager
     cache ourCache
}

func GetCache() {
    return cache
}
```

**Comment by ironcladlou** [comment]
For the use cases where people want to work with multiple namespaces, I'm now wondering if this is more of a documentation issue. Based on a tip from the [kubebuilder book](
https://book.kubebuilder.io/beyond_basics/using_client_go_informers.htm) I was able to support multi-namespace with [minimal fuss](https://github.com/openshift/cluster-ingress-operator/pull/87) and no new features/wrappers.

**Comment by shawn-hurley** [comment]
@ironcladlou I think that I have discussed this before, but the solution that you are you using has some severe problems with the default client that we would expect folks to use. The way that you are doing things is clever and works for your use case.

I think that this is an issue that we want to solve, either here or upstream.

**Comment by ironcladlou** [comment]
I agree it's still not ideal. My solution does imply an understanding of how to deal with a mixture of scoped/caching clients and live clients, and ensuring they share schemes, etc. Probably not a reasonable expectation for most users.

**Comment by hasbro17** [comment]
/remove-lifecycle stale

This is coming up with the stable release of controller-runtime v0.2.0, currently [v0.2.0-alpha.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.2.0-alpha.0)

ref: https://github.com/operator-framework/operator-sdk/pull/1388
