### ISSUE TITLE
Add a check to discover ServiceMonitor

### ISSUE THREAD

**Issue by LiliC** [operator-framework/operator-sdk#789]
So we don't produce an error when creating `ServiceMonitor` resource, we can use the discovery API to see if the ServiceMonitor is registered and create it only if it is.

**Comment by LiliC** [comment]
Another question as part of this is we mentioned in the meeting that we want to enable this creation of ServiceMonitor by default in the generated operators?

cc @chancez @hasbro17

**Comment by shawn-hurley** [comment]
1. by "enabling the creation of ServiceMonitors by default" does that mean that every operator `CSV` would have a dependency on that resource? Does this mean that if I am running my newly created operator that I would also have to install the Prometheus operator (is that the correct operator?)?

2. Using the discovery API to determine if it exists to me seems like the approach that is most usable by the many different users IMO

**Comment by LiliC** [comment]
> 1. by "enabling the creation of ServiceMonitors by default" does that mean that every operator CSV would have a dependency on that resource?

Yes, that is what I understood @hasbro17 and @chancez suggest in the call we had, just wanted to make sure I understood that correctly.

> Does this mean that if I am running my newly created operator that I would also have to install the Prometheus operator (is that the correct operator?)?

https://github.com/coreos/prometheus-operator 

In my opinion I don't think we should have a dependancy on the operator on by default, we should detect if it is there first and if yes then we can create the `ServiceMonitor` CRD.

**Comment by shawn-hurley** [comment]
> n my opinion I don't think we should have a dependancy on the operator on by default, we should detect if it is there first and if yes then we can create the ServiceMonitor CRD.

👍
