### ISSUE TITLE
How to upgrade from v0.1.x to v0.2.x without creating a new project

### ISSUE THREAD

**Issue by talham7391** [operator-framework/operator-sdk#816]
I recently upgraded from operator v0.0.6 to v0.1.1 and now I see there is a v0.2.0. Is there any way to upgrade to v0.2.0 without having to create a new project?

**Comment by joelanford** [comment]
@talham7391 There should be no breaking changes from v0.1.1 to v0.2.0 (see the [CHANGELOG](https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md)), so you shouldn't need to create a new project.

Give it a shot and let us know if you run into any issues!

**Comment by talham7391** [comment]
@joelanford thankyou!

**Comment by LiliC** [comment]
Closing this, but @talham7391 feel free to open a new issue if you run into any problems with the `v0.2.0` release. Thanks!
