### ISSUE TITLE
Create new document for cluster-scoped operators

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-sdk#837]
We currently duplicate our documentation about cluster-scoped operators in each of the three user guides (Go, Ansible, and Helm). We should abstract that documentation (and any other relevant docs, links, etc) into a separate document and link to it from each of the three user guides.

The relevant sections are:
* https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#operator-scope
* https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md#operator-scope
* https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md#operator-scope

**Comment by Avni-Sharma** [comment]
Hi @joelanford . I would like to take this up

**Comment by joelanford** [comment]
I know @hasbro17 was going to begin working on this, and I'm not sure if he has started yet.

@hasbro17, can @Avni-Sharma take this off your plate?

**Comment by hasbro17** [comment]
@Avni-Sharma The doc changes here depend on some CLI changes that need to be made as a result of #890 
So I think it's probably best to wait until I can get those changes in first.

In the meanwhile you can probably pick up another issue like #1165 if you'd like.

**Comment by Avni-Sharma** [comment]
Sure, I would go through that

**Comment by xcoulon** [comment]
May I suggest that the document to create also contains a comparison table of `cluster-scoped` vs `namespace-scoped` operators and `cluster-scoped` vs `namespace-scoped` CRDs?

**Comment by joelanford** [comment]
This issue is closed by #1434
