### ISSUE TITLE
Add possibility to declare proxy as build-arg to docker build 

### ISSUE THREAD

**Issue by allamand** [operator-framework/operator-sdk#846]
## Feature Request

We have specific Dockerfile which need to access package through a proxy.
with the old docker_build.sh script I was able to add `--build-arg https_proxy=$https_proxy --build-arg http_proxy=$http_proxy` to the script to activate the proxy is the var exists.

I would like that operator-sdk build command can pass thoses build-args if http_proxy env var exists.

**Comment by joelanford** [comment]
@allamand Are you able to make use of the feature in Docker 17.07+ to set proxy variables in ~/.docker/config.json (https://docs.docker.com/network/proxy/)?

**Comment by joelanford** [comment]
@allamand - Just following up to see if you were able to solve this issue with `~/.docker/config.json`, or if there's still a feature you'd like to be added to the SDK?
