### ISSUE TITLE
Integrate codegen into the SDK binary

### ISSUE THREAD

**Issue by estroz** [operator-framework/operator-sdk#868]
With #820 merged, the SDK will build binaries to a project-local directory from their vendored code. While this solution is better than our current solution, calling `generate-groups.sh` from `vendor`, it still creates binaries without explicit user knowledge. The SDK binary should vendor codegen libraries and call code generation functions directly.

**Comment by estroz** [comment]
Closed by #1470

**Comment by LouisPlisso** [comment]
Hey, is there any documentation on how to have projects generated with a previous version of the operator-sdk to move to a vendor-free configuration: we have switched to go modules and getting rid of vendor would be nice
Thanks for your reply

**Comment by estroz** [comment]
@LouisPlisso follow the [version upgrade guide)(https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md) from the version following your project’s current one past `0.8.x`, in which we add module support.
