### ISSUE TITLE
How to scale in my statefulset (using Helm)?

### ISSUE THREAD

**Issue by gmflau** [operator-framework/operator-sdk#875]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I managed to create my operator for my statefulset workload plus managed to scale it out with more pods for my statefulset. 

**Describe the solution you'd like**
The problem now is how to scale in.  My stateful cannot simply reduce the replicacount to scale in.  Before we reduce the size of our statefulse, we need to run some command inside the container to gracefully reduce the size of our workload cluster then reduce the size of our statefulset.  Is there a way to do it in our operator using operator-dsk with Helm?

**Comment by joelanford** [comment]
@gmflau I'm going to close this since I think I've answered your question, but if feel free to re-open if you have more questions!
