### ISSUE TITLE
[Feature Request] allow developer to provide their own scaffold templates

### ISSUE THREAD

**Issue by paulczar** [operator-framework/operator-sdk#877]
## Feature Request

I'm am writing an operator for GCP resources and I'd love a way to specify my own templated files rather than the defaults, especially for the API Definition ( I bring in extra imports and build some of my own deepcopyinto functions ) and the controller file ( there's a lot of boilerplate I replace every time I add a resource, and I'd love to do that in a template ). 

I'd be okay with providing a flag with an alternative template file for each one, or even just a directory location with specifically named files that if they exist would override the templates used by default.

**Comment by LiliC** [comment]
Hi @paulczar 👋This is an interesting feature request, would you be interested in working on this? If so you can have a look at how to create a [new proposal](https://github.com/operator-framework/operator-sdk/tree/master/doc/proposals.). Thanks!
