### ISSUE TITLE
Combining operator-sdk test framework with BDD godog

### ISSUE THREAD

**Issue by aaronmcohen** [operator-framework/operator-sdk#882]
## Type of question

 how to implement the test framework feature

## Question

I am trying to run BDD tests ([godog](https://github.com/DATA-DOG/godog)) via the operator-sdk test framework. The problem I am running into is the test framework's [main_entry.go](https://github.com/operator-framework/operator-sdk/blob/master/pkg/test/main_entry.go) file will leverage functions like os.exit and prevent the BDD tests from being run. Is there anyway to run the test-framework without using the main_entry point? Possibly run it via `go test`?

Thank you.

**Environment**
* operator-sdk version:

  operator-sdk version v0.3.0+git

* Kubernetes version information:

  Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-01-03T15:59:21Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:  Minishift

**Comment by LiliC** [comment]
cc @AlexNPavel

**Comment by shawnshuang** [comment]
@AlexNPavel @LiliC Is it possible to reopen this issue? I have the same issue as @aaronmcohen and would also like a way to run the operator-sdk test framework with godog.
