### ISSUE TITLE
Adding Reconciler for secondary resources

### ISSUE THREAD

**Issue by spiegela** [operator-framework/operator-sdk#883]
## Type of question

How to implement a specific feature

## Question

Is there a way to get just a secondary "watched" resource without doing a listing?

In migrating from `0.0.7` to `0.3.0` I am implementing a handler that watches secondary resources. I found the information for adding the "Watch"; however, I don't see how to implement a Reconcile loop for the secondary resources.

```golang
func add(mgr manager.Manager, r reconcile.Reconciler) error {
	...
	// primary watch
	err = c.Watch(&source.Kind{Type: &myresourcev1alpha1.MyResource{}},
		&handler.EnqueueRequestForObject{})
	if err != nil {
		return err
	}
	// secondary watch
	err = c.Watch(&source.Kind{Type: &appsv1.Deployment{}}, &handler.EnqueueRequestForOwner{
		IsController: true,
		OwnerType:    &myresourcev1alpha1.MyResource{},
	})
```

With `0.0.x` code, I would use a type-switch in the `Handle` function:

```golang
func (h *Handler) Handle(ctx context.Context, event sdk.Event) error {
	switch o := event.Object.(type) {
	case *v1alpha1.MyResource:
		return h.ReconcileMyResource(o)
	case *appsv1.Deployment:
		return h.ReconcileDeployment(o)
	}
}
```
However, since the `0.1.x+` Reconciler uses a `reconcile.Request`, I have the name, but not the type:
```golang
func (r *ReconcileZookeeperCluster) Reconcile(request reconcile.Request) (reconcile.Result, error) {
	instance = &myresourcev1alpha1.MyResource{}
	err := r.client.Get(context.TODO(), request.NamespacedName, instance)
	...
```
**Environment**
* operator-sdk version: `0.3.0`

* Kubernetes version information: `1.11.x`

* Kubernetes cluster kind:  Opensource Trunk

**Comment by joelanford** [comment]
@spiegela The secondary watch will trigger your Reconcile function for your CR and the name and namespace in the `reconcile.Request` will be the name and namespace of the CR. The conventional pattern is that you'll reconcile your entire CR again if any of its child resources change.

Basically, your CR reconciliation loop should just be reconciling each of its child resources and then updating the CR status. In your example, you could likely have `h.ReconcileMyResource(o)` call `h.ReconcileDeployment(o)`.

Does that help?

**Comment by spiegela** [comment]
@joelanford I see. That's why the example does a `Get` of the CR and a `List` of the pods. Your explanation does help. I'll pop back in if I have any other trouble with the upgrade.

Thanks!
