### ISSUE TITLE
Helmfile project type support

### ISSUE THREAD

**Issue by vintikzzz** [operator-framework/operator-sdk#908]
I am currently deploying medium-sized project using [Helmfile](https://github.com/roboll/helmfile). And it will be great if I could convert my helmfile project to an operator project. So creating new operator could look like:
`operator-sdk new my-operator --api-version=example.com/v1alpha1 --kind=Example --type=helmfile`

**Comment by joelanford** [comment]
@vintikzzz Helmfile looks interesting! I'm not very familiar with it though. My understanding from reading the README is that it's a wrapper around the Helm CLI that makes it easier to manage a set of Helm releases.

You may have seen this already, but we now have support for Helm-based operators (as of v0.3.0). Is it possible for you to convert your project to use the `--type=helm` project layout? If not, what is missing?

**Comment by kfox1111** [comment]
helm is an imperative way to launch a new release of a chart.
a Helmfile is a declarative way to manage a chart.

Helmfile therefore is closer to the input a Helm based Operator would take in that drives Helm. The main difference being a Helmfile is yaml formatted for the 'helmfile' binary. While the Operator takes in a k8s CRD that contains Helmfile like info specific to the chart.

**Comment by vintikzzz** [comment]
@joelanford it is possible to "repack" all helm charts to one global helm chart by hand. But doing that way makes it hard to manage all the things, we need to "repack" each time on any change of source helm charts.

**Comment by joelanford** [comment]
@vintikzzz It is possible to include multiple helm charts in a single Helm-based operator, You would have a separate CRD for each chart and separate CRs for each release in your Helmfile.

We could look into adding some features of Helmfile to the Helm operator (e.g. adding annotations to CRs to control `wait`, `timeout`, `recreatePods`, and `force`, or to use shared values from a ConfigMap or Secret)

The features of Helmfile that simplify managing multiple releases within a single declared YAML file/CR spec and fetching charts from remote repos at runtime are probably out of scope for the Helm operator, so I think your instinct for a separate project kind is probably correct.

Would you be interested in working on this? If so, we'd welcome you to draft a new proposal for the design (here's the [proposal template](https://github.com/operator-framework/operator-sdk/blob/master/doc/proposals/TEMPLATE.md)). Thanks!

**Comment by joelanford** [comment]
@vintikzzz I'm going to close this since Helmfile support is out of scope for the current Helm operator. If you'd like to draft a proposal and contribute an implementation, feel free to submit a proposal PR or re-open this issue to discuss more.
