### ISSUE TITLE
Ansible Operator needs to be able to allow for more than 1 worker per controller

### ISSUE THREAD

**Issue by shawn-hurley** [operator-framework/operator-sdk#915]
## Bug Report

**What did you do?**
Attempted to have two worker for a specific GVK

**What did you expect to see?**
Have two workers working at the same time.

**What did you see instead? Under which circumstances?**
No way to define two workers.

**Environment**
* operator-sdk version:
0.3.0

* Are you writing your operator in ansible, helm, or go?
ansible

**Possible Solution**
Add option to the watches file and pass to `controller.Options.MaxConcurrentReconciles`. I believe that we will need to add a new way to get the options from Watches and set in the controller options because adding to the interface is not sustainable.

**Comment by mhrivnak** [comment]
This is a runtime setting that end users of an operator will want to set based on the needs and constraints of their cluster, so I don't think it's a good fit for watches.yaml.

How about setting via environment variable? It might be verbose to compose a variable name based on GVK, but there is probably a precedent to follow.

I could also see it as an annotation on a CRD.

**Comment by shawn-hurley** [comment]
> This is a runtime setting that end users of an operator will want to set based on the needs and constraints of their cluster, so I don't think it's a good fit for watches.yaml.

This makes sense to me, I think your right that we should not be doing this in the watches file. 

> I could also see it as an annotation on a CRD.

+1 I like this option

> How about setting via environment variable? It might be verbose to compose a variable name based on GVK, but there is probably a precedent to follow.

What about annotations on its pod so something like workers.ansible.operator-sdk.io: <GVK;NUM> and the same format for the CRD?

**Comment by mhrivnak** [comment]
> What about annotations on its pod so something like workers.ansible.operator-sdk.io: <GVK;NUM> and the same format for the CRD?

Nice, I like that option too. It's probably better than an annotation on the CRD since it's closer to where the effect would take place.

A factor that may help us choose is to figure out how a user of OLM would set the value for any of these options. I don't really know what that UX is like, but maybe that will be informative.

**Comment by matihost** [comment]
https://github.com/operator-framework/operator-sdk/pull/1144#issuecomment-469736537
