### ISSUE TITLE
Need e2e tests for migrate command dependencies

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-sdk#931]
See #921 

We need to make sure that the Gopkg.toml's scaffolded by the `operator-sdk migrate` command can be used to run `dep ensure` successfully.

**Comment by estroz** [comment]
@joelanford is this issue specifically for `Gopkg.toml`, or does it include `go.mod`? The latter is now tested, but not the former.

**Comment by joelanford** [comment]
This will soon be obsolete since the plan is to drop support for dep once Go 1.13 is released. Closing.
