### ISSUE TITLE
Bug: Scorecard Proxy Cache Must Be Disabled For Go Operators

### ISSUE THREAD

**Issue by AlexNPavel** [operator-framework/operator-sdk#935]
## Bug Report

Currently, the scorecard tests and ansible operator share the same proxy code. However, the informer cache for the scorecard had to be disabled due to an error that occurs for the go based memcached-operator. During the initial listing that occurs when the manager/client gets created, these types of errors get printed and the operator fails to continue:

```
E0116 22:51:20.876869       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Deployment: serializer for text/plain; charset=utf-8 doesn't exist
```

This only happens for the go based memcached-operator that we also use for test subcommand tests (`test/subcommand/test-local`). The ansible and helm memcached-operators run correctly without any issues.

**Comment by odra** [comment]
Is anyone work on this? Can I pick it?

**Comment by shawn-hurley** [comment]
@odra Sounds good to me, let me know if you need help!

**Comment by odra** [comment]
:+1:
