### ISSUE TITLE
test local no longer uses the default kubeconfig if not specified

### ISSUE THREAD

**Issue by darkowlzz** [operator-framework/operator-sdk#943]
## Bug Report

**What did you do?**
Updated SDK from v0.1.0 to v0.3.0.
I used to run the tests using `operator-sdk test local .` with sdk v0.1.0. But in v0.3.0, that fails with error
```
failed to set up framework: failed to build the kubeconfig: invalid configuration: no configuration has been provided
```
Passing `--kubeconfig ~/.kube/config` seems to work as before.

**What did you expect to see?**
I expected it to work as before, use the default kubeconfig in the system.
Seems to be related to this change https://github.com/operator-framework/operator-sdk/pull/717/files#diff-b6a250dfb7ca3e246979976a0467cf97 .

**What did you see instead? Under which circumstances?**
Tests started failing with invalid configuration error.

**Environment**
* operator-sdk version: v0.3.0. 

* Kubernetes version information: N/A

* Kubernetes cluster kind: N/A

* Are you writing your operator in ansible, helm, or go? go

**Possible Solution**

Use the default kubeconfig path when kubeconfig is not passed after this check https://github.com/operator-framework/operator-sdk/blob/006715346bc4cbbd7bf903de437d2e3b17148f85/commands/operator-sdk/cmd/test/local.go#L179-L181

**Additional context**

**Comment by AlexNPavel** [comment]
When you updated your project, did you also update the `Gopkg.toml` for v0.3.0 and run a `dep ensure`? The PR you linked simply changes how we determine the default kubeconfig and also allows us to determine a default namespace based on the kubeconfig. By default, the kubeconfig getter that we are using still falls back to `~/.kube/config` as it did before.

**Comment by darkowlzz** [comment]
ah! I see now, it happens here https://github.com/operator-framework/operator-sdk/blob/master/pkg/test/framework.go#L90 and then continues with the obtained kubeconfig from client-go clientcmd. Makes sense. Updating vendor made it work. I was updating it in the wrong way. First time. Thanks a lot.
Closing this and the related PR that I created :sweat_smile: .

**Comment by AlexNPavel** [comment]
We don't have any upgrade guide yet, so I'll open an issue for that. For upgrading the Gopkg.toml, the best option is probably to use the `print-deps` subcommand of the sdk. Using `operator-sdk print-deps --as-file` will print out the default `Gopkg.toml` file that the sdk generates. If you made any changes to your `Gopkg.toml`, make note of those changes and add them to the new generated file. Then run `dep ensure`. If you didn't make any changes, it should be safe to overwrite the old `Gopkg.toml` file and then run `dep ensure`. This will make sure that the dependencies of the SDK are updated correctly as well. I don't believe any breaking changes were made to our dependencies between `v0.1.0` and `v0.3.0` so this should be a seamless upgrade.

**Comment by darkowlzz** [comment]
Thanks! That's very useful. Everything is good now. :)
