### ISSUE TITLE
Thoughts on the ansible operator

### ISSUE THREAD

**Issue by willthames** [operator-framework/operator-sdk#954]
1. It's very hard to see what has going wrong when no hosts match - the logs report the playbook executed successfully, but you have to go into the archives within the container and check stdout (it's not showing up in status.events - should it?)

2. I'm not clear *why* the host isn't matching. `ansible -m debug -a var=a_working_var hostname` works fine. However, the logs do show:

    ```
    /tmp/ansible-operator/runner/example.com/v1alpha1/ExampleApplication/namespace/application      /inventory/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
    ```

    which is surprising as my ansible.cfg has `inventory = /opt/ansible/inventory`, and `ansible-config dump` shows that that is being respected (the above ansible command with `-vvv` run from the directory above inventory/hosts doesn't pick up the inventory/hosts by default)

3. The playbook is run from the execution directory, but none of the accompanying resources for the playbook are similarly copied. This means things that I have in the playbook directory, such as ansible.cfg, library, module_utils, plugins, roles etc. are not in place. I can resolve all of those with a custom /etc/ansible/ansible.cfg pointing resources at /opt/ansible but...

4. I also have templates that get loaded by a generic role for all applications (so the templates are separate to the roles). Because the templates aren't copied, the playbook won't be able to find them, and I don't think I can override *that* with a custom ansible.cfg. Oh, and the first thing my playbook does is `import_tasks` and I'm guessing it won't find that either! (I have to guess at this point because of the inventory problem)

It might be that my use case is not what the ansible operator is designed for - if so, let me know, and I'll investigate other approaches for git-ops, but I do think that it is an ideal candidate for a simple declarative specification of *what* should be deployed in an environment, leaving the playbooks to specify *how* to deploy them.

**Comment by LiliC** [comment]
cc @shawn-hurley @mhrivnak

**Comment by willthames** [comment]
Here's a sanitised version of our ansible directory (`application` is a placeholder for all of our many applications):

```
.
├── inventory
│   └── group_vars
│       ├── all
│       ├── application
│       ├── application-prod
│       ├── application-staging
│       ├── prod
│       └── staging
├── library
├── module_utils
│   ├── common
│   └── k8s
├── playbooks
├── plugins
│   ├── filter
│   └── inventory
├── roles
│   └── applications
│       └── generic
│           ├── defaults
│           └── tasks
└── templates
    └── application
```

And here's our proposed ansible.cfg

```
[defaults]
inventory_plugins = /opt/ansible/plugins/inventory
stdout_callback = yaml
callback_whitelist = profile_tasks,timer
module_utils = /opt/ansible/module_utils
library = /opt/ansible/library
inventory = /opt/ansible/inventory
filter_plugins = /opt/ansible/plugins/filter
remote_tmp = /tmp/ansible
```

**Comment by fabianvf** [comment]
> Oh, and the first thing my playbook does is import_tasks and I'm guessing it won't find that either!

Does the task file your playbook is importing exist in the `playbooks` directory or somewhere else?

**Comment by willthames** [comment]
I think all the issues here have been dealt with now so I'll close this one and raise another one.
