### ISSUE TITLE
Handling Events in reconcile loop

### ISSUE THREAD

**Issue by yaminisridaran** [operator-framework/operator-sdk#955]
I have a primary resource 
// Watch for changes to primary resource Memcached
     err = c.Watch(&source.Kind{Type: &cachev1alpha1.Memcached{}}, &handler.EnqueueRequestForObject{})
     if err != nil {
         return err
    }

In reconcile loop I need to get the delete event similar to the old operator sdk  
if event.deleted {
        //logic
}
Is this possible in new operator sdk?

**Comment by LiliC** [comment]
@yaminisridaran What do you need the delete even for? You can use [finalizers](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#finalizers), would that be enough for you?

The events are triggered by a delete event in the same way:
https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#resources-watched-by-the-controller

**Comment by yaminisridaran** [comment]
@LiliC I need to go an action on create update and delete event. In old operator sdk . Event.create used to be useful. Is their any similar in the new sdk

**Comment by shawn-hurley** [comment]
There is nothing exactly the same. You could do something with the status of the resource, like add a reference to the thing you need to do. This will allow for you reconcile loop to make sure that 1. it always does that thing when there is no status block, and 2. should make sure that the situation is still correct each run of the reconcile loop. 

Let me know if you have any more questions

**Comment by yaminisridaran** [comment]
@shawn-hurley Inside Reconcile loop I think using r.client.Get(context.TODO(), request.NamespacedName, instance)
and the err.IsnotFound means delete event otherwise create event but I am currently having a Status to distinguish between create and update.

Is their a better way we can achieve the same.

**Comment by shawn-hurley** [comment]
Yes, for delete event I would use the finalizer as @LiliC noted above. That would be the correct way.


For the create vs. update that is an option, I don't like distinguishing between them, but I don't know your use case.

**Comment by yaminisridaran** [comment]
Thank You @LiliC and @shawn-hurley. Do we have slack channel for operator sdk?

**Comment by LiliC** [comment]
@yaminisridaran yes we on the #kubernetes-operators on k8s slack channel :)

**Comment by LiliC** [comment]
@yaminisridaran closing this issue for now, but if you further questions feel free to open a new issue or ask on the above slack channel. :)

**Comment by AsherShoshan** [comment]
LiLiC, So have you got an answer for your question?  I have the exact one. How to know the event type. 
Mostly for update one for access oldObj and newObj, compare and decide what to do in reconciliation loop.

**Comment by yaminisridaran** [comment]
HI LiLiC,
Operator sdk considering Add and Update event as same. We need to
differentiate between the Add and Update events either by using status (or)
if you are using like external service to be update we need to use http api.
Delete event we can identify using finaliser. When Delete event is
triggered  DeletionTimeStamp is non Zero. This DeletionTimeStamp is Zero in
Add and Update events.

Thanks & Regards
Yamini

**Comment by traghave** [comment]
@LiliC @yaminisridaran 
I'm having similar issue, is there way we can distinguish between add and update operations.
Incase of Add I want to invoke POST call to a custom API where as for update I need to do PUT.
Could you help?

**Comment by shawn-hurley** [comment]
Hello Folks,

There seems to be a lot of questions about the operator knowing if a create event or update event. This is expressly against the design decisions made by controller-runtime. 

The reason for this is that no mechanism exists to guarantee that you will get the creation event before processing the addition event. This means that your controller should be making decisions based on the current spec and status that your reconciler has and the state of the cluster. I think that if we need to have a more detailed discussion of this we should use the [kubebuilder community meeting](https://github.com/kubernetes/community/tree/master/sig-api-machinery#meetings) or the [operator sig meeting](https://commons.openshift.org/index.html#event|operator-framework-sig-3rd-fridays|602) to discuss.
