### ISSUE TITLE
Ansible Molecule Test Fails CI on Version Bump

### ISSUE THREAD

**Issue by AlexNPavel** [operator-framework/operator-sdk#958]
The Ansible Molecule E2E tests currently depend on the image for the base ansible operator existing with the current image tag in quay. This works fine for master builds, as that uses the last version release, but when a new release is made, the tests run before the deploy stage, so the Ansible Molecule test fails. The current workaround is running the deploy stage for the Ansible operator base image before the tests. One potential solution for future releases would be to make molecule run the version that is built in the test (which would have the `:dev` tag).

Here is an example of the Molecule test failure output:
```
    TASK [Build Operator Image] ****************************************************
    fatal: [kind-test-local]: FAILED! => {"changed": true, "cmd": ["docker", "build", "-f", "/build/build/Dockerfile", "-t", "ansible.example.com/memcached-operator:testing", "/build"], "delta": "0:00:01.120205", "end": "2019-01-18 20:50:29.886104", "msg": "non-zero return code", "rc": 1, "start": "2019-01-18 20:50:28.765899", "stderr": "manifest for quay.io/operator-framework/ansible-operator:v0.4.0 not found", "stderr_lines": ["manifest for quay.io/operator-framework/ansible-operator:v0.4.0 not found"], "stdout": "Sending build context to Docker daemon  161.3kB\r\r\nStep 1/4 : FROM quay.io/operator-framework/ansible-operator:v0.4.0", "stdout_lines": ["Sending build context to Docker daemon  161.3kB", "", "Step 1/4 : FROM quay.io/operator-framework/ansible-operator:v0.4.0"]}
```

**Comment by mhrivnak** [comment]
@fabianvf
