### ISSUE TITLE
Repect Kubeconfig variable

### ISSUE THREAD

**Issue by chmouel** [operator-framework/operator-sdk#980]
## Feature Request

**Is your feature request related to a problem? Please describe.**

KUBECONFIG environment variable doesn't  seem to be respected, it only use .kube/config unless --kubeconfig flag is passed,

**Describe the solution you'd like**

- Use .kube/config as default
- Respect KUBECONFIG variable if there.
- let the user override it with --kubeconfig,

**Comment by LiliC** [comment]
This is in the scenario when running it locally with `operator-sdk up local` -> https://github.com/operator-framework/operator-sdk/blob/419cfd39bea8657babc55759db5fd77cada54334/commands/operator-sdk/cmd/up/local.go#L80

**Comment by LiliC** [comment]
cc @hasbro17 any historical reason behind why we are ignoring the env var `KUBECONFIG`?

**Comment by AlexNPavel** [comment]
We started using the standard clientcmd config getter in v0.2.0 (https://github.com/operator-framework/operator-sdk/blob/master/internal/util/k8sutil/k8sutil.go#L28), but it looks like we only changed internal libraries and the `test` subcommands and forgot about `up`. I'll make a PR to change it to use the correct config getter.
