### ISSUE TITLE
Cannot update CR status in 3.11

### ISSUE THREAD

**Issue by eivantsov** [operator-framework/operator-sdk#981]
## Type of question

Need help

## Question

**What did you do?**

The operator updates CR status based on whether or not a few preceding actions were successful. The following code works fine in 3.9 and I can see status field of my CR being updated:

```
                                instance.Status.Provisoned = true
				logrus.Info("Updating CR status")
				err = r.client.Update(context.TODO(), instance)
				if err != nil {
					logrus.Errorf("Failed to update CR status", err)
				} else {
					logrus.Info("CR status updated")
				}
```

However on 3.11, the same code fails to update status, but the operator prints no error. My CR does not get status block, and thus further operator business logic 

I am using 0.3.0 SDK version.

**Comment by shawn-hurley** [comment]
Depending on your CRD you may need to use the `StatusWriter`.

i.e: `r.client.Status().Update(context.TODO(), instance)`

**Comment by joelanford** [comment]
Here's our doc about the status subresource and using the StatusWriter as well: https://github.com/operator-framework/operator-sdk/blob/master/doc/user/client.md#updating-status-subresource

**Comment by eivantsov** [comment]
@shawn-hurley thanks that worked. Somehow, it worked with just Update in 3.9 though
@joelanford thanks for the link!
