### ISSUE TITLE
Sending WATCH_NAMESPACE="" results in error log

### ISSUE THREAD

**Issue by kahootali** [operator-framework/operator-sdk#987]
## Bug Report

**What did you do?**
I am using operator-sdk to create an operator, and I want it to be deployed globally, so I have used `WATCH_NAMESPACE=""` to look globally. But I am using `sdk.ExposeMetricsPort()` which further calls k8sutil.GetWatchNamespace() which logs an error `level=error msg="Failed to initialize service object for operator metrics: WATCH_NAMESPACE must not be empty"`, however I want it to be empty.

* Are you writing your operator in ansible, helm, or go?
Golang

**Possible Solution**
I believe WATCH_NAMESPACE should be able to set to "" or the log should not be error level rather info

**Comment by shawn-hurley** [comment]
I am going to close this as we have fixed the issue. 

please re-open if this is not the case.

/close
