### ISSUE TITLE
Generated CSV should have package definition and follow directory structure

### ISSUE THREAD

**Issue by dmesser** [operator-framework/operator-sdk#990]
Currently we aim to [generate a ClusterServiceVersion and the CRDs](https://github.com/operator-framework/operator-sdk/blob/master/doc/design/milestone-0.2.0/csv-generation.md) currently found in an operator-sdk project to form a `bundle`.

For easy local testing using OLM/operator-registry we should also generate manifests to form a [package definition](https://github.com/operator-framework/operator-registry#manifest-format). The  directory structure should follow `<package-name>`/`<CSV-semantic-version>`/ containing one or more CSVs following the proposed naming scheme of `<operator-name>.vX.Y.Z.clusterserviceversion.yaml` and one or more CRDs following the notation `<kind>.crd.yaml`.

Example:
```
manifests
└── etcd
  ├── 0.6.1
  │   ├── etcdcluster.crd.yaml
  │   └── etcdoperator.clusterserviceversion.yaml
  ├── 0.9.0
  │   ├── etcdbackup.crd.yaml
  │   ├── etcdcluster.crd.yaml
  │   ├── etcdoperator.v0.9.0.clusterserviceversion.yaml
  │   └── etcdrestore.crd.yaml
  ├── 0.9.2
  │   ├── etcdbackup.crd.yaml
  │   ├── etcdcluster.crd.yaml
  │   ├── etcdoperator.v0.9.2.clusterserviceversion.yaml
  │   └── etcdrestore.crd.yaml
  └── etcd.package.yaml
```

This format would also allow to easily commit an operator to the [community operator repository](https://github.com/operator-framework/community-operators#adding-your-okd-operator). Further alignment between the expected directory structures between these two routes might be necessary.

**Comment by djzager** [comment]
This would be awesome. Definitely related to the conversation we had in #900 but, looking more closely, this looks much more easy to manage from an operator developer perspective.

**Comment by eriknelson** [comment]
+1, minor nit, I'm guessing `<operator-name>.vX.Y.Z.clusterversion.yaml` -> `<operator-name>.vX.Y.Z.clusterserviceversion.yaml`

**Comment by dmesser** [comment]
Thanks @eriknelson - fixed.

**Comment by estroz** [comment]
@dmesser thanks for filing an issue about this. I'm going to respond in #900 to keep discussion related to CSV dir structure in one place.

**Comment by dmesser** [comment]
Gotcha, closing this.
