### ISSUE TITLE
Required to watch all crds in all controllers parallel in the operator

### ISSUE THREAD

**Issue by yaminisridaran** [operator-framework/operator-sdk#993]
Required to watch all crds in all controllers parallel in the operator.
I tried EnqueueRequestForObject api ,It is only getting triggered for the controller crd.
but it is not getting triggered for other crds

**Comment by AlexNPavel** [comment]
Can you please claify the question?

**Comment by yaminisridaran** [comment]
@shawn-hurley  I am using handler.EnqueueRequestForObject along in watch with the A object in B controller. Now B controller is watching A resource and execute the reconcile B when A resource is triggered. But I require the name of the A resource to get the spec of A resources inside the reconcile of B controller. Do we have any other better approach for this use case?

**Comment by shawn-hurley** [comment]
B controller/reconcile should only ever reconcile B resources. A controller/reconcile should only ever reconcile A resources. If apart of B reconciles it manages A then the name should be deterministic or use some other mechanism(label), just like all the resources that B controller creates. This is the fundamental way that controllers and reconcilers should be used. 

I am still fairly confused though. `EnqueueRequestForObject` will enqueue the name and namespace for the object that it is watching. This means that you're not getting B's resource name you're getting A's resource name. Is there any code that I could look at to maybe further understand?

**Comment by yaminisridaran** [comment]
Thank you @shawn-hurley and @AlexNPavel. I am using labels and issue is resolved. I am closing this issue
