### ISSUE TITLE
operator-sdk add controller fails when API group contains hyphen

### ISSUE THREAD

**Issue by nak3** [operator-framework/operator-sdk#997]
## Bug Report

**What did you do?**

When `operator-sdk add controller` contains hyphone in the API
version, it always fail. Please refer to the erorr below:

**What did you expect to see?**

Create auto generated code
`pkg/controller/appservice/appservice_controller.go` without error.

**What did you see instead? Under which circumstances?**

Run `operator-sdk add controller ` with `--api-version` which contains hyphen in the API group.

```
$ operator-sdk add controller --api-version=node-problem-detector.operator.k8s.io/v1alpha1 --kind=AppService
INFO[0000] Generating controller version node-problem-detector.operator.k8s.io/v1alpha1 for kind AppService. 
Error: controller scaffold failed: (/home/knakayam/.go/src/github.com/example-inc/app-operator/pkg/controller/appservice/appservice_controller.go:6:6: expected 'STRING', found '-' (and 10 more errors))
Usage:
  operator-sdk add controller [flags]

Flags:
      --api-version string   Kubernetes APIVersion that has a format of $GROUP_NAME/$VERSION (e.g app.example.com/v1alpha1)
  -h, --help                 help for controller
      --kind string          Kubernetes resource Kind name. (e.g AppService)
```

The error `expected 'STRING', found '-'` is gofmt error. You can test
following import sentence:

```
package main

import (
	a-b "fmt"
)
```

**Environment**
* operator-sdk version:

- Build on top of 770a5b7f890cd6cc361998d588efa7794a6ac42d

**Possible Solution**

https://github.com/operator-framework/operator-sdk/pull/998

**Additional context**
Some projects already used group name with hyphone like - https://github.com/openshift/node-problem-detector-operator/blob/master/deploy/crd.yaml#L6

**Comment by LiliC** [comment]
This is valid in upstream kubernetes as well:

> Group names must be lower case and be valid DNS subdomains.
