### ISSUE TITLE
Add ability to expose metrics in non leader pods

### ISSUE THREAD

**Issue by lilic** [operator-framework/operator-sdk#999]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Metrics serving is being started only when we call the `Start()` in controller-runtime, we lock any non leaders with a lock before we call the `Start()` in the generated operators. Due to this the metrics are only being served for non leader pods.

**Describe the solution you'd like**
We have two possible solutions:
1. Serve the metrics independently of controller-runtime, this requires us disabling serving of metrics altogether in controller-runtime. 
2. Add new feature in controller-runtime to start serving metric independently of starting the manager. 

See https://github.com/operator-framework/operator-sdk/pull/786#discussion_r250213654 for full background.

**Comment by LiliC** [comment]
Opened PR -> https://github.com/kubernetes-sigs/controller-runtime/pull/337
